### ISSUE TITLE
Broken ReadMe Links

### ISSUE THREAD

**Issue by oddlittlebird** [grafana/loki#1000]
The API Documentation link and Operations link in the main Loki readme.md file are broken.

**To Reproduce**
1. Click either link.
2. Observe the 404 page that results.

**Expected behavior**
Not a 404 link. They should lead to https://github.com/grafana/loki/blob/master/docs/loki/api.md and https://github.com/grafana/loki/blob/master/docs/loki/operations.md

**Environment:**
The interwebz

I would be happy to fix these for you. I am a documentation pro but an open source noob, so little fixes like this are helpful for me to learn.

**Comment by rfratto** [comment]
Closed by #1003
