### ISSUE TITLE
Reconsider enabled linters

### ISSUE THREAD

**Issue by rfratto** [grafana/loki#1002]
We [enable](https://github.com/grafana/loki/blob/3467440b301cd88d2b6edefa39fac75771240568/.golangci.yml) the following linters:

    - deadcode
    - errcheck
    - goconst
    - gofmt
    - goimports
    - golint
    - gosimple
    - ineffassign
    - megacheck
    - misspell
    - structcheck
    - unconvert
    - unparam
    - varcheck
    - govet
    - unused # new from here.
    - interfacer
    - typecheck

At least `interfacer` and `megacheck` are deprecated and should likely be removed. `interfacer` in particular has questionable usability and can be prone to false-positives. 

The list of enabled linters should be fully re-considered and whittled down to a more appropriate list.

**Comment by pracucci** [comment]
I checked all the available linters and I would suggest:
- Remove `interfacer`
- Replace `megacheck` with `staticcheck`
- Add `prealloc`: finds slice declarations that could potentially be preallocated

Any feedback?
