### ISSUE TITLE
Skip tls verify for S3 bucket option on helm chart

### ISSUE THREAD

**Issue by david-nano** [grafana/loki#10030]
**Is your feature request related to a problem? Please describe.**
We have local netapp with S3, which is internal soluion, once trying to use it we get "tls: failed to verify certificate: x509"
But this ok by me, we can skip the verify, today no option to do it.

**Describe the solution you'd like**
on s3 values: https://github.com/grafana/loki/blob/a0e9f1aeb5d557330eabde21efd02cca58d77b1a/production/helm/loki/values.yaml#L265C5-L265C7
add option to `tls_verify: true or false`

**Describe alternatives you've considered**
Use AWS, but this is not an option for the long term.

**Additional context** 
Logs when trying use https with
```
level=info ts=2023-07-24T07:13:17.404546324Z caller=compactor.go:497 msg="compactor started"
ts=2023-07-24T07:13:17.404617423Z caller=spanlogger.go:85 level=info msg="building index list cache"
ts=2023-07-24T07:13:17.417953887Z caller=spanlogger.go:85 level=info msg="index list cache built" duration=13.313664ms
level=error ts=2023-07-24T07:13:17.418041586Z caller=cached_client.go:65 msg="failed to build cache" err="RequestError: send request failed\ncaused by: Get \"http://logs-store.deeps3.netapp.local/?delimiter=&list-type=2&prefix=index%2F\": dial tcp 10.111.10.230:80: connect: connection refused"
ts=2023-07-24T07:13:17.418109085Z caller=spanlogger.go:85 level=info msg="building index list cache"
ts=2023-07-24T07:13:17.432629337Z caller=spanlogger.go:85 level=info msg="index list cache built" duration=14.501952ms
level=error ts=2023-07-24T07:13:17.432729936Z caller=cached_client.go:65 msg="failed to build cache" err="RequestError: send request failed\ncaused by: Get \"http://logs-store.deeps3.netapp.local/?delimiter=&list-type=2&prefix=index%2F\": dial tcp 10.111.10.230:80: connect: connection refused"
level=error ts=2023-07-24T07:13:17.432848335Z caller=compactor.go:460 msg="failed to run compaction" err="RequestError: send request failed\ncaused by: Get \"http://logs-store.deeps3.netapp.local/?delimiter=&list-type=2&prefix=index%2F\": dial tcp 10.111.10.230:80: connect: connection refused"
ts=2023-07-24T07:14:06.273192305Z caller=memberlist_logger.go:74 level=info msg="Suspect loki-backend-0-0d372d5d has failed, no acks received"
level=error ts=2023-07-24T07:14:12.530152784Z caller=ruler.go:542 msg="unable to list rules" err="RequestError: send request failed\ncaused by: Get \"http://logs-store.deeps3.netapp.local/?delimiter=&list-type=2&prefix=rules%2F\": dial tcp 10.111.10.230:80: connect: connection refused"
ts=2023-07-24T07:14:20.563206136Z caller=memberlist_logger.go:74 level=info msg="Marking loki-backend-0-0d372d5d as failed, suspect timeout reached (2 peer confirmations)"
```

**Edit:** we need solution for local certificate, to mount "pem" file.

**Comment by mancubus77** [comment]
+1

**Comment by Sheikh-Abubaker** [comment]
Hi @david-nano did you mean that I just have to append ""tls_verify: true or false"" onto here https://github.com/grafana/loki/blob/a0e9f1aeb5d557330eabde21efd02cca58d77b1a/production/helm/loki/values.yaml#L265C5-L265C7 ?

**Comment by david-nano** [comment]
> Hi @david-nano did you mean that I just have to append ""tls_verify: true or false"" onto here https://github.com/grafana/loki/blob/a0e9f1aeb5d557330eabde21efd02cca58d77b1a/production/helm/loki/values.yaml#L265C5-L265C7 ?

Yes. That way I can use secure S3 self-hosted but skip the TLS verify in case it's self-sign.
Is there any ETA?

**Comment by Sheikh-Abubaker** [comment]
> > Hi @david-nano did you mean that I just have to append ""tls_verify: true or false"" onto here https://github.com/grafana/loki/blob/a0e9f1aeb5d557330eabde21efd02cca58d77b1a/production/helm/loki/values.yaml#L265C5-L265C7 ?
> 
> Yes. That way I can use secure S3 self-hosted but skip the TLS verify in case it's self-sign. Is there any ETA?

Alright just give me a min I'll open a PR a do it right away.

**Comment by helletheone** [comment]
hello is there any update on the PR? 
we need this feature too :)

**Comment by Sheikh-Abubaker** [comment]
> hello is there any update on the PR? we need this feature too :)

I've already Opened a PR last month but since then no one has reviewed it yet.

**Comment by Sheikh-Abubaker** [comment]
I hope PR will be merged soon

**Comment by MichelHollands** [comment]
As mentioned by @sojjan1337 this is not needed. You can specify `insecure_skip_verify: true` in the `http_config` block it in the values.yaml when you deploy.
