### ISSUE TITLE
Helm Chart: Installation in non-default namespace not working

### ISSUE THREAD

**Issue by jhedev** [grafana/loki#10048]
**Describe the bug**
When deploying loki with the standard helm chart the read deployments error with `level=warn ts=2023-07-25T07:25:18.070475696Z caller=dns_resolver.go:225 msg="failed DNS A record lookup" err="lookup query-scheduler-discovery.loki.svc.cluster.local. on 172.20.0.10:53: no such host"`.

I got it working when simply adding the namespace to the respective service (https://github.com/grafana/loki/blob/main/production/helm/loki/templates/backend/query-scheduler-discovery.yaml#L6-L10). 
The linked service currently does not set the namespace. As such it cannot work when installed in a non-default namespace. 

**To Reproduce**
Use the standard `grafana/loki` helm chart and install it in a non-default namespace. 

**Expected behavior**
The installation to work

**Environment:**
- AWS EKS

**Screenshots, Promtail config, or terminal output**

**Comment by jhedev** [comment]
Now I also realised that the write components in the helm chart (see here https://github.com/grafana/loki/blob/028c12f624011b0693d8c7f74df39bc6a63ae5a4/production/helm/loki/templates/write/statefulset-write.yaml) do not set the right namespace. 

All resources for the write part are created in the default namespace which caused my setup to fail. Recreating them in the correct namespace seems to work. 

Am I missing something or is this a bug in the helm chart?

**Comment by ccureau** [comment]
I am also seeing this behavior with chart version `5.9.2`. Using kustomize and installing in the `loki` namespace.
