### ISSUE TITLE
PROPOSAL: fluentd output plugin

### ISSUE THREAD

**Issue by gouthamve** [grafana/loki#101]
I think it'll be useful to have a Fluentd output plugin for Loki. Lots of people already have fluentd installs and sometimes even a complete pipeline with fluentd --> Kafka --> fluentd --> ELK and just having another output to Loki would help them use Loki without many changes.

We use promtail to tag the logs with the correct kubernetes labels but most people don't use kubernetes and still want to use Loki. While we can support Promtail for Kubernetes, I think it is best to just delegate everything else to fluentd.

**Comment by giosakti** [comment]
I am having a similar setup in my company and will take a look into this possibility 👍

**Comment by bigkraig** [comment]
We have been using fluent-bit, but it is the same use case

**Comment by eeddaann** [comment]
I started to work on it in this [repo](https://github.com/eeddaann/fluent-plugin-loki) 
It's based on [fluentd's http output plugin](https://github.com/fluent-plugins-nursery/fluent-plugin-out-http). 
All contributions are welcome..

**Comment by hellojukay** [comment]
I also think this is very necessary

**Comment by bigkraig** [comment]
Relates to #185

**Comment by tomwilkie** [comment]
We merged on in #210
