### ISSUE TITLE
docker images for 2.7.6 are missing

### ISSUE THREAD

**Issue by jcberleur** [grafana/loki#10122]
**Describe the bug**
docker images for 2.7.6 for loki and promtail are not available

**To Reproduce**

1. `docker pull --platform linux/amd64 grafana/promtail:2.7.6`
2. `Error response from daemon: manifest for grafana/promtail:2.7.6 not found: manifest unknown: manifest unknown`

**Expected behavior**
Downloading the docker image.

**Comment by chaudum** [comment]
It seems there was a bug in the 2.7.x release pipeline. [2.7.5](https://hub.docker.com/r/grafana/loki/tags?page=1&name=2.7.5) still has a multi-arch/os Docker image, whereas [2.7.6](https://hub.docker.com/r/grafana/loki/tags?page=1&name=2.7.6) does not. However, there is a dedicated 2.7.6-amd64 image.

We'll need to investigate what went wrong.

**Comment by chaudum** [comment]
@jcberleur We've identified the problem and working on a fix. Will let you know when the images are available. Thanks again for your report and your patience.

**Comment by gtirloni** [comment]
> @jcberleur We've identified the problem and working on a fix. Will let you know when the images are available. Thanks again for your report and your patience.

Thanks for working on this! I spent some time investigating why 2.7.7 was missing even though I could see it on the releases page.

**Comment by chaudum** [comment]
The following images are now available on Docker Hub:

[`grafana/loki:2.7.6`](https://hub.docker.com/r/grafana/loki/tags?page=1&name=2.7.6)
[`grafana/loki:2.7.7`](https://hub.docker.com/r/grafana/loki/tags?page=1&name=2.7.7)
[`grafana/promtail:2.7.6`](https://hub.docker.com/r/grafana/promtail/tags?page=1&name=2.7.6)
[`grafana/promtail:2.7.7`](https://hub.docker.com/r/grafana/promtail/tags?page=1&name=2.7.7)
