### ISSUE TITLE
Docs feedback: /docs/sources/clients/_index.md

### ISSUE THREAD

**Issue by lionelmarksgrafana** [grafana/loki#10173]
Please update to reflect the officially supported clients that Grafana Labs can provide tech support on.

But perhaps include a list of "known to work" agents that may encounter breaking changes, best effort support.

**Comment by GrafanaWriter** [comment]
@lionelmarksgrafana - can you please provide a list of supported clients that you're aware of to start us off?

**Comment by JStickler** [comment]
@lionelmarksgrafana Could you look at the current client page and let me know if that satisfies your request?

https://grafana.com/docs/loki/latest/send-data/

**Comment by lionelmarksgrafana** [comment]
This looks really good! great work !

**Comment by JStickler** [comment]
@lionelmarksgrafana , so can we close this issue?

**Comment by lionelmarksgrafana** [comment]
of course.. is that something I have to close out?

**Comment by JStickler** [comment]
@lionelmarksgrafana Nope, just wanted your approval before I close it.
