### ISSUE TITLE
How to know when lambda promtail successfully fetch the log from S3

### ISSUE THREAD

**Issue by svenikea** [grafana/loki#10195]
Hi guys, I successfully deployed the promtail to my lambda, and when I check the log, it only said fetching `s3://mybucket/aws/log/xxx.log.gz` that's it, I don't know if it also successfully handles decompressing the log and putting the label in it but I check Loki in Grafana, there was no label from S3.

For example here is the log from lambda 

```
level=info caller=s3.go:144 msg="fetching s3 file: access-log/AWSLogs/667683585420/elasticloadbalancing/eu-west-1/2023/08/09/667683585420_elasticloadbalancing_eu-west-1_app.grafa-LoadB-UR2O62S7AFEY.27e3764dc6e2df24_20230809T0345Z_52.18.161.40_j8lea9kq.log.gz"
END RequestId: a17325b7-d427-401b-867b-1af9bd13703b
REPORT RequestId: a17325b7-d427-401b-867b-1af9bd13703b	Duration: 99.35 ms	Billed Duration: 100 ms	Memory Size: 128 MB	Max Memory Used: 34 MB	
```

Is there a way for me to debug if the lambda is working? 

Thanks

**Comment by svenikea** [comment]
Upon more investigating, I can see that my lambda is showing some errors, I can't find a way to debug it
![image](https://github.com/grafana/loki/assets/44079366/ef5e4f62-2323-4830-a85d-50b97568db9a)

**Comment by svenikea** [comment]
I will close this issue because my permission for the lambda was pointing to the wrong s3 bucket

**Comment by thaw-zin-myo** [comment]
Hello @svenikea, I have a similar issue. I want to send the ALB Access Logs to Grafana Cloud. Configured trigger Lambda to fetch logs from S3. Lambda permission is fine and Lambda works every request from S3 but not sending to Grafana Cloud. Environments are configured in Lambda configuration. Let me know an
![CloudWatch-ap-southeast-1](https://github.com/grafana/loki/assets/116049602/81a7bb00-6488-44f7-80e1-e4c5c8e48697)
y misconfiguration.
