### ISSUE TITLE
hosted log demo instance failed

### ISSUE THREAD

**Issue by daixiang0** [grafana/loki#102]
I login grafana to try online test, but i met below issue:
- i can remove grafana instance but logs or metrics not
- [logs instance]( https://logs-us-west1.grafana.net) can not work now:
```
[root@dx-app ~]# logcli labels app
https://logs-us-west1.grafana.net/api/prom/label/app/values
2018/12/14 15:12:10 Error doing request: Error response from server: too many failed ingesters
 (<nil>)
```

I am sure my promtail can work since i can get app info in the last:
```
[root@dx-app ~]# logcli labels app
https://logs-us-west1.grafana.net/api/prom/label/app/values
helm
mongo
nginx
flask
```

**Comment by gouthamve** [comment]
Hi, sorry about that! Our demo cluster is under heavy load and I'm going to scale it up now. Should work now!

**Comment by daixiang0** [comment]
@gouthamve Thanks very much!
Maybe auto scale when under heavy load is better for users.
Other question, why i can not remove metrics or log instances?

**Comment by daixiang0** [comment]
@gouthamve the server is down again:
```
[root@dx-app ~]# logcli labels app
https://log-us.grafana.net/api/prom/label/app/values
2018/12/15 10:40:29 Error doing request: Error response from server: <!doctype html>

**Comment by daixiang0** [comment]
@gouthamve any input?

**Comment by gouthamve** [comment]
Hi the URL seems to be wrong `https://logs-us-west1.grafana.net/` should be the URL no?
