### ISSUE TITLE
Current client-go version (v0.26.2) contains possible panic during discovery

### ISSUE THREAD

**Issue by seans3** [grafana/loki#10208]
Please update `grafana loki` client-go version to v0.26.4+

Why: Possible panic when using client-go v0.26.0 - v0.26.3 (looks like current client-go is affected: v0.26.2) for discovery.

https://github.com/grafana/loki/blob/main/operator/go.mod#L25

kubernetes issue: https://github.com/kubernetes/kubernetes/issues/119840

**Comment by periklis** [comment]
Already upgraded to 1.27.7 by #11232
