### ISSUE TITLE
Change config files to use TDSB as a default, like we recommend in the docs.

### ISSUE THREAD

**Issue by wardbekker** [grafana/loki#10266]
TODO: changing the config files to use tsdb, too. This way anyone starting from scratch is already using it

- https://github.com/grafana/loki/blob/42b8a6cbcaf8211c0344c0f8e7d00a1617c911bf/cmd/loki/loki-local-config.yaml#L26-L34
- https://github.com/grafana/loki/blob/42b8a6cbcaf8211c0344c0f8e7d00a1617c911bf/cmd/loki/loki-docker-config.yaml#L18-L25

_Originally posted by @MasslessParticle in https://github.com/grafana/loki/issues/9246#issuecomment-1680748876_

**Comment by paul1r** [comment]
Above docker files are adjusted in this PR:
https://github.com/grafana/loki/pull/10781
