### ISSUE TITLE
Add metrics for per tenant usage

### ISSUE THREAD

**Issue by gouthamve** [grafana/loki#103]
We need to track the following per-tenant metrics:

- The number of active streams (currently being reported as 1)
- Number of uncompressed bytes received
- Number of uncompressed bytes queried
- Number of log lines received
- Number of log lines queried
- Bytes of compressed data stored in ObjectStore

**Comment by aylei** [comment]
Is anyone actively working on this issue? If not I would like to take this.

**Comment by gouthamve** [comment]
Sorry, @aylei I'm already working on it as we need it ASAP for tracking the usage of our cloud instances.

**Comment by gouthamve** [comment]
The query metrics are hard to get right. If a query matches just a single line, but we had to decode an entire chunk (1000 entries for example), should we count 1 or 1000? Further, we might be retrieving three chunks (due to replication) to do it.

For the compressed bytes in ObjectStore, the only feasible way I see is via Cortex's Store interface.
