### ISSUE TITLE
Docs feedback: /docs/sources/installation/sizing/index.md

### ISSUE THREAD

**Issue by wcall** [grafana/loki#10315]
Update the selection options list for the "Node Type?" drop-down select menu. AWS - t2.4xlarge is not a valid EC2 instance type. Please see https://aws.amazon.com/ec2/instance-types/ click T2 tab and notice how t2.2xlarge is the largest available in the T2 General Purpose class.

**Comment by GrafanaWriter** [comment]
Fixed with (https://github.com/grafana/loki/pull/10347)
