### ISSUE TITLE
Docker Image Tags Missing - Docker Hub

### ISSUE THREAD

**Issue by therealdwright** [grafana/loki#10332]
**Describe the bug**
The docker hub images listed in your [most recent release v2.8.4](https://github.com/grafana/loki/releases/tag/v2.8.4) are not in docker hub.

**To Reproduce**
1. docker pull "grafana/loki:v2.8.4"
2. docker pull "grafana/promtail:v2.8.4"

Observe error:
```
Error response from daemon: manifest for grafana/loki:v2.8.4 not found: manifest unknown: manifest unknown
Error response from daemon: manifest for grafana/promtail:v2.8.4 not found: manifest unknown: manifest unknown
```

**Expected behavior**
The image pulls without error.

**Environment:**
 - Infrastructure: Ubuntu 22.04
 - Deployment tool: N/A

**Screenshots, Promtail config, or terminal output**
<img width="934" alt="image" src="https://github.com/grafana/loki/assets/15135979/95461872-d8fc-42bf-a139-cb2f0fdb9898">

**Comment by siddhikhapare** [comment]
@therealdwright Hi, In versions of Loki starting from 1.4.0, the "v" prefix has been eliminated. For instance, instead of using "grafana/loki:v1.4.0," you can now use "grafana/loki:1.4.0." This note has provided here https://hub.docker.com/r/grafana/loki.

**Comment by therealdwright** [comment]
> @therealdwright Hi, In versions of Loki starting from 1.4.0, the "v" prefix has been eliminated. For instance, instead of using "grafana/loki:v1.4.0," you can now use "grafana/loki:1.4.0." This note has provided here https://hub.docker.com/r/grafana/loki.

Perhaps the release notes need to be updated in that case:

<img width="501" alt="image" src="https://github.com/grafana/loki/assets/15135979/ad6c4500-bcae-4c4f-838b-eef9934efdda">

**Comment by siddhikhapare** [comment]
I have successfully obtained and installed the Grafana Docker image by using the command docker pull 'grafana/loki:2.8.4'.  
![dockerimage](https://live.staticflickr.com/65535/53143661482_ce25186aa3_o.png)

**Comment by therealdwright** [comment]
Can confirm images as described here work, release is still got the incorrect instructions but I'll leave that to the maintainers to deal with.
