### ISSUE TITLE
Loki cannot flush data to s3 when using kube2iam

### ISSUE THREAD

**Issue by claaslisowski** [grafana/loki#1034]
**Describe the bug**
We're running the helm chart with Loki 0.3 in EKS with 3 nodes.
We use kube2iam with a role that has S3 access.
Loki writes the chunks without issues to S3.
However when one of the pods is terminated, e.g. for an update the StatefulSet, Loki looses the capabilities to write to S3 and we receive this error:

```
level=error ts=2019-09-20T12:33:03.146995349Z caller=flush.go:156 org_id=fake msg="failed to flush user" err="NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"
```

(Full error logs attached and linked below)

That puts Loki in a loop state from which is is terminated after x seconds (tried up to 3 minutes). Once the pod is killed because the terminationGracePeriodSeconds expired it leaves the consul state in *LEAVING*. When Loki starts up again it can find an entry with its own ID and the state = LEAVING and therefore doesn't start the ingesting module.

**To Reproduce**
1. Started loki 0.3.0 with > 1 replicas 
  - with consul
  - with S3 bucket 
  -  kube2iam 
  - AWS IAM role
2. Started promtail
3. Observe that S3 contains data chunks
4. `kubectl delete po loki-0` 
5. observe that error message from above
6. observe that loki hangs in a loop until killed by Kubernetes 

**Expected behavior**
I expect Loki to flush the streams properly (as it does when using AWS access key and secret).

**Environment:**
 - Infrastructure: Kubernetes on EKS
 - Deployment tool: kr8 (jsonnet with helm )

**Screenshots, promtail config, or terminal output**
[loki-shutdown-error.log](https://github.com/grafana/loki/files/3636244/loki-shutdown-error.log)

**Comment by claaslisowski** [comment]
We are also using cortex as remote storage for prometheus there it works with kube2iam role. Not completely smooth, the shutdown process is similar as with Loki, same errors are thrown.
On startup however it restarts once more, probably the consul key is cleanup along any of these steps:

These are the logs for a cortex pod after a shutdown. You can see that it was left in the state LEAVING.
Then it gets a sigterm (because of a livenessProbe on /ready) and after that it works fine again.
I know that livenessProbe wasn't recommended on the ingester but without it it wouldn't recover properly. 

```
level=info ts=2019-09-20T15:18:04.030849851Z caller=cortex.go:198 msg=initialising module=overrides
level=info ts=2019-09-20T15:18:04.030900256Z caller=override.go:53 msg="per-tenant overrides disabled"
level=info ts=2019-09-20T15:18:04.030928299Z caller=cortex.go:198 msg=initialising module=store
level=info ts=2019-09-20T15:18:04.08604375Z caller=cortex.go:198 msg=initialising module=server
level=info ts=2019-09-20T15:18:04.088985501Z caller=server.go:117 http=[::]:9009 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2019-09-20T15:18:04.090630458Z caller=cortex.go:198 msg=initialising module=ring
level=info ts=2019-09-20T15:18:04.090752847Z caller=cortex.go:198 msg=initialising module=ingester
level=info ts=2019-09-20T15:18:04.091136048Z caller=cortex.go:198 msg=initialising module=distributor
level=info ts=2019-09-20T15:18:04.091243457Z caller=cortex.go:198 msg=initialising module=table-manager
level=info ts=2019-09-20T15:18:04.108258105Z caller=lifecycler.go:397 msg="existing entry found in ring" state=LEAVING tokens=512
level=info ts=2019-09-20T15:18:04.153915982Z caller=cortex.go:198 msg=initialising module=querier
level=info ts=2019-09-20T15:18:04.153961133Z caller=worker.go:72 msg="no address specified, not starting worker"
level=info ts=2019-09-20T15:18:04.157862548Z caller=cortex.go:198 msg=initialising module=all
level=info ts=2019-09-20T15:18:04.157912173Z caller=main.go:68 msg="Starting Cortex" version="(version=, branch=, revision=)"
level=info ts=2019-09-20T15:19:10.628296043Z caller=table_manager.go:220 msg="synching tables" num_expected_tables=27 expected_tables=27
level=info ts=2019-09-20T15:19:14.830497134Z caller=signals.go:54 msg="=== received SIGINT/SIGTERM ===\n*** exiting"
level=info ts=2019-09-20T15:19:14.830551086Z caller=cortex.go:224 msg=stopping module=all
level=info ts=2019-09-20T15:19:14.830587636Z caller=cortex.go:224 msg=stopping module=querier
level=info ts=2019-09-20T15:19:14.830604093Z caller=cortex.go:224 msg=stopping module=distributor
level=info ts=2019-09-20T15:19:14.830626761Z caller=cortex.go:224 msg=stopping module=ingester
level=info ts=2019-09-20T15:19:14.830671667Z caller=transfer.go:212 msg="nothing to transfer"

```

**Comment by joe-elliott** [comment]
It appears that Loki is calling s3.PutObject regardless of whether it's shutting down or just storing chunks normally.  So if the IAM role is working for normal operation it should work for shutdown flushing as well.

It appears that kube2iam had a bug in which it would not provide credentials to terminating pods:

https://github.com/jtblin/kube2iam/pull/173

Can you double check your kube2iam version?  Also any kube2iam logs might be helpful.

**Comment by claaslisowski** [comment]
Thanks @joe-elliott that was exactly the reason and updated kube2iam solved the issue.

**Comment by jaya-rama** [comment]
How can we deploy loki with s3 bucket inside kubernetes?

can someone help me to do this using helm or yaml files?

**Comment by jaya-rama** [comment]
> **Describe the bug**
> We're running the helm chart with Loki 0.3 in EKS with 3 nodes.
> We use kube2iam with a role that has S3 access.
> Loki writes the chunks without issues to S3.
> However when one of the pods is terminated, e.g. for an update the StatefulSet, Loki looses the capabilities to write to S3 and we receive this error:
> 
> ```
> level=error ts=2019-09-20T12:33:03.146995349Z caller=flush.go:156 org_id=fake msg="failed to flush user" err="NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"
> ```
> 
> (Full error logs attached and linked below)
> 
> That puts Loki in a loop state from which is is terminated after x seconds (tried up to 3 minutes). Once the pod is killed because the terminationGracePeriodSeconds expired it leaves the consul state in _LEAVING_. When Loki starts up again it can find an entry with its own ID and the state = LEAVING and therefore doesn't start the ingesting module.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Started loki 0.3.0 with > 1 replicas
> 
> * with consul
> * with S3 bucket
> * kube2iam
> * AWS IAM role
> 
> 1. Started promtail
> 2. Observe that S3 contains data chunks
> 3. `kubectl delete po loki-0`
> 4. observe that error message from above
> 5. observe that loki hangs in a loop until killed by Kubernetes
> 
> **Expected behavior**
> I expect Loki to flush the streams properly (as it does when using AWS access key and secret).
> 
> **Environment:**
> 
> * Infrastructure: Kubernetes on EKS
> * Deployment tool: kr8 (jsonnet with helm )
> 
> **Screenshots, promtail config, or terminal output**
> [loki-shutdown-error.log](https://github.com/grafana/loki/files/3636244/loki-shutdown-error.log)

How can we deploy loki with s3 bucket inside kubernetes?

can someone help me to do this using helm or yaml files?

**Comment by pavelnikolov** [comment]
@jaya-rama did you figure it out? I'm struggling with the configuration too

**Comment by jaya-rama** [comment]
> @jaya-rama did you figure it out? I'm struggling with the configuration too

Yes

**Comment by pavelnikolov** [comment]
What config did you use?
