### ISSUE TITLE
AWS signing region = dummy

### ISSUE THREAD

**Issue by tivvit** [grafana/loki#1038]
I ran into an issue with custom s3 endpoint. The S3 SDK is using v4 signing which is using region and I need to change it to something different than `dummy`. Loki is using `weaveworks/common` where this issue was recently fixed (https://github.com/weaveworks/common/commit/ecd64a57df80817ab201b56e5ba4c8a1b2f01512). But Loki is not using an upstream version it is using a fork https://github.com/sandlis/weaveworks-common/tree/server-listen-addr (https://github.com/grafana/loki/blob/master/Gopkg.toml#L31). That should be solved after merging this https://github.com/weaveworks/common/pull/153 (https://github.com/grafana/loki/issues/945) which is quite surprisingly a different branch then mentioned earlier but that is not important. 

It would be great to rebase the fork to master or to go back to upstream (which is probably not possible because of the features added in the fork). 

I will try if the code added to `weaveworks/common` will solve my problem but I am quite sure it will. I wanted to change the dependency but the relations of the projects are not very clear to me, so I will leave to someone who knows the project better than me. If there is anything I can help with it would be a pleasure.

**Comment by tivvit** [comment]
I confirm that the setup works for me with the code from upstream and correctly set `AWS_REGION` env variable.

**Comment by tivvit** [comment]
The code may be seen here https://github.com/tivvit/loki/commit/4774e7a8753b88cfa95f96b9fc6fd843e08ca12a

**Comment by ThoreKr** [comment]
@tivvit How do you determine whether an Endpoint should be http or https?

**Comment by tivvit** [comment]
Good question @ThoreKr 

I am using http, therefore I hit the general case https://github.com/tivvit/loki/commit/4774e7a8753b88cfa95f96b9fc6fd843e08ca12a#diff-a55d7f0f417b8521b203aa3ff35c9bafR56

I suppose loki aws url may be `https://` instead `s3://` but maybe it would break something I did not test it.
