### ISSUE TITLE
helm template fails with default values yaml

### ISSUE THREAD

**Issue by ArieLevs** [grafana/loki#10410]
**Describe the bug**
helm template for Loki helm chart with values.yaml from (current) main branch fails.

root cause seems to be this commit https://github.com/grafana/loki/commit/04685ea5123956f7b0936e88552a9947156b510a
that contains a change with
```
{{ include "loki.rulerConfig" . }}
```
to
```
{{ include "loki.rulerConfig". }}
```

**To Reproduce**
executing command
```
helm template grafana/loki --version 5.15.0 -f values.yaml
```
when the `values.yaml` contains content of file https://github.com/grafana/loki/blob/bcf917f65ad70568467d4af02c385607c7032ac9/production/helm/loki/values.yaml

will result in 
```
Error: template: loki/templates/write/statefulset-write.yaml:43:28:
...
parse error at (loki/templates/write/statefulset-write.yaml:81): unexpected <.> in operand
```

**Expected behavior**
Succesful helm tempalte

**Environment:**
 - Infrastructure: kubernetes
 - Deployment tool: Helm

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by JStickler** [comment]
This should be fixed via #10479
