### ISSUE TITLE
Loki 2.9 Release

### ISSUE THREAD

**Issue by kavirajk** [grafana/loki#10468]
We have started the release process for Loki 2.9. It will be cut from the release-2.9.x branch, which is based off the weekly release k163.

When done, the release will be available in the [releases](https://github.com/grafana/loki/releases) section of this repository.

**Comment by nikolay** [comment]
@kavirajk No binaries attached to the release, which breaks [asdf](https://asdf-vm.com/).

**Comment by jangrewe** [comment]
```
$  curl -sI https://github.com/grafana/loki/releases/download/v2.9.0/loki-linux-amd64.zip | head -n1
HTTP/2 404
```

**Comment by nikolay** [comment]
It seems that only @grafanabot releases are proper. It's sad that all human releases are without artifacts, i.e. 🤖 > 👨🏻‍💻.

**Comment by liv-io** [comment]
Assets are missing for this release. Thanks for taking care of this.

**Comment by nikolay** [comment]
All releases **should be** done consistently by @grafanabot! At least, that's what I am expecting from Grafana based on my respect for the brand. Handcrafting works only in the art domain.

**Comment by kavirajk** [comment]
Hey folks. Thanks for reporting this. Assets should be accessible and working now.

It was my mistake to create a release and publish manually instead of using the one created (draft) by Grafana bot. Fixed the assets few days ago. We are working to keep the release process as consistent as possible.

Let me know if you still face any issues with assets.
