### ISSUE TITLE
Clarify replication factor documentation

### ISSUE THREAD

**Issue by taleena** [grafana/loki#10485]
We've received questions around the replication_factor in loki, mentioned here: https://grafana.com/blog/2021/02/16/the-essential-config-settings-you-should-use-so-you-wont-drop-logs-in-loki/

We mention setting replication_factor to 3. However, we don't really say why that is important, or expand on the the connection between this and the number of ingestors (which is also generally 3). This is leading to some confusion and questions in OSS and from our partners.

Request updating/adding documentation around this, especially since that config blog is from 2021.

**Comment by MasslessParticle** [comment]
I think everything you're looking for is covered [here](https://grafana.com/docs/loki/latest/get-started/components/#replication-factor)?

**Comment by taleena** [comment]
This was from Sep 2023, so it's very likely this was updated and so this issue may now be solved. There have been further questions that have arisen around the WAL, but I think they are more for engineering. :) We can close this, unless someone form the docs team disagrees.
