### ISSUE TITLE
2.9.0 version cannot be unzipped

### ISSUE THREAD

**Issue by orange-kush** [grafana/loki#10500]
**Describe the bug**
When trying to unzip the file downloaded after executing: "curl -O -L "https://github.com/grafana/loki/releases/download/v2.9.0/promtail-linux-amd64.zip"
 I get an error message saying either the file is not a zip, or that the inside files are corrupted.

However, when trying to do it with any older version it works like a charm.

**To Reproduce**
1. curl -O -L "https://github.com/grafana/loki/releases/download/v2.9.0/promtail-linux-amd64.zip"
2. unzip promtail-linux-amd63.zip
3. error
4. curl -O -L "https://github.com/grafana/loki/releases/download/v2.8.0/promtail-linux-amd64.zip"
5. unzip promtail-linux-amd64.zip
6. no error

**Expected behavior**
allow the files to be unzipped

**Environment:**
 - Infrastructure: Ubuntu server 22.04 jammy jellyfish
 - Deployment tool: binary

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by liv-io** [comment]
@orange-kush The binary is simply not available under your link or any link in fact. They forgot to build/publish it for the latest release.

**Comment by Nudin** [comment]
It cannot be unziped, because it does not exist. The link is returning a 404 only since all the artifacts are missing from the release, see: https://github.com/grafana/loki/issues/10468 :/

**Comment by kavirajk** [comment]
Thanks for reporting this. Assets should be accessible and working now. 

```
$ curl -O -L "https://github.com/grafana/loki/releases/download/v2.9.0/promtail-linux-amd64.zip"
$ unzip promtail-linux-amd64.zip
```
