### ISSUE TITLE
Docs feedback: /docs/sources/get-started/architecture.md

### ISSUE THREAD

**Issue by saule1508** [grafana/loki#10524]
The doc contains a lot of references to boltdb_shipper but my understanding is that new users of loki should use tsdb and not boltdb. For example, in this page:

`This mode uses an adapter called [boltdb_shipper](https://grafana.com/docs/loki/latest/operations/storage/boltdb-shipper/) to store the index in object storage (the same way we store chunks).`

But this is confusing for new users because since 2.8 tsdb_shipper is available and is superior

The rest of the documentation would need to be adapted in this regard but I think having a warning note would be beneficial.

In my experience it is often confusing with loki doc to make sure it is still relevant as loki evoluates quickly.

See also https://github.com/grafana/loki/issues/9105

**Comment by JStickler** [comment]
@saule1508 One of the projects that the team is working on this quarter is cleaning up the boltdb-shipper code and docs to point users towards TSDB as the current preferred store.  Until we release the next version of Loki (and the docs) you can read the https://grafana.com/docs/loki/next/ for all the doc updates that will be published with the next release.

**Comment by saule1508** [comment]
@JStickler thank you, I created a pull request since it is a trivial quick fix but feel free to wait for next doc (https://github.com/grafana/loki/pull/10652)

**Comment by saule1508** [comment]
closing
