### ISSUE TITLE
Regression: PR 10388 causes multiple Helm resource annotations to be missing

### ISSUE THREAD

**Issue by willhughes-au** [grafana/loki#10528]
**Describe the bug**

PR #10388 was supposed to omit the `annotations` sections when empty. 

However the same `if` statement is used across a number of templates: 

`{{- if or (not (empty .Values.loki.annotations)) (not (empty .Values.backend.annotations))}}`

The issue is that `.Values.backend.annotations` is only used in `production/helm/loki/templates/backend/statefulset-backend.yaml`

The following templates use other chart value annotations: 

`production/helm/loki/templates/gateway/deployment-gateway.yaml` uses `.Values.gateway.annotations` 
`production/helm/loki/templates/single-binary/statefulset.yaml` uses `.Values.singleBinary.annotations` 
`production/helm/loki/templates/write/statefulset-write.yaml` uses `.Values.write.annotations`

**To Reproduce**
1. Deploy the Loki chart prior to 5.20.0, with annotations only set on `singleBinary.annotations` (as an example)
2. Note the statefulset has annotations
3. Upgrade to chart version 5.20.0 
4. Note that the annotations are gone, unless you have `loki.annotations` are also set. 

**Expected behavior**

Annotations should be kept.

**Environment:**
 - Infrastructure: EKS
 - Deployment tool: helm 

**Screenshots, Promtail config, or terminal output**

**Comment by rissson** [comment]
We're experiencing the same problem.
