### ISSUE TITLE
Support Promtail installations on Linux using package manager and systemd

### ISSUE THREAD

**Issue by jsirianni** [grafana/loki#10520]
**Is your feature request related to a problem? Please describe.**

There does not seem to be a supported path for installing Promtail on Linux (debian and rhel based systems) using a package manager and systemd.

**Describe the solution you'd like**

It would be nice to have deb and rpm packages available, that would install the binary and manage the systemd unit.

**Describe alternatives you've considered**

Sometimes docker is suitable on these systems, however, managing the container ecosystem on a system that otherwise doesn't require it can be frustrating.

**Comment by jeschkies** [comment]
There are Managed packages. See https://grafana.com/docs/loki/latest/setup/install/local/
