### ISSUE TITLE
Upgrading to 2.9.0 - "index gateway get ring: too many unhealthy instances in the ring"

### ISSUE THREAD

**Issue by WoodyWoodsta** [grafana/loki#10537]
**Describe the bug**
After upgrading from 2.8.4 to 2.9.0, I now get the following errors from `read` when attempting to execute a query:

```
msg="error querying storage" err="index gateway get ring: too many unhealthy instances in the ring"
```

I've deployed Loki in simple, scalable mode, and I've got 3 read, 3 write, 1 backend and 1 gateway deployments.

Has something changed in the ring requirements for Loki across this new version?

**To Reproduce**
1. Upgraded Loki to 2.9.0 (helm chart 5.20)
2. Allowed the cluster upgrade to roll out
3. Query anything

**Expected behavior**
Queries to run successfully.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
`read` log lines:

```
level=info ts=2023-09-11T11:23:00.01501528Z caller=engine.go:234 component=querier org_id=*** traceID=7e34703bc816af04 msg="executing query" type=range query="sum(rate_counter({job=\"loki.source.kubernetes_events\"} | logfmt count, type, namespace, name | type=\"Warning\" | unwrap count [10m])) by (type, name)" length=5m0s step=1s query_hash=1059187683
level=error ts=2023-09-11T11:23:00.0166908Z caller=series_index_store.go:626 org_id=*** traceID=7e34703bc816af04 msg="error querying storage" err="index gateway get ring: too many unhealthy instances in the ring"
```

`/memberlist`

```json
{
  "Now": "2023-09-11T11:24:58.040549064Z",
  "Memberlist": {},
  "SortedMembers": [
    {
      "Name": "loki-backend-0-2bddb021",
      "Addr": "10.244.28.184",
      "Port": 7946,
      "Meta": null,
      "State": 0,
      "PMin": 1,
      "PMax": 5,
      "PCur": 2,
      "DMin": 0,
      "DMax": 0,
      "DCur": 0
    },
    {
      "Name": "loki-read-6c5f7b99d-ff759-0434c974",
      "Addr": "10.244.28.157",
      "Port": 7946,
      "Meta": null,
      "State": 0,
      "PMin": 1,
      "PMax": 5,
      "PCur": 2,
      "DMin": 0,
      "DMax": 0,
      "DCur": 0
    },
    {
      "Name": "loki-read-6c5f7b99d-jb6hn-4339bfc7",
      "Addr": "10.244.28.169",
      "Port": 7946,
      "Meta": null,
      "State": 0,
      "PMin": 1,
      "PMax": 5,
      "PCur": 2,
      "DMin": 0,
      "DMax": 0,
      "DCur": 0
    },
    {
      "Name": "loki-read-6c5f7b99d-vhv9m-d3c7c834",
      "Addr": "10.244.28.130",
      "Port": 7946,
      "Meta": null,
      "State": 0,
      "PMin": 1,
      "PMax": 5,
      "PCur": 2,
      "DMin": 0,
      "DMax": 0,
      "DCur": 0
    },
    {
      "Name": "loki-write-0-0daac721",
      "Addr": "10.244.28.178",
      "Port": 7946,
      "Meta": null,
      "State": 0,
      "PMin": 1,
      "PMax": 5,
      "PCur": 2,
      "DMin": 0,
      "DMax": 0,
      "DCur": 0
    },
    {
      "Name": "loki-write-1-0c90a409",
      "Addr": "10.244.28.167",
      "Port": 7946,
      "Meta": null,
      "State": 0,
      "PMin": 1,
      "PMax": 5,
      "PCur": 2,
      "DMin": 0,
      "DMax": 0,
      "DCur": 0
    },
    {
      "Name": "loki-write-2-c6e16266",
      "Addr": "10.244.28.137",
      "Port": 7946,
      "Meta": null,
      "State": 0,
      "PMin": 1,
      "PMax": 5,
      "PCur": 2,
      "DMin": 0,
      "DMax": 0,
      "DCur": 0
    }
  ],
  "Store": {
    "collectors/compactor": {
      "Version": 251,
      "CodecID": "ringDesc"
    },
    "collectors/distributor": {
      "Version": 2264,
      "CodecID": "ringDesc"
    },
    "collectors/index-gateway": {
      "Version": 251,
      "CodecID": "ringDesc"
    },
    "collectors/ring": {
      "Version": 2265,
      "CodecID": "ringDesc"
    },
    "collectors/usagestats_token": {
      "Version": 1,
      "CodecID": "usagestats.jsonCodec"
    }
  },
  "MessageHistoryBufferBytes": 0,
  "SentMessages": null,
  "ReceivedMessages": null
}
```

`/indexgateway/ring`

```
{
  "shards": [
    {
      "id": "loki-backend-0",
      "state": "ACTIVE",
      "address": "10.244.28.184:9095",
      "timestamp": "2023-09-11T11:25:39Z",
      "registered_timestamp": "2023-09-11T10:22:24Z",
      "zone": "",
      "tokens": [***]
    }
  ],
  "now": "2023-09-11T11:25:45.925540533Z"
}
```

**Comment by jocelynthode** [comment]
We were facing exactly the same issue with the same setup as you. Setting the backend replicas to `3` instead of `1` solved the issue. It probably is a new requirement although I have not yet investigated more than this.

**Comment by WoodyWoodsta** [comment]
I had a similar issue with another component (either loki or mimir, I can't remember) and it was a min required instances thing, but nowhere can I see where this has changed.

**Comment by chaudum** [comment]
The bug was introduced with https://github.com/grafana/loki/pull/9170/files#diff-63fce4804a7a1326e58b3c5ab9bf8efed2fb8407de8280a170e1f74979a4b394R291

The simple scalable deployment requires the index gateway as part of the `backend` target to run in ring mode for discovery. However, the default replication factor for the index gateway is 3.

So there are two possible solutions: Either run >= 3 `backend` targets or set the [index gateway replication factor](https://grafana.com/docs/loki/latest/configure/#index_gateway) to 1.

We consider updating the Helm chart default values to match the replication factor with the number of backend replicas.

**Comment by WoodyWoodsta** [comment]
Thanks @chaudum - that makes sense. I do wish the error message for "not enough instances" was distinguishable from "too many unhealthy instances".

Will close as this isn't actually a bug!

**Comment by a5r0n** [comment]
@WoodyWoodsta maybe we should re-open this to keep track on the issue

**Comment by WoodyWoodsta** [comment]
My understanding is that it's not a bug, just a misconfiguration, unless you're referring to the fact that `index_gateway_shard_size` does not seem to work?

**Comment by ngochieu642** [comment]
I think the reason was the number of running backend pods (`backend.replicas=3`) is not enough

In my case, there should be 3 loki-backend pods, but because of pod anti-affinity, so only 1 pod was running (because I was running single-node minikube). But I guess any cluster with `nodes > 50% backend.replicas` will work just fine

So I just override the pod affinity and it works. Here is my `values.yaml` for [loki helm chart](https://github.com/grafana/loki/tree/main/production/helm/loki)

```yaml
backend:
  affinity: {}

write:
  affinity: {}

read:
  affinity: {}

loki:
  schemaConfig:
    configs:
      - from: "2024-01-23"
        index:
          period: 24h
          prefix: index_
        object_store: s3
        schema: v12
        store: tsdb

  storage_config:
    tsdb_shipper:
      shared_store: s3

    aws:
      access_key_id: ~
      secret_access_key: ~
      bucketnames: loki-test
      endpoint: ...
      region: ...
      s3forcepathstyle: true

  compactor:
    shared_store: s3
    compaction_interval: 10m
    retention_enabled: true
    retention_delete_delay: 8h
    retention_delete_worker_count: 10
```
