### ISSUE TITLE
Review labels consistency in lambda-promtail

### ISSUE THREAD

**Issue by thepalbi** [grafana/loki#10544]
Lambda promtail adds the `__aws_log_type` label to entries, to tell apart which was the logging source of that entry. This label is added for s3-based logs, but not for cloudwatch logs for example. 

We should review the supported sources, and make these labels consistent.

**Comment by spedersen-emailage** [comment]
Looks like `kinesis` and `s3` are the only two that add these labels.

https://github.com/search?q=repo%3Agrafana%2Floki%20__aws_log_type&type=code

**Comment by cstyan** [comment]
a test that enforces that this label is always set seems valid?
