### ISSUE TITLE
got logs but it's comming with LogfmtParserError error

### ISSUE THREAD

**Issue by ravi2099** [grafana/loki#10627]
kindly suggest authentic solution for this.

**Comment by dannykopping** [comment]
Hi @ravi2099, we'll need more details than that please.

What is the log line, and what is the exact error message?

**Comment by ravi2099** [comment]
@dannykopping  sure. Here is screenshot.
![logs](https://github.com/grafana/loki/assets/99610681/4f286542-d32b-440e-964b-38e0f613ddc4)
![log](https://github.com/grafana/loki/assets/99610681/d4d37a9d-ddc5-44ab-a5cd-186aa5d15366)

**Comment by dannykopping** [comment]
Those log messages are not in `logfmt` format, they are in `json` format.

You can use the ` | json` pipeline to process those correctly.
