### ISSUE TITLE
Support case-insensitive LogQL keywords

### ISSUE THREAD

**Issue by dannykopping** [grafana/loki#10638]
**Is your feature request related to a problem? Please describe.**
Loki's keywords & functions are currently case-sensitive.

Invalid:

```logql
count_over_time({app="distributor"}[$__auto]) > 1
AND 
count_over_time({app="distributor"}[$__auto]) < 100
```

Produces: `parse error at line 2, col 1: syntax error: unexpected IDENTIFIER`

Valid:

```logql
count_over_time({app="distributor"}[$__auto]) > 1
and 
count_over_time({app="distributor"}[$__auto]) < 100
```

**Describe the solution you'd like**
Folks coming from a predominantly SQL background might find writing the above query as the following to read better:

```logql
COUNT_OVER_TIME({app="distributor"}[$__auto]) > 1
AND 
COUNT_OVER_TIME({app="distributor"}[$__auto]) < 100
```

**Describe alternatives you've considered**
At the very least, improve the error message.

**Comment by dannykopping** [comment]
Great!

You can start by looking at the grammar, defined in https://github.com/grafana/loki/blob/main/pkg/logql/syntax/expr.y.
The https://github.com/grafana/loki/blob/main/pkg/logql/syntax/ package will likely where most of the changes will need to be made.

**Comment by Sheikh-Abubaker** [comment]
![image](https://github.com/grafana/loki/assets/99421476/e3489aeb-2b1d-469f-bce2-09853a0c8376)

Is this where the grammar is defined and if I change "and", "or" to "AND", "OR" will it then solve the issue ?

**Comment by dannykopping** [comment]
It's not as simple as that, I'm afraid.

**Comment by Sheikh-Abubaker** [comment]
![image](https://github.com/grafana/loki/assets/99421476/52a7c937-597b-43d6-9e45-896419d57574)

Will making changes to this function lead to solution ?

**Comment by dannykopping** [comment]
Possibly... I haven't looked into how this can be done yet.
If you're interested in contributing this change, I'd suggest doing the following:

- start with creating unit-tests which run queries with `COUNT_OVER_TIME` and `count_over_time` (for example), which will initially fail
- look around the code-base for where these identifiers are being processed (I think your snippet above might be that place)
- ensure the token is always lower-cased
- see if your tests pass

I won't have time to go back and forth on implementation questions like the above, unfortunately... The best way for us to collaborate is for you to understand the problem completely and implement a proposed solution in a PR, at which point I'll review it and we can discuss specifics.

Sound good?
