### ISSUE TITLE
Label issues for hacktoberfest

### ISSUE THREAD

**Issue by pracucci** [grafana/loki#1065]
The [Hacktoberfest](https://hacktoberfest.digitalocean.com/) is about to start. Would be nice if a maintainer with the right privileges will tag some issues - where we want support - with the `hacktoberfest` label.

**Comment by cyriltovena** [comment]
I’ll take a look today

**Comment by cyriltovena** [comment]
Voila !

**Comment by pracucci** [comment]
Thanks @cyriltovena !
