### ISSUE TITLE
Multi bucket s3 setup

### ISSUE THREAD

**Issue by tivvit** [grafana/loki#1066]
We are using custom s3 provider (Swift) and that has write rate-limiting for a single bucket. Does Loki currently support multi s3 bucket setup? I did a quick scan of docs and code and I am afraid it does not. 

Do you think it would be a useful feature?

**Comment by mizeng** [comment]
Yes, you are right. I was facing similar issue in Ceph Obj with S3 API. My proposal is to automatically isolate chunk objs with sub bucket with namespace. e.g. base bucket for loki is "s3://loki", sub bucket are "s3://loki/ns1" and "s3://loki/ns2". However this need quite a few code change in read/write to support this new storage arch.

**Comment by tivvit** [comment]
Thanks for your reply. I did not try (I moved to different storage) but this can be helpful for others.
