### ISSUE TITLE
Promtail: Pack add a config to support unorder JSON keys

### ISSUE THREAD

**Issue by lefay1982** [grafana/loki#10691]
**Is your feature request related to a problem? Please describe.**

The Fluent-Bit send logs to loki can keep origin  unorder keys json.
In loki:
![image](https://github.com/grafana/loki/assets/5716884/d7e5f47c-3273-406e-8323-bb5847e73892)

but  Grafana Agent's Promtail  config pack a new json, default sort the keys in pack.go code in line 73:
![image](https://github.com/grafana/loki/assets/5716884/f8d97c20-e06d-4d79-a026-e41406b5b259)
In loki:
![image](https://github.com/grafana/loki/assets/5716884/8c34bcdb-12d4-4223-af0b-93ae89362242)

**Describe alternatives you've considered**

so please add a config in promtail to support pack unordered keys json log. 

### Environment:
- Loki version: 2.8.5
- Agent version: v0.36.2

**Comment by vash-knives** [comment]
@JStickler , I can work on this, do you have any direction as to where is the best place to store the flag to switch between `ordered` and `unordered` ?

**Comment by lefay1982** [comment]
@vash-knives @JStickler This feature is belong to pack, you can add a option `sort_by_keys` default value can be false.

The `sort_by_keys` flag can be in here:
![image](https://github.com/grafana/loki/assets/5716884/31c8e79a-8a38-426c-83aa-07da1ea8eb22)

**Comment by vash-knives** [comment]
@lefay1982 can you drop your yaml pipeline_stages real quick just so i have an idea how you're configuring your promtail scrape job.

**Comment by lefay1982** [comment]
@vash-knives 
          pipeline_stages:
            - match:
                selector: '{job="agent"}'
                stages:
                  - multiline:
                      firstline: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3,9}'
                      max_wait_time: 3s
                  - regex:
                      name: log_entry
                      expression: '^(?P<time>[^\t]+)\t(?P<level>[^\t\s]+)[\s]*\t(?P<thread>[^\t]+)\t(?P<logger>[^\t]+)\t(?P<file>[^:]+):(?P<line>[\d]+)\t\[(?P<traceid>[^\t]*)\]\t(?P<msg>(?s:.*))$'
                  - pack:
                      name: out_map
                      labels:
                        - time
                        - level
                        - thread
                        - logger
                        - file
                        - traceid
                        - msg
                  - timestamp:
                      source: time
                      location: "Asia/Shanghai"
                      format: "2006-01-02 15:04:05.000"
                      fallback_formats: 
                        - RFC3339Nano
                  - labels:
                      app_name:
                      time:
                      level:
                      thread:
                  - output:
                      source: out_map

**Comment by vash-knives** [comment]
@JStickler , do you by any chance know how to run the unit tests locally for promtail changes or is the "run all unit tests" the only option i have?

**Comment by cstyan** [comment]
Commenting with the same message I left on the related PR:

> Hello, thanks for your PR.
>
 > We're currently reevaluating promtails position as a project within Grafana Labs. Internally we're actually using the [Agent](https://github.com/grafana/agent) for both metrics and logs collection at this point. Additionally, the agent team is more likely to have time to dedicate to your PR.
>
> While we haven't made a formal decision yet, we expect in the near future that all new feature work will be done in the Agent's log collection pipelines rather than in Promtail.

**Comment by lefay1982** [comment]
![image](https://github.com/grafana/loki/assets/5716884/844b1e7a-0d12-4db0-804e-c3b95d5d3e4d)
the agent project has the same pack.go file, who can synchronize modify this file to disable sort labels?

**Comment by cstyan** [comment]
A feature request should be made in the agent repo.
