### ISSUE TITLE
Can't Run Loki with non user 0

### ISSUE THREAD

**Issue by EvertonSA** [grafana/loki#10799]
Our container audit stack provided by Microsoft is detecting promtail is running as root (user 0).

I tried to use a different user but it seems not possible as it leads to permission issues.

Can it be possible to run promtail with user 10001, like loki? 

https://github.com/grafana/loki/blob/main/cmd/loki/Dockerfile#L14

**Comment by hainenber** [comment]
IMO, Promtail is run as root to allow tailing logs from any paths user can specified in `promtail-docker-config.yaml`. If you want to run it as another user, you'll need to grant necessary read permission for that `promtail` user.

**Comment by EvertonSA** [comment]
Thanks,  makes sense to me
