### ISSUE TITLE
promtail fails to parse RFC5424 syslog with nanoseconds

### ISSUE THREAD

**Issue by llamafilm** [grafana/loki#10866]
**Describe the bug**
Promtail fails to parse syslog messages based on RFC5424 with nanosecond resolution in timestamps

**To Reproduce**
```
echo "<14>1 2023-10-12T06:46:31.088609123Z 10.0.0.4 qsys - - - Error Control Failed to send email." | nc -u -v -w 1 10.0.0.5 514
```

**Expected behavior**
It should parse the message

**Environment:**
Promtail 2.8.4 running in Docker

**Screenshots, Promtail config, or terminal output**
```
level=warn ts=2023-10-12T06:50:45.49684743Z caller=syslogtarget.go:105 msg="error parsing syslog stream" err="expecting a RFC3339MICRO timestamp or a nil value [col 26]"
```

If I remove the last 3 digits from the timestamp then it works fine.

**Comment by hainenber** [comment]
Actually by RFC5424's [definition](https://datatracker.ietf.org/doc/html/rfc5424), the timestamp field should only have maximum length of 6 digits. Hope this helps!

```
   Example 5 - An Invalid TIMESTAMP

         2003-08-24T05:14:15.000000003-07:00

   This example is nearly the same as Example 4, but it is specifying
   TIME-SECFRAC in nanoseconds.  This results in TIME-SECFRAC being
   longer than the allowed 6 digits, which invalidates it.

```

**Comment by llamafilm** [comment]
Thanks, I see that you’re right.
