### ISSUE TITLE
Fix Docker Hub tags for Loki

### ISSUE THREAD

**Issue by aku** [grafana/loki#1087]
**Describe the bug**
**docker pull grafana/loki:latest** command pulls Loki with old API (**/api/prom/push** instead of **/loki/api/v1/pull**)

Currently, I have to build from source or provide some label from grafanabot
e.g. **grafana/loki:master-42040f2**

**Expected behavior**
Please provide correct labels/tags for Loki images

**Comment by cyriltovena** [comment]
The CI needs to be update to include a push to latest.

**Comment by slim-bean** [comment]
It looks like when moving to Drone.io for building images we no longer tag `master` or `latest` 

@sh0rez it doesn't look like drone config calls the make targets for building images, could we updated it to do this so we can get the `master` and `latest` tags?

**Comment by sh0rez** [comment]
I‘ll look into it!

**Comment by edasque** [comment]
AFAIK, this is still the case. latest is over a month old. Would be nice to version tag too so we can start using SEMVER on something like 0.3

**Comment by sh0rez** [comment]
Been quite busy for the last weeks, will look into this after I am back from vacation

**Comment by slim-bean** [comment]
Version tags exist already `v0.3.0` is the most recent, `v0.4.0` will be out soon

I will hopefully also get a chance to look at the latest/master tags this week
