### ISSUE TITLE
Helm: sidecar is not part of singleBinary

### ISSUE THREAD

**Issue by awoimbee** [grafana/loki#10967]
**Describe the bug**
When I deploy loki in singleBinary mode, but `sidecar.rules.enabled` is `true`, I expect the sidecar to be deployed with loki.
But it's not, a code search (`repo:grafana/loki path:/^production\/helm\/loki\/templates\// sidecar`) shows that sidecar is only present in `statefulset-backend.yaml`.

What I did:
Switched to the "scalable" deployment, got better query speeds at the same time !

**Comment by marknesterovych** [comment]
Got the same situation. sidecar is ignored in single binary mode.

**Comment by alarobric** [comment]
Is there any reason for this to be the case? I'm finding documentation on how to actually deploy recording rules or alerts to be quite sparse, and now finding that the helm chart support for this isn't there either.
