### ISSUE TITLE
Loki API could return the size of logs it has processed.

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#1098]
**Is your feature request related to a problem? Please describe.**

When doing a query it would be interesting to know how many logs and how much bytes has been processed.

This can be very interesting for queries returning metrics or filter queries.

**Describe the solution you'd like**

Extends the API with more information.

**Comment by adityacs** [comment]
@cyriltovena I started looking into this. It's trickier than I thought. Could you please give me some clue on which part of the code is downloading the chunk and iterating over the logs. I initially thought `len(h)` here https://github.com/grafana/loki/blob/master/pkg/iter/iterator.go#L73 should give the number of log lines to iterate. My understanding was wrong. Kindly give some clue to proceed on this.

**Comment by cyriltovena** [comment]
The statistics added recently cover this. Sorry forgot to close.

**Comment by adityacs** [comment]
@cyriltovena Sorry, I referenced wrong issue
