### ISSUE TITLE
Docker hub `latest` tag points to 2.8.6 instead of 2.9.2

### ISSUE THREAD

**Issue by mjec** [grafana/loki#10990]
**Describe the bug**

The dockerhub `grafana/loki:latest` image currently points to version 2.8.6, while the latest stable is 2.9.2.

This caused a downgrade when I rebuilt the container, resulting in hard-to-understand behavior regressions (in my case, loss of the `unixToTime` template function).

I understand that using `:latest` is not ideal when consistent behavior is required, but in the absence of a `2.9` (or other semver-compatible) label, it's the only way to automatically get patch updates on rebuild. 

I suspect the cause of this is that whatever the last-in-time tagged build is will update `:latest`, even when there's an earlier-in-time but later-in-version build available. It seems like the release of 2.8.6 happened 11 minutes after 2.9.2, hence the regression. I suspect the code responsible is here: https://github.com/grafana/loki/blob/9d9b05ad408876d51a773ca68f926c0da712259d/.drone/docker-manifest.tmpl#L4-L6

**To Reproduce**
`docker pull grafana/loki:latest && docker run -it grafana/loki:latest loki -version`

**Expected behavior**
In accordance with #4557, I expected `:latest` to point to the latest stable version.

**Environment:**
 - Infrastructure: bare metal
 - Deployment tool: plain docker

**Screenshots, Promtail config, or terminal output**

Output from `loki -version`:

```
loki, version 2.8.6 (branch: HEAD, revision: 990ac685e)
  build user:       root@6fad14503983
  build date:       2023-10-17T14:21:58Z
  go version:       go1.20.10
  platform:         linux/amd64
```

**Comment by ashwanthgoli** [comment]
thank you @mjec for reporting this. we have updated the latest tag to use v2.9.2 images.
we'll use the this [issue](https://github.com/grafana/loki/issues/10695) to improve the tagging process for releases.
