### ISSUE TITLE
yamllint errors syntax error: found character '\t' that cannot start any token (syntax)

### ISSUE THREAD

**Issue by earimont-ib** [grafana/loki#11059]
**Describe the bug**
syntax error: found character '\t' that cannot start any token (syntax) 
https://github.com/grafana/loki/blob/main/production/helm/loki/templates/backend/statefulset-backend.yaml#L262C22-L262C22

https://github.com/grafana/loki/blob/main/production/helm/loki/templates/read/statefulset-read.yaml#L165C22-L165C22

https://github.com/grafana/loki/blob/main/production/helm/loki/templates/single-binary/statefulset.yaml#L179

**To Reproduce**
1. Started Loki (SHA or version)
2. Started Promtail (SHA or version) to tail '...'
3. Query: `{} term`

**Expected behavior**

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by hainenber** [comment]
I have a hunch that a literal Tab character is in your config. I'm not sure if Loki toolchains has any sanitizer but I tend to run `yq` or `yamllint` over to ensure hygiene.

**Comment by earimont-ib** [comment]
@hainenber @nashton Looks like this commit https://github.com/grafana/loki/commit/5132f6d2a76a26d6e3b8b7127094d16eb26e9442 addresses this issue?

**Comment by hainenber** [comment]
Yep, looks like it!
