### ISSUE TITLE
Loki defines metrics that it never updates

### ISSUE THREAD

**Issue by rfratto** [grafana/loki#1105]
Referring to the [list of metrics](https://github.com/grafana/loki/blob/master/docs/operations/observability.md) that Loki exposes, it seems that a subset of them are defined but never incremented. One example of this is `loki_ingester_chunks_flushed_total`, although there may be others.

**Comment by joe-elliott** [comment]
Reviewing all metrics in the linked documents only `loki_ingester_chunks_flushed_total` is missing.  This metric is trivially calculated by summing `loki_ingester_chunks_stored_total`.  Removing it from the documentation/codebase.
