### ISSUE TITLE
Suppor for referencing nested record fields in Fluent plugin

### ISSUE THREAD

**Issue by Horkyze** [grafana/loki#1107]
Currently, there is no way (that I know of) to reference nested JSON items in fluents plugin.

Somthing like this:
```
label_keys container_tag, hostname, message['path'], massage.path
```

It would be awesome to have the ability to use Fluent's [RecordAccessor](https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin_helper/record_accessor.rb) module.

So the nested items will be accessible like this:

```
label_keys container_tag, hostname, $.message.method,  $.message.anyting
```

The whole problem can be avoided I one does not uses nested JSONs in their record data model. But on the other hand, nesting provides better readability.

**Comment by cyriltovena** [comment]
This is only true for fluentd, for fluent-bit we have nested mapping via json config.

This is very interesting, thank you !

**Comment by slim-bean** [comment]
This looks like it's supported now as of #1186
