### ISSUE TITLE
[K8S self monitoring] relabelings break other kubernetes monitoring dashboards

### ISSUE THREAD

**Issue by bossm8** [grafana/loki#11080]
**Describe the bug**
Adding the relabelings as described in the [documentation](https://grafana.com/docs/loki/next/setup/install/helm/monitor-and-alert/with-local-monitoring/). Breaks the default kube-prometheus-stack dashboards.

**To Reproduce**
1. Started Loki (SHA or version)
2. Started Promtail (SHA or version) to tail '...'
3. Query: `{} term`

**Expected behavior**
The default kube-prometheus-stack dashboards still work when relabelings described in the documentation are added to the kube-prometheus-stack.

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Screenshots, Promtail config, or terminal output**
<img width="1914" alt="image" src="https://github.com/grafana/loki/assets/91630231/04aab6cc-007c-4236-a9f2-af0a3ba8a42f">

**Comment by jakeforge** [comment]
Has anyone found a workaround for this?  This is a pretty important feature for those of us leveraging built in dashboards form both loki and kube-prometheus-stack.  
Is there another place to put the relabeling config so that it doesn't apply to all metrics scraped by the prometheus?
