### ISSUE TITLE
Different packaging for release binaries

### ISSUE THREAD

**Issue by aledeganopix4d** [grafana/loki#1113]
We deploy `promtail` on all our infra VMs as native binaries. Unfortunately the choice of gunzipping the binary file is a bit incovenient for us for two reasons:

1. We deploy with Saltstack that natively (through archive.extract) is unable to open .gz files (it can open .tar.gz though)
2. On Windows there's no native tool that can uncompress the .gz file and thus would require to install gzip first (or similar archive manager)

A simple solution could be to compress the resulting binary in `.zip` format which is much more supported.

Alternatively the uncompressed binary would work too.

How does the community feel about this?
Thanks!

**Comment by sh0rez** [comment]
Hi, thanks for pointing out! I assumed that `gzip` was well-supported at the time choosing this format.

Of course we can switch to a more common format. I wonder what fits best here, `tar.gz` is probably the most common format in the UNIX world, while `zip` should be supported literally everywhere.

We would need to carefully update install instructions to make users aware of this change / update all old releases

What do you think @slim-bean @rfratto @cyriltovena

**Comment by cyriltovena** [comment]
yes let's do it !
