### ISSUE TITLE
Operator: Support configuring Azure Service Principal auth in object storage secret

### ISSUE THREAD

**Issue by calohmn** [grafana/loki#11150]
**Is your feature request related to a problem? Please describe.**

When using the Loki Operator in connection with Azure Blob storage, the Secret for object storage authentication currently must contain the storage account name and account key.
```
kubectl create secret generic lokistack-dev-azure \
  --from-literal=container="<AZURE_CONTAINER_NAME>" \
  --from-literal=environment="<AZURE_ENVIRONMENTs>" \
  --from-literal=account_name="<AZURE_ACCOUNT_NAME>" \
  --from-literal=account_key="<AZURE_ACCOUNT_KEY>" \
  --from-literal=endpoint_suffix="<OPTIONAL_AZURE_ENDPOINT_SUFFIX>"
```
But, using the account key for storage account access is discouraged by Microsoft (see for example [here](https://learn.microsoft.com/en-us/azure/storage/common/shared-key-authorization-prevent)).
Therefore, the object storage secret should support configuration of the Service Principal tenant-id, client-id and client-secret as an alternative.

**Describe the solution you'd like**

Adding support for object storage Secret entries that map to the `use_service_principal`, `tenant_id`, `client_id` and `client_secret` configuration entries of the Loki `azure_storage_config`.

**Describe alternatives you've considered**

**Additional context**

**Comment by periklis** [comment]
@calohmn Thanks for raising this, we already work on the proposal for adding STS/WIF/etc. support in the operator. I encourage you to read through this proposal: 
- https://github.com/grafana/loki/pull/11060

**Comment by periklis** [comment]
@calohmn Wanted to let you that the current state in main supports Azure Workload Identity Federation as opposed to use static service account credentials. We believe this might be a heavier approach when running Loki Operator on environments like Azure but it is on the other hand the future-proof approach on most managed clusters. Thus I tend to see only diminishing returns by adding support for a third approach with the service principal only w/o federation in play. 

If you have a good argument and would like to contribute this piece, glad to hear and read from you in form of a PR. Even happier helping you to land your contribution soon. Till then closing this issue as we will not pursue for now.
