### ISSUE TITLE
Configure encoding of scraped logs

### ISSUE THREAD

**Issue by aledegano** [grafana/loki#1119]
As Windows is... special... in the Server2019 edition (at least) the log files are saved with the `UTF-16` encoding, this means that trying to scrape them as-is will result in a mangled output in Grafana.

If it was possible to specify through configuration the encoding of the scraped logs (and then parsing the files accordingly) this problem above could be simply solved.

For the time being I'm re-saving the files with `UTF-8` encoding so that they can be displayed correctly.

**Comment by jgehrcke** [comment]
I assume that the underlying premise here is that Loki as a storage system is entirely bytes-oriented (not text-oriented) at all its interfaces.

That in turn means that these interfaces makes "most sense" (in practice, to humans) when the payload data that loki stores -- byte sequences -- after all represent text stored via the UTF-8 encoding.

Given the byte-oriented interfaces, including the push interface, it's the responsibility of the operators to make sure that the abstract text information (which logs after all are) enters the storage system encoded in a consistent, meaningful, predictable way (using a single, useful text encoding -- say, utf-8). This can only be enforced by convention (not by e.g. the Loki API).

The pushing entities (such as Promtail) can of course help with enforcing that convention, by for example making sure that they only push byte sequences that are valid in the target encoding (say, utf-8).

In addition, when different log sources emit their log data in different text encodings (to the file system) then a pushing entity (Promtail) can help normalize that to a single codec.

The configuration interface in Promtail should then really expose the fact that there is both, an input codec per log file (with which Promtail will decode the byte sequence in the file) as well as an output codec (with which Promtail will encode the log text into a byte sequence before pushing the data to Loki).

**Comment by snv** [comment]
I too am having a problem with Log-Files, which are not UTF8 (and can not that easily be changed).
The above pull-request addresses this issue, but it seems to have been closed, because it has been ignored :(

**Comment by yosiasz** [comment]
https://github.com/grafana/loki/issues/6235
