### ISSUE TITLE
Distributed Loki Querier's Skew

### ISSUE THREAD

**Issue by naveenpg11** [grafana/loki#11223]
**Describe the bug**

Is there any reason a querier has to be distributed across nodes by default ? 
[This](https://github.com/grafana/helm-charts/blob/4754e9a88a4a548ddea7bd65128218829087cc5a/charts/loki-distributed/values.yaml#L685C1-L691C68) topologySpreadConstraints is by default, placing only one querier in a node ? 
Is there any reason behind this ? 

Other ref: [Link](https://grafana.slack.com/archives/CEPJRLQNL/p1699091400505169?thread_ts=1699032593.472769&cid=CEPJRLQNL)

**Expected behavior**
Can we not have this constraint ? 

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Helm

**Comment by QuentinBisson** [comment]
@naveenpg11 why can you not remove it when you deploy your loki chart?

I'm guessing having it spread to different nodes helps ensuring querying works when a node dies. So if you have 2 pods spread across nodes, it's less likely that querying will stop working.

If the 2 queriers are on the same node, a node failure has more consequences

**Comment by DylanGuedes** [comment]
Hey thanks for your report.

I'll close this issue because, as @QuentinBisson pointed out, `topologySpreadConstraints` is modifiable so it isn't really a "constraint".
