### ISSUE TITLE
Release 0.3.0 checksum error

### ISSUE THREAD

**Issue by mleyden** [grafana/loki#1125]
Using:
molecule, version 2.20.2
ansible 2.8.3
docker with CentOS 7

Downloading as follows:
> curl -o /usr/local/bin/loki.gz -L https://github.com/grafana/loki/releases/download/v0.3.0/loki_linux_amd64.gz

Using sha256sum ver. 8.22
> sha256sum /usr/local/bin/loki.gz
936cd0cb8e28944d97a877976910376df8d881a4892d24fcf56526ea4ebcca33  /usr/local/bin/loki.gz

Which does not match the entry in https://github.com/grafana/loki/releases/download/v0.3.0/SHA256SUMS
which states it should be 2dc01f97e50b1de286bc02c09f95e18a9140c5a5345f737b22c145f2f020720a

**Comment by rfratto** [comment]
Hi, thanks for reporting. We've re-released v0.3.0 and the SHAs should match now. 

The promtail binaries for v0.3.0 was updated last week to address #1057 before v0.4.0 but apparently caused issues in the SHA256SUMS. Going forward, we'll make sure that we don't change binaries after the initial release.
