### ISSUE TITLE
Add default value for loki/promail

### ISSUE THREAD

**Issue by daixiang0** [grafana/loki#1127]
Built loki binary file with master HEAD commit, run below cmd:
```
 ./loki -server.http-listen-port 3100 -server.http-listen-host localhost
level=info ts=2019-10-08T01:33:38.130165721Z caller=loki.go:125 msg=initialising module=server
level=info ts=2019-10-08T01:33:38.130678565Z caller=server.go:121 http=127.0.0.1:3100 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2019-10-08T01:33:38.131111781Z caller=loki.go:125 msg=initialising module=overrides
level=info ts=2019-10-08T01:33:38.131144879Z caller=override.go:53 msg="per-tenant overrides disabled"
level=info ts=2019-10-08T01:33:38.131172672Z caller=loki.go:125 msg=initialising module=table-manager
level=error ts=2019-10-08T01:33:38.131201345Z caller=main.go:65 msg="error initialising loki" err="error initialising module: table-manager: Must set -dynamodb.url in aws mode"
```

The root reason is that some config like tablemanager does not have default value.

@slim-bean @cyriltovena if needed, i would like to do this.

**Comment by daixiang0** [comment]
Also, need to document which value must set i think.

**Comment by sh0rez** [comment]
The thing here seems to be that this is very environment specific, IE Dynamo on Aws but Bigtable on Gcp. 

It would be hard to find a default that fits all so it might be better to improve the error message instead

**Comment by daixiang0** [comment]
Yep, so need to discuss which parts of config can use default and which must be set by users.

**Comment by rfratto** [comment]
I agree with @sh0rez about the difficulty of this. Perhaps the default config (i.e., when no config file is provided) should be a single-binary Loki with local storage for quick demoing/evaluation. I don't think it's going to be possible to provide a _useful_ config by default, though.

**Comment by daixiang0** [comment]
@rfratto @sh0rez any new about this?
