### ISSUE TITLE
Multiple S3 buckets leads to Loki errors and failure

### ISSUE THREAD

**Issue by akevdmeer** [grafana/loki#11316]
Configuring multiple buckets on an AWS/S3 store leads to errors such as missing chunks at query time, and compaction errors like

`level=error caller=compactor.go:128 table-name=loki_index_tsdb_19683 msg="failed to remove downloaded index file" path=/var/loki/compactor/loki_index_tsdb_19683/1700667008-loki-write-0-1700660468255353690.tsdb err="remove /var/loki/compactor/loki_index_tsdb_19683/1700667008-loki-write-0-1700660468255353690.tsdb: no such file or directory"
`

Configure multiple buckets, populate with logs. Await concurrent compactions of a table due to repeated S3 common prefixes being returned, and resulting misbehaviour.

Please see candidate fix in PR.

**Comment by davidkohr** [comment]
This still happens in version 3.5.7, but when you add one or more new buckets to an existing Loki setup.

`level=error ts=2025-10-22T04:09:20.977026595Z caller=compactor.go:129 table-name=index_20382 msg="failed to remove downloaded index file" path=/var/loki/compactor/index_20382/1761066938-grafana-loki-ingester-zone-a-0-1760458073577170966.tsdb err="remove /var/loki/compactor/index_20382/1761066938-grafana-loki-ingester-zone-a-0-1760458073577170966.tsdb: no such file or directory"`
