### ISSUE TITLE
Loki's memcache library uses timeouts incorrectly

### ISSUE THREAD

**Issue by dannykopping** [grafana/loki#11345]
Relates to #7911

**Describe the bug**
_This is not a bug in Loki necessarily, but I'm documenting it here to describe how the underlying lib's incorrect behaviour affects Loki._

Loki uses [grafana/gomemcache](https://github.com/grafana/gomemcache) for communicating with memcached servers. When using chunks cache:

```yaml
memcached_client:
  # Maximum time to wait before giving up on memcached requests.
  # CLI flag: -<prefix>.memcached.timeout
  [timeout: <duration> | default = 100ms]
```

The value of thie `timeout` field is passed to the `Timeout` member of the gomemcache `Client` struct:

https://github.com/grafana/gomemcache/blob/6947259a05865b6a7482cb73b556591498f3da0a/memcache/memcache.go#L154-L156

```go
	// Timeout specifies the socket read/write timeout.
	// If zero, DefaultTimeout is used.
	Timeout time.Duration
```

Since this timeout is being used in `net.Conn.SetDeadline`, the lib needs to extend the deadline after each request on the connection. However, the deadline is only extended each time a new connection is [fetched from the pool](https://github.com/grafana/gomemcache/blob/6947259a05865b6a7482cb73b556591498f3da0a/memcache/memcache.go#L418-L422) and (this is where the bug is) _not_ after each item is fetched from memcached.

When using traditional in-memory memcached this problem is less likely because the latencies are lower, but it can still happen using our default memcached client settings. When using extstore, however, and especially under high load, high latencies can be introduced by reading large volumes of data from the SSD, writing back to the network, reading from the network, or a combination of these.

**To Reproduce**
1. Use Loki with memcached + extstore
2. Introduce high load or network/disk latency, observe some memcached requests timing out

**Expected behavior**
gomemcache's connection deadline should be reset after reading each item from the connection, not only after all items have [been read and parsed](https://github.com/grafana/gomemcache/blob/6947259a05865b6a7482cb73b556591498f3da0a/memcache/memcache.go#L654-L659).

I've [created a branch in gomemcache](https://github.com/grafana/gomemcache/compare/master...dannykopping:gomemcache:dannykopping/prove-network-timeout#diff-a77e620e2ac3ca11d2a44e7593d683aae170f4ec9081a4f33b14c5de18df1327) to validate @dormando's theory, and unsurprisingly he is correct.

**Acknowledgments**
Credit and huge thanks go to @dormando for discovering this issue and reporting it to me.
[Here is the discussion thread in the memcached Discord.](https://discord.com/channels/634311773750689794/1171640517889638430)

**Comment by Hitesh-Agrawal** [comment]
This bug is fixed in which version of Loki.
