### ISSUE TITLE
operator: Update kustomize files to remove deprecated keywords/features

### ISSUE THREAD

**Issue by fortra-cloudops-platform** [grafana/loki#11419]
When using kustomize to deploy the operator I see these WARNINGS

```
# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'vars' is deprecated. Please use 'replacements' instead. [EXPERIMENTAL] Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
```

**To Reproduce**
Run `kustomize build` for the operator

**Expected behavior**
No Warnings of deprecations

**Comment by periklis** [comment]
The kustomize config is still v4 but we are happy for any contribution to push this to v5. Glad to help anybody driving this

**Comment by periklis** [comment]
This will be addressed soon when upgrading the operator code base using operator-sdk v1.33 and refactoring the underlying code structure to reflect kubebuilder go/v4 as per later requires kustomize v5.
