### ISSUE TITLE
Make `/ingester/shutdown` endpoint work with `GET`

### ISSUE THREAD

**Issue by andresperezl** [grafana/loki#11431]
**Is your feature request related to a problem? Please describe.**
Currently the `/ingester/shutdown` endpoint only works with the `POST` method, but the kuberentes lifecycle `httpGet` (as the name implies) sends a `GET` requests, which doesn't do anything when triggered against that pod.

**Describe the solution you'd like**
The `/ingester/shutdown` endpoint should work with a HTTP `GET` request

**Describe alternatives you've considered**
The work around is using the `exec` to use a tool like `wget` or `curl` to send a `POST` request to the endpoint.

**Additional context**
In the loki chart is using the `httpGet` as well which is basically a no-op: https://github.com/grafana/loki/blob/main/production/helm/loki/templates/write/statefulset-write.yaml#L121

https://grafana.com/docs/loki/latest/operations/storage/wal/#kubernetes-hacking
https://grafana.com/docs/loki/latest/reference/api/#flush-in-memory-chunks-and-shut-down

**Comment by splitice** [comment]
@andresperezl you beat me to this issue by less than a day!

I was wondering why the kubernetes call wasnt working after flush on shutdown was removed from the ingester component :(
