### ISSUE TITLE
Documentation https://grafana.com/docs/loki is not complete for distributor ipv6

### ISSUE THREAD

**Issue by fayak** [grafana/loki#11459]
**Is your feature request related to a problem? Please describe.**
(Not sure if a feature request is the most appropriate for mention such issues, it looked better than a bug report, sorry if it's not the best place)
Documentation found in https://grafana.com/docs/loki/v2.9.x/configure/#distributor doesn't mention option `ring.instance_enable_ipv6` https://github.com/grafana/loki/blob/main/pkg/distributor/distributor_ring.go#L34C51-L34C51 and its flag https://github.com/grafana/loki/blob/main/pkg/distributor/distributor_ring.go#L59

**Describe the solution you'd like**
Having this flag/option mentioned like they are for other components

**Describe alternatives you've considered**
//

**Additional context**
//

**Comment by rgroothuijsen** [comment]
Since the field is marked with `doc:"hidden"` I'm thinking that this might be intentional, though I'm not sure since the field doesn't have this tag in the other cases.

**Comment by JStickler** [comment]
Closing, as not documenting this setting is intentional.
