### ISSUE TITLE
Different config between doc and code for limits config

### ISSUE THREAD

**Issue by mizeng** [grafana/loki#1147]
**Describe the bug**
Seems there're quite a few difference of limits config between config doc and real code.
e.g. https://github.com/grafana/loki/tree/master/docs/configuration#limits_config vs https://github.com/grafana/loki/blob/master/pkg/util/validation/limits.go#L15-L40

Take ** ingestion_rate** as an example, I can not find it in the code at all. Instead, there's one named "ingestion_rate_mb". Do I miss something?

**Comment by eminden** [comment]
I hit the same one (ingestion-rate-limit-mb vs ingestion-rate) right now.

**Comment by pstibrany** [comment]
This seems to have been fixed by https://github.com/grafana/loki/pull/1278
