### ISSUE TITLE
Promtail Unhealthy: kubernetes_events Warning  loki-stack-promtail

### ISSUE THREAD

**Issue by wuestkamp** [grafana/loki#1149]
**Describe the bug**
`loki-stack-promtail` instances go into Warning state.

I get notified through Grafana/Prometheus if "kubernetes_events" Warning events happen

**Expected behavior**
`loki-stack-promtail` should not get into a Warning state.

**Environment:**
DigitalOcean cluster
```
helm3 upgrade --install loki-stack -n=loki-stack loki/loki-stack
```
installed `grafana/promtail:v0.3.0` and `grafana/loki:v0.3.0`

**Kubernetes Event**
```
kubernetes_events{
  app=
  "event-exporter",
  event_kind=
  "Pod",
  event_name=
  "loki-stack-promtail-w4jx6",
  event_namespace=
  "loki-stack",
  event_reason=
  "Unhealthy",
  event_source=
  "pool-8ctjae4p1-w47h/kubelet",
  event_subobject=
  "spec.containers{promtail}",
  event_type=
  "Warning",
  instance=
  "x.x.x.x:9102",
  job=
  "kubernetes-pods",
  kubernetes_namespace=
  "event-exporter",
  kubernetes_pod_name=
  "event-exporter-7fd4984744-cpffj",
  pod_template_hash=
  "7fd4984744"
}
```

**memory and cpu**
No spikes visible.

**logs**
Before one occasion there was an error log from `loki-stack-promtail-w4jx6`:

```
level=error ts=2019-10-12T07:37:24.50926847Z caller=filetarget.go:260 msg=" failed to remove directory from watcher" error="can't remove non-existent inotify watch for: /var/log/pods/default_cluster-status-1570865640-8qwvr_338438ec-37cb-4ccb-966a-b86dff2b87a6/cluster-status"
```
But on the other occasions where this happened no logs other than that the `cluster-status` was "Adding target" and "Removing target". `cluster-status` is a cronjob that runs every minute.

**objects in namespace loki-stack**
```
➜  ~ kubectl -n loki-stack get all
NAME                            READY   STATUS    RESTARTS   AGE
pod/loki-stack-0                1/1     Running   0          13h
pod/loki-stack-promtail-45tdl   1/1     Running   0          13h
pod/loki-stack-promtail-t2hsh   1/1     Running   0          34h
pod/loki-stack-promtail-w4jx6   1/1     Running   0          34h

NAME                          TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
service/loki-stack            ClusterIP   10.245.135.120   <none>        3100/TCP   7d20h
service/loki-stack-headless   ClusterIP   None             <none>        3100/TCP   7d20h

NAME                                 DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/loki-stack-promtail   3         3         3       3            3           <none>          7d20h

NAME                          READY   AGE
statefulset.apps/loki-stack   1/1     7d20h
```

Any ideas where further to look or gather logs?

Thanks

**Comment by slim-bean** [comment]
@wuestkamp did this issue still exist for you? Have you tried newer versions of Loki? This was quite some time ago and we aren't exactly sure how to proceed, let us know if there is more information or if the issue still exists. Thanks!

**Comment by wuestkamp** [comment]
I think it went away, not sure why though :)

**Comment by Alxander64** [comment]
I still see the same error log mentioned in the original post. Also running the Helm chart on Kubernetes (AWS EKS).

**Comment by dmerrick** [comment]
I also see the same error. This issue might be the same as https://github.com/grafana/loki/issues/3874?
