### ISSUE TITLE
Time series for log volume

### ISSUE THREAD

**Issue by davkal** [grafana/loki#115]
The UI shows a graph of the log messages distribution over the selected time range broken down by log level. Currently this is being produced ad-hoc based on the returned rows (1000). Would be great to have this as timeseries that exist independently, but can still be broken down by log level.

**Comment by negbie** [comment]
With this https://github.com/grafana/loki/commit/7bcdf0e0b1ae136cc2ffebf72dc9a9997552549f
it could be broken down by line count.

**Comment by roidelapluie** [comment]
This would be really nice (#361). Currently it is like lying to the users.
