### ISSUE TITLE
can you use kubernetes discovery when docker using journald?

### ISSUE THREAD

**Issue by cameronbraid** [grafana/loki#1151]
I am running openshift which uses journald for logging and therefore /var/log/pods/* is empty

How would I go about configuring promtail to use kubernetes discovery with journald ?

**Comment by cameronbraid** [comment]
I managed to setup some relabel configs to at least make the extracted log events usable

```
      - source_labels: ['__journal_container_name']
        regex: ^([^_]+)_([^\._]+)(\.([^_]+))?_([^_]+)_([^_]+)_[^_]+_[^_]+$
        target_label: 'namespace'
        replacement: '${6}'

      - source_labels: ['__journal_container_name']
        regex: ^([^_]+)_([^\._]+)(\.([^_]+))?_([^_]+)_([^_]+)_[^_]+_[^_]+$
        target_label: 'instance'
        replacement: '${5}'

      - source_labels: ['__journal_container_name']
        regex: ^([^_]+)_([^\._]+)(\.([^_]+))?_([^_]+)_([^_]+)_[^_]+_[^_]+$
        target_label: 'container_name'
        replacement: '${2}'

```

they are based off the regular expression from fluentd https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/blob/master/README.md

```
^(?<name_prefix>[^_]+)_(?<container_name>[^\._]+)(\.(?<container_hash>[^_]+))?_(?<pod_name>[^_]+)_(?<namespace>[^_]+)_[^_]+_[^_]+$
```

**Comment by cyriltovena** [comment]
Our current kubernetes service discovery works only with files. But from what I can see you already have some source label that have what you need.

I think you have the right solution here, though we need to document this, feel free to send us a PR if you have some time to give back.

**Comment by slim-bean** [comment]
It seems like you were able to get this to work? Given the age of this issue I'm going to close it but please feel free to comment if there is more we can do.

I also believe efforts are underway to improve the promtail/openshift experience within RedHat as well so maybe this will be less of an issue in the future.
