### ISSUE TITLE
failed to create target - too many open files, ulimit -n 1048576

### ISSUE THREAD

**Issue by cameronbraid** [grafana/loki#1153]
I am getting errors in promtail :
```
level=error ts=2019-10-14T16:21:22.143910463Z caller=filetargetmanager.go:261 msg="Failed to create target" key="{container_name=\"sentinel\", deployment=\"redis-ha-3\", deploymentconfig=\"redis-ha\", instance=\"redis-ha-3-vmxdz\", job=\"project/redis-ha\", name=\"redis-ha\", namespace=\"project\", redis_sentinel=\"true\"}" error="filetarget.fsnotify.NewWatcher: too many open files"
```

on the host

```
ulimit -n
1024000
```

in the promtail container

```
root@promtail-22r6h:/# ulimit -n
1048576
```

Any hints on how to solve this ?

**Comment by cyriltovena** [comment]
Hello @cameronbraid do you have more details ?

Is this happening for every nodes ? or only certain nodes ? Can you check which files are open ?

**Comment by cameronbraid** [comment]
Sure, its a openshift cluster v3.9, docker log driver is json-file

There are 3 nodes that are working fine, and three that have this issue.

On one of the problematic nodes the file counts are :

```
>find /var/log/pods | wc -l
200
> find /var/lib/docker/containers | wc -l
2304
> sysctl fs.file-max
fs.file-max = 13059628
> sysctl fs.file-nr
fs.file-nr = 62688      0       13059628
```

**Comment by cyriltovena** [comment]
I think there is something on those nodes already using a lot of file descriptors, and this is not promtail.

You should check what that is, if this is fine for you, then the only options is busting up that limit.

**Comment by cameronbraid** [comment]
Yes, there are lots of file descriptors used, that's not the case. as Nothing else is complaining about it.  Its only promtail.  

And you can see from the stats, 62688 open before launching promtail, with a max of 13059628, leaving room for 12996940 more. The targets that promtail creates are all in /var/log/pods and /var/lib/docker/containers which are a total of 2500.

**Comment by cyriltovena** [comment]
Could you check ulimit from within the promtail container ? It should see the same ulimit than the host but it doesn’t seems true here

**Comment by cameronbraid** [comment]
in promtail container
```
# ulimit -n
1048576
```

**Comment by cameronbraid** [comment]
Also in the container :
```
> cat /proc/sys/fs/file-nr
85248   0       13059968
```

**Comment by cyriltovena** [comment]
Have you tried to check the /service-discovery and /targets page of promtail to see how many targets you have ? I’m wondering if this is a promtail or openshift issue.

**Comment by cyriltovena** [comment]
Can you also activate debug log in promtail and share that with us ? we will see path and targets found.

**Comment by cyriltovena** [comment]
You can also check the metric exposed promtail_files_active_total.

**Comment by cyriltovena** [comment]
One last thing if your log files are rotating but old logs files are not deleted over time, promtail will keep watching them. This could easily build up, any chance you have ton of log file not used ?

**Comment by cyriltovena** [comment]
https://access.redhat.com/solutions/2334181 Do hou have a max file limit for docker ?

**Comment by cameronbraid** [comment]
/metrics :
promtail_files_active_total 0.0
promtail_targets_active_total 99.0

/service-discovery :
kubernetes-pods-app (17/794 active targets)
kubernetes-pods-direct-controllers (42/819 active targets)
kubernetes-pods-indirect-controller (0/777 active targets)
kubernetes-pods-name (40/817 active targets)
kubernetes-pods-static (0/777 active targets)

/targets :
kubernetes-pods-app (0/17 ready) 
kubernetes-pods-direct-controllers (0/42 ready) 
kubernetes-pods-indirect-controller (0/0 ready) 
kubernetes-pods-name (0/40 ready) 
kubernetes-pods-static (0/0 ready)

re https://github.com/grafana/loki/issues/1153#issuecomment-542953062
I don't think this is the case as :
find /var/lib/docker/containers -name "*.log" | wc -l
185

**Comment by cameronbraid** [comment]
[debug-log.txt](https://github.com/grafana/loki/files/3737010/debug-log.txt)

**Comment by cameronbraid** [comment]
/metrics :
promtail_files_active_total 0.0
promtail_targets_active_total 99.0

/service-discovery :
kubernetes-pods-app (17/794 active targets)
kubernetes-pods-direct-controllers (42/819 active targets)
kubernetes-pods-indirect-controller (0/777 active targets)
kubernetes-pods-name (40/817 active targets)
kubernetes-pods-static (0/777 active targets)

/targets :
kubernetes-pods-app (0/17 ready) 
kubernetes-pods-direct-controllers (0/42 ready) 
kubernetes-pods-indirect-controller (0/0 ready) 
kubernetes-pods-name (0/40 ready) 
kubernetes-pods-static (0/0 ready)

find /var/lib/docker/containers -name "*.log" | wc -l
185

**Comment by cameronbraid** [comment]
Also, by default openshift 3.9 uses journald for logging, however I changed it to use json-file and enabled log rotation as well

**Comment by cyriltovena** [comment]
From the log file you are not tailing a single file, but still creating a new watcher failed.

Are those master nodes or anything special ?

**Comment by cameronbraid** [comment]
The node I am using is compute,infra and master, though I am not sure how that would impact anything ?

**Comment by cyriltovena** [comment]
Have you tried this on the host ? 
```
sysctl -a | grep inotify
lsof | grep inotify | wc -l
```

**Comment by cameronbraid** [comment]
```
fs.inotify.max_queued_events = 16384
fs.inotify.max_user_instances = 128
fs.inotify.max_user_watches = 65536
```

```
lsof | grep inotify | wc -l
19547
```

I upped the inotify limits and am no longer getting that error.. however I still have issues.. will open a separate ticket for that.

Thanks heaps for your help.

**Comment by cyriltovena** [comment]
you should take a look at who is using inotify, if an application is leaking could be interesting to know, I don't think its promtail since from the logs it was not even able to go that far.

**Comment by miklezzzz** [comment]
@cyriltovena Hi, I observe something similar to TS.
Before promtail is running:
```
lsof | grep inotify | wc -l
490
```
After:
```
lsof | grep inotify | grep promtail | wc -l
15429
```
I wouldn't notice a problem, but **kubectl logs** to pods on a certain node started to fail with too many open files.

Is it by design?

**Comment by miklezzzz** [comment]
at the same time, there are not more than 160+ log files to tail.
```
cat /run/promtail/positions.yaml | wc -l 
165
```
some of them are marked with "?", though...

**Comment by miklezzzz** [comment]
i've updated /proc/sys/fs/inotify/max_user_instances to 512 instead of default 128 and problem's gone

**Comment by roidelapluie** [comment]
good catch .. wondering if loki should check this

**Comment by adamcharnock** [comment]
I found this command helpful to get a list inotify counts by process. Note that is important to run it as root (via `sudo` here) otherwise you'll only get a partial count:

```
sudo lsof | grep inotify | tr -s ' ' | cut -f1,2 -d" " | sort | uniq -c | sort
```

Example tail of the output:

```
     39 container 38751
     39 container 455668
     51 cilium-ag 3306
     60 container 4848
     78 kubelet 455304
     90 kube-apis 8649
     92 container 454706
    312 promtail 4314
```

**Comment by younsl** [comment]
Same as [miklezzzz's solution](https://github.com/grafana/loki/issues/1153#issuecomment-564991396). On a target instance with promtail v2.9.8 installed, increase the `fs.inotify.max_user_instances` kernel parameter from `128` (default) to `1024` using the following procedure, then `filetarget.fsnotify.NewWatcher: too many open files` errors have disappeared.

```bash
# Environment: promtail 2.9.8 on amd64 EC2
echo "fs.inotify.max_user_instances = 1024" | sudo tee -a /etc/sysctl.conf
sudo sysctl -p
sysctl fs.inotify
```

**Comment by StianOvrevage** [comment]
It seems it's possible to use the suggested pattern in the helm chart values to spin up a init container and change the `max_user_instances` directly:

```
initContainer: []
  # # -- Specifies whether the init container for setting inotify max user instances is to be enabled
  # - name: init
  #   # -- Docker registry, image and tag for the init container image
  #   image: docker.io/busybox:1.33
  #   # -- Docker image pull policy for the init container image
  #   imagePullPolicy: IfNotPresent
  #   # -- The inotify max user instances to configure
  #   command:
  #     - sh
  #     - -c
  #     - sysctl -w fs.inotify.max_user_instances=128
  #   securityContext:
  #     privileged: true
```

https://github.com/grafana/helm-charts/blob/promtail-6.16.6/charts/promtail/values.yaml#L82

**Comment by rtomik** [comment]
@StianOvrevage thanks it solved the issue for me
