### ISSUE TITLE
Docs feedback: /docs/sources/send-data/fluentbit/_index.md

### ISSUE THREAD

**Issue by PeterStolz** [grafana/loki#11575]
Under the [Kubernetes](https://grafana.com/docs/loki/latest/send-data/fluentbit/#kubernetes) section the grafana fluent-bit helm chart is referenced, but it has been deprecated. I would suggest adding instruction/references to the official fluent bit helm installation.

**Comment by JStickler** [comment]
It appears that the Grafana Fluent Bit Helm chart was deprecated quite a while ago (May 2021).  What's not clear is what modifications need to be made to the Fluent Bit Helm chart to make it work with Loki, as after comparing the two charts, there are significant differences between the two.  @PeterStolz  do you use Fluent Bit and do you have any insights into if we also need to document how to update the chart?

**Comment by PeterStolz** [comment]
Hi,
we are using the official fluent-bit helm chart with the grafana-loki plugin. The only changes needed to the values.yaml in order to use the fluent-bit plugin are:
```yaml
image: 
  repository: grafana/fluent-bit-plugin-loki
  tag: main-e2ed1c0

args:
  - "-e"
  - "/fluent-bit/bin/out_grafana_loki.so"
  - --workdir=/fluent-bit/etc
  - --config=/fluent-bit/etc/conf/fluent-bit.conf
 ```

However I want to note that there is a problem with the more recent builds which appears to be a problem with the stack interaction of the plugin written in go and fluent-bit written in C. I therefore binary searched through the images and found the one I tagged to be among the most recent working versions.
This has also been reported in the [grafana forum](https://community.grafana.com/t/grafana-loki-plugin-for-fluent-bit-core-dumped/110488).  
Once/If that issue is resolved we could update the tag to a more recent version. If it bothers you that we do not use a version tag here I can also hop to the nearest version tag, although the versions have more to do with core grafana than with the loki plugin.

We could therefore update the docs to include this command
```bash
helm install fluent-bit fluent/fluent-bit   --set image.repository=grafana/fluent-bit-plugin-loki \
  --set image.tag=main-e2ed1c0 \
  --set args[0]="-e" \
  --set args[1]="/fluent-bit/bin/out_grafana_loki.so" \
  --set args[2]="--workdir=/fluent-bit/etc" \
  --set args[3]="--config=/fluent-bit/etc/conf/fluent-bit.conf"
```

In production we use fluent-bit chart version 0.40.0 which is the most recent one. If you want we could theoretically pin that, though in my opinion it is stable enough.

Let me know what you think and I would be happy to create a PR for it.

**Comment by JStickler** [comment]
>Let me know what you think and I would be happy to create a PR for it.

That would be awesome. We don't have a whole lot of experience with Fluent-bit on the Grafana team, it's mostly a community supported client.  I'll defer to what you think would be most useful as far as updating the docs.  Please tag me on the PR and I'll make sure it gets reviewed.
