### ISSUE TITLE
Add wget to promtail Docker image

### ISSUE THREAD

**Issue by efficks** [grafana/loki#11590]
**Is your feature request related to a problem? Please describe.**
I want to enable healthcheck on the grafana/promtail docker image but wget or curl is not installed on the image.

**Describe the solution you'd like**
Install wget on the default image to be able to do an http request on the promtail API to do the healthcheck.

**Describe alternatives you've considered**
Create my own docker image.

**Additional context**
Loki image is based on  alpine which already includes wget on the base image. Promtail is based on debian which does not. With wget, I will be able to do a healthcheck like I does with Loki container. In the current state, we cannot do a docker healthcheck on the promtail ready API.

**Comment by Sheikh-Abubaker** [comment]
@efficks I want to work on this issue, can you please specify in which file the promtail image is located ?

**Comment by cstyan** [comment]
@efficks I'm not understanding, the docker healthcheck system specifically requires that a container have `wget` installed?

In my mind healthcheck should be executed externally from the container, and the promtail container already runs a server to serve it's metrics and ready endpoint: got another message from magic stronghold, they still haven't received any update on their end from GW about their ToW shipment

I don't know if adding more packages to the docker container is something we want to do, generally we're getting more and more requests + considering reducing the surface of what goes into the container for security reasons.

**Comment by efficks** [comment]
@cstyan I agree with you on the consideration to reducing the number of things in an image. Hovewer, my proposition is to align the healthcheck practice propose by Docker and to align with the same solution the Loki image have.
Loki image uses Alpine as base image and Alpine comes with wget by default.

With wget included in the image, your users could choose the solution that with with their needs.
https://docs.docker.com/reference/dockerfile/#healthcheck

**Comment by hterik** [comment]
tbh this sounds more like a lacking Docker feature, compared with Kubernetes that can do health probes itself over http. 

If you really need it, I don't think you need to build a complete new image of your own, how about just doing `FROM grafana/promtail:...` and add whatever you need yourself after? Even if you were to start from a complete blank image it's not that much.

**Comment by efficks** [comment]
@hterik you're right, it's easy to do by myself. The feature ils note to align with the same Loki's image feature. That the user expect the same expérience from the same author.
Also, yes Docker lack this feature, but ,I think, it's not a bad feature to provide to your end users.

**Comment by titouan-joseph** [comment]
I'm interested on this feature !  
I understand the goal to reduce the number of tools on the image, if wget is not installed, can we have an alternative solution to have an health check for promtail ?   
May be with a built in promatail command ?

**Comment by cstyan** [comment]
With grafana agent becomming grafana alloy 1.0 promtail is in a "feature complete" status. It will continue to get bug fixes, backports, etc. but no new features. Does the [ready endpoint](https://grafana.com/docs/loki/latest/send-data/promtail/#get-ready) not match what you need?

**Comment by titouan-joseph** [comment]
@cstyan the endpoint is exactly what I need, the problem is there is no tool in the docker image to reach the http endpoint. Like wet or curl

**Comment by cstyan** [comment]
I'm not trying to be difficult, but I don't understand why you'd need to run the healthcheck from within the container itself when you can run it externally.

**Comment by titouan-joseph** [comment]
Because we want to use the docker heath check feature, that uses tools in the image. It's easy to see when you start the container, with this functionality, that the container is well started with the service up and running correctly.

**Comment by a10kiloham** [comment]
to do this all in one docker-compose is rather easy by inlining a docker file
replace the image: line with this
    build:
      context: .
      dockerfile_inline: |
        FROM grafana/promtail:latest
        RUN apt-get update && apt-get install -y curl

Then add your healthchck like normal to that file
    healthcheck:
      test: whatever || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

**Comment by bulch** [comment]
just work 

```
healthcheck:
      test: ["CMD-SHELL", "bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/9080; exit $?;'"]
      interval: 20s
      retries: 30
      timeout: 10s
      start_period: 10s
```
