### ISSUE TITLE
logcli on OSX does not respect VPN DNS

### ISSUE THREAD

**Issue by brokenjacobs** [grafana/loki#1161]
**Describe the bug**
When connected over a VPN, on OSX, the logcli binary doesn't use the scutil resolvers configured by the vpn, instead it tries to parse /etc/resolv.conf and use the native go resolver. This is due to the way the go resolver system works on OSX.

**To Reproduce**
Connect with vpn.
use logcli
observe host not found error

**Expected behavior**
logcli connected to the appropriate server and working

Let's just cut to the resolution here, many go cli tools have suffered the same problem, including kubectl. The solution is to compile cgo support when building for darwin/osx. Here are the relevant kubectl issues:
https://github.com/kubernetes/kubernetes/issues/23130
https://github.com/kubernetes/release/issues/469
and some linked background material:
https://inconshreveable.com/04-30-2014/cross-compiling-golang-programs-with-native-libraries/

**Comment by rfratto** [comment]
Reopening since the PR to fix is also marked keepalive.

**Comment by mattmendick** [comment]
Does the [dns-heaven](https://github.com/greenboxal/dns-heaven) tool work to workaround this? Not a good solution for sure, but something that might help ease the pain.

**Comment by brokenjacobs** [comment]
yes

**Comment by slim-bean** [comment]
I'm going to close this issue (and the associated PR) with the suggested `dns-heaven` workaround above.  I'm not sure if this is the best solution but we haven't really heard other complaints about this and I don't want to leave it idle forever.

Please feel free to add comments or thumbs up this issue if the workaround doesn't work for you or you have other ideas, thanks!
