### ISSUE TITLE
Loki Components permission issue on /tmp/ file system deployed by operator 

### ISSUE THREAD

**Issue by mariodietner** [grafana/loki#11631]
**Describe the bug**

When deploying the operator by following isntructions with the make command and afterwards depoloying the lokistack_dev.yaml from the operator/hack path, the components Compactor, Index-Gateway, Ingester and Ruler face all the same issue with ownership permissions on /tmp/ folder. 

Owner of the entire /tmp/ folder is Root. It is neccesary to hack into the pod (i mean hack, because the pod does not run: stop operator, change the args of the statefulset and set permissions to root user, reset the statefulset, sh into the pod and fix permissions manually)

I would suggest to fix this with adding following command to cmd/loki/Dockerfile:

RUN chown -R loki:loki /tmp/

I would create a PR for it, but i want to be sure i am not missing anything in my steps of deployment.

Affected version/branches:

main
release/v2.9.3

**To Reproduce**

1. Build and Started Operator
2. Deployed lokistack
3. See status of compontents

**Expected behavior**

I would excepct the permissions of the /tmp/ folder to be set to user loki and group loki.

**Environment:**
 - Infrastructure: Azure AKS
 - Deployment tool: make build command and kubectl

**Screenshots, Promtail config, or terminal output**

on all components:

msg="error running loki" err="mkdir /tmp/loki/tsdb-index: permission denied

on ruler component:

msg="unable to map rule files" user=..data err="mkdir /tmp/loki/..data: permission denied"

**Comment by periklis** [comment]
@mariodietner Thanks for reaching out for help here. If you are using the `lokstack_dev.yaml` as is today, I am curious what the storageClass `standard` is mapped on your AKS cluster.

**Comment by mariodietner** [comment]
@periklis thanks for your reply. I have recreated standard from "default" - which was in the cluster as default storage. Definition is as follows:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  resourceVersion: '442'
  creationTimestamp: '2022-08-30T15:26:11Z'
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: 'true'
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
  managedFields:
    - manager: kubectl-create
      operation: Update
      apiVersion: storage.k8s.io/v1
      time: '2022-08-30T15:26:11Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:allowVolumeExpansion: {}
        f:metadata:
          f:annotations:
            .: {}
            f:storageclass.kubernetes.io/is-default-class: {}
          f:labels:
            .: {}
            f:addonmanager.kubernetes.io/mode: {}
            f:kubernetes.io/cluster-service: {}
        f:parameters:
          .: {}
          f:skuname: {}
        f:provisioner: {}
        f:reclaimPolicy: {}
        f:volumeBindingMode: {}
  selfLink: /apis/storage.k8s.io/v1/storageclasses/default
provisioner: disk.csi.azure.com
parameters:
  skuname: StandardSSD_LRS
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
```

**Comment by periklis** [comment]
@mariodietner Sorry for the late reply here, I don't see any particular issue with the storage class provided TBH. I have used a similar class on non-AKS installations on Azure (mostly OpenShift) w/o an issue. Since observing this for the first time on Loki, I believe it might be an AKS pod policy issue on what a pod can mount or not. I don't believe we can workaround this w/o your investigation on AKS sight. If you figure out anything new, please feel free to reopen this issue.

**Comment by revlver** [comment]
@mariodietner were you able to fix this , I am facing exact same issue in AKS
