### ISSUE TITLE
How to configure ruler alertmanager_url when deploying the ruler with operator

### ISSUE THREAD

**Issue by mariodietner** [grafana/loki#11632]
ver: main branch

I am deploying the ruler by using the following lokistack_dev.yaml configuration:

spec:
  rules:
    enabled: true
    selector:
      matchLabels: 
        app.kubernetes.io/name: loki-alerts

The ruler picks the AlertRules CRDs and evaluates the rules successfully. 

What i see in the config of etc/loki/local-config.yaml is the alertmanager url as follows:

ruler:
  alertmanager_url: http://localhost:9093

which is part of the official loki build image, used by the operator. 

My question is, how can i rewrite this configuration in my current setup, without the need to build my own loki image ?

**Comment by periklis** [comment]
@mariodietner Good to hear more people being interested and using the Loki Operator. The resource you are looking for to configure the Ruler is a companion resource to LokiStack namely the `RulerConfig`. Have a look on the RulerConfigSpec here: https://loki-operator.dev/docs/api.md/#loki-grafana-com-v1-RulerConfigSpec

We don't have good examples in the repo, but I would be glad to help you contribute some if you are interested.

**Comment by mariodietner** [comment]
@periklis thank you for your reply. I have used the RulerConfig configuration, but i think i am missing something here... there seems to be no effect. Even the etc/loki/ local config, config/config.yaml and runtime config show no difference. Is there any specific label annotation/fitler? I am using the default alertmanager from prometheus-community/kube-prometheus-stack 

Here my configuration attemp:

apiVersion: loki.grafana.com/v1
kind: RulerConfig
metadata:
  name: rulerconfig-dev
spec:
  alertmanager:
    endpoints:
      - http://promgraf-kube-prometheus-s-alertmanager.default:9093
    discovery:
      enableSRV: true

**Comment by shev06** [comment]
Unable to apply a rulerconfig as well from the operator. Seems to have no effect.

**Comment by mariodietner** [comment]
I have found the Problem. The impleemntation of ruler_config_disvocery.go is trying to find lokistack kubernetes resource with the name of rulerconfig CRD instead of the name of lokistack CRD, which results in not found error. Looks like a design problem. I will try to create a PR. 

Workaround: LokiStack name and RulerConfig name must be equal for the time being.

**Comment by periklis** [comment]
Sorry for the late reply but the rulerconfig name being equal set to the lokistack name is a feature and not a design flaw. Looking back in history when we started designing the LokiStack CRD we figured out very fast that the more we strive to keep it simple and away from Loki config bloatness/mightiness the more we need to offload things to optional resources. The design cut was made to offload all the ruler configuration into the optional `RulerConfig` CRD. However we wanted to make it easy for users to establish the required 1-to-1 relationship between `LokiStack` and `RulerConfig`. Therefore the requirement using the same name was born.

Albeit the `RulerConfig` but itself stems from a time where the AlertManager as well as the RemoteWrite config it encloses were global for all Loki tenants. Nowadays Loki supports per-tenant alertmanager and remote write configs which is a feature still missing in the `RulerConfig` and probably worth thinking if we need a `v2` API where breaking changes might be considered. Meanwhile the interest so far has been very low or unknown from the community and we keep with what we have.

Last but not least the `loki.grafana.com/rulerConfigDiscoveredAt` annotation is an internal operator detail that should not bother users except when the inspect the `LokiStack` custom resource. It is not meant to be used and set by the users. In more detail the creation of a same-named `RulerConfig` is just signaled into the `LokiStack` controller reconciliation loop to eliminate the need of having concurrent access on the LokiStack from two independent controllers and thus go routines. You will find similar annotations for rules discovered or certs rotated.

**Comment by periklis** [comment]
As per explained above this is not a particular issue on the operator code base rather a not-well documented detail. If you want to contribute on our docs that will be rendered on https://loki-operator.dev feel free to ping with a PR. Glad to get help in this matter any time & anyhow.

**Comment by mariodietner** [comment]
Thank you for the explanation. I did not had any time working on that topic further, since the naming convention worked. 

To be honest i would expect the RulerConfig to be part of LokiStack under the same configuration area. That would make clear about the 1:1 relation.
