### ISSUE TITLE
Unknown error during query transaction. Please check JS console logs.

### ISSUE THREAD

**Issue by alucianus** [grafana/loki#1164]
Hello everyone, I use Loki 0.3.0  locally...  when I run  one week log query, or more it returns an error
`Unknown error during query transaction. Please check JS console logs.`
My database is Boltdb actually with 3G used disk, my server has 4vcpu, 4gb Ram  with few hosts collected
Anyone did have the same problem? 
My syslog :
`level=warn ts=2019-10-15T20:01:05.240017374Z caller=logging.go:49 traceID=6158441f9e7adf15 msg="GET /api/prom/query?direction=BACKWARD&limit=10000&regexp=&query=%7Bjob%3D%22proxy%22%7D%7C%3D%22172.16.x.x%22%7C%3D%22google%22&start=1569207600000000000&end=1569639599000000000&refId=A (500) 38.762693392s Response: \"write tcp 192.168.x.x:3100->192.168.x.x:48906: *i/o timeout\* \n\" ws: false; Accept: application/json, text/plain, */*; Accept-Encoding: gzip, deflate, br; Accept-Language: en-US,en;q=0.5; Cache-Control: max-age=0; User-Agent: Grafana/6.4.1; X-Forwarded-For: 172.16.x.x, 172.16.x.x; X-Grafana-Org-Id: 1; "`

It seems like a timeout issue, can I solved it? 

My query :
![image](https://user-images.githubusercontent.com/21344575/66935196-0bd38580-f012-11e9-9c39-c4dd11a99b57.png)

Through logcli same query:

`# logcli query '{job="proxy"}|="172.16.x.x"|="Status:403"' --limit 2000 --from 2019-09-20T00:00:10-03:00 --to 2019-09-27T15:11:10-03:00
`

2019/10/16 12:46:35 http://log.datacenter.local:3100/api/prom/query?query=%7Bjob%3D%22proxy%22%7D%7C%3D%22172.16.x.x%22%7C%3D%22Status%3A403%22&limit=2000&start=1568948410000000000&end=1569607870000000000&direction=BACKWARD&regexp=
2019/10/16 12:47:25 Query failed: Get http://log.datacenter.local:3100/api/prom/query?query=%7Bjob%3D%22proxy%22%7D%7C%3D%22172.16.x.x%22%7C%3D%22Status%3A403%22&limit=2000&start=1568948410000000000&end=1569607870000000000&direction=BACKWARD&regexp=: EOF

**Comment by cyriltovena** [comment]
Hello @alucianus ,

By default Grafana will timeout within 30s, the query you are running probably needs more than 30sec.

One thing you can do right now is update this timeout: https://grafana.com/docs/installation/configuration/#timeout

Currently Loki queries are run within a single go routine so using a single CPU, we're currently working to improve that.

Although I didn't catch correctly if you are running in into issue with logcli, I don't think this has some timeout so you shouldn't experience any problem.

Let me know.

**Comment by cyriltovena** [comment]
You can also activate debug logs, it should output numbers about the size of your query (indexes and chunks involved). Don't hesitate to share that with us to see if there is anything abnormal.

**Comment by alucianus** [comment]
Hi @cyriltovena thanks again...
I Ran the same comand and Logcli reports  EOF error as well... so we eliminate grafana side issue Right? 
you're right I run my loki with default parameters I start it through systemd 

 ```
service loki status
 loki.service - Grafana-loki Server
   Loaded: loaded (/etc/systemd/system/loki.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2019-10-16 11:34:08 -03; 20h ago
 Main PID: 34995 (loki)
    Tasks: 74 (limit: 4671)
   Memory: 447.6M
   CGroup: /system.slice/loki.service
           └─34995 /usr/local/bin/loki -config.file=/files/loki.yaml
```

So I saw a lot of option to configure I will try change it.
soon I send you the results
thanks

**Comment by cyriltovena** [comment]
Yep the EOF from the logcli sounds like a bug, never seen this before.  Uses this flag`-log.level=debug` and share the output with us.

**Comment by alucianus** [comment]
I Tried  ` -querier.query_timeout` option  don't work

[debug.txt](https://github.com/grafana/loki/files/3739288/debug.txt)

**Comment by cyriltovena** [comment]
Was this log using logcli ? I can see that it timeout after 47seconds. If you want to increate Grafana timeout you have to use Grafana config file.

**Comment by cyriltovena** [comment]
`-querier.query_timeout=5m` should also help.

**Comment by alucianus** [comment]
YEs...through logcli ...

loki side increased to 10 min
```
Active: active (running) since Thu 2019-10-17 10:07:07 -03; 6s ago
 Main PID: 68096 (loki)
    Tasks: 13 (limit: 4671)
   Memory: 17.9M
   CGroup: /system.slice/loki.service
           └─68096 /usr/local/bin/loki -config.file=/files/loki.yaml -querier.query_timeout=10m
```
Grafana side Increase to  600s 


Not  work yet!

**Comment by cyriltovena** [comment]
do you still get the same error or does it takes now 10 min and then fails ?

**Comment by alucianus** [comment]
Yes  both sides same query.. same issue
splitting in two not working too...

**Comment by alucianus** [comment]
Good News @cyriltovena I got it
I was already giving up, I changed three parameters and works for me

`/usr/local/bin/loki -config.file=/files/loki.yaml -querier.query_timeout=10m -server.http-read-timeout=10m -server.http-write-timeout=10m
`
After this I was able to make complex queries in a period of a month in both cases grafana and logcli 
runs smoothly hehe !
Thank you so much!
best regards

**Comment by davkal** [comment]
FYI https://github.com/grafana/grafana/pull/19910 makes sure Loki connection errors are passed through to the query row.

**Comment by CrashLaker** [comment]
Hi al,

Although @alucianus flags has helped me execute some long running queries > 7days there's still some timout inbetween when i'm to increase this range e.g. 30days.

Still don't know if it's on grafana or loki's end.

![image](https://user-images.githubusercontent.com/4432491/118278638-94d9c980-b4a0-11eb-8d15-cbd01983499b.png)

`grafana.ini`
```
[dataproxy]
timeout = 600
```

`loki-config.yaml`
```
server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  http_server_read_timeout: 10m
  http_server_write_timeout: 10m

querier:
  query_timeout: 10m
```

can anyone help me?

**Comment by CrashLaker** [comment]
got it to work.

there was one more config missing in loki:
```
querier:
  query_timeout: 10m
  engine:
    timeout: 10m
```

it ran in 7.5mins. but at least it completed
![image](https://user-images.githubusercontent.com/4432491/118292745-539ce600-b4af-11eb-9de1-eb204d1dd2dd.png)

also the storage footprint is huge. 94GB congrats Loki team!
![image](https://user-images.githubusercontent.com/4432491/118292542-1df7fd00-b4af-11eb-9bd1-f8602fcbb930.png)
