### ISSUE TITLE
loki-stack sets a name for prometheus; breaks multiple helm releases

### ISSUE THREAD

**Issue by rally25rs** [grafana/loki#1169]
**Describe the bug**
The loki-stack values.yaml sets a hard-coded name for `prometheus`:
```
prometheus:
  server:
    fullnameOverride: prometheus-server
```
This overrides prometheus' default behavior of incorporating the `{{.Release.Name}}` into the service name.

Since the release name is no longer included, this breaks Helm installs if you try to have more than one release, since `prometheus-server` will already exist on the second helm release.

**To Reproduce**

1. set up a helm chart that uses loki-stack as a requirement
2. install it once with `helm install release-one`
3. attempt to make a second release `helm install release-two`

This will result in
```
Error: release release-two failed: clusterroles.rbac.authorization.k8s.io "prometheus-server" already exists
```

**Expected behavior**
I don't see why loki-stack overrides the prometheus name, since it isn't referenced anywhere else in the helm charts.
I'm guessing this values.yml line should be removed:
https://github.com/grafana/loki/blob/master/production/helm/loki-stack/values.yaml#L21

When not overridden, I believe prometheus will incorporate the release name into it's server name on it's own.
https://github.com/helm/charts/blob/master/stable/prometheus/templates/_helpers.tpl#L79-L84

[The commit where this config was added](https://github.com/grafana/loki/pull/586/commits/c392ceba32c1cb591a361e3df3facc14f5f217ee) doesn't give much indication of _why_ the `fullnameOverride` was added 🤷‍♂ 

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
(see error message in bug description)

**Comment by cyriltovena** [comment]
Hey @rally25rs ,

I did this :), I'm sorry it causes trouble for you, the idea was that its not possible to get the actual value generated service name from another chart to use for the grafana datasource here:

https://github.com/cyriltovena/loki/blob/c392ceba32c1cb591a361e3df3facc14f5f217ee/production/helm/loki-stack/templates/datasources.yaml#L27

There is may be an easier way to fix this.

**Comment by rally25rs** [comment]
Ah I see. Yeah that makes sense. It's unfortunate that the prometheus chart doesn't `tpl` the value it gets, otherwise you could use `{{.Release.Name}}` in `values.yaml` to override the name.

I suppose another solution could be to copy/paste the name generation helper https://github.com/helm/charts/blob/master/stable/prometheus/templates/_helpers.tpl#L72-L87 up to `loki-stack`, then I believe `prometheus` and `loki-stack/templates/datasources.yaml` could both use the same implementation.
