### ISSUE TITLE
Invalid documentation about duration.

### ISSUE THREAD

**Issue by maxless** [grafana/loki#1170]
The documentation states:
```
<duration>: a duration matching the regular expression [0-9]+(ms|[smhdwy])
```

But when I try to set duration to "7d" and "14d", for example, I get this error message:
```
caller=main.go:48 msg="error loading config" filename=/etc/loki/local-config.yaml err="yaml: unmarshal errors:\n  line 38: cannot unmarshal !!str `7d` into time.Duration\n  line 55: cannot unmarshal !!str `14d` into time.Duration"
```

**Comment by cyriltovena** [comment]
Hello @maxless,

Which field are you try to update ?

**Comment by maxless** [comment]
limits_config.reject_old_samples_max_age
and
table_manager.retention_period

**Comment by cyriltovena** [comment]
@maxless we're using the duration format from golang: https://golang.org/pkg/time/#ParseDuration

Unfortunately `d` as in days is not supported 

> Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".

You can still express your settings in hours. `24h`

**Comment by maxless** [comment]
Then you need to fix the docs.

https://github.com/grafana/loki/tree/master/docs/configuration

```
<duration>: a duration matching the regular expression [0-9]+(ms|[smhdwy])
```

**Comment by cyriltovena** [comment]
Ho yes !
