### ISSUE TITLE
Docs feedback: /docs/sources/setup/install/helm/reference.md

### ISSUE THREAD

**Issue by micheljung** [grafana/loki#11729]
The docs are difficult to read as they're not responsive:

![image](https://github.com/grafana/loki/assets/1864183/a772f81f-4529-47f6-8bcd-367a7c53e624)

There is a lot of white space left and right while the content is cut off.

**Comment by JStickler** [comment]
@micheljung To view large tables in the docs, click the Expand Table button.
![ExpandTable](https://github.com/grafana/loki/assets/4106682/b9cf32b3-1007-468c-af00-61b7fc40476e)
