### ISSUE TITLE
Loki does not support do-block-storage (digitalocean) as storageClassName

### ISSUE THREAD

**Issue by raimon-segura** [grafana/loki#1190]
**Describe the bug**
Loki does not support do-block-storage (digitalocean) as storageClassName , it worked before using loki.persistence.existingClaim .

Seems that "do-block-storage" is not in the list of supported storageClassName's:
"aws, cassandra, inmemory, gcp, bigtable, bigtable-hashed"

That message comes from https://github.com/cortexproject/cortex/blob/master/pkg/chunk/storage/factory.go#L124 , but it has no recent changes.

**To Reproduce**
Install loki with heml without claim:
helm upgrade --install loki loki/loki-stack \\
    --set loki.persistence.enabled=true \\
    --set loki.persistence.storageClassName=do-block-storage \\
    --set loki.persistence.size=10Gi 

OR, with claim
helm upgrade --install loki loki/loki-stack \\
    --set loki.persistence.enabled=true \\
    --set loki.persistence.existingClaim=loki-do-pv-claim \\
    --kube-context $K8_CONTEXT \\
    --namespace logging    

**Expected behavior**
It should work with loki.persistence.storageClassName=do-block-storage  as before

**Environment:**
kubernetes & helm

**Screenshots, Promtail config, or terminal output**
level=info ts=2019-10-22T16:46:08.903033507Z caller=loki.go:125 msg=initialising module=server
level=info ts=2019-10-22T16:46:08.903177321Z caller=server.go:120 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2019-10-22T16:46:08.903372323Z caller=loki.go:125 msg=initialising module=overrides
level=info ts=2019-10-22T16:46:08.903384662Z caller=override.go:48 msg="per-tenant overides disabled"
level=info ts=2019-10-22T16:46:08.903393363Z caller=loki.go:125 msg=initialising module=table-manager
level=error ts=2019-10-22T16:46:08.903409534Z caller=main.go:71 msg="error initialising loki" err="error initialising module: table-manager: Unrecognized storage client , choose one of: aws, cassandra, inmemory, gcp, bigtable, bigtable-hashed"

Thanks!

**Comment by cyriltovena** [comment]
Can you share your full config ? Existing claim is a kubernetes config but I think there's something wrong with your Loki config.

**Comment by slim-bean** [comment]
I'm closing this issue as we are waiting for feedback, and it appears to be a config issue.
