### ISSUE TITLE
Use correct Kubernetes terminology throughout documentation

### ISSUE THREAD

**Issue by jdbaldry** [grafana/loki#11944]
For example, _Pod_ not _pod_ and _Deployment_ not _deployment_.

https://grafana.com/docs/writers-toolkit/write/style-guide/capitalization-punctuation/#kubernetes-objects

**Comment by edsoncelio** [comment]
Hi @jdbaldry,
Just to clarify, this issue is for this page in particular? https://grafana.com/docs/loki/latest/setup/install/helm/reference/

**Comment by jdbaldry** [comment]
I was thinking of the full documentation but going page by page might make the PRs more manageable.

The following output is a non-exhaustive list based upon the [`Grafana.Kuberenetes` Vale linting rule](https://github.com/grafana/writers-toolkit/blob/main/vale/Grafana/Kubernetes.yml).

It's non-exhaustive because to avoid false-positives, the rule checks for "Kubernetes deployment" and not just "deployment".

```
sources/send-data/fluentd/_index.md:209:238:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/send-data/promtail/logrotation/_index.md:17:146:Grafana.Kubernetes:Use '`kubelet`' instead of 'Kubelet'.
sources/send-data/promtail/logrotation/_index.md:50:563:Grafana.Kubernetes:Use '`kubelet`' instead of 'Kubelet'.
sources/send-data/promtail/logrotation/_index.md:92:204:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/send-data/promtail/logrotation/_index.md:146:20:Grafana.Kubernetes:Use '`kubelet`' instead of 'kubelet'.
sources/send-data/promtail/installation.md:53:26:Grafana.Kubernetes:Use 'DaemonSet' instead of 'daemonSet'.
sources/send-data/promtail/cloud/eks/_index.md:21:4:Grafana.Kubernetes:Use '`kubectl`' instead of 'kubectl'.
sources/send-data/promtail/cloud/eks/_index.md:30:85:Grafana.Kubernetes:Use 'DaemonSet' instead of 'daemonset'.
sources/send-data/promtail/cloud/eks/_index.md:142:13:Grafana.Kubernetes:Use '`kubelet`' instead of 'kubelet'.
sources/send-data/promtail/cloud/eks/_index.md:189:93:Grafana.Kubernetes:Use '`kubelet`' instead of 'Kubelet'.
sources/send-data/promtail/cloud/eks/_index.md:255:162:Grafana.Kubernetes:Use '`kubelet`' instead of 'kubelet'.
sources/send-data/promtail/_index.md:128:51:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/send-data/otel/_index.md:78:9:Grafana.Kubernetes:Use 'DaemonSet' instead of 'daemonset'.
sources/send-data/otel/_index.md:82:9:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/send-data/otel/_index.md:83:9:Grafana.Kubernetes:Use 'ReplicaSet' instead of 'replicaset'.
sources/send-data/otel/_index.md:84:9:Grafana.Kubernetes:Use 'StatefulSet' instead of 'statefulset'.
sources/send-data/promtail/scraping.md:78:53:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/send-data/promtail/scraping.md:105:42:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/send-data/promtail/scraping.md:107:35:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/send-data/promtail/scraping.md:112:53:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/send-data/promtail/scraping.md:113:75:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/send-data/promtail/scraping.md:505:35:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/send-data/k6/log-generation.md:99:3:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/configure/examples/query-frontend.md:157:55:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/alert/_index.md:363:565:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/setup/install/istio.md:18:21:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/setup/install/istio.md:26:172:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/setup/install/istio.md:26:195:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/send-data/promtail/configuration.md:1619:19:Grafana.Kubernetes:Use '`kubelet`' instead of 'Kubelet'.
sources/send-data/promtail/configuration.md:1666:55:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/send-data/promtail/configuration.md:1667:22:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/send-data/promtail/configuration.md:1668:22:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/send-data/promtail/configuration.md:1668:35:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/send-data/promtail/configuration.md:1669:22:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/send-data/promtail/configuration.md:1670:22:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/send-data/promtail/configuration.md:1671:22:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/send-data/promtail/configuration.md:1672:22:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/send-data/promtail/configuration.md:1678:22:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/send-data/promtail/configuration.md:1681:22:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/send-data/promtail/configuration.md:1682:22:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/send-data/promtail/configuration.md:1683:22:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/send-data/promtail/configuration.md:1684:22:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/send-data/promtail/configuration.md:1685:22:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/send-data/promtail/configuration.md:1691:13:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/send-data/promtail/configuration.md:1691:56:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/send-data/promtail/configuration.md:1708:31:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/setup/migrate/migrate-from-distributed/index.md:86:353:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/release-notes/v2-8.md:14:303:Grafana.Kubernetes:Use 'Kubernetes Deployment' instead of 'Kubernetes deployment'.
sources/operations/zone-ingesters.md:108:125:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/operations/troubleshooting.md:126:29:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/operations/troubleshooting.md:129:77:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/operations/troubleshooting.md:133:10:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/operations/troubleshooting.md:148:39:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/operations/troubleshooting.md:151:42:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/operations/troubleshooting.md:185:35:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/operations/troubleshooting.md:185:82:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/operations/troubleshooting.md:186:8:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/operations/troubleshooting.md:186:46:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/operations/troubleshooting.md:190:26:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/operations/troubleshooting.md:190:56:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/setup/upgrade/_index.md:439:50:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/setup/upgrade/_index.md:482:110:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/setup/upgrade/_index.md:485:57:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/operations/storage/wal.md:41:121:Grafana.Kubernetes:Use 'StatefulSet' instead of 'statefulset'.
sources/operations/storage/wal.md:51:115:Grafana.Kubernetes:Use 'StatefulSet' instead of 'statefulset'.
sources/operations/storage/wal.md:65:44:Grafana.Kubernetes:Use 'StatefulSet' instead of 'statefulset'.
sources/operations/storage/wal.md:86:170:Grafana.Kubernetes:Use 'StatefulSet' instead of 'statefulset'.
sources/operations/storage/wal.md:98:127:Grafana.Kubernetes:Use 'StatefulSet' instead of 'statefulset'.
sources/operations/storage/wal.md:98:176:Grafana.Kubernetes:Use 'StatefulSet' instead of 'statefulset'.
sources/operations/storage/wal.md:98:291:Grafana.Kubernetes:Use 'StatefulSet' instead of 'statefulset'.
sources/operations/storage/wal.md:104:49:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/operations/loki-canary/_index.md:292:37:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/setup/install/helm/reference.md:257:32:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/setup/install/helm/reference.md:275:45:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/setup/install/helm/reference.md:320:54:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/setup/install/helm/reference.md:2620:49:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/setup/install/helm/reference.md:3182:152:Grafana.Kubernetes:Use '`kubelet`' instead of 'kubelet'.
sources/setup/install/helm/reference.md:3218:100:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/setup/install/helm/reference.md:3470:42:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/setup/install/helm/reference.md:3515:51:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/setup/install/helm/reference.md:3902:58:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/setup/install/helm/reference.md:4046:51:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/setup/install/helm/reference.md:4082:60:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/setup/install/helm/reference.md:4761:32:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/setup/install/helm/reference.md:4779:43:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/setup/install/helm/reference.md:4824:52:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/community/design-documents/2020-02-Promtail-Push-API.md:63:81:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
sources/get-started/labels/structured-metadata.md:15:12:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
```

**Comment by edsoncelio** [comment]
> I was thinking of the full documentation but going page by page might make the PRs more manageable.
> 
> The following output is a non-exhaustive list based upon the [`Grafana.Kuberenetes` Vale linting rule](https://github.com/grafana/writers-toolkit/blob/main/vale/Grafana/Kubernetes.yml).
> 
> It's non-exhaustive because to avoid false-positives, the rule checks for "Kubernetes deployment" and not just "deployment".
> 
> ```
> sources/send-data/fluentd/_index.md:209:238:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/send-data/promtail/logrotation/_index.md:17:146:Grafana.Kubernetes:Use '`kubelet`' instead of 'Kubelet'.
> sources/send-data/promtail/logrotation/_index.md:50:563:Grafana.Kubernetes:Use '`kubelet`' instead of 'Kubelet'.
> sources/send-data/promtail/logrotation/_index.md:92:204:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/send-data/promtail/logrotation/_index.md:146:20:Grafana.Kubernetes:Use '`kubelet`' instead of 'kubelet'.
> sources/send-data/promtail/installation.md:53:26:Grafana.Kubernetes:Use 'DaemonSet' instead of 'daemonSet'.
> sources/send-data/promtail/cloud/eks/_index.md:21:4:Grafana.Kubernetes:Use '`kubectl`' instead of 'kubectl'.
> sources/send-data/promtail/cloud/eks/_index.md:30:85:Grafana.Kubernetes:Use 'DaemonSet' instead of 'daemonset'.
> sources/send-data/promtail/cloud/eks/_index.md:142:13:Grafana.Kubernetes:Use '`kubelet`' instead of 'kubelet'.
> sources/send-data/promtail/cloud/eks/_index.md:189:93:Grafana.Kubernetes:Use '`kubelet`' instead of 'Kubelet'.
> sources/send-data/promtail/cloud/eks/_index.md:255:162:Grafana.Kubernetes:Use '`kubelet`' instead of 'kubelet'.
> sources/send-data/promtail/_index.md:128:51:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/send-data/otel/_index.md:78:9:Grafana.Kubernetes:Use 'DaemonSet' instead of 'daemonset'.
> sources/send-data/otel/_index.md:82:9:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/send-data/otel/_index.md:83:9:Grafana.Kubernetes:Use 'ReplicaSet' instead of 'replicaset'.
> sources/send-data/otel/_index.md:84:9:Grafana.Kubernetes:Use 'StatefulSet' instead of 'statefulset'.
> sources/send-data/promtail/scraping.md:78:53:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/send-data/promtail/scraping.md:105:42:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/send-data/promtail/scraping.md:107:35:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/send-data/promtail/scraping.md:112:53:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/send-data/promtail/scraping.md:113:75:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/send-data/promtail/scraping.md:505:35:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/send-data/k6/log-generation.md:99:3:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/configure/examples/query-frontend.md:157:55:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/alert/_index.md:363:565:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/setup/install/istio.md:18:21:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/setup/install/istio.md:26:172:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/setup/install/istio.md:26:195:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/send-data/promtail/configuration.md:1619:19:Grafana.Kubernetes:Use '`kubelet`' instead of 'Kubelet'.
> sources/send-data/promtail/configuration.md:1666:55:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/send-data/promtail/configuration.md:1667:22:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/send-data/promtail/configuration.md:1668:22:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/send-data/promtail/configuration.md:1668:35:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/send-data/promtail/configuration.md:1669:22:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/send-data/promtail/configuration.md:1670:22:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/send-data/promtail/configuration.md:1671:22:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/send-data/promtail/configuration.md:1672:22:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/send-data/promtail/configuration.md:1678:22:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/send-data/promtail/configuration.md:1681:22:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/send-data/promtail/configuration.md:1682:22:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/send-data/promtail/configuration.md:1683:22:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/send-data/promtail/configuration.md:1684:22:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/send-data/promtail/configuration.md:1685:22:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/send-data/promtail/configuration.md:1691:13:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/send-data/promtail/configuration.md:1691:56:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/send-data/promtail/configuration.md:1708:31:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/setup/migrate/migrate-from-distributed/index.md:86:353:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/release-notes/v2-8.md:14:303:Grafana.Kubernetes:Use 'Kubernetes Deployment' instead of 'Kubernetes deployment'.
> sources/operations/zone-ingesters.md:108:125:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/operations/troubleshooting.md:126:29:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/operations/troubleshooting.md:129:77:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/operations/troubleshooting.md:133:10:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/operations/troubleshooting.md:148:39:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/operations/troubleshooting.md:151:42:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/operations/troubleshooting.md:185:35:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/operations/troubleshooting.md:185:82:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/operations/troubleshooting.md:186:8:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/operations/troubleshooting.md:186:46:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/operations/troubleshooting.md:190:26:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/operations/troubleshooting.md:190:56:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/setup/upgrade/_index.md:439:50:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/setup/upgrade/_index.md:482:110:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/setup/upgrade/_index.md:485:57:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/operations/storage/wal.md:41:121:Grafana.Kubernetes:Use 'StatefulSet' instead of 'statefulset'.
> sources/operations/storage/wal.md:51:115:Grafana.Kubernetes:Use 'StatefulSet' instead of 'statefulset'.
> sources/operations/storage/wal.md:65:44:Grafana.Kubernetes:Use 'StatefulSet' instead of 'statefulset'.
> sources/operations/storage/wal.md:86:170:Grafana.Kubernetes:Use 'StatefulSet' instead of 'statefulset'.
> sources/operations/storage/wal.md:98:127:Grafana.Kubernetes:Use 'StatefulSet' instead of 'statefulset'.
> sources/operations/storage/wal.md:98:176:Grafana.Kubernetes:Use 'StatefulSet' instead of 'statefulset'.
> sources/operations/storage/wal.md:98:291:Grafana.Kubernetes:Use 'StatefulSet' instead of 'statefulset'.
> sources/operations/storage/wal.md:104:49:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/operations/loki-canary/_index.md:292:37:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/setup/install/helm/reference.md:257:32:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/setup/install/helm/reference.md:275:45:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/setup/install/helm/reference.md:320:54:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/setup/install/helm/reference.md:2620:49:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/setup/install/helm/reference.md:3182:152:Grafana.Kubernetes:Use '`kubelet`' instead of 'kubelet'.
> sources/setup/install/helm/reference.md:3218:100:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/setup/install/helm/reference.md:3470:42:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/setup/install/helm/reference.md:3515:51:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/setup/install/helm/reference.md:3902:58:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/setup/install/helm/reference.md:4046:51:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/setup/install/helm/reference.md:4082:60:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/setup/install/helm/reference.md:4761:32:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/setup/install/helm/reference.md:4779:43:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/setup/install/helm/reference.md:4824:52:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/community/design-documents/2020-02-Promtail-Push-API.md:63:81:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> sources/get-started/labels/structured-metadata.md:15:12:Grafana.Kubernetes:Use 'Pod' instead of 'pod'.
> ```

Got it!
I'm planning to work on it and i'll open a PR per section/topic, like: 
* setup/install/helm/reference
* sources/operations/troubleshooting
* sources/send-data/promtail/configuration

Thanks for the clarification, I'll keep you posted in this issue :)
