### ISSUE TITLE
What (if any) limits should be applied to the default Helm installation

### ISSUE THREAD

**Issue by slim-bean** [grafana/loki#1200]
The v0.4.0 release introduced finer grained limit controls on Loki for both reads and writes via PR #948, however we have seen since release that the defaults are lower than traffic users are sending and their clients are getting rate limited.

Should we raise the limits on ingestion for the Helm installation? Or remove the limit completely?

**Comment by cyriltovena** [comment]
@sandlis can you take this one, when you can ? Thanks !

**Comment by slim-bean** [comment]
We changed the behavior of rate limited logs to be retried (not dropped) I don't think this is an issue anymore
