### ISSUE TITLE
v0.4.0: x_build_info isn't emitting version anymore.

### ISSUE THREAD

**Issue by Robert-Stam** [grafana/loki#1208]
**Describe the bug**
loki_build_info and promtail_build_info isn't emitting version anymore.
This was emitted in v0.1.0-0.3.0

**To Reproduce**
1. Started Loki & Promtail 0.4.0
2. Scrape both components with Prometheus
3. Retrieve the loki_build_info and promtail_build_info metrics
4. Inspect that the 'version' label is missing.

**Expected behavior**
The 'version' label with value '0.4.0'

**Environment:**
 - Infrastructure: Kubernetes Google gke (k8s v 1.14.6)
 - Deployment tool: Yaml

**Comment by Robert-Stam** [comment]
I checked with v1.0.0, however it's still broken.

**Comment by cyriltovena** [comment]
Someone is working on this I believe

**Comment by pstibrany** [comment]
> Someone is working on this I believe

It's fixed in PR #1095.
