### ISSUE TITLE
Support standard protocols as alternatives

### ISSUE THREAD

**Issue by NotAFile** [grafana/loki#121]
One of the great things about Prometheus is that it can use simple, standard protocols for transferring data. This means I can just use "curl" on any machine for testing and that anything that can accept HTTP requests can also trivially expose prometheus metrics, without adding a requirement for any specific library or dependency.

However, loki currently appears to only support comparatively obscure "snappy" compression and a (private) protobuf format for transferring logs. Theses are probably good technical choices, but are also hurdles that complicate implementation and integration of loki into other systems.

The low hurdle of Prometheus is IMO one of the reasons for it's big success. Unlike other monitoring systems there's no single big daemon or library that needs to support everyone's use cases because you can just trivially create your own exporters. I think this is definitely something worth emulating.

I think it would be helpful to do the following to simplify agent implementation:
 - allow no compression and standard gzip as alternatives to snappy
 - allow a simple text format as alternative to protobuf

**Comment by negbie** [comment]
Shouldn't it be easy to port the proto file to other languages? I didn't tried it yet, just wrote a Go Client in under 200 lines of code to send any kind of layer 7 data captured by gopacket to loki. Wouldn't GZIP stress the CPU too much? With protobuf it's very easy to batch a lot of entries and compress them efficiently with snappy. Please don't get me wrong. I see a reason for plain text in a lab environment with a small amount of traffic/throughput.

**Comment by jgsqware** [comment]
https://github.com/grafana/loki/blob/master/docs/api.md

**Comment by NotAFile** [comment]
Works for me. Thanks!
