### ISSUE TITLE
Ingesting logs to Loki using OpenTelemetry Collector with GRPC

### ISSUE THREAD

**Issue by npuichigo** [grafana/loki#12110]
Currently, the doc says only http OTLP exporter is supported -> "Loki natively supports ingesting OpenTelemetry logs over HTTP. For ingesting logs to Loki using the OpenTelemetry Collector, you must use the [otlphttp exporter](https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/otlphttpexporter)."

**Comment by JStickler** [comment]
It's unclear why you opened this issue?  Is this a question?  Loki support for OpenTelemetry is currently under development.  Native support for the ingestion of logs in OpenTelemetry Protocol(OTLP) format will be GA in Loki 3.0
