### ISSUE TITLE
Docs feedback: /docs/sources/send-data/promtail/installation.md

### ISSUE THREAD

**Issue by isaric** [grafana/loki#12155]
I've noticed two issues in "Install using Docker" section.

There is only a single line instruction which shows how to pull the image.
There is no run command that shows which arguments are needed for running a Promtail Docker container.

Another smaller issue is the comment above the "docker pull" line which gets copied into your clipboard when you want to
copy the pull command.

**Comment by JStickler** [comment]
@isaric is this feedback for the topic for installing Loki (https://grafana.com/docs/loki/latest/setup/install/docker/ ) or for installing Promtail (https://grafana.com/docs/loki/latest/send-data/promtail/installation/ )?

**Comment by isaric** [comment]
This is about installing promtail @JStickler
