### ISSUE TITLE
Option in Loki's configuration that enables automatic flush before a pod completes

### ISSUE THREAD

**Issue by P0lskay** [grafana/loki#12214]
**Is your feature request related to a problem? Please describe.**
We are currently using Loki in Kubernetes and would like to be able to horizontally scale our Loki ingester. However, this is currently impossible because the Loki ingester does not automatically flush its WAL (write-ahead log) storage before shutting down, which causes data loss. If there was a way to configure Loki to automatically flush its storage before shutting down a pod, this would be a great improvement. This would ensure that all data is written to disk and would prevent any data loss due to scale down. 

**Describe the solution you'd like**
It would be helpful if there was an option in Loki's configuration that could be set to enable automatic flush before a pod completes. This would make it easier for us to scale our cluster without worrying about data loss.

**Comment by paul1r** [comment]
Have you tried the `-ingester.flush-on-shutdown` argument [doc](https://grafana.com/docs/loki/latest/configure/#ingester)?

**Comment by P0lskay** [comment]
Thank you for the suggestion. It seems that we may have not looked at the [documentation](https://grafana.com/docs/loki/latest/operations/storage/wal/#changes-in-lifecycle-when-wal-is-enabled) thoroughly. We were somewhat confused by the information regarding the WAL in the documentation. It appears that the information may be outdated or incomplete. Thank you for pointing this out. It seems that this may be what we were searching for.
