### ISSUE TITLE
How to configure Loki as Prometheus datasource?

### ISSUE THREAD

**Issue by vukor** [grafana/loki#1222]
Hello,
New v0.4.0 release version is support PromQL as I understand. Here proof link - https://grafana.com/blog/2019/10/28/whats-new-in-loki-v0.4.0/

I would like to add Loki as Prometheus datasource in Grafana (6.4.3 version) but can't find what is correct address? I already use Loki datasource (address is http://loki:3100) and it works.

I need to use PromQL to configure alert trigger for some log message regexp.
Thanks.

**Comment by vukor** [comment]
More details:

Inside grafana/loki:v0.4.0 container: 
```
/ $ netstat -ltnup
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 :::3100                 :::*                    LISTEN      1/loki
tcp        0      0 :::9095                 :::*                    LISTEN      1/loki
```

9095 - is some binary data
3100 - Loki datasource, http://loki:3100/loki return 404

**Comment by negbie** [comment]
Hi,
did you try it with curl like in the examples here? Just to make sure that you can reach the query endpoint. 
https://github.com/grafana/loki/blob/master/docs/api.md#examples

**Comment by slim-bean** [comment]
Append `loki` to the end of your URL, like this: `http://loki:3100/loki` and be sure to select the Prometheus data source type.

**Comment by vukor** [comment]
Thanks guys, http://loki:3100/loki looks working.

**Comment by lobatt** [comment]
> Append `loki` to the end of your URL, like this: `http://loki:3100/loki` and be sure to select the Prometheus data source type.

I know this issue has been closed, but I am having some issue setting this up.
I am thrilled to learn the support for metrics for Loki.

However, when I configure my Prometheus data source to use http://loki:3100/loki as server URL, with latest docker images.

My grafana UI got stucked "Loading metrics", hence not being able to perform any query.

![image](https://user-images.githubusercontent.com/1172678/69000372-a0910380-089c-11ea-88df-76931013b9d6.png)

Am I missing anything?

**Comment by cyriltovena** [comment]
No you’re not missing anything. This box doesn’t yet work (soon) but you can still make queries.

**Comment by lobatt** [comment]
> No you’re not missing anything. This box doesn’t yet work (soon) but you can still make queries.

Thanks @cyriltovena .

So for keep an eye on the progress, should I watch releases of Loki or Grafana itself?

**Comment by cyriltovena** [comment]
Grafana, there is already a version supporting this but not tagged I think

**Comment by guobei2028** [comment]
https://[my-loki-url]/loki in my 2.0 version seems to have no effect. Has anyone encountered the same situation？
I already use Loki datasource (address is http://loki:3100) and it works.

**Comment by frankyaorenjie** [comment]
Yes, this solution doesn't work in new version. Grafana 7.4.0-pre

**Comment by saibug** [comment]
Having same issue in production ! 
My loki version is : 2.4.2 
From read instance, this is log output : 
`read_1   | level=error ts=2022-05-09T12:41:32.850473694Z caller=retry.go:73 org_id=fake msg="error processing request" try=4 err="rpc error: code = Code(500) desc = unsupported response type, got (scalar)"
read_1   | level=info ts=2022-05-09T12:41:32.850559168Z caller=metrics.go:92 org_id=fake latency=fast query=1+1 query_type=metric range_type=instant length=0s step=0s duration=0s status=500 limit=100 returned_lines=0 throughput=0B total_bytes=0B` 

Thank you

**Comment by KVInventoR** [comment]
Hey
same for me, I also got an issue:
```
loki-linux-amd64 --version
loki, version 2.5.0 (branch: HEAD, revision: 2d9d0ee23)
  build user:       root@4779f4b48f3a
  build date:       2022-04-07T21:50:00Z
  go version:       go1.17.6
  platform:         linux/amd64
  ```
  
  grafana                        7.0.0
