### ISSUE TITLE
Base Kustomize manifests for Loki?

### ISSUE THREAD

**Issue by CiucurDaniel** [grafana/loki#12261]
I was wondering if there are some base kustomization resources that one can use to deploy Loki. I'm looking for something similar to what kube-prometheus provides [here](https://github.com/prometheus-operator/kube-prometheus/blob/main/kustomization.yaml) ?

`/operator/config` I noticed here we do have some kustomize files but they are no documented (eg: basic usage, purpose, diff between community, community-openshift, openshift)

If we can some clarity here, I can try to help with the docs and with [Kustomize version PR](https://github.com/grafana/loki/issues/11419).
```[tasklist]
### Tasks
```

**Comment by periklis** [comment]
FYI the `operator/config` kustomize manifests are simply for internal use by the operator maintainers to generate bundles in `operator/bundles`. The best place we maintain production/deploy manifest is the `production` folder.
