### ISSUE TITLE
Adapt centralised limits code for Loki

### ISSUE THREAD

**Issue by tomwilkie** [grafana/loki#1229]
There are two Loki limits which we need to centralize:
- `IngestionRate` (based on [this Cortex PR](https://github.com/cortexproject/cortex/pull/1766) once merged)
- `MaxStreamsPerUser`

**Comment by tomwilkie** [comment]
(Sorry if this has already been done - feel free to close if so)

**Comment by pracucci** [comment]
Closed by #1493 and #1486.
