### ISSUE TITLE
What's with the v0.6.0 operator release?

### ISSUE THREAD

**Issue by electrofloat** [grafana/loki#12296]
This is the 4th time today I'm receiving a notification from github, that operator v0.6.0 has been released.

**Comment by carlpett** [comment]
They are all from different commits (in order of releases today):
- c025fb0
- 243e6f8
- 3cc4c67
- 3cc4feb

It is not great that there's re-tagging in this way (it looks like the commits are trying to fix things in the release workflow, but still)

**Comment by periklis** [comment]
@electrofloat sorry for the disruption. We tried to establish our new Loki Operator release pipeline today and we had to recreate the tag a couple of times unfortunately.
