### ISSUE TITLE
Loki's configuration

### ISSUE THREAD

**Issue by shirpx** [grafana/loki#123]
hey,
i am trying to deploy loki using image grafana/loki:master
and this conf file:
https://github.com/grafana/loki/blob/master/docs/loki-local-config.yaml

and i’m getting errors:
caller=consul_client.go:182 msg=“error getting path” key=ring err=null
level=info ts=2018-12-13T16:07:43.715778784Z caller=lifecycler.go:360 msg=“entry not found in ring, adding with no tokens”
level=info ts=2018-12-13T16:07:43.716520284Z caller=lifecycler.go:290 msg=“auto-joining cluster after timeout”

the problem is in that section from what i understand:
 ring:
   store: inmemory

not sure what it the correct conf and what am i missing.

**Comment by tomwilkie** [comment]
Hi @shirpx!  These error messages are not really errors; they're just saying that the ring is missing on startup - which is to be expected with the in-memory ring.  When you run Loki pointed at a consul cluster with an existing ring, this won't happen.

**Comment by hekmat1** [comment]
@tomwilkie but how? can you please explain: run Loki pointed at a consul cluster with an existing ring?
