### ISSUE TITLE
Filter with the pattern

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#12347]
Right now you can only use 
```
| pattern `foo <buzz> bar`
``` 

 to extract fields/labels (e.g `buzz` here) but you can't use it for filtering non matching log line of that pattern.

While we can easily make the suggested pattern filtering by replacing fields with regex

```
|~ `foo (.*) bar
``` 

this is by far inefficient.

I suggest we introduce a new way in the language to filter with the pattern language. This will be much more efficient and less problematic with control character which has been proven to be painful in my previous hackathon.

We should be able to filter in and out with pattern.  Part of the task is to suggest the two new language syntax addition.

**Comment by cyriltovena** [comment]
What would be the alternative for filtering in ?

**Comment by kolesnikovae** [comment]
After an internal discussion we decided to extend the syntax with a new line filter operator:

```
|> "pattern string"
```

And exclamation sight instead of the pipe for negation:
```
!> "pattern string"
```
