### ISSUE TITLE
Loki keeps restarting

### ISSUE THREAD

**Issue by philbour** [grafana/loki#1236]
**Describe the bug**
I've deployed Loki 0.4.0 onto my Kubernetes cluster and am running a load test. Loki appears to keep restarting, about every 12 hours or so. I do see errors at the end of the log file - 

> level=info ts=2019-11-05T19:31:45.798594733Z caller=signals.go:54 msg="=== received SIGINT/SIGTERM ===\n*** exiting"
level=info ts=2019-11-05T19:31:45.798683183Z caller=loki.go:175 msg="notifying module about stopping" module=all
level=info ts=2019-11-05T19:31:45.798722534Z caller=loki.go:175 msg="notifying module about stopping" module=distributor
level=info ts=2019-11-05T19:31:45.79873496Z caller=loki.go:175 msg="notifying module about stopping" module=ingester
level=info ts=2019-11-05T19:31:45.798747364Z caller=loki.go:175 msg="notifying module about stopping" module=querier
level=info ts=2019-11-05T19:31:45.798757813Z caller=loki.go:175 msg="notifying module about stopping" module=ring
level=info ts=2019-11-05T19:31:45.798764454Z caller=loki.go:175 msg="notifying module about stopping" module=store
level=info ts=2019-11-05T19:31:45.798769923Z caller=loki.go:175 msg="notifying module about stopping" module=table-manager
level=info ts=2019-11-05T19:31:45.798775786Z caller=loki.go:175 msg="notifying module about stopping" module=overrides
level=info ts=2019-11-05T19:31:45.798781389Z caller=loki.go:175 msg="notifying module about stopping" module=server
level=info ts=2019-11-05T19:31:45.798786954Z caller=loki.go:157 msg=stopping module=all
level=info ts=2019-11-05T19:31:45.798797464Z caller=loki.go:157 msg=stopping module=distributor
level=info ts=2019-11-05T19:31:45.798803792Z caller=loki.go:157 msg=stopping module=ingester
level=info ts=2019-11-05T19:31:45.798822813Z caller=lifecycler.go:476 msg="changing ingester state from" old_state=ACTIVE new_state=LEAVING
level=error ts=2019-11-05T19:31:45.7990441Z caller=transfer.go:153 msg="transfer failed" err="cannot find ingester to transfer chunks to: no pending ingesters"

**To Reproduce**
1. Deploy Loki stack

**Expected behavior**
Not to restart

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
Kubernetes 1.14.3

 - Deployment tool: [e.g., helm, jsonnet]
Deployed loki stack with helm

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by philbour** [comment]
From looking at the prom tail logs, I see warning around the same time which make sense as Loki would have been temporarily unavailable. But I also see errors about exceeding the ingestion rate limit. Am I just hitting Loki with too much data? I am running a load test with a lot of pods deployed

> level=warn ts=2019-11-05T19:31:47.180551917Z caller=client.go:201 component=client host=loki:3100 msg="error sending batch, will retry" status=-1 error="Post http://loki:3100/api/prom/push: dial tcp 10.101.158.202:3100: connect: connection refused"
level=warn ts=2019-11-05T19:31:48.380692687Z caller=client.go:201 component=client host=loki:3100 msg="error sending batch, will retry" status=-1 error="Post http://loki:3100/api/prom/push: dial tcp 10.101.158.202:3100: connect: connection refused"
level=warn ts=2019-11-05T19:31:49.672659786Z caller=client.go:201 component=client host=loki:3100 msg="error sending batch, will retry" status=-1 error="Post http://loki:3100/api/prom/push: dial tcp 10.101.158.202:3100: connect: connection refused"
level=warn ts=2019-11-05T19:31:51.188759276Z caller=client.go:201 component=client host=loki:3100 msg="error sending batch, will retry" status=-1 error="Post http://loki:3100/api/prom/push: dial tcp 10.101.158.202:3100: connect: connection refused"
level=warn ts=2019-11-05T19:31:53.495126559Z caller=client.go:201 component=client host=loki:3100 msg="error sending batch, will retry" status=-1 error="Post http://loki:3100/api/prom/push: dial tcp 10.101.158.202:3100: connect: connection refused"
level=warn ts=2019-11-05T19:31:56.193433145Z caller=client.go:201 component=client host=loki:3100 msg="error sending batch, will retry" status=-1 error="Post http://loki:3100/api/prom/push: dial tcp 10.101.158.202:3100: connect: connection refused"
level=warn ts=2019-11-05T19:32:01.244600046Z caller=client.go:201 component=client host=loki:3100 msg="error sending batch, will retry" status=-1 error="Post http://loki:3100/api/prom/push: dial tcp 10.101.158.202:3100: connect: connection refused"
level=warn ts=2019-11-05T19:32:05.640863113Z caller=client.go:201 component=client host=loki:3100 msg="error sending batch, will retry" status=-1 error="Post http://loki:3100/api/prom/push: dial tcp 10.101.158.202:3100: connect: connection refused"
level=warn ts=2019-11-05T19:32:11.60581206Z caller=client.go:201 component=client host=loki:3100 msg="error sending batch, will retry" status=-1 error="Post http://loki:3100/api/prom/push: dial tcp 10.101.158.202:3100: connect: connection refused"
level=warn ts=2019-11-05T19:32:16.52064586Z caller=client.go:201 component=client host=loki:3100 msg="error sending batch, will retry" status=-1 error="Post http://loki:3100/api/prom/push: dial tcp 10.101.158.202:3100: connect: connection refused"
level=warn ts=2019-11-05T19:32:22.100665582Z caller=client.go:201 component=client host=loki:3100 msg="error sending batch, will retry" status=-1 error="Post http://loki:3100/api/prom/push: dial tcp 10.101.158.202:3100: connect: connection refused"
level=warn ts=2019-11-05T19:32:27.964529894Z caller=client.go:201 component=client host=loki:3100 msg="error sending batch, will retry" status=-1 error="Post http://loki:3100/api/prom/push: dial tcp 10.101.158.202:3100: connect: connection refused"
level=warn ts=2019-11-05T19:32:33.616837065Z caller=client.go:201 component=client host=loki:3100 msg="error sending batch, will retry" status=-1 error="Post http://loki:3100/api/prom/push: dial tcp 10.101.158.202:3100: connect: connection refused"
level=warn ts=2019-11-05T19:32:39.496595655Z caller=client.go:201 component=client host=loki:3100 msg="error sending batch, will retry" status=-1 error="Post http://loki:3100/api/prom/push: dial tcp 10.101.158.202:3100: connect: connection refused"
level=error ts=2019-11-05T19:32:47.615506118Z caller=client.go:206 component=client host=loki:3100 msg="final error sending batch" status=429 error="server returned HTTP status 429 Too Many Requests (429): ingestion rate limit (4194304) exceeded while adding 564 lines"
level=error ts=2019-11-05T19:32:47.740107607Z caller=client.go:206 component=client host=loki:3100 msg="final error sending batch" status=429 error="server returned HTTP status 429 Too Many Requests (429): ingestion rate limit (4194304) exceeded while adding 580 lines"
level=error ts=2019-11-05T19:32:47.787497678Z caller=client.go:206 component=client host=loki:3100 msg="final error sending batch" status=429 error="server returned HTTP status 429 Too Many Requests (429): ingestion rate limit (4194304) exceeded while adding 558 lines"

**Comment by slim-bean** [comment]
There are rate limits in Loki, there is some info in the docs (sorry, on mobile hard to link)

The sigint/sigterm line indicates something outside Loki sent this signal, as on Loki is not crashing it's being told to shutdown

I'm not sure what would be causing this for you? Can you check the node logs or kube events to see if there is any indication why the process is being told to shutdown?

**Comment by slim-bean** [comment]
If the node runs out of memory it may be evicting the Loki process? I believe a `get pods` would show pods with evicted status

**Comment by philbour** [comment]
Definitely no memory issue on the node. I was thinking perhaps the pod was exceeding its memory limits but there does not appear to be any set? Only using < 200 MB anyway, which is pretty impressive!

The only other thing I can think of is the liveness probe, perhaps kubernetes is killing the container?

**Comment by philbour** [comment]
Turns out it was something stupid I was doing! I was running a load test with Loki deployed but with no persistence configured. The pod would eventually run out of storage.

**Comment by sahilpatel09** [comment]
I am having this issue with grafana/loki version 2.7.2. I think after sometime the healthcheck kicks in and restarts the container. 

level=warn ts=2023-08-03T13:18:21.327806757Z caller=loki.go:251 msg="per-tenant timeout not configured, using default engine timeout (\"5m0s\"). This behavior will change in the next major to always use the default per-tenant timeout (\"5m\")."
level=info ts=2023-08-03T13:18:21.329168094Z caller=main.go:103 msg="Starting Loki" version="(version=2.7.2, branch=HEAD, revision=c35554d09)"
level=info ts=2023-08-03T13:18:21.330542586Z caller=server.go:323 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2023-08-03T13:18:21.331821155Z caller=memberlist_client.go:436 msg="Using memberlist cluster label and node name" cluster_label= node=af98800d672e-65f402e7
level=warn ts=2023-08-03T13:18:21.332971999Z caller=cache.go:114 msg="fifocache config is deprecated. use embedded-cache instead"
level=warn ts=2023-08-03T13:18:21.332992917Z caller=experimental.go:20 msg="experimental feature in use" feature="In-memory (FIFO) cache - chunksembedded-cache"
level=info ts=2023-08-03T13:18:21.333235212Z caller=table_manager.go:262 msg="query readiness setup completed" duration=1.16µs distinct_users_len=0
level=info ts=2023-08-03T13:18:21.333257649Z caller=shipper.go:127 msg="starting index shipper in RW mode"
level=info ts=2023-08-03T13:18:21.333310649Z caller=shipper_index_client.go:78 msg="starting boltdb shipper in RW mode"
level=info ts=2023-08-03T13:18:21.33360908Z caller=worker.go:112 msg="Starting querier worker using query-scheduler and scheduler ring for addresses"
level=info ts=2023-08-03T13:18:21.337917171Z caller=mapper.go:47 msg="cleaning up mapped rules directory" path=/loki/rules-temp
level=info ts=2023-08-03T13:18:21.340351872Z caller=memberlist_client.go:543 msg="memberlist fast-join starting" nodes_found=1 to_join=4
level=info ts=2023-08-03T13:18:21.340931223Z caller=table_manager.go:134 msg="uploading tables"
level=info ts=2023-08-03T13:18:21.340964109Z caller=table_manager.go:166 msg="handing over indexes to shipper"
level=info ts=2023-08-03T13:18:21.344024838Z caller=module_service.go:82 msg=initialising module=server
level=info ts=2023-08-03T13:18:21.344462813Z caller=module_service.go:82 msg=initialising module=cache-generation-loader
level=info ts=2023-08-03T13:18:21.344555713Z caller=memberlist_client.go:563 msg="memberlist fast-join finished" joined_nodes=1 elapsed_time=4.208464ms
level=info ts=2023-08-03T13:18:21.344572702Z caller=memberlist_client.go:576 msg="joining memberlist cluster" join_members=localhost:7946
level=info ts=2023-08-03T13:18:21.345069213Z caller=module_service.go:82 msg=initialising module=memberlist-kv
level=info ts=2023-08-03T13:18:21.345093143Z caller=module_service.go:82 msg=initialising module=query-frontend-tripperware
level=info ts=2023-08-03T13:18:21.345110169Z caller=module_service.go:82 msg=initialising module=ring
level=info ts=2023-08-03T13:18:21.345220985Z caller=ring.go:263 msg="ring doesn't exist in KV store yet"
level=info ts=2023-08-03T13:18:21.345255195Z caller=client.go:255 msg="value is nil" key=collectors/ring index=1
level=info ts=2023-08-03T13:18:21.345307982Z caller=module_service.go:82 msg=initialising module=usage-report
level=info ts=2023-08-03T13:18:21.345748835Z caller=memberlist_client.go:595 msg="joining memberlist cluster succeeded" reached_nodes=1 elapsed_time=1.176063ms
level=info ts=2023-08-03T13:18:21.345823898Z caller=module_service.go:82 msg=initialising module=ingester-querier
level=info ts=2023-08-03T13:18:21.345855684Z caller=module_service.go:82 msg=initialising module=store
level=info ts=2023-08-03T13:18:21.345872982Z caller=module_service.go:82 msg=initialising module=ingester
level=info ts=2023-08-03T13:18:21.345895474Z caller=ingester.go:417 msg="recovering from checkpoint"
level=info ts=2023-08-03T13:18:21.345957627Z caller=module_service.go:82 msg=initialising module=query-scheduler
level=info ts=2023-08-03T13:18:21.346016674Z caller=ring.go:263 msg="ring doesn't exist in KV store yet"
level=info ts=2023-08-03T13:18:21.346051383Z caller=module_service.go:82 msg=initialising module=compactor
level=info ts=2023-08-03T13:18:21.346053359Z caller=module_service.go:82 msg=initialising module=distributor
level=info ts=2023-08-03T13:18:21.346119404Z caller=ring.go:263 msg="ring doesn't exist in KV store yet"
level=info ts=2023-08-03T13:18:21.346169649Z caller=module_service.go:82 msg=initialising module=ruler
level=info ts=2023-08-03T13:18:21.346208338Z caller=ruler.go:446 msg="ruler up and running"
level=info ts=2023-08-03T13:18:21.346413923Z caller=lifecycler.go:547 msg="not loading tokens from file, tokens file path is empty"
level=info ts=2023-08-03T13:18:21.346453627Z caller=lifecycler.go:576 msg="instance not found in ring, adding with no tokens" ring=distributor
level=info ts=2023-08-03T13:18:21.346456283Z caller=basic_lifecycler.go:261 msg="instance not found in the ring" instance=af98800d672e ring=scheduler
level=info ts=2023-08-03T13:18:21.346481766Z caller=basic_lifecycler_delegates.go:63 msg="not loading tokens from file, tokens file path is empty"
level=info ts=2023-08-03T13:18:21.346580802Z caller=lifecycler.go:416 msg="auto-joining cluster after timeout" ring=distributor
level=info ts=2023-08-03T13:18:21.346629989Z caller=basic_lifecycler.go:261 msg="instance not found in the ring" instance=af98800d672e ring=compactor
level=info ts=2023-08-03T13:18:21.346646829Z caller=basic_lifecycler_delegates.go:63 msg="not loading tokens from file, tokens file path is empty"
level=info ts=2023-08-03T13:18:21.346778872Z caller=compactor.go:328 msg="waiting until compactor is JOINING in the ring"
level=info ts=2023-08-03T13:18:21.346791813Z caller=compactor.go:332 msg="compactor is JOINING in the ring"
level=info ts=2023-08-03T13:18:21.346832584Z caller=ingester.go:433 msg="recovered WAL checkpoint recovery finished" elapsed=943.027µs errors=false
level=info ts=2023-08-03T13:18:21.346840959Z caller=ingester.go:439 msg="recovering from WAL"
level=info ts=2023-08-03T13:18:21.346983488Z caller=scheduler.go:617 msg="waiting until scheduler is JOINING in the ring"
level=info ts=2023-08-03T13:18:21.346993264Z caller=scheduler.go:621 msg="scheduler is JOINING in the ring"
level=info ts=2023-08-03T13:18:21.347125646Z caller=ingester.go:455 msg="WAL segment recovery finished" elapsed=1.239018ms errors=false
level=info ts=2023-08-03T13:18:21.347258188Z caller=ingester.go:403 msg="closing recoverer"
level=info ts=2023-08-03T13:18:21.347267733Z caller=ingester.go:411 msg="WAL recovery finished" time=1.380873ms
level=info ts=2023-08-03T13:18:21.347305341Z caller=lifecycler.go:547 msg="not loading tokens from file, tokens file path is empty"
level=info ts=2023-08-03T13:18:21.347334481Z caller=lifecycler.go:576 msg="instance not found in ring, adding with no tokens" ring=ingester
level=info ts=2023-08-03T13:18:21.347374065Z caller=lifecycler.go:416 msg="auto-joining cluster after timeout" ring=ingester
level=info ts=2023-08-03T13:18:21.347453436Z caller=wal.go:156 msg=started component=wal
level=info ts=2023-08-03T13:18:22.347791726Z caller=compactor.go:342 msg="waiting until compactor is ACTIVE in the ring"
level=info ts=2023-08-03T13:18:22.347834711Z caller=scheduler.go:631 msg="waiting until scheduler is ACTIVE in the ring"
level=info ts=2023-08-03T13:18:22.473513174Z caller=scheduler.go:635 msg="scheduler is ACTIVE in the ring"
level=info ts=2023-08-03T13:18:22.473587945Z caller=module_service.go:82 msg=initialising module=query-frontend
level=info ts=2023-08-03T13:18:22.473597815Z caller=module_service.go:82 msg=initialising module=querier
level=info ts=2023-08-03T13:18:22.495706554Z caller=compactor.go:346 msg="compactor is ACTIVE in the ring"
level=info ts=2023-08-03T13:18:22.495733658Z caller=loki.go:461 msg="Loki started"
level=info ts=2023-08-03T13:18:25.474357866Z caller=worker.go:209 msg="adding connection" addr=127.0.0.1:9095
level=info ts=2023-08-03T13:18:25.474362603Z caller=scheduler.go:682 msg="this scheduler is in the ReplicationSet, will now accept requests."
level=info ts=2023-08-03T13:18:27.496216799Z caller=compactor.go:407 msg="this instance has been chosen to run the compactor, starting compactor"
level=info ts=2023-08-03T13:18:27.496285049Z caller=compactor.go:436 msg="waiting 10m0s for ring to stay stable and previous compactions to finish before starting compactor"
level=info ts=2023-08-03T13:18:32.474742781Z caller=frontend_scheduler_worker.go:101 msg="adding connection to scheduler" addr=127.0.0.1:9095
level=info ts=2023-08-03T13:19:13.640611975Z caller=signals.go:55 msg="=== received SIGINT/SIGTERM ===\n*** exiting"
level=info ts=2023-08-03T13:19:13.64085963Z caller=compactor.go:493 msg="compactor started"
ts=2023-08-03T13:19:13.640890949Z caller=spanlogger.go:80 level=info msg="building index list cache"
ts=2023-08-03T13:19:13.641469253Z caller=spanlogger.go:80 level=info msg="index list cache built" duration=12.205µs
level=info ts=2023-08-03T13:19:13.641666243Z caller=basic_lifecycler.go:202 msg="ring lifecycler is shutting down" ring=compactor
level=info ts=2023-08-03T13:19:13.641757407Z caller=lifecycler.go:466 msg="lifecycler loop() exited gracefully" ring=distributor
level=info ts=2023-08-03T13:19:13.641782157Z caller=basic_lifecycler.go:372 msg="unregistering instance from ring" ring=compactor
level=info ts=2023-08-03T13:19:13.641792645Z caller=lifecycler.go:791 msg="changing instance state from" old_state=ACTIVE new_state=LEAVING ring=distributor
level=info ts=2023-08-03T13:19:13.641811962Z caller=basic_lifecycler.go:242 msg="instance removed from the ring" ring=compactor
level=info ts=2023-08-03T13:19:13.641834851Z caller=compactor.go:389 msg="compactor exiting"
level=info ts=2023-08-03T13:19:13.64188213Z caller=lifecycler.go:875 msg="lifecycler entering final sleep before shutdown" final_sleep=0s
level=info ts=2023-08-03T13:19:13.641910981Z caller=lifecycler.go:518 msg="instance removed from the KV store" ring=distributor
level=info ts=2023-08-03T13:19:13.641927206Z caller=manager.go:255 msg="stopping user managers"
level=info ts=2023-08-03T13:19:13.641945918Z caller=manager.go:269 msg="all user managers stopped"
level=info ts=2023-08-03T13:19:13.64195213Z caller=mapper.go:47 msg="cleaning up mapped rules directory" path=/loki/rules-temp
level=info ts=2023-08-03T13:19:13.641989177Z caller=module_service.go:114 msg="module stopped" module=ruler
level=info ts=2023-08-03T13:19:13.642028654Z caller=module_service.go:114 msg="module stopped" module=distributor
level=info ts=2023-08-03T13:19:13.642068224Z caller=wal.go:144 msg=stopped component=wal
level=info ts=2023-08-03T13:19:13.642076516Z caller=lifecycler.go:466 msg="lifecycler loop() exited gracefully" ring=ingester
level=info ts=2023-08-03T13:19:13.642091401Z caller=module_service.go:114 msg="module stopped" module=query-frontend
level=info ts=2023-08-03T13:19:13.642084935Z caller=lifecycler.go:791 msg="changing instance state from" old_state=ACTIVE new_state=LEAVING ring=ingester
level=info ts=2023-08-03T13:19:13.642100467Z caller=module_service.go:114 msg="module stopped" module=compactor
level=info ts=2023-08-03T13:19:13.64212131Z caller=module_service.go:114 msg="module stopped" module=query-frontend-tripperware
level=info ts=2023-08-03T13:19:13.642156055Z caller=lifecycler.go:858 msg="transfers are disabled"
level=info ts=2023-08-03T13:19:13.642177633Z caller=lifecycler.go:875 msg="lifecycler entering final sleep before shutdown" final_sleep=0s
level=info ts=2023-08-03T13:19:13.642205567Z caller=lifecycler.go:518 msg="instance removed from the KV store" ring=ingester
level=info ts=2023-08-03T13:19:13.642563022Z caller=module_service.go:114 msg="module stopped" module=ingester
level=info ts=2023-08-03T13:19:13.642653535Z caller=module_service.go:114 msg="module stopped" module=querier
level=info ts=2023-08-03T13:19:13.642713736Z caller=module_service.go:114 msg="module stopped" module=cache-generation-loader
level=info ts=2023-08-03T13:19:13.642727327Z caller=module_service.go:114 msg="module stopped" module=ingester-querier
level=info ts=2023-08-03T13:19:13.642747226Z caller=table_manager.go:95 msg="stopping table manager"
level=info ts=2023-08-03T13:19:13.642754763Z caller=table_manager.go:166 msg="handing over indexes to shipper"
level=info ts=2023-08-03T13:19:13.642759788Z caller=table_manager.go:75 msg="stopping table manager"
level=info ts=2023-08-03T13:19:13.642765656Z caller=table_manager.go:134 msg="uploading tables"
level=info ts=2023-08-03T13:19:13.642798562Z caller=module_service.go:114 msg="module stopped" module=store
level=info ts=2023-08-03T13:19:13.642807913Z caller=basic_lifecycler.go:202 msg="ring lifecycler is shutting down" ring=scheduler
level=info ts=2023-08-03T13:19:13.642900395Z caller=basic_lifecycler.go:372 msg="unregistering instance from ring" ring=scheduler
level=info ts=2023-08-03T13:19:13.642929544Z caller=basic_lifecycler.go:242 msg="instance removed from the ring" ring=scheduler
level=info ts=2023-08-03T13:19:13.642947202Z caller=module_service.go:114 msg="module stopped" module=query-scheduler
level=info ts=2023-08-03T13:19:13.642984763Z caller=module_service.go:114 msg="module stopped" module=usage-report
