### ISSUE TITLE
Release "store objects under prefix object storage" feature

### ISSUE THREAD

**Issue by tculp** [grafana/loki#12364]
The feature proposed in [#5889](https://github.com/grafana/loki/issues/5889) and merged in [#10096](https://github.com/grafana/loki/pull/10096) has not yet been included in a release, documented, or included in the Loki helm charts.

Could this feature please be released or expectations set on when it may be released? It has been 5 months since the feature has been merged and the issue has been marked as completed, and despite multiple requests in the original issue for more information a update has not been given.

**Comment by tculp** [comment]
Thanks for the update!

**Comment by JStickler** [comment]
@tculp Can we close this issue?  Or do you want to wait until the release is officially out?

**Comment by tculp** [comment]
I'm tempted to wait until the release is officially out

**Comment by simonfelding** [comment]
Until then, you can use the CLI flag `-store.object-prefix`

**Comment by JStickler** [comment]
@tculp Loki 3.0 has been released, and the CHANGELOG has been updated and indicates that #10096 is included in the release.  (Release Notes are still being updated, our new automated release process only captured the most recent changes in the changelog so I've got to make some manual updates...)

**Comment by tculp** [comment]
Yeah, I actually have loki deployed with object_prefix set and it's working. Documentation in the helm chart would be nice, but I think this ticket would be considered done.

So other people can find it, here's the value that works:
```
loki:
  storage_config:
    object_prefix: loki-logs
```

**Comment by Yikuan-Tu** [comment]
@tculp Hi there, thank you for bringing this up.
Can you please share more information about how you use `object_prefix` ?
Im using helm chart version 6.3.4 with loki 3.0.0 to install loki into my cluster. My values look like:
```
storage_config:
    object_prefix: ${object_prefix}
    aws:
      s3: ${s3_path}
      insecure: false
      region: ${aws_region}
      sse:
        type: SSE-S3
```
but Im still encountering this error:
`field object_prefix not found in type storage.Config`
I really appreciate your help.
