### ISSUE TITLE
[Helm] Allow setting chunk memcached_client timeouts from helm chart

### ISSUE THREAD

**Issue by anindyameister** [grafana/loki#12413]
**Is your feature request related to a problem? Please describe.**
As seen [here](https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml#L145-#L151), the loki helm chart only reads the host and service for the chuck cache from helm values. Please enable timeout for the chunk memcache client in helm.

**Describe the solution you'd like**
Helm chart should add additional templating to allow configuring chunk cache timeouts.

**Describe alternatives you've considered**

**Additional context**

**Comment by JStickler** [comment]
I believe there is already a PR open for this.  Does #10730 look like it would meet your needs?

**Comment by anindyameister** [comment]
> I believe there is already a PR open for this. Does #10730 look like it would meet your needs?

yes, that's exactly what I needed. I'll close this.
