### ISSUE TITLE
[Bloom]Low log ingestion rate may cause blocks generated by compact tasks in two neighboring interval on S3 both being deleted

### ISSUE THREAD

**Issue by honganan** [grafana/loki#12499]
**Describe the bug**
Bloom compactor compact blocks in interval. Newer task compact newer blocks and replace the olds if there are outdated. Compactor judge outdated blocks by checking it's associating TSDB Index Sources.

If we have a slow log ingestion rates and there is no new log comes between two compaction interval, the newer task will put(overrides) the same block and meta files as previous exists to Object Store, and then the new task will then consider one of these two metas to be outdated and will delete it's data on OSS. 

That results in the only one blocks-and-metas in Object Store been deleted.

The normal work flow should like:
1. Task1 build and upload blocks-and-metas version 1
2. After an compaction interval there is a Task2 build and upload blocks-and-metas version 2
3. Task2 find version 1 outdated and delete it
4. The Object Store contains only the newer version 2 files

In this situation it acts like:
1. Task1 build and upload blocks-and-metas version 1
2. After an compaction interval there is a Task2 also build and upload blocks-and-metas version 1(As no new log comes and TSDB Sources not changed)
3. Task2 compares two version 1 metas and consider one of them outdated and delete it's metas and blocks
4. The Object Store is empty now!

**To Reproduce**
1. Started Loki Writer and control log ingestion rate(It's better to ingeste logs manually)
2. Stop the ingestion after ingestes some logs 
3. Started Loki Bloom Compactor(2.9.0 or newer) and let Bloom Compactor generates blocks and metas first time
4. Confirm blocks uploaded to OSS and wait Bloom Compactor generates blocks second time
5. After the second interval task completed check OSS, blocks and metas been cleared now

Another simpler way to understand this issue is to run a Unit test:
```golang
func Test_OutdatedMetas(t *testing.T) {
	gen := func(bounds v1.FingerprintBounds, tsdbTimes ...model.Time) (meta bloomshipper.Meta) {
		for _, tsdbTime := range tsdbTimes {
			meta.Sources = append(meta.Sources, tsdb.SingleTenantTSDBIdentifier{TS: tsdbTime.Time()})
		}
		meta.Bounds = bounds
		return meta
	}

	for _, tc := range []struct {
		desc  string
		metas []bloomshipper.Meta
		exp   []bloomshipper.Meta
	}{
		{
			desc: "no outdated meta",
			metas: []bloomshipper.Meta{
				gen(v1.NewBounds(0, 10), 0),
				gen(v1.NewBounds(0, 10), 0),
			},
			exp: []bloomshipper.Meta{
				gen(v1.NewBounds(0, 10), 0),
			},
		},
	} {
		t.Run(tc.desc, func(t *testing.T) {
			outdated, err := outdatedMetas(tc.metas)
			require.NoError(t, err)
			require.Equal(t, tc.exp, outdated)
		})
	}
}
```
`outdatedMetas` consider one of these two same metas outdated, and `SimpleBloomController` will delete the outdated metas and blocks after build gaps. But the new task upload data is done before the outdate check.

**Expected behavior**
If no new data changs, the blocks and metas shouldn't be changed or we could just update it's time but should nerver delete them.

**Environment:**
 - Infrastructure: [laptop]
 - Deployment tool: [none]

**Screenshots, Promtail config, or terminal output**

<Sorry for not mother language expression>

**Comment by salvacorts** [comment]
Hello, Thank you for opening this issue! (you just created the first issue for blooms which is pretty exciting 🎉 )

I could successfully reproduce the issue and we are working to fix it :)
