### ISSUE TITLE
hello, my loki docker container stop working and cant make it work again

### ISSUE THREAD

**Issue by userbox020** [grafana/loki#12529]
Hello,
I already restart pc, restart container, deleted container and build it again and nothing, same error.
here a left the error:

```
(base) mruserbox@guru-X99:~$ docker logs effc9feeb3b6
failed parsing config: /etc/loki/loki.yml: yaml: unmarshal errors:
  line 21: field shared_store not found in type compactor.Config. Use `-config.expand-env=true` flag if you want to expand environment variables in your config file
```

**Comment by BilikoX** [comment]
> The same issue with Helm Chart.
> 
> Compactor config in Values file:
> 
> ```
> ...
> loki:
>   compactor:
>     shared_store: s3
>     delete_request_cancel_period: 10m
>     working_directory: /var/loki/index-compactor
>     compaction_interval: 10m
>     retention_enabled: true
>     retention_delete_delay: 2h
>     retention_delete_worker_count: 150
> ...
> ```
> 
> All PODs like loki-read, loki-write, loki-backend, ... shows the same error log:
> 
> ```
> failed parsing config: /etc/loki/config/config.yaml: yaml: unmarshal errors:
>   line 40: field shared_store not found in type compactor.Config
> ```
> 
> Updated from last 5.X.X to 6.0.0 Chart version.

Use `delete_request_store` instead of `shared_store`. Please refer to the details for more information [Upgrade Loki](https://grafana.com/docs/loki/latest/setup/upgrade/#removed-shared_store-and-shared_store_key_prefix-from-compactor-configuration)

**Comment by sbrodriguez** [comment]
It works using that key, with other new changes like v13 schemaConfig and other keys removed like enforce_metric_name.
Reading the URL all problems could be done.
Thanks @BilikoX

**Comment by userbox020** [comment]
hi, i know nothing about how loki internally works, but i guess the latest docker image had some bug with the new loki update and its fix know, because i deleted again the container and download latest and start working like nothing happens.
Im glad loki working now, its very helpfull to see logs and findout whats going on with my running software

**Comment by papdaniel** [comment]
Wow, the message `field shared_store not found in type compactor.Config` quiet misleading. I was like: but it's there, what's wrong? 
I think something like `field shared_store is invalid in type compactor.Config` would be clearer
