### ISSUE TITLE
Add 'level' to the LogQL-filter

### ISSUE THREAD

**Issue by Zenlil** [grafana/loki#1256]
We have a a few k8-clusters and a large number of microservices in these all logging nicely in JSON and would like to create a dashboard in Grafana with a LogQL like: {cluster="prod",level>"info"}

This would then return the last log-rows with state "warning" or more severe.

**Comment by cyriltovena** [comment]
Hey @Zenlil,

How about `{cluster="prod",level=~"warning|error|fatal"}` ?

**Comment by Zenlil** [comment]
Would work too, but right now (0.4.0) adding level to the LogQL dont work at all.
It just ignores anything i write regarding "level".

**Comment by cyriltovena** [comment]
do you have a level label ? You should definitely have one using this feature : https://github.com/grafana/loki/blob/master/docs/clients/promtail/pipelines.md

**Comment by Zenlil** [comment]
I'm using the default helm-chart v0.17.1 with loki v0.4.0. Running Grafana 6.4.4
All my services send the "level" property.

When in Grafana-Explore UI i type: {cluster="dev"}
I then get 100 rows of different levels. These are indicated both in the timeline-graph and below in the legend.
Clicking an level in the legend does filter on that specific level. Clicking again removes that filter.
Changing the LogQL-expression to: {cluster="dev",level="info"} gives me 0 rows, always.
Changing the "info" to different values all yield 0 rows. Only when i revert to the first expression do I get any rows.

**Comment by cyriltovena** [comment]
Can you post the json response result from the query without the level label?

You can find it in the dev network tab of your browser.

**Comment by Zenlil** [comment]
[loki-request-response.txt](https://github.com/grafana/loki/files/3855520/loki-request-response.txt)

I've attached a file describing the request and response (clean it out a bit for similar log-lines)

I've also noted that in Grafana each log-line has a prefeixed color indicating the level, but when toggling the "labels" chekbox I get all labels except "level" for each line.

**Comment by cyriltovena** [comment]
You don’t have the level label, that’s why you can’t filter on it, please refer to my previous comment.

**Comment by pedroetb** [comment]
> do you have a level label ? You should definitely have one using this feature : https://github.com/grafana/loki/blob/master/docs/clients/promtail/pipelines.md

updated link: https://github.com/grafana/loki/blob/main/docs/sources/clients/promtail/pipelines.md
