### ISSUE TITLE
Issue deploy Loki using Helm chart 6.1.0 with Azure storage

### ISSUE THREAD

**Issue by gzk120** [grafana/loki#12606]
**Describe the bug**
I am trying to upgrade loki but getting issue with Azure storage but same configuration working with aws s3

*Error:*

`level=error ts=2024-04-14T09:43:19.887071998Z caller=log.go:216 msg="error running loki" err="init compactor: failed to init delete store: Get \"https://.blob.core.windows.net/loki/index/delete_requests/delete_requests.gz?timeout=31\": 3 errors occurred:\n\t* dial tcp: lookup .blob.core.windows.net: no such host\n\t* dial tcp: lookup .blob.core.windows.net: no such host\n\t* dial tcp: lookup .blob.core.windows.net: no such host\n\n\nerror initialising module: compactor\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:138\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/loki/v3/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:453\nmain.main\n\t/src/loki/cmd/loki/main.go:122\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650"`

**it works fine if i use S3 bucket and configrations**
**My Config file**
loki:
  auth_enabled: false
  query_scheduler:
    use_scheduler_ring: false
  server:
    log_level: debug
  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: azure
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  common:
    path_prefix: /var/loki
    replication_factor: 2
  distributor:
    ring:
      kvstore:
        store: memberlist
  compactor:
    working_directory: /var/loki/retention
    retention_enabled: true
    delete_request_store: azure
  storage:
    bucketNames:
      chunks: loki
      ruler: loki
      admin: loki
    type: azure
    azure:
      environment: "env"
      container_name: "loki"
      account_name: "name"
      account_key: "KeyGoesHere"
      use_managed_identity: false
    filesystem:
      directory: /var/loki/chunks
  storage_config:
    tsdb_shipper:
      active_index_directory: /var/loki/index
      cache_location: /var/loki/index_cache
      cache_ttl: 48h
      index_gateway_client:
        server_address: '{{ include "loki.indexGatewayAddress" . }}'
  limits_config:
    deletion_mode: filter-and-delete
  ingester:
    chunk_encoding: snappy
    wal:
      dir: /var/loki/wal
  analytics:
    reporting_enabled: false
  tracing:
    enabled: true
  querier:
    max_concurrent: 4
deploymentMode: SimpleScalable
lokiCanary:
  enabled: false
test:
  enabled: false
chunksCache:
  enabled: false
backend:
  replicas: 2
read:
  replicas: 2
write:
  replicas: 2
minio:
  enabled: false
singleBinary:
  replicas: 0
ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 2
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
ruler:
  enabled: false

**Comment by bslpzk** [comment]
Helm gives an error due to missing variables for Azure, cause developers changed the variable names since Chart moved to version 6.0.0+.
You can check the current values for azure blob, for example, [see here.](https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml#L337-L345) 
You should also realize that the `container_name` value no longer exists - the `bucketNames` section is used instead.
Here is an example of the simplest configuration for azure blob:
```yaml
loki:
  storage:
    azure:
      accountKey: < account_key >
      accountName: < account_name >
      endpointSuffix: < if you need it >
    bucketNames:
      admin: < container_name >
      chunks: < container_name >
      ruler: < container_name >
    type: azure
```

**Comment by gzk120** [comment]
i created  container for chunks, and loki in storage. i was using the wrong names container_name. make sure you have enough permission to read and write to storage.
