### ISSUE TITLE
Enabling pattern_ingester leads to errors in loki-write

### ISSUE THREAD

**Issue by rknightion** [grafana/loki#12691]
**Describe the bug**
When setting pattern_ingester.enabled to true in the latest chart that [implemented the feature](https://github.com/grafana/loki/pull/12685), the loki-write pods are filled with the following:
```
level=error ts=2024-04-19T10:04:55.069123188Z caller=tee.go:53 component=pattern-tee msg="failed to send stream to pattern ingester" err="empty ring"
level=error ts=2024-04-19T10:04:55.069189015Z caller=tee.go:53 component=pattern-tee msg="failed to send stream to pattern ingester" err="empty ring"
```
This is in SSD mode. 
**To Reproduce**
Set
```
  pattern_ingester:
    enabled: true
```
In the values file on the latest chart. 
**Expected behavior**
Pattern_ingester works

**Comment by cyriltovena** [comment]
Can you share the config you're using, the full one please ? It seems to works for me and some other users.

**Comment by cyriltovena** [comment]
ho you need the latest image ! it doesn't work with 3.0.0
