### ISSUE TITLE
logstash-output-loki-1.1.0

### ISSUE THREAD

**Issue by wlyu** [grafana/loki#12719]
Unknown setting 'metadata_fields' for loki
 
 #metadata_fields => ["trace_id"] #default empty array, no structure metadata will be included
 
 
 anyone know?

**Comment by wlyu** [comment]
Version 1.2.0 and greater of this plugin you can also specify a structured metadata via the `metadata_fields` configuration.

**Comment by tiantangkuohai** [comment]
How to install >= 1.2.0 version in logstash?

**Comment by devcrops-official** [comment]
Same here, I can't find version 1.2.0 and the command 
`logstash-plugin install --version 1.2.0 logstash-output-loki`
return:
```
Plugin logstash-output-loki version 1.2.0 does not exist
```

**Comment by vlad-diachenko** [comment]
> Same here [@wlyu](https://github.com/wlyu) , I can't find the version 1.2.0, and the command
> 
> `logstash-plugin install --version 1.2.0 logstash-output-loki`
> 
> return:
> 
> ```
> Plugin logstash-output-loki version 1.2.0 does not exist
> ```

The new version of GEM has been published 
https://rubygems.org/gems/logstash-output-loki/versions/1.2.0
