### ISSUE TITLE
Despite providing "schema_config" in Values.Yaml, keep getting error: You must provide a schema_config for Loki

### ISSUE THREAD

**Issue by ajmal-yazdani** [grafana/loki#12711]
**Describe the bug**
 **helm upgrade --install loki -n grafana grafana/loki -f .\values.yaml**
Release "loki" does not exist. Installing it now.
**Error**: execution error at (loki/templates/validate.yaml:40:4): You must provide a schema_config for Loki, one is not provided as this will be individual for every Loki cluster. See https://grafana.com/docs/loki/latest/operations/storage/schema/ for schema information. For quick testing (with no persistence) add `--set loki.useTestSchema=true`

**To Reproduce**
1. Install basic grafana/loki helm chart 

**Expected behavior**
It's should take "schema_config" from Values.YAML file and should not generate the error.

**Environment:**
 - Infrastructure: Kubernetes (AKS)
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**

**Values.YAML**
loki:
  auth_enabled: false
  **schema_config:**
    configs:
      - from: "2020-12-11"
        index:
          period: 24h
          prefix: index_
        object_store: azure
        schema: v11
        store: boltdb-shipper
  storage:
    bucketNames:
      chunks: loki
    type: azure
    azure:
      accountName: ${AZURE_ACCOUNT_NAME}
      accountKey: ${AZURE_ACCOUNT_KEY}
  extraArgs:
    - "-config.expand-env=true"
  extraEnvFrom:
    - secretRef:
        name: loki-azure-credentials
write:
  extraArgs:
    - "-config.expand-env=true"
  extraEnvFrom:
    - secretRef:
        name: loki-azure-credentials
read:
  extraArgs:
    - "-config.expand-env=true"
  extraEnvFrom:
    - secretRef:
        name: loki-azure-credentials
backend:
  extraArgs:
    - "-config.expand-env=true"
  extraEnvFrom:
    - secretRef:
        name: loki-azure-credentials

**Comment by ajmal-yazdani** [comment]
After changing from "schema_config" to "schemaConfig", it's works. lol :) huge documentation issues.

**Comment by banoleb** [comment]
the correct option is
```
loki:
  auth_enabled: false
  schemaConfig:
    configs:
      - from: "2022-01-11"
        index:
          period: 24h
          prefix: loki_ye
        object_store: s3
        schema: v12
        store: boltdb-shipper
```

I was completely discouraged

**Comment by nedstb** [comment]
seriously. schema_config -> schemaConfig.  was that mentioned anywhere,  what other yaml keys have changed ?

**Comment by csyyy106** [comment]
Good. It works for me
