### ISSUE TITLE
Docs feedback: /docs/sources/setup/install/helm/reference.md

### ISSUE THREAD

**Issue by woody1872** [grafana/loki#12738]
This page is really unusable the way it is being rendered, see below:

![Screenshot 2024-04-22 at 22 48 48](https://github.com/grafana/loki/assets/26095602/2c9ced5f-86fc-48ef-8ee1-a1af57585066)

The contents of the table are extremely wide and the horizontal scrollbar is barely working.

There is an awful lot of unused space on the screen which would be very nice to use here.

**Comment by DylanGuedes** [comment]
Thanks for your report. I opened a PR tackling it. FYI: there's a `expand table` button that makes it a little better (in case you haven't used it).

![image](https://github.com/grafana/loki/assets/7079397/02c8ff23-b853-4e7d-8702-3dadc3fa238e)
