### ISSUE TITLE
Permission denied loki components

### ISSUE THREAD

**Issue by brunodeoliveiramacedo** [grafana/loki#12797]
I am using Loki operator 0.6.0.

I am getting this error for index-gateway, ingester and compactor.

level=error ts=2024-04-26T01:41:45.697144768Z caller=log.go:230 msg="error running loki" err="mkdir /tmp/loki/index_cache: permission denied\nerror creating index client\ngithub.com/grafana/loki/pkg/storage.(*store).storeForPeriod\n\t/src/loki/pkg/storage/store.go:295\ngithub.com/grafana/loki/pkg/storage.(*store).init\n\t/src/loki/pkg/storage/store.go:177\ngithub.com/grafana/loki/pkg/storage.NewStore\n\t/src/loki/pkg/storage/store.go:155\ngithub.com/grafana/loki/pkg/loki.(*Loki).initStore\n\t/src/loki/pkg/loki/modules.go:690\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:136\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:461\nmain.main\n\t/src/loki/cmd/loki/main.go:110\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650\nerror initialising module: store\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:138\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:461\nmain.main\n\t/src/loki/cmd/loki/main.go:110\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650"

**Comment by hogisim314** [comment]
I got an error from compactor, index-gateway, ingestor too. 
I don't know how to solve this. Did you solve it?

**Comment by brunooliveiramac** [comment]
> I got an error from compactor, index-gateway, ingestor too. I don't know how to solve this. Did you solve it?

Rolled back to an older version loki:2.8.2

Then I'm patching:

```
kubectl patch statefulset lokistack-prod-index-gateway --namespace loki --patch '{
  "spec": {
    "template": {
      "spec": {
        "initContainers": [
          {
            "name": "fix-permissions",
            "image": "busybox:latest",
            "command": [
              "sh",
              "-c",
              "id; ls -la /tmp/; mkdir -p /tmp/loki; chown 10001:10001 /tmp/loki; mkdir -p /tmp/wal; chown 10001:10001 /tmp/wal; mkdir -p /tmp/loki/rules; chown 10001:10001 /tmp/loki/rules; mkdir -p /tmp/loki/index; chown 10001:10001 /tmp/loki/index;"
            ],
            "imagePullPolicy": "Always",
            "securityContext": {
              "privileged": true,
              "runAsUser": 0,
              "runAsGroup": 0,
              "runAsNonRoot": false
            },
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "volumeMounts": [
              {
                "name": "storage",
                "mountPath": "/tmp/loki"
              }
            ]
          }
        ]
      }
    }
  }
}' --type merge

```

The patch doesn't work in Loki 3.0.0

**Comment by calinah** [comment]
I'm also experiencing this error with Loki Operator v0.8.0 and Loki v3.4.2. Since this issue was previously closed, could you please clarify the recommended fix, @periklis? Reverting to older versions doesn’t seem like a sustainable solution, so I’d really appreciate any guidance on how to address this in the current releases.

**Comment by brunodeoliveiramacedo** [comment]
just abandon the operator and use the helm chart.
It's way simple and flexible.
