### ISSUE TITLE
[v0.4.0] Unrecognized storage client dynamodb

### ISSUE THREAD

**Issue by Tzrlk** [grafana/loki#1281]
**Describe the bug**
When following the configuration reference, the comment above `schema_config.configs[*].store` says:
```yaml
# Which store to use for the index. Either cassandra, bigtable, dynamodb, or
# boltdb
store: <string>
```
However, when running loki with dynamodb as the client, the following message is sent to the logs:
```
level=error ts=2019-11-19T00:52:11.372697769Z caller=main.go:65 msg="error initialising loki" err="error initialising module: table-manager: Unrecognized storage client dynamodb, choose one of: aws, cassandra, inmemory, gcp, bigtable, bigtable-hashed"
```

**To Reproduce**
1. In an aws dynamodb-backed deployment, set the schema config store type to `dynamodb` as per the documentation.

**Expected behavior**
Starting up and using the dynamodb config was expected.

**Environment:**
 - Infrastructure: Kubernetes, EKS, AWS
 - Deployment tool: Helm

**Screenshots, Promtail config, or terminal output**
![image](https://user-images.githubusercontent.com/169667/69107021-f7811d80-0ad4-11ea-8e39-5d175241cc4c.png)

**Comment by slim-bean** [comment]
Hey @Tzrlk, it looks like that comment is wrong :(

https://github.com/cortexproject/cortex/blob/ed7c302fd96892b1c4c822a6ccd60317fde51c00/pkg/chunk/storage/factory.go#L182

Looks like you would need to use `aws`  

This is confusing, will leave this issue open to see if we can tidy this up some.
