### ISSUE TITLE
Query frontend is getting panic when queried for labels after upgrading to v3.0.0

### ISSUE THREAD

**Issue by rakheshkumbi** [grafana/loki#12842]
**Describe the bug**
I have upgraded all the Loki components (microservice mode) from 2.9.5 to 3.0.0. All the components are up and running and no error logs observed. When I query Loki for labels from grafana (Under Explore -> Label Filters), the query frontend is getting panic. With the same configuration when I role back to v2.9.5, I am able get the response and no panic is observed.

**To Reproduce**
1. Started all the Loki components (v3.0.0)
2. Query for labels from Grafana

**Expected behavior**
Loki should return the labels.

**Environment:**
 - Infrastructure: VM
 - Deployment tool: internal

**Screenshots, Promtail config, or terminal output**
Query frontend logs:
GET /loki/api/v1/labels?start=1714474823903000000&end=1714478423903000000 (500) 1.005608ms Response: \"error while processing request: runtime error: invalid memory address or nil pointer dereference

Apr 30 14:15:50      loki-3.0.0[324329]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 30 14:15:50      loki-3.0.0[324329]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x22c8d5f]
Apr 30 14:15:50      loki-3.0.0[324329]: goroutine 181236 [running]:
Apr 30 14:15:50      loki-3.0.0[324329]: github.com/grafana/loki/v3/pkg/lokifrontend/frontend.downstreamRoundTripper.Do({0xc000bbebd0, {0x32314e0, 0x48f6180}, {0x0, 0x0}}, {0x3254d88, 0xc0090b2120}, {0x32702e0, 0xc008efea00})
Apr 30 14:15:50      loki-3.0.0[324329]:         /src/loki/pkg/lokifrontend/frontend/downstream_roundtripper.go:37 +0x9f
Apr 30 14:15:50      loki-3.0.0[324329]: github.com/grafana/loki/v3/pkg/querier/queryrange/queryrangebase.retry.Do({{0x3231a60, 0xc000b8c0a0}, {0x3233d20, 0xc0009e7e30}, 0x3, 0xc000a91140}, {0x3254d88?, 0xc0090b2120}, {0x32702e0, 0xc008efea00})
Apr 30 14:15:50      loki-3.0.0[324329]:         /src/loki/pkg/querier/queryrange/queryrangebase/retry.go:86 +0x2c3
Apr 30 14:15:50      loki-3.0.0[324329]: github.com/grafana/loki/v3/pkg/querier/queryrange.NewLabelsTripperware.InstrumentMiddleware.func8.1.1({0x3254d88?, 0xc0090b2120?})
Apr 30 14:15:50      loki-3.0.0[324329]:         /src/loki/pkg/querier/queryrange/queryrangebase/instrumentation.go:28 +0x42
Apr 30 14:15:50      loki-3.0.0[324329]: github.com/grafana/dskit/instrument.CollectedRequest({0x3254d88, 0xc0090b20f0}, {0x2a6b8f9, 0x5}, {0x3249af0, 0xc000128c68}, 0x10?, 0xc008be7640)
Apr 30 14:15:50      loki-3.0.0[324329]:         /src/loki/vendor/github.com/grafana/dskit/instrument/instrument.go:172 +0x262
Apr 30 14:15:50      loki-3.0.0[324329]: github.com/grafana/loki/v3/pkg/querier/queryrange.NewLabelsTripperware.InstrumentMiddleware.func8.1({0x3254d88?, 0xc0090b20f0?}, {0x32702e0?, 0xc008efea00?})
Apr 30 14:15:50      loki-3.0.0[324329]:         /src/loki/pkg/querier/queryrange/queryrangebase/instrumentation.go:26 +0xa8
Apr 30 14:15:50      loki-3.0.0[324329]: github.com/grafana/loki/v3/pkg/querier/queryrange/queryrangebase.HandlerFunc.Do(0x3254d88?, {0x3254d88?, 0xc0090b20f0?}, {0x32702e0?, 0xc008efea00?})
Apr 30 14:15:50      loki-3.0.0[324329]:         /src/loki/pkg/querier/queryrange/queryrangebase/roundtrip.go:80 +0x37
Apr 30 14:15:50      loki-3.0.0[324329]: github.com/grafana/loki/v3/pkg/querier/queryrange.NewLabelsCacheMiddleware.NewResultsCacheMiddleware.func2.1({0x3254d88, 0xc0090b20f0}, {0x326d5c0?, 0xc008efea00})
Apr 30 14:15:50      loki-3.0.0[324329]:         /src/loki/pkg/querier/queryrange/queryrangebase/results_cache.go:147 +0x6c
Apr 30 14:15:50      loki-3.0.0[324329]: github.com/grafana/loki/v3/pkg/storage/chunk/cache/resultscache.HandlerFunc.Do(0x3254d88?, {0x3254d88?, 0xc0090b20f0?}, {0x326d5c0?, 0xc008efea00?})
Apr 30 14:15:50      loki-3.0.0[324329]:         /src/loki/pkg/storage/chunk/cache/resultscache/util.go:11 +0x37
Apr 30 14:15:50      loki-3.0.0[324329]: github.com/grafana/loki/v3/pkg/storage/chunk/cache/resultscache.ResultsCache.Do({{0x3231a60, 0xc000b8c0a0}, {0x3233020, 0xc0009f9f50}, {0x3255178, 0xc00061a2d0}, {0x7f6cbfdca488, 0xc000569b78}, {0x32336a0>
Apr 30 14:15:50      loki-3.0.0[324329]:         /src/loki/pkg/storage/chunk/cache/resultscache/cache.go:112 +0xb45
Apr 30 14:15:50      loki-3.0.0[324329]: github.com/grafana/loki/v3/pkg/querier/queryrange/queryrangebase.resultsCache.Do({0xc000914fd0, {0x3231a60, 0xc000b8c0a0}, {0x323fd60, 0xc0008952c0}, 0xc0006e9098}, {0x3254d88, 0xc0090b20c0}, {0x32702e0, >
Apr 30 14:15:50      loki-3.0.0[324329]:         /src/loki/pkg/querier/queryrange/queryrangebase/results_cache.go:186 +0xf3
Apr 30 14:15:50      loki-3.0.0[324329]: github.com/grafana/loki/v3/pkg/querier/queryrange.NewLabelsTripperware.InstrumentMiddleware.func7.1.1({0x3254d88?, 0xc0090b20c0?})
Apr 30 14:15:50      loki-3.0.0[324329]:         /src/loki/pkg/querier/queryrange/queryrangebase/instrumentation.go:28 +0x42
Apr 30 14:15:50      loki-3.0.0[324329]: github.com/grafana/dskit/instrument.CollectedRequest({0x3254d88, 0xc0090b2090}, {0x2a93388, 0x13}, {0x3249af0, 0xc000128c60}, 0xc0009950e4?, 0xc008be7d60)
Apr 30 14:15:50      loki-3.0.0[324329]:         /src/loki/vendor/github.com/grafana/dskit/instrument/instrument.go:172 +0x262
Apr 30 14:15:50      loki-3.0.0[324329]: github.com/grafana/loki/v3/pkg/querier/queryrange.NewLabelsTripperware.InstrumentMiddleware.func7.1({0x3254d88?, 0xc0090b2090?}, {0x32702e0?, 0xc008efea00?})
Apr 30 14:15:50      loki-3.0.0[324329]:         /src/loki/pkg/querier/queryrange/queryrangebase/instrumentation.go:26 +0xa8
Apr 30 14:15:50      loki-3.0.0[324329]: github.com/grafana/loki/v3/pkg/querier/queryrange/queryrangebase.HandlerFunc.Do(0xc009098200?, {0x3254d88?, 0xc0090b2090?}, {0x32702e0?, 0xc008efea00?})
Apr 30 14:15:50      loki-3.0.0[324329]:         /src/loki/pkg/querier/queryrange/queryrangebase/roundtrip.go:80 +0x37
Apr 30 14:15:50      loki-3.0.0[324329]: github.com/grafana/loki/v3/pkg/querier/queryrange.(*seriesLimiter).Do(0xc008efebe0, {0x3254d88, 0xc0090b2090}, {0x32702e0, 0xc008efea00})
Apr 30 14:15:50      loki-3.0.0[324329]:         /src/loki/pkg/querier/queryrange/limits.go:416 +0x86
Apr 30 14:15:50      loki-3.0.0[324329]: github.com/grafana/loki/v3/pkg/querier/queryrange.(*splitByInterval).loop(0x44549c?, {0x3254dc0, 0xc008efeb90}, 0xc009106540?, {0x3233640, 0xc008efebe0})
Apr 30 14:15:50      loki-3.0.0[324329]:         /src/loki/pkg/querier/queryrange/split_by_interval.go:162 +0x134
Apr 30 14:15:50      loki-3.0.0[324329]: created by github.com/grafana/loki/v3/pkg/querier/queryrange.(*splitByInterval).Process in goroutine 181152
Apr 30 14:15:50      loki-3.0.0[324329]:         /src/loki/pkg/querier/queryrange/split_by_interval.go:126 +0x15e
Apr 30 14:15:50      systemd[1]: loki-query-frontend.service: Main process exited, code=exited, status=2/INVALIDARGUMENT

**Comment by kavirajk** [comment]
@rakheshkumbi thanks for reporting the issue. Can you share your Loki config please? (the one caused panic on Loki 3.0, but ran fine on 2.9.5)

**Comment by rakheshkumbi** [comment]
Hi @kavirajk Thanks for the response.

Here are the flags which were used 

/usr/sbin/cos-loki-3.0.0 \
  -auth.enabled=true \
  -log.level=info \
  -config.file=/conf/loki-common.yaml \
  -runtime-config.file=/conf/loki-runtime.yaml \
  -server.grpc-max-recv-msg-size-bytes=104857600 \
  -server.grpc-max-send-msg-size-bytes=104857600 \
  -server.grpc-max-concurrent-streams=1000 \
  -server.grpc-listen-port=9141 \
  -server.http-listen-port=8141 \
  \
  -querier.max-concurrent=20 \
  -querier.compress-http-responses=true \
  -querier.align-querier-with-step=true \
  -querier.split-queries-by-interval=24h \
  -querier.max-concurrent-tail-requests=20 \
  -querier.tail-max-duration=10m \
  -querier.max-retries-per-request=3 \
  -querier.cache-results=true \
  -querier.max-query-lookback=7d \
  \
  -frontend.downstream-url=https://loki-test \
  -frontend.log-queries-longer-than=10s \
  -frontend.memcached.addresses=<xyz> \
  -frontend.memcached.max-item-size=5242880 \
  -frontend.tail-proxy-url=https://loki-test \
  -frontend.max-queriers-per-tenant=3 \
  -frontend.max-query-bytes-read=5MB \
  \
  -boltdb.shipper.active-index-directory=/local/cos-loki-query-frontend/index \
  -boltdb.shipper.cache-location=/local/cos-loki-query-frontend/boltdb-cache \
  \
  -validation.max-entries-limit=5000 \
  -validation.allow-structured-metadata=false \
  \
  -reporting.enabled=false \
  -target=query-frontend

Here is the content of loki-common.yaml

ingester:
  lifecycler:
    interface_names:
      - ens160

schema_config:
  configs:
    - from: 2021-11-15
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: loki_index_
        period: 24h
    - from: 2024-03-07
      store: boltdb-shipper
      object_store: s3
      schema: v13
      index:
        prefix: loki_index_
        period: 24h

storage_config:
  aws:
    access_key_id: <xyz>
    secret_access_key: <xyz>

limits_config:
  allow_structured_metadata: false

common:
  compactor_address: http://<xyz>

#According to Loki v3.0.0 compactor.delete-request-store should be explicitly configured if retention is enabled
compactor:
  working_directory: <xyz>
  delete_request_store: s3

analytics:
  reporting_enabled: false

Here is the runtime config:

overrides:
  xyz:
    retention_period: 45d
    max_query_lookback: 45d

**Comment by rakheshkumbi** [comment]
Hi @kavirajk Thanks for the fix, I am validating it. will update once I test the fix.
