### ISSUE TITLE
Promtail: Grafana Cloud

### ISSUE THREAD

**Issue by CEikermann** [grafana/loki#1284]
Hello,

we are currently trying out to use the promtail helm chart to use it with manged Loki instance by Grafana Cloud.

It seems the client.url is hardcoded to "http://promtail-loki:3100/loki/api/v1/push" - but grafana cloud needs "https://<instanceId>:<apiKey>@<instanceUrl>/api/prom/push"

Is there a way we can set the client url via helm chart?

Best regards,
Christian

**Comment by Eraac** [comment]
@CEikermann you can set this values

* `loki.serviceScheme` -> http/https
* `loki.user` & `loki.password` (basic auth), but care if you have any special character (like `:`)
* `loki.serviceName` -> domain
* `loki.servicePort`

**Comment by CEikermann** [comment]
ah okay thanks for the info, yeah talking about the URI part ;)
Will check out to make a PR.

**Comment by slim-bean** [comment]
Hey @CEikermann! The `/loki/api/v1/push` should work for hosted-grafana. I think we just need to get the right variables @Eraac defined setup for you.  Can you reach out to the Grafana Cloud support to have them help you get setup?

**Comment by cstyan** [comment]
@CEikermann please reach out to support or open a new issue if you are still having issues with helm charts
