### ISSUE TITLE
Unable to disable stream sharding via CLI

### ISSUE THREAD

**Issue by nehaev** [grafana/loki#12904]
**Describe the bug**
The documentation on stream sharding config (https://grafana.com/docs/loki/latest/configure/#limits_config, see `shard_streams`) lacks a CLI flag that can be used to disable this feature.

**Expected behavior**
A CLI flag for disabling stream sharding is defined.

**Comment by DylanGuedes** [comment]
`shard-streams.enabled` should do it, but yeah, we lacked documenting it. I'll close the issue for now but I'm adding to my backlog to document it.
