### ISSUE TITLE
Mismatch in count of OTel attributes to index and default label limit

### ISSUE THREAD

**Issue by lindeskar** [grafana/loki#12913]
**Describe the bug**
The count of OTel attributes to index (17) and the default label limit (15) do not match:

https://github.com/grafana/loki/blob/19fef9355fdd46911611dbec25df0f5a4e397d31/docs/sources/shared/configuration.md?plain=1#L2008-L2011

https://github.com/grafana/loki/blob/19fef9355fdd46911611dbec25df0f5a4e397d31/docs/sources/shared/configuration.md?plain=1#L2896-L2898

The 17 OTel resource attributes are also listed in the docs, which mentions the old default limit (`max_label_names_per_series: 30`):

https://github.com/grafana/loki/blob/19fef9355fdd46911611dbec25df0f5a4e397d31/docs/sources/send-data/otel/_index.md?plain=1#L75-L92

**To Reproduce**
1. Read the docs

**Expected behavior**
The count of attributes and labels match.

**Environment:**
 - https://grafana.com/docs/loki/v3.0.x/configure/
 - https://grafana.com/docs/loki/v3.0.x/send-data/otel/#format-considerations

**Screenshots, Promtail config, or terminal output**
-

**Comment**
I would have created a PR to fix the docs, but I suspect this might lead to a default config change?

**Comment by lindeskar** [comment]
Maybe the idea was that all attributes will never be used at once? (Deployment / StatefulSet / DaemonSet / ...)

If so, this issue is just reporting the old limit in:

https://github.com/grafana/loki/blob/19fef9355fdd46911611dbec25df0f5a4e397d31/docs/sources/send-data/otel/_index.md?plain=1#L75-L92

**Comment by sandeepsukhani** [comment]
> Maybe the idea was that all attributes will never be used at once? (Deployment / StatefulSet / DaemonSet / ...)

Yeah, not all attributes will be set at once. Some of them are mutually exclusive.

> If so, this issue is just reporting the old default limit (30) in:

Yeah, it was a mistake. I think I referenced the old limit, which was 30 earlier. Thanks for pointing it out! I will fix it.
