### ISSUE TITLE
no logs found while data can be seen in live stream in grafana cloud

### ISSUE THREAD

**Issue by chesha1** [grafana/loki#12935]
Logs are sent to loki and grafana in cloud, they can be seen in live stream mode, and the labels they brought appear.

However, the logs themself disappear.

The request body is below, the logs are sent to loki by raw http request.
```
{
	"streams": [
		{
			"stream": {
				"app": "test",
				"namespace": "test2"
			},
			"values": [
				[
					"1715313600000000000",
					"{\"level\":\"info\",\"message\":\"Hello world!\"}"
				],
				[
					"1715313600000000000",
					"{\"level\":\"info\",\"message\":\"Hello world!\"}"
				]
			]
		}
	]
}
```

They can be seen in live stream:
![image](https://github.com/grafana/loki/assets/49867392/656b716c-b12c-4d95-bbfc-550dfac5d7a8)

But they disappeared when querying:
![image](https://github.com/grafana/loki/assets/49867392/293150a5-8c19-44c0-b5a3-23ad2396fea8)

The query time rangeis correct, I use the the last 7 days option.

**Comment by paul1r** [comment]
The data you sent via the `curl` command is in the `test2` namespace, but your query is in the `test3` namespace.   Could this be what you are running into?

**Comment by chesha1** [comment]
> The data you sent via the `curl` command is in the `test2` namespace, but your query is in the `test3` namespace. Could this be what you are running into?

No, I have tried `test`, `test2`, `test3`, every possible logql sentence finds nothing.

By the way, label selector can find the label shortly after the data was sent. But after a long time, the label selector found nothing either. It seems like logs has some default expiration period.

I don't know whether the above phenomenon show more evidence to find the reason behind it

**Comment by paul1r** [comment]
May I access your instance?

**Comment by chesha1** [comment]
> May I access your instance?

Sure, but please give me an e-mail address, I'll send account and password to you.
If you do not want to leak e-mail address to public access, you could send an e-mail to chesha1@163.com to get me know.

**Comment by paul1r** [comment]
No worries, I work here, just needed your permission to access. :)

I logged in and definitely was able to reproduce what you are seeing.  I also have been experimenting with my own Grafana cloud instance.

I wonder if there's a slight error with the curl command? 

I was running `curl -v  -H "Content-Type: application/json" -POST -s "$LOKI_URL/loki/api/v1/push" -d @test.json` and was able to see my logs pushed successfully.  
Can you post the output of that for yourself?

**Comment by chesha1** [comment]
> No worries, I work here, just needed your permission to access. :)
> 
> I logged in and definitely was able to reproduce what you are seeing. I also have been experimenting with my own Grafana cloud instance.
> 
> I wonder if there's a slight error with the curl command?
> 
> I was running `curl -v -H "Content-Type: application/json" -POST -s "$LOKI_URL/loki/api/v1/push" -d @test.json` and was able to see my logs pushed successfully. Can you post the output of that for yourself?
> 
> For reference, my `test.json` contained:
> 
> ```
> {
>     "streams": [
>         {
>             "stream": {
>                 "label3": "value1"
>             },
>             "values": [
>                 ["1715369732907106983", "log message 1"]
>             ]
>         }
>     ]
> }
> ```


I have run the same curl as yours, but once again new labels appeared in grafana, but the logs themself cannot be queried.

And the loki url I used is `https://787766:glc_eyJvIj---{some characters hidden here}-----0xIn19@logs-prod-020.grafana.net/loki/api/v1/push`

Below is the response after curl, it may help find the resaon:
```
*   Trying 54.251.81.84:443...
* TCP_NODELAY set
* Connected to logs-prod-020.grafana.net (54.251.81.84) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=New York; L=New York; O=Raintank Inc.; CN=grafana.com
*  start date: Feb  2 00:00:00 2024 GMT
*  expire date: Mar  4 23:59:59 2025 GMT
*  subjectAltName: host "logs-prod-020.grafana.net" matched cert's "*.grafana.net"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert Global G2 TLS RSA SHA256 2020 CA1
*  SSL certificate verify ok.
* Server auth using Basic with user '787766'
> POST /loki/api/v1/push HTTP/1.1
> Host: logs-prod-020.grafana.net
> Authorization: Basic Nzg3NzY2OmdsY19leUp2SWpvaU1UQXpNVGcxTnlJc0ltNGlPaUp6ZEdGamF5MDRNek0zTlRJdGFHd3RkM0pwZEdVdGJHOW5jeUlzSW1zaU9pSTFjamc0T1VaWlMwUXdNelExZDJOa05sRm5NVWxUYjBFaUxDSnRJanA3SW5JaU9pSndjbTlrTFdGd0xYTnZkWFJvWldGemRDMHhJbjE5
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 204
> 
* upload completely sent off: 204 out of 204 bytes
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Mark bundle as not supporting multiuse
< HTTP/1.1 204 No Content
< Date: Sat, 11 May 2024 03:14:17 GMT
< 
* Connection #0 to host logs-prod-020.grafana.net left intact
root@server1:~/grafana# ./command.sh 
*   Trying 54.251.81.84:443...
* TCP_NODELAY set
* Connected to logs-prod-020.grafana.net (54.251.81.84) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=New York; L=New York; O=Raintank Inc.; CN=grafana.com
*  start date: Feb  2 00:00:00 2024 GMT
*  expire date: Mar  4 23:59:59 2025 GMT
*  subjectAltName: host "logs-prod-020.grafana.net" matched cert's "*.grafana.net"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert Global G2 TLS RSA SHA256 2020 CA1
*  SSL certificate verify ok.
* Server auth using Basic with user '787766'
> POST /loki/api/v1/push HTTP/1.1
> Host: logs-prod-020.grafana.net
> Authorization: Basic Nzg3NzY2OmdsY19leUp2SWpvaU1UQXpNVGcxTnlJc0ltNGlPaUp6ZEdGamF5MDRNek0zTlRJdGFHd3RkM0pwZEdVdGJHOW5jeUlzSW1zaU9pSTFjamc0T1VaWlMwUXdNelExZDJOa05sRm5NVWxUYjBFaUxDSnRJanA3SW5JaU9pSndjbTlrTFdGd0xYTnZkWFJvWldGemRDMHhJbjE5
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 204
> 
* upload completely sent off: 204 out of 204 bytes
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Mark bundle as not supporting multiuse
< HTTP/1.1 204 No Content
< Date: Sat, 11 May 2024 03:14:33 GMT
< 
* Connection #0 to host logs-prod-020.grafana.net left intact
```

**Comment by paul1r** [comment]
I'm seeing logs in your instance now. [explore query](https://chesha1.grafana.net/explore?schemaVersion=1&panes=%7B%22ppd%22:%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bservice_name%3D%5C%22unknown_service%5C%22%7D%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%221715252629802%22,%22to%22:%221715425429802%22%7D%7D%7D&orgId=1)

![Screenshot 2024-05-11 at 7 04 43 AM](https://github.com/grafana/loki/assets/129207811/0613bd54-f6d3-43d4-be40-8fea2fb0f42c)

**Comment by chesha1** [comment]
From your link, I can now see the previous logs now. Thank you.

But there's a long delay from sending them to seeing them, is it an expected behaviour?

**Comment by chesha1** [comment]
> I'm seeing logs in your instance now. [explore query](https://chesha1.grafana.net/explore?schemaVersion=1&panes=%7B%22ppd%22:%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bservice_name%3D%5C%22unknown_service%5C%22%7D%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%221715252629802%22,%22to%22:%221715425429802%22%7D%7D%7D&orgId=1)
> 
> ![Screenshot 2024-05-11 at 7 04 43 AM](https://private-user-images.githubusercontent.com/129207811/329776371-0613bd54-f6d3-43d4-be40-8fea2fb0f42c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0Mjc0MTcsIm5iZiI6MTcxNTQyNzExNywicGF0aCI6Ii8xMjkyMDc4MTEvMzI5Nzc2MzcxLTA2MTNiZDU0LWY2ZDMtNDNkNC1iZTQwLThmZWEyZmIwZjQyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQxMTMxNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOGM1ZDgxOWMwZjYwOGJlN2E1ZWM4YjI4NjlkZTMxYzY5ZmE4ZGMwYTQzMjJkMzc4N2ZhMjdiN2JjMzk1MWVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1FG703ltuTutWPuAvMDIF3Bl1K4f4J6UeuxMy6gcYo8)

From your link, I can now see the previous logs now. Thank you.

But there's a long delay from sending them to seeing them, is it an expected behaviour?

**Comment by paul1r** [comment]
I think what you are seeing is a side effect of ingesting "old" logs.  This is very nuanced, but if you send logs that are not recent (around "now"), they are not immediately queryable.  (There's also nuances about sending items out of order too, but that isn't the issue in this case)

For a curl command, you could try using something like `"$(date +%s)"000000000` to put a current timestamp on it.

At this point though, I would recommend playing around with ingesting logs in a traditional fashion.  The `promtail` distribution within Loki is feature-complete and won't receive new updates, but is functional.  Alternatively, you could use [Grafana Alloy](https://grafana.com/docs/alloy/latest/tutorials/processing-logs/) to ingest logs.

Another possible idea would be to use this [article](https://opensource.com/article/20/10/shell-history-loki-fzf) as a guide on sending your shell history to Loki.

I'm glad you are up and running, and I hope you find value with Loki!

**Comment by paul1r** [comment]
It occurred to me that my answer may not have been entirely clear.  Generally, when ingesting logs that are "now", you'll see them and they will be queryable almost instantaneously.  What you are seeing is a side effect of "old" logs. I hope that helps.

**Comment by chesha1** [comment]
> It occurred to me that my answer may not have been entirely clear. Generally, when ingesting logs that are "now", you'll see them and they will be queryable almost instantaneously. What you are seeing is a side effect of "old" logs. I hope that helps.

Thank you very much for your help. I truly appreciate your kindness in helping me find the appropriate method to send logs to Grafana Cloud using Loki.

When I send logs with the current timestamp, everything works as expected.

**Comment by FinemechanicPub** [comment]
> What you are seeing is a side effect of "old" logs

Is there any chance this "side effect" will be fixed? The unpredictable ways of Loki are kind of frustrating. 

Now I see that when a new recent log entry is pushed to Loki, the preceding (not the one just pushed) entry is added to query results. Off by one error, really?
