### ISSUE TITLE
Docs feedback: /docs/sources/release-notes/_index.md (Broken link)

### ISSUE THREAD

**Issue by ThomasThelen** [grafana/loki#12987]
The [V3.0 release notes](https://grafana.com/docs/loki/latest/release-notes/v3.0/) link is broken.

<img width="1728" alt="Screenshot 2024-05-19 at 11 49 30 AM" src="https://github.com/grafana/loki/assets/9289652/31c08032-9ced-465c-8e40-c825c0370d28">

**Comment by JStickler** [comment]
Closing as this was fixed in https://github.com/grafana/loki/pull/12990
