### ISSUE TITLE
GO111MODULE option default value is on

### ISSUE THREAD

**Issue by zhangjianweibj** [grafana/loki#1302]
base image is golang:1.13.1-stretch, GO111MODULE option default value is on.i hava run the image:
![image](https://user-images.githubusercontent.com/18585129/69338222-a4a69200-0c9d-11ea-99d7-4fe177b11b8d.png)

and result is:
![image](https://user-images.githubusercontent.com/18585129/69338251-b5ef9e80-0c9d-11ea-9b39-a7cfa3d5ef53.png)

**Comment by rfratto** [comment]
Closed by #1303.
