### ISSUE TITLE
Alloy Exited (2) 11 seconds ago 

### ISSUE THREAD

**Issue by vince-1998** [grafana/loki#13035]
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x3d4cc7e]

goroutine 323 [running]:
github.com/grafana/alloy/internal/component/loki/source/docker/internal/dockertarget.(*Target).Stop(0xc0034dc540)
        /src/alloy/internal/component/loki/source/docker/internal/dockertarget/target.go:238 +0x1e
github.com/grafana/alloy/internal/component/loki/source/docker.(*tailer).Run(0xc001d52080, {0x8e87d40, 0xc0031a0320})
        /src/alloy/internal/component/loki/source/docker/runner.go:116 +0x2f8
github.com/grafana/alloy/internal/runner.(*Runner[...]).ApplyTasks.func2()
        /src/alloy/internal/runner/runner.go:166 +0x90
created by github.com/grafana/alloy/internal/runner.(*Runner[...]).ApplyTasks in goroutine 166
        /src/alloy/internal/runner/runner.go:163 +0x585

Failed to start alloy. How do I solve this problem

**Comment by JStickler** [comment]
Questions have a better chance of being answered if you ask them on the [community forums](https://community.grafana.com/c/grafana-loki/41).   Or maybe over in the [Alloy repo](https://github.com/grafana/alloy)?

**Comment by paul1r** [comment]
This has been addressed. You can either pin the alloy version to `1.0.0` in the docker-compose file, or update the Loki repo from main to pull in an updated docker-compose configuration.  More details are [here](https://github.com/grafana/loki/issues/13065)
