### ISSUE TITLE
Loki returns 400 code when add --step 1.96 ( float number)

### ISSUE THREAD

**Issue by huihuiy02** [grafana/loki#1305]
**Describe the bug**
Grafana returns error "rpc error: code = Code(400) desc = strconv.Atoi: parsing "3.928": invalid syntax" When I search the last 12 hours logs or more. 

**To Reproduce**
1. Started Loki and Grafana with the latest version via docker-compose 
`version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:v1.0.0
    ports:
      - "3100:3100"
    volumes:
      - /data/loki/conf:/data/loki/conf
    command: -config.file=/data/loki/conf/loki.yaml
    networks:
      - loki

  grafana:
    image: grafana/grafana:master
    ports:
      - "3000:3000"
    networks:
      - loki`
2. Log in Grafana and add Loki source
3. Query: '{job="xxx"}'  and try to change time frame from last 3 hours, 6 hours or 2 days

**Expected behavior**
You will see error below
> rpc error: code = Code(400) desc = strconv.Atoi: parsing "3.928"

**Environment:**
 - Infrastructure: running docker on instance directly
 - Deployment tool: docker-compose

**Screenshots, Promtail config, or terminal output**
<img width="827" alt="Screen Shot 2019-11-22 at 7 46 38 PM" src="https://user-images.githubusercontent.com/55412695/69403978-e0eef680-0d60-11ea-9764-440d29f2e3ae.png">

**Comment by davkal** [comment]
this is being handled in https://github.com/grafana/grafana/pull/20541
