### ISSUE TITLE
loki ingester not starting: flag not defined: -ingester.ring.instance-availability-zone

### ISSUE THREAD

**Issue by kirankumar-grootan** [grafana/loki#13061]
when installing loki 6.6.2 helm chart in distributed mode. ingesters are not starting it says
https://github.com/grafana/loki/blob/main/production/helm/loki/templates/ingester/statefulset-ingester.yaml#L90

```
loki flag provided but not defined: -ingester.ring.instance-availability-zone
Run with -help to get list of available parameters
```
as per doc i dont find any argument

this version of chart is installing loki version 3.0.0

pls make pod anti affinity as empty in chart by default
or its good to add `app.kubernetes.io/name: loki` label to affinity selector as it is getting conflicted with other ingester (mimir, tempo etc) and pod not scheduling

**Comment by Arno-Pretorius** [comment]
I am getting the same error as above and I am using Loki with Helm Chart 6.6.0 using Loki version 3.0.0

**Comment by kirankumar-grootan** [comment]
yes! as per the Loki doc this argument is available for Mimir and other Loki components but not ingester.

**Comment by Arno-Pretorius** [comment]
I created this PR because if I remove the parament from my live manifest my Ingester deploys and functions normally. https://github.com/grafana/loki/pull/13118

**Comment by Arno-Pretorius** [comment]
> Shouldn't it be `ingester.availability-zone` like in the zone-aware StatefulSets?
> 
> https://github.com/grafana/loki/blob/30df31e28b5c360ffed2dea3b47f515e4e24146d/production/helm/loki/templates/ingester/statefulset-ingester-zone-a.yaml#L103
> 
> It's also documented in: https://grafana.com/docs/loki/latest/configure/#ingester

Dis changes works I made the change in my Live manifest and the pods are running fine now.

**Comment by aliasboink** [comment]
I am getting the same error. 
It seems to make any deployment of the official Helm Chart of Grafana Loki Distributed impossible unless you fork and make changes to fix the issue.
There are two other PR's regarding this - when is it going to be fixed?

**Comment by kirankumar-grootan** [comment]
@Arno-Pretorius @lindeskar any ETA when this PR https://github.com/grafana/loki/pull/13118 will be merged

**Comment by lindeskar** [comment]
@kirankumar-grootan I also want it fixed, but I'm not a maintainer. 🤷🏻

**Comment by rlees85** [comment]
> @Arno-Pretorius @lindeskar any ETA when this PR #13118 will be merged?

When one of the two contributors who have subkitted PRs (thanks both btw) implement the requested changes ... Hopefully soon or I'll have to submit a third.

I'm not a contributor by the way, this isn't an authoritative response but its what I assume is holding it up

**Comment by Arno-Pretorius** [comment]
@lindeskar I updated the PR with the new changes and Reset the review just waiting for approval the argument is now set to "-ingester.availability-zone=zone-default"

**Comment by kirankumar-grootan** [comment]
@cyriltovena, I apologize for tagging you directly, but we haven't received any response on this issue for weeks. Could you please take a look at this issue? appreciate your help. Thank you!

**Comment by kirankumar-grootan** [comment]
6.6.6 helm chart has been published with the fix.

Thank you all for the contribution.
