### ISSUE TITLE
Wrong api endpoiont in fluent-plugin-grafana-loki

### ISSUE THREAD

**Issue by Horkyze** [grafana/loki#1307]
**Describe the bug**
Since loki 1.0.0 is now using api  `/api/v1/*` shouldnt this be reflected in here? https://github.com/grafana/loki/blob/fd25e6d180009e3fc80642f81d07e470ba6546e9/fluentd/fluent-plugin-grafana-loki/lib/fluent/plugin/out_loki.rb#L121

**Comment by slim-bean** [comment]
yes absolutely this should be updated, would you be willing to open a PR?
