### ISSUE TITLE
fluent-bit (and probably promtail): JSON maps not really a good fit for ordered record data

### ISSUE THREAD

**Issue by JensErat** [grafana/loki#1309]
**Is your feature request related to a problem? Please describe.**

I'm not entirely sure whether this should be an issue or feature request.

At least fluentd has some kind of order guarantee for key/value pairs in records, for example see the [`fluent-plugin-record-sort`](https://github.com/sampointer/fluent-plugin-record-sort).

If this is passed to the fluent-bit Loki plugin, we unmarshal the binpack'ed format to Go maps. But go maps are unsorted -- actually I stumbled over that extending some test cases for an issue I had. The test was flaky, and obviously it was golang's randomized maps feature.

The current behavior (randomized order of keys in record output) has two issues:

- for testing, which we can surely workaround but is tedious
- for querying, because unreliable order makes grepping over the log lines annoying

While one could argue that JSON does not have an order defined, this is annoying anyway. For Key-Value-output, we're sorting the keys already. Let's also do this for JSON output -- the required change is minimal, I will propose a PR shortly after.

**Describe the solution you'd like**

I proposed a minor change that at least provides a stable sort order. This enhances the current situation drastically, but is not really a correct solution in my opinion.

**Describe alternatives you've considered**

To be correct, we'd have to rewrite large portions of the code and maintain a stable order. Something like a tree type with key value support. I'm not sure whether this is important and worth the effort, though. Any thoughts on use cases where keeping order is strictly required?

**Additional context**

**Comment by cyriltovena** [comment]
I think this solved.
