### ISSUE TITLE
Standardise org/instance terminology

### ISSUE THREAD

**Issue by gouthamve** [grafana/loki#131]
In some places we are referring to a tenant as an "org" and in another place we are referring to it as an "instance". We should pick one and be consistent.

**Comment by daixiang0** [comment]
I think "instance" is better, since "org" looks like official, while at present loki demo does not support to remove.

**Comment by tomwilkie** [comment]
Org is a hangover from scope days (where the user context propagation code comes from).  User is misleading too.  Instance is what we use in the code, and tenant is sometimes used informally.  I think both instance and tentant are fine, but org and user should be banned.  Instance is preferred in the code.

**Comment by tomwilkie** [comment]
Yeah, tenant it is.

**Comment by slim-bean** [comment]
@daixiang0 would you be interested in looking at this?  This would affect code in the ingester package

**Comment by daixiang0** [comment]
@slim-bean sorry for delay reply, i would like to looking at this if you have no plan about this.
