### ISSUE TITLE
[helm] test-canary template doesn't respect test.enabled flag

### ISSUE THREAD

**Issue by aledefault** [grafana/loki#13124]
**Describe the bug**
test-canary template only checks if Loki Canary is enabled (`lokiCanary.enabled`). It should also checks `test.enabled`.

**To Reproduce**
1. Install using Helm and using a value of `test.enabled: false`

**To fix it**

```
# test-canary.yaml
...
{{- if and .enabled $.Values.lokiCanary.enabled }}
...
```

**Expected behavior**
If `test.enabled` is false, `loki-helm-test` should not be deploy.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Helm

**Comment by lindhe** [comment]
Seems like a duplicate of #12765?

**Comment by aledefault** [comment]
> Seems like a duplicate of [#12765](https://github.com/grafana/loki/issues/12765)?

Agree. Closed by [your PR](https://github.com/grafana/loki/pull/15346). Thanks!
