### ISSUE TITLE
Loki write pods in crashBackOff loop - Migrating to TSDB

### ISSUE THREAD

**Issue by kunalmehta-eve** [grafana/loki#13136]
**Describe the bug**

I am trying to migrate loki schema to TSDB here is the partial configuration of values.yaml

`loki:
  auth_enabled: false
  analytics:
    reporting_enabled: false
  storage:
    type: azure
    azure:
      accountName: ${loki_azurerm_storage_account_name}
    bucketNames:
      chunks: ${loki_chunks_azurerm_storage_container_name}
      ruler: ${loki_ruler_azurerm_storage_container_name}
      admin: ${loki_admin_azurerm_storage_container_name}

  ingester:
    max_chunk_age: 24h

  ingester_client:
    grpc_client_config:
      grpc_keepalive_time: 30s     # Adjust keepalive settings
      grpc_keepalive_timeout: 20s  # Adjust keepalive settings

  structuredConfig:
    query_range:
      # By default, Loki parallelises queries that can be split/sharded. This was a controversial change in v2.4.2
      # and causes the number of active connections to rise significantly. We don't really need this feature for our
      # current scale, so we therefore disable it. See https://github.com/grafana/loki/pull/5077/files#r781448453
      parallelise_shardable_queries: false
  server:
    # Without increasing the write timeout, long-running queries fail with a 502 Bad Gateway error
    # due to a i/o timeout in the read pod.
    http_server_write_timeout: 10m

  limits_config:
    allow_structured_metadata: false
    max_concurrent_tail_requests: 100
    discover_service_name: [ ]
  schemaConfig:
     configs:
        - from: 2022-01-11
          store: boltdb-shipper
          object_store: azure
          schema: v12
          index:
            prefix: loki_index_
            period: 24h
        - from: 2024-06-06
          store: tsdb
          object_store: azure
          schema: v13
          index:
            prefix: index_
            period: 24h

storage_config:
    tsdb_shipper:
     active_index_directory: /data/tsdb-index
      cache_location: /data/tsdb-cache
      cache_ttl: 24h
    azure:
      container_name: ${loki_chunks_azurerm_storage_container_name}
      account_name: ${loki_azurerm_storage_account_name}`

I added second item in schema configurations and storage_config block as mentioned in https://grafana.com/docs/loki/latest/setup/migrate/migrate-to-tsdb/

But deployment is failing with write pods to start :

**_level=error ts=2024-06-05T08:56:46.999593633Z caller=log.go:216 msg="error running loki" err="mkdir /data: read-only file system\nerror initialising module: store\ngithub.com/grafana_**

**To Reproduce**
Using loki helm chart 6.0.0

**Expected behavior**

**Environment:**
 - Azure Kubernetes Service
 - Deployment tool: Helm

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by kunalmehta-eve** [comment]
@cyriltovena @owen-d  Please suggest

**Comment by JStickler** [comment]
Questions have a better chance of being answered if you ask them on the [community forums](https://community.grafana.com/c/grafana-loki/41).
