### ISSUE TITLE
IO Read full | IO wait  in Loki ( Memory keeps growing)

### ISSUE THREAD

**Issue by huihuiy02** [grafana/loki#1319]
**Describe the bug**
I use docker-compose to run loki in a server with 2vcpu and 8G memory. For production load, I tried to run a load testing and see how much resources Loki will consumed. 

Loki crashed due to IO Read full and IO wait.   Just curious here, Loki will create the chunks in memory. Still enough memory there.  Why Loki try to read data from the disk? 

BTW: We store all the index in Google bigtable and all data in GCS bucket. 

**To Reproduce**
1. Started Loki (SHA or version)
2. Started Promtail (SHA or version) to tail '...'
3. Query: `{} term`
`version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - /data/loki/conf:/data/loki/conf
    command: -config.file=/data/loki/conf/loki.yaml
    networks:
      - loki

  grafana:
    image: grafana/grafana:master
    ports:
      - "3000:3000"
    networks:
      - loki`

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

> loki_1     |
loki_1     | goroutine 6095 [IO wait, 4 minutes]:
loki_1     | internal/poll.runtime_pollWait(0x7fcd22f8d250, 0x72, 0xffffffffffffffff)
loki_1     | 	/usr/local/go/src/runtime/netpoll.go:184 +0x55
loki_1     | internal/poll.(*pollDesc).wait(0xc007c97318, 0x72, 0x8000, 0x8000, 0xffffffffffffffff)
loki_1     | 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
loki_1     | internal/poll.(*pollDesc).waitRead(...)
loki_1     | 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
loki_1     | internal/poll.(*FD).Read(0xc007c97300, 0xc0044b0000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
loki_1     | 	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x1cf
loki_1     | net.(*netFD).Read(0xc007c97300, 0xc0044b0000, 0x8000, 0x8000, 0x0, 0x800010601, 0x0)
loki_1     | 	/usr/local/go/src/net/fd_unix.go:202 +0x4f
loki_1     | net.(*conn).Read(0xc00000e7e8, 0xc0044b0000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
loki_1     | 	/usr/local/go/src/net/net.go:184 +0x68
loki_1     | bufio.(*Reader).Read(0xc000077680, 0xc00014e658, 0x9, 0x9, 0x4c47fa, 0x8000000000000000, 0x1881c03a1c5)

**Comment by slim-bean** [comment]
I don't think this was disk related, glancing at that stack it seems more like the network I/O was the bottleneck

**Comment by huihuiy02** [comment]
That's wired. I'm running N1 machine. From the monitoring, the network shouldn't be a bottleneck. 


<img width="738" alt="Screen Shot 2019-11-26 at 10 47 07 AM" src="https://user-images.githubusercontent.com/55412695/69581646-bee4c500-103b-11ea-96b9-5bee039900a6.png">

**Comment by huihuiy02** [comment]
I tested the network throughput as below. 

> ------------------------------------------------------------
Server listening on TCP port 5001
TCP window size:  128 KByte (default)
------------------------------------------------------------



[  4] local 10.128.15.196 port 5001 connected with 10.128.0.8 port 58706
[ ID] Interval       Transfer     Bandwidth
[  4]  0.0-10.0 sec  6.88 GBytes  5.90 Gbits/sec


It can hit 125 MB maximum. 

<img width="577" alt="Screen Shot 2019-11-26 at 11 21 04 AM" src="https://user-images.githubusercontent.com/55412695/69583081-eb4e1080-103e-11ea-8346-75df20e7e26e.png">

**Comment by huihuiy02** [comment]
I'm pretty sure the disk IO is the bottleneck. I  run the Loki on the instance directly instead of using docker for performance.  It still crashed after a high IO read as below.  

<img width="1409" alt="Screen Shot 2019-11-27 at 7 44 27 AM" src="https://user-images.githubusercontent.com/55412695/69662907-1a6d8c00-10ea-11ea-8a37-d22222a40b7b.png">

`limits_config:
  ingestion_rate_mb: 10
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h`

**Comment by huihuiy02** [comment]
BTW:  As per GCP documentation, the IOPS for my current SSD-based instance is around 6000 IOPS.   I'm curious what Loki is doing for the disk seed?   All the chunk data is stored in memory and flush to the backend storage in the GCS bucket.

**Comment by slim-bean** [comment]
Loki wouldn't be using any disk that I'm aware of if you have configured remote storage for chunks and index.

I still believe from the stack trace you pasted the I/O issue is around network not disk:

```
loki_1 | net.(*conn).Read(0xc00000e7e8, 0xc0044b0000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
loki_1 | /usr/local/go/src/net/net.go:184 +0x68
```

**Comment by slim-bean** [comment]
can you paste the full stack trace, full config file, and explain a little more detailed how you are doing the load testing?

**Comment by huihuiy02** [comment]
I'm trying to load testing against our application which generates lots of logs in a period of time.  The promtail  will send all logs to the Loki. 
The config file for Loki:
```
auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s

schema_config:
  configs:
  - from: 2018-04-15
    store: bigtable
    object_store: gcs
    schema: v9
    index:
      prefix: loki_index_
      period: 168h

storage_config:
  bigtable:
    instance: staging-loki
    project: xxxxx
  gcs:
    bucket_name: xxxxx

limits_config:
  ingestion_rate_mb: 10
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0

table_manager:
  chunk_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  index_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  retention_deletes_enabled: false
  retention_period: 672h
```

The full stack trace looks like as below: 

> loki_1     | goroutine 328 [IO wait]:
> loki_1     | internal/poll.runtime_pollWait(0x7f0f7127c590, 0x72, 0xffffffffffffffff)
> loki_1     | 	/usr/local/go/src/runtime/netpoll.go:184 +0x55
> loki_1     | internal/poll.(*pollDesc).wait(0xc0000ae798, 0x72, 0x8000, 0x8000, 0xffffffffffffffff)
> loki_1     | 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
> loki_1     | internal/poll.(*pollDesc).waitRead(...)
> loki_1     | 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
> loki_1     | internal/poll.(*FD).Read(0xc0000ae780, 0xc000540000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
> loki_1     | 	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x1cf
> loki_1     | net.(*netFD).Read(0xc0000ae780, 0xc000540000, 0x8000, 0x8000, 0x0, 0x800000601, 0x0)
> loki_1     | 	/usr/local/go/src/net/fd_unix.go:202 +0x4f
> loki_1     | net.(*conn).Read(0xc000112008, 0xc000540000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
> loki_1     | 	/usr/local/go/src/net/net.go:184 +0x68
> loki_1     | bufio.(*Reader).Read(0xc0004accc0, 0xc000597458, 0x9, 0x9, 0xc000c0ad10, 0x40caf8, 0x20)
> loki_1     | 	/usr/local/go/src/bufio/bufio.go:226 +0x26a
> loki_1     | io.ReadAtLeast(0x1bf97c0, 0xc0004accc0, 0xc000597458, 0x9, 0x9, 0x9, 0xc000c0adc8, 0xc000c0ad70, 0xc000c0ae38)
> loki_1     | 	/usr/local/go/src/io/io.go:310 +0x87
> loki_1     | io.ReadFull(...)
> loki_1     | 	/usr/local/go/src/io/io.go:329
> loki_1     | golang.org/x/net/http2.readFrameHeader(0xc000597458, 0x9, 0x9, 0x1bf97c0, 0xc0004accc0, 0x0, 0x18700000000, 0xc1025f90c0, 0x20)
> loki_1     | 	/src/loki/vendor/golang.org/x/net/http2/frame.go:237 +0x87
> loki_1     | golang.org/x/net/http2.(*Framer).ReadFrame(0xc000597420, 0xc1025f90c0, 0xc1025f90c0, 0x0, 0x0)
> loki_1     | 	/src/loki/vendor/golang.org/x/net/http2/frame.go:492 +0xa1
> loki_1     | google.golang.org/grpc/internal/transport.(*http2Server).HandleStreams(0xc0003dea80, 0xc000179080, 0x1955d30)
> loki_1     | 	/src/loki/vendor/google.golang.org/grpc/internal/transport/http2_server.go:451 +0x9e
> loki_1     | google.golang.org/grpc.(*Server).serveStreams(0xc00022cd80, 0x1c4c3e0, 0xc0003dea80)
> loki_1     | 	/src/loki/vendor/google.golang.org/grpc/server.go:718 +0xf3
> loki_1     | google.golang.org/grpc.(*Server).handleRawConn.func1(0xc00022cd80, 0x1c4c3e0, 0xc0003dea80)
> loki_1     | 	/src/loki/vendor/google.golang.org/grpc/server.go:679 +0x3f
> loki_1     | created by google.golang.org/grpc.(*Server).handleRawConn
> loki_1     | 	/src/loki/vendor/google.golang.org/grpc/server.go:678 +0x562
> loki_1     |
> loki_1     | goroutine 4740 [IO wait]:
> loki_1     | internal/poll.runtime_pollWait(0x7f0f7127cc10, 0x72, 0xffffffffffffffff)
> loki_1     | 	/usr/local/go/src/runtime/netpoll.go:184 +0x55
> loki_1     | internal/poll.(*pollDesc).wait(0xc005901718, 0x72, 0x1300, 0x1350, 0xffffffffffffffff)
> loki_1     | 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
> loki_1     | internal/poll.(*pollDesc).waitRead(...)
> loki_1     | 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
> loki_1     | internal/poll.(*FD).Read(0xc005901700, 0xc0003d6000, 0x1350, 0x1350, 0x0, 0x0, 0x0)
> loki_1     | 	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x1cf
> loki_1     | net.(*netFD).Read(0xc005901700, 0xc0003d6000, 0x1350, 0x1350, 0x20301a, 0x0, 0x134b)
> loki_1     | 	/usr/local/go/src/net/fd_unix.go:202 +0x4f
> loki_1     | net.(*conn).Read(0xc00000e720, 0xc0003d6000, 0x1350, 0x1350, 0x0, 0x0, 0x0)
> loki_1     | 	/usr/local/go/src/net/net.go:184 +0x68
> loki_1     | crypto/tls.(*atLeastReader).Read(0xc068a29300, 0xc0003d6000, 0x1350, 0x1350, 0x23, 0x1bf9b80, 0xc0006fb970)
> loki_1     | 	/usr/local/go/src/crypto/tls/conn.go:780 +0x60
> loki_1     | bytes.(*Buffer).ReadFrom(0xc0002153d8, 0x1bf99a0, 0xc068a29300, 0x40a265, 0x1692720, 0x1883920)
> loki_1     | 	/usr/local/go/src/bytes/buffer.go:204 +0xb4
> loki_1     | crypto/tls.(*Conn).readFromUntil(0xc000215180, 0x1bfcca0, 0xc00000e720, 0x5, 0xc00000e720, 0xd)
> loki_1     | 	/usr/local/go/src/crypto/tls/conn.go:802 +0xec
> loki_1     | crypto/tls.(*Conn).readRecordOrCCS(0xc000215180, 0x0, 0x0, 0x0)
> loki_1     | 	/usr/local/go/src/crypto/tls/conn.go:609 +0x124
> loki_1     | crypto/tls.(*Conn).readRecord(...)
> loki_1     | 	/usr/local/go/src/crypto/tls/conn.go:577
> loki_1     | crypto/tls.(*Conn).Read(0xc000215180, 0xc0005a1000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
> loki_1     | 	/usr/local/go/src/crypto/tls/conn.go:1255 +0x161
> loki_1     | bufio.(*Reader).Read(0xc003570c60, 0xc000183a78, 0x9, 0x9, 0xc0006fbd93, 0xce1edcd5, 0x1)
> loki_1     | 	/usr/local/go/src/bufio/bufio.go:226 +0x26a
> loki_1     | io.ReadAtLeast(0x1bf97c0, 0xc003570c60, 0xc000183a78, 0x9, 0x9, 0x9, 0x7499dd, 0xc002e550d0, 0xc004043d40)
> loki_1     | 	/usr/local/go/src/io/io.go:310 +0x87
> loki_1     | io.ReadFull(...)
> loki_1     | 	/usr/local/go/src/io/io.go:329
> loki_1     | net/http.http2readFrameHeader(0xc000183a78, 0x9, 0x9, 0x1bf97c0, 0xc003570c60, 0x0, 0xc000000000, 0xc0006fbdf0, 0x74ddc2)
> loki_1     | 	/usr/local/go/src/net/http/h2_bundle.go:1477 +0x87
> loki_1     | net/http.(*http2Framer).ReadFrame(0xc000183a40, 0xc12b2936e0, 0x0, 0x0, 0x0)
> loki_1     | 	/usr/local/go/src/net/http/h2_bundle.go:1735 +0xa1
> loki_1     | net/http.(*http2clientConnReadLoop).run(0xc0006fbfb8, 0xa7, 0x110)
> loki_1     | 	/usr/local/go/src/net/http/h2_bundle.go:8175 +0x8e
> loki_1     | net/http.(*http2ClientConn).readLoop(0xc002e55080)
> loki_1     | 	/usr/local/go/src/net/http/h2_bundle.go:8103 +0xa3
> loki_1     | created by net/http.(*http2Transport).newClientConn
> loki_1     | 	/usr/local/go/src/net/http/h2_bundle.go:7162 +0x62f
> loki_loki_1 exited with code 2

To prevent the bad performance running in the container, I already run the Loki in the instance. Teh same IO error. 
`nohup ./loki-linux-amd64 -config.file=/data/loki/conf/loki.yaml &`

Let me know if you need more information.

**Comment by huihuiy02** [comment]
> Loki wouldn't be using any disk that I'm aware of if you have configured remote storage for chunks and index.
> 
> I still believe from the stack trace you pasted the I/O issue is around network not disk:
> 
> ```
> loki_1 | net.(*conn).Read(0xc00000e7e8, 0xc0044b0000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
> loki_1 | /usr/local/go/src/net/net.go:184 +0x68
> ```

I'm 100% sure the index and chunk already configured to use bigtable and GCS bucket in google cloud. I can see all the table created and chunk data in our bucket. 

<img width="1419" alt="Screen Shot 2019-11-27 at 8 19 33 AM" src="https://user-images.githubusercontent.com/55412695/69665237-daf56e80-10ee-11ea-9cd5-759e1ea53098.png">

**Comment by slim-bean** [comment]
Is the volume of logs substantial enough to cause Loki to use all the memory on the machine? The disk IOPS you are seeing might be the kernel trying to swap memory to disk

**Comment by huihuiy02** [comment]
Yes, you are correct. I appreciate for your help. This is due to the memory issue.   Do you have any recommendations for a production config?   I have increased the memory to 16G. However, after a certain time, the memory usage is hitting 90%.   It seems the memory didn't release.   

We already configure the below
```
  chunk_idle_period: 3m
  chunk_retain_period: 30s
  flush_check_period: 15s
```

Any advice to flush the chunk data and release the memory frequently?

**Comment by huihuiy02** [comment]
https://github.com/grafana/loki/issues/203

**Comment by slim-bean** [comment]
Generally to scale Loki we would recommend using microservices [1]. For
example we have currently 15 distributors and 7 ingesters in our ops
environment, we use ksonnet to configure and deploy this setup [2]. I
believe limits on the distributors are around 200MB memory and the
ingesters are 10GB, though I think they are running pretty far under this.
This supports an ingestion of about 15-20MB/sec

I'm afraid we haven't really done much benchmarking for the single binary
to see how well it scales vertically.

I would also suggest to try setting the environment variable
`GODEBUG=madvdontneed=1` which will revert Go to the pre 1.12 way it
released memory which IMO was better [3] this won't really change the max
memory used by Loki but it will allow it to release memory when ingestion
rates drop.

If you do have success benchmarking/scaling the single binary please let us
know how it goes and feel free to post back to this issue.  We generally
use `loki_distributor_bytes_received_total` to track ingestion rate into
Loki.

Good Luck!!

[1] https://github.com/grafana/loki/blob/master/docs/architecture.md

[2]
https://github.com/grafana/loki/blob/master/docs/operations/scalability.md

[3] https://golang.org/doc/go1.12#runtime

**Comment by huihuiy02** [comment]
Thanks for the reply. That helps a lot.  Hopefully, you don't mind my stupid question again for the microservice model. 

We are not supposed to use k8s in our environment. Therefore, we will set up all the microservice on the gcp intances directly. 

Distributor: ( Stateless)
We can have a tcp load balancer to process requests for several backend distributor as they are stateless. 

Ingester: We will setup  an instance group of instances with ingesters. They can register themselves into the hash rings. 

My question is here:  **How does distributor talk to Consul to retrieve the ingester?**  

We configure the ring_config under ingester_config, am I right? 
```
    ring:
      kvstore:
        store: consul/etcd/inmemory
```

**Comment by slim-bean** [comment]
hey @huihuiy02 apologies for not noticing your response and question.

The different components of Loki run the same code (single binary) and use the same config file, therefore the distributors will look for the ring configuration just like the ingesters.

Part of the information stored in the ring is the IP address of the ingesters, this is what allows the distributors to find them.
