### ISSUE TITLE
Handoff vs just flushing

### ISSUE THREAD

**Issue by gouthamve** [grafana/loki#132]
One of the main reasons Cortex has handoff is because of the sheer amount of writes that'll happen to the database. Here we're going to have magnitudes less streams, and maybe just flushing on exit is a better tradeoff.

**Comment by daixiang0** [comment]
For multi-cpus, handoff is inevitable.
Besides, flushing does not impact on data right?

**Comment by gouthamve** [comment]
No, but it does slow down rollouts. Can you explain what you mean by multi-CPUs?

**Comment by daixiang0** [comment]
I mean multi-core cpus, which is common in production environment.

**Comment by tomwilkie** [comment]
How do multi-core CPUs affect chunk handoffs on rolling upgrades?

@gouthamve I think you've point is valid, we should experiment to see if chunk handoffs are necessary on rolling upgrades.

**Comment by slim-bean** [comment]
Handoff was implemented in #794
