### ISSUE TITLE
query results always get label level=debug for json format logs 

### ISSUE THREAD

**Issue by zegocloud23** [grafana/loki#13211]
I found that grafana always got a tag after executing the query， but this label is not the same as in the log,and I didn't add the level tag. Can you tell me where the configuration is wrong?
![image](https://github.com/grafana/loki/assets/137152615/f80d33f7-3b35-406b-9286-67b5080fa7ab)

**Comment by zegocloud23** [comment]
I see, limits_config.discover_log_levels controls this field.

**Comment by jameshartig** [comment]
What was the query you were running? This could be related to https://github.com/grafana/loki/issues/12839 if you were extracting that field at query-time.
