### ISSUE TITLE
Decouple logproto.Direction from storage iterators

### ISSUE THREAD

**Issue by owen-d** [grafana/loki#1321]
## What
Currently, we have a lot of complex code in the storage [batchChunkIterator](https://github.com/grafana/loki/blob/master/pkg/storage/iterator.go#L19-L278) which handles conditional logic for scanning chunks forward or backward in time. This will be further complicated by the fixes proposed in https://github.com/grafana/loki/pull/1299. We can refactor the iterator to be unaware of `logproto.Direction`, which can be extricated and handled independently. This would isolate the forward vs backward logic and streamline the iterator code.
## Why
The code seems unnecessarily complex which in turn makes it difficult/time-intensive/error prone to extend.
### Possible impl
At a glance, this might be solved by further encapsulating direction logic within the [lazyChunks](https://github.com/grafana/loki/blob/master/pkg/storage/iterator.go#L21-L24) structure.

**Comment by slim-bean** [comment]
should we tag this with keepalive @owen-d ?

**Comment by slim-bean** [comment]
Closing this, we have a few of these refactor or improve PR's and recently we have been closing them to keep the issue backlog smaller.
