### ISSUE TITLE
Loki 3.0.0: `local` ruler-storage now needlessly requires the rules directory to be writable

### ISSUE THREAD

**Issue by whentze** [grafana/loki#13222]
**Describe the bug**
Loki v3.0.0, when configured to use the `local` ruler-storage backend and given a read-only rule directory, crashes at startup.

This regression seems to have been introduced in https://github.com/grafana/loki/pull/12019, in which the `EnsureDirectory` utility was extended with an additional check that the directory be writable. That check is needed for the bloomstore but not for all the other users of that utility function, such as ruler-storage.

**To Reproduce**
1. Configured `local` ruler-storage backend with a read-only directory
2. Started loki v3.0.0
3. It crashed (see below for log messages)

**Expected behavior**
Loki should start normally. The `local` ruler-storage backend is [documented as read-only](https://grafana.com/docs/loki/v3.0.x/alert/#ruler-storage) so it should work if that directory is read-only (as it did in 2.9.x).

**Environment:**
 - Infrastructure: Linux VM
 - Deployment tool: NixOS

Note: This issue also occurs in containerized setups in which the ruler storage is mounted in as a readonly volume.

**Screenshots, Promtail config, or terminal output**
```
insufficient permissions: /nix/store/1rnvm2hh2qmk37plaryxqpy8y2jzv2ri-loki-rules dr-xr-xr-x
error initialising module: ruler-storage
github.com/grafana/dskit/modules.(*Manager).initModule
        github.com/grafana/dskit@v0.0.0-20240104111617-ea101a3b86eb/modules/modules.go:138
github.com/grafana/dskit/modules.(*Manager).InitModuleServices
        github.com/grafana/dskit@v0.0.0-20240104111617-ea101a3b86eb/modules/modules.go:108
github.com/grafana/loki/v3/pkg/loki.(*Loki).Run
        github.com/grafana/loki/v3/pkg/loki/loki.go:453
main.main
        github.com/grafana/loki/v3/cmd/loki/main.go:122
runtime.main
        runtime/proc.go:271
runtime.goexit
        runtime/asm_amd64.s:1695
```

**Comment by owen-d** [comment]
Ugh, sorry -- I pushed a PR to address this and make it less likely in the future.

**Comment by whentze** [comment]
No worries, and thank you for the very quick fix! 👍🏼 

Could you cut a patch release for this, too?
