### ISSUE TITLE
loki  show nothing

### ISSUE THREAD

**Issue by chenpfeisoo** [grafana/loki#1329]
I  used helm  deploy  loki  prometail and  granfan ,   everything looks well , but  
 loki  shows none  avaliable  lables 

![image](https://user-images.githubusercontent.com/18147157/69797604-efc72480-120a-11ea-966f-34ba94dd84c1.png)
promtail config 
![image](https://user-images.githubusercontent.com/18147157/69797723-27ce6780-120b-11ea-9789-1b1090462fd4.png)
pod of promtail  is ok 
![image](https://user-images.githubusercontent.com/18147157/69797775-42084580-120b-11ea-927c-84a6ba7a8964.png)
how can i find out the question ?

**Comment by daixiang0** [comment]
check promtail log please.

**Comment by chenpfeisoo** [comment]
the log shows as this . 
![image](https://user-images.githubusercontent.com/18147157/69857695-6a577900-12cb-11ea-8d7f-e9e9a106a418.png)
for example:
`level=error ts=2019-11-29T07:15:19.194393117Z caller=filetarget.go:272 msg="failed to tail file, stat failed" error="stat /var/log/pods/monitoring_prometheus-k8s-1_da67962b-5347-4323-843e-863ff688f60f/prometheus/3.log: no such file or directory" filename=/var/log/pods/monitoring_prometheus-k8s-1_da67962b-5347-4323-843e-863ff688f60f/prometheus/3.log`

in my work node ,  the file is  exist 
/var/log/pods/monitoring_prometheus-k8s-1_da67962b-5347-4323-843e-863ff688f60f/prometheus/3.log
![image](https://user-images.githubusercontent.com/18147157/69859184-a2ac8680-12ce-11ea-92d8-0bd4ff56f60e.png)
what's the reason of the log  prints this message that has no such file or directory ?

**Comment by chenpfeisoo** [comment]
@daixiang0   Can you see where is wrong ？

**Comment by chenpfeisoo** [comment]
@daixiang0  I read this  issue #429 ，  have a symlinks in /var/lib/docker ,  I changes configration like this
![image](https://user-images.githubusercontent.com/18147157/70031377-0cd26d80-15e6-11ea-9d3e-528cc381e3e2.png)
 promtail log shows well
![image](https://user-images.githubusercontent.com/18147157/70031394-207dd400-15e6-11ea-9837-5bd381048562.png)
I test this job 
![image](https://user-images.githubusercontent.com/18147157/70031462-460add80-15e6-11ea-92aa-89ec37072dc7.png)
but still show nothing
![image](https://user-images.githubusercontent.com/18147157/70031518-62a71580-15e6-11ea-90f1-693072bcdb1e.png)

The time frame is right
