### ISSUE TITLE
How to configure and run against docker?

### ISSUE THREAD

**Issue by inliquid** [grafana/loki#1332]
I want `loki` to run against few docker containers with microservices. Have installed `loki` driver for docker, got `graphana` running with `prometheus`. Now, I want to run `loki` as a standalone server on my dev machine to evaluate this config. However it just doesn't start (Windows):

```
C:\***\loki-1.0.0>loki-windows-amd64.exe
level=info ts=2019-11-28T16:47:33.8332088Z caller=loki.go:125 msg=initialising module=server
level=info ts=2019-11-28T16:47:33.8362071Z caller=server.go:121 http=[::]:80 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2019-11-28T16:47:33.8372068Z caller=loki.go:125 msg=initialising module=overrides
level=info ts=2019-11-28T16:47:33.8372068Z caller=override.go:53 msg="per-tenant overrides disabled"
level=info ts=2019-11-28T16:47:33.8372068Z caller=loki.go:125 msg=initialising module=table-manager
level=error ts=2019-11-28T16:47:33.8372068Z caller=main.go:65 msg="error initialising loki" err="error initialising module: table-manager: Must set -dynamodb.url in aws mode"
```

What am I supposed to do? I was trying to look at docs, googling, etc, but looks like there is NOTHING. How do I configure it? Can you please give any link or anything?

**Comment by cyriltovena** [comment]
Hey @inliquid ,

You need to pass a configuration file to loki, there is an example as well as a detailed documentation (https://github.com/grafana/loki/blob/master/docs/configuration/examples.md).

Here is an example how to run Loki with a configuration: 

```
loki-windows-amd64.exe -config.file="path\to\config.yaml"
```

You can also use our local config here: https://github.com/grafana/loki/blob/master/cmd/loki/loki-local-config.yaml

Let us know how it goes on windows.

**Comment by inliquid** [comment]
@cyriltovena thanks, I'll check this out and come back.

**Comment by inliquid** [comment]
Thanks again @cyriltovena with your help I managed to run `loki` instance by using default config from https://github.com/grafana/loki/blob/master/cmd/loki/loki-local-config.yaml
I also changed paths to make them relative and it seems to work, since loki created folders within its working dir:
```yaml
storage_config:
  boltdb:
    directory: index

  filesystem:
    directory: chunks
```
Then I run docker container with these options:
```
docker run <...> --log-driver=loki --log-opt loki-url="http://127.0.0.1:3100"
```
(I didn't find any hint on what is the url that should be used, so I tried that one)

`graphana` seems to see `loki` at `http://127.0.0.1:3100` and lets adding it as the Loki data source.

However when I try to add something on dashboard it's not clear if logs have even been read. Looks like... no?:
![изображение](https://user-images.githubusercontent.com/6797881/69863684-74b74a00-12ae-11ea-9a70-330ac0a042bc.png)

Here is example of logs written to container's stdout:
```json
{"level":"info","message":"Called Customer.ListPage","time":"2019/11/29 10:29:46.779978","args":{"order":"created_at desc","pageSize":10,"pageNum":1},"err":"<nil>","delay":"2.5565ms","result":10}
```

**Comment by cyriltovena** [comment]
`--log-opt loki-url="http://127.0.0.1:3100/loki/api/v1/push" `
