### ISSUE TITLE
Logcli --version not showing content

### ISSUE THREAD

**Issue by FedericoPonzi** [grafana/loki#1335]
**Describe the bug**
Logcli is not showing informations when using --version command.

**To Reproduce**
* Download logcli v1 from releases
* Try doing logcli --version

**Expected behavior**
Builds and version informations are shown.

**Environment:**
amd64

**Screenshots, Promtail config, or terminal output**
```
logcli --version
logcli, version  (branch: , revision: )
  build user:       
  build date:       
  go version:       go1.13.1
```

**Comment by pstibrany** [comment]
Thanks for report. This will be fixed by PR https://github.com/grafana/loki/pull/1095, when it gets merged.
