### ISSUE TITLE
field pattern_ingester not found in type loki.ConfigWrapper

### ISSUE THREAD

**Issue by apt4user** [grafana/loki#13351]
**Describe the bug**
I am getting in the title mentioned error, when I try to run Loki 2.9.2 locally with the sample configuration file 
wget https://raw.githubusercontent.com/grafana/loki/main/cmd/loki/loki-local-config.yaml

Afaik all newer versions are affected as well.

To install Loki, i followed the steps described here: https://grafana.com/docs/loki/latest/setup/install/local/

I didn't install Loki via apt.
I just downloaded the zip file for linux systems

**To Reproduce**
Install loki and try a run:
`sudo wget -P /usr/local/bin "https://github.com/grafana/loki/releases/download/v2.9.2/loki-linux-amd64.zip"`
`sudo wget -P /usr/local/etc/loki https://raw.githubusercontent.com/grafana/loki/main/cmd/loki/loki-local-config.yaml`

**Expected behavior**
No errors while starting the process

**Environment:**
 - Ubuntu 22.04
 - Loki version: 2.9.2.

**Comment by apt4user** [comment]
see thread:
https://github.com/grafana/loki/issues/13352

**Comment by ssichynskyi** [comment]
Just in case someone lands here while looking for the solution. I've had the same issue because used `latest` tag on my Loki container. When I've changed it to `main` the problem disappeared. I find it very confusing...

**Comment by pope12389** [comment]
It also happend on version 3.1.1

**Comment by snuup** [comment]
i face the same. what is the solution?
