### ISSUE TITLE
field encoding not found in type lokifrontend.Config

### ISSUE THREAD

**Issue by apt4user** [grafana/loki#13352]
**Describe the bug**
I am getting in the title mentioned error, when I try to run Loki 2.9.2 locally with the sample configuration file
wget https://raw.githubusercontent.com/grafana/loki/main/cmd/loki/loki-local-config.yaml

Afaik all newer versions are affected as well.

To install Loki, i followed the steps described here: https://grafana.com/docs/loki/latest/setup/install/local/

I didn't install Loki via apt.
I just downloaded the zip file for linux systems

**To Reproduce**
Install loki and try a run:
`sudo wget -P /usr/local/bin "https://github.com/grafana/loki/releases/download/v2.9.2/loki-linux-amd64.zip"`
`sudo wget -P /usr/local/etc/loki https://raw.githubusercontent.com/grafana/loki/main/cmd/loki/loki-local-config.yaml`

**Expected behavior**
No errors while starting the process

**Environment:**
 - Ubuntu 22.04
 -  Loki version: 2.9.2

**Comment by JStickler** [comment]
The sample config file on the `main` branch is configured for Loki 3.0.  Try running the config file for the `release-2.9-x` branch.

**Comment by apt4user** [comment]
Thank you for your help!
