### ISSUE TITLE
failed to flush chunks: store put chunk: writing index entry: index writer is not initialized due to tsdb store being initialized in read-only mode

### ISSUE THREAD

**Issue by pulchart** [grafana/loki#13443]
**Describe the bug**

I see continuous error messages like this:

`Jul 08 13:18:05 loki1 loki[3156280]: level=error ts=2024-07-08T11:18:05.198151748Z caller=flush.go:178 component=ingester loop=13 org_id=common msg="failed to flush" retries=3 err="failed to flush chunks: store put chunk: writing index entry: index writer is not initialized due to tsdb store being initialized in read-only mode, num_chunks: 1, labels: ..."`

 after I enable bloom in our scalable monolithic deployment. The same setup is working without bloom filters enabled like a charm.

**To Reproduce**
1. Switch loki 3.0 and/or 3.1 from `target=all` into `target=all,bloom-compactor,bloom-gateway` and properly configure bloom sections in configuration.
2. Re-start  the Loki service (all nodes in cluster)
3. See logs

**Expected behavior**

Scalable monolithic Loki deployment with bloom filters woks without errors like the same setup without bloom filters.

**Environment:**
 - X virtual machines each with monolithic setup
 - deployment via puppet and configuration based on loki documentation

**Comment by JStickler** [comment]
>Scalable monolithic Loki deployment

@pulchart , could you clarify, do you have monolithic (single binary) deployment or a simple scalable (SSD) with read, write, and backend components?

**Comment by pulchart** [comment]
@JStickler 
Installed loki from rpm (single binary) at each Virtual machine as example 3x-4x of them in my test-bet environment. Each of them uses the same configuration, with mentioned target setup, and are part of one memberlist.

**Comment by pulchart** [comment]
I reviewed the Loki code and found a potential issue here:
https://github.com/grafana/loki/blob/main/pkg/loki/modules.go#L902-L905
```
	case t.Cfg.isTarget(IngesterRF1), t.Cfg.isTarget(Querier), t.Cfg.isTarget(Ruler), t.Cfg.isTarget(Read), t.Cfg.isTarget(Backend), t.isModuleActive(IndexGateway), t.Cfg.isTarget(BloomCompactor), t.Cfg.isTarget(BloomPlanner), t.Cfg.isTarget(BloomBuilder):
		// We do not want query to do any updates to index
		t.Cfg.StorageConfig.BoltDBShipperConfig.Mode = indexshipper.ModeReadOnly
		t.Cfg.StorageConfig.TSDBShipperConfig.Mode = indexshipper.ModeReadOnly
```

The code does not adequately handle "target profiles." It seems that "target=all,bloom-compactor" is being implicitly treated as "target=read,bloom-compactor" in this instance.

**Comment by pulchart** [comment]
I build loki 3.1 with patch:
```
diff --git a/pkg/loki/modules.go b/pkg/loki/modules.go
index c3904d1e6..c5df2ad73 100644
--- a/pkg/loki/modules.go
+++ b/pkg/loki/modules.go
@@ -807,7 +807,7 @@ func (t *Loki) updateConfigForShipperStore() {
 		t.Cfg.StorageConfig.TSDBShipperConfig.Mode = indexshipper.ModeWriteOnly
 		t.Cfg.StorageConfig.TSDBShipperConfig.IngesterDBRetainPeriod = shipperQuerierIndexUpdateDelay(t.Cfg.StorageConfig.IndexCacheValidity, t.Cfg.StorageConfig.TSDBShipperConfig.ResyncInterval)
 
-	case t.Cfg.isTarget(Querier), t.Cfg.isTarget(Ruler), t.Cfg.isTarget(Read), t.Cfg.isTarget(Backend), t.isModuleActive(IndexGateway), t.Cfg.isTarget(BloomCompactor), t.Cfg.isTarget(BloomPlanner), t.Cfg.isTarget(BloomBuilder):
+	case t.Cfg.isTarget(Read):
 		// We do not want query to do any updates to index
 		t.Cfg.StorageConfig.BoltDBShipperConfig.Mode = indexshipper.ModeReadOnly
 		t.Cfg.StorageConfig.TSDBShipperConfig.Mode = indexshipper.ModeReadOnly
```

The issue with `target=allbloom-compactor,bloom-gateway` is gone and loki looks to be working again.

**Comment by chaudum** [comment]
Hi @pulchart @Kamilcuk 

Bloom filters are by design not supported to work in single binary mode. @JStickler  We should probably update the documentation to state that explicitly.

You need to run at least Simple Scalable mode (SSD) or in a fully distributed microservice mode.

**Comment by chaudum** [comment]
Re-opening the issue until the documentation is more explicit.

**Comment by pulchart** [comment]
I'm not satisfied with the justification provided:
> The reason is that bloom filters also come with a relatively high cost for both building
and querying the bloom filters that only pays off at large scale deployments.

I am utilizing a scalable single binary deployment (multiple nodes, approximately 6, in a memberlist with target=all) to handle 2TiB of logs daily. This setup would significantly benefit from bloom filters. However, this decision requires me to maintain dedicated builds of Loki (with oneliner patch) to enable the use of bloom filters with target=all.

Why not allow users to configure it when to use bloom filters instead of hardcoding this decision into single line of code?
