### ISSUE TITLE
promtail docs refer to invalid parameter http_listen_host

### ISSUE THREAD

**Issue by jtackaberry** [grafana/loki#1344]
Tiny bug in the [promtail `server_config` docs](https://github.com/grafana/loki/blob/master/docs/clients/promtail/configuration.md#server_config) where `http_listen_host` should actually be `http_listen_address`

**Comment by xmackex** [comment]
In Loki docs  in [server_config](https://github.com/grafana/loki/blob/master/docs/configuration/README.md#server_config) also

**Comment by pstibrany** [comment]
Thank you for your reports.
