### ISSUE TITLE
Detected Fields API returns wrong type

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#13455]
<img width="2542" alt="image" src="https://github.com/grafana/loki/assets/1053421/28ea9b1f-cc80-49a4-b8fd-18df98c4ab6c">

For example here bytes_per_shard should be bytes type

I also stumble on low cardinality that are actually high.

cc @trevorwhitney

**Comment by trevorwhitney** [comment]
#13515 fixes the incorrect type bug. I've split cardinality into a separate issue as I think it might be a bigger problem to solve.
