### ISSUE TITLE
Helm chart for AWS-based (S3, DynamoDB) deployments?

### ISSUE THREAD

**Issue by timcooijmans** [grafana/loki#1352]
Hi,

I was looking through the Helm-chart to deploy (only) Loki. It seems that the Helm-chart deploys a BoltDB-based deployment by using a Statefulset and PersistentVolumes. 

When using Loki with S3 and DynamoDB on AWS, you don't need PVs if I understand it correctly. It seems that this kind of deployment is not supported by the Helm-chart (or at least not documented).

Please provide support and/or documentation. for AWS-based deployments in the Helm-chart.

**Comment by halcyondude** [comment]
+1, please advise.

**Comment by myroslavrys** [comment]
+1

**Comment by Eraac** [comment]
[Here](https://gist.github.com/Eraac/4731ee1f5043e1ed3d15f02240b0d983) my values.yaml file for loki helm chart using S3 + DynamoDB + EKS + eks-iam + memcache

But configured as one service (not microservice)

**Comment by thanasisk** [comment]
:+1: including AWS specific information and not having to dig through gists would be a major productivity boon for all
