### ISSUE TITLE
Cannot specify a custom config file when starting loki with docker-compose

### ISSUE THREAD

**Issue by MrMebelMan** [grafana/loki#1354]
**Describe the bug**
When using a custom config.yaml path in docker-compose, I am getting a "no such file" error.

**To Reproduce**
```
cd production
# create a config file local-config.yaml
# update docker-compose command:-config.file=./local-config.yaml
docker-compose up
```

**Expected behavior**
Loki reads my custom config file.

**Environment:**
 - Infrastructure: bare-metal
 - Deployment tool: docker-compose

**Terminal output**
```
loki_1      | failed parsing config: sourcing: open ./local-config.yaml: no such file or directory
```

**Comment by cyriltovena** [comment]
You need to mount the file with a volume property see docker documentation. https://docs.docker.com/compose/compose-file/#volume-configuration-reference

**Comment by MrMebelMan** [comment]
Thanks a lot, it  helped, but now I am getting the following error when starting loki:

`level=error ts=2019-12-04T11:10:14.038171058Z caller=main.go:65 msg="error initialising loki" err="error initialising module: table-manager: Must set -dynamodb.url in aws mode"`

Unfortunately, I couldn't find any solutions (just [this issue](https://github.com/grafana/loki/issues/1127)). I am using the [default configuration file](https://github.com/grafana/loki/blob/master/cmd/loki/loki-local-config.yaml).

**Comment by pstibrany** [comment]
> Thanks a lot, it helped, but now I am getting the following error when starting loki:
> 
> `level=error ts=2019-12-04T11:10:14.038171058Z caller=main.go:65 msg="error initialising loki" err="error initialising module: table-manager: Must set -dynamodb.url in aws mode"`
> 
> Unfortunately, I couldn't find any solutions (just [this issue](https://github.com/grafana/loki/issues/1127)). I am using the [default configuration file](https://github.com/grafana/loki/blob/master/cmd/loki/loki-local-config.yaml).

How exactly do you start loki, what are the command line parameters (it should be `-config.file loki-local-config.yaml`)? This error message suggests that it's using default configuration instead.

**Comment by MrMebelMan** [comment]
The problem was on my side, sorry and thank you :pray:
