### ISSUE TITLE
Documentation feedback: /docs/sources/setup/install/helm/install-monolithic/_index.md

### ISSUE THREAD

**Issue by c7nd85** [grafana/loki#13569]
loki:
  commonConfig:
    replication_factor: 3
  schemaConfig:
    configs:
    - from: "2024-01-01"
      store: tsdb
      index:
        prefix: loki_index_
        period: 24h
      object_store: s3
      schema: v13
  storage:
    type: 's3'
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    s3:
      endpoint: foo.aws.com
      region: <AWS region>
      secretAccessKey: supersecret
      accessKeyId: secret
      s3ForcePathStyle: false
      insecure: false
singleBinary:  <---------------------------------------------------- change to SimpleScalable
  replicas: 3

**Comment by JStickler** [comment]
NOTABUG this is correct for the monolithic installation.

https://github.com/grafana/loki/blob/c9c50885cb84d1f5c215fa8167e5391dcfbcdc6f/production/helm/loki/values.yaml#L1215
