### ISSUE TITLE
Getting logs from docker containers.

### ISSUE THREAD

**Issue by itpizza** [grafana/loki#136]
Hi! Tell me please, is there a way to get logs from docker containers? 
When I add to datasource PostgreSQL(running in docker container) and then I push "Save&Test" button I get "Database Connection OK" message, but I can't see any log in Explore menu.

**Comment by aylei** [comment]
Hi @itpizza, can you please clarify what mea? Have you collected the log by `promtail`? Thanks!

**Comment by itpizza** [comment]
> Hi @itpizza, can you please clarify what you mean? Have you collected the log using `promtail`? Thanks!

I want to see logs from docker container(PostgreSQL) in Loki. Is it possible? If yes, how I can add my docker-container log in Loki.
By default, Loki shows logs from the /var/log/ directory. And if I run PostgreSQL with "--log-driver=syslog" setting I can see Postgres container logs in Loki along with others system logs.
I would like to get only the logs from Docker containers. Thanks!

**Comment by aylei** [comment]
@itpizza AFAIK, you can only collect the container logs written to STDOUT and STDERR unless you run `promtail` as a sidecar. And the default configuration in `/docs` collects logs located in `/var/log` from your node, not your container.

**Comment by itpizza** [comment]
> @itpizza AFAIK, you can only collect the container logs written to STDOUT and STDERR unless you run `promtail` as a sidecar. And the default configuration in `/docs` collects logs located in `/var/log` from your node, not your container.

Ok. Thanks for the replies :)
