### ISSUE TITLE
Promtail timezone stage doesn't work well on Windows

### ISSUE THREAD

**Issue by slim-bean** [grafana/loki#1361]
This looks to be the result of: https://github.com/golang/go/issues/21881

There are a few options on that page, I'm inclined towards just embedding the timezone data into the binary itself for all our builds (we could then remove it from the promtail docker image), looks like it would add about another 1MB to the binary size (which is already 60MB? 80MB?)

This has the issue that it will likely never get updated unless someone specifically finds a bug and updates it manually... (We should have a makefile target which at least makes this easy to do)

IMO it's better than asking people to download a zip file and set environment variables (or install Go) is a worse alternative.

Thoughts anyone?

**Comment by tdabasinskas** [comment]
For me, embedding the timezone data into the windows image makes sense. Even if it increases the binary size by 1MB (I think it's actually ~800KB or so), it's better than having the users to sped time troubleshooting the reason timezone stage does not work or/and getting the the zip on machines manually.

**Comment by pstibrany** [comment]
There are discussions on that issue about using data that's already available on Windows. Perhaps we can wait until it gets fixed? It's not like there are no workarounds today:

> Or set the %ZONEINFO% environment variable to point to your shipped zoneinfo.zip.

(https://github.com/golang/go/issues/21881#issuecomment-370040513)

This looks like a good solution until it's fixed properly. (But we should document it for Windows users)

**Comment by cyriltovena** [comment]
This should be possible now that go 1.15 is merged. #2877

**Comment by splitt3r** [comment]
Would it be enough to do sth. like https://github.com/DataDog/terraform-provider-datadog/pull/728/files in https://github.com/grafana/loki/blob/c4faa579e33b33afa2c15bca72796d000e6b79fb/pkg/logentry/stages/timestamp.go?

**Comment by cyriltovena** [comment]
> Would it be enough to do sth. like https://github.com/DataDog/terraform-provider-datadog/pull/728/files in https://github.com/grafana/loki/blob/c4faa579e33b33afa2c15bca72796d000e6b79fb/pkg/logentry/stages/timestamp.go?

Yes this will do.
