### ISSUE TITLE
In the ring, when it is detected that the state of a node is unhealthy, will it be automatically moved to the ring?

### ISSUE THREAD

**Issue by hexiang1219** [grafana/loki#13732]
the loki I deployed found the following error log in the distributor component:
`level=warn ts=2024-08-01T04:37:33.021974079Z caller=logging.go:86 traceID=10dbe6e76e8f0926 orgID=xxx msg="POST /api/prom/push (500) 852.956µs Response: \"at least 2 live replicas required, could only find 1 - unhealthy instances: xxxx:9095\\n\" ws: false; Connection: close; Content-Length: 3142; Content-Type: application/x-protobuf; User-Agent: promtail/2.9.1; X-Scope-Orgid: xxx; "`

then I found that this unhealthy node has not been removed from the ring, causing the distributor to still make requests to this unhealthy node. 

finally, I manually removed the unhealthy nodes from the ring and recovered.

**Version:** v2.8.3

**Comment by tonyswu** [comment]
You can try setting `autoforget_unhealthy` to true, see https://grafana.com/docs/loki/latest/configure/#ingester.

**Comment by hexiang1219** [comment]
> You can try setting `autoforget_unhealthy` to true, see https://grafana.com/docs/loki/latest/configure/#ingester.

ok,thanks.
