### ISSUE TITLE
Make Helm Charts easier to find

### ISSUE THREAD

**Issue by ldealmei** [grafana/loki#1377]
**Is your feature request related to a problem? Please describe.**
Currently, it is a bit "hard" to find where the source code of the Chart is. The documentation leads to [this page](https://github.com/grafana/loki/blob/master/docs/installation/helm.md) in most cases, which contains mainly general "how to use Helm" information rather than information about the Chart itself. For installing, it is important to know what `values` are made available for customization so I feel that making finding the Charts easier could benefit first-time users.

**Describe the solution you'd like**
Adding links to the `loki/production/helm` folder in the installation docs.

Thanks!

**Comment by evalsocket** [comment]
@cyriltovena Would like to work on this. Can this be assigned to me ?

**Comment by ldealmei** [comment]
Thank you!
