### ISSUE TITLE
Bug while installing Grafana-Loki with Helm

### ISSUE THREAD

**Issue by BeneaAlinAndrei** [grafana/loki#1385]
**Describe the bug**

I receive the Error `Error: could not get apiVersions from Kubernetes: unable to retrieve the complete list of server APIs: custom.metrics.k8s.io/v1beta1: the server is currently unable to handle the request
` while trying installing the Grafana Loki.

Also after running the command `sudo kubectl get apiservice` i found:

`v1beta1.custom.metrics.k8s.io   False (MissingEndpoints) ` 

**To Reproduce**
1. I follow the Read Me from: https://github.com/grafana/loki/blob/master/docs/installation/helm.md
2. I run the command `$ helm upgrade --install loki loki/loki-stack`

**Environment:**
 - Infrastructure: 

        * Kubernetes v14.9 Server Version and 15.3 Client Version,
        * Kubeflow v0.7.0-rc.8
        * Helm v3.0

If any one knows how to pass this problem, thanks a lot!

**Comment by cyriltovena** [comment]
What happens here ? I’m curious to know more about how you solved it.

**Comment by BeneaAlinAndrei** [comment]
> What happens here ? I’m curious to know more about how you solved it.

This was not a problem form Grafana but from Helm.

There is a problem at Helm V3.0 that doesn't manage the packages correctly and if it detects one service that is not running properly  the installation crash. In my case the service custom.metrics was False and it prevented Helm from finishing the installation of Grafana-Loki.

I resolved this issue by deleting that specific service  
`kubectl delete apiservce <service-name>`

More info here: https://github.com/helm/helm/issues/6361

**Comment by cyriltovena** [comment]
Thanks

**Comment by geekdave** [comment]
The helm issue appears to be fixed in https://github.com/helm/helm/releases/tag/v3.0.2
