### ISSUE TITLE
How to downgrade loki version.

### ISSUE THREAD

**Issue by undefined2407** [grafana/loki#13953]
Currently I am using Grafana version 8.1.2 which is using loki verison - github.com/grafana/loki v1.6.2-0.20210520072447-15d417efe103
but I want to downgrade the loki version to github.com/grafana/loki v1.6.2-0.20201026154740-6978ee5d7387 which is being used in 7.5.17.

How to achieve it ?

I tried to replace the loki version in go.mod file of 8.1.2 with the one being used in 7.5.17. But it breaks the Grafana server.

Any suggestions ?

**Comment by JStickler** [comment]
I think that anyone answering this question would suggest that you upgrade to a supported version of both Grafana and Loki.  You are on very old versions of both (current version of Grafana is 11.3 and Loki is 3.2.1)
