### ISSUE TITLE
error sending batch, will retry

### ISSUE THREAD

**Issue by wanghe-fit2cloud** [grafana/loki#1398]
Environments:
1. loki:v1.2.0
2. grafana:6.4.3
3. k8s:v1.16.3
4. kube-proxy mode:ipvs

promtail log:
level=warn ts=2019-12-11T10:13:21.000561436Z caller=client.go:226 component=client host=f2c-loki:3100 msg="error sending batch, will retry" status=-1 error="Post http://f2c-loki:3100/loki/api/v1/push: dial tcp 179.10.182.19:3100: connect: no route to host"
level=warn ts=2019-12-11T10:13:22.580520575Z caller=client.go:226 component=client host=f2c-loki:3100 msg="error sending batch, will retry" status=-1 error="Post http://f2c-loki:3100/loki/api/v1/push: dial tcp 179.10.182.19:3100: connect: no route to host"
level=warn ts=2019-12-11T10:13:24.820475912Z caller=client.go:226 component=client host=f2c-loki:3100 msg="error sending batch, will retry" status=-1 error="Post http://f2c-loki:3100/loki/api/v1/push: dial tcp 179.10.182.19:3100: connect: no route to host"
level=warn ts=2019-12-11T10:13:28.354476471Z caller=client.go:226 component=client host=f2c-loki:3100 msg="error sending batch, will retry" status=-1 error="Post http://f2c-loki:3100/loki/api/v1/push: dial tcp 179.10.182.19:3100: connect: no route to host"
level=warn ts=2019-12-11T10:13:32.305331883Z caller=client.go:226 component=client host=f2c-loki:3100 msg="error sending batch, will retry" status=-1 error="Post http://f2c-loki:3100/loki/api/v1/push: dial tcp 179.10.182.19:3100: connect: no route to host"
level=warn ts=2019-12-11T10:13:37.362513052Z caller=client.go:226 component=client host=f2c-loki:3100 msg="error sending batch, will retry" status=-1 error="Post http://f2c-loki:3100/loki/api/v1/push: dial tcp 179.10.182.19:3100: connect: no route to host"
level=warn ts=2019-12-11T10:13:41.602511101Z caller=client.go:226 component=client host=f2c-loki:3100 msg="error sending batch, will retry" status=-1 error="Post http://f2c-loki:3100/loki/api/v1/push: dial tcp 179.10.182.19:3100: connect: no route to host"
level=warn ts=2019-12-11T10:13:45.998561283Z caller=client.go:226 component=client host=f2c-loki:3100 msg="error sending batch, will retry" status=-1 error="Post http://f2c-loki:3100/loki/api/v1/push: dial tcp 179.10.182.19:3100: connect: no route to host"
level=warn ts=2019-12-11T10:13:51.396518582Z caller=client.go:226 component=client host=f2c-loki:3100 msg="error sending batch, will retry" status=-1 error="Post http://f2c-loki:3100/loki/api/v1/push: dial tcp 179.10.182.19:3100: connect: no route to host"
level=warn ts=2019-12-11T10:13:57.124531316Z caller=client.go:226 component=client host=f2c-loki:3100 msg="error sending batch, will retry" status=-1 error="Post http://f2c-loki:3100/loki/api/v1/push: dial tcp 179.10.182.19:3100: connect: no route to host"

**Comment by wanghe-fit2cloud** [comment]
when browse grafana explore
Error connecting to datasource: Loki: Bad Gateway. 502 
![image](https://user-images.githubusercontent.com/46734380/71403411-a4b5fb00-266a-11ea-9181-c23f3f2a0ba6.png)

**Comment by wanghe-fit2cloud** [comment]
loki values.yml

[values.txt](https://github.com/grafana/loki/files/3997708/values.txt)

**Comment by wanghe-fit2cloud** [comment]
# kubectl get svc
NAME                                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
f2c-grafana                         NodePort    179.10.253.204   <none>        80:31460/TCP     11h
f2c-loki                            NodePort    179.10.217.194   <none>        3100:32598/TCP   4h20m
f2c-loki-headless                   ClusterIP   None             <none>        3100/TCP         4h20m

when test curl in the curl pod
# curl http://f2c-loki:3100/loki/api/v1/push
curl: (7) Failed to connect to f2c-loki port 3100: Host is unreachable

ping f2c-loki successful

**Comment by sbkg0002** [comment]
Did you resolve this?

**Comment by lukaszraczylo** [comment]
Key: Network policies
