### ISSUE TITLE
Applying patterns line length limit on the json message key

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#13984]
We drop lines that are too big [default 3k chars](https://github.com/grafana/loki/blob/main/pkg/pattern/drain/drain.go#L209-L211) or contains too many tokens for performance reasons in pattern ingesters.

For json log line we only use a [set of keys](https://github.com/grafana/loki/blob/main/pkg/pattern/drain/line_tokenizer.go#L263-L269) for discovering patterns.

 We could probably do the json message parsing prior that [limit](https://github.com/grafana/loki/blob/main/pkg/pattern/drain/drain.go#L146-L147) and apply that limit on the message key.

Notes:

- We should avoid parsing the json key twice.
- This might means we'll hold the backing array for the log buffer entirely and increase memory usage.

**Comment by ravishankar15** [comment]
Hi @cyriltovena Correct me if my understanding is wrong, Basically if its a `jsonTokenizer` we wanted to check MaxAllowedLineLength on the extracted line from the set of keys that is after `Tokenize`. For other tokenizers it should proceed as it is now ? 

Can you help with the clarification. I can raise a PR for this.
