### ISSUE TITLE
Override less specific docker tags on push/release (v1.2 updates when we push v1.2.1)

### ISSUE THREAD

**Issue by edasque** [grafana/loki#1401]
Hi,

I believe it's typical for people to version pin their docker containers on _feature_ in SEMVER (MAJOR,MINOR,PATCH or BREAK,FEATURE,FIX - https://semver.org/) but I believe that's not currently possible for Loki images because of the 'v' prefix that's in the tag of the images published (i.e. v1.4.0) in the Docker hub. Grafana for example doesn't use the 'v' (6.5.2) and it's possible to version pin the docker image you want to use.

I imagine the current 'v' is in inherited directly from the github version, would it be possible to trim it in the building and tagging of the images?

Thank you in advance,

--E

**Comment by sh0rez** [comment]
Possible – yes, of course. But the semver spec states that you may use optional `v` prefixes in front of your versions, so it should be fine in theory.

Can you give examples where the prefix causes problems?

**Comment by edasque** [comment]
@sh0rez .

I am used to doing something like the following in my docker-compose, helm file, etc:

```image: grafana/loki:1.2``` 

so that when I redeploy the container, it grabs the newest version of loki from 1.2.0 to 1.2.1 to 1.2.2, etc.

I could even just pin to 1 and get 1.0, 1.2, etc.

While semver is cool with "v" prefix, it seems most docker tools are not.

```image: grafana/loki:v1.2```  simply doesn't work, from what I can tell.

**Comment by ThisGuyCodes** [comment]
@edasque the behaviour you describe is a result of maintainers overriding less precise tags (i.e. when 1.2.2 comes out they update 1.2 to point to the same version as 1.2.2).

Example:
`docker pull thisguy/semver-test:1.1` fails
`docker pull thisguy/semver-test:1.1.1` succeeds

Perhaps this ask could be adjusted to maintain tags using only the major +/ minor versions when new releases come out?

**Comment by edasque** [comment]
I thought it was a behavior from docker tagging but I may very well be wrong. In this case, yes, maybe Loki can point the major and minor tag to the latest fix of that release.

grafana/grafana does that, maybe you guys can look into what they do

**Comment by sh0rez** [comment]
Yeah I guess I can enable that here as well. Will look into it for the next release!

**Comment by edasque** [comment]
Super, thank you. I feel it's a Docker pattern found in most of the images I use. To the point that I thought it was built into the pull image stuff.

**Comment by edasque** [comment]
@sh0rez any progress? Didn’t want this to go stale

**Comment by owen-d** [comment]
I also think this functionality would be nice. Now, to convince someone to do the CI work... 😈 .

**Comment by edasque** [comment]
I don't believe that has been completed yet?
