### ISSUE TITLE
Missing chunkDelimiter parameter for Azure storage in Helm chart

### ISSUE THREAD

**Issue by NGPixel** [grafana/loki#14010]
**Describe the bug**
The Loki helm chart is missing the `loki.storage.azure.chunkDelimiter` parameter. This is needed when migrating from S3 (which uses `:`) to Azure Blob Storage (which uses `-` by default *(why?!)*).

**To Reproduce**
1. Set `loki.storage.azure.chunkDelimiter` to `:`
2. Deploy to Kubernetes
3. Delimiter is still using `-` because parameter is not set in the template.

**Expected behavior**
Being able to set `chunkDelimiter` as part of the helm values.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
N/A

**Comment by ubcharron** [comment]
I think there's an issue issue with quoting. In chart version 6.18, helm fails to generate the template if I set chunkDelimiter to ":"

```
loki:
  storage:
    azure:
      chunkDelimiter: ":"
```

`Error: 'error converting YAML to JSON: yaml: line 35: mapping values are not allowed in this context`

I need to set it as follows for it to work:
```
chunkDelimiter: "\":\""
```
