### ISSUE TITLE
Http api response: per-user streams limit (10000) exceeded

### ISSUE THREAD

**Issue by ximply** [grafana/loki#1403]
**Describe the bug**
Http POST data by api (/loki/api/v1/push), then sometimes response per-user streams limit (10000) exceeded, but I can not find this error string from loki source files. 

**Env**
Loki version:v1.0.0, running on local mode
OS: Centos 6.6  
Kernel: Linux 2.6.32-696.20.1.el6.x86_64 #1 SMP Fri Jan 26 17:51:45 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tdabasinskas** [comment]
The limit comes from [`max_streams_per_user`](https://github.com/grafana/loki/blob/master/docs/configuration/README.md#limits_config) Ingester configuration parameter and, if you're curious, it's in the source code at https://github.com/grafana/loki/blob/master/pkg/ingester/instance.go#L153-L155:

```go
	if len(i.streams) >= i.limits.MaxStreamsPerUser(i.instanceID) {
		return nil, httpgrpc.Errorf(http.StatusTooManyRequests, "per-user streams limit (%d) exceeded", i.limits.MaxStreamsPerUser(i.instanceID))
	}
```

**Comment by ximply** [comment]
Got it, thanks!

**Comment by vrischmann** [comment]
Hello, 

I have a follow-up question about this, what exactly is the user in this case ?

**Comment by pstibrany** [comment]
> I have a follow-up question about this, what exactly is the user in this case ?

User = Tenant = Organization. Our terminology is confused here, but they all refer to the same thing.

**Comment by vrischmann** [comment]
Thanks.
