### ISSUE TITLE
listen tcp :3100: bind: address already in use

### ISSUE THREAD

**Issue by yogeshi533** [grafana/loki#14030]
Hi Team, 

THis is the first time i had installed loki , after installed when i use the below cmd am getting this error. And attached the screenshot 

### **azureuser@Master:~$ ./loki-linux-amd64 --config.file=loki-local-config.yaml**

listen tcp :3100: bind: address already in use
error initialising module: server

github.com/grafana/dskit/modules.(*Manager).initModule
        /src/loki/vendor/github.com/grafana/dskit/modules/modules.go:138
github.com/grafana/dskit/modules.(*Manager).InitModuleServices
        /src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108
github.com/grafana/loki/v3/pkg/loki.(*Loki).Run
        /src/loki/pkg/loki/loki.go:453
main.main
        /src/loki/cmd/loki/main.go:122
runtime.main
        /usr/local/go/src/runtime/proc.go:267
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1650
level=info ts=2024-09-02T13:54:15.478629417Z caller=main.go:120 msg="Starting Loki" version="(version=3.0.0, branch=release-3.0.x, revision=b4f7181)"
level=error ts=2024-09-02T13:54:15.48082327Z caller=log.go:216 msg="error running loki" err="listen tcp :3100: bind: address already in use\nerror initialising module: server\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:138\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/loki/v3/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:453\nmain.main\n\t/src/loki/cmd/loki/main.go:122\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650"

![Image](https://github.com/user-attachments/assets/a0892027-71a1-4a7f-bb1d-9213ee051758)

You may submit questions in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

**NOTE: All questions submitted as issues will be closed.**

**Comment by chaudum** [comment]
Loki binds to 3 different ports:
* `3100` for HTTP
* `9095` for gRPC
* `7946` for memberlist

All three ports need to be available. I assume some other application you're running interferes with Loki's ports.

You can configure the ports using

```yaml
server:
  http_listen_port: 3100
  grpc_listen_port: 9095
memberlist:
  bind_port: 7946
```
