### ISSUE TITLE
LogQL queries of the form line_filter label_filter line_filter max out memory

### ISSUE THREAD

**Issue by ChrisSteinbach** [grafana/loki#14069]
**Describe the bug**
LogQL queries of the form line_filter label_filter line_filter max out memory.

**To Reproduce**
1. Loki veresion 3.1.0 running
2. Add to Grafana as a datasource
3. From the Grafana explorer, run a query that includes a line filter, followed by a label filter, followed by another line filter, for example,

{application="myapp"} !~ ".*Canceled" |  cluster="Primary" |~ "test"

**Expected behavior**
Any matching log lines are returned

**Actual behaviour**
Memory usage rises to max and Loki nodes need restarting

**Environment:**
 - Infrastructure: Four Loki VMs with Minio backend running on the same four nodes 
 - Deployment tool: own scripts deploying in monolithic mode

**Screenshots, Promtail config, or terminal output**
Nothing obviously interesting from the Loki logs except that the query (and the count_over_time query that Grafana uses for the "Log volume" view are logged as being slow. A figure around 30 seconds is usually seen, the query hangs from the user perspective.

**Notes**
The same query slightly rearranged isn't a problem so, for example, the following combinations of filter types are not a problem:

 - line_filter, line_filter, label_filter
 - label_filter, line_filter, label_filter
 - label_filter, label_filter, line_filter

**Comment by yincongcyincong** [comment]
i think this issure is fixed by this pr(https://github.com/grafana/loki/pull/13501), please use latest version

**Comment by JStickler** [comment]
@ChrisSteinbach Did @yincongcyincong's suggestions solve your problem?  Can this issue be closed?

**Comment by ChrisSteinbach** [comment]
@JStickler yes, and sorry for not updating. Upgrading seems to have fixed the problem for us thanks!
