### ISSUE TITLE
Support microsecond timestamp format

### ISSUE THREAD

**Issue by wphan** [grafana/loki#1407]
**Is your feature request related to a problem? Please describe.**
I'm currently using zerolog for my logging package and they can output microsecond timestamps.

**Describe the solution you'd like**
Add another parser for `UnixUs` here: https://github.com/grafana/loki/blob/a2e2272653d78576cafbc8168c3249970ac2cbe5/pkg/logentry/stages/util.go#L81

**Describe alternatives you've considered**
* adding three `0`s to the end of my timestamps and treating them as `UnixNs` in promtail stage
* Getting zerolog to support nanosecond timestamps 😄 

**Additional context**
If there's interest on this I can work on the PR for this.  Unless there is a better way to achieve this, any input is appreciated.

**Comment by cyriltovena** [comment]
Yes I think this a good candidate for a PR, feel free to add another parser and document it.

**Comment by evalsocket** [comment]
@cyriltovena Would like to work on this. ?

**Comment by pstibrany** [comment]
@evalsocket feel free to send PR

**Comment by wphan** [comment]
https://github.com/grafana/loki/pull/1426 can't seem to add reviewers
