### ISSUE TITLE
[Better] "Getting started" guide

### ISSUE THREAD

**Issue by DazWilkin** [grafana/loki#1410]
I tried this once before (out of curiosity, liking Prometheus, Grafana and Jsonnet).

I returned again but I am again admitting defeat :-(

I'm submitting this issue, in case I'm representative of other developers who struggle with this.

Is there a definitive, working "Getting start" guide that goes from having a Kubernetes cluster to a working example? Should I use the Helm deployment rather than Tanka?

This recommended (!) approach appears insufficient and incorrect:
https://github.com/grafana/loki/blob/master/docs/installation/tanka.md

Issues:
+ https://github.com/grafana/loki/blob/master/docs/installation/tanka.md
+ I think needs `jb install github.com/grafana/loki/production/ksonnet/promtail`
+ I remain unclear as to what e.g. `htpasswd` refers to

There's little explanation of the goal and how the steps contribute to this.

I assume we need Loki running to aggregate logs, at least one promtail (agent) to gather logs and some application (configured) to ship logs caught by promtail into Loki that can be viewed in Grafana.

After muddling through the instruction, I receive (unexpected) errors about Bigtable:
```bash
tk status environments/loki
evaluating jsonnet: RUNTIME ERROR: must specify bigtable instance
	.../loki/vendor/loki/config.libsonnet:21:24-62	object <anonymous>
	.../loki/vendor/loki/config.libsonnet:74:19-46	object <anonymous>
	.../loki/vendor/ksonnet-util/kausal.libsonnet:391:9-28	builtin function <toString>
	.../loki/vendor/ksonnet-util/kausal.libsonnet:391:7-29	function <anonymous>
	.../loki/vendor/loki/config.libsonnet:234:22-57	object <anonymous>
	During manifestation
```

**Comment by DazWilkin** [comment]
I tried the Helm instructions. These work flawlessly!

**Comment by codesse** [comment]
Totally agree with @DazWilkin ... I get the same error with tk.
Just copying&pasting commands without knowing what and why I am doing that.

**Comment by lmctague93** [comment]
I'm also experiencing the same error when using Tanka. I'm trying to use `tk export` so that I can use raw yaml files. Is there a way we can ignore this error?

**Comment by efvhi** [comment]
got the same error

**Comment by Arturx47** [comment]
the same for me also, and this case seams not to be closed ....also with helm i have some problems....the health check on the loki testing pod is failing....and i don't now why... so i went to tanka...just to get this issue...

**Comment by robertb724** [comment]
I get the same errors as well. Just trying to get example YAMLs of production setup on system. The all-in-one helm setup works great. Have not found any clear documentation on how to setup production.
