### ISSUE TITLE
How to create alert when using loki?

### ISSUE THREAD

**Issue by orange888** [grafana/loki#1422]
How to create alert when using with loki?

**Comment by pstibrany** [comment]
Do you mean Alert in Grafana based on log entries? I don't think that is currently possible. @davkal

**Comment by orange888** [comment]
> Do you mean Alert in Grafana based on log entries? I don't think that is currently possible. /cc @davkal
Yes, custom alert based on log (loki)?
Can loki subscribe to kafka?  kafka -> promtail -> loki? Or kafka -> loki?

**Comment by pstibrany** [comment]
> Yes, custom alert based on log (loki)?

David will give you a definitive answer, but I don't think it's currently supported by Grafana (and not sure what kind of support it would need from Loki. Tailing everything all the time doesn't sound like good idea).

> Can loki subscribe to kafka? kafka -> promtail -> loki? Or kafka -> loki?

Not at the moment.

**Comment by davkal** [comment]
Grafana alerting is only available for certain datasources. Even though Loki is not supported, Prometheus is supported. And Loki has a prometheus-compatible API, so you can add your Loki as a Promehteus datasource, see #1222. Then you need to set up logql queries that return timeseries and alert on those, e.g., `count_over_time({job="foo"} |= "error" [5m]) > 0`

**Comment by miklezzzz** [comment]
@davkal  could u please elaborate it in more detail? Where should i set up logql queries? thx

**Comment by davkal** [comment]
> Where should i set up logql queries?

You create a graph panel using the prometheus datasource that points to loki. In the query field you write the logql query and you should see a line graph for your log volume (depends on the query). Then you can add a panel alert.

**Comment by anandecemptc** [comment]
@davkal. - When i create prometheus datasource and that datasources pointed to loki service ,
Facing 404 not found error, see the grafana error logs 
t=2019-12-28T00:58:25+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/11/api/v1/query status=404 remote_addr=106.198.13.89 time_ms=202 size=19 referer=https://monitoring-dev.np.example.com/datasources/edit/11/

**Comment by Eraac** [comment]
@anandecemptc URL should be `http(s)://<loki-domain>/loki` (ex. `https://loki.domain.tld/loki`). The same as loki datasource but suffix with `/loki` (and select prometheus datasource)

**Comment by anandecemptc** [comment]
Thanks Eraac.

I have created a prmetheus datasource using loki url (ex. https://loki.domain.tld/loki), during the creation and saving the datasource i checked the datasource and it was worked. 

When i checked through the Grafana explore option and metrics are not loaded.

still metric loading... 
![image](https://user-images.githubusercontent.com/15903560/71806343-92868480-308e-11ea-84e4-5c9ecded5782.png)

When i searched with some string and its not displayed anything.
![image](https://user-images.githubusercontent.com/15903560/71806458-e1341e80-308e-11ea-97c3-90e767299043.png)

I created a  dashboard and added the query on that dashboard and itsn't loaded anything.
![image](https://user-images.githubusercontent.com/15903560/71806592-2d7f5e80-308f-11ea-977c-1f4d248f4194.png)

**Comment by cyriltovena** [comment]
You need to use a metric query, see https://github.com/grafana/loki/blob/master/docs/logql.md#counting-logs.

Alternatively I want to add that a safe option is also to add metrics pipeline in promtail and scrape promtail with a Prometheus. This allows to create custom metrics in promtail.

See metrics stage : https://github.com/grafana/loki/blob/master/docs/clients/promtail/pipelines.md

**Comment by cyriltovena** [comment]
> @davkal. - When i create prometheus datasource and that datasources pointed to loki service ,
> Facing 404 not found error, see the grafana error logs
> t=2019-12-28T00:58:25+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/11/api/v1/query status=404 remote_addr=106.198.13.89 time_ms=202 size=19 referer=https://monitoring-dev.np.example.com/datasources/edit/11/

You might be using a too old Loki server.

**Comment by chrono2002** [comment]
Trick don't work now. Alerter always gives:

Test Rule


Expand All
Copy to Clipboard
Object
firing:true
state:""
conditionEvals:" = true"
timeMs:"1.050ms"
error:"tsdb.HandleRequest() error bad_response: readObjectStart: expect { or n, but found p, error found in #1 byte of ...|parse error|..., bigger context ...|parse error : syntax error: unexpected $end |..."
logs:Array[1]
0:Object
message:"Condition[0]: Query"
data:Object

**Comment by houstonj1** [comment]
I am also seeing this with grafana 6.6.2 and above when trying to create an alert using the prometheus from Loki

```
tsdb.HandleRequest() error bad_response: readObjectStart: expect { or n, but found p, error found in #1 byte of ...|parse error|..., bigger context ...|parse error : syntax error: unexpected end|...
```

**Comment by cyriltovena** [comment]
@chrono2002 @houstonj1 I'm working on a fix https://github.com/grafana/loki/issues/2020

**Comment by cyriltovena** [comment]
btw which Loki are you using ? Cloud / Tanka / Helm ?

**Comment by houstonj1** [comment]
@cyriltovena We are deploying Loki v1.4.1 with a custom Helm chart

**Comment by cyriltovena** [comment]
You shouldn't be impacted then. Hum.

**Comment by houstonj1** [comment]
To get things working again, I rolled back to Grafana v6.5.3

**Comment by chrono2002** [comment]
> Doesn't work for now. Alerter fires:

Upgraded to latest Loki. Everything is ok now.

**Comment by coverthesea** [comment]
hello,
error Cannot read property '__name__' of undefined

![image](https://user-images.githubusercontent.com/48321555/98801720-2ebaae00-244d-11eb-97a4-312df7ba2d4b.png)

**Comment by jengstro2** [comment]
I was able to do it. Alarm is working. Via PrometheusDatasource (LOKI as db). The tricky thing is the job names, which are prompted from loki as like this e.g. : {filename="C:\abc\xyz\Server\log\Server_Log.txt", job="My_Server_logs"}

Use regex to search *text* from the job name. That's it. 
_count_over_time({job =~ ".*My_Server_logs.*"} |~ "ERROR" [1m])_
Alarms do work from Grafana/Graph panel.
![loki_alarm_prometheys](https://user-images.githubusercontent.com/16317652/112328800-52c1b200-8cbf-11eb-9081-03e04d1a360b.PNG)
Naturally it would be nice that LOKI datasource would support directly alarms.

**Comment by cyriltovena** [comment]
Possible with the latest grafana.

**Comment by maitrungduc1410** [comment]
Latest version of grafana supports Loki Alert natively

**Comment by zquaisar** [comment]
i'm not able to get the Loki alerting working with Grafana now. It used to work in a different implementation 8 months back however not any more with Loki (2.4.2) and grafana being (8.3.6 or 8.4). This is with trying to add loki as prometheus datasource. Any help would be appreciated. 

'Error reading Prometheus: server_error: server error: 500'

**Comment by DylanGuedes** [comment]
Please note that Loki has its own data source in Grafana since a few versions ago. Try using it instead of Prometheus.

**Comment by zquaisar** [comment]
@DylanGuedes its doesn't work with the version of Grafana version 8.x. doesn't recognise the Loki endpoint '/loki'

**Comment by saibug** [comment]
same issue for me with grafana version 7/8 and loki 2.6.1
