### ISSUE TITLE
Helm release CI broken?

### ISSUE THREAD

**Issue by rlex** [grafana/loki#14258]
**Describe the bug**
Seems like last two helm charts version (6.13.0, 6.14.0) weren't released properly? https://github.com/grafana/loki/actions/runs/11030863951/job/30636372416

**To Reproduce**
N/A

**Expected behavior**
Helm chart 6.14.0 should be available

**Environment:**
N/A

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by trevorwhitney** [comment]
Thank you for reporting! This is likely due to the on-going fallout from removing PATs and needing to switch everything over to using GH apps. I will look into it.
