### ISSUE TITLE
multitenency

### ISSUE THREAD

**Issue by kfox1111** [grafana/loki#143]
The sooner we think about it, the easier it will be.

I'd like to be able to have users access just the logs for their assigned namespaces.

**Comment by kfox1111** [comment]
ok, cool.

how about a kubernetes apiserver extension? then you could reuse all the kubernetes auth bits.

**Comment by tomwilkie** [comment]
Sure, that sounds interesting!  A reverse proxy in front on loki to authenticate requests and map them to the correct instance using k8s credentials could work.  I've found k8s credentials hard to work with in the past through.  What do you have in mind?

**Comment by donmstewart** [comment]
Quick question on the current tenantid as we are using Prometheus in federated Kubernetes clusters with remote_write. Cortex is aggregating these prometheus pushes and we thought we could use the tenantId to differentiate and limit visibility of data. However, there is no way to add Http Headers using Prometheus remote_write so is this scenario possible without having to do nginx rewrite magic for each cluster which would also require changes when new clusters come online?
