### ISSUE TITLE
Refactor the labels builder to remove the StreamLabel list

### ISSUE THREAD

**Issue by ravishankar15** [grafana/loki#14307]
**Is your feature request related to a problem? Please describe.**
The current labels builder has two list base and `add[StreamLabel]` which is confusing and the `add[StreamLabel]` might not be needed since all the values are available in `base`

**Describe the solution you'd like**
https://github.com/grafana/loki/pull/13955#discussion_r1735713847

**Describe alternatives you've considered**

**Additional context**

**Comment by salvacorts** [comment]
> `fmt.go#L394` where we fetch the label if it is in base and send the category as StreamLabel

You're right, I was wrong, we do use `add[StreamLabel]`. Really good catch! 👏 

> When we initialise the builder we can copy all the labels to add[StreamLabel] and use the add[StreamLabel] for all cases

I don't think this would simplify things substantially but we may make things a bit more difficult to reason about.
As you pointed out, `base` is a read-only slice with the original stream labels, we then use the add array to overwrite/enrich the original labels from `base`. 

IMO we are good as we are now. Moreover provided this is part of the critical path of Loki, I would avoid making changes here that wouldn't solve any bug or improve the performance.

Wdyt?

**Comment by ravishankar15** [comment]
Yeah @salvacorts I agree with your thought I will close this issue.
