### ISSUE TITLE
Allow setting ingester_client.remote_timeout in loki-operator

### ISSUE THREAD

**Issue by leevi978** [grafana/loki#14326]
**Is your feature request related to a problem? Please describe.**
I am facing the same issue as described in #6182. The solution seems to be to set the `ingester_client.remote_timeout` to a value higher than 1s, but this is not an option with the loki-operator, as it is hardcoded in the loki-config.yaml file. See https://github.com/grafana/loki/blob/11b92eeb95612a2bb002ea22f048c55ae20557a2/operator/internal/manifests/internal/config/loki-config.yaml#L180

**Describe the solution you'd like**
Template the `ingester_client.remote_timeout` field in the [internal loki-config](https://github.com/grafana/loki/blob/main/operator/internal/manifests/internal/config/loki-config.yaml) in the loki-operator, so that it is no longer hardcoded as 1s, but configurable in the LokiStack CR.

**Describe alternatives you've considered**
I have not been able to find any other suitable alternatives. As far as I can see, the loki-operator hardcodes this value. If I want to overwrite it, it would be through hacks, which is not something I would like to do.

**Additional context**
I am running Loki operator v5.9.6 on OpenShift v4.14, using Vector as collectors.

**Comment by periklis** [comment]
@leevi978 Can you describe what is happening on your cluster that requires a higher timeout?

**Comment by leevi978** [comment]
@periklis 
Of course. The distributors are spamming the following log statement over and over, which seems to return a 500 status to the collectors:
```
level=error ts=2024-10-01T08:10:13.624555948Z caller=ratestore.go:303 msg="unable to get stream rates from ingester" ingester=<IP>:9095 err="rpc error: code = DeadlineExceeded desc = context deadline exceeded"
```

**Comment by leevi978** [comment]
@periklis 

It spams this log statement as well from time to time:
```
level=warn ts=2024-10-01T08:01:38.766421389Z caller=logging.go:126 orgID=application msg="POST /loki/api/v1/push (500) 1.018077949s Response: \"rpc error: code = DeadlineExceeded desc = context deadline exceeded\\n\" ws: false; Accept-Encoding: identity; Content-Encoding: snappy; Content-Length: 3344; Content-Type: application/x-protobuf; User-Agent: Vector/0.34.1 (x86_64-unknown-linux-gnu); X-Forwarded-For: 172.29.19.29; X-Forwarded-Prefix: /api/logs/v1/application; X-Scope-Orgid: application; "
```

**Comment by periklis** [comment]
@leevi978 What is the result of your investigation about the latency between distributors and ingesters on your cluster? Do you use any mesh or some sort of bare metal networking etc.?

**Comment by leevi978** [comment]
@periklis 
We are not using any sort of mesh for the log components. We have Service Mesh on the cluster, but none of the log stack components are on the mesh. We are running on Azure Red Hat OpenShift, and have implemented the LokiStack according to [Red Hats documentation for OpenShift Container Platform v4.14](https://docs.openshift.com/container-platform/4.14/observability/logging/cluster-logging-deploying.html).

Does this answer your question, or did I misunderstand what you are asking?

**Comment by periklis** [comment]
@leevi978 Regardless what you run on, I suggest to troubleshoot the network latency between the distributor and ingester pods. I agree that the value we use is quite eager. I suspect we keep this using the default since Loki 2.2 when we started designing/developing the Loki Operator. The value default moved nowadays to `5s`. However I would like to understand under what circumstances you see a latency happening here. 

In further note, we are very very savvy opening Loki configuration options on the LokiStack CRD. In fact we have a ratio of ~10% options provided for the sake of keeping LokiStack uniform and easy to handle.

**Comment by leevi978** [comment]
@periklis I understand why you're hesitant to add new configuration, and I appreciate CRD's that requires the minimum amount of work to set up. I will troubleshoot the network latency further, as you're suggesting.

However, I do have questions. I am quite novice in the field of cluster logging, so feel free to let me know if there are aspects I am missing. But wouldn't restricting the timeout to 1s no matter what restrict the possibility of running Loki-operator on clusters with variable network stability? Organizations doesn't necessarily use open-source tools uniformly, and some may be more susceptible to network latency than others. I assume that might be why the default in Loki has been changed to `5s`.

**Comment by periklis** [comment]
> However, I do have questions. I am quite novice in the field of cluster logging, so feel free to let me know if there are aspects I am missing. But wouldn't restricting the timeout to 1s no matter what restrict the possibility of running Loki-operator on clusters with variable network stability? Organizations doesn't necessarily use open-source tools uniformly, and some may be more susceptible to network latency than others. I assume that might be why the default in Loki has been changed to `5s`.

Since this is the first report ever about this setting, I guess we do not have any limitation on our customer base. At least from the thousand of clusters out there, I have no report or customer case that this is an issue.

**Comment by someStrangerFromTheAbyss** [comment]
Want to add i just tested the fix mentionned in the issue linked in the OP. Fixed our issue of context deadline and we use Helm to deploy the loki solution.

Ill start working on it tomorrow since we need it for our production.

**Comment by someStrangerFromTheAbyss** [comment]
After some investigation, this feature will not be needed. Turns out, the issue was something else. I apologize but i will not be working on that.

**Comment by leevi978** [comment]
> After some investigation, this feature will not be needed. Turns out, the issue was something else. I apologize but i will not be working on that.

@someStrangerFromTheAbyss Great that you found the issue! May I ask what caused it? I still haven't been able to identify the issue in my own cluster.
