### ISSUE TITLE
[loki-canary] Stream label configuration

### ISSUE THREAD

**Issue by theo-lubert** [grafana/loki#1435]
**Is your feature request related to a problem? Please describe.**

We are currently trying to get `loki-canary` to work with the `Docker log driver` in a Swarm environnement. But it seems they are simply not compatible, as `loki-canary` is incapable of fetching the correct labels (there are "labelname" and "labelvalue" configurations already, but one is missing for "stream").

Loki-canary expects a "stream" label (stdout/stderr), while the Docker log driver publishes this under the "source" label. Looking at the source code, it looks like both are hardcoded.

Example:
```
loki-canary:
  query={stream="stdout",swarm_service="monitoring_loki-canary"} => KO (Empty)

manually:
  query={source="stdout",swarm_service="monitoring_loki-canary"} => Success
```

**Source:**

[loki-canary (reader.go #L106)](https://github.com/grafana/loki/blob/b34c2b0bd35e742057ede230e42305ec79f11c1b/pkg/canary/reader/reader.go#L106)

[Docker log driver (loki.go #L60)](https://github.com/grafana/loki/blob/b1e232c00720ff5a536b0c3d410a721354899e6e/cmd/docker-driver/loki.go#L60)

**Describe the solution you'd like**

Both projects should allow customization, starting with `loki-canary` to mitigate this very case.
But I think that the `Docker log driver` should too, in order to play nice with other implementations based on "stream" that might exist (canary, generic grafana dashboards, etc)

**Describe alternatives you've considered**

There are no known workarounds.
We could use promtail of course, but it would defeat the purpose of `loki-canary`, since we would use a different log transmission medium for the rest of the swarm (`Docker log driver`).

**Additional context**
_none_

**Comment by rndmh3ro** [comment]
I'm experiencing the same problem. `loki-canary` in combination with the docker-driver is sadly unusable with this bug.

Can we reopen this?
