### ISSUE TITLE
Helm release CI broken for 6.17

### ISSUE THREAD

**Issue by perosb** [grafana/loki#14373]
**Describe the bug**
Similar to #14258 there seem to be issues pushing new helm release.
Latest 6.17 is still missing/broken with "Bad credentials" https://github.com/grafana/loki/actions/runs/11140450797/job/30959240111

**Comment by LukoJy3D** [comment]
Got a response in slack that `It's already being triaged by the engineering team`

**Comment by rlex** [comment]
Just wanted to chime in - pyroscope seemingly have same issue. Given it's also grafana project, might be worth a mention.

**Comment by deb0ro** [comment]
Any new update here? We are waiting for 3.2.0 to test bloom filters. Thanks! :)

**Comment by deb0ro** [comment]
Hi @trevorwhitney , since you work on the similar bug, can you check this one as well? Thanks!

**Comment by rlex** [comment]
@deb0ro in the meantime you can use last available version (6.16.0) and set loki.image.tag value to 3.2.0, it will work with blooms.

**Comment by Starefossen** [comment]
Please fix the broken CI!

**Comment by trevorwhitney** [comment]
PR to fix the weekly releases: https://github.com/grafana/loki/pull/14501
This will create PRs that look like https://github.com/grafana/loki/pull/14509 that when merged should trigger https://github.com/grafana/loki/pull/14501/files#diff-e55e8b28bf787ec17d6f2b235a396d3256da0ec8b9818603c61b46197d84e6c0

**Comment by trevorwhitney** [comment]
6.18.0 appears to have released correctly: https://github.com/grafana/helm-charts/commit/b138bb7e5b63179b691988953180996e5bc5efb8
