### ISSUE TITLE
promtail don't scrape spark-driver logs from spark-operator

### ISSUE THREAD

**Issue by oliv3340** [grafana/loki#1439]
**Describe the bug**
When a spark application is submit to spark-operator, logs from spark executors are correctly scrape but not logs from the spark driver.

**To Reproduce**
0. Setup k8s
1. Started Loki master helm chart ($ helm upgrade --install loki loki/loki-stack)
2. Started Spark Operator 
$ helm repo add incubator http://storage.googleapis.com/kubernetes-charts-incubator
$ helm install incubator/sparkoperator --namespace spark-operator --set sparkJobNamespace=default
3. Submit spark example application with kubectl apply (yaml are here under examples : https://github.com/GoogleCloudPlatform/spark-on-k8s-operator)
4. Check spark logs

**Expected behavior**
Getting spark driver logs on loki

**Environment:**
 - Infrastructure: k8s v1.15
 - Deployment tool: helm & kubectl apply

**Screenshots, Promtail config, or terminal output**
None.

**Details**
I haven't make any changes on promtail config. I'm pretty new on k8s so I'm lost about where the problem could be and how to play with metadata to correctly scrape the missings logs.

Tell me if you need more informations about my use case.

**Comment by warrenzhu25** [comment]
I also faced same issue. Could anybody help?
