### ISSUE TITLE
Outdated Query Acceleration with Blooms Doc

### ISSUE THREAD

**Issue by emadolsky** [grafana/loki#14414]
**Describe the issue**
The doc [Query Acceleration with Blooms (Experimental)](/grafana/loki/blob/main/docs/sources/operations/query-acceleration-blooms.md) contains outdated information about n-grams even though the blooms are being created from structured metadata instead of the n-grams.

**Expected **
A clear and concise description of the latest developments on Blooms, and the current way the blooms are built and used.

**Comment by emadolsky** [comment]
cc: @chaudum

**Comment by chaudum** [comment]
Thanks @emadolsky We will update the docs accordingly.
