### ISSUE TITLE
Missing permissions for DynamoDB

### ISSUE THREAD

**Issue by a-hat** [grafana/loki#1443]
https://github.com/grafana/loki/blob/master/docs/operations/storage/README.md lists the IAM permissions required for the DynamoDB backend.

I added all those permission, but loki fails to operate, unless I create these additional permissions:

`dynamodb:CreateTable` on `arn:aws:dynamodb:<aws_region>:<aws_account_id>:table/<prefix>*`
`dynamodb:ListTables` on `arn:aws:dynamodb:<aws_region>:<aws_account_id>:table/*`

`CreateTable` makes sense to me, and should probably be added to the documentation.

I am not sure, why loki needs `ListTables` without the table prefix. In the documentation this permission is listed as a requirement for auto-scaling, however I am using the loki helm chart, and auto-scaling seems to be disabled by default.

**Comment by chancez** [comment]
@a-hat Loki dynamically creates tables per chunk period and listing tables in the AWS API doesn't work on a prefix basis so it needs the capability of listing all tables. At least this is my understanding from reading the code.

**Comment by Eraac** [comment]
> Loki dynamically creates tables per chunk period and listing tables in the AWS API doesn't work on a prefix basis so it needs the capability of listing all tables

Absolutely, I've write this documentation and I don't know why I forgot CreateTable, but is fixed now
