### ISSUE TITLE
too many failed ingesters (unstable ring)

### ISSUE THREAD

**Issue by tivvit** [grafana/loki#1444]
Hi I am running Loki in version 1.0.0 in k8s.

I am facing problems with ring consistency. I think it is caused by not balanced traffic to the ingesters - some of them are constant in terms of free RAM but some of them are consuming RAM quickly and then they are killed by OOM - after the restart, they are not accepted to the ring. I thought adding more ingesters would solve the problem (the traffic will be more balanced) but the ring seems even less stable. 

Additional info:
* #ingesters: 60
* #messages: 350k/s
* ingester RAM: 10GB
* ring backend: consul
* replication factor: 2

Any suggestions?

**Comment by slim-bean** [comment]
60 ingesters! awesome.

Unfortunately Consul is a problem at this scale, however there are a few things you can try which have helped us:

  * Mount the consul data directory into a ramdisk, the data stored in consul is essentially ephemeral, if it's lost the ingesters will replace it, so mounting the consul store in a ramdisk can improve performance substantially
  * Tweak the healthchecks:  `--no-consul.health-summary` and `--consul.allow_stale`
  * Snapshot raft.db more frequently to keep it from getting too big
    `"raft_snapshot_threshold": 128, "raft_trailing_logs": 10000,`

Here is an example deployment yaml:

```
Pod Template:
  Labels:           name=consul
  Annotations:      consul-hash: e56ef6821a3557604caccaf6d5820239
  Service Account:  consul-sidekick
  Containers:
   consul:
    Image:       consul:1.5.3
    Ports:       8300/TCP, 8301/TCP, 8400/TCP, 8500/TCP
    Host Ports:  0/TCP, 0/TCP, 0/TCP, 0/TCP
    Args:
      agent
      -ui
      -server
      -client=0.0.0.0
      -config-file=/etc/config/consul-config.json
      -bootstrap-expect=1
    Requests:
      cpu:     100m
      memory:  500Mi
    Environment:
      CHECKPOINT_DISABLE:  1
    Mounts:
      /consul/data/ from data (rw)
      /etc/config from consul (rw)
   sidekick:
    Image:      weaveworks/consul-sidekick:master-f18ad13
    Port:       <none>
    Host Port:  <none>
    Args:
      --namespace=$(POD_NAMESPACE)
      --pod-name=$(POD_NAME)
    Environment:
      POD_NAMESPACE:   (v1:metadata.namespace)
      POD_NAME:        (v1:metadata.name)
    Mounts:
      /consul/data/ from data (rw)
      /etc/config from consul (rw)
   statsd-exporter:
    Image:      prom/statsd-exporter:v0.12.2
    Port:       8000/TCP
    Host Port:  0/TCP
    Args:
      --web.listen-address=:8000
      --statsd.mapping-config=/etc/config/mapping
    Environment:  <none>
    Mounts:
      /consul/data/ from data (rw)
      /etc/config from consul (rw)
   consul-exporter:
    Image:      prom/consul-exporter:v0.5.0
    Port:       9107/TCP
    Host Port:  0/TCP
    Args:
      --consul.server=localhost:8500
      --web.listen-address=:9107
      --consul.timeout=1s
      --no-consul.health-summary
      --consul.allow_stale
    Environment:  <none>
    Mounts:
      /consul/data/ from data (rw)
      /etc/config from consul (rw)
  Volumes:
   consul:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      consul
    Optional:  false
   data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
```

And config:

```

/cc @mizeng I believe you were also having consul troubles with a high ingester count and may want to give this a try too.

**Comment by tivvit** [comment]
Thanks for the quick reply. I will try the suggested changes.

Do you think it would be better to use Etcd instead?

**Comment by tivvit** [comment]
Another question. Is it better to have big ingesters? I can scale them down and make them bigger but it would be even harder to redeploy them after that.

**Comment by slim-bean** [comment]
yeah making them big comes with other problems, I think it's probably better to keep them small and use more of them.

We've not used etcd for the ring, not sure if it's supported out of the box or not if it is you may want to give it a try!

**Comment by sc7565** [comment]
Our testing, proved etcd server stable than consul with default configuration, if this helps

**Comment by tivvit** [comment]
Thanks for your suggestions. 

I am running Consul in the VM (not k8s), I used a much bigger instance (which is able to store more file cache), therefore I did not need to use ramdisk. I have also used longer `heartbeat_period`.

The ring is stable now.

I did not try the ETCD and for now, Consul works for me. I will try it if I will encounter problems again.
