### ISSUE TITLE
Failed batch due to entry out of order leads to stuck Loki timestamps

### ISSUE THREAD

**Issue by jheusser** [grafana/loki#1449]
**Describe the bug**

After a single Promtail process reports a "final error sending batch" due to "entry with timestamp 2019-12-08 00:34:40.966000015 +0000 UTC ignored, reason: 'entry out of order' for stream: ..." any log line (from independent Promtail processes) sent to Loki are somehow stored at the timestamp "13:59:59.." when querying Loki, even most recently written data. If a query does not go back past 13:59:59 of the current day then it appears as if Loki does not have any recent log lines written to.

Once the offending Promtail process is restarted Loki starts reporting data at correct timestamps again, no Loki restart required.

**To Reproduce**

Hard to reproduce. Send out of order timestamps from Promtail to Loki.

**Expected behavior**

Promtail log lines that have timestamps out of order are ignored and do not mess up Loki.

**Environment:**

- Linux 4.4.0-142-generic #168-Ubuntu

- Promtail: 

promtail, version v1.1.0 (branch: HEAD, revision: 191f87a3)
  build user:       root@9579864ae191
  build date:       2019-12-04T18:26:05Z
  go version:       go1.13.4

- Loki:

loki, version v1.1.0 (branch: HEAD, revision: 191f87a3)
  build user:       root@9579864ae191
  build date:       2019-12-04T18:26:05Z
  go version:       go1.13.4

- LogCLI:

logcli, version  (branch: , revision: )
  build user:
  build date:
  go version:       go1.13.4

**Screenshots, Promtail config, or terminal output**

Promtail error journal:
"... level=error ts=2019-12-20T04:52:38.062235011Z caller=client.go:231 component=client host=hostname msg="final error sending batch" status=400 error="server returned HTTP status 400 Bad Request (400): entry with timestamp 2019-12-20 04:52:37.171000001 +0000 UTC ignored, reason: 'entry out of order' for stream: ...."

Querying/tailing recent Loki for log lines for this or any other Promtail instance:
**2019-12-21T13:59:59+01:00** 2019-12-21 15:43:42.698 INFO ....

Latest Loki log lines are always fixed to 13:59:59. Queries on recent data fail unless start time is before 13:59:59. Any new log line is recorded at this same second.

**Comment by sandlis** [comment]
Can you please try enabling debug logs in promtail and reproduce it?
I suspect it could be due to mismatch in timestamp format for some of the log lines.
2 timestamps in your example query response makes my doubt stronger for mismatch in timestamp format.
> 2019-12-21T13:59:59+01:00 2019-12-21 15:43:42.698 INFO ...

Maybe you can verify that by looking at logs which have a fixed timestamp.
FYI, In promtail you can configure actions for log lines which have timestamps which cannot be parsed. The default action is to use last successfully parsed timestamp.

**Comment by jheusser** [comment]
Thanks @sandlis!

Just for completion, I turned on Promtail debug logging (`-log.level=debug`) which eventually showed the issue being the custom [timestamp stage](https://github.com/grafana/loki/blob/master/docs/clients/promtail/stages/timestamp.md) format, which was erroneously using 12-hour zero prefixed instead of 24-hour. This in turn rejects any log lines after 12:59:59 UTC.
