### ISSUE TITLE
logcli should send Accept-Encoding: gzip

### ISSUE THREAD

**Issue by jtackaberry** [grafana/loki#14597]
**Is your feature request related to a problem? Please describe.**

We use logcli for bulk downloading large amounts of log data.  Data is not compressed in transit, which unnecessarily inflates data transfer costs.

**Describe the solution you'd like**

logcli should pass `Accept-Encoding: gzip` to Loki and handle gzip-compressed payloads.

**Describe alternatives you've considered**

Pay 10-15x more in data transfer costs :)

**Additional context**

N/A

**Comment by chaudum** [comment]
@jtackaberry I merged your PR

**Comment by jtackaberry** [comment]
Thanks @chaudum!
