### ISSUE TITLE
Ability to alter number of returned log lines on a query by query basis.

### ISSUE THREAD

**Issue by AndrewNeudegg** [grafana/loki#1461]
**Is your feature request related to a problem? Please describe.**

Some applications generate large numbers of log entries when in a faliure condition (Elasticsearch), this limits our ability to diagnose problems since the number of log entries in a particular second can be greater than our default max number of lines to return. This can make it tricky to diagnose issues.

Increasing the max returned lines can degrade performance for all users, if many users are querying with complex queries.

**Describe the solution you'd like**
The ability to increase the maximum number of lines returned on a query by query basis provided that the user supplied max number of lines is less than some operator configurable value.

Ideally this would change the configuration `maxLines: xxx` to `defaultMaxLines: xxx`.

It would be useful if this `maxLines` value could be supplied through the Grafana Loki UI (Dashboards view), so that a user did not have to use the cli in order to override this value.

**Describe alternatives you've considered**
- Pagination, this would be a good alternative but might requre more work to integrate into the UI. If not implemented correctly it could be difficult to use. 
- Permently increasing the number of log lines that are returned, it would be nice to not have to over-provision resources.

**Comment by cyriltovena** [comment]
/cc @davkal 

How about a query string to avoid duplicates server side ?

**Comment by davkal** [comment]
There will be a per-query line limit in Explore soon: https://github.com/grafana/grafana/pull/21089

Also, we'll soon work on pagination/scrolling: https://github.com/grafana/grafana/issues/19354

**Comment by AndrewNeudegg** [comment]
Thanks, will close this issue
