### ISSUE TITLE
[OTLP Endpoint] Add `deployment.environment.name` to the list of promoted resource attributes

### ISSUE THREAD

**Issue by cyrille-leclerc** [grafana/loki#14658]
**Is your feature request related to a problem? Please describe.**

OpenTelemetry semantic convention renamed the `deployment.environment` resource attribute into `deployment.environment.name` ([here](https://opentelemetry.io/docs/specs/semconv/resource/deployment-environment/)) and the Loki OTLP endpoint is only promoting `deployment.environment` as logstream label, creating a feature gap for users embracing the new attribute name.

**Describe the solution you'd like**

The Loki OTLP endpoint could by default promote as logstream label the new resource attribute `deployment.environment.name` in addition to the already promoted `deployment.environment` to help users migrate.

Note that we probably don't want to do renaming during the ingestion and help users migrating to just one name as such a schema normalization capability is not in place in any of Loki, Mimir, Tempo, or Pyroscope components today.

**Describe alternatives you've considered**

Don't change the default behaviour, let users encounter regressions as they adopt the new resource attribute name and figure out themselves the solution: edit the Loki config file for self managed users and open a support ticket for Grafana Cloud users.

**Additional context**

cc @sandeepsukhani and @vlad-diachenko for Loki, cc @aknuds1 and @jesusvazquez who are rolling out a similar resource attribute promotion feature in for Prometheus & Mimir.

**Comment by jesusvazquez** [comment]
I've made sure to record this as well in our design doc to do this in Mimir https://docs.google.com/document/d/1tVeuVvt4A_Y9bDUqivngnmFnXSA06ge9wONbvfMz5PQ/edit?tab=t.0 thanks @cyrille-leclerc
