### ISSUE TITLE
Request data older than the retention_period result as an error

### ISSUE THREAD

**Issue by Eraac** [grafana/loki#1467]
**Describe the bug**
If via Grafana you request 30 days of logs with a retention_period of 2 weeks, Loki return an error

**To Reproduce**
1. Started Loki (2 weeks of retention_period for the index, store in dynamoDB)
3. Query last 30 days of data

**Expected behavior**
Loki shouldn't try to read deleted index (and generate error)

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm
 - Loki version: 1.2

**Logs in Grafana**
```
QueryPage error: table=loki_index_2605, err=ResourceNotFoundException: Requested resource not found status code: 400, request id: SJQA2EBBC38QBE9G0QT2FBH8PNVV4KQNSO5AEMVJF66Q9ASUAAJG
```

`loki_index_2605` is an old table (dynamoDB), ~ 5 weeks old I guess, so with a retention_period of 2 weeks this table doesn't exist anymore

**Comment by sandlis** [comment]
While updating retention, ideally you should also change max look back period [here](https://github.com/grafana/loki/blob/master/cmd/loki/loki-local-config.yaml#L41).
Do you want to contribute by adding a check for it and update relevant documentation?
