### ISSUE TITLE
Loki Logcli is not working

### ISSUE THREAD

**Issue by AnandPalani92** [grafana/loki#1468]
**Describe the bug**
I have tried the loki logcli to access the container logs on kubernetes and itsn't not working. I used to following way as per the loki documentation. Environment vars exposed as mentioned.
$ export GRAFANA_ADDR=https://test.grafanadomain.com
$ export GRAFANA_USERNAME=admin
$ export GRAFANA_PASSWORD=admin123

After exposed the environment vars and i got following error.

![Capture1](https://user-images.githubusercontent.com/15903560/71796845-c8694000-3071-11ea-948c-607ada5210e6.PNG)

**Expected behavior**
logcli labels analytics
https://monitoring-dev.example.com//loki/api/v1/label/analytics/values
Error doing request: readObjectStart: expect { or n, but found <, error found in #1 byte of ...|<!DOCTYPE h|..., bigger context ...|<!DOCTYPE html>
<html lang="en">

<head>
  <meta ch|...

**Environment:**
 - Infrastructure: Aws EKS environment
 - Deployment tool: helm charts

**Screenshots, Promtail config, or terminal output**
![image](https://user-images.githubusercontent.com/15903560/71796888-f51d5780-3071-11ea-916e-4fb8b7c10117.png)

**Comment by sandlis** [comment]
Can you please try hitting that URL directly using a browser and see what HTML is being returned? I suspect some other component is erroring out and the request is not even reaching Loki.

**Comment by AnandPalani92** [comment]
Thanks Sandeep for your response.

When I tried the URL and it's showing 404 not found error.

While checking grafa logs there no hit on that.

**Comment by sandlis** [comment]
I think the issue is with the url that is set in GRAFANA_ADDR. It should be pointing to loki server, not grafana since logcli is meant to talk to loki server directly. Can you please give a try after updating it?

**Comment by AnandPalani92** [comment]
Yes. Its working now. as per the Docs i just given the Grafana url

Thanks for your prompt response
