### ISSUE TITLE
CI: Helm chart publishing still broken

### ISSUE THREAD

**Issue by trevorwhitney** [grafana/loki#14835]
#14799 fixed the `helm-ci` action, allowing helm PRs to be merged. However, publishing releases is still broken:
* https://github.com/grafana/loki/actions/runs/11727098884/job/32667387047
* https://github.com/grafana/loki/actions/runs/11728642157/job/32672566084

```
Run helm push "/home/runner/work/loki/loki/.cr-release-packages/loki-6.19.0.tgz" "oci://ghcr.io/${GITHUB_REPOSITORY_OWNER}/helm-charts"
  helm push "/home/runner/work/loki/loki/.cr-release-packages/loki-6.19.0.tgz" "oci://ghcr.io/${GITHUB_REPOSITORY_OWNER}/helm-charts"
  shell: /usr/bin/bash -e {0}
  env:
    CR_CONFIGFILE: /home/runner/work/loki/loki/source/production/helm/cr.yaml
    CT_CONFIGFILE: /home/runner/work/loki/loki/source/production/helm/ct.yaml
    CR_INDEX_PATH: /home/runner/work/loki/loki/.cr-index
    CR_PACKAGE_PATH: /home/runner/work/loki/loki/.cr-release-packages
    CR_TOOL_PATH: /home/runner/work/loki/loki/.cr-tool
    HELM_TAG_PREFIX: helm
    github_app_id: ***
    AUTHTOKEN: ***
Error: unexpected status from POST request to https://ghcr.io/v[2](https://github.com/grafana/loki/actions/runs/11727098884/job/32667387047#step:18:2)/grafana/helm-charts/loki/blobs/uploads/: 403 Forbidden
Error: Process completed with exit code 1.
```

Last successful run was 3 weeks ago: https://github.com/grafana/loki/actions/runs/11374046600

**Comment by trevorwhitney** [comment]
@morganrowse if you're still interested, looks like the saga isn't quite over

**Comment by morganrowse** [comment]
Hi @trevorwhitney just got back from leave ready to look into this. 

I have a theory that this CI bug was introduced by some upstream changes to `grafana/helm-charts` shared github actions [here]( https://github.com/grafana/helm-charts/commits/main/.github/workflows/update-helm-repo.yaml), The `grafana/loki` actions make use of the `main` [here](https://github.com/grafana/loki/blob/main/.github/workflows/helm-release.yaml#L14), something akin to using `latest` on a docker container.

Reviewing later runs of this helm-release action [here](https://github.com/grafana/loki/actions/runs/11864074832/job/33066809449). A new issue is occurring where it fails trying to create a helm tag that already exists.

```
Making tag helm-loki-6.19.0
fatal: tag 'helm-loki-6.19.0' already exists
Error: Process completed with exit code 128.
```

Ill look into it this morning.

**Comment by narqo** [comment]
> Im not seeing any fundemental code differences between mimr and loki CI. Are there GitHub app or repo permission settings required to get this working as expected?

It should just work since https://github.com/grafana/helm-charts/pull/3424 (it works for k6-operator also).

**Comment by trevorwhitney** [comment]
@narqo we're referencing thew workflow @ `main` but still seeing those 403 errors `Error: unexpected status from POST request to https://ghcr.io/v2/grafana/helm-charts/loki/blobs/uploads/: 403 Forbidden`

**Comment by trevorwhitney** [comment]
Awesome, thanks @morganrowse, I reverted the release pipeline to `70dbbb722dee3f2ee126e12684cc0e92a20972ed` before the `ghcr` changes, and our release went out successfully this week. Going to keep this issue open until we fix it for real though, as we should bring back the `ghcr` pushing.

**Comment by flostru** [comment]
Bump

We are migrating all our internal dependencies to dedicated OCI Paths, Loki ist one of the last ones remaining.

```bash
$ skopeo list-tags docker://ghcr.io/grafana/helm-charts/loki
{
    "Repository": "ghcr.io/grafana/helm-charts/loki",
    "Tags": [
        "6.20.0-weekly.229"
    ]
}
```

**Comment by trevorwhitney** [comment]
@flostru we fixed the traditional helm publishing by removing the ghcr step, which never worked. Would you mind creating a new ticket with your request that we publish to ghcr and I'll bring it up with the team / other maintainers?
