### ISSUE TITLE
Helm Hub cannot show README for loki, loki-stack, promtail

### ISSUE THREAD

**Issue by oke-py** [grafana/loki#1483]
**Describe the bug**
Helm Hub cannot show README for loki, loki-stack, promtail.
README URL returns 404.

- https://hub.helm.sh/charts/loki/loki
- https://hub.helm.sh/charts/loki/loki-stack
- https://hub.helm.sh/charts/loki/promtail

See: https://github.com/helm/hub/issues/225

**To Reproduce**
N/A

**Expected behavior**
README can be shown in Helm Hub.
Only https://hub.helm.sh/charts/loki/fluent-bit works fine for now.

**Environment:**
N/A

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

![loki](https://user-images.githubusercontent.com/4710215/71967207-4bdb8a80-3246-11ea-86e8-968fed2ce694.png)

**Comment by oke-py** [comment]
> the problem in your case is that the urls are not complete:
> ```
>   - apiVersion: v1
>     appVersion: v1.2.0
>     created: 2020-01-08T08:12:23.012221912Z
>     description: 'Loki: like Prometheus, but for logs.'
> ...
>     urls:
>     - loki-0.21.0.tgz
>     version: 0.21.0
> ```
> That url should be the complete URL to the tarball.

https://github.com/helm/hub/issues/225#issuecomment-571943163

**Comment by slim-bean** [comment]
I think this is related to another issues and should be fixed

**Comment by oke-py** [comment]
wontfix?

**Comment by cyriltovena** [comment]
No we just didn't found the time to do it.
