### ISSUE TITLE
Documentation feedback: /docs/sources/configure/_index.md

### ISSUE THREAD

**Issue by daimalou** [grafana/loki#14854]
https://grafana.com/docs/loki/latest/configure/#printing-loki-config-at-runtime

The Right TOC Scroll Height need expand.  It's very very hard to scroll.

**Comment by JStickler** [comment]
Our website team controls that, I've asked them if there's anything we can do to expand the scrollable area.

**Comment by JStickler** [comment]
@daimalou Just to follow up, there is a draft PR in progress to fix this issue.  Thanks for reporting it.
