### ISSUE TITLE
loki docker log driver and its docker-compose logs behaviour 

### ISSUE THREAD

**Issue by iammteah** [grafana/loki#1487]
Hello there,

Is there a way to get the container logs with the ```docker-compose logs``` command as well beside the ```docker logs``` command, which is working well?

I've got the standard config for the loki docker log driver like
```
{
    "debug" : true,
    "log-driver": "loki",
    "log-opts": {
        "loki-url": "https://api.url/loki/api/v1/push",
      }
  }
```

and when I call for logs with ```docker-compose logs``` I get something like
```user@server /srv/docker/app # docker-compose logs 
Attaching to appserver, db
appserver    | WARNING: no logs are available with the 'loki' log driver
db           | WARNING: no logs are available with the 'loki' log driver
``` 
while with ```docker logs``` I get normal log output

docker-compose versions tried: 1.23.1 , 1.25.1

**Comment by cyriltovena** [comment]
I think you need a license but I might be wrong, on the Loki side we keep the json log driver running while sending to Loki, you should be able to find them on the host.

This might be an opportunity to update the documentation.

**Comment by cyriltovena** [comment]
In fact there’s an API to implement: https://docs.docker.com/engine/extend/plugins_logging/#logdriverreadlogs

**Comment by cyriltovena** [comment]
We are in fact implementing this API.

but 

For those who have the issue related to `no logs are available` this is in fact on purpose from the docker-compose tooling.

see https://github.com/docker/compose/blob/master/compose/container.py#L196

Basically no log  from docker-compose if you use a plugin, not sure why. But docker logs should work still, if you want to use that.

If someone wants to open an issue on their side, feel free to do so.
