### ISSUE TITLE
Loki Read and write performance analysis

### ISSUE THREAD

**Issue by yang3808282** [grafana/loki#1491]
Can give some performance index data for comparison of loki and ES? And where does loki improve write performance over ES?

**Comment by sandlis** [comment]
We don't have any numbers but you can look at the following blog post which shows why [Insider](https://insider.in/)(a famous company from India which sells tickets for events/concerts) switched from ES to Loki, which includes factors like scalability, cost, drop in average response time to issues etc.
https://grafana.com/blog/2019/11/19/how-loki-helped-paytm-insider-save-75-of-logging-and-monitoring-costs/

**Comment by yang3808282** [comment]
> We don't have any numbers but you can take a look at the following blog post which shows why [Insider](https://insider.in/)(a famous company from India which sells tickets for events/concerts) switched from ES to Loki, which includes factors like scalability, cost, drop in average response time to issues etc.
> https://grafana.com/blog/2019/11/19/how-loki-helped-paytm-insider-save-75-of-logging-and-monitoring-costs/

thanks for your reply. I want to test the write performance and read data performance of loki, such as write time, the amount of disk occupied by the data, and the time required to read the data. Please guide me how to do it
