### ISSUE TITLE
ELK comparison to Loki

### ISSUE THREAD

**Issue by tomwilkie** [grafana/loki#150]
We should include a comparison between the Loki stack and the ELK stack. See https://www.reddit.com/r/kubernetes/comments/a6zbnq/grafanaloki_like_prometheus_but_for_logs/ec1g3qg/

**Comment by daixiang0** [comment]
maybe compare with EFK is better.

**Comment by takanabe** [comment]
I think the explanation is listed https://github.com/grafana/loki#loki-like-prometheus-but-for-logs 

But if you think that the explicit comparisons are necessary between Grafana + Loki and EFK, I may send PRs to make my understanding against the systems more confident...

**Comment by schrej** [comment]
Can't this be closed since #982 added a [comparison section](https://github.com/grafana/loki/blob/master/docs/overview/comparisons.md)?

**Comment by cyriltovena** [comment]
Yes thank you for the reminder

**Comment by QuinnBast** [comment]
The comparison documentation linked above seems to have disappeared.

**Comment by schrej** [comment]
It only got moved: https://github.com/grafana/loki/blob/master/docs/sources/overview/comparisons.md

**Comment by kokizzu** [comment]
link is broken btw '__')
