### ISSUE TITLE
[3.3.0] loki-local-config.yaml#L41 causing startup failure

### ISSUE THREAD

**Issue by tgurr** [grafana/loki#15039]
**Describe the bug**
When trying to start loki 3.3.0 with the default [loki-local-config.yaml](https://github.com/grafana/loki/blob/v3.3.0/cmd/loki/loki-local-config.yaml) from the release/tagged 3.3.0 tarball loki fails to start with:

```
Nov 20 16:06:21 localhost loki[897933]: failed parsing config: /etc/loki/config.yml: yaml: unmarshal errors:
Nov 20 16:06:21 localhost loki[897933]:   line 41: field enabled not found in type aggregation.Config. Use `-config.expand-env=true` flag if you want to expand environment variables in your config file
```

To offending line is https://github.com/grafana/loki/blob/v3.3.0/cmd/loki/loki-local-config.yaml#L41, after removing it loki 3.3.0 starts up fine.

**To Reproduce**
1. Use [loki-local-config.yaml](https://github.com/grafana/loki/blob/v3.3.0/cmd/loki/loki-local-config.yaml) shipped with loki 3.3.0
2. Try to start loki 3.3.0

**Expected behavior**
Service running

**Environment:**
 - Infrastructure: pc
 - Deployment tool: none

**Screenshots, Promtail config, or terminal output**
https://github.com/grafana/loki/blob/v3.3.0/cmd/loki/loki-local-config.yaml#L41

**Comment by bursan85** [comment]
Nice, thank you.
Also, as a temporary workaround for Almalinux if the person is not fun of editing the config file,  just install an older version of the package loki. This also works.

sudo dnf install loki-3.2.1-1.x86_64
sudo systemctl restart loki

**Comment by jd-apprentice** [comment]
After following the installation guide from here https://grafana.com/docs/loki/latest/setup/install/local/

I also got this error, for now I just commented the line like this

![Image](https://github.com/user-attachments/assets/4c4e2391-1f7e-4b4a-8ca1-e1d1bf13c122)

![Image](https://github.com/user-attachments/assets/6e910373-9e56-4f1f-a900-9cbe15fb240d)
