### ISSUE TITLE
Improve indexing of log stream metadata

### ISSUE THREAD

**Issue by slim-bean** [grafana/loki#1507]
**Is your feature request related to a problem? Please describe.**

Queries such as `rate` and `count_over_time` can be very slow as they require downloading and decompressing every chunk that matches the label.

**Describe the solution you'd like**

For queries which do not have filters (e.g. `|=`) if Loki stored entry counts as metadata in the chunk header we could only download the chunk header for each chunk and avoid decompressing entirely, this would improve performance for these queries significantly.

This only works if you don't filter, and also would see max performance if we only downloaded the header of the chunk rather than the entire chunk.

**Comment by cyriltovena** [comment]
From some discussion with @gouthamve, we might want to use the index instead, at the same time this might be an opportunity to register difference schema/index for Loki itself.

**Comment by cyriltovena** [comment]
Forgot to mention that this won't help metrics queries as they are relative to the start,end and step. So we don't have the distribution over time, which what the metrics queries are returning.

However using the index to store more information is definitively interesting for other use cases.

**Comment by cyriltovena** [comment]
I definitely agree with you @owen-d (created an issue for your idea https://github.com/grafana/loki/issues/1584),  we have 3 good usages for Loki to contains metrics about streams without processing them:
- Query frontend can use those for query planning.
- Series API could be faster and richer. (contain more info without downloading logs)
- We could be way faster for `count_over_time` and `rate`. (not for filter queries though)

We should do something !

Crazy idea: should we just ingest (or optionally remote write/remote read) tsdb chunks, I mean the ruler also needs this too, we would have data over time.

**Comment by slim-bean** [comment]
I've updated the title of this issue to better reflect what we need going forward which is a way to get some info about the volume of logs a query will have to process.

**Comment by slim-bean** [comment]
Closing this issue for now, this is still something we will eventually look into at a later point.

**Comment by arun11299** [comment]
@slim-bean This would be really good improvement. Rate and count is something I personally need to look at the health and overall sanity of the logs being generated. These certainly get very slow or timeout when viewing the data over a period of 12 hours or so.

**Comment by slim-bean** [comment]
Something you can do today which we do for a much more efficient way to just do log line counting is do this at the agent level in promtail:

https://grafana.com/docs/loki/latest/clients/promtail/stages/metrics/#counter

This is what it looks like in our environment

```
 - metrics:
            byte_count_total:
                config:
                    action: add
                    count_entry_bytes: true
                    match_all: true
                description: A running counter of all bytes per stream with their
                    corresponding labels
                type: Counter
            line_count_total:
                config:
                    action: inc
                    match_all: true
                description: A running counter of all lines with their corresponding
                    labels
                type: Counter
`

This ticket was closed because it's unlikely we will add this metadata to the index anytime soon, if at all. Mainly because the use case it covers is really limited, this metadata is only useful if you do not apply any filter expressions to your logs and only for doing a count.  As Cyril mentioned above you can't really effectively do a rate unless you open up the chunk and read the log lines because the step size in a rate count can vary and the rate of logs being written can vary within the chunk.

There really isn't much to gain here for such a narrow use case, instead a much more performant solution would be doing this at the agent on ingestion as I suggested above with promtail counters.

**Comment by arun11299** [comment]
@slim-bean Thats really cool and yeah makes more sense to store the counts as metric. Looking at the link you posted, I do not understand how to provide the values which could be in the orders of tens and hundreds at may but yet pre-defined ? for eg: the event name. Ideally I would like this to be part of prometheus label.
