### ISSUE TITLE
Error in the communication of the loki network

### ISSUE THREAD

**Issue by AUThomasCH** [grafana/loki#1513]
I have a communication problem between loki, grafana and promtail. For better understanding I have attached a pastebin of the output after the command "docker-compose up".
[Pastebin](https://pastebin.com/hsqKwTJf)

The error from the pastebin:
error="Post http://loki:3100/loki/api/v1/push: dial tcp: lookup loki on 127.0.0.11:53: read udp 127.0.0.1:43454->127.0.0.11:53: read: connection refused"

Somehow the communication within the network does not work.

The system is running the UFW Firewall and ports 9090 and 3100 are not open. Only port 3000 for Grafana is open.

Is the error in the firewall setting? The query of Grafana runs via localhost, or do I not understand it correctly?

The system runs on the GCP under Debian 10.

Thanks for your help.

**Comment by AUThomasCH** [comment]
It was indeed UFW.

**Comment by AlbertSu123** [comment]
Did you figure this out?
