### ISSUE TITLE
Notification templates can't be modified

### ISSUE THREAD

**Issue by bLd75** [grafana/loki#15196]
**Describe the bug**
On Grafana OSS v11.3.0, it is not possible to modify a notification template, it blocks saving of changes with error message `Another template with this name already exists`.
It seems Grafana incorrectly interprets a template modification as a creation.

**To Reproduce**
1. Create a notification template and save it
2. Modify the notification template
3. Save

**Expected behavior**
Allow modification of existing notification templates

**Environment:**
 - Infrastructure:  Kubernetes
 - Deployment tool: argocd
 - Version: Grafana OSS v11.3.0

**Screenshots, Promtail config, or terminal output**
![Image](https://github.com/user-attachments/assets/054bc440-22d4-4c5f-8e17-a133a8dc7844)
![Image](https://github.com/user-attachments/assets/c4f11eab-5067-485c-bed5-bc17ba0617ed)

**Comment by JStickler** [comment]
@bLd75 I think you need to create this issue against the [Grafana repo](https://github.com/grafana/grafana).  This functionality is not part of the Loki code.

**Comment by bLd75** [comment]
So sorry for the mistake, closing the issue
