### ISSUE TITLE
How to Safely Transition from Single-Tenant to Multi-Tenant in Loki without Impacting Existing Services?

### ISSUE THREAD

**Issue by soonyubi** [grafana/loki#15193]
We are operating a service where we use Grafana, Loki, and OpenTelemetry to collect and visualize logs. In our current production environment, we are using single-tenant mode with auth_enabled: false.

Now, we are planning to switch to multi-tenant mode by enabling auth_enabled: true. However, we are concerned about potential issues that may arise from this change.

For example, when switching to multi-tenancy, will existing data still be accessible in Grafana, or will we need to update all data sources with the appropriate header values (like X-Scope-OrgID)?

What are the best practices to safely transition from single-tenant to multi-tenant mode in Loki, ensuring that our monitoring services remain unaffected during the deployment process?

We would greatly appreciate any advice or recommendations based on similar experiences.

**Comment by JStickler** [comment]
Questions have a better chance of being answered if you ask them on the [community forums](https://community.grafana.com/c/grafana-loki/41).

**Comment by soonyubi** [comment]
thank you

**Comment by JStickler** [comment]
Link for others who have the same question
https://community.grafana.com/t/how-to-safely-transition-from-single-tenant-to-multi-tenant-in-loki-without-impacting-existing-services/138151
