### ISSUE TITLE
ARM version of loki plugin not working anymore

### ISSUE THREAD

**Issue by francescor** [grafana/loki#15318]
**Describe the bug**

We've been using the ARM version of the Docker loki plugin, but it does not work anymore

**To Reproduce**

1. setup brand new ARM  "Ubuntu 22.04.5 LTS" with latest docker
2. execute `sudo docker plugin install grafana/loki-docker-driver:latest      --alias loki --grant-all-permissions` and I get 

```
$ sudo docker plugin install grafana/loki-docker-driver:latest      --alias loki --grant-all-permissions
latest: Pulling from grafana/loki-docker-driver
Digest: sha256:82270b494d8c157f035fde65bc0159076f4c4361b5bb061b4fc817e8db04234a
32dbe5a742d5: Complete 
Error response from daemon: dial unix /run/docker/plugins/f50ab7f3a49b2f1d4c629e8690d1ca5af5cc96522720530f6c2643a319ee5a0b/loki.sock: connect: no such file or directory
$ docker plugin ls 
ID             NAME          DESCRIPTION           ENABLED
f50ab7f3a49b   loki:latest   Loki Logging Driver   false
```

while if I use dev image created by @tucksaun as in https://github.com/grafana/loki/pull/9247#issuecomment-2520904954 
it works

```
$ docker plugin install tucksaun/loki-docker-driver:main-arm64 --alias loki --grant-all-permissions
main-arm64: Pulling from tucksaun/loki-docker-driver
Digest: sha256:43b6c0d6449bbeacd21e0564ed04a7ef4babb3adcf63c008363096acada5cccf
b959e15d6c4b: Complete 
Installed plugin tucksaun/loki-docker-driver:main-arm64
$ docker plugin ls
ID             NAME          DESCRIPTION           ENABLED
ae02e6d68fe1   loki:latest   Loki Logging Driver   true
```

**Expected behavior**

We use cloud-init to create our docker swarm nodes, so nothing changed on our side: 
so we would expect the above docker plugin install command would work

**Environment:**
 - Infrastructure: Docker swarm
 - Swarm nodes with  "Ubuntu 22.04.5 LTS"
- Docker version 27.4.0, build bde2b89

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by trevorwhitney** [comment]
This was fixed in https://github.com/grafana/loki/pull/9247, which did not make it into our release branch for 3.3.x. I've backported it in, so hopefully this is fixed with the 3.3.2 patch.

**Comment by francescor** [comment]
thanks @trevorwhitney 

we'll wait for that release: check manually, then put into production, and return our feed here

**Comment by trevorwhitney** [comment]
So, fixing this for `arm` is going to be a lot more involved. After further investigation, while #9247 fixes publishing, the driver build still depends on our build image, which is only being build for `amd` and `arm64` as we have a dependency on `trivy` which does not appear to build an `arm` image.

An `arm` build would require a different version of the build image, or a different `Dockerfile` to build from. This has likely been broken for `arm` at least as long as we've had `trivy` in our build process, if not longer.

**Comment by francescor** [comment]
sorry to hear it's not that easy :(

@trevorwhitney  difficulties are not clear to me, but it's my lack of knownledge on this.  

What I can tell you is that I did not even know the difference between arm and arm64: now I realize the title of this issues is not correct, since our need, indeed, is for the `arm64` image of the loki docker plugin (not the `arm`).

Our context is Docker Swarm (several) running in AWS Ec2.  We are migrating our Swarm nodes from 

```
node.platform.arch == x86_64
```
to 

```
node.platform.arch == aarch64
```

We are almost there: with great benefits in terms of cpu efficency even if we moved there with the aim to have a lower AWS bill.

All our  docker nodes need (and badly), loki :)  

We cannot imagine working without it.

**Comment by trevorwhitney** [comment]
ok, the `arm64` build is in progress of being fixed

**Comment by trevorwhitney** [comment]
@francescor what's the last working version of the plugin for you? I've never used it, and I can't get it to work on my machine, which I suspect is either a) we've never successfully built an arm64 version, or b) because I'm using orbstack on mac. I may need you to test out some release candidates for me unless I can find a way to run it myself.

**Comment by francescor** [comment]
@trevorwhitney I've pulled a working image https://github.com/grafana/loki/pull/9247#issuecomment-2479706423 with grafana/loki-docker-driver:latest on the 15th of November 2024

Yes, I am available for testing a release candidate, thank you

**Comment by trevorwhitney** [comment]
@francescor ok, I think I got it to work locally with trevorwhitney075/loki-docker-driver:1.14.2-arm64, you want to give it a second check? In the meantime I'm going to work on getting this plugged back into the Loki release and hopefully we can publish the driver again with the next patch release.

**Comment by francescor** [comment]
Yes, it works

```
dante@boat-worker-arm-5258:~$ docker plugin ls 
ID        NAME      DESCRIPTION   ENABLED

dante@boat-worker-arm-5258:~$ docker plugin install trevorwhitney075/loki-docker-driver:1.14.2-arm64 --alias loki --grant-all-permissions
1.14.2-arm64: Pulling from trevorwhitney075/loki-docker-driver
Digest: sha256:9482d7dab13cd1d9a5f7ab43c2588da99fd76ea0b53b6b86fd303397523889dd
b90c9bfb42c1: Complete 
Installed plugin trevorwhitney075/loki-docker-driver:1.14.2-arm64

dante@boat-worker-arm-5258:~$ docker plugin ls 
ID             NAME          DESCRIPTION           ENABLED
669d563ad756   loki:latest   Loki Logging Driver   true

dante@boat-worker-arm-5258:~$ docker plugin inspect loki:latest 
[
    {
        "Config": {
            "Args": {
                "Description": "",
                "Name": "",
                "Settable": null,
                "Value": null
            },
            "Description": "Loki Logging Driver",
            "DockerVersion": "26.1.3",
            "Documentation": "https://github.com/grafana/loki",
            "Entrypoint": [
                "/bin/docker-driver"
            ],
            "Env": [
                {
                    "Description": "Set log level to output for plugin logs",
                    "Name": "LOG_LEVEL",
                    "Settable": [
                        "value"
                    ],
                    "Value": "info"
                },
                {
                    "Description": "Activate pprof debugging endpoint for the given port.",
                    "Name": "PPROF_PORT",
                    "Settable": [
                        "value"
                    ],
                    "Value": ""
                }
            ],
            "Interface": {
                "Socket": "loki.sock",
                "Types": [
                    "docker.logdriver/1.0"
                ]
            },
            "IpcHost": false,
            "Linux": {
                "AllowAllDevices": false,
                "Capabilities": null,
                "Devices": null
            },
            "Mounts": null,
            "Network": {
                "Type": "host"
            },
            "PidHost": false,
            "PropagatedMount": "",
            "User": {},
            "WorkDir": "",
            "rootfs": {
                "diff_ids": [
                    "sha256:b90c9bfb42c1bc023807599f743bf1e7da3f62db85de5fb2ba8a781f14d55128"
                ],
                "type": "layers"
            }
        },
        "Enabled": true,
        "Id": "669d563ad75681f13eb0006c4f743fa4deac5f8b71aa5b58655eeb2940e747cf",
        "Name": "loki:latest",
        "PluginReference": "docker.io/trevorwhitney075/loki-docker-driver:1.14.2-arm64",
        "Settings": {
            "Args": [],
            "Devices": [],
            "Env": [
                "LOG_LEVEL=info",
                "PPROF_PORT="
            ],
            "Mounts": []
        }
    }
]
dante@boat-worker-arm-5258:~$ uname -a
Linux boat-worker-arm-5258 6.8.0-1021-aws #23~22.04.1-Ubuntu SMP Tue Dec 10 16:31:58 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
dante@boat-worker-arm-5258:~$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
dante@boat-worker-arm-5258:~$ docker --version
Docker version 27.4.0, build bde2b89
```

**Comment by trevorwhitney** [comment]
Plugin is fixed as of version `3.3.2`.

It is available at `grafana/loki-docker-driver:3.3.2-arm64` and `grafana/loki-docker-driver:3.3.2-amd64`

**Comment by francescor** [comment]
@trevorwhitney I may did not get this one:

> Going forward plugin version will follow Loki version, and be released alongside each Loki release.

**Comment by tucksaun** [comment]
AFAICT `latest` has not been updated for years, so you need to use a more up-to-date tag.
Also, Docker plugins do not support multi-arch images, so one needs to use the `-arm64` variant of the tag.

**Comment by trevorwhitney** [comment]
correct, use a more recent numbered version, do not use `latest`, and use the correct architecture.
