### ISSUE TITLE
Make the Loki Docker driver work with Amazon ECS

### ISSUE THREAD

**Issue by fitzoh** [grafana/loki#1532]
**Is your feature request related to a problem? Please describe.**
I want to use the Loki Docker driver to get my logs from [Amazon ECS](https://aws.amazon.com/ecs/) into Loki, but there isn't an easy way to do so.

**Describe the solution you'd like**
The Loki Docker driver is easily usable with Amazon ECS.

**Describe alternatives you've considered**
The solution suggested by Amazon in the [LogConfiguration documentation](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_LogConfiguration.html) is to fork the ECS agent and run a custom build.  You can also work around it by setting the Loki driver as the default Docker logging driver ([docs](https://docs.docker.com/config/containers/logging/configure/)) on your EC2 instance, then providing no logging configuration in your ECS task.

**Additional context**
This isn't really a problem that can be fixed within Loki, but this issue provides a reference point for people who are interested in using Loki with ECS or attempting to find more information.

It may make sense for a Loki maintainer to open a PR to add support to the [ECS agent](https://github.com/aws/amazon-ecs-agent).

This issue would also be resolved by the completion of https://github.com/aws/containers-roadmap/issues/435, which allows the usage of arbitrary custom log drivers with ECS.

The documentation added in #1531 should also be updated once a better solution is available.

**Comment by slim-bean** [comment]
@cyriltovena looked into this but it requires many steps including many upstream changes on the Amazon side, we started making some PR's for this but it's difficulty and feels unlikely to succeed.

Instead there is another approach with FireLens which would cover this case and also Fargate, please check [here](https://github.com/grafana/loki/blob/master/docs/clients/aws/ecs/ecs.md) for info on this approach.
