### ISSUE TITLE
Unable to install promtail using helm. 

### ISSUE THREAD

**Issue by ksriteja95** [grafana/loki#1535]
Promtail is unable to install using helm charts.    I am getting the error below in logs of all pods. 

 `Not ready: Unable to find any logs to tail. Please verify permissions, volumes, scrape_config, etc.\\n\" ws: false; Accept-Encoding: gzip; Connection: close; User-Agent: kube-probe/1.12+`

I was trying to install it on rancher kubernetes. its creating the pod but not initializing it. 
<img width="576" alt="Capture" src="https://user-images.githubusercontent.com/46532977/72556754-23f6b300-3854-11ea-9ece-a2e1490931c5.PNG">

Getting a warning message on kubernetes dashboard like 
`Search Line limits were exceeded, some search paths have been omitted, the applied search line is:default.svc.cluster.local svc.cluster.local cluster.local rancher.internal 
Readiness probe failed: HTTP probe failed with statuscode: 500`

**Comment by slim-bean** [comment]
Can you look at the service discovery information from one of the promtail pods and see what it says:  https://github.com/grafana/loki/blob/master/docs/getting-started/troubleshooting.md#troubleshooting-targets

How many nodes are in your cluster?

**Comment by ksriteja95** [comment]
I do have around 25 nodes.  After troubleshooting i get these results
<img width="307" alt="Capture" src="https://user-images.githubusercontent.com/46532977/72963681-b8897580-3d6c-11ea-8c48-4c81e89b4388.PNG">
<img width="827" alt="Capture1" src="https://user-images.githubusercontent.com/46532977/72963682-b8897580-3d6c-11ea-86d7-7637c3fc825b.PNG">
