### ISSUE TITLE
Optimize multiple simple regex "or" filters to use byte.contains

### ISSUE THREAD

**Issue by mattmendick** [grafana/loki#1542]
A common way to match multiple simple words in either label matching or log text is to use a regex filter, `|~ "first-term|second-term"` for example. This is expensive to compute as the regex engine can be slow.

Specifically for this case where the regex is a simple string contains another string, break the query into n queries where n is the number of terms provided, using the faster `byte.contains` method to match, then combine the results. This would be as if the user searched first on `|= "first-term"` and then on `|= "second-term"` and then manually combined the results, but automatically converted and computed when executing the original `|~ "first-term|second-term"`.

**Comment by rfratto** [comment]
@gouthamve had mentioned that the Prometheus code already does this for its label matchers. I took a quick look at the code but wasn't able to find anything other than some optimizations in the TSDB [querier](https://github.com/prometheus/prometheus/blob/4708915ac6ef3f1a8b7c348c6463c08f098a1e0a/tsdb/querier.go#L303). We should follow up with Goutham later to find out where this code is; we might be able to take it and use it ourselves.
