### ISSUE TITLE
Multidimensional, nested, labels array, max count of labels

### ISSUE THREAD

**Issue by koi8-r** [grafana/loki#1549]
Documentation says that the **loki** is a **multidimensional** label-based system. That this mean ?
1. Can I create big number of labels, for example set postgres primary id as a label ?
2. Can I set nested labels?
3. If I have a multiple validation errors for single log line, can i set label as array ?

Sory for may bad English =)

**Comment by pstibrany** [comment]
Loki's label model is based on Prometheus labels: https://prometheus.io/docs/concepts/data_model/

Labels are meant to be used as dimensions for log files (eg. server names, file name, cluster name, device ID), but not as a place to store more data.

1. you can, but it's not a good idea. Each unique combination of label names and values form a new series of log lines (= effective a log file). Using eg. primary ID as a label, will create a lot of short-lived series (log files), which will make index bigger. Loki has limits in place to avoid explosion of series like that.
2. No
3. Label names and values are always strings.

Hope that helps.

**Comment by koi8-r** [comment]
> Loki's label model is based on Prometheus labels: https://prometheus.io/docs/concepts/data_model/
> 
> Labels are meant to be used as dimensions for log files (eg. server names, file name, cluster name, device ID), but not as a place to store more data.
> 
> 1. you can, but it's not a good idea. Each unique combination of label names and values form a new series of log lines (= effective a log file). Using eg. primary ID as a label, will create a lot of short-lived series (log files), which will make index bigger. Loki has limits in place to avoid explosion of series like that.
> 2. No
> 3. Label names and values are always strings.
> 
> Hope that helps.

Thaks, you answer for all my questions
