### ISSUE TITLE
Partial result for query range.

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#1552]
**Is your feature request related to a problem? Please describe.**

Currently when doing query range search (using |= or |~) over long per period of time, the user might receive a 502 (Gateway timeout) or 500 (timeout). However the query has probably executed long enough to have meaningful result and could be followed up with a smaller queries to fetch remaining/missing information. Unfortunately right now we are wasting the full result and we return an API error.

**Describe the solution you'd like**

I would like Loki to return partial results instead of timing out. We could use the current API structure to return the partial result and send a 200 instead. The timeout should be configurable.

```
{
  "status": "error",
  "data":{
    "resultType": "streams",
    "resultMetadata": {
       "start": 1569266497240578000,
       "end": 1569266492548155000,
     },
    "result": [
      {
        "stream": {
          "filename": "/var/log/myproject.log",
          "job": "varlogs",
          "level": "info"
        },
        "values": [
          [
            "1569266497240578000",
            "foo"
          ],
          [
            "1569266492548155000",
            "bar"
          ]
        ]
      }
    ]
  },
  "errorType": "timeout",
  "error": "context cancelled",
}
```

The `resultMetadata` would contains enough informations for the user to send follow up queries to accomplish the full query.

Alternatively we could use the `warning` property.

I think this would really help by not wasting work done by Loki.

**Describe alternatives you've considered**
Increase timeout but that doesn't solve every requests.

related issue:
- https://github.com/grafana/loki/issues/1098
- https://github.com/grafana/loki/issues/1252

**Comment by owen-d** [comment]
As an alternative, we could also use a statistics api to signal this query has touched too many series/log lines.

**Comment by slim-bean** [comment]
@davkal and/or @aocenas I would like to re-surface this and see if what Cyril is proposing here makes sense for partial responses from Loki when the query times out.

The goal would be to allow returning any results obtained while querying before the timeout (or indicate no results) and provide Grafana with the timespan covered during the query, this would give the user the chance to re-submit the query where it left off.

WDYT?

**Comment by aocenas** [comment]
Could this be automated instead of user triggered? We already show partial responses in case of prometheus and cloud watch so we could implement sort of a retry (while moving the time range) to get the whole response while providing partial results to user and ability for the user to cancel the query.

This would not need any new UI as the user does not need to be aware that it's not a single request, similar to how they may not be aware of any retries implemented by the data source plugin at the moment.

**Comment by slim-bean** [comment]
For anyone who comes along this issue, there are also discussions around having a full streaming query endpoint in Loki, which will be tackled as a separate issue.  There still is a usecase however for amending the current API with this additional metadata as it's going to be an easier effort and still useful for anyone wanting a traditional synchronous API

**Comment by slim-bean** [comment]
Closing this for now, we will likely not extend the existing endpoint and instead address this as part of a streaming API
