### ISSUE TITLE
Promtail : Support entire extracted value map in template pipeline stage

### ISSUE THREAD

**Issue by robshep** [grafana/loki#1559]
**Is your feature request related to a problem? Please describe.**
I want to construct a new log message from previously extracted parts but cannot join elements together.  

**Describe the solution you'd like**
The template pipeline stage operator to have access to the whole scope
Here's a simplistic - *but maybe not 100% correct* - example)

    pipeline_stages:
        - json:
            expressions:
              msg: msg
              exception: exec_info
        - template:
               source: output_msg
               template: '{{ .msg }} with exception: {{ .exception }}'
        - output:
            source: output_msg

**Describe alternatives you've considered**
I've thrashed with the other pipeline operators, to no avail.

**Comment by robshep** [comment]
Or even support String Templates in the `output` stage for the same effect.

**Comment by adityacs** [comment]
@robshep Allowing all extracted values in a single template stage would not be a good idea as templating is just to manipulate the current extracted values. It would be good to support templating/manipulating the log line in output stage.

@cyriltovena @slim-bean What's your thoughts on this?

**Comment by cyriltovena** [comment]
I think it's a fair request we can support at least in template multiple keys.

For the output I don't think we can unless we do a breaking change so I'm less interested by this idea.

All in for more function and properties in template, it can be used for labels as well as entries.

**Comment by adityacs** [comment]
@cyriltovena If we support multiple keys in template, what would be the new key to the templated values? With the current logic, we reassign the templated value to the same extracted key. In the case of having multiple template keys, we should create new extracted key. We should add a field to existing template `TemplateConfig` fields to label the new templated value.

Is it ok to have above changes to `template`?

**Comment by cyriltovena** [comment]
Sorry I think this wasn't clear.

I think we can support this: 

```
    - template:
           source: output_msg
           template: '{{ .msg }} with exception: {{ .exception }}'
```

without breaking the current API or change the current template stage config. Might not be easy but it seems like a nice to have.
