### ISSUE TITLE
Helm chart for loki-stack requires template "loki.serviceName"...it does not exist

### ISSUE THREAD

**Issue by dankirkpatrick** [grafana/loki#1566]
**Describe the bug**
When installing the helm chart for loki-stack, I get an error that reads:

```
Error: template: loki-stack/templates/tests/loki-test-pod.yaml:20:25: executing "loki-stack/templates/tests/loki-test-pod.yaml" at <{{template "loki.serviceName" .}}>: template "loki.serviceName" not defined
```

**To Reproduce**
1. Install the helm chart.  Type:

```
helm install loki -n monitor loki/loki-stack
```

**Expected behavior**
The helm chart should install instead of giving an error.

**Environment:**
 - On-premises K8S cluster, provisioned with Kubespray, running on vSphere
 - Deployment tool: helm v3

**Screenshots, Promtail config, or terminal output**
```
% helm install loki -n monitor loki/loki-stack -f charts/loki/values.yaml
Error: template: loki-stack/templates/tests/loki-test-pod.yaml:20:25: executing "loki-stack/templates/tests/loki-test-pod.yaml" at <{{template "loki.serviceName" .}}>: template "loki.serviceName" not defined
```

**Comment by cyriltovena** [comment]
Interesting it seems to work for me. Which commit are you using for the chart ? I tried from the repo and from master.

**Comment by shaikatz** [comment]
Looks like for some reason `loki.serviceName` is defined inside promtail helpers instead of loki helpers.
That produce @dankirkpatrick issue, probably he had disabled promtail.

**Comment by cyriltovena** [comment]
Right and the test is using that. Seems like a bug to fix.

**Comment by Tikam02** [comment]
### Loki-Stack Lint error - git actions failing

[ERROR] templates/: template: loki-stack/templates/tests/loki-test-pod.yaml:22:23: executing "loki-stack/templates/tests/loki-test-pod.yaml" at <.Values.loki.service.port>: nil pointer evaluating interface {}.port

##[error]Process completed with exit code 1.

**Comment by jaswanth99999** [comment]
This problem is still in chart v2.6.1. Is there any workaround to resolve this?
