### ISSUE TITLE
Request start and end inclusivity/exclusivity

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#1570]
**Describe the bug**
It seems that the start is not inclusive anymore from this discussion https://github.com/grafana/loki/issues/597#issuecomment-577768610

We should have the start inclusive and end exclusive for log query requests and also add this as part of the API documentation. The precision should be nanoseconds.

**To Reproduce**
see discussion

**Expected behavior**
 the start inclusive and end exclusive, at least that how it was before.

/cc @aocenas can you add commit information where you found this please.

**Comment by aocenas** [comment]
Hey @cyriltovena sorry my bad, I thought I was some newer master but seems like I did not pull for quite some time, now testing it on 1.3.0 and seems like this works as expected. Going to close this now, will test on master and reopen if I see this again.

**Comment by cyriltovena** [comment]
Out of curiosity on which sha were you ?
