### ISSUE TITLE
Helm chart service.yaml template missing a port

### ISSUE THREAD

**Issue by mrothroc** [grafana/loki#1571]
**Describe the bug**
When you deploy via the helm chart, the headless service only has one port exposed: http-metrics.  However, internally the service also relies on port 9095 for grpc.  This creates an issue with Istio.  The Istio sidecar discovers ports via the service entry.  Without this port being listed (and with a name prefixed with grpc), Loki starts but logs errors and is non responsive.

This error is seen in the logs after injecting the Istio sidecar:
"POST /api/prom/push (500) 283.514µs Response: \"rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: write tcp 10.44.0.63:35254->10.44.0.63:9095: write: broken pipe\\n\"

**To Reproduce**
1. Enable automatic sidecar injection in the namespace with Loki
2. Restart Loki to inject the sidecar
3. Watch the Loki logs.
In about a minute, you will see repeated error messages.

**Expected behavior**
It should work with the sidecar injected.

**Environment:**
GKE with managed istio

**Workaround:**
Manually edit the stateful set to add this to the ports in the container spec:
        - containerPort: 9095
          name: grpc-submit
          protocol: TCP

Manually edit the headless service to add this to the ports:
  - name: grpc-submit
    port: 9095
    protocol: TCP
    targetPort: grpc-submit

**Comment by adityacs** [comment]
@mrothroc This is already supported. FYR https://github.com/grafana/loki/blob/master/production/helm/loki/templates/service-headless.yaml#L18

https://github.com/grafana/loki/blob/master/production/helm/loki/values.yaml#L232

**Comment by shantanu-dahiya** [comment]
@adityacs your links are no longer working. Can you share updated links?
