### ISSUE TITLE
Code coverage in PR

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#1574]
**Is your feature request related to a problem? Please describe.**
Would be nice to have code coverage comparison during github PR.

Currently it's hard to see what is covered by tests without pulling the PR and executing tests.

**Describe the solution you'd like**
There is a log of SaaS product or even open source cli we could use.

For instance https://codecov.io/ seems free for open source project.

**Describe alternatives you've considered**
No code coverage as we live like this until now.

/cc @mattmendick I think you could maybe take a look at this ? May be compare what is out there or even start to try some of them.

**Comment by owen-d** [comment]
closing this as we now have this added. Reopen if insufficient @cyriltovena :)
