### ISSUE TITLE
Series API return total bytes for each stream within the range

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#1584]
**Is your feature request related to a problem? Please describe.**

It could be really useful for the frontend to be able to send a first query using the series API and retrieve the amount of data it will target beforehand. This could allow to increase the parallelism based on the total size to process of course still bound by a per tenant Limit. As of today we recommend to use snappy so we know we can decompress ~450MB/sec, this means for a dataset of 1GB we don't need more than 2 worker, more will probably be a waste of resources.

We  need to actually store in the chunk the total size before compression see https://github.com/grafana/loki/issues/1507.
However I want to point out that currently we still need to download every chunks before replying
https://github.com/grafana/loki/blob/master/pkg/querier/querier.go#L497. We might want to revisit that and may be have a new schema or avoid to download chunks (streaming).  We should also start thinking about result caching.

**Describe the solution you'd like**
I would like to include in the Series API, the total size of data (before compression), and may be more information that could be useful about a stream.

**Describe alternatives you've considered**
Directly communicate with the store API from the frontend ?

**Comment by slim-bean** [comment]
@cyriltovena I don't think we want this closed yet do we?

**Comment by cyriltovena** [comment]
I'd like to keep this as a goal.
