### ISSUE TITLE
Improve stream proto format

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#1588]
**Is your feature request related to a problem? Please describe.**
Currently we have:

```
message Stream {
  string labels = 1 [(gogoproto.jsontag) = "labels"];
  repeated Entry entries = 2 [(gogoproto.nullable) = false, (gogoproto.jsontag) = "entries"];
}
```

This causes a lot of transformation between string and labels object. 

**Describe the solution you'd like**
I think we used to have this proto exposed, but it is not the case anymore and we should make that proto more easier to work with by having labels a repeated object.

**Comment by cyriltovena** [comment]
We should use this type:

https://github.com/cortexproject/cortex/blob/master/pkg/ingester/client/timeseries.go#L69

Like cortex does here:

https://github.com/cortexproject/cortex/blob/master/pkg/querier/queryrange/queryrange.proto#L43

**Comment by evalsocket** [comment]
@CyrilPeponnet Would like to work on this. Can this be assigned to me.

**Comment by CyrilPeponnet** [comment]
Wrong Cyril :) not the first time though :)

**Comment by cyriltovena** [comment]
Sure not an easy one but we’ll guide you during review

**Comment by cyriltovena** [comment]
This seems more complicated than I thought, we will need to keep backward compatibility. If we don't then rolling out a new version will be difficult as ingester won't allow old distributors message.

We should may be introduce a new field instead:

```proto
message Stream {
  string labels = 1 [(gogoproto.jsontag) = "labels"];
  repeated Entry entries = 2 [(gogoproto.nullable) = false, (gogoproto.jsontag) = "entries"];
  repeated cortex.LabelPair label = 3 [(gogoproto.nullable) = false, (gogoproto.jsontag) = "metric", (gogoproto.customtype) = "github.com/cortexproject/cortex/pkg/ingester/client.LabelAdapter"];
```

Then refactor the code to use `labels` as fallback.

We should also be careful to keep the same label order along the way as this will be a big refactoring touching most of the component.

**Comment by cyriltovena** [comment]
Also I just realized the `Stream` proto is used by our push API. So this would be a big API break.

**Comment by nfoerster** [comment]
Yes it's used by the deprecated POST API `/api/prom/push`. However I can't find new protobuf structures for the new POST API `/loki/api/v1/push`.

**Comment by slim-bean** [comment]
Changing the push API at this point seems to have more cost than benefit, closing this.
