### ISSUE TITLE
Cannot calcurate in LogQL like PromQL. Error is "parse error at line 1, col 84: syntax error: unexpected IDENTIFIER"

### ISSUE THREAD

**Issue by mtamura2** [grafana/loki#1589]
**Describe the bug**
In Grafana Metrics, I try this Query 
`rate({logName="apache-access",httpStatus="200"}[1h]) - 1`
but, I Got Error "parse error at line 1, col 84: syntax error: unexpected IDENTIFIER"...
Cannot I calcurate in Query？

**To Reproduce**
loki, version v1.3.0
`rate({logName="apache-access",httpStatus="200"}[1h])` looks Fine. 

**Expected behavior**
PromQL can calcurate. 
`rate(process_max_fds[1m])-1`
I hope this in LogQL.
Finally, I will get Monthly Uptime Percentage from access_log.
`sum({logName="apache-access",httpStatus="200"}[1h])  / sum({logName="apache-access"}[1h])`

Thank you.

**Comment by cyriltovena** [comment]
We don’t yet support binary operations, but that’s on the todo list

**Comment by owen-d** [comment]
This should come very soon:
https://github.com/grafana/loki/pull/1662 will add binary operators and I have another PR ready afterwards to add numeric literals. Then your query should work :)
