### ISSUE TITLE
Promtail not sending logs

### ISSUE THREAD

**Issue by ksriteja95** [grafana/loki#1592]
I am getting error below and promtail pods are not running. Install loki using helm 
> msg="GET /ready (500) 41.427µs Response: \"Not ready: Unable to find any logs to tail. Please verify permissions, volumes, scrape_config, etc.\\n\" ws: false; Accept-Encoding: gzip; Connection: close; User-Agent: kube-probe/1.12+;

<img width="545" alt="Capture" src="https://user-images.githubusercontent.com/46532977/73287052-78335880-41ad-11ea-8f5c-5e584297adf8.PNG">

**Comment by ksriteja95** [comment]
After troubleshooting i get these results
<img width="307" alt="72963681-b8897580-3d6c-11ea-8c48-4c81e89b4388" src="https://user-images.githubusercontent.com/46532977/73287390-0b6c8e00-41ae-11ea-9533-f79f517fa512.png">
<img width="827" alt="72963682-b8897580-3d6c-11ea-86d7-7637c3fc825b" src="https://user-images.githubusercontent.com/46532977/73287391-0b6c8e00-41ae-11ea-9990-62d3c43197cc.png">

**Comment by imranrazakhan** [comment]
@ksriteja95  Are you able to resolve this issue?

**Comment by yudar1024** [comment]
same issue.
