### ISSUE TITLE
Docs: Promtail Docker config example seem out of date with the docs

### ISSUE THREAD

**Issue by aocenas** [grafana/loki#1593]
**Describe the bug**
In docs [example section]( https://github.com/grafana/loki/blob/master/docs/clients/promtail/configuration.md#example-docker-config) there are parts:
```
pipeline_stages:
   - docker:
```
but `docker` does not seem to be a valid option for the `pipeline_stages`. I would expect `kubernetes_sd_config` there.

**To Reproduce**

**Expected behavior**

**Environment:**

**Screenshots, Promtail config, or terminal output**

**Comment by slim-bean** [comment]
hey @aocenas I agree that example is confusing and misleading.  The config is technically valid if you had docker writing logs into `/var/log` but this is very OS dependent and we really recommend the docker logging driver instead.

`docker` is a valid pipeline_stage but was not documented which is also not very helpful.

I opened #1602 to hopefully address the problems you encountered.
