### ISSUE TITLE
Installation documentation flow missing steps

### ISSUE THREAD

**Issue by avarsava** [grafana/loki#1594]
Scenario: I am setting up Loki for the first time. I am working top to bottom through the installation documentation.
I want to install locally, so the first page I read is 2.iii, 'Installing locally'. I complete the instructions under 'Release binaries', which leads me to the instructions on the release page, which only instruct on how to extract and make executable the release.
I then move on to the next relevant page, 3.i 'Grafana'. This page assumes I have loki completely set up and ready to serve data, when at this point in the process I do not have loki configured or running, nor is promtail installed.

Suggested solution; re-order documentation or add pages in between 2.iii and 3.i for completing setup process.

**Comment by rfratto** [comment]
Reopening and marking as keepalive, I think this is important and should be fixed.

**Comment by slim-bean** [comment]
Documentation is always a continuing effort and this is excellent feedback. I'm closing this issue for now as we are focusing on pruning our open issues list to be a small set of actively actively worked/discussed issues.  That doesn't mean we won't take this into consideration while improving our documentation.
