### ISSUE TITLE
Add config reload endoint / signal to promtail

### ISSUE THREAD

**Issue by tomwilkie** [grafana/loki#16]
So we don't have to restart all the pods just to change the scrape config etc.

**Comment by daixiang0** [comment]
@tomwilkie hi! there is a [issue](https://github.com/kubernetes/kubernetes/issues/22368) about this, some recommend [reloader](https://github.com/stakater/reloader).
If not use reloader, i think add second pod in promtail to watch config hash in liveness is a way that do not introduce more dependence. WDYT?

**Comment by hairyhenderson** [comment]
Seems like there's a PR for this pending - would be nice to see this happen instead of the issue going stale and disappearing 😉

**Comment by cyriltovena** [comment]
@hairyhenderson how this would be useful for you ? Can you give us more informations ?

**Comment by hairyhenderson** [comment]
@cyriltovena like the description says, it's annoying to restart processes to reload configs. I'm used to being able to send a signal or call a reload endpoint in Prometheus, and this is one area where Loki _isn't_ "Like Prometheus, but for logs" 😉

**Comment by cyriltovena** [comment]
yeah but Prometheus could miss some scrape and it make sense to not restart to avoid this kind of behaviour, promtail though won't miss anything as everything is on disk.

**Comment by hairyhenderson** [comment]
Sure... But there are side-effects of processes terminating which may be undesirable. And, it's conventional for processes in UNIX to listen to a SIGHUP and reload config based on that.

I suppose my question is: why would you _not_ want this feature?

**Comment by pastatopf** [comment]
Upvote fromy my side :-)

**Comment by Perry-The-Cynic** [comment]
It's no longer true that (from promtail's perspective) "everything is on disk." The syslog endpoint has data pushed onto promtail, and depending on the retry policy of the sender restarting promtail may drop some messages.

**Comment by cyriltovena** [comment]
> It's no longer true that (from promtail's perspective) "everything is on disk." The syslog endpoint has data pushed onto promtail, and depending on the retry policy of the sender restarting promtail may drop some messages.

Very good point. Although that seems easier to fix than implementing a reload.

**Comment by timurkhisamov** [comment]
Upvote

**Comment by tomasfreund** [comment]
Hi, this is a big issue for us. We provision client certificates for promtail with ACME dns-01 challenge and promtail does not seem to reload the certificates at all. We need promtail to either reload certificates or to have a config reload endpoint so that we can reuse existing tooling from Prometheus.

**Comment by marcusne** [comment]
Hi, same here /reload would be really helpful to maintain promtail in K8s or at least support e.g. SIGHUP

**Comment by liguozhong** [comment]
reload is a very dangerous feature, it is easy to make promtail panic, we can refer to the failure history of another log agent

● https://github.com/vectordotdev/vector/issues/10485
● https://github.com/vectordotdev/vector/issues/10412
● https://github.com/vectordotdev/vector/issues/13228
