### ISSUE TITLE
Loki returns an entire table on query with negative limit value.

### ISSUE THREAD

**Issue by Estrax** [grafana/loki#1604]
**Describe the bug**
When querying Loki with a query parameter `limit: -1` (or any other negative value), Loki returns an entire table. When doing it from Grafana, it crashes a browser thread when the returned object is too big (because parsing takes too long or we exceed a memory limit).

**Expected behavior**
With negative limit parameter Loki returns no elements.

**Comment by adityacs** [comment]
@cyriltovena This is already fixed here #1470 
@Estrax Which version of loki you are using?
Example
```
curl 'http://localhost:3100/loki/api/v1/query_range?direction=BACKWARD&end=1581911056457208000&limit=-1&query=%7Bfilename%3D%22%2Fvar%2Flog%2Fsystem.log%22%7D&start=1581695056457208000'
rpc error: code = Code(400) desc = limit must be a positive value
```

**Comment by Estrax** [comment]
@adityacs always the current master :) this particular thing was noticed in 1.3.0. We already took care of that on a Grafana side, I just pointed it out that it might be worth checking on a Loki side again.

**Comment by adityacs** [comment]
@Estrax Sorry for delayed reply. I tested this on `6.6.0` Grafana. It returns the expected error

<img width="900" alt="Screenshot 2020-03-09 at 4 14 19 PM" src="https://user-images.githubusercontent.com/7681197/76205920-286e9500-6221-11ea-80e2-178e762d9b82.png">
