### ISSUE TITLE
Add Redis defaultDatabase support

### ISSUE THREAD

**Issue by sergeyshaykhullin** [grafana/loki#1618]
**Is your feature request related to a problem? Please describe.**
Trying to use non-default redis database with `redis-master.redis:6379,defaultDatabase=14` endpoint, getting `msg="failed to put to redis" name=store.index-cache-read.redis err="dial tcp: address tcp/6379,defaultDatabase=14: unknown port`

**Describe the solution you'd like**
Add more cache-config options or connection string parsing

**Describe alternatives you've considered**
🔝 

**Additional context**
Loki is working anyway, but not using cache and spamming with errors. Using default database (db0) works fine

**Comment by kong62** [comment]
I am same issue

```
# kubectl logs -f -n grafana ingester-loki-4 --tail=100
level=error ts=2020-11-30T10:54:24.752039646Z caller=redis_cache.go:57 msg="failed to put to redis" name=store.index-cache-write.redis err="EXECABORT Transaction discarded because of previous errors."
level=error ts=2020-11-30T10:54:24.752183644Z caller=redis_cache.go:37 msg="failed to get from redis" name=chunksredis err="MOVED 3270 10.41.178.48:6379"
```

```
      redis:
        endpoint: redis-redis-cluster:6379
        # Redis Sentinel master name. An empty string for Redis Server or Redis Cluster.
        #master_name: master
        timeout: 10s
        expiration: 1h
        db: 0
        pool_size: 0
        password: root@1234
        #enable_tls: false
        idle_timeout: 0s
        max_connection_age: 0s
```
