### ISSUE TITLE
Provide configs for mixin queries

### ISSUE THREAD

**Issue by shaikatz** [grafana/loki#1622]
**Is your feature request related to a problem? Please describe.**
My setup has a different label then the hardcoded `cluster` to distinguish between clusters.
Currently, I cannot override it since it's hardcoded inside the dashboard queries.

**Describe the solution you'd like**
I would like to create `config.libsonnet` in `loki-mixin`.
This file will hold for example the `clusterLabel` configuration.
I will then use this configure in all the files to replace the hardcoded `cluster=` with config reference. 

**Additional context**
You can see the following [commit](https://github.com/shaikatz/loki/commit/327ba04e1e4a1889d0281e1678e067c2e24a8d41) to understand my proposal.

Waiting for a green light in order to do this change for all the dashboards and open a PR.

**Comment by cyriltovena** [comment]
I did something similar for cortex.

https://github.com/grafana/cortex-jsonnet/blob/master/cortex-mixin/alerts.libsonnet#L16

So yeah you can go ahead but make sure we can have a default that doesn't impact anyone. In this example if the setting is empty, it doesn't add any matcher.

**Comment by cyriltovena** [comment]
And Sorry for the delay.
