### ISSUE TITLE
Add Grafana datasource even if Grafana is not installed

### ISSUE THREAD

**Issue by fredgate** [grafana/loki#1624]
**Describe the bug**
The umbrella helm chart `loki-stack` allow to install desired charts using flags : Loki, Promtail, Fluentbit, Grafana, Prometheus.
When Prometheus and Grafana are installed in another way (for example using `prometheus-operator`), it should be useful to be able to install the file that declares Loki as a datasource in Grafana.
But actually it is not possible as the ConfigMap containing this file is installed only if Grafana is enabled, i.e. only if Grafana is installed by this chart.
The condition is in file https://github.com/grafana/loki/blob/master/production/helm/loki-stack/templates/datasources.yaml#L1
```
{{- if and .Values.grafana.enabled .Values.grafana.sidecar.datasources.enabled }}
````

**To Reproduce**
Install Loki stack with default values :
```
helm upgrade --install loki loki/loki-stack
```

**Expected behavior**
The ConfigMap with Loki datasource for Grafana should be installed.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Helm

**Comment by owen-d** [comment]
Hey, thanks for the details; this is a great candidate for a PR. Would you be interested in contributing this change?

**Comment by fredgate** [comment]
Sure I can contribute to this.
So the datasources for Grafana should be installed if the sidecar is enabled, even if Grafana is not enabled.

It will introduce a small breaking change as by default Grafana is disabled, and sidecar is enabled.
https://github.com/grafana/loki/blob/50c216a7b4f31ffe559fb2e843ada21af6866ee3/production/helm/loki-stack/values.yaml#L10-L14
With default configuration, actually the datasources are not installed, but after the changes they will be. Are you agree with that ?

**Comment by owen-d** [comment]
I think that's reasonable.

**Comment by fredgate** [comment]
So how to upgrade the chart version. Currently it is `0.31.1`. Should we set `0.32.0`, `0.31.2` (or even `1.0.0`) ?

**Comment by cyriltovena** [comment]
0.32.0 is fine
