### ISSUE TITLE
Request: promtail client binary for AIX (7.2)

### ISSUE THREAD

**Issue by Mikesch-mp** [grafana/loki#1635]
**Is your feature request related to a problem? Please describe.**
We have a lot aof AIX lpars, with mayn applications that write their own logfiles which cant use the central syslog. As iam not familar with go enough, i dont get it compiled for AIX. i tried it with
'''
GOOS=aix GOARCH=ppc64 go build ./cmd/promtail 
'''
but it doesnt build for me.

**Describe the solution you'd like**
Go should be able to compile the binary also for AIX, please provide it.

**Comment by Mikesch-mp** [comment]
#bump

**Comment by Mikesch-mp** [comment]
#bump

**Comment by kidharbachan** [comment]
We need this as well

**Comment by wlargou** [comment]
Anyone found the solution to build it ?

**Comment by szydell** [comment]
bump

**Comment by troyskigit** [comment]
Having installed promtail on linux, I too would like to find an AIX version  or details of how to compile for AIX.

**Comment by FlanniganColum** [comment]
This would also be a necessary component for me also

**Comment by AlahmadiQ8** [comment]
We Bumping since we also have AIX servers that we would like to install promtail on.

**Comment by j796160836** [comment]
bump
