### ISSUE TITLE
How to get the top N row of return data?

### ISSUE THREAD

**Issue by crossdbpro** [grafana/loki#1655]
I have a health check system regularly writing the result of checking. The data can be filtered in Loki easily, but I'm having trouble coming up with a command just to show the top one row of latest data.
Please advise.

**Comment by owen-d** [comment]
Please check out the LogQL [docs](https://github.com/grafana/loki/blob/master/docs/logql.md). If you know the labels that are creating the log lines, it may be something as simple as `{app="foo", env="bar"}`. You can also set the limit parameter if you're only interested in a few lines.

Users generally use grafana to visualize data from loki, but you may also use `logcli`, a CLI which is bundled in this project.

**Comment by jackeylhm** [comment]
Thanks for the reply, Owen

From the document provided, I could not find any way to limit to just one row of returned data , using the latest timestamp. My use case can be quite common, I just need to get the latest data (output) of filtered labels.
Is there command key words similar to top, limit,  or like shell script "| head -n 3"  , or | timestamp=max(ts)    ..and such?

Thanks in advance.

**Comment by cyriltovena** [comment]
You can use the logcli https://github.com/grafana/loki/blob/master/docs/getting-started/logcli.md it contains a way to limit and choose direction (backward recent first), loki support per query limit but Grafana currently set it once in the data source, I believe this will be added soon in grafana.
