### ISSUE TITLE
Trailing / in storage_config.s3 results in SignatureDoesNotMatch error

### ISSUE THREAD

**Issue by evgenii-petrov-arrival** [grafana/loki#1657]
**Describe the bug**
When storage_config.s3 is set to `s3://$region/$bucket/` instead of `s3://$region/$bucket` following error appears in the logs:

```
level=error ts=2020-02-07T14:53:30.994885382Z caller=flush.go:178 org_id=fake msg="failed to flush user" err="SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.\n\tstatus code: 403, request id: A6885D570623B3A6, host id: meiDS9Nm9yXWxHwpw8qg5KU3ZxIpEClgJN2aOekcTu6gNHQJdhn6eFQnPDwtKjuELWfBtJEWOTg="
```

**To Reproduce**
1. Start Loki v1.3.0 with storage_config.s3 set to `s3://$region/$bucket/` and ingester.chunk_idle_period to 1m to observe the failure quickly
2. Send some logs using `/api/prom/push`

**Expected behavior**
Trailing slash is detected and not used in object key generation, so no error occurs.

**Environment:**
 - Infrastructure: EKS
 - Deployment tool: kubernetes manifests generated from jsonnet once

**Comment by raypettersen** [comment]
Did you ever locate the problem?

**Comment by evgenii-petrov-arrival** [comment]
The problem is that object URI gets a double slash, like `s3://$region/$bucket//$object`, which results in the above error.

[This issue](https://github.com/aws/aws-sdk-js/issues/86) helped me figure this issue out.

**Comment by ognjen-it** [comment]
I have the same issue when I provided bad s3 credentials
