### ISSUE TITLE
Querier returns 400 for all type of errors.

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#1658]
Just discovered we return 400 in case of error in the LogQL engine.

I think we should have at least a way to separate limit and bad request types from internal errors which should translate in 500.

or may be create a function in logql `Error(err error) int ` that returns the status code for an error, default to 500

**Comment by owen-d** [comment]
After a little looking, I believe we should check the error type and 400 if it's a parse error (500 otherwise).

**Comment by cyriltovena** [comment]
Yes I think this would be a good first step. To avoid the httpgrpc.Errorf contamination we could use an exposed error we could check against in the querier.

**Comment by owen-d** [comment]
logql already uses a `ParseError` type, so it might be as easy as introducing a few type switches
