### ISSUE TITLE
How to set non-root path for loki 

### ISSUE THREAD

**Issue by cloudam** [grafana/loki#1668]
I installed loki using helm and configured ingress to to port 3100 and path /loki. Now when I access https://myURL/loki is giving 404. It seems loki is trying to basepath as / instead of /loki. 

is there a way where I can install loki with defining path (key for path)?

**Comment by cloudam** [comment]
http_path_prefix proeprty is missing in values.yaml

**Comment by cloudam** [comment]
Tried with solution in https://github.com/grafana/loki/issues/144. But its not working too. getting below error

helm upgrade --install loki loki/loki-stack --namespace=monitoring -server.path-prefix=/loki/
Error: unknown shorthand flag: 's' in -server.path-prefix=/sonar/loki/

**Comment by cyriltovena** [comment]
Helm doesn't understand loki flags. You have to use extraArgs and because it's a dictionary I don't think you can't use command line with helm (e.g. --set) .

You need to have your own custom helm value override:

```yaml
loki:
  extraArgs:
    server.path-prefix: /sonar/loki/
```

then you can do

```
helm upgrade --install loki loki/loki-stack --namespace=monitoring -f values.yaml
```

**Comment by cloudam** [comment]
> Helm doesn't understand loki flags. You have to use [`extraArgs`](https://github.com/grafana/loki/blob/f21e36bc843ed1d9603aa0790f7010756332e549/production/helm/loki/values.yaml#L95) and because it's a dictionary I don't think you can't use command line with helm (e.g. --set) .
> 
> You need to have your own custom helm value override:
> 
> ```yaml
> loki:
>   extraArgs:
>     server.path-prefix: /sonar/loki/
> ```
> 
> then you can do
> 
> ```
> helm upgrade --install loki loki/loki-stack --namespace=monitoring -f values.yaml
> ```

I tired this. But loki pod is not coming up. 

![image](https://user-images.githubusercontent.com/12157763/78836691-9cd35a00-79c0-11ea-896b-81c02435b9e0.png)
 
Below are values.yaml  entries

## Additional Loki container arguments, e.g. log level (debug, info, warn, error)
extraArgs:
  server.path-prefix: /sonar/loki/
  # log.level: debug

livenessProbe:
  httpGet:
    path: /ready
    port: http-metrics
  initialDelaySeconds: 45

**Comment by cyriltovena** [comment]
Those are just shutdown logs, the error is fine, can you share more logs ?

**Comment by cloudam** [comment]
Thanks Cyril. I am attaching my values.yaml file and complete pod logs.
[loki_logs.txt](https://github.com/grafana/loki/files/4457481/loki_logs.txt)
[values.yaml.txt](https://github.com/grafana/loki/files/4457483/values.yaml.txt)

**Comment by cloudam** [comment]
Issue is fixed. its because of the liveness and readiness probe. I set the same urls for readiness check.

Thanks a lot Cyril. Really appreciate your help.

**Comment by cloudam** [comment]
@cyriltovena 
Now after installing loki under custom path, its not picking the labels.
http://localhost:3100/status/loki/api/prom/label
{"values":["__name__"]}

do we need to change something in promtail values.yaml?

**Comment by cyriltovena** [comment]
Looks like the config for promtail url is wrong may be you should use that prefix now ? see the url here suggester https://github.com/grafana/loki/blob/6d5408c100e464e807cc3b1ad48be512c96167e3/docs/clients/promtail/configuration.md#client_config

may be it should be http://example.com:3100/sonar/loki/api/v1/push ?

**Comment by abbbhardwaj** [comment]
Hi @cloudam - Can you share your values.yaml on how did you set external url for loki?

I need to run loki behind a custom domain https://customdomain.com/loki. But I don't know where to find it in helm charts. Can you help?
