### ISSUE TITLE
Loki Helm Chart document should support Helm 3 ?

### ISSUE THREAD

**Issue by oke-py** [grafana/loki#1690]
**Is your feature request related to a problem? Please describe.**
Helm 3 is GA now and some command options changed from v2.
For example, the command below fails.

```
$ helm install stable/grafana -n loki-grafana
Error: must either provide a name or specify --generate-name
```

**Describe the solution you'd like**
The document below should be updated.
https://github.com/grafana/loki/tree/master/production/helm

**Describe alternatives you've considered**
I'm not sure which of Helm v2 or v3 should be mainly supported.

**Additional context**
N/A

**Comment by merqurio** [comment]
It works on Helm 3, the example fails because the `-n` argument was deprecated. Test this, it works for me:

```sh
helm install  loki-grafana stable/grafana
```

**Comment by oke-py** [comment]
thx, but what I'd like to know is whether the document should be updated or not.
