### ISSUE TITLE
Align model types and proto types when applicable

### ISSUE THREAD

**Issue by owen-d** [grafana/loki#1691]
I'd really like to see deduplication of code around logproto definitions. I think this is feasible and would help with both code deduping and type conversions.

Should follow https://github.com/grafana/loki/pull/1669

**Comment by owen-d** [comment]
cc @cyriltovena

**Comment by cyriltovena** [comment]
Which duplications ? Something we should be careful is currently our push API uses the same logproto definitions, so changing it is an API break.
