### ISSUE TITLE
Explain 'query' vs 'instant-query' in logcli

### ISSUE THREAD

**Issue by avarsava** [grafana/loki#1694]
The distinction between 'query' and 'instant-query' in logcli, the help output, and the documentation is completely unexplained. Please include explanations in the help output and documentation.

**Comment by avarsava** [comment]
@rfratto explained to me the distinction, but it's not clear from the help output and documentation that 'query' returns logs or metrics grouped into small windows of time (like the graph in the Expore pane in Grafana) and 'instant-query' returns metrics (like the table on the same). 
It seems to me like I would always want to use 'instant-query'; if I figure a metrics query is a question, then the answer should not be repeated to me many times for many slivers of time - I just want the answer for the period I specified in the question.

**Comment by owen-d** [comment]
Thanks - these are very good points. It's unfortunately very easy to forget who we're writing (or not writing) documentation for. I think either @slim-bean or myself are good candidates to add some docs here (because I've worked on LogQL and he's explained different queries 1000x to different people).

**Comment by cyriltovena** [comment]
If someone tackle this issue. We should may be link to Ian's talk https://www.youtube.com/watch?v=hTjHuoWxsks `PromQL for mere mortals` very good introduction on this subject.

**Comment by k3a** [comment]
From https://grafana.com/docs/grafana/latest/features/explore/: "When a query is executed, it actually executes two queries, a normal Prometheus query for the graph and an Instant Query for the table. An Instant Query returns the last value for each time series which shows a good summary of the data shown in the graph."
