### ISSUE TITLE
Streaming data: Wrong sorting

### ISSUE THREAD

**Issue by nt-rbmk** [grafana/loki#1698]
Hello,

first of all i` d like to congratulate you for the good job.

I popped up to a weird behavior while playing around with grafana-loki-promtail:
Logs seem not be sorted correctly, because **ts** under **Parsed fields** takes some time ~10m to get the proper value (from UTC->EET)
I` m using pipeline(s) in promtail to pass the proper timestamp.

**Environment:**
grafana: 6.5.1
loki: v1.3.0
promtail: v1.3.0

Distro: Ubuntu 18.04.4 LTS

```
root@ip-10-50-1-131:~# timedatectl 
                      Local time: Fri 2020-02-14 13:58:46 EET
                  Universal time: Fri 2020-02-14 11:58:46 UTC
                        RTC time: Fri 2020-02-14 11:58:47
                       Time zone: Europe/Athens (EET, +0200)
       System clock synchronized: yes
systemd-timesyncd.service active: yes
                 RTC in local TZ: no
root@ip-10-50-1-131:~# 
```

Please find attached screenshots and configs.

Best,

![stream1](https://user-images.githubusercontent.com/61050727/74531029-3f78da80-4f34-11ea-96c4-cb4a295a1c40.png)
![stream2](https://user-images.githubusercontent.com/61050727/74531039-430c6180-4f34-11ea-97fd-898c4a3996f1.png)
[loki-cfg.txt](https://github.com/grafana/loki/files/4204379/loki-cfg.txt)
[promtail-cfg.txt](https://github.com/grafana/loki/files/4204380/promtail-cfg.txt)

**Comment by nt-rbmk** [comment]
After some time, the ts of the following log was converted in a mysterious way to the proper one.
```
2020-02-14 13:40:13	
10.3.0.67 - - [14/Feb/2020:13:40:13 +0200] "GET / HTTP/1.1" 200 3477 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0"'
```

![stream3](https://user-images.githubusercontent.com/61050727/74531472-6552af00-4f35-11ea-8ab1-2c48841edad7.png)

**Comment by cyriltovena** [comment]
Have you check using the API if the timestamp are correct? I’m asking to triage the issue, not sure if this a grafana or loki issue.

Also you can cat your raw log to promtail locally in dry mode it show the timestamp it will send.

See https://github.com/grafana/loki/blob/master/docs/clients/promtail/troubleshooting.md#dry-running

This would help you verify promtail parsing is working as expected

**Comment by cyriltovena** [comment]
At least on the first look, I’d say it’s a UI issue, let us know.

**Comment by nt-rbmk** [comment]
Hello @cyriltovena,

thank you very much for the rapid response.
Please find attached the debug.

Best,
[debug_promtail.txt](https://github.com/grafana/loki/files/4212724/debug_promtail.txt)

P.S. i changed the **chunk_idle_period** value in loki config (from 5m -> 1m) and now is takes ~2m to get the proper value.

**Comment by cyriltovena** [comment]
Can you share you promtail config too please ?

**Comment by nt-rbmk** [comment]
Sure!
[promtail-cfg.txt](https://github.com/grafana/loki/files/4214401/promtail-cfg.txt)

**Comment by cyriltovena** [comment]
I don't see any issue, looks more like a UI glitch, the timestamp is the same in both cases, the only difference is the format really (one using UTC).

To confirm this is really a Loki issue I would need you too give a try to logcli and see if you see the same problem. (see https://github.com/grafana/loki/blob/master/docs/getting-started/logcli.md)

Thanks

**Comment by clemdem** [comment]
Hi,

First I'd also thank you for this great project.

I'm new to Loki and facing the same issue. As you can see the sort is not rendering well:

![image](https://user-images.githubusercontent.com/58794961/81414121-c8c03780-9146-11ea-9d04-8bebdc3f839a.png)

The component is configured in Ascending order.

With logcli the sort seems ok. After some time sort becomes ok in Grafana too.

Grafana: 6.5.2
Loki: 1.4.1
Promtail: 1.4.1

So it's maybe more a Grafana bug?

@nt-rbmk Did you solve this problem?

Thanks

**Comment by nt-rbmk** [comment]
@clemdem Nope, didn` t solve it.

**Comment by cyriltovena** [comment]
Do you have a simple way to reproduce this ? How can we get the same data ?
