### ISSUE TITLE
Improve caching strategy

### ISSUE THREAD

**Issue by slim-bean** [grafana/loki#1701]
It would be nice to modify the Tiered cache code and some other bits in cortex to allow a more complex caching strategy. 

Mainly, when a chunk is written it's stored in cache, we would like to keep _x_ amount of data in this cache for general querying, assuming a lot of queries will be within say the last hour (_x_ == 1 hour in this case).

However when people query older data, say from a week ago, when those chunks are loaded from the store they will be placed into the chunk cache after being read.  This would cause evictions of this last _x_ of data we are trying to cache for recent queries.

Essentially queries will fight over cache between recently written chunks and queries for data outside of what's in the cache.

I think an interesting approach would be to introduce another caching layer, keep the first layer for just the last _x_ chunks but also support adding another cache for query data.  This additional cache could potentially have a high churn rate and will be difficult to size, but is advantageous in cases where people run the same queries repeatedly, meanwhile we always maintain the last _x_ of data in a cache to make sure recent queries are fast.

**Comment by cyriltovena** [comment]
I think this is on point. The current strategy (mixing query and ingestion cache) doesn't work well for Loki, cause one can totally erase the other due to the size.

I think we have to have a cache per tenant also. Currently a single tenant can take over the full cache cluster.

Now the question is how do we do that cause this code is deep into Cortex.

/cc @gouthamve We need your input here.

**Comment by slim-bean** [comment]
This is still an issue/concern and we periodically discuss ways to handle this. I'm closing this issue for now as we are focusing on pruning our open issues list to be a small set of actively actively worked/discussed issues.
