### ISSUE TITLE
Frontend 500 on merging response.

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#1702]
This errors seems to happen `merging responses requires at least one response`. Not sure how but we should find out. I've seen it once too.

/cc @owen-d if you have some time next week.
/cc @gouthamve Do you have more context ?

**Comment by cyriltovena** [comment]
![image](https://user-images.githubusercontent.com/1053421/75553124-c6828400-5a05-11ea-9451-3216fbab1a41.png)


Look what I found today ! Going to fix this, somehow we get 0 interval and that's bad !

**Comment by cyriltovena** [comment]
Reopening this is still a thing ! It seems to happen when we provide a very high limit. 

/cc @slim-bean you do remember the query please ?

**Comment by cyriltovena** [comment]
I think I fixed this recently

**Comment by aricalee** [comment]
May I reopen this one...
I met the same issue again with loki 2.2.1...the issue happened when I run a "long" query with "Last 30 days"...after I got the issue the 1st time, all the following queries against the "Last 30 days" will always have the error very fast showed on the browser.

Anyway else I should provide to continue the troubleshooting of the issue?
