### ISSUE TITLE
Promtail does not fully use http_path_prefix

### ISSUE THREAD

**Issue by amiga23** [grafana/loki#1709]
**Describe the bug**
when setting http_path_prefix e.g. "/promtail/"
```
$ curl http://promtail:3101/promtail/
<a href="/targets">See Other</a>.
```

**To Reproduce**
1. Start promtail docker image with http_path_prefix configured as "/promtail/"
2. curl promtail endpoint with /promtail/

**Expected behavior**
Promtail should answer with redirect to:
/promtail/targets
but it does redirect to /targets
so http_path_prefix seems to be implemented only half-way

**Environment:**
 - Infrastructure: kubernetes (k3s with containerd instead of docker)
 - Deployment tool: kustomize

**Screenshots, Promtail config, or terminal output**
n/a

**Comment by kelceydamage** [comment]
Hi, I'm experiencing the same exact issue. `http_path_prefix` is not being respected by promtail internal forwarding.

**Comment by firmero** [comment]
Still same behavior, redirecting to `/targets`,  also hrefs contain fixed paths not reflecting `http_path_prefix`.

**Comment by Rom888** [comment]
The same issue.

**Comment by Apollo3zehn** [comment]
Same problem here. Exposing via NGINX on path http://server/promtail is not working.

**Comment by bsinou** [comment]
The issue is still there in `grafana/promtail:2.3.0` docker image.
Should we open a new issue?

**Comment by amiga23** [comment]
@bsinou if you want to get it fixed, either create a pull request ;-) or open a new ticket. This ticket was closed automatically, so I guess no developer is reading this.
