### ISSUE TITLE
Stop tagging things with :master, tag with :latest

### ISSUE THREAD

**Issue by tomwilkie** [grafana/loki#171]
I've accidentally tested the wrong version locally because of this...

**Comment by bergquist** [comment]
For grafana `latest` is the latest stable release. The version we want people to pull when they don't specify any version. `master` is the latest build from the master branch. 

At this stage. I guess both `master` and `latest` is the same thing for loki

**Comment by Dieterbe** [comment]
FWIW we started following the same pattern as grafana with crng and metrictank and will also adopt it for other projects (tsdb-gw). I think this matches the docker best practice.

**Comment by bergquist** [comment]
Yea I should have mentioned that `latest` is the default tag used by docker when nothing is specified.

**Comment by daixiang0** [comment]
@tomwilkie hi, now seems no latest tag can get which lead `docker pull grafana/loki` failed.
