### ISSUE TITLE
Querier errors cleanup

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#1714]
While working on https://github.com/grafana/loki/issues/1658

I realize there is a lot of other places where we don't send the right status code.

On top of this our errors are not consistent sometimes we use httpgrpc, sometimes we don't. Which leds to different type of error message structure.

Question should we come up with a json structure for error ? is that an API break ? at the very least we should ensure all status code are correct for all error path.

/cc @slim-bean

**Comment by slim-bean** [comment]
@cyriltovena can you update this and identify any areas we haven't fixed?

**Comment by cyriltovena** [comment]
Closing let's create new issue if we found this again, I've already worked on this.
