### ISSUE TITLE
where Loki and promtail log file

### ISSUE THREAD

**Issue by yang3808282** [grafana/loki#1715]
where is the file of loki.log and protail.log , i can not find it

**Comment by cyriltovena** [comment]
Hey 👋,

they log to stdout (which can be redirected to a file) so it depends on how you run them like almost any software. How do you run Loki and Promtail ? Kubernetes ? Linux systemd ? ./loki ?

**Comment by yang3808282** [comment]
> Hey 👋,
> 
> they log to stdout (which can be redirected to a file) so it depends on how you run them like almost any software. How do you run Loki and Promtail ? Kubernetes ? Linux systemd ? ./loki ?

yep,i run it on linux system,like this:
