### ISSUE TITLE
CI steps to push fluentd image with Loki output plugin

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#1724]
**Is your feature request related to a problem? Please describe.**

Currently we have a docker image that embed fluentd and our Loki plugin. But we don't provide a built version that can be easily be pulled.

**Describe the solution you'd like**
We should build a new image on each merge to master, like we do for other docker images.

Bonus point it would be great to also automatically push to gem repository.

**Comment by cyriltovena** [comment]
FYI we already have a step for fluent-bit that could may be re-used.

**Comment by Skeen** [comment]
There appears to be 3 docker images related to FluentBit / FluentD, namely:
* [grafana/fluent-bit-plugin-loki](https://hub.docker.com/r/grafana/fluent-bit-plugin-loki), which is for FluentBit and seems to be updated by CI.
* [fluent-plugin-grafana-loki](https://hub.docker.com/r/grafana/fluent-plugin-grafana-loki), which is for FluentBit and which seems to not to be updated.
* [grafana/fluent-plugin-loki](https://hub.docker.com/r/grafana/fluent-plugin-loki), which is for FluentD and which seems to not be updated.

If this analysis is indeed correct, could a deprecation warning be added to [fluent-plugin-grafana-loki](https://hub.docker.com/r/grafana/fluent-plugin-grafana-loki)'s documentation page redirecting to [grafana/fluent-bit-plugin-loki](https://hub.docker.com/r/grafana/fluent-bit-plugin-loki)? - Assuming this ticket is about [grafana/fluent-plugin-loki](https://hub.docker.com/r/grafana/fluent-plugin-loki).

**Comment by cyriltovena** [comment]
Yep we need to deprecate one, the one you choose for instance.
