### ISSUE TITLE
Provide Changelog for 1.3.0

### ISSUE THREAD

**Issue by till** [grafana/loki#1725]
**Describe the bug**
Changelog does not include 1.3.0.

**To Reproduce**
https://github.com/grafana/loki/blob/v1.2.0/CHANGELOG.md

**Expected behavior**
A description of all changes, and maybe upgrade paths (e.g. what happens when you change compression, etc..)

**Comment by jgehrcke** [comment]
The `CHANGELOG.md` file on the `1.2.0` branch will never contain a changelog for the 1.3.0 release.

Have a look at the `master` branch for now! https://github.com/grafana/loki/blob/master/CHANGELOG.md

You will also find release notes on https://github.com/grafana/loki/releases.

**Comment by till** [comment]
Ah, the link to the changelog in the 1.3 release notes is wrong. Maybe that can be fixed.

**Comment by till** [comment]
@jgehrcke

**Comment by till** [comment]
Le sigh.

**Comment by slim-bean** [comment]
Sorry @till that this went unnoticed for so long, this is fixed now, thank you for the issue!
