### ISSUE TITLE
Regex Label Name Filtering

### ISSUE THREAD

**Issue by m-mccormick** [grafana/loki#1729]
**Is your feature request related to a problem? Please describe.**
Querying multiple labels simultaneously.

**Describe the solution you'd like**
If I have multiple labels, for example:
- item00A
- item01A
- item00B
- item01B

It would be beneficial to be able to query them using regex such as:
- `{item*="value"}` to select:
  - item00A
  - item01A
  - item00B
  - item01B
- `{item*A="value"}` to select:
  - item00A
  - item01A
- `{item01*="value"}` to select:
  - item01A
  - item01B

**Describe alternatives you've considered**
Chaining queries together, but depending on the number of permutations, this could be tedious.

**Additional context**
None.

**Comment by cyriltovena** [comment]
Thanks for the issue @m-mccormick.

Have you thought about consolidating those label names into one ? At least from your example it is one of the solution I'd suggest.

**Comment by m-mccormick** [comment]
@cyriltovena 
I've been digging trying to figure out how to combine values into the same field but I'm having trouble coming up with an appropriate query. Here is how I'm attempting to approach combining values into a single label:

Let's say I have a label `info`:
![image](https://user-images.githubusercontent.com/12577607/75119220-c4f43d00-564e-11ea-9a68-176cfb393d7f.png)


So, I effectively have an array of items in a value with a `_` delimeter, Entry 1 being:
index `0` = `a`
index `1` = `b`
index `2` = `c`

Case 1: Query Match Index
I would like to match based on a specific index being a specific value, say querying `info` index `1` = `b` would match only Log Entry 1. If `b` is at a different index, it would not be a match.

Case 2: Query Value Index
I'm not sure if this can be extrapolated to metrics/time series, but return/plot index number based on value `b` query.

If regex could be used on the label name, it appears both of these could be accomplished rather easily by putting the index in the label name.

**Comment by cyriltovena** [comment]
What I was saying is you decide how log label s are populated in Loki, either via relabeling or via pipeline stages.

You should try to rework that label to have each index with their respective value.

info_1 info_2, ...

See those for manipulating labels:

https://github.com/grafana/loki/blob/master/docs/clients/promtail/configuration.md#pipeline_stages

https://github.com/grafana/loki/blob/master/docs/clients/promtail/configuration.md#relabel_config

**Comment by m-mccormick** [comment]
I understand. In the case of a tree structure of labels, how would one traverse the tree, especially if it has any depth? For example:

- info_1_1_1
- info_1_1_2
- info_1_2_1
- info_1_2_2
- info_2_1_1
- info_2_1_2
- info_2_2_1
- info_2_2_2

**Comment by cyriltovena** [comment]
Not sure if you found your way around but we want to improve logql see https://github.com/grafana/loki/pull/1848 it might help if not let’s discuss it.
