### ISSUE TITLE
Posting JSON to Loki

### ISSUE THREAD

**Issue by JosephWoodward** [grafana/loki#173]
According to the [documentation](https://github.com/grafana/loki/blob/master/docs/api.md#rest-api) you can post JSON objects to Loki like so, providing you're supplying the `Content-Type: application/json` header:

```http
POST http://localhost:3100/api/prom/push
Content-Type: application/json

{
    "streams": [
        {
            "labels": "{foo=\"bar\"}",
            "entries": [
                {"ts": "2018-12-18T08:28:06.801064-04:00", "line": "baz"}
            ]
        }
    ]
}
```

However it appears that Loki does not accept this:

```http
HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Wed, 19 Dec 2018 22:59:51 GMT
Content-Length: 22

snappy: corrupt input
```

**Comment by DanCech** [comment]
There was an issue with using `ts` for the line timestamps, try grabbing master and using `timestamp` instead.

**Comment by JosephWoodward** [comment]
Perfect, that seems to have fixed it - thanks!

**Comment by sleleko** [comment]
> Perfect, that seems to have fixed it - thanks!

How?

**Comment by JosephWoodward** [comment]
@sleleko I pulled down master and changed the property from `ts` to `timestamp` then it worked. Are you having problems getting it working?

**Comment by sleleko** [comment]
> @sleleko I pulled down master and changed the property from `ts` to `timestamp` then it worked. Like this:
> 
> ```httpspec
> POST http://localhost:3100/api/prom/push
> Content-Type: application/json
> 
> {
>     "streams": [
>         {
>             "labels": "{foo=\"bar\"}",
>             "entries": [
>                 {"timestamp": "2018-12-18T08:28:06.801064-04:00", "line": "baz"}
>             ]
>         }
>     ]
> }
> ```
> 
> Are you having problems getting it working?

Yes. Labels are pushing and I,m can see its in Grafana. But entries section not working, can.,t see this data in Grafana (
