### ISSUE TITLE
metric loki_request_duration_second: add tenant ID dimension

### ISSUE THREAD

**Issue by jgehrcke** [grafana/loki#1737]
Thanks for the nice overview in https://github.com/grafana/loki/blob/master/docs/operations/observability.md#observing-loki.

I see that `loki_request_duration_second` is emitted by all components. It has quite some cardinality already, and can seemingly be used to get insight into many important aspects of HTTP request handling. Just to name an example, it can be used to visualize the rate of 204 responses to POST requests to the distributor.

 I think I'd love for this metric to add one more dimension for the tenant ID! To stay with the mentioned example, we could then use it to visualize the rate of 400 responses to POST requests to the distributor for a specific tenant ID.

What do yo think?

**Comment by slim-bean** [comment]
We've discussed this before and the problem as you mention is cardinality, adding a tenant ID to a histogram would cause an exponential explosion of metrics, if you have 1000 tenants in a system multiply by what looks like 15 buckets in that histogram you would be exporting 15,000 metrics....

Also, generally speaking it's not often useful to know what the individual latency for a tenant is, that is, we know the average and quantile latencies, like 99%, so if we know that 99% of requests take 100ms is there really any value in knowing what an individuals latency was, we know it was less than 100ms.

Likewise if there is a problem and that latency goes up, does it matter which tenant(s) are being affected individually?  You can use the quantiles to get a better idea of how many tenants are affected.

**Comment by cyriltovena** [comment]
Loki support tracing and also logging so you should be able to find those slow request and pinpoint who is generating them by checking traces or logs.

**Comment by jgehrcke** [comment]
Thanks for the feedback here everyone! Happy for now. :)
