### ISSUE TITLE
Provide logcli docker image

### ISSUE THREAD

**Issue by varac** [grafana/loki#1751]
**Is your feature request related to a problem? Please describe.**

I'd like to install logcli as a docker container, because installing binaries on some OS  (i.e.  k3os/coreos) is discouraged in favor of container installations.
However. the official [grafana/logcli](https://hub.docker.com/r/grafana/logcli/tags) is lacking tags and is therefore not usabale. I also don't like to install untrusted images from docker hub.

**Describe the solution you'd like**

Please publish latest logcli docker images, or include logcli inside the `grafana/loki` image.

**Describe alternatives you've considered**

* Maintaining your own image, which comes with extra overhead for a lot of users
* Installing the binary as descibed in the docs.

Thanks !

**Comment by cyriltovena** [comment]
If someone wants to do this I've started a branch
https://github.com/cyriltovena/loki/tree/logci-docker

We just need to hook the CI.

**Comment by tharun208** [comment]
I like to work on this

**Comment by slim-bean** [comment]
@tharun208 let us know if there is anything we can do to help!

**Comment by tharun208** [comment]
@slim-bean raised a pr
