### ISSUE TITLE
S3 bucket prefix should be configurable

### ISSUE THREAD

**Issue by Jiawei0227** [grafana/loki#1760]
It seems we only support the pointing bucket name in S3. However, we need should also support custom prefix of where the chunks go into the S3 bucket.

Right now they are all under "fake", which is unpleasant.

**Comment by slim-bean** [comment]
`fake` is the tenant ID, when running Loki in a multi-tenant configuration this is replaced by a unique tenant id.  When auth is disabled it defaults to fake.

Is there a use case you have for a custom prefix or do you just not like the word 'fake'?

**Comment by Jiawei0227** [comment]
Yes, I do have a use case for a custom prefix... It would be good if we can define a root prefix to place the fake/ or the multi-tenant id. We can make it default to "". What do you think?

**Comment by Jiawei0227** [comment]
Hey, any updates on this? If someone can point me where this is configured I can help to make the change.

**Comment by cyriltovena** [comment]
That's more a cortex discussion since we are using cortex for storing logs see https://github.com/cortexproject/cortex if that get accepted there then it will be added here too.

**Comment by vprus** [comment]
I think it's strange that I can specify bucket, but not prefix. Basically no other tools works this way. For specific example, I want logs to be put into "company-name-logs" bucket, and Loki to write to "company-name-logs/loki" specifically. The reason is that it's easier to keep track of all logs, and add some S3 lifecycle rules, if all logs are in the same bucket.

**Comment by alysonfranklin** [comment]
I'm still having the same problem.
Is there already a solution for this case?

I would like to use another Loki to send files to the same bucket, and I can't because of this problem.

**Comment by LinTechSo** [comment]
Hi, same issue, any updates? @vprus @alysonfranklin @Jiawei0227

**Comment by Jiawei0227** [comment]
unfortunately I dont know much about loki code so we will need Loki team to help here

**Comment by darintay** [comment]
I raised an issue on the Cortex side, but no response, and it's not clear to me how active that project is now post-Mimir fork.

Another similar issue here - https://github.com/grafana/loki/issues/5889 - that maybe has someone looking at it

**Comment by Ibtihaj-Abdullah** [comment]
Nay updates on this issue? Anyone? It's 2025 and i can't believe loki didnt address this
