### ISSUE TITLE
Stop tailing files after no updates to them for X minutes

### ISSUE THREAD

**Issue by mwarchut-monsoon** [grafana/loki#1761]
It would be great if there was a setting so that promtail would stop tailing files after they not received any entries for X amount of time.    I don't see anything like that in here.  Our log collection server has literally 100's of thousands of files and as it sits promtail crashes if it tries to tail too many files.

**Comment by adityacs** [comment]
@slim-bean Thinking on this feature. If we stop tailing a file after X minutes, later when there is an update to the file after X+Y minutes, we won't be tailing the new updates of the file since we already stopped it. So, it's similar to removing the file. 

Suppose user wants to tail the file again. Loki will start reading the file from the beginning which is kind of duplicate.

Do you think this would be good feature to be included?
OR
Should we just leave it to user for managing the files?

**Comment by mwarchut-monsoon** [comment]
The problem I am running into is that we have too many files for promtail to tail.. Maybe minutes is too granular and it should be hours or days.   our logs have a max size and when they reach it a new one is started and the previous one closed permanently.   Logstash has a feature like this.

**Comment by adityacs** [comment]
@mwarchut-monsoon 
> logs have a max size and when they reach it a new one is started and the previous one closed permanently. Logstash has a feature like this

This makes sense

**Comment by slim-bean** [comment]
Apologies for not responding sooner, this is a tricky one for the reasons @adityacs mentioned.
The biggest problem I see is how do we manage the state over promtail restarts? This feels like it would be a pretty big change to promtail.

Typically I think this would be handled by the way files are renamed when they are rolled (usually a number is appended) and the path matching is setup to ignore the rolled files.

@mwarchut-monsoon does your file rolling behavior not create files in a way you cant create a matching expression that ignores the rolled files?

Often you see this as:

app.log
app.log.1
app.log.2

Where a matcher of `app.log` or `*.log` would ignore the rolled files.

**Comment by slim-bean** [comment]
Copying my note from the associated pr:

>Sorry for the slow response on this, it's been difficult for me to make up my mind here.  It's easy to say to people they should change how their environment works but I realize that's not always easy to do.  
>
>That being said, there are quite a few edge cases with supporting this and it would be difficult to get it right, and it's difficult for me to choose adding more complexity to the project when existing solutions for rotating logs are battle tested and better suited to solve this problem.
>
>I'm going to close this PR and the corresponding issue with the guidance that people really should lean on using log rotating solutions and/or schemes that allow promtail to work as built today.

**Comment by mayconritzmann** [comment]
I am having a similar problem, I have an environment where the log file is modified on a slower scale.

Where is the problem? I have a Grafana panel where I describe the file name according to the label delivered by the Loki datasource.

label_values ​​(filename)

As the file is closed after X minutes that I have not found the value anywhere, the list is displayed only with files that are in the tailing state.

Does anyone know maybe how to increase this close time of the file?
