### ISSUE TITLE
Loki clustered deployment configuration

### ISSUE THREAD

**Issue by yang3808282** [grafana/loki#1768]
When I deploy a loki cluster, do each component only need to configure its own config, or all of them? For example, the configuration file of the ingester component only needs to write the ingester_config part, or do I need to configure server_config, chunk_store_config, storage_config, etc.
![image](https://user-images.githubusercontent.com/40430624/75740268-2c427900-5d42-11ea-95c9-af7b6672573e.png)

**Comment by slim-bean** [comment]
The only need config sections that are relevant to them, however, in some cases they share the same config (for example the lifecycle section with the ring information is used by multiple components).

We typically deploy it as one config file and share that same file with each component

**Comment by yang3808282** [comment]
> The only need config sections that are relevant to them, however, in some cases they share the same config (for example the lifecycle section with the ring information is used by multiple components).
> 
> We typically deploy it as one config file and share that same file with each component

I got it,can you share with your confug file? I can learn from it. I also want to ask another question, In the cluster deployment process, does each loki machine deploy a consul server, do I need to deploy a consul client?

**Comment by senior88oqz** [comment]
> > The only need config sections that are relevant to them, however, in some cases they share the same config (for example the lifecycle section with the ring information is used by multiple components).
> > We typically deploy it as one config file and share that same file with each component
> 
> I got it,can you share with your confug file? I can learn from it. I also want to ask another question, In the cluster deployment process, does each loki machine deploy a consul server, do I need to deploy a consul client?

You may take a look at discussions around https://github.com/grafana/loki/issues/643#issuecomment-498631712; I also found https://github.com/grafana/loki/pull/680 very useful although it was merged.

**Comment by yang3808282** [comment]
> > > The only need config sections that are relevant to them, however, in some cases they share the same config (for example the lifecycle section with the ring information is used by multiple components).
> > > We typically deploy it as one config file and share that same file with each component
> > 
> > 
> > I got it,can you share with your confug file? I can learn from it. I also want to ask another question, In the cluster deployment process, does each loki machine deploy a consul server, do I need to deploy a consul client?
> 
> You may take a look at discussions around [#643 (comment)](https://github.com/grafana/loki/issues/643#issuecomment-498631712); I also found #680 very useful although it was merged.

How can i express my gratitude to you！
