### ISSUE TITLE
Can't access http://slack.raintank.io/ to join the #loki slack channel as per Readme

### ISSUE THREAD

**Issue by markfermor** [grafana/loki#1769]
**Describe the bug**
Was hoping to chat about Loki in the slack channel but doesn't seem to be possible to get logged in

**To Reproduce**
Go to http://slack.raintank.io/ as per docs

**Expected behavior**
Not sure, a method to sign-up to grafana slack?

**Environment:**
NA

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by slim-bean** [comment]
We'll take a look, thanks @markfermor

**Comment by rfratto** [comment]
Thanks for the heaps up @markfermor, the link should work again. I've also updated the readme to point to https://slack.grafana.com, although both links are valid and let you join the same Slack.

**Comment by markfermor** [comment]
Many thanks :)
