### ISSUE TITLE
Doc: conflicting schema version recommendation

### ISSUE THREAD

**Issue by candlerb** [grafana/loki#1778]
**Describe the bug**
The documentation is inconsistent as to whether new installations should use v10 or v11 schema.

**To Reproduce**
At https://github.com/grafana/loki/blob/master/docs/architecture.md it says:

> The current schema recommendation is the v10 schema.

But in the sample loki configuration at https://github.com/grafana/loki/blob/master/cmd/loki/loki-local-config.yaml it says

> `schema: v11`

**Expected behavior**
If the current schema recommendation is the v10 schema, then I'd expect the sample config to use the v10 schema too.

**Environment:**
N/A

**Screenshots, Promtail config, or terminal output**
N/A

**Comment by slim-bean** [comment]
hey @candlerb thanks for bringing this up.

v11 is the recommended schema, would you be interested in a PR to fix the docs?
