### ISSUE TITLE
Fluent-bit Loki Plugin key_value format

### ISSUE THREAD

**Issue by davidpean** [grafana/loki#1784]
**Describe the bug**
When using the fluent-bit loki plugin and setting LineFormat=key_value, strings are not being quoted thus causing parsing problems in Loki

**To Reproduce**

Using a fluent-bit image with the following config

```
[Output]
    Name loki
    Match *
    Url ${LOKI_URL}/loki/api/v1/push
    BatchWait 1
    # (1sec)
    BatchSize 30720
    # (30KiB)
    LineFormat key_value
    LogLevel debug
```

**Expected behavior**
Example log message from Grafana that Loki parses

`t=2020-03-09T13:04:38+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=92.577 alertId=147 name="Disk Used alert" firing=false attemptID=1`
--

**Environment:**
 - Infrastructure: docker, aws
 - Deployment tool: ECS

**Screenshots, Promtail config, or terminal output**

Outputs logs in format `key=value message=this is a log entry ts=1234`

When Loki parses the spaces obviously cause the fields to get incorrectly set

https://github.com/grafana/loki/blob/master/cmd/fluent-bit/loki.go#L195 

Compared with Fluentd grafana loki plugin - https://github.com/grafana/loki/blob/master/fluentd/fluent-plugin-grafana-loki/lib/fluent/plugin/out_loki.rb#L241 (which quotes values)

**Comment by cyriltovena** [comment]
I'm thinking of using this https://github.com/go-logfmt/logfmt
