### ISSUE TITLE
Implement Cortex readiness Handler in Loki

### ISSUE THREAD

**Issue by adityacs** [grafana/loki#1788]
**Is your feature request related to a problem?
Loki currently handles `/ready` endpoint individually for each modules. Also, we are missing `/ready` endpoint for query-frontend. 

**Describe the solution you'd like**
Cortex now has `readiness Handler` irrespective of module. Loki should implement this

**Comment by cyriltovena** [comment]
I'm going to assign this to Peter ! I think he has plan for this.

**Comment by adityacs** [comment]
@cyriltovena Sure.
@pstibrany I have changed the title and description of this issue

**Comment by pstibrany** [comment]
https://github.com/grafana/loki/pull/1804 implements unified /ready handler (among other things) that works in microservices as well as single-binary mode.

**Comment by adityacs** [comment]
@cyriltovena We can close this issue as #1804 is merged.
