### ISSUE TITLE
Run promtail as a service from an installation package. 

### ISSUE THREAD

**Issue by wardbekker** [grafana/loki#1790]
**Is your feature request related to a problem? Please describe.**
Promtail is now a binary release. If you want to run it as a service, you need to create and register the service definitions yourself.  For non-k8s installs, users very likely want to run promtail as a service.

**Describe the solution you'd like**
Provide installation packages for all major operating systems that will install promtail as a service. 

**Describe alternatives you've considered**
Self scripting the service definitions. However, providing promtail as a service will improve onboarding and increase Loki adoption 

** Relevant Resources / projects ** 
https://github.com/kardianos/service
https://github.com/jordansissel/fpm

**Comment by slim-bean** [comment]
Duplicate of #52
