### ISSUE TITLE
Optimize empty filter queries

### ISSUE THREAD

**Issue by slim-bean** [grafana/loki#1792]
If a query like:

`{label="foo"} |= ""` or `{label="foo"} |~ ""` these should be optimized to `{label="foo"}`

You might ask why would someone do this? When creating a dashboard with a log panel you might want to create a text variable on the dashboard which could be used in the filter expression like so:

`{label="foo"} |~ "$searchVar"`

If the user leaves this filter blank it ends up sending the query as `{label="foo"} |~ ""`

**Comment by cyriltovena** [comment]
We should also support `{label="foo"} |~ ".*"`

**Comment by gabzim** [comment]
> It only works when the search is not empty but when you enter in the Grafana dashboard, it is empty and the query fails.

I've been struggling with this. I use a ` | json | field=$var` and I need a way to say `if $var is empty, don't filter at all, otherwise to filter on the label "field" that was added by the json step`
