### ISSUE TITLE
Document promtail configs

### ISSUE THREAD

**Issue by gouthamve** [grafana/loki#18]

**Comment by dguendisch** [comment]
Desperately needed. I have a hard time grasping the meaning of the various `job_name`s in the `scrape_configs` section and especially the dropping syntax...

**Comment by daixiang0** [comment]
here is https://github.com/grafana/loki/blob/master/docs/promtail.md.

**Comment by korjavin** [comment]
404 there

**Comment by messju** [comment]
have a look here: https://github.com/grafana/loki/blob/master/docs/clients/promtail/README.md

**Comment by timo-klarshift** [comment]
All links in this issue are 404

**Comment by cyriltovena** [comment]
https://grafana.com/docs/loki/latest/clients/promtail/
