### ISSUE TITLE
Heuristics pkg consuming `logql/stats` for query suggestions

### ISSUE THREAD

**Issue by owen-d** [grafana/loki#1803]
As per some discussion, I think it's a good idea to create a heuristics pkg which can read the logql statistics from a query and suggest query improvements (too many series? try adding labels. Too much data? try reducing time range or adding filters/etc).

Thoughts?

/cc @slim-bean @cyriltovena 

Functionality ideas:
- handle `{foo=~".*"}` queries which would match _everything_ and give suggestions for `{foo=~".+"}`, basically when there's one matcher and it willl match anything.
- handle high cardinality queries, suggesting additional label filtering

**Comment by cyriltovena** [comment]
@slim-bean had some similar idea yesterday.

**Comment by slim-bean** [comment]
Closing this in an effort close long standing bugs, still a good idea, still want to do this. Will revisit at a future date.
