### ISSUE TITLE
Loki backfills empty tables on new deployments

### ISSUE THREAD

**Issue by chancez** [grafana/loki#1820]
**Is your feature request related to a problem? Please describe.**
Sometimes I deploy Loki in new environments reusing an existing configuration, but the schema_config has dates in the past that I didn't properly update before deploying Loki. This leads to a number of unnecessary tables being created in the past up to the table retention, that never get any use unless you've got enough old log data that you need to backfill. Given that most logging systems rotate logs regularly, this seems less likely and the backfilling of tables is unnecessary in many cases.

**Describe the solution you'd like**

This isn't all that unexpected, but for a fresh deploy, it would seem that Loki could probably only create the table for the current index period unless configured otherwise. If you need it to backfill to the earliest time within the table retention period, then you could configure that explicitly in the `table_manager`.

Additionally, it would be ideal to have a method to tell Loki to delete tables that are within the retention period so that when you want to delete old tables, before the retention period, you can do so without changing retention, redeploying, and waiting for tables to be deleted, then changing retention back to the desired value. For example, there could be a configuration in the `schema_config` or `table_manager` which could indicate that if tables exist that do not have a corresponding schema_config, they should be deleted. This however would require storing a list of previously created tables somewhere, so that when you remove a schema_config, the table manager can detect the removal and determine which tables no longer need to exist.

**Describe alternatives you've considered**

I've provided two solution to slightly different, but related issues. I think either or both could improve the status quo.

**Additional context**
I'm using DynamoDB with S3 in Kubernetes. Our index period is 168h, 7 days, and we never have logs older than 7 days lying around, and if we do it's okay if these logs cannot be stored in the cases of not backfilling older tables beyond the current period. I think this is a reasonable trade off to avoid the extraneous old tables.

**Comment by chancez** [comment]
CC @owen-d

**Comment by owen-d** [comment]
Thanks @chancez!

@slim-bean @cyriltovena I know we've chatted about this. Going to keep tabs on it as I want to work on a few AWS quality of life issues soon.

**Comment by cyriltovena** [comment]
Yeah seems fair, does creating table  cost something  ?

**Comment by chancez** [comment]
Dynamodb tables can cost a lot or very little based on the credits/provisioning. So not really, but if you configure inactive tables with decent provisioned throughput, it could be a bit expensive.
