### ISSUE TITLE
Auto reconnect or quickly exit when cassandra cluster down and then up.

### ISSUE THREAD

**Issue by cmsxbc** [grafana/loki#1821]
**Is your feature request related to a problem? Please describe.**
Using cassandra cluster as storage.When the cassandra cluster down, this error occurs.And it will never recover though the cassandra is UP. 
And if we want to restart loki, loki will fall because of loop forever.
![image](https://user-images.githubusercontent.com/3500109/77029657-41243b00-69d7-11ea-87e4-9e375657d35b.png)

**Describe the solution you'd like**
As gocql wounld fix it (eg. [gocql-915](https://github.com/gocql/gocql/issues/915) created at 2017 and never closed.)
Would loki do something to reconect? Or do not retry to flush forever.

**Describe alternatives you've considered**

**Additional context**

**Comment by freggelicious** [comment]
I'm experiencing the same issue. I run Cassandra as a Statefullset within my K8s cluster. For some reason my Cassandra cluster became unhealthy. I initiated a restarted of the Cassandra pods and the cluster was healthy again, but i got the same error as you mention. I was able to get it working again by restarting the Loki pod, but this is not preferred.

**Comment by liguozhong** [comment]
I also have this error on online loki

**Comment by liguozhong** [comment]
![image](https://user-images.githubusercontent.com/9583245/179951377-19007c7a-f715-4013-a771-fe1044165270.png)
