### ISSUE TITLE
Enabling `health_check_ingesters: true` leads to panics.

### ISSUE THREAD

**Issue by pstibrany** [grafana/loki#1829]
Structure returned by https://github.com/grafana/loki/blob/107dfd3607a634fea1fecf763e10b0e5fa6fb9c1/pkg/ingester/client/client.go#L35 has no implementation for `grpc_health_v1.HealthClient`, so calling methods of this interface panics.

This happens if someone enables 'health_check_ingesters: true'.

Loki 1.3.0

**Comment by adityacs** [comment]
@pstibrany @owen-d we have fixed this in https://github.com/grafana/loki/pull/1730

**Comment by pstibrany** [comment]
> @pstibrany @owen-d we have fixed this in #1730

Great, I missed that! Thank you!

**Comment by owen-d** [comment]
Awesome, what a nice surprise.

Thanks @adityacs
