### ISSUE TITLE
more configurable job label in mixin

### ISSUE THREAD

**Issue by brancz** [grafana/loki#1830]
**Is your feature request related to a problem? Please describe.**

Make loki and promtail mixin less opinionated about their Prometheus scrape config. The kubernetes-mixin is rather successful with this, it makes no assumption about the scrape configs of users and where it does it makes it selectors fully configurable.

Currently it seems there is some scheme of `<namespace>/<type>` format expected in the job selectors.

**Describe the solution you'd like**

Ideally make the `job` label-selector used configurable in some way.

**Describe alternatives you've considered**

Have inconsistent scrape configs and labeling in my infrastructure. This would be a shame as preventing that is exactly why relabeling is free form and why monitoring mixins were created :) 

**Additional context**

As far as I can tell this is primarily about the way the `job` label is scoped in queries in the dashboards. Also I believe only dashboards are currently affected by this, alerting rules seem to be agnostic to the job label format, that's nice to see already :slightly_smiling_face: .

@cyriltovena @gouthamve @metalmatze @bwplotka @tomwilkie

**Comment by brancz** [comment]
I'll try to see if I can come up with something that would continue to default to the current selectors but make them configurable.

**Comment by cyriltovena** [comment]
> As far as I can tell this is primarily about the way the `job` label is scoped in queries in the dashboards. Also I believe only dashboards are currently affected by this, alerting rules seem to be agnostic to the job label format, that's nice to see already 🙂 .

I've got more alerts and dashboards coming up and they all use the job label 🙃. Let me know if you sort this out so I can translate them too.

**Comment by brancz** [comment]
I haven't been able to find something that I quite like that doesn't involve changing the templated labels being queried a little bit. It would also be nice if it wasn't necessary to have the components be running on Kubernetes to use the dashboards. What I'm thinking is that it would be nice to just rely on `job` and `instance` labels. Would you be ok if we rework the dashboards slightly to be based around those labels? Then not only would they not rely on the format of the `job` label but also work in non-kubernetes environments.

**Comment by cyriltovena** [comment]
How would that work for the Read dashboard ? It seems to rely heavily on cluster/namespace labels for dropdown and job for filtering applications.

Maybe you can show an example of one dashboard and we can see if we're fine with it.

**Comment by brancz** [comment]
Opened a WIP PR to demonstrate the direction I was thinking: https://github.com/grafana/loki/pull/1978

**Comment by brancz** [comment]
Sorry I haven’t had time to follow up on this but I intend to move it forward at some point.

**Comment by periklis** [comment]
@brancz @cyriltovena I will take over this PR and close the loose edges. I would like to see this part of the mixin sooner than later.

**Comment by brancz** [comment]
Feel free to continue what I started in the WIP PR.
