### ISSUE TITLE
promtail static_configs targets can have any value

### ISSUE THREAD

**Issue by Mario-Hofstaetter** [grafana/loki#1831]
**Describe the bug**
Documentation https://github.com/grafana/loki/blob/v1.3.0/docs/clients/promtail/configuration.md#static_config
states that in `static_config`:
```
# Configures the discovery to look on the current machine. Must be either
# localhost or the hostname of the current computer.
targets:
  - localhost
```

**However, this is not enforced, and has no effect?**

**To Reproduce**
Run promtail with a scrape_configs containing:
```
    static_configs:
      - targets:
          - "foobar"
```
on a machine __not__ named `foobar` 😄 
Service Discovery shows `__address__="foobar"`, 
but logs are pushed to loki correctly. `__address__` label is not visible inside grafana.

**Expected behavior**
??? Is this an unused config value when running static?
Does this have any effect?

**Environment:**
 - Promtail bare-metal on Windows 10, 1909

**Comment by adityacs** [comment]
@Mario-Hofstaetter The labels with `__` is dropped here `https://github.com/grafana/loki/blob/master/pkg/promtail/targets/filetargetmanager.go#L249`

If you want to add host label, You can add an extra label under `labels`

```
labels:
      job: varlogs
      __path__: /var/log/*log
     hostname: systemhostname
```

**Comment by cyriltovena** [comment]
__address__ and __host__ are not available those are labels used only during scrapping. You could still add them via relabelling or pipeline stage or even like @adityacs suggested.

And yes:

```
# Configures the discovery to look on the current machine. Must be either
# localhost or the hostname of the current computer.
targets:
  - localhost
```
is not used in Loki and doesn't have side effects.

Feel free to send a PR to update the documentation.
