### ISSUE TITLE
empty groupings in logql aggregations throw parse errors

### ISSUE THREAD

**Issue by owen-d** [grafana/loki#1835]
`sum by () (rate({app="foo"}[1m]))` and `sum without () (rate({app="foo"}[1m]))` both throw syntax errors. While these are redundant cases of `sum(rate({app="food"}[1m]))` and `rate({app="foo"}[1m])`, respectively, they are still valid and should not error.

**Comment by slim-bean** [comment]
I think we can close this, I'm ok with a syntax error and requiring the user to remove the empty parens.
