### ISSUE TITLE
Loki pod stuck in terminating state

### ISSUE THREAD

**Issue by tanora** [grafana/loki#1836]
Loki is been deployed with helm. The Loki pod gets stuck in a terminating stage. The only way to delete the pod is to run `kubectl delete pod loki-0 --grace-period=0 --force`. I also get this following error.

level=error ts=2020-03-23T06:28:56.677314609Z caller=flush.go:178 org_id=fake msg="failed to flush user" err="RequestCanceled: request context canceled\ncaused by: context deadline exceeded"

Loki is configured to use S3 and DynamoDB with all permissions in the link bellow except the AutoScaling permissions.

https://github.com/grafana/loki/tree/master/docs/operations/storage

**Comment by tanora** [comment]
The pod does delete without force, it just takes a few hours.

**Comment by cyriltovena** [comment]
Yes it's because it's flushing your data so you don't lose any. Thanks for reporting.

**Comment by tanora** [comment]
Thanks.

**Comment by CasparChou** [comment]
my logs showing this repeatedly
and loki can't be kill by signal 9
It can't wait hours, how should I do?

```
level=info ts=2021-04-08T07:13:07.229265903Z caller=table_manager.go:171 msg="uploading tables"
level=info ts=2021-04-08T07:13:07.229396956Z caller=table.go:340 msg="uploading table index_18724"
level=info ts=2021-04-08T07:13:07.22941025Z caller=table.go:367 msg="finished uploading table index_18724"
level=info ts=2021-04-08T07:13:07.22942584Z caller=table.go:425 msg="cleaning up unwanted dbs from table index_18724"
level=error ts=2021-04-08T07:13:07.555730251Z caller=pool.go:161 msg="error removing stale clients" err="too many failed ingesters"
level=info ts=2021-04-08T07:13:08.671144143Z caller=table.go:340 msg="uploading table index_18725"
level=info ts=2021-04-08T07:13:08.671179357Z caller=table.go:367 msg="finished uploading table index_18725"
level=info ts=2021-04-08T07:13:08.671193587Z caller=table.go:425 msg="cleaning up unwanted dbs from table index_18725"
```
