### ISSUE TITLE
Support 0 for model.Duration in the table manager

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#1839]
Recently the table manager period has been changed to use `model.Duration` from Prometheus because of a vendoring in Cortex. see https://github.com/grafana/loki/blob/master/vendor/github.com/cortexproject/cortex/pkg/chunk/table_manager.go#L95 and #1838

The problem is that before `time.Duration` was supporting the value 0. Before it propagates to other fields we should try to suggest in the [prometheus common project](https://github.com/prometheus/common) a change to support the 0 value. Then backport this to Cortex and Loki.

**Comment by cyriltovena** [comment]
PR to Prometheus. https://github.com/prometheus/common/pull/226 let's see.

**Comment by cyriltovena** [comment]
Prometheus won't accept this PR. I don't think it's worth wasting time arguing or pushing further. We'll have to use the new `0s` default.

**Comment by cyriltovena** [comment]
Change of plan upstream Prometheus accepted the PR. We need to update cortex and then get that into Loki. Should be easy for anyone to take it.

**Comment by mmedum** [comment]
Hi @cyriltovena i would like to do some work on this. Could you get me up to speed quickly on this? :)

**Comment by cyriltovena** [comment]
Sure:
- First you need to update prometheus common in cortex. using https://github.com/prometheus/common/pull/226
- Then update Loki from the latest cortex.
- That's should be it really it will support the 0 duration now.

Maybe you should wait for https://github.com/grafana/loki/pull/1869 before starting anything so you don't get conflicts.

**Comment by mmedum** [comment]
Will do. 🙂

Just going to start on one of the other issues.

**Comment by mmedum** [comment]
Hi agian @cyriltovena 

From what I can tell, PRs should be merged for dependencies. Are you still missing this update or did it already get merged with resolution of #1869?

**Comment by cyriltovena** [comment]
I need to check

**Comment by lukashass** [comment]
I just came across an error that I suppose would be fixed by resolving this issue.

`failed parsing config: /etc/loki/local-config.yaml: not a valid duration string: "0"` while using `grafana/loki:latest` with the default config file.

It seems [this](https://github.com/grafana/loki/blob/master/cmd/loki/loki-local-config.yaml#L41) line still uses `0` while the last line in the file was changed to using `0s` in 0ad1c6c1af77f09159b0e66cdd2832f1cabf3606.

**Comment by cyriltovena** [comment]
@mmedum This is still an issue and this hasn't been fixed by #1869.

If you want to take this, first open a PR on cortex to update prometheus/common there to latest.

Once it's merged in cortex, open a PR here to update cortex to latest.

Good luck ✌️ 

@lukashass you're probably hitting another one.

```
chunk_store_config:
  max_look_back_period: 0s
```

Use this instead of the default and the error will go away.

**Comment by mmedum** [comment]
@cyriltovena Thanks.

But maybe I am a bit useless, from what I can see, cortexproject/cortex uses prometheus/common lastest already. 

I have in my fork updated loki to use cortexproject/cortex v1.0.0, as that is the lastest release from what I can tell. But it seems I am hitting a snag with:

```
go: finding module for package github.com/cortexproject/cortex/pkg/ring/client
github.com/grafana/loki/pkg/distributor imports
	github.com/cortexproject/cortex/pkg/ring/client: module github.com/cortexproject/cortex@latest found (v1.0.0), but does not contain package github.com/cortexproject/cortex/pkg/ring/client
```

**Comment by cyriltovena** [comment]
Let me check

**Comment by cyriltovena** [comment]
So Cortex doesn't use latest prometheus/common, you can either try to overrides in Loki or update it first in Cortex.

**Comment by ghostsquad** [comment]
I'm following the Tanka installation guide, and I'm running into the same problem. What keys in the jsonnet need to be updated to be `0s` instead of `0` ?

**Comment by ghostsquad** [comment]
I think I resolved with this below. It would be nice if the defaults just worked.

```
_config+:: {
    ...
    loki+: {
      chunk_store_config+: {
        max_look_back_period: "0s",
      },
      table_manager+: {
        retention_period: "0s",
      },
    },
  },
```
