### ISSUE TITLE
Support series API in logcli

### ISSUE THREAD

**Issue by yeya24** [grafana/loki#1841]
**Describe the solution you'd like**

Since there is already a series API to get the different series, so it would be nice to add this functionality in logcli.

**Comment by owen-d** [comment]
Thanks @yeya24 !

**Comment by aabidaz** [comment]
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.
> 
> Since there is already a series API to get the different series, so it would be nice to add this functionality in logcli.

I want to learn how to make commands for fb cloning
