### ISSUE TITLE
Document backup procedure for boltdb

### ISSUE THREAD

**Issue by stvnwrgs** [grafana/loki#1844]
**Is your feature request related to a problem? Please describe.**
There is no documentation on how to create backups with boltdb. I could also not find any documentation in cortex. I'm not sure which components need to be backed up and how? Can I just create disk snapshots of etcd and the ingester? I guess that would lead to a split brain?

**Describe the solution you'd like**
I would like to see some documentation about creating backups and restoring backups. Including all components needed. 

I would also like to help with some documentation. But first of all, I would need to understand better how the data is persisted. Consul/etcd support exports/snapshots. Is the data in etcd needed or is it just used for service discovery? Is there any way to export/import data to the loki components yet?

**Comment by cyriltovena** [comment]
boltdb is persisted on disk and you can take a snapshot of the data. When you configure boltdb usually you give a path.

Are you running consul/etcd and boltdb ? Can you explain a bit more how you run Loki ?
