### ISSUE TITLE
Consider abandoning promtail and contributing to existing log collectors

### ISSUE THREAD

**Issue by redbaron** [grafana/loki#185]
It is a significant effort to make a reliable and feature rich log collector.  Please consider NOT doing it and preparing output plugins for existing popular ones:
 - fluent-bit (https://github.com/fluent/fluent-bit/issues/994)
 - fluentd
 - beats

**Comment by kfox1111** [comment]
+1. it is a lot of effort to get a log collector working reliably and to integrate it with k8s. fluent-bit is very light weight. It would be a good fit I think.

**Comment by DanCech** [comment]
I think the idea here is for loki to support multiple collectors for different use-cases, which makes sense to me.

**Comment by adamdecaf** [comment]
From what I understand about `promtail` is that it won't get into the business of parsing/tokenizing logs, so the log patterns from fluentbit/logstash might not apply.

**Comment by redbaron** [comment]
Output plugin for existing log collectors can (and should) pack log entry
back into string before sending it to Loki. Creating and maintaining
promtail is a wasted effort IMHO, unless it is going to offer some killer
features, but from what I've read it has no ambitions.

**Comment by kfox1111** [comment]
Yeah, I kind of objected to doing any parsing in fluent-bit too. it really should just ship the logs. something else like fluentd can parse them much more flexibly. But you can turn off the parsing in the config and just not use it. Not sure when its off how much code is still executed...

If the goal was to really do just pure log shipping without any parsing code, maybe we can get a build time configurable to fluent-bit that disables all parsing machinery? Then there wouldn't be a need for another project.

**Comment by AlessandroEmm** [comment]
Any consensus as to where loki is heading? 🤔  We'd prefer a solution based on fluentbit because being non-opinionated usually helps a great deal in case some new or additional log aggregator appears.

**Comment by tomwilkie** [comment]
We've added a fluentd output plugin for Loki (in #210) and are happy to merge / maintain others.

We're going to continue to develop promtail, especially for the Kubernetes use case, as having systematically consistent labels with Prometheus is key to the usability of Loki, and I don't see how we can achieve this with fluentd.  That being said, fluentd will be supported as a first class agent.

**Comment by mrueg** [comment]
There is https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter which enriches logs with kubernetes metadata.

**Comment by redbaron** [comment]
fluent-bit can also do it out of the box. and if loki doesn't find certain labels in the incoming data for it to function, it can always reject malformed input

**Comment by DearMadMan** [comment]
seems fluent-bit not support yet....

**Comment by kfox1111** [comment]
Looking for a volunteer to add the support. :)

**Comment by harobed** [comment]
> seems fluent-bit not support yet....

@DearMadMan https://github.com/cosmo0920/fluent-bit-go-loki ?
