### ISSUE TITLE
Improve documentation around chunk/index schema

### ISSUE THREAD

**Issue by rfratto** [grafana/loki#1851]
The current recommended schema is hidden away at the bottom of [this](https://github.com/grafana/loki/blob/34b3a764c7fd378c1808c3c433738dda3f05f74d/docs/overview/README.md#chunk-store) file. It's hard to find unless you know it's there, but it's also wrong; people should be using `v11` and not the `v10` that's in that file. 

Another place the schema documentation is out of date is our [configuration reference](https://github.com/grafana/loki/tree/master/docs/configuration#schema_config), where it only says to use `v9` or `v10`. 

A few things would make this a lot better:

1. Only ever mention the latest schema version in the documentation, removing all references to older versions in examples. 
2. Provide a version history of schema changes so users know when they would want to upgrade. 
3. Add documentation for how to upgrade to a new schema version. I don't think we document this at all right now.
4. Add a process around updating references to old schema versions when a new one is released.

**Comment by rfratto** [comment]
#1852 removes references to old schema versions but the rest still need to be done (imo).

**Comment by slim-bean** [comment]
Going to close this, it's still an issue and not one we have forgotten about but I don't think it needs an open issue.
