### ISSUE TITLE
Improve documentation with consistent terminology

### ISSUE THREAD

**Issue by slim-bean** [grafana/loki#1855]
As an example someone posted from slack:

>What I tried to ask is if there is more explanation on the limits_config parameters, e.g.
```
# Maximum number of active streams per user, per ingester. 0 to disable.
[max_streams_per_user: <int> | default = 10000]
```
> what is a stream? what is a user?
```
# Per-user ingestion rate limit in sample size per second. Units in MB.
[ingestion_rate_mb: <float> | default = 4]
```
> what is a sample ?
```
# Per-user allowed ingestion burst size (in sample size). Units in MB.
# The burst size refers to the per-distributor local rate limiter even in the
# case of the "global" strategy, and should be set at least to the maximum logs
# size expected in a single push request.
[ingestion_burst_size_mb: <int> | default = 6]
```
> What is an ingestion burst? What is a distributor ? What is a push request? I guess the push request is the batchsize in promtail client_config ?

I think this is mostly valid feedback and criticism of the docs

The entry point to the docs does talk about architecture and describe what a distributor is but I suspect we never clearly define what a `sample` is, I'm not actually sure to be honest.

I also know the rate limiting is not obviously defined, I know the implementation is: https://godoc.org/golang.org/x/time/rate, but I don't think I could easily explain how this works.

**Comment by LinTechSo** [comment]
Hi, any updates ?
