### ISSUE TITLE
Host Helm Chart in a repository

### ISSUE THREAD

**Issue by JamesLaverack** [grafana/loki#186]
Right now if you want to deploy using the Helm chart method you have to clone the Loki repo and access the chart locally.

Helm provides a mechanism to install helm charts without needing to clone their source, called [chart repositories](https://docs.helm.sh/developing_charts/#the-chart-repository-guide). This would allow a user to deploy Loki like this:

```bash
helm repo add grafana <REPO-URL>
helm install grafana/loki --name loki --namespace <YOUR-NAMESPACE>
```

**Comment by kfox1111** [comment]
+1.

Also, you can register the repo with hub.helm.sh so that users can more easily find it.

**Comment by daixiang0** [comment]
@kfox1111 hi, i saw grafana helm repo is stable/grafana, but i do not find any setting in stable part in hub.helm.sh, is somewhere wrong?

**Comment by kfox1111** [comment]
showed up for me: https://hub.helm.sh/charts/stable/grafana

**Comment by kfox1111** [comment]
How do we move this forward?

Is there any ci currently? I helped the ceph-csi folks get into hub.helm.sh recently. Willing to help a bit get this going.

**Comment by monotek** [comment]
The helm guys providing some tooling for this now too: https://github.com/helm/chart-releaser

**Comment by jpds** [comment]
I also require this as I would like to deploy loki with https://github.com/weaveworks/flux/

**Comment by daixiang0** [comment]
@kfox1111 do you have time to do this? Or i feel free to do this.

**Comment by monotek** [comment]
Link for reference: https://github.com/helm/charts/pull/12268

**Comment by kfox1111** [comment]
@daixiang0 go for it. The chart posted to helm/charts looks pretty good. A couple comments on the pr. Thanks for working on it.

**Comment by daixiang0** [comment]
@davkal about this [comment](https://github.com/helm/charts/pull/12268#issuecomment-474382318), is there any progress, willing to do it.

**Comment by davkal** [comment]
We decided to host the chart ourselves. Still deciding next steps...

**Comment by kir4h** [comment]
Voting also for this moving forward. Any help needed?

**Comment by steven-sheehy** [comment]
This issue is fixed by https://github.com/grafana/loki/pull/440. Please close

**Comment by davkal** [comment]
Happy to close it. Thanks for your contribution @steven-sheehy

**Comment by kfox1111** [comment]
One more thing before closing. Can someone submit the repo to hub.helm.sh?

**Comment by steven-sheehy** [comment]
That's already done: https://github.com/helm/hub/pull/64

**Comment by kfox1111** [comment]
Ah. Missed it. Thanks. :)
