### ISSUE TITLE
Not specifying query-frontend downstream URL doesn't log any error

### ISSUE THREAD

**Issue by adityacs** [grafana/loki#1863]
**Describe the bug**
If we don't specify frontend-downstream URL, there is no error logged. When we try to send any request to query-frontend, the request hangs and there is no error returned to client. 

**To Reproduce**
1. Start Loki  with target as `query-fronted` without specifying `frontend.downstream-url`

**Expected behavior**
Error returned to client

/cc @cyriltovena

**Comment by adityacs** [comment]
If there is no downstream URL, cortex by default configures GRPC Roundtrip. I am not sure how that flow works with Cortex. 
Am I missing something?

**Comment by cyriltovena** [comment]
Yes by default it uses GRPC unless you provide that downstream URL. 

For sure we could warn the users if there is no connected GRPC client ready to process item in the frontend queue. But that's more work for Cortex.

**Comment by adityacs** [comment]
Thanks @cyriltovena . Yeah, it would be good to warn user. So, he will be aware of what is not configured

**Comment by owen-d** [comment]
More explicitly, the query frontend operates in one of _two_ fashions:

1) with `frontend.downstream-url`. This just proxies requests over http to said url.
2) without (1). This way it defaults to grpc as a _pull_ service. This requires the as-of-yet undocumented https://github.com/grafana/loki/issues/1867. In this form, the frontend instantiates per-tenant queues that downstream queriers pull queries from via grpc. In your example configuration, it's enqueueing queries, but nothing is dequeueing them :)

**Comment by adityacs** [comment]
I was trying to figure out how GRPC thing works without providing any address to connect to 😉. I couldn't get any thing. 

Thanks @owen-d
