### ISSUE TITLE
Document frontend worker

### ISSUE THREAD

**Issue by owen-d** [grafana/loki#1867]
Trying to answer https://github.com/grafana/loki/issues/1863 I realized we don't have docs relating to the frontend worker (used when we run the query-frontend+queriers in grpc mode)

We should document the frontend worker configs
```
// WorkerConfig is config for a worker.
type WorkerConfig struct {
	Address           string
	Parallelism       int
	DNSLookupDuration time.Duration

	GRPCClientConfig grpcclient.Config `yaml:"grpc_client_config"`
}
```

**Comment by adityacs** [comment]
@owen-d Also, this is little confusing https://github.com/cortexproject/cortex/blob/12b15b9b2ecb36029e8f4330b4e2c01e7f180619/pkg/querier/frontend/frontend.go#L51

In Loki context, we should say it should be downstream querier/Loki URL

**Comment by owen-d** [comment]
haha good point
