### ISSUE TITLE
Pods/Namespace not showing in Loki/Grafana

### ISSUE THREAD

**Issue by Superset1986** [grafana/loki#1877]
**Describe the bug**
When i open Grafana and do a Query with Explorer i don't see all my pods or namespaces.    When i look in the promtail log i see its finding the log for the missing pods but they are not showing up in Loki/grafana. 

**To Reproduce**
Open grafana and do a query for pods with the "app" label
**Expected behavior**
i would expect to see all my pods with the "app" label . i have and identical environment and in this installation i'm able to all my pods when doing a query for "app" 

**Environment:**
Kubernetes (AKS)
Used helm to install with the following kommands 
helm repo add loki https://grafana.github.io/loki/charts
helm repo update
helm upgrade --install loki loki/loki-stack  --namespace monitoring

I have tried helm delete --purge and reinstalling with the same result.  Anybody who can point me in the right direction for troubleshooting this issue?

**Comment by Superset1986** [comment]
Was simply because my pods hadn't had any log events since i deployed Loki.

**Comment by Shubhamxshah** [comment]
this comment helped stop my head from spinning. Tyvm :D
