### ISSUE TITLE
[helm loki/promtail] update of DaemonSet takes a long with a lot of nodes

### ISSUE THREAD

**Issue by stefanandres** [grafana/loki#1878]
**Is your feature request related to a problem? Please describe.**
When deploying a change for the promtail DaemonSet, the configured default is to only rollover one pod at a time. 
This may take 1 minute per pod. When you have a Cluster of more than a few Nodes, this will take an immensive amount of time for simples changes.

Current default:
```yaml
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
```

**Describe the solution you'd like**
Since having a slow rollover does not give you any more availablility, we may configure to allow more parallel rollover.

**Additional context**

I'd suggest to change the [MaxUnavailble](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#max-unavailable) settings in the [UpdateStrategy](https://github.com/grafana/loki/blob/master/production/helm/promtail/templates/daemonset.yaml#L18).

Now we can also discuss a sane default for the helm chart.

1. The option should be configureable
2. What default should be use here? If we continue to use `1` updates are slow, but misconfiguration of the pod would mean that only one logging Pod would be broken and not all of them. If we use something like `100%` options are fast, but when the Pod is misconfigured all logs would be broken.

Let me know what you think of it and I can whip up some PR ;)

**Comment by cyriltovena** [comment]
I think 25% is a sane default. And yes we would love a contribution to improve this.

Thank you :)
