### ISSUE TITLE
Output json logs for loki/promtail

### ISSUE THREAD

**Issue by seankhliao** [grafana/loki#1885]
**Is your feature request related to a problem? Please describe.**
I want loki/promtail to output its own logs in JSON

**Describe the solution you'd like**
config for setting log format

**Describe alternatives you've considered**

**Additional context**
I've had a look at the code and it looks like it would need to be a coordinated change in 
[github.com/weaveworks/common/server](https://github.com/weaveworks/common/blob/master/server/server.go#L32) for the config struct and [github.com/cortexproject/pkg/util](https://github.com/cortexproject/cortex/blob/master/pkg/util/log.go#L41) to actually setup the logger?

**Comment by cyriltovena** [comment]
Yep that's correct, feel free to send us a PR, I don't think that should be too much work, we use gokit logger and it has a json implementation.

**Comment by seankhliao** [comment]
I'm more concerned that it needs changes in exported function signatures (inserting a format arg instead of just a level), at the very least in `NewPrometheusLogger` called by `InitLogger` in cortex 

And possibly `logging.NewGoKit` and `logging.NewLogrus` in weaveworks/common since it wouldn't make sense to have a LogFormat field in the config struct be a noop?

**Comment by cyriltovena** [comment]
I see that you're doing the work on Cortex side awesome ! Thank you ! @gouthamve if you can assist it would be great.

**Comment by slim-bean** [comment]
@kavirajk can you check if this works in latest promtail now? and see if we need to add this to our documentation.
