### ISSUE TITLE
docker plugin: Cleanup stale JSON log files

### ISSUE THREAD

**Issue by ushuz** [grafana/loki#1886]
**Is your feature request related to a problem? Please describe.**
JSON log files created by the plugin for containers are not properly cleaned up after the corresponding containers getting removed or recreated. The leftover would gradually eat up free disk space. By default those files can be found at `/var/lib/docker/plugins/<id>/rootfs/var/log/docker/`.

Look at code, a file gets created in `StartLogging()`:
https://github.com/grafana/loki/blob/87c63855ddf00747adb94f9f828a28fc4f76ad65/cmd/docker-driver/driver.go#L70

but, neglected in `StopLogging()` (`lf.Close()` won't delete the file):
https://github.com/grafana/loki/blob/87c63855ddf00747adb94f9f828a28fc4f76ad65/cmd/docker-driver/driver.go#L100-L109

**Describe the solution you'd like**
Cleanup stale JSON log files properly.

**Describe alternatives you've considered**
Periodically scan and delete closed files from plugin filesystem with crontab or something.

**Comment by owen-d** [comment]
Nice, thanks for the research! Would you be interested in submitting a PR?

**Comment by cyriltovena** [comment]
The line you're showing doesn't create a file. I'm thinking about this. Maybe we could have an option.

Going to try what files are being created first.

**Comment by cyriltovena** [comment]
Also FYI if we get rids of the files you'll never be able to do `docker logs` may be you're fine with this ? 

This why the file is created so you can still see logs by doing `docker logs`.

**Comment by cyriltovena** [comment]
Ok I got a PR almost ready that will solve all of this.

**Comment by ushuz** [comment]
> Also FYI if we get rid of the files you'll never be able to do `docker logs` may be you're fine with this ?
> 
> This why the file is created so you can still see logs by doing `docker logs`.

@cyriltovena I do aware that `docker logs` depends on the underlaying JSON files, but what I'm requesting is "cleanup at `StopLogging()`", so I think `docker logs` would still be functional as long as the container is running, but might be empty for stopped containers though.

`keep-file` in #1906 is what I need. Thank you for the quick response!
