### ISSUE TITLE
Allow separate fields for "short message" and "full message"

### ISSUE THREAD

**Issue by rrajkomar** [grafana/loki#1895]
**Is your feature request related to a problem? Please describe.**
Most of the time, having only the log message does not provide enough information to solve a particular issue.
On the other hand having all the log information dispayed in the line can rapidly clutter the loki UI.
Having two fields (or having a way to split them but using a specific name within the log entry) coud allow having the best of both:

**Describe the solution you'd like**
Take this example :  
Note: I removed some data on purpose

```
{"message":"Exception here","level":300,"level_name":"WARNING","channel":"app","datetime":"2020-04-04 14:57:40","ctxt_exception":"{\"class\":\"Exception\",\"message\":\"Testing exception\",\"code\":0,\"file\":\"[...]\",\"trace\":[...]}"}
```
Having this kind of line in the UI could rapidly clutter the interface.
On the other hand having just `Exception here` while keeping all the other information in the parsed fields table that can be opened would be awesome

**Describe alternatives you've considered**
Using the labels to store of the information. But they're not meant to so.

**Comment by owen-d** [comment]
Hey, thanks for taking the time to think about this & put it into words. From what I can tell, this has two parts:

1) Be able to pass "hints" alongside log lines in returned data (such as, `format=json`)
2) Use (1) in Grafana to present a richer log viewing experience (expandable json, etc).

I can see (1) being a natural followup to the LogQL fields impl. (2) would definitely be on the grafana side. Did I get this right, @rrajkomar? @cyriltovena WDYT?

**Comment by cyriltovena** [comment]
Yeah @owen-d  I think this goes exactly into the LogQL field scope we want to do, being able to select fields that we want to show (remove other), but still being able to get details when we want.

@rrajkomar If you have some time you could review the design doc and let us know if you think this would solve your issue. https://github.com/grafana/loki/pull/1848

**Comment by rrajkomar** [comment]
Hi, the doc seems (unless I didn't get it at all, which is highly likely) more related to searching through the logs rather than pushing logs to loki.

My issue was more related to how very limited the push JSON format is :
Here's an extract from the api doc :
``` 
{
  "streams": [
    {
      "stream": {
        "label": "value"
      },
      "values": [
          [ "<unix epoch in nanoseconds>", "<log line>" ],
          [ "<unix epoch in nanoseconds>", "<log line>" ]
      ]
    }
  ]
}
```
where "log_lines" are displayed as is the UI.

My feature request could simply be summarized into a somewhat more formal structure of the "log_line" values where we could have something like this :
```
{
[...],
'message': 'Just the log message'
[...]
}
```
where message would be the only thing displayed by default. and on a click on the log line the full parsed list of fields would appear as it does now.

Note :  another approach could be on the UI side to be able to select which of the parsed fields should be displayed by default (which is I believe the approach Graylog uses for example)
Maybe this approach would be easier and more adaptable to any form of log format since it relies on the already parsed fields.

**Comment by negbie** [comment]
@rrajkomar to be more specific it's in the gelf specification. Not only related to Graylog.
https://docs.graylog.org/en/3.2/pages/gelf.html

**Comment by cyriltovena** [comment]
if we ever allows this kind of field it would be parsed server side from the log line, I don't think we will support pushing complex object.

**Comment by rrajkomar** [comment]
@cyriltovena As I said, an implementation server side or even UI side is fine.
It is not the way of pushing the log that is problematic, only the display in Grafana UI.

Since all the fields in the log message are parsed anyway (we can see them when expanding a log line in Grafana UI), IMHO I believe it would be user-friendlier to display separate fields (which could be selected, and even have an option for a customisable default parsed fields display) rather than the entire log entries which could rapidly make the UI less readable.
