### ISSUE TITLE
Memory Configurations for Loki

### ISSUE THREAD

**Issue by ahus1** [grafana/loki#191]
I'm looking for documentation how to configure and/or calculate the memory (RAM) used by loki.

**Comment by danieldabate** [comment]
Any information related to this topic would be very useful for us too. We are running Loki and some queries get it OOMKilled. I can just keep giving it more and more RAM, but would like to have more information to take a better decision.

**Comment by agolomoodysaada** [comment]
Experiencing this pain as well. A query shouldn't cause Loki to crash

**Comment by Kuqd** [comment]
Are you still experiencing the same?

**Comment by agolomoodysaada** [comment]
I'm experiencing this with `grafana/loki@sha256:00c8c4047b282b639861c2a1fe4ffda42b0961420b69ad58e620380340037ef`

**Comment by agolomoodysaada** [comment]
I updated to the latest version and still experiencing OOMKilled events

**Comment by agolomoodysaada** [comment]
actually... I'm now seeing `level=warn ts=2019-05-17T14:32:54.082466654Z caller=logging.go:49 traceID=55bd9a8915b11fb6 msg="GET /ready (500) 71.86µs Response: \"Not ready: waiting for 1m0s after startup\\n\" ws: false; Accept-Encoding: gzip; Connection: close; User-Agent: kube-probe/1.11+; "`

**Comment by agolomoodysaada** [comment]
But still OOMKilled happening even after adding memory to 8G

**Comment by cyriltovena** [comment]
You should not need more than 10gib now even if you're using Loki intensively.
