### ISSUE TITLE
Excluding files from directory for promtail/rotating log files

### ISSUE THREAD

**Issue by ahus1** [grafana/loki#192]
Reading the source and the examples I came to the conclusion that promtail looks into __path__ and ready from all files that it finds. Looking at the Docker-Example where it scrapes /var/log, I wonder how to handle rotating log files: 

* is there a way to exclude/include only specific files?
* how will positions work with rotating files? 

Expected behavior: if a file rotates (new file with same old file name) a log tailer should start at the beginning of the new files, and probably read not-yet-pushed data from the old file.

**Comment by slim-bean** [comment]
Between glob support and some changes made to read a file to completion when it is rotated/renamed I believe this case to be covered now.

**Comment by laixintao** [comment]
Hi @slim-bean I have the same concern with @ahus1 

Is the behavior of promtail is like what @ahus1 saied now?

> Expected behavior: if a file rotates (new file with same old file name) a log tailer should start at the beginning of the new files, and probably read not-yet-pushed data from the old file.

For example I have a log named "django.log" and when it reached 200M it will be renamed to "django.log.1" and start a new "django.log", what will happen to promtail?

**Comment by analytically** [comment]
I also wonder this. We run promtail in Nomad.

**Comment by slim-bean** [comment]
We regularly tail rotating log files, this is handled by promtail automatically. Both in the case where the file is renamed and a new file is created as well as the file being truncated

**Comment by pourer** [comment]
In my scenario,  `__path__` congfig as `/usr/local/test/*.log`, and log file named `test.log`.
When the log file `test.log` reached 100M, it will be renamed to `test.20200707-183213.408507.log` and start a new `test.log`.
Now, promtail will start new tailer for `test.20200707-183213.408507.log`, but `test.20200707-183213.408507.log` scraped before it rotated.
Is this not a problem?

**Comment by cyriltovena** [comment]
> I also wonder this. We run promtail in Nomad.

have you thought about running the docker driver in nomad instead ?
