### ISSUE TITLE
Promtail: Allow designating a --client.url as optional

### ISSUE THREAD

**Issue by slim-bean** [grafana/loki#1932]
I thought we had an issue similar to this but didn't see any.  Currently if you specify multiple clients in promtail (which are Loki servers, the terminology here may be a bit confusing), the sending of logs is done in a single thread, synchronously.

This means if a destination Loki is slow to respond, it slows logs sending to any other configure Loki servers.

This may be desirable in some situations if you want to try to guarantee logs are sent to both instances, however in other circumstances it may not be.

Typically if someone wants to send to multiple Loki servers with the best guarantee of getting logs to both without any interference we recommend running two Promtail agents.

There are a few problems and a few solutions in this area that would be nice to improve, one of which is allowing the designation of a client as "optional" or basically make sending a best effort, through the send on a thread, let it do retries, but if don't hold up reading the file and sending other clients.

One perfect use case for this is one we have, where we want to send logs from a cluster to our primary operations Loki, but also to lower level environments to have log volume for testing.

I think too if people start creating shims which implement the Loki write API but send data to other systems, this kind of option would be desirable there as well.

**Comment by adityacs** [comment]
@slim-bean Aren't we already doing this in different go routines?

Each client is run on different thread https://github.com/grafana/loki/blob/master/pkg/promtail/client/client.go#L144. So, even sending logs should happen on different threads.

**Comment by slim-bean** [comment]
It still ends up being single threaded because how the multi-client works, basically a multi-client is just a client that intercepts the Handle call then loops through all the clients and calls Handle.

If you look through everything it ends up being single threaded because all the channels end up blocking waiting for sends, so if one of the clients is slow to send it ends up blocking all the way back up to here:

https://github.com/grafana/loki/blob/f9ff2a4b02832c7495f890abd2d73f4c8d44f1af/pkg/promtail/client/multi.go#L37

**Comment by adityacs** [comment]
Ah! ok. Got your point

**Comment by adityacs** [comment]
@slim-bean We should `keepalive` this
