### ISSUE TITLE
Loki receiving multiple log files instead of just latest from promtail

### ISSUE THREAD

**Issue by daveram** [grafana/loki#1933]
**Describe the bug**
After running promtail for a while against a log directory where we have files created one-per-day, when I run count_over_time queries for the job I still see counts for almost every file, even though only one of them has new entries.  Also worth noting that loki is ingesting well over the size of the log files, almost like it's multiplying the data.  I suspect this is related and possibly the root of the issue where promtail is re-sending old logs

**To Reproduce**
1. Started Loki (v1.3.0) in monolithic mode
2. Started Promtail (v1.3.0) to tail multiple directories as individual jobs
3. Query: `count_over_time({job="httpd_dev_access"}[1m])` - Querying a single job shows multiple time series by filename when only one file is getting new log entries

**Expected behavior**
count_over_time query should only have one time series for the one file that has new log entries in the time range selected.  Also attaching prometheus metrics for loki to show how the traffic is around 250-300MB/sec, whereas the log files are around 2GB/day and much smaller

**Environment:**
 - Infrastructure: bare-metal
 - Deployment tool: ansible

**Screenshots, Promtail config, or terminal output**
![query](https://user-images.githubusercontent.com/8410976/79101016-90326700-7d1c-11ea-8da7-c5249b825a6f.PNG)
[promtail.yml.txt](https://github.com/grafana/loki/files/4468442/promtail.yml.txt)
[sd_httpd_dev.yml.txt](https://github.com/grafana/loki/files/4468444/sd_httpd_dev.yml.txt)
![loki-traffic](https://user-images.githubusercontent.com/8410976/79101182-dd163d80-7d1c-11ea-9775-10f12a2546c2.PNG)

**Comment by slim-bean** [comment]
Hi @daveram could you please include your promtail config and the promtail log output?

Also it would be interesting to see the positions file content.

**Comment by cyriltovena** [comment]
You should use a rate not increase for your metrics. This might also be confusing 250mb/sec is an insane amount for Loki single binary (right ? You run a single replica?), It's probably 5mb/sec.

I'm also curious to see your Loki config.

**Comment by daveram** [comment]
@slim-bean 
Promtail config got nested between the screenshots, putting here for easier viewing.  Also uploaded positions and log files below.  Note I did see errors indicating we have to increase open files limit, but I'm assuming that has nothing to do with this issue unless promtail can't mark a file as being read properly
[promtail.yml.txt](https://github.com/grafana/loki/files/4468442/promtail.yml.txt)
[sd_httpd_dev.yml.txt](https://github.com/grafana/loki/files/4468444/sd_httpd_dev.yml.txt)
[positions.yaml.txt](https://github.com/grafana/loki/files/4470509/positions.yaml.txt)
[promtail_log.zip](https://github.com/grafana/loki/files/4470513/promtail_log.zip)

@cyriltovena 
My mistake should've said 300MB/min in my original post based on increase over 1m, still way higher than what we should be seeing.  Changing it to rate is about 5MB/sec as you noted.  And yes, single binary

**Comment by daveram** [comment]
Should also note there are more static discovery files aside from sd_httpd_dev.yml as noted in the promtail.yml config, but they are all the same format and setup just slightly different labels and paths.  Lemme know if you want all those as well

**Comment by daveram** [comment]
Upped the open files limit and restarted promtail, still showing all the different filenames in the time series during a count_over_time query so don't think it's related

**Comment by daveram** [comment]
Left it alone for a few hours after fixing the open files limit, lo and behold I now only see one time series in the count_over_time query for the latest log file.  Traffic and chunk sizes have gone way down along with queries now becoming nice and quick without the hundreds of series to figure out.  Think this was the source of the problem all along, promtail wasn't able to properly finish reading anything due to open file limits, so it just kept re-reading and re-sending all logs

**Comment by devadded** [comment]
Hi @daveram @cyriltovena @slim-bean!!!
I'm new to using Loki, and I didn't find a lot of documentation about it, could you tell me how I can collect several different servers and show this in graphana?
Because I'm doing this with LocalHost normally, but when I need to add the LOG from other servers, I still don't understand how I do it.

can you help me?

**Comment by cyriltovena** [comment]
You need to install promtail or any other client on each server see https://grafana.com/docs/loki/latest/clients/
