### ISSUE TITLE
Retrieve raw logs easily

### ISSUE THREAD

**Issue by aaronsuns** [grafana/loki#1940]
This issue has been discussed in slack channel, as suggested by Diana Sarlinska I'm writing a feature request. 
Right now the logs are only available in loki UI and with a line limit, default is 1000, when the log file is too large or burst of logs line in short time period, it's hard to analysis in the we UI, browser can stuck if set the line limit too big(>5000 lines).  
So it would be good to have an option that let user easily to export the raw log as text file, with or without time stamps.
There are some existing tools called logcli could do that, but it would be nice loki provide this directly.

**Comment by slim-bean** [comment]
Can you elaborate a little more on your use case?  

I would say Loki currently has this support either via Logcli or directly via the API (querying logs is exactly returning them in plain text)

Can you describe a little better what you mean by export?

**Comment by aaronsuns** [comment]
How about create a button beside the query, which could export the full log based the query.
When I try logcli it does not work directly, maybe mismatch version or something else, didn't dig too much into it.
When I try API, need to configure authentication keys and so on, after the authentication works, I still don't get the api fully working, it return a html page instead of the logs I want.
A simple button on the UI do the export would save many user's effort.

**Comment by danieldabate** [comment]
This issue is related to Grafana. It should be moved to that project.

**Comment by pgassmann** [comment]
@aaronsuns did you find a solution that works for you? I don't find 

@slim-bean The use case is that we would like to filter with context. you can easily process text logs with `grep bla -C 5`or `| grep foo -B 2 -A 20`. The log panel for grafana dashboards very limited features and also the explore is limited to context on click on a single line.

@danieldabate The feature could be implemented in Loki API/LogQL, Grafana then uses that function.

Related question: How can i access the actual log message content text with LogQL? 
` | line_format "{{ .compose_service }} - {{ . }}" `

`{{ . }}`just returns all the labels.

**Comment by aaronsuns** [comment]
The solution is to stopping using Grafana.  :)
