### ISSUE TITLE
Docker logging driver?

### ISSUE THREAD

**Issue by prologic** [grafana/loki#195]
Are there plans to build a [Docker logging driver plugin](https://docs.docker.com/config/containers/logging/plugins/) based on Loki?

**Comment by eeddaann** [comment]
Instead of implementing it from zero, this driver can be used: https://github.com/deep-compute/docker-file-log-driver 
and promtail can be configured to collect the logs from that file

**Comment by lfdominguez** [comment]
I'm coding one for Docker... (and with support for Docker Swarm tags as service name, etc) https://github.com/lfdominguez/docker_log_driver_loki

**Comment by lfdominguez** [comment]
In futher version i will change to use the protobuff protocol, i need get working with json first gg.

**Comment by SvenDowideit** [comment]
for now, i'm using the journald docker daemon log setting, and then grabing those using fluentd which can push to loki

**Comment by nunofernandes** [comment]
It would be awesome if we could send the docker logs to loki directly (without having the logs sent to file and then to loki).

**Comment by lfdominguez** [comment]
> It would be awesome if we could send the docker logs to loki directly (without having the logs sent to file and then to loki).

check
https://github.com/lfdominguez/docker_log_driver_loki

**Comment by y0zg** [comment]
> > It would be awesome if we could send the docker logs to loki directly (without having the logs sent to file and then to loki).
> 
> check
> https://github.com/lfdominguez/docker_log_driver_loki

@lfdominguez 

Thank you, any guide how to start using it? ;)

**Comment by lfdominguez** [comment]
> > > It would be awesome if we could send the docker logs to loki directly (without having the logs sent to file and then to loki).
> > 
> > 
> > check
> > https://github.com/lfdominguez/docker_log_driver_loki
> 
> @lfdominguez
> 
> Thank you, any guide how to start using it? ;)

only use de Makefile and put the options loki-host and loki-port. Soon I will put the configuration on README... sorry

**Comment by TigerC10** [comment]
+1

Need an official Docker Logging Driver to get buy in the enterprise.

**Comment by Kuqd** [comment]
This is totally a legitimate feature, I’m not sure if the docker plugin is solution. May be for swarm users.

For sure, in the meantime I would recommend to use a service discovery compatible with Prometheus service discovery such as consul, very simple to use.

**Comment by TigerC10** [comment]
> This is totally a legitimate feature, I’m not sure if the docker plugin is solution. May be for swarm users.

I disagree, we use Amazon ECS and Fargate and currently configure Docker to send logs through the Splunk logging driver.  We also have some teams using the CloudWatch logging driver.  Because of how easy it is to configure logging drivers, pretty much the only way I will get buy-in to switch to Loki from the enterprise teams logging in this way is if Loki also has a logging driver.

**Comment by nunofernandes** [comment]
Completely agree with @TigerC10 as I do have the same scenario (using cloudwatch logging driver).

**Comment by Kuqd** [comment]
Sounds fair, I'll dig into it.

**Comment by lfdominguez** [comment]
You can help or fork or whatever you want ;) with my [plugin](https://github.com/lfdominguez/docker_log_driver_loki)

**Comment by Kuqd** [comment]
I'll read it for inspiration but I think it's better if this code live in grafana/loki as there is a lot of pkg I could use.

**Comment by Kuqd** [comment]
@TigerC10 if we do release a docker driver it won't be added by default to ecs image. Would you install it yourself or will you wait for the support in the ecs ?

**Comment by nunofernandes** [comment]
@Kuqd  yes.. I do that for other drivers (rexray/ebs and efs). So I would just add an aditional driver there.

**Comment by TigerC10** [comment]
@Kuqd Yes, we maintain our own ECS images for other monitoring and security software, can easily add Loki driver to the images.

**Comment by Kuqd** [comment]
Alright so that also seems fair to add the possibility to parse lines via config file optionally so you can set index log level.

`host` and `container_name` labels will be there by default and you would be able to include anything from docker labels and docker env container runtime via plugin option.

**Comment by Kuqd** [comment]
I'm aiming for this config:

```json
{
  "log-driver": "loki",
  "log-opts": {
    "url": "http://loki/api/prom/push",
// many other tls option.
    "external-labels": "container_name={{.Name}},env=prod",
    "labels": "production_status",
    "env": "os,customer"
  }
}
```

**Comment by lfdominguez** [comment]
> I'm aiming for this config:
> 
> ```json
> {
>   "log-driver": "loki",
>   "log-opts": {
>     "url": "http://loki/api/prom/push",
> // many other tls option.
>     "external-labels": "container_name={{.Name}},env=prod",
>     "labels": "production_status",
>     "env": "os,customer"
>   }
> }
> ```

umm.. i will change the config options of my plugin... now are
`loki-host` & `loki-port`

**Comment by Kuqd** [comment]
how do you usually deal with config file when using docker drivers ? I don't seem to understand how to mount a hostpath in my plugin to add a config.

**Comment by lfdominguez** [comment]
I don't have config files... the config is on docker daemon or used directly on docker command

**Comment by TigerC10** [comment]
In AWS, we use the USERDATA feature of EC2 and/or the Init Scripts in CloudFormation Templates.  See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-init.html

So, on the consumer side of this plug-in, we would install the Loki driver plugin with USERDATA on the instance profile, then we would use the Init Scripts to define the config file(s).

**Comment by lfdominguez** [comment]
With it you can populate the /etc/docker/daemon.json (Debian) with the configuration, and every container use them.

**Comment by Kuqd** [comment]
Thanks everyone, I should release the driver today or tomorrow.

@lfdominguez I've added swarm support like you did but using the `ContainerLabels` property as the extracted data doesn't contains those swarm labels.
