### ISSUE TITLE
[Bug] go get fails with "invalid pseudo-version"

### ISSUE THREAD

**Issue by jpmcb** [grafana/loki#1952]
When attempting to `go get` the loki package, I'm running into "invalid pseudo-version" errors on golang.org/x/net. Here's a fresh example to reproduce:

```
➜ mkdir testing
➜ cd testing
➜ go version
go version go1.14 darwin/amd64
➜ go mod init example.com
go: creating new go.mod: module example.com
➜ go get github.com/grafana/loki@master
go: github.com/grafana/loki master => v1.4.2-0.20200416202212-b5b3e78424e3
go get: github.com/grafana/loki@v1.4.2-0.20200416202212-b5b3e78424e3 requires
	go.etcd.io/etcd@v0.0.0-20190815204525-8f85f0dc2607 requires
	golang.org/x/net@v0.0.0-20190813000000-74dc4d7220e7: invalid pseudo-version: does not match version-control timestamp (2019-08-13T14:13:03Z)
```

It looks like at one point this was a problem with go 1.13 proxying incorrectly:
```
// Override reference causing proxy error.  Otherwise it attempts to download https://proxy.golang.org/golang.org/x/net/@v/v0.0.0-20190813000000-74dc4d7220e7.info
replace golang.org/x/net => golang.org/x/net v0.0.0-20190923162816-aa69164e4478
```

And this appears to be the related issue: https://github.com/golang/go/issues/32805

I'm not sure if this was an issue only with go 1.13, but when attempting to fetch the package directly:
```
➜ go get golang.org/x/net@v0.0.0-20190923162816-aa69164e4478
go: downloading golang.org/x/net v0.0.0-20190923162816-aa69164e4478
```
it is successful.

Here's the resulting go mod:
```
➜ cat go.mod
module example.com

go 1.14

require (
	golang.org/x/net v0.0.0-20190923162816-aa69164e4478 // indirect
	golang.org/x/sys v0.0.0-20200323222414-85ca7c5b95cd // indirect
)
```

I believe the correct syntax for this [as defined in this doc](https://golang.org/doc/go1.13#version-validation) should be to explicitly define the version:
```
// Override reference causing proxy error.  Otherwise it attempts to download https://proxy.golang.org/golang.org/x/net/@v/v0.0.0-20190813000000-74dc4d7220e7.info
replace golang.org/x/net v0.0.0-20190813000000-74dc4d7220e7 => golang.org/x/net v0.0.0-20190923162816-aa69164e4478
```

PR incoming! 🚀

**Comment by cyriltovena** [comment]
Nice work! Thanks a lot for this.

**Comment by jpmcb** [comment]
Hi @cyriltovena @owen-d! 

Unfortunately, after my PR this is still broken :(((

We are still getting this error:
```
go get: github.com/grafana/loki@v1.4.1 requires
        go.etcd.io/etcd@v0.0.0-20190815204525-8f85f0dc2607 requires
        golang.org/x/net@v0.0.0-20190813000000-74dc4d7220e7: invalid pseudo-version: does not match version-control timestamp (2019-08-13T14:13:03Z)
```

I downgrade to `go version 1.13` and did `go clean --modcache` but still having a problem. We also tried this on a few of our team's machines with no success.

I think we have a path forward however, here's our investigation:

* Created a new `go mod init` project and `go mod get github.com/grafana/loki@v1.0.0` is also unsuccessful.
 * This leads us to believe that the etcd module required by `github.com/cortexproject/cortex` is what's causing this issue:
```
➜ go mod why -m go.etcd.io/etcd
# go.etcd.io/etcd
github.com/grafana/loki/pkg/loki
github.com/cortexproject/cortex/pkg/ring/kv
github.com/cortexproject/cortex/pkg/ring/kv/etcd
go.etcd.io/etcd/clientv3
```

Within loki, when attempting to upgrade the etc client:
```
go get -u go.etcd.io/etcd
go: go.etcd.io/etcd upgrade => v3.3.20+incompatible
go: finding module for package github.com/coreos/etcd/etcdmain
go: found github.com/coreos/etcd/etcdmain in github.com/coreos/etcd v3.3.20+incompatible
go: downloading github.com/spf13/cobra v0.0.3
go: finding module for package github.com/coreos/bbolt
go: downloading github.com/inconshreveable/mousetrap v1.0.0
go: found github.com/coreos/bbolt in github.com/coreos/bbolt v1.3.4
go: go.etcd.io/etcd imports
        github.com/coreos/etcd/etcdmain imports
        github.com/coreos/etcd/etcdserver imports
        github.com/coreos/etcd/mvcc/backend imports
        github.com/coreos/bbolt: github.com/coreos/bbolt@v1.3.4: parsing go.mod:
        module declares its path as: go.etcd.io/bbolt
                but was required as: github.com/coreos/bbolt
```
which _appears_ to be an issue with etcd's go mod itself: https://github.com/etcd-io/etcd/issues/11154

**A Path forward**
[This comment in the etc issue](https://github.com/etcd-io/etcd/issues/11154#issuecomment-568587798) has gotten a fair amount of traction and a few referenced prs out there have used it. Pr for this incoming 🔥

**Comment by jpmcb** [comment]
Working now! Thank you for the quick response on this! 🙌
