### ISSUE TITLE
Promtail on Windows writes info messages to stderr stream

### ISSUE THREAD

**Issue by SDedik** [grafana/loki#1969]
**Describe the bug**
Windows version of promtail writes information messages to stderr stream which causes, for instance, PowerShell ISE to treat them as exceptions. Only real error messages should be sent to stderr stream. Information messages and warnings should be sent to stdout.

**To Reproduce**
Run following command from PowerShell ISE
```
& C:\promtail\promtail.exe "-config.file=C:\promtail\config.yaml"

promtail.exe : level=info ts=2020-04-21T13:22:22.315849Z caller=server.go:147 http=[::]:80 grpc=[::]:9095 msg="server listening on addresses"
At line:1 char:1
+ & C:\promtail\promtail.exe "-config.file=C:\promtail\config.yaml"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (level=info ts=2...g on addresses":String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

Split output by streams to separate files to verify which content goes where:
```
& cmd /c "C:\promtail\promtail.exe -config.file=C:\promtail\config.yaml 2> C:\log\sterr.txt 1> C:\log\stdout.txt"
```
`stdout.txt` file is empty. All messages has been written to `stderr.txt` file.

**Expected behavior**
Only real error messages should be sent to stderr stream. Information messages and warnings should be sent to stdout.

**Environment:**
C:\promtail\promtail.exe -version
promtail, version 1.4.1 (branch: HEAD, revision: 2445ccd2)
  build user:       root@bb5e00b6b7f4
  build date:       2020-04-06T20:29:26Z
  go version:       go1.13.4

**Comment by slim-bean** [comment]
This change was intentional in #1180 for an issue described in #810 

Can you run promtail and redirect stderr to stdout? `2>&1` ?

**Comment by SDedik** [comment]
Of course I can, but the whole reason of bringing this up is to fix broken behavior.
Now I understand that you did it for a reason to fix one case, but IMO, you overdone it creating issues with other cases.
Constantly redirecting streams cause it's own inconveniences starting from: not every form of executable invocation allow for stream to be redirected: powrshell call operator (&), WMI Win32_Process Create method, other examples. And down to: wrapping direct executable invocation into some shell gets really complicated really fast especially if one have to deal with quotes and double quotes. Consider chain of wrappers and transformation when I need to launch it from, say, Jenkins pipeline: Jenkinsfine 'powershell' step -> CPS transformation -> Passed to Jenkins Java agent -> Into Jenkins runtime-generated PowerShell wrapper -> Real invocation. Handling quotes and double quotes in this chain sometimes really hard and if it can be avoided, it better be avoided.

Besides, in general, don't you agree that sending information messages like `level=info ts=2020-04-21T13:22:22.315849Z caller=server.go:147 http=[::]:80 grpc=[::]:9095 msg="server listening on addresses"` to error stream is plain wrong?

**Comment by cyriltovena** [comment]
The change mentioned was actually only for kubernetes logs when erroring.

Not sure why promtail logs to stderr, I’ll take a look.

**Comment by cyriltovena** [comment]
Ok so we're using cortex.

And the logger looks like this.

```golang
// NewPrometheusLogger creates a new instance of PrometheusLogger which exposes
// Prometheus counters for various log levels.
func NewPrometheusLogger(l logging.Level) (log.Logger, error) {
	logger := log.NewLogfmtLogger(log.NewSyncWriter(os.Stderr))
	logger = level.NewFilter(logger, l.Gokit)

	// Initialise counters for all supported levels:
	for _, level := range supportedLevels {
		logMessages.WithLabelValues(level.String())
	}

	logger = &PrometheusLogger{
		logger: logger,
	}

	// return a Logger without caller information, shouldn't use directly
	logger = log.With(logger, "ts", log.DefaultTimestampUTC)
	return logger, nil
}
```

I see 3 options:
- We make the output configurable [stdout|stderr] (copy cortex code)
- We change it to stdout, currently everything is stderr
- We don't change anything and let's user redirect.

/cc @slim-bean @owen-d

**Comment by cyriltovena** [comment]
IMO I think we should change this. @slim-bean let me know ! I don't think that will cause any issue.

**Comment by rafaribe** [comment]
Has this been addressed in any way since June?
