### ISSUE TITLE
trailing / cause logcli tail fail

### ISSUE THREAD

**Issue by chinglinwen** [grafana/loki#1985]
**Describe the bug**

```
export LOKI_ADDR=http://10.105.217.89:3100/

[root@nt9 ~]# logcli query --exclude-label=filename --exclude-label=instance --limit=100  '{namespace="openstack", component="compute"}' -t
ws://10.105.217.89:3100//loki/api/v1/tail?query=%7Bnamespace%3D%22openstack%22%2C+component%3D%22compute%22%7D&delay_for=0&limit=100&start=1587891554713983957
Tailing logs failed: Error response from server:  (websocket: bad handshake)
```
It got us hours to find out it.

logcli should be provide helpful error, Create this issue as this may help others.

I don't find the version flag, so I don't know the version. I guess it's about the latest version.

**Comment by slim-bean** [comment]
Hey @chinglinwen trying to better understand your issue?  Did you figure out what was causing the problem?

**Comment by chinglinwen** [comment]
LOKI_ADDR can't have trailing slash after addr:port, when remove that, it works fine. @slim-bean 

Good: `export LOKI_ADDR=http://10.105.217.89:3100`

Bad: `export LOKI_ADDR=http://10.105.217.89:3100/`
