### ISSUE TITLE
Proposal: Loki plugin development 

### ISSUE THREAD

**Issue by adityacs** [grafana/loki#1989]
### Loki client 
This might be already discussed. However, still wanted to bring this topic for discussion. 

With the expanding plugin support for Loki(fluentd, fluentbit, yet to come logstash and logback), I think it would be better if we can develop Loki client in commonly used programming languages like Go, Java, Ruby etc... 

There are n number of tools out there and it would be difficult to provide plugin support for each tool. Most of the coding related to concurrency, adding logs to batch and pushing to Loki using JSON or Protobuf remains the same for all plugins. So, if we can develop clients in popular languages which takes care of these common things, users can develop their own plugin and right minimal code for only converting the events/logs to Loki format. May be if there are lot of requests from the community for a specific plugin we can later develop one or merge a plugin already developed by someone.

This one is written in Rust https://github.com/timberio/vector/blob/master/src/sinks/loki.rs

I know that developing and maintaining client code in many languages is not an easy task. However, this avoids writing boilerplate code and sets a standard for sending logs to Loki. 

### Move plugins under a single folder
Should we move all the plugins under a common folder say `plugins`. Currently `fluentbit` is under `cmd` and `fluentd` is in root. May be can place all plugins under a single directory called `plugins`. Nothing important just for better organization. 

@cyriltovena  @slim-bean thoughts?

**Comment by cyriltovena** [comment]
I'm in to reorganize things with regards to client/plugin.

I'm also in for creating clients in many different languages to ease adoption.

**Comment by adityacs** [comment]
@cyriltovena For restructuring the plugin directory I will create a separate PR.

Regarding `creating clients in many different languages` , let me know how do you want to take this forward

**Comment by slim-bean** [comment]
I'm not sure we want this closed but I didn't have a chance to catch up with it yet so reopening

**Comment by adityacs** [comment]
@slim-bean Supporting multiple clients in different languages would be a good addition. We need some plan for this. However, I haven't seen any request from the community. So, not sure if we require this

**Comment by slim-bean** [comment]
The scope of this is a little generic, but I do think we should solve making the Go client we have built easier to consume in other projects (not have to vendor the entire Loki repo)
