### ISSUE TITLE
Switch to disable promtail http/grpc servers, and document behaviour for port = 0

### ISSUE THREAD

**Issue by candlerb** [grafana/loki#1991]
**Is your feature request related to a problem? Please describe.**
By default, promtail listens on http and grpc ports.  You may not want these servers to be active or accessible.

The example promtail configurations [here](https://github.com/grafana/loki/blob/master/docs/clients/promtail/configuration.md#example-static-config) and [here](https://github.com/grafana/loki/blob/master/cmd/promtail/promtail-local-config.yaml) show

```
  grpc_listen_port: 0
```

Users might expect this to mean "disable grpc server".  Actually what happens is that the grpc server binds to a random port.

I cannot see that this is a useful behaviour.  It's not secure (since anyone can find it using nmap).

**Describe the solution you'd like**
Implement the ability to *disable* http server and grpc server, e.g. by setting the port to zero as per example configs, or by having a separate flag.

**Describe alternatives you've considered**
If this isn't implemented, then at least document [here](https://github.com/grafana/loki/blob/master/docs/clients/promtail/configuration.md#server_config) the current behaviour:

```
# HTTP server listen port (0 means random port)
[http_listen_port: <int> | default = 80]

# gRPC server listen host
[grpc_listen_address: <string>]

# gRPC server listen port (0 means random port)
[grpc_listen_port: <int> | default = 9095]
```

Also change `grpc_listen_port: 0` to `grpc_listen_port: 9095` in all the sample configs (since the `0` example is not useful, but people are likely to copy it)

**Additional context**
Workaround is to bind servers to 127.0.0.1 and/or use iptables to block traffic.

**Comment by Dhana-Krishnasamy** [comment]
Just want to mention that, 
We have a security constraint that we cannot have unsecure open ports in our systems. To scrap the log files and send them to loki, we dont need a http interface anyway.

Proposed solution:
Provide a flag to turn off the http server. Just like how Fluent Bit [does](https://fluentbit.io/documentation/0.13/configuration/file.html#config_section)

Even if the listen address is loopback address, it still exposes us to Elevation of rights attack

**Comment by cyriltovena** [comment]
@Dhana-Krishnasamy The http server is required for healtchecking, don't you need it too ?

**Comment by Dhana-Krishnasamy** [comment]
> @Dhana-Krishnasamy The http server is required for healtchecking, don't you need it too ?

Good question, I think it would be nice if promtail could post the health info as well like the log it scraps. Unsecure port is a no-go for us.

**Comment by mm2175** [comment]
How to disable grpc server only? Our use cases want to disable grpc server and keeps http server.

**Comment by sjonpaulbrown** [comment]
> How to disable grpc server only? Our use cases want to disable grpc server and keeps http server.

For those who find their way here from Google, the `disable` flag was added to the [server config ](https://github.com/grafana/loki/commit/34f9c601c9761a5d2e3b0702d00029421e7b2ad2) as part of the [following PR](https://github.com/grafana/loki/commit/34f9c601c9761a5d2e3b0702d00029421e7b2ad2). It defaults to `false`.
