### ISSUE TITLE
Request: Provide an option to disable http server

### ISSUE THREAD

**Issue by Dhana-Krishnasamy** [grafana/loki#1992]
We have a security constraint that we cannot have unsecure open ports in our systems. To scrap the log files and send them to loki, we dont need a http interface anyway. 

Proposed solution:
Provide a flag to turn off the http server. Just like how Fluent Bit [does](https://fluentbit.io/documentation/0.13/configuration/file.html#config_section) 

Even if the listen address is loopback address, it  still exposes us to Elevation of rights attack

**Comment by hhromic** [comment]
Looks exactly like the request in #1991  👍

**Comment by Dhana-Krishnasamy** [comment]
> Looks exactly like the request in #1991 👍

similar, but that one could get closed as it wants better documentation. which I think is already there.

**Comment by hhromic** [comment]
The other issue is explicitly requesting a feature to disable the server:

> Describe the solution you'd like
> Implement the ability to disable http server and grpc server, by setting the port to zero.

In *addition* to better documentation.
