### ISSUE TITLE
docker log difference

### ISSUE THREAD

**Issue by rafipiccolo** [grafana/loki#1994]
**Describe the bug**
When i activate the driver it works but "docker logs" doesn't report the timestamp in the same format as before. Causing bugs in other apps relying on it.

**To Reproduce**
follow the readme of this repo. I did this :
```
    #> docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions

    #> emacs /etc/docker/daemon.json
    {
        "debug" : true,
        "log-driver": "loki",
        "log-opts": {
            "loki-url": "http://localhost:3100/loki/api/v1/push",
            "loki-batch-size": "10"
        }
    }    
```

and then reboot docker

and they play with the "docker logs" command

**Expected behavior**
the timestamp should be in this format : (utc)
2020-04-27T12:40:13.867149140Z 
and not : 
2020-04-27T14:40:13.867149140+02:00

i know it means exactly the same, but some projects rely on this format to work.

**Environment:**
French server with ubuntu + docker + docker compose

**Screenshots, Promtail config, or terminal output**
default install of docker
```#> docker logs -t xxxx
2020-04-27T12:40:13.867149140Z Mon Apr 27 12:40:13 UTC 2020
...
```

with loki's driver :
```#> docker logs -t xxxx
2020-04-27T14:40:13.867149140+02:00 Mon Apr 27 12:40:13 UTC 2020
...
```

**Comment by cyriltovena** [comment]
When the container is started you should be able to find the file (/var/log/docker/containerid/...) where the logs is read from using the docker driver. Can you check if the file is also in this format e.g with the tz.

**Comment by rafipiccolo** [comment]
im in ubuntu 18.04
all default install
This folder doesn't exist : /var/log/docker

Before installing the driver logs are here :
`/var/lib/docker/containers/ed1f795397c34a02d562fda791db4d106baa92c6b85e478fd08c24a87785c077/ed1f795397c34a02d562fda791db4d106baa92c6b85e478fd08c24a87785c077-json.log`

after installing and rebooting everything, logs are not written, but the container folder exist
```
#> ls /var/lib/docker/containers/912b87bccb3822aaf91c817d28f7305769b534176e8d7818ff86ccfaadc27937/
checkpoints
config.v2.json
hostconfig.json
hostname
hosts
mounts
resolv.conf
resolv.conf.hash
```

**Comment by cyriltovena** [comment]
`docker logs` is achieved using a local json log file. The file is deleted when the container is stopped. I'm curious to see how the date is in this file. see https://github.com/grafana/loki/blob/cdbbec329b385cba560a3624653fbf982e5d4821/cmd/docker-driver/driver.go#L75

**Comment by rafipiccolo** [comment]
I dont know why would loki try to write there when the default config of
docker says logs are usually stored here
/var/log/docker/containerid/containerid.json
I don't speak "go" :) but i guess from the source that the folder
/var/log/docker/xxx is normally getting created if it doesn't exists.
Correct ?

From my side : the container is up. But as I stated the folder
/var/log/docker doesn't exist. I didn't delete it. Should I create it ?
With which rights ?

I read that for ubuntu i can type this to see docker daemon logs :
journalctl -u docker.service
I setted debug:true in deamon.json
I see no warnings/errors.
Do you have some advice ?

when i inspect the running container i can see that LogPath is empty. Is
that normal ?

    docker inspect --format='{{.LogPath}}' d0efd29307c5

thank you for your help.


Le lun. 27 avr. 2020 à 23:57, Cyril Tovena <notifications@github.com> a
écrit :

**Comment by cyriltovena** [comment]
If the logpath is empty then it will default to the folder I told you. It will create the folder if it doesn’t exist.

**Comment by cyriltovena** [comment]
You would see an error in the deamon log on case of failure. Make sure you’re pulling the latest driver.

**Comment by cyriltovena** [comment]
I wasn't able to help you much here, let me know if you still need help, pretty sure we can fix that. I tried to get more intel on the problem but didn't work out.
