### ISSUE TITLE
Docker Driver Pipeline Extracted Map Issue

### ISSUE THREAD

**Issue by delta50** [grafana/loki#1997]
**Describe the bug**
According to the documentation, you should be able to use regex stages to add key-value pairs to the extracted map, and then reference them in a template stage, however this was not working for me. I was able to reference a key in the map in a label stage, but not a template stage.

**To Reproduce**
I am running a docker container with the loki logging driver version 1.3.0 and when I use the following pipeline I nothing is output. 
```pipeline_stages:
  - docker: {}
  - match:
      selector: '{container_name=~".*"} |~ "^\\| .*"'
      action: keep
      stages:
        - regex:
            expression: "^\\| (?P<timestamp>.*?) \\|"
        - regex:
            expression: "^\\| .*? \\| (?P<level>.*?) \\|"
        - regex:
            expression: "^\\| .*? (?P<message>\\| .*?)$"
        - template:
            source: output_log
            template: '{{ .level }} {{ .message  }}'
        - timestamp:
            source: timestamp
            format: RFC1123
        - labels:
            level:
  - match:
      selector: '{container_name=~".*"} !~ "^\\| .*"'
      action: drop
  - output:
      source: output_log
```

I tried a few different configurations but nothing seems to work. Using one of the keys as a source does find the key, however it is unable to reference any other keys. For example the following change just prints the message:
```       - template:
            source: message
            template: '{{ .level }} {{ .Value  }}'
```
**Expected behavior**
The documentation leads me to believe that I should be able to use regex stages to build up the extracted map, and then combine them later in a single template stage for output.

**Environment:**
I am running docker containers on an ec2 using the loki-docker driver and the above pipeline configuration. I installed the pipeline configuration using the steps outlined here: [https://github.com/grafana/loki/pull/1555](https://github.com/grafana/loki/pull/1555)

**Comment by adityacs** [comment]
Hi @delta50 Support for entire extracted map to be available for template was added in `1.4` release. If you want this `'{{ .level }} {{ .Value  }}'`or this `'{{ .level }} {{ .message  }}'` to work, you have to upgrade to 1.4
