### ISSUE TITLE
can not get log on loki server with loki-shipper by Lambad function

### ISSUE THREAD

**Issue by kush2100** [grafana/loki#2002]
i have try to connect Lambda function with Loki for cloudwatch log push on loki.
As i can see on Lambda function CWlog, send CWlogs push to loki but i didn't find any log on loki server.
Lambda log from CW:
START RequestId: e2a48999-73cf-4d4d-bd6b-261fa7fa7548 Version: $LATEST

{'stream': [{'label': '{logGroup="web"}', 'label_values': [{'timestamp': '2020-04-28T04:40:54', 'line': '10.0.10.122 - [28/Apr/2020:04:40:54 +0000] "GET / HTTP/1.1" 301 232 "-" "ELB-HealthChecker/2.0"'}]}]}

http://172.31.37.222:3100/loki/api/v1/push

/var/runtime/botocore/vendored/requests/api.py:64: DeprecationWarning: You are using the post() function from 'botocore.vendored.requests'.  This dependency was removed from Botocore and will be removed from Lambda after 2021/01/30. https://aws.amazon.com/blogs/developer/removing-the-vendored-version-of-requests-from-botocore/. Install the requests package, 'import requests' directly, and use the requests.post() function instead.

DeprecationWarning

END RequestId: e2a48999-73cf-4d4d-bd6b-261fa7fa7548

REPORT RequestId: e2a48999-73cf-4d4d-bd6b-261fa7fa7548

**Comment by cyriltovena** [comment]
Not sure what tool you are using but the request body seems to not fit the current API.

**Comment by kush2100** [comment]
Is there any option for cloudwatch log push to grafana Loki?

**Comment by kush2100** [comment]
Is there any way to push cloudwatch log in Grafana Loki ?

**Comment by cyriltovena** [comment]
We have a PR open and most likely docs to follow.
