### ISSUE TITLE
Outdated container on Dockerhub

### ISSUE THREAD

**Issue by dginther** [grafana/loki#2005]
**Describe the bug**
https://hub.docker.com/r/grafana/fluent-plugin-grafana-loki appears to be out of date, having last been updated 9 months ago.
Not a huge deal but it does seem that the versions and features are a bit out of date and not everything functions as expected. In particular, the container uses a deprecated api/prom/push path by default.
I suspect the version of Fluentd that this is using is out of date, as some built-in plugins that I expected were not present either.

If a new container could be built and pushed, that would be excellent.

**To Reproduce**
1. docker pull grafana/fluent-plugin-grafana-loki:latest
2. Configure container to output to http://localhost:3100/loki/api/v1/push

**Expected behavior**
Logs would be pushed to the above address. Instead, logs are pushed to: http://localhost:3100/loki/api/v1/push/api/prom/push

**Environment:**
 - Infrastructure: vagrant
 - Deployment tool: vagrant

**Screenshots, Promtail config, or terminal output**
N/A

**Comment by nawabb** [comment]
There does seem to be a different image at https://hub.docker.com/r/grafana/fluent-plugin-loki/ but the Loki documentation does not seem to be update. 

I did not get it though as I am having another issue with Loki v1.4.1 with 404 Page Not found using Loki's Docker image. 

docker run -p 3100:3100  grafana/loki:1.4.1 

When I go to http://localhost:3100/ or http://localhost:3100/health I get error 404 page not found
But localhost:3100/ready says Ready

**Comment by cyriltovena** [comment]
Loki should be added as a datasource to grafana

**Comment by nawabb** [comment]
Thanks @cyriltovena However:

* I tried using Grafana connected to Loki. I still see http://localhost:3100/health return "404 page not found" where-in health should say OK or something of the sorts. May be the docker image build has some issues?

* Documentation links to https://hub.docker.com/r/grafana/fluent-plugin-grafana-loki which should be updated to https://hub.docker.com/r/grafana/fluent-plugin-loki/  (this is outdated https://github.com/grafana/loki/blob/master/docs/clients/fluentd/README.md)

**Comment by cyriltovena** [comment]
Yes I would love help to solve those documentation issue !

use this one for readiness: ` http://localhost:3100/ready` If you want to query either use Loki as datasource in Grafana or LogCLI.
