### ISSUE TITLE
Loki Grafana unable to display logs

### ISSUE THREAD

**Issue by shkmaaz11** [grafana/loki#2008]
**Describe the bug**
Unable to visualize the logs in grafana explorer
**To Reproduce**
1. I have cloned the https://github.com/grafana/loki and started conatiners using docker-compose.
2.All the containers are up and running.
3.In Grafana explorer ,I added loki datasource but I am unable to see the promtail logs .

**Expected behavior**
I should be able to see promtail logs in grafana explorer
**Environment:**
![image](https://user-images.githubusercontent.com/14906278/80599944-4f8b5b00-8a49-11ea-9854-8e310de03eb9.png)

 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by adityacs** [comment]
@shkmaaz11 Kindly check the logs of `promtail` container. See if it's able to connect to `loki` container and also check if promtail is able to read the logs which it is intended to.

**Comment by abhi0977** [comment]
same issue with me.
I tried `clone loki` -> `cd production` ->` docker-compose up`
and it gives the same result (above screenshot).

**Comment by abhi0977** [comment]
@shkmaaz11 
try this.
bash into promtail container.

- cd /var/log
- and create any log file with .log extension
- add few logs 
- refresh your grafana & yo

you should see that log file.

**Comment by shkmaaz11** [comment]
> @shkmaaz11 Kindly check the logs of `promtail` container. See if it's able to connect to `loki` container and also check if promtail is able to read the logs which it is intended to.

Promatil is connected to Loki but No,it doesn't read the logs.

**Comment by shkmaaz11** [comment]
> @shkmaaz11
> try this.
> bash into promtail container.
> 
> * cd /var/log
> * and create any log file with .log extension
> * add few logs
> * refresh your grafana & yo
> 
> you should see that log file.

Thanks @abhi0977 ,But this is a dirty fix.I already did that.I want promtail to connect to my logs once it has started  up.

**Comment by abhi0977** [comment]
> > @shkmaaz11
> > try this.
> > bash into promtail container.
> > 
> > * cd /var/log
> > * and create any log file with .log extension
> > * add few logs
> > * refresh your grafana & yo
> > 
> > you should see that log file.
> 
> Thanks @abhi0977 ,But this is a dirty fix.I already did that.I want promtail to connect to my logs once it has started up.

@shkmaaz11 
this is just to confirm if your loki and promtail is configured correctly.
do you see any .log extension file in /var/log (inside promtail container)?
