### ISSUE TITLE
"\." -> "invalid char escape"

### ISSUE THREAD

**Issue by Dieterbe** [grafana/loki#2016]
**Describe the bug**

A clause like `|~ "[0-9]*s\" orgID"` works fine. note how I'm escaping like `\"` to match `"`. This is as expected
However when I update the clause to this:
```
|~ "\.[0-9]*s\" orgID"
```
E.g. I merely add `\.` to match a literal `.`
It no longer works. I get the error `parse error at line 1, col 98: invalid char escape`
this is in Grafana v7.1.0-b8976df5pre (55ac97dccc) Explore mode, querying Loki-ops

**Comment by rbudiharso** [comment]
A pattern like `{container_name="app"} |~ "\s4[00-99]{2}\s"` also results in the same error. In this case I want to match HTTP status code like 400 or 401 (its 3 digit with single space around it).

**Comment by cyriltovena** [comment]
`{job="default/prometheus"} |~ "\\s4[00-99]{2}\\s"` This works.

@Dieterbe `|~ "\\.[0-9]*s\" orgID"` this works too. 

I've open an issue to improve this see https://github.com/grafana/loki/issues/2061
