### ISSUE TITLE
fluent-plugin-grafana-loki ARM64 go exec error

### ISSUE THREAD

**Issue by Shikachuu** [grafana/loki#2037]
**Describe the bug**
According to the Docker Hub page there is no ARM64 arch image currently for **fluent-plugin-grafana-loki**, but the parent image currently have support for that arch, yet the Loki build script based on another tag which does not.

If you try to run the x86_64, you will get an error from 
`standard_init_linux.go`: `211: exec user process caused "exec format error"`
and somehow I am not at all surprised.

**To Reproduce**
1. Started Loki via Docker-Compose, the version basicly don't mind because you will not able to use it anyways.
2. Started fluent-plugin-grafana-loki(sha256:ace38894ce845734baec6322c307fe8596c965aa9c0411f3328c5cff822523b1) container from the same Docker-Compose script which failed immediately the error message: `standard_init_linux.go:
211: exec user process caused "exec format error"`, then the container quits with exit code 1

**Expected behavior**
The container should boot up and load the config files etc.

**Environment:**
 - Infrastructure: 
    - Docker 19.03.8 (afacb8b)
    - Raspberry Pi 3B, Raspbian Buster
    - Kernel  4.19
 - Deployment tool: Docker-Compose

**Screenshots, Promtail config, or terminal output**
```bash
fluentd       | standard_init_linux.go: 211: exec user process caused "exec format error"
teststack_fluentd exited with code 1
```

**Comment by cyriltovena** [comment]
The official repo is now https://hub.docker.com/r/grafana/fluent-plugin-loki/tags and we don't support yet ARM.

**Comment by Shikachuu** [comment]
@cyriltovena thanks, "yet" means is it planned?
Does the actual plugin have some non ARM compatible dependency?

**Comment by cyriltovena** [comment]
It should compile for ARM, but promtail does fantastic job on ARM too.
