### ISSUE TITLE
Question: Loki and SIEM

### ISSUE THREAD

**Issue by PraserX** [grafana/loki#2047]
Hi,

I have a question about SIEM. Is there any way how to send logs from Loki to some SIEM solution? I understand Loki's purpose but if we have centralized log management, it would be great to send logs from Loki to SIEM, because we already collect logs from many sources, and we have them at one place.

I understand that we can send logs by two different collectors. By one to Loki and by another one to some SIEM. But much conceptual solution is the that one, where we have one collector and one centralized log management with some forwarder for SIEM.

So is there any way how to forward logs from Loki to SIEM? Or are there any future plans for that? Please let me know if there is some solution.

Thank you!

P.S.: I send question to lokiproject@googlegroups.com but it seems that the e-mail address does not exist.

**Comment by cyriltovena** [comment]
We’re thinking about doing remote write for sure but the API will be the same as the push API and  would  probably not support SIEM.
 
Sorry seems like you would have to build a this on your own.

**Comment by georgelza** [comment]
a solution could be to create a data pipeline, use, the beats framework to ingest the data, publishing it to kafka from where it is then stored in Loki via a Kafka sink connector into Loki, use the same Kafka stream to forward/sink data into your SIEM solution.
thinking out loud...
