### ISSUE TITLE
[Promtail] Issue with regex pipeline_stage when using syslog as input

### ISSUE THREAD

**Issue by MartinHerren** [grafana/loki#2052]
**Describe the bug**
We started successfully using promtail/loki/grafana to handle logs. Our application is configured to log into rsyslog and rsyslog is configured to log into an application specific file.

Promtail was configured to scrape this file and logs were processed through some pipeline_stages that added source timestamp and some labels according to some regex and everything works fine.

Now we changed to forward rsyslog as described in https://github.com/grafana/loki/blob/master/docs/clients/promtail/scraping.md#rsyslog-output-configuration directly to promtail instead of writing a log file and reading it back live.

The syslog connection works fine and the logs are accessible in loki/grafana. The thing that don't work anymore is all the pipeline_stages that added some labels. The regex stage seems to see an 'empty log line'.

**To Reproduce**
We use the latest grafana/promtail:latest docker container (re-pulled today).

A sample config snipped with an ugly attempt to even get the whole log line into a label:

    scrape_configs:
    - job_name: erxlogs
    
      pipeline_stages:
      - regex:
          expression: '(?P<all>.*?)'
      - labels:
              all:
    
      syslog:
          listen_address: 0.0.0.0:1514
          idle_timeout: 60s
          label_structured_data: no
          labels:
            job: erx
            robot: ErxBot-100
            role: slave
    
      relabel_configs:
        - source_labels: ['__syslog_message_hostname']
          target_label: 'host'
        - source_labels: ['__syslog_message_app_name']
          target_label: 'app'

The 'all' label is effectively added to the log line but is empty. Also tried to set label_structured_data to yes but nothing changes. Maybe a specific 'source' must be set for regex but nothing found in the documentation.

**Expected behavior**
I'd expect the regex pipeline stage to see the (same) log line whether it comes from a file or syslog.

**Environment:**
latest grafana/promtail:latest docker container

**Screenshots, Promtail config, or terminal output**
Here we can see the labels from syslog (job, robot & role) as well as from relabel_config (app & host) are correctly added. Also the 'all' label from the pipeline_stages is added but empty. When scraping from file we can easily parse all fields from the log line into labels using regex/timestamp/labels stages.

![Screenshot from 2020-05-06 14-42-09](https://user-images.githubusercontent.com/2501617/81178152-0f2b6000-8fa8-11ea-978c-93815c9837b9.png)

**Comment by MartinHerren** [comment]
Sorry for the noise, it seems that the issue is that with files it works with a regex expression like "^your_regex$" but for syslog the start and end of line must be left out "your_regex".

**Comment by cyriltovena** [comment]
Nice I’m glad you worked it out. By the way  you can use promtail dry-run and —stdin to try your config also activating debug log usually give more help for this too.
