### ISSUE TITLE
Regexp literal escaping

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#2061]
**Is your feature request related to a problem? Please describe.**

For filter expression and soon to come extract expression, regexp can be difficult to write. Because of the quoted string `{app="foo"} |= "\\w+"`  the normal string escape rules (preceding special characters with \ when included in a string) are necessary. This causes regular expression to be converted.

**Describe the solution you'd like**
Javascript has 2 ways of declaring regexp see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp

> The literal notation's parameters are enclosed between slashes and do not use quotation marks.
The constructor function's parameters are not enclosed between slashes but do use quotation marks.

Example:

```
let re = /\w+/
let re = new RegExp('\\w+')
```
As you can see the first one doesn't need escape.

So my suggestion is to support the two syntax:

- `{app="foo"} |= "\\w+"`
- `{app="foo"} |= /\w+/`

**Describe alternatives you've considered**
Do nothing and live with it, personally sometimes it a pain to prepare a regex in an online editor and then have to fiddle with it to make sure everything is escaped correctly.

**Additional context**
Here is a example that was difficult to build for this reason:
![image](https://user-images.githubusercontent.com/1053421/81574831-4cab3700-9374-11ea-8ad0-f1adae54e9a1.png)

/cc @owen-d @slim-bean if we have consensus I could work on that.

**Comment by owen-d** [comment]
lgtm - go for it!

**Comment by slim-bean** [comment]
love it!

**Comment by cyriltovena** [comment]
I don't think we can support this with the current lexer. We might need to build our own.

/cc @owen-d

**Comment by cyriltovena** [comment]
Fixed by #2095
