### ISSUE TITLE
Weird result using operators

### ISSUE THREAD

**Issue by Mortega5** [grafana/loki#2062]
**Describe the bug**
I'm using the substract operation to know the remaining calls in the system using logs but it's something weird.

![image](https://user-images.githubusercontent.com/8302870/81575896-daece080-93a7-11ea-9c04-075813f58028.png)

As you can see in the picture, the remaining calls in the system is 0 but the total open calls is 3 and the total closed calls is 2. 

I'm using the following queries using promQL api:

* Open calls: `sum by (id) (count_over_time( ( {nodeType="AP"} |~ "Open session")[$__interval]))`
* Closed calls: `sum by (id) (count_over_time(({nodeType="AP"} |~ "Closed session")[$__interval]))`
* Remaining calls: `sum by (id) (count_over_time( ( {nodeType="AP"} |~ "Open session")[$__interval])) - sum by (id) (count_over_time( ( {nodeType="AP"} |~ "Closed session")[$__interval]))`

If I change the range, it works sometimes

** last 6 hours **
![image](https://user-images.githubusercontent.com/8302870/81575980-f8ba4580-93a7-11ea-9087-2fbdd7d988cd.png)

** last 7 days ** (works)
![image](https://user-images.githubusercontent.com/8302870/81576078-14255080-93a8-11ea-90bb-09af0896d3d2.png)

Am I doing something wrong?

I'm using a singlestat with the total value
![image](https://user-images.githubusercontent.com/8302870/81576293-5ea6cd00-93a8-11ea-9d9a-961608746a33.png)

**To Reproduce**
I'm not sure how reproduce it. I have recorded some logs and I have queried them using the previous queries.

**Expected behavior**
The difference between both queries should be correct (1 in this case)

**Environment:**
 - Infrastructure: kubernetes 1.15.11-eks
 - loki image: grafana/loki:1.4.1
 - grafana image: grafana/grafana:6.6.2
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**

Queries made by grafana:

```
request:Object
method:"GET"
url:"api/datasources/proxy/3/api/v1/query_range?query=sum%20by%20(id)%20(count_over_time(%20(%20%7BnodeType%3D%22AP%22%7D%20%7C~%20%22Open%20session%22)%5B15s%5D))%20-%20sum%20by%20(id)%20(count_over_time((%7BnodeType%3D%22AP%22%7D%20%7C~%20%22Closed%20session%22)%5B15s%5D))&start=1589207340&end=1589208000&step=15"
```

**Comment by cyriltovena** [comment]
I recently fixed something similar can you try latest ? See
https://github.com/grafana/loki/commit/fcb4c763dce7b49ae341bbdd0f31306190c62af0

**Comment by Mortega5** [comment]
Using this version does not work properly either. Could be an error with the date ranges?
Because changing date ranges sometimes works

**15 min**
![image](https://user-images.githubusercontent.com/8302870/81653410-08cc3680-9435-11ea-80e0-cedc29633aee.png)

**30 min**
![image](https://user-images.githubusercontent.com/8302870/81653499-1d103380-9435-11ea-9ca8-106e31232829.png)

**1 hour**
![image](https://user-images.githubusercontent.com/8302870/81653521-29948c00-9435-11ea-9775-cd690fa0bac0.png)
**6 hours (works)** 
![image](https://user-images.githubusercontent.com/8302870/81653562-3a450200-9435-11ea-9f4a-b832d50e7eb6.png)

**1 day**
![image](https://user-images.githubusercontent.com/8302870/81653600-48931e00-9435-11ea-8457-35d10b5c6277.png)

**2 days (works)**
![image](https://user-images.githubusercontent.com/8302870/81653626-53e64980-9435-11ea-8e2f-5f3cb048441f.png)

**Comment by Mortega5** [comment]
Using that version does not work properly either. Could be an error with the date ranges?

Because changing date ranges sometimes works.

**15 min** (works)
![image](https://user-images.githubusercontent.com/8302870/81661412-6021d500-943c-11ea-9b7f-9fa979452db1.png)


**30 min** (works)
![image](https://user-images.githubusercontent.com/8302870/81661453-6a43d380-943c-11ea-85f1-8451ad11cea0.png)


**3 hours**
![image](https://user-images.githubusercontent.com/8302870/81661476-7334a500-943c-11ea-9697-2a9613e30d0e.png)


**6 hours (works)** 
![image](https://user-images.githubusercontent.com/8302870/81661311-37014480-943c-11ea-9776-fc920214a34a.png)

**1 day**
![image](https://user-images.githubusercontent.com/8302870/81661503-7e87d080-943c-11ea-9e8f-5518de9b9b46.png)

**2 days (works)**
![image](https://user-images.githubusercontent.com/8302870/81661527-88113880-943c-11ea-9a36-2cddf7263c95.png)

**Comment by cyriltovena** [comment]
Those single stats are probably using the last available point by the way and from the screenshot it seems that zero is correct.

Making the time window bigger increase the range `$__interval` and so it covers a bigger range which contains points.

Try to use graph everywhere see if it works correctly.

**Comment by owen-d** [comment]
Can you confirm that the single-stat panel isn't using an instant query instead of a range query?

Other than that, what is the `id` in `sum by (id)`?  Is it possible you're grouping by different `id` labels than you expect? Also is that useful in a single stat panel?

**Comment by Mortega5** [comment]
> Can you confirm that the single-stat panel isn't using an instant query instead of a range query?

Grafana is quering using the `/query_range` endpoint and it return a list of values, so I guess.

**Request**:
```
{
  "request": {
    "url": "api/datasources/proxy/3/api/v1/query_range?query=sum%20(count_over_time(%20(%20%7BnodeType%3D%22AP%22%7D%20%7C~%20%22Open%20session%22)%5B1m%5D))%20-%20sum%20(count_over_time((%7BnodeType%3D%22AP%22%7D%20%7C~%20%22Closed%20session%22)%5B1m%5D))&start=1589204040&end=1589290440&step=60",
    "method": "GET"
  },
  "response": {
    "status": "success",
    "data": {
      "resultType": "matrix",
      "result": [
        {
          "metric": {},
          "values": [
            [
              1589204340,
              "0"
            ],
            [
              1589204940,
              "0"
            ],
            [
              1589205780,
              "0"
            ],
            [
              1589206380,
              "0"
            ],
            [
              1589206800,
              "0"
            ],
            [
              1589207460,
              "0"
            ],
            [
              1589209380,
              "0"
            ],
            [
              1589209980,
              "0"
            ],
            [
              1589210580,
              "0"
            ],
            [
              1589211180,
              "0"
            ],
            [
              1589268240,
              "0"
            ],
            [
              1589268900,
              "0"
            ],
            [
              1589270160,
              "0"
            ],
            [
              1589270760,
              "0"
            ],
            [
              1589271360,
              "0"
            ],
            [
              1589271960,
              "0"
            ],
            [
              1589272560,
              "0"
            ],
            [
              1589274900,
              "3"
            ],
            [
              1589275560,
              "1"
            ],
            [
              1589279220,
              "0"
            ],
            [
              1589279340,
              "-1"
            ],
            [
              1589284800,
              "0"
            ],
            [
              1589289180,
              "1"
            ],
            [
              1589289780,
              "0"
            ],
            [
              1589290380,
              "0"
            ]
          ]
        }
      ],
      "stats": {
        "summary": {
          "bytesProcessedPerSecond": 57969973,
          "linesProcessedPerSecond": 83702,
          "totalBytesProcessed": 8465979,
          "totalLinesProcessed": 12224,
          "execTime": 0.146040761
        },
        "store": {
          "totalChunksRef": 672,
          "totalChunksDownloaded": 672,
          "chunksDownloadTime": 0.151961019,
          "headChunkBytes": 0,
          "headChunkLines": 0,
          "decompressedBytes": 7936471,
          "decompressedLines": 11402,
          "compressedBytes": 687208,
          "totalDuplicates": 0
        },
        "ingester": {
          "totalReached": 2,
          "totalChunksMatched": 18,
          "totalBatches": 0,
          "totalLinesSent": 0,
          "headChunkBytes": 529508,
          "headChunkLines": 822,
          "decompressedBytes": 0,
          "decompressedLines": 0,
          "compressedBytes": 0,
          "totalDuplicates": 0
        }
      }
    }
  }
}
```

I have changed everything to charts and this is the result( I have removed `sum by (id)` in order to avoid issues and the legend shows the current query):

**5 min**
![image](https://user-images.githubusercontent.com/8302870/81695738-4d6ec680-9463-11ea-8239-222aa9c35457.png)

**3 hours**
![image](https://user-images.githubusercontent.com/8302870/81695923-90c93500-9463-11ea-863f-0c28e5d35ca1.png)
**6 hours**
![image](https://user-images.githubusercontent.com/8302870/81695959-9cb4f700-9463-11ea-8e86-f58d67b1acd0.png)

**12 hours**
![image](https://user-images.githubusercontent.com/8302870/81696022-b0f8f400-9463-11ea-9da4-b06b21ad1d2e.png)

**24 hours**
![image](https://user-images.githubusercontent.com/8302870/81696075-c110d380-9463-11ea-9ec0-351d7fc42387.png)

I have tried using `sum by(nodeType)` and the graphs are the same. I have checked the id label and it is the same for all the logs.
