### ISSUE TITLE
Helm chart for Loki production deployment

### ISSUE THREAD

**Issue by langecode** [grafana/loki#2065]
Not so much a question as it is just information. We have created a Helm chart for Grafana Loki production deployment based on your public ksonnet scripts. So just for information for what its worth there is a Helm version of this here:
https://github.com/mhivestasoffshore/charts/tree/master/charts/loki

Thanks for a nice product.

**Comment by owen-d** [comment]
This is really cool, thanks! Would you be interested in talking about it at our next community call? Feel free to drop by #loki-dev on grafana.slack.com for more information.

**Comment by langecode** [comment]
I am sure we can arrange that. I have joined the `#loki-dev` channel so we might discus there.

**Comment by nhuray** [comment]
@langecode @owen-d Do we have plan to update the code to Loki 2.0 and integrating it in the official Loki project ?
