### ISSUE TITLE
Write Ahead Log in ingesters for crash resiliency

### ISSUE THREAD

**Issue by gouthamve** [grafana/loki#2067]
**Is your feature request related to a problem? Please describe.**
A crash in the ingesters would currently lead to loss of data. While we can try to prevent crashes, we can't completely avoid them. Even a simple OOM would cause data-loss. One solution to the problem is a [Write Ahead Log (WAL)](https://www.wikiwand.com/en/Write-ahead_logging).

Cortex and Prometheus solve this problem by using a WAL as well. With Loki we have a different problems, but not fundamentally different from Cortex: In Cortex we store the last 10mins of WAL and then checkpoint the in-mem data to disk every 10mins. This means we will need to have a disk space of `O(memory + 10mins ingest)` for the WAL which doesn't seem too terrible imo.

**Comment by owen-d** [comment]
We'll need to be cognizant of the processing costs for a WAL ingesting logs instead of metrics (this should be a heavier load)

**Comment by gouthamve** [comment]
Not necessarily imo, while logs are bigger compared to metrics, we kinda do (4x) _more_  throughput in Cortex ingesters than Loki ingesters (compared our prod envs). This is because the number of streams is higher in metrics.

**Comment by cyriltovena** [comment]
#2704

**Comment by owen-d** [comment]
This has been merged in master, closing this as cleanup :)
