### ISSUE TITLE
Brew formula for loki/logCLI/promtail

### ISSUE THREAD

**Issue by chancez** [grafana/loki#2071]
**Is your feature request related to a problem? Please describe.**
It would be nice if the Loki suite of tools were packaged for MacOS using Homebrew. I'm most interested in logCLI, but the others make sense as well for anyone just trying to get started with everything. 

One potential benefit is, if packaged for homebrew, it's possible to provide out of the box configurations for using promtail with Loki using MacOS logs or something similar. 

**Describe the solution you'd like**
`brew install loki` provides loki + logCLI and maybe `promtail` or potentially a separate formula for `promtail` makes sense.

**Describe alternatives you've considered**
Not doing it, since you can just download the release tarball.

**Comment by tharun208** [comment]
I like to work on this

**Comment by cyriltovena** [comment]
it's all yours !

**Comment by tharun208** [comment]
as far as I know, `brew formulae` can be created with one binary at a time. can we have only `loki` with `brew install loki`?

**Comment by chancez** [comment]
@tharun208 forumula can definitely have multiple binaries. See the prometheus formula.

**Comment by tharun208** [comment]
> @tharun208 formula can definitely have multiple binaries. See the prometheus formula.

sure will look into it

**Comment by tharun208** [comment]
> > @tharun208 formula can definitely have multiple binaries. See the prometheus formula.
> 
> sure will look into it
But , here what the ask is adding `loki` and `logcli` to the same formula.That we cant be able to do.

**Comment by tharun208** [comment]
I will create a brew formula for `loki`.

**Comment by philoserf** [comment]
@cyriltovena This was not revived. I guess the keepalive came too late. Needs a reopen.

**Comment by tharun208** [comment]
@philoserf  @cyriltovena, I see there are 3 separate formulae's for `loki`, `promtail`, and `logcli`. Do we still want to include `logcli` in `loki` formulae?
