### ISSUE TITLE
Bytes Log Aggregations

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#2077]
**Is your feature request related to a problem? Please describe.**

It could be super interesting and very simple to add similar operation as `rate` and `count_over_time` but to count bytes in logs.

For example:

```
sum by (job) (brate({cluster="prod"}[1m]))
```

Would give you the total bytes/sec of logs per job.

or 

```
sum by (job) (bytes_over_time({cluster="prod"}[1m]))
```

Will give you the total bytes over time per job.

This can be super interesting to weight your logs per stream.

**Describe alternatives you've considered**
We just don't add those operator but that's too bad there are very simple to add !

/cc @slim-bean @owen-d WDYT ? @tomwilkie

**Comment by owen-d** [comment]
I like the idea

**Comment by cyriltovena** [comment]
brate or bytes_rate

**Comment by owen-d** [comment]
berate 😆

**Comment by rfratto** [comment]
I would personally go for `bytes_rate` since it's more descriptive of what the value is (or `byte_rate`, which I think might be more grammatically correct)
