### ISSUE TITLE
AWS config example

### ISSUE THREAD

**Issue by arnitolog** [grafana/loki#208]
is there any example how to configure Loki to store logs in AWS S3 bucket?

**Comment by vishesh92** [comment]
+1

**Comment by mazzy89** [comment]
The author itself replied me to this question a month ago on Reddit https://www.reddit.com/r/kubernetes/comments/a6zbnq/grafanaloki_like_prometheus_but_for_logs/ebzpv0y

**Comment by perriea** [comment]
The Loki configuration is a same as Cortex:
https://github.com/grafana/loki/blob/master/pkg/loki/loki.go#L26
https://github.com/cortexproject/cortex/blob/master/pkg/chunk/storage/factory.go#L23

I will try to propose a configuration in the coming days :)

**Comment by tomwilkie** [comment]
I think this has been covered now, closing.
