### ISSUE TITLE
Create Loki Operator

### ISSUE THREAD

**Issue by reidlai** [grafana/loki#2082]
**Describe the bug**
I installed loki stack using Helm3 successfully with chart "loki/loki-stack" and version "0.36.2".  However, loki-stack chart cannot be found when I use operator-sdk to create helm based operator as follow:

```
operator-sdk new loki-operator --type helm --helm-chart loki/loki-stack --helm-chart-version 0.36.2
```

Error: 
INFO[0000] Creating new Helm operator 'loki-operator'.  
FATA[0000] failed to create helm chart: failed to fetch chart: chart "loki/loki-stack" version "0.36.2" not found in https://grafana.github.io/loki/charts repository 

**To Reproduce**

```
helm repo add loki https://grafana.github.io/loki/charts
helm repo update
operator-sdk new loki-operator --type helm --helm-chart loki/loki-stack --helm-chart-version 0.36.2
```
**Expected behavior**
operator-sdk found helm and create new operator

**Environment:**
MIniKube 1.9.2
Kubernetes 1.17.5
Operator-SDK version: v0.17.0
Helm version: v3.2.1
Machine: Macbook Pro 2018

**Screenshots, Promtail config, or terminal output**

```
operator-sdk new loki-operator --type helm --helm-chart loki/loki-stack --helm-chart-version 0.36.2
```

Error: 
INFO[0000] Creating new Helm operator 'loki-operator'.  
FATA[0000] failed to create helm chart: failed to fetch chart: chart "loki/loki-stack" version "0.36.2" not found in https://grafana.github.io/loki/charts repository

**Comment by PiotrKlimczak** [comment]
+1

**Comment by tlipatov** [comment]
A Loki kubernetes operator would be extremely useful for managing recording/alerting rules similar to how we can with the prometheus operator

**Comment by jpinsonneau** [comment]
> A Loki kubernetes operator would be extremely useful for managing recording/alerting rules similar to how we can with the prometheus operator

Check https://github.com/grafana/loki/tree/main/operator :partying_face:
