### ISSUE TITLE
Loki-stack Helm Lint chart - bug 

### ISSUE THREAD

**Issue by Tikam02** [grafana/loki#2085]
**Describe the bug**
while passing Loki-stack chart in git actions, Helm lint chart could not pass the service port displaying this error: 

> [ERROR] templates/: template: loki-stack/templates/tests/loki-test-pod.yaml:22:18: executing "loki-stack/templates/tests/loki-test-pod.yaml" at <.Values.loki.service.port>: nil pointer evaluating interface {}.port

**Expected behavior**
should pass 

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool:  helm

**Screenshot**
![loki-stack-2](https://user-images.githubusercontent.com/10548085/82136698-e9b31780-982d-11ea-97f1-87e4e8b5ac04.PNG)

**Comment by cyriltovena** [comment]
Can you provide the command you used and the helm version please ?

**Comment by Tikam02** [comment]
I could not able to provide the command since it's workflow, but the bug is resolved when I put the port value as port:"8000" in loki-test-pod.yaml, it's not executing without value since intially it was null.
