### ISSUE TITLE
Documentation about local installation

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#2103]
The docs section for running Loki locally is not very well furnished see https://github.com/grafana/loki/blob/master/docs/installation/local.md

Would be great to have more on how to get up and running.

Windows and linux seems appropriate.

**Comment by rlex** [comment]
Just in case, i have ansible role here which i use for running simple one-node loki server: https://github.com/rlex/ansible-role-loki
There is also promtail role:
https://github.com/patrickjahns/ansible-role-promtail

**Comment by Daniel15** [comment]
@rlex Your Ansible role looks really good and is a good indication at what would be good to include in the docs:

 - A systemd unit. Ideally contained in the tar.gz file download so I could just `mv loki.service /etc/systemd/system/loki.service && systemctl reload`
 - A minimal config documented somewhere. The bare minimum configuration required for Loki to start, without any unnecessary boilerplate.

The docs should mention that a separate user should be created, for security reasons.

It would be really nice to have a Debian package for Loki so I could simply `apt install loki` and get a working installation that's configured correctly.

**Comment by sreyasvpariyath** [comment]
I followed this.
https://sbcode.net/grafana/install-loki-service/
And this
https://sbcode.net/grafana/install-promtail-service/

**Comment by Daniel15** [comment]
> I followed this.
> [sbcode.net/grafana/install-loki-service](https://sbcode.net/grafana/install-loki-service/)

One major issue with that guide is that Loki ends up running as root. You should add `User=loki` to the systemd unit, and add a user called `loki`, for example by doing:
```
adduser --system loki --group --home /var/local/loki/
```

The other thing I'm curious about is that `config-loki.yml` file. It's very large. I wonder if all of those config items are needed, or if Loki has some defaults that can be omitted. That's some thing the Loki docs don't really clarify at the moment.

**Comment by NINNiT** [comment]
Here's a shell script we are using to install and update loki as a system service.  An official apt package would be really nice though!
```
## Loki Installation Script
## Author: NINNiT

# Installation Variables (change this to your liking)
LOKI_VERSION_TAG="v2.3.0"
LOKI_BINARY_PATH=/usr/local/bin
LOKI_CONFIG_PATH=/etc/loki

# color variables
GREEN_COLOR="\033[0;32m"
NC="\033[0m"

printf "${GREEN_COLOR}Installing dependencies...${NC}\n"
apt install wget unzip

# download binary archive
printf "${GREEN_COLOR}Downloading binary...${NC}\n"
wget https://github.com/grafana/loki/releases/download/${LOKI_VERSION_TAG}/loki-linux-amd64.zip

# download configuration file
printf "${GREEN_COLOR}Downloading configuration...${NC}\n"
wget https://raw.githubusercontent.com/grafana/loki/${LOKI_VERSION_TAG}/cmd/loki/loki-local-config.yaml

# unzip
printf "${GREEN_COLOR}Unzipping...${NC}\n"
unzip loki-linux-amd64.zip

# set exec permissions and move binary
printf "${GREEN_COLOR}Setting permissions...${NC}\n"
chmod +x loki-linux-amd64

printf "${GREEN_COLOR}Installing binary to ${LOKI_BINARY_PATH}...${NC}\n"
cp loki-linux-amd64 ${LOKI_BINARY_PATH}/loki

# installing config
printf "${GREEN_COLOR}Checking if a config already exists in ${LOKI_CONFIG_PATH}... ${NC}\n"
mkdir -p ${LOKI_CONFIG_PATH}
if test -f "${LOKI_CONFIG_PATH}/config.yaml"; then
    echo "${GREEN_COLOR}Configuration found, keeping old config... ${NC}\n"
    echo "${GREEN_COLOR}Installing new config to ${LOKI_CONFIG_PATH}/config-${LOKI_VERSION_TAG}.yaml... ${NC}\n"
    cp loki-local-config.yaml ${LOKI_CONFIG_PATH}/config-${LOKI_VERSION_TAG}.yaml
fi

# create loki user
printf "${GREEN_COLOR}Creating loki user...${NC}\n"
useradd --system loki

# move systemd service file
printf "${GREEN_COLOR}Moving service file...${NC}\n"
cp loki.service /etc/systemd/system/

# reload daemons
printf "${GREEN_COLOR}Reload daemons...${NC}\n"
systemctl daemon-reload

# cleanup
printf "${GREEN_COLOR}Cleaning up...${NC}\n"
rm loki-linux-amd64*
rm loki-local-config.yaml*
```

And the systemd service file (keep this in the same directory as the installation script):
```
[Unit]
Description=Loki service
After=network.target

[Service]
Type=simple
User=loki
ExecStart=/usr/local/bin/loki -config.file /etc/loki/config.yaml

[Install]
WantedBy=multi-user.target

```
