### ISSUE TITLE
loki 1.5.0 failed parsing config: not a valid duration string: "0"

### ISSUE THREAD

**Issue by adacaccia** [grafana/loki#2113]
**Describe the bug**
Hello, as directed by the release docs of Loki 1.5.0, I've tried to test the current config I use (standard from the Helm manifest), but received this error without an indication of line number nor context.

**To Reproduce**
1. Started Loki 1.5.0 (./loki-linux-amd64 -config.file loki.yaml)

**Expected behavior**
Loki should have started on my laptop, locally.

**Environment:**
 - Infrastructure: laptop
 - Deployment tool: wget

**Screenshots, Promtail config, or terminal output**
failed parsing config: loki.yaml: not a valid duration string: "0"

But the string "0" is not at all present in the supplied loki.yaml config file!
Here is it:

---loki.yaml
auth_enabled: false
chunk_store_config:
  max_look_back_period: 0
ingester:
  chunk_block_size: 262144
  chunk_idle_period: 3m
  chunk_retain_period: 1m
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  max_transfer_retries: 0
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
schema_config:
  configs:
  - from: "2018-04-15"
    index:
      period: 168h
      prefix: index_
    object_store: filesystem
    schema: v9
    store: boltdb
server:
  http_listen_port: 3100
storage_config:
  boltdb:
    directory: /data/loki/index
  filesystem:
    directory: /data/loki/chunks
table_manager:
  retention_deletes_enabled: false
  retention_period: 0s

**Comment by adacaccia** [comment]
Ok, I've figured out:

chunk_store_config:
  max_look_back_period: 0

given it is a "period" of time, I've tried to replace it with:

chunk_store_config:
  max_look_back_period: 0s

And Loki 1.5.0 stared on my laptop, as expected!

**Comment by slim-bean** [comment]
Thanks for reporting this though @adacaccia  I suspect many others will run into this too. I will update the upgrade guide release notes to mention this

**Comment by KingJ** [comment]
I'm hitting this on a completely fresh install whilst following the [Tanka installation documentation](https://github.com/grafana/loki/blob/master/docs/installation/tanka.md). It looks like the value for `max_look_back_period` in the default ksonnet configuration is also set to `0` rather than `0s`.

https://github.com/grafana/loki/blob/v1.5.0/production/ksonnet/loki/config.libsonnet#L239

**Comment by cyriltovena** [comment]
This commit fixes it https://github.com/grafana/loki/commit/e4a53605862c7c7fac7507b1eeaa7f1b5361b54f

Not yet released  though.
