### ISSUE TITLE
logql Engine redesign

### ISSUE THREAD

**Issue by owen-d** [grafana/loki#2114]
This is a placeholder issue for some concepts I've been thinking about.
I'd like to redesign the logql engine to take advantage of a few things.

1) Better concurrency support
For instance, I'd like to evaluate each leg of a binop expression concurrently, or give downstream implementations the ability to choose how to handle this.
2) Dedupe expressions
Queries like `a / (a + b)` should only need to evaluate `a` once. It'd also be nice to allow incremental caching of sub-expressions here, enabling greater re-use across different queries that consume the same underlying requests.

I'm guessing this will look like a query planner. I'd like this to be implemented in a way that allows us to easily extract different pieces such that we can distribute the query planner over different components in the future.

/cc @cyriltovena

**Comment by cyriltovena** [comment]
1- How does Prometheus handle this ? 

2- A big yes !

**Comment by slim-bean** [comment]
Closing this issue as we continue to focus the issue list for more actionable items and move higher level items like this to a separate home.
