### ISSUE TITLE
Grafana alerts fail with error

### ISSUE THREAD

**Issue by Alpha200** [grafana/loki#2117]
**Describe the bug**
Loki alert in grafana fails with error.

**To Reproduce**
1. Use Loki 1.5 and Grafana 7.0
2. Connect Grafana to Loki with Prometheus data source
2. Create alert for query: `sum by(container_name) (count_over_time({host="coreos"} |~ "(?i)error*" [$__interval]))`
3. Query fails with: `tsdb.HandleRequest() error bad_response: readObjectStart: expect { or n, but found p, error found in #1 byte of ...|parse error|..., bigger context ...|parse error at line 0, col 73: not a valid duration|...`

**Expected behavior**
The alert should not fail.

**Environment:**
 - Docker

**Screenshots, Promtail config, or terminal output**
![image](https://user-images.githubusercontent.com/693245/82699730-79612780-9c6d-11ea-8633-b6b802f0fe1a.png)

**Comment by adityacs** [comment]
@Alpha200  Kindly replace `$__interval` to some value like `5m`, `10m` etc... and test you rule. Using `$__interval` or any other template variables in alerts is not supported in Grafana.

**Comment by Alpha200** [comment]
That did it. Thank you!

**Comment by cyriltovena** [comment]
Thanks @adityacs.

By the way @Alpha200 you should pick a range that is big enough to cover your FOR clause.
