### ISSUE TITLE
Is there any way to read loki logs using python3?

### ISSUE THREAD

**Issue by ashish0x01** [grafana/loki#2132]
Please ask questions you have in the mailing list: https://groups.google.com/forum/#!forum/lokiproject

Or join our #loki slack channel at http://slack.raintank.io/

**Comment by cyriltovena** [comment]
From the API ?

**Comment by ashish0x01** [comment]
yes... I want to fetch JSON logs via python

**Comment by cyriltovena** [comment]
Write a custom client in python against this API then https://github.com/grafana/loki/blob/master/docs/api.md#get-lokiapiv1query_range
