### ISSUE TITLE
Can't enable plugin on server on Ubuntu 18.05

### ISSUE THREAD

**Issue by skor-012** [grafana/loki#2147]
Can't run loki docker plugin 

**To Reproduce**
1. docker plugin install  grafana/loki-docker-driver:latest --alias loki --grant-all-permissions

expects that plugin enabling but got this error

Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"\\\" to rootfs \\\"/var/lib/docker/plugins/cae5c01a8057d45dccac67b5d67f78b9ac77d02461f814b897172945cb913fc5/rootfs\\\" at \\\"/var/lib/docker/plugins/cae5c01a8057d45dccac67b5d67f78b9ac77d02461f814b897172945cb913fc5/rootfs/data\\\" caused \\\"invalid argument\\\"\"": unknown

docker plugin enable loki do same error

**Comment by rubycut** [comment]
I have same issue.

**Comment by cdreier** [comment]
i had the same issue, but i got around it when i just updated the plugin

```
docker plugin disable loki
docker plugin upgrade loki grafana/loki-docker-driver:master
docker plugin enable loki
```

**Comment by cyriltovena** [comment]
seems like there is an issue with latest and empty mount. https://github.com/grafana/loki/pull/2054 is probably why.

**Comment by cyriltovena** [comment]
In the meantime you can do this:

```
docker plugin set loki:latest data.source=/tmp
docker plugin enable loki:latest
```

If you want to use latest. I'm thinking about what should be the final solution.

**Comment by cyriltovena** [comment]
@bkmit #2054 seems to cause problem with some version of docker and/or OS. I feel like we have a new way to include pipeline via log-opt and we should advertise this instead.  https://github.com/grafana/loki/tree/master/cmd/docker-driver#pipeline-stages

I'm going to remove the mount in the spec and document how to reproduce it locally. If you still want to use the old image you can use this tag `master-5e0fe09` which support the mount.

**Comment by rubycut** [comment]
> In the meantime you can do this:
> 
> ```
> docker plugin set loki:latest data.source=/tmp
> docker plugin enable loki:latest
> ```
> 
> If you want to use latest. I'm thinking about what should be the final solution.

Yes, this works.
