### ISSUE TITLE
Feature to be able to change timezone in Promtail container

### ISSUE THREAD

**Issue by vijay-jindal** [grafana/loki#2154]
**Is your feature request related to a problem? Please describe.**
The machine on which Loki is running uses IST timezone. The application which produces the logs produce them in IST timezone. I am using Grafana in IST timezone. But the problem is, the logs that come from Promtail have a UTC timestamp and hence I am facing issue when searching logs in a particular time range.

**Describe the solution you'd like**
I am wondering if there can be an input in Promtail configuration file where the timezone can be set by the user as per his/her requirement.

**Additional context**
I am currently using grafana/promtail docker image to run Promtail in my Kubernetes cluster. I am using promtail as a Sidecar with the pods.

**Comment by owen-d** [comment]
We'd like to leave ingestion agnostic of the consumer, so I don't suspect we'll be adding support to do this.

**Comment by cyriltovena** [comment]
It's not fully clear the problem here @vijay-jindal.

Can you provide some example ? the data sent from promtail is a timestamp so far so good but I'm wondering why you're facing issue with Grafana setup as IST timezone.

**Comment by aocenas** [comment]
@vijay-jindal in Grafana 7.0 we introduced better support for [timezones](https://grafana.com/docs/grafana/latest/guides/whats-new-in-v7-0/#time-zone-support). You can set any timezone either in preferences or override it for single dashboard. Are you using that when you say `I am using Grafana in IST timezone`? If so are only the Loki logs shown in UTC or is everything still shown in UTC instead of IST?

**Comment by vijay-jindal** [comment]
Hi.
@aocenas , I am using the feature you are talking about.
@cyriltovena ,
Every log that comes from Promtail comes with a timestamp that is set by Promtail, since Promtail is running on UTC, the timestamp on the logs is also in UTC.

Now, when I query the logs from Grafana with current IST time

**Comment by vijay-jindal** [comment]
Hi.
@aocenas , I am using the feature you are talking about.
@cyriltovena ,
Every log that comes from Promtail comes with a timestamp that is set by Promtail, since Promtail is running on UTC, the timestamp on the logs is also in UTC.

Now, when I query the logs from Grafana with current IST time, the logs that Loki returns is based on the timestamp that is assigned by Promtail and hence I do not get the logs of current IST time, instead I get logs of current UTC time.

So, if I query a log for time : 08:30:00 2020/05/29
I get logs for : 03:00:00 2020/05/29

Therefore in any case, I'm not able to get logs for the latest 5:30H.

It is possible if I change grafana time to UTC, but in that case confusion arises due to differences in timestamp from Grafana and Loki.

**Comment by aocenas** [comment]
hmm will have to check later but I think that is the correct behavior. ie:
search for `now` in Grafana which is in IST -> convert to `now` in UTC -> send to Loki -> return log with UTC timestamp -> Grafana should convert the UTC and show it as IST. What ever the timezone the time itself is the same if converted to unix epoch time. So the different timezones should not be a problem and they should represent the same moment in time.

There could be a bug somewhere in the process though. Probably check if you can whether the timestamps in Loki are correct, ie if you log something it is saved with a correct UTC timestamp. If that is true then if there is a bug it is probably in Grafana and we may show wrong timezone somewhere.

**Comment by vijay-jindal** [comment]
I restarted the service and the timestamp 'in the log' matches the time that I give as an input in Grafana. The only thing is, the timestamp under the **parse fields** in the log context of Grafana is still in UTC, leading to occasional confusion to some of the users when querying logs. It is not an immediate issue, but can cause some confusion.

<img width="1280" alt="Screenshot 2020-06-02 at 10 33 48 AM" src="https://user-images.githubusercontent.com/25745453/83488370-5d118600-a4ca-11ea-8485-385bf2cd1a62.png">

**Comment by aocenas** [comment]
@vijay-jindal Yes this looks correct to me. I understand that the parsed fields may be confusing but at the moment we do not do much formatting there and it's more a raw data display, that's why it is just plain ISO string.

You can create an issue in Grafana repo if you think this should be also formatted in the currently selected timezone. Can't make any promises but we will consider it.

**Comment by vijay-jindal** [comment]
@aocenas , Thank you. :)
