### ISSUE TITLE
Add more debugging logs to Promtail

### ISSUE THREAD

**Issue by hreidar** [grafana/loki#2158]
**Is your feature request related to a problem? Please describe.**
Greetings all, I have been battling Promtail for a few days now and I'm unable to get any logs to my Loki servers. The [logs](https://paste.gnome.org/paruo4lyt) show me three kinds of messages, "new target", "dropping target, no labels" and "ignoring target, wrong host". In the case of "new target" message I only see a subset of the labels I believe should be there (at least I see many more labels when using kubectl describe on my objects). This is followed by a "dropping target, no labels" message which is understandable if Promtail is only seeing the labels it prints out with the "new target" message. In the case where I see the "ignoring target, wrong host" message the labels seems fine. I'm unsure if the problem is that Promtail is not getting all the labels from the api-server or if I'm doing something wrong in my configuration.

**Describe the solution you'd like**
It would be nice to have some more debugging logs from earlier in the process where you can see all the info coming from the api-server and a list of the files Promtail is supposed to be working with.

**Additional context**
I have it running on a local k8s cluster (version 1.18.2) which was bootstrapped with kubeadm on Ubuntu 18.04.4. It has a Cilium CNI and no kube-proxy. I used the instructions on the Loki's [github page](https://github.com/grafana/loki/blob/master/docs/clients/promtail/installation.md) to install with few changes.

[Here are my install instructions and current configuration](https://pastebin.com/UY1YGnAX)

I used the [helm template](https://github.com/grafana/loki/blob/master/production/helm/promtail/templates/configmap.yaml) as a base for the configmap but I had to make some changes as my paths are a bit different, as can be seen in the example here below:

```bash
root@promtail-88ths:/var/log/pods# ls -l
total 32
drwxr-xr-x 4 root root 4096 May 29 11:24 kube-system_cilium-fgsm4_d166d361-aa6e-4924-b261-640ad416b326
drwxr-xr-x 3 root root 4096 May 11 12:20 kube-system_coredns-66bff467f8-hzwgv_55649469-53ee-4331-9eda-cf57a1fd814e
drwxr-xr-x 3 root root 4096 May 11 14:47 kube-system_hubble-554gp_be720fc2-4bb1-42dd-92ea-07f871fb39b0
drwxr-xr-x 3 root root 4096 May 10 13:19 kube-system_kube-apiserver-k8s-c2-m1_3603a5737b9e5f5a2008e1cc64eb5581
drwxr-xr-x 3 root root 4096 May 10 14:39 kube-system_kube-controller-manager-k8s-c2-m1_6ebebdc276265f42d294ef5c1178df8e
drwxr-xr-x 3 root root 4096 May  8 09:20 kube-system_kube-scheduler-k8s-c2-m1_155707e0c19147c8dc5e997f089c0ad1
drwxr-xr-x 3 root root 4096 May 11 14:56 lens-metrics_node-exporter-t67nj_12d1fad0-6e48-4070-8e4c-eb4f80d99b84
drwxr-xr-x 3 root root 4096 May 30 10:36 promtail_promtail-88ths_c71917f7-8e2f-4e97-b7eb-365337269381
root@promtail-88ths:/var/log/pods# 
root@promtail-88ths:/var/log/pods# ls -l lens-metrics_node-exporter-t67nj_12d1fad0-6e48-4070-8e4c-eb4f80d99b84/node-exporter/0.log 
lrwxrwxrwx 1 root root 165 May 11 14:56 lens-metrics_node-exporter-t67nj_12d1fad0-6e48-4070-8e4c-eb4f80d99b84/node-exporter/0.log -> /var/lib/docker/containers/a3f967377b8c7b7e7f27537d3f2e84e84ce3039a6e83c7aa26c1ca24c4cf293e/a3f967377b8c7b7e7f27537d3f2e84e84ce3039a6e83c7aa26c1ca24c4cf293e-json.log
```

**Comment by cyriltovena** [comment]
Have you tried this ? https://github.com/grafana/loki/blob/65ba42a6e7dc975d6f25b15fc6f9b8d72446b3e2/docs/getting-started/troubleshooting.md#troubleshooting-targets
