### ISSUE TITLE
Question: support indexing as optional

### ISSUE THREAD

**Issue by ghost** [grafana/loki#217]
It would make Loki more useful for detailed searching of logs if it did indexing.

There are greats libs out there that support this in golang using badger and bleve together. They also are able to use Alisa's so that the index data is horizontally distributed as well as the act of indexing 

I can suggest sone libs if required that already do the above things 

The use case is of course when you need to do very detailed log searching. Facet based searching also 

This is partly why elastic search is so popular with log storage - the logs are heavily indexed.

**Comment by kiney** [comment]
As I understand it was a conscious design choice to _not_ build a second elastic.

**Comment by mumoshu** [comment]
I do second NOT to build a second elastic, but I agree on making structured logs and traces stored efficiently searchable would be useful.

For that I don't need unstructured text indexing provided by bleve, but optional indexing on structured data. #91 seems like a relevant issue.

**Comment by slim-bean** [comment]
Closing as a duplicate or closely related to #91
