### ISSUE TITLE
Helm chart cannot be install correctly

### ISSUE THREAD

**Issue by joker9357** [grafana/loki#2174]
I follow the wiki and try to install the loki by default config. And then helm report below Error.

`helm upgrade --install loki loki/loki-stack
Release "loki" does not exist. Installing it now.
Error: rendered manifests contain a resource that already exists. Unable to continue with install: PodSecurityPolicy "loki" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "loki"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "default"`

helm version is 
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

kubectl version is
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"059c666b8d0cce7219d2958e6ecc3198072de9bc", GitTreeState:"clean", BuildDate:"2020-04-03T15:17:29Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**Comment by mrgoonie** [comment]
Did you solve it @joker9357 ?

**Comment by mrgoonie** [comment]
For someone seeking the answer, use this install command instead:

```
helm install loki-stack grafana/loki-stack \
  --create-namespace \
  --namespace loki-stack \
  --set promtail.enabled=true,loki.persistence.enabled=true,loki.persistence.size=10Gi 
```
