### ISSUE TITLE
Why loki keep synching tables

### ISSUE THREAD

**Issue by joker9357** [grafana/loki#2175]
I set up a loki pod by helm template and value, and the the pod running. but the log shows it keep synching tables.
`level=info ts=2020-06-04T04:25:31.302529715Z caller=table_manager.go:292 msg="synching tables" expected_tables=113
level=info ts=2020-06-04T04:27:31.300142037Z caller=table_manager.go:292 msg="synching tables" expected_tables=113
level=info ts=2020-06-04T04:29:31.300162165Z caller=table_manager.go:292 msg="synching tables" expected_tables=113
level=info ts=2020-06-04T04:31:31.300109738Z caller=table_manager.go:292 msg="synching tables" expected_tables=113
level=info ts=2020-06-04T04:33:31.300056316Z caller=table_manager.go:292 msg="synching tables" expected_tables=113
level=info ts=2020-06-04T04:35:31.300104201Z caller=table_manager.go:292 msg="synching tables" expected_tables=113
level=info ts=2020-06-04T04:37:31.299998778Z caller=table_manager.go:292 msg="synching tables" expected_tables=113
level=info ts=2020-06-04T04:39:31.300233388Z caller=table_manager.go:292 msg="synching tables" expected_tables=113
level=info ts=2020-06-04T04:41:31.300559084Z caller=table_manager.go:292 msg="synching tables" expected_tables=113
level=info ts=2020-06-04T04:43:31.300164005Z caller=table_manager.go:292 msg="synching tables" expected_tables=113
level=info ts=2020-06-04T04:45:31.300413086Z caller=table_manager.go:292 msg="synching tables" expected_tables=113
level=info ts=2020-06-04T04:47:31.300161896Z caller=table_manager.go:292 msg="synching tables" expected_tables=113
level=info ts=2020-06-04T04:49:31.300108567Z caller=table_manager.go:292 msg="synching tables" expected_tables=113
level=info ts=2020-06-04T04:51:31.30009496Z caller=table_manager.go:292 msg="synching tables" expected_tables=113
level=info ts=2020-06-04T04:53:31.300125165Z caller=table_manager.go:292 msg="synching tables" expected_tables=113
level=info ts=2020-06-04T04:55:31.300161796Z caller=table_manager.go:292 msg="synching tables" expected_tables=113
level=info ts=2020-06-04T04:57:31.300106395Z caller=table_manager.go:292 msg="synching tables" expected_tables=113
level=info ts=2020-06-04T04:59:31.300417164Z caller=table_manager.go:292 msg="synching tables" expected_tables=113
level=info ts=2020-06-04T05:01:31.30026783Z caller=table_manager.go:292 msg="synching tables" expected_tables=113
level=info ts=2020-06-04T05:03:31.300207665Z caller=table_manager.go:292 msg="synching tables" expected_tables=113
level=info ts=2020-06-04T05:05:31.300197872Z caller=table_manager.go:292 msg="synching tables" expected_tables=113
level=info ts=2020-06-04T05:07:31.300167452Z caller=table_manager.go:292 msg="synching tables" expected_tables=113
level=info ts=2020-06-04T05:09:31.300110206Z caller=table_manager.go:292 msg="synching tables" expected_tables=113`

And I also set up the fluent-bit-plugin and setting the url with 
`http://loki-service-name.namesspace:3100/api/v1/push`
but it shows 404 cannot found the page, so I'm not sure if my loki running correctly.

**Comment by adityacs** [comment]
The logs you see for `syncing tables` is fine, that is just the index tables being polled every 2mins. 

Path should be `/loki/api/v1/push` and not `api/v1/push`
