### ISSUE TITLE
Promtail - Add config.file location URL capability

### ISSUE THREAD

**Issue by vincent-gou** [grafana/loki#2177]
**Is your feature request related to a problem? Please describe.**
Promtail client can only read config.file from local storage. I got promtail deployed on different servers that i can't manage directly. I can't find any information on that subject.

**Describe the solution you'd like**
Get promtail ability to read config.file from an URL.
I use this solution for telegraf agent for example:
`telegraf --config "https://xxxx.domain.com/telegraf?client=52410725-813e-4a87-9457-ff09fe7abext&application=aaaaaa&os=windows&host=srv-yyyyy&editor=xxxx&app_component=back-full"`

**Describe alternatives you've considered**
none for now.

**Additional context**
Thanks

**Comment by slim-bean** [comment]
hey @vincent-gou there is currently no support for this I'm afraid, we did discuss it a long time ago but it was never really a priority and actually haven't really seen any requests for it until yours.

I think this makes sense, some consideration would be versioning the config file as config options can change.

/cc @rfratto not sure if you've considered this yet with the Grafana Agent?

**Comment by rfratto** [comment]
I haven't considered it yet, but I agree it makes sense and I'd like to eventually see it added to the Agent.

**Comment by vincent-gou** [comment]
Ok thanks all for your feedback. 

I think that i have a workaround by downloading on each promtail reload or restart (via custom script) config.file.
If you decide to go further with this maybe issue #16 may be interesting to implement.

Best regards

Vincent
