### ISSUE TITLE
Loki makes GET requests to localhost:5778 every 1 minute

### ISSUE THREAD

**Issue by susuper** [grafana/loki#2183]
Hello.
I've notices that Loki makes this request to localhost:5778 every 1 minute:
GET /sampling?service=loki-all HTTP/1.1
Host: localhost:5778
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip

I guess it is somehow related to Jaeger which I don't use. 
Is there a way to disable these requests, please?

**Comment by periklis** [comment]
@susuper You may check #2191 that will resolve your issues with tracing. Although, if you can't wait for releasing this PR, you could use Jaeger's env variables to disabling auto-activation by setting `JAEGER_DISABLED=true` for your loki installation. More info on Jaeger can be found [here](https://www.jaegertracing.io/docs/1.16/client-features/)

**Comment by susuper** [comment]
@periklis Thank you!
