### ISSUE TITLE
Explain storage configs filesystem and s3 

### ISSUE THREAD

**Issue by Tikam02** [grafana/loki#2184]
# Need clarification on how storage endpoint works.
```
If object_store= filesystem :
                    then -> save it to local 
if object_store= s3: s3 | aws :
                     then -> save it to aws | s3
# How to do both at the same time saving it in local and exporting at s3
```
## How to save logs at local filesystem and export logs to s3 at the same time.

**Comment by slim-bean** [comment]
This is not possible with Loki, you can only choose from one object store type.

If you are going to use S3 is there a reason to not use that for the store?

If you were looking for a long term backup, you could build a separate process outside of Loki that copies the index files and chunk files to s3.

**Comment by Tikam02** [comment]
okay, Thanks for the information @slim-bean

**Comment by Tikam02** [comment]
@slim-bean can I use  newly released boltdb-shipper in production.Is it stable now?
https://github.com/grafana/loki/blob/master/docs/operations/storage/boltdb-shipper.md
