### ISSUE TITLE
loki-stack cannot be used as a datasource for external grafana installs

### ISSUE THREAD

**Issue by gclawes** [grafana/loki#2186]
**Describe the bug**
After PR #2086, loki-stack can no longer be used to install loki as a datasource for other grafana installations, such as from prometheus-operator.

**To Reproduce**
1. Install prometheus-operator with grafana installed
2. Install loki-stack with grafana disabled
3. Query: `{} term`

**Expected behavior**
I would expect the grafana datasource configmap to be usable when installing grafana with methods other than loki-stack.

**Environment:**
 - Infrastructure: k3s
 - Deployment tool: helm

**Comment by cyriltovena** [comment]
Yes good catch, my suggestions is: let’s add a another setting (bool) to force. Easy enough.

**Comment by gclawes** [comment]
Why not just revert it to the original setting?  If you want both enabled, just toggle both bools?

**Comment by cyriltovena** [comment]
Yeah that works too.

**Comment by gclawes** [comment]
I think that's the way to go, reduce unnecessary logic.
