### ISSUE TITLE
fluentbit plugin cannot find the loki Api path

### ISSUE THREAD

**Issue by joker9357** [grafana/loki#2187]
Loki and Fluentbit is running and fluentbit can found the loki host but it return 404 error

`level=error caller=client.go:247 id=0 component=client host=loki-headless.bpc-logging:3100 msg="final error sending batch" status=404 error="server returned HTTP status 404 Not Found (404): 404 page not found"
`

below is my fluentbit and loki's configmap and statefulsets. I have blocked for several days.

`
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-loki-config
  namespace: bpc-logging
  labels:
    app: fluent-bit
data:
  fluent-bit.conf: |-
    [SERVICE]
        Flush          1
        Daemon         Off
        Log_Level      warn
        Parsers_File   parsers.conf
    [INPUT]
        Name           tail
        Tag            kube.*
        Path           /var/log/containers/*.log
        Parser         docker
        DB             /run/fluent-bit/flb_kube.db
        Mem_Buf_Limit  5MB
    [FILTER]
        Name           kubernetes
        Match          kube.*
        Kube_URL       https://kubernetes.default.svc:443
        Merge_Log On
    [Output]
        Name loki
        Match *
        Url http://loki-headless.bpc-logging:3100/loki/api/v1/push
        Labels {job="fluent-bit"}
        RemoveKeys kubernetes,stream
        LabelMapPath /fluent-bit/etc/labelmap.json
        LineFormat json
        LogLevel warn
  parsers.conf: |-
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
  labelmap.json: |-
    {
      "kubernetes": {
        "container_name": "container",
        "host": "node",
        "labels": {
          "app": "app",
          "release": "release"
        },
        "namespace_name": "namespace",
        "pod_name": "instance"
      },
      "stream": "stream"
    }
`

`
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluent-bit-loki
  namespace: bpc-logging
  labels:
    app: fluent-bit-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      app: fluent-bit
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fluent-bit
        version: v1
        kubernetes.io/cluster-service: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2020"
        prometheus.io/path: /api/v1/metrics/prometheus
    spec:
      containers:
      - name: fluent-bit-loki
        image: grafana/fluent-bit-plugin-loki:1.5.0-amd64
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 2020
            name: http-metrics
        volumeMounts:
          - name: config
            mountPath: /fluent-bit/etc
          - name: run
            mountPath: /run/fluent-bit
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: 
        resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
      terminationGracePeriodSeconds: 10
      volumes:
      - name: config
        configMap:
          name: fluent-bit-loki-config
      - name: run
        hostPath:
          path: /run/fluent-bit
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      serviceAccountName: fluent-bit
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
`
`
apiVersion: v1
kind: Secret
metadata:
  name: loki
  namespace: bpc-logging
  labels:
    app: loki
stringData:
  loki.yaml: |-
      auth_enabled: false
      ingester:
        chunk_idle_period: 3m
        chunk_block_size: 262144
        chunk_retain_period: 1m
        max_transfer_retries: 0
        lifecycler:
          ring:
            kvstore:
              store: inmemory
            replication_factor: 1
      limits_config:
        enforce_metric_name: false
        reject_old_samples: true
        reject_old_samples_max_age: 168h
      schema_config:
        configs:
        - from: 2018-04-15
          store: boltdb
          object_store: filesystem
          schema: v9
          index:
            prefix: index_
            period: 168h
      server:
        http_listen_port: 3100
      storage_config:
        boltdb:
          directory: /data/loki/index
        filesystem:
          directory: /data/loki/chunks
      chunk_store_config:
        max_look_back_period: 0s
      table_manager:
        retention_deletes_enabled: false
        retention_period: 0s
`
`
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  namespace: bpc-logging
  labels:
    app: loki
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: loki
  serviceName: loki-headless
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: loki
        name: loki
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "http-metrics"
    spec:
      serviceAccountName: loki
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      containers:
        - name: loki
          image: grafana/loki:1.5.0
          imagePullPolicy: IfNotPresent
          args:
            - "-config.file=/etc/loki/loki.yaml"
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: storage
              mountPath: "/data"
          ports:
            - name: http-metrics
              containerPort: 3100
              protocol: TCP
          livenessProbe:
            httpGet:
                path: /ready
                port: http-metrics
            initialDelaySeconds: 45
          readinessProbe:
            httpGet:
                path: /ready
                port: http-metrics
            initialDelaySeconds: 45
          resources:
            limits:
                cpu: 200m
                memory: 256Mi
            requests:
                cpu: 100m
                memory: 128Mi
          securityContext:
            readOnlyRootFilesystem: true
      volumes:
        - name: config
          secret:
            secretName: loki
        - name: storage
          emptyDir: {}
`

**Comment by joker9357** [comment]
I tried /loki/api/prom/push and /loki/api/v1/push, neither of them can work

**Comment by jumping** [comment]
same issues, any solutions ?

**Comment by cyriltovena** [comment]
Have you tried to curl see if the problem is elsewhere?
