### ISSUE TITLE
Tailing Logs from an API

### ISSUE THREAD

**Issue by krishnapatamsettisonos** [grafana/loki#2188]
**Is your feature request related to a problem? Please describe.**
We are using Loki as our logging system and its working great. Thanks for the open-source tool. As we progress, we have new requirements regarding the logs. We are planning to get logs to Loki from a partner who offers system logs via an API call. I know that Loki works on the base of an agent that needs to be installed on the host machine. But, it would be great if we have an ability to tail the logs in Live from an external API call. 

**Describe the solution you'd like**
Looking for something that Loki can tail the logs from an API call and with a poll duration set to 1m,5m, 30 minutes, Live durations, etc.

**Comment by slim-bean** [comment]
Glad you are enjoying Loki!!

We've seen similar requests before however I'm not quite sure how we would implement something like this.

There are an incredible number of API designs and types out there with almost a dozen authentication schemes.   It would be a massive undertaking to try to build a tool which could support this in a generic sense.

The [Loki push api](https://github.com/grafana/loki/blob/master/docs/api.md#post-lokiapiv1push) is fairly simple, perhaps you can build a small app which is catered for the specific API in question, polls it, and in turn just pushes the results to Loki?
