### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by sandstrom** [grafana/loki#219]
This is a great project! 🐋 

When following it from a distance, it isn't that easy to know what's going on. Have you thought about adding a changelog?

The format suggested on this page is pretty good:
https://keepachangelog.com/en/1.0.0/

**Comment by sandstrom** [comment]
Remove stale label, please 😄

**Comment by sh0rez** [comment]
Hi!
We actually do have a `CHANGELOG.md` since our second release. You can find it here: https://github.com/grafana/loki/blob/master/CHANGELOG.md
