### ISSUE TITLE
[Docs] Multiples docker-driver configuration

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#2198]
**Describe the bug**
We currently have 2 places for docker-driver documentation [here](https://github.com/grafana/loki/tree/master/cmd/docker-driver/README.md) and [there](https://github.com/grafana/loki/tree/master/docs/clients/docker-driver).

This is confusing.

**Expected behavior**
We should merge everything in docs/clients/docker-driver and in the https://github.com/grafana/loki/tree/master/cmd/docker-driver/README.md we should just reference that the docs are at https://github.com/grafana/loki/tree/master/docs/clients/docker-driver

/cc @oddlittlebird @theMercedes WDYT ?

**Comment by oddlittlebird** [comment]
Is there a difference between the Docker Driver Client and the Docker Logging Driver?

**Comment by cyriltovena** [comment]
None !

**Comment by cyriltovena** [comment]
Plus some docs is duplicates.

**Comment by oddlittlebird** [comment]
In that case, I agree that the content should be merged. However, one topic would be crazy long. It should be something like:

Docker Driver Client - concept info, explain what this is and why you use it
- Install Docker Driver Client
- Uninstall Docker Driver Client
- Upgrade Docker Driver Client
- Configure Docker Driver Client (this might be more than one)
- Docker Driver Client options (to hold that long table in the middle of things)
- Troubleshoot Docker Driver Client

@theMercedes, thoughts?
