### ISSUE TITLE
Do the FORWARD vs BACKWARD direction client side

### ISSUE THREAD

**Issue by gouthamve** [grafana/loki#22]
Doing it server-side is a little complicated and takes some extra effort. We compress in-order and when we read back, we just stream through the chunk bytes. Now if we want to support backward direction, we need to first get all the data in-mem in forward direction and then loop backward.

Now this means we might be deflating and holding MBs more than we need to in the ingesters. This task can be effectively delegated to the client itself.

**Comment by tomwilkie** [comment]
@gouthamve WDYT?  Should I close?

**Comment by gouthamve** [comment]
Yes
