### ISSUE TITLE
The documentation needs an example of usage of Golang client library

### ISSUE THREAD

**Issue by afiskon** [grafana/loki#220]
Hello,

We would like to use Loki in our project https://github.com/insolar/insolar

The documentation https://github.com/grafana/loki/blob/master/docs/api.md suggests to use Golang client library but doesn't provide an example of how to do it. I tried to figure it out by looking at the code and found it to be not the easiest task.

Here is what I ended up with:

```
package main

import (
	"flag"
	"fmt"
	"github.com/prometheus/common/model"
	"github.com/sirupsen/logrus"
	"log"
	"os"
	"time"

	"github.com/grafana/loki/pkg/promtail"
	kit "github.com/go-kit/kit/log/logrus"
)

func main() {
	log := logrus.New()

	var lokiFlags flag.FlagSet
	err := lokiFlags.Set("client.url", "http://localhost:3100")
	if err != nil {
		log.Fatalf("lokiFlags.Set: %s\n", err)
	}

	// default values for client.batch-wait (1 sec)
	// and client.batch-size-bytes (100 KB) seem to be OK

	var cfg promtail.ClientConfig
	cfg.RegisterFlags(&lokiFlags)

	loki, err := promtail.NewClient(cfg, kit.NewLogrusLogger(log))
	if err != nil {
		log.Fatalf("promtail.NewClient: %s\n", err)
	}

//	err := loki.Handle(nil /* ??? */, "Hello world!")
//	if err != nil {
//		log.Fatalf("loki.Handle: %s\n", err)
//	}
}
```

The first issue I discovered is that I can't create ClientConfig directly, because it's URL field is a structure of a vendored package. Thus I had to use a workaround with `cfg.RegisterFlags`. The second issue is the following. It seems that to submit a log entry to promtail I have to call `loki.Handle`. However it's first argument is also a structure from a vendored packet. Thus I get:

```
./main.go:36:35: cannot use "github.com/prometheus/common/model".LabelSet literal (type "github.com/prometheus/common/model".LabelSet) as type "github.com/grafana/loki/vendor/github.com/prometheus/common/model".LabelSet in argument to loki.Handle
```

or:

```
main.go:6:2: use of vendored package not allowed
```

... if I try to import "github.com/grafana/loki/vendor/github.com/prometheus/common/model" instead of "github.com/prometheus/common/model".

Could you please provide an example of how the Golang client library actually supposed to be used?

**Comment by vtolstov** [comment]
nice thing to have...

**Comment by regardfs** [comment]
> Hello,
> 
> We would like to use Loki in our project https://github.com/insolar/insolar
> 
> The documentation https://github.com/grafana/loki/blob/master/docs/api.md suggests to use Golang client library but doesn't provide an example of how to do it. I tried to figure it out by looking at the code and found it to be not the easiest task.
> 
> Here is what I ended up with:
> 
> ```
> package main
> 
> import (
> 	"flag"
> 	"fmt"
> 	"github.com/prometheus/common/model"
> 	"github.com/sirupsen/logrus"
> 	"log"
> 	"os"
> 	"time"
> 
> 	"github.com/grafana/loki/pkg/promtail"
> 	kit "github.com/go-kit/kit/log/logrus"
> )
> 
> func main() {
> 	log := logrus.New()
> 
> 	var lokiFlags flag.FlagSet
> 	err := lokiFlags.Set("client.url", "http://localhost:3100")
> 	if err != nil {
> 		log.Fatalf("lokiFlags.Set: %s\n", err)
> 	}
> 
> 	// default values for client.batch-wait (1 sec)
> 	// and client.batch-size-bytes (100 KB) seem to be OK
> 
> 	var cfg promtail.ClientConfig
> 	cfg.RegisterFlags(&lokiFlags)
> 
> 	loki, err := promtail.NewClient(cfg, kit.NewLogrusLogger(log))
> 	if err != nil {
> 		log.Fatalf("promtail.NewClient: %s\n", err)
> 	}
> 
> //	err := loki.Handle(nil /* ??? */, "Hello world!")
> //	if err != nil {
> //		log.Fatalf("loki.Handle: %s\n", err)
> //	}
> }
> ```
> 
> The first issue I discovered is that I can't create ClientConfig directly, because it's URL field is a structure of a vendored package. Thus I had to use a workaround with `cfg.RegisterFlags`. The second issue is the following. It seems that to submit a log entry to promtail I have to call `loki.Handle`. However it's first argument is also a structure from a vendored packet. Thus I get:
> 
> ```
> ./main.go:36:35: cannot use "github.com/prometheus/common/model".LabelSet literal (type "github.com/prometheus/common/model".LabelSet) as type "github.com/grafana/loki/vendor/github.com/prometheus/common/model".LabelSet in argument to loki.Handle
> ```
> 
> or:
> 
> ```
> main.go:6:2: use of vendored package not allowed
> ```
> 
> ... if I try to import "github.com/grafana/loki/vendor/github.com/prometheus/common/model" instead of "github.com/prometheus/common/model".
> 
> Could you please provide an example of how the Golang client library actually supposed to be used?

hi, have u ever write an example? I met the same error..

**Comment by cyriltovena** [comment]
We're building a client that will have way less dependency.

In the meantime I think you need all the same replace directive in go.mod as we have in our go.mod.

**Comment by cyriltovena** [comment]
here is the work in progress https://github.com/grafana/loki-client-go
