### ISSUE TITLE
Host detection issue on Amazon Linux 1

### ISSUE THREAD

**Issue by devblueray** [grafana/loki#2203]
Adding this per @cyriltovena 
**Describe the bug**
Amazon Linux 1 removes the domain name when it sets the host name which prevents you from using ec2_sd_configs to get the host tags because the hostname needs to match a tag and the only tag available is __meta_ec2_private_dns_name which matches the hostname on Amazon Linux 2 but not 1.

Ex: 
AL1: ip-10-10-10-10
AL2: ip-10-10-10-10.ec2.internal

**To Reproduce**
1. Create an Amazon Linux 1 instance 
2. Install and run promtail with the attached config.
3. Log into promtail console > service discovery and you will see "Dropped: ignoring target, wrong host" under the entry for your host  
4. Edit /etc/sysconfig/network and change HOSTNAME=the value from __meta_ec2_private_dns_name and reboot
5. Run hostname to verify that it matches the __meta_ec2_private_dns_name tag
6. Run promtail and repeat step 3, you will now see your host has been found and can be seen under targets.

**Expected behavior**
Should ignore the domain name on AL1 instances so it sees ip-10-10-10-10 as a valid host match for ip-10-10-10-10.ec2.internal (or whatever domain you have)

**Environment:**
- Infra: Elastic Beanstalk Docker (EC2/ASG/ALB)
- Deployed via eb deploy command

**Screenshots, Promtail config, or terminal output**
`server:
    http_listen_port: 9080
    grpc_listen_port: 0

positions:
    filename: /var/log/positions.yaml # This location needs to be writeable by promtail.

client:
    url: http://loki:3100/loki/api/v1/push

scrape_configs:
    - job_name: access_logs
      ec2_sd_configs:
      - region: us-east-1
        port: 9100
      relabel_configs:
      - action: replace
        regex: '.*'
        replacement: /home/ec2-user/log
        target_label: __path__
      - source_labels: [__meta_ec2_private_dns_name]
        regex: '(.*)'
        target_label: __host__
`

**Comment by cyriltovena** [comment]
```
   - source_labels: [__meta_ec2_private_dns_name]
        regex: "(.*)"
        replacement: '${1}.ec2.internal'
        target_label: __host__
```

This should help overcome the problem.

**Comment by adsanz** [comment]
For folks arriving here for the same issue, you might need to change the above answer for something like this:

```yaml
      - source_labels: [__meta_ec2_private_dns_name]
        regex: "(.*).us-west-2.compute.internal"
        replacement: '${1}'
        target_label: __host__
```
(replacement is optional)
