### ISSUE TITLE
Promtail keeps handles on log files on Windows preventing deletion of parent directories

### ISSUE THREAD

**Issue by swisspol** [grafana/loki#2209]
**Describe the bug**
We use Promtail with static configs to monitor log files of temporary jobs on Windows machines. For instance:

```
- targets:
    - localhost
  labels:
    job: allocs
    __path__: Z:/Nomad/alloc/**/alloc/logs/*.0
```

The bug is that if the owner app of the log closes the log file then try tries to delete the parent directory (or you try directly in PowerShell): it will fail saying the directory is "locked" even though it's empty in Windows Explorer. That's because Promtail is still watching the log file and has a handle to it. The only way to be able to delete the directory is to stop Promtail.

**To Reproduce**
(see above)

**Expected behavior**
Promtail detects that a log file is deleted or closed by its own and closes it as well, releasing its handle on it.

**Environment:**
- Promtail 1.5.0
- Windows Server 2019 standard AMI in AWS

**Screenshots, Promtail config, or terminal output**
n/a

**Comment by swisspol** [comment]
Anyone?

**Comment by swisspol** [comment]
Hello?

**Comment by swisspol** [comment]
Does anyone even care?

**Comment by mateinavidad** [comment]
I am seeing a similar behaviour. Promtail keeps handles on logfiles which leads to failures when trying to remove the containers. 
```
Error waiting for container: unable to remove filesystem for 7ae7acd975a9c2890e1452c38bbea4b2d69a6c5a7a85726faf336ae6477f4554: CreateFile C:\\ProgramData\\docker\\containers\\7ae7acd975a9c2890e1452c38bbea4b2d69a6c5a7a85726faf336ae6477f4554\\7ae7acd975a9c2890e1452c38bbea4b2d69a6c5a7a85726faf336ae6477f4554-json.log: Access is denied.
```

Any feedback here ?

**Comment by zlepper** [comment]
We are seeing more than just it keeping the directories locked, it's also keeping the files themselves locked, which is preventing both automatic and manual cleanup... I have now seen more than one case of our server dying because we cannot cleanup log files, and thus running out of disk space...
