### ISSUE TITLE
Enforce query legend when using Loki as Data Source

### ISSUE THREAD

**Issue by alecrux** [grafana/loki#2210]
When creating a Query using a Prometheus Data Source, you have the option to enforce a Legend.
![image](https://user-images.githubusercontent.com/35157010/84540786-1be85580-acc4-11ea-9211-2f4f9afdbb0d.png)

But when creating a Query using a Loki Data Source, there is no such option.
![image](https://user-images.githubusercontent.com/35157010/84541133-c496b500-acc4-11ea-8aa6-46c745c08f5a.png)

I would like to see the "legend" fields, the same way it looks when selecting a Prometheus Data Source.

I've considered improving the labeling of my logs, but I've been building some dashboards that perform filtering, not only on labels, but on message content as well, such as this:
`{app="cassandra"} |~ "(duration|latency)s*(=|is|of)s*[d.]+"`
That feature would be very helpful in that case.

Maybe the way I built my Dashboards goes against Loki best practices, so any advice would be appreciated.

**Comment by cyriltovena** [comment]
This now possible with the latest Grafana

**Comment by alecrux** [comment]
I just updated my environment to the most recent version of Grafana (v.7.1.1) but there is still no "Legend" field available when selecting Loki as a data source.

@cyriltovena, which version are you talking about exactly?

**Comment by cyriltovena** [comment]
![image](https://user-images.githubusercontent.com/1053421/88604752-1bbed200-d046-11ea-9ec9-10593e06c69d.png)

I'm running Grafana v7.2.0-f406815cpre (0d933b79b7) but pretty sure it has been added on 7.1.1

**Comment by alecrux** [comment]
@cyriltovena never mind. It was due to a browser cache issue. It's present in v7.1.1 (3039f9c3bd). Thanks!

**Comment by raffraffraff** [comment]
If anyone else is having the issue and used the latest helm chart, your `image.pullPolicy` might need a tweak

**Comment by ruanbekker** [comment]
for anyone running into this, I've bumped up to `grafana/grafana:7.1.5` and I can confirm the legend input is there.
