### ISSUE TITLE
Add uuid-type variable to fluentd-loki or fluentbit-loki plugin

### ISSUE THREAD

**Issue by gabrielvieira10** [grafana/loki#2213]
Recently I got a problem with loki where I try to pass logs from fluentbit to loki, but it gets out-of-order error when receiving logs from multiple sources.
To fix it I tried to use fluentd to aggregate the logs, but since my project is expected to scale a lot, multiple fluentd will be necessary, thus coming back to the same problem.

So I thought in changing the label value to to a random uuid for each log in fluentd, then loki will not recognize it as out-of-order, and for my application it does not matter.
I think this feature still does not exist, so I'd like to request it.

The idea is similar to this one:
https://github.com/sonots/fluent-plugin-record-reformer/issues/6
The merge request generated from this issue(was rejected, but might serve as reference):
https://github.com/sonots/fluent-plugin-record-reformer/pull/7/files

If implemented to fluent-bit loki plugin it would also solve my problem.

**Comment by adityacs** [comment]
@gabrielvieira10 Adding `uuid` for each log would not be a good idea as it induces very high cardinality.  I would rather suggest you add some extra labels using `Labels` available in `fluent-bit` configuration to the different fluent bit instances you are running. So, that way the logs from different sources would be having unique labels.

**Comment by gabrielvieira10** [comment]
@adityacs 
Thanks, that is a great idea!
I'll try to add these labels. As far as I know I can only add the labels manually for every container or through environments variables, right?
Since my system needs to scale, I plan to set through environments variables.
If there is any other easier method please let me know.

**Comment by adityacs** [comment]
> even if it's like 1 hour later than the previous log

I guess you meant 1 hour earlier.

I believe fluent-bit supports multiple `input` and `output`. If you exactly know which files might cause this problem, you can configure multiple `input` specifying each file and `tag` separately and correspondingly configure outputs matching those tags with extra labels to it.

I am not aware of any other better way.
