### ISSUE TITLE
Explore does not list Loki datasource

### ISSUE THREAD

**Issue by christiangroth** [grafana/loki#223]
Hi,

I tried Loki but have some difficulties getting it to work. I'm using the docker-compose stack mentioned at https://github.com/grafana/loki/tree/master/production#run-locally-using-docker

The stack starts and runs without errors, I can login to Grafana and add the Loki datasource and testing the datasource is okay. When I switch to explore view I only get the message: "Please add a datasource that supports Explore (e.g., Prometheus)."

Am I missing something?

Grafana v5.5.0-pre1 (commit: 8fef213)

**Comment by christiangroth** [comment]
When adding a second Loki datasource using the exact same definition, the explore page works. Removing one of the datasources again, explore stops working. It seems to be a bug when having a single loki datasource only, and no other datasources.

**Comment by davkal** [comment]
Just tried with Grafana v5.5.0-pre1 (3581d61), it works there.

**Comment by davkal** [comment]
Can repro in grafana/grafana@8fef213

**Comment by davkal** [comment]
Issue moved to [grafana/grafana #14926](https://github.com/grafana/grafana/issues/14926) via [**ZenHub**](https://www.zenhub.com/)

**Comment by davkal** [comment]
Fixed now in `master`.

**Comment by daixiang0** [comment]
@davkal hi, seems that grafana/grafana:latest do not update, still no loki entry.

**Comment by davkal** [comment]
@daixiang0 you need `grafana/grafana:master` for now.

**Comment by daixiang0** [comment]
@davkal please update lastest tag since it is the default.
