### ISSUE TITLE
PodSecurityPolicy is a cluster-wide resource and should not have a namespace field

### ISSUE THREAD

**Issue by chauffer** [grafana/loki#2234]
From https://kubernetes.io/docs/concepts/policy/pod-security-policy/:
>A Pod Security Policy is a **cluster-level** resource that controls security sensitive aspects of the pod specification.

Examples as to where it's set: https://github.com/grafana/loki/blob/e2a7941e326a57f2c42de1d26f4cb198e2a199cb/production/helm/loki/templates/podsecuritypolicy.yaml#L6

This is an issue when using the manifests through other tools such as Terraform where they hit different API endpoints when a resource is expected to be cluster-wide or namespace-wide, thus resulting in errors until manually fixing the manifests.

**Comment by chauffer** [comment]
ClusterRole in promtail is also an offender
https://github.com/grafana/loki/blob/e2a7941e326a57f2c42de1d26f4cb198e2a199cb/production/helm/promtail/templates/clusterrole.yaml#L11

**Comment by cyriltovena** [comment]
Thanks for reporting! If you want to contribute that’s an easy one ;)
