### ISSUE TITLE
Docker swarm support

### ISSUE THREAD

**Issue by anjmao** [grafana/loki#224]
Hi, I'm using docker swarm cluster instead of kubernetes because for simpler apps kubernetes is just a huge overkill. Is there any plans, examples for setting up loki to fetch logs from docker containers? I'm also interested in contribution to support docker swarm. Ideally I would like to put labels on my docker compose files so promtail could fetch the logs.

**Comment by davkal** [comment]
Promtail is responsible for applying labels to log streams. It's using Prometheus' service discovery code (hence the name promtail) to automatically determine the label for a stream. Prometheus does not support service discovery for docker or swarm: https://github.com/prometheus/prometheus/issues/1766

If you look at that issue, some efforts are being made to use a sidecar to generate a static config. This could work, but is has not been tried.

**Comment by SvenDowideit** [comment]
@anjmao I am using Docker Swarm, and am using the `journald` log driver configured in the daemon - then fluentd to pick those up from each node and push them to loki. It works pretty well imo

with that config, your compose file's `logging.options.tag` settings are used, and can be seen in the grafana explore UI

see the README at https://github.com/grafana/loki/tree/master/fluentd/fluent-plugin-loki

**Comment by Kuqd** [comment]
This is ready see https://github.com/grafana/loki/blob/master/cmd/docker-driver/README.md
