### ISSUE TITLE
Comparison operators ignores 0 lines

### ISSUE THREAD

**Issue by andreykud** [grafana/loki#2240]
I'm trying to use new feature in master, "comparsion operators", it filters good, but it always adds zero rows to result

promtail and loki version - last master on this date

Can you please help, what i do wrong?
Example of query is here:

![image](https://user-images.githubusercontent.com/23506848/85110442-9876b900-b21b-11ea-82c4-cb5f3e11f38c.png)

**Comment by cyriltovena** [comment]
Just to add more details , can you tell us what you expect? Thank you /cc @owen-d

**Comment by owen-d** [comment]
Hm, this is weird. I was able to produce something similar in Grafana, but it appears to be a visual bug -- opening the network tab shows data as expected.

![image](https://user-images.githubusercontent.com/8173478/85132021-fa2c2880-b205-11ea-8762-88a1c0a026b4.png)

vs 
![image](https://user-images.githubusercontent.com/8173478/85132105-1e880500-b206-11ea-8ba8-be5340ce133c.png)

and 
![image](https://user-images.githubusercontent.com/8173478/85132124-2647a980-b206-11ea-968b-00e6594b0a21.png)


One unrelated bit: it seems to drop labels in the table on my grafana but not in your example.
P.S. the count aggregates the count of streams, not the count of log entries. For that you'll want `count_over_time`. Your example made me think you're looking for count_over_time, but I could be wrong.

/cc @davkal Heads up

**Comment by andreykud** [comment]
@cyriltovena thank you for reply. I'm trying to print count of custom filtered label (action is logon or logoff in this case) in logs and exclude records without them.
@owen-d thank you for reply. You are right, it seems it is trouble with visualization. Maybe you know how zero values can be hidden? I would be very grateful if you can prompt how to do it.

**Comment by slim-bean** [comment]
Might be related to https://github.com/grafana/grafana/issues/25553 ?
