### ISSUE TITLE
Https s3 access

### ISSUE THREAD

**Issue by mrmassis** [grafana/loki#2244]
Hi,
I want to store Chunks in a s3 storage. I use the ceph and https.
I can't find a way to config. 
The aws.s3 didn't work for me. Only in http way.
How I can't connect to ceph via https.
Tkz

**Comment by mrmassis** [comment]
@ThoreKr can I resolve your problem?

**Comment by mrmassis** [comment]
Can you*

**Comment by ThoreKr** [comment]
The config I'm using is mentioned in https://github.com/grafana/loki/issues/1051#issuecomment-646923354

**Comment by slim-bean** [comment]
Thanks @ThoreKr ❤️ 

@mrmassis did the config @ThoreKr provided work for you? Can we close this?

**Comment by mrmassis** [comment]
Yes, tkz a lot.
