### ISSUE TITLE
Problem with Getting Started Docs for AWS

### ISSUE THREAD

**Issue by ghostsquad** [grafana/loki#2257]
https://github.com/grafana/loki/blob/v1.5.0/docs/installation/tanka.md?ts=4

There are several problems with the page here:

1. defaults don't work. I had to add the following in order to get Loki to deploy without crashing:

```
   loki+: {
      chunk_store_config+: {
        max_look_back_period: "0s",
      },
      table_manager+: {
        retention_period: "0s",
      },

      schema_config+: {
        configs: [{
          from: '2020-05-15',
          store: 'aws',
          object_store: 's3',
          schema: 'v11',
          index: {
            prefix: '%s_index_' % $._config.table_prefix,
            period: '%dh' % $._config.index_period_hours,
          },
        }],
      },
    },
```

the `s3_address` key is misleading. This is not the address, but actually just the "region"

```
s3_address: 'us-west-2',
```

I found this out by looking in `loki/config.libsonnet`

```
client_configs: {
  s3: {
    s3forcepathstyle: $._config.s3_path_style,
  } + (
    if $._config.s3_access_key != '' then {
      s3: 's3://' + $._config.s3_access_key + ':' + $._config.s3_secret_access_key + '@' + $._config.s3_address + '/' + $._config.s3_bucket_name,
    } else {
      s3: 's3://' + $._config.s3_address + '/' + $._config.s3_bucket_name,
    }
  ),
```

and cross referencing with this example configuration:
https://github.com/grafana/loki/blob/master/docs/configuration/examples.md?ts=4

**Comment by ysaakpr** [comment]
Yes, on internet there is no term used so called s3_address, either it should be a full s3 bucket URL else a bucket and region.

**Comment by ghostsquad** [comment]
Not stale

**Comment by ghostsquad** [comment]
Not stale

**Comment by dgzlopes** [comment]
Not stale

**Comment by ksiadz** [comment]
it seems to still be an issue

**Comment by ghostsquad** [comment]
Stale bot is annoying isn't it?
