### ISSUE TITLE
Docs seems to be missing/inaccurate for Tanka + FluentBit Installation

### ISSUE THREAD

**Issue by ghostsquad** [grafana/loki#2262]
After reading this page on getting started with FluentBit:

https://github.com/grafana/loki/blob/master/cmd/fluent-bit/README.md?ts=4

It's leading me to send traffic to `loki:3100` by default. But The installation I have from Tanka doesn't include a `Loki` server specifically. It's broken out:

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/903488/85605832-67292f00-b607-11ea-83b4-00d683a120d2.png">

It's not entirely clear where I should be pointing fluentbit at. I'm assuming `ingester` based on the name. Anyways... I think there's a lot to be desired of the documentation.

I'm happy to help contribute if that's something that would help.

**Comment by ghostsquad** [comment]
pointing at the ingester leaves me with logs from fluentbit like this:

```
level=error caller=client.go:247 id=0 component=client host=ingester.loki.svc.cluster.local:80 msg="final error sending batch" status=404 error="server returned HTTP status 404 Not Found (404): 404 page not found"
```

**Comment by cyriltovena** [comment]
You should send logs to distributors.

**Comment by ghostsquad** [comment]
Yep, I figured that out. I'm happy to help contribute to the documentation when I have the chance. Mind leaving this open?

**Comment by GrafanaWriter** [comment]
I believe we now have [updated documentation ](https://grafana.com/docs/loki/latest/clients/fluentbit/)@ghostsquad, so I will close.
