### ISSUE TITLE
Following local.md

### ISSUE THREAD

**Issue by flopp999** [grafana/loki#2276]
**Describe the bug**
Starting in Linux steps are not correct or?

https://github.com/grafana/loki/blob/master/docs/installation/local.md

Is says
"6. Enter the following command to start Loki:

**Windows**

```
.\loki-windows-amd64.exe --config.file=loki-local-config.yaml
```

**Linux**
```
./promtail-linux-amd64 -config.file=promtail-local-config.yaml
```
"

So for Windows we starta Loki and for Linux we start Promtail?

**Comment by owen-d** [comment]
Thanks!
