### ISSUE TITLE
server returned HTTP status 400 Bad Request (400): sample for 'logs' has timestamp too new: 1593500259515

### ISSUE THREAD

**Issue by cbmyfirst** [grafana/loki#2278]
**Describe the bug**
Not worked fine under different machie, please help, thanks in advance!!

**Loki(172.18.188.64), promtail(172.18.188.50) run as docker, docker image is both latest**
loki-config.yml as below:

> auth_enabled: false
> 
> server:
>   http_listen_port: 3100
> 
> ingester:
>   lifecycler:
>     address: 127.0.0.1
>     ring:
>       kvstore:
>         store: inmemory
>       replication_factor: 1
>     final_sleep: 0s
>   chunk_idle_period: 5m
>   chunk_retain_period: 30s
>   max_transfer_retries: 0
> 
> schema_config:
>   configs:
>     - from: 2018-04-15
>       store: boltdb
>       object_store: filesystem
>       schema: v11
>       index:
>         prefix: index_
>         period: 168h
> 
> storage_config:
>   boltdb:
>     directory: /loki/index
> 
>   filesystem:
>     directory: /loki/chunks
> 
> limits_config:
>   enforce_metric_name: false
>   reject_old_samples: true
>   reject_old_samples_max_age: 168h
> 
> chunk_store_config:
>   max_look_back_period: 0s
> 
> table_manager:
>   retention_deletes_enabled: false
>   retention_period: 0s
>   chunk_tables_provisioning:
>     inactive_read_throughput: 0
>     inactive_write_throughput: 0
>     provisioned_read_throughput: 0
>     provisioned_write_throughput: 0
>   index_tables_provisioning:
>     inactive_read_throughput: 0
>     inactive_write_throughput: 0
>     provisioned_read_throughput: 0
>     provisioned_write_throughput: 0
>   retention_deletes_enabled: false
>   retention_period: 0

promtail-config.yml as below:

> server:
>   http_listen_port: 9080
>   grpc_listen_port: 0
>   #disable: false
> 
> positions:
>   filename: /tmp/positions.yaml
> 
> clients:
>   - url: http://172.18.188.64:3100/loki/api/v1/push
> 
> scrape_configs:
> - job_name: system
>   pipeline_stages:  
>   static_configs:
>   - targets:
>      - localhost
>     labels:
>       job: scilogs
>       host: sci_v1
>       __path__: /var/log/nginx/error.log

**Environment:**
docker & docker-compose

**Screenshots, Promtail config, or terminal output**
![image](https://user-images.githubusercontent.com/5827478/86095630-cc3bc380-bae4-11ea-886b-7457b7b39c01.png)
![image](https://user-images.githubusercontent.com/5827478/86095676-db227600-bae4-11ea-8eaf-c562f0e6a41e.png)
![image](https://user-images.githubusercontent.com/5827478/86095743-f42b2700-bae4-11ea-817f-6984ad9932fd.png)

**Comment by adityacs** [comment]
Looks like your systems `172.18.188.64 ` and `172.18.188.50` are out of sync in time by more than 10mins. Could you please verify this?

**Comment by cbmyfirst** [comment]
> Looks like your systems `172.18.188.64 ` and `172.18.188.50` are out of sync in time by more than 10mins. Could you please verify this?

Yes, you are right, YOUR answer is very helpful for me, thanks you very much!
