### ISSUE TITLE
runtime: program exceeds 10000-thread limit

### ISSUE THREAD

**Issue by oskoi** [grafana/loki#228]
I'm trying to search logs for a day and get this...
[loki.log](https://github.com/grafana/loki/files/2774651/loki.log)

loki:
repository: grafana/loki
tag: master

promtail:
repository: grafana/promtail
tag: master 

for installation used helm https://github.com/grafana/loki/tree/master/production/helm

**Comment by daixiang0** [comment]
Could you share more details? Maybe the way to reproduce?

**Comment by tomwilkie** [comment]
Going to close as a dupe of #227
