### ISSUE TITLE
Better enable discovering dropped log lines

### ISSUE THREAD

**Issue by owen-d** [grafana/loki#2280]
Finding dropped log lines has proved a problem for many. We've been hesitant to log these at the API level due to cluttering concerns. Currently there are metrics in place for the intersection of `tenant,reason` concerning dropped lines, but we should consider better enabling the use case of finding these.

Perhaps we can log the label sets at the promtail level?

**Comment by slim-bean** [comment]
The error message we return to the client is fairly descriptive for these dropped lines:

https://github.com/grafana/loki/blob/272a89c13df853a69ef50a53172ce5309c8f36a1/pkg/util/validation/validate.go#L15-L41

I'm reasonably sure we log this in promtail but I haven't verified this in a while, would be worth doing.

**Comment by slim-bean** [comment]
One area we should improve here is the promtail_mixin in this regard, the dashboard and metrics (as well as alerts) should be updated to give some better visibility here.

It's tricky though because of the batched nature of promtail pushes, when we get an error back we don't know how much of the batch succeeded vs failed.  Loki doesn't provide that currently and it's not easy to fix this...

**Comment by owen-d** [comment]
I think this will be greatly helped by LogQL v2's addition of metric extraction + an exported dashboard.

**Comment by piroux** [comment]
Moreover, I would really love to be able generate metrics, in a `match` block, on some filtered logs, which I am dropping intentionally.
Right now, as written in the docs, this is not possible with the [current behaviour](https://github.com/grafana/loki/blob/de644b52c3389833b94435eaef548dfc3d2c38d7/docs/clients/promtail/stages/match.md#schema) of the `drop` action:
```
When set to drop, entries will be dropped and no later metrics will be recorded.
```

_I do not know if this is out of the scope of this issue, I guess you will tell me._

**Comment by LinTechSo** [comment]
Hi, any updates ?
