### ISSUE TITLE
No releases for loki-docker-driver on Docker Hub

### ISSUE THREAD

**Issue by till** [grafana/loki#2291]
Not sure if bug or feature, therefor I made it a question! ;-)

I checked here:
https://hub.docker.com/r/grafana/loki-docker-driver/tags

It seems the only available _releases_ are `latest` or `master-hash` builds.

Is it possible push tags from this repo to Docker hub as well — e.g. `x.y.z`? We are trying to figure out enable upgrades of the driver without causing a lot of downtime for our clusters. This would def help.

**Comment by cyriltovena** [comment]
Sure we can do this. cc @slim-bean 

In the meantime you can upgrade using the sha that goes with the release, not the best option for sure.

**Comment by avkonst** [comment]
Is it the last release is 1.5.0? I can see this image on docker hub.

**Comment by till** [comment]
It looks like they are there. I will close this ticket.
