### ISSUE TITLE
Buckets per tenant

### ISSUE THREAD

**Issue by mrmassis** [grafana/loki#2292]
Hi everyone,
Considering multiple prefixes in S3 it is not possible to do a good retention management. The S3 replace the lifecycle rules  files and no update it.

For example, if I have the following scenario:

1 tenants and a folder called test, the chunks would be stored inside
s3: // test / tenant1 / chunks-tenant1
We could apply retention in the tenant1 prefix. 

Now if a new tenant is created, tenant2.
s3: // test / tenant1 / chunks-tenant1
s3: // test / tenant2 / chunks-tenant2

If we wanted retention in tenant2 we would need to update the retention of tenant1 or it would be lost (considering s3).
This starts to get expensive, as the number of tenants goes up. As it is implemented today, there is no way to focus only on the rule of a given tenant. This would be easily worked around if each tenant was in a different bucket. It is possible?

Thank you

**Comment by owen-d** [comment]
Noted, this is definitely something we intend to improve.

**Comment by mrmassis** [comment]
I'm working in it. I'm writing a patch to do it

**Comment by mrmassis** [comment]
@owen-d I created a patch to enable one bucket per tenant. But, there is a restriction: the index bucket must be created before.

Now is enough setting S3 url without the bucket indicate.
What you thing about it

[bucket.patch.txt](https://github.com/grafana/loki/files/4881216/bucket.patch.txt)

**Comment by mrmassis** [comment]
I this way is possible set diferent polices without affect the other tenant.

**Comment by owen-d** [comment]
Thanks for your interest in contributing!

I think it'd be really nice to find a provider-agnostic way of doing this but perhaps if that isn't possible, we may do something like you've suggested. There's also been some talk of allowing even more granularity in retention controls than just _tenant_. For instance, label-matching based retention such that streams where `{env="dev"}` has less retention than `{env="prod"}`. Please join us on [slack](http://slack.grafana.com/) in #loki-dev, via our mailing list, and/or come to our next community call (the first Thursday of each month) if you'd like to discuss this further.

**Comment by mrmassis** [comment]
Os course,
Tkz for your considerations.
Regards

Ps: I'm available to help in loki grafana.

**Comment by LinTechSo** [comment]
HI, any updates?
