### ISSUE TITLE
 I want to know if there is any performance bottleneck for loki

### ISSUE THREAD

**Issue by MargeDog** [grafana/loki#2299]
Please ask questions you have in the mailing list: https://groups.google.com/forum/#!forum/lokiproject

I am currently trying to use loki as our online logging platform, but I don’t know if loki will have problems with too many log nodes causing slow response or even unable to get logs well, I hope that experienced friends can give me This can only suggest
Or join our #loki slack channel at http://slack.raintank.io/

**Comment by owen-d** [comment]
Thank you for your interest. This is a little difficult to answer and given that it's not an issue with the software, I'll be closing this issue.  However, Loki uses a push model for logs, where logs are collected by a component (`promtail`, our docker driver, `fluet{d,bit}`) and forwarded to Loki. As always, network issues that affect this flow can cause degradation of service.

Feel free to ask questions in the mailing list or on https://slack.grafana.com/
