### ISSUE TITLE
No Labels Found

### ISSUE THREAD

**Issue by nomatterz** [grafana/loki#2300]
**Describe the bug**
Grafana doesn't show labels in dropdown menu in Explore tab.
But I can query logs for example `{container="mongo"}` and get the results. So there are definitely existing labels. 

**Environment:**
 - Infrastructure: [Kubernetes]
 - Deployment tool: [helm]

**Screenshots, Promtail config, or terminal output**

![image](https://user-images.githubusercontent.com/48525503/86591355-1831b100-bf9a-11ea-87d6-aa965a85bd3d.png)

**Comment by owen-d** [comment]
A few things to try:

- Open the network tab and see if data is being returned but not displayed.
- Give the labels [API endpoint](https://github.com/grafana/loki/blob/master/docs/api.md#get-apipromlabel) a try and see if it returns any data (this will help determine if the problem is at the Grafana server layer). This can be done manually or via [logcli](https://github.com/grafana/loki/blob/master/docs/getting-started/logcli.md).

**Comment by nomatterz** [comment]
Hi @owen-d 
Those 2 checks confirmed there are labels in Loki
```
/ # ./logcli labels
http://loki.logging:3100/loki/api/v1/labels
__name__
app_kubernetes_io_instance
app_kubernetes_io_name
container
container_id
controller_revision_hash
host
namespace
pod
pod_id
pod_template_hash
statefulset_kubernetes_io_pod_name
```

![image](https://user-images.githubusercontent.com/48525503/86599969-0c4ceb80-bfa8-11ea-941c-3c3e18f2ba4c.png)

**Comment by owen-d** [comment]
This looks like it may be an issue between Loki & Grafana. What versions are you running?
/cc @davkal

**Comment by cyriltovena** [comment]
Definitely interesting 🧐 can you check for the /labels http call when you load the page or switch from one data source to another. The screenshot you have is for label values this one usually works fine.

What’s the time range when that happens 1h or 3h or 6h ? Can you set 1h and refresh the page ? What store schema are you using ? V9, v10 or v11 ?

**Comment by nomatterz** [comment]
@owen-d 
Grafana - Grafana v7.0.1 (ef5b586d7d)
Loki - v1.5.0
@cyriltovena 
```
schema_config:
  configs:
  - from: "2018-04-15"
    index:
      period: 168h
      prefix: index_
    object_store: filesystem
    schema: v9
    store: boltdb
```
This happens no matter  what time range is.
Regarding call to /labels if i get you correctly here is the result:
![image](https://user-images.githubusercontent.com/48525503/86748572-3dc7c480-c045-11ea-9a9e-61b77c3734e9.png)

**Comment by cyriltovena** [comment]
I think Owen fist intuition was right seem like a Grafana bug, have you to clear cache or incognito window ?

**Comment by aocenas** [comment]
@nomatterz can you check the console in the browser if there is any javascript errors there? Can't reproduce this with my local setup so far.

**Comment by nomatterz** [comment]
@cyriltovena 

Yes, sure

@aocenas 
At first there are no errors, but when i change timerange and start typing label name i get this:
![image](https://user-images.githubusercontent.com/48525503/86798414-6cf82900-c079-11ea-8d23-4973fe96e445.png)

**Comment by ivanahuckova** [comment]
Hi @nomatterz! 👋 I think that this issue might be similar to https://github.com/grafana/grafana/issues/26213. Basically, we weren't sending the time range when we were fetching labels and we always just fetched labels from the past 1 hour. Looking at the results from your print screen, I can see that the first log (and therefore also value) was from 2+ hours in the past, and therefore labels query probably didn't fetch it. This PR https://github.com/grafana/grafana/pull/26622 that will be part of 7.2 fixes it. I will close this issue for now, but if you will encounter this issue after 7.2,  please reopen it! 🙂

**Comment by nomatterz** [comment]
Hi @ivanahuckova 

Thank you for your input.
I think you're right with the cause of the issue.
I've just generated logs and checked Explore tab, all relevant labels are present.
![image](https://user-images.githubusercontent.com/48525503/90017220-dcce8480-dcb3-11ea-9449-e1336cfc02b8.png)

**Comment by ivanahuckova** [comment]
Awesome! 🙂 I am really glad it helped and thank you for confirming it. As mentioned, this fix will be part of 7.2 release.

**Comment by albrookesplowman** [comment]
Hi, was this fixed as we are running grafana 7.5.5 with loki 2.2.0 in kubernetes and we are getting labels disappearing and then re-appearing some time later before disappearing again.

Does anyone have any clues on a fix?

**Comment by ivanahuckova** [comment]
This was fixed in Grafana's 8.0.0-beta2 release.

**Comment by albrookesplowman** [comment]
@ivanahuckova  we are still running the same issue even when we have the 8.0.0-beta2 release installed.  Is there a version of Loki that is required too?

**Comment by ivanahuckova** [comment]
It should work with all Loki versions. Could you please comment on https://github.com/grafana/grafana/issues/32528 (closed issue) and share your network tab.
