### ISSUE TITLE
Use .git/objects-like way to organize data/chunks layout to reduce file number in same directory.

### ISSUE THREAD

**Issue by sesky4** [grafana/loki#2310]
**Is your feature request related to a problem? Please describe.**
Getting slower while more and more log lines coming.

**Describe the solution you'd like**
Use .git/objects-like way to organize data/chunks layout to reduce file number in same directory.
But since the chunk filename are likely having same prefix, maybe we should use suffix. 

layout eg.

- data
  - chunks
      - jAy
        - Y0Y
          - ZmFrZS9jMmVjY2RiODA4ODA5NjQ2OjE3MmEyNDZkZTRkOjE3MmEyNDczOTJjOjNiNj

so the full name of this chunk file is
`ZmFrZS9jMmVjY2RiODA4ODA5NjQ2OjE3MmEyNDZkZTRkOjE3MmEyNDczOTJjOjNiNj + Y0Y + jAy`

**Additional context**
Large number of files in same directory may affect performance on some filesystems.(I guess)

**Comment by cyriltovena** [comment]
Definitely something to work on. Thanks for the issue

**Comment by slim-bean** [comment]
This is still an issue/concern and we periodically discuss ways to handle this. I'm closing this issue for now as we are focusing on pruning our open issues list to be a small set of actively actively worked/discussed issues.  That doesn't mean this isn't important so please 👍 if this is important to you.
