### ISSUE TITLE
Environmental expansion

### ISSUE THREAD

**Issue by owen-d** [grafana/loki#2311]
I think we should allow config files to expand env vars. The alternative for i.e. injecting sensitive credentials is bespoke preprocessing or exposing them in the process list via flags. Cortex supports this via `-config.expand-env`: https://cortexmetrics.io/docs/configuration/configuration-file/#use-environment-variables-in-the-configuration

**Comment by mkjoerg** [comment]
This is especially useful in GitOps deployments, where you don't want the values file to contain secrets. With cortex this makes deploying it very straight forward, by just replacing the secret with Env variables.

**Comment by patrickhuy** [comment]
We are deploying Loki using ArgoCD (with the provided helm chart) and would like a way to not include AWS/S3 secrets into Git. Allowing the config to reference the environment would be a very good fit for this.

**Comment by xandout** [comment]
Throwing my use-case into the ring.  I run loki-stack in multiple envs and would like to be able to use ENV expansion for S3 bucket names.

```yaml
    storage_config:
      aws:
        s3: "s3://$AWS_REGION/$LOKI_BUCKET"
```

This would allow me to keep my configs the same across envs and control behavior with the env.
