### ISSUE TITLE
loki install k8s,loki can scale up with boltdb store index metadata?

### ISSUE THREAD

**Issue by huangkaiyan10** [grafana/loki#2312]
Please ask questions you have in the mailing list: https://groups.google.com/forum/#!forum/lokiproject

Or join our #loki slack channel at http://slack.raintank.io/
loki install k8s,loki can scale up with boltdb store index metadata?

**Comment by cyriltovena** [comment]
Not yet, with boltdb shipper and menberlist you will be able see:


https://grafana.com/blog/2020/05/20/loki-v1.5.0-released-with-no-more-dependency-on-a-separate-index-store/


https://github.com/grafana/loki/blob/master/docs/operations/storage/boltdb-shipper.md


https://github.com/grafana/loki/blob/master/docs/configuration/examples.md#almost-zero-dependencies-setup
