### ISSUE TITLE
Log retention based on severity level

### ISSUE THREAD

**Issue by arun11299** [grafana/loki#2316]
Hello Folks,
I have this feature request and could potentially block us into fully migrating into Loki based log management solution. I am not sure if there is already a way to handle this. From the Slack group I was told that, it is not handled.

**Is your feature request related to a problem? Please describe.**
Currently we are using Mongo DB as our logging sink and are planning to slowly move towards Loki based solution. One of the things here we do that, is to set severity based TTL fields i.e. document expiry. Logs with "debug" severity will expire sooner than "notice" like that. This helps us save a lot of disk space and in general helps us keep the system healthy.

It appears that Loki as of now does not provide any solution to handle this.

**Describe the solution you'd like**
Since "severity" is one of the essential component of a log message, we would like to set log retention based on severity. This would help us manage the disk usage really well and it should be beneficial for others as well.

Thanks!

**Comment by owen-d** [comment]
Hey, we've talked about label-based retention (log_level could be a subset of this), but it's not currently available. We're definitely thinking about it and can see the value.

**Comment by arun11299** [comment]
Hi @owen-d 
Really glad to know that it is being considered. Waiting for it :)
I will close this for now. Please feel free to open it if you want it to be referenced for the development activity.

Thanks.
