### ISSUE TITLE
promtail static_config differentiate k8s pod replicas 

### ISSUE THREAD

**Issue by vmuthuprasad** [grafana/loki#2322]
hi, 

     i'm using promtail static config to collect logs generated by my application and i have 2 replicas for my application. 
     In loki explore i can't differentiate logs, that i'm able to identify from which pod logs were collected. 
     Is there a way to append logs with pod id or host or anything to differentiate them.

my promtail config
```yaml
scrape_configs:
      - job_name: dlpapi 
        entry_parser: raw 
        static_configs: 
          - targets: 
              - localhost 
            labels: 
              job: apicontainerlogs
              mylabel: dlpapi              
              __path__:   /home/logs/dlpserv-logger.log```

**Comment by cyriltovena** [comment]
Are you logging in a file inside the log ? if yes one option I see is passing the pod name from environment variable to the config file by doing a sed when the container start.

See https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/

**Comment by vmuthuprasad** [comment]
@cyriltovena thanks for response, it would be really helpful if you can share sample code for this.

**Comment by cyriltovena** [comment]
May be reply to my question and explain how /where you log ?

**Comment by vmuthuprasad** [comment]
@cyriltovena thanks again, it worked for me using init-container and sed command in it as follows

````initContainers:
      - name: init-container
        image: busybox:1.28
        command: ['sh', '-c','sed -e "s/{hostname}/$NODE_NAME/" -e "s/{podname}/$POD_NAME/" -e "s/{podip}/$POD_IP/"  /tmp/promtail/promtail_template.yaml > /shared/promtail.yaml']    
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name        
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
            - name: config
              mountPath: /tmp/promtail
            - name: shared-promtail
              mountPath: /shared````

**Comment by cyriltovena** [comment]
Well done, you sorted it out on your own 🤩👏
