### ISSUE TITLE
Error logs are shown in reverse order in Grafana

### ISSUE THREAD

**Issue by cxdhefei** [grafana/loki#2326]
raw log:
![image](https://user-images.githubusercontent.com/16495772/87011830-03078d00-c1fb-11ea-8a7c-38a8319e2a64.png)

grafana:|
![image](https://user-images.githubusercontent.com/16495772/87011870-1155a900-c1fb-11ea-9213-446d95cf09bc.png)

how to config promtail to reserve this problem？

**Comment by avkonst** [comment]
This is duplicate issue. Search for the open tickets.
