### ISSUE TITLE
can't disambiguate "no stream available" from "no matches of keyword within stream", affecting grafana alerts

### ISSUE THREAD

**Issue by Dieterbe** [grafana/loki#2337]
I have a query like `{namespace="metrictank", cluster="foo",container="metrictank"}`, which shows data in explore.
When I keep this same selector, but wrap it like so:
`rate((<selector> |= "PANIC")[5m])` it returns no data.
in grafana i have an alert on the latter query, but because it returns no data, my alert goes into "unknown" state.

I would like to make the argument that the rate should be reported as 0, that seems to make more sense.
That said, if the selector were to not match any streams, then it makes complete sense that no data is reported.
(in fact, in that case, it's really useful to have the "unknown" state in grafana, it's a sign i should fix my queries)

@cyriltovena suggested we could implement something like 
`rate((<selector> |= "PANIC")[5m]) or vector(0)` but i'm not sure that is what I want. If the selector matches no stream, would this simply return 0 ? (and thus obfuscate the fact that my selector is broken?).

**Comment by owen-d** [comment]
I see - this seems like a valuable request. There's a big difference between "no filtered points for streams" and "no streams". It's not something we support right now though.

The `or vector(0)` will return a series with 0 labels and a value of 0 if you don't see any matching streams, like:

![image](https://user-images.githubusercontent.com/8173478/87431090-23956580-c5b4-11ea-8bec-9d300104c17c.png)

Note: We don't yet have the `vector` function implemented in loki so I'll need to do that.

**Comment by Dieterbe** [comment]
right so that's not a good solution to this problem then, I think ? because it would mask the issue of a stream not existing?

**Comment by Dieterbe** [comment]
any news on this?

**Comment by papovyr** [comment]
When I do rate((<selector> |= "err")[5m]) or vector(0)
i get error in Grafana, `parse error at line 1, col 115: syntax error: unexpected IDENTIFIER`
Any timeline when `vector (0)` will be implemented in loki
