### ISSUE TITLE
logcli OAuth

### ISSUE THREAD

**Issue by daurnimator** [grafana/loki#2340]
Currently we have developers accessing loki via the grafana GUI where we use the OAuth-passthrough feature, however we'd like to allow developers to use `logcli`.

Could you add a config option (and/or flag) to the `logcli` executable that sets OAuth headers?

**Comment by owen-d** [comment]
Cool idea. We'd love a PR but I'm not sure this is going to be highly prioritized otherwise.

**Comment by daurnimator** [comment]
.

**Comment by to-kr** [comment]
Grafana issues: Support SSO for Loki Log CLI
https://github.com/grafana/loki/issues/395

**Comment by daurnimator** [comment]
.

**Comment by daurnimator** [comment]
@stale ?
