### ISSUE TITLE
Error in Promtail when Helm Charts are deployed

### ISSUE THREAD

**Issue by athreya92** [grafana/loki#235]
I'm facing a strange issue with Promtail. 
Once the chart is deployed, all the loki pods are up and running. However checking the logs of loki-promtail pod showed error messages for all the pods..

` level=info ts=2019-01-22T08:16:17.814179823Z caller=targetmanager.go:142 msg="Adding target" key="{app=\"cassandra\", instance=\"cassandra-6d8fbff784-b8z8p\", job=\"ndn-base/cassandra\", namespace=\"ndn-base\", pod_template_hash=\"2849699340\"}"
`
`level=error ts=2019-01-22T08:16:17.814286689Z caller=targetmanager.go:145 msg="Failed to create target" key="{app=\"cassandra\", instance=\"cassandra-6d8fbff784-b8z8p\", job=\"ndn-base/cassandra\", namespace=\"ndn-base\", pod_template_hash=\"2849699340\"}" error="ioutil.ReadDir: readdirent: not a directory"
`

K8s Version

`Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
`

Helm Version

`Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
`

Loki Version - `Master`

OS - `CentOS 7.5`

**Comment by sureshamk** [comment]
I am also facing this issue in AKS , Kubernetes version 1.11.5

**Comment by daixiang0** [comment]
please look this #238 if you custom docker data root.

**Comment by hisarbalik** [comment]
I have same problem on AKS, if I change image pull policy to Always problem gone

**Comment by hisarbalik** [comment]
> @hisarbalik maybe the image you had is too old in your env, so pull a newer works

No image is same and this only happen if I delete and install same helm chart on the cluster, I suspect after redeploying promtail somehow can't access existing files/directories from previous deployment

**Comment by daixiang0** [comment]
@hisarbalik try `helm del --purge loki` which would clean all things.

**Comment by slim-bean** [comment]
This issue is quite old and we haven't had any similar reports, so I'm closing it assuming it's fixed.  Please create a new issue if there are issues with the helm charts.
