### ISSUE TITLE
logcli param since may be handled on the server

### ISSUE THREAD

**Issue by tivvit** [grafana/loki#2368]
**Is your feature request related to a problem? Please describe.**
Since (by default `--since=1h`) is prepared on the client, but client may have the time skewed. Unix nano may be seen in the request.
```
logcli --addr 'http://tt-laas-loki.ops.iszn.cz' query '{app="loki-querier"}' -t                 
ws://tt-laas-loki.ops.iszn.cz/loki/api/v1/tail?query=%7Bapp%3D%22loki-querier%22%7D&delay_for=0&limit=30&start=1594929876219340368
```
**Describe the solution you'd like**
I think it would be better to send only a relative difference to the server which would authoritatively say what is the time now.

**Comment by owen-d** [comment]
I'm not sure if it's worth adding this to the API: having this problem on the client side seems ok. Additionally, the server may also have clock skew.

**Comment by tivvit** [comment]
I am not sure either but two people tried to tail logs and they wanted to start from now. For the first one, it was working ok and for the second one, it was still returning some historic results. This inconsistency was unexpected for me and it was quite hard to debug.

**Comment by cyriltovena** [comment]
yeah that seems like a difficult problem to solve this since at first the client had his time skewed.

We might support a default since in the Loki API, may be by default we should not pass any start/end and let the server decide ?

**Comment by tivvit** [comment]
@cyriltovena I think it would be good to support both "absolute start/end" and "relative since" in the API

**Comment by tivvit** [comment]
@cyriltovena do you have any conclusions for this?
