### ISSUE TITLE
Loki FluentBit plugin: failed to parse BatchWait: 1

### ISSUE THREAD

**Issue by divlv** [grafana/loki#2372]
Running Loki FluentBit plugin from Docker container. (grafana/fluent-bit-plugin-loki:master-eb39e82-amd64)
Starting from version **master-eb39e82-amd64** there's an error on start:
```
[2020/07/17 17:18:54] [ info] [input:forward:forward.0] listening on 0.0.0.0:24224
level=error caller=out_loki.go:49 [flb-go]="failed to launch" error="failed to parse BatchWait: 1"
[2020/07/17 17:18:54] [error] [go proxy]: plugin 'loki' failed to initialize
```

Previous version (master-72880d1-amd64) works good.

**Comment by cyriltovena** [comment]
We switched  `BatchWait` to duration format. If you replace `1` to `1s`. that should do the job. 

I can send a PR to avoid the breaking change if you want.

**Comment by cyriltovena** [comment]
Well I just did, easy enough.

**Comment by dmitrijszaharovs** [comment]
Confirmed.
`BatchWait 1s` works for me on **master-8de2167-amd64** build.

**Comment by divlv** [comment]
Confirmed.
`BatchWait 1s` works for me on **master-8de2167-amd64** build.
