### ISSUE TITLE
Multiple backend support 

### ISSUE THREAD

**Issue by Nilubkal** [grafana/loki#2383]
This is a sort of a confrontational question not related to any bugs or improvements.

Is it possible to use multiple storage location  ( BioltDB + Amazon S3  for example ) so that the logs can be stored synchronized in two places. Whats the best practice for replicating the collected logs with Loki ( to keep them as a backup for example ) ?

**Comment by owen-d** [comment]
Replicating to different backends is not currently supported although you could ship logs to _two_ Loki installs, each with a separate backend configuration.

Also, BoltDB is an _index_ store while S3 is an _object store_ -- Loki uses one of each.

See https://grafana.com/docs/loki/latest/storage/

**Comment by Nilubkal** [comment]
Thanks @owen-d  !
