### ISSUE TITLE
support promtail to be ready status when no logs to tail 

### ISSUE THREAD

**Issue by liberwang1013** [grafana/loki#2394]
**Is your feature request related to a problem? Please describe.**

I deploy loki-stack in kubernetes cluster. In my promtail configuration, I skip scrape logs in loki & kube-system namespace. In this condition, promtail client in kubernetes master node is always in status of NotReady.
```
level=warn ts=2020-07-23T03:29:28.460070273Z caller=logging.go:49 msg="GET /ready (500) 32.437µs Response: \"Not ready: Unable to find any logs to tail. Please verify permissions, volumes, scrape_config, etc.\\n\" ws: false; Accept-Encoding: gzip; Connection: close; User-Agent: kube-probe/1.12; "
```

**Describe the solution you'd like**
promtail can give a configuration item to support skip any logs

**Comment by liberwang1013** [comment]
another problem is that in some case promtail rolling update was blocked.
```
deploymentStrategy:
  rollingUpdate:
    maxUnavailable: 1
  type: RollingUpdate
```

in my deployment strategy maxUnavailable is 1, but it always 3 unready pod running on my master nodes, so the rest pods can't update to.

**Comment by slim-bean** [comment]
Hi @liberwang1013, I have good news, the config option you want already exists! But it took me a minute to find it, the description I think could use improvement in the docs.

`health_check_target: false` in the [server:](https://github.com/grafana/loki/blob/master/docs/sources/clients/promtail/configuration.md#server_config) section should do what you want.
