### ISSUE TITLE
Query with derived fields 

### ISSUE THREAD

**Issue by dudikrisher** [grafana/loki#2395]
**Is your feature request related to a problem? Please describe.**
I'm using Loki to track and monitor logs, I added few derived fields which help me a lot. 
However due to the fact that I can't query using the derived fields, i'm very limited.

**Describe the solution you'd like**
Add the ability to query using derived field.:
`{derivedfield1="myvalue" } ` 

**Additional context**
The above is crucial, in addition the statistics on derived fields are great, however the usability of clicking on it from the log record is very poor:

![image](https://user-images.githubusercontent.com/879781/88273550-044cb580-cce3-11ea-935f-2a0ea0935b7a.png)

**Comment by cyriltovena** [comment]
This is in our roadmap. I’m working on it, we call it logql v2.

**Comment by dudikrisher** [comment]
Thank you for your response, any expected schedule for it?

**Comment by cyriltovena** [comment]
This year ;)
