### ISSUE TITLE
Promtail support for journalctl / systemd and syslog

### ISSUE THREAD

**Issue by tomwilkie** [grafana/loki#24]

**Comment by geekodour** [comment]
@gouthamve is #26 a PR for this?

but I think a different package for promtail ( #52 ) will be a good idea before that. are there any other discussions on a package for promtail other than #52 ?

**Comment by pstadler** [comment]
Came here to vote for adding syslog(+tls) support. This should work out of the box with logspout (see #82), but also many *NIX-style systems.

As an example, I'm sending a bunch of logs from different systems to Papertrail using syslog:
- Kubernetes container logs (via logspout)
- EdgeRouter logs
- FreeNAS system logs
- Docker logs on FreeNAS (via logspout)

Please note that the Papertrail UI is brilliant for streaming logs - couldn't find a way to stream logs on the Grafana UI yet, is there something planned?

**Comment by SvenDowideit** [comment]
https://github.com/hikhvar/journaldtail works for my testing.

**Comment by daixiang0** [comment]
@tomwilkie is there any plan about this?

**Comment by RRadziejewski** [comment]
I am also wondering about this can we get such a feature?

**Comment by slim-bean** [comment]
It's good to see people adding thumbs up to the first comment, this helps us understand community interest in this, and it looks like there is quite a bit :) 

We are still working diligently to get loki/promtail out of alpha and into a beta stage and filling some much needed holes, so there isn't a plan for this work just yet, but it sounds like we should be looking into it.  

Keep adding those thumbs up to the original comment, it helps us prioritize a lot!

**Comment by genebean** [comment]
Adding this would remove any need for me to use Fluentd on Linux so I am a big 👍

**Comment by billimek** [comment]
This is the last thing preventing me from dumping elasticsearch - would love to see this implemented!

**Comment by slim-bean** [comment]
Hey @billimek, journalctl is implemented but we are sorting out the best way to package promtail with this support, is journal support what you are looking for?

**Comment by wagdav** [comment]
We're using the systemd journal scraper since a couple of weeks now in production and we are very happy with it.  We are building promtail from source and used [this configuration example](https://github.com/grafana/loki/blob/master/docs/promtail-examples.md#simple-systemd-journal-config) to set it up.

**Comment by slim-bean** [comment]
#935 will handle the syslog part of this, journald support was recently added, closing
