### ISSUE TITLE
Make debug easier

### ISSUE THREAD

**Issue by yubozhao** [grafana/loki#240]
I wish there is a debug field inside the Loki config and maybe in promtail config as well.  It is really hard to trace issues.  I wish more log could be generated from the Loki operation, so we can have more insight of whats happening.  ```level.Info(util.Logger).Log()``` should be used in more places instead of just resident in Loki init

**Comment by daixiang0** [comment]
@yubozhao is any plan about this?

**Comment by yubozhao** [comment]
@daixiang0 I don't think so.  I think the core team of Grafana is focusing on other stuff (more visibility, must-have features log-retention, etc) right now, that this probably a very low priority.
