### ISSUE TITLE
Table View in Dashboard Doesn't Aggregate Resaults

### ISSUE THREAD

**Issue by dudikrisher** [grafana/loki#2401]
**Describe the bug**
When displaying logs on table it does not aggregate all the results and you need to switch between sources, on log view it works as expected.  

**Expected behavior**
Results should be shown in single table.

**Screenshots, Promtail config, or terminal output**
Table view and logs view with the same query:
![image](https://user-images.githubusercontent.com/879781/88290049-d4aba680-ccfe-11ea-9e2a-ccd41cd06a36.png)

**Comment by cyriltovena** [comment]
I don't think the table view is really supported, the first row is the timestamp the second row header are the labels and value is the log line, the rest seems to be grafana specific. This is more a grafana feature request.
