### ISSUE TITLE
Grafana dashboards job selector

### ISSUE THREAD

**Issue by tivvit** [grafana/loki#2404]
Hi I am trying to use dashboards provided in https://github.com/grafana/loki/tree/master/production/loki-mixin

I am a bit confused about the `job` label (https://github.com/grafana/loki/blob/master/production/loki-mixin/dashboards.libsonnet#L27). How do you create it? I can imagine that you are using relabeling or creating jobs Prometheus definitions dynamically with deployments.

Connected to https://github.com/grafana/loki/issues/678

**Comment by cyriltovena** [comment]
That's correct at Grafana Labs we use job=namespace/container via relabelling.

There's effort to improve the usability of those dashboard see https://github.com/grafana/loki/pull/1978.

**Comment by tivvit** [comment]
thanks for the info. I will close this and I will follow the #1978
