### ISSUE TITLE
Make Promtail more friendly for using as a library

### ISSUE THREAD

**Issue by rfratto** [grafana/loki#2405]
I'm working on [embedding](https://github.com/grafana/agent/pull/125) Promtail into grafana/agent and while my prototype works, there's a few things I'd like to change in Promtail to embed it more cleanly:

1. Allow passing a custom `log.Logger` to Promtail rather than using `util.Logger`. I'd like to log messages using my existing logger with a `component=promtail` key to make it clear log lines are logging related. 
2. Allow providing a custom mux router and cleanup function to `pkg/promtail/targets/lokipush`. The Agent creates one server object and I'd prefer to not have to have a second one for the Loki Push API. 
3. Add `RegisterFlagsWithPrefix` functions to all config structs so I can register flags to a flagset but with a namespaced prefix to make it clear they're logging related.  

I'd like to make separate PRs to handle all of these, but wanted to open an issue first to collect feedback first. I think passing a custom logger and router is best implemented through the functional options pattern. My usage of `pkg/promtail` would look something like:

```
promtail.New(cfg, false, promtail.WithLogger(logger), promtail.WithRouter(router))
```

While `cmd/promtail` would continue to use it like it already does:

```
promtail.New(config, *dryRun)
```

/cc @slim-bean @owen-d @cyriltovena

**Comment by owen-d** [comment]
All ideas seem good to me, although I admit I'm not super familiar with (2).

**Comment by cyriltovena** [comment]
Looks good to me, not sure about the function pattern, I prefer (cfg Config, opt ...optionfunc) or just more parameters. I don’t like mutating stuff after New.

**Comment by rfratto** [comment]
I'm going to close this as implemented now, with the exception of this:

> Allow providing a custom mux router and cleanup function to pkg/promtail/targets/lokipush. The Agent creates one server object and I'd prefer to not have to have a second one for the Loki Push API.

At first I didn't realize the user can have an arbitrary number of the loki push targets, each on a different port. I don't think its worth having the Agent just use one server here, since I'd have to place extra restrictions that doesn't exist in Promtail (i.e., only allow a single push target). Plus, the syslog target _definitely_ needs a separate port, so even if I did have a solution for the push target, there's always going to be at least one other target that depends on multiple ports being opened.
