### ISSUE TITLE
docker-driver loki-tls-cert-file client certificate authentication

### ISSUE THREAD

**Issue by nikel123** [grafana/loki#2419]
So far I understand it should be possible to use a client certificate for authentication, but I haven't found a way to provide it to the driver. Probably mounts for locations of the file can be added to the plugin configuration, similar to how it's done in https://github.com/vieux/docker-volume-sshfs

**Comment by cyriltovena** [comment]
We have an issue (just re-open) for documenting this. https://github.com/grafana/loki/issues/700

when you do `docker plugin ls` this give you the ID of the plugin, usually plugin rootfs is mounted from `/var/lib/docker/plugins/$PLUGIN_ID/roofts/` you can add file in there and reference that in your config.

Not super simple but that's how it is for logger plugin, other options are you need to rebuild the plugin manually.

**Comment by nikel123** [comment]
Why not add mounts to the config? https://docs.docker.com/engine/extend/config/
Then one could use 'docker plugin set' to provide the folder for the keys without needing to find the id. The ID issue would be, that after upgrade of the plugin one have to resetup all the key files, which is not the best IMHO.
Either way, thank you very much for your answer.

**Comment by nikel123** [comment]
https://docs.docker.com/engine/reference/commandline/plugin_set/ section about changing source of a mount.

**Comment by cyriltovena** [comment]
We did that and then we realized that we need a default path to mount which get triggered once you start the start a container. 

It's impossible to find a safe path that exists for everyone as default, and so it was causing many issues, most people couldn't figure this out and the error was not really helpful.

see https://github.com/grafana/loki/pull/2295

You can also configure the `config.json` yourself by accessing the same path I told you, or rebuild the plugin with that option.

**Comment by nikel123** [comment]
rbind option get apparetly around it (sshfs plugin does) and following works for me also:

diff --git a/cmd/docker-driver/config.json b/cmd/docker-driver/config.json
index 905ba305..726d7899 100644
--- a/cmd/docker-driver/config.json
+++ b/cmd/docker-driver/config.json
@@ -22,5 +22,20 @@
                 "value"
             ]
         }
+    ],
+    "mounts": [
+        {
+            "name": "ssl",
+            "description": "ssl key and certificates location on the host",
+            "destination": "/etc/loki/ssl",
+            "source": "",
+            "options": [
+              "rbind"
+            ],
+            "settable": [
+                "source"
+            ],
+            "type": "bind"
+        }
     ]
 }
