### ISSUE TITLE
Loki driver installed but cannot be activated

### ISSUE THREAD

**Issue by Gsyltc** [grafana/loki#2430]
**Describe the bug**

1°) Installation

command line to install 
`$ docker plugin install  grafana/loki-docker-driver:latest --alias loki --grant-all-permissions`

response

```
Status: Downloaded newer image for grafana/loki-docker-driver:latest
Error response from daemon: dial unix /run/docker/plugins/b8f8eaab9e750be2cf50a873b239b121b5371e5898bf9b0473009ca466db42b1/loki.sock: connect: no such file or directory

$ docker plugin ls
ID                               NAME                DESCRIPTION            ENABLED
902247e0b511        loki:latest         Loki Logging Driver          false
```

Architecture : amr64v8
OS : Armbian buster (Kernel 5.6.15-meson64)
Hardwxare : Odroid N2
Docker version 19.03.12

Plugin cannot be enabled.

Do you have an idea please ?

Thanks

**Comment by cyriltovena** [comment]
There is another issue for the docker driver arm support. I posted an arm tag you can use in the meantime.

**Comment by KlimDos** [comment]
> There is another issue for the docker driver arm support. I posted an arm tag you can use in the meantime.

hey there 
wold u mind to point me out to that issue?

**Comment by KlimDos** [comment]
> **Describe the bug**
> 
> 1°) Installation
> 
> command line to install
> `$ docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions`
> 
> response
> 
> ```
> Status: Downloaded newer image for grafana/loki-docker-driver:latest
> Error response from daemon: dial unix /run/docker/plugins/b8f8eaab9e750be2cf50a873b239b121b5371e5898bf9b0473009ca466db42b1/loki.sock: connect: no such file or directory
> 
> $ docker plugin ls
> ID                               NAME                DESCRIPTION            ENABLED
> 902247e0b511        loki:latest         Loki Logging Driver          false
> ```
> 
> Architecture : amr64v8
> OS : Armbian buster (Kernel 5.6.15-meson64)
> Hardwxare : Odroid N2
> Docker version 19.03.12
> 
> Plugin cannot be enabled.
> 
> Do you have an idea please ?
> 
> Thanks

H

> There is another issue for the docker driver arm support. I posted an arm tag you can use in the meantime.

i ve found it - https://github.com/grafana/loki/issues/1973


@Gsyltc 
```
docker plugin install grafana/loki-docker-driver:arm-v7 --alias loki --grant-all-permissions
```

works fine in my armbian orangepi

**Comment by guvmao** [comment]
I posted an linux/arm64/v8 tag you can use in the meantime.
```
docker plugin install miacis/loki-docker-driver:latest --alias loki --grant-all-permissions
```
