### ISSUE TITLE
Remove old entries

### ISSUE THREAD

**Issue by zamek42** [grafana/loki#2433]
Hi All,

How can I remove old entries from Loki database? I used simple filesystem storage. 
thx,
Zamek

**Comment by slim-bean** [comment]
Hello @zamek42!

The current mechanism for removing old data would be to [enable retention](https://grafana.com/docs/loki/latest/configuration/#table_manager_config) 

set `retention_deletes_enabled=true` and `retention_period` to a multiple of the index table period in the `schema_config` e.g. `period: 168h`

**Comment by zamek42** [comment]
Thx a lot, it seems good :)
