### ISSUE TITLE
Docker driver image should publish `master` image or it should be removed from dockerhub

### ISSUE THREAD

**Issue by owen-d** [grafana/loki#2440]
I'm of the opinion that keeping `:master` up to date is a good idea.

from https://github.com/grafana/loki/pull/2420

**Comment by slim-bean** [comment]
I deleted the `master` tag.

We already push a `master-xxxxxx` tag with every release, master isn't really a first class tag name in docker world so I don't know if it really adds any value if it's the same as the `:latest` tag?

I would suggest anyone who wants the bleeding edge use `latest` or pick a specific `master-xxxxxx` tag
