### ISSUE TITLE
No labels and no logs

### ISSUE THREAD

**Issue by nortrom-lh** [grafana/loki#2446]
![grafana](https://user-images.githubusercontent.com/58798187/88877734-cdcde800-d258-11ea-89c8-068d0142bb2b.jpg)

hello
 Installing by docker-compose，but there is no labels in grafana，help check the question。

[root@elk ~]# more docker-compose.yaml
version: "3"

networks:
   loki:

services:
  loki:
    image: grafana/loki:1.4.0
    ports:
      - "3100:3100"
    networks:
      - loki
  grafana:
    image: grafana/grafana:master
    ports:
      - "3000:3000"
    environment:
      GF_EXPLORE_ENABLED: "true"
    networks:
      - loki
  promtail:
    image: grafana/promtail:master
    volumes:
      - /tmp/log:/var/log
      - /root/promtail:/etc/promtail
    networks:
      - loki
---------------------------------------------------------------------------
[root@elk promtail]# more config.yml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://192.168.56.107:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - 192.168.56.107 
    labels:
      job: varlogs
      __path__: /var/log/*log

**Comment by slim-bean** [comment]
the promtail scrape config looks incorrect to me:

```
scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
```

It's a bit hard to tell what the indentation is in your example, you can escape blocks of yaml in markdown using three backticks before and after the code section.

It's possible what you have is the same as what I pasted it just didn't format well.

Aside from this check all the logs for promtail and Loki, are there errors?

Also keep in mind the labels in Grafana are only loaded when the page loads or when the time window is changed.

**Comment by nortrom-lh** [comment]
Hi，Bean， thank you，you are right，in the docker-compose，there is a problem。
