### ISSUE TITLE
No way to use Docker recommended naming in labels

### ISSUE THREAD

**Issue by RaitoBezarius** [grafana/loki#2455]
**Describe the bug**
Docker actually recommends labels to have a `com.xxx.yyy.zzz` naming which clashes with the label regex being in use in Loki/Prometheus, which makes it in turn *impossible* to get those labels in Loki.

**To Reproduce**
1. Started Loki (any)
2. Use Docker logging driver
3. Use the log opt: `labels: "com.xxx.yyy.zzz"` in `daemon.json`

**Expected behavior**
There should be a way to prepare for those, as they're… technically the Docker recommendation. I'd expect that relabelling can be done *before* validation of the labels name, which, according to the current code, is not the case.

**Environment:**
 - Infrastructure: laptop
 - Deployment tool: Dokku (which labels with `com.dokku.app-name` for example).

**Comment by cyriltovena** [comment]
Hey @RaitoBezarius ,

Sorry for the late reply I was off, just to be clear, the problem is that `com.xxx.yyy.zzz` is not a valid label as per this prometheus label code ?

```
// IsValid is true iff the label name matches the pattern of LabelNameRE. This
// method, however, does not use LabelNameRE for the check but a much faster
// hardcoded implementation.
func (ln LabelName) IsValid() bool {
	if len(ln) == 0 {
		return false
	}
	for i, b := range ln {
		if !((b >= 'a' && b <= 'z') || (b >= 'A' && b <= 'Z') || b == '_' || (b >= '0' && b <= '9' && i > 0)) {
			return false
		}
	}
	return true
}
```

And so when you want to use those . notation label it just error out to you ? In this case I'm all good for that PR.
