### ISSUE TITLE
some pod log miss

### ISSUE THREAD

**Issue by daixiang0** [grafana/loki#246]
I deploy many pods but some of their log miss:
```
kube-system    kubernetes-dashboard-64d57c7445-slcvr         1/1       Running   0          4d        190.174.103.129   dx-master.localdomain
kube-system    tiller-deploy-84d6787987-j6fhm                1/1       Running   0          4d        190.174.103.131   dx-master.localdomain
test   elasticsearch-logging-0                       1/1       Running   1          1d        190.174.103.158   dx-master.localdomain
test   fluentd-es-hpcxz                              1/1       Running   0          1d        190.173.52.29     dx-slave-0.localdomain
test   fluentd-es-mqljs                              1/1       Running   0          1d        190.165.252.157   dx-slave-1.localdomain
test   fluentd-es-tczqf                              1/1       Running   0          1d        190.174.103.159   dx-master.localdomain
test   grafana-7f5897bc9f-8sm42                      1/1       Running   0          3d        190.174.103.148   dx-master.localdomain
test   loki-5c5d8d7d7d-5d6lt                         1/1       Running   0          1d        190.173.52.27     dx-slave-0.localdomain
test   loki-promtail-875jf                           1/1       Running   0          1d        190.165.252.156   dx-slave-1.localdomain
test   loki-promtail-p5dvz                           1/1       Running   0          1d        190.173.52.28     dx-slave-0.localdomain
test   loki-promtail-rmm4l                           1/1       Running   0          1d        190.174.103.157   dx-master.localdomain
test   prometheus-7cc9854c5d-bm96d                   1/1       Running   3          3d        190.174.103.139   dx-master.localdomain
```
I can only get helm/promail log, others like prometheus/fluentd/grafana all missed.

The logic about how promtail use config to get index is complex for me while i want to learn it. 

It is a key for loki but i think, since no docs about it, users can not custom them as they want.

**Comment by tomwilkie** [comment]
@daixiang0 this is probably because those pods don't have a name or app label, which is something we require right now.  We're hoping we can reduce this by using `__meta_kubernetes_pod_controller_name`, but that seems to use the replica set name when we want the deployment name.  @woodsaj is looking into is, see #154

**Comment by daixiang0** [comment]
@tomwilkie thanks for your quick input. Also, i want docs about those part then i could custom or contribute to this part if possible.

**Comment by daixiang0** [comment]
@tomwilkie also find:
```
[root@dx-master prometheus]# pwd
/var/log/pods/c1e05ea4-211a-11e9-8f73-1e00130014eb/prometheus
[root@dx-master prometheus]# ll
total 0
drwxr-xr-x 2 root root  32 1月  26 15:14 ./
drwxr-xr-x 3 root root  24 1月  26 11:30 ../
lrwxrwxrwx 1 root root 170 1月  26 15:12 2.log -> /test/docker/containers/281da7d99bdf77b6baa82771632c1ba2ec79f7d7fde760059fe96bc8f8e3cc43/281da7d99bdf77b6baa82771632c1ba2ec79f7d7fde760059fe96bc8f8e3cc43-json.log
lrwxrwxrwx 1 root root 170 1月  26 15:14 3.log -> /test/docker/containers/9cea17941932e30853b990e9cb4d13d6656612c669770aa7632bb08347d6e23f/9cea17941932e30853b990e9cb4d13d6656612c669770aa7632bb08347d6e23f-json.log
```

The 3.log is the active log.

**Comment by faheem-cliqz** [comment]
Just to add some more info. As an example we switched some of our deployments to use the [recommended kubernetes labeling scheme](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels). Also helm [recommends these labels](https://github.com/helm/helm/blob/master/docs/chart_best_practices/labels.md#standard-labels) with some additions. So `app` and `name` labels are used less and less day by day. Hence no logs were scrapped for those pods.

**Comment by daixiang0** [comment]
@tomwilkie hi, after #154 merged, i test but some pod logs still miss, is it based on prometheus version?
such as prometheus and helm can not found.
```
Labels:         k8s-app=prometheus
Labels:         app=helm
                name=tiller
```
I found root cause is that default backoff_config stop promtail send bitches, so add backoff_config in helm can fix.

**Comment by daixiang0** [comment]
@davkal sorry that still need this open, i can not get loki log.
Seems that `app` label drop, while `k8s-app` keep.

**Comment by hreidar** [comment]
@daixiang0 did you solve your problem somehow? I'm battling the same in my setup. Some targets are dropped and I can't figure out why. It is really hard to debug this Promtail config as the debug logs don't show which part of the config is the reason why things get dropped

**Comment by quchenyuan** [comment]
Same problem here:
I test with a pod runs the following shell script:
`
#! /bin/bash

i=0
while true
do
  d=$(date "+%Y-%m-%d  %H:%M:%S.%N")
  printf "%-10d %20s %-10s %s\n" $i "$d" "---" "$(cat ./text)"
  sleep 0.1;
  ((i++));
done
`
./text is a file with a single line, which has a length of 25214


I query with logcli and found that some lines are missing: 
`  
   2020-06-29T17:37:09+08:00 2020-06-29T17:37:09.788688333+08:00 stdout F 9          2020-06-29  09:37:09. ---    
   2020-06-29T17:37:09+08:00 2020-06-29T17:37:09.99691343+08:00 stdout F 11         2020-06-29  09:37:09. ---
   2020-06-29T17:37:10+08:00 2020-06-29T17:37:10.100728939+08:00 stdout F 12         2020-06-29  09:37:10. ---


   2020-06-29T17:37:10+08:00 2020-06-29T17:37:10.829034129+08:00 stdout F 19         2020-06-29  09:37:10. ---
   2020-06-29T17:37:10+08:00 2020-06-29T17:37:10.932854453+08:00 stdout F 20         2020-06-29  09:37:10. ---
   2020-06-29T17:37:11+08:00 2020-06-29T17:37:11.140982502+08:00 stdout F 22         2020-06-29  09:37:11. ---
`

and I checked the original log files, the number sequences are continuous. 

Besides, no errors or exceptions are found in promtail logs.

Does anyone have a clue with this?

**Comment by adovy** [comment]
missing logs if app deployment has more than 1 replica
