### ISSUE TITLE
directly ingesting logs to loki by grpc  

### ISSUE THREAD

**Issue by pavanbadugu** [grafana/loki#2462]
I have a requirement where I have a Loki instance running and i have checked the logdata.protofile which has a pusher service but what i don't understand is how to make loki to listen to grpc can some one point me to a config file where loki directly accept grpc requests rather than snappy compressed proto bytes/json over http

**Comment by dominicqi** [comment]
> I have a requirement where I have a Loki instance running and i have checked the logdata.protofile which has a pusher service but what i don't understand is how to make loki to listen to grpc can some one point me to a config file where loki directly accept grpc requests rather than snappy compressed proto bytes/json over http

I found the loki config server.grpc_listen_port/address config. but i test the grpc  pusher server work wrong.

**Comment by dominicqi** [comment]
> I have a requirement where I have a Loki instance running and i have checked the logdata.protofile which has a pusher service but what i don't understand is how to make loki to listen to grpc can some one point me to a config file where loki directly accept grpc requests rather than snappy compressed proto bytes/json over http

i got it the grpc labels must be query label format ,examples  {a="av",b="xx"}
