### ISSUE TITLE
Loki mixins

### ISSUE THREAD

**Issue by nhuray** [grafana/loki#2468]
Hi guys,

I'm trying to build loki and promtail mixins but I don't understand how it works.

So far I used the [kubernetes-monitoring mixins](https://github.com/kubernetes-monitoring/kubernetes-mixin) and I build the project using the `Makefile` but for Loki there's no Makefile, and no guidance for building the mixins.

Could you please help me or redirect me to the documentation.

Thanks

**Comment by owen-d** [comment]
Hey, sorry about that. Unfortunately this is one area where our docs are lacking (I think we just have https://github.com/grafana/loki/tree/master/production/ksonnet). That being said, they should be usable with [jsonnet-bundler](https://github.com/jsonnet-bundler/jsonnet-bundler) as mentioned [here](https://github.com/grafana/loki/tree/master/production/ksonnet).

**Comment by nhuray** [comment]
Thanks for you help @owen-d,  

Actually I already installed promtail and loki using helm chart but the chart does not include the prometheus rules like `prometheus-operator` is doing. 

So I would like to build those rules from [promtail-mixin](https://github.com/grafana/loki/tree/master/production/promtail-mixin) and [loki-mixin](https://github.com/grafana/loki/tree/master/production/promtail-mixin) directory but I didn't find a way to build them in order to generate  `PrometheusRule` yaml files.

**Comment by owen-d** [comment]
Hey, unfortunately there's not much tooling around this :(. As it currently stands, you'll probably need to write your own process for extracting the alerts into a rules file, which is likely just casting it to yaml. We'd definitely appreciate PRs around this if you feel like contributing, but I don't think it's something we'll be able to prioritize soon ourselves.
