### ISSUE TITLE
Unable to Docker plugin enable loki

### ISSUE THREAD

**Issue by JustinR93** [grafana/loki#2478]
**Describe the bug**
When I try to enable docker loki driver I get the following error `Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:297: applying cgroup configuration for process caused \"open /sys/fs/cgroup/cpuset/00b390560ede6cecdf2d52f530a083ff9b99ff5408285297dca6a5c27e6ceae3/cpuset.cpus: permission denied\"": unknown`

**To Reproduce**
1. Install Loki driver `docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions`
2. Error occurs can reconfirm an error when running `docker plugin enable loki`

**Expected behavior**
Loki driver to be enable

**Environment:**
 - Infrastructure: Pop_OS Laptop 
 - Deployment tool: Just docker cli

**Comment by Badmullafo** [comment]
I have the same issue

It seems to be a security thing. In my kernel log `/var/log/kern.log` I can see an apparmor entry related to that action. I was thinking it could be something to do with an incorrectly configured apparmor profile. I installed docker from snap not using apt

`Aug  7 20:52:00 ubuntu-pi4 kernel: [ 1449.479951] audit: type=1400 audit(1596833520.152:378): apparmor="DENIED" operation="open" profile="snap.docker.dockerd" name="/sys/fs/cgroup/cpuset/8fef40be2524055981662a25cc94a575047ec99eb4ef6e299be8f3557cdcb4de/cpuset.cpus" pid=6038 comm="runc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0`

`Hardware: Raspberry pi 4 (arm)
Environment: 
NAME="Ubuntu"
VERSION="19.10 (Eoan Ermine)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 19.10"
VERSION_ID="19.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan`

**Comment by JustinR93** [comment]
I also installed via snap, I was wondering if that was going to be the issue or not.
