### ISSUE TITLE
Tanka installation broken due to missing jaeger dependency

### ISSUE THREAD

**Issue by HenriTEL** [grafana/loki#2485]
I tried to generate manifests by following the basic example provided by [the documentation](https://github.com/grafana/loki/blob/v1.5.0/docs/installation/tanka.md).
But at the end, running `tk show environments/loki` gives the following error:                                                     
```
evaluating jsonnet: RUNTIME ERROR: couldn't open import "jaeger-agent-mixin/jaeger.libsonnet": no match locally or in the Jsonnet library paths
	<PATH_TO_PROJECT>/vendor/loki/loki.libsonnet:2:2-46	$
	main.jsonnet:2:14-42	thunk <loki> from <$>
	main.jsonnet:5:1-5	$
	During evaluation
```

**Comment by owen-d** [comment]
I think this may be broken on 1.5, but was fixed in master. It requires [jsonnet bundler](https://github.com/jsonnet-bundler/jsonnet-bundler) to install but the dependency reference is [here](https://github.com/grafana/loki/blob/master/production/ksonnet/loki/jsonnetfile.json#L14-L21).

**Comment by HenriTEL** [comment]
Thank you. I generated the manifets from the helm chart, which was enough for my use case.
