### ISSUE TITLE
How to deploy Consul and integrate it with monolithic Loki in a Kubernetes environment?

### ISSUE THREAD

**Issue by iamparamvs** [grafana/loki#2498]
I have been trying to deploy **Consul** and integrating it with **monolithic deployment of Loki** to allow horizontal scaling. I want to use Consul as the ring store, but due to lack of documentation on internet, I am not able to reach anywhere. 

As suggested in a webinar by the Loki team, it has been suggested to use a single instance of Consul instead of a Consul Cluster. Can anyone suggest on how to deploy a single instance of Consul? Also, the configuration to be used in Loki, once the consul is setup.

Any leads on the same would be helpful. Thankyou. 

You can also text me on Slack: https://join.slack.com/t/grafana/shared_invite/zt-fmfyfgtu-bO31EWlZJTq0mGanD7oKQA

**Comment by owen-d** [comment]
Hey, sorry our docs are pretty lacking here. We'll be improving these as quickly as we can with guides/examples, but I'm going to close this as it's a Consul related question and only tangentially a Loki one.
