### ISSUE TITLE
Lambda Promtail has a link in the docs that lead to 404 page

### ISSUE THREAD

**Issue by yaron-idan** [grafana/loki#2514]
**Describe the bug**
I'm trying to understand the usage of lambda promtail. Clicking this [link](https://grafana.com/docs/loki/tools/lambda-promtail/) in the docs results in a 404

**To Reproduce**
1. Go to [lambda promtail docs page](https://grafana.com/docs/loki/latest/clients/lambda-promtail/)
2. Click the first hyperlink with the `here` caption
3. Feel lost

**Expected behavior**
docs for the lambda promtail client should appear

**Comment by slim-bean** [comment]
As a workaround you can view the docs on github: https://github.com/grafana/loki/tree/master/tools/lambda-promtail

Currently we only copy docs from the `/docs` folder so it looks like we need to move this, thanks for letting us know!

**Comment by yaron-idan** [comment]
Wow, that was super quick. Thanks!
