### ISSUE TITLE
delete pushed log

### ISSUE THREAD

**Issue by kaven-wei** [grafana/loki#2516]
How can I delete pushed log using label?
Can I invoke Http Api to resolve it?

**Comment by slim-bean** [comment]
Currently the only way to delete is with retention settings in the table manager, there is not a way to delete logs with labels.

The plan is to support this, but will be a couple months before this functionality is added.

**Comment by AnderssonPeter** [comment]
Was this ever added?

**Comment by sandstrom** [comment]
@slim-bean When you do add this, don't enable it by default. 

From a security perspective, it's pretty nice that a log-aggregator doesn't permit logging entities (any server/etc sending logs to it) to delete logs.

For most cases, I think it's much better to handle deletion via a centralized retention policy (either in loki, or on the underlying storage, e.g. an S3 bucket with automatic deletion after X months).
