### ISSUE TITLE
Documentation links are dead

### ISSUE THREAD

**Issue by yeya** [grafana/loki#2518]
**Describe the bug**
Documentation links are dead

**To Reproduce**
1. Open this [URL](https://github.com/grafana/loki/blob/v1.6.0/docs/sources/getting-started/_index.md)
2. Click any of the links

**Expected behavior**
Return 200 with some content

**Comment by owen-d** [comment]
Ugh! These were all changed to support the new [docs site](https://grafana.com/docs/loki/latest/getting-started/) but it seems that broke the github links :(. I'm not sure the best fix here. @robbymilo Do you know any tricks that might help us here?

**Comment by charandas** [comment]
By merging my PR #2521 , the website links are now broken. I am sorry, I wasn't aware of this discrepancy.

https://grafana.com/docs/loki/latest/installation/
