### ISSUE TITLE
Test failures building 1.6.0 (x86_64 linux)

### ISSUE THREAD

**Issue by daurnimator** [grafana/loki#2519]
```
FAIL	github.com/grafana/loki/pkg/chunkenc [build failed]
```
```
    drop_test.go:373: validateDropConfig() error = drop stage invalid duration, 10y cannot be converted to a duration: time: unknown unit "y" in duration "10y", wantErr = drop stage invalid duration, 10y cannot be converted to a duration: time: unknown unit y in duration 10y
    --- FAIL: Test/invalid_idle_duration (0.00s)
```
```
FAIL	github.com/grafana/loki/pkg/logentry/stages	0.028s
```

**Comment by slim-bean** [comment]
I can't really explain why you are seeing this, our CI runs on the same architecture....

**Comment by daurnimator** [comment]
FYI these errors were hit when trying to package 1.6.0 for archlinux (https://www.archlinux.org/packages/community/x86_64/loki/)

**Comment by daurnimator** [comment]
We'd like to get loki and logcli updated... do you need any extra info from us?

**Comment by daurnimator** [comment]
Are we safe to ignore these test failures to get 1.6.x out to arch users?

[loki-build.log](https://github.com/grafana/loki/files/5338214/loki-build.log)

**Comment by jelly** [comment]
With 2.0.0, one test failed, which is now disabled in the Arch package build. tgist.github.com/jelly/5c0f5db0e8e64169de51e60e29226510

**Comment by mweinelt** [comment]
@jelly How did you disable the test? The arch package is still on 1.5.0.
