### ISSUE TITLE
Can't get full logs of selected pod

### ISSUE THREAD

**Issue by yellowmegaman** [grafana/loki#2522]
**Describe the bug**
I want to be able to get *all* logs of particular pod

**To Reproduce**
1. Started Loki (grafana/loki:1.5.0)
2. Started Promtail (grafana/promtail:1.5.0)
3. Query: 
```
$ logcli --addr="$LOKI_URL" query 'count_over_time({namespace="somenamespace", pod="somepod-0"}[32h])' --
forward  | jq -r '.[].values[-1][1]' | awk '{total+=$1} END{print total}'
$ 1088907
$ logcli --addr="$LOKI_URL" query '{namespace="somenamespace", pod="somepod-0"}' --no-labels -q --since=32h --limit=5000000 --output=raw --forward --batch=1088907 > somepod-0.log-1088907
Query failed: loghttp.QueryResponse.Data: ReadArrayCB: expect ] in the end, but found , error found in #10 byte of ...|ber\"}\n"]|..., bigger context ...|\",\"message\":\"Sent message to subscriber\"}\n"]|...
$ logcli --addr="$LOKI_URL" query '{namespace="somenamespace", pod="somepod-0"}' --no-labels -q --since=32h --limit=5000000 --output=raw --forward --batch=1088906 > somepod-0.log-1088906
Query failed: loghttp.QueryResponse.Data: readStringSlowPath: unexpected end of input, error found in #10 byte of ...|omponent\"|..., bigger context ...|7EYsvF0IXBf_U\",\"role\":\"virtual\",\"component\"|...
```
But, if I change batch size to something smaller, like, 108890, I can get logs:
```
$ logcli --addr="$LOKI_URL" query '{namespace="somenamespace", pod="somepod-0"}' --no-labels -q --since=32h --limit=5000000 --output=raw --forward --batch=108890 > somepod-0.log-108890
$ cat somepod-0.log-108890 | wc -l
1088907
```

**Expected behavior**
Being able to get *all* logs without doing this kind of stuff with limits and batch size.
If I leave batch size at default (1000), I will get logs in 30-40 minutes instead of 3-4 minutes.
If it's not possible, I'd like to be able to run query with batch size equal to number of total lines of logs, but instead I get an error.

**Environment:**
 - Infrastructure: Azure, AKS (Kubernetes v1.16.10)
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
Loki configuration:
```
  loki.yaml: |
    ---
    auth_enabled: false
    chunk_store_config:
      max_look_back_period: 0s
    ingester:
      chunk_block_size: 262144
      chunk_idle_period: 3m
      chunk_retain_period: 1m
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
      max_transfer_retries: 0
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_entries_limit_per_query: 5000000
    schema_config:
      configs:
      - from: "2018-04-15"
        index:
          period: 168h
          prefix: index_
        object_store: filesystem
        schema: v9
        store: boltdb
    server:
      http_listen_port: 3100
    storage_config:
      boltdb:
        directory: /data/loki/index
      filesystem:
        directory: /data/loki/chunks
    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h
```

**Comment by yellowmegaman** [comment]
Logcli, version 1.6.0 (branch: HEAD, revision: 6e3e2fa3)

**Comment by slim-bean** [comment]
Loki doesn't yet have a streaming API so you are going to need to batch requests at some point unless your logs are small enough to fit entirely into Loki's memory.

You could try with logli 1.5.0 which doesn't include any batching support with a really large limit, but in my experiences things get strange when trying to query really large limits.

I think 1.6.0 with a batch size of 100k is going to be about the best you can do

**Comment by AdieOlami** [comment]
Hi @yellowmegaman are you able to solve this or automate the process?
