### ISSUE TITLE
loki high availability deployment

### ISSUE THREAD

**Issue by zjj2wry** [grafana/loki#2531]
**Describe the bug**

**To Reproduce**
1. Started Loki (SHA or version)
2. Started Promtail (SHA or version) to tail '...'
3. Query: `{} term`

**Expected behavior**
I am trying to deploy a high availability Loki, but it will deploy memcache、consul、gateway(separate component) in the production deploy. I know this is for better performance, But it looks more complicated. Can I just deploy 3 replicas Loki statefulset, no consul, no memcache？

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by zjj2wry** [comment]
> Memcache is just for caching - look into your configuration and you can run Loki without it.
> 
> Consul / Etcd is needed for keeping the state of Loki ingesters (called ring), there is an experimental feature to move this functionality directly into ingesters, you can try enabling it.

https://grafana.com/docs/loki/latest/configuration/examples/#almost-zero-dependencies-setup

thanks, I find the doc `almost-zero-dependencies-setup`, that is what I want. Can I deploy only one statefulset instead of separate distributor、query、ingest when use memberlist?

**Comment by tivvit** [comment]
I do not have any experience with this kind of setup. But I think you can have separate containers (distributor, query, ingester) in one statefulset. On the other hand, if you do not separate the components you can have single instance deployment which does not need memberlist at all.

**Comment by zjj2wry** [comment]
> I do not have any experience with this kind of setup. But I think you can have separate containers (distributor, query, ingester) in one statefulset. On the other hand, if you do not separate the components you can have single instance deployment which does not need memberlist at all.

I want to deploy a Loki cluster with high availability and horizontal scale in my Kubernetes cluster. I test it `all-in-one` stateful with multiple replicas, I think it can work fine, but I can not find a document about it.

**Comment by tivvit** [comment]
The thing is that the components (distributor, query, ingester) does not scale proportionally, therefore I am not sure if this is the best idea. Why do you want to deploy it like this?
