### ISSUE TITLE
Logging Driver: Allow driver to use docker DNS by joining docker network

### ISSUE THREAD

**Issue by hamiltont** [grafana/loki#2537]
**Is your feature request related to a problem? Please describe.**

We run a docker swarm and are looking into the Loki driver. One snag - all examples I can find for `loki-url` use either a static domain (e.g. `loki.foo.com`) or they use the docker host IP address (`host.docker.internal`). 

Neither of these work well a swarm with multiple nodes that is running a loki instance inside the swarm. The docker host address will not work at all on nodes other than the one node running loki

**Describe the solution you'd like**

Ideally, we could specify which network to attach the loki driver to (currently it runs with the host's network). That would allow the common docker pattern of using a docker-provided DNS name that round-robins to the matching containers. This would also work well in swarm mode using an overlay network. For example: 

```
loki-url: http://loki:3100/loki/api/v1/push
loki-network: loki
```

**Describe alternatives you've considered**

We considered HTTP redirect sidecars to make the host.docker.internal approach work on all nodes, even those not running loki. Problem is you need to run the sidecar on all nodes *except* the node running loki, so you now have to label your nodes specifically to work around this issue. 

We also considering using a static name (e.g. `loki.foo.com`) and only making it available from inside the swarm. While this would work for our production stack, anyone trying to do local development would have a problem (we often spin up a vagrant-powered swarm cluster locally) and have to reconfigure their local machine to affix a permanent IP address to the loki container, which can change location. In short, they would have exactly the type of issue the docker dns system addresses ;-)

**Comment by hamiltont** [comment]
Bump

**Comment by hamiltont** [comment]
bump

>

**Comment by caleb-adams** [comment]
This is highly desirable for my team.

**Comment by colomonkey** [comment]
Would like some more info on this as well.

**Comment by batazor** [comment]
up

**Comment by hamiltont** [comment]
🔼

**Comment by batazor** [comment]
:up:

**Comment by cyriltovena** [comment]
There's nothing we can do, by default the plugin runs on the host network.

see #1368 (which has workaround an a lot of explanation) and #1962

**Comment by KES777** [comment]
@cyriltovena How to run plugin on different network?

My service is ran on its network:
```
networks:
  mynet:
```

It would be nice that `logging driver loki` will attach to service's network. And this issue should be mentioned on documentation page: https://grafana.com/docs/loki/latest/clients/docker-driver/

I dig whole the day, to understand what is happening... =(

**Comment by FSeidinger-XI** [comment]
That also cost me a lot of time until I came across this issue. There is currently no way to connect to the loki service in docker swarm. As suggested please add a notice to the documentation, that docker swarm is not supported.

**Comment by avpetkun** [comment]
I found a solution for docker compose: just expose loki service port to localhost.
`ports:
      - "127.0.0.1:3100:3100"`

**Comment by FSeidinger-XI** [comment]
> I found a simple and safe solution for docker compose: just expose loki service port to localhost.

You are sure, you used this with docker swarm? You see docker compose and docker stack deploy are two very different beast. 

Whereas docker compose will start services on the node you run that command, docker swarm will start the services on any node available in the swarm cluster. Localhost does not have any meaning in a cluster.

**Comment by Vrashabh-Sontakke** [comment]
@FSeidinger-XI 
Did you find the correct way to do this with docker swarm ?
