### ISSUE TITLE
Querier high memory demands

### ISSUE THREAD

**Issue by tivvit** [grafana/loki#2540]
Hi I am running Loki 1.6.0 and I discovered that querier may be consuming a lot of memory. 

```
logcli --addr 'http://10.240.12.14:3100' query '{namespace="email-prod"}' --from 2020-08-07T11:30:00+02:00 --to 2020-08-07T11:35:01+02:00 --limit 100 --stats
http://10.240.12.14:3100/loki/api/v1/query_range?direction=BACKWARD&end=1596792901000000000&limit=100&query=%7Bnamespace%3D%22email-prod%22%7D&start=1596792600000000000
Ingester.TotalReached 		 0
Ingester.TotalChunksMatched 	 0
Ingester.TotalBatches 		 0
Ingester.TotalLinesSent 	 0
Ingester.HeadChunkBytes 	 0 B
Ingester.HeadChunkLines 	 0
Ingester.DecompressedBytes 	 0 B
Ingester.DecompressedLines 	 0
Ingester.CompressedBytes 	 0 B
Ingester.TotalDuplicates 	 0
Store.TotalChunksRef 		 13289
Store.TotalChunksDownloaded 	 9100
Store.ChunksDownloadTime 	 1m10.572962271s
Store.HeadChunkBytes 		 0 B
Store.HeadChunkLines 		 0
Store.DecompressedBytes 	 2.2 GB
Store.DecompressedLines 	 11754901
Store.CompressedBytes 		 1.0 GB
Store.TotalDuplicates 		 1485
Summary.BytesProcessedPerSeconds 	 0 B
Summary.LinesProcessedPerSeconds 	 0
Summary.TotalBytesProcessed 		 2.2 GB
Summary.TotalLinesProcessed 		 11754901
Summary.ExecTime 			 1m57.495258511s

```
As you can see I am limiting the results to 100 but still I did scan 11M log lines. 

when I try to scan 10 minutes I get

```
logcli --addr 'http://10.240.12.14:3100' query '{namespace="email-prod"}' --from 2020-08-07T11:30:00+02:00 --to 2020-08-07T11:40:01+02:00 --limit 100 --stats | wc -l
http://10.240.12.14:3100/loki/api/v1/query_range?direction=BACKWARD&end=1596793201000000000&limit=100&query=%7Bnamespace%3D%22email-prod%22%7D&start=1596792600000000000
Query failed: Get http://10.240.12.14:3100/loki/api/v1/query_range?direction=BACKWARD&end=1596793201000000000&limit=100&query=%7Bnamespace%3D%22email-prod%22%7D&start=1596792600000000000: EOF
0
```
log
```
level=warn ts=2020-08-22T20:46:05.155937413Z caller=logging.go:62 traceID=19cbdd3ed1a4e54e msg="GET /loki/api/v1/query_range?direction=BACKWARD&end=1596793201000000000&limit=100&query=%7Bnamespace%3D%22email-prod%22%7D&start=1596792600000000000 (500) 1m46.885742911s Response: \"EOF\\n\" ws: false; User-Agent: Go-http-client/1.1; "
```
This error is caused by the failing querier which hits the memory limit (15GB). The first query (the successful one) used over 13GB.

relevant frontend config
```
frontend_worker:
  parallelism: 2

query_range:
  align_queries_with_step: true
  split_queries_by_interval: 30s
  parallelise_shardable_queries: true
```

What I do not understand is:
* why is needed 13GB of memory for processing 2.2GB of raw data?
* the data is queried only based on label, there is no need to do any processing, the querier should know that I requested only 100 lines, why does it need to bring everything to memory when it already does have the data for the response?
* I am using query-frontend component, I thought that the query will be processed by multiple queriers (based on the `split_queries_by_interval: 30s`  config option), but based on metrics it seems that only single querier is used for processing. 

maybe this is caused by some misconfiguration?

**Comment by tivvit** [comment]
Thanks for the comprehensive info.

I am really not sure about the querier internals. I was just thinking about this problem based mainly on the info provided here.

Local optimization:
* I understand that it is much simpler to not shard the query to multiple queriers. I also understand that the 13k series has to be downloaded. I am still not sure why is the memory footprint so big. The query is for 100 records, therefore there is no need to keep more than 100 results (I imagine a heap is used for this). My conclusion is that all the memory is consumed by the downloaded chunks and there can be rate-limiting implemented for that. 
* I think that the series are also split by time, are they downloaded in order? The series which occurs "later" should be processed after the "sooner" series and if the limit is already filled they do not need to processed at all. 

parallelization:
* The sharding you are proposing sounds like a good solution. Loki can do the sharding based on the number of series and `chunk_target_size` which could serve as an estimate for how many bytes will be processed. There is still the overhead with merging the results, but that is probably already implemented in the frontend for more complex queries. I will speed up the downloading process a lot.

streaming:
* streaming API would come in handy, but the problem with sorting the stream is still present if I understand correctly. Loki may provide a streaming API that could be consumed by i.e. Spark and this system may do the sorting. 

IMHO it is better to focus on local optimizations and streaming instead of sharding (which would be reasonable only if it would be very simple change using already present frontend features).

There is another important question and that is what it the use-case of this.
* I think the use-case is downloading logs. The user may want to download hours of logs (huge amounts) based only on the labels. Maybe for post-processing or as a backup. I was already thinking about something like https://www.elastic.co/guide/en/elasticsearch/reference/current/scroll-api.html for Loki. I think the streaming API could serve this purpose well.

**Comment by kirooshu** [comment]
We are having the same problem as @tivvit and it is not a fun one. If the client can OOM your service with a query, then you cannot run a shared service such as log aggregation and log search. I wonder how Grafana runs a shared Loki when I can potentially add as many streams and then query them in this "inefficient" way. 

>  I'm wondering if we should look at this.

To be honest, this should be one of the top priorities of Loki right now because otherwise it is simply not usable at any scale if the querier is not predictable. We cannot allow users to "just query" logs if they can OOM the service at will. It was annoying for us as we only got to the querier as the problem when we split Loki from a monolith to microservices and saw which component exactly OOMs.

```
logcli --org-id=docker '{fluentd_worker="0"}' --analyze-labels
/loki/api/v1/series?end=1605646152924170000&match=%7Bfluentd_worker%3D%220%22%7D&start=1605642552924170000
Total Streams:  6308
Unique Labels:  8

Label Name      Unique Values  Found In Streams
pod_name        1307           6279
container_name  108            6279
app             71             5213
host            59             6308
namespace       39             6279
track           18             4924
stream          2              6308
fluentd_worker  1              6308
```

And something like this will push queriers to 60GB of memory:

```
logcli --org-id=docker 'sum(count_over_time({fluentd_worker="0"}[1m]))' --stats --from 2020-11-17T11:40:00-05:00 --to 2020-11-17T11:45:01-05:00
/loki/api/v1/query_range?direction=BACKWARD&end=1605631501000000000&limit=500&query=sum%28count_over_time%28%7Bfluentd_worker%3D%220%22%7D%5B1m%5D%29%29&start=1605631200000000000
```

I feel like getting counts over labels only should be as fast as prometheus. I wonder if loki should just push metrics to prometheus instance and satisfy all series queries out of that :)

I also wonder if a columnar file format like Parquet is not better format for chunks than the current chunkenc: https://github.com/grafana/loki/blob/master/pkg/chunkenc/README.md ?
