### ISSUE TITLE
Logstash with logstash-output-loki plugin make Logstash use too much CPU

### ISSUE THREAD

**Issue by acheng-floyd** [grafana/loki#2551]
Before i want to use Loki,  i  just collect my log with filebeat and send the logs to redis on clients, then i have a log server installed with logstash, logstash reads the logs from redis and use file output to save logs to a new file, that's  working for a long time.
Now i just update my logstash to 7.9.0 version, and install the plugin  logstash-output-loki , here is one of my config pipline files :

input {
  redis {
        data_type => "list"
        host => "192.100.1.19"
        db => "0"
        port => "6379"
        password => "xxxx"
        key => "floydtest18_cscerror"
        type => "floydtest18_cscerror"
        }
}
output {
   if [type] == "floydtest18_cscerror" {
       loki {
           url => "http://192.100.1.10:3100/loki/api/v1/push"
       }
   }
}

I already test the config file is working, and log was saved to loki, but problem is that logstash consume much more CPU than before. As it's seen below
![image](https://user-images.githubusercontent.com/62228888/91180702-33a37780-e712-11ea-9778-34f4164a517c.png)

If there are more piplines , the logstash will consume all the CPU resources.

![image](https://user-images.githubusercontent.com/62228888/91181079-b298b000-e712-11ea-81bc-7ca17f3c6f52.png)

I googled the problem , and could just find that there's a similar problem when use kafka output plugin, the plugin  also caused  logstash consume high cpu resource. After they fix the bug of kafka output plugin, the problem's resolved. So i guess if there's something wrong with logstash-output-loki also caused the problem !

Hope someone can help me to find out , thank you

**Comment by acheng-floyd** [comment]
here is my logfile after i started my logstash about 2 minutes
[logstash-plain.log](https://github.com/grafana/loki/files/5124086/logstash-plain.log)

**Comment by acheng-floyd** [comment]
Here is the thread information from VisualVM
![image](https://user-images.githubusercontent.com/62228888/91187040-ed521680-e719-11ea-8926-f9bb0455dc83.png)

![image](https://user-images.githubusercontent.com/62228888/91187198-183c6a80-e71a-11ea-9503-e3ed716efbdc.png)

**Comment by acheng-floyd** [comment]
![image](https://user-images.githubusercontent.com/62228888/91189065-30ad8480-e71c-11ea-827b-20efe840870c.png)

**Comment by adityacs** [comment]
@acheng-floyd Thanks for reporting the issue. It looks like this is caused by `concurrent-ruby` library. Not very sure though. Will get back to you.

**Comment by acheng-floyd** [comment]
@adityacs Thank you for your rerply. If you need more information i would be glad to upload

**Comment by adityacs** [comment]
This issue is caused by the `concurrent-ruby-edge` library used in the code. In the `select` code it is expected to block on multiple channels and not just loop infinitely. However,  the code is just looping which makes 1 full(core) CPU to be consumed.
https://github.com/grafana/loki/blob/dd7d821b31cbf22b24fb938caeaa684edc3747be/cmd/logstash/lib/logstash/outputs/loki.rb#L141
 

Have created an issue [here](https://github.com/ruby-concurrency/concurrent-ruby/issues/883). Let's wait for the response

**Comment by cyriltovena** [comment]
Can we avoid the select ?

**Comment by adityacs** [comment]
@cyriltovena In this implementation #2607, I have changed the code to use the native Ruby multi threading.
