### ISSUE TITLE
Provide option to toggle \n and \t characters in log messages to literal newlines and tabs

### ISSUE THREAD

**Issue by ethirolle** [grafana/loki#2562]
**Is your feature request related to a problem? Please describe.**
Many logs (e..g., from java or SQL) will include log messages that embed a lot of `\n` or `\r\n` or `\t` characters. These formatted log messages are pretty hard to read when viewed in Loki. They would be much easier to read if we could toggle into a view where these formatting characters are rendered as actual newlines & tabs.

Example screenshot:
![image](https://user-images.githubusercontent.com/10763196/91461143-a453ac80-e856-11ea-8656-d75ef6b348a4.png)

**Describe the solution you'd like**
The Loki UI depends somewhat on a "one log entry per line" view. When you click on a log line, you get a pop-out with the log labels and parsed fields.

My idea is to provide a tab or toggle in the Loki log UI that allows the user to toggle into a view where the log message is displayed with literal newlines and tabs substituted for the `\n` and `\t` characters.

**Describe alternatives you've considered**
I have read through https://github.com/grafana/loki/issues/74, which discusses a related-but-different problem: i..,e that is basically the inverse problem: how to parse logging in such a way that a multi-line entry (like a stack trace) is treated as a single log entry.

I do not see any other existing GH issues that treat this exact same feature request.

**Additional context**
Here is an example of one log line pulled from Loki, which shows the kind of formatting that is typical in some logging:
[one-log-line_prettified.JSON.txt](https://github.com/grafana/loki/files/5137182/one-log-line_prettified.JSON.txt)

and here is how that **message** looks like after substituting literal newlines for every "\n":
[one-log-line-MESSAGE-with-newlines.txt](https://github.com/grafana/loki/files/5137200/one-log-line-MESSAGE-with-newlines.txt)

**Comment by Fr33maan** [comment]
really needed for grafana to be considered as a viable log option

**Comment by slim-bean** [comment]
This issue should really be opened in the github.com/grafana/grafana repo, Loki just stores the data and sends it over an API it's not responsible for any of the UI visualizations.

**Comment by ethirolle** [comment]
> This issue should really be opened in the github.com/grafana/grafana repo, Loki just stores the data and sends it over an API it's not responsible for any of the UI visualizations.

I have opened this feature request in the Grafana repo: https://github.com/grafana/grafana/issues/27964. Closing this issue here.

**Comment by sourcehawk** [comment]
Was this feature actually implemented? I am still unable to get grafana / loki to format newlines in my log messages.
