### ISSUE TITLE
Documentation Incorrect: S3 or AWS for object_storage

### ISSUE THREAD

**Issue by nawabb** [grafana/loki#2573]
**Describe the bug**
As per the configuration reference  https://grafana.com/docs/loki/latest/configuration/

```
# Which store to use for the chunks. Either aws, azure, gcp,
# bigtable, gcs, cassandra, swift or filesystem. If omitted, defaults to the same
# value as store.
[object_store: <string>]
```

As per the example config https://grafana.com/docs/loki/latest/configuration/examples/#s3-compatible-apis
```
schema_config:
  configs:
  - from: 2020-05-15
    store: aws
    object_store: s3
```

Question: s3 is not a valid value for object_store and should be aws. One of the two documents are incorrect.

Follow up Question: I am trying to deploy Loki using Minio. However, it is not saving anything to Minio and as soon as Loki is restarted, all chunks are lost. I see index being populated in cassandra though. Loki config and logs attached which seems normal. I tried using both s3 and aws as object_store and tried different values of chunk_idle_period and chunk_block_size
[loki-config-2020aug30-n.txt](https://github.com/grafana/loki/files/5147551/loki-config-2020aug30-n.txt)

**To Reproduce**
1. Started Loki (SHA or version)
2. Started Promtail (SHA or version) to tail '...'
3. Query: `{} term`

**Expected behavior**

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by OcamsRazor** [comment]
@nawabb I did the same setup last week:
- `object_store` should be set to `s3`.
- I see in your linked config that you are combining both the short and expanded config for `storage_config`; I suggest you try using only one and see if that fixes it ?

**Comment by ysaakpr** [comment]
not really about `object_store`, mostly about `store: aws`

**Comment by netdata-be** [comment]
I agree with this issue, its not consistent, should ik be aws or should it be s3 or are both allowed.
Anyhow the documentation of examples should reflect the correct one.
