### ISSUE TITLE
Restore Loki Logs from another System

### ISSUE THREAD

**Issue by Guizhu83** [grafana/loki#2588]
Hey all,

we want to use Loki in our project but there is an scenario what we can not realize.
We want to copy Loki Logs to another System to be able to analyse them later.

When I've transferred such older Data to a dedicated System and start Loki with them, it seems it is ignoring that information.
I tried several things but didn't found a way the read them. Here is my Loki Config:

`auth_enabled: false

server:
  http_listen_port: 11187
  log_level: 'debug'

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 10s
  chunk_retain_period: 2s

schema_config:
  configs:
  - from: 2020-09-01
    store: boltdb
    object_store: filesystem
    schema: v11
    index:
      prefix: index_

storage_config:
  boltdb:
    directory: C:\PROGRA~2\Loki\Imports\index

  filesystem:
    directory: C:\PROGRA~2\Loki\Imports\chunks

limits_config:
  enforce_metric_name: false
  reject_old_samples: false

chunk_store_config:
  max_look_back_period: 0

table_manager:
  chunk_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  index_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  retention_deletes_enabled: false`

I am really grateful for every tip.

regards,

Sebastian

**Comment by slim-bean** [comment]
This should work, though you would need to shutdown the source Loki before copying as the boltdb are not considered safe to copy when open.

Alternatively if you use the [boltdb-shipper](https://grafana.com/docs/loki/latest/operations/storage/boltdb-shipper/) index type (which is still under development and marked experimental but i would say very functional at this point)

for a filesystem setup you would need to define `filesystem` as the `shared store` in the `boltdb_shipper` config, but then you can copy the filesystem directory between machines while Loki is running on both the source and destination, the only caveat here is the most recent 15-30mins of logs won't be available in the stored files.

**Comment by Guizhu83** [comment]
Thanks for that tip. We are trying it with boltdb and schema v11 more out and we are stopping loki before we start the backup or restore process.

What we found now:
If we change the OS Date to the same date as the backup was created... the logs will all shown. (The Backups is 3 weeks old now)
It seems there is any setting in tloki which is defining that data as "to old"  
Is the setting "max_look_back_period: 0" correct if i want to look back unlimited?
Are there other values which i can try?

Thanks again for your help and best regards!

**Comment by pcbl** [comment]
Hey Folks,

I have the same issue. Basically we have a "Backup" from Loki(BoltDB + Filesystem). The Backup is just a COPY from Loki files(storage_config.boltdb.directory and storage_config.boltdb.filesystem)...

https://groups.google.com/g/lokiproject/c/DhzUFXaQzE8

Then when I start a loki with the data from the backup, I am unable to see the labels that I expect. To check that, I just make a GET on /loki/api/v1/label 

BUT, when I change my system date to a date within the timeframe of the labels I want to query, It shows the labels and I am abble to query it! I tried many different settings such as ingester.query_store_max_look_back_period=-1 but I did not managed to query those old logs, unless I change my System Date time! :-|

I believe that I might be missing some setting, Could you guys give us some insight?

**Comment by pcbl** [comment]
hey Folks, in the end it turned out that the issue was on grafana! :-)

It was always sending the wrong timestamp(now)... 

https://github.com/grafana/grafana/pull/26622

As soon as Take the latest grafana beta, it worked. I got some other strage behavior, regarding some data which is not being correctly summarized... I am investigating deeper, but now it seems way better!
