### ISSUE TITLE
Governance hard to find

### ISSUE THREAD

**Issue by sh0rez** [grafana/loki#2596]
The Governance of this project is buried a bit deep in `docs/sources/community/governance.md`. This is mostly due to the layout of the docs directory, which is set up in a way it can be deployed to https://grafana.com

Several links (`MAINTAINERS.md` for example) in that document are also broken, and will 404 on grafana.com, because they refer to the repo root, which is not mirrored. 

As an idea, what about moving the Governance out of the docs folder, to `/GOVERNANCE.md`, like [Tanka has it](https://github.com/grafana/tanka/blob/master/GOVERNANCE.md), and [Grafana as well](https://github.com/grafana/grafana/blob/master/GOVERNANCE.md)?

@slim-bean @RichiH

**Comment by RichiH** [comment]
We had this discussion some time ago. I would prefer to have it in the root of the main repo.
