### ISSUE TITLE
msg="error handling line" error="invalid character '-' after top-level value"

### ISSUE THREAD

**Issue by tomwilkie** [grafana/loki#260]

**Comment by steven-sheehy** [comment]
I just tried out Loki for the first time via the helm chart, and this error shows up repeatedly in the logs and it doesn't seem to be forwarding anything on to loki.

`level=error ts=2019-02-25T21:41:06.104363214Z caller=tailer.go:108 msg="error handling line" path=/var/log/pods/c8d5fe66-3945-11e9-a076-00505691cd09/loki/0.log error="invalid character '-' after top-level value"`

Kubernetes: v1.11.6
Runtime: containerd 1.2.2

**Comment by steven-sheehy** [comment]
Switching to `entry_parser: raw` in promtail configmap made it start working. Containerd's log format isn't json, so the above error is due to parsing non-json logs. I filed #357 to make promtail smarter about selecting log format.
