### ISSUE TITLE
Get the top 10 of logs

### ISSUE THREAD

**Issue by AntoineGodeau** [grafana/loki#2629]
Hello,

I would like to know if this is possible to extract the top 10 of logs present in Loki ? 

I didn't find how to do it actualy and don't know if this is possible

**Comment by cyriltovena** [comment]
Hello Antoine,

What do you mean ? top 10 by time ? If so yes the query range return data backward see our API however you still need to provide label matchers.

**Comment by AntoineGodeau** [comment]
Hello Cyril,

Yes. I would like to see logs which have the most accurate during a Time range. I need it to tell to my dev team to improve the log management.

**Comment by cyriltovena** [comment]
Loki gives you the top 1k by default for a given time range, from the most recent to the oldest.

See :
- https://grafana.com/docs/loki/latest/api/#get-lokiapiv1query_range
- https://grafana.com/docs/loki/latest/logql/

**Comment by AntoineGodeau** [comment]
Hello Cyril,

I don't want the top 1k from recent to oldest, but top X during the time range in accuracy

**Comment by cyriltovena** [comment]
Sure Antoine,

Check the API documentation, you can provide a start and an end (aka timerange).
