### ISSUE TITLE
clients timeout when pushing streams

### ISSUE THREAD

**Issue by woodsaj** [grafana/loki#263]
https://github.com/grafana/loki/pull/251  added label validation on received streams, but this has introduced a few bugs that lead to push requests never responding.

**Comment by woodsaj** [comment]
# issues:
1) 
https://github.com/grafana/loki/blob/ab4c5bebab7f3e8a371e3caa9e1b8b4e55369d21/pkg/distributor/distributor.go#L119-L130

A slice of streamTrackers is created which has the same length as the number of streams in the Request.
As the request streams are iterated, we are now skipping over streams that have invalid labels.  If the labels are valid we get the token for the labelSet and add it to `keys` slice and then add the stream to the streamTracker slice at our current position.  

This leads to gaps in the streamTrackers slice and additionally results in the length of keys not matching the length of streams.

2)
https://github.com/grafana/loki/blob/ab4c5bebab7f3e8a371e3caa9e1b8b4e55369d21/pkg/distributor/distributor.go#L132-L134

To check if the request has any data to be processed we are checking if the number of streamTrackers is >0.  However this slice is always initialized to the size of req.Streams, which is just the number of streams received.  But we really want the number of valid streams.  If a user sends a request where all streams all have invalid labels, we will end up with a deadlock.

3) 
https://github.com/grafana/loki/blob/ab4c5bebab7f3e8a371e3caa9e1b8b4e55369d21/pkg/distributor/distributor.go#L143-L150

This loop assumes that len(keys) is the same as len(streams).  which is not true with the current code.

**Comment by tomwilkie** [comment]
Fixed in https://github.com/grafana/loki/commit/a422f394bb4660c98f7d692e16c3cc28747b7abd
