### ISSUE TITLE
loki-canary error

### ISSUE THREAD

**Issue by lianfulei** [grafana/loki#2633]
error reading websocket, will retry in 10 seconds: read tcp 172.16.3.111:41432->172.16.3.111:3100: i/o timeout

**Comment by spykermj** [comment]
@lianfulei , there are not many details here but I had a similar issue when the query loki-canary was performing did not match any logging streams.

The key arguments that are relevant are labelname, labelvalue, streamname and streamvalue. See this page: https://grafana.com/docs/loki/latest/operations/loki-canary/.

In my case, I did not have a label for the stream value. Once I added stream as a label, this problem went away.

**Comment by lianfulei** [comment]
@spykermj stream as a label,How to add this one? Can you tell me more about it

**Comment by spykermj** [comment]
@lianfulei, I am not using promtail to collect the logs so I can't give you a promtail example. I am using fluentd, so I can explain it with fluentd configuration.

~~~
     <match loki>
      @type copy
      <store>
        @type loki
        # ... skip some items not relevant to this discussion
        <label>
          container $.kubernetes.container_name
          namespace $.kubernetes.namespace_name
          pod $.kubernetes.pod_name
          node $.kubernetes.host
          HOSTNAME
          SYSTEMD_UNIT
          stream
        </label>
        # ... more skipping
      </store>
    </match>
~~~

Fluentd configuration for Loki requires that you explicitly define which key value pairs will be indexed as labels. From my example, pod will be a key that maps to the name of the pod that the logs come from and stream will be the key that maps to the name of the source stream (stdout or stderr are the only values I've seen).

This snippet of yaml from my Loki deployment manifest demonstrates how to use these values:

~~~
  template:
    metadata:
      labels:
        name: loki-canary
    spec:
      containers:
      - args:
        - -addr=querier:3100
        - -interval=1s
        - -labelname=pod
        - -labelvalue=$(POD_NAME)
        - -port=80
        - -size=1024
        - -wait=3m
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: grafana/loki-canary:1.6.0
~~~

**Comment by lianfulei** [comment]
@spykermj ok,3q

**Comment by andrusstrockiy** [comment]
@spykermj thanks for extract from loki canary. 
Hit the same issue only with filebeat  exporter ( switched because  promtail so far doesn't support multiline logs ) after adding 
```code
       - -labelname=pod
        - -labelvalue=$(POD_NAME)
...
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
```
canary started to tweet properly.
`Querying loki for logs with query: http://loki-stack:3100/loki/api/v1/query_range?start=1603284636653451185&end=1603284656653451185&query=%7Bstream%3D%22stdout%22%2Cpod%3D%22loki-canary-6pmq6%22%7D&limit=1000
1603285185653543279 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp
1603285191653435460 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp
1603285192653423800 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp
1603285193654794395 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp
1603285194653533784 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp
1603285195653431641 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp`

**Comment by lianfulei** [comment]
3q

**Comment by SnoozeFreddo** [comment]
I am still having this issue


`websocket missing entry: 1691097292178524266websocket missing entry: 1691097293178905482websocket missing entry: 1691097294178630874websocket missing entry: 1691097295178024987websocket missing entry: 1691097296177928273websocket missing entry: 1691097297178077699websocket missing entry: 1691097298178000248websocket missing entry: 16910972991789384001691097361178781063 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp1691097362178884104 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp1691097363177997942 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp1691097364178629758 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp1691097365177935394 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp1691097366178023252 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp1691097367178027280 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp1691097368181424157 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp1691097369180416495 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp1691097370178945169 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppptimeout tailing new logs (timeout period: 10.00s), will retry in 10 seconds: read tcp 10.244.2.54:35702->10.245.81.243:80: i/o timeout1691097371178013467 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp1691097372177995697 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp1691097373177992921 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp1691097374178433996 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp1691097375178029733 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp1691097376178571032 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp1691097377178516065 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp1691097378178936476 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp1691097379178069126 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp1691097380177991038 pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppConnecting to loki at ws://loki-gateway.kube-logging.svc.cluster.local.:80/loki/api/v1/tail?query=%7Bstream%3D%22stdout%22%2Cpod%3D%22loki-canary-cl9z4%22%7D, querying for label 'pod' with value 'loki-canary-cl9z4'1691097381178454852 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp1691097382178590316 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp1691097383178427457 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp1691097384178482669 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp1691097385178011926 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp1691097386178027697 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp1691097387178033932 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp1691097388178506207 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp1691097389178045069 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp1691097390177966402 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppptimeout tailing new logs (timeout period: 10.00s), will retry in 10 seconds: read tcp 10.244.2.54:54274->10.245.81.243:80: i/o timeout1691097391178590349 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp1691097392178605199 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp`


And here is an image of the logs in [grafana](https://imgur.com/a/d640goW)

**Comment by tenbarge** [comment]
Check that you are pushing the logs to loki, either with promtail or the `-push` option when starting loki-canary.

**Comment by SnoozeFreddo** [comment]
I can see the logs in Grafana, they are also in my S3.
