### ISSUE TITLE
count_over_time() query metric aggregator displaying unexpectedly in Grafana

### ISSUE THREAD

**Issue by wcedmisten** [grafana/loki#2634]
**Describe the bug**
count_over_time() does not aggregate over the range specified in the query, and instead shows individual spikes of value 1 for each log entry.

**To Reproduce**
1. Started Loki 1.3.0 via loki-stack-0.31.1 helm chart
2. Started Promtail 1.3.0 to tail Python code being deployed in a kubernetes service
3. Query: `count_over_time( {instance="mionlinewatcher-9f5bb9c45-m7p74"}[24h] |= "Successfully submitted task: recording-" )`

**Expected behavior**
Graph shown in grafana has an increasing value, starting at 0 and resulting in a final value of 34.

**Environment:**
 - Infrastructure: kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
![image](https://user-images.githubusercontent.com/4565200/93479420-47ce3500-f8ca-11ea-9248-f7a85e0895a6.png)

![image](https://user-images.githubusercontent.com/4565200/93479616-849a2c00-f8ca-11ea-996e-0cca41be6004.png)

**Comment by cyriltovena** [comment]
We might have fixed this one after 1.3 can you try some more recent release and confirm if still unexpected please ?

**Comment by wcedmisten** [comment]
Will do, thanks!

**Comment by wcedmisten** [comment]
Upgrading to 1.6.0 fixed this issue! Thanks!
