### ISSUE TITLE
LogQL throwing parse error for keys containing "." or "/"

### ISSUE THREAD

**Issue by yashvardhan-kukreja** [grafana/loki#2648]
**Describe the bug**
LogQL not able to process keys with "/" and "." in them. I want to fetch the logs and filter them on the basis of the keys "namespace" and "xyz.io/service". But LogQL gives a parse error in that query for the "." And if I remove the ".", then it gives parse error for "/". Please fix this.

**To Reproduce**
1. Started Loki (SHA or version)
2. Started Promtail (SHA or version) to tail '...'
3. Query: `{namespace=~"chronos", xyz.io/service="chronos-service"}`

**Expected behavior**

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by slim-bean** [comment]
The label name you provided contains invalid characters. Loki uses the same rules as [Prometheus for Label names](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels).

It shouldn't be possible to ingest the label `xyz.io/service` either? This should have thrown an error on ingestion too.

**Comment by yashvardhan-kukreja** [comment]
Thanks for the quick reply @slim-bean . Yes, I received those errors. But I wanted to know that is there any way with which I can use the label  name "xyz.io/service" without any errors (even if it requires a hacky approach)? Or is it impossible?

**Comment by slim-bean** [comment]
Adding support for these characters wouldn't really be an option, there are too many places we use Prometheus code to parse labels which expects the labels to adhere to their regex rules.

Depending on the client you are using to ingest the data you could manipulate it there. E.g. in Promtail you can use the relabeling_rules section of the config to replace all the invalid characters with `_` I believe.

**Comment by yashvardhan-kukreja** [comment]
Yes, coincidentally that's what I came up with yesterday. Thanks for the quick replies tho :)
