### ISSUE TITLE
Readiness Probe Fails for query-frontend with Auth Enabled

### ISSUE THREAD

**Issue by ErikKringen** [grafana/loki#2652]
**Describe the bug**
When running Loki in micro-service mode, the query-frontend with `auth_enabled: true` requires a `X-Scope-OrgID` for it's `/ready` check 

**To Reproduce**
1. Started Loki 1.6.0: `/usr/bin/loki -config.file=/etc/loki/config/config.yaml -target=query-frontend`
2. Request `GET http://<ip>:3100/ready`with and without `X-Scope-OrgID` header set

**Expected behavior**
with or without `X-Scope-OrgID` set
Response Status: 200
Body: `ready`

Actual:
without `X-Scope-OrgID` set
Response Status: 401
Body: `no org id`

with `X-Scope-OrgID` set
Response Status: 200
Body: `ready`

**Environment:**
 - Infrastructure: laptop
 - Deployment tool: none

**Comment by slim-bean** [comment]
Fixed in #2608
