### ISSUE TITLE
Switch to Ragel lexer

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#2654]
We are currently using the go lexer for logql. So far it has served us well but it is not easy to introduce new tokens that will be specific to our own language.

This is why I suggest we make a switch to Ragel (suggested by @tomwilkie), a generated lexer that goes well with the YACC parser we are using.

I don't think this is going to be an easy switch since we supporting multiple STRING token such as:

- "hello world\" foo"
- `hello world " foo`

Some resources:
- https://medium.com/@mhamrah/lexing-with-ragel-and-parsing-with-yacc-using-go-81e50475f88f
- https://www.colm.net/files/ragel/ragel-guide-6.3.pdf

/cc @owen-d since you've been working in this area too.

**Comment by tomwilkie** [comment]
I'm "meh" on Ragel.  I wanted to try something other than lex, and ragel was easier to read IMO.  That being said, I couldn't find any good docs, and had to reverse engineer for examples.

But it seems to work.

**Comment by jeschkies** [comment]
How about PEG with [pigeon](https://github.com/mna/pigeon) as an alternative? It seems easier to read and may encourage drive-by contributions.
