### ISSUE TITLE
High Availability

### ISSUE THREAD

**Issue by nfrush** [grafana/loki#266]
Hi,

I was looking at Loki and wondering whether you guys supported High Availability and Remote Read/Write (like Prometheus). I'd love to outfit an adapter to a Time Series database in order to provide long term storage for such logs.

**Comment by tomwilkie** [comment]
For long term storage of timeseries data you probably want Cortex, which Loki is based on: https://github.com/cortexproject/cortex

Loki does indeed support high availability, but for log streams, not timeseries data.
