### ISSUE TITLE
Rate limiting or Quotas within Promtail.

### ISSUE THREAD

**Issue by Whyeasy** [grafana/loki#2664]
**Is your feature request related to a problem? Please describe.**

A few weeks back we had two services that were not configured correctly which doubled the amount of storage of logs within a week. Rate limiting on the ingester level would block all the logs, would be great to solve this with something else.

**Describe the solution you'd like**

It would be great to have some rate limiting or quotas within Promtail. This way the logs are not send and will save you traffic and processing within Loki. This way it would be possible to do these limits based an labels/tags.

So if a service hits the rate limit, other services are not impacted by it. This will also help people that use Grafana cloud, this way they can limit egress of their logs or limit storage.

**Describe alternatives you've considered**

A checked if this was possible with the rate limiting within Loki, but this can only be set per tenant. Which will block/limit all logs.

**Comment by shane-axiom** [comment]
I came here to request the same thing for the Docker log driver, so I'll just comment here and suggest that this issue be expanded. Maybe promtail and the Docker driver share some common code where this check could be implemented?

This issue is coming up more and more for us. Some rogue containers starts spamming thousands of log lines per second (I'm looking at you, Dask worker) and we end up with significant latency in our log pipelines (i.e. one or a few bad containers degrade the whole system).

It would be great to be able to specify a sanity ceiling for logs at the point of ingestion (promtail, Docker driver, etc). Something like loki's [ingestion_rate_mb](https://grafana.com/docs/loki/latest/configuration/#limits_config), but at the promtail config/Docker container level.

**Comment by shane-axiom** [comment]
Pingin to keep this alive, I feel this is pretty important.

**Comment by owen-d** [comment]
This is compelling, but there is a lot of complexity about how we'd do this. Closing for now, but we're not opposed to something like this (external contributions welcome)

**Comment by M3r1** [comment]
Hello, any solution yet? We are running Loki on a limited environment and are extremely sensitive to clients overloading us.

We could really use a per node rate limit in Promtail or a per stream limit in Loki, also if such option doesn't yet exist is there any workaround to this issue? Any help would be greatly appreciated.

**Comment by 09jvilla** [comment]
Thanks to a contribution by @liguozhong , this is now complete:

Per stream limits:
https://grafana.com/docs/loki/latest/clients/promtail/stages/limit/

Global limits:
https://grafana.com/docs/loki/latest/clients/promtail/configuration/#limits_config

**Comment by mbonanata** [comment]
Excelent! Only one question: In the documentation it does not say that the limit is per stream, is that really the case?

**Comment by 09jvilla** [comment]
You can create per stream limits by using the `limit` pipeline stage 
https://grafana.com/docs/loki/latest/clients/promtail/stages/limit/

First you'd need to match the streams you actually want to select; then you can `limit` them. See here for more detail: 
https://grafana.com/docs/loki/latest/clients/promtail/pipelines/

**Comment by mbonanata** [comment]
Thanks!!!

**Comment by dudicoco** [comment]
@09jvilla can you please elaborate regarding the limit per stream?
For example, in a dynamic environment like k8s we would want to throttle logs per service without affecting other services, as @Whyeasy mentioned.
Is promtail able to do that?

**Comment by liguozhong** [comment]
> @09jvilla can you please elaborate regarding the limit per stream? For example, in a dynamic environment like k8s we would want to throttle logs per service without affecting other services, as @Whyeasy mentioned. Is promtail able to do that?

yes
https://github.com/grafana/loki/pull/7597
```
- limit:
    rate: 10
    burst: 10
    drop: true
    by_label_name: "service"
```

**Comment by dudicoco** [comment]
Thanks @liguozhong!

How can the rate-limited labels be exposed as prometheus metrics so it's possible to alert on those?

**Comment by LarsBingBong** [comment]
@dudicoco did you figure out how to expose them via Prometheus labels?
