### ISSUE TITLE
Consider signing the  SHA256SUMS file for releases.

### ISSUE THREAD

**Issue by joharohl** [grafana/loki#2673]
**Is your feature request related to a problem? Please describe.**
I would like to be able to verify that the release I'm downloading is the one that was published by you.

**Describe the solution you'd like**
Add a signature (or other means of verification) of the SHA256SUMS file published on the release page.

**Describe alternatives you've considered**
Currently we manually verify the binaries and sign the SHA256SUMS file.

**Comment by isodude** [comment]
ping @cyriltovena maybe?

There's a bunch of ways of signing the repo nowadays, e.g. cosign as well.
