### ISSUE TITLE
Remove vague link text

### ISSUE THREAD

**Issue by oddlittlebird** [grafana/loki#2680]
**What would you like to be added**:

Replace unhelpful link text, such as "here" or "documentation", throughout the Loki technical documentation. "here" is probably the biggest offender.

Link text should be descriptive, preferably the title of the page or section being linked to.

Examples:
- **Incorrect:** For more information, go [here](https://grafana.com/docs/grafana/latest/administration/image_rendering/).
- **Correct:** For more information about setting up image rendering, refer to [Image rendering](https://grafana.com/docs/grafana/latest/administration/image_rendering/).

**Why is this needed**: To improve the quality of our technical documentation.

**Comment by bemasher** [comment]
Is there any preference to avoiding bare links?

e.g.
https://helm.sh/docs/using_helm/#installing-helm
vs
[Installing Helm](https://helm.sh/docs/using_helm/#installing-helm)

**Comment by oddlittlebird** [comment]
The latter. Link text should be actual words that make sense in the context of the written sentence.
