### ISSUE TITLE
Make note format consistent

### ISSUE THREAD

**Issue by oddlittlebird** [grafana/loki#2682]
**What would you like to be added**: Currently the notes, warnings, cautions, and tips (mostly notes) in the Loki documentation are inconsistently formatted. Review usage and make consistent throughout.

**Correct:**
```
> **Note:** Note that this note is indented, in sentence case, and has the colon inside the bold formatting.
```

**Incorrect:**
```
**NOTE:**
_Note:_
**Note.**
**Note**:
```

**Why is this needed**: Make the documentation more consistent and professional. Raise the quality of our technical documentation.

**Comment by i-am-jeetu** [comment]
Hi @oddlittlebird, Please assign this to me. I want to take this up.

**Comment by oddlittlebird** [comment]
You got it.

**Comment by i-am-jeetu** [comment]
Here on this page, the line ``Make sure tiller is installed correctly in your cluster`` looks like a warning. But ``> **Warning:** `` is not added in front. Should I add it? There are many such cases in the Loki documentation.

https://grafana.com/docs/loki/latest/clients/fluentbit/

**Comment by oddlittlebird** [comment]
Yes, please do.
