### ISSUE TITLE
how can i query cortex ring status when i use etcd

### ISSUE THREAD

**Issue by feiguoL** [grafana/loki#2690]
when I get etcd ring key and value by etcdctl response is messy code:
![image](https://user-images.githubusercontent.com/45145345/94422050-105c6400-01b9-11eb-8ff1-5ce8f16ebe2d.png)

**Comment by slim-bean** [comment]
the information in the ring is not plaintext.

There is an http endpont `/ring` which is exported by the distributors (or the single binary) which will show ring information

**Comment by feiguoL** [comment]
thanks
