### ISSUE TITLE
config validator for CI checks

### ISSUE THREAD

**Issue by zswanson** [grafana/loki#2713]
**Is your feature request related to a problem? Please describe.**
With the yaml based config and options inherited from cortex etc its easy to make mistakes in the loki config file that don't manifest until runtime. Right now the only way to test the config, per the team on Slack, is to run loki on it. This is fine for a manual check but it becomes difficult to work with in CI environments. 

**Describe the solution you'd like**
An option that when passed to Loki causes it to load and validate the config, then exit with any validation errors and a 1 return code, or a standard 0 if the config is valid.

**Describe alternatives you've considered**
Could be better ways but my initial though is to run loki in a 'daemonized' format, backgrounded with a recorded pid. Check the PID and process status for a few seconds, and test the port. if its up for X seconds, the config is _probably_ valid (?) and we can kill the process and record it as a 'pass'. If it exits right away with a bad return code, its invalid.

**Comment by sreeram-boyapati** [comment]
@zswanson https://github.com/stelligent/config-lint 
Can we leverage a tool like this and write rules for config validation? It seems very extensible to more formats and the ruleset can be written in yaml and used at other places.

**Comment by zswanson** [comment]
@sreeram-boyapati That could work too I suppose. The downside is that it adds an extra thing that has to be maintained, and would probably need to be a part of the core teams testing.

**Comment by dlemel8** [comment]
Hey @zswanson , I want to work on this.
I assume you want to add a standalone flag (separated from Config struct), for example "verify config".
If "verify config" is set, we will load and validate the config and then exit with proper exit code.
Am I correct? 
Thanks.

**Comment by sreeram-boyapati** [comment]
I don't think it should be part of core repo. It breaks the `open for extension, closed for modification` principle. The feature is not part of the product offering. Circle CI does config validation for its CLI by making a graphQL query to an external validator. 

https://github.com/CircleCI-Public/circleci-cli/commit/06c8db4910ce1b9a1d57379716f6c9017ab4a8e2

**Comment by zswanson** [comment]
@dlemel8 yes that matches what I'd find useful. 

@sreeram-boyapati isn't it effectively already in the core, by virtue that loki does config validation internally at startup? It just doesn't have a way of short circuiting the rest of the startup process to exit and tell you that it was valid.
