### ISSUE TITLE
Ready-made matchers for IP addresses

### ISSUE THREAD

**Issue by RichiH** [grafana/loki#2722]
A recurring pain point is writing matchers for IPv4, IPv6, email addresses, etc. This leads to cargo culting of regexps, often wrong, from stackexchange. Even worse is trying to find valid regex for CIDR matching.

https://mobile.twitter.com/bettersafetynet/status/1312884924811227137 reminded me that we have the chance to get this right for our users days one, so we should :)

**Comment by kavirajk** [comment]
Interesting. +1. I think we should add a cidr matcher.

Adding some examples to see how the usage might look like.

```
{job="syslog", instance="localhost"} | logfmt | remote_ip = cidr("192.168.0.0/24")
```

```
cidr(pattern)
```

pattern can be one of the following for both ipv4 and ipv6.

1. single IP - `192.168.0.1`, `::1`, `127.0.0.1`
2. IP mask - `2001:db8::/32`, `127.0.0.0/8`
3. IP range - `192.168.0.1-192.168.10.13`. 

Examples

```
{job="syslog", instance="localhost"} | logfmt | remote_ip = cidr("192.168.0.1-192.168.10.13") #  ip range
```

``` 
{job="syslog", instance="localhost"} | logfmt |= cidr("192.168.0.0/24") # line matcher
```

wdyt @cyriltovena ??

**Comment by RichiH** [comment]
`cidr("192.168.0.1-192.168.10.13")` is not CIDR, it's a range. I have not come up with a syntax I like, yet. `ip_address` is descriptive, but long. Maybe `ip()` is enough.

What I am unclear on is how to match within strings, etc with the proposed syntax. "Does this log line contain a valid email address?" "Does this log line contain any mention of 192.168.0.0/16?" etc

**Comment by kavirajk** [comment]
@RichiH true. I have changed it to just 'ip()'

Here is the refined design doc

https://docs.google.com/document/d/1tTevtkZ5fmyzbEoYIpAkMpyA3xNMkff-QMYK4jlSlXM/edit#

> Does this log line contain a valid email address?" "Does this log line contain any mention of 192.168.0.0/16?" etc

It totally depends on the 'pattern' you use with 'ip(pattern)'. If pattern is CIDR pattern then it matches line that contains any of the ip within that range.

**Comment by RichiH** [comment]
Just so it does not get dropped: The initial issue is also about e.g. email addresses. No problem if that's out of scope for now, just want to make sure we don't drop it by closing this issue before we thought about what else we want in the medium term.

**Comment by RichiH** [comment]
Also, I think we should make the doc public so others can comment before we drop a finished feature.

**Comment by kavirajk** [comment]
@RichiH 

Good points.

Yes. I made the doc public

RE: email. I think we can create another issue to track it.

**Comment by RichiH** [comment]
I enabled global commenting access to facilitate discussion.

**Comment by kavirajk** [comment]
Design doc: https://docs.google.com/document/d/1tTevtkZ5fmyzbEoYIpAkMpyA3xNMkff-QMYK4jlSlXM/edit#heading=h.2rwixxvuhsi
