### ISSUE TITLE
Helm templating error when using loki-stack chart and disabling Loki

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [grafana/loki#2731]
**Describe the bug**
When I am using the [loki-stack](https://github.com/grafana/loki/blob/master/production/helm/loki-stack) Helm chart and disabling Loki in the `values.yaml` file using

```
loki:
  enabled: false
```

**To Reproduce**
1. Run `helm template loki loki/loki-stack -n monitoring -f values.yaml` with a `values.yaml` containing the above content
2. See the error
```
Error: template: loki-stack/templates/tests/loki-test-pod.yaml:22:24: executing "loki-stack/templates/tests/loki-test-pod.yaml" at <.Values.loki.service.port>: nil pointer evaluating interface {}.port
```

**Expected behavior**
Since the loki-stack chart has an option to disable the deployment of Loki itself, it should not error out on doing the same.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Helm

**Comment by SayakMukhopadhyay** [comment]
This issue is possibly because the tests are not conditioned to run only when Loki is enabled.

**Comment by alexnuttinck** [comment]
This issue is still there in chart v2.3.1 of loki-stack.

**Comment by vildek** [comment]
Issues still in latest version.

**Comment by SayakMukhopadhyay** [comment]
@vildek As per https://grafana.com/docs/loki/latest/installation/helm/#deploy-loki-stack-loki-promtail-grafana-prometheus-with-persistent-volume-claim the new charts repo is https://github.com/grafana/helm-charts so I think we should test the charts from there and see if this issue still exists or not. I haven't upgraded to the latest loki so it will be a while before I make the change.

**Comment by yasincebeci** [comment]
This issue is still exist in chart v2.4.1 of loki-stack.

**Comment by smallc2009** [comment]
This issue is still exist in chart v2.5.1 of loki-stack.

**Comment by jaswanth99999** [comment]
This issue still exists in chart v2.6.1. Is there any workaround to resolve this?
