### ISSUE TITLE
Helm templating error for fluent-bit chart - BatchSize in fluent-bit configmap wrong

### ISSUE THREAD

**Issue by iptizer** [grafana/loki#2734]
**Describe the bug**

The helm chart of fluent-bit encodes the value of *BatchSize* the wrong way, which causes fluent-bit pods to fail.

**To Reproduce**

Execute the following:

```sh
$ helm repo add loki https://grafana.github.io/loki/charts
$ helm repo update
$ helm template loki loki/loki-stack --set "fluent-bit.enabled=true" | less
```

Search for *ConfigMap* with the name *loki-fluent-bit-loki*, which looks as follows:

```yaml
---
# Source: loki-stack/charts/fluent-bit/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-fluent-bit-loki
  namespace: default
  labels:
    app: fluent-bit-loki
    chart: fluent-bit-0.3.1
    release: loki
    heritage: Helm
data:
  fluent-bit.conf: |-
    [SERVICE]
        HTTP_Server    On
        HTTP_Listen    0.0.0.0
        HTTP_PORT      2020
        Flush          1
        Daemon         Off
        Log_Level      warn
        Parsers_File   parsers.conf
    [INPUT]
        Name           tail
        Tag            kube.*
        Path           /var/log/containers/*.log
        Parser         docker
        DB             /run/fluent-bit/flb_kube.db
        Mem_Buf_Limit  5MB
    [FILTER]
        Name           kubernetes
        Match          kube.*
        Kube_URL       https://kubernetes.default.svc:443
        Merge_Log On
        K8S-Logging.Parser Off
    [Output]
        Name loki
        Match *
        Url http://loki:3100/api/prom/push
        TenantID ""
        BatchWait 1
        BatchSize 1.048576e+06
        Labels {job="fluent-bit"}
        RemoveKeys kubernetes,stream
        AutoKubernetesLabels false
        LabelMapPath /fluent-bit/etc/labelmap.json
        LineFormat json
        LogLevel warn
...
```

See the value of *BatchSize* which is something with *1.048576e+06*, which causes the fluent-bit pods to fail with the following error:

```txt
level=error caller=out_loki.go:49 [flb-go="failed to launch" error="failed to parse BatchSize: 1.048576e+06"
```

**Expected behavior**
The value from *values.yaml* as set in [this line](https://github.com/grafana/loki/blob/master/production/helm/fluent-bit/values.yaml#L13). So not encoded with "e+06"

**Environment:**
 - Infrastructure: Not relevant as the template is already wrong.
 - Deployment tool: helm as described above.

**Screenshots, Promtail config, or terminal output**

Using the newest chart version which is as follows:

```
$ helm search repo fluent-bit
NAME                    CHART VERSION   APP VERSION     DESCRIPTION                                       
loki/fluent-bit         0.3.1           v1.6.0          Uses fluent-bit Loki go plugin for gathering lo...
```

**Comment by Ameya14** [comment]
I am also facing this issue. Loki fluent bit pods are crashing and giving me this error "level=error caller=out_loki.go:49 [flb-go]="failed to launch" error="failed to parse BatchSize: 1.048576e+06". It was working fine a few days before. Is it due to the recent update?

**Comment by punkerside** [comment]
level=error caller=out_loki.go:49 [flb-go]="failed to launch" error="failed to parse BatchSize: 1.048576e+06"

**Comment by iptizer** [comment]
It is most likely caused by this commit: https://github.com/grafana/loki/commit/d3bf21e7742882d6696e865ddde0f8b8a081bc96

If I have time later on, I will take a look.

**Comment by xanderflood** [comment]
https://github.com/helm/helm/issues/1707#issuecomment-613133567 Looks like this is considered an active bug by Helm, but there's a workaround available

**Comment by BostjanBozic** [comment]
I experienced same issue both with `BatchWait` and `BatchSize`. As a workaround, I just set those in ConfigMap as following:
```
        BatchWait 1s
        BatchSize 1048576
```

**Comment by kgsatish** [comment]
I had the same issue but changing 'BatchSize {{ .Values.config.batchSize }}' to 'BatchSize {{ .Values.config.batchSize | int }}' in configmap.yaml in fluent-bit/templates solved the issue. But this requires a proper fix so that the default chart package works without any workarounds.

**Comment by xanderflood** [comment]
> I had the same issue but changing 'BatchSize {{ .Values.config.batchSize }}' to 'BatchSize {{ .Values.config.batchSize | int }}' in configmap.yaml in fluent-bit/templates solved the issue. But this requires a proper fix so that the default chart package works without any workarounds.

In addition to a fix so that the default template works, this brings to light a number of other bugs that would only appear when certain configs are applied, and they should all be fixed too to the extent that they can be identified

**Comment by czhujer** [comment]
looks like this is workaound/solution too :)
in helm values yaml:
```
config:
  batchSize: "1048576"
```
