### ISSUE TITLE
Using the sample loki config file returns an error

### ISSUE THREAD

**Issue by matthewhelmke** [grafana/loki#2736]
**Describe the bug**
Following the directions here: https://grafana.com/docs/loki/latest/installation/local/

I downloaded this config file: https://github.com/grafana/loki/blob/master/cmd/loki/loki-local-config.yaml

Which causes Loki to return this error when running using `./loki-linux-amd64 -config.file=loki-local-config.yaml`
```
failed parsing config: loki-local-config.yaml: yaml: unmarshal errors:   line 47: field ruler not found in type main.Config
```

**To Reproduce**
See above

**Expected behavior**
I presume the `ruler` entry is maybe incorrect in the sample? :smile: 

**Environment:**
 - Infrastructure: cloud instance in Linode
 - Deployment tool: direct download

**Comment by slim-bean** [comment]
I'm afraid you have fallen victim to a config file which is configured for the master branch, you didn't specify the version you are running but I suspect probably the latest release 1.6.1.

The easiest path forward is to just remove the ruler section, 1.7.0 is also coming soon which will support this config.

**Comment by matthewhelmke** [comment]
That makes sense. Yes, I am running 1.6.1. Thank you for a path forward.

**Comment by haohaifeng002** [comment]
loki v1.6.1 configs url is like :
https://github.com/grafana/loki/blob/v1.6.1/cmd/loki/loki-local-config.yaml
https://github.com/grafana/loki/blob/v1.6.1/cmd/promtail/promtail-local-config.yaml

**Comment by chiqui3d** [comment]
I just followed this tutorial https://grafana.com/docs/loki/latest/installation/docker/ and the same thing happened to me, I think it takes me less time to set up my own simple log system than to understand all this.

**Comment by srajasub** [comment]
What is wrong here with this schema_config? I wanted to use two different data sources of promtail in single loki.

[root@TPC-E3-09-017 loki]# ./loki-linux-amd64 -config.file=loki-local-config.yaml
failed parsing config: loki-local-config.yaml: yaml: unmarshal errors:
  line 35: field name not found in type config.plain
  line 37: field labels not found in type config.plain
  line 39: field name not found in type config.plain
  line 41: field labels not found in type config.plain
[root@TPC-E3-09-017 loki]#


`schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
    - name: rig1
      schema: v11
      labels:
        job: STABILITY_P
    - name: rig2
      schema: v11
      labels:
        job: STABILITY_P1
`
