### ISSUE TITLE
  line 47: field ruler not found in type main.Config

### ISSUE THREAD

**Issue by forging2012** [grafana/loki#2759]
wget https://raw.githubusercontent.com/grafana/loki/master/cmd/loki/loki-local-config.yaml
./loki-linux-amd64 -config.file=loki-local-config.yaml

```
./loki-linux-amd64 -version
loki, version 1.6.1 (branch: HEAD, revision: 623858df)
  build user:       root@dd6ba3f86fac
  build date:       2020-08-24T19:10:42Z
  go version:       go1.14.2
```

ERROR:

loki]# ./loki-linux-amd64 -config.file=loki-local-config.yaml
failed parsing config: loki-local-config.yaml: yaml: unmarshal errors:
  line 47: field ruler not found in type main.Config

**Comment by dvonessen** [comment]
Hi @forging2012 i encounter the same error.
But found this issue here https://github.com/grafana/loki/issues/2736 that says, the `ruler` field is supported in Loki version 1.7.0 not in 1.6.1. Simple solution just remove this section.

**Comment by forging2012** [comment]
TKS
