### ISSUE TITLE
Loki stops connecting if cassandra is unavailable for few mins  and back

### ISSUE THREAD

**Issue by widdix123** [grafana/loki#2760]
**Describe the bug**
Loki works fine and connects to cassandra. Connection from grafana to loki is good.

If cassandra is restarted or unavailable for few mins, loki throws below error which is fine as cassandra is down

```
level=error ts=2020-10-14T09:59:15.209997356Z caller=flush.go:198 org_id=fake msg="failed to flush user" err="gocql: no hosts available in the pool"
level=error ts=2020-10-14T09:59:15.21164723Z caller=
``` 

Once Cassandra is back online, loki does not reestablish connection to cassandra or restarts . This seems to be a bug with loki as it should be able to connect to cassandra

**To Reproduce**
1. Started Loki 1.5.0
2. Started Promtail 1.5.0
3. using rook cassandra v1.3.2
4. Restart cassandra
5. Loki will throw error 

```
level=error ts=2020-10-14T09:59:15.209997356Z caller=flush.go:198 org_id=fake msg="failed to flush user" err="gocql: no hosts available in the pool"
level=error ts=2020-10-14T09:59:15.21164723Z caller=
``` 

**Expected behavior**
Loki should be able to establish connection back to cassandra or restart

**Environment:**
 - Infrastructure: EKS 1.7
 - Deployment tool: kubectl kustomization 

**Screenshots, Promtail config, or terminal output**

Grafana snapshot of loki datasource
===========================

![image](https://user-images.githubusercontent.com/38529736/95977283-51e64380-0e36-11eb-948b-d6eaba40bc2f.png)

Logs of loki
========

```
level=error ts=2020-10-14T09:59:15.209997356Z caller=flush.go:198 org_id=fake msg="failed to flush user" err="gocql: no hosts available in the pool"
level=error ts=2020-10-14T09:59:15.21164723Z caller=
```

**Comment by Makkinwa** [comment]
???
