### ISSUE TITLE
Compactor finds no objects at index prefix in AWS S3

### ISSUE THREAD

**Issue by zswanson** [grafana/loki#2763]
**Describe the bug**
Running compactor mode off master, and working with @sandeepsukhani  to use specific debug builds it appears that something in the AWS integration isn't getting the bucket prefix/objects correctly. The compactor finds the bucket and prefixes, but reports that it has 0 objects at any prefix and no compacting occurs. Loki is otherwise using the boltdb-shipper with that same bucket without any issue. 

```
level=info ts=2020-10-15T01:15:18.764418448Z caller=loki.go:226 msg="Loki started"
level=info ts=2020-10-15T01:15:19.219000165Z caller=compactor.go:110 msg="list of tables" tables="unsupported value type"
level=info ts=2020-10-15T01:15:19.21910678Z caller=compactor.go:113 msg="compacting table" table-name="{\n  Prefix: \"index/index_18546/\"\n}"
level=info ts=2020-10-15T01:15:19.219380113Z caller=table.go:64 msg="listing files from path {\n  Prefix: \"index/index_18546/\"\n}/"
level=info ts=2020-10-15T01:15:19.263586526Z caller=table.go:70 msg="listed files" count=0
```

The AWS credentials/IAM profile for this had full S3 rights, this is not an IAM permission or bucket policy issue.
Inspection of the prefixes however shows that it has objects present as expected. 

**To Reproduce**
1. Started a Loki system configured to use an AWS S3 bucket and boltdb-shipper
2. Started Loki using master build in compactor mode, using the same configuration as above. 
3. Observed logs from compactor indicating it will not perform compaction due to no files found

**Expected behavior**
Compactor finds index objects and performs compaction.

**Environment:**
 - Infrastructure: AWS S3, AWS Fargate (loki deployment) and local docker for testing

**Comment by zswanson** [comment]
@sandeepsukhani confirming that the build debug-compactor-29dd4ab fixes this problem

**Comment by sandeepsukhani** [comment]
@zswanson Thanks for the confirmation! The fix has been merged so you can switch to latest master build if you want.
Closing this, please feel free to reopen it if you the issue again.
