### ISSUE TITLE
How long will loki ongest support WAL ?

### ISSUE THREAD

**Issue by feiguoL** [grafana/loki#2777]
the cortex already support [WAL](https://grafana.com/blog/2020/04/29/how-cortex-uses-the-prometheus-write-ahead-log-wal-to-prevent-data-loss/) 

loki has plan that support this feature?

that is relate of pull request [issue 2764](https://github.com/grafana/loki/pull/2764) begin WAL of Loki?

**Comment by owen-d** [comment]
Yes, I'm working on the WAL right now. If you're curious, here's the design doc https://github.com/grafana/loki/pull/2704

**Comment by feiguoL** [comment]
> Yes, I'm working on the WAL right now. If you're curious, here's the design doc #2704

thank you
