### ISSUE TITLE
Loki log driver not storing logs as files on disk, even with keep-file: true

### ISSUE THREAD

**Issue by chancez** [grafana/loki#2784]
**Describe the bug**

I'm running the latest loki log driver and not seeing the files mentioned on disk in the log driver logs.

**To Reproduce**
1. Install the loki docker log driver: 
```
docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions
```
2. Run a container which produces logs regularly using the log driver: 
```
[root@fake-rackhost-1 ~]# docker run -d --rm --log-driver loki chentex/random-logger:latest
6ae8b0c4388210bb8a024862922ac84291dfba5d470dedec501962ecb5271605
```
3. Check the docker daemon logs to view where the logfile should be:

```
[root@fake-rackhost-1 ~]# journalctl -u docker --since '5 minutes ago' | grep '6ae8b0c4388210bb8a024862922ac84291dfba5d470dedec501962ecb5271605'
Oct 20 08:48:11 fake-rackhost-1.lab.example.com dockerd[131229]: time="2020-10-20T08:48:11-07:00" level=info msg="level=info ts=2020-10-20T15:48:11.538420631Z caller=driver.go:77 msg=\"starting logging driver for container\" id=6ae8b0c4388210bb8a024862922ac84291dfba5d470dedec501962ecb5271605 config=\"map[env:NOMAD_TASK_NAME,NOMAD_GROUP_NAME,NOMAD_JOB_NAME keep-file:true loki-external-labels:container={{.Name}},region=berkeley-775,rackhost=true,on_premise=true,fridge=fake-rackhost-1 loki-url:https://loki.infra.example.com/loki/api/v1/push max-file:3 max-size:512m]\" file=/run/docker/logging/66b20299a71412ea66be9c09a441c2c47255c7ec2b43242c5c57365eeb953cb2 logpath=/var/log/docker/6ae8b0c4388210bb8a024862922ac84291dfba5d470dedec501962ecb5271605/json.log" plugin=9a7dc5a1d588240cf7d068c9b350b18a9679e1ab17e3caed4561c5eb249b3516
```

4. Check the location of the log file mentioned in the docker daemon logs. It does not exist:
```
[root@fake-rackhost-1 ~]# ls -lah /var/log/docker/6ae8b0c4388210bb8a024862922ac84291dfba5d470dedec501962ecb5271605/json.log
ls: cannot access '/var/log/docker/6ae8b0c4388210bb8a024862922ac84291dfba5d470dedec501962ecb5271605/json.log': No such file or directory
[root@fake-rackhost-1 ~]# ls -lah /var/log/docker
ls: cannot access '/var/log/docker': No such file or directory
[root@fake-rackhost-1 ~]# ls -l /var/log/docker
ls: cannot access '/var/log/docker': No such file or directory
```

**Expected behavior**
I expect the log files to exist in `/var/log/docker`.

**Environment:**
 - Infrastructure: docker

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

This is a fresh host, so it should be the latest version the driver since we used `:latest`:
```
[root@fake-rackhost-1 ~]# docker plugin ls
ID                  NAME                DESCRIPTION           ENABLED
9a7dc5a1d588        loki:latest         Loki Logging Driver   true
```

```
[root@fake-rackhost-1 ~]# cat /etc/docker/daemon.json
{
    "log-driver": "loki",
    "log-opts": {
        "env": "NOMAD_TASK_NAME,NOMAD_GROUP_NAME,NOMAD_JOB_NAME",
        "keep-file": "true",
        "loki-external-labels": "container={{.Name}},region=berkeley-775,rackhost=true,on_premise=true,fridge=fake-rackhost-1",
        "loki-url": "https://loki.infra.example.com/loki/api/v1/push",
        "max-file": "3",
        "max-size": "512m"
    }
}
```

When I look at the code, I think I can see the bug. I noticed that `cfgNofile` is never used to access `logCtx.Config` in https://github.com/grafana/loki/blob/master/cmd/docker-driver/config.go#L135
but it is accessed in `driver.go` `StartLogging` where I linked above

**Comment by Leosirth** [comment]
```
/var/log/docker/6ae8b0c4388210bb8a024862922ac84291dfba5d470dedec501962ecb5271605/json.log
```
I don't know what is logged here, but it's not the path of the logs.

In order to see if the logs are available also after the container is stopped just try:
```
docker logs <containerID>
```

In order to see where the logs are stored run:

```
docker inspect --format='{{.LogPath}}' <containerID>
```

**Comment by chancez** [comment]
@Leosirth I'm particularly interested in sending logs to Loki, and having the driver store the log files on disk. The code very clearly is supposed to store them in `/var/log/docker`: https://github.com/grafana/loki/blob/master/cmd/docker-driver/driver.go#L75.

> In order to see where the logs are stored run:

This only applies if using the JSON log driver. I'm using the Loki log driver, which stores the files in a different location.

**Comment by Leosirth** [comment]
I'm using the Loki Docker Driver and the logs are stored also on filesystem and are accessible using "docker logs" also for stopped container (providing the keep-file)

I think the path displayed is just wrong, the real path is what displayed by docker inspect.

The linked code just suppose to have the logs in /var/log/docker but this is not always true

**Comment by Leosirth** [comment]
Indeed the docker inspect display an empty path for Loki Driver, just use it to a container with the default logging driver to see where is your logging path

**Comment by chancez** [comment]
Using `find`, I was able to discover that the logs end up in the docker plugin's container filesystem.

```
find /var/lib/docker -name 'json.log'
/var/lib/docker/plugins/9a7dc5a1d588240cf7d068c9b350b18a9679e1ab17e3caed4561c5eb249b3516/rootfs/var/log/docker/41f224934f887f9c430f5ce1a02471490f1c2cd9618f7be7a4ba3c01294d4b21/json.log
```

**Comment by chancez** [comment]
Is it possible to get the docker plugin to store these on the host using a volume mount of some sort for the docker plugin?
