### ISSUE TITLE
invalid chunk ID

### ISSUE THREAD

**Issue by negbie** [grafana/loki#279]
Using loki version=master-df84364, branch=master, revision=df84364 in docker with some decent traffic I get for every query

ts=2019-02-02T11:59:10.659089335Z caller=spanlogger.go:36 org_id=fake method=SeriesStore.Get level=error err=convertChunkIDsToChunks err="invalid chunk ID \"fake/17954246163057195906:1549108478663:1549108588872\""
ts=2019-02-02T11:59:10.669233275Z caller=spanlogger.go:36 org_id=fake method=SeriesStore.Get level=error err=convertChunkIDsToChunks err="invalid chunk ID \"fake/17954246163057195906:1549108478663:1549108588872\""
ts=2019-02-02T11:59:14.947581409Z caller=spanlogger.go:36 org_id=fake method=SeriesStore.Get level=error err=convertChunkIDsToChunks err="invalid chunk ID \"fake/17954246163057195906:1549108478663:1549108588872\""
ts=2019-02-02T11:59:14.9692575Z caller=spanlogger.go:36 org_id=fake method=SeriesStore.Get level=error err=convertChunkIDsToChunks err="invalid chunk ID \"fake/17954246163057195906:1549108478663:1549108588872\""

I use this config
https://github.com/grafana/loki/blob/master/cmd/loki/loki-local-config.yaml

Do I run into some limitations I'm not aware of (storage,chunk_idle_period,object_store)?

**Comment by afoninsky** [comment]
I have the same issue with default settings using official helm chart. Docker tag is `master`.

**Comment by sevaho** [comment]
Any fix for this yet?

**Comment by tomwilkie** [comment]
I'm seeing this too.  Looking at this now, sorry for the delay.
