### ISSUE TITLE
Production ready Helm Chart

### ISSUE THREAD

**Issue by alexandrsemak** [grafana/loki#2791]
Hey guys, do you have plan for adding production ready Helm Chart especially for Loki?
We are interesting in separate target{distributor, ingester, querier, query-frontend, table-manage} and query and query-fronted options.

**Comment by unguiculus** [comment]
I'm working on a Helm chart which should hopefully be upstream soon.

See:
* #2593
* https://github.com/unguiculus/loki-helm-chart/

**Comment by alexandrsemak** [comment]
@unguiculus Cool, as I can see ше almost done
