### ISSUE TITLE
Deduping API 

### ISSUE THREAD

**Issue by davkal** [grafana/loki#28]
Deduping of Logging is currently implemented in the browser. It would be great to examine how a backend solution might perform in comparison:
Browser deduping needs all data to be transferred to the browser, and then might block the main thread causing the UI to be laggy. Backend deduping should result in less data being transferred while keeping the UI responsive. However, switching between deduping modes will need to issue a new request and introduce a whole roundtrip to see results.

## Modes of deduping:

Let's consider some typical log lines.
```
level=info ts=2018-11-26T07:00:11.259316Z caller=head.go:488 component=tsdb msg="head GC completed" duration=2.377771ms
level=info ts=2018-11-26T09:00:13.8587Z caller=compact.go:398 component=tsdb msg="write block" mint=1543212000000 maxt=1543219200000 ulid=01CX7KYRPYW343SSNYKM9DT9GN
level=info ts=2018-11-26T09:00:13.869071Z caller=head.go:488 component=tsdb msg="head GC completed" duration=1.297539ms
level=info ts=2018-11-26T09:00:14.337816Z caller=compact.go:352 component=tsdb msg="compact blocks" count=3 mint=1543190400000 maxt=1543212000000 ulid=01CX7KYS5Q79P73ZAK7F7V2DHS sources="[01CX7050KNQE7D574MK52KDE10 01CX771CS377RYCJM9X3ZAK9DJ 01CX7D2YVYMZAX7SZZS46YXDN6]"
level=info ts=2018-11-26T09:00:14.809531Z caller=compact.go:352 component=tsdb msg="compact blocks" count=3 mint=1543147200000 maxt=1543212000000 ulid=01CX7KYSMR8CP3Z207N6R1F4HB sources="[01CX6AR258F3PGSBZEHCQ6JBM1 01CX7051MJX15JFZNV0R8EM8NM 01CX7KYS5Q79P73ZAK7F7V2DHS]"
level=info ts=2018-11-26T11:15:01.397752Z caller=compact.go:398 component=tsdb msg="write block" mint=1543219200000 maxt=1543226400000 ulid=01CX7VNJM26JE9X5EGY28DE2N0
level=info ts=2018-11-26T11:15:01.406863Z caller=head.go:488 component=tsdb msg="head GC completed" duration=1.037851ms
```

Ideally, log lines provide little breadcrumbs of what a software was doing when. At the same time, lines repeat a lot, which sometimes is less useful to display as it adds a lot of noise. There are a couple of strategies we can use to identify a line as repeating and hence in need of deduping.

### Exact matches:

Exact matches should be done on the whole line payload, except for dates. This allows to dedup messages that carry the exact same information. The argument for excluding the dates is that it's more likely that they are a mandatory field than being useful to the reader as a distinguishing feature of each line. As a first step, I would only strip ISO dates.

### Ignore duration and IPs:

Numbers usually make up the variable parts of a log line, e.g., `duration=1.037851ms`. For display purposes we can choose not to care about repeated lines that have different durations. For this we can simply compare lines with numbers stripped. Numbers are also represented in IP addresses, those would be stripped as well.

### Structure:

Structured logging can produce lines that could be considered repeated if their structure is the same, i.e. its keys are the same. Consider:

```
level=info ts=2018-11-26T09:00:14.809531Z caller=compact.go:352 component=tsdb msg="compact blocks" count=3 mint=1543147200000 maxt=1543212000000 ulid=01CX7KYSMR8CP3Z207N6R1F4HB sources="[01CX6AR258F3PGSBZEHCQ6JBM1 01CX7051MJX15JFZNV0R8EM8NM 01CX7KYS5Q79P73ZAK7F7V2DHS]"

```

It's structure would be: `level ts caller component msg count mint maxt ulid sources`. Keys might need to be sorted to be consistent.

 
### Signature:

Some log lines carry lots of variable data, but confer little information, e.g, lines with alphanumerical IDs. For the most aggressive deduping, we could consider a line's signature, ie., stripped of all letters and numbers, so that only whitespace and punctuation remains. Consider:

```
level=info ts=2018-11-26T09:00:14.809531Z caller=compact.go:352 component=tsdb msg="compact blocks" count=3 mint=1543147200000 maxt=1543212000000 ulid=01CX7KYSMR8CP3Z207N6R1F4HB sources="[01CX6AR258F3PGSBZEHCQ6JBM1 01CX7051MJX15JFZNV0R8EM8NM 01CX7KYS5Q79P73ZAK7F7V2DHS]"

```

It's signature would be: `= =--::. =.: = =" " = = = = ="[  ]"`.

## Latency discussion:

With 24h of Cassandra logs, signature deduping can easily strip 50% of messages. Quick benchmark:

Transfer:
- 500 lines, 130KB take roughly 280ms
- 1000 lines, 260KB take roughly 420ms

Deduping
- non-optimized signature deduping of 1000 lines down to ~550 takes 40ms in the browser

Rendering
- 1000 lines takes 300ms
- 500 lines takes 120ms
- this can be sped up with virtualised rendering though

## Open questions:

- should streams be deduped individually or merged? (Merging a couple of `{app="cassandra"}` logs together might lead to log lines interleaving that will be considered repeated even though they may come from different hosts)

**Comment by slim-bean** [comment]
@davkal can you give some feedback to the use cases for this and if we should still entertain this?

**Comment by davkal** [comment]
I would wait on this until this has more community demand/traction/feedback. I'll make sure to actively ask Loki users about dedup needs.
