### ISSUE TITLE
Installation with Tanka getting error "evaluating jsonnet: RUNTIME ERROR: Field does not exist: spec   /root/loki/vendor/consul/consul.libsonnet:305:5-20   During manifestation"

### ISSUE THREAD

**Issue by why-xn** [grafana/loki#2800]
**Description**

I am trying to install Loki in production. I am following the steps provided in the documentation.
https://grafana.com/docs/loki/latest/installation/tanka/

When I am running this command, getting the following error

Command:
tk show environments/loki

Error:
evaluating jsonnet: RUNTIME ERROR: Field does not exist: spec
	/root/loki/vendor/consul/consul.libsonnet:305:5-20	
	During manifestation

My lib/k.libsonnet looks like this
import "ksonnet.beta.4/k.libsonnet"

I also tried using ' import "github.com/jsonnet-libs/k8s-alpha/1.14/extensions/kausal-shim.libsonnet" '
That produces the following error.

evaluating jsonnet: RUNTIME ERROR: Field does not exist: webhook
	/root/loki/vendor/github.com/jsonnet-libs/k8s-alpha/1.14/extensions/kausal-shim.libsonnet:184:26-65	object <anonymous>
	/root/loki/vendor/github.com/jsonnet-libs/k8s-alpha/1.14/extensions/kausal-shim.libsonnet:198:21-33	object <anonymous>
	During manifestation

I am trying to configure loki with S3

**Comment by vukor** [comment]
Try this (see - https://grafana.com/docs/loki/latest/installation/tanka/):
```cat > lib/k.libsonnet <<EOF
(import 'github.com/jsonnet-libs/k8s-alpha/1.14/main.libsonnet')
+ (import 'github.com/jsonnet-libs/k8s-alpha/1.14/extensions/kausal-shim.libsonnet')
EOF```
