### ISSUE TITLE
Please lower dynamodb provision_config defaults (it implies a costs of 500$/month!)

### ISSUE THREAD

**Issue by francescor** [grafana/loki#2801]
I read in https://grafana.com/docs/loki/latest/configuration/#provision_config that the defaults are 

```
# DynamoDB table default write throughput.
# CLI flag: -<prefix>.write-throughput
[provisioned_write_throughput: <int> | default = 3000]

# DynamoDB table default read throughput.
# CLI flag: -<prefix>.read-throughput
[provisioned_read_throughput: <int> | default = 300]
```
but these appears to be the defaults for me (with `image: grafana/loki:1.5.0`)

![Screenshot from 2020-10-25 11-17-12](https://user-images.githubusercontent.com/424577/97104388-cda48380-16b3-11eb-8d83-d81f5a2835bd.png) _(screenshot from aws dynamodb console)_

and this imply as you can see, a monthly costs (for my regions, Ireland) of almost 500$/month!

btw, you can see defaults for provisioned_write_throughput is _just_ 1000, so, if I understood it correctly, I'm glad that the defaults appears to be different, or else the costs would be:

 
![Screenshot from 2020-10-25 11-23-31](https://user-images.githubusercontent.com/424577/97104491-908cc100-16b4-11eb-896f-67053261b8a9.png)

**Comment by owen-d** [comment]
I think lowering this is completely reasonable, but it's relatively low priority for us as it's (1) configurable and (2) inherited from Cortex. I believe it's better to open this in that repo.

**Comment by JuHyung-Son** [comment]
@francescor Hi is lowering default setting reduce aws cost??
I found there are a lot of tables created when I lower default setting

**Comment by francescor** [comment]
@JuHyung-Son  Hi, 
I left this project time ago, so I really don't know how to help, sorry

**Comment by gvillafanetapia** [comment]
> I found there are a lot of tables created when I lower default setting

you need to check your [storage schema config](https://grafana.com/docs/loki/latest/operations/storage/schema/)

`from` and `period`.. if you set from 1 year ago with period 24h it will create 365 tables (one per day) for example.

**Comment by francescor** [comment]
Hi, please reconsider this issue
I am back to the Loki project, and my client is still facing this issue (with a lot of waisted $$)

I would set both 
```
Provisioned read capacity units = 1
Provisioned write capacity units = 1
```

or even better: on demand, so to lower default costs

**Comment by francescor** [comment]
yes, confirmed: once again my client setup loki/dynamodb on aws with the default: 92 tables forcasting to be 570$/month each (provisioned 300/1000) 
we fortunately spotted it now, only one was with the default, the other 91 with 300/1, for a total of useless 3k$/months

I think it is really necessary to change defaults, or at least add a visible warning

**Comment by Kosiare** [comment]
I support the idea behind this issue. This default setting can make really surprising costs for anyone that is not aware of this. Thanks to my habit of checking billing everyday company I work for didn't have to pay for it that much.

At least I'd suggest making some kind of warning in docs and/or `README.md`. Also I'd put some lower values into the Helm Chart default values file.
