### ISSUE TITLE
Promtail's jsonnet config references an incorrect tag (2.0)

### ISSUE THREAD

**Issue by freddd** [grafana/loki#2818]
**Describe the bug**
[The config.libsonnet for Promtail](https://github.com/grafana/loki/blob/master/production/ksonnet/promtail/config.libsonnet#L3) is referencing `'grafana/promtail:v2.0.0'` while the image in [Dockerhub is `grafana/promtail:2.0.0` (no `v` as prefix)](https://hub.docker.com/layers/grafana/promtail/2.0.0/images/sha256-82c93aef52d2a847a830139db9f606eac61635ceb27186cbfac3d9e1f5ffdbe4?context=explore).

**To Reproduce**
1. Use the tanka templates for Promtail from master and get an ErrImagePull because the image doesn't exist

**Expected behavior**
The tag should be the same as for the rest of Loki (v2.0.0)

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: jsonnet, Tanka

**Comment by owen-d** [comment]
Thanks!
