### ISSUE TITLE
how count label info with logql？

### ISSUE THREAD

**Issue by lddlww** [grafana/loki#2829]
i want collect mysql slowquery log into loki，but i met some problem，my log like follow
```
{ip="1.1.1.1",timestamp=1500000,user="x",query_time="12s"} select * from tables where id=1;
{ip="1.1.1.1",timestamp=1500000,user="x",query_time="11s"} select * from tables where id=2;
{ip="1.1.1.1",timestamp=1500000,user="x",query_time="13s"} select * from tables where id=1;
```
can i use logql to find the  sql with longest ```query_time``` label? or how can i use loql to count label info like sort,max,min and so on?

**Comment by cyriltovena** [comment]
query_time should not be a label but instead part of the log line then you can parse the logline at query time to extract it as labels.

Once that is done you can also do `| query_time > 1s`

Read more about all of this here: https://grafana.com/docs/loki/latest/logql/#Parser-Expression

**Comment by lddlww** [comment]
thanks for reply, and i am closing this issue now
