### ISSUE TITLE
Deprecate and Remove fluent-bit output plugin

### ISSUE THREAD

**Issue by kavirajk** [grafana/loki#2834]
Goal is to getrid of flutent-bit plugin in loki repository, as now fluent-bit have native output support for [loki](https://docs.fluentbit.io/manual/pipeline/outputs/loki) 

- [ ] Test if native plugin is stable
- [ ] Test native plugin have no issue with timestamp ordering

Do the regression by deploying fluent-bit it in internal cluster and ingest some app logs to loki via native output plugin.

**Comment by owen-d** [comment]
We're planning on removing this plugin after we remove the ordering constraint in Loki.

**Comment by camaeel** [comment]
IMHO native plugin doesn't send logs to the loki on  grafana cloud.

**Comment by osg-grafana** [comment]
cc @marcusolsson

**Comment by dannykopping** [comment]
@owen-d just a reminder to close this out after out-of-order is rolled out
