### ISSUE TITLE
Remember selected fields when re-running the query

### ISSUE THREAD

**Issue by luca-battistelli** [grafana/loki#2840]
**Is your feature request related to a problem? Please describe.**
It's frustrating to select some parsed fields to show instead of the whole log line, just for the setting to be forgotten as soon as the query is re-run.

**Describe the solution you'd like**
I'd like Loki to remember fields to show instead of the whole log line when queries are re-run

**Comment by cyriltovena** [comment]
cc @ivanahuckova I think this is more a grafana request than a Loki one.

**Comment by luca-battistelli** [comment]
Sorry about this, never got around to close this and https://github.com/grafana/loki/issues/2841 and reopen in grafana. Will do so now

**Comment by luca-battistelli** [comment]
Raised in grafana as https://github.com/grafana/grafana/issues/29199
