### ISSUE TITLE
Make logs more readable when multiple fields are selected

### ISSUE THREAD

**Issue by luca-battistelli** [grafana/loki#2841]
**Is your feature request related to a problem? Please describe.**
When selecting multiple parsed fields to show instead of the whole message, Loki shows `logger_name="com.foo.bar.logger" level="ERROR"`. This makes it hard to see patterns in the logs.

**Describe the solution you'd like**
I'd like a tabular format, with headers at the top (logger_name and level in the example above) and tabulated values for each log line.

**Comment by slim-bean** [comment]
hey @luca-battistelli I didn't see your other two issues when responding to the first, this and #2840 are also UI issues which would need to be addressed in the Grafana project, Thanks!

**Comment by luca-battistelli** [comment]
Raised in grafana https://github.com/grafana/grafana/issues/29200
