### ISSUE TITLE
Do not open and close log line detail when selecting text on it

### ISSUE THREAD

**Issue by luca-battistelli** [grafana/loki#2842]
**Describe the bug**
When selecting text from a log line (to copy-paste elsewhere for instance) the detail log line opens.

**To Reproduce**
1. Started Loki (Grafana v7.2.1 (72a6c64532))
2. Run any query
3. Select text on a log line
4. The detail of the log line opens

**Expected behavior**
The detail of the log line should not open when selecting text, just on click

**Comment by slim-bean** [comment]
Hey @luca-battistelli I'm familiar with what you are describing but this could really only be addressed in Grafana, could you close this issue and re-open it in github.com/grafana/grafana ?

**Comment by luca-battistelli** [comment]
Sure thing, thanks
