### ISSUE TITLE
Loki Memory usage too high, what is the possible reason for this？Even memory leaks

### ISSUE THREAD

**Issue by guobei2028** [grafana/loki#2845]
The pod of each Loki gives the resources of 4core CPU and 8g memory, but the memory usage is still insufficient, which causes the Loki to restart. There are three pods in total.

I have tried two storage schemes, Cassandra + S3 and boltdb shipper + S3, but both of them have the problem of high memory usage. What is the possible reason for this

loki.yaml like this：
auth_enabled: false
chunk_store_config:
  max_look_back_period: 168h
ingester:
  chunk_block_size: 262144
  chunk_idle_period: 3m
  chunk_retain_period: 1m
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  max_transfer_retries: 0
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 24h
schema_config:
  configs:
  - from: "2018-04-15"
    index:
      period: 24h
      prefix: loki_index_
    object_store: aws
    schema: v11
    store: boltdb-shipper
server:
  http_listen_port: 3100
storage_config:
  aws:
    access_key_id: XXXXXXXXXXXXXXXXXXXXX
    bucketnames: XXXXXXXX-125145678
    endpoint: cos.ap-nanjing.myqcloud.com
    region: ap-nanjing
    s3: s3://XXXXXXXXXXXXXXXXXXXXX:XXXXXXXXXXXXXXXXXXXXX@ap-nanjing
    s3forcepathstyle: true
    secret_access_key: XXXXXXXXXXXXXXXXXXXXX
  boltdb_shipper:
    active_index_directory: /data/loki/index
    cache_location: /data/loki/boltdb-cache
    shared_store: aws
table_manager:
  retention_deletes_enabled: true
  retention_period: 168h

**Comment by guobei2028** [comment]
![image](https://user-images.githubusercontent.com/22144126/97583373-d5f11b80-1a31-11eb-8edb-da0ad8b34605.png)

The memory usage is shown in the figure

**Comment by guobei2028** [comment]
Does anyone have the same problem？
Who can help me analyze the reason？I'll thank you very much

**Comment by sandeepsukhani** [comment]
Can you please share following info to help debug the problem?

What is your ingestion rate? You can look at `loki_distributor_bytes_received_total` metric for that.
Is it happening for all the queries or just specific queries? Can you please share what queries are you running?
What is the memory usage when not running any queries?

**Comment by guobei2028** [comment]
> Can you please share following info to help debug the problem?
> 
> What is your ingestion rate? You can look at `loki_distributor_bytes_received_total` metric for that.
> Is it happening for all the queries or just specific queries? Can you please share what queries are you running?
> What is the memory usage when not running any queries?

loki_distributor_bytes_received_total{tenant="fake"} 8.826208989e+09
yes,it maybe happend for all the queries. Because I did not set a special query value。Where can I set specific queries? Do you mean the log label query item in grafana?
Whenever Loki’s pod restarts, the memory usage is about 300M

**Comment by guobei2028** [comment]
> Can you please share following info to help debug the problem?
> 
> What is your ingestion rate? You can look at `loki_distributor_bytes_received_total` metric for that.
> Is it happening for all the queries or just specific queries? Can you please share what queries are you running?
> What is the memory usage when not running any queries?

Does the memory usage of loki have anything to do with too many collection objects set by promtail? This is my promtail configuration：
`promtail.yaml: |
    client:
      backoff_config:
        max_period: 5s
        max_retries: 20
        min_period: 100ms
      batchsize: 102400
      batchwait: 1s
      external_labels: {}
      timeout: 10s
    positions:
      filename: /run/promtail/positions.yaml
    server:
      http_listen_port: 3101
    target_config:
      sync_period: 10s
    scrape_configs:
    - job_name: kubernetes-pods-name
      pipeline_stages:
        - docker: {}
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels:
        - __meta_kubernetes_pod_label_name
        target_label: __service__
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: __host__
      - action: drop
        regex: ''
        source_labels:
        - __service__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        replacement: $1
        separator: /
        source_labels:
        - __meta_kubernetes_namespace
        - __service__
        target_label: workload
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: workload
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        target_label: __path__
    - job_name: kubernetes-pods-app
      pipeline_stages:
        - docker: {}
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - action: drop
        regex: .+
        source_labels:
        - __meta_kubernetes_pod_label_name
      - source_labels:
        - __meta_kubernetes_pod_label_app
        target_label: __service__
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: __host__
      - action: drop
        regex: ''
        source_labels:
        - __service__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        replacement: $1
        separator: /
        source_labels:
        - __meta_kubernetes_namespace
        - __service__
        target_label: workload
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        target_label: __path__
    - job_name: kubernetes-pods-direct-controllers
      pipeline_stages:
        - docker: {}
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - action: drop
        regex: .+
        separator: ''
        source_labels:
        - __meta_kubernetes_pod_label_name
        - __meta_kubernetes_pod_label_app
      - action: drop
        regex: '[0-9a-z-.]+-[0-9a-f]{8,10}'
        source_labels:
        - __meta_kubernetes_pod_controller_name
      - source_labels:
        - __meta_kubernetes_pod_controller_name
        target_label: __service__
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: __host__
      - action: drop
        regex: ''
        source_labels:
        - __service__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        replacement: $1
        separator: /
        source_labels:
        - __meta_kubernetes_namespace
        - __service__
        target_label: workload
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        target_label: __path__
    - job_name: kubernetes-pods-indirect-controller
      pipeline_stages:
        - docker: {}
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - action: drop
        regex: .+
        separator: ''
        source_labels:
        - __meta_kubernetes_pod_label_name
        - __meta_kubernetes_pod_label_app
      - action: keep
        regex: '[0-9a-z-.]+-[0-9a-f]{8,10}'
        source_labels:
        - __meta_kubernetes_pod_controller_name
      - action: replace
        regex: '([0-9a-z-.]+)-[0-9a-f]{8,10}'
        source_labels:
        - __meta_kubernetes_pod_controller_name
        target_label: __service__
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: __host__
      - action: drop
        regex: ''
        source_labels:
        - __service__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        replacement: $1
        separator: /
        source_labels:
        - __meta_kubernetes_namespace
        - __service__
        target_label: workload
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        target_label: __path__
    - job_name: kubernetes-pods-static
      pipeline_stages:
        - docker: {}
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - action: drop
        regex: ''
        source_labels:
        - __meta_kubernetes_pod_annotation_kubernetes_io_config_mirror
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_label_component
        target_label: __service__
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: __host__
      - action: drop
        regex: ''
        source_labels:
        - __service__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        replacement: $1
        separator: /
        source_labels:
        - __meta_kubernetes_namespace
        - __service__
        target_label: workload
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_annotation_kubernetes_io_config_mirror
        - __meta_kubernetes_pod_container_name
        target_label: __path__`

**Comment by zhanghjster** [comment]
There are metrics can help. https://github.com/grafana/loki/blob/master/docs/sources/operations/observability.md. You can find the bytes put to Loki, chunks in memory, chunks flush to storage then. And check the log tool to see if there are some error.

**Comment by guobei2028** [comment]
> There are metrics can help. https://github.com/grafana/loki/blob/master/docs/sources/operations/observability.md. You can find the bytes put to Loki, chunks in memory, chunks flush to storage then. And check the log to see if there are some error.

staging：
loki_distributor_bytes_received_total{tenant="fake"} 1.7781228376e+10
loki_distributor_ingester_appends_total{ingester="9.164.1.250:9095"} 173796
loki_distributor_lines_received_total{tenant="fake"} 1.27146373e+08586
loki_ingester_chunk_stored_bytes_total{tenant="fake"} 3.68150642e+08
loki_ingester_chunk_compression_ratio_sum 42248.34240033463
loki_ingester_chunk_compression_ratio_count 2462


log_messages_total{level="debug"} 492742
log_messages_total{level="error"} 120
log_messages_total{level="info"} 2313
log_messages_total{level="warn"} 2

loki_ingester_memory_chunks 4415     #内存中的块总数，chunk_block_size: 262144 
loki_ingester_memory_streams{tenant="fake"} 31   #内存中的流总数。

**Comment by guobei2028** [comment]
> Can you please share following info to help debug the problem?
> 
> What is your ingestion rate? You can look at `loki_distributor_bytes_received_total` metric for that.
> Is it happening for all the queries or just specific queries? Can you please share what queries are you running?
> What is the memory usage when not running any queries?

the metrics like：
loki_distributor_bytes_received_total{tenant="fake"} 1.7781228376e+10
loki_distributor_ingester_appends_total{ingester="9.164.1.250:9095"} 173796
loki_distributor_lines_received_total{tenant="fake"} 1.27146373e+08586
loki_ingester_chunk_stored_bytes_total{tenant="fake"} 3.68150642e+08
loki_ingester_chunk_compression_ratio_sum 42248.34240033463
loki_ingester_chunk_compression_ratio_count 2462

log_messages_total{level="debug"} 492742
log_messages_total{level="error"} 120
log_messages_total{level="info"} 2313
log_messages_total{level="warn"} 2

loki_ingester_memory_chunks 4415 #内存中的块总数，chunk_block_size: 262144
loki_ingester_memory_streams{tenant="fake"} 31 #内存中的流总数。

chunk_block_size: 262144
chunk_retain_period：1m

What can I modify to reduce memory usage？

**Comment by zhanghjster** [comment]
> > There are metrics can help. https://github.com/grafana/loki/blob/master/docs/sources/operations/observability.md. You can find the bytes put to Loki, chunks in memory, chunks flush to storage then. And check the log to see if there are some error.
> 
> loki_distributor_bytes_received_total{tenant="fake"} 1.7781228376e+10
> loki_distributor_ingester_appends_total{ingester="9.164.1.250:9095"} 173796
> loki_distributor_lines_received_total{tenant="fake"} 1.27146373e+08586
> loki_ingester_chunk_stored_bytes_total{tenant="fake"} 3.68150642e+08
> loki_ingester_chunk_compression_ratio_sum 42248.34240033463
> loki_ingester_chunk_compression_ratio_count 2462
> 
> log_messages_total{level="debug"} 492742
> log_messages_total{level="error"} 120
> log_messages_total{level="info"} 2313
> log_messages_total{level="warn"} 2
> 
> loki_ingester_memory_chunks 4415 #内存中的块总数，chunk_block_size: 262144
> loki_ingester_memory_streams{tenant="fake"} 31 #内存中的流总数。
> 
> 是因为loki_ingester_memory_chunks太多了吗？导致总内存：4415 * 262144 bytes=1.07G，
> 总日志量是固定的，可以通过什么方法降内存？减小chunk_retain_period吗？chunk_retain_period目前设置的是1m

一个chunk里默认存10个block，估算的时候还得*10，另外还得看些压缩比的分布，这个loki_ingester_chunk_compression_ratio_bucket能查到，然后可以估算一下内存里一共存了多少数据。但最终占用Golang占用内存应该会比估算的值还会高。至于内存中Chunk会有这么多，可以看下

1. 报流量是不是很大，使得还没刷写呢内存就被写超了。 看你的配置里刷写频率+回收频率2分钟，看下两分钟内数据有多少进来
2. 看下刷写耗时，是不是有报错或者写S3慢
    cortex_s3_request_duration_seconds_bucket  这个指标可以查写S3返回码和耗时分布

**Comment by kirooshu** [comment]
We are experiencing the same problem. loki qeriers have 30G of memory and running 10 of them, yet, we are able to OOM them with queries from the frontend. As it was said before, it should not be possible to OOM with a query, it should either fail or be slow but not take pods with it.

I can share more information if you ask for something specific but we are ingesting 50k log lines per second and use boltdb-shipper with index/chunk storage in S3.

**Comment by sandeepsukhani** [comment]
> As it was said before, it should not be possible to OOM with a query, it should either fail or be slow but not take pods with it.
It is not possible to have a 100% protection against OOM kills because you can't tell in advance how much logs a query would fetch. The only way to protect against OOM kills now is to have proper limits set to avoid queries of deaths.

30G is a decent amount of memory and you run 10 of them so my bet would be on queries of deaths. You can find the details on limits config at https://grafana.com/docs/loki/latest/configuration/#limits_config

**Comment by sandeepsukhani** [comment]
@guobei2028 Are you facing the problem only when you run queries or Loki gets OOM killed even without any queries?

**Comment by cyriltovena** [comment]
@kirooshu can you share a pprof heap profile of the querier when that happens.

You need to port forward 3100 then you can get it at http://localhost:3100/debug/pprof/heap

**Comment by guobei2028** [comment]
> @guobei2028 Are you facing the problem only when you run queries or Loki gets OOM killed even without any queries?

yes，Oom often occurs when querying, but no specific rule is found. When oom occurs, a pod of Loki will restart automatically

**Comment by guobei2028** [comment]
> @ guobei2028您是否仅在运行查询或Loki即使没有任何查询都杀死OOM时才遇到问题？

Yes, oom often occurs during queries, but the specific query scenario is not found.

**Comment by guobei2028** [comment]
> @kirooshu can you share a pprof heap profile of the querier when that happens.
> 
> You need to port forward 3100 then you can get it at http://localhost:3100/debug/pprof/heap

**Comment by guobei2028** [comment]
> @guobei2028 Are you facing the problem only when you run queries or Loki gets OOM killed even without any queries?

I now encounter this problem, can you help me see what caused it?https://github.com/grafana/loki/issues/2950

**Comment by kong62** [comment]
> > @guobei2028 Are you facing the problem only when you run queries or Loki gets OOM killed even without any queries?
> 
> yes，Oom often occurs when querying, but no specific rule is found. When oom occurs, a pod of Loki will restart automatically

请问你是如何解决的呢？
我这边情况是这样：
1. 170 台 k8s 节点，4000 pod
2. 10 台 distrutor
3. 25 台ingester （40GB内存每台）
ingester 一直 OOM，limits-config 里面也都降低了一些参数，现在无解了

**Comment by marcusteixeira** [comment]
reopen please.

**Comment by puppetninja** [comment]
we are facing the same situation in our prod environment, the memory usage keeps growing till the pod got killed....we deploy with single binary mode though

**Comment by csdaraujo** [comment]
https://github.com/grafana/loki/issues/6501#issuecomment-1319843370

**Comment by fumanne** [comment]
> > > @guobei2028 Are you facing the problem only when you run queries or Loki gets OOM killed even without any queries?
> > 
> > 
> > yes，Oom often occurs when querying, but no specific rule is found. When oom occurs, a pod of Loki will restart automatically
> 
> 请问你是如何解决的呢？ 我这边情况是这样：
> 
> 1. 170 台 k8s 节点，4000 pod
> 2. 10 台 distrutor
> 3. 25 台ingester （40GB内存每台）
>    ingester 一直 OOM，limits-config 里面也都降低了一些参数，现在无解了

请问 最终你解决了吗？ 我想借鉴一下

**Comment by liuxuzxx** [comment]
我这边也碰到这个这个问题。
部署的Loki版本是: 2.9.2 部署方式是分布式的部署方式，部署的组件信息为:

Installed components:
* gateway : 1个
* ingester : 3个，每个给2500MB的内存
* distributor: 3个
* querier: 1个
* query-frontend:1个

发现的情况是：
1.其中一个Ingester一直重启，基本上是5-7分钟左右就会重启一下，看系统日志都是:OOMkill的问题

发现问题所在：
1.这个ingester的Pod里面的/var/loki/wal下面的文件很多，所以修改了下配置信息:

`yaml
    ingester:
      wal:
        dir: /var/loki/wal
        replay_memory_ceiling: 1GB  #这个配置默认是4GB，所以看到恢复的时候，一直加载这个wal下面的信息，导致OOMKill
`

**Comment by ahsifer** [comment]
I have read the following parameter and I think it might be useful. I am considering setting this parameter to the available memory for the pod.
```
-frontend.max-query-bytes-read value
    	Max number of bytes a query can fetch. Enforced in log and metric queries only when TSDB is used. The default value of 0 disables this limit.
```
