### ISSUE TITLE
Adding Math functions to line_format

### ISSUE THREAD

**Issue by Leosirth** [grafana/loki#2847]
**Is your feature request related to a problem? Please describe.**
I have a scenario where AccessLogs from my reverse proxy have the duration logged as nanoseconds.
It would be great if I could format the extracted label "duration" as milliseconds (dividing it by 1000000).

**Describe the solution you'd like**
Having the Math and Conversion functions from sprig available on line_format as a follow-up of #2822 PR
Something like:

```
{log_type="access_log"}
| json
| line_format "{{.ClientHost}}\t{{.OriginStatus}}\t{{div (.Duration | int) 1000000}}\t{{.RequestScheme}}\t{{.RequestAddr}}\t{{.RequestPath}}"
```

**Describe alternatives you've considered**
Using Grafana to graph it as a metric

**Additional context**
http://masterminds.github.io/sprig/math.html
http://masterminds.github.io/sprig/conversion.html

**Comment by cyriltovena** [comment]
I'm not against that.

/cc @grafana/loki-team who vouch for or against ?

I intentionally added strings functions only for now, wanted that we selectively choose what we add as we go.

**Comment by owen-d** [comment]
I can see this being a nice thing to have.

**Comment by Leosirth** [comment]
Good bot, keep it open

**Comment by Leosirth** [comment]
Good bot, keep it open

**Comment by m4ver1k** [comment]
@cyriltovena is someone working on this ?
if not is it something I can give a try ?

**Comment by cyriltovena** [comment]
We want to do it but we did not yet had the time so yeah go ahead
