### ISSUE TITLE
Configure authentication credentials in Loki docker log driver

### ISSUE THREAD

**Issue by chancez** [grafana/loki#2849]
**Is your feature request related to a problem? Please describe.**
I can't seem to configure authentication on the Loki docker log driver.

**Describe the solution you'd like**
I want to be able to configure things like bearer token auth, or basic auth credentials for the docker log driver.

**Describe alternatives you've considered**
Disabling authentication.

**Additional context**
The default tanka setup for Loki enables authentication, and thus anyone using that with the docker log driver might need to disable it if they wish to use the log driver with the tanka based Loki install.

**Comment by chancez** [comment]
@owen-d can this be reopened?

**Comment by owen-d** [comment]
Hey, sorry I haven't seen this. Does this work (from our [docs](https://grafana.com/docs/loki/latest/clients/docker-driver/configuration/)): 
`--log-opt loki-url="https://<user_id>:<password>@logs-us-west1.grafana.net/loki/api/v1/push"`

If not, I might be missing something here (I don't do much work on the docker driver).

**Comment by chancez** [comment]
@owen-d this works, but I was looking for first class support, so I can avoid storing the creds in the docker config.

**Comment by thomas-mc-work** [comment]
Same here. I'd prefer separate fields for username/password. This way docker secrets could be used which feels more appropriate.
