### ISSUE TITLE
logs from fluentd-loki output are cut of

### ISSUE THREAD

**Issue by wetescka** [grafana/loki#2857]
**Describe the bug**
logs are read from /var/log/ on a remote host and sent to fluentd. Fluentd forwards this logs to loki with the loki-plugin. If a log-event now contains a double quote ("), the message is cut of, with the key=value line format.

This only seems to happen with key=value, I had no issue with the json line format so far.

**To Reproduce**
1. Started Fluentd with loki-input plugin 
2. Read log-events that contain double quotes (") and forward them to fluentd
3. Checked results in Grafana

**Expected behavior**
Log-events that contain double quotes (") are escaped, like json line format.

**Environment:**
 - loki and fluentd running in container on docker

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
![image](https://user-images.githubusercontent.com/54581731/97719420-5ada4480-1ac7-11eb-9342-85d6a5395675.png)

**Comment by secustor** [comment]
I had a [chat](https://grafana.slack.com/archives/CBA3NSALE/p1604361419076200) with @ivanahuckova from the Frontend team and this seems to be a issue with escaption of quotes in the fluentD plugin. 
https://github.com/grafana/loki/blob/master/cmd/fluentd/lib/fluent/plugin/out_loki.rb#L282-L286
