### ISSUE TITLE
Searching logs with ANSI escape codes (colors)

### ISSUE THREAD

**Issue by talsaiag** [grafana/loki#2861]
**Issue description**
I'm always frustrated when I need to search for a string in a log containing multi-colors (ansi escape codes).

**Requested solution**
I would like the search feature using `|= "sub-string"` to ignore ansi-escaping and search the text itself.

**Alternatives we've considered**
We considered and decided not to remove the colors from the logs at the moment.

**Additional info**
Note that when simply refining the query in the query box (writing without hitting SHIFT+ENTER) the expected does happen (it marks all sub-strings correctly ignoring colors with dotted under-line) - but as soon as I hit SHIFT-ENTER the query returns nothing (if the filter-text is expected to span over multiple color spans)

**Comment by talsaiag** [comment]
closed in favor of https://github.com/grafana/grafana/issues/29039

**Comment by talsaiag** [comment]
as per [requested](https://github.com/grafana/grafana/issues/29039#issuecomment-786714329) by @ivanahuckova - re-opening the issue as it seems to be a filtering made by Loki itself and not Granfana's UI.

**Comment by ivanahuckova** [comment]
Please see https://github.com/grafana/grafana/issues/29039 for more context. Using of filter expression on log line that has ANSI only on specific characters/words doesn't work.

Lines with ANSI:
![image](https://user-images.githubusercontent.com/30407135/109331791-94487400-785d-11eb-8933-eada923ed26b.png)
Searching for Lorem ipsum:
![image](https://user-images.githubusercontent.com/30407135/109331738-809d0d80-785d-11eb-858a-0dad1a9527ea.png)
Searching only for ipsum:
![image](https://user-images.githubusercontent.com/30407135/109332004-d5408880-785d-11eb-8c92-92e09294b8fa.png)

**Comment by ivanahuckova** [comment]
+cc @cyriltovena @kavirajk

**Comment by cyriltovena** [comment]
Yup the `|=` does a string contains. I have to think about how we could skip those color code.

**Comment by talsaiag** [comment]
maybe something along the lines of `re.sub(r'\x1b\[[0-9;]*m', '', message)` (or the go equivalent for this logic) before checking string contains when filtering at the backend as well?
(not sure this covers all colors codes but this would work for our use-case at least)

**Comment by cyriltovena** [comment]
You can use  `!~ "re2 regex"` this in the meantime. For example `!~ "sub-string"` would work, but this isn't going to be fast.

**Comment by talsaiag** [comment]
it is not feasible to write an expression that correctly ignores escape codes while searching for a substring :\

**Comment by owen-d** [comment]
I think we could handle this in one of three ways:
1) Make it easier for promtail to filter out color codes
2) Let logql by default ignore color codes
3) Introduce a new logql operator to ignore these specifically.

Marking this as a zombie because we're not going to prioritize a PR for this, but we'd welcome external contributions!

**Comment by mueslo** [comment]
This is such a basic missing functionality, I am surprised it is still not fixed. It also leads to multiple follow-on issues, such as misclassified log levels.  The "decolorize" filter also doesn't help, since it doesn't actually seem to remove the ANSI codes from the searched log text, only from display.
