### ISSUE TITLE
Allow administrators to define line_format presets

### ISSUE THREAD

**Issue by cykl** [grafana/loki#2866]
**Is your feature request related to a problem? Please describe.**

Structured logs are often hard to read for humans because they contains too many details. Users typically want to hide most of the labels and focus on the essential ones. 

A sensible organization would encourages developers to use a common logs format and a set of standardized keys. This allows logging stack owners to provide a set of predefined formatting templates (ex. `line_format ".{{ts}} .{{level}} .{{message}}"` ).

Loki 2.0 allows user to format the log line using `line_format` which is great. But having to re-type  the same `line_format`s again and again is frustrating. 

**Describe the solution you'd like**

It would be great if Loki would allow the administrators to define some line_format "presets". That could improve developer experience both in Grafana and logcli.

**Describe alternatives you've considered**

Formatting could be seen as a client concern (ie. Grafana & logcli). And there is already some overlap between the "[toggling parsed field"](https://github.com/grafana/grafana/pull/26178)" feature available since Grafana 7.2 and `line_format`. 

**Additional context**

It should be easy to start with a canonical representation of a log and then add additional labels as need arise. It's unclear how it would work with preset templates.

**Comment by cykl** [comment]
While #2840 is a Grafana issue rather than a Loki one, it seems related.

**Comment by cyriltovena** [comment]
This is a great issue and use case, but I really wonder if this should be solved by Loki or the ui itself ?

**Comment by owen-d** [comment]
I can see this being helpful, but we won't be prioritizing it yet.
