### ISSUE TITLE
Download the logs

### ISSUE THREAD

**Issue by AdieOlami** [grafana/loki#2880]
I have some logs that I am able to view with grafana but I need to download the logs. I am able to get the particular logs I need for download via labels but how can I export these logs to my local machine or to an azure storage. Thanks

**Comment by pgassmann** [comment]
its possible to get the source logs with `logcli` directly from loki. But it would be useful, if one could download the logs in a usable format through grafana.

**Comment by marcbachmann** [comment]
This is a duplicate of #409

**Comment by pgassmann** [comment]
I reported the issue in the grafana project: Download Logs for manual processing
https://github.com/grafana/grafana/issues/28752
