### ISSUE TITLE
loki-logstash-output

### ISSUE THREAD

**Issue by yangvipguang** [grafana/loki#2886]
Please ask questions you have in the mailing list: https://groups.google.com/forum/#!forum/lokiproject

Or join our #loki slack channel at http://slack.raintank.io/
I have  configure  logstash with loki output :
![image](https://user-images.githubusercontent.com/11416887/98253557-20d0dd00-1fb6-11eb-99ac-bcd75839b445.png)

But Why Can't I see   two static labels as configured above。
![image](https://user-images.githubusercontent.com/11416887/98253410-f848e300-1fb5-11eb-9903-5e4e3656a561.png)

And  logstash  has no errors
![image](https://user-images.githubusercontent.com/11416887/98253873-8ae98200-1fb6-11eb-8e94-10ca1958e925.png)

**Comment by cyriltovena** [comment]
Can you do a text ouput see what fields comes out ?

**Comment by yangvipguang** [comment]
@cyriltovena 
I configure logstash  output as stdout:
![image](https://user-images.githubusercontent.com/11416887/98524216-ea46db00-22b1-11eb-90f1-5a5ad7965ebf.png) 

I can see cluster and  job have been added in the field.
but i have a little confued, will all the fields（version、tenant and so on） be added in the loki as labels？

**Comment by cyriltovena** [comment]
Can you share you configuration please ?

**Comment by yangvipguang** [comment]
`## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry, and imagePullSecrets
##
# global:
#   imageRegistry: myRegistryName
#   imagePullSecrets:
#     - myRegistryKeySecretName

## Bitnami Logstash image
## ref: https://hub.docker.com/r/bitnami/logstash/tags/
##
image:
  registry: registry.cn-hangzhou.aliyuncs.com
  repository: saas-databases/logstash-sls-loki
  tag: 7.9.3-debian-10-r9
  ## Specify a imagePullPolicy. Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: Always
  ## Optionally specify an array of imagePullSecrets (secrets must be manually created in the namespace)
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets:
  #   - myRegistryKeySecretName

  ## Set to true if you would like to see extra information on logs
  ## ref:  https://github.com/bitnami/minideb-extras/#turn-on-bash-debugging
  ##
  debug: true

## String to partially override logstash.fullname template (will maintain the release name)
##
# nameOverride:

## String to fully override logstash.fullname template
##
# fullnameOverride:

## Kubernetes Cluster Domain
##
clusterDomain: cluster.local

## Logstash configuration file name. It must match the name of the configuration file mounted as a configmap
##
configFileName: logstash.conf
## Whether to enable the Logstash Monitoring API or not  Kubernetes cluster domain
##
enableMonitoringAPI: true
## Logstash Monitoring API Port
##
monitoringAPIPort: 9600

## An array to add extra environment variables
## For example:
## extraEnvVars:
##  - name: ELASTICSEARCH_HOST
##    value: "x.y.z"
##
# extraEnvVars:

## Input Plugins configuration
## ref: https://www.elastic.co/guide/en/logstash/current/input-plugins.html
##
input: |-
 logservice {
   endpoint => "cn-shanghai-intranet.log.aliyuncs.com"
   access_id => "xxx"
   access_key => "xxx"
   project => "k8s-log-c009d1c4cf8f149e297da635b20c26fad"
   logstore => "service"
   consumer_group => "Runsa04-Logstash"
   consumer_name => "Runsa04-Logstash-loki"
   position => "end"
   checkpoint_second => 30
   include_meta => true
   consumer_name_with_ip => true
 }
## Filter Plugins configuration
## ref: https://www.elastic.co/guide/en/logstash/current/filter-plugins.html
##
# filter: |-
#   grok {
#     match => { "message" => "%{COMBINEDAPACHELOG}" }
#   }
#   date {
#     match => [ "timestamp" , "dd/MMM/yyyy:HH:mm:ss Z" ]
#   }
#
#
filter: |-
 mutate {
    add_field => {
      "source-data" => "aliyun-log"
    }
 }
## Output Plugins configuration
## ref: https://www.elastic.co/guide/en/logstash/current/output-plugins.html
output: |-
  loki {
    url => "http://loki:3100/loki/api/v1/push"
  }
## ConfigMap with Logstash configuration
## NOTE: This will override input, filter, and output parameters
##
# existingConfiguration:

## Array to add extra volumes (evaluated as a template)
## extraVolumes:
##   - name: myvolume
##     configMap:
##       name: myconfigmap
extraVolumes: []

## Array to add extra mounts (normally used with extraVolumes, evaluated as a template)
##
## extraVolumeMounts:
##   - mountPath: /opt/bitnami/desired-path
##     name: myvolume
##     readOnly: true
extraVolumeMounts: []

containerPorts:
  # - name: syslog-udp
  #   containerPort: 1514
  #   protocol: UDP
  # - name: syslog-tcp
  #   containerPort: 1514
  #   protocol: TCP
  - name: http
    containerPort: 8080
    protocol: TCP
  - name: monitoring
    containerPort: 9600
    protocol: TCP

## Number of Logstash replicas to deploy
##
replicaCount: 1

## Update strategy, can be set to RollingUpdate or OnDelete by default.
## ref: https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#updating-statefulsets
##
updateStrategy: RollingUpdate

## Pod management policy
## https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#pod-management-policies
##
podManagementPolicy: OrderedReady

## Pod annotations. Evaluated as a template
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
##
podAnnotations: {}

## Affinity for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}

## Node labels for pod assignment. Evaluated as a template.
## ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

## Tolerations for pod assignment. Evaluated as a template.
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: {}

## Pod priority
## ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
##
# priorityClassName: ""

## K8s Security Context for Logstash pods
## https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
##
securityContext:
  enabled: true
  fsGroup: 1001
  runAsUser: 1001

## Logstash containers' resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits: {}
  #   cpu: 100m
  #   memory: 128Mi
  requests: {}
  #   cpu: 100m
  #   memory: 128Mi

## Logstash pods' liveness and readiness probes
## ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes
##
livenessProbe:
  httpGet:
    path: /
    port: monitoring
  initialDelaySeconds: 60
  # periodSeconds: 10
  # timeoutSeconds: 5
  # successThreshold: 1
  # failureThreshold: 6
readinessProbe:
  httpGet:
    path: /
    port: monitoring
  initialDelaySeconds: 60
  # periodSeconds: 10
  # timeoutSeconds: 5
  # successThreshold: 1
  # failureThreshold: 6

## Service paramaters
##
service:
  ## Service type
  ##
  type: ClusterIP
  ## Logstash svc ports
  ##
  ports:
    # syslog-udp:
    #   port: 1514
    #   targetPort: syslog-udp
    #   protocol: UDP
    # syslog-tcp:
    #   port: 1514
    #   targetPort: syslog-tcp
    #   protocol: TCP
    http:
      port: 8080
      targetPort: http
      protocol: TCP
  # loadBalancerIP:
  ## Load Balancer sources
  ## https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/#restrict-access-for-loadbalancer-service
  ##
  # loadBalancerSourceRanges:
  # - 10.10.10.0/24
  ## Set the Cluster IP to use
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#choosing-your-own-ip-address
  ##
  # clusterIP: None
  ## Provide any additional annotations which may be required
  ##
  annotations: {}

## Ingress paramaters
##
ingress:
  ## Set to true to enable ingress record generation
  enabled: false

  ## Set this to true in order to add the corresponding annotations for cert-manager
  certManager: false

  ## Ingress annotations done as key:value pairs
  ## For a full list of possible ingress annotations, please see
  ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md
  ##
  ## If tls is set to true, annotation ingress.kubernetes.io/secure-backends: "true" will automatically be set
  ## If certManager is set to true, annotation kubernetes.io/tls-acme: "true" will automatically be set
  annotations: {}
  #  kubernetes.io/ingress.class: nginx

  ## The list of hostnames to be covered with this ingress record.
  ## Most likely this will be just one host, but in the event more hosts are needed, this is an array
  hosts:
    - name: logstash.local
      path: /

  ## The tls configuration for the ingress
  ## see: https://kubernetes.io/docs/concepts/services-networking/ingress/#tls
  # tls:
  # - hosts:
  #   - logstash.local
  #   secretName: logstash.local-tls

  secrets:
  ## If you're providing your own certificates, please use this to add the certificates as secrets
  ## key and certificate should start with -----BEGIN CERTIFICATE----- or
  ## -----BEGIN RSA PRIVATE KEY-----
  ##
  ## name should line up with a tlsSecret set further up
  ## If you're using cert-manager, this is unneeded, as it will create the secret for you if it is not set
  ##
  ## It is also possible to create and manage the certificates outside of this helm chart
  ## Please see README.md for more information
  # - name: logstash.local-tls
  #   key:
  #   certificate:

## Prometheus metrics
##
metrics:
  enabled: true
  ## Bitnami Logstash Promtheus Exporter image
  ## ref: https://hub.docker.com/r/bitnami/logstash-exporter/tags/
  ##
  image:
    registry: docker.io
    repository: bitnami/logstash-exporter
    tag: 0.1.2-debian-10-r250
    ## Specify a imagePullPolicy. Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets (secrets must be manually created in the namespace)
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ##
    # pullSecrets:
    #   - myRegistryKeySecretName

  ## Logstash Prometheus Exporter containers' resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits: {}
    #   cpu: 100m
    #   memory: 128Mi
    requests: {}
    #   cpu: 100m
    #   memory: 128Mi

  ## Prometheus Operator ServiceMonitor configuration
  ##
  serviceMonitor:
    enabled: false
    ## Namespace in which Prometheus is running
    ##
    # namespace: monitoring

    ## Interval at which metrics should be scraped.
    ## ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#endpoint
    ##
    # interval: 10s

    ## Timeout after which the scrape is ended
    ## ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#endpoint
    ##
    # scrapeTimeout: 10s

    ## ServiceMonitor selector labels
    ## ref: https://github.com/bitnami/charts/tree/master/bitnami/prometheus-operator#prometheus-configuration
    ##
    # selector:
    #   prometheus: my-prometheus

  ## Logstash Prometheus Exporter containers' liveness and readiness probes
  ## ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes
  ##
  livenessProbe:
    httpGet:
      path: /metrics
      port: metrics
    initialDelaySeconds: 60
    # periodSeconds: 10
    # timeoutSeconds: 5
    # successThreshold: 1
    # failureThreshold: 6
  readinessProbe:
    httpGet:
      path: /metrics
      port: metrics
    initialDelaySeconds: 60
    # periodSeconds: 10
    # timeoutSeconds: 5
    # successThreshold: 1
    # failureThreshold: 6

  service:
    ## Service type
    ##
    type: ClusterIP
    ## Logstash Prometheus port
    ##
    port: 9198
    ## Specify the nodePort value for the LoadBalancer and NodePort service types.
    ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
    ##
    nodePort: ""
    ## Set the LoadBalancer service type to internal only.
    ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
    ##
    # loadBalancerIP:
    ## Load Balancer sources
    ## https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/#restrict-access-for-loadbalancer-service
    ##
    # loadBalancerSourceRanges:
    # - 10.10.10.0/24
    ## Set the Cluster IP to use
    ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#choosing-your-own-ip-address
    ##
    # clusterIP: None
    ## Annotations for the Prometheus metrics service
    ##
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9198"
      prometheus.io/path: "/metrics"

## Pod disruption budget configuration
## ref: https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
##
podDisruptionBudget:
  ## Specifies whether a Pod disruption budget should be created
  ##
  create: false
  minAvailable: 1
  # maxUnavailable: 1
`

**Comment by yangvipguang** [comment]
I have change the  fillter  with adding only one field .

[values-no.txt](https://github.com/grafana/loki/files/5563824/values-no.txt)

![image](https://user-images.githubusercontent.com/11416887/99610538-fdde0880-2a4c-11eb-993e-b153765c13e6.png)

**Comment by adityacs** [comment]
@yangvipguang I can see that static labels added in logstash are pushed to loki. Below is my logstash configuration

```
input {
    beats {
        port => 5044
    }
}

filter {
  mutate {
    add_field => {
      "cluster" => "us-central1"
      "job" => "logstash"
    }
  }
}

output {
  loki {
    url => "http://localhost:3100/loki/api/v1/push"
  }
}
```

Screenshot from Grafana

<img width="439" alt="Screenshot 2020-12-17 at 3 30 22 PM" src="https://user-images.githubusercontent.com/7681197/102473198-32a9a380-407d-11eb-87c2-6f6a6704961b.png">

**Comment by yangvipguang** [comment]
@cyriltovena  @adityacs   I change the input with filebeat , it works well. So I guess the alicloud log plugin sls  is not work with loki. But works well with elasticsearch . I am so confusing.

**Comment by adityacs** [comment]
@yangvipguang We don't do anything special for Loki. We just read all the data available from logstash `event`.  If you can see the fields in `stdout` it should be available in Loki as well.

**Comment by krish512** [comment]
This is still a problem for me
When using Logstash, no labels are created in Loki

**Comment by cyriltovena** [comment]
There's little to no information on what your problem is.

**Comment by xom4ek** [comment]
Same problem with http input plugin.

**Comment by MuhammadNaeemAkhtar** [comment]
How can I add logstash-output-loki plugin. 
Bu running the following command "/usr/share/logstash/bin/logstash-plugin list logstash-output"
I only have the following plugins:
logstash-output-cloudwatch
logstash-output-csv
logstash-output-elastic_app_search
logstash-output-elasticsearch
logstash-output-email
logstash-output-file
logstash-output-graphite
logstash-output-http
logstash-output-kafka
logstash-output-lumberjack
logstash-output-nagios
logstash-output-null
logstash-output-pagerduty
logstash-output-pipe
logstash-output-rabbitmq
logstash-output-redis
logstash-output-s3
logstash-output-sns
logstash-output-sqs
logstash-output-stdout
logstash-output-tcp
logstash-output-udp
logstash-output-webhdfs

**Comment by MuhammadNaeemAkhtar** [comment]
Using "/usr/share/logstash/bin/logstash-plugin install logstash-output-loki" solved the problem

**Comment by sohel2020** [comment]
@adityacs 
This is my *stdout* from rubydebug. I can see that tag in the log browser but I don't see any log with that tag. 
`{
        "tag" => "tarikur-test",
    "message" => "host=gelftester @version=1 AppName=testapp Environment=test level=1 facility=gelftester user_id=42 version=1.0 source_host=172.17.0.1 @timestamp=2022-05-04T17:17:05.000Z longer test message. dontn worry be happy"
}`
