### ISSUE TITLE
absent_over_time and absent

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#2893]
Like for Prometheus https://prometheus.io/docs/prometheus/latest/querying/functions/#absent_over_time

absent_over_time can be useful for alerting when a stream disappears for too long. aka something stopped logging.

[ absent()](https://prometheus.io/docs/prometheus/latest/querying/functions/#absent) should also be implemented for vectors generated by range aggregations.

**Comment by tabnul** [comment]
eagerly waiting for this too.
what are possible workarounds? 
I am thinking of a time function like in prometheus (Extract last log record time from current time and alert if there is a result bigger than 5 minutes), but this doesnt seem possible either.

**Comment by ruanbekker** [comment]
Hey @tabnul , I made a workaround that fits my use-case, where I alert to slack when log content is not visible within one minute using AWS Lambda and CloudWatch Events:

- https://gist.github.com/ruanbekker/cb989521fbd55da3fc9165d9e94e24e5
