### ISSUE TITLE
Loki Canary hit max concurrent tail request limit

### ISSUE THREAD

**Issue by AClarkie** [grafana/loki#2894]
**Describe the bug**
When using Loki Canary with Loki in microservices mode the log tail check exceeds the max concurrent tail request limit.

From the docs:
https://grafana.com/docs/loki/latest/operations/loki-canary/

```
Meanwhile, Loki Canary will open a WebSocket connection to Loki and will tail the logs it creates. When a log is received on the WebSocket, the timestamp in the log message is compared to the internal array.
```

The logs from one of the failing canary pods:

```
Connecting to loki at ws://loki-gateway:80/loki/api/v1/tail?query=%7Bstream%3D%22stdout%22%2Cpod%3D%22loki-canary-dqjvk%22%7D, querying for label 'pod' with value 'loki-canary-dqjvk'
error reading websocket, will retry in 10 seconds: websocket: close 1011 (internal server error): rpc error: code = Code(400) desc = max concurrent tail requests limit exceeded, count > limit (11 > 10)
```

**To Reproduce**
1. Started Loki 2.0 in microservices mode
2. Started Loki Canary 2.0 pointing to the loki-gateway
3. Observe the logs of the loki-canary pods

**Expected behavior**
I expect the tail to work successfully 

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm 

**Screenshots, Promtail config, or terminal output**
Loki canary logs:
```
Connecting to loki at ws://loki-gateway:80/loki/api/v1/tail?query=%7Bstream%3D%22stdout%22%2Cpod%3D%22loki-canary-dqjvk%22%7D, querying for label 'pod' with value 'loki-canary-dqjvk'
error reading websocket, will retry in 10 seconds: websocket: close 1011 (internal server error): rpc error: code = Code(400) desc = max concurrent tail requests limit exceeded, count > limit (11 > 10)
```

**Comment by cyriltovena** [comment]
Are you running 10 canary ? you can change this limit via the configuration if you want to add more tail space for canaries.

**Comment by james-callahan** [comment]
We're also hitting this issue: with loki-canary running as a daemonset (which appears to be the recommendation?). Am I correct in that for a cluster with ~100 nodes, I would need to allow at least 100+x tail connections?

**Comment by james-callahan** [comment]
> I don't see an option for that? https://grafana.com/docs/loki/latest/configuration/#querier_config

I found `max_concurrent_tail_requests`/`querier.max-concurrent-tail-requests` in https://github.com/sandeepsukhani/loki/blob/master/pkg/util/validation/limits.go#L46
This config option is apparently undocumented.

**Comment by james-callahan** [comment]
.

**Comment by Jaypers** [comment]
Was there any solution for this?

**Comment by piratetm** [comment]
up

**Comment by lutartur** [comment]
for helm chart 6.2.2, mode [Simple Scalable ](https://grafana.com/docs/loki/latest/get-started/deployment-modes/#simple-scalable)
```
loki:
  ...
  structuredConfig:
    limits_config:
      ...
      max_concurrent_tail_requests: 100 
```
