### ISSUE TITLE
Ingester crashed with `fatal error: concurrent map writes`

### ISSUE THREAD

**Issue by jgehrcke** [grafana/loki#2905]
Observed with Loki 2.0.0 plus a few commits (specifically: fd451d9).

One ingester out of three crashed with `fatal error: concurrent map writes`.

Last regular log message of that ingester:
```
level=info ts=2020-11-09T14:53:46.987917425Z caller=table.go:425 msg="cleaning up unwanted dbs from table bk-2650-9a4-a_loki_index_18575"
```

Right after that, in stderr:
```
fatal error: concurrent map writes
```
And then this stack trace in stderr (just the leading end)
```
runtime.throw(0x226ac76, 0x15)
	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc000486cb8 sp=0xc000486c88 pc=0x437892
runtime.mapassign_fast64(0x1ee7600, 0xc0006b8780, 0xf4a203337233f5a3, 0xc04e9b5bc0)
	/usr/local/go/src/runtime/map_fast64.go:176 +0x325 fp=0xc000486cf8 sp=0xc000486cb8 pc=0x412ea5
	/src/loki/pkg/logql/log/pipeline.go:52 +0x185 fp=0xc000486d58 sp=0xc000486cf8 pc=0x15cde05
	/src/loki/pkg/ingester/instance.go:214 +0xa2 fp=0xc000486e18 sp=0xc000486d58 pc=0x1bb0f22
	/src/loki/pkg/ingester/instance.go:374 +0x227 fp=0xc000486ec8 sp=0xc000486e18 pc=0x1ba71e7
	/src/loki/pkg/ingester/instance.go:210 +0x1ec fp=0xc000486fa8 sp=0xc000486ec8 pc=0x1ba626c
	/src/loki/pkg/ingester/ingester.go:297 +0x1da fp=0xc000487608 sp=0xc000486fa8 pc=0x1ba1dda
	/src/loki/pkg/logproto/logproto.pb.go:2863 +0x10b fp=0xc000487660 sp=0xc000487608 pc=0x1580aeb
	/src/loki/pkg/loki/loki.go:198 +0x78 fp=0xc000487720 sp=0xc0004876d0 pc=0x1cb1bf8
google.golang.org/grpc.(*Server).processStreamingRPC(0xc00031f380, 0x26702a0, 0xc001591380, 0xc0425f7800, 0xc000642810, 0x34f9ac0, 0x0, 0x0, 0x0)
	/src/loki/vendor/google.golang.org/grpc/server.go:1336 +0x522 fp=0xc000487e40 sp=0xc000487c78 pc=0xa1c5e2
google.golang.org/grpc.(*Server).handleStream(0xc00031f380, 0x26702a0, 0xc001591380, 0xc0425f7800, 0x0)
	/src/loki/vendor/google.golang.org/grpc/server.go:1409 +0xc5c fp=0xc000487f68 sp=0xc000487e40 pc=0xa1e45c
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0001a68c0, 0xc00031f380, 0x26702a0, 0xc001591380, 0xc0425f7800)
	/src/loki/vendor/google.golang.org/grpc/server.go:746 +0xa5 fp=0xc000487fb8 sp=0xc000487f68 pc=0xa2c845
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000487fc0 sp=0xc000487fb8 pc=0x4701e1
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/src/loki/vendor/google.golang.org/grpc/server.go:744 +0xa5

	/src/loki/pkg/loki/loki.go:264 +0x6bd
main.main()
	/src/loki/cmd/loki/main.go:132 +0x59c
...
```

I do not have a repro yet, sorry. This does not seem to be deterministically reproducible. We've seen that in CI twice now. The test scenario / load remained the same; what changed is that we bumped Loki from 1.6.x to 2.0.0 (specifically to Loki commit fd451d9).

It is likely that we don't get a clean repro for this one. With this specific error message, though, I hope that the details provided so far are of value.

I can tell that `fatal error: concurrent map writes` was logged at `2020-11-09T14:53:58.706Z`. At that specific time the test client had issued a GET request with a query to Loki, and was waiting for the HTTP response. The HTTP response arrived at `2020-11-09T14:53:58.938Z` with

```
  status: 500
  body[:500]: rpc error: code = Unavailable desc = transport is closing
```
(which I guess is expected when an ingester goes away unexpectedly)

**Comment by jgehrcke** [comment]
@cyriltovena @slim-bean can we get some eyes on this one? :-) Still not further clue, but happens rather often during query.

**Comment by jgehrcke** [comment]
Is this a candidate for a fix?
https://github.com/grafana/loki/commit/095b4a1cb789e36458fdbb1360209865a8f97515

**Comment by cyriltovena** [comment]
Yep I submitted multiple fix for this recently should all be good now.

**Comment by jgehrcke** [comment]
Confirmed: never seen again.
