### ISSUE TITLE
Promtail error unable to parse syslog messages

### ISSUE THREAD

**Issue by shivangijaiswal26** [grafana/loki#2916]
Hi All, I have installed promtail as a binary and loki, grafana running as docker compose containers. Syslog -ng service is running and the configuration that i have given in syslog-ng.conf file is  .

destination d_loki {
 syslog("127.0.0.1" transport("tcp") port(9080));
};
While starting promtail its says listening to syslog target but i dont see job syslog present in grafana explore--> log-->job .
[root@hostname bin]# ./promtail -config.file ./config-promtail.yml
level=info ts=2020-11-11T02:57:47.055742192Z caller=syslogtarget.go:100 msg="syslog listening on address" address=[::]:1514
level=info ts=2020-11-11T02:57:47.055921902Z caller=server.go:194 http=[::]:9080 grpc=[::]:34493 msg="server listening on addresses"
level=info ts=2020-11-11T02:57:47.056087725Z caller=main.go:108 msg="Starting Promtail" version="(version=1.6.0, branch=HEAD, revision=6e3e2fa3)"
and the promtail configuration is mentioned below
[root@hostname bin]# cat config-promtail.yml
server:
 http_listen_port: 9080
 grpc_listen_port: 0
positions:
 filename: /tmp/positions.yaml
clients:
 - url: http://127.0.0.1:3100/loki/api/v1/push
scrape_configs:
 - job_name: journal
  journal:
   max_age: 12h
   labels:
    job: systemd-journal
  relabel_configs:
   - source_labels: ['__journal__systemd_unit']
    target_label: 'unit'
 - job_name: syslog
  syslog:
   listen_address: 0.0.0.0:1514
   idle_timeout: 60s
   label_structured_data: yes
   labels:
    job: "syslog"
  relabel_configs:
   - source_labels: ['__syslog_message_hostname']
    target_label: 'host'
[root@hostname bin]# docker ps
CONTAINER ID    IMAGE          COMMAND         CREATED      STATUS       PORTS          NAMES
a1c49902bf87    grafana/grafana:latest "/run.sh"        12 days ago    Up 12 days     0.0.0.0:3000->3000/tcp production_grafana_1
5e90792e730b    grafana/loki:1.6.0   "/usr/bin/loki -conf…" 12 days ago    Up 12 days     0.0.0.0:3100->3100/tcp production_loki_1
[root@hostname bin]#

Error received is error parsing syslog stream expecting a version  value in the range 1-999
Please assist me.

Thanks

**Comment by McPo** [comment]
This issue is caused by an incorrect syslog format.

Promtail only support syslog over TCP with RFC5424 format. https://grafana.com/docs/loki/latest/clients/promtail/scraping/#syslog-receiver

In my case I was attempting to send it from docker-compose (Not using the loki plugin as I also need metric support). Telling docker-compose to use RFC5424 resolved the issue for me

``` docker-compose
logging:
    driver: syslog
    options:
      syslog-address: "tcp://:1514"
      syslog-format: rfc5424
```
