### ISSUE TITLE
Promtail kubernetes_sd_config other roles apart from pod

### ISSUE THREAD

**Issue by itsLucario** [grafana/loki#2919]
If Promtail only uses kubernetes_sd_config pod role type to discover pods. Why there are other roles specified in promtail kubernetes_sd_config documentation. It really confuses the understanding of how it is working. And why/where/how other role types can be used/helpful (Which is not documented anywhere).

ConfigMap default: 
https://github.com/grafana/loki/blob/master/production/helm/promtail/templates/configmap.yaml

Kubernetes_sd_config promtail documentation
https://grafana.com/docs/loki/latest/clients/promtail/configuration/#kubernetes_sd_config

Kindly let me know if I'm wrong or am I missing something here.

**Comment by cyriltovena** [comment]
Promtail support other service discovery like this ec2 it allows to add ec2 metadata to your logs. Not sure I understand your question 


See https://grafana.com/docs/loki/latest/clients/aws/ec2/

**Comment by itsLucario** [comment]
In Promtail kubernetes_sd_config we use only **role: pod** to get the logs from containers and their metadata with relabel_config.

```
kubernetes_sd_configs:
      - role: pod
```

But according to documentation it also supports other roles such as `node, service, ingress etc. ` What is the use of these roles?
Cause I have seen no documentation in Promtail on how to make use of these roles.

**Comment by yongzhang** [comment]
I have the same question, I don't understand the difference in `kubernetes-pods-app-kubernetes-io-name`, `kubernetes-pods-app`, `kubernetes-pods-direct-controllers`, `kubernetes-pods-indirect-controller` and `kubernetes-other`.
