### ISSUE TITLE
Write logs to distributor via GRPC `Error: 12 UNIMPLEMENTED: unknown service logproto.Pusher`

### ISSUE THREAD

**Issue by codewithcheese** [grafana/loki#2921]
Tried to use GRPC to push to distributor but received the following error: `Error: 12 UNIMPLEMENTED: unknown service logproto.Pusher`. Distributor does not implement GRPC Pusher service. Therefore, it is not possible to push logs to the distributor via GRPC.

The Distributor should support receiving logs via GRPC for applications that need to use the API directly not via promtail. GRPC provides a number of benefits over REST such as HTTP2 without TLS.

**Comment by jgehrcke** [comment]
> that need to use the API directly not via promtail.

You can also POST protobuf messages over HTTP as of today, maybe that serves you as a middle ground :).
