### ISSUE TITLE
Multi-tenant support with Promtail as Deamonset

### ISSUE THREAD

**Issue by itsLucario** [grafana/loki#2938]
As per the Promtail documentations it has a stage called tenant which takes in a source or a value.

So when using promtail as Deamonset I must be able to use this tenant stage as below and logs must be separated to their respective tenant names. 
```

pipeline_stages:
  - tenant:
      source: namespace
```

The namespace given in above source is taken from kubernetes metadata through relabel_config. 
But once everything gets deployed I'm unable to get logs from Loki with `X-Scope-OrgID` set to namespace name.

It would be of great help if anyone can suggest what is wrong with this approach.

**Comment by cyriltovena** [comment]
Nothing wrongs with this, have you tried to run promtail with --dry-run to see what's happening. Are you sure the label namespace exists ?

Can you share your full config ?

**Comment by dbluxo** [comment]
Hi @itsLucario, have you followed this approach any further? How do you do the mapping between namespace and the setting of the X-Scope-OrgID in the Grafana requests?

**Comment by itsLucario** [comment]
Hi @dbluxo, 
Once the logs get sent from promtail along with tenant (Can be namespace name) to Loki. In Grafana you you'll be able to set the headers with X-Scope-OrgID with your tenant and you'll be able to view the logs.

**Comment by dbluxo** [comment]
How do you set the X-Scope-OrgID in Grafana, when configuring the Loki datasource as "Custom HTTP Header"? For me this option is ignored.

**Comment by itsraghurama** [comment]
@itsLucario I am trying to get the tenant info in the similar fashion using relabel_info but failing. As per the loki documentation tenant_id can be dynamically only by using the extracted fields. Can you please share the config snippet you using to set the tenant through relable_config?

**Comment by dbluxo** [comment]
When using the promtaill Helm Chart you can add the following after [this line](https://github.com/grafana/helm-charts/blob/promtail-6.0.2/charts/promtail/values.yaml#L257):

```yaml
      - tenant: # https://grafana.com/docs/loki/latest/clients/promtail/stages/tenant/
          source: namespace
```
