### ISSUE TITLE
Invalid Version 2 

### ISSUE THREAD

**Issue by reasland** [grafana/loki#2939]
**Describe the bug**
When attempting to query loki with grafana outputs 500 error of invalid version 2

**To Reproduce**
1. Started Loki (master)
2. Started Promtail (master) to tail '...'
3. Query: `api/datasources/proxy/2/loki/api/v1/query_range?direction=BACKWARD&limit=1728&query=sum(rate(%7Bjob%3D%22hybris%22%2Cenv%3D%22prd%22%7D%7C%3D%20%22ERROR%22%20%5B1m%5D))%20by%20(instance)&start=1605615224000000000&end=1605626025000000000&step=5`

**Expected behavior**
Expected to get a data set of results returned by query

**Environment:**
 - Infrastructure: [Azure VM, docker]
 - Deployment tool: [docker(chef)]

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
![image](https://user-images.githubusercontent.com/55564295/99408009-5a0e2480-28b5-11eb-9a38-785fe3994514.png)

**Comment by cyriltovena** [comment]
Fixes by #2945
