### ISSUE TITLE
Support cli autocompletion to logcli

### ISSUE THREAD

**Issue by ibotty** [grafana/loki#2949]
**Is your feature request related to a problem? Please describe.**
I would like to have completion for logcli in bash.

**Describe the solution you'd like**
I'd appreciate a simple `logcli completion bash` subcommand that generates bash completion.  Similarly maybe for other shells (zsh, fish, etc.).

**Comment by ibotty** [comment]
I'd still like to have autocompletion in bash.

**Comment by ibotty** [comment]
It's still relevant.

**Comment by dbirks** [comment]
I just found that the kingpin package (that logcli uses under the hood for argument parsing) includes some support for completion by default ([kingpin docs](https://github.com/alecthomas/kingpin#bashzsh-shell-completion)).

So I added this to my ~/.zshrc:
```
eval "$(logcli --completion-script-zsh)"
```

And I get some completions :slightly_smiling_face: 

![image](https://user-images.githubusercontent.com/7545665/193678202-987fce48-d5f4-4cd2-aaf2-388874bc1ef3.png)

**Comment by awsms** [comment]
> I just found that the kingpin package (that logcli uses under the hood for argument parsing) includes some support for completion by default ([kingpin docs](https://github.com/alecthomas/kingpin#bashzsh-shell-completion)).
> 
> So I added this to my ~/.zshrc:
> 
> ```
> eval "$(logcli --completion-script-zsh)"
> ```
> 
> And I get some completions 🙂
> 
> ![image](https://user-images.githubusercontent.com/7545665/193678202-987fce48-d5f4-4cd2-aaf2-388874bc1ef3.png)

is there anything like this for the fish shell?

**Comment by dbirks** [comment]
Hmm no it looks like it's an open issue upstream: https://github.com/alecthomas/kingpin/issues/259
