### ISSUE TITLE
Allow math on label_format expressions

### ISSUE THREAD

**Issue by owen-d** [grafana/loki#2955]
I would suggest we open up `label_format` stages to allow mathematical operations. For instance, say you wanted counts based on status code groups (2xx, 4xx, etc).

I'd like to use something like this, taking into account integer division to do the grouping: ` | json | status="{{.status / 100}}"`

/cc @cyriltovena @chancez WDYT?

**Comment by chancez** [comment]
So an example using that might be like this:
```
sum by (status_bucket) (count_over_time({} | logfmt | label_format status_bucket="{{ div .status 100}}"))
```

Also what about cases where the value of the label isn't fully known, for example with a duration field. Status has a fixed number of values (0-599 roughly speaking) so it's reasonable to just divide by 100. With a duration, we can do something similar, but what if we wanted to have a fixed number of buckets for a field with an unknown range of values. Or what if we wanted to have an unspecified amount of fixed size bucket, or a specific amount of fixed size buckets, with overflow going into the last bucket (or a spill-over bucket?).

**Comment by owen-d** [comment]
It'll probably be helpful to expose the ability to clamp values to `[min,max]`, operate on parse-able durations, etc, as you've suggested.

**Comment by chancez** [comment]
Not stale. After holidays discussion can continue.

**Comment by chancez** [comment]
Not stale

**Comment by chancez** [comment]
@owen-d can we get a keep alive label?
