### ISSUE TITLE
nginx log files

### ISSUE THREAD

**Issue by supermiguel** [grafana/loki#296]
I have some nginx pods, is there a way to expose their /var/log/nginx/error.log exposed to loki?

**Comment by tomwilkie** [comment]
Typically the idea is that you direct these log files to stdout, and then have promtail consume that.  See  https://github.com/cortexproject/cortex/blob/master/k8s/nginx-config.yaml#L8

Alternatively you could mount the host FS inside the nginx container, and in promtail, and have them share the logs that way.
