### ISSUE TITLE
Alertmanager authentication configuration for ruler

### ISSUE THREAD

**Issue by pgassmann** [grafana/loki#2963]
**Is your feature request related to a problem? Please describe.**

There is currently no option to configure authentication for the loki ruler to alertmanager connection.

Currently `ruler_config` only has a simple string option for alertmanager_url:
https://grafana.com/docs/loki/latest/configuration/#ruler_config

```yaml
# Comma-separated list of Alertmanager URLs to send notifications to.
# Each Alertmanager URL is treated as a separate group in the configuration.
# Multiple Alertmanagers in HA per group can be supported by using DNS
# resolution via -ruler.alertmanager-discovery.
# CLI flag: -ruler.alertmanager-url
[alertmanager_url: <string> | default = ""]
```

**Describe the solution you'd like**

Options to configure authentication. like in promtail for connection to loki: https://grafana.com/docs/loki/latest/clients/promtail/configuration/#client_config
Or prometheus configuration for alertmanager https://www.prometheus.io/docs/prometheus/latest/configuration/configuration/#alertmanager_config

Extract from promtail configuration:
```yaml
# If using basic auth, configures the username and password
# sent.
basic_auth:
  # The username to use for basic auth
  [username: <string>]

  # The password to use for basic auth
  [password: <string>]

  # The file containing the password for basic auth
  [password_file: <filename>]

# Bearer token to send to the server.
[bearer_token: <secret>]
```

**Describe alternatives you've considered**

Currently the only option seems to connect without authentication over a secure internal network, or otherwise restrict access to alertmanager by ip whitelisting. or use a cryptic url.

**Comment by m4ver1k** [comment]
@cyriltovena I was checking this issue, looks like this is not supported in Cortex atm or have I misunderstood something ? So the issue have to be opened in cortex right ?

https://github.com/cortexproject/cortex/blob/master/pkg/ruler/ruler.go#L78

**Comment by cyriltovena** [comment]
That is correct.

**Comment by owen-d** [comment]
Makes sense, we'll take a look!

**Comment by Lirt** [comment]
For anyone wanting to workaround across this missing functionality you can create simple nginx proxy with basic auth. It will proxy `alerts` POST request from Loki to AlertManager authenticating instead of Loki.

Here is sample gist that worked for me: https://gist.github.com/Lirt/c0cd37c1f76e01ce781710e210bc1c35

In Loki I only need to change configuration to use:

```yaml
...
ruler:
  alertmanager_url: http://nginx-proxy-to-alertmanager:9093
```

**Comment by harre-orz** [comment]
I also made my proxy deamon to solve the same problem, and the following processing has also been added.

- BASIC authentification. (this issue)
- multi posting alert to AlertManager.
- https and ignore certification check.
- append external_labels for like prometheus.  (I know that promtail can do a similar setting, but I needed this setting.)

https://github.com/harre-orz/loki-proxy-am

I hope these function in loki!

**Comment by pgassmann** [comment]
@owen-d @dannykopping This issue was assigned on Apr 15. Is there any progress so far?
@m4ver1k is there a corresponding issue in cortex?

**Comment by osipovdaniil** [comment]
i set ruler_client `tls_cert_path`, `tls_key_path`, but i can't connected to alertmanager. These params are not for `alertmanager_url`?

How can i connected to my alertmanager using tls?

**Comment by dannykopping** [comment]
Looking at https://github.com/grafana/loki/blob/main/pkg/ruler/base/notifier.go#L161-L176 which we forked from Cortex (most of the ruler implementation is from Cortex), you'll see references to `rulerConfig.Notifier`.

Confusingly, `Notifier` is mapped to the `alertmanager_client` key.
If you search for that key in https://cortexmetrics.io/docs/configuration/configuration-file/, you'll see the settings you can define for authentication.

I believe it would be:

```yaml
...

ruler:
  alertmanager_client:
    tls_cert_path: /path/to/cert
    ...
...
```

This is all very under-documented right now unfortunately, but I hope this solves your problem?

**Comment by osipovdaniil** [comment]
@dannykopping Yes, it's working for me! Thank's, Love you!

**Comment by dannykopping** [comment]
@pgassmann @harre-orz @Lirt @m4ver1k I believe https://github.com/grafana/loki/issues/2963#issuecomment-1017494557 is your answer. Please confirm?

**Comment by BenoitKnecht** [comment]
@pgassmann FYI `external_labels` have been implemented in #5450.

**Comment by dannykopping** [comment]
@pgassmann apologies, I seem to have missed your reply on this one.

> should I create issues for those: testing alertmanager connection at startup

I'm not sure what this will achieve TBH. If we check the connection at startup, that says nothing about the future state of the connection. I'm convinceable, though. Can you expand a bit on what you think we should do here?

> @pgassmann FYI `external_labels` have been implemented in #5450.

:heart:

**Comment by ilolicon** [comment]
> alertmanager_client:

> @dannykopping thank you. Yes, the option works.
> 
> ```
> ruler:
>   storage:
>     type: local
>     local:
>       directory: /data/loki/rules # volume, directory to scan for rules
>   rule_path: /data/loki/rules-temp # volume, store temporary rule files
>   alertmanager_url: "{{ loki_alertmanager_url }}"
>   enable_alertmanager_v2: true
> 
>   alertmanager_client:
>     basic_auth_username: "{{ loki_alertmanager_username }}"
>     basic_auth_password: "{{ loki_alertmanager_password }}"
> ```
> 
> Testing it was not so straightforward. At startup, loki does not check if the connection to alertmanager works! I needed to configure an alert that I can trigger, then add a line to a logfile that is collected by loki to find out if the change is working.
> 
> By testing this, i found also that it would also be useful to have an `external_labels` option for the ruler, so I can add a `alertsource` label to all alerts. otherwise you can't see where an alert in alertmanager is coming from. @harre-orz has implemented that feature in his proxy. [#2963 (comment)](https://github.com/grafana/loki/issues/2963#issuecomment-913088223)
> 
> should I create issues for those: testing alertmanager connection at startup and external labels?

```
  alertmanager_client:
    basic_auth_username: "{{ loki_alertmanager_username }}"
    basic_auth_password: "{{ loki_alertmanager_password }}"
``` 
thanks, It works for me

**Comment by deggja** [comment]
> ruler: Add support for alertmanager header authorization #6136

Sorry to barge into a already closed thread @pgassmann - but I'm also attempting to configure this for Loki right now and I'm having some issues due to a lack of documentation. Do you you (or anyone in this thread) mind sharing a working configuration?

Thanks, and sorry again .. :-)

**Comment by pgassmann** [comment]
@deggja what does not work? I'm still using the same config as written above: https://github.com/grafana/loki/issues/2963#issuecomment-1020291820
Altertmanager is set up with basic auth on the nginx reverse proxy.

**Comment by deggja** [comment]
> @dannykopping thank you. Yes, the option works.
> 
> ```
> ruler:
>   storage:
>     type: local
>     local:
>       directory: /data/loki/rules # volume, directory to scan for rules
>   rule_path: /data/loki/rules-temp # volume, store temporary rule files
>   alertmanager_url: "{{ loki_alertmanager_url }}"
>   enable_alertmanager_v2: true
> 
>   alertmanager_client:
>     basic_auth_username: "{{ loki_alertmanager_username }}"
>     basic_auth_password: "{{ loki_alertmanager_password }}"
> ```
> 
> Testing it was not so straightforward. At startup, loki does not check if the connection to alertmanager works! I needed to configure an alert that I can trigger, then add a line to a logfile that is collected by loki to find out if the change is working.
> 
> By testing this, i found also that it would also be useful to have an `external_labels` option for the ruler, so I can add a `alertsource` label to all alerts. otherwise you can't see where an alert in alertmanager is coming from. @harre-orz has implemented that feature in his proxy. [#2963 (comment)](https://github.com/grafana/loki/issues/2963#issuecomment-913088223)
> 
> should I create issues for those: testing alertmanager connection at startup and external labels?

i tried configuring it in a similar fashion.

However, my loki pods are giving the following error:

```
level=error ts=2023-05-23T13:50:25.586886176Z caller=notifier.go:534 user=1 alertmanager=https://mimir-alertmanager.com/alertmanager/api/v2/alerts count=1 msg="Error sending alert" err="bad response status 401 Unauthorized"
```

My config looks like this:

```
rulerConfig: 
    wal:
      dir: /loki/ruler-wal
    alertmanager_url: https://mimir-alerrtmanager.com/alertmanager/
    enable_alertmanager_v2: true
    alertmanager_client:
      basic_auth_username: ${loki_alertmanager_username}
      basic_auth_password: ${loki_alertmanager_password}
    ring:
      kvstore:
        store: inmemory
    enable_api: true
    rule_path: /loki/rules/fake/
    storage:
      type: azure
      local:
        directory: /loki/rules
```

And I could not find any docs on it like you stated - those seem to be MIA. So I was curious as to how you got this to work.. :-)
