### ISSUE TITLE
Support watching for PrometheusRules via Kubernetes API

### ISSUE THREAD

**Issue by steven-sheehy** [grafana/loki#2990]
**Is your feature request related to a problem? Please describe.**
Loki 2.0 added support for `PrometheusRule`-like objects to perform log alerts. However, they're not truly Kubernetes objects that are managed by a CRD like they are for Prometheus Operator. The only way to add these objects is one of the supported ruler [storage types](https://grafana.com/docs/loki/latest/alerting/#ruler-storage), via the ruler API or the Cortex CLI.

I'm using GitOps to deploy helm charts to many clusters and as such the CI pipeline can't use imperative tools like the Cortex CLI. Since I'm using local storage, currently I have to populate a Loki configmap with the `PrometheusRule`'s for all the apps across the cluster. Since Loki is a cluster-wide component it's in a separate chart than the apps that may get deployed multiple times to different namespaces. This requires editing the common chart that contains Loki whenever a separate app chart changes its log alerts. While this is declarative and useable with my deployment pattern, it's not very decentralized and won't scale as more apps get added.

**Describe the solution you'd like**
I suggest Loki add support for watching create, update or delete of `PrometheusRule` similar to how Prometheus Operator does. A [`ruleNamespaceSelector`](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#namespaceselector) would be used to listen for all namespaces or a list of namespaces. A [`ruleSelector`](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#prometheusspec) would be used to filter for a subset of rules within the configured namespaces. To differentiate between Prometheus controlled `PrometheusRule` and Loki controlled `PrometheusRule`, users can add a unique label to every rule like `rule=loki` and `rule=prometheus` and adjust their `ruleSelector` accordingly.

**Describe alternatives you've considered**
- Use the ruler API (I'm using local storage)
- Use the cortex CLI (I'm using local storage)

**Additional context**

**Comment by cyriltovena** [comment]
I think this is fine as long as it is done via sidecar that in the end uses the API to sync rules.

> I'm using GitOps to deploy helm charts to many clusters and as such the CI pipeline can't use imperative tools like the Cortex CLI.

We use GitOps and Cortex CLI, but I agree that it's not super declarative, it does try to sync all the time on each commit.

Basically this github actions, https://github.com/grafana/cortex-rules-action also works for Loki.

**Comment by steven-sheehy** [comment]
Not sure what you mean by sidecar. You want another process in your codebase besides Loki to watch for PrometheusRules? Doesn't it make more sense for Loki itself to be responsible for syncing those rules from multiple sources (S3, filesystem, k8s API, etc.) into its in-memory objects? Or maybe it should be a new storage type in Cortex that loki can use?
