### ISSUE TITLE
GET /loki/api/v1/query_range  exist bug

### ISSUE THREAD

**Issue by gpfwhu** [grafana/loki#2993]
import time

start_time=(int(time.time()) - 60* 5)*(10**9)

query='{project="XXX"} |= "ERROR" '&start=start_time

when   "|=" and "start" all in parameters,
the parameter "start" is inoperative

**Comment by cyriltovena** [comment]
you need to url encode this.

**Comment by cyriltovena** [comment]
urllib.urlencode(f)

**Comment by gpfwhu** [comment]
> you need to url encode this.

it is not the solution.

i just simplize the question

i use requests like 

requests.get(url, parameters) 
whichi parameters like 

{'query': '{project="XXX"} |= "ERROR" ', 'start': start_time}

requests has encode the parameter

**Comment by cyriltovena** [comment]
if Grafana can do it 
![image](https://user-images.githubusercontent.com/1053421/100783295-97a59e00-33db-11eb-8fa3-e0a6cc01bc1d.png)
Then you can too.
