### ISSUE TITLE
Doc issue with promtail timestamp stage

### ISSUE THREAD

**Issue by vx-i** [grafana/loki#2995]
I wanted to use 'location' setting in the promtail timestamp stage and got this error message:

invalid timestamp stage config: invalid location specified: The system cannot find the path specified.

**promtail.yaml**
scrape_configs:
- job_name: sql_exporter
  pipeline_stages:
  - match:
      selector: '{job="sql_exporter_log"}'
      stages:
      - regex:
          expression: "^I(?P<timestamp>\\d{4}\\s\\S+?)\\s{4}\\d+\\s\\S+\\s(?P<content>.*)$"
      - template:
          source: output
          template: '{{ .timestamp }} {{ .content }}'
      - timestamp:
          source: timestamp
          location: "Europe/Berlin"
          format: "0102 15:04:05.000000"          
      - output:
          source: output

**Expected behavior**
This configuration should work, because it's a valid IANA Timezone Database string.

**Environment:**
Windows 2016 Server, local installation as NSSM service

After I examine the source code, played with it on 'Go Playground' and everything was working, I took a closer look at Go time module documentation. There was my answer:

> LoadLocation returns the Location with the given name.
>
>If the name is "" or "UTC", LoadLocation returns UTC. If the name is "Local", LoadLocation returns Local.
>
>Otherwise, the name is taken to be a location name corresponding to a file in the IANA Time Zone database, such as >"America/New_York".
>
>The time zone database needed by LoadLocation may not be present on all systems, especially non-Unix systems. >LoadLocation looks in the directory or uncompressed zip file named by the ZONEINFO environment variable, if any, then looks >in known installation locations on Unix systems, and finally looks in $GOROOT/lib/time/zoneinfo.zip.

[Link](https://golang.org/pkg/time/#LoadLocation)

At least for Windows systems that means to use 'Local' as string, right? And if yes, shouldn't it be mentioned in the Loki documentation?

**Comment by vx-i** [comment]
No one an idea? Is there a best practice for windows and promtail?

**Comment by splitt3r** [comment]
This should be fixed by https://github.com/grafana/loki/issues/1361.
