### ISSUE TITLE
Metric Queries every query return data different

### ISSUE THREAD

**Issue by Enivel** [grafana/loki#2997]
**Describe the bug**
Metric Queries on  different start and end time query  same range return data inconsistent.

![Xnip2020-11-27_16-59-27](https://user-images.githubusercontent.com/1982819/100432820-18f7ea80-30d5-11eb-9100-f6aa164c0842.jpg)
![Xnip2020-11-27_16-54-24](https://user-images.githubusercontent.com/1982819/100432838-201ef880-30d5-11eb-884e-bff19b6768de.jpg)

![Xnip2020-11-27_16-58-30](https://user-images.githubusercontent.com/1982819/100432829-1d240800-30d5-11eb-8454-14ba9b95f77e.jpg)
![Xnip2020-11-27_16-57-58](https://user-images.githubusercontent.com/1982819/100432834-1e553500-30d5-11eb-9d7a-ec9a104c2bf9.jpg)

**To Reproduce**
install from helm loki version 2.0.0

**Comment by Enivel** [comment]
general log queries works fine

**Comment by cyriltovena** [comment]
Yes this is because you're not using $__interval for the range so you're not always looking at the whole range and some logs are skipped. 

`sum(rate(...[$__interval])` However I think for small timerange there's a Grafana bug see https://github.com/grafana/grafana/issues/29210

**Comment by Enivel** [comment]
thanks for your answer.
