### ISSUE TITLE
Install from source error

### ISSUE THREAD

**Issue by 1231sadqwf** [grafana/loki#3007]
docker run --rm --tty -i \
        -v /root/loki/.cache:/go/cache:delegated \
        -v /root/loki/.pkg:/go/pkg:delegated \
        -v /root/loki:/src/loki:delegated \
        grafana/loki-build-image:0.12.0 pkg/ingester/checkpoint.pb.go;
/usr/bin/docker-current: Error response from daemon: invalid bind mount spec "/root/loki/.cache:/go/cache:delegated": invalid mode: delegated.
See '/usr/bin/docker-current run --help'.
make: *** [pkg/ingester/checkpoint.pb.go] Error 125

**Comment by 1231sadqwf** [comment]
while I use make command will get this error

**Comment by cyriltovena** [comment]
what docker/os version are you on ? you can remove the :delegated everywhere that's mostly for mac but should be a no-op on linux/windows. Although I never tried it on windows.

**Comment by 1231sadqwf** [comment]
os: CentOS Linux release 7.4.1708 (Core)
docker: Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-203.git0be3e21.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      0be3e21/1.13.1
 Built:           Thu Nov 12 15:11:46 2020
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-203.git0be3e21.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      0be3e21/1.13.1
 Built:           Thu Nov 12 15:11:46 2020
 OS/Arch:         linux/amd64
 Experimental:    false

**Comment by 1231sadqwf** [comment]
> what docker/os version are you on ? you can remove the :delegated everywhere that's mostly for mac but should be a no-op on linux/windows. Although I never tried it on windows.

may I know how to remove delegated?

**Comment by cyriltovena** [comment]
https://github.com/grafana/loki/blob/master/Makefile#L72

Replace by

```
MOUNT_FLAGS :=
```
