### ISSUE TITLE
Start and end time parameters in query label_values(filename) loki

### ISSUE THREAD

**Issue by eduardoaw** [grafana/loki#3011]
I am setting up a logs grafana dashboard, and I would like to dynamically load the files that are generated in the logs directory into the dashboard selection variable via loki datasource.

I can load, but only the labels of log files that are modified are loaded.

After 1 day no longer appear.

-----------------------

26/11

![image](https://user-images.githubusercontent.com/11036786/100749404-628d5180-33c3-11eb-800b-2559c48f1eff.png)

27/11

![image](https://user-images.githubusercontent.com/11036786/100749443-6e791380-33c3-11eb-9160-fe30451f0671.png)

-----------------------

Know that api loki/api/v1/label/filename has the parameters ```start``` and ```end```

[Loki API Documentation](https://grafana.com/docs/loki/latest/api/#get-lokiapiv1labels)

Consulting the api, I have the expected results 

![image](https://user-images.githubusercontent.com/11036786/100749585-9f594880-33c3-11eb-8e55-7845a7bf80b7.png)

How can I pass these parameters in the query ```label_values(filename)```?

![image](https://user-images.githubusercontent.com/11036786/100749638-b4ce7280-33c3-11eb-9272-4e82b1206a20.png)

I've tried ```label_values({start: 1603506254000000000, end: 1607506254000000000}, filename)```, but it didn't work.

![image](https://user-images.githubusercontent.com/11036786/100749677-c283f800-33c3-11eb-95e4-9070e7ba2065.png)

Would have a way to spend an initial and final period, so that I could see all the label files for the current month?

**Comment by cyriltovena** [comment]
Dupe of https://github.com/grafana/grafana/issues/25205

**Comment by Mzs-code** [comment]
> Dupe of [grafana/grafana#25205](https://github.com/grafana/grafana/issues/25205)

start,end param still not work, Im not sure its a dupe

**Comment by Mzs-code** [comment]
> Dupe of [grafana/grafana#25205](https://github.com/grafana/grafana/issues/25205)

start,end param still not work, Im not sure its a dupe
