### ISSUE TITLE
Support show line context in LogQL syntax

### ISSUE THREAD

**Issue by alanhe** [grafana/loki#3019]
**Is your feature request related to a problem? Please describe.**
Grep supports showing contexts around the matching line, e.g.:
```bash
$ grep -B 1 -A 5 Exception *.log
```

It's useful when debugging messages span many lines, but LogQL does not seem to have similar feature.

I would like to have something like:
```text
{ ... } |= "Exception" |~ ".*socket.*" [1,5]
```

**Additional context**
Grafana has this "Show context" kinda work around, but
 1.  some of our users call APIs directly, and 
 2. when there are a lot lines, it is not easy to click the *Show context* link one-by-one.

**Comment by caleb15** [comment]
I would like this feature as well. (Ordinarily I would just +1 but I'm commenting to get rid of the stale bot)

**Comment by caleb15** [comment]
Ah, I'm guessing it's because the issue is closed. @slim-bean can this be reopened please? Another person asked for this in slack as well.

**Comment by lofwyr** [comment]
The "Show context" feature in grafana kinda works, but a more natural version is still preferred.

**Comment by mizeng** [comment]
The "Show context" feature in Grafana is a work around way which is not so accurate, which just trigger another 2 loqql queries with all the labels of the specific line and modified timestamp(before and after). It will show incorrect result in some scenarios which I encounter several times.

**Comment by folex** [comment]
Yeah, one has to press "show context" for every line. It would be awesome to see the whole log with -C10 right away.

**Comment by wiwwo** [comment]
+1 for this feature.
Any update?

**Comment by jonac21** [comment]
I think this feature could be very useful. +1

Please, re-open
