### ISSUE TITLE
Why Loki write disk not fast enough?

### ISSUE THREAD

**Issue by zxhdaniel** [grafana/loki#3022]
I am Testing Loki in Monolithic mode, dozens of promtail is pushing logs to Loki. I found that, when the logs are pushing, The disk write rate of Loki is not fast enough, is about 20MB, even though the ioutil of the device is not busy, the CPU usage is about 200%, but my host has 16 cores. But when the logs finish push, The disk write rate is rise to about 200MB, Is there some bottleneck about Loki?

There  is screenshot of dstat:
![25k 35.4G 3843M 67.9G 16.6G.png](http://ww1.sinaimg.cn/large/6a262fc6ly1gl9ts5nvcoj21940luqv5.jpg)

My host: 16 cores, 128g, The max CpuUsage of Loki is about 200%.

**Comment by cyriltovena** [comment]
Loki uses a flush loop so it doesn't flush to disk on received. What's the issue ?

**Comment by cyriltovena** [comment]
You can reduce the timer of the flush loop using

```
ingester:
  flush_check_period: 1s
```

By default its 30s

**Comment by zxhdaniel** [comment]
The case shows upon is already set the flush_check_period to 1s.
I wonder to know why the host is not so busy, why Loki can not obtain more resources?
