### ISSUE TITLE
[Feature Request] rate_over_time for unwrapped ranges

### ISSUE THREAD

**Issue by loganmc10** [grafana/loki#3044]
**Is your feature request related to a problem? Please describe.**
I am trying to collect Netflow via Loki. There are labels like DstAddr, SrcAddr, etc. The value is "Bytes", which is the unwrapped value.

I'd like to be able to chart the rate of this value, I assume I would need a ```rate_over_time``` function

**Describe the solution you'd like**
```rate_over_time``` for unwrapped values. If it supported grouping that would be icing on the cake.

**Describe alternatives you've considered**
I've considered messing around with a formula related to sum_over_time, and I assume this might be possible? For instance I assume something like ```sum_over_time/(time in seconds)``` would yield the rate?

**Comment by cyriltovena** [comment]
Yes that sounds like an interesting and missing feature.

What alternatives names comes up ? Should we use rate() if unwrap is there then use the value instead of rate_over_time ?
