### ISSUE TITLE
Does Loki docker driver respect `max-file` and `max-size` from json-driver?

### ISSUE THREAD

**Issue by vitalets** [grafana/loki#3046]
I have a docker daemon with the default json logging config:
```json
{
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "10m",
    "max-file": "3"
  }
}
```
Then I run a container that sends logs to Loki : 
```
docker run --log-driver=loki --log-opt loki-url="..." my-container
```
I don't specify `max-file` and `max-size` options.
What will be actual values of `max-file` and `max-size`?
Will Loki use it's defaults (`max-file=1`, `max-size=-1` per [docs](https://grafana.com/docs/loki/latest/clients/docker-driver/configuration/#supported-log-opt-options)) or it will borrow these options from json log driver?

It would be great to clarify in docs.
Thanks!

**Comment by cyriltovena** [comment]
It will use the default.

**Comment by vitalets** [comment]
Thanks, @cyriltovena !

How about such addition in docs?

> **Note**: The Loki logging driver still uses the json-log driver in combination with sending logs to Loki, this is mainly useful to keep the `docker logs` command working.
> You can adjust file size and rotation using the respective log option `max-size` and `max-file`. **Keep in mind that default values for these options are not taken from json-log configuration.**
> You can deactivate this behavior by setting the log option `no-file` to true.

**Comment by cyriltovena** [comment]
Sounds good !
