### ISSUE TITLE
The __host__ relabeling is not mandatory for kubernetes_sd_configs unlike the docs

### ISSUE THREAD

**Issue by y-taka-23** [grafana/loki#3054]
**Describe the bug**

The Document (docs/sources/clients/promtail/scraping.md) says that

> Promtail looks for a `__host__` label on each target and validates that it is set to the same hostname as Promtail's

It means that Promtail keeps the target iff the `__host__` label is defined AND its value coincides `HOSTNAME`.

On the other hand, actually, Promtail doesn't require the `__host__` label to discover Pods. The implementation (pkg/promtail/targets/file/filetargetmanager.go) is

```go
host, ok := labels[hostLabel]
if ok && string(host) != s.hostname {
    // drop the target
}
```

which means Promtail keeps the target iff the `__host__` is undefined OR, when defined, its value coincides `HOSTNAME`.

**Expected behaviour**

Firstly I tried fix the behavior to revise the conditional simply as:

```go
host, ok := labels[hostLabel]
if !ok || string(host) != s.hostname {
    // drop the target
}
```

But it cannot work because the `sync` method is for general targets (including non-service-discovered files) and we cannot assume they have the `__host__` label.

We know whether a target originates from `kubernetes_sd_configs` at the point of `NewFileTargetManager`, but cannot use the information after the method to keep/drop the target. Do you have any good ideas?

**Environment:**

 - Infrastructure: Kubernetes

**Comment by svenstaro** [comment]
I actually like this as I use `kubernetes_sd_configs` but cannot run Promtail as a DaemonSet as this is a multi-tenancy cluster. I only run a single Promtail per Namespace so I'd prefer not to be forced to hack around the `__HOST__` enforcement.
