### ISSUE TITLE
Allow for non-DaemonSet Kubernetes operation

### ISSUE THREAD

**Issue by svenstaro** [grafana/loki#3060]
**Is your feature request related to a problem? Please describe.**
I'm stuck on an OpenShift multi-tenant cluster and so I can't run a Promtail DaemonSet.

**Describe the solution you'd like**
As I would only like to monitor a couple of namespaces and use the Promtail Kubernetes integration, I came up with a solution that involves mounting a shared PVC that all logs in a namespace write their logs to. I then started a Promtail that also had this volume attached in order to re-create the DaemonSet-like experience with mounted host container logs.

The problem with this solution is that it's not currently supported and that it does not in fact work with the most recent version of Promtail. There are two unnecessary blockers right now:
- `__host__` label comparison with `$HOSTNAME`. This is not desired for my approach as I run a Promtail per namespace as opposed to per node.
- de644b52c introduced a check that breaks my current setup so I'm stuck on Promtail 1.5.0. The API pre-filtering needs to be disabled for my approach to work.

**Describe alternatives you've considered**
The only alternative is running sidecars with every single Pod but given the number of Pods I have, I find this unreasonably unwieldy.

**Additional context**
I think this would be fairly easily achieved by adding a CLI flag `-disable-kubernetes-checks` or something like that which would disable the `__host__` checks as well as the code introduced by de644b52c.

It would make Promtail quite a bit more flexible in how it could be used. The restrictions that are in place currently could easily be lifted.

**Comment by svenstaro** [comment]
Remove stale

**Comment by weinrea** [comment]
I too would be interested in a solution for this use case.
kubernetes_sd_configs  works fine in prometheus for a multi-tenant cluster and it's a shame that it doesn't for promtail.
