### ISSUE TITLE
GET /loki/api/v1/tail\ websocket endpoint not accepting the "start" query parameter

### ISSUE THREAD

**Issue by annelaurefroment** [grafana/loki#3066]
**Describe the bug**
The `GET /loki/api/v1/tail` websocket endpoint of loki is not accepting the "start" query param we feed to it. Despite having set the "start" query parameter to a certain epoch timestamp, the request still ends up defaulting it to the epoch timestamp of 1 hr ago from the current time.

**What was expected to happen?**
Logs are supposed to start from the provided start epoch input, and if the input is wrong then maybe a warning message saying that the start param has defaulted to one hour

**Steps to reproduce the problem:**
1. Start tailing a local instance with a timestamp specific timestamp (in this example I'm querying the local Grafana logs from the grafana job)
```
curl -H 'Sec-WebSocket-Version: 13' -H 'Sec-WebSocket-Extensions: permessage-deflate' -H 'Sec-WebSocket-Key: v4vMUSLqpDDrrvhrCqfE+Q==' -H 'Connection: keep-alive, Upgrade' -H 'Upgrade: websocket' 'http://localhost:3100/loki/api/v1/tail?query=%7Bjob%3D%22grafana%22%7D&start=1607631118000000000'
```
2. Logs flowing on start from 1607630862956435900 in my example instead of the given start 1607621787000000000
```
{"streams":[{"stream":{"filename":"/var/log/grafana/grafana.log","job":"grafana","server":"192.168.56.1"},"values":[["1607630862956435900"
```

**Comment by annelaurefroment** [comment]
The use case for setting the start parameter for the `/tail` endpoint is to backfill and continue streaming after the websocket connection drops off (because of some network issue for example).  
The workaround is to implement a batch job before restarting streaming to do the backfill. It works, but it would be easier to only use the `/tail` endpoint.

**Comment by sakryt** [comment]
I have the same problem with GET /loki/api/v1/query_range.
I wonder that if the "limit" parameter beyond the really data counts,  does Loki will return more data that out of the "start" parameter?

**Comment by matteobovetti** [comment]
Hi all, I have the same problem. I'm using tail API, with `start` parameter, for ingesting loki data starting from a timestamp to now (now = ~real time streaming).
I hope that this issue will be considerate in the future.

In the mean while, there are other kind of solution to get data from loki in real time starting from a timestamp?

In addition, we use the start parameter to recover when our ingestion service go down. And if the `start` parameter not work properly we lose some data.
