### ISSUE TITLE
fluent-bit broken starting with Helm chart version 2.1.1 (wrong output name)

### ISSUE THREAD

**Issue by Aransh** [grafana/loki#3081]
**Describe the bug**
Starting with version 2.1.1, the loki-stack helm chart changes the output name in the configmap for fluent-bit from "loki" to "grafana-loki" (which doesn't exist), resulting in the fluent-bit pods failing to start, with error:
"Output plugin 'grafana-loki' cannot be loaded
Error: You must specify an output target. Aborting"

**To Reproduce**
1. Install loki-stack helm chart with fluent-bit enabled.
2. Look at fluent-bit kubernetes pods logs, they would have failed to start an error.

**Expected behavior**
As in version 2.1.0 and below, the output name should be Loki to allow fluent-bit to start and function normally.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Comment by apryce** [comment]
I confirmed a hacky workaround of editing the configmap to loki to return service

**Comment by SergeyLadutko** [comment]
Make in configmap 
[Output]
Name loki  

this is a temporary solution
