### ISSUE TITLE
Twistlock reporting promtail image with Critical Vulnerability

### ISSUE THREAD

**Issue by Gerthum** [grafana/loki#3089]
**Describe the bug**
Running promtail image through Twistlock image scanner generates a critical security vulnerability.
Package: bzip2
Description: BZ2_decompress in decompress.c in bzip2 through 1.0.6 has an out-of-bounds write when there are many selectors. 

**To Reproduce**
Run image through Twistlock

**Expected behavior**

**Environment:**
N/A

**Screenshots, Promtail config, or terminal output**
![image](https://user-images.githubusercontent.com/22023028/102538208-e1e38a80-4110-11eb-84b5-24fbb5579d76.png)

**Comment by JeffLuoo** [comment]
bump this ticket up. Is there any fix to this Vulnerability?
