### ISSUE TITLE
LogCLI query fails with error "Failed to parse labels"

### ISSUE THREAD

**Issue by sandlis** [grafana/loki#309]
Steps:
1. Pushed logs with labels using /api/prom/push with command:

> curl --header "Content-Type: application/json"   --request POST   --data '{"streams": [{"labels": "{foo=\"bar\"}","entries": [{"ts": "2019-02-11T16:57:44.130307+05:30", "line": "sample" }]}]}'   http://127.0.0.1:3100/api/prom/push

2. Queried logs using logcli with command:

> ./logcli query '{foo="bar"}' --addr="http://localhost:3100"

It returned the following error:

> 2019/02/11 17:12:43 Failed to parse labels: syntax error

After investigating the issue, I found that currLabels were not being set in heapIterator.Next()
Will send a PR with fix for this.

**Comment by tomwilkie** [comment]
Fixed by #308
