### ISSUE TITLE
some labels get object not found in storage

### ISSUE THREAD

**Issue by aladmit** [grafana/loki#3098]
**Describe the bug**
Query with some labels works just fine, with others hit error object not found in storage.

For example, if I query `{job="kube-system/kube-apiserver"}` I get logs just as expected.
If I query `{job="monitoring/loki-distributor"}` I get object not found in storage.

**To Reproduce**
I'm don't know how to reproduce it :(

**Expected behavior**
I get logs for any labels.

**Environment:**
 - Infrastructure: Kubernetes on bare-metal, installed with kubespray
 - Deployment tool: helm chart loki-distributed with filesystem storage and boltdb-shipper

**Screenshots, Promtail config, or terminal output**
<details>
  <summary>Querier logs</summary>
  
`ts=2020-12-23T11:02:54.918070807Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 method=SeriesStore.GetChunkRefs level=debug metric=logs
ts=2020-12-23T11:02:54.918105574Z caller=spanlogger.go:53 org_id=fake traceID=3a3b75d10b9c4cbf method=SeriesStore.GetChunkRefs level=debug metric=logs
ts=2020-12-23T11:02:54.918159916Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 method=SeriesStore.lookupSeriesByMetricNameMatchers level=debug metricName=logs matchers=1
ts=2020-12-23T11:02:54.918196942Z caller=spanlogger.go:53 org_id=fake traceID=3a3b75d10b9c4cbf method=SeriesStore.lookupSeriesByMetricNameMatchers level=debug metricName=logs matchers=1
ts=2020-12-23T11:02:54.918286709Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 method=Store.lookupIdsByMetricNameMatcher level=debug metricName=logs matcher="job=\"monitoring/loki-distributor\""
ts=2020-12-23T11:02:54.91830802Z caller=spanlogger.go:53 org_id=fake traceID=3a3b75d10b9c4cbf method=Store.lookupIdsByMetricNameMatcher level=debug metricName=logs matcher="job=\"monitoring/loki-distributor\""
ts=2020-12-23T11:02:54.918403787Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 method=Store.lookupIdsByMetricNameMatcher level=debug matcher="job=\"monitoring/loki-distributor\"" queries=16
ts=2020-12-23T11:02:54.918415554Z caller=spanlogger.go:53 org_id=fake traceID=3a3b75d10b9c4cbf method=Store.lookupIdsByMetricNameMatcher level=debug matcher="job=\"monitoring/loki-distributor\"" queries=16
ts=2020-12-23T11:02:54.918454942Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 method=Store.lookupIdsByMetricNameMatcher level=debug matcher="job=\"monitoring/loki-distributor\"" filteredQueries=16
ts=2020-12-23T11:02:54.918590449Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 method=cachingIndexClient.cacheFetch level=debug hits=0 misses=16
ts=2020-12-23T11:02:54.918458997Z caller=spanlogger.go:53 org_id=fake traceID=3a3b75d10b9c4cbf method=Store.lookupIdsByMetricNameMatcher level=debug matcher="job=\"monitoring/loki-distributor\"" filteredQueries=16
ts=2020-12-23T11:02:54.91869594Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 method=Shipper.Downloads.Query level=debug table-name=loki_index_18619
ts=2020-12-23T11:02:54.918777901Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 method=Shipper.Downloads.Table.MultiQueries level=debug table-name=loki_index_18619 query-count=16
ts=2020-12-23T11:02:54.918776677Z caller=spanlogger.go:53 org_id=fake traceID=3a3b75d10b9c4cbf method=cachingIndexClient.cacheFetch level=debug hits=0 misses=16
ts=2020-12-23T11:02:54.91883139Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 level=debug queried=downloads-manager
ts=2020-12-23T11:02:54.918913868Z caller=spanlogger.go:53 org_id=fake traceID=3a3b75d10b9c4cbf method=Shipper.Downloads.Query level=debug table-name=loki_index_18619
ts=2020-12-23T11:02:54.918990426Z caller=spanlogger.go:53 org_id=fake traceID=3a3b75d10b9c4cbf method=Shipper.Downloads.Table.MultiQueries level=debug table-name=loki_index_18619 query-count=16
ts=2020-12-23T11:02:54.919028644Z caller=spanlogger.go:53 org_id=fake traceID=3a3b75d10b9c4cbf level=debug queried=downloads-manager
ts=2020-12-23T11:02:54.919050703Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 method=Store.lookupIdsByMetricNameMatcher level=debug matcher="job=\"monitoring/loki-distributor\"" entries=0
ts=2020-12-23T11:02:54.919091219Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 method=Store.lookupIdsByMetricNameMatcher level=debug matcher="job=\"monitoring/loki-distributor\"" ids=0
ts=2020-12-23T11:02:54.91914665Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 method=SeriesStore.lookupSeriesByMetricNameMatchers level=debug msg="post intersection" ids=0
ts=2020-12-23T11:02:54.919177202Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 method=SeriesStore.GetChunkRefs level=debug series-ids=0
ts=2020-12-23T11:02:54.91921901Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 method=SeriesStore.lookupChunksBySeries level=debug seriesIDs=0
ts=2020-12-23T11:02:54.919251404Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 method=SeriesStore.lookupChunksBySeries level=debug queries=0
ts=2020-12-23T11:02:54.91929169Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 method=SeriesStore.lookupChunksBySeries level=debug entries=0
ts=2020-12-23T11:02:54.919336071Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 method=SeriesStore.GetChunkRefs level=debug chunk-ids=0
ts=2020-12-23T11:02:54.919362959Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 method=SeriesStore.GetChunkRefs level=debug chunks-post-filtering=0
ts=2020-12-23T11:02:54.919215205Z caller=spanlogger.go:53 org_id=fake traceID=3a3b75d10b9c4cbf method=Store.lookupIdsByMetricNameMatcher level=debug matcher="job=\"monitoring/loki-distributor\"" entries=0
ts=2020-12-23T11:02:54.919411208Z caller=spanlogger.go:53 org_id=fake traceID=3a3b75d10b9c4cbf method=Store.lookupIdsByMetricNameMatcher level=debug matcher="job=\"monitoring/loki-distributor\"" ids=0
ts=2020-12-23T11:02:54.919470186Z caller=spanlogger.go:53 org_id=fake traceID=3a3b75d10b9c4cbf method=SeriesStore.lookupSeriesByMetricNameMatchers level=debug msg="post intersection" ids=0
ts=2020-12-23T11:02:54.919506241Z caller=spanlogger.go:53 org_id=fake traceID=3a3b75d10b9c4cbf method=SeriesStore.GetChunkRefs level=debug series-ids=0
ts=2020-12-23T11:02:54.919542946Z caller=spanlogger.go:53 org_id=fake traceID=3a3b75d10b9c4cbf method=SeriesStore.lookupChunksBySeries level=debug seriesIDs=0
ts=2020-12-23T11:02:54.919576345Z caller=spanlogger.go:53 org_id=fake traceID=3a3b75d10b9c4cbf method=SeriesStore.lookupChunksBySeries level=debug queries=0
ts=2020-12-23T11:02:54.919612103Z caller=spanlogger.go:53 org_id=fake traceID=3a3b75d10b9c4cbf method=SeriesStore.lookupChunksBySeries level=debug entries=0
ts=2020-12-23T11:02:54.919649553Z caller=spanlogger.go:53 org_id=fake traceID=3a3b75d10b9c4cbf method=SeriesStore.GetChunkRefs level=debug chunk-ids=0
ts=2020-12-23T11:02:54.919672963Z caller=spanlogger.go:53 org_id=fake traceID=3a3b75d10b9c4cbf method=SeriesStore.GetChunkRefs level=debug chunks-post-filtering=0
ts=2020-12-23T11:02:54.920455862Z caller=spanlogger.go:53 org_id=fake traceID=3a3b75d10b9c4cbf level=debug ingester-chunks-count=0
level=debug ts=2020-12-23T11:02:54.920508943Z caller=async_store.go:57 msg="got chunk ids from ingester" count=0
ts=2020-12-23T11:02:54.920611504Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 level=debug ingester-chunks-count=1
level=debug ts=2020-12-23T11:02:54.920673663Z caller=async_store.go:57 msg="got chunk ids from ingester" count=1
level=debug ts=2020-12-23T11:02:54.920745946Z caller=async_store.go:78 msg="post-filtering ingester chunks" count=1
ts=2020-12-23T11:02:54.920743794Z caller=spanlogger.go:53 org_id=fake traceID=3a3b75d10b9c4cbf method=query.Exec level=debug Ingester.TotalReached=1 Ingester.TotalChunksMatched=0 Ingester.TotalBatches=0 Ingester.TotalLinesSent=0 Ingester.HeadChunkBytes="0 B" Ingester.HeadChunkLines=0 Ingester.DecompressedBytes="0 B" Ingester.DecompressedLines=0 Ingester.CompressedBytes="0 B" Ingester.TotalDuplicates=0 Store.TotalChunksRef=0 Store.TotalChunksDownloaded=0 Store.ChunksDownloadTime=0s Store.HeadChunkBytes="0 B" Store.HeadChunkLines=0 Store.DecompressedBytes="0 B" Store.DecompressedLines=0 Store.CompressedBytes="0 B" Store.TotalDuplicates=0
ts=2020-12-23T11:02:54.920842063Z caller=spanlogger.go:53 org_id=fake traceID=3a3b75d10b9c4cbf method=query.Exec level=debug Summary.BytesProcessedPerSecond="0 B" Summary.LinesProcessedPerSecond=0 Summary.TotalBytesProcessed="0 B" Summary.TotalLinesProcessed=0 Summary.ExecTime=3.148868ms
ts=2020-12-23T11:02:54.920961561Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 method=LokiStore.fetchLazyChunks level=debug msg="loading lazy chunks" chunks=1
level=info ts=2020-12-23T11:02:54.920991515Z caller=metrics.go:81 org_id=fake traceID=3a3b75d10b9c4cbf latency=fast query="{job=\"monitoring/loki-distributor\"}" query_type=limited range_type=instant length=0s step=0s duration=3.148868ms status=200 throughput_mb=0 total_bytes_mb=0
ts=2020-12-23T11:02:54.921052886Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 method=Fetcher.processCacheResponse level=debug chunks=1 decodeRequests=0 missing=1
level=debug ts=2020-12-23T11:02:54.921137878Z caller=logging.go:66 traceID=3a3b75d10b9c4cbf msg="GET /loki/api/v1/query?query=%7Bjob%3D%22monitoring%2Floki-distributor%22%7D&time=1608721375000000000&limit=1000 (200) 3.726261ms"
level=error ts=2020-12-23T11:02:54.921273631Z caller=batch.go:659 msg="error fetching chunks" err="object not found in storage"
ts=2020-12-23T11:02:54.921379603Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 method=query.Exec level=debug Ingester.TotalReached=1 Ingester.TotalChunksMatched=0 Ingester.TotalBatches=0 Ingester.TotalLinesSent=0 Ingester.HeadChunkBytes="0 B" Ingester.HeadChunkLines=0 Ingester.DecompressedBytes="0 B" Ingester.DecompressedLines=0 Ingester.CompressedBytes="0 B" Ingester.TotalDuplicates=0 Store.TotalChunksRef=1 Store.TotalChunksDownloaded=1 Store.ChunksDownloadTime=370.861µs Store.HeadChunkBytes="0 B" Store.HeadChunkLines=0 Store.DecompressedBytes="0 B" Store.DecompressedLines=0 Store.CompressedBytes="0 B" Store.TotalDuplicates=0
ts=2020-12-23T11:02:54.921434356Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 method=query.Exec level=debug Summary.BytesProcessedPerSecond="0 B" Summary.LinesProcessedPerSecond=0 Summary.TotalBytesProcessed="0 B" Summary.TotalLinesProcessed=0 Summary.ExecTime=3.785025ms
level=info ts=2020-12-23T11:02:54.921486783Z caller=metrics.go:81 org_id=fake traceID=2b68bea5fb9a4b37 latency=fast query="{job=\"monitoring/loki-distributor\"}" query_type=limited range_type=range length=3h0m1s step=5s duration=3.785025ms status=500 throughput_mb=0 total_bytes_mb=0
level=warn ts=2020-12-23T11:02:54.921585567Z caller=logging.go:71 traceID=2b68bea5fb9a4b37 msg="GET /loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=%7Bjob%3D%22monitoring%2Floki-distributor%22%7D&start=1608710574000000000&end=1608721375000000000&step=5 (500) 4.153299ms Response: \"object not found in storage\\n\" ws: false; Accept: application/json, text/plain, */*; Accept-Encoding: gzip, deflate, br; Accept-Language: en-gb; Connection: close; User-Agent: Grafana/7.2.0; X-Forwarded-For: 172.25.110.0, 172.25.49.134, 172.25.49.134; X-Grafana-Org-Id: 1; X-Original-Forwarded-For: 109.252.193.175; X-Real-Ip: 172.25.110.0; X-Request-Id: b405cf53d79e19b55e34dda969d6a747; X-Scheme: http; uber-trace-id: 2b68bea5fb9a4b37:2b68bea5fb9a4b37:0000000000000000:0; "
ts=2020-12-23T11:02:58.115453848Z caller=memberlist_logger.go:74 level=debug msg="Initiating push/pull sync with: loki-ruler-856fb4dbb4-qdt79-983ecac1 172.25.22.226:7946"
ts=2020-12-23T11:03:09.08971896Z caller=memberlist_logger.go:74 level=debug msg="Stream connection from=172.25.22.226:35006"
ts=2020-12-23T11:03:28.117605971Z caller=memberlist_logger.go:74 level=debug msg="Initiating push/pull sync with: loki-distributor-5fd75cd446-n86v5-18b64a10 172.25.49.235:7946"
ts=2020-12-23T11:03:39.09164258Z caller=memberlist_logger.go:74 level=debug msg="Stream connection from=172.25.22.226:35882"
ts=2020-12-23T11:03:58.120137943Z caller=memberlist_logger.go:74 level=debug msg="Initiating push/pull sync with: loki-distributor-5fd75cd446-n86v5-18b64a10 172.25.49.235:7946"
level=info ts=2020-12-23T11:04:11.7610901Z caller=table_manager.go:181 msg="syncing tables"
level=debug ts=2020-12-23T11:04:11.761150039Z caller=table.go:302 msg="syncing files for table loki_index_18616"
level=debug ts=2020-12-23T11:04:11.761199917Z caller=table.go:309 msg="updates for table loki_index_18616. toDownload: [], toDelete: []"
level=debug ts=2020-12-23T11:04:11.761248603Z caller=table.go:302 msg="syncing files for table loki_index_18613"
`
</details>

<details>
  <summary>Ingester logs</summary>
  
`ts=2020-12-23T11:02:41.940937912Z caller=memberlist_logger.go:74 level=debug msg="Initiating push/pull sync with: loki-ruler-856fb4dbb4-qdt79-983ecac1 172.25.22.226:7946"
level=debug ts=2020-12-23T11:02:48.912536286Z caller=grpc_logging.go:41 method=/grpc.health.v1.Health/Check duration=90.992µs msg="gRPC (success)"
level=debug ts=2020-12-23T11:02:50.057807522Z caller=grpc_logging.go:41 method=/grpc.health.v1.Health/Check duration=50.438µs msg="gRPC (success)"
level=debug ts=2020-12-23T11:02:54.91865473Z caller=grpc_logging.go:58 duration=351.335µs method=/logproto.Querier/Query msg="gRPC (success)"
level=debug ts=2020-12-23T11:02:54.918708081Z caller=grpc_logging.go:58 method=/logproto.Querier/Query duration=333.17µs msg="gRPC (success)"
ts=2020-12-23T11:02:54.918823581Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 method=SeriesStore.GetChunkRefs level=debug metric=logs
ts=2020-12-23T11:02:54.918890027Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 method=SeriesStore.lookupSeriesByMetricNameMatchers level=debug metricName=logs matchers=1
ts=2020-12-23T11:02:54.91891793Z caller=spanlogger.go:53 org_id=fake traceID=3a3b75d10b9c4cbf method=SeriesStore.GetChunkRefs level=debug metric=logs
ts=2020-12-23T11:02:54.918995913Z caller=spanlogger.go:53 org_id=fake traceID=3a3b75d10b9c4cbf method=SeriesStore.lookupSeriesByMetricNameMatchers level=debug metricName=logs matchers=1
ts=2020-12-23T11:02:54.919020744Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 method=Store.lookupIdsByMetricNameMatcher level=debug metricName=logs matcher="job=\"monitoring/loki-distributor\""
ts=2020-12-23T11:02:54.919121274Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 method=Store.lookupIdsByMetricNameMatcher level=debug matcher="job=\"monitoring/loki-distributor\"" queries=16
ts=2020-12-23T11:02:54.91913525Z caller=spanlogger.go:53 org_id=fake traceID=3a3b75d10b9c4cbf method=Store.lookupIdsByMetricNameMatcher level=debug metricName=logs matcher="job=\"monitoring/loki-distributor\""
ts=2020-12-23T11:02:54.919170384Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 method=Store.lookupIdsByMetricNameMatcher level=debug matcher="job=\"monitoring/loki-distributor\"" filteredQueries=16
ts=2020-12-23T11:02:54.919234708Z caller=spanlogger.go:53 org_id=fake traceID=3a3b75d10b9c4cbf method=Store.lookupIdsByMetricNameMatcher level=debug matcher="job=\"monitoring/loki-distributor\"" queries=16
ts=2020-12-23T11:02:54.919283261Z caller=spanlogger.go:53 org_id=fake traceID=3a3b75d10b9c4cbf method=Store.lookupIdsByMetricNameMatcher level=debug matcher="job=\"monitoring/loki-distributor\"" filteredQueries=16
ts=2020-12-23T11:02:54.919428198Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 method=cachingIndexClient.cacheFetch level=debug hits=16 misses=0
ts=2020-12-23T11:02:54.919510038Z caller=spanlogger.go:53 org_id=fake traceID=3a3b75d10b9c4cbf method=cachingIndexClient.cacheFetch level=debug hits=16 misses=0
ts=2020-12-23T11:02:54.919523324Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 method=Store.lookupIdsByMetricNameMatcher level=debug matcher="job=\"monitoring/loki-distributor\"" entries=1
ts=2020-12-23T11:02:54.919564465Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 method=Store.lookupIdsByMetricNameMatcher level=debug matcher="job=\"monitoring/loki-distributor\"" ids=1
ts=2020-12-23T11:02:54.919592907Z caller=spanlogger.go:53 org_id=fake traceID=3a3b75d10b9c4cbf method=Store.lookupIdsByMetricNameMatcher level=debug matcher="job=\"monitoring/loki-distributor\"" entries=1
ts=2020-12-23T11:02:54.919623739Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 method=SeriesStore.lookupSeriesByMetricNameMatchers level=debug msg="post intersection" ids=1
ts=2020-12-23T11:02:54.919649189Z caller=spanlogger.go:53 org_id=fake traceID=3a3b75d10b9c4cbf method=Store.lookupIdsByMetricNameMatcher level=debug matcher="job=\"monitoring/loki-distributor\"" ids=1
ts=2020-12-23T11:02:54.919659561Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 method=SeriesStore.GetChunkRefs level=debug series-ids=1
ts=2020-12-23T11:02:54.919695566Z caller=spanlogger.go:53 org_id=fake traceID=3a3b75d10b9c4cbf method=SeriesStore.lookupSeriesByMetricNameMatchers level=debug msg="post intersection" ids=1
ts=2020-12-23T11:02:54.919780166Z caller=spanlogger.go:53 org_id=fake traceID=3a3b75d10b9c4cbf method=SeriesStore.GetChunkRefs level=debug series-ids=1
ts=2020-12-23T11:02:54.91969946Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 method=SeriesStore.lookupChunksBySeries level=debug seriesIDs=1
ts=2020-12-23T11:02:54.91985554Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 method=SeriesStore.lookupChunksBySeries level=debug queries=1
ts=2020-12-23T11:02:54.919922928Z caller=spanlogger.go:53 org_id=fake traceID=3a3b75d10b9c4cbf method=SeriesStore.lookupChunksBySeries level=debug seriesIDs=1
ts=2020-12-23T11:02:54.919963431Z caller=spanlogger.go:53 org_id=fake traceID=3a3b75d10b9c4cbf method=SeriesStore.lookupChunksBySeries level=debug queries=1
ts=2020-12-23T11:02:54.919959059Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 method=cachingIndexClient.cacheFetch level=debug hits=1 misses=0
ts=2020-12-23T11:02:54.920006818Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 method=SeriesStore.lookupChunksBySeries level=debug entries=1
ts=2020-12-23T11:02:54.920023233Z caller=spanlogger.go:53 org_id=fake traceID=3a3b75d10b9c4cbf method=cachingIndexClient.cacheFetch level=debug hits=1 misses=0
ts=2020-12-23T11:02:54.920047124Z caller=spanlogger.go:53 org_id=fake traceID=3a3b75d10b9c4cbf method=SeriesStore.lookupChunksBySeries level=debug entries=0
ts=2020-12-23T11:02:54.920093961Z caller=spanlogger.go:53 org_id=fake traceID=3a3b75d10b9c4cbf method=SeriesStore.GetChunkRefs level=debug chunk-ids=0
ts=2020-12-23T11:02:54.920119815Z caller=spanlogger.go:53 org_id=fake traceID=3a3b75d10b9c4cbf method=SeriesStore.GetChunkRefs level=debug chunks-post-filtering=0
ts=2020-12-23T11:02:54.920042659Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 method=SeriesStore.GetChunkRefs level=debug chunk-ids=1
level=debug ts=2020-12-23T11:02:54.92015897Z caller=grpc_logging.go:41 method=/logproto.Querier/GetChunkIDs duration=1.540669ms msg="gRPC (success)"
ts=2020-12-23T11:02:54.920195972Z caller=spanlogger.go:53 org_id=fake traceID=2b68bea5fb9a4b37 method=SeriesStore.GetChunkRefs level=debug chunks-post-filtering=1
level=debug ts=2020-12-23T11:02:54.920282802Z caller=grpc_logging.go:41 method=/logproto.Querier/GetChunkIDs duration=1.653712ms msg="gRPC (success)"
`
</details>

<details>
  <summary>Loki config</summary>
  

`    auth_enabled: false

    server:
      http_listen_port: 3100

    distributor:
      ring:
        kvstore:
          store: memberlist

    memberlist:
      join_members:
        - loki-memberlist

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
      chunk_idle_period: 30m
      chunk_block_size: 262144
      chunk_encoding: snappy
      chunk_retain_period: 1m
      max_transfer_retries: 0

    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_cache_freshness_per_query: 10m

    schema_config:
      configs:
        - from: 2020-09-07
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: loki_index_
            period: 24h

    storage_config:
      boltdb_shipper:
        shared_store: filesystem
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        cache_ttl: 168h
      filesystem:
        directory: /var/loki/chunks

    chunk_store_config:
      max_look_back_period: 0s

    table_manager:
      retention_deletes_enabled: false
      retention_period: 0s

    query_range:
      align_queries_with_step: true
      max_retries: 5
      split_queries_by_interval: 15m
      cache_results: true
      results_cache:
        cache:
          enable_fifocache: true
          fifocache:
            max_size_items: 1024
            validity: 24h

    frontend_worker:
      frontend_address: loki-query-frontend:9095

    frontend:
      log_queries_longer_than: 5s
      compress_responses: true

    compactor:
      shared_store: filesystem

    ruler:
      storage:
        type: local
        local:
          directory: /etc/loki/rules
      ring:
        kvstore:
          store: memberlist
      rule_path: /tmp/loki/scratch
      alertmanager_url: http://kube-prometheus-stack-alertmanager:9093
      external_url: https://alertmanager.xx
`
</details>

**Comment by aladmit** [comment]
Oh, I didn't see that warning in Loki-distributed chart. I guess this is root of all my problems.

> Querying will not be possible (or limited to the ingesters' in-memory caches) because that would otherwise require shared storage between ingesters and queriers

**Comment by TChinaBen** [comment]
Could you tell me how you solved it? I also met the same problem

**Comment by aladmit** [comment]
> Could you tell me how you solved it? I also met the same problem

Sure @TChinaBen! All ingesters and queriers should have shared storage. If you use S3-like storage, you set one bucket for queriers and ingesters, and it just works.

Unfortunately, I wanted to use Filesystem as storage. So, I scaled both ingesters and queriers replicas to 1, created a directory on a k8s node, and mounted it as a hostPath volume to ingester and querier StatefulSets. On the one hand, it works fine. But, on the other hand, it impossible to scale this solution horizontally because you are limited to one directory on only one server.

**Comment by TChinaBen** [comment]
Thank you very much for your answer. I have been stuck on this problem for a long time. I also use the file system as storage, and your answer is very helpful to me




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "grafana/loki"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月29日(星期二) 下午5:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [grafana/loki] some labels get object not found in storage (#3098)





  
Could you tell me how you solved it? I also met the same problem
  
Sure @TChinaBen! All ingesters and queriers should have shared storage. If you use S3-like storage, you set one bucket for queriers and ingesters, and it just works.
 
Unfortunately, I wanted to use Filesystem as storage. So, I scaled both ingesters and queriers replicas to 1, created a directory on a k8s node, and mounted it as a hostPath volume to ingester and querier StatefulSets. On the one hand, it works fine. But, on the other hand, it impossible to scale this solution horizontally because you are limited to one directory on only one server.
