### ISSUE TITLE
relabel_configs for __host__ matches too many targets

### ISSUE THREAD

**Issue by mindthevirt** [grafana/loki#3107]
**Describe the bug**
My EC2 instances by default don't have a FQDN but instead just the the short hostname. Since promtail will drop any targets where __host__ is not equal to the $HOSTNAME on the node, I tried to use a regex to match only one node but here is what's happening.

my configuration under relabel_configs:

` - source_labels: [__meta_ec2_private_dns_name]
        regex: '(^([^.]+))'
        target_label: __host__`

__meta_ec2_private_dns_name = test.mydomain.com
$HOSTNAME = test

There are other nodes I'm getting via ec2_sd_configs but none of the other nodes are named "test" and hence only one EC2 instance should match.

but instead all my ec2 instances seems to match for unknown reasons.

**To Reproduce**
1. Started Loki (SHA or version)
2. Started Promtail on an EC2 instance with ec2_sd_configs set. 
3. Query: browse to /targets and see everything matching.

**Expected behavior**
Only one ec2 instance, where the $HOSTNAME = (^([^.]+)) of __meta_ec2_private_dns_name should be matching

**Comment by cyriltovena** [comment]
use __host__ see https://grafana.com/blog/2020/07/13/loki-tutorial-how-to-set-up-promtail-on-aws-ec2-to-find-and-analyze-your-logs/
