### ISSUE TITLE
Promtail Not Reporting Rotated Log files

### ISSUE THREAD

**Issue by mnadeem** [grafana/loki#3108]
**Describe the bug**
Spring Boot ( And the underlying framework, Logback) [rotates ](https://docs.spring.io/spring-boot/docs/1.3.8.RELEASE/reference/html/boot-features-logging.html#boot-features-logging-file-output) the log files after reaching the max size (10MB in our case), what it means is, the previous file is renamed and the new empty file is created, subsequently all the new logs goes to the new log file.

If I look at the log file, it seems rotated log files are not being considered.

```
   level=info ts=2021-01-03T14:11:48.675999438Z caller=tailer.go:138 component=tailer msg="tail routine: tail channel closed, stopping tailer" path=/app/log/boot-prometheus-12-kwkls.log
level=info ts=2021-01-03T14:11:48.676098527Z caller=tailer.go:131 component=tailer msg="tail routine: exited" path=/app/log/boot-prometheus-12-kwkls.log
level=info ts=2021-01-03T14:11:55.598828608Z caller=tailer.go:166 component=tailer msg="skipping update of position for a file which does not currently exist"
level=info ts=2021-01-03T14:11:55.601859507Z caller=tailer.go:166 component=tailer msg="skipping update of position for a file which does not currently exist"
level=info ts=2021-01-03T14:11:55.602102601Z caller=tailer.go:166 component=tailer msg="skipping update of position for a file which does not currently exist"
level=info ts=2021-01-03T14:11:55.603313069Z caller=tailer.go:122 component=tailer msg="tail routine: started" path=/app/log/boot-prometheus-12-kwkls.log
ts=2021-01-03T14:11:55.603364338Z caller=log.go:124 component=tailer level=info msg="Seeked /app/log/boot-prometheus.log - &{Offset:10444467 Whence:0}"
ts=2021-01-03T14:11:55.853637618Z caller=log.go:124 component=tailer level=info msg="Re-opening truncated file /app/log/boot-prometheus.log ..."
ts=2021-01-03T14:11:55.855141649Z caller=log.go:124 component=tailer level=info msg="Successfully reopened truncated /app/log/boot-prometheus.log"
level=info ts=2021-01-03T14:12:05.598853169Z caller=tailer.go:166 component=tailer msg="skipping update of position for a file which does not currently exist"
level=info ts=2021-01-03T14:12:05.601948821Z caller=tailer.go:166 component=tailer msg="skipping update of position for a file which does not currently exist"
level=info ts=2021-01-03T14:12:15.598808288Z caller=tailer.go:166 component=tailer msg="skipping update of position for a file which does not currently exist"
level=info ts=2021-01-03T14:12:15.601943196Z caller=tailer.go:166 component=tailer msg="skipping update of position for a file which does not currently exist"
```

Promtail version is **2.1.0**

**To Reproduce**
1. Create Spring boot Java application, as described [here](https://reachmnadeem.wordpress.com/2021/01/02/logging-stack-for-spring-boot-application-using-grafan-loki-on-openshift-kubernetes/), 
2. make sure to set lower value for `logging.file.max-size` probably **1KB**
3.  Add the following scrap config
```
          - job_name: boot-prometheus
            static_configs:
              - targets:
                  - localhost
                labels:
                  job: boot-prometheus
                  __path__: /app/log/boot-prometheus*.log
```
3. When the log file is rotated, promtail excludes the new logs.

**Expected behavior**
Promtail should consider the new entries in the new rotated log files.

**Environment:**
 - Infrastructure:  Kubernetes on Openshift OKD
   OpenShift Master:   v3.11.0+7876dd5-361
   Kubernetes Master:   v1.11.0+d4cacc0

**Screenshots, Promtail config, or terminal output**
```
   level=info ts=2021-01-03T14:11:48.675999438Z caller=tailer.go:138 component=tailer msg="tail routine: tail channel closed, stopping tailer" path=/app/log/boot-prometheus-12-kwkls.log
level=info ts=2021-01-03T14:11:48.676098527Z caller=tailer.go:131 component=tailer msg="tail routine: exited" path=/app/log/boot-prometheus-12-kwkls.log
level=info ts=2021-01-03T14:11:55.598828608Z caller=tailer.go:166 component=tailer msg="skipping update of position for a file which does not currently exist"
level=info ts=2021-01-03T14:11:55.601859507Z caller=tailer.go:166 component=tailer msg="skipping update of position for a file which does not currently exist"
level=info ts=2021-01-03T14:11:55.602102601Z caller=tailer.go:166 component=tailer msg="skipping update of position for a file which does not currently exist"
level=info ts=2021-01-03T14:11:55.603313069Z caller=tailer.go:122 component=tailer msg="tail routine: started" path=/app/log/boot-prometheus-12-kwkls.log
ts=2021-01-03T14:11:55.603364338Z caller=log.go:124 component=tailer level=info msg="Seeked /app/log/boot-prometheus.log - &{Offset:10444467 Whence:0}"
ts=2021-01-03T14:11:55.853637618Z caller=log.go:124 component=tailer level=info msg="Re-opening truncated file /app/log/boot-prometheus.log ..."
ts=2021-01-03T14:11:55.855141649Z caller=log.go:124 component=tailer level=info msg="Successfully reopened truncated /app/log/boot-prometheus.log"
level=info ts=2021-01-03T14:12:05.598853169Z caller=tailer.go:166 component=tailer msg="skipping update of position for a file which does not currently exist"
level=info ts=2021-01-03T14:12:05.601948821Z caller=tailer.go:166 component=tailer msg="skipping update of position for a file which does not currently exist"
level=info ts=2021-01-03T14:12:15.598808288Z caller=tailer.go:166 component=tailer msg="skipping update of position for a file which does not currently exist"
level=info ts=2021-01-03T14:12:15.601943196Z caller=tailer.go:166 component=tailer msg="skipping update of position for a file which does not currently exist"
```

Refer this on how did I setup my Loki

https://reachmnadeem.wordpress.com/2021/01/02/logging-stack-for-spring-boot-application-using-grafan-loki-on-openshift-kubernetes/

**Comment by mnadeem** [comment]
No help even after making sure the new rotated file have new name (Added time stamp)

```
level=info ts=2021-01-03T17:27:25.535502192Z caller=tailer.go:122 component=tailer msg="tail routine: started" path=/app/log/boot-prometheus-37-9c62b_2021-03-01_0.log
ts=2021-01-03T17:27:25.535502885Z caller=log.go:124 component=tailer level=info msg="Seeked /app/log/boot-prometheus-37-9c62b_2021-03-01_0.log - &{Offset:0 Whence:0}"
level=info ts=2021-01-03T17:27:25.598810958Z caller=tailer.go:166 component=tailer msg="skipping update of position for a file which does not currently exist"
```

Restarted promtail as well. No luck :(

**Comment by cyriltovena** [comment]
Was this resolved ?

**Comment by yangvipguang** [comment]
@cyriltovena  I have the same issue .
![image](https://user-images.githubusercontent.com/11416887/156091888-53cd0388-7931-46f2-992f-79c6e2473f09.png)
![5EFA29F0-9E89-4226-8013-34F862317560](https://user-images.githubusercontent.com/11416887/156091909-69aa1b7e-7f34-4edf-a3ae-afb4a0d8fed6.png)

after 18:33:31.887. No logs have been reported, and the promtail logs indicate it is waiting for logs to appear, but Application log output is normal。
![image](https://user-images.githubusercontent.com/11416887/156091968-026e715b-20c5-47aa-86bd-b191227395c9.png)
![image](https://user-images.githubusercontent.com/11416887/156092381-7d5c95c0-6032-492f-bf64-0e77d1a69c45.png)

**Comment by pehon** [comment]
I got the same error in log "skipping update of position for a file which does not currently exist" because of abandoned log files under windows.

**Comment by 76mrmario** [comment]
There are som news for it?

**Comment by djukic-marko** [comment]
Hi, we seem to have the same problem. Upon changing the file name for log rotation, positions.yml seems to remember the position from renamed file and does not start reading the new file until the line specified in positions.yml is reached. Upon reaching that line (if logs grow that far), it starts shipping again to Loki.

It seems to me that it would be logical that positions.yml file is reset upon rotating logs, or am I missing something?
