### ISSUE TITLE
Line comments like PromQL

### ISSUE THREAD

**Issue by dannykopping** [grafana/loki#3112]
**Is your feature request related to a problem? Please describe.**
Using the Loki datasource, the LogQL query editor in the _Explore_ view in Grafana syntax-highlights line comments beginning with (`#`); this is specified in the Loki datasource's [syntax description](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/loki/syntax.ts#L166).

![image](https://user-images.githubusercontent.com/373762/103513784-fd21fa00-4e73-11eb-9116-3a9e69a5faff.png)

However, as far as I can tell, this feature is not implemented in LogQL.

**Describe the solution you'd like**
Implement line comments in a way that matches the UI syntax highlighting and mirrors PromQL so as to not violate expectations.

**Describe alternatives you've considered**
Interestingly, line comments using `//` work and I would _guess_ we get this for free since `goyacc` is used? I can't see it explicitly mentioned in the [grammar definition](https://github.com/grafana/loki/blob/master/pkg/logql/expr.y).

**Additional context**
I have a branch where I've hacked together an implementation - if the maintainers would like this feature, I'll happily submit a PR.

**Comment by cyriltovena** [comment]
👋 Yeah I think we want this. 

But currently this is handle by the go lexer (https://github.com/grafana/loki/blob/master/pkg/logql/lex.go#L102) but as you state, the go lexer only understand `//` and `/**/`.

Not sure where this should be done in the lexer or the parser (goyacc), might be easier in the lexer code, let me know if you need a hand.

**Comment by dannykopping** [comment]
@cyriltovena great!

I've got a very quick-n-dirty implementation done:
https://github.com/grafana/loki/compare/master...dannykopping:dannykopping/line-comments?expand=1

Do you think this is the right approach?

**Comment by dannykopping** [comment]
I should actually remove my parser changes - I just implemented it in the lexer.

**Comment by cyriltovena** [comment]
Yeah the lexer change looks good to me. Can you add more tests and some test in the lexer_test.go ?

**Comment by dannykopping** [comment]
Of course :+1: 
Expect a PR in the next day or two
