### ISSUE TITLE
Missing Documenation for BoltDB Shipper schema_config and storage_config

### ISSUE THREAD

**Issue by ThreeFx** [grafana/loki#3121]
**Describe the bug**

The configuration documentation is lacking with repect to the new BoltDB-Shipper (mode ?).

The documenation is also unclear on whether boltdb-shipper is actually stable, for example see [this page](https://grafana.com/docs/loki/latest/storage/#single-store). The descriptions of boltdb-shipper and boltdb conflict as far as I can tell.

**To Reproduce**
Open documentation at https://grafana.com/docs/loki/latest/configuration/#storage_config

**Expected behavior**
Documentation provided for the options listed in the [default local template](https://raw.githubusercontent.com/grafana/loki/v2.1.0/cmd/loki/loki-local-config.yaml)

**Environment:**
N/A

**Screenshots, Promtail config, or terminal output**
N/A

**Comment by maxmeyer** [comment]
Still a valid issue.

**Comment by C-Duv** [comment]
> Still a valid issue.

Yes, still valid: the document is not clear about BoltDB-Shipper.
