### ISSUE TITLE
Add mutations such as mutiplication/division to allow exposing metrics in the proper units

### ISSUE THREAD

**Issue by frittentheke** [grafana/loki#3129]
**Is your feature request related to a problem? Please describe.**
Some logs contain valuable metric data Promtail is able aggregate and expose as Prometheus metrics already.
Unfortunately the data is not always in the proper format / unit to follow the best-practices and to use the Prometheus recommended base-units (https://prometheus.io/docs/practices/naming/#base-units).
So a field extracted from a log could contain milliseconds instead of seconds or bits insteads of bytes.

**Describe the solution you'd like**
It would be great to have a few mutations such as multiplication or / division available which can be applied to fields.
Potentially this would could be covered by the `template` (https://grafana.com/docs/loki/latest/clients/promtail/stages/template/#supported-functions) feature and go-template. But unfortunately there are not arithmetic functions allowed / implemented (yet):

`invalid template stage config: template: pipeline_template:1: function \"div\" not defined"`

To not have to maintain a homegrown list of functions the Sprig library (http://masterminds.github.io/sprig/) could be added enabling more than enough magic to mutate things as required - i.e. use their `divf` on `ms` to become `seconds`.

**Describe alternatives you've considered**
This functionality cannot be covered by string manipulations such as the already available regex or the existing go template magic.

**Additional context**
-

**Comment by cyriltovena** [comment]
There's another issue somewhere for this. I prefer to add slowly what we need instead of using sprig, this is mostly because it is run on server side.

**Comment by frittentheke** [comment]
@cyriltovena thanks for your response !

I suppose you are talking about:
 * https://github.com/grafana/loki/issues/2847
 * https://github.com/grafana/loki/issues/2955
 
 which are technically related, but they are more about LogQL than the metrics extraction.
 In any case I suppose once implemented, those functions are likely applicable to all those cases.

**Comment by frittentheke** [comment]
not stale

**Comment by frittentheke** [comment]
@cyriltovena I believe this feature was implemented via merged PR https://github.com/grafana/loki/pull/3434 ?

**Comment by cyriltovena** [comment]
only for LogQL so far.
