### ISSUE TITLE
Targets added twice, causing OOO samples

### ISSUE THREAD

**Issue by tomwilkie** [grafana/loki#313]
We see targets added multiple times in promtail, where is should only happen once.  Can't for the life of me see why.

**Comment by tomwilkie** [comment]
Ah it is because they have an app and a name label - good catch @woodsaj!

**Comment by tomwilkie** [comment]
Want to unify the `syncers` to dedupe targets across scrapeconfigs, but then won't know how to remove them...

**Comment by woodsaj** [comment]
@tomwilkie cant we just fix the scrape_configs so that we only add the pods once.
eg, add  the following to https://github.com/grafana/loki/blob/master/production/ksonnet/promtail/promtail.libsonnet#L131
```
          // Drop pods with a 'name' and an 'app' label.  They will have already been added by 
          // the scrape_config that matches on the 'name' label
          {
            source_labels: ['__meta_kubernetes_pod_label_app'],
            action: 'drop',
            regex: '.+',
          },
```

**Comment by Kuqd** [comment]
seems to be fixed.
