### ISSUE TITLE
Provide Memberlist metrics

### ISSUE THREAD

**Issue by lmickh** [grafana/loki#3140]
It is hard to determine the health of the memberlist ring and tokens.  The only insight I've found into it so far is the `/ring` path.

It would be beneficial to include `memberlist` metrics similar to what Tempo is outputting so that split brains could be detected via metrics alerts.  Examples: `tempo_memberlist_client_cluster_members_count` and `tempo_memberlist_client_cluster_node_health_score`

**Comment by huikang** [comment]
Hi, @cyriltovena , have anyone taken this task? If not, I'd like to give it a shot. Thanks.

**Comment by huikang** [comment]
After some investigation, I found that the memberlist metrics have already been included in the current loki implementation. For example:

```
curl localhost:3100/metrics

# HELP memberlist_client_cluster_node_health_score Health score of this cluster. Lower value is better. 0 = healthy
# TYPE memberlist_client_cluster_node_health_score gauge
memberlist_client_cluster_node_health_score 0

# HELP memberlist_client_cluster_members_count Number of members in memberlist cluster
# TYPE memberlist_client_cluster_members_count gauge
memberlist_client_cluster_members_count 1
```

@cyriltovena , is it ok to close this?

**Comment by lmickh** [comment]
Ah!  You are right.  It does provide them, just not with the `loki_` prefix.  I assumed they would be the same as the other `loki_` metrics when I created the issue.
