### ISSUE TITLE
Garbled characters displayed

### ISSUE THREAD

**Issue by mnadeem** [grafana/loki#3145]
**Describe the bug**
Garbled characters displayed in the log along with valid log (interlaced) in Grafana

**To Reproduce**
1. Started Loki (grafana/loki:2.1.0, , Grafana 7.3.6)
2. Started Promtail (grafana/promtail:master-ee9c629) to tail '...'
3. Having multiple jobs configured, and query for jobs by some pattern `{job!="job-prefix*"}`

**Expected behavior**
Display the log text and not compressed characters.

**Environment:**
 - Infrastructure: Openshift OKD
 - Deployment tool: oc command line tool

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

![image](https://user-images.githubusercontent.com/476145/104020369-1a8ff480-51e3-11eb-87c0-6f90baec2d95.png)

![image](https://user-images.githubusercontent.com/476145/104020282-f3d1be00-51e2-11eb-935c-32373fa732b9.png)

**Comment by cyriltovena** [comment]
What storage are you using ? Seems like a corrupted chunk, what compression? Do you more info about config ? Is this happening only with one stream ?

**Comment by mnadeem** [comment]
I an storing it in S3, how can I get the compression
Yes this is happening only for one stream

**Comment by sterling000** [comment]
i'm getting the same thing from basic docker logs using the docker local log-driver on windows wsl2

**Comment by kirannhegde** [comment]
Hello @mnadeem  Were you able to resolve this issue ? If so , what was the resolution?

Thank,
Kiran Hegde
