### ISSUE TITLE
'entry out of order' for single stream

### ISSUE THREAD

**Issue by loganmc10** [grafana/loki#3154]
**Describe the bug**
I have a Python script that is using the requests library to send logs to Loki. It only sends 1 stream at a time, but sometimes (very rare), I get:
> Loki error: entry with timestamp 2021-01-11 13:22:44 +0000 UTC ignored, reason: 'entry out of order' for stream: {job="smarts"},
total ignored: 1 out of 1

**To Reproduce**
Here is the revelant Python code:
```
...
current_time = int(time.time()) * 1000 * 1000 * 1000
item_output['values'].append([str(current_time), json.dumps(logs)])
loki_output['streams'].append(item_output)

r = requests.post('https://logs-prod-us-central2.grafana.net/loki/api/v1/push', json=loki_output, auth=('MY_USER_NAME', 'MY_KEY'))
if r.status_code != 200 and r.status_code != 204:
    print("Loki error: " + r.text)
```

**Expected behavior**
I expected that in an HTTP POST with only 1 stream, it would be impossible for anything to be out of order.

**Environment:**
Python script, pushing to Grafana Cloud

**Comment by loganmc10** [comment]
I think I understand the issue, I thought the 'out of order' limitation was just per HTTP POST, but it seems that it is enforced on the Loki side for a given set of labels. I assume my script is somehow being executed in a somewhat out of order fashion.

**Comment by codeofsumit** [comment]
@loganmc10 How did you solve it?

**Comment by osipovdaniil** [comment]
@loganmc10 How to fix this problem?

**Comment by loganmc10** [comment]
I just misunderstood what the limitation was. Loki doesn't allow you to submit out of order logs. This is calculated based on the label set.

To avoid it, sometimes you have to make a larger label set so that there are more unique sets that aren't out of order (this goes against Loki's best practices, but is probably one of the only ways to avoid this issue)
