### ISSUE TITLE
loki-docker-driver plugin version always shows loki:latest

### ISSUE THREAD

**Issue by pgassmann** [grafana/loki#3155]
**Describe the bug**

When installing a specific version of the log driver, `docker plugin ls` always shows `loki:latest`

```bash
# docker plugin ls
ID                  NAME                DESCRIPTION           ENABLED
4f424e26e5eb        loki:latest         Loki Logging Driver   true
```
Is this an issue in the release process of the loki log driver docker plugin or is this a general issue with docker plugins?

When installing loki:latest, it's not possible to check if the installed version is up-to-date.

**To Reproduce**
1. Install specific version of the log driver `docker plugin upgrade loki grafana/loki-docker-driver:2.1.0 --grant-all-permissions --skip-remote-check`
2. `docker plugin ls`
3. see output showing `loki:latest`

Full update instructions:
```
# docker plugin disable loki -f
# docker plugin upgrade loki grafana/loki-docker-driver:2.1.0 --grant-all-permissions --skip-remote-check
# docker plugin enable loki
# systemctl restart docker
```

**Expected behavior**

when installing a specific version, `docker plugin ls` should show `loki:2.1.0`

When installing loki:latest, it should be possible to check if the installed version is up-to-date.

**Environment:**
 - Infrastructure: Ubuntu Server with Docker 19.03.13
 - Deployment tool: shell

**Additional Information**

With `docker plugin inspect loki` the version is visible in `"PluginReference"`

```bash
# docker plugin inspect loki
[
    {
        "Config": {
            "Args": {
                "Description": "",
                "Name": "",
                "Settable": null,
                "Value": null
            },
            "Description": "Loki Logging Driver",
            "DockerVersion": "17.09.0-ce",
            "Documentation": "https://github.com/grafana/loki",
            "Entrypoint": [
                "/bin/docker-driver"
            ],
            "Env": [
                {
                    "Description": "Set log level to output for plugin logs",
                    "Name": "LOG_LEVEL",
                    "Settable": [
                        "value"
                    ],
                    "Value": "info"
                }
            ],
            "Interface": {
                "Socket": "loki.sock",
                "Types": [
                    "docker.logdriver/1.0"
                ]
            },
            "IpcHost": false,
            "Linux": {
                "AllowAllDevices": false,
                "Capabilities": null,
                "Devices": null
            },
            "Mounts": null,
            "Network": {
                "Type": "host"
            },
            "PidHost": false,
            "PropagatedMount": "",
            "User": {},
            "WorkDir": "",
            "rootfs": {
                "diff_ids": [
                    "sha256:56a7c7af3e1b0ec95ab8cf1297e416487410b2554faf0c09f988840c7404d06d"
                ],
                "type": "layers"
            }
        },
        "Enabled": true,
        "Id": "4f424e26e5ebf503f593f32bd0cf22b386038f95c0b4184f90c71a2bc25952e8",
        "Name": "loki:latest",
        "PluginReference": "docker.io/grafana/loki-docker-driver:2.1.0",
        "Settings": {
            "Args": [],
            "Devices": [],
            "Env": [
                "LOG_LEVEL=info"
            ],
            "Mounts": []
        }
    }
]

```

PS: Also note that the DockerVersion is showing "17.09.0-ce" and not the current version of docker. Is that intentional?

**Comment by pgassmann** [comment]
Please /reopen the issue has multiple upvotes.

**Comment by cyriltovena** [comment]
I don't see how this could be fixed ? Docker documentation is really obscure. I'm happy to improve if you know where this is wrong ?

**Comment by aminvakil** [comment]
This is still an issue after two and half years, this may not be critical or important, at least this issue should've been kept opened.
