### ISSUE TITLE
When using S3 with an Access Key Secret with a '/' Loki is logging SignatureDoesNotMatch Error

### ISSUE THREAD

**Issue by stevejr** [grafana/loki#3161]
**Describe the bug**
When running Loki with S3 configured as the storage and an IAM Access Secret with a '/' in it which has been replaced with the URL encoded value of %2F Loki is returning a SignatureDoesNotMatch error when querying data via Grafana or when trying to sync tables

Error seen is:

`level=info ts=2021-01-12T19:08:51.114389075Z caller=loki.go:227 msg="Loki started"
level=error ts=2021-01-12T19:08:51.175651371Z caller=table_manager.go:218 msg="error syncing tables" err="SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.\n\tstatus code: 403, request id: FM4TEPCV6PBP9MBJ, host id: tneydXdjrY4JNPbqIuynPpiJAGNDBJHUEFYYNKwlsAWWS1NSpv8tOmiG83/sv5zPyz90fX9wgG0="
level=error ts=2021-01-12T19:08:51.176535554Z caller=compactor.go:83 msg="failed to run compaction" err="SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.\n\tstatus code: 403, request id: 99BCD411771FCC47, host id: kC/FuL4WHD6Iw0QuvFewDyYAKrpNUJPjPUvJuXqvbPvZjP7p1KNOO0Nr2pZDP4jhobcggQED6I0="`

Query from Grafana:

`evel=warn ts=2021-01-12T19:13:18.177291295Z caller=logging.go:71 traceID=315dbb5c924ce9c0 msg="GET /loki/api/v1/query_range?direction=BACKWARD&limit=1000&regexp=&start=1610475198000000000&end=1610478799000000000&step=1&query=%7Bnamespace%3D%22loki%22%7D (500) 28.086498ms Response: \"rpc error: code = Unknown desc = SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.\\n\\tstatus code: 403, request id: 1F70D3B5E494DB4E, host id: +CMuW6J7XjLbWdAKdTHIKzclk/fh2IcB1SfpseWgsWIjapD4N42Kvi2/RJe7oqgZXASAjsDYyGk=\\n\" ws: false; Accept: application/json, text/plain, */*; Accept-Encoding: gzip, deflate; Accept-Language: en-gb; Content-Type: application/json; User-Agent: Grafana/6.7.0; X-Forwarded-For: 127.0.0.1, 127.0.0.1; X-Grafana-Org-Id: 1; "
`
**To Reproduce**
1. Started Loki (SHA or version): Docker image grafana/loki:2.1.0
2. Started Promtail (SHA or version) to tail '...': Docker image grafana/promtail:2.1.0
3. Query: `{} term`

**Expected behavior**
When the secret is URL encoded Loki should work as expected

**Environment:**
 - Infrastructure: EKS
 - Deployment tool: Helm + Kustomize

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by stevejr** [comment]
If I change the Loki configuration so that I use an IAM Role on the Loki Service Account then access works fine and I do not see the Signature error

**Comment by harrychu-vista** [comment]
![image](https://user-images.githubusercontent.com/75280903/104970891-ee316f00-5a51-11eb-92f2-919f25be9fdb.png)
I'm having a similar issue here, when there is `/` in the secret key, the whole s3 bucket string will not be parsed correctly

**Comment by ashishkarpe** [comment]
@stevejr can you please let me know what changes did you make to your Loki config coz I am also stuck for the same thing. I have created aws secret for s3 bucket name but getting an 

error: `level=error ts=2021-09-13T07:53:10.506060453Z caller=table_manager.go:234 msg="error syncing tables" err="SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.\n\tstatus code: 403, `

**Comment by ashishkarpe** [comment]
> ![image](https://user-images.githubusercontent.com/75280903/104970891-ee316f00-5a51-11eb-92f2-919f25be9fdb.png)
> I'm having a similar issue here, when there is `/` in the secret key, the whole s3 bucket string will not be parsed correctly

did you get any solution ? if yes please share it will help me also

**Comment by stevejr** [comment]
@ashishkarpe - The only solution I found was to switch from using an Access ID/Secret to using the IAM Roles for Service Accounts feature (my cluster is an EKS one). This resolved the issue.

I had read elsewhere that the issue could be the Slash character in the secret which means that the parsing of the secret string stops at the slash and hence why you get the signature error. I think the only solution was to keep generating a secret until it didn't contain a slash but that seems extremely fragile to me hence why I went with the IAM role.

**Comment by ashishkarpe** [comment]
actually, to avoid parsing I changed my s3 path secret name from /mylogs/secret/path to myLogsBucketName but then now I am getting Getting error

**Comment by ashishkarpe** [comment]
@stevejr I have crated bucket using AWS SDK and when I try to use Access ID/Secret it works but I want to do it using IAM role but not sure what will be s3 URL in this case. So can you share your loki-config.yaml or any document to refer in case how to use case of IAM role instead of Access ID/Secret in s3 path URL?

**Comment by anandavijaya** [comment]
> @ashishkarpe - The only solution I found was to switch from using an Access ID/Secret to using the IAM Roles for Service Accounts feature (my cluster is an EKS one). This resolved the issue.
> 
> I had read elsewhere that the issue could be the Slash character in the secret which means that the parsing of the secret string stops at the slash and hence why you get the signature error. I think the only solution was to keep generating a secret until it didn't contain a slash but that seems extremely fragile to me hence why I went with the IAM role.

I replace slash to %2F and it worked

**Comment by kine-admin** [comment]
@anandavijaya where did make changes can you share please

**Comment by Akashkine** [comment]
@anandavijaya where did you make changes can you share please

**Comment by sweepchild** [comment]
> @anandavijaya where did you make changes can you share please

just change slashes (/) in secret with "%2F";

for example if secret is "abcdef1234/foo/bar123123"
it has to be changed to " "abcdef1234%2Ffoo%2Fbar123123"
