### ISSUE TITLE
add grafana-loki helm chart to hub.helm.sh

### ISSUE THREAD

**Issue by monotek** [grafana/loki#317]
I just started to create a Grafana Loki Helm chart because i did not find it on https://hub.helm.sh.

Could you please add the chart there?
 
Even when its in an early state i'm pretty sure it would help to spread the seed ;-)

**Comment by kfox1111** [comment]
Dup of https://github.com/grafana/loki/issues/186

**Comment by monotek** [comment]
sorry.
