### ISSUE TITLE
Can't provision dashboard from loki-mixin in Kubernetes: ConfigMap metadata.annotations is too long

### ISSUE THREAD

**Issue by cippaciong** [grafana/loki#3171]
**Describe the bug**
I use `kube-prometheus` to deploy Prometheus/Alertmanager/Grafana to Kubernetes. I am trying to add the alerts and dashboards provided by [loki-mixin](https://github.com/grafana/loki/tree/v2.1.0/production/loki-mixin/dashboards) but I am unable to apply the generated manifests due to this error:
```
The ConfigMap "grafana-dashboard-loki-operational" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

My understanding is that the error is not related to the dashboard length in the ConfigMap `data`, but rather to the `kubectl.kubernetes.io/last-applied-configuration` annotation created by `kubectl apply` ([see comment](https://github.com/prometheus-operator/prometheus-operator/issues/535#issuecomment-319649378)).

This problem affects only `grafana-dashboard-loki-operational`. If I manually delete its ConfigMap from the manifests, I can apply everything else without an error.

**To Reproduce**
1. Create a clean "`kube-prometheus`" configuration
2. Install `loki-mixin` running `jb install https://github.com/grafana/loki/production/loki-mixin@v2.1.0` (requires jsonnet-bundler)
3. Import the mixin in the jsonnet configuration:`(import 'github.com/grafana/loki/production/loki-mixin/mixin.libsonnet')`
4. Generate the manifests with `jsonnet` and apply them with `kubectl apply`

**Environment:**
 - Infrastructure: EKS running Kubernetes 1.18.9
 - Deployment tool: kube-prometheus 0.6, jsonnet, kubectl, jsonnet-bundler

**Configuration**
This is my `main.jsonnet` configuration.
```jsonnet
local kp =
  (import 'github.com/prometheus-operator/kube-prometheus/jsonnet/kube-prometheus/kube-prometheus.libsonnet') +

  // Uncomment the following imports to enable its patches
  (import 'github.com/prometheus-operator/kube-prometheus/jsonnet/kube-prometheus/kube-prometheus-anti-affinity.libsonnet') +
  (import 'github.com/prometheus-operator/kube-prometheus/jsonnet/kube-prometheus/kube-prometheus-managed-cluster.libsonnet') +

  // Additional mixins
  (import 'gitlab.com/uneeq-oss/cert-manager-mixin/mixin.libsonnet') +
  (import 'github.com/grafana/loki/production/loki-mixin/mixin.libsonnet') +

  // Custom configurations
  (import 'config/alertmanager-config.libsonnet') +
  (import 'config/alerting-rules.libsonnet') +
  (import 'config/general-requests-limits.libsonnet') +
  (import 'config/grafana-config.libsonnet') +
  (import 'config/grafana-dashboards.libsonnet') +
  (import 'config/prometheus-namespaces.libsonnet') +
  (import 'config/prometheus-retention-persistency.libsonnet') +


  {
    _config+:: {
      namespace: 'monitoring',

      versions+:: {
        alertmanager: 'v0.21.0',
        grafana: '7.3.5',
        nodeExporter: 'v1.0.1',
        prometheus: 'v2.23.0',
        prometheusAdapter: 'v0.8.2',
        kubeStateMetrics: '1.9.7',
      },
    },
  };


{ ['setup/0namespace-' + name]: kp.kubePrometheus[name] for name in std.objectFields(kp.kubePrometheus) } +
{
  ['setup/prometheus-operator-' + name]: kp.prometheusOperator[name]
  for name in std.filter((function(name) name != 'serviceMonitor'), std.objectFields(kp.prometheusOperator))
} +
// serviceMonitor is separated so that it can be created after the CRDs are ready
{ 'prometheus-operator-serviceMonitor': kp.prometheusOperator.serviceMonitor } +
{ ['node-exporter-' + name]: kp.nodeExporter[name] for name in std.objectFields(kp.nodeExporter) } +
{ ['kube-state-metrics-' + name]: kp.kubeStateMetrics[name] for name in std.objectFields(kp.kubeStateMetrics) } +
{ ['alertmanager-' + name]: kp.alertmanager[name] for name in std.objectFields(kp.alertmanager) } +
{ ['prometheus-' + name]: kp.prometheus[name] for name in std.objectFields(kp.prometheus) } +
{ ['prometheus-adapter-' + name]: kp.prometheusAdapter[name] for name in std.objectFields(kp.prometheusAdapter) }
{ ['grafana-' + name]: kp.grafana[name] for name in std.objectFields(kp.grafana) }
```

**Comment by kaflake** [comment]
I have the same error. Is there a solution or a workaround?

**Comment by timbrown5** [comment]
I am seeing this too.

**Comment by fitz123** [comment]
I've used this manual to add loki mixin and it works
https://github.com/prometheus-operator/kube-prometheus/blob/main/examples/mixin-inclusion.jsonnet
