### ISSUE TITLE
Set Labels from Environment Variables

### ISSUE THREAD

**Issue by base698** [grafana/loki#319]
Running `promtail` on a cluster, it would be handy to have information stored in labels from environment variables.  Examples would be hostnames, regions, rack location, etc.  Something that has to be specified during runtime.

**Comment by tomwilkie** [comment]
@base698 can you use config management to inject this into the config file?  There is an external labels field for this kind of thing - see https://github.com/grafana/loki/blob/master/production/ksonnet/promtail/promtail.libsonnet#L42

**Comment by base698** [comment]
I'm not familiar with libsonnet.  Where is this referenced:  $._config.promtail_config.external_labels ?

**Comment by yubozhao** [comment]
@base698 The reference for external_labels is at https://github.com/grafana/loki/blob/40ae03b48a4bba0c79f804cbe5ac82bcc0679344/pkg/promtail/client/client.go#L56

You can pass in as '--client.external_labels=LABELS' or generate a dynamic promtail-config base on your labels.

I will put up an example of this later on

**Comment by almariah** [comment]
@yubozhao `--client.external_labels` is not supported yet

**Comment by yubozhao** [comment]
@almariah It is not implemented yet?  That's too bad.  I thought it is implemented with https://github.com/grafana/loki/blob/439e7bb7d66fac44f5c85d5937df057348101824/pkg/promtail/client/client.go#L241

**Comment by almariah** [comment]
@yubozhao Yes `externalLabels ` is merged but from config file. Look at:

https://github.com/grafana/loki/blob/439e7bb7d66fac44f5c85d5937df057348101824/pkg/promtail/client/client.go#L68-L77

This is where parsing CLI are configured and `'--client.external_labels=LABELS'` not yet implemented.

**Comment by almariah** [comment]
@yubozhao I guess because parsing a map from CLI is not implemented in https://github.com/cortexproject/cortex/tree/master/pkg/util/flagext which is used in promtail for parsing flags

**Comment by yubozhao** [comment]
@almariah oh cool.  Thanks for point it out for me!  I haven't touch Loki for a long time, thanks for bring me up to speed.   I remember you could pass variables as container arguments.  Maybe that is changed now?
