### ISSUE TITLE
How to make Loki work with only AWS DynamoDB without S3?

### ISSUE THREAD

**Issue by rward27** [grafana/loki#3203]
Hi
I am able to configure Loki to make it work with S3+DynamoDB storage.

But I want to remove S3 from the picture and just use DynamoDB for both the types of storage viz: chunk and index store.

How can I achieve this? I tried to modify the config file but then my loki pod fails to start

**Comment by MarjanJordanovski** [comment]
Anyone on this? I get error on loki pod when try only dynamodb: at least one bucket must be specified
