### ISSUE TITLE
Please add compression ability in push API

### ISSUE THREAD

**Issue by ukolovda** [grafana/loki#3205]
**Is your feature request related to a problem? Please describe.**
I need send very big logs.
When I send it to Loki, I have high network traffic between servers.

**Describe the solution you'd like**
I want send compressed POST body (JSON in my case) to API for reduce network traffic.
I try GZIP logs. File reduced to 25-30 times from origin size.

Gzipped API can have some extension: /loki/api/v1/push.gz
Or use HTTP request header "Content-Encoding: gzip"

**Describe alternatives you've considered**
It may be proprietary HTTP or TCP service on same node (where runs Loki), which will receive GZIPped log data (in custom format), decompress it and send to Loki.

**Additional context**

**Comment by cyriltovena** [comment]
The API currently support proto snappy encoded or json. I'm not opposed to allow for gzip json.
