### ISSUE TITLE
Incorrect lines returned with '| logfmt' and limit

### ISSUE THREAD

**Issue by pawel-jaworski** [grafana/loki#3208]
**Describe the bug**
When querying for lines with `{label="value"} | logfmt` and `limit` set to be lower than the total number of lines in Loki, initially incorrect lines are returned. After ~ 5 mins, the result is correct. Approximate 5 mins time does not depend on the number of lines in Loki. Example below shows the behaviour for total 8 lines in Loki and `limit=2`, but the same behaviour occurred for 20000 lines in Loki and `limit=5000`.

**To Reproduce**
Steps to reproduce the behaviour:
1. Send 8 lines to Loki in 2 streams, with alternate timestamps:
```
1611241643000000000 {host="agent" log_stream="dispatcher" job="3"} msg="dispatcher_0"
1611241643000000001 {host="agent" log_stream="cmd_worker" job="3"} msg="cmd_worker_1"
1611241643000000002 {host="agent" log_stream="dispatcher" job="3"} msg="dispatcher_2"
1611241643000000003 {host="agent" log_stream="cmd_worker" job="3"} msg="cmd_worker_3"
1611241643000000004 {host="agent" log_stream="dispatcher" job="3"} msg="dispatcher_4"
1611241643000000005 {host="agent" log_stream="cmd_worker" job="3"} msg="cmd_worker_5"
1611241643000000006 {host="agent" log_stream="dispatcher" job="3"} msg="dispatcher_6"
1611241643000000007 {host="agent" log_stream="cmd_worker" job="3"} msg="cmd_worker_7"
```
Row format is `nanosecond_unix_epoch {label1="value1" ... labelN="valueN"} log_line`, where in our case N=3

2. In `logcli` run: `query '{job="3"}' --limit 2`
3. In `logcli` run: `query '{job="3"} | logfmt'`
4. In `logcli` run: `query '{job="3"} | logfmt' --limit 2`
5. Wait ~ 5 mins (on my machine, possibly can be less/more on a different machine) wrt first Loki line timestamp.
6. Repeat query from step 4.

**Expected behavior**
The lines returned in step 4 should be the same as in step 2. In step 4, only the logs from one stream are returned and they start from the middle. Only after waiting ~ 5 mins, the lines returned in step 6 are the same as in step 2. Output of step 3 shows that all logs are correctly sent to Loki.

**Environment:**
 - Ubuntu 18.04.5 LTS x86-64
 - Loki 2.1.0 (branch: HEAD, revision: 1b79df37)

**Screenshots, Promtail config, or terminal output**
Step 2:
```
pawel@asus:/opt/starfish/grafana/loki$ ./logcli-linux-amd64 query --addr="http://localhost:7860" '{job="3"}' --limit 2
2021-01-21 16:08:38.822736 I | proto: duplicate proto type registered: ingester.Series
http://localhost:7860/loki/api/v1/query_range?direction=BACKWARD&end=1611241718823265423&limit=2&query=%7Bjob%3D%223%22%7D&start=1611238118823265423
Common labels: {host="agent", job="3"}
2021-01-21T16:07:23+01:00 {log_stream="cmd_worker"} msg="cmd_worker_7"
2021-01-21T16:07:23+01:00 {log_stream="dispatcher"} msg="dispatcher_6"
```
Step 3:
```
pawel@asus:/opt/starfish/grafana/loki$ ./logcli-linux-amd64 query --addr="http://localhost:7860" '{job="3"} | logfmt'
2021-01-21 16:09:11.947264 I | proto: duplicate proto type registered: ingester.Series
http://localhost:7860/loki/api/v1/query_range?direction=BACKWARD&end=1611241751947738464&limit=30&query=%7Bjob%3D%223%22%7D+%7C+logfmt&start=1611238151947738464
Common labels: {host="agent", job="3"}
2021-01-21T16:07:23+01:00 {log_stream="cmd_worker", msg="cmd_worker_7"} msg="cmd_worker_7"
2021-01-21T16:07:23+01:00 {log_stream="dispatcher", msg="dispatcher_6"} msg="dispatcher_6"
2021-01-21T16:07:23+01:00 {log_stream="cmd_worker", msg="cmd_worker_5"} msg="cmd_worker_5"
2021-01-21T16:07:23+01:00 {log_stream="dispatcher", msg="dispatcher_4"} msg="dispatcher_4"
2021-01-21T16:07:23+01:00 {log_stream="cmd_worker", msg="cmd_worker_3"} msg="cmd_worker_3"
2021-01-21T16:07:23+01:00 {log_stream="dispatcher", msg="dispatcher_2"} msg="dispatcher_2"
2021-01-21T16:07:23+01:00 {log_stream="cmd_worker", msg="cmd_worker_1"} msg="cmd_worker_1"
2021-01-21T16:07:23+01:00 {log_stream="dispatcher", msg="dispatcher_0"} msg="dispatcher_0"
http://localhost:7860/loki/api/v1/query_range?direction=BACKWARD&end=1611241643000000001&limit=23&query=%7Bjob%3D%223%22%7D+%7C+logfmt&start=1611238151947738464
```
Step 4:
```
pawel@asus:/opt/starfish/grafana/loki$ ./logcli-linux-amd64 query --addr="http://localhost:7860" '{job="3"} | logfmt' --limit 2
2021-01-21 16:09:15.309635 I | proto: duplicate proto type registered: ingester.Series
http://localhost:7860/loki/api/v1/query_range?direction=BACKWARD&end=1611241755310151428&limit=2&query=%7Bjob%3D%223%22%7D+%7C+logfmt&start=1611238155310151428
Common labels: {host="agent", job="3", log_stream="cmd_worker"}
2021-01-21T16:07:23+01:00 {msg="cmd_worker_3"} msg="cmd_worker_3"
2021-01-21T16:07:23+01:00 {msg="cmd_worker_1"} msg="cmd_worker_1"
```
Step 6:
```
pawel@asus:/opt/starfish/grafana/loki$ ./logcli-linux-amd64 query --addr="http://localhost:7860" '{job="3"} | logfmt' --limit 2
2021-01-21 16:12:36.847723 I | proto: duplicate proto type registered: ingester.Series
http://localhost:7860/loki/api/v1/query_range?direction=BACKWARD&end=1611241956848398857&limit=2&query=%7Bjob%3D%223%22%7D+%7C+logfmt&start=1611238356848398857
Common labels: {host="agent", job="3"}
2021-01-21T16:07:23+01:00 {log_stream="cmd_worker", msg="cmd_worker_7"} msg="cmd_worker_7"
2021-01-21T16:07:23+01:00 {log_stream="dispatcher", msg="dispatcher_6"} msg="dispatcher_6"
```

**Comment by cyriltovena** [comment]
Hey @pawel-jaworski , Are all your line timestamps the same ?

**Comment by pawel-jaworski** [comment]
Thanks for your reply.
1. The timestamps are not the same. They differ by 1 ns, see step 1. In `logcli` the accuracy is 1 s, so it looks like they are all the same, but they are not.
2. Yes, I run it as a single binary.
3. No, replications are off.

**Comment by pawel-jaworski** [comment]
@cyriltovena any update on this?

**Comment by cyriltovena** [comment]
Can you reliable reproduce this ? does it happen only for fresh data ? Does it goes away for older data ?

**Comment by pawel-jaworski** [comment]
I'm able to reliably reproduce it. I checked it multiple times within a week and it happened every time. The time period I mentioned (~ 5 mins 15 secs) was the same all the time. I checked it on fresh data, didn't check it on older data. But because the issue disappears after ~5 mins, I would assume that for older data it's ok. Will check and get back to you. Do you have any specific time range in mind when saying "older" data?

**Comment by cyriltovena** [comment]
No that answer the question.

**Comment by cyriltovena** [comment]
Not going to lie this and #3345 has haunted my night for 7 days straight. 

But thanks to your issue I was able to reproduce with a small subset and found the issue, took me too so long, this was a real emotional rollercoaster, I'm exhausted.

Again thank you 🚀 

Fix is coming I'm testing it in our env.

**Comment by cyriltovena** [comment]
@pawel-jaworski if you want to try it I pushed `grafana/loki:fix-ingester-headchunk-reversal-760c28d`

**Comment by cyriltovena** [comment]
Not fully done there's more to it, on it.

**Comment by pawel-jaworski** [comment]
Great news, thanks!
