### ISSUE TITLE
loki retention policy

### ISSUE THREAD

**Issue by mmalik1500** [grafana/loki#3209]
Hi,

I want to save my data to be stored for 6 months and I configured the loki's configuration file as follows:

auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_transfer_retries: 0

schema_config:
  configs:
    - from: 2018-04-15
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 168h

storage_config:
  boltdb:
    directory: /tmp/loki/index

🇶🇦   filesystem:
    directory: /tmp/loki/chunks

limits_config:
 enforce_metric_name: false
 reject_old_samples: true
 reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 4368h

table_manager:
  retention_deletes_enabled: true
  retention_period: 4368h

Could anyone please check if my setting are correct ?

Thanks in advance.

**Comment by caleb15** [comment]
You can use backticks to better format your settings file, like so:

```
retention_period: 4368h
```

You would write it out like so:
\```
example
\```

Just a FYI :)
