### ISSUE TITLE
need to rebuild loki image 

### ISSUE THREAD

**Issue by soodrenu** [grafana/loki#3213]
Hello Team,

I need to rebuild loki image using redhat ,  registry.access.redhat.com/ubi8/ubi:8.1 ,
request your guidance for the same , how should i go about it?

Regards,
Renu

**Comment by cyriltovena** [comment]
clone the repo.

```
make docker-image
```

it should works using only docker.

**Comment by ukolovda** [comment]
> make docker-image

```
make loki-image
```

worked for me.

But before it I run 

```
make loki
```

without it I got the error:

```
bash: line 5: protoc: command not found
make: *** [Makefile:332: pkg/logproto/logproto.pb.go] Error 127

```
