### ISSUE TITLE
HTTP API Endpoint to get Loki version

### ISSUE THREAD

**Issue by loganmc10** [grafana/loki#3221]
**Is your feature request related to a problem? Please describe.**
Prometheus has this endpoint: ```GET /api/v1/status/buildinfo``` which will return the version of Prometheus. I don't see any way using Loki's HTTP API to figure out what version of Loki I'm talking to.

**Describe the solution you'd like**
```GET /api/v1/status/buildinfo``` or alternative for Loki.

**Additional context**
I'm using Grafana Cloud, so I don't have any access or control over the Loki server. I don't know what version of Loki I'm using, I'd like to know so that I know when I can use new features that become available.

**Comment by owen-d** [comment]
I like this request. One thing to note is that Grafana Cloud uses it's own internal release schedule which doesn't exactly correspond to Loki releases. However, Loki releases tend to be based on these internal builds which are then tagged & released as `x.y.z`. These tend to be the `k<xx>` branches here: https://github.com/grafana/loki/branches/all?query=k

I think we should expose this information, but having a commit hash and a `k<xx>` returned to you (in the case of Grafana Cloud) may not be the most helpful :(

**Comment by loganmc10** [comment]
Stalebot this is a really good idea, I promise

**Comment by loganmc10** [comment]
Plz stalebot have mercy on me
