### ISSUE TITLE
The json parser ignores objects

### ISSUE THREAD

**Issue by renatomjr** [grafana/loki#3227]
**Describe the bug**
The `json` parser ignores objects.

**To Reproduce**
Log line: `{"level": "info", "body": {"id": "1", "data": {"a": "b"}}}`
Query: `{level="info"} | json | line_format "{{.body_data}}"`
Result: empty line

**Expected behavior**
Result: ` {"a": "b"}`

**Environment:**
 - Infrastructure: kubernetes
 - Deployment tool: helm

There is an alternative way to get the `body_data` value?
The use case is a Grafana table panel where `body_id` is a column and `body_data` is another.

**Comment by vyzigold** [comment]
Hello, take a look here: [parser expressions](https://grafana.com/docs/loki/latest/logql/#parser-expression). There is a sentence saying: "Nested properties are flattened into label keys using the `_` separator." 
So as I understand it, the query should look something like this: `{level="info"} | json | line_format "{{.body_data_a}}"` 
and the result should be: `b`.

**Comment by renatomjr** [comment]
Thank you, but there is a way to get the entire `body_data` object and output a string representation of it?

**Comment by cyriltovena** [comment]
Cc @dannykopping you cover this no?

**Comment by dannykopping** [comment]
@cyriltovena correct: https://github.com/grafana/loki/pull/3280/files#diff-c3a5c0501669f6c25bb23430a1f1bb4fcce88bfccf3cfa6741122af4ad3e803aR214

**Comment by renatomjr** [comment]
In Loki 2.2.0, the query `{level="info"} | json raw_body="body" | line_format "{{.raw_body}}"` covers my use case.
Thank you.
