### ISSUE TITLE
[docs] Add deployment system requirements

### ISSUE THREAD

**Issue by caleb15** [grafana/loki#3232]
**Is your feature request related to a problem? Please describe.**
I'm evaluating what logging system to use with kubernetes but I'm not sure how much Loki will cost or how much hardware resources it will need for X amount of logs per day.

**Describe the solution you'd like**
A page describing an example of CPU and memory requests and limits needed for a certain X amount of daily logs  in production. From there readers could extrapolate to form a rough guess of what they would need for their setup.

**Describe alternatives you've considered**
I searched online for blog posts but didn't find any.
I could test Loki myself and make a guess as to what it will need in production.

**Additional context**
As an example vault has a very useful reference architecture page along with server sizing for a production environment.
https://learn.hashicorp.com/tutorials/vault/reference-architecture#deployment-system-requirements

**Comment by martysohio** [comment]
Agreed, I am working with a loki setup with about 120GB of chunk data with a 1.5 gb index and the loki ingester container RAM goes up over several days as data comes in and its not clear why. Nor does anything in the config documentation stand out as to why.

I did get a profile but I'm not familiar enough with golang to dig much

`File: loki
Type: inuse_space
Time: Feb 23, 2021 at 12:53pm (EST)
Showing nodes accounting for 12253.46MB, 99.22% of 12349.93MB total
Dropped 93 nodes (cum <= 61.75MB)
      flat  flat%   sum%        cum   cum%
 8455.41MB 68.47% 68.47%  8455.41MB 68.47%  bytes.makeSlice
 3781.01MB 30.62% 99.08%  3781.01MB 30.62%  github.com/grafana/loki/pkg/logproto.(*Entry).Unmarshal
   14.01MB  0.11% 99.19%  4750.86MB 38.47%  github.com/grafana/loki/pkg/chunkenc.(*MemChunk).cut
    1.54MB 0.012% 99.21%  4802.97MB 38.89%  github.com/grafana/loki/pkg/ingester.(*stream).Push
    1.48MB 0.012% 99.22%  3752.56MB 30.39%  github.com/grafana/loki/pkg/ingester.(*Ingester).flushChunks
         0     0% 99.22%  8453.78MB 68.45%  bytes.(*Buffer).Write
         0     0% 99.22%  8455.41MB 68.47%  bytes.(*Buffer).grow
         0     0% 99.22%  3750.08MB 30.37%  github.com/cortexproject/cortex/pkg/chunk.(*Chunk).Encode
         0     0% 99.22%  4799.93MB 38.87%  github.com/grafana/loki/pkg/chunkenc.(*MemChunk).Append
         0     0% 99.22%  3748.50MB 30.35%  github.com/grafana/loki/pkg/chunkenc.(*MemChunk).WriteTo
         0     0% 99.22%  4736.85MB 38.36%  github.com/grafana/loki/pkg/chunkenc.(*headBlock).serialise
         0     0% 99.22%  3748.50MB 30.35%  github.com/grafana/loki/pkg/chunkenc.Facade.Marshal
         0     0% 99.22%  4804.48MB 38.90%  github.com/grafana/loki/pkg/ingester.(*Ingester).Push
         0     0% 99.22%  3752.56MB 30.39%  github.com/grafana/loki/pkg/ingester.(*Ingester).flushLoop
         0     0% 99.22%  3752.56MB 30.39%  github.com/grafana/loki/pkg/ingester.(*Ingester).flushUserSeries
         0     0% 99.22%  4804.48MB 38.90%  github.com/grafana/loki/pkg/ingester.(*instance).Push
         0     0% 99.22%  3781.01MB 30.62%  github.com/grafana/loki/pkg/logproto.(*PushRequest).Unmarshal
         0     0% 99.22%  3781.01MB 30.62%  github.com/grafana/loki/pkg/logproto.(*Stream).Unmarshal
         0     0% 99.22%  8585.49MB 69.52%  github.com/grafana/loki/pkg/logproto._Pusher_Push_Handler
         0     0% 99.22%  4804.48MB 38.90%  github.com/grafana/loki/pkg/logproto._Pusher_Push_Handler.func1
         0     0% 99.22%  4804.48MB 38.90%  github.com/grafana/loki/pkg/loki.glob..func2
         0     0% 99.22%  4804.48MB 38.90%  github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1
         0     0% 99.22%  4804.48MB 38.90%  github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
         0     0% 99.22%  4804.48MB 38.90%  github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1
         0     0% 99.22%  4715.37MB 38.18%  github.com/klauspost/compress/flate.(*Writer).Write (inline)
         0     0% 99.22%  4718.64MB 38.21%  github.com/klauspost/compress/flate.(*compressor).storeFast
         0     0% 99.22%  4715.37MB 38.18%  github.com/klauspost/compress/flate.(*compressor).write
         0     0% 99.22%  4717.49MB 38.20%  github.com/klauspost/compress/flate.(*huffmanBitWriter).write (inline)
         0     0% 99.22%  1598.83MB 12.95%  github.com/klauspost/compress/flate.(*huffmanBitWriter).writeBits (inline)
         0     0% 99.22%  4715.95MB 38.19%  github.com/klauspost/compress/flate.(*huffmanBitWriter).writeBlockDynamic
         0     0% 99.22%  1682.01MB 13.62%  github.com/klauspost/compress/flate.(*huffmanBitWriter).writeCode (inline)
         0     0% 99.22%    92.52MB  0.75%  github.com/klauspost/compress/flate.(*huffmanBitWriter).writeDynamicHeader
         0     0% 99.22%  4715.95MB 38.19%  github.com/klauspost/compress/flate.(*huffmanBitWriter).writeOutBits
         0     0% 99.22%  4622.39MB 37.43%  github.com/klauspost/compress/flate.(*huffmanBitWriter).writeTokens
         0     0% 99.22%  4730.40MB 38.30%  github.com/klauspost/compress/gzip.(*Writer).Write
         0     0% 99.22%  4804.48MB 38.90%  github.com/opentracing-contrib/go-grpc.OpenTracingServerInterceptor.func1
         0     0% 99.22%  4804.48MB 38.90%  github.com/weaveworks/common/middleware.GRPCServerLog.UnaryServerInterceptor
         0     0% 99.22%  4804.48MB 38.90%  github.com/weaveworks/common/middleware.UnaryServerInstrumentInterceptor.func1
         0     0% 99.22%  5305.69MB 42.96%  google.golang.org/grpc.(*Server).handleStream
         0     0% 99.22%  8585.49MB 69.52%  google.golang.org/grpc.(*Server).processUnaryRPC
         0     0% 99.22%  3781.01MB 30.62%  google.golang.org/grpc.(*Server).processUnaryRPC.func2
         0     0% 99.22%  3869.53MB 31.33%  google.golang.org/grpc.(*Server).serveStreams.func1.1
         0     0% 99.22%  3781.01MB 30.62%  google.golang.org/grpc/encoding/proto.codec.Unmarshal`
