### ISSUE TITLE
Advice needed: Unwrapping parsed field.

### ISSUE THREAD

**Issue by aaron-parsons** [grafana/loki#3253]
Hi, @owen-d, @cyriltovena,

I'm trying to do something that is new to me with a loki query to make up a dashboard. I am interested in monitoring a variable in a log that takes different values over time.

I use logfmt to extract the variable from the log to a parsed field "Duration", which appears as, for instance "1s". I'm now trying to pipe this to unwrap so that I can plot it in a graph using the following query:

{stack="stack1", selection"selection_name"} |= "Completed" | logfmt | unwrap duration_seconds(Duration)

which I got the inspiration for from here: https://grafana.com/docs/loki/latest/logql/#unwrapped-range-aggregations

This doesn't work, and I get the error:

parse error at line 1, col 93: syntax error: unexpected unwrap
Object
status:400
statusText:""
data:Object
error:""
response:"parse error at line 1, col 93: syntax error: unexpected unwrap"
message:"parse error at line 1, col 93: syntax error: unexpected unwrap"
config:Object
url:"api/datasources/proxy/9/loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=%7Bstack%3D%22stack1%22%2C%20selection%3D%22selection_name%22%7D%20%7C%3D%20%22Completed%22%20%7C%20logfmt%20%7C%20unwrap%20duration_seconds(Duration)&start=1611848857000000000&end=1611852458000000000&step=2"
retry:0
headers:Object
hideFromInspector:false
message:"parse error at line 1, col 93: syntax error: unexpected unwrap"

I've tried for a fair while to get this to work, with different permutations, switching form logfmt to using regexp etc... but to no avail.

Any chance you could drop me a hint as to what I am doing wrong?

I'm sure its something simple, I just can't see it.

Thanks,

Aaron

**Comment by aaron-parsons** [comment]
I guess I should add that I am using this through the grafana cloud interface.

**Comment by xkilian** [comment]
I am trying to do the exact same things and cannot figure out how to pass the raw value. You can convert your metric to a vector using a *_over_time function, but that function will modify or filter the raw value:
avg_over_time ( {stack="stack1", selection"selection_name"} |= "Completed" | logfmt | unwrap duration_seconds(Duration) [1m] )

**Comment by aaron-parsons** [comment]
Thanks @xkilian for the reply! I am very pleased to hear it is not just me having trouble. With your advice I can now get something to plot, which is a start :-)

I am wondering whether the *over_time function is needed to fill in gaps in the vector? Otherwise we have a non continuous dataset which I guess could be a problem for plotting (I don't know if logql/ grafana can do NaNs for filling otherwise?). It's certainly not ideal to do it this way for stats for me since it means the minimum in the series is always 0 and not the minimum value of my metric,

Perhaps @owen-d, @cyriltovena, could advise?

**Comment by xkilian** [comment]
Here is the answer you are looking for, this should be clearly stated in examples and documentation:
In Grafana 7, you have the transformations tab, select "Labels to Fields". Select visualisation as a Table, you will see each label as a colomn. Once you have this data, make sur the colomn names match what the plugin is expecting.
Switch your visualisation to the panel you want and it should work.

So your query should be:
{stack="stack1", selection"selection_name"} |= "Completed" | logfmt

Transformation = Labels to Fields

Pfiou, sounds easy, but I just recently made the switch to Grafana 7 from 6.x so I was not familiar enough with the new transformations.

**Comment by owen-d** [comment]
We've talked about a `raw` function before to do what you've described. I think it'd be helpful as well, but we haven't done it yet because we haven't settled on a strategy for handling timestamp precision. Prometheus, which we pride ourselves on being compatible with, uses millisecond resolution metrics, but we use nanosecond precision logs. I figure rounding to the nearest `ms` might be reasonable enough.

Am I forgetting something @cyriltovena?

**Comment by xkilian** [comment]
For all the use-cases I am familiar with rounding to ms, would be perfectly acceptable. This is also a case where we are converting an event to a metric, which to be honest, if you really need super precise metrics, they should not be going to a logging system, but directly to a time-series metric store that supports the appropriate precision.
You get my vote to implement some time of way to convert certain labels to raw metrics! Thanks for chiming in.

**Comment by slim-bean** [comment]
There has been quite some internal debate about this. 

Personally my vote is to just use unwrap and return a time series with the logs turned into sample values with the log nanosecond timestamp and the value becoming the value of what was unwrapped.

This is technically possibly not compatible with the prometheus API, their timestamp is [unix_seconds].[millis] but I don't think adding more precision on the end is really a breaking change, at least not to me it isn't 🙂

**Comment by xkilian** [comment]
It would be consistent with how functions make use of metrics. Intuitively this is what I was expecting, call unwrap and specifiy what is a metric and like in Prometheus, if you want to call an *_over_time function you can. 
Loki is supposed to be Prometheus for Logs.

**Comment by xkilian** [comment]
On a side note, using the "Labels to Fields" trick to get the raw values (for latitude, longitude from a Loki log lines), is there a way in Grafana to order the data by time. I noticed that the data is not strictly ordered by time. I tried the Grafana Transform Organize fields, but to no avail. Strange. Which has the GPS data moving around in a wonky way.

**Comment by owen-d** [comment]
Edit: I think we skipped this because we didn't know how to handle logs with the same timestamp but different `unwrapped` labels. We'll just have to agree on how to treat this.

**Comment by owen-d** [comment]
Ok, I started some hacking around this to see what it'd look like and I ran into a few things:
1) A lot of our internal code expects a sort of _alignment_ when iterating through samples (the `step` parameter in metric queries). I haven't benchmarked yet, but I expect a naive implementation wouldn't be very efficient. This isn't any sort of blocker though.
2) Raw queries like these have potentially a huge amount of data to push to the browser. This is unlike log queries (which have limits) and metric queries (which downsample via aggregation). We might need to be careful about this one.
3) Already mentioned, but reiterating here. What about logs that share the same timestamp?
4) I think we have to use `ms` instead of nanoseconds because we return the same datastructures as Prometheus, so I'm guessing our external API already uses the `int64` as `ms`.

**Comment by aaron-parsons** [comment]
Hi @owen-d ,

I was just wondering if you managed to get any further with this?

Looks like you did a lot of digging.

Aaron

**Comment by cyriltovena** [comment]
I built this PR for this specific use-case, https://github.com/grafana/loki/pull/3050 using:

first_over_time({stack="stack1", selection"=selection_name"} |= "Completed" | logfmt | unwrap duration_seconds(Duration)[1m])
last_over_time({stack="stack1", selection"=selection_name"} |= "Completed" | logfmt | unwrap duration_seconds(Duration)[1m])

 Depending on the `[range]` you'll use you may lose some point but for most use case `[1m]` you'll get the first or last point during the last minute. (minute could be 30s or 1s).

Obviously if you have many points in a single nanoseconds you'll get a single one.

If you think this would solve your issue, then I guess we can prioritize the PR review.

**Comment by xkilian** [comment]
I like the idea of providing a function.  Makes it consistent. It does provide the last and first, which is great! 
But, it does not provide a list of raw values for a given time window or dashboard time range.

**Comment by HireChrisJohnston** [comment]
I had struggled with the learning of LogQL and hope this helps someone today in this example.  It took me hours to figure out the correct syntax and structure of the language in the common manipulations that must be performed when using a regex


- uses regular expression for groups (line 2)
- builds a logfmt string (line 3)
- unwraps the value and filters error (line 4-5)
- passes string to metric formulas


The query will return the most recent value of a humidity sensor. AKA raw value of regex capture group using LogQL

```
last_over_time({filename="/var/log/airthing.log",job="varlogs"}
 | regexp `Timestamp:.*, Humidity: (?P<humidity>\d{2}.\d).*Temperature: (?P<temp>\d{2}.\d).*STA: (?P<sta>\d*).*LTA: (?P<lta>\d*)`
  | line_format "humid={{.humidity}}" 
  | logfmt
  | unwrap humid
  | __error__ = ""[$__interval]) 
by (time)
```

**Comment by MuhammadNaeemAkhtar** [comment]
Hi,
Is there anyone who able to resolve the issue I am having the same issue of searching the raw data. I want them to find the command run by the  username on the hostname.
![image](https://user-images.githubusercontent.com/41923503/159896386-9e931735-9aac-4322-91d9-c82959d028a1.png)
