### ISSUE TITLE
JSON Push API endpoint broken

### ISSUE THREAD

**Issue by lukesteensen** [grafana/loki#3257]
**Describe the bug**
The [`push`](https://github.com/grafana/loki/blob/master/docs/sources/api/_index.md#post-lokiapiv1push) API endpoint no longer accepts JSON data, returning a 400 and `snappy: corrupt input`.

**To Reproduce**
1. Started Loki (`docker run --rm -it --network=host grafana/loki:master-51952da`)
2. Send the example curl request from the API docs.

**Expected behavior**
The request should succeed.

**Environment:**
 - Infrastructure: local Ubuntu machine
 - Deployment tool: docker

**Screenshots, Promtail config, or terminal output**
```
$ curl -v -H "Content-Type: application/json" -XPOST -s "http://localhost:3100/loki/api/v1/push" --data-raw '{"streams": [{ "stream": { "foo": "bar2" }, "values": [ [ "1570818238000000000", "fizzbuzz" ] ] }]}'
*   Trying 127.0.0.1:3100...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 3100 (#0)
> POST /loki/api/v1/push HTTP/1.1
> Host: localhost:3100
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 99
> 
* upload completely sent off: 99 out of 99 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Thu, 28 Jan 2021 21:22:58 GMT
< Content-Length: 22
< 
snappy: corrupt input
```

**Comment by dannykopping** [comment]
Hey @lukesteensen - thanks for reporting.
We noticed it to and have pushed a fix already (https://github.com/grafana/loki/pull/3261)

**Comment by lukesteensen** [comment]
Great, thank you!
