### ISSUE TITLE
Loki  Sometimes gets into a bad state and continuously consumes 3 CPUs out of 4  

### ISSUE THREAD

**Issue by Alexander-Bartosh** [grafana/loki#3264]
**Describe the bug**
Loki Randomly gets into a bad state and consumes 3 CPUs out of 4 
It does not get out of the state.( waited for few hours - constant 3 out of 4 CPU load )
Do not see any stage events in the logs 
Only killing the pod helps for approximately for a day. 
The cluster log amount is very small  (See dashdoard screenshot)
Can not relate this event to any query executed by grafana

**To Reproduce**
1. Deploy Loki-Stack (helm)
2. Deploy Grafana
3. Add Loki Prometheus datasource http://loki.monitoring.svc.cluster.local:3100/loki
4. Create a simple aller using the data source. (Amount of logs the alert is running on in very small. LogQL behind the aller runs  on regular basis. I do not know if the alert is related to observed bahaviour ) 

**Expected behavior**
Do not expect this to happend

**Environment:**
 - Infrastructure: AKS 1.18 
 - Deployment tool: helm, default parameters. Loki 2.1

**Screenshots, Promtail config, or terminal output**
Last 3 hours. 
Loki is in the bad state for 1 hour 
![image](https://user-images.githubusercontent.com/634983/106271641-1e39f880-6230-11eb-9c0d-90b7b69aba65.png)
![image](https://user-images.githubusercontent.com/634983/106271759-4c1f3d00-6230-11eb-91d8-e4f5af406209.png)

![image](https://user-images.githubusercontent.com/634983/106271918-7f61cc00-6230-11eb-80b5-ff1357b046c7.png)

**Comment by Alexander-Bartosh** [comment]
Will gladly provide any other info  that is needed, if will know how to collect that

**Comment by Alexander-Bartosh** [comment]
It looks like getting to the state relates to opening this dashboard: 
![image](https://user-images.githubusercontent.com/634983/106619353-cc1b0f00-6570-11eb-8120-2b26d6113053.png)

**Comment by Alexander-Bartosh** [comment]
Will try to reproduce with debug logs enabled

**Comment by marvin-sinister** [comment]
We can probably combine with  #3275, since I'm getting the same issue on same dashboard. The difference is that recent requests bug out for me when it happens.

**Comment by Alexander-Bartosh** [comment]
@marvin-sinister Agree!
I had a suspicion on the garbage requests as well

**Comment by Alexander-Bartosh** [comment]
Closing this one #3275 describes the problem and reproduction

**Comment by cyriltovena** [comment]
see https://github.com/grafana/loki/issues/3275#issuecomment-780373814
