### ISSUE TITLE
What a way of alerting when promtail is "behind"

### ISSUE THREAD

**Issue by tomwilkie** [grafana/loki#327]
I want to build an alert to say if promtail is "behind".  Idea would be to export size of each file promtail is following, and the position it has read up to, and alert if there is a "big" difference for a while.  WDYT? /cc @slim-bean

**Comment by khaines** [comment]
+1 for this

**Comment by slim-bean** [comment]
@tomwilkie I'm debating if this would be most useful as an overall alert, that is, look at all the files being tailed and report on the largest difference, or would we want a metric for each file?

I think it might be easier to configure one alert for a single metric reporting overall on promtail being behind, and maybe augment that with some logging in promtail which periodically shows each file and how caught up we are?  Something that you could find if you drill in on the logs from loki.

**Comment by tomwilkie** [comment]
@slim-bean philosophically I'd lean towards exposing the raw data and then synthesising an alert out of it in Prometheus.  That data will probably be useful for other things.

**Comment by slim-bean** [comment]
@DanCech proposed the idea of exporting the data as a histogram, create buckets for how far behind, and then a count of the number of files in those buckets.  This would be a nice way of combining the output from all the logs being tailed and keep the number of series from growing directly with the number of logs tailed.

**Comment by tomwilkie** [comment]
> keep the number of series from growing directly with the number of logs tailed.

Is this really a concern?  How many files do we think a single cluster of promtails will follow?  In a k8s world, there is always at least one series per target (`up`), so I think there is precedent for having automatic series order #targets.

**Comment by slim-bean** [comment]
A metric `promtail_file_bytes_total` was added which can be used to alert when compared to `promtail_read_bytes_total`.  For example we are running this alert now: `abs(promtail_file_bytes_total - promtail_read_bytes_total) > 100000`
