### ISSUE TITLE
Shortly after ingestion, queries with timestamps outside specified range are included in a query

### ISSUE THREAD

**Issue by thrixton** [grafana/loki#3286]
**Describe the bug**
Intermittently, for a period after ingestion, log records with a timestamp outside the range specified are included.  
Using LogCLI, this results in an error after returning a stream of records. (`Query failed: Error response from server: end timestamp must not be before or equal to start time
 (<nil>)` ). The grafana UI does not error, it just silently returns the records.

It appears to be triggered by filtering out a large number of the records which would otherwise be returned.
I've observed this 10 minutes after ingestion.

**To Reproduce**
* Record start (s1)
* Ingest a large volume of data (10k+ records) (Batch 1)
* Record finish (f1)
* Wait 5 minutes
* Record start (s2)
* Ingest a large volume of data (10k+ records) (Batch 2)
* Record finish (f2)
* Query based between s2 and f2, doing a narrowing filter to ensure less than 1K records are returned
* Observe that records with a timestamp between s1 and f1 are returned

**Expected behavior**
Records between s1 and f1 should not be returned

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm
 - Loki-Stack helm chart version: 2.1.0

**Comment by admayber** [comment]
I've observed a similar issue.

**Comment by admayber** [comment]
@thrixton - I recently switched over to the newer helm repo at https://grafana.github.io/loki/charts and installed loki-stack 2.3.1 and this issue seems to be fixed

**Comment by thrixton** [comment]
Thanks @admayber , I'm currently using loki-stack 2.3.0, i'll give 2.3.1 a go
