### ISSUE TITLE
UI of prometheus can't be accessed when installed with loki-stack

### ISSUE THREAD

**Issue by MrAmbiG** [grafana/loki#3293]
**Describe the bug**
I installed loki-stack (prometheus and loki). when I expose prometheus server service via Nodeport or loadbalancer, the UI isn't accessible.

**To Reproduce**
Install loki-stack-2.3.0 with prometheus enabled. expose  loki-prometheus-server as nodeport or loadbalancer.

**Expected behavior**
We should be able to access the prometheus UI.

**Environment:**
 - Infrastructure: [k8s 1.18, baremetal, 6 nodes, ]
 - Deployment tool: [e.g., helm]

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by skk2142** [comment]
Any updates on this?  I'm facing the same problem.

**Comment by MrAmbiG** [comment]
update:
I installed the prometheus operator from bitnami and disabled prometheus from loki-stack. Now I am good. so now i have
grafana, prometheus from bitnami
loki, promtail from loki-stack
