### ISSUE TITLE
"server returned HTTP status 400 Bad Request (400): proto: Stream: wiretype end group for non-group"

### ISSUE THREAD

**Issue by reasland** [grafana/loki#3294]
**Describe the bug**

Since updating to promtail container hash a1bf327e14d7
(Using latest tag)
Promtail is no longer able to forward logs to loki distributor

**To Reproduce**
1. Started Loki (0ea5b5cfea19)
2. Started Promtail (a1bf327e14d7) to tail '...'
3. Attempt to forward logs to Loki

**Expected behavior**

Forward logs to loki distributor to be ingested

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Servers running promtail in docker, Loki running on server via docker
 - Deployment tool: [e.g., helm, jsonnet]
 - Docker/Chef

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
level=error ts=2021-02-04T14:58:38.601947081Z caller=client.go:333 component=client host=azl-prd-prometheus-01.trek.web:3100 msg="final error sending batch" status=400 error="server returned HTTP status 400 Bad Request (400): proto: Stream: wiretype end group for non-group"

Downgrading to tag 'master-3bd725e' works

**Comment by rward27** [comment]
I am facing this same issue

**Comment by KristopherBorja** [comment]
I am facing the same issue
