### ISSUE TITLE
Azure Blob Storage Shared Access Signature (SAS) does not work

### ISSUE THREAD

**Issue by marcino239** [grafana/loki#3309]
**Describe the bug**
When using Azure Blob SAS token instead of Account Key, Loki throws this error:
```
illegal base64 data at input byte 0
error initialising module: table-manager
github.com/cortexproject/cortex/pkg/util/modules.(*Manager).initModule
/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:105
```

**To Reproduce**
1. Started Loki grafana/loki:2.1.0
2. Started Promtail (SHA or version) grafana/promtail:2.1.0

**Expected behavior**
Loki should accept SAS token

**Environment:**
Kubernetes 1.16.13
Helm 3.5.1

Loki works with Azure Blob Account Keys, but they are not recommended due to very wide permissions

**Comment by nholik** [comment]
> Is there any way to help move this forward ?

This https://github.com/thanos-io/objstore/issues/52 would need to move forward first, then I could submit a PR for loki to utilize it.  It is a niche use case, but adding to the discussion on the issue and PR could help move it forward.
