### ISSUE TITLE
Question: how to count line number?

### ISSUE THREAD

**Issue by sesky4** [grafana/loki#3310]
I know it sounds a stupid question, but I can't figure it out...
What I want is count the **Number of occurrences** in a given time. Just like
```
{job="my_app"} |="something"
```

**count_over_time** and **rate** shows the average, not the total number.
And **count** seems only count the stream, not the log lines in a stream.

**Comment by chancez** [comment]
`count_over_time` isn't an average (avg_over_time is though). It's the count for the time being queried back to the beginning of the time window in your range vector.

You can do an instant query with `count_over_time` with a specific window size to get what your asking for.

For example, the query below if sent to the `query` endpoint (not `query_range`) for the time 14:00, then it would count the logs between 13:00 and 14:00.

```
count_over_time({job="my_app"} |="something" [1h])
```

Note that until recently in Grafana 7.4, you couldn't do instant queries in the explore UI with the Loki datasource.
