### ISSUE TITLE
Loki docker log driver logs are never cleaned up, eventually filling up the disk

### ISSUE THREAD

**Issue by chancez** [grafana/loki#3313]
**Describe the bug**
Basically, the loki log driver for docker has no cleanup mechanisms for it's local copy of the docker log files. This results in thousands of log files that are never deleted, eventually filling the host's disk:
(note that `/var/lib/docker/plugins/2bbe5b99ba226781755f91b0141c31bb374b4eed23067abee87e14647ac692f6/rootfs` is the loki log drivers' container rootfs).
```
[root@fake-rackhost-1 ~]# du -cksh /var/lib/docker/plugins/2bbe5b99ba226781755f91b0141c31bb374b4eed23067abee87e14647ac692f6/rootfs/var/log/docker/
33G	/var/lib/docker/plugins/2bbe5b99ba226781755f91b0141c31bb374b4eed23067abee87e14647ac692f6/rootfs/var/log/docker/
33G	total
[root@fake-rackhost-1 ~]# find /var/lib/docker/plugins/2bbe5b99ba226781755f91b0141c31bb374b4eed23067abee87e14647ac692f6/rootfs/var/log/docker/ -type f | grep log | wc -l
18477
```

**To Reproduce**

This is our docker configuration:
```
[root@fake-rackhost-1 ~]# cat /etc/docker/daemon.json
{
    "log-driver": "loki",
    "log-opts": {
        "env": "NOMAD_TASK_NAME,NOMAD_GROUP_NAME,NOMAD_JOB_NAME",
        "keep-file": "true",
        "loki-external-labels": "container={{.Name}}",
        "loki-retries": "10",
        "loki-url": "https://loki.example.com/loki/api/v1/push",
        "max-file": "1",
        "max-size": "100m"
    }
}
```

You should be able to reproduce by spawning a large number of containers, removing them, and noticing the logs in the log-drivers rootfs are never cleaned up.

**Expected behavior**
I'd love if the log driver could just delete log files for containers that no longer exist. I'm not sure if the docker plugin model supports this, but it could just be a background thread that does periodic garbage collection.

For now, I will look at using logrotate or cron to delete them.

**Environment:**
 - Infrastructure: bare-metal
 - Deployment tool: nomad (though that shouldn't matter).

**Comment by chancez** [comment]
I wrote this script which basically looks at `/var/lib/docker/plugins`, finds the log files, filters out any opened by `docker-driver` (the process-name of the loki docker log driver), and deletes them.

```
#!/bin/bash
# find container log files in the docker plugin directory where the
# Loki log driver stores them, then use lsof to find the open log files,
# and remove those from the list of files to be deleted
find /var/lib/docker/plugins/ -type f -name '*json.log*' -print0 \
| grep --null-data -v -F -f \
  <(lsof -c docker-driver +D /var/lib/docker/plugins/ \
    | grep json.log \
    | grep -v deleted \
    | awk '{print $9}' \
    | sort  \
    | uniq) \
| xargs -0 -L1 rm --
```

We'll probably run this in cron, and may adapt it further to leave logs less than 1 week old, in case we stop containers but do not remove them.

**Comment by carlosflorencio** [comment]
Was being affected by this as well, will try the log opts from the docs to see if the log starts rotating:

```
--log-opt max-size=50m
--log-opt max-file=20
```

https://github.com/grafana/loki/blob/master/docs/sources/clients/docker-driver/configuration.md

**Comment by chancez** [comment]
The logs do correctly get rotated, but once the container is deleted, the log file/directory remains.

**Comment by carlosflorencio** [comment]
Did you take a look at the `keep-file` option? 

```
This indicates the driver to keep json log files once the container is stopped. By default files are removed, this means you won't be able to use docker logs once the container is stopped.
```

**Comment by chancez** [comment]
I did; but I basically assumed that would only impact stopped containers, not removed containers. I can test that though.

**Comment by chancez** [comment]
That option does seem to be working when docker is restarted. It would be nice if we could have the option to read logs of stopped containers, but remove the files if the container is deleted, or if docker is restarted.

**Comment by chancez** [comment]
Well, that's that. Thanks @carlosflorencio! `keep-file: false` seems like it will do what I want.
