### ISSUE TITLE
Docs: Fix the meaning of "latest" docs in Loki

### ISSUE THREAD

**Issue by kavirajk** [grafana/loki#3317]
**Is your feature request related to a problem? Please describe.**

Currently Loki "latest" docs points the latest docs on master branch on Loki git repository.
<img width="1151" alt="Screenshot 2021-02-10 at 12 05 24" src="https://user-images.githubusercontent.com/3735252/107502252-bb821e80-6b98-11eb-801c-49dcbc4b0c13.png">

This is confusing because, as a Loki user, I would expect to see latest release docs when the docs says "latest" version.

We can add "nightly" version to points to latest docs on master branch on Loki repository instead.

**Describe the solution you'd like**

1. "latest" -> "latest release version" (e.g: 2.1.0)
2. "nightly" -> "latest docs on master branch of Loki repository"

Meaning "latest" version should always be alias to "latest release version"

**Describe alternatives you've considered**

Bit weird, but have a doc that explains the actually meaning of "latest" version on current Loki

**Additional context**
NA

**Comment by osg-grafana** [comment]
Please add a codeowners entry for the Docs Squad.

**Comment by oddlittlebird** [comment]
Would this add "nightly" to the doc path? The other docs use "latest." Please be consistent.

**Comment by kavirajk** [comment]
@oddlittlebird 
We don't mind naming here(it can be "stable" and "latest" as well) :)

But real problem is we have to have clear separation between unstable master branch docs vs latest stable released version. And user coming to docs page should land on latest stable version by default.

**Comment by osg-grafana** [comment]
If this line exists, something is fundamentally unclear: 'Bit weird, but have a doc that explains the actually meaning of "latest" version on current Loki'.

How about .../dev/... for anything that is under active development, and all released docs have .../1.2.3/... in the URL that is stable.

**Comment by achatterjee-grafana** [comment]
Interesting observation @osg-grafana. I am thinking of a situation where a user would be interested to check the `dev` branch you mention. From a doc perspective, it will typically be the released version. 

Double thumbs up for considering actual released versions and not just `latest`. Most users are NOT on `latest`. Thanks!

**Comment by osg-grafana** [comment]
Hi @achatterjee-grafana, I can likely be more clear:

1. Unversioned: a URL containing `.../main/...` or `.../dev/...`, for example, could more clearly indicate to OSS contributors that what they are looking at is actively being developed, and will be released sometime in the future.
2. Versioned: a release that has been cut and reflected in the URL as something similar to `.../#.#.#/...`.

There is a need for both of these scenarios.
