### ISSUE TITLE
Make it possible to see the context for a given entry.

### ISSUE THREAD

**Issue by tomwilkie** [grafana/loki#332]
Say I found a match, I want to show the time around it (+/- 10mins) for the current selector.

**Comment by tomwilkie** [comment]
@davkal what do you think Grafana would need to implement this server-side?  Or do you think this could be implemented entirely in Grafana?  For instance, when selecting a line for additional context, Grafana could issue a new query without the regexp filter, with the exact labels for the selected line, and with a start & end timestamp +/- 10mins.

**Comment by davkal** [comment]
I thought about this a while back:

- `context` could be a parameter, similar to `step` in prometheus
- when `context` is received, loki returns log lines surrounding the matched lines
- search matched lines (M) need to be sandwiched by context lines (C) but they still need to sorted by time, e.g. `context=3` returns `CCCMCCC` for a given stream
- context could be directional: `context=+3` results in `MCCC`
- context lines need to be marked as such, so they can be skipped (by in-browser analysis or server-side pattern-based processing for alerting)

Unclear parts:

- how context should be displayed: like a normal line (grep), or collapse/expand context lines on the matched row. My feeling is that expand/collapse will be neat, but less useful than seeing everything. Users request context for a reason, so there it would be odd to hide it.
- should there be a time unit for the context parameter? or is number lines enough?

**Comment by davkal** [comment]
From a use case point of view, how common are the these scenario compared to one another?

A) see all context all the time (grep)
B) query for matches first, then request context per line

**Comment by tomwilkie** [comment]
Doing context for every line would also be be tricky it the backend, but possible for sure.  In this case though I only wanted to see the context for a given line I'd found by searching.

**Comment by davkal** [comment]
Is there a date range cutoff, e.g., 6h, below which queries return particularly fast? Quite like to keep that feature very responsive.

**Comment by tomwilkie** [comment]
Short answer is no, but queries on recent data will be more responsive.  

It depends more on the length of the query right now, but we're going to fix that.

**Comment by daixiang0** [comment]
Is any process about this? It would be a meaningful feature for us!

**Comment by tomwilkie** [comment]
@davkal this is done (in Grafana) and works well.  Can we close this?
