### ISSUE TITLE
Failed fallback ping: read tcp i/o timeout

### ISSUE THREAD

**Issue by dbluxo** [grafana/loki#3320]
**Describe the bug**:
We have deployed the loki-distributed [helm chart](https://github.com/grafana/helm-charts/tree/main/charts/loki-distributed). All in all it works, but we regularly get `Failed fallback ping: read tcp i/o timeout` messages and wonder what this could be and if we should worry about it.

**Environment:**
 - Infrastructure: AWS, Kubernetes
 - Deployment tool: helm

The nodes are allowed to communicate with each other via TCP and UPD over all ports. We also increased the `memberlist.packet_dial_timeout` and `memberlist.packet_write_timeout`, but this did not help.

**Terminal output**:
```
...
ts=2021-02-10T15:45:42.258821298Z caller=memberlist_logger.go:74 level=error msg="Failed fallback ping: read tcp 1.20.9.178:37580->1.30.0.99:7946: i/o timeout"
ts=2021-02-10T15:45:42.25888291Z caller=memberlist_logger.go:74 level=info msg="Suspect loki-distributed-distributor-5574f7f4d6-cmdhr-51caf0b6 has failed, no acks received"
ts=2021-02-10T15:45:43.116428163Z caller=memberlist_logger.go:74 level=error msg="Failed fallback ping: read tcp 1.10.8.221:38144->1.30.0.97:7946: i/o timeout"
ts=2021-02-10T15:45:43.242141315Z caller=memberlist_logger.go:74 level=info msg="Suspect loki-distributed-querier-0-ad576f7b has failed, no acks received"
ts=2021-02-10T15:45:43.259519103Z caller=memberlist_logger.go:74 level=warn msg="Refuting a suspect message (from: loki-distributed-ingester-2-2fab799f)"
ts=2021-02-10T15:45:43.234127902Z caller=memberlist_logger.go:74 level=warn msg="Refuting a suspect message (from: loki-distributed-distributor-5574f7f4d6-c8wj4-dc9c6ceb)"
...
ts=2021-02-10T15:46:02.036564693Z caller=memberlist_logger.go:74 level=warn msg="Was able to connect to loki-distributed-ingester-1-930ee310 but other probes failed, network may be misconfigured"
...
ts=2021-02-10T15:46:43.415077038Z caller=memberlist_logger.go:74 level=error msg="Failed fallback ping: read tcp 1.30.0.99:55428->1.20.3.218:7946: i/o timeout"
...
ts=2021-02-10T15:47:14.116301691Z caller=memberlist_logger.go:74 level=warn msg="Was able to connect to loki-distributed-distributor-5574f7f4d6-cmdhr-51caf0b6 but other probes failed, network may be misconfigured"
ts=2021-02-10T15:47:14.34752145Z caller=memberlist_logger.go:74 level=info msg="Suspect loki-distributed-querier-1-f5c19285 has failed, no acks received"
ts=2021-02-10T15:47:14.435785447Z caller=memberlist_logger.go:74 level=warn msg="Refuting a suspect message (from: loki-distributed-ingester-2-2fab799f)"
...
```

**Comment by twiechert** [comment]
Very likely to be the same reported here:

https://github.com/grafana/helm-charts/issues/157

**Comment by dbluxo** [comment]
> Are you using AWS CNI or a vendor one? Or did you ideally even find a solution to the problem?

@twiechert We are using the OpenShift SDN default CNI network provider: https://docs.openshift.com/container-platform/4.7/networking/openshift_sdn/about-openshift-sdn.html

Unfortunately we have't found a solution for this problem yet.

**Comment by bt909** [comment]
I've tried a bit with our Openshift 4.6 installation (same as dbluxo) and see this issue. Running on AWS EKS 1.19 with plain Amazon CNI, there is no such issue. So it looks like a network problem. I will open a Red Hat case to search for a solution and post the outcome here, if we get it solved.

**Comment by nvanheuverzwijn** [comment]
I have this exact same problem.
I'm using a kubernetes cluster with kops in AWS and Calico.

**Comment by nvanheuverzwijn** [comment]
@dbluxo @bt909 I think I understand what's going on..

The message "Suspect loki-distributed-distributor-5574f7f4d6-cmdhr-51caf0b6 has failed, no acks received" means that the pod that you are currently showing us the log message is suspecting that the `distributor` is dead. This message is broadcasted.

The message "Refuting a suspect message (from: loki-distributed-distributor-5574f7f4d6-c8wj4-dc9c6ceb)" means that the `distributor` saw that other nodes in the memberlist think it is dead so it is broadcasting a "refute" message to everyone.

This may be caused because the pod is under a lot of pressure e.g. the node supporting the pod is at 100% cpu.

**Comment by bt909** [comment]
@nvanheuverzwijn Yes, that is my understanding right now too. It was interesting that we saw this on nearly empty clusters. But we played around with resources and that seemed to resolve this issue. We now have load on the clusters and with good resources this message is very rare now.
