### ISSUE TITLE
Minimal filesystem documentation

### ISSUE THREAD

**Issue by theonlydoo** [grafana/loki#3324]
**Describe the bug**
Using loki in production for a while on a ext4 filesystem without `dir_index`, encountering a bug like described in:

- https://github.com/grafana/loki/issues/1502#issuecomment-777343212
- https://github.com/grafana/loki/issues/1502#issuecomment-765305138
- and https://github.com/grafana/loki/issues/1502#issue-548470519 (and I think others :-))

**To Reproduce**
1. Started Loki 
2. Started Promtail 
3. wait for a few hours/days to fill up your directory index space. 
4. cry

**Expected behavior**
Since it seems to be a requirement, it should be explicit in Loki's documentation that `dir_index` should be enabled.

**Environment:**
 - Infrastructure: bare metal + local storage and bare metal + minio remote storage.

**Comment by pettai** [comment]
Moving away from a flat single directory is the correct solution
 https://github.com/grafana/loki/issues/364

**Comment by theonlydoo** [comment]
@pettai indeed, but we still need to know its limitations and requirements.
