### ISSUE TITLE
Keep high cardinality labels without index to preserve context 

### ISSUE THREAD

**Issue by skk2142** [grafana/loki#3327]
**Is your feature request related to a problem? Please describe.**
There are many labels generated in kubernetes pods that are high cardinality, so inappropriate for indexing but they carry important information. 

**Describe the solution you'd like**
Skip indexing high cardinality labels but still keep them for context. 

Is there a way to keep some labels as a part of the log during the pipeline stage?

**Comment by frittentheke** [comment]
One thing would be to render the output as JSON and then place all those labels in there as fields as well as the source `message`.. This allows to just apply the `json` LogQL filter later when querying.

Adding the functionality of just dumping a set or even all existing fields as JSON to the `output` https://grafana.com/docs/loki/latest/clients/promtail/stages/output( would make this very easy. Similar to how the `labels` stage works.

**Comment by skk2142** [comment]
Thanks. It makes sense and that's what I wanted to do but I couldn't find any example of how to add a field to the output. All the examples that I have seen typically extract a field from labels or source and make that field as the new source. Any pointers on how to add a field to the source as a part of a JSON object, something like: { message: "<orignal_message>", "key1": "value1",... }

**Comment by frittentheke** [comment]
not stale
