### ISSUE TITLE
Missing arm docker image for fluent-bit-plugin-loki

### ISSUE THREAD

**Issue by draeron** [grafana/loki#3334]
This probably just require some new target on grafana docker build bot.

https://hub.docker.com/r/grafana/fluent-bit-plugin-loki

**Comment by nicocti** [comment]
+1, don't know where this is configured though...

**Comment by draeron** [comment]
unstale

**Comment by nicocti** [comment]
turns out the fluent-bit docker image has loki plugin embedded, and is available for ARM, so we don't actually need that fluent-bit-plugin-loki image !

**Comment by soumik-avoma** [comment]
@n0vad3v Is there a doc/step to implement this on ECS?
