### ISSUE TITLE
how can I increase the maximum active stream limit?

### ISSUE THREAD

**Issue by larsrnielsen** [grafana/loki#3335]
Got no answer to my question on Slack, trying here...

how can I increase the maximum active stream limit? I have installed Promtail, Loki via Helm and is using DynamoDB & S3 for index/storage

```
level=warn ts=2021-02-12T16:07:58.412735932Z caller=grpc_logging.go:38 method=/logproto.Pusher/Push duration=18.875075ms err="rpc error: code = Code(429) desc = Maximum active stream limit exceeded, reduce the number of active streams (reduce labels or reduce label values), or contact your Loki administrator to see if the limit can be increased" msg="gRPC\n"
```

**Comment by marioeu** [comment]
Hey @larsrnielsen, found that answer on the link below... you should look at max_streams_per_user where the default value is 10k, which in my case was quite low considering the volume of data I need to consume.

[https://grafana.com/docs/loki/latest/configuration/#limits_config](url)

**Comment by andreabenini** [comment]
Same problem here, I've moved `max_streams_per_user` to 100000 (100k) so:
```
limits_config:
  max_streams_per_user: 100000
```
It takes longer but after a short while I'm still getting what @larsrnielsen had, 
```
level=warn ts=2021-03-xxTxx:xx:xx.522790169Z caller=grpc_logging.go:38 duration=2.336389ms method=/logproto.Pusher/Push err="rpc error: code = Code(429) desc = Maximum active stream limit exceeded, reduce the number of active streams (reduce labels or reduce label values), or contact your Loki administrator to see if the limit can be increased" msg="gRPC\n"
```
I'm receiving just 4 promtail logs from remote hosts (PostgreSQL) but I _journalctl_ is full of them and loki seems to be really memory hungry (dedicated machine with 16Gb). Are there any hints to reduce that message ?

**Comment by yongzhang** [comment]
Same issue, should we disable `max_streams_per_user`?

**Comment by andreabenini** [comment]
@yongzhang 
Tried disabling that too but it continuously eats memory until the crash, I still haven't found a viable solution for it.
I'm parsing a considerable amount of logs (~1Gb/day logs from pgsql, from each single machine) but I'm far from solving it, messages persist and I don't have some kind of working sample to get ideas from.

**Comment by slim-bean** [comment]
Using regex to extract the timestamp in conjunction with the timestamp pipeline stage is normal practice and no problem.

This however:
```
- labels:
                  proxy_remote_addr:
                  proxy_time_local:
                  proxy_method:
                  proxy_request:
                  proxy_protocol:
                  proxy_status:
                  proxy_http_referer:
                  proxy_http_user_agent:
```
Should be removed entirely. This is not how to use Loki and it won't work well at all.

These values should not be stored as labels, rather you should use the regex or even more preferable the pattern [parser](https://grafana.com/docs/loki/latest/logql/#pattern) to extract them into labels at query time.

**Comment by smhhoseinee** [comment]
> @yongzhang 
I have the same problem 
did you find any solution ?

**Comment by yongzhang** [comment]
> [@yongzhang ](https://github.com/andreabenini) I have the same problem did you find any solution ?

For my case, the solution is to extract as less labels as possible in pipeline stages as suggested here https://github.com/grafana/loki/issues/3335#issuecomment-942150973

**Comment by xinkunZ** [comment]
> Using regex to extract the timestamp in conjunction with the timestamp pipeline stage is normal practice and no problem.
> 
> This however:
> 
> ```
> - labels:
>                   proxy_remote_addr:
>                   proxy_time_local:
>                   proxy_method:
>                   proxy_request:
>                   proxy_protocol:
>                   proxy_status:
>                   proxy_http_referer:
>                   proxy_http_user_agent:
> ```
> 
> Should be removed entirely. This is not how to use Loki and it won't work well at all.
> 
> These values should **not** be stored as labels, rather you should use the regex or even more preferable the pattern [parser](https://grafana.com/docs/loki/latest/logql/#pattern) to extract them into labels at query time.

@slim-bean  how about add some business "id" into labels？   I‘m using loki to store zipkin spans, it is a json data model, I just want to index all span id, but I got the exception too
```
HTTP status 429 Too Many Requests (429): Maximum active stream limit exceeded, reduce the number of active streams (reduce labels or reduce label values), or contact your Loki administrator to see if the limit can be increased"
```

**Comment by kumarganesh2814** [comment]
@slim-bean I dont use any labels as mentioned above 
[prod-1-loki-distributed-value.txt](https://github.com/grafana/loki/files/9166853/prod-1-loki-distributed-value.txt)
Still I see all these errors:

`HTTP status 429 Too Many Requests (429): Maximum active stream limit exceeded, reduce the number of active streams (reduce labels or reduce label values), or contact your Loki administrator to see if the limit can be increased"`

Any other solution which I can make

I tried increasing all values suggested at places:

`max_streams_per_user: 100000 `

` http_server_read_timeout: 60s
  http_server_write_timeout: 60`

**Comment by beremour** [comment]
So, what is the solution for this ?

**Comment by maciekm** [comment]
`max_streams_per_user` defaults to `0`, you most likely want to increase:
```
# Maximum number of active streams per user, across the cluster. 0 to disable.
# When the global limit is enabled, each ingester is configured with a dynamic
# local limit based on the replication factor and the current number of healthy
# ingesters, and is kept updated whenever the number of ingesters change.
# CLI flag: -ingester.max-global-streams-per-user

[max_global_streams_per_user: | default = 5000]
```

**Comment by joyartoun** [comment]
@maciekm Just want to express my gratitude for your comment, helped me alot!

**Comment by LennyPedersen** [comment]
Thanks @maciekm, it lead me into the right direction !

**Comment by morpig** [comment]
> These values should **not** be stored as labels, rather you should use the regex or even more preferable the pattern [parser](https://grafana.com/docs/loki/latest/logql/#pattern) to extract them into labels at query time.

@slim-bean experienced the same issue and I came across your statement. currently, i'm logging unique values on labels. 

in my case, each jobs/services have their own log formats (which I have a regex expression ready for it)

how would I query a userId from multiple jobs/services then? if I have 10 services, should I put all 10 regexes to a single query? thx
