### ISSUE TITLE
Driver causes Timeouts UnixHTTPConnectionPool Read timed out

### ISSUE THREAD

**Issue by rrajkomar** [grafana/loki#3336]
**Describe the bug**
Using the docker driver  causes slowiness when stopping or downing a stack

**To Reproduce**

1. A docker-compose project with two containers (php and nginx) connected to a loki container through the 172.17.0.1:3100 endpoint
2. Start the stack (no issues)
3. docker-compose stop or down the stack 

**Expected behavior**
No error. Fast shutdown (at least no longer than without)

**Actual behaviour** 
ERROR: for XXXXXXXX-nginx_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=130)

(Note: I increased the default timeout value to find a workaround)

Without the driver active on the container : less than a few seconds to down.

Relates to https://github.com/grafana/loki/issues/2053
And I did test the same stack with and without the driver on the container causing issues and there is definitely something related.

**Comment by rrajkomar** [comment]
Please note that the issue seems to be only when shutting down the stack, there's no delay at startup

**Comment by LinFor** [comment]
I have exactly the same issue regularily, but only with promtail and loki services.

**Comment by eringuet** [comment]
Having this issue. Using the example configuration and loki plugin. Containers do not shut stop when using docker container stop or docker-compose down.

**Comment by jeschkies** [comment]
This might be related to #2361 as well.
