### ISSUE TITLE
promtail: too many open files - possibly GO related?

### ISSUE THREAD

**Issue by jamiew0w** [grafana/loki#3346]
**Describe the bug**
Promtail isn't sending logs to loki, it needs to do a DNS lookup and fails with the message:
* Not just DNS, 

```
msg="error sending batch, will retry" status=-1 error="Post \"https://bleh.bleh/api/v1/push\": x509: failed to load system roots and no roots provided; open /etc/ssl/certs/ca-certificates.crt: too many open files

msg="error sending batch, will retry" status=-1 error="Post \"https://bleh.bleh/api/v1/push\": dial tcp: lookup loki.labs.ie on 127.0.0.1:53: dial udp 127.0.0.1:53: socket: too many open files
```

**To Reproduce**
1. Started Loki (SHA or version)

```promtail, version 2.1.0 (branch: HEAD, revision: 1b79df37)
  build user:       root@b8941a81fe55
  build date:       2020-12-24T14:08:17Z
  go version:       go1.15.3
  platform:         linux/amd64
```

2. Started Promtail (SHA or version) to tail '...'

```2021-02-16 22:37:41.217290 I | proto: duplicate proto type registered: ingester.Series
loki, version 2.1.0 (branch: HEAD, revision: 1b79df37)
  build user:       root@b8941a81fe55
  build date:       2020-12-24T14:08:17Z
  go version:       go1.15.3
  platform:         linux/amd64
```

**Expected behavior**
It should work. ulimits seem fine:

```
root@ingest:/etc/systemd# ulimit -Hn
150000
root@ingest:/etc/systemd# ulimit -Sn
150000
```

**Environment:**
 - Infrastructure: Ubuntu 20.04 virtual machines:
 
 ```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

 - Deployment tool: github releases

**Screenshots, Promtail config, or terminal output**

I think its a GO related issue rather than loki, but I'm not knowledgeable enough to say for sure.

**Comment by unguiculus** [comment]
Probably not only related to ulimits. The Promtail Helm chart has an optional init container for tweaking `fs.inotify.max_user_instances` to fix issues with too many open files.

See https://github.com/grafana/helm-charts/blob/86c43461578f0d53d9f3edc49a2a36e4a984e7a7/charts/promtail/templates/daemonset.yaml#L40-L42

**Comment by Alxander64** [comment]
What @unguiculus suggested worked for me

**Comment by younsl** [comment]
The collection target was a Standalone EC2 instance running Ubuntu 20.04.5 LTS with promtail 2.0.0. I resolved the issue as follows. Thanks @unguiculus!

Increased `max_user_instances` parameter from 1024 to 2048:

```bash
sudo sysctl -w fs.inotify.max_user_instances=2048
```

However, the `too many open files` error messages occurred again in `promtail` daemon.

Increased `max_user_watches` parameter from 59,498 to 118,996:

```bash
sudo sysctl -w fs.inotify.max_user_watches=118996
```

Check the applied kernel parameters:

```console
$ sysctl fs.inotify.max_user_instances fs.inotify.max_user_watches
fs.inotify.max_user_instances = 2048
fs.inotify.max_user_watches = 118996
```

**Comment by younsl** [comment]
Here's my solution in standalone EC2 environment as a target. I hope this helps you guys.

---

## Summary

If encounter the `error="filetarget.fsnotify.NewWatcher: too many open files"` error in standalone EC2, you can resolve it by adding the LimitNOFILE setting to the service file.

```mermaid
flowchart LR
  subgraph "Target EC2"
    p("promtail daemon")
    style p fill:#00008B,stroke:#ffffff,color:#ffffff
  end
  a("ALB")
  subgraph "EKS"
    i("Ingress")
    l("loki-distributed pods")
  end
  p --443--> a --> i --> l
```

## Environment

I resolved the issue in the following environment:

- **Target**: EC2, amd64, Ubuntu 20.04.5 LTS
  - **Logs to scrape**: the ec2_sd_configs located in `/var/log/**.log`, the journal located in `/var/log/journal`
- **Promtail** v2.0.0 (controlled by systemd)
- [**Loki distributed** chart](https://github.com/grafana/helm-charts/tree/main/charts/loki-distributed) 0.79.2 (loki v2.9.8)
- **EKS v1.28**

## Solutions

### Declare `LimitNOFILE` in promtail service

Monitoring command showed that promtail daemon was using up to 25,000 inotify, already before action.

```console
$ sudo lsof | grep inotify | tr -s ' ' | cut -f1,2 -d" " | sort | uniq -c | sort
  25550 promtail- 2965164
```

Relavant kernel parameters for inotify (In my case, no changes were needed to solve the problem):

```console
$ sysctl fs.inotify
fs.inotify.max_queued_events = 16384
fs.inotify.max_user_instances = 1024
fs.inotify.max_user_watches = 59498
```

Add the `LimitNOFILE` setting to your `promtail.service` file as follows:

```yaml
# /etc/systemd/system/promtail.service
[Service]
...
LimitNOFILE=500000
```

The complete `promtail.service` file should look like this:

```yaml
# /etc/systemd/system/promtail.service
[Unit]
Description=Promtail

[Service]
User=root
WorkingDirectory=/opt/promtail/
ExecStartPre=/bin/sleep 30
ExecStart=/opt/promtail/promtail-linux-amd64 --config.file=./ec2-promtail.yaml
SuccessExitStatus=143
TimeoutStopSec=10
Restart=on-failure
RestartSec=5
LimitNOFILE=500000

[Install]
WantedBy=multi-user.target
```

Reload and restart the promtail daemon to apply the changed systemd settings.

```bash
systemctl daemon-reload
systemctl restart promtail.service

# Continue to monitor whether the too many open files error occurs again.
watch -d -n2 "systemctl status promtail -l"
```

I actually solved the `too many open files` error this way.

After the `LimitNOFILE` setting was added to the promtail daemon, I observed that it was occupying over 100000 inotify without any `too many open files` error.

```console
$ sudo lsof | grep inotify | tr -s ' ' | cut -f1,2 -d" " | sort | uniq -c | sort
 110418 promtail- 3040317
```

## References

- https://github.com/grafana/loki/issues/1153
- https://www.robustperception.io/dealing-with-too-many-open-files/
- [Run the Promtail client on AWS EC2](https://grafana.com/docs/loki/latest/send-data/promtail/cloud/ec2/) <sup>Official installation guide by loki</sup>

**Comment by younsl** [comment]
Here's my solution in standalone EC2 environment as a target. I hope this helps you guys.

---

## Summary

If encounter the `error="filetarget.fsnotify.NewWatcher: too many open files"` error in standalone EC2, you can resolve it by adding the LimitNOFILE setting to the promtail service file.

```mermaid
flowchart LR
  subgraph "Target EC2"
    p("promtail daemon")
    style p fill:#00008B,stroke:#ffffff,color:#ffffff
  end
  a("ALB")
  subgraph "EKS"
    i("Ingress")
    l("loki-distributed pods")
  end
  p --443--> a --> i --> l
```

## Environment

I resolved the issue in the following environment:

### Target

- **Target**: EC2, amd64, Ubuntu 20.04.5 LTS
  - **Logs to scrape**: the ec2_sd_configs located in `/var/log/**.log`, the journal located in `/var/log/journal`
- **Promtail** v2.0.0 (controlled by systemd)

> [!NOTE]
> The EC2 Instance, which is the target of log scraping, was installed and configured by referring to the Loki official documentation: [Run the Promtail client on AWS EC2](https://grafana.com/docs/loki/latest/send-data/promtail/cloud/ec2/).

### Log aggregation system

- [**Loki distributed** chart](https://github.com/grafana/helm-charts/tree/main/charts/loki-distributed) 0.79.2 (loki v2.9.8)
- **EKS v1.28**

## Solutions

### Declare `LimitNOFILE` in promtail service

Monitoring command showed that promtail daemon was using up to 25,000 inotify, already before action.

```console
$ sudo lsof | grep inotify | tr -s ' ' | cut -f1,2 -d" " | sort | uniq -c | sort
  25550 promtail- 2965164
```

Relavant kernel parameters for inotify (In my case, no changes were needed to solve the problem):

```console
$ sysctl fs.inotify
fs.inotify.max_queued_events = 16384
fs.inotify.max_user_instances = 1024
fs.inotify.max_user_watches = 59498
```

Add the `LimitNOFILE` setting to your `promtail.service` file as follows:

```yaml
# /etc/systemd/system/promtail.service
[Service]
...
LimitNOFILE=500000
```

The complete `promtail.service` file should look like this:

```yaml
# /etc/systemd/system/promtail.service
[Unit]
Description=Promtail

[Service]
User=root
WorkingDirectory=/opt/promtail/
ExecStartPre=/bin/sleep 30
ExecStart=/opt/promtail/promtail-linux-amd64 --config.file=./ec2-promtail.yaml
SuccessExitStatus=143
TimeoutStopSec=10
Restart=on-failure
RestartSec=5
LimitNOFILE=500000

[Install]
WantedBy=multi-user.target
```

Reload and restart the promtail daemon to apply the changed systemd settings.

```bash
systemctl daemon-reload
systemctl restart promtail.service

# Continue to monitor whether the too many open files error occurs again.
watch -d -n2 "systemctl status promtail -l"
```

I actually solved the `too many open files` error this way.

After the `LimitNOFILE` setting was added to the promtail daemon, I observed that it was occupying over 100000 inotify without any `too many open files` error.

```console
$ sudo lsof | grep inotify | tr -s ' ' | cut -f1,2 -d" " | sort | uniq -c | sort
 110418 promtail- 3040317
```

## References

- https://github.com/grafana/loki/issues/1153
- https://www.robustperception.io/dealing-with-too-many-open-files/
- [Run the Promtail client on AWS EC2](https://grafana.com/docs/loki/latest/send-data/promtail/cloud/ec2/) <sup>Official installation guide by loki</sup>
