### ISSUE TITLE
[promtail] Additional file-based metric for unready targets

### ISSUE THREAD

**Issue by sboschman** [grafana/loki#3359]
**Is your feature request related to a problem? Please describe.**
Sometimes promtail fails to update kubernetes service discovery labels and is unable to match a target to a logfile. The application pod has been redeployed with a new version, new pod uid, new log file location. But promtail service discovery keeps using the old/previous labels and the target is 'not ready' (as it has no logfile).
To at least be notified when this happens, I was looking into creating a Prometheus alert to detect 'not ready' promtail targets.

**Describe the solution you'd like**
https://github.com/grafana/loki/blob/master/pkg/promtail/targets/file/metrics.go#L24 has three relevant metrics: files_active_total (gauge), targets_failed_total (counter) and targets_active_total (gauge).

1 active target can have multiple active files, so target_active_total - files_active_total does not work.

As far as I understand the code the flow is:
- get list of potential targets from service discovery
- throw away potential targets that fail sanity checks and report to targets_failed_total with reason
- the remaining targets are 'active targets' and reported to target_active_total
- target tries to open its logfiles, might fail -> not ready, but this is not reported to any metric

To be able to create a Prometheus alert it would be nice to have the fact that a target has no logfile associated with it reported to a metric. 

As a sidenote, I am not sure it is good practice to name gauge metrics with the '_total' suffix, I think that suffix is sort of reserved for counters.

So, perhaps target_active_total could be split with a 'status' label:
`target_active(status='ready')` and `target_active(status='unready')`

**Describe alternatives you've considered**
Keep the `target_active_total` / `target_active` metric and introduce a new `target_unready` metric, but it seems most kubernetes metrics use the label approach

**Comment by james-callahan** [comment]
Could this be reopened? (would be good to have this metric).

> The application pod has been redeployed with a new version, new pod uid, new log file location. But promtail service discovery keeps using the old/previous labels and the target is 'not ready' (as it has no logfile).

@sboschman  do you think you hit the same as I describe in #3892 ?

**Comment by sboschman** [comment]
@james-callahan Yes, your description in #3892 sounds exactly like what I see happening. We run on Kubernetes Rancher/RKE 1.20.
