### ISSUE TITLE
Cluster Failure - Loki logs

### ISSUE THREAD

**Issue by iyappansg** [grafana/loki#3364]
Hi All,

This is my first question to the forum. So please excuse , if its not relevant.

When we are running LOKI server as part of kubernetes cluster, if something goes bad to the cluster , what will happen to my logs. Is it recoverable ? What is the strategy we need to have to recover the logs.

Thanks,
Iyappan S

**Comment by adityacs** [comment]
@iyappansg You can read more about how Loki stores data here https://github.com/grafana/loki/blob/master/docs/sources/storage/_index.md.
