### ISSUE TITLE
Promtail not following symlinks as expected

### ISSUE THREAD

**Issue by fchiorascu** [grafana/loki#3374]
**Is your feature request related to a problem? Please describe.**
Possibility to collect (tail) logs from stdout/stderr, port?

The current static_config uses **__path__** (log files) https://grafana.com/docs/loki/latest/clients/promtail/configuration/#static_configs that for `symlinks ` is not working as expected.

**Using: PLG Stack**
Grafana: 7.4.0
Loki: 2.1.0
Promtail: 2.1.0

**Describe the solution you'd like**
- **Promtail** being able to tail logs from: path file logs - symlinks, port, stdout, stderr of a pod/container in RHEL OpenSHift Container > 3.9 from a namespace.

**Describe alternatives you've considered**
- At least being able to tail path file logs - symlinks.

**Additional context**
- https://docs.fluentbit.io/manual/pipeline/filters/standard-output
- https://docs.fluentbit.io/manual/pipeline/inputs/tcp

**Comment by bramevo** [comment]
+1 For this request. I need to be able parse compressed log files (gzip) and this would be possible using the above I assume.
Now I need a dedicated container just for decompressing the logfiles before using the promtail container to parse them.

**Comment by proffalken** [comment]
Isn't this what Fluentd/fluent-bit are for?

Promtail seems like a good starting place to slurp logs, but if you want to do processing on the data as it comes in then there are plenty of existing tools for that and we should be careful not to re-invent the wheel.

Admittedly neither of them are able to parse compressed files, but it feels we should add the features to something like that rather than adding it to promtail?

**Comment by fchiorascu** [comment]
@proffalken thank you for your point of view.

I understand that is not a need of reinventing the wheel or covering the same aspects with multiple options/similar tools, this is clear and no doubt there. However I don't need promtail for log processing or to use in complex ecosystems, it was a good fit for us due to the fact that is lightweight and we could integrate in a small RHEL OpenShift Container Platform (namespace) to collect logs from 1 application (backend/frontend) but he is not behaving well with symlinks and doesn't have the maturity or alternatives to file log __path__ such as stdout, stderr, port. Why to use fluentbit/fluentd instead of using entire PLG Stack, reducing the complexity and being sure that the pieces integrates seamlessly.

**Comment by proffalken** [comment]
@fchiorascu that's fair enough, objection removed ;)

**Comment by proffalken** [comment]
Commenting to keep this open, I think it's a really useful addition to Loki/Promtail.

**Comment by proffalken** [comment]
No thanks @stalebot - let's keep this one open...

**Comment by majuansari** [comment]
Please keep this one open. Much needed feature

**Comment by MurzNN** [comment]
Very useful feature, reopen pls!

**Comment by fchiorascu** [comment]
Reopen please.

**Comment by slim-bean** [comment]
Trying to understand this issue and it feels like it covers multiple topics.

In regards to the symlinks not working, this sounds like a bug, we use symlinks all the time without issue, are you able to provide more context here?

In regards to logs from stdout and stderr, promtail supports the `--stdin` [flag now which lets you pipe logs into promtail.](https://grafana.com/docs/loki/latest/clients/promtail/troubleshooting/#pipe-data-to-promtail)

**Comment by MurzNN** [comment]
Bump

**Comment by DylanGuedes** [comment]
Apparently, https://github.com/grafana/tail/pull/12 solves this :eyes:
