### ISSUE TITLE
Loki or promtail should handle "entry out of order" messages

### ISSUE THREAD

**Issue by moduspwnens** [grafana/loki#3379]
**Is your feature request related to a problem? Please describe.**
We run ~100 single-node kubernetes clusters acting as network appliances, and to help troubleshoot some issues, we're using promtail to scoop up apiserver audit logs and send them to a centralized Loki instance. All log streams have a "host_ip" label that keeps them unique for each host, and each host has only a single promtail instance running.

Many of the log entries get rejected by Loki, though, because they're out of order. As it looks, though, Loki is just correct: apiserver audit logs sometimes just have entries with timestamps that are out of order--especially when there is a lot of activity. The logs for k3s and containerd (which we're also forwarding) have the same issue, although not quite as severe.

apiserver audit logs are especially useful for troubleshooting when and what changed a given Kubernetes resource from one state to another, but that usefulness is limited greatly when a significant chunk (~10-20%) of those log messages are ignored due to being out of order.

**Describe the solution you'd like**
Ideally, Loki would simply support ingesting out-of-order messages, even if there were some caveats (like a sliding time window, or only within the same batch from promtail). Although I understand this is architecturally difficult due to the way Loki works.

**Describe alternatives you've considered**
We could build our own process for continuously watching some log files, parsing out the timestamps like promtail will, reorder entries as necessary, and write out new log files for promtail to consume. Although this seems like overkill for an issue that is likely reasonably common and should have a cleaner solution.

It might be possible to make Loki configurable to "fudge" the timestamps on offending entries within an allowable window, while also keeping the original timestamp in metadata of some kind. Then at least it wouldn't be *ignoring* the messages, although obviously it would introduce some cognitive overhead when reviewing log messages. Most offending entries are within factions of seconds, although being able to see the original order of operations occurring is still important.

Presumably promtail could itself support some form of sliding time window to allow for tracking / reordering individual messages, although I understand this will have non-trivial architectural trade-offs.

**Additional context**
I wouldn't normally complain about something like this if it's only us affected, but I expect ingesting apiserver audit logs is probably something a lot of other people do, so it'll need a good solution at some point (if one doesn't already exist).

I'm no Go expert, but my assumption (since the k3s and containerd logs also have out-of-order entries) is that it's a result of Go's emphasis on concurrency, so it might also affect more use cases than just the ones we've seen.

**Comment by ChrisSteinbach** [comment]
This must be a problem for every multithreaded service right? Unless thread synchronisation for the sake of log timestamp ordering is more common than I imagine. How do folks get around that? One log stream per thread sound like an ugly fix.

**Comment by moduspwnens** [comment]
It might not be a factor for containerized applications, since you're then (presumably) relying on the container engine's logging facility that presumably does its own timestamps. The use cases I'm struggling with (apiserver audit logs, k3s, and containerd) are all node-level things that are not, themselves, containerized.

**Comment by pepisito** [comment]
How do the other log platforms (ELK, Splunk, etc.) handle this log out-of-order issue?  Is this the responsibility of the user, or, log platforms?

**Comment by bramevo** [comment]
We have the same issue. We try to process logs from our CDN (Akamai). We have an option to get these logs either aggregated by log arrival time (which are out of order) or aggregated by hit time. But aggregated by hit time is only possible once a day, while aggregated by log arrival time can be as fast as once per hour.

So the side effect of the requirement to provide logs in a none out-of-order way would delay receiving the logs from hours to days. Having to wait an additional day to analyse the logs (because in order logs are required) kills our use case.

**Comment by frittentheke** [comment]
@bramevo if I understand correctly you receive the logs in large chunks once per hour, just not strictly sorted by timestamp?
While I understand the issue with Loki not being able to even tolerate a short interval of out-of-order logs,  could you not simply sort them prior to feeding them into Loki? Certainly there is the risk that the last few lines around the turn of the hour would leak into the next chunk you receive from Akamai, but this would get you there 99%. And if you cut off the last few minutes of every log data chunk and leave that for the next hour data you should be good, right?

**Comment by frittentheke** [comment]
And just BTW ... this "issue" is being discussed and even designed on at
* https://github.com/grafana/loki/issues/1544
* https://github.com/grafana/loki/pull/3268

**Comment by ukolovda** [comment]
There was PR https://github.com/grafana/loki/pull/3268 from @owen-d 
It start discuss this problem and ways to resolve it. But I don't know situation now.
Do anybody working with this issue? Where can I see status and, my make some help?

**Comment by stevehipwell** [comment]
@owen-d is there a status update on your work for this?
