### ISSUE TITLE
logcli: Support reconnecting on connection closed with --tail

### ISSUE THREAD

**Issue by chancez** [grafana/loki#3387]
**Is your feature request related to a problem? Please describe.**
If loki is configured with a `querier.max_tail_duration`, then `logcli query --tail` will disconnect after being connected for the max_tail_duration with the following error:
```Error reading stream: websocket: close 1011 (internal server error): reached tail max duration limit```
It would be useful if `logcli` could detect this and reconnect automatically.

**Describe the solution you'd like**
`logcli query --tail` reconnects automatically instead of exiting with `Error reading stream: websocket: close 1011 (internal server error): reached tail max duration limit`. It should also ideally track the last timestamp it saw and reconnect starting from that time to avoid replaying logs already seen.

**Describe alternatives you've considered**
This could be opt-in with another flag combined with `--tail`. 

Also, instead of having the client tracking the last timestamp it saw, the tail API could return a "continuation token" of sorts, so that the server is responsible for tracking where in a stream a client was, and then if a client reconnects with the same continuation token, then the stream picks up where it left off.

**Comment by boniek83** [comment]
I would also argue this shouldn't be an error level log on Loki's side. This is just debug, info at best.

**Comment by james-callahan** [comment]
> I would also argue this shouldn't be an error level log on Loki's side. This is just debug, info at best.

Agreed. Should we open a new issue for that?
