### ISSUE TITLE
Install and run Loki locally: fail to start loki: duplicate proto type registered: ingester.Series

### ISSUE THREAD

**Issue by mrechte** [grafana/loki#3392]
**Describe the bug**
loki does not start.

**To Reproduce**
I followed the instructions on https://grafana.com/docs/loki/latest/installation/local/, downloaded v2.1.0 for linux-amd64 platform and the 2 yaml files.

I did not change the default config.

```
$ ./loki-linux-amd64 -config.file=loki-local-config.yaml
2021-02-26 16:00:12.851126 I | proto: duplicate proto type registered: ingester.Series
failed parsing config: loki-local-config.yaml: yaml: unmarshal errors:
  line 7: field wal not found in type ingester.Config
```

**Environment:**
ArchLinux

**Comment by slim-bean** [comment]
hey @mrechte!

The duplicate proto type registered message is unrelated, (it's related to a vendoring issue with cortex which we can't seem to make go away) but it also doesn't seem to cause any problems aside from that annoying message.

The problem you are seeing here is that the WAL code is not in 2.1.0 and you are using a config file from master which includes WAL code configs.

You would need to build a binary from master to use your config or [the docs for 2.1.0](https://grafana.com/docs/loki/v2.1.0/installation/local/) have links to tagged versions of those config files which should work.
