### ISSUE TITLE
Document the "replace" pipeline stage

### ISSUE THREAD

**Issue by dannykopping** [grafana/loki#3415]
**Is your feature request related to a problem? Please describe.**
The `replace` pipeline stage is currently [undocumented](https://grafana.com/docs/loki/latest/clients/promtail/configuration/#pipeline_stages).

**Comment by slim-bean** [comment]
Looks like [it is documented](https://grafana.com/docs/loki/latest/clients/promtail/stages/replace/) but not updated in the link listed in the issue

**Comment by namit-chandwani** [comment]
Hey, I'd like to work on this issue. Can you please assign it to me?

**Comment by dannykopping** [comment]
@namit-chandwani feel free to assign yourself and submit a PR :slightly_smiling_face:

**Comment by sasagarw** [comment]
I am planning to work on this issue. Can you please assign this to me? @slim-bean

**Comment by sasagarw** [comment]
@dannykopping can you please review and merge #5200 if appropriate?

**Comment by dannykopping** [comment]
> @dannykopping can you please review and merge #5200 if appropriate?

Our technical writer, @KMiller-Grafana, is the only one who can review and approve documentation changes. It's in her to-do list, thanks for the PR @sasagarw :+1:
