### ISSUE TITLE
Logcli field regex does not work with "log" field specifically

### ISSUE THREAD

**Issue by caleb15** [grafana/loki#3436]
**Describe the bug**
Logcli field regex behaves in very strange ways contrary to expectation

**To Reproduce**
1. Started Loki (helm chart version 2.3.0, which was latest last time I checked)
2. Started Promtail (helm chart version 3.0.5, which was latest last time I checked) to tail '...'
3. Query: `logcli query '{app="nginx",job="fifteen5/nginx"} | json | log=~".*"'`

**Expected behavior**
All nginx logs to be returned.

**Environment:**
 - Infrastructure: kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

The same query on a different field worked:
`logcli query '{app="nginx",job="fifteen5/nginx"} | json | stream=~".*"'`

Using an exact match works:
`{app="nginx",job="fifteen5/nginx"} | json | log="10.51.82.226 - - [04/Mar/2021:01:33:52 +0000] \"GET / HTTP/1.1\" 404 118 \"-\" \"ELB-HealthChecker/2.0\"\n"`

Here's an example of the log line that should be showing up:
`{"log":"10.51.82.226 - - [04/Mar/2021:01:33:52 +0000] \"GET / HTTP/1.1\" 404 118 \"-\" \"ELB-HealthChecker/2.0\"\n","stream":"stdout","time":"2021-03-04T01:33:52.615363491Z"}`

**Comment by caleb15** [comment]
ohhhh wait maybe this is it:

https://prometheus.io/docs/prometheus/latest/querying/basics/

Vector selectors must either specify a name or at least one label matcher that does not match the empty string. The following expression is illegal:
> {job=~".*"} # Bad!

That's reallly weird..... `.*` is a valid regex. :|

**Comment by caleb15** [comment]
I had other problems with it too, I'll have to go back and test this again.

**Comment by caleb15** [comment]
ah `{app="nginx"} | json | log=~".+"` still fails (as in returns no logs when it should)

**Comment by caleb15** [comment]
What's also weird is if `.*` is invalid why would it work for stream but not log? I feel like there's either a bug or I'm missing something major here :thinking:

**Comment by paaacman** [comment]
Workaround : use `line_format` to access Line filter:
`{app="nginx",job="fifteen5/nginx"} | json | line_format "{{.log}}" |= "is not found"`

**Comment by caleb15** [comment]
I found the reason - the newline in the log is messing things up.
`{app="nginx"} | json | log=~".+\n"` works!

**Comment by caleb15** [comment]
and here's the other part of the puzzle - the prometheus docs say `Regex-matches are fully anchored`. This explains why partial matches were not working, I have to match the entire string.

**Comment by caleb15** [comment]
and the last thing I found is if I want `.` to match newline I can enable the single line flag, like so:
`{app="nginx"} | json | log =~ "(?s).*is not found.*"`

**Comment by caleb15** [comment]
oh wait one more thing, `.*` does actually work after all:
`{app="bamboo-hr-sync"} | json | log=~".*"` matches `{"log":"OK","stream":"stdout","time":"2021-03-04T11:04:23.536263015Z"}`
