### ISSUE TITLE
Loki rule operator

### ISSUE THREAD

**Issue by steven166** [grafana/loki#3456]
**Is your feature request related to a problem? Please describe.**
Currently there is no easy declarative way to create and maintain Loki alert rules via the Kubernetes Api. For example see [this comment](https://github.com/grafana/loki/issues/2990#issuecomment-736743856).

**Describe the solution you'd like**
I've created the [loki-rule-operator](https://github.com/opsgy/loki-rule-operator) which adds a `LokiRule` and `GlobalLokiRule` [CRD](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#customresourcedefinitions) to Kubernetes, that let you configure Loki Alert Rules via the Kubernetes Api. It works almost the same way as with the `PrometheusRule` CRD from the [prometheus-operator](https://github.com/prometheus-operator/prometheus-operator). 

This operator will help users to manage and interact with their Loki alert rules in a more natural way with Kubernetes. Wouldn't it be nice to propose this operator as an alternative way for users to interact with the Ruler in the [documentation](https://grafana.com/docs/loki/latest/alerting/#interacting-with-the-ruler)? 

**Describe alternatives you've considered**
The alternative is to use the cortex tool. But not many users are familiar with this cli and compared to the Kubernetes Api has it way fewer integrations with existing tooling (a few examples: Helm, ArgoCD...). 

**Additional context**
Addition information about the loki-rule-operator can be found on its [Github page](https://github.com/opsgy/loki-rule-operator).

**Comment by nvanheuverzwijn** [comment]
@steven166 @cyriltovena I have opened a PR that adds a helm-chart to install this @steven166 contribution. _It works_.

**Comment by jtyr** [comment]
I think this should only be mentioned in the official Loki documentation but the Helm chart should be published in the operator's repository.

**Comment by Kampe** [comment]
would love to see this added as an option within the helm chart

**Comment by zkl94** [comment]
It's a shame this didn't make it to the official helm chart level. We are using kube-prometheus stack and developers are defining PrometheusRule and AlertmanagerConfig to add rules and alerts for their specific applications (namespaces). It would be great if we can define Loki rules with CRD as well.

**Comment by periklis** [comment]
@Kampe The Loki Operator hosted in this [repo](https://github.com/grafana/loki/tree/main/operator) supports CRDs for `AlertingRule` and `RecordingRule`. Let me know if that helps.

**Comment by zkl94** [comment]
@periklis does this operator have a corresponding helm chart atm?

**Comment by periklis** [comment]
@zkl94 No it does not. You can install only directly from the repo as per first release is still outstanding.

**Comment by dansl1982** [comment]
Hi All, 

Do you know if I can use the loki-operator alongside the Loki-distributed? If yes, is there a helm chart to install Loki-operator? 

I want to use it to manage LokiRules. 

Thanks in advance

**Comment by juliendf** [comment]
@dansl1982 Did you find an answer ? I would like to do the same thing but my understanding is that you should have a lokistack to be able to use the operator to deploy rules. Is that correct ?

**Comment by tomhaynes** [comment]
We're also keen to adopt this, and would ideally have a helm chart @periklis is there an ETA for the first release?

**Comment by onedr0p** [comment]
I couldn't find a issue requesting a loki-operator helm chart, maybe the operator is still in testing?

**Comment by efekete** [comment]
Any news on this? I would also like to test this

**Comment by efekete** [comment]
Is there a plan to create a Helm chart for that or include it to Loki helm chart?

**Comment by periklis** [comment]
No plans doing so.

**Comment by periklis** [comment]
Please feel free to submit a PR, glad to help you with reviews

**Comment by efekete** [comment]
I started writing some Helm for the loki operator and I think I managed to deploy (huge WIP, can't commit atm to actually finish it to be community ready, though I can share what I have)

but I ended up with questions:
 - can I actually deploy with it only alertrules and recordingrules

**Comment by periklis** [comment]
> I started writing some Helm for the loki operator and I think I managed to deploy (huge WIP, can't commit atm to actually finish it to be community ready, though I can share what I have)
> 
> but I ended up with questions:
> 
>     * can I actually deploy with it only alertrules and recordingrules?
> 
>     * how do I point to my current Loki installation? (if possible)

@efekete Sorry for the late reply, was off on other duties the last week. Please share even in a working branch what you have to get a feeling where you are. To both question I can answer with no, because the Loki Operator is an all-or-nothing design. Mean it manages your Loki instance as well as the accompanying AlertingRules/RecordingRules and the RulerConfig.

**Comment by camoes** [comment]
So this means that we can't follow the same approach that we can with the prometheus-operator PrometheusRule objects then? If we already have an existing loki stack running how can we dynamically add new alertingrules to the existing stack without ConfigMaps approach ?

**Comment by camoes** [comment]
In case somebody else get to this thread , there is a way to achieve this making use of grafana-agent/Alloy https://community.grafana.com/t/loki-dynamic-alerting-rules-generation/139953/5

**Comment by sharovmerk** [comment]
@camoes but it does not support LogQL syntax, so the issue is still actual

**Comment by sharovmerk** [comment]
@periklis if operator does not support managing rules for the external Loki stack, can https://github.com/opsgy/loki-rule-operator be integrated to loki?

**Comment by MauritsMonteyne** [comment]
@sharovmerk I recently added the option to specify match conditions for admission webhooks for the kube prometheus chart. It's now possible to disable rule validation for rules with a certain tag e.g. `loki=<tenant>`

```
    admissionWebhooks:
      matchConditions:
        # Disable Prometheus rule validation when the object has a "loki" label
        - name: ignore-loki-rules
          expression: '!("loki" in object.metadata.labels)'

```

**Comment by kvendingoldo** [comment]
@MauritsMonteyne thank you very much for your help.
I created a guide for people, who will try to do it in the future: https://hackernoon.com/how-to-create-loki-alerts-via-prometheusrule-resource
