### ISSUE TITLE
Promtail missing short-lived pod logs

### ISSUE THREAD

**Issue by nmiculinic** [grafana/loki#3458]
**Describe the bug**

We have a short-lived container. It's created, it executes quite quickly (thing `echo "sss"; exit 1`) and when the pod phase reaches completed a controller deletes the pod. 

The promtail hasn't shipped the pod's logs to the loki. It hasn't added it as a target, nor started tailing the log file before the log file was deleted (we're using docker with json-log logging driver)

**To Reproduce**
1. Started Promtail (SHA or version) to tail '...': v2.1.0
2. Start short-lived container

**Expected behavior**
Promtail tailing the short-lived container logfile and shipping it out

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]: k8s, EKS
 - Deployment tool: [e.g., helm, jsonnet]: helm, promtail

**Comment by ipleten** [comment]
I wonder why it was closed it's still an issue.
