### ISSUE TITLE
Tenant Federation

### ISSUE THREAD

**Issue by midnightconman** [grafana/loki#3462]
**Is your feature request related to a problem? Please describe.**
Multi-tenant support is great, it makes possible tenant ingestion limits that can greatly increase the stability of the platform. Unfortunately there are no mechanisms to allow querying across tenants.

**Describe the solution you'd like**
Now that Cortex has tenant federation, when can we get this functionality in Loki? https://github.com/cortexproject/cortex/pull/3250

**Describe alternatives you've considered**
We earlier spoke about allowing multiple tenant IDs via a separator, not sure if there are any other possible solutions?

**Additional context**
https://github.com/grafana/loki/issues/1650

**Comment by Nitive** [comment]
Not stale

**Comment by midnightconman** [comment]
Stalebot closed this even after a comment 😿

**Comment by singh9vj** [comment]
Please let us know if this is still not possible to create a global querier across multiple tenants.

**Comment by slim-bean** [comment]
Loki does not yet have this ability but it's on the short list of features. stay tuned.

**Comment by jkroepke** [comment]
Is there any workarounds?

**Comment by slim-bean** [comment]
This functionality exists now!

It's not in a released version of Loki yet, but a new release with it should be available in the next couple weeks.

https://grafana.com/docs/loki/next/operations/multi-tenancy/#multi-tenant-queries

If you don't want to wait for the release, we have an internal release we are running `grafana/loki:k100-92a8b63` which has this functionality in it.

**Comment by jkroepke** [comment]
@slim-bean Sounds great! But an Superview of all tenants, e.g. `X-Scope-OrgID: *` is still not possible?

**Comment by 09jvilla** [comment]
> But an Superview of all tenants, e.g. X-Scope-OrgID: * is still not possible?

Correct.

**Comment by 09jvilla** [comment]
Closing as completed with the release of Loki 2.6. 
https://grafana.com/docs/loki/latest/operations/multi-tenancy/#multi-tenant-queries
