### ISSUE TITLE
need retest hook for PR

### ISSUE THREAD

**Issue by daixiang0** [grafana/loki#348]
Sometimes, PR test failed since network issue, but for now, only need to add a new commit to retest.

**Comment by daixiang0** [comment]
like [test result](https://circleci.com/gh/grafana/loki/2922?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link)

**Comment by daixiang0** [comment]
update:
[test failed](https://circleci.com/gh/grafana/loki/2932?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link)

**Comment by daixiang0** [comment]
use `git commit --amend` can change commit id.

**Comment by tomwilkie** [comment]
You can go into the circle ci UI and click rerun.

**Comment by daixiang0** [comment]
@tomwilkie oops, seems i do not have rerun access...
