### ISSUE TITLE
Timeout errors between grafana and loki

### ISSUE THREAD

**Issue by UndeadJoe** [grafana/loki#349]
There are many timeout errors when started grafana and loki in kubernetes cluster.

In Grafana logs i see error:
"http: proxy error: dial tcp <ip-address-of-loki-server>:3100: i/o timeout"

![image](https://user-images.githubusercontent.com/6937605/53226446-12307e00-368c-11e9-8af9-19bd7a492bb3.png)

Query is simple:
![image](https://user-images.githubusercontent.com/6937605/53225809-3b500f00-368a-11e9-8066-44e22155e879.png)
For 24 hours time range there are about 500 messages with this query.

**Environment:**
 - Infrastructure: Kubernetes at AWS, started with kops utility
 - Kubernetes version: v1.10.6
 - Grafana v6.0.0-beta3 (19192fc)
 - Loki version=master-351b4c6 (deploy via Helm)
 - Promtail version=master-351b4c6 (deploy via Helm)

Loki and Grafana кun on different nodes

![image](https://user-images.githubusercontent.com/6937605/53226859-87e91980-368d-11e9-9e2c-9a9ba2aa78d0.png)

**Comment by wangxisea** [comment]
same issue here

**Comment by Kuqd** [comment]
How many replica of Loki do you have and how many discovered pods do you see for each?

I've spotted a bad selector in helm for services and I have a fix in my current branch.

Can you confirm if this is related?

**Comment by Shenderchuk** [comment]
The similar issue here:

Seems that Grafana can't proceed a query every single time, sometimes need to click several times to get the results.
[image](https://user-images.githubusercontent.com/1496260/61773746-13fa9b00-adfe-11e9-99d6-14d7489779bb.png)
![image](https://user-images.githubusercontent.com/1496260/61774019-ae5ade80-adfe-11e9-8a51-0080ae067149.png)

**Environment**:

Infrastructure: Kubernetes at AKS
Kubernetes version: v1.13.5
Grafana v6.1.4
Loki version=master-7deb02b (deployed via Helm)
Promtail version=master-7deb02b (deployed via Helm)

**Comment by Kuqd** [comment]
Grafana is timing out, the default timeout is 30s which might not be enough for you query yet (we're working on perf improvements), you can tweak this using https://grafana.com/docs/installation/configuration/#timeout

**Comment by KeTao** [comment]
No , you can't close the ticket .

NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
loki    loki            1               2021-07-20 16:46:17.314767554 +0800 CST deployed        loki-stack-2.4.1        v2.1.0     


t=2021-07-20T10:09:02+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/1/loki/api/v1/label status=502 remote_addr=127.0.0.1 time_ms=30016 size=0 referer=http://192.168.168.6:3000/datasources/edit/1/

**Comment by LinTechSo** [comment]
Hi. any updates?
