### ISSUE TITLE
LogQl aggregation operator to display unique users (for example)

### ISSUE THREAD

**Issue by Rom888** [grafana/loki#3495]
**Is your feature request related to a problem? Please describe.**
Unable to create LogQl query to display the number of UNIQUE users in the Grafana Worldmap panel.

**Describe the solution you'd like**
I have scrapped by Promtail nginx logs (example):
```
geoip_country_code="US" IP="52.15.212.33"
geoip_country_code="US" IP="52.15.212.33"
geoip_country_code="US" IP="52.15.212.1"
geoip_country_code="CA" IP="64.77.16.77"
geoip_country_code="CA" IP="64.77.16.77"
geoip_country_code="CA" IP="64.77.16.2"
```
This query returns NOT UNIQUE BY IP requests by country, and Grafana can show it on Worldmap panel:
```
sum by (geoip_country_code) (count_over_time({ http_host="example.com" }))
```
it returns:
```
US = 3
CA = 3
```
But no way to create Loki query (or using Loki+Grafana) to return UNIQUE user requests by IP and by country code. It should return:

```
US = 2
CA = 2
```

**Describe alternatives you've considered**
I tried to use Grafana Transform, but without success.
This query returns unique visitors count by IP, but it can't aggregate by country:
```
count (sum by (IP) (count_over_time({ http_host="example.com" })))
```
result = 4

**Comment by npordash** [comment]
Does this work for you?

```
count without (IP) (sum by (IP, geoip_country_code) (count_over_time({...})))
```

**Comment by Rom888** [comment]
@npordash , yes, this does!
Thank you very much!
