### ISSUE TITLE
log path not set correctly in promtail for k8s 1.10 and newer

### ISSUE THREAD

**Issue by woodsaj** [grafana/loki#35]
in k8s 1.10 the container log path was changed from `/var/log/pods/<UID>/<container>_0.log` to `/var/log/pods/<UID>/<container>/0.log`

https://github.com/kubernetes/kubernetes/issues/55905

**Comment by slim-bean** [comment]
@woodsaj I believe with changes in #331 that we could create a config `/var/log/pods/<UID>/**/*.log` which would match `/var/log/pods/<UID>/<container>_0.log` from k8 1.9 and older and also match `/var/log/pods/<UID>/<container>/0.log` for k8 1.10 and later?

**Comment by woodsaj** [comment]
`/var/log/pods/<UID>/**/*.log` wont work, as the target for each container will match the logs of every container in the pod. 

what we really want is something like `/var/log/pods/<UID>/<container>{_,/}*.log` . 
This works with shell expansion in bash,
```
anthony:~/go/src/github.com/grafana/loki$ ls -l ./tmp/foo{_,/}*.log
-rw-rw-r-- 1 anthony anthony 0 Feb 18 12:49 ./tmp/foo_0.log
-rw-rw-r-- 1 anthony anthony 0 Feb 18 12:44 ./tmp/foo/0.log
anthony:~/go/src/github.com/grafana/loki$ 
```
but doesnt work with promtail.
```
level=error ts=2019-02-18T04:53:12.328021379Z caller=filetargetmanager.go:173 msg="Failed to create target" key="{job=\"varlogs\"}" error="filetarget.sync: filetarget.sync.filepath.Glob: syntax error in pattern"
```

**Comment by tomwilkie** [comment]
Do keep in mind we can have multiple scrape configs, one the matches `/var/log/pods/<UID>/<container>_*.log` and one for `/var/log/pods/<UID>/<container>/*.log`.

**Comment by Serrvosky** [comment]
I leave here my final scrape config, for kubernetes v.1.14. It's working 

```
- source_labels: [__meta_kubernetes_pod_node_name]
          target_label: __path__
          replacement: '/var/log/pods/*/$1/*.log'
```

**Comment by steven-sheehy** [comment]
@woodsaj @slim-bean I believe this can be closed now
