### ISSUE TITLE
Loki Imported logs not visible

### ISSUE THREAD

**Issue by shrivastavshubham34** [grafana/loki#3500]
**Tried to copy chunks folder from older Loki machine(v1.4.1) to latest one with different storage, but the older data is not visible in logs**

1. Deployed Loki-stack Helm Chart (loki-0.28.1) on EKS with EBS volume enabled. 
2. Deployed new loki-stack given here using EFS volumes [https://github.com/grafana/helm-charts/tree/main/charts/loki-stack](url) 
3. Copied the chunks folder contents from the old volume to the new volume (contents inside /loki/chunks )

![image](https://user-images.githubusercontent.com/13406071/111413579-bafb0d00-869b-11eb-8b7f-212f7c44f638.png)

How do I make sure old logs can be viewed

**Comment by the-maldridge** [comment]
I'm also interested in this, as due to the _interesting_ and unique design choices alluded to in #1827 I'm now in a position where I have all the chunk data, but not the matched indexes that go with it.  Surely there is some way to re-ingest all the chunks and reconstruct indexes for it.

**Comment by shrivastavshubham34** [comment]
Please don't stale it, I still need to figure this out

**Comment by sauhrabh** [comment]
Using EFS instead of EBS. Interested in how EBS works out with Loki.
