### ISSUE TITLE
Support Alicloud OSS

### ISSUE THREAD

**Issue by SecretSun** [grafana/loki#3504]
We hope to support Alicloud OSS. Do you have any support plan.
In summary, the use of object storage, from the cost and complexity of operation and maintenance, are greatly improved

**Comment by adityacs** [comment]
@SecretSun Any Object Storage which supports S3 compatible APIs can be configured with Loki. You have to just configure the specific endpoint. Looking at this https://www.alibabacloud.com/help/doc-detail/64919.htm, they do support S3 APIs

FYR: https://github.com/grafana/loki/blob/master/docs/sources/storage/_index.md#notable-mentions

**Comment by SecretSun** [comment]
@adityacs 
Can you help us to provide a list of all the APIs that use S3 instead Or a snippet of code.
Let's see if we can help Support Alicloud OSS.

**Comment by xingren23** [comment]
> @adityacs
> Can you help us to provide a list of all the APIs that use S3 instead Or a snippet of code？
> Let's see if we can help Support Alicloud OSS.

if you want use alicloud oss native api,  you could implement cortex chunk api (ObjectClient) that loki used to access bucket object, and update cortex version in loki. 
so alicloud as s3 compatible oss is well
