### ISSUE TITLE
CORS issue on firing the Loki push API from React app

### ISSUE THREAD

**Issue by rsharma5577** [grafana/loki#3508]
Description:
I want to push the logs with help of /loki/api/v1/push  API from React app.
But when the API is fired, it gives the CORS error

**To Reproduce**
1. Started Loki (SHA or version)
2. fired the query from inside the react app

![image](https://user-images.githubusercontent.com/80900098/111631243-2dddc280-8819-11eb-8d64-7cbc58d7d405.png)

**Comment by owen-d** [comment]
I don't think theres a single "correct" CORS policy that Loki should use. Rather, I can see it being dependent on each deployment. Therefore, I think adding CORS policies should be independent of the Loki repository and should instead be set in a reverse proxy, etc.

**Comment by ukolovda** [comment]
@rsharma5577 ,  AFAIK you should set CORS headers in your origin application, not in Loki.

**Comment by navneetgarggate6** [comment]
@rsharma5577 are you able to fix it?
