### ISSUE TITLE
Improve query-frontend json unmarshalling.

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#3511]
@slim-bean just found out some queries with huge labelset on the query-frontend can OOM.

We should dig into this.

![image](https://user-images.githubusercontent.com/1053421/111659657-cb1e0400-87e3-11eb-8014-0e640ffad08c.png)
![image](https://user-images.githubusercontent.com/1053421/111659723-d709c600-87e3-11eb-8f76-ea89a73d15ff.png)

See if we can do better allocation wise. or find a way to not crash when log line are huge.

**Comment by liguozhong** [comment]
![image](https://user-images.githubusercontent.com/9583245/124495959-61098900-ddeb-11eb-8fc4-69efb82aec1f.png)
