### ISSUE TITLE
Negative line filter regex excludes all log lines when using empty string

### ISSUE THREAD

**Issue by Mario-Hofstaetter** [grafana/loki#3523]
**Describe the bug**

When using a [line filter expression](https://grafana.com/docs/loki/latest/logql/#line-filter-expression) with the operator `!~: Log line does not match regular expression.` in LogQL, 

**an empty string will execluded all log lines.**
The regex `""` does not match anything, so the LogQL 

```text
{label="foobar"} !~ ""
```

**should not exclude any lines from stream `foobar`**, but it excludes every line.
This is needed to use a empty grafana dashboard variable (see below).

**To Reproduce**

1. Use Loki 2.2.0 containing some log lines you can query
2. Using `logcli` query e.g.:

```text
logcli query '{job="yourlabel"} !~ "foobarxxx"'
```

This should return _some_ logs for you. Then query:

```text
logcli query '{job="yourlabel"} !~ ""'
```

For me this does not return any logs  ❌ . The behavior is the same from within grafana.

In Windows powershell I have to enter this (triple double quote needed for escaping ):

```
.\logcli.exe query '{job="""mylabel"""} !~ """"""'
```

**Expected behavior**

The Expression `!~ ""` should not exclude any log lines, this is the case with prometheus promql and negative regex matching prometheus labels.

## Update

Ok I realized the difference in behavior of the operator is probably the real issue here.
In prometheus, the query 

```text
my_counter_total {foo !~ "ipsum"}
``` 

does NOT exclude metric `my_counter_total {foo="lorem ipsum"}`, for an exclusion, e.g. `{foo !~ ".*ipsum"}` is needed.

But in LogQL
```text
{foo = "bar"} !~ "ipsum"
``` 
will exclude all log lines containing `ipsum`, so I guess internally the filter value is surrounded by regex wildcards, and this is not something that can be changed without breaking things...

Would an exception for empty string be possible?

**WHY this is needed ?**

I created a Grafana dashboard, with a Dashboard variable of type `Textbox` to let the user exclude loglines matching the entered text (RegExp), and the same with an include variable.

It is not possible to leave the Exclude Variable empty, because it will exclude everything.

LogQL in Logs Panel:
```text
{foo="bar"} |~ ".*$IncludeText.*" !~ "$ExcludeText"
```

When using Prometheus, this works as expected, leaving the variable `$ExcludeText` EMPTY will not exclude metrics labels.

**Workaround in Grafana**

Setting a default like `<PlaceHolder>` for the dashboard variable ensures the exclude filter does not excluded everything, but that ain't pretty.

**Environment:**
 - Windows Server 2016, `loki-windows-amd64.exe` binary release `v2.2.0`
 - logcli `v2.2.0`
 - Grafana `Grafana v7.4.3 (010f20c1c8)`

**Comment by Mario-Hofstaetter** [comment]
Hey stale bot, seems this ticket did not gain any traction, or my description was unclear, or its just not important enough.
Keep it open though. :-)

**Comment by darxriggs** [comment]
Please keep this open.

**Comment by acefed** [comment]
This worked for me as a workaround in Loki LogQL queries, without a visible `<PlaceHolder>` in the text input on the dashboard:
`!~ '""|$ExcludeText'`
... a regex exclude for (empty string "" OR variable $ExcludeText).

Adding case insensitivity could also help in some use cases: 
`!~ '(?i)""|$ExcludeText'`

**Comment by n9** [comment]
@acefed I do not understand why `""` should match an empty string. I think it will match `'""'` (a string with two quotes).

**Comment by Alwinius** [comment]
This fixes the problem as long as the log message does not contain (two double quotes) because otherwise it will be filtered on empty variable. If this is really the workaround, something more uncommon than (two double quotes) should be selected
