### ISSUE TITLE
A stop job is running for Service for promtail on reboot/shutdown

### ISSUE THREAD

**Issue by inginheiiro** [grafana/loki#3531]
Hi,
I have ubuntu 20.04 with loki 2.2 and promtail installed as services.

When the server reboots, the promtail service waits for 1m.30s ...

Anyone came across with this?

Promtail.yml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /data/loki/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log

![image](https://user-images.githubusercontent.com/19993596/112294693-0197cb00-8c8b-11eb-8c7f-1c3f1670265e.png)

**Comment by rmadrona** [comment]
I have same issue on ubuntu 20.04 LTS

**Comment by jeschkies** [comment]
How did you define the systemd unit? I don't think we have an official version.
