### ISSUE TITLE
can we use loki for frontend logging ?

### ISSUE THREAD

**Issue by navneetgarggate6** [grafana/loki#3545]
Please ask questions you have in the mailing list: https://groups.google.com/forum/#!forum/lokiproject

Or join our #loki slack channel at http://slack.raintank.io/
I want to log my react application log and monitor what can we done using loki?

**Comment by cyriltovena** [comment]
Yes the API supports json.

**Comment by navneetgarggate6** [comment]
Ok thanks, is there any documentation or example for the same ?

**Comment by cyriltovena** [comment]
https://grafana.com/docs/loki/latest/api/

https://www.npmjs.com/package/winston-loki

**Comment by navneetgarggate6** [comment]
Thanks

**Comment by navneetgarggate6** [comment]
I stuck with cors can you please help me on that?

**Comment by sheenarbw** [comment]
> https://grafana.com/docs/loki/latest/api/
> 
> https://www.npmjs.com/package/winston-loki

It looks like Winston isn't quite ready for frontend logging: https://github.com/winstonjs/winston/issues/287
