### ISSUE TITLE
Serverside Log Transformation

### ISSUE THREAD

**Issue by u-anna** [grafana/loki#3547]
**Is your feature request related to a problem? Please describe.**
We currently have more than 4000 clients sending us logs each day. These logs are generated through different applications, some of them with different formats.
To make life easy on ourselves we want the logs to be identical or at least as close to identical as possible. For this we want to transform the logs.

At the moment promtail supports the transformation of logs however, any change to the transformation needs to be rolled out to all of the clients using promtail.
Since, as we all know, not everyone keeps their software up-to-date, changing the transformations on every client is a long and tedious process.

**Describe the solution you'd like**
We would like to be able to transform the logs send by clients before they are persisted through loki. So basically a serverside transformation instead of a client side.

**Describe alternatives you've considered**
As an alternative we are currently still running filebeat on the clients and transforming the data through logstash. Which works fine but we would prefer using promtail.

**Additional context**

**Comment by cyriltovena** [comment]
What about using [Promtail API](https://grafana.com/docs/loki/latest/clients/promtail/configuration/#loki_push_api). You need to run a set of promtail configured to expose the Push API and send to your central Loki.

Then ask all your customers to send to your set of Promtail.
