### ISSUE TITLE
Default values for query API are not documented

### ISSUE THREAD

**Issue by Sniliev** [grafana/loki#356]
**Describe the bug**
Querying loki via the http API I only get results that are newer than an hour. Older results are not shown.

**To Reproduce**
1. Started loki ( 5207751cbdadd821aaf9999ee052ce25cc19d305 ) with the following command: ` ./loki -config.file=./cmd/loki/loki-local-config.yaml`
2. Started promtail ( 5207751cbdadd821aaf9999ee052ce25cc19d305 ) to tail a custom file in my user's home directory directory with the following command: ``./promtail -config.file=./cmd/promtail/promtail-local-config.yaml``
3. Query:  I'm running the following: 
`curl 'http://localhost:3100/api/prom/query?query=%7B__filename__="/home/user/file.log"%7D&limit=3'`

**Expected behavior**
Get the last three entries in the `/home/user/file.log` file, regardless of how old they are.

**Environment:**
 - Infrastructure: [kvm]
 - Deployment tool: Built from source as described here: https://github.com/grafana/loki/blob/master/production/README.md#build-and-run-from-source

**Screenshots, promtail config, or terminal output**
I'm using the default configs from the repo: 
`/src/github.com/grafana/loki/cmd/loki/loki-local-config.yaml`
`/src/github.com/grafana/loki/cmd/promtail/promtail-local-config.yaml`

The only change I've made is to the  `promtail-local-config.yaml` file. Changed \_\_path\_\_ to point to the testing log file.

Currently there is no ouptut of the loki command when executing the query. A few commits back ( unfortunately I don't remembar which commit exactly I was on) I used to get this error: 
`runtime error: invalid memory address or nil pointer dereference`

**Comment by Sniliev** [comment]
Found that this is due to default value for the start parameter of the query.

**Comment by sleleko** [comment]
Hello @Sniliev . Thanks for you example for GET query. But how push new data ?
I,m will try 
curl -i -H "Content-type: application/json" \                                               
-X POST --data '{
  "streams": [
    {                                                                          
      "labels": "{source=\"JSON\",job=\"simpleJsonJob\", host=\"SimpleHost\"}",    
      "entries": [{ "timestamp": "1554887676", "line": "TEST!" }]                  
    }
  ]
}' "loki:3100/api/prom/push"
But resive only
HTTP/1.1 204 No Content
Date: Wed, 10 Apr 2019 09:38:57 GMT

And in Grafana can see only lables..

**Comment by daixiang0** [comment]
> "entries": [{ "timestamp": "1554887676", "line": "TEST!" }]
you need use ts like UTC timestamp(2019-02-11T13:12:06.801064Z)
