### ISSUE TITLE
how to config no restriction for lines of loki return

### ISSUE THREAD

**Issue by yaofly2019** [grafana/loki#3560]
loki grafana only return 1000 lines per query, how can I return more lines ?

![image](https://user-images.githubusercontent.com/58969363/113088394-112d8b80-9218-11eb-8c12-f1c7bbaa63f3.png)

Here is the configuration for loki:

auth_enabled: false
chunk_store_config:
  max_look_back_period: 0s
compactor:
  shared_store: filesystem
  working_directory: /data/loki/boltdb-shipper-compactor
ingester:
  chunk_block_size: 262144
  chunk_idle_period: 3m
  chunk_retain_period: 1m
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  max_transfer_retries: 0
limits_config:
  enforce_metric_name: false
  ingestion_burst_size_mb: 64
  ingestion_rate_mb: 32
  max_entries_limit_per_query: 0
  reject_old_samples: true
  reject_old_samples_max_age: 168h

**Comment by caleb15** [comment]
see https://github.com/grafana/loki/issues/1917

**Comment by yaofly2019** [comment]
> see #1917

thanks!
