### ISSUE TITLE
Json filter 64 bit integer truncated

### ISSUE THREAD

**Issue by stevenbrookes** [grafana/loki#3565]
**Describe the bug**

When using the json filter on a log line that contains 64bit integers, the derived labels are incorrect.  It looks likely they have been converted to 64bit floats and truncated.

**To Reproduce**
Create a log line containing a 64bit integer   { "id": 676996931091701602 }
Query in Grafana   file.log | json
See the Detected field    id  676996931091701600

**Expected behavior**
The detected field should match the value of the original field

**Environment:**
2021-03-31 16:24:53
loki_build_info
HEAD
go1.15.3
localhost:3100
loki
a27c7991
2.2.0
1

**Screenshots, Promtail config, or terminal output**
Example screenshot

![image](https://user-images.githubusercontent.com/43211757/113169721-c6bf0580-923d-11eb-8c09-b8c9212c2ae6.png)

**Comment by cyriltovena** [comment]
Sounds like a Grafana issue.

/cc @ivanahuckova  ? Should we transfer the issue ?

**Comment by stevenbrookes** [comment]
My impression was that was caused by the json parser in Loki. A lot if json parsers seem to have a limitation on converting 64 bit integer to float as JavaScript has no 64 bit integer support. But that’s not a limitation of json.

I can try a logcli query to prove if the issue is in Loki or Grafana if that will help isolate it more.

**Comment by ivanahuckova** [comment]
@stevenbrookes Yes, could you please try logcli query to see if the issue is in Loki or Grafana. If it is only Grafana issue, we can transfer this to Grafana repo.
