### ISSUE TITLE
Auto detect log format

### ISSUE THREAD

**Issue by steven-sheehy** [grafana/loki#357]
**Is your feature request related to a problem? Please describe.**
I ran into issue #260 when trying out Loki via the Helm chart and using containerd. Logs would not scrape and that error showed up repeatedly in the logs. After realizing containerd's logs were not in JSON format, I set the `entry_parser: raw` in the promtail scrape config and logs started to appear.

**Describe the solution you'd like**
I would like Loki to automatically detect the log line format and choose the correct `EntryParser` without user input. It can be as simple as try each parser until one is successful, then use that parser for the rest of that log file.

**Describe alternatives you've considered**
Helm chart should allow promtail configmap to be configurable, so at least it can be done declaratively via helm.

**Additional context**

**Comment by daixiang0** [comment]
close this since duplicate as #380
