### ISSUE TITLE
Ascending by time

### ISSUE THREAD

**Issue by yaofly2019** [grafana/loki#3574]
how to query ascending by time，not desc

![image](https://user-images.githubusercontent.com/58969363/113396346-fbfa5d80-93cd-11eb-82e3-082db9daf500.png)

**Comment by james-callahan** [comment]
On the right click "Flip results order"
![image](https://user-images.githubusercontent.com/35791147/114268784-520e7700-9a46-11eb-92b5-a9d1f07fb6a6.png)
