### ISSUE TITLE
Support CRI log format

### ISSUE THREAD

**Issue by steven-sheehy** [grafana/loki#358]
**Is your feature request related to a problem? Please describe.**
Containerd does not support JSON format, so after setting promtail's `entry_parser: raw` to make it work, I noticed that there were duplicate timestamps in the loki output. Containerd writes its logs in the [CRI format](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/kubelet-cri-logging.md) `<RFC3339Nano> <stream> <flags> <app output>\n`.  Other CRI runtimes like CRI-O may also support this same format, but I am not sure. Example log:

`2019-02-23T05:30:45.598142519Z stdout F INFO  2019-02-23 05:30:45,596 [main] c.f.e.w.i.InventoryApplication: No active profile set`

When I view the logs in Grafana, containerd's timestamp and other metadata isn't removed and the loki timestamp differs slightly from the containerd timestamp.

**Describe the solution you'd like**
promtail should be able to retrieve logs from containerd with the correct timestamp and remove all other data except the application stdout.

**Describe alternatives you've considered**
Instead of a containerd-specific solution, implement a generic regex-based`EntryParser` similar to Fluent Bit's [regex parser](https://docs.fluentbit.io/manual/parser/regular_expression).

Or, instead of reading log files integrate with containerd directly via their API. This is the approach containerd's dev recommended via slack.

**Additional context**
In Grafana, if I enable all options I end up with 4 date/times being printed on screen, making it unuseable:
1. Grafana timestamp
2. Grafana local time
3. Containerd timestamp
4. Application timestamp

![screen shot 2019-02-26 at 10 46 47](https://user-images.githubusercontent.com/17552371/53430495-3ce44480-39b4-11e9-9687-a0332740b990.png)

This issue deals with only item 3 above.

Containerd is the underlying runtime of Docker 18.09+, the runtime used in [IBM Cloud](https://www.ibm.com/blogs/bluemix/2019/01/ibm-cloud-kubernetes-service-supports-containerd/), Pivotal Cloud Foundry and soon to be [GKE and Azure](https://github.com/containerd/containerd/blob/master/ADOPTERS.md) so it's important that it is supported.

**Comment by steven-sheehy** [comment]
I've confirmed with both containerd and CRI-O developers that they implement the [CRI log format](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/kubelet-cri-logging.md) and that the format is stable. Updating title to reflect that.

**Comment by NickLarsenNZ** [comment]
> I've confirmed with both containerd and CRI-O developers that they implement the [CRI log format](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/kubelet-cri-logging.md?rgh-link-date=2019-03-04T16%3A56%3A28Z) and that the format is stable. Updating title to reflect that.

For anyone stumbling on this issue, the archived link is: <https://github.com/kubernetes/design-proposals-archive/blob/main/node/kubelet-cri-logging.md>
