### ISSUE TITLE
Improve UX of (or simply remove) "Common labels" from LogCLI

### ISSUE THREAD

**Issue by samjewell** [grafana/loki#3581]
**Problem description**

I'm piping output from `logcli` into other Unix tools at the command-line (specifically [within a Python script](https://github.com/grafana/deployment_tools/blob/master/docker/bigquery-sync/loki/loki-tap.py#L24-L36)). Downstream (down-pipe?) I want to manipulate **all** labels that I have selected/renamed in the `logcli` query via `logfmt` and `label_format`. But unfortunately those labels I am renaming are not present in the line-by-line output on STDOUT, because they are common across all records! They're being omitted from STDOUT and moved into the "Common labels:" output on STDERR (where they aren't accessible to other tools that I'm piping STDOUT into).

**Some options for solution I'd like to see**
- Docs
   - Make the docs more explicit - highlight this functionality more prominently. It's easy to miss the "Common labels" output on STDERR - especially if looking at 30 records on screen, or (worse) when piping directly into `jq`
   - From @cyriltovena on [Slack](https://raintank-corp.slack.com/archives/C9T1FLN9K/p1617096921379300?thread_ts=1617093659.373100&cid=C9T1FLN9K): "`-o jsonl` doc is lying it also uses common labels"
- UX
   - Possibly remove the "Common labels" functionality completely. This may be a breaking change, but it seems the simplest solution to me at the moment. I think it was added by @tomwilkie in the very early days of this project here: [`687cb06` (#7)](https://github.com/grafana/loki/pull/7/commits/687cb0633532e7b326727cd3ec31b1e31735c8e9), and doesn't seem to have been added in response to any external or community requests.
   - Add a CLI flag to allow the "Common labels" functionality to be switched off by the user.
   - When renaming labels via `label_format` we could consider always adding these labels to the log lines themselves, rather than adding them to "Common labels". For me at least I was using `label_format` because I wanted to see those labels in STDOUT.

**Alternatives I've considered**
We (@jeschkies and I) briefly considered parsing STDERR as well as STDOUT, but we wanted to see what others thought about this issue first.

**Additional context**
Initial [Slack discussion](https://raintank-corp.slack.com/archives/C9T1FLN9K/p1617096453376700?thread_ts=1617093659.373100&cid=C9T1FLN9K) on Grafana internal

The command I've been running is this:
```
logcli -o jsonl query '{name="cortex-gw", namespace="prod"} |= "eventType=bi" | logfmt | label_format user_agent=userAgent,user_agent_group=userAgentGroup,ns=namespace' | jq .
```

And specifically the `ns=namespace` is coming out on STDERR (when I remove the `jq` downstream pipe):
![Screenshot 2021-04-06 at 13 47 42](https://user-images.githubusercontent.com/2903904/113712976-b2b45180-96de-11eb-9da3-7d60afc1d090.png)

**Comment by cyriltovena** [comment]
I think the `common labels` have been added just for simplicity and it does make sense that for users that wants to parse data after to add an option to disable it.

I also think we should not have common labels when using `-o jsonl`. I really expect only json in that case a bit like `-o raw`.

**Comment by jeschkies** [comment]
@cyriltovena should this be a breaking change then or on to opt-in? I guess `-o jsonl` should just include the common labels by default. that would not be a breaking change. Removing them from `stderr` would be another step via an option which is not a breaking change either.

**Comment by cyriltovena** [comment]
I'm ok with breaking change,  I don't think common labels is useful for json output.

This is a versioned CLI so people can choose to upgrade or not and I don't think anyone rely on this feature.

**Comment by samjewell** [comment]
Also when I use `--since 0.5s` in this query, I'm getting the "Common labels:" printed twice over! The second time there are no records that follow the "Common labels:" message.
Maybe that problem will completely go away if we make the other improvements we've discussed here, or maybe not 🤔
