### ISSUE TITLE
Cannot bring up Loki with Docker Compose on current Debian system

### ISSUE THREAD

**Issue by bobstrecansky-mc** [grafana/loki#359]
**Describe the bug**
I went to try out loki after learning about it at grafanacon.  I git cloned the repo and attempted to run a `docker-compose up` as prescribed in the documentation:
 https://github.com/grafana/loki/blob/master/production/README.md#run-locally-using-docker

**To Reproduce**
On debian version 9.8:
1.) git clone `grafana/loki`
2.) apt install docker-compose
3.) Attempt to run a `docker-compose pull`

**Expected behavior**
Have loki and promtail executing on the test host in docker containers

**Environment:**
 - Infrastructure: virtual machine
 - Deployment tool: docker-compose

**Screenshots, promtail config, or terminal output**
```root@li796-74:~# apt install docker-compose
Reading package lists... Done
Building dependency tree
Reading state information... Done
docker-compose is already the newest version (1.8.0-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@testhost:~# git clone https://github.com/grafana/loki.git
Cloning into 'loki'...
remote: Enumerating objects: 28, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 10099 (delta 2), reused 3 (delta 0), pack-reused 10071
Receiving objects: 100% (10099/10099), 11.37 MiB | 13.33 MiB/s, done.
Resolving deltas: 100% (4566/4566), done.
root@testhost:~# cd loki/production/
root@testhost:~/loki/production# docker-compose pull
ERROR: Version in "./docker-compose.yaml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/```

**Comment by smlx** [comment]
Hi, you should install the docker-compose version from Debian backports - it's much newer.

https://backports.debian.org/Instructions/

**Comment by bobstrecansky** [comment]
Agreed that is possible.  I'd think one should be able to install loki on the newest version of Debian / stock docker-compose without any additional apt configuration?  I would think that would be a barrier for entry for adoption.  Happy to close this issue if y'all think it's unwarranted.

**Comment by kiney** [comment]
You can also install current docker-compose with pip.
@bobstrecansky This might actually be a valid compose 2 file, have you tried replacing the version "3" with "2" in the first line?
But i don't think it really makes sense to actively support ancient versions of docker or docker-compose...

**Comment by bobstrecansky-mc** [comment]
Good enough for me, I just wanted to let y'all know that it didn't work for my use case in the current capacity.  I did validate this works with the backports version of docker-compose.  Going to close this issue, as I feel it has resolution steps should others run into this same issue.
