### ISSUE TITLE
Docs: The chunk_retain_period comment is confusing

### ISSUE THREAD

**Issue by klausenbusk** [grafana/loki#3598]
The local and docker config contains this line (added in https://github.com/grafana/loki/commit/af6e8cb6c9a02be44a978c4933fb17778cb401b7):
https://github.com/grafana/loki/blob/8012362674568379a3871ff8c4a2bfd1ddba7ad1/cmd/loki/loki-local-config.yaml#L21

Five days later the fifocache was enabled per default: https://github.com/grafana/loki/commit/f60554ce91e7c00365351d7163c30da6bf0171e5 and it defaults to `index_cache_validity - 1minute` (4 min):
https://github.com/grafana/loki/blob/46eff3c12cc0170c21905b783c90e8a1653a4b83/pkg/loki/modules.go#L307

`chunk_retain_period` should be bumped to 4min to avoid this confusion.

**Comment by klausenbusk** [comment]
..

**Comment by klausenbusk** [comment]
Still relevant

**Comment by klausenbusk** [comment]
.

**Comment by klausenbusk** [comment]
...

**Comment by owen-d** [comment]
Hey, these are actually separate configurations. Using the `chunk_retain_period > 0` is helpful when using an external index cache (memcached, etc). In that case, there can be a period after the ingesters have flushed data to storage which makes the index-cache stale. Setting the retain period to slightly larger than the cache TTL in this case will ensure that the ingesters will still serve this data until the cache TTL expires and then repopulates with the data.
