### ISSUE TITLE
Is Promtrail needed when installing the Loki Docker driver and changing the daemon.json?

### ISSUE THREAD

**Issue by Muddz** [grafana/loki#3604]
I have installed the Loki Docker Driver and changed the `daemon.json` as suggested in the readme and I have Loki and Grafana running from the same docker-compose file and I have access to the Grafana frontend and setup Loki as the data source, where it also says it has found labels. But I can't find any logs or labels. Is it simply because Promtrail is needed?

**Comment by dannykopping** [comment]
Please refrain from asking questions in GitHub Issues.

We have a [Community forum](https://community.grafana.com/c/grafana-loki/41), [#loki in slack.grafana.com](https://slack.grafana.com/) and our [mailing list](https://groups.google.com/forum/#!forum/lokiproject).
