### ISSUE TITLE
Loki can't connect to Cassandra

### ISSUE THREAD

**Issue by Makkinwa** [grafana/loki#3607]
**Describe the bug**
I create a cassandra and loki instances in kubernetes, I wanted to use cassandra as a storage for loki's chunks and indexes
When I'm trying to start loki with following loki.yaml config below, Loki just crashes with no useful info in logs. 
I tried to start loki many times but there is no tables in keyspace "test" in cassandra. So loki didn't connect to cassandra

---------- loki.yaml
auth_enabled: false
chunk_store_config:
  max_look_back_period: 0s
ingester:
  chunk_block_size: 262144
  chunk_idle_period: 3m
  chunk_retain_period: 1m
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  max_transfer_retries: 0
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
schema_config:
  configs:
    - from: 2021-07-01
      store: cassandra
      object_store: cassandra
      schema: v11
      index:
        prefix: index_
        period: 168h
      chunks:
        prefix: chunk_
        period: 168h
server:
  http_listen_port: 3100
storage_config:
  cassandra:
    addresses: cassandra.monitoring.svc
    keyspace: test
    auth: false
table_manager:
  retention_deletes_enabled: false
  retention_period: 0s

--------

Command and logs I get from loki:
/ $ loki -config.file=/etc/loki/loki.yaml  -log.level=debug
level=info ts=2021-04-14T08:35:01.84651284Z caller=main.go:131 msg="Starting Loki" version="(version=master-e8cce09, branch=master, revision=e8cce09d)"
level=info ts=2021-04-14T08:35:01.84719383Z caller=server.go:229 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2021-04-14T08:35:01.847304039Z caller=modules.go:467 msg="RulerStorage is not configured in single binary mode and will not be started."

**To Reproduce**
1. Started Loki (loki, version master-e8cce09 (branch: master, revision: e8cce09d)
  build user:       root@e945d23b3b42
  build date:       2021-02-01T14:02:12Z
  go version:       go1.15.3
  platform:         linux/amd64
)
2. Cassandra version: 4.0-beta4. I used default cassandra config.

**Expected behavior**
I want loki to store chunks and indexes in cassandra

**Environment:**
 - Infrastructure: kubernetes Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:39:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**Comment by jtyr** [comment]
How did you install Cassandra? Are you sure there is no authentication required? Please can you try to connect to Cassandra via `gcqlsh` using this pod?

```shell
kubectl run test -it --rm --image jtyr/gcqlsh
```

Then try to connect to your Cassandra:

```shell
# If it doesn't require authentication
gcqlsh -host cassandra.monitoring.svc -k test
# If it requires authentication
gcqlsh -host cassandra.monitoring.svc -username cassandra -password yourpassword -k test
```

Once you are connected, you can check if any tables are created there (run as `gcqlsh` command):

```sql
desc tables;
```

Once you can run this test successfully, Loki must be configured accordingly and then it should be able to connect.
