### ISSUE TITLE
Allow more configurable Loki client

### ISSUE THREAD

**Issue by owen-d** [grafana/loki#3608]
Grafana would like to have the ability to configure more in the Loki client than is currently available here: https://github.com/grafana/grafana/blob/b3ac63dad7738ffad96b545116bb516ac94e9385/pkg/tsdb/loki/loki.go#L48-L52

Perhaps we can add a constructor passing an `*http.Client`.

@marefr does that sound good?

**Comment by marefr** [comment]
Sounds good. Either a `*http.Client` or a `http.RoundTripper` would be nice. `http.RoundTripper` is the transport of `*http.Client` and is normally what you would override to implement outgoing HTTP client request middlewares.
