### ISSUE TITLE
Loki ruler not evaluting rules (err wrong chunk metadata)

### ISSUE THREAD

**Issue by gmintoco** [grafana/loki#3609]
**Describe the bug**
No alerts are received for evaluated rules. Expressions evaluate properly in Grafana but the ruler returns `err="wrong chunk metadata"`
 
**To Reproduce**
1. Started Loki v2.2.1
2. Started Promtail v2.2.1
3. This is the error message from the ruler 

          level=warn ts=2021-04-15T05:12:44.790561185Z caller=manager.go:598 user=..data group=veeam_backup_warning_error msg="Evaluating rule failed" rule="alert: VeeamBackupError\nexpr: sum by(VEEAM_MIB__backupJobName,location,entity,VEEAM_MIB__backupJobResult,VEEAM_MIB__backupJobName)(count_over_time({app=\"snmptrapd\"}\n | json | ( ( ( __error__!=\"JSONParserErr\" , SNMPv2_MIB__snmpTrapEnterprise_0=\"VEEAM-MIB::traps\"\n ) , SNMPv2_MIB__snmpTrapOID_0=\"VEEAM-MIB::onBackupJobCompleted\" ) , VEEAM_MIB__backupJobResult=\"Failed\"\n )[12h]))\nlabels:\n email_contact: ops@vlahvwd.com\n gitlab_project: fake-support\n severity: high\n slack_channel: fake-slack-alert\nannotations:\n description: Backup {{ $labels.VEEAM_MIB__backupJobResult | toLower }} for {{ $labels.VEEAM_MIB__backupJobName\n }} on {{ $labels.location }}. This could be caused by a number off issues. Start\n by checking the Veeam logs `{{ $labels.location }}`.\n gitlab_incident_markdown: |\n /label ~\\\"Fake\\\" ~\\\"Incident\\\" ~\\\"Loki\\\" ~\\\"Backup\\\" ~\\\"Fake\\\"\\n Veeam backup failed for {{ $labels.VEEAM_MIB__backupJobName }} on {{ $labels.location }}\n observability_url: https://grafana.blahblah.org/explore?orgId=1&left=%5B%22now-24h%22,%22now%22,%22Loki%20Global%22,%7B%22exemplar%22:true,%22expr%22:%22sum%20by%20(VEEAM_MIB__backupJobName,%20location,%20entity,%20%5CrVEEAM_MIB__backupJobResult,%20VEEAM_MIB__backupJobName)%20(count_over_time(%7Bapp%3D%5C%22snmptrapd%5C%22%7D%20%7C%20json%20%7C%20__error__!%3D%5C%22JSONParserErr%5C%22%20and%20SNMPv2_MIB__snmpTrapEnterprise_0%3D%5C%22VEEAM-MIB::traps%5C%22%20and%20SNMPv2_MIB__snmpTrapOID_0%3D%5C%22VEEAM-MIB::onBackupJobCompleted%5C%22%20%5B12h%5D)%20)%22,%22instant%22:true,%22range%22:false%7D%5D\n runbook_url: https://docs.google.com/document/d/kjhawed/edit#bookmark=id.t1a1tz1ryz8f\n summary: Backup {{ $labels.VEEAM_MIB__backupJobName }} error on {{ $labels.location\n }}\n`" err="wrong chunk metadata"

4. This is the expression. Which returns the expected result in grafana:
                           
        sum by (VEEAM_MIB__backupJobName, location, entity, VEEAM_MIB__backupJobResult, VEEAM_MIB__backupJobName) 
            (
            count_over_time(
            {app="snmptrapd"} | json | __error__!="JSONParserErr" and SNMPv2_MIB__snmpTrapEnterprise_0="VEEAM-MIB::traps" and SNMPv2_MIB__snmpTrapOID_0="VEEAM-MIB::onBackupJobCompleted" and VEEAM_MIB__backupJobResult="Warning" [12h]
             )
            )

5. This is the loki config:
          
         auth_enabled: false
        
        server:
          http_listen_port: 3100
          # default gRPC port 9095
          grpc_server_max_recv_msg_size: 8388608
        
        query_range:
          # make queries more cache-able by aligning them with their step intervals
          align_queries_with_step: true
          max_retries: 5
          # parallelize queries in 15min intervals
          split_queries_by_interval: 15m
          cache_results: true
        
          results_cache:
            cache:
              # We're going to use the in-process "FIFO" cache
              enable_fifocache: true
              fifocache:
                max_size_bytes: 1024
                validity: 24h
        
        distributor:
          ring:
            kvstore:
              store: memberlist
        
        ingester:
          lifecycler:
            ring:
              kvstore:
                store: memberlist
              replication_factor: 1
            final_sleep: 0s
          chunk_idle_period: 5m
          chunk_retain_period: 30s
        
        memberlist:
          abort_if_cluster_join_fails: false
        
          # Expose this port on all distributor, ingester
          # and querier replicas.
          bind_port: 7946
        
          # You can use a headless k8s service for all distributor,
          # ingester and querier components.
          join_members:
          - loki-global-prod-gossip.loki-global.svc.cluster.local:7946
        
          max_join_backoff: 1m
          max_join_retries: 10
          min_join_backoff: 1s
        
        schema_config:
          configs:
            - from: 2018-04-15
              store: boltdb-shipper
              object_store: gcs
              schema: v11
              index:
                prefix: loki_index_
                period: 24h
        
        storage_config:
         gcs:
           bucket_name: loki-global-prod-w3uijdfwcr
         boltdb_shipper:
            active_index_directory: /data/loki/index
            shared_store: gcs
            cache_location: /data/loki/boltdb-cache
        
        chunk_store_config:
          max_look_back_period: 672h
        
        table_manager:
          retention_deletes_enabled: true
          retention_period: 672h
        
        compactor:
          shared_store: gcs
        
        limits_config:
          enforce_metric_name: false
          max_cache_freshness_per_query: '10m'
          reject_old_samples: true
          reject_old_samples_max_age: 168h
          max_query_parallelism: 16
        
        frontend:
          log_queries_longer_than: 5s
          compress_responses: true
        
        frontend_worker:
          frontend_address: loki-global-prod-query-frontend-discovery.loki-global.svc.cluster.local:9095
          grpc_client_config:
                max_send_msg_size: 1.048576e+08
          parallelism: 2
        
        ruler:
          external_url: https://alertmanager-it-operations-cluster.greenpeace.org
          storage:
            type: local
            local:
              directory: /tmp/rules
          rule_path: /tmp/scratch
          alertmanager_url: http://127.0.0.1:10000
          ring:
            kvstore:
              store: memberlist
          enable_api: true

**Expected behavior**
Rules to evaluate properly.

**Environment:**
 - Infrastructure: Kubernetes
 - Terraform

**Screenshots, Promtail config, or terminal output**
Grafana results:

![image](https://user-images.githubusercontent.com/50625416/114817848-138a0b00-9dfe-11eb-9a30-086777a242f6.png)

**Comment by owen-d** [comment]
This query is working in the Grafana screen shot you uploaded, but the ruler is having issues? Are both running the same Loki versions?

For future investigation, this comes from the Cortex code: https://github.com/cortexproject/cortex/blob/master/pkg/chunk/chunk.go#L25.

**Comment by gmintoco** [comment]
Hey,

Thats correct the same query works in Grafana but the ruler returns that error (wrong chunk metadata). All components are running Loki v2.2.1.

To be clear though some rules succeed (the example loki one is fine for example (although it says total bytes are 0 which seems like it might be suspcious)

`level=info ts=2021-04-15T12:44:48.978734542Z caller=metrics.go:91 org_id=..data traceID=2f561824daa80060 latency=fast query="(sum by(container)(rate({job=~\"loki-dev/.*\"}[1m])) > 1000)" query_type=metric range_type=instant length=0s step=0s duration=3.295506ms status=200 limit=0 returned_lines=0 throughput=0B total_bytes=0B
`

In case it might help here is the log of the ruler starting:

      level=info ts=2021-04-15T12:46:07.7650768Z caller=main.go:130 msg="Starting Loki" version="(version=2.2.1, branch=HEAD, revision=babea82ef)"
      level=info ts=2021-04-15T12:46:07.771109425Z caller=server.go:229 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
      level=info ts=2021-04-15T12:46:07.77293818Z caller=memberlist_client.go:380 msg="Using memberlist cluster node name" name=loki-global-prod-ruler-79958fc749-5bpqs-ce3beb1c
      level=info ts=2021-04-15T12:46:07.791391045Z caller=shipper_index_client.go:100 msg="starting boltdb shipper in 1 mode"
      level=info ts=2021-04-15T12:46:07.793078786Z caller=mapper.go:38 msg="cleaning up mapped rules directory" path=/tmp/scratch
      level=error ts=2021-04-15T12:46:07.793238878Z caller=mapper.go:42 msg="unable to read rules directory" path=/tmp/scratch err="open /tmp/scratch: no such file or directory"
      level=info ts=2021-04-15T12:46:07.799637832Z caller=module_service.go:59 msg=initialising module=memberlist-kv
      level=info ts=2021-04-15T12:46:07.800340937Z caller=module_service.go:59 msg=initialising module=server
      level=info ts=2021-04-15T12:46:07.801190607Z caller=module_service.go:59 msg=initialising module=ring
      level=info ts=2021-04-15T12:46:07.801621196Z caller=module_service.go:59 msg=initialising module=ingester-querier
      level=info ts=2021-04-15T12:46:07.802080671Z caller=module_service.go:59 msg=initialising module=store
      level=info ts=2021-04-15T12:46:07.802154375Z caller=module_service.go:59 msg=initialising module=ruler
      level=info ts=2021-04-15T12:46:07.802323448Z caller=ruler.go:403 msg="ruler up and running"
      level=info ts=2021-04-15T12:46:07.803324244Z caller=loki.go:248 msg="Loki started"
      level=info ts=2021-04-15T12:46:07.810059344Z caller=mapper.go:139 msg="updating rule file" file=/tmp/scratch/..2021_04_15_12_46_06.784713667/rules.yaml
      level=info ts=2021-04-15T12:46:07.815465349Z caller=mapper.go:139 msg="updating rule file" file=/tmp/scratch/..data/rules.yaml
      level=info ts=2021-04-15T12:46:07.836454708Z caller=memberlist_client.go:492 msg="joined memberlist cluster" reached_nodes=5
      level=info ts=2021-04-15T12:46:17.705692519Z caller=table_manager.go:182 msg="downloading all files for table loki_index_18732"
      level=info ts=2021-04-15T12:46:17.925366917Z caller=util.go:55 msg="downloaded file loki_index_18732/loki-global-prod-ingester-0-1611285985038488625-1618485300.gz"
      level=info ts=2021-04-15T12:46:17.92965395Z caller=util.go:55 msg="downloaded file loki_index_18732/loki-global-prod-ingester-0-1611285985038488625-1618486200.gz"
      level=info ts=2021-04-15T12:46:17.944038687Z caller=util.go:55 msg="downloaded file loki_index_18732/loki-global-prod-ingester-0-1611285985038488625-1618484400.gz"
      level=info ts=2021-04-15T12:46:17.962062783Z caller=util.go:55 msg="downloaded file loki_index_18732/loki-global-prod-ingester-0-1611285985038488625-1618488900.gz"
      level=info ts=2021-04-15T12:46:17.966101004Z caller=util.go:55 msg="downloaded file loki_index_18732/loki-global-prod-ingester-0-1611285985038488625-1618483500.gz"
      level=info ts=2021-04-15T12:46:17.974594785Z caller=util.go:55 msg="downloaded file loki_index_18732/loki-global-prod-ingester-0-1611285985038488625-1618487100.gz"
      level=info ts=2021-04-15T12:46:17.978318986Z caller=util.go:55 msg="downloaded file loki_index_18732/loki-global-prod-ingester-0-1611285985038488625-1618488000.gz"
      level=info ts=2021-04-15T12:46:18.055839355Z caller=util.go:55 msg="downloaded file loki_index_18732/compactor-1618484184.gz"

**Comment by gmintoco** [comment]
This is the debug log from the ruler as well:

        level=debug ts=2021-04-16T06:38:02.108676986Z caller=async_store.go:90 msg="post-filtering ingester chunks" count=4
        ts=2021-04-16T06:38:02.108768832Z caller=spanlogger.go:79 org_id=..2021_04_16_06_35_35.718703364 traceID=1a03fdc108ac4950 method=query.Exec level=debug Ingester.TotalReached=1 Ingester.TotalChunksMatched=0 Ingester.TotalBatches=0 Ingester.TotalLinesSent=0 Ingester.HeadChunkBytes="0 B" Ingester.HeadChunkLines=0 Ingester.DecompressedBytes="0 B" Ingester.DecompressedLines=0 Ingester.CompressedBytes="0 B" Ingester.TotalDuplicates=0 Store.TotalChunksRef=0 Store.TotalChunksDownloaded=0 Store.ChunksDownloadTime=0s Store.HeadChunkBytes="0 B" Store.HeadChunkLines=0 Store.DecompressedBytes="0 B" Store.DecompressedLines=0 Store.CompressedBytes="0 B" Store.TotalDuplicates=0
        ts=2021-04-16T06:38:02.108954244Z caller=spanlogger.go:79 org_id=..2021_04_16_06_35_35.718703364 traceID=1a03fdc108ac4950 method=query.Exec level=debug Summary.BytesProcessedPerSecond="0 B" Summary.LinesProcessedPerSecond=0 Summary.TotalBytesProcessed="0 B" Summary.TotalLinesProcessed=0 Summary.ExecTime=8.064686ms
        level=info ts=2021-04-16T06:38:02.109217913Z caller=metrics.go:91 org_id=..2021_04_16_06_35_35.718703364 traceID=1a03fdc108ac4950 latency=fast query="sum by(VEEAM_MIB__backupJobName,location,entity,VEEAM_MIB__backupJobResult,VEEAM_MIB__backupJobName)(count_over_time({app=\"snmptrapd\"} | json | ( ( ( __error__!=\"JSONParserErr\" , SNMPv2_MIB__snmpTrapEnterprise_0=\"VEEAM-MIB::traps\" ) , SNMPv2_MIB__snmpTrapOID_0=\"VEEAM-MIB::onBackupJobCompleted\" ) , VEEAM_MIB__backupJobResult=\"Warning\" )[12h]))" query_type=metric range_type=instant length=0s step=0s duration=8.064686ms status=500 limit=0 returned_lines=0 throughput=0B total_bytes=0B
        level=warn ts=2021-04-16T06:38:02.109324575Z caller=manager.go:598 user=..2021_04_16_06_35_35.718703364 group=veeam_backup_warning_error msg="Evaluating rule failed" rule="alert: VeeamBackupWarning\nexpr: sum by(VEEAM_MIB__backupJobName,location,entity,VEEAM_MIB__backupJobResult,VEEAM_MIB__backupJobName)(count_over_time({app=\"snmptrapd\"}\n | json | ( ( ( __error__!=\"JSONParserErr\" , SNMPv2_MIB__snmpTrapEnterprise_0=\"VEEAM-MIB::traps\"\n ) , SNMPv2_MIB__snmpTrapOID_0=\"VEEAM-MIB::onBackupJobCompleted\" ) , VEEAM_MIB__backupJobResult=\"Warning\"\n )[12h]))\nlabels:\n email_contact: ops-group@company.com\n gitlab_project: tree-support\n severity: low\n slack_channel: tree-slack-alert\nannotations:\n description: Backup {{ $labels.VEEAM_MIB__backupJobResult | toLower }} for {{ $labels.VEEAM_MIB__backupJobName\n }} on {{ $labels.location }}. This could be caused by a number off issues. Start\n by checking the Veeam logs there `{{ $labels.location }}`.\n gitlab_incident_markdown: |\n /label ~\\\"tree\\\" ~\\\"Incident\\\" ~\\\"Loki\\\" ~\\\"Backup\\\" ~\\\"tree\\\"\\n Veeam backup warning for {{ $labels.VEEAM_MIB__backupJobName }} on {{ $labels.location }}\n observability_url: https://grafana.company.com/explore?orgId=1&left=%5B%22now-24h%22,%22now%22,%22Loki%20Global%22,%7B%22exemplar%22:true,%22expr%22:%22sum%20by%20(VEEAM_MIB__backupJobName,%20location,%20entity,%20%5CrVEEAM_MIB__backupJobResult,%20VEEAM_MIB__backupJobName)%20(count_over_time(%7Bapp%3D%5C%22snmptrapd%5C%22%7D%20%7C%20json%20%7C%20__error__!%3D%5C%22JSONParserErr%5C%22%20and%20SNMPv2_MIB__snmpTrapEnterprise_0%3D%5C%22VEEAM-MIB::traps%5C%22%20and%20SNMPv2_MIB__snmpTrapOID_0%3D%5C%22VEEAM-MIB::onBackupJobCompleted%5C%22%20%5B12h%5D)%20)%22,%22instant%22:true,%22range%22:false%7D%5D\n runbook_url: https://docs.google.com/document/d/blah-blah/edit#bookmark=id.9d5l6l4io59t\n summary: Backup {{ $labels.VEEAM_MIB__backupJobName }} warning on {{ $labels.location\n }}\n" err="wrong chunk metadata"
        ts=2021-04-16T06:38:02.110488954Z caller=spanlogger.go:79 org_id=..2021_04_16_06_35_35.718703364 traceID=7c1a0ae81c490122 method=SeriesStore.GetChunkRefs level=debug metric=logs
        ts=2021-04-16T06:38:02.110550291Z caller=spanlogger.go:79 org_id=..2021_04_16_06_35_35.718703364 traceID=7c1a0ae81c490122 method=SeriesStore.lookupSeriesByMetricNameMatchers level=debug metricName=logs matchers=1
        ts=2021-04-16T06:38:02.110600052Z caller=spanlogger.go:79 org_id=..2021_04_16_06_35_35.718703364 traceID=7c1a0ae81c490122 method=Store.lookupIdsByMetricNameMatcher level=debug metricName=logs matcher="app=\"snmptrapd\""
        ts=2021-04-16T06:38:02.110751036Z caller=spanlogger.go:79 org_id=..2021_04_16_06_35_35.718703364 traceID=7c1a0ae81c490122 method=Store.lookupIdsByMetricNameMatcher level=debug matcher="app=\"snmptrapd\"" queries=32
        ts=2021-04-16T06:38:02.110788911Z caller=spanlogger.go:79 org_id=..2021_04_16_06_35_35.718703364 traceID=7c1a0ae81c490122 method=Store.lookupIdsByMetricNameMatcher level=debug matcher="app=\"snmptrapd\"" filteredQueries=32
        ts=2021-04-16T06:38:02.110871723Z caller=spanlogger.go:79 org_id=..2021_04_16_06_35_35.718703364 traceID=7c1a0ae81c490122 method=cachingIndexClient.cacheFetch level=debug hits=0 misses=32
        ts=2021-04-16T06:38:02.110933423Z caller=spanlogger.go:79 org_id=..2021_04_16_06_35_35.718703364 traceID=7c1a0ae81c490122 method=treeper.Downloads.Query level=debug table-name=loki_index_18732
        ts=2021-04-16T06:38:02.110973892Z caller=spanlogger.go:79 org_id=..2021_04_16_06_35_35.718703364 traceID=7c1a0ae81c490122 method=treeper.Downloads.Table.MultiQueries level=debug table-name=loki_index_18732 query-count=16
        ts=2021-04-16T06:38:02.111086292Z caller=spanlogger.go:79 org_id=..2021_04_16_06_35_35.718703364 traceID=7c1a0ae81c490122 method=treeper.Downloads.Table.MultiQueries level=debug queried-db=compactor-1618534585.gz
        ts=2021-04-16T06:38:02.11115806Z caller=spanlogger.go:79 org_id=..2021_04_16_06_35_35.718703364 traceID=7c1a0ae81c490122 method=treeper.Downloads.Table.MultiQueries level=debug queried-db=loki-global-prod-ingester-0-1611285985038488625-1618533900.gz
        ts=2021-04-16T06:38:02.111191857Z caller=spanlogger.go:79 org_id=..2021_04_16_06_35_35.718703364 traceID=7c1a0ae81c490122 method=treeper.Downloads.Query level=debug table-name=loki_index_18733
        ts=2021-04-16T06:38:02.112726631Z caller=spanlogger.go:79 org_id=..2021_04_16_06_35_35.718703364 traceID=7c1a0ae81c490122 method=treeper.Downloads.Table.MultiQueries level=debug table-name=loki_index_18733 query-count=16
        ts=2021-04-16T06:38:02.11280357Z caller=spanlogger.go:79 org_id=..2021_04_16_06_35_35.718703364 traceID=7c1a0ae81c490122 level=debug ingester-chunks-count=4
        level=debug ts=2021-04-16T06:38:02.112834933Z caller=async_store.go:69 msg="got chunk ids from ingester" count=4
        ts=2021-04-16T06:38:02.112911071Z caller=spanlogger.go:79 org_id=..2021_04_16_06_35_35.718703364 traceID=7c1a0ae81c490122 method=treeper.Downloads.Table.MultiQueries level=debug queried-db=loki-global-prod-ingester-0-1611285985038488625-1618551000.gz
        ts=2021-04-16T06:38:02.112995218Z caller=spanlogger.go:79 org_id=..2021_04_16_06_35_35.718703364 traceID=7c1a0ae81c490122 method=treeper.Downloads.Table.MultiQueries level=debug queried-db=loki-global-prod-ingester-0-1611285985038488625-1618553700.gz
        ts=2021-04-16T06:38:02.113089986Z caller=spanlogger.go:79 org_id=..2021_04_16_06_35_35.718703364 traceID=7c1a0ae81c490122 method=treeper.Downloads.Table.MultiQueries level=debug queried-db=compactor-1618548230.gz
        ts=2021-04-16T06:38:02.113154082Z caller=spanlogger.go:79 org_id=..2021_04_16_06_35_35.718703364 traceID=7c1a0ae81c490122 method=treeper.Downloads.Table.MultiQueries level=debug queried-db=loki-global-prod-ingester-0-1611285985038488625-1618548300.gz
        ts=2021-04-16T06:38:02.113224782Z caller=spanlogger.go:79 org_id=..2021_04_16_06_35_35.718703364 traceID=7c1a0ae81c490122 method=treeper.Downloads.Table.MultiQueries level=debug queried-db=loki-global-prod-ingester-0-1611285985038488625-1618550100.gz
        ts=2021-04-16T06:38:02.113289552Z caller=spanlogger.go:79 org_id=..2021_04_16_06_35_35.718703364 traceID=7c1a0ae81c490122 method=treeper.Downloads.Table.MultiQueries level=debug queried-db=loki-global-prod-ingester-0-1611285985038488625-1618552800.gz
        ts=2021-04-16T06:38:02.113362974Z caller=spanlogger.go:79 org_id=..2021_04_16_06_35_35.718703364 traceID=7c1a0ae81c490122 method=treeper.Downloads.Table.MultiQueries level=debug queried-db=loki-global-prod-ingester-0-1611285985038488625-1618547400.gz
        ts=2021-04-16T06:38:02.113436014Z caller=spanlogger.go:79 org_id=..2021_04_16_06_35_35.718703364 traceID=7c1a0ae81c490122 method=treeper.Downloads.Table.MultiQueries level=debug queried-db=loki-global-prod-ingester-0-1611285985038488625-1618549200.gz
        ts=2021-04-16T06:38:02.113508434Z caller=spanlogger.go:79 org_id=..2021_04_16_06_35_35.718703364 traceID=7c1a0ae81c490122 method=treeper.Downloads.Table.MultiQueries level=debug queried-db=loki-global-prod-ingester-0-1611285985038488625-1618551900.gz
        ts=2021-04-16T06:38:02.113549399Z caller=spanlogger.go:79 org_id=..2021_04_16_06_35_35.718703364 traceID=7c1a0ae81c490122 level=debug queried=downloads-manager
        ts=2021-04-16T06:38:02.11368336Z caller=spanlogger.go:79 org_id=..2021_04_16_06_35_35.718703364 traceID=7c1a0ae81c490122 method=Store.lookupIdsByMetricNameMatcher level=debug matcher="app=\"snmptrapd\"" entries=0
        ts=2021-04-16T06:38:02.113721128Z caller=spanlogger.go:79 org_id=..2021_04_16_06_35_35.718703364 traceID=7c1a0ae81c490122 method=Store.lookupIdsByMetricNameMatcher level=debug matcher="app=\"snmptrapd\"" ids=0
        ts=2021-04-16T06:38:02.113932838Z caller=spanlogger.go:79 org_id=..2021_04_16_06_35_35.718703364 traceID=7c1a0ae81c490122 method=SeriesStore.lookupSeriesByMetricNameMatchers level=debug msg="post intersection" ids=0
        ts=2021-04-16T06:38:02.113963533Z caller=spanlogger.go:79 org_id=..2021_04_16_06_35_35.718703364 traceID=7c1a0ae81c490122 method=SeriesStore.GetChunkRefs level=debug series-ids=0
        ts=2021-04-16T06:38:02.113988584Z caller=spanlogger.go:79 org_id=..2021_04_16_06_35_35.718703364 traceID=7c1a0ae81c490122 method=SeriesStore.lookupChunksBySeries level=debug seriesIDs=0
        ts=2021-04-16T06:38:02.114048237Z caller=spanlogger.go:79 org_id=..2021_04_16_06_35_35.718703364 traceID=7c1a0ae81c490122 method=SeriesStore.lookupChunksBySeries level=debug queries=0
        ts=2021-04-16T06:38:02.11407988Z caller=spanlogger.go:79 org_id=..2021_04_16_06_35_35.718703364 traceID=7c1a0ae81c490122 method=SeriesStore.lookupChunksBySeries level=debug entries=0
        ts=2021-04-16T06:38:02.114091137Z caller=spanlogger.go:79 org_id=..2021_04_16_06_35_35.718703364 traceID=7c1a0ae81c490122 method=SeriesStore.GetChunkRefs level=debug chunk-ids=0
        ts=2021-04-16T06:38:02.114105476Z caller=spanlogger.go:79 org_id=..2021_04_16_06_35_35.718703364 traceID=7c1a0ae81c490122 method=SeriesStore.GetChunkRefs level=debug chunks-post-filtering=0
        level=debug ts=2021-04-16T06:38:02.114178427Z caller=async_store.go:90 msg="post-filtering ingester chunks" count=4
        ts=2021-04-16T06:38:02.11423496Z caller=spanlogger.go:79 org_id=..2021_04_16_06_35_35.718703364 traceID=7c1a0ae81c490122 method=query.Exec level=debug Ingester.TotalReached=1 Ingester.TotalChunksMatched=0 Ingester.TotalBatches=0 Ingester.TotalLinesSent=0 Ingester.HeadChunkBytes="0 B" Ingester.HeadChunkLines=0 Ingester.DecompressedBytes="0 B" Ingester.DecompressedLines=0 Ingester.CompressedBytes="0 B" Ingester.TotalDuplicates=0 Store.TotalChunksRef=0 Store.TotalChunksDownloaded=0 Store.ChunksDownloadTime=0s Store.HeadChunkBytes="0 B" Store.HeadChunkLines=0 Store.DecompressedBytes="0 B" Store.DecompressedLines=0 Store.CompressedBytes="0 B" Store.TotalDuplicates=0
        ts=2021-04-16T06:38:02.114347635Z caller=spanlogger.go:79 org_id=..2021_04_16_06_35_35.718703364 traceID=7c1a0ae81c490122 method=query.Exec level=debug Summary.BytesProcessedPerSecond="0 B" Summary.LinesProcessedPerSecond=0 Summary.TotalBytesProcessed="0 B" Summary.TotalLinesProcessed=0 Summary.ExecTime=4.432778ms
        level=info ts=2021-04-16T06:38:02.114522718Z caller=metrics.go:91 org_id=..2021_04_16_06_35_35.718703364 traceID=7c1a0ae81c490122 latency=fast query="sum by(VEEAM_MIB__backupJobName,location,entity,VEEAM_MIB__backupJobResult,VEEAM_MIB__backupJobName)(count_over_time({app=\"snmptrapd\"} | json | ( ( ( __error__!=\"JSONParserErr\" , SNMPv2_MIB__snmpTrapEnterprise_0=\"VEEAM-MIB::traps\" ) , SNMPv2_MIB__snmpTrapOID_0=\"VEEAM-MIB::onBackupJobCompleted\" ) , VEEAM_MIB__backupJobResult=\"Failed\" )[12h]))" query_type=metric range_type=instant length=0s step=0s duration=4.432778ms status=500 limit=0 returned_lines=0 throughput=0B total_bytes=0B
        level=warn ts=2021-04-16T06:38:02.114629928Z caller=manager.go:598 user=..2021_04_16_06_35_35.718703364 group=veeam_backup_warning_error msg="Evaluating rule failed" rule="alert: VeeamBackupError\nexpr: sum by(VEEAM_MIB__backupJobName,location,entity,VEEAM_MIB__backupJobResult,VEEAM_MIB__backupJobName)(count_over_time({app=\"snmptrapd\"}\n | json | ( ( ( __error__!=\"JSONParserErr\" , SNMPv2_MIB__snmpTrapEnterprise_0=\"VEEAM-MIB::traps\"\n ) , SNMPv2_MIB__snmpTrapOID_0=\"VEEAM-MIB::onBackupJobCompleted\" ) , VEEAM_MIB__backupJobResult=\"Failed\"\n )[12h]))\nlabels:\n email_contact: ops-group@company.com\n gitlab_project: tree-support\n severity: high\n slack_channel: tree-slack-alert\nannotations:\n description: Backup {{ $labels.VEEAM_MIB__backupJobResult | toLower }} for {{ $labels.VEEAM_MIB__backupJobName\n }} on {{ $labels.location }}. This could be caused by a number off issues. Start\n by checking the Veeam logs there `{{ $labels.location }}`.\n gitlab_incident_markdown: |\n /label ~\\\"tree\\\" ~\\\"Incident\\\" ~\\\"Loki\\\" ~\\\"Backup\\\" ~\\\"tree\\\"\\n Veeam backup failed for {{ $labels.VEEAM_MIB__backupJobName }} on {{ $labels.location }}\n observability_url: https://grafana.company.com/explore?orgId=1&left=%5B%22now-24h%22,%22now%22,%22Loki%20Global%22,%7B%22exemplar%22:true,%22expr%22:%22sum%20by%20(VEEAM_MIB__backupJobName,%20location,%20entity,%20%5CrVEEAM_MIB__backupJobResult,%20VEEAM_MIB__backupJobName)%20(count_over_time(%7Bapp%3D%5C%22snmptrapd%5C%22%7D%20%7C%20json%20%7C%20__error__!%3D%5C%22JSONParserErr%5C%22%20and%20SNMPv2_MIB__snmpTrapEnterprise_0%3D%5C%22VEEAM-MIB::traps%5C%22%20and%20SNMPv2_MIB__snmpTrapOID_0%3D%5C%22VEEAM-MIB::onBackupJobCompleted%5C%22%20%5B12h%5D)%20)%22,%22instant%22:true,%22range%22:false%7D%5D\n runbook_url: https://docs.google.com/document/d/blah-blah/edit#bookmark=id.9d5l6l4io59t\n summary: Backup {{ $labels.VEEAM_MIB__backupJobName }} error on {{ $labels.location\n }}\n" err="wrong chunk metadata"

**Comment by gmintoco** [comment]
I believe I have resolved this. It was my own mistake not reading the documentation close enough (but maybe it would be worth adding an error for it too)

Essentially the rules have to be in /<your rule directory>/<tenant_id>/rule1.yaml this is documented here: https://grafana.com/docs/loki/latest/alerting/ under "Ruler Storage"

I'm not quite sure how that resulted in an err chunk metadata error but putting all my rules under 'fake' (not using multi tenant) has seemed to resolve the issue. (rule location as configured is /tmp/rules and configmap is mounted at /tmp/fake/rules.yaml) 

It could be a consideration to add an error if rules are found 'orphaned' and not in a subdirectory maybe ? Either way I'll close the issue now :)
