### ISSUE TITLE
History graph should contain all the messages, not just 1000

### ISSUE THREAD

**Issue by roidelapluie** [grafana/loki#361]
**Is your feature request related to a problem? Please describe.**

When we open Loki in Grafana, it fetches 1000 lines of log.
But I would still expect the top representation to show all the messages.

![1000](https://user-images.githubusercontent.com/291750/53555873-143e8500-3b43-11e9-8f7f-0a3d732adc9f.png)

**Describe the solution you'd like**

I would like to see all the messages in that panel, even if all the logs are not shown below.

**Describe alternatives you've considered**

increasing the number of lines -- but even 10000 is really not a lot.

**Comment by roidelapluie** [comment]
This is almost a lie, as the graph suggests there are no logs before 7am.

**Comment by negbie** [comment]
Seems like a duplicate https://github.com/grafana/loki/issues/115

**Comment by roidelapluie** [comment]
yes, even if the #115 was not obvious to me so I did not find it directly.
