### ISSUE TITLE
Do not fetch 1000 lines. Fetch as much as screen can show.

### ISSUE THREAD

**Issue by roidelapluie** [grafana/loki#362]
**Is your feature request related to a problem? Please describe.**

the 1000 lines limitation is not useful, it would be better to address #361 and then show log lines as we scroll in the explore page. Or add pagination.

**Describe the solution you'd like**

When I scroll on explore, we see lines of logs loaded on the fly. Maybe once we have reached 1000 we can go to another page.

**Comment by steven-sheehy** [comment]
I think this issue is more appropriate in the Grafana repository. There is a similar issue about [auto-refresh and tailing](https://github.com/grafana/grafana/issues/15192), but your paging request might be separate.

**Comment by Kuqd** [comment]
Yes let's bring this to grafana.

Thank for the suggestion @roidelapluie
