### ISSUE TITLE
Docs feedback: /getting-started/get-logs-into-loki.md

### ISSUE THREAD

**Issue by eduardoroliveira** [grafana/loki#3634]
The wget link is broken at https://grafana.com/docs/loki/latest/getting-started/get-logs-into-loki/.

Change it to https://raw.githubusercontent.com/grafana/loki/main/clients/cmd/promtail/promtail-local-config.yaml

Edit this page is also broken

**Comment by oddlittlebird** [comment]
@robbymilo, I got a 404 when I clicked the Edit this page link in the Loki OSS docs.

**Comment by oddlittlebird** [comment]
@eduardoroliveira, thanks for letting us know!

**Comment by osg-grafana** [comment]
> @robbymilo, I got a 404 when I clicked the Edit this page link in the Loki OSS docs.

Refer to https://github.com/grafana/website/pull/4087.
