### ISSUE TITLE
Docs: Get Logs into Loki wget file not found

### ISSUE THREAD

**Issue by scoren-gl** [grafana/loki#3636]
On the docs page [Get Logs into Loki](https://grafana.com/docs/loki/latest/getting-started/get-logs-into-loki/) the YAML file mentioned in the wget command is 404ing:

`wget https://raw.githubusercontent.com/grafana/loki/master/cmd/promtail/promtail-local-config.yaml`

**Comment by owen-d** [comment]
I think this is closed by https://github.com/grafana/loki/pull/3633 and should take effect after the website is rebuilt
