### ISSUE TITLE
Promtail local-config yaml file not found

### ISSUE THREAD

**Issue by yanngit** [grafana/loki#3646]
**Describe the bug**
As written in the [doc](https://grafana.com/docs/loki/latest/installation/local/) it's possible to get a default configuration file for promtail. Due to recent changes the link is not defined as 404 and I cannot find promtail folder in the main branch ... could you fix the doc ? Thanks

**To Reproduce**
wget https://raw.githubusercontent.com/grafana/loki/main/cmd/promtail/promtail-local-config.yaml

**Expected behavior**
Default yaml file should be available

**Environment:**

**Screenshots, Promtail config, or terminal output**

**Comment by alexisparron** [comment]
I found the correct URL. Seems there are changes in the folder structure.

wget https://raw.githubusercontent.com/grafana/loki/main/clients/cmd/promtail/promtail-local-config.yaml
