### ISSUE TITLE
Can I use one Loki to collect logs from multiple applications

### ISSUE THREAD

**Issue by MarjanJordanovski** [grafana/loki#3649]
I'm wondering if I can use one Loki to collect logs from multiple applications, and based on labels or tags of that logs to store them to different s3 buckets.
Thanks!

**Comment by sandstrom** [comment]
Is this an issue with the code itself, or a general question? For general questions [Stackoverflow](https://stackoverflow.com/) is better than Github.

(I'd recommend closing this issue)
