### ISSUE TITLE
github.com/prometheus/common@v0.21.0 is not supported

### ISSUE THREAD

**Issue by marefr** [grafana/loki#3659]
**Describe the bug**
Upgraded github.com/prometheus/common dependency to v0.21.0 in https://github.com/grafana/grafana due to dependency changes. Grafana itself already has a dependency on loki. Had to add a replace directive to use v0.20.0 of github.com/prometheus/common.

[prometheus/common 0.21.0 release](https://github.com/prometheus/common/releases/tag/v0.21.0)

**To Reproduce**
Try to use loki with github.com/prometheus/common@v0.21.0 dependency.

**Expected behavior**
Able to use github.com/prometheus/common@v0.21.0 with loki dependency.

**Comment by cyriltovena** [comment]
Fixed by https://github.com/grafana/loki/commit/d88f3996eaa2ab4e60f29cdb396e947d28ea0986
