### ISSUE TITLE
Docs feedback: /logql/_index.md

### ISSUE THREAD

**Issue by monktastic** [grafana/loki#3669]
Everywhere that "filter out" is used, I think you mean "filter in." To "filter out" is to _remove_. For example:

> a log pipeline |= "metrics.go" | logfmt | duration > 10s and throughput_mb < 500 which will filter out log that contains the word metrics.go, then parses each log line to extract more labels and filter with them.

This pipeline filters _in_ logs with "metrics.go," AFAICT. If "filter in" is too awkward a phrase, perhaps "filters for."

**Comment by cyriltovena** [comment]
Correct do you want to update it or should I ?
