### ISSUE TITLE
Chunk size not configurable

### ISSUE THREAD

**Issue by davkal** [grafana/loki#367]
Chunk file size is currently [hardcoded](https://github.com/grafana/loki/blob/5207751cbdadd821aaf9999ee052ce25cc19d305/pkg/chunkenc/gzip.go#L135) but would be a good candidate for operational tuning, e.g., to reign in number of files created, #364

**Comment by daixiang0** [comment]
The size can be written in loki config,  do you mean auto merge them if too large?

**Comment by dguendisch** [comment]
Definitely needed. As it stands, my 10GB PVC (some gcp pd-standard disk) has utilized 0,013% of storage but already 0,02% of inodes, which means I'll never be able to "fill" that 10GB disk but will run out of inodes before (at about 6,5GB of data stored).
