### ISSUE TITLE
Dropping labels from parsed line

### ISSUE THREAD

**Issue by boniek83** [grafana/loki#3671]
**Is your feature request related to a problem? Please describe.**
I want to use log lines as annotation source for some of my dashboards. Precisely this is about using Heptio Eventrouter logs to enhance dashboards for pod monitoring. After parsing json log lines there is a lot of labels displayed alongside, which makes using verbose log lines such as these useless for annotations.

**Describe the solution you'd like**
It would be useful to have ability to drop all, or better yet some labels, after parsing log line using json, logfmt or whatever.

**Describe alternatives you've considered**
No viable alternatives.

**Additional context**

**Comment by cyriltovena** [comment]
You can use the new json parser with parameter that allows you to parse only the labels that you want.

I'm pasting the doc https://grafana.com/docs/loki/latest/logql/:

>Using | json label="expression", another="expression" in your pipeline will extract only the specified json fields to labels. You can specify one or more expressions in this way, the same as label_format; all expressions must be quoted.

>Currently, we only support field access (my.field, my["field"]) and array access (list[0]), and any combination of these in any level of nesting (my.list[0]["field"]).

>For example, | json first_server="servers[0]", ua="request.headers[\"User-Agent\"] will extract from the following document:
```
{
    "protocol": "HTTP/2.0",
    "servers": ["129.0.1.1","10.2.1.3"],
    "request": {
        "time": "6.032",
        "method": "GET",
        "host": "foo.grafana.net",
        "size": "55",
        "headers": {
          "Accept": "*/*",
          "User-Agent": "curl/7.68.0"
        }
    },
    "response": {
        "status": 401,
        "size": "228",
        "latency_seconds": "6.031"
    }
}
```
>The following list of labels:
```
"first_server" => "129.0.1.1"
"ua" => "curl/7.68.0"
```
>If an array or an object returned by an expression, it will be assigned to the label in json format.

>For example, | json server_list="servers", headers="request.headers will extract:
```
"server_list" => `["129.0.1.1","10.2.1.3"]`
"headers" => `{"Accept": "*/*", "User-Agent": "curl/7.68.0"}`
```

**Comment by cyriltovena** [comment]
tbh I was hoping the annotations feature in Grafana would allow at some point to remove unwanted labels.

See https://github.com/grafana/grafana/issues/29536

I think you can empty labels using label format that's not the best solution but a good workaround for now.

`| label_format pod="",file=""`

**Comment by boniek83** [comment]
Workaround works as expected and since this seems more like grafana issue than loki issue I'm closing this.

**Comment by james-callahan** [comment]
I think this should be re-opened: dropping log labels is useful after you use them. e.g. today I was trying to look through some old mongo logs in grafana's Explore view:
```
{filename="/mongo/log/mongod.log"}
  | pattern "<timestamp> <severity> <component> [<context>] <message>" # Mongo 4.0 log format
  | line_format "{{.message}}"
```

After this, I would like to `  | drop_label message`, so that `message` doesn't appear when I tick "Unique labels"; or when I expand it.

**Comment by damluk** [comment]
> After this, I would like to ` | drop_label message`, so that `message` doesn't appear when I tick "Unique labels"; or when I expand it.

`| label_format message=message`

**Comment by joaopedrodcf** [comment]
It would be amazing to have that `drop_label` feauture instead of typing all the labels

**Comment by AndreKR** [comment]
> | label_format message=message

*Why* does this work? 😄

**Comment by agardiman** [comment]
@damluk thanks for the trick! can you explain please what syntax is that and why it's removing the label? I don't find anything like that in the documentation.

**Comment by damluk** [comment]
> @damluk thanks for the trick! can you explain please what syntax is that and why it's removing the label? I don't find anything like that in the documentation.

It is not mentioned explicitly. However, when I was looking for a drop-label feature, I stumbled upon [this description](https://grafana.com/docs/loki/latest/query/log_queries/#labels-format-expression):
> When both side are label identifiers, for example `dst=src`, the operation will rename the `src` label into `dst`.

One way to achieve the above, is a simple
```
dst := src
delete(src)
```
So a `message=message` would boil down to
```
message := message
delete(message)
```

And indeed it worked. In principle, this trick could stop working at some release.

**Comment by agardiman** [comment]
@damluk Nice! Thanks for the explanation, very clever!
