### ISSUE TITLE
correcting default config values

### ISSUE THREAD

**Issue by Nemric** [grafana/loki#3676]
**Describe the bug**
I run loki as a container with podman. after upadting to the latest version loki failed to start with this message :
failed parsing config: /mnt/config/loki.yaml: yaml: unmarshal errors:
  line 52: field max_look_back_period not found in type chunk.StoreConfig

**To Reproduce**
run loki in podman (or other) with default setting (without any config file)

**Expected behavior**
I expect loki to start normally

It appears that in last commit in vendor/github.com/cortexproject/cortex/pkg/chunk/chunk_store.go depracated
```
f.Var(&cfg.MaxLookBackPeriod, "store.max-look-back-period", "Deprecated: use -querier.max-query-lookback instead. Limit how long back data can be queried. This setting applies to chunks storage only.") // To be removed in Cortex 1.8.
}
```
has been removed but default config files have not been updated to

**Comment by cyriltovena** [comment]
Fixed in main now.
