### ISSUE TITLE
Logs arrive delayed in loki

### ISSUE THREAD

**Issue by PixelBumper** [grafana/loki#3682]
**Describe the bug**
We have setup loki-stack in our cluster and unfortunately we are experiencing that some logs arrive delayed by 20 to 60 min.

This happens sporadically for some logs and there seems not to be any correlation between app and log being missing.
Basically it could affect any logfile in the cluster.

Eventually the logs end up in loki, however the long delay renders it unusable in scenarios in which we need to take a look at recent log messages.

We are running the loki-stack chart in EKS with self managed worker nodes (currently spot instances, as there is little traffic) and Loki is configured to use S3 storage

Loki has been scaled to 3 instances, however I fear that it is part of the issue, as according to this [issue](https://github.com/grafana/loki/issues/50) single binary mode cannot be scaled out.

We also checked the loki and promtail logs for errors and we see quite regularly "errors fetching chunks", "failed to flush user" and "error querying storage".
Unfortunately we cannot tell if it is part of the regular operational loki noise.

Questions:

    Is this a bug or an issue in our loki setup?
    Should we switch to distributed loki? If so is there a migration path to switch from the loki-stack chart to the loki-distributed chart?

**To Reproduce**
install loki-stack on kubernetes

**Expected behavior**
Logs should be visible in loki with at most a minute delay

**Environment:**
 - Infrastructure: Kubernetes on aws (self managed nodes)
 - Deployment tool: helm (loki-stack)

**Screenshots, Promtail config, or terminal output**

Configuration for loki-stack:

    grafana:
      enabled: false
    prometheus:
      enabled: false
    promtail:
      enabled: true
      extraVolumes:
      - name: journal
        hostPath:
          path: /var/log/journal
      extraVolumeMounts:
        - name: journal
          mountPath: /var/log/journal
          readOnly: true
      config:
        lokiAddress: "http://infrastructure-loki-stack:3100/loki/api/v1/push"
        snippets:
          pipelineStages:
            - docker: { }
            - match:
                selector: '{app="eventrouter"}'
                stages:
                - json:
                    expressions:
                      event_verb: verb
                      event_type: event.type
                      event_kind: event.involvedObject.kind
                      event_reason: event.reason
                      event_namespace: event.metadata.namespace
                      event_involved_object_namespace: event.involvedObject.namespace
                      event_name: event.metadata.name
                      event_source_host: event.source.host
                      event_source_component: event.source.component
                - labels:
                    event_verb: ""
                    event_type: ""
                    event_kind: ""
                    event_reason: ""
                    event_namespace: ""
                    event_involved_object_namespace: ""
                    event_name: ""
                    event_source_host: ""
                    event_source_component: ""
      file: |
        server:
          log_level: info
          http_listen_port: {{ .Values.config.serverPort }}
        client:
          url: {{ .Values.config.lokiAddress }}
          tenant_id: dev-cluster
        positions:
          filename: /run/promtail/positions.yaml
        scrape_configs:
          # This reuses the existing default scrape configs
          {{- tpl .Values.config.snippets.scrapeConfigs . | nindent 2 }}

          # Add an additional scrape config for syslog
          - job_name: journal
            pipeline_stages:
              - docker: {}
            journal:
              path: /var/log/journal
              max_age: 12h
              labels:
                job: systemd-journal
            relabel_configs:
              - source_labels:
                  - '__journal__systemd_unit'
                target_label: 'unit'
              - source_labels:
                  - '__journal__hostname'
                target_label: 'hostname'
    loki:
      enabled: true
      replicas: 3
      rbac:
        create: false
      serviceAccount:
        create: false
        name: loki
      persistence:
        enabled: false
        server:
      config:
        auth_enabled: true
        schema_config:
          configs:
            - from: 2021-02-08
              store: boltdb-shipper
              object_store: s3
              schema: v11
              index:
                prefix: index_
                period: 24h
        compactor:
          working_directory: /data/loki/boltdb-shipper-compactor
          shared_store: aws
        storage_config:
          aws:
            s3: <redacted>
            s3forcepathstyle: true
          boltdb_shipper:
            active_index_directory: /data/loki/index
            shared_store: s3
            cache_location: /data/loki/boltdb-cache
Log excerpt:

	level=error ts=2021-04-30T07:53:56.163348745Z caller=batch.go:666 msg="error fetching chunks" err="RequestCanceled: request context canceled\ncaused by: context canceled"
    level=error ts=2021-04-30T07:53:37.273776057Z caller=batch.go:666 msg="error fetching chunks" err="RequestCanceled: request context canceled\ncaused by: context canceled"
    level=error ts=2021-04-30T07:52:26.707204681Z caller=batch.go:666 msg="error fetching chunks" err="RequestCanceled: request context canceled\ncaused by: context canceled"
    level=error ts=2021-04-30T07:40:35.164853261Z caller=batch.go:666 msg="error fetching chunks" err="RequestCanceled: request context canceled\ncaused by: context canceled"
    level=error ts=2021-04-30T07:36:25.332394004Z caller=batch.go:666 msg="error fetching chunks" err="RequestCanceled: request context canceled\ncaused by: context canceled"
    level=error ts=2021-04-30T07:36:02.919799739Z caller=batch.go:666 msg="error fetching chunks" err="RequestCanceled: request context canceled\ncaused by: context canceled"
    level=error ts=2021-04-30T06:39:31.782224193Z caller=batch.go:666 msg="error fetching chunks" err="RequestCanceled: request context canceled\ncaused by: context canceled"
    level=error ts=2021-04-30T06:39:25.968183068Z caller=batch.go:666 msg="error fetching chunks" err="RequestCanceled: request context canceled\ncaused by: context canceled"
    level=error ts=2021-04-30T06:39:24.931348125Z caller=batch.go:666 msg="error fetching chunks" err="RequestCanceled: request context canceled\ncaused by: context canceled"
    level=error ts=2021-04-30T06:39:23.654459228Z caller=batch.go:666 msg="error fetching chunks" err="RequestCanceled: request context canceled\ncaused by: context canceled"
    level=error ts=2021-04-30T03:53:10.804081067Z caller=flush.go:199 org_id=canary-cluster msg="failed to flush user" err="RequestError: send request failed\ncaused by: Put \"https://s3.<redacted>/loki/canary-cluster/b5a992545ffb2d3d%3A17920e5a620%3A17920e5a621%3Aebffe933\": EOF"
    level=error ts=2021-04-30T02:41:10.367905991Z caller=flush.go:199 org_id=demo-cluster msg="failed to flush user" err="RequestError: send request failed\ncaused by: Put \"https://s3.<redacted>/loki/demo-cluster/ad6fcdfd42d594e8%3A17920a37c19%3A17920a3f168%3Ad3951e4f\": EOF"
    ts=2021-04-29T23:34:55.955138144Z caller=spanlogger.go:53 org_id=dev-cluster traceID=47374c93dba8643d method=SeriesStore.GetChunkRefs level=error msg=lookupChunksBySeries err="context canceled"
    level=error ts=2021-04-29T23:34:55.955090578Z caller=chunk_store.go:533 org_id=dev-cluster traceID=47374c93dba8643d msg="error querying storage" err="context canceled"
    ts=2021-04-29T23:28:18.242479767Z caller=spanlogger.go:53 org_id=dev-cluster traceID=4157565c02219948 method=SeriesStore.GetChunkRefs level=error msg=lookupChunksBySeries err="context canceled"
    level=error ts=2021-04-29T23:28:18.242365185Z caller=chunk_store.go:533 org_id=dev-cluster traceID=4157565c02219948 msg="error querying storage" err="context canceled"
    ts=2021-04-29T22:52:39.050014958Z caller=spanlogger.go:53 org_id=dev-cluster traceID=16bcf389f688dca8 method=SeriesStore.GetChunkRefs level=error msg=lookupChunksBySeries err="context canceled"
    level=error ts=2021-04-29T22:52:39.049947496Z caller=chunk_store.go:533 org_id=dev-cluster traceID=16bcf389f688dca8 msg="error querying storage" err="context canceled"
    ts=2021-04-29T22:32:39.611868053Z caller=spanlogger.go:53 org_id=prod-cluster traceID=18811faaca0abfe method=SeriesStore.GetChunkRefs level=error msg=lookupChunksBySeries err="context canceled"
    level=error ts=2021-04-29T22:32:39.611812188Z caller=chunk_store.go:533 org_id=prod-cluster traceID=18811faaca0abfe msg="error querying storage" err="context canceled"
    ts=2021-04-29T22:11:41.639383294Z caller=spanlogger.go:53 org_id=prod-cluster traceID=7e6f094a9d1cf62 method=SeriesStore.GetChunkRefs level=error msg=lookupChunksBySeries err="context canceled"
    level=error ts=2021-04-29T22:11:41.639218112Z caller=chunk_store.go:533 org_id=prod-cluster traceID=7e6f094a9d1cf62 msg="error querying storage" err="context canceled"
    ts=2021-04-29T22:04:39.863712943Z caller=spanlogger.go:53 org_id=prod-cluster traceID=3d23d8aa09334fad method=SeriesStore.GetChunkRefs level=error msg=lookupChunksBySeries err="context canceled"
    level=error ts=2021-04-29T22:04:39.862672415Z caller=chunk_store.go:533 org_id=prod-cluster traceID=3d23d8aa09334fad msg="error querying storage" err="context canceled"

**Comment by PixelBumper** [comment]
Can I provide something else to help debugging this issue?

**Comment by openbob** [comment]
We are coming across the exact same issues that has become a blocker.  We use 3 x replica, AWS DynamoDB and s3 as backend. Any comment from the loki maintainers will be highly appreciated. Many thanks.

**Comment by cyriltovena** [comment]
loki-stack can't be scaled it's the single binary you should check out https://github.com/grafana/helm-charts/tree/main/charts/loki-distributed or scale the current one to 1.

**Comment by danielserrao** [comment]
I don't think this bug is fixed. I'm getting error below:

failed to get s3 object: RequestCanceled: request context canceled\ncaused by: context canceled

This is on loki-distributed with image grafana/loki version 2.4.2

**Comment by LinTechSo** [comment]
Hi. any updates?

**Comment by michaelosthege** [comment]
Also check if the clock on the machine emitting the logs is correctly synchronized.
