### ISSUE TITLE
Error installing loki and promtail when running jb

### ISSUE THREAD

**Issue by c0ffeec0der** [grafana/loki#3689]
**Describe the bug**
Error installing loki and promtail when running jb install

**To Reproduce**
1. Create new folder
2. Run jb install github.com/grafana/loki/production/ksonnet/loki
3. Terminal will show error
4. Run jb install github.com/grafana/loki/production/ksonnet/promtail
5. Terminal will show error

**Expected behavior**
Install sucess

**Environment:**
 - Infrastructure: Windows
 - Deployment tool: Jb

**Screenshots, Promtail config, or terminal output**
Loki
----
GET https://github.com/grafana/jsonnet-libs/archive/e5b5d8191dbbbaa5b4d68a946417177a44c74b16.tar.gz 200
GET https://github.com/ksonnet/ksonnet-lib/archive/0d2f82676817bbf9e4acf6495b2090205f323b9f.tar.gz 200
GET https://github.com/grafana/loki/archive/.tar.gz 404
archive install failed: unexpected status code 404     
retrying with git...
Initialized empty Git repository in C:/some folder/.git/
fatal: couldn't find remote ref master
remote: Enumerating objects: 63633, done.
remote: Counting objects: 100% (1788/1788), done.
remote: Compressing objects: 100% (964/964), done.
remote: Total 63633 (delta 860), reused 1277 (delta 764), pack-reused 61845R
Receiving objects: 100% (63633/63633), 140.49 MiB | 2.40 MiB/s, done.
Resolving deltas: 100% (36232/36232), done.
From https://github.com/grafana/loki
 * [new branch]      1929_targets_not_required_for_scrape -> origin/1929_targets_not_required_for_scrape
 * [new branch]      add-org-id-frontend     -> origin/add-org-id-frontend
 * [new branch]      add-scrape-troubleshooting -> origin/add-scrape-troubleshooting
 * [new branch]      cleanup-errors          -> origin/cleanup-errors  
 * [new branch]      debug-issue-2624        -> origin/debug-issue-2624
 * [new branch]      doc-.Entry              -> origin/doc-.Entry
 * [new branch]      doc-fixes               -> origin/doc-fixes 
 * [new branch]      doc-promtail-installation -> origin/doc-promtail-installation
 * [new branch]      docs-add-hostname-to-deamonset -> origin/docs-add-hostname-to-deamonset
 * [new branch]      docs-fix-basic-concepts-links -> origin/docs-fix-basic-concepts-links  
 * [new branch]      fix-dynamodb-key        -> origin/fix-dynamodb-key
 * [new branch]      fix/docker-driver-signal-handling -> origin/fix/docker-driver-signal-handling
 * [new branch]      fix/vendor-cortext1.4.0 -> origin/fix/vendor-cortext1.4.0
 * [new branch]      gh-pages                -> origin/gh-pages    
 * [new branch]      index-verify            -> origin/index-verify
 * [new branch]      k12                     -> origin/k12
 * [new branch]      k13                     -> origin/k13
 * [new branch]      k14                     -> origin/k14
 * [new branch]      k15                     -> origin/k15
 * [new branch]      k16                     -> origin/k16
 * [new branch]      k17                     -> origin/k17
 * [new branch]      k18                     -> origin/k18
 * [new branch]      k19                     -> origin/k19
 * [new branch]      k20                     -> origin/k20
 * [new branch]      k21                     -> origin/k21
 * [new branch]      k22                     -> origin/k22
 * [new branch]      k23                     -> origin/k23
 * [new branch]      k24                     -> origin/k24
 * [new branch]      k25                     -> origin/k25
 * [new branch]      k26                     -> origin/k26
 * [new branch]      k27                     -> origin/k27
 * [new branch]      k28                     -> origin/k28
 * [new branch]      k29                     -> origin/k29
 * [new branch]      k30                     -> origin/k30
 * [new branch]      k31                     -> origin/k31
 * [new branch]      k32                     -> origin/k32
 * [new branch]      k33                     -> origin/k33
 * [new branch]      k34                     -> origin/k34
 * [new branch]      k35                     -> origin/k35
 * [new branch]      k36                     -> origin/k36
 * [new branch]      k37                     -> origin/k37
 * [new branch]      k38                     -> origin/k38
 * [new branch]      k39                     -> origin/k39
 * [new branch]      k40                     -> origin/k40
 * [new branch]      k41                     -> origin/k41
 * [new branch]      k42                     -> origin/k42
 * [new branch]      k43                     -> origin/k43
 * [new branch]      k44                     -> origin/k44
 * [new branch]      k45                     -> origin/k45
 * [new branch]      k46                     -> origin/k46
 * [new branch]      k47                     -> origin/k47
 * [new branch]      k48                     -> origin/k48
 * [new branch]      k49                     -> origin/k49
 * [new branch]      logcli-cgo-mac          -> origin/logcli-cgo-mac
 * [new branch]      main                    -> origin/main
 * [new branch]      ossfuzzbadge            -> origin/ossfuzzbadge
 * [new branch]      race-errors             -> origin/race-errors
 * [new branch]      release-2.0.1           -> origin/release-2.0.1
 * [new branch]      release-2.2             -> origin/release-2.2
 * [new branch]      release-2.2.1           -> origin/release-2.2.1
 * [new branch]      revert-2836-tests-fix-quoting-go-1.15 -> origin/revert-2836-tests-fix-quoting-go-1.15
 * [new branch]      revert-link-changes     -> origin/revert-link-changes
 * [new branch]      runtime-options         -> origin/runtime-options
 * [new branch]      sam-coren-loki-docs-edits -> origin/sam-coren-loki-docs-edits
 * [new branch]      timestamp-doc           -> origin/timestamp-doc
 * [new branch]      transfers               -> origin/transfers
 * [new branch]      trigger-drone           -> origin/trigger-drone
 * [new branch]      update-block-transfer   -> origin/update-block-transfer
 * [new branch]      update-cortex           -> origin/update-cortex
 * [new branch]      update-cortex-vendoring -> origin/update-cortex-vendoring
 * [new branch]      use-build-image         -> origin/use-build-image
 * [new tag]         v2.0.1                  -> v2.0.1
 * [new tag]         v2.2.0                  -> v2.2.0
 * [new tag]         v2.2.1                  -> v2.2.1
 * [new tag]           v0.1.0                  -> v0.1.0
 * [new tag]           v0.2.0                  -> v0.2.0
 * [new tag]           v0.3.0                  -> v0.3.0
 * [new tag]           v0.4.0                  -> v0.4.0
 * [new tag]           v1.0.0                  -> v1.0.0
 * [new tag]           v1.0.1                  -> v1.0.1
 * [new tag]           v1.1.0                  -> v1.1.0
 * [new tag]           v1.2.0                  -> v1.2.0
 * [new tag]           v1.3.0                  -> v1.3.0
 * [new tag]           v1.4.0                  -> v1.4.0
 * [new tag]           v1.4.1                  -> v1.4.1
 * [new tag]           v1.5.0                  -> v1.5.0
 * [new tag]           v1.6.0                  -> v1.6.0
 * [new tag]           v1.6.1                  -> v1.6.1
 * [new tag]           v2.0.0                  -> v2.0.0
 * [new tag]           v2.1.0                  -> v2.1.0
error: pathspec 'master' did not match any file(s) known to git
jb.exe: error: failed to install packages: downloading: exit status 1

Promtail
---------
GET https://github.com/grafana/loki/archive/.tar.gz 404
archive install failed: unexpected status code 404
retrying with git...
Initialized empty Git repository in C:/some folder/.git/
fatal: couldn't find remote ref master
remote: Enumerating objects: 63633, done.
remote: Counting objects: 100% (1787/1787), done.
remote: Compressing objects: 100% (963/963), done.
remote: Total 63633 (delta 861), reused 1277 (delta 764), pack-reused 61846
Receiving objects: 100% (63633/63633), 140.59 MiB | 1.86 MiB/s, done.
Resolving deltas: 100% (36230/36230), done.
From https://github.com/grafana/loki
 * [new branch]      1929_targets_not_required_for_scrape -> origin/1929_targets_not_required_for_scrape
 * [new branch]      add-org-id-frontend     -> origin/add-org-id-frontend
 * [new branch]      add-scrape-troubleshooting -> origin/add-scrape-troubleshooting
 * [new branch]      cleanup-errors          -> origin/cleanup-errors
 * [new branch]      debug-issue-2624        -> origin/debug-issue-2624
 * [new branch]      doc-.Entry              -> origin/doc-.Entry
 * [new branch]      doc-fixes               -> origin/doc-fixes
 * [new branch]      doc-promtail-installation -> origin/doc-promtail-installation
 * [new branch]      docs-add-hostname-to-deamonset -> origin/docs-add-hostname-to-deamonset
 * [new branch]      docs-fix-basic-concepts-links -> origin/docs-fix-basic-concepts-links
 * [new branch]      fix-dynamodb-key        -> origin/fix-dynamodb-key
 * [new branch]      fix/docker-driver-signal-handling -> origin/fix/docker-driver-signal-handling
 * [new branch]      fix/vendor-cortext1.4.0 -> origin/fix/vendor-cortext1.4.0
 * [new branch]      gh-pages                -> origin/gh-pages
 * [new branch]      index-verify            -> origin/index-verify
 * [new branch]      k12                     -> origin/k12
 * [new branch]      k13                     -> origin/k13
 * [new branch]      k14                     -> origin/k14
 * [new branch]      k15                     -> origin/k15
 * [new branch]      k16                     -> origin/k16
 * [new branch]      k17                     -> origin/k17
 * [new branch]      k18                     -> origin/k18
 * [new branch]      k19                     -> origin/k19
 * [new branch]      k20                     -> origin/k20
 * [new branch]      k21                     -> origin/k21
 * [new branch]      k22                     -> origin/k22
 * [new branch]      k23                     -> origin/k23
 * [new branch]      k24                     -> origin/k24
 * [new branch]      k25                     -> origin/k25
 * [new branch]      k26                     -> origin/k26
 * [new branch]      k27                     -> origin/k27
 * [new branch]      k28                     -> origin/k28
 * [new branch]      k29                     -> origin/k29
 * [new branch]      k30                     -> origin/k30
 * [new branch]      k31                     -> origin/k31
 * [new branch]      k32                     -> origin/k32
 * [new branch]      k33                     -> origin/k33
 * [new branch]      k34                     -> origin/k34
 * [new branch]      k35                     -> origin/k35
 * [new branch]      k36                     -> origin/k36
 * [new branch]      k37                     -> origin/k37
 * [new branch]      k38                     -> origin/k38
 * [new branch]      k39                     -> origin/k39
 * [new branch]      k40                     -> origin/k40
 * [new branch]      k41                     -> origin/k41
 * [new branch]      k42                     -> origin/k42
 * [new branch]      k43                     -> origin/k43
 * [new branch]      k44                     -> origin/k44
 * [new branch]      k45                     -> origin/k45
 * [new branch]      k46                     -> origin/k46
 * [new branch]      k47                     -> origin/k47
 * [new branch]      k48                     -> origin/k48
 * [new branch]      k49                     -> origin/k49
 * [new branch]      logcli-cgo-mac          -> origin/logcli-cgo-mac
 * [new branch]      main                    -> origin/main
 * [new branch]      ossfuzzbadge            -> origin/ossfuzzbadge
 * [new branch]      race-errors             -> origin/race-errors
 * [new branch]      release-2.0.1           -> origin/release-2.0.1
 * [new branch]      release-2.2             -> origin/release-2.2
 * [new branch]      release-2.2.1           -> origin/release-2.2.1
 * [new branch]      revert-2836-tests-fix-quoting-go-1.15 -> origin/revert-2836-tests-fix-quoting-go-1.15
 * [new branch]      revert-link-changes     -> origin/revert-link-changes
 * [new branch]      runtime-options         -> origin/runtime-options
 * [new branch]      sam-coren-loki-docs-edits -> origin/sam-coren-loki-docs-edits
 * [new branch]      timestamp-doc           -> origin/timestamp-doc
 * [new branch]      transfers               -> origin/transfers
 * [new branch]      trigger-drone           -> origin/trigger-drone
 * [new branch]      update-block-transfer   -> origin/update-block-transfer
 * [new branch]      update-cortex           -> origin/update-cortex
 * [new branch]      update-cortex-vendoring -> origin/update-cortex-vendoring
 * [new branch]      use-build-image         -> origin/use-build-image
 * [new tag]         v2.0.1                  -> v2.0.1
 * [new tag]         v2.2.0                  -> v2.2.0
 * [new tag]         v2.2.1                  -> v2.2.1
 * [new tag]           v0.1.0                  -> v0.1.0
 * [new tag]           v0.2.0                  -> v0.2.0
 * [new tag]           v0.3.0                  -> v0.3.0
 * [new tag]           v0.4.0                  -> v0.4.0
 * [new tag]           v1.0.0                  -> v1.0.0
 * [new tag]           v1.0.1                  -> v1.0.1
 * [new tag]           v1.1.0                  -> v1.1.0
 * [new tag]           v1.2.0                  -> v1.2.0
 * [new tag]           v1.3.0                  -> v1.3.0
 * [new tag]           v1.4.0                  -> v1.4.0
 * [new tag]           v1.4.1                  -> v1.4.1
 * [new tag]           v1.5.0                  -> v1.5.0
 * [new tag]           v1.6.0                  -> v1.6.0
 * [new tag]           v1.6.1                  -> v1.6.1
 * [new tag]           v2.0.0                  -> v2.0.0
 * [new tag]           v2.1.0                  -> v2.1.0
error: pathspec 'master' did not match any file(s) known to git
jb.exe: error: failed to install packages: downloading: exit status 1

**Comment by brokenjacobs** [comment]
Looks like this has to do with changing the default branch name from 'master' to 'main' in promtail and loki. Unfortunately the default branch name of the k8s library also in the documentation is 'master'. So if you do what git says and change your default branch to main instead of master, the documentation will still fail as is (In addition to breaking on any other modules that have changed the default branch name). I don't know how to override the default branch name for a specific jsonnet bundler module, but any pointers in the right direction would be greatly appreciated.
