### ISSUE TITLE
Fix broken link on Loki architecture page

### ISSUE THREAD

**Issue by osg-grafana** [grafana/loki#3695]
@dp1140a commented on [Mon May 03 2021](https://github.com/grafana/technical-documentation/issues/46)

Broken link on the Loki Architecture page

**To Reproduce**
1. Go to [https://grafana.com/docs/loki/latest/architecture/](https://grafana.com/docs/loki/latest/architecture/)
2. Click on Dynamo-Style under Quorum Consistency. This is linked to https://www.allthingsdistributed.com/files/amazon-dynamo-sosp2007.pdf

**Expected behavior**
The page should come up

**Screenshots**
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>TVEDDQTD29DVDRTM</RequestId>
<HostId>OKea7OWTNHYRGEqO5GmqeijcMIpomozpgdfpopZBu3F+mcORQIV3VYERJJmZ0o2SMPvwrELLj1o=</HostId>
</Error>
```

**Comment by KMiller-Grafana** [comment]
This issue has been corrected in commit https://github.com/grafana/loki/commit/d9380eaac950c669864c0af60fd99eae281d2438, PR https://github.com/grafana/loki/pull/3713.
