### ISSUE TITLE
Document support for Loki client Telegraf

### ISSUE THREAD

**Issue by osg-grafana** [grafana/loki#3696]
@dp1140a commented on [Tue May 04 2021](https://github.com/grafana/technical-documentation/issues/47)

**Describe the bug**
Add Telegraf as a supported Loki client
https://grafana.com/docs/loki/latest/clients/#loki-clients

**To Reproduce**
Telegraf now supports Loki as an output

**Additional context**
https://github.com/influxdata/telegraf/blob/release-1.18/plugins/outputs/loki/README.md

**Comment by dp1140a** [comment]
Was this resolved?
