### ISSUE TITLE
Dublicate strings in config.go

### ISSUE THREAD

**Issue by KVInventoR** [grafana/loki#3724]
https://github.com/grafana/loki/blob/d9380eaac950c669864c0af60fd99eae281d2438/clients/cmd/docker-driver/config.go#L184

https://github.com/grafana/loki/blob/d9380eaac950c669864c0af60fd99eae281d2438/clients/cmd/docker-driver/config.go#L187

is it dublicate?

**Comment by 3Xpl0it3r** [comment]
yeah, it looks duplicated
