### ISSUE TITLE
error creating logger: error creating loki logger: unable to load specified CA cert

### ISSUE THREAD

**Issue by KVInventoR** [grafana/loki#3725]
I am trying to use our private CaCrt for docker container.
My run command looks like:

`docker run --log-driver=loki --log-opt loki-url="https://loki.company.com/loki/api/v1/push" --log-opt loki-tls-ca-file="/cacrt.pem"  --name nginx -p 81:80 -d nginx
`

but I got a response:
`docker: Error response from daemon: failed to initialize logging driver: error creating logger: error creating loki logger: unable to load specified CA cert /cacrt.pem: open /cacrt.pem: no such file or directory.
`

it looks really strange, because:
```
# ls -lah /cacrt.pem
-rw-r--r-- 1 root root 7.5K May 14 06:18 /cacrt.pem
#

```

Can someone help to figure out what exactly is wrong?

**Comment by 3Xpl0it3r** [comment]
the cacert file is existed in container?

**Comment by KVInventoR** [comment]
yes, I did the same command with next options:

`docker run -v /cacrt.pem:/cacrt.pem --log-driver=loki --log-opt loki-url="https://loki.company.com" --log-opt loki-tls-ca-file="/cacrt.pem"  --name nginx -p 81:80 -d nginx`

and got the same errror:
`
docker: Error response from daemon: failed to initialize logging driver: error creating logger: error creating loki logger: unable to load specified CA cert /cacrt.pem: open /cacrt.pem: no such file or directory.`

**Comment by 3Xpl0it3r** [comment]
I will look into this.

**Comment by 3Xpl0it3r** [comment]
hi ,I look into this ,the docker plugin binary is running in an different pid namespace and different mount namespace, that you can execute docker plugin inspect Loki and you will find it 
```bash
[root@3xpl0it3r 15240]# ls /var/lib/docker/plugins/0023a224b73967b271758afbff0d37cf6933f97bc52d429c67af11f38ec44a36/rootfs/
bin  dev  etc  home  lib  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
[root@3xpl0it3r 15240]# ls /var/lib/docker/plugins/0023a224b73967b271758afbff0d37cf6933f97bc52d429c67af11f38ec44a36/rootfs/bin/
arch      busybox  chown  df             dumpkmap  false    fsync   gzip      ipcalc    linux32  ls        mknod   mountpoint  nice   pipe_progress  reformime  run-parts  sh     su     true    watch
ash       cat      cp     dmesg          echo      fatattr  getopt  hostname  kbd_mode  linux64  lzop      mktemp  mpstat      pidof  printenv       rev        sed        sleep  sync   umount  zcat
base64    chgrp    date   dnsdomainname  ed        fdflush  grep    ionice    kill      ln       makemime  more    mv          ping   ps             rm         setpriv    stat   tar    uname
bbconfig  chmod    dd     docker-driver  egrep     fgrep    gunzip  iostat    link      login    mkdir     mount   netstat     ping6  pwd            rmdir      setserial  stty   touch  usleep
```
so you should put you cacert in <docker-pluging-rootfs>/cacert

I will try to improve it.
