### ISSUE TITLE
Promtail - fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by dilshann** [grafana/loki#3729]
Hi,

I'm trying to start the Promtail service but every time it failed with "fatal error: runtime: out of memory"
Herewith attached the same error information
[promtail-error-info.txt](https://github.com/grafana/loki/files/6488851/promtail-error-info.txt)

server -: AWS linux ec2

Memory information
[root@ip-]# free -m
              total        used        free      shared  buff/cache   available
Mem:           3884         885        2756           0         242        2783
Swap:             0           0           0

[root@ip-]# ./promtail --version
promtail, version 1.6.1 (branch: HEAD, revision: 623858df)
  build user:       root@dd6ba3f86fac
  build date:       2020-08-24T19:10:42Z
  go version:       go1.14.2

Promtail config file

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
 - url: http://x.x.x.x:3100/loki/api/v1/push

scrape_configs:
 - job_name: Test-Job
   pipeline_stages:
   static_configs:
   - targets:
      - localhost
     labels:
      job: Test-Job-Log
      host: x.x.x.x
      __path__: /var/log/app/application.log

Can you please help to sort out this issue.

--
Thank you
Dilshan

**Comment by dannykopping** [comment]
Please ask questions you have in the mailing list: https://groups.google.com/forum/#!forum/lokiproject

Or join our #loki slack channel at http://slack.raintank.io/
