### ISSUE TITLE
Docs feedback: /clients/promtail/stages/regex.md

### ISSUE THREAD

**Issue by smilelikeshit** [grafana/loki#3737]
2019-01-01T01:00:00.000000001Z stderr P i'm a log message!

using regex = ^(?s)(?P<time>\\S+?) (?P<stream>stdout|stderr) (?P<flags>\\S+?) (?P<content>.*)  doesn't work . please fix

**Comment by 3Xpl0it3r** [comment]
in fact it worked, the group data that parsed by regex will stored to extract Data, the doc is https://grafana.com/docs/loki/latest/clients/promtail/stages/regex/
update to latest version Promtail --log.level debug  will display extracted data

**Comment by smilelikeshit** [comment]
thank you @3Xpl0it3r
