### ISSUE TITLE
Access to original (unparsed) message in line_format template

### ISSUE THREAD

**Issue by JNevrly** [grafana/loki#3754]
**Is your feature request related to a problem? Please describe.**
Currently, there is no way to access the original (unparsed) message in the `line_format` filter. (Or, if there is, I could not find any documentation). 
```
... | line_format "{{.log_label1}}, {{.log_label2}}: {{<some way to show the entire original log entry>}}"
```

**Describe the solution you'd like**
A pre-defined label, such as `.original_log` that could be used to access the original log entry:
```
... | line_format "{{.log_label1}}, {{.log_label2}}: {{.original_log}}"
```

**Describe alternatives you've considered**
The only alternative known to me is to use [capture_all regex to create a parsed field](https://stackoverflow.com/questions/66784344/get-original-entry-value-in-logql-line-format). Seems as unnecessary step to employ regex filter for, plus it complicates things when regex filter is actually used for other parsing.

**Comment by cyriltovena** [comment]
The problem currently is that having this field will create an overhead.

You could use multiple regexp stage.

```
...| regexp "(?P<original_log>.*)" | regexp "another regexp expr" | line_format "{{.log_label1}}, {{.log_label2}}: {{.original_log}}"
```

WDYT ?

What's nice with this is that this is opt-in and in the future we'll have parser that can catch all and be more efficient than regexp.

**Comment by JNevrly** [comment]
Thanks! I've actually arrived to this form as well (took me some time to realize I can layer regexp stages like that ;)). So I agree it's a working interim solution.

However, I also think that an improved `line_format` parser would not only be more efficient, but also more _understandable_ solution, as it took me quite some time to arrive to a working solution for something that seems like a trivial functionality.

**Comment by cyriltovena** [comment]
Yes I don't disagree but the change is a bit complex to not make everyone pay for it.

**Comment by slim-bean** [comment]
In Loki 2.3 and newer you can use the pattern parser to accomplish this as well and it should be faster than regex for Loki to execute:

```
{app="cainjector"} | pattern `<message>` | line_format " foo {{.message}}"
```

I know the stalebot closed this but this is still a very interesting issue, I added the revivable tag as this is worth having IMO we just need to figure out how to do it with good performance as Cyril mentioned.

**Comment by JNevrly** [comment]
Thanks for keeping looking into this! The pattern parser looks interesting, but is it documented somewhere? I tried to look it up in LogQL docs but found no mention of it...

**Comment by slim-bean** [comment]
As of right now it's unreleased, I cheated in that comment and referenced the next release :)

You can find the docs under the "next" dropdown which is for unreleased changes: https://grafana.com/docs/loki/next/logql/#pattern

Next release coming soon! within the next couple weeks.
