### ISSUE TITLE
Multi cluster log management

### ISSUE THREAD

**Issue by cloudcafetech** [grafana/loki#3776]
Does Loki support ```remote_write``` similar like Prometheus for multiple cluster log management.

**Comment by dannykopping** [comment]
You may submit questions in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

**NOTE: All questions submitted as issues will be closed.**
