### ISSUE TITLE
Kubernetes logs to s3 bucket using loki 

### ISSUE THREAD

**Issue by jaya-rama** [grafana/loki#3783]
can someone say how to deploy loki-stack in kubernetes  and store logs in S3 buckets using helm or using yaml files

**Comment by dannykopping** [comment]
You may submit questions in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

**NOTE: All questions submitted as issues will be closed.**
