### ISSUE TITLE
Queriers died due to lack of space 

### ISSUE THREAD

**Issue by james-callahan** [grafana/loki#3787]
**Describe the bug**

We were unable to run any loki queries. Checking logs (via `kubectl logs`) I found that they were full of e.g.:
> level=error ts=2021-06-02T04:51:03.396298288Z caller=chunk_store.go:543 org_id=fake traceID=757220130bc46841 msg="error querying storage" err="mkdir /data/boltdb-cache/loki_index_18780: no space left on device"

We were able to get things up and running again by increasing the size of the /data PVC.

**Expected behavior**
1. some sort of warning that space is running out? perhaps a recommended alert config?
2. queriers shouldn't hard-fail when they run out of space: the storage appears to be a cache: why wasn't the cache cleared when the space was low?
3. docs should have guidance on how much storage queriers need

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: kustomize + ArgoCD

**Screenshots, Promtail config, or terminal output**

Slowly queriers died; then came back up again after I grew their PVC:
![image](https://user-images.githubusercontent.com/35791147/120426221-037cb980-c3b3-11eb-8d61-1623ccf78b15.png)

**Comment by dannykopping** [comment]
Hey @james-callahan 

That's an unfortunate situation!

Let's address your requests in order:

> 1. some sort of warning that space is running out? perhaps a recommended alert config?

We _could_ add a warning if the queriers run out of space (you could say we already do with the `no space left on device` error in the logs), however there are many issues that can occur with storage such as permission issues, too many open files, etc - most of which are out of our control. The storage layer is out of scope for Loki; Loki assumes that storage is always available and has available resources. You will need to configure some alerts based on your own storage, unfortunately.

> 2. queriers shouldn't hard-fail when they run out of space: the storage appears to be a cache: why wasn't the cache cleared when the space was low?

The storage that queriers query is not a cache; the queriers query chunks out of storage and chunks store all logs ingested into the database.

> 3. docs should have guidance on how much storage queriers need

Again, we'd love to be more helpful here but this is entirely dependent on your situation.
That said, if you ingest ~10GB of logs a day, you'll need about ~50GB of object storage for 30 days retention; it's a bit inexact since log data is so variable.

Hope that helps.

**Comment by james-callahan** [comment]
>  The storage layer is out of scope for Loki; Loki assumes that storage is always available and has available resources.

By default all the deployment scripts set the PV at 10GB.
https://github.com/grafana/loki/blob/490c19e38c2e78eee8a73541ab4670ed28fb3945/production/ksonnet/loki/config.libsonnet#L23


> The storage that queriers query is not a cache

Then why is it called `boltdb-cache`?

>  That said, if you ingest ~10GB of logs a day, you'll need about ~50GB of object storage for 30 days retention; it's a bit inexact since log data is so variable.

I think you may have confused this question with a different one: this issue is about the boltdb-cache; not the actual primary storage of logs.

**Comment by dannykopping** [comment]
Apologies @james-callahan - I missed the `boltdb-cache` bit in the error message; I shouldn't answer issues passed my bedtime :innocent: 

> By default all the deployment scripts set the PV at 10GB.

Indeed, but we can't predict how much will be needed - it's up to the user to configure a size that's appropriate to their workloads.

For the boltdb-cache, you can specify the `boltdb.shipper.cache-ttl` flag, which configures the TTL for boltdb files stored in cache for queries. By default, this is 24 hours.

We would also recommend setting up alerts for when your disks are approaching their capacity.

We use the following alert definition internally to predict if the disk will be full soon:

```promql
(
  kubelet_volume_stats_available_bytes{job="kube-system/kubelet"}
/
  kubelet_volume_stats_capacity_bytes{job="kube-system/kubelet"}
) < 0.20
and
predict_linear(kubelet_volume_stats_available_bytes{job="kube-system/kubelet"}[2h], 6 * 3600) < 0
```

**Comment by james-callahan** [comment]
@dannykopping why not have e.g. the default set to 50Gb?

However, this issue was sort of meant to be asking for a feature: why don't we automatically clean out the cache a bit if we get the out-of-space error?

Alternatively: how can a loki operator predict how much boltdb-cache they need?

**Comment by dannykopping** [comment]
As I said, it all depends on your workload. 50GB may be right for you but will be a waste of money for someone else.

> However, this issue was sort of meant to be asking for a feature: why don't we automatically clean out the cache a bit if we get the out-of-space error?

Feel free to submit another issue with that as a feature request (this is reported as a bug currently) :+1: 

Thanks for your submission.
