### ISSUE TITLE
Ruler isn't working with long time range alerting rules

### ISSUE THREAD

**Issue by Hayk96** [grafana/loki#3788]
We are running Loki in microservices mode in the Kubernetes cluster and getting a problem with the Ruler component. The alerting rules work incorrectly when the time range of the alert expression is more than probably ~30 minutes. e.g  `sum(count_over_time({service="my-service"} |= "sign-in" [6h])) < 10` In this case I get a fake alert because Ruler can’t to get the results of the query for the entire time window 6h. As a persistent storage backend, we use Amazon S3 for storing chunks. As I’m understanding it correctly the Ruler can’t reach the Amazon S3 bucket and just gets the query results from the ingesters. Does this problem happen with someone? Is this a known issue?

**Comment by cyriltovena** [comment]
Hello ! 

The ruler should access chunks in s3. But the ruler uses instant queries that are not parallelized so they may just be slow to run. Have you checked the logs of the ruler ?

**Comment by Hayk96** [comment]
Thank you for the response @cyriltovena. 
The logs of the Ruler look ok, no warnings/erros in the logs. Yes, it does instant queries as you already said, I see it in the logs `"range_type":"instant"`.  Can you give any prompts on how I can fix it, where I should look? I could not find that configuration section inside the Ruler config.

**Comment by dannykopping** [comment]
Hey @Hayk96 - GitHub Issues isn't the best place to get support from our team.
We try to keep GitHub Issues strictly for bug reports and feature requests.

Shoot us a message in `#loki` in [Grafana's Public Slack](https://slack.grafana.com/), and we can take it from there.
It'll work better for troubleshooting issues like this.

**Comment by Hayk96** [comment]
Good, I'm closing this issue now, then will post it in [Slack](https://slack.grafana.com/) again by expecting responses from the community.
Thank You.
