### ISSUE TITLE
Possiblity to run a selection of services instead of just "all" or "single"

### ISSUE THREAD

**Issue by gmintoco** [grafana/loki#3801]
**Is your feature request related to a problem? Please describe.**
When using boltdb and filesystem storage in microservices mode it is difficult to implement retention and the compactor because they both need access to the storage (which is on the single ingester).

It would be nice if it was possible to run a selection of services using --target so that compactor, ingester and tablemanager could be all on one node while still offloading query processing to other services.

**Describe the solution you'd like**
Supporting a comman seperated list of services with the --target parameter. ie `--target=ingester,compactor,tablemanager`

**Describe alternatives you've considered**
Just using monolithic mode or moving to a local minio

**Additional context**

**Comment by dannykopping** [comment]
@gmintoco please see the linked PR for the fix.

I think you know this already, but just in case: you should only have a single instance of the `compactor` running:
https://grafana.com/docs/loki/latest/operations/storage/boltdb-shipper/#compactor

HTH :+1:

**Comment by gmintoco** [comment]
Hey @dannykopping thanks a lot! 

And yeah I am aware only a single compactor should be running :) thanks
