### ISSUE TITLE
i can't tail loki log

### ISSUE THREAD

**Issue by kulame** [grafana/loki#3802]
Tailing logs failed: Error response from server: Internal Server Error
 (websocket: bad handshake)

**Describe the bug**

➜  ~ logcli query --tail '{appname="gaia"}' 
ws://172.18.52.141:3100/loki/api/v1/tail?limit=30&query=%7Bappname%3D%22gaia%22%7D&start=1622799938042281360
Tailing logs failed: Error response from server: Internal Server Error
 (websocket: bad handshake)

**Environment:**
➜  ~ logcli --version                       
logcli, version 2.2.1 (branch: HEAD, revision: babea82e)
  build user:       root@e2d295b84e26
  build date:       2021-04-06T00:52:41Z
  go version:       go1.15.3
  platform:         linux/amd64

loki version :2.2.1

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
