### ISSUE TITLE
Not installed loki with tanka

### ISSUE THREAD

**Issue by gespispace** [grafana/loki#3808]
**Describe the bug**
If I try install loki by example in docs, install doesn't work.
Error in the [docs](https://grafana.com/docs/loki/latest/installation/tanka/#deploying)
I think error in jsonnet-bundler. in this [line](https://github.com/jsonnet-bundler/jsonnet-bundler/blob/dafc283219baad354ecec101ec33070049e3a7b4/spec/v1/deps/git.go
), use only branch master, but in `grafana/loki` not have branch master.

**To Reproduce**
1. jb install github.com/grafana/loki/production/ksonnet/loki

**Expected behavior**
Install lib ksonnet loki

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: jsonnet

**Screenshots, Promtail config, or terminal output**
![image](https://user-images.githubusercontent.com/37763089/120924026-182abb80-c6eb-11eb-89db-9b9826b680b7.png)
![image](https://user-images.githubusercontent.com/37763089/120924036-224cba00-c6eb-11eb-8931-5f966ff9818e.png)

**Comment by kavirajk** [comment]
@gespispace Thanks for reporting!. It's indeed the problem with `jb`. Looks like it understands `master` branch by default whereas Loki uses `main` branch.

One workaround would be to use explicit `main` branch while installing `loki` and `promtail`

1. `jb install github.com/grafana/loki/production/ksonnet/loki@main`
2. `jb install github.com/grafana/loki/production/ksonnet/promtail@main`

We will update the doc soon!

**Comment by gespispace** [comment]
Thank you.
