### ISSUE TITLE
docker-driver: possible race condition in driver.StartLogging

### ISSUE THREAD

**Issue by rgl** [grafana/loki#3818]
It seems the following code has a race condition. The whole function should be under the lock because right now it will be possible to call `StartLogging` multiple times while the main body of that function is executing; this will lead to opening the log file multiple times until the second lock/unlock block is executed.

https://github.com/grafana/loki/blob/110ff6fb9e478da530e45ee7dc41e7b4109a375f/clients/cmd/docker-driver/driver.go#L68-L74

**Comment by kavirajk** [comment]
Hi @rgl 
> right now it will be possible to call StartLogging multiple times while the main body of that function is executing; this will lead to opening the log file multiple times

I actually don't see any problem in calling this `StartLogging` multiple times. May be I miss something? If it's called with same `file`, it will exit at line:72 safely(after unlock). And I don't see any problem with calling it multiple times with different files. It opens the given log file only if it's not already opened.

Would be nice if you can write a test or some example uses cases to show the race condition :)

**Comment by rgl** [comment]
> > right now it will be possible to call StartLogging multiple times while the main body of that function is executing; this will lead to opening the log file multiple times
> 
> I actually don't see any problem in calling this `StartLogging` multiple times. May be I miss something? If it's called with same `file`, it will exit at line:72 safely(after unlock). And I don't see any problem with calling it multiple times with different files. It opens the given log file only if it's not already opened.

It will happen in this scenario:

1. there are two threads calling `StartLogging` with the same file.
2. both threads run to line 75. because the file is not in `d.logs[file]`.
3. now there's a race between them.
    * both will open the same file, the last one, will save it in `d.logs[file]`.
    * both will be consuming the same file.

> Would be nice if you can write a test or some example uses cases to show the race condition :)

Sorry, but I still haven't used (or learned about) the go race detector, so I'll have to pass that for now.

I can provide a PR to fix the race instead :-)

**Comment by cyriltovena** [comment]
I don't think there's a race.

How do you know it is happening ? From what I can read in docker code this file is a unique id.

**Comment by rgl** [comment]
I do not really known how docker calls this code; if you think docker will never parallel call this with the same file, the code is fine as-is.

I only brought that up from a pure code analyses viewpoint.
