### ISSUE TITLE
is it recommended to do a horizontal pod scaling flor loki or shoud it be increase of size whenever we need .If i do a horizontal scaling does the data in grafana show from all the pods?

### ISSUE THREAD

**Issue by soum1234** [grafana/loki#382]
Please ask questions you have in the mailing list: https://groups.google.com/forum/#!forum/lokiproject

Or join our #loki slack channel at http://slack.raintank.io/

**Comment by Kuqd** [comment]
We are doing it whenever we need to, however you can't use the helm chart for scaling right now at least not without a proper ring. The default ring is in memory, so if you scale it they pod won't know each other.

However you can use our ksonnet or you own deployment.

But if autoscaling works for you, I'd say why not, I don't see any issues with that.
