### ISSUE TITLE
alert multi tenant

### ISSUE THREAD

**Issue by shaoxiaowen** [grafana/loki#3836]
install loki with helm and set alert config

`alerting_groups:
  - name: example
    rules:
    - alert: notebook
      expr: sum (count_over_time({job="notebook"} |= "error" [1m])) > 0
      for: 1m`

how to send alert by tenant/org_id?

**Comment by dannykopping** [comment]
Hi

Please note our questions policy on GitHub below.

You may submit questions in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

**NOTE: All questions submitted as issues will be closed.**
