### ISSUE TITLE
Missing logs on Loki when large amounts are sent

### ISSUE THREAD

**Issue by rmondegar** [grafana/loki#3839]
**Describe the bug**
Logs are partially missing when large amounts are sent from Promtail to Loki.
When the amount of logs are reduced considerably, there are no noticeable log losses.

**To Reproduce**
1. Start Promtail docker container (2.0.0)
2. Start Loki docker container (2.0.0)
3. Parse a high volume of logs from Rsyslog

**Expected behavior**
All the logs to be available on Loki side

**Environment:**
- Single server
- Rsyslog -> Promtail -> Loki

**Screenshots, Promtail config, or terminal output**

[promtail.yaml.txt](https://github.com/grafana/loki/files/6634210/promtail.yaml.txt)
[loki.yaml.txt](https://github.com/grafana/loki/files/6634259/loki.yaml.txt)
![image](https://user-images.githubusercontent.com/60993939/121592229-cd71b200-ca10-11eb-8364-d4d9b553d774.png)
![image](https://user-images.githubusercontent.com/60993939/121592301-e1b5af00-ca10-11eb-8693-07e0fa85e74c.png)
![image](https://user-images.githubusercontent.com/60993939/121593017-cb5c2300-ca11-11eb-90cb-ce196f674c0b.png)

If applicable, add any output to help explain your problem.

**Comment by dannykopping** [comment]
Hey @rmondegar 

Are you seeing an error messages in the Loki server's logs?

**Comment by rmondegar** [comment]
Thanks for the quick reply @dannykopping.
We are seeing some warning messages on the promtail side. We assume those warning messages are because we have some application with names longer than 48 characters:

![image](https://user-images.githubusercontent.com/60993939/121594240-2a6e6780-ca13-11eb-842a-fe50e634774e.png)

On the Loki side, we only see informational messages:

![image](https://user-images.githubusercontent.com/60993939/121594526-90f38580-ca13-11eb-9b2a-639b549a2737.png)

**Comment by dannykopping** [comment]
OK.

I think we need to figure out if the issue is on the sending side or the receiving side.

Can you quantify what "a large amount" of logs mean? At what point did the issue go away, and how are you quantifying how many messages are missing?

Wild stab in the dark:
Grafana will by default only show the most recent 1000 log messages, in case you were not aware of that.

Also: any particular reason to be using `2.0.0` instead of the latest release `2.2.1`?

**Comment by rmondegar** [comment]
Hello again,

By large amount I mean 797520 log entries within one hour.
We have noticed that issue goes away when we reduce our logs sent to promtail considerable, to around 15000 per hour.

Yes, I'm aware the default only shows 1000 log messages. We are using the "Live" function to see it in real time.
We first noticed this when one of our alerts was fired because a log message wasn't found.

We are running 2.0.0 for no particular reason. It was considered to be stable until we have noticed the current issue. It's possible to upgrade if this could be part of the issue.

**Comment by dannykopping** [comment]
I would suggest starting with the latest release, although I don't think this is a bug.

I suspect the issue you may be running into is [rate-limiting](https://grafana.com/docs/loki/latest/configuration/#limits_config) (there are some default rate-limits), or your `table-manager` is misconfigured (I don't know enough about this component to be useful here).

**Comment by rmondegar** [comment]
That does make sense. I'll investigate rate-limits further and see what needs to be increased.
Is there a way of telling which rate-limit am I hitting currently?

**Comment by dannykopping** [comment]
Yes, we have these two metrics: https://github.com/grafana/loki/blob/main/pkg/validation/validate.go#L47

- `loki_discarded_bytes_total`
- `loki_discarded_samples_total`

At GrafanaLabs, we have a recording rule which tracks our customers' rate-limited traffic:

```yaml
...
  - expr: sum(label_replace(rate(loki_discarded_samples_total[5m]), "id", "$1", "tenant", "(.*)")) by (id, namespace, reason)
    record: samples_discarded_per_second
...
```

**Comment by rmondegar** [comment]
Thanks @dannykopping. I'll try it with 2.2.1 and increasing the metrics you have pointed out.

**Comment by rmondegar** [comment]
Hi @dannykopping. I have set up loki/promtail 2.2.1 and started scrapping Loki metrics with Prometheus.
I can't find the metrics you mentioned:

![image](https://user-images.githubusercontent.com/60993939/121701491-563b2d00-caa7-11eb-87e6-cc616f9f5967.png)

Do I have to do anything else to enable those metrics? If there is any documentation on this, please point me to that.

**Comment by dannykopping** [comment]
I believe those metrics will only show up if you've actually hit the limits.
I think I might have reached the end of my usefulness here (I'm still new to the project).

@cyriltovena / @sandeepsukhani would you be able to assist here?

**Comment by rmondegar** [comment]
Hello @dannykopping. We have figured out the root cause.
We are sending APPNAMES larger than 47 characters from Rsyslog to Promtail. When this happens, it seems that Promtail momentarily drops every log received, including non-offending entries.
This became more noticeable once we introduced more hosts with APPNAMES that are above the limit.

(Rsyslog side)
![image](https://user-images.githubusercontent.com/60993939/122292962-eb398e00-cecc-11eb-9987-f9b46d0a84d3.png)

(Promtail side)
![image](https://user-images.githubusercontent.com/60993939/122292803-c218fd80-cecc-11eb-8c93-a0ecf673b363.png)

To prevent this from happening, we have created a sanitizing rule in our Rsyslog in order to trim any APPNAME longer than 47 characters on the logs sent to Promtail, using the following:

```
set $.APPNAME47 = substring($app-name, 0, 47);

template(name="syslog_to_promtail_47_characters" type="string"
     string="<%PRI%>1 %TIMESTAMP:::date-rfc3339% %HOSTNAME% %$.APPNAME47% %PROCID% %MSGID% %STRUCTURED-DATA% %msg%\n")

*.*  action(
    type="omfwd"
    target="127.0.0.1"
    port="1514"
    protocol="tcp"
    tcp_framing="octet-counted"
    action.resumeRetryCount="100"
    queue.type="linkedList"
    queue.size="10000"
    queue.filename="srvrfwd"
    queue.saveonshutdown="on"
    Template="syslog_to_promtail_47_characters"
)
```

I'm still interested in the metrics you have mentioned in order to monitor the health of our Loki instance, but the original issue can now be considered closed.

**Comment by dannykopping** [comment]
Amazing find @rmondegar!

According to the [syslog RFC](https://datatracker.ietf.org/doc/html/rfc5424#section-6):
```
APP-NAME        = NILVALUE / 1*48PRINTUSASCII
```

([source](https://github.com/influxdata/telegraf/issues/7100))

This also solves the mystery why those metrics never showed up - the logs never made it to Loki; they were dropped on the floor by Promtail.

Since this is on Promtail's side, you could confirm using the `promtail_dropped_entries_total` metric.
([here](https://github.com/grafana/loki/blob/main/clients/pkg/promtail/client/client.go#L58) are all the available Promtail metrics)

Thanks for letting us know.
This is what OSS is all about!
