### ISSUE TITLE
Promtail EC2 permissions

### ISSUE THREAD

**Issue by ust-ops** [grafana/loki#3845]
What are the permissions to grant, for the ACCESS_KEY and SECRET_KEY when setting up Promtail on EC2 machine?

Key / Role ARL will set on ec2_sd_config section of YML file

**Comment by dannykopping** [comment]
Thank you for your question.
Please note our questions policy on GitHub below.

You may submit questions in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

**NOTE: All questions submitted as issues will be closed.**
