### ISSUE TITLE
docker-driver: log labels set at the dockerd level

### ISSUE THREAD

**Issue by rgl** [grafana/loki#3847]
**Description** 

When I set some labels at the dockerd level I would like to also send them to loki.

**Describe the solution you'd like**

Currently the `labels` setting only looks for labels in the container, but maybe it should also look into dockerd labels?

**Describe alternatives you've considered**

`loki-external-labels` and `loki-relabel-config` do not seem to allow this.

**Comment by kavirajk** [comment]
AFAIU, we cannot get access to daemon labels. And I think that's the constraints comes with docker driver plugin model.

I see we can add labels at two points
1. While configuring the loki log driver via `log-opts` as explained [here](https://docs.docker.com/config/containers/logging/configure/)
2. And during runtime. But during runtime, all the docker driver plugin model have access to only the following struct as explained [here](https://docs.docker.com/engine/extend/plugins_logging/)
```
type Info struct {
	Config              map[string]string
	ContainerID         string
	ContainerName       string
	ContainerEntrypoint string
	ContainerArgs       []string
	ContainerImageID    string
	ContainerImageName  string
	ContainerCreated    time.Time
	ContainerEnv        []string
	ContainerLabels     map[string]string
	LogPath             string
	DaemonName          string
}
```
As you can see, look like we have access to only `ContainerLabels`. No daemon labels.

But that's my understanding! :)

**Comment by rgl** [comment]
Thank you for pointing me to look into those links. I now understand all of this better!

And indeed, looking at the docker plugin code ([which is still the same in moby](https://github.com/moby/moby/blob/master/daemon/logger/loginfo.go#L11-L25)), there are is no way to get the daemon labels. Will do it with `loki-external-labels`.
