### ISSUE TITLE
i have the loki server which has chunks and indexes .Now if i want to query the boltdb , how can i do that.pls give me some guide  or link on boltdb query

### ISSUE THREAD

**Issue by soum1234** [grafana/loki#385]
Please ask questions you have in the mailing list: https://groups.google.com/forum/#!forum/lokiproject

Or join our #loki slack channel at http://slack.raintank.io/

**Comment by Kuqd** [comment]
There is a client here https://github.com/boltdb/bolt/blob/master/cmd/bolt/main.go but boltdb is a very low level go key value store that Loki used to store chunks and indexes. If you want to query logs you should use the logcli provided or just use grafana with Loki as datasource.

https://m.youtube.com/watch?v=ENM2f1QZam8 Here is a demo
