### ISSUE TITLE
Running Loki distributed with Cassandra I get this error message: caller=tcp_transport.go:289 "TCPTransport unknown message type" msgType=G

### ISSUE THREAD

**Issue by data-dude** [grafana/loki#3853]
**Describe the bug**
Running Loki distributed with Cassandra I get this error message: loki "unknown message type" msgType=G

**To Reproduce**
1. Install Loki distributed with Cassandra
2. Run promtail to ingest data
3. Look at logs

**Expected behavior**
I expect not to see this error about every second in the Loki distributor logs

**Environment:**
 - Infrastructure: k8s 1.19.3
 - Deployment tool: Helm3

**Screenshots, Promtail config, or terminal output**
Unfortunately this is running on a closed network and I can't share things like screenshots. 

Everything seems to be fine otherwise.  I just get these messages about every second.

**Comment by pschulten** [comment]
@data-dude 
I have the same errors in my logs. 
After setting `log.level` to `debug` and `memberlist.transport-debug`to `true` and grepping for the error with `-B1`
I get:
```
--
loki-querier-74664965cb-hddhw loki level=debug ts=2021-09-20T18:32:54.823013146Z caller=tcp_transport.go:234 msg="TCPTransport: New connection" addr=10.0.2.190:56860
loki-querier-74664965cb-hddhw loki level=error ts=2021-09-20T18:32:54.823325191Z caller=tcp_transport.go:313 msg="TCPTransport: unknown message type" msgType=G
--
loki-querier-74664965cb-hddhw loki level=debug ts=2021-09-20T18:32:56.167488268Z caller=tcp_transport.go:234 msg="TCPTransport: New connection" addr=10.0.5.231:42144
loki-querier-74664965cb-hddhw loki level=error ts=2021-09-20T18:32:56.16763425Z caller=tcp_transport.go:313 msg="TCPTransport: unknown message type" msgType=G
--
```
It's coming from the prometheis running in my cluster :) so I guess the error is safe to ignore.
Maybe @dannykopping can shed some light on this?

**Comment by pschulten** [comment]
This error went away after I put the right selector into the servicemonitor

**Comment by step-baby** [comment]
@pschulten I have the same errors in my logs. Can you tell me how to deal with it in detail

**Comment by benzyonts** [comment]
@step-baby @pschulten
if you are using Prometheus scape Annotations try changing the "prometheus.io/port" to port number instead of name:
`
podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3100"
`
for me the prometheus scraped all the available ports instead of the only one i selected via the annotation.

you can verify if this is your problem by connection to the prometheus dashboard:
`
kubectl -n monitoring port-forward svc/prometheus-server 8080:80
browse to: http://127.0.0.1:8080/targets#job-kubernetes-pods
search for Loki endpoints with State Down
`
