### ISSUE TITLE
Logcli doesn't do retries on timeout failures

### ISSUE THREAD

**Issue by ronensc** [grafana/loki#3855]
**Describe the bug**
I'm using logcli to download a large volume of logs from loki in batches.
This might take a long time to complete. Unfortunately, logcli stops on the first error it encounters, rather then doing retries.

**To Reproduce**
1. Started Loki on a limited resources cluster.
2. Query using logcli.

**Expected behavior**
I was expecting logcli to do a retry on a timeout error and proceed with the query.

**Proposed Simple Solution**
A very simple solution would be to replace the following `log.Fatalf()` with `log.Println()` followed by a `continue` statement.
https://github.com/grafana/loki/blob/bdee4a37417f6c3f5e1087c6353866c046b5a42c/pkg/logcli/query/query.go#L104

**Environment:**
 - Infrastructure: OpenShift cluster
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**

```
$ logcli query '{filename="XXX.json"}' --batch=50000 --limit=5000000          
Query failed: Error response from server: <html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>                                                                                                                                                                                                     (<nil>)     
```

**Comment by vyzigold** [comment]
I think your solution might end in infinite loop when the server never responds correctly, but maybe --retries _n_ flag might be a better solution, so it would retry each query at most _n_ times when getting error response from the server before stopping. So it would look similar to this.
```
logcli query '{filename="XXX.json"}' --batch=50000 --limit=5000000 --retries 2
Query failed: Error response from server: <html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>

...output successfully continues...
```
