### ISSUE TITLE
Support Full-Range Histograms for Log Counts over a certain period of time

### ISSUE THREAD

**Issue by sherifkayad** [grafana/loki#3858]
**Is your feature request related to a problem? Please describe.**
As a developer / tester / Loki user from the Grafana Explore view, I would like to see the volume of logs generated / available at a certain time frame.

Currently Grafana only shows the volume of the latest 1000 log entries and it doesn't respect the full time range that the user selected for the Histogram view.

**Describe the solution you'd like**
Basically I want Loki to support the "Full-Range Histograms" query that Grafana does to visualize the volume over the whole time frame that the user selects. (Check the screenshot attached)

**Describe alternatives you've considered**
No alternatives here. It's a fact that people now (with Grafana 8.x) can paginate through older logs if needed, however, it's definitely necessary to see the volume of logs available at a certain time range.

For example one of our critical use cases is to drill down in time frames when there's a big peak in logs in a certain time frame.

**Additional context**
![image](https://user-images.githubusercontent.com/8362784/122195915-0b4e5a80-ce97-11eb-9498-d4fbb2b57339.png)

This issue is related to:
- #3119
- #115
- #361
- #115
- #2226 
- https://github.com/grafana/grafana/pull/33259
- https://github.com/grafana/grafana/issues/19949
- https://github.com/grafana/grafana/issues/26808
- https://github.com/grafana/grafana/issues/28844

**Comment by sherifkayad** [comment]
@slim-bean maybe something to look at .. Happy to discuss further if needed.

**Comment by sherifkayad** [comment]
@slim-bean can you check this one? .. It's somehow marked as stale ..

**Comment by RmStorm** [comment]
Hello! I just wrote a rather [large comment](https://github.com/grafana/grafana/issues/19949#issuecomment-907841202) in the related Grafana thread that I think this is a severe issue for usability! Is there anything I can do to help out with getting this implemented? Is there someone with knowledge of the relevant pieces of code that can point out to me how to go about implementing this functionality?

**Comment by sherifkayad** [comment]
Keeping the issue alive

**Comment by sherifkayad** [comment]
Seems like the PR https://github.com/grafana/grafana/pull/39327 (issue https://github.com/grafana/grafana/issues/19949) will address this issue here. Closing this ticket

**Comment by 09jvilla** [comment]
@wuzhihui1123 @r0bj how about yall?

**Comment by 09jvilla** [comment]
@RmStorm same question to you

**Comment by sherifkayad** [comment]
@09jvilla I tried it and I really like it. Also lots of our teams are extremely happy with this feature in place.

**Comment by 09jvilla** [comment]
That's great to hear @sherifkayad !

I know that we implemented it with some protections to avoid overwhelming the Loki backend. Specifically, the histogram will fail to load if the query required to build the histogram takes longer than 10s. Sounds like this hasn't happened very frequently for you? If so, that's also great to hear.

**Comment by sherifkayad** [comment]
@09jvilla welllll 😄 .. it happened a couple of times actually and it's not the best thing ever .. i think it would be great if the value can be configurable and then one could see what value would be a good compromise between getting the results and overwhelming Loki.

I actually wanted to wait a bit on further development efforts there .. but definitely great to know if you guys plan to enable that via a configuration value. Let me know if I need to open a ticket for that.

Thanks for the reminder btw 👍

**Comment by r0bj** [comment]
@09jvilla Thanks for this feature, this is a significant and important improvement. However we definitely need a parameter to tune backend timeout, 10s is not enough for our clusters. We often see timeout.

**Comment by 09jvilla** [comment]
Thanks @sherifkayad and @r0bj for your input. We have been discussing internally ways to reduce the frequency of the backend timeout - a tuning parameter is one option, but there are other ways to solve this as well (e.g., optimize the code path required to populate the histogram). Stay tuned as we might be asking for some input from the community on our different options. 

Besides the pain around the times where the histogram doesn't load, is there any other feedback you have or anything else that has stood out to you (good or bad) about the histogram changes? Also, was it sufficiently clear to you why the histogram wasn't loading?

**Comment by sherifkayad** [comment]
@09jvilla I think the only thing that stood out was the discussion here https://github.com/grafana/grafana/discussions/43274 .. Basically the Volume Histogram can't parse the log levels from any field other than the `level` field .. which isn't the case in the Log Panel .. I initially reported that as an issue and then it was moved to a discussion. I hope you have that on your radar

**Comment by 09jvilla** [comment]
Got it - thanks @sherifkayad - I hadn't been aware of that request but will take a closer look.

**Comment by 09jvilla** [comment]
@sherifkayad -- One more question looping back to what I mentioned before:

> was it sufficiently clear to you why the histogram wasn't loading?

As a short term improvement, we were wondering if we need to improve the way we indicate to the user that the histogram has failed to load and why this happened. What was your experience like?

**Comment by sherifkayad** [comment]
@09jvilla At first it wasn't clear for us why this happens, then we came across the answer in the community forum here https://community.grafana.com/t/increasing-timeout-query-to-loki-datasource/58582/6 that explained the reason and that the timeout for now is basically hardcoded. That's when the error started to make sense.

In my view it would be nice to make it clear in the log message that this is an experimental feature and "inefficient" queries needing more than 10 seconds will fail to render the volume histogram. I mean the current message `Request timed-out. Please make your query more specific and try again.` is a bit too vague for normal users e.g. some of our development team members that just act from a plain "standard user" point of view.

**Comment by 09jvilla** [comment]
Thanks for the input @sherifkayad . I think your suggestion falls into the bucket of how we might look to make the timeout more configurable for users, and back to my earlier comment, we haven't decided if this is the route we want to pursue, or whether we'd rather just leave as is for now and focus on figuring out how to get a greater fraction of the log volume requests to complete. 

We'll share more when we know more and/or when we're looking for some more feedback. Thanks!
