### ISSUE TITLE
`parallelise_shardable_queries` should be true by default

### ISSUE THREAD

**Issue by james-callahan** [grafana/loki#3861]
Why is `parallelise_shardable_queries` not turned on by default?
https://github.com/grafana/loki/blob/6d026d211de2000974ed4898937986145e04b241/docs/sources/configuration/_index.md#L344

**Describe the solution you'd like**
The default for `parallelise_shardable_queries` should be true.

**Additional context**

https://app.slack.com/client/T05675Y01/CEPJRLQNL?cdn_fallback=2

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.

PS: the link you provided just goes to the Loki channel - not sure which message you were referring to there.

**Comment by james-callahan** [comment]
> We try to keep GitHub issues strictly for bug reports and feature requests.

Is this not a feature request?



> PS: the link you provided just goes to the Loki channel - not sure which message you were referring to there.

It goes to specifically to a thread; screenshot:
![image](https://user-images.githubusercontent.com/35791147/122380606-65d8db00-cfab-11eb-90dc-c2cd81b6faf4.png)

**Comment by dannykopping** [comment]
It doesn't use our [feature request template](https://github.com/grafana/loki/issues/new?assignees=&labels=&template=feature_request.md&title=), but I'll reopen.

That link doesn't work for me, here's my attempt:
https://grafana.slack.com/archives/CEPJRLQNL/p1621837693070900

**Comment by owen-d** [comment]
This is a tough one. While this config certainly helps, it really requires a scaled out read path to be useful. By default, the query frontend will split queries by a time range and if `parallelise_shardable_queries` is enabled, it will then split these intervals based on the index sharding factor (from our schema configs, often 16x). This can easily mean dispatching hundreds or a thousand+ smaller queries. These are executed on queriers according to their own parallelism (ideally derived from available cpu cores), but if there are not enough queriers to accept all these queries, they'll just sit in queue. That's largely why this isn't a default at the moment, does this help?

**Comment by james-callahan** [comment]
@owen-d would it make sense to have it on by default when there is more than one querier node?

**Comment by james-callahan** [comment]
.

**Comment by owen-d** [comment]
> would it make sense to have it on by default when there is more than one querier node?
I'd probably start turning this on when deploying ~10+ queriers with 5+ available CPU cores each.
