### ISSUE TITLE
pull all logs from in a time range

### ISSUE THREAD

**Issue by eldaduzman** [grafana/loki#3872]
Hi team grafana!

Just wanted to make sure because it is not straight forward from the documentation,
But what is the correct way to pull logs from a given time range - in a way that guaranties retrieval of all log records?

For example, if I requested an interval I'm not assured to get all the logs in the interval, so how can I safely move to the next interval?

The same goes for the limit, I can limit the number of records to (say) 1000 and then the next request should have the max timestamp from the previous request as it's start input, but then again, I'm not assured to get all records this way either,

So I need to know if there's a recommended way to do that?

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
