### ISSUE TITLE
Latest Loki + Promtail on Grafana v8 DO NOT display colors in the logs (show raw ANSI coloring codes instead)

### ISSUE THREAD

**Issue by waterdrop01** [grafana/loki#3883]
Here is what I see when querying my k8s app logs on Grafana (using Loki as datasource):
![Screenshot from 2021-06-23 00-58-08](https://user-images.githubusercontent.com/47316824/123010379-c9557500-d3be-11eb-840e-d68cbb9b8211.png)

But, here is what "kubectl logs <pod_id>" shows:
![Screenshot from 2021-06-23 00-58-38](https://user-images.githubusercontent.com/47316824/123010449-ed18bb00-d3be-11eb-8fad-34ca53b2fa37.png)

You can see that Grafana displays ANSI color codes, while it should display purple color text...

Do you have the same problem?

Thanks for your help!

**Environment**:
- Grafana version: v8.0.3
- Data source type & version: Loki latest version installed using Helm
- OS Grafana is installed on: Kubernetes

**App**
- That's the logs of a Nodejs app running in Kubernetes, and started using this env:
```
- name: DEBUG_COLORS
              value: 'true'
```

**Comment by waterdrop01** [comment]
Cross posting as this issue seems to be related to Grafana (see https://github.com/grafana/grafana/issues/36051).

I'll close this issue if confirmed.

**Comment by dannykopping** [comment]
Hey @waterdrop01
Thanks for also cross-posting to Grafana; I'll close this one.
