### ISSUE TITLE
Change the default loki storage directory from fake to something like default...

### ISSUE THREAD

**Issue by jbw815** [grafana/loki#3886]
**Is your feature request related to a problem? Please describe.**
It looked really bad when I shared what I was working on with my team and managers to have the directory called fake.  I spent time explaining that it wasn't fake data I was storing.  I then needed to figure out how to do a OrgID to make it read differently.

**Describe the solution you'd like**
Change the default directory created from fake to default or something similar.

**Describe alternatives you've considered**
Make it easier to set the OrgID.

**Additional context**
This should actually help with adoption.  The on-ramp for Loki is pretty easy but the effort to change the OrgID from a poorly named default to something less offensive to my Dev Community was a big effort.

**Comment by chrisbecke** [comment]
Oh is that what that bloody directory is all about.
How do I set a valid looking default OrgID then?
