### ISSUE TITLE
logcli cannot be installed with "go get" (dependency issue?)

### ISSUE THREAD

**Issue by dpkirchner** [grafana/loki#3887]
**Describe the bug**
logcli cannot be installed with the go get command shown in the documentation: `go get github.com/grafana/loki/cmd/logcli`

https://grafana.com/docs/loki/latest/getting-started/logcli/#from-source

**To Reproduce**
1. Install go
2. Run `go get github.com/grafana/loki/cmd/logcli`

**Expected behavior**
I expected logcli to be installed to $GOPATH/bin

**Environment:**
 - Infrastructure: macOS Big Sur
 - Deployment tool: go get `go version go1.16.4 darwin/amd64`

**Screenshots, Promtail config, or terminal output**

Here's the output when installing with an empty $GOPATH: https://gist.github.com/dpkirchner/69c423ea58c0fda846aa636190ee8168

Seems like the grpc/naming or cortex package dependencies may be the culprit. However, my go-fu is poor. I can go get the cortex/pkg/querier/frontend package successfully, for what it's worth.

```
go: downloading github.com/grafana/loki v1.6.1
go: downloading github.com/prometheus/common v0.10.0
go: downloading gopkg.in/alecthomas/kingpin.v2 v2.2.6
go: downloading github.com/gorilla/websocket v1.4.0
go: downloading github.com/json-iterator/go v1.1.10
[...]
go: downloading google.golang.org/grpc v1.38.0
github.com/grafana/loki/cmd/logcli imports
	github.com/grafana/loki/pkg/logcli/query imports
	github.com/grafana/loki/pkg/loki imports
	github.com/cortexproject/cortex/pkg/querier/frontend imports
	google.golang.org/grpc/naming: cannot find module providing package google.golang.org/grpc/naming
go: downloading github.com/Azure/azure-sdk-for-go v0.2.0-beta
go: downloading github.com/blang/semver v1.1.0
[...]
```

**Comment by championj-fz** [comment]
Not sure if you needed a workaround, but I am experiencing the same issue with 'go get ...' but was able to build from source by cloning repo and running `go build ./cmd/logcli` from repo root.

**Comment by josh-m-sharpe** [comment]
real issue:
```
go get github.com/grafana/loki/cmd/logcli
package io/fs: unrecognized import path "io/fs": import path does not begin with hostname
```
