### ISSUE TITLE
use own http/grpc server to get api requests

### ISSUE THREAD

**Issue by vtolstov** [grafana/loki#389]
Does it possible to put log entry with labels via some interface? For example i don't want to use weaveworks server, and use own grpc/http server that get request via api?
In this case i can handle auth via own server (I'm use jwt tokens with custom auth service)

**Comment by tomwilkie** [comment]
Questions like this are best asked on the mailing list (lokiproject@googlegroups.com).

If you want to do custom authentication this is best achieved by putting a custom reverse proxy in front of Loki.  For instance, you could use nginx to do auth and then forward requests from that to loki.
