### ISSUE TITLE
Promtail using stale kubernetes service discovery data

### ISSUE THREAD

**Issue by james-callahan** [grafana/loki#3892]
**Describe the bug**

#### Story

We noticed a couple of days ago that logs for some of our pods were not showing up in loki; while they were available via `kubectl logs`.
Restarting promtail on the affected boxes fixed the issue; and the missing logs came pouring in.

Today it occurred again, and I had a closer look. Eventually I opened the web UI for the promtail running on the node where the pod with missing logs was running. It was showing my missing pod's containers as unhealthy! 
![image](https://user-images.githubusercontent.com/35791147/123215503-e21f7100-d50b-11eb-97ab-081144f2bad0.png)

I checked on the node, and the log file was there; but with a different pod `uid` in the path than the target expected.
The log file had uid `35762179-8418-4c8b-9136-0b62f7602cd6` but hovering on the target in the web UI told me that service discovery had ` __meta_kubernetes_pod_uid=56173637-f002-47fb-9401-f0d09c92b5bd`.
![image](https://user-images.githubusercontent.com/35791147/123215990-6a057b00-d50c-11eb-8c15-170af5d8669c.png)

Looking into old logs: that uid was a previous incarnation of the same pod before it was restarted for some reason. And the new pod happened to get scheduled to the same node.

#### Conjecture

There is a bug somewhere in the service discovery code where if the same pod name is scheduled to the same node, an old (cached) set of labels is used; in this case giving us the wrong ` __meta_kubernetes_pod_uid`

**To Reproduce**
Unknown

**Expected behavior**
Correct pod uid is returned by service discovery

**Environment:**
 - Infrastructure: Kubernetes (AWS EKS 1.20)
 - Deployment tool: kustomize (via https://github.com/BitGo/kustomize-loki)

**Misc:**
Possible previous reports of the same issue:
  - https://github.com/grafana/loki/issues/3359#issue-811438985
  - https://community.grafana.com/t/restarting-a-pod-causes-a-lost-of-target-promtail/46810

**Comment by james-callahan** [comment]
Is someone able to look into this? we have to restrart our promtail pods frequently to avoid missing logs :(

**Comment by rsteneteg** [comment]
Hi, I think this issue will be fixed with this PR https://github.com/grafana/loki/pull/4461

The issue here is that Promtail removes all labels with `__` prefix before it checks if it has the target or not, and since the other labels has not changed it thinks that the target is the same.

The above PR does a check to see if the `__path__` has actually changed, and if so updates the path on the target to cause the tailer to update the path and read from the new path.

**Comment by cstyan** [comment]
@rsteneteg your PR seems to be fixing something else?

@james-callahan can you confirm whether you're still seeing this issue or not? If so it might require a bug report to prometheus itself.

**Comment by cstyan** [comment]
@rsteneteg Ah right, the k8s sd uses filetargets. :+1: seems like the correct fix then. I'll leave this open for a little bit to see if James replies re: if he's still seeing the issue or not. Thanks!

**Comment by james-callahan** [comment]
> @james-callahan can you confirm whether you're still seeing this issue or not? If so it might require a bug report to prometheus itself.

I'm no longer the primary maintainer of a promtail-using cluster.
The issue was only on some pod restarts, so it was non-trivial to replicate; more something that would happen every day or two when we had high node churn (due to e.g. spot instances)

**Comment by rsteneteg** [comment]
> > @james-callahan can you confirm whether you're still seeing this issue or not? If so it might require a bug report to prometheus itself.
> 
> I'm no longer the primary maintainer of a promtail-using cluster. The issue was only on some pod restarts, so it was non-trivial to replicate; more something that would happen every day or two when we had high node churn (due to e.g. spot instances)

This seems to match what I saw, it only happened on statefulsets where the podname is the same between restarts, and if the restart happened quickly. In cases where it took longer for the pod to be recreated it would allow Promtail to remove the filetarget before the new one came up.

**Comment by cstyan** [comment]
@rsteneteg @james-callahan thanks to both of you for your input :+1: I'll close this for now as it seems likely that Roger's PR has fixed this, but we can reopen if someone else reports the same issue.
