### ISSUE TITLE
Confusing error from too-early query

### ISSUE THREAD

**Issue by bboreham** [grafana/loki#3895]
**Describe the bug**

I made a query with dates back in March - from 2021-03-11 21:32:42 to 2021-03-11 22:15:24 UTC - which is before the retention time of this instance.
The response was:
```
invalid query, through < from (2021-03-11 22:15:25 +0000 UTC < 2021-05-24 13:11:23.167533766 +0000 UTC m=-2573205.369511330)
```

I found this confusing because it isn't true that my `through` was before `from`; it introduces a date in May that is not in my query, and the `m=-2573205.369511330` bit at the end isn't helpful.

**To Reproduce**
1. Started Loki `grafana/loki:k52-e08fbd1`
2. [logs not important because there aren't any in the time range]
3. Query: `{cluster="us-central1",namespace="prod"}`

**Expected behavior**
Message should be more like "2021-03-11 22:15:24 UTC is before the retention time of 2021-05-24 13:11:23 UTC".

**Environment:**
 - Infrastructure: this was the Grafana Labs 'loki-ops' instance.
 - Deployment tool: jsonnet

**Comment by QBH-insist** [comment]
hello, i had the same experience，Did you solve it?  Look forward to your reply

**Comment by QBH-insist** [comment]
Hey, My problem has been solved
I set it 20s by mistake
> chunk_store_config:
  max_look_back_period: 20s  change to 0s
