### ISSUE TITLE
How can I use the logQL matched log line within my alert for Alertmanager.

### ISSUE THREAD

**Issue by JessedeJonge** [grafana/loki#3925]
Following the tutorial to alert based on LogQL. Let's say I use the following alert rule https://grafana.com/docs/loki/latest/alerting/#event-alerting. The expression will match some log lines. I know how to use the gathered labels in my Alert template ( $.Labels), but how can I actually use the matched log line within my alert?

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
