### ISSUE TITLE
Support building promtail without systemd/journald support (disabling cgo)

### ISSUE THREAD

**Issue by ecraven** [grafana/loki#3933]
**Describe the bug**
Several linux distributions do not ship with systemd. Building promtail without journald scraping support (which is useless on those distributions anyway) would be useful.

**To Reproduce**
0. run an Alpine linux container (e.g. `podman run -ti  --rm library/alpine`)
1. get the latest loki release
2. run `make promtail`
3. see the following error:
```
CGO_ENABLED=1 go build -ldflags "-s -w -X github.com/grafana/loki/pkg/build.Branch= -X github.com/grafana/loki/pkg/build.Version= -X github.com/grafana/loki/pkg/build.Revision= -X github.com/grafana/loki/pkg/build.BuildUser=root@f71acacd48c9 -X github.com/grafana/loki/pkg/build.BuildDate=2021-07-02T08:20:03Z" -tags netgo -mod=vendor -o cmd/promtail/promtail ./cmd/promtail
# github.com/coreos/go-systemd/sdjournal
vendor/github.com/coreos/go-systemd/sdjournal/journal.go:27:11: fatal error: systemd/sd-journal.h: No such file or directory
   27 | // #include <systemd/sd-journal.h>
      |           ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:222: cmd/promtail/promtail] Error 2
```

It seems that the Makefile *unconditionally* sets `PROMTAIL_CGO` when the system is linux. There should be a way for the user compiling promtail to override this behaviour in the Makefile.
```
# Validate GOHOSTOS=linux && GOOS=linux to use CGO.
ifeq ($(shell go env GOHOSTOS),linux)
ifeq ($(shell go env GOOS),linux)
PROMTAIL_CGO = 1
PROMTAIL_GO_FLAGS = $(DYN_GO_FLAGS)
PROMTAIL_DEBUG_GO_FLAGS = $(DYN_DEBUG_GO_FLAGS)
endif
endif
```

**Expected behavior**
Some way to *disable* PROMTAIL_CGO when compiling on linux.

**Comment by kavirajk** [comment]
Adding bit of a context
https://community.grafana.com/t/build-promtail-without-systemd-support/49811

**Comment by ecraven** [comment]
Maybe it would be enough to only set `PROMTAIL_CGO` to 1 if it isn't explicitly set to 0 in an environment variable?

**Comment by kavirajk** [comment]
Yea exactly!. I think simple fix would be to change `PROMTAIL_CGO = 1` -> `PROMTAIL_CGO ?= 1`. Meaning it try to set the value from ENV variable if set.

PR is welcome :)

**Comment by ecraven** [comment]
I think the other two variables in that block also only need to be set *iff* `PROMTAIL_CGO` is 1. Not sure about the right syntax for that :-/

**Comment by kavirajk** [comment]
You mean `PROMTAIL_GO_FLAGS` and `PROMTAIL_DEBUG_GO_FLAGS`?  I don't think these two variables matters here. I see those are for different purposes.

Curious. does setting `PROMTAIL_CGO=0` able to build without systemd dependency in your case?

**Comment by ecraven** [comment]
@kavirajk no, that does not work, as the value of PROMTAIL_CGO is never read but only ever *set*.
I've just started a PR that should fix this, it works for me. It just uses the normal environment variable CGO_ENABLED, if that is 0, it ignores that entire block ;)

**Comment by kavirajk** [comment]
> no, that does not work, as the value of PROMTAIL_CGO is never read but only ever set

I think I didn't understand what you mean. I see the value of `PROMTAIL_CGO` is read in the promtail build section.

```
clients/cmd/promtail/promtail: $(APP_GO_FILES) $(PROMTAIL_GENERATED_FILE) clients/cmd/promtail/main.go
	CGO_ENABLED=$(PROMTAIL_CGO) go build $(PROMTAIL_GO_FLAGS) -o $@ ./$(@D)
	$(NETGO_CHECK)

clients/cmd/promtail/promtail-debug: $(APP_GO_FILES) clients/pkg/promtail/server/ui/assets_vfsdata.go clients/cmd/promtail/main.go
	CGO_ENABLED=$(PROMTAIL_CGO) go build $(PROMTAIL_DEBUG_GO_FLAGS) -o $@ ./$(@D)
	$(NETGO_CHECK)

```

I like the idea of controlling it via just `CGO_ENABLED` variable. But my concern is why want to disable the complete block?  This also adds other build information like Branch, Version, BuildTime, etc into the promtail binary. which is completely independent of CGO dependency!. Not sure if I miss anything here!

**Comment by ecraven** [comment]
I've reduced the scope to only affect the PROMTAIL_CGO variable, not the others, this seems to work fine (not sure why it didn't before).

**Comment by ecraven** [comment]
> > no, that does not work, as the value of PROMTAIL_CGO is never read but only ever set
> 
> I think I didn't understand what you mean. I see the value of `PROMTAIL_CGO` is read in the promtail build section.

Sorry, I meant the *environment variable* PROMTAIL_CGO (outside of the Makefile) is never read, so even if I set that it doesn't influence anything.
