### ISSUE TITLE
Docs: improve documentation about latest docker tag

### ISSUE THREAD

**Issue by dannykopping** [grafana/loki#3943]
**Is your feature request related to a problem? Please describe.**
It is easy for users to incorrectly assume that `grafana/loki:latest` refers to the latest _released_ version of Loki, but instead refers to the (sometimes unstable) tip of `main`. See #3942 as a case in point.

**Describe the solution you'd like**
We should make it very explicit in our documentation and https://hub.docker.com/r/grafana/loki page that the use of `latest` should be discouraged, unless users accept the instability for whatever reason.

**Describe alternatives you've considered**
We could change `latest` to refer to the latest _released_ version, but this may violate some users' expectations for those users that *know* that `latest` refers to the tip of `main`.

**Additional context**
We could additionally publish a `stable` tag (or `v2-stable`, for example) which does actually point to the latest _released_ version.

**Comment by hhromic** [comment]
I fell for this today as well :(
Keep in mind that many public Docker images use `latest` to refer to the latest *released* version.

Moreover, Grafana itself seems to be using this approach as well (see images below).
So, why not be consistent in the entire `grafana` namespace? :)

---

![image](https://user-images.githubusercontent.com/5802993/124690714-80c7ac80-ded2-11eb-8631-1fed20a0a257.png)

![image](https://user-images.githubusercontent.com/5802993/124690739-891fe780-ded2-11eb-92f1-9c6477a1e5f7.png)
