### ISSUE TITLE
Promtail deployment with SELinux support

### ISSUE THREAD

**Issue by aalcaraz97** [grafana/loki#3945]
**Describe the bug**
I am deploying Promtail in a K3S cluster using the Promtail Helm Chart.
I have deployed K3S using the "--selinux" flag, which enables the containerd SELinux support in the pods of the Kubernetes cluster.
After deploying the Helm Chart, the Promtail pod is failing with CrashLookBackOff errors. 
More precisely, when checking the Promtail logs of the container:
```bash
kubectl logs -n "$PROMTAIL_NAMESPACE" <promtail-pod-name> -c promtail

level=error ts=2021-07-05T17:47:23.524533517Z caller=main.go:108 msg="error creating promtail" error="open /run/promtail/positions.yaml: permission denied"
```

**To Reproduce**
1) Install K3S in a machine with the --selinux flag
2) Deploy Loki and Promtail using the official Helm Charts (Loki Helm Chart: v2.2.0, Promtail Helm Chart: v3.5.0)
3) Promtail pod will be on CrashLookBackOff state after deploying the Promtail Helm Chart

**Expected behavior**
The Promtail pod should be Running after deploying the Promtail Helm Chart

**Environment:**
 - Infrastructure: K3S with --selinux flag activated, K3S version: v1.20.4
 - Deployment tool: Promtail Helm Chart (Promtail image version: v2.2.0, Helm Chart version: v3.5.0)

**Screenshots, Promtail config, or terminal output**
In order to fix the issue, I modified the default podSecurityPolicy that comes in the Promtail Helm Chart and the containerSecurityContext field in the values.yaml, so the Promtail container is run as privileged.
New podSecurityPolicy values:
```yaml
podSecurityPolicy:
  privileged: true
  allowPrivilegeEscalation: true
```
New containerSecurityContext values:
```yaml
containerSecurityContext:
  privileged: true
  allowPrivilegeEscalation: true
```
With these changes, the Promtail pod is Running after deploying the Helm Chart into the cluster. 
Is this the correct way to fix this SELinux issue with the Promtail pod? Any other/better solution that just run the container as privileged?

FYI: Istio CNI plugin has similar issue when using the --selinux flag on Kubernetes. According to some [Github post](https://github.com/istio/istio/pull/32360#issuecomment-825760168), the solution was to run the container as privileged (the same approach I used)

**Comment by 8ball030** [comment]
Thank you alot whoever you are.
You solutions worked flawlessly.

**Comment by VigneshR10** [comment]
Great, the solution is working 🚀 . Much appreciated. 👏
