### ISSUE TITLE
[Docker Image] incorrect default configuration for `rule_path`

### ISSUE THREAD

**Issue by hhromic** [grafana/loki#3952]
**Describe the bug**

I noticed that the following change: https://github.com/grafana/loki/commit/af6e8cb6c9a02be44a978c4933fb17778cb401b7

Modified the value for `rule_path` which was not properly reflected in the `Dockerfile` here:
https://github.com/grafana/loki/blob/055c35e47abb9f1891b6775ad79d5856597d4246/cmd/loki/Dockerfile#L19

This leads to a runtime error with the current Docker image as shown below:
```
$ docker run --rm grafana/loki:2.2.1
(...)
level=info ts=2021-07-07T01:11:43.2350717Z caller=mapper.go:38 msg="cleaning up mapped rules directory" path=/loki/rules-temp
level=error ts=2021-07-07T01:11:43.2352261Z caller=mapper.go:42 msg="unable to read rules directory" path=/loki/rules-temp err="open /loki/rules-temp: no such file or directory"
(...)
```

Note that Loki still continues to operate.

**To Reproduce**
1. Start Loki using Docker: `docker run --rm grafana/loki:2.2.1`
2. Observe the logging output for: `open /loki/rules-temp: no such file or directory`

**Expected behavior**
No errors during Loki initialisation with the provided default settings.

**Environment:**
 - Infrastructure: Docker
 - Deployment tool: Simple Docker Image

**Screenshots, Promtail config, or terminal output**
N/A

**Comment by LinTechSo** [comment]
Hi, any updates ?
