### ISSUE TITLE
[Docker Image] List Rules API failing with default configuration

### ISSUE THREAD

**Issue by hhromic** [grafana/loki#3953]
**Describe the bug**

The List Rules API is not working with the default configuration provided in the Loki Docker Image.
The problem seems to be that, by default, the `local` storage module is used with Loki in single-tenant mode.
However, there is no directory for `fake` in the default `/loki/rules` directory. This results in the List Rules API to fail.

I noticed the problem while migrating to the new Grafana 8.x which includes the new Alert system.
In our setup, the Grafana Alerts page is complaining about all of our Loki datasources with the error:
```
unable to read dir /loki/rules/fake: open /loki/rules/fake: no such file or directory
```

**To Reproduce**
1. Start Loki using Docker: `docker run --rm -p 3100:3100 grafana/loki:2.2.1`
2. Do a request to the List Rules API: `curl localhost:3100/loki/api/v1/rules`
3. Observe curl response: `unable to read dir /loki/rules/fake: open /loki/rules/fake: no such file or directory`

**Expected behavior**
If we start the Loki container with a shell to pre-create `/loki/rules/fake`, then the endpoint works as expected:
```
$ docker run --rm -p 3100:3100 --entrypoint sh grafana/loki:2.2.1 -c 'mkdir -p /loki/rules/fake && loki -config.file=/etc/loki/local-config.yaml'

$ curl localhost:3100/loki/api/v1/rules
no rule groups found
```

Perhaps the Loki `Dockerfile` should create a default `fake` subdirectory in `/loki/rules` here?
https://github.com/grafana/loki/blob/055c35e47abb9f1891b6775ad79d5856597d4246/cmd/loki/Dockerfile#L18

**Environment:**
 - Infrastructure: Docker
 - Deployment tool: Simple Docker Image

**Screenshots, Promtail config, or terminal output**

Here is a screenshot of the errors seen in Grafana (sorry about the ugly anonymisation):
![image](https://user-images.githubusercontent.com/5802993/124736648-200a9500-df0f-11eb-96e1-7062a91aec73.png)

**Comment by hhromic** [comment]
After thinking about this issue a bit more, I am now thinking that creating the directory in the Docker image building might not be the best solution. The main argument is that users _not_ using Loki in standalone mode will end up with an unnecessary `/loki/rules/fake` directory.

So for a better solution, I see two possibilities:
1. Loki auto-creates directories under `/loki/rules` (i.e. the rules dir) on demand by itself.
2. Loki considers missing directories under `/loki/rules` (i.e. the rules dir) as *no rules defined* instead of an error.

I personally think that perhaps option (2) is safer and less invasive to the filesystem. What do you think?

**Comment by owen-d** [comment]
Well put @hhromic - I think (2) makes a lot of sense. This will require a change to Cortex and is reminiscent of [this](https://github.com/cortexproject/cortex/issues/4354) issue, although not exactly the same:.

**Comment by hhromic** [comment]
> This will require a change to Cortex and is reminiscent of [this](https://github.com/cortexproject/cortex/issues/4354) issue, although not exactly the same.

Indeed it looks like actually implementing the Ruler API for local storage would also get rid of the issue reported here. However, as you probably are implying, it is much more work than the ideas I suggested.

If implementing the Ruler API for local storage is on the roadmap, perhaps any work done in my previous suggestions would be wasted effort. I guess it will depend on the timeline for implementing the Ruler API in that case (if any). In the meantime, I guess my original proposal of providing an empty `/loki/rules/fake` directory in the Docker image would be the simplest and easiest solution. This would be removed when the Ruler API for local storage is in place.

**Comment by eKL016** [comment]
I also encountered the issue while using new unified Grafana alerts :(
I agree with this reply.  I wonder if there is any timeline for implementing the Ruler API?

> > This will require a change to Cortex and is reminiscent of [this](https://github.com/cortexproject/cortex/issues/4354) issue, although not exactly the same.
> 
> Indeed it looks like actually implementing the Ruler API for local storage would also get rid of the issue reported here. However, as you probably are implying, it is much more work than the ideas I suggested.
> 
> If implementing the Ruler API for local storage is on the roadmap, perhaps any work done in my previous suggestions would be wasted effort. I guess it will depend on the timeline for implementing the Ruler API in that case (if any). In the meantime, I guess my original proposal of providing an empty `/loki/rules/fake` directory in the Docker image would be the simplest and easiest solution. This would be removed when the Ruler API for local storage is in place.

**Comment by tennox** [comment]
it's not @stale
