### ISSUE TITLE
How to use static tags in logstash output Loki ？

### ISSUE THREAD

**Issue by qiuyuetao** [grafana/loki#3987]
Hello, we want to replace es with Loki. The previous architecture is filebeat, Kafka, logstash, es. We have made the following changes:

1. Logstash install the output Loki plug-in

2. In logstash, change output to

```
loki {

url => " http://loki.logger:3100/loki/api/v1/push "

}
```

3. Loki automatically gets labels from the log, but the monitoring shows that chunks in memory is large and increasing continuously, while chunk size is small and there are many chunks in steam, as shown in the figure below

4. In the official website, I saw that this may be the Loki performance degradation caused by dynamic tags, so I would like to ask how to solve this problem.

5. In addition, there are a lot of random flow errors, with error code of 400

Note: we use the default configuration #

**Comment by adityacs** [comment]
@qiuyuetao Please refer to the doc here https://github.com/grafana/loki/blob/main/docs/sources/clients/logstash/_index.md#usage-and-configuration. You can use the logstash `filter` plugin to add and drop labels. Just copy pasting an example from the doc here

```
input {
  ...
}

filter {
  mutate {
    add_field => {
      "cluster" => "us-central1"
      "job" => "logstash"
    }
    replace => { "type" => "stream"}
    remove_field => ["src"]
  }
}
output {
  loki {
    url => "http://myloki.domain:3100/loki/api/v1/push"
  }
}

```

**Comment by qiuyuetao** [comment]
> @qiuyuetao请参阅此处的文档https://github.com/grafana/loki/blob/main/docs/sources/clients/logstash/_index.md#usage-and-configuration。您可以使用 logstash`filter`插件添加和删除标签。只需从此处复制粘贴文档中的示例
> 
> ```
> input {
>   ...
> }
> 
> filter {
>   mutate {
>     add_field => {
>       "cluster" => "us-central1"
>       "job" => "logstash"
>     }
>     replace => { "type" => "stream"}
>     remove_field => ["src"]
>   }
> }
> output {
>   loki {
>     url => "http://myloki.domain:3100/loki/api/v1/push"
>   }
> }
> ```

**Comment by qiuyuetao** [comment]
> @qiuyuetao请参阅此处的文档https://github.com/grafana/loki/blob/main/docs/sources/clients/logstash/_index.md#usage-and-configuration。您可以使用 logstash`filter`插件添加和删除标签。只需从此处复制粘贴文档中的示例
> 
> ```
> input {
>   ...
> }
> 
> filter {
>   mutate {
>     add_field => {
>       "cluster" => "us-central1"
>       "job" => "logstash"
>     }
>     replace => { "type" => "stream"}
>     remove_field => ["src"]
>   }
> }
> output {
>   loki {
>     url => "http://myloki.domain:3100/loki/api/v1/push"
>   }
> }
> ```

Thank you very much. I did this, but there are many uncertain field combinations and many labels in my log, which makes the performance of Loki very poor. After running for a while, the streams in Loki will occupy the memory until oom
