### ISSUE TITLE
[loki-distributed] Unable to add gateway as a datasource on Kubernetes-hosted Grafana

### ISSUE THREAD

**Issue by hyperyn** [grafana/loki#3988]
**Describe the bug**
Upon deploying the Loki-distributed chart with default values to a Kubernetes cluster using Helm, we are unable to set the gateway service as a datasource for Grafana. E.g. `helm install loki grafana/loki-distributed -n monitoring`

Grafana is being hosted on the same cluster, within the same namespace, and was deployed using the `prometheus-community/kube-prometheus-stack` Helm chart. 

All Loki pods show as healthy, and no errors appear in any of their logs.

We have attempted to add the Grafana datasource using the following endpoint (obtained from `kubectl get services -n monitoring`):
`http://loki-loki-distributed-gateway`
`http://loki-loki-distributed-gateway.monitoring.svc.cluster.local`
`http://<ip of the gateway>`
With `:80` appended, etc.

Everything returns the same error in Grafana: "Loki: Bad Gateway. 502. Bad Gateway".

When using the Loki-stack chart, with the following endpoint, the configuration worked just fine:
`http://loki:3100`

It is worth noting that promtail is able to push just fine using the exact same gateway endpoint (with the necessary nginx route): `http://loki-loki-distributed-gateway/loki/api/v1/push`. Also, `curl`ing the `http://loki-loki-distributed-gateway.monitoring` endpoint from another pod returns a `200 OK`.

Any advice? The documentation is super sparse on this, and all I've gleaned from similar issues using this chart is "point Loki to the gateway", which is what we're trying to do...

**To Reproduce**
1. Deploy the latest loki-distributed chart to Kubernetes using Helm.
2. attempt to add the resultant gateway as a data source in Grafana.

**Expected behavior**
The gateway should successfully be added as a datasource.

**Environment:**
 - Infrastructure: Kubernetes v1.20.5
 - Deployment tool: Helm

**Comment by hyperyn** [comment]
One coffee later, turns out this was just a Grafana thing - the original datasource was set by Prometheus' config and, therefore, couldn't be modified via any other means.

**Comment by Singaalegion** [comment]
Hi @hyperyn, I am getting this error [loki-loki-distributed-ruler.loki.svc.cluster.local could not be resolved (3: Host not found)](https://stackoverflow.com/questions/77043889/loki-loki-distributed-ruler-loki-svc-cluster-local-could-not-be-resolved-3-host). Could you please help me with this issue?
