### ISSUE TITLE
Unable to get logs by using LogCLI

### ISSUE THREAD

**Issue by jaya-rama** [grafana/loki#3989]
I have deployed loki with S3 as object store in kubernetes and I port-forwarded Loki to port 3100 and installed logcli-windows-amd64.exe in windows and executed the command to get logs of namespace logging 
logcli-windows-amd64 query '{namespace="logging"}'

and I got the below as response 
http://localhost:3100/loki/api/v1/query_range?direction=BACKWARD&end=1626163093498191400&limit=30&query=%27%7Bnamespace%3Dlogging%7D%27&start=1626159493498191400
Query failed: Error response from server: parse error at line 1, col 1: invalid char literal
 (<nil>)
can someone help me how to solve this?

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
