### ISSUE TITLE
Feature request: A bucket per tenant

### ISSUE THREAD

**Issue by ronensc** [grafana/loki#4013]
**Is your feature request related to a problem? Please describe.**
Currently, there is no option to separate tenant's data by bucket.

**Describe the solution you'd like**
I would like to have my data of each tenant in its own bucket (and own credentials), rather than in a separate directory in the same bucket.

**Describe alternatives you've considered**

**Additional context**
I found that this was asked in the community forum:
https://community.grafana.com/t/multitenancy-in-loki/50372

and also in the `What do you want from Loki in 2021?` issue: https://github.com/grafana/loki/issues/3119#issuecomment-856943738

**Comment by eranra** [comment]
FYI @periklis
