### ISSUE TITLE
How to split a query into multiple streams, grouped by label?

### ISSUE THREAD

**Issue by waterdrop01** [grafana/loki#4022]
Hello,

I have 3 apps deployed on Kubernetes. 

I would like to query `bytes_rate({app="xxx"}[1m])` for each of the apps, and draw the result as stacked series.

Currently `logql` will -based on the filter/selector- aggregate all data into **one** stream. 

What I'd like to do is split into **multiple** stream, identified by labels such as `app=1`, `app=2`, `app=3`. This would result in 3 series on the chart (similar to how prometheus is splitting by `kubernetes_node` for instance).

Is it possible? Thank you for your help!

**Comment by Berkmann18** [comment]
That would great to know.

**Comment by yeldiRium** [comment]
I would also like to know this.
