### ISSUE TITLE
Bump telegraf dependency to remove go mod consul replace

### ISSUE THREAD

**Issue by jesusvazquez** [grafana/loki#4035]
I was sorting out some dependencies on a project and run into this problem:
```
	github.com/hashicorp/consul/api: ambiguous import: found package github.com/hashicorp/consul/api in multiple modules:
	github.com/hashicorp/consul v1.2.1 (/home/chusi/go/pkg/mod/github.com/hashicorp/consul@v1.2.1/api)
	github.com/hashicorp/consul/api v1.8.1 (/home/chusi/go/pkg/mod/github.com/hashicorp/consul/api@v1.8.1)
```

My code was importing latest available consul but there where some ambiguous imports trying to fetch an older consul version `consul@v1.2.1/api`. So I looked into the go graph dependency to find the following: 
```
❯ go mod graph | grep " github.com/hashicorp/consul@"
github.com/influxdata/telegraf@v1.16.3 github.com/hashicorp/consul@v1.2.1
❯ go mod graph | grep " github.com/influxdata/telegraf@v1.16.3"
github.com/grafana/loki@v1.6.2-0.20210722133053-3e385464c694 github.com/influxdata/telegraf@v1.16.3
``` 

https://github.com/grafana/loki/blob/17f4a73a24c8afc36bcb4e2795c6b1e06d4b95a1/go.mod#L42

https://github.com/grafana/loki/blob/826fdfa3b9c35405e58e5cff3860d4d7500e77a1/go.mod#L95

Because of this loki has to add a replace in go.mod anyone importing loki has to do the same too.

I went ahead and checked telegraf latest version and they've already updated their consul dependency https://github.com/influxdata/telegraf/blob/master/go.mod#L77 so if Loki updates telegraf to [latest](https://github.com/influxdata/telegraf/releases/tag/v1.19.1) we can solve this issue.

**Comment by owen-d** [comment]
Thanks for the research! Would you like to try a PR?

**Comment by jesusvazquez** [comment]
Yes! I'll give a try to this very soon and come back with my findings.
