### ISSUE TITLE
Journal: A "bad message" error results in an infinite hot-loop

### ISSUE THREAD

**Issue by href** [grafana/loki#4053]
**Description**
The systemd journal library may at times follow logs that it cannot process. When that happens, `promtail` enters an infinite loop that will produce the following error messages as fast as it can (with newlines for claritry):

    Jul 23 08:24:35 host promtail[425]:
    level=error
    ts=2021-07-23T06:24:35.747004119Z
    caller=journaltarget.go:185
    msg="received error during sdjournal follow"
    err="failed to iterate journal: bad message"

This is likely related to #2928, which introduced a loop over the journal follow logic.

**Environment**
Systemd 241 and 245

    promtail, version 2.2.1 (branch: HEAD, revision: babea82e)
    build user:       root@e2d295b84e26
    build date:       2021-04-06T00:52:41Z
    go version:       go1.15.3
    platform:         linux/amd64

**Theory**
The intention of #2928 is to skip log entries when "bad message" occurs, but from my study of the source code involved, this is likely not what's happening:

The error clearly bubbles out of `Follow` in the following snippet:
https://github.com/grafana/loki/blob/b4086dfe3350aecf907a5fb6e9f1ce2c0a638d29/clients/pkg/promtail/targets/journal/journaltarget.go#L181-L187

The error is logged and `Follow` is called again. For it to produce a differing result, the current line would have to be skipped at some point, or we are likely reading the same result over and over again (which is what we are observing).

Inside `Follow` the `Read` function is called, which is the function that advances the current cursor here:
https://github.com/grafana/loki/blob/babea82ef558c4b4dc685fd4ca677de1f0a7ee8f/vendor/github.com/coreos/go-systemd/sdjournal/read.go#L138-L147

Internally, this calls `sd_journal_next`, which in turn calls `real_journal_next`:
https://github.com/systemd/systemd/blob/91d0750dbf65e1ffa627fa880c50673a27758cf6/src/libsystemd/sd-journal/sd-journal.c#L816

Towards the end of that function, `journal_file_move_to_object` is called. This is where `EBADMSG` comes from! Unfortunately, reading a bad message does not advance the cursor, as an error forces to function to exit before that:
https://github.com/systemd/systemd/blob/91d0750dbf65e1ffa627fa880c50673a27758cf6/src/libsystemd/sd-journal/sd-journal.c#L861-L867

**Expected Behavior**
Ideally we would like to skip bad messages, but I'm not sure this is possible, as the skip functions systemd offers are really just "next" calls with a counter. It might make sense to treat these errors like end-of-file errors, since this seems to be what `journald` is doing internally:

https://unix.stackexchange.com/a/87862/413524

**Comment by cyriltovena** [comment]
May be one of those two could help https://github.com/coreos/go-systemd/blob/main/sdjournal/journal.go#L572-L606 ? what do you think ?

**Comment by href** [comment]
My impression is that it won't, since `Next` is already called every time `Follow` is called. It seems to be unable to move beyond the bad message.

Interestingly, I can run `journalctl --verify` without issue, so the journal files should be okay. I'm a bit limited in what I can check at the moment though, but I hope I can reliably reproduce this issue soon enough.

**Comment by dannykopping** [comment]
@href please see https://github.com/grafana/loki/pull/4066 and give us your thoughts.
This won't really solve the problem of stepping over bad messages (@cyriltovena and I paired up for an hour on this today and could not reproduce), but it does prevent the hot-loop at the very least.

**Comment by href** [comment]
I haven't been able to reproduce this in the past 24 hours either (before it repeatedly happened on multiple hosts over the course of a few days). What those hosts share is a recent hard reboot, so we suspect that this somehow introduced corrupt journal files. Though we were not able to confirm this theory with `systemctl --verify`.

In any case, I had a look at your PR and to me it looks great. This would certainly defuse the situation and would allow us to go live with `promtail`. We feared that it would repeat in prod, causing our log partitions to quickly fill up. I don't see that happening again with your change. To keep trying every 100ms for other errors seems alright to me.

Thanks a lot for fixing this so quickly! I'm impressed ❤️

**Comment by dannykopping** [comment]
Awesome, thanks for reporting this @href and happy Promtailing :tada:

**Comment by href** [comment]
I was wondering, when will this be included in a release? I didn't see any mention of this in the 2.3.0 change log, so I'm unsure if this made it into it or not.

**Comment by dannykopping** [comment]
@href hhmm, doesn't seem like it was, for some reason.
I'll make sure it's included in the v2.3.1 patch release coming soon

**Comment by href** [comment]
Awesome, thank you!
