### ISSUE TITLE
How to install loki as a cluster with multiple nodes

### ISSUE THREAD

**Issue by ningyougang** [grafana/loki#4054]
For loki installation, there has several methods: https://grafana.com/docs/loki/latest/installation/ 
* Install using Tanka (recommended)
* Install through Helm
* Install through Docker or Docker Compose
* Install and run locally
* Install from source

### 1. Install loki as a cluster with multiple physcial nodes (non-k8s env)
But, does has any way of `install loki in multiple physical nodes`? my requirements as below
* These multiple loki nodes form a whole cluster.
* Any node can handle the write/read request.
* If any one node is shoutdown, does not affect the work of the entire cluster.

###  2. Install loki as a cluster with multiple physcial nodes (k8s env)
I checked, support several ways. e.g. helm, Tanka.

Which one is better?

**Comment by jeschkies** [comment]
Hi,

thanks for the questions. In the `production/docker` folder is a [README](https://github.com/grafana/loki/tree/main/production/docker) with a graph explaining the setup you envision for your first point. You could extract the right commands for Loki from the `docker-compose-ha-memberlist.yaml` there.

As for the second point, we are using the Tanka setup ourselves. So this is the most tested I'd say and would go with that.

Does this answer your questions?
