### ISSUE TITLE
Move `astmapper` into loki

### ISSUE THREAD

**Issue by trevorwhitney** [grafana/loki#4063]
**Is your feature request related to a problem? Please describe.**
Currently, loki depends on the [astmapper](https://github.com/grafana/loki/blob/main/vendor/github.com/cortexproject/cortex/pkg/querier/astmapper/astmapper.go#L165) in cortex. As it is unlikely this is going to change much, it seems like a good candiate to bring into loki directly. This will allow for increased agility if we need to change things for loki, as well as the ability to rename some labels like `__cortex_shard__` to `__loki_shard__`.

**Describe the solution you'd like**
Copy `astmapper` package into loki to sever that cortex dependency.

**Comment by owen-d** [comment]
This seems reasonable, but we'll need to make sure we update all the forked chunk storage code to depend on the new pkg.
