### ISSUE TITLE
expected to rewrite the timestamp using field 'mytime' but failed

### ISSUE THREAD

**Issue by IAMLGT** [grafana/loki#4064]
my loki and promtail version is 2.2.0
promtail config is like this:
![image](https://user-images.githubusercontent.com/53335036/127251644-e5033b80-e3fa-4f61-b386-a3e205d40ae4.png)
expected to rewrite the timestamp using field 'mytime' but failed
my log is like this: 
2021-07-26 08:54:49 INFO 14
but result shows to be:
![image](https://user-images.githubusercontent.com/53335036/127251885-b6aec04c-47fa-4660-a60e-b829e7075a60.png)

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
