### ISSUE TITLE
Query Error

### ISSUE THREAD

**Issue by QBH-insist** [grafana/loki#4065]
**Describe the bug**
It was occoured error frequently when choose range time manually

**To Reproduce**
1. open grafana's website, and choose "last 1 hour" search. result is right
![image](https://user-images.githubusercontent.com/39401478/127252943-fefe1ce3-daf2-4309-956f-78525741761f.png)
`http://ip:port/api/datasources/proxy/1/loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=%7Bservice%3D%22test-service%22%7D&start=1627434922000000000&end=1627438523000000000&step=2`

2. choose same time manually, result is error
![image](https://user-images.githubusercontent.com/39401478/127253084-124c5a71-d487-44cb-ba2a-cd236a1809da.png)

`http://ip:port/api/datasources/proxy/1/loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=%7Bservice%3D%22test-service%22%7D&start=1627434922000000000&end=1627438523000000000&step=2`

3. choose time 2021-07-27 00:00:00 to 2021-07-28 23:59:59, result is right
![image](https://user-images.githubusercontent.com/39401478/127252535-604c8047-7817-410c-a83c-ea1da5aa30e0.png)
`http://ip:port/api/datasources/proxy/1/loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=%7Bservice%3D%22test-service%22%7D&start=1627315200000000000&end=1627488000000000000&step=120`

4.choose time 2021-07-27 00:00:00 to 2021-07-27 23:59:59, result is error
![image](https://user-images.githubusercontent.com/39401478/127252615-a5a95fac-6a9c-416e-9d3f-7be76781f4a6.png)
`http://ip:port/api/datasources/proxy/1/loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=%7Bservice%3D%22test-service%22%7D&start=1627315200000000000&end=1627401600000000000&step=60`

Error Reuslt Log;
Loki: 
![image](https://user-images.githubusercontent.com/39401478/127253494-d11691b9-d1f1-4bd7-90d1-9ec4a5bb39bc.png)
Grafana:
![image](https://user-images.githubusercontent.com/39401478/127253507-76202bdc-e6e6-4a7f-a430-dadeaed4683c.png)

**Expected behavior**
I hope query normally when choose range time manually

**Environment:**
Grafana version: v8.0.6
Data source type & version: Loki v2.2.1

**Screenshots, Promtail config, or terminal output**
**Loki and Grafana deploy on the same machine:**
docker-compose.yml:
![image](https://user-images.githubusercontent.com/39401478/127255113-5891179b-6192-4a1e-b802-57e17cacb1eb.png)

loki.yml
![image](https://user-images.githubusercontent.com/39401478/127254423-13073710-7f2c-4649-bcf8-69df171f4296.png)

promtail.yml
![image](https://user-images.githubusercontent.com/39401478/127255634-ebd6b75b-dada-48a0-bb9a-ebc0ae0e7240.png)

OS：centos 7.9

**Comment by QBH-insist** [comment]
My problem has been solved
I set it 20s by mistake

> chunk_store_config:
max_look_back_period: 20s change to 0s

**Comment by dannykopping** [comment]
Thanks for letting us know @QBH-insist :+1:
