### ISSUE TITLE
count returning back the sum instead of the count in this case

### ISSUE THREAD

**Issue by Phara0h** [grafana/loki#4077]
**Describe the bug**
```js
count(sum(count_over_time({app="foo", environment="production"} |  json [$__interval])) by (ip))
```
in this example, the last operation `count` produces the `sum` of all the values instead of the `count` of the array the previous operation returned.

**To Reproduce**
1. generate some data that has random ips, some having duplicates (simulating web traffic). Make sure the ips are not a label in loki
2.  try to get the real count 
``` js
count(sum(count_over_time({app="foo", environment="production"} |  json [$__interval])) by (ip))
```

**Expected behavior**
the count should count the actual numbers of rows returned from the previous operation instead of summing all the values inside those results

**Environment:**
 - Infrastructure: ec2 running latest version of loki
 - Deployment tool: manual

**Comment by cstyan** [comment]
I've tried a query like this in one of our environments and I'm not seeing the same results you're seeing.

Example:
```
sum(count_over_time({cluster="x",container="y"}[5m])) by (z)
``` 
returns 5 unique series and 
```
count(sum(count_over_time({cluster="x",container="y"}[5m])) by (z))
```
returns the value 5, which is what you're expecting if I'm understanding your description.

**Comment by Phara0h** [comment]
but your not piping with ` |  json` and doing the sum by a label that is created after the parse from `| json`

**Comment by Phara0h** [comment]
still an issue
