### ISSUE TITLE
query error

### ISSUE THREAD

**Issue by tangxy** [grafana/loki#4078]
**Describe the bug**
choose last 5 minutes， query is ok
It was occoured error frequently when choose range last 1 hours or longer

**To Reproduce**
1. loki version 2.2.1
2. curl 'http://grafana-wgc.devops.svc.lakalajr.local/api/datasources/proxy/2/loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=%7Bapplication%3D%22aps-service-flow%22%7D&start=1627606585000000000&end=1627610186000000000&step=2' \
  -H 'Connection: keep-alive' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36' \
  -H 'x-grafana-org-id: 1' \
  -H 'Referer: http://grafana-wgc.devops.svc.lakalajr.local/explore?orgId=1&left=%5B%22now-5m%22,%22now%22,%22Loki%22,%7B%22expr%22:%22%7Bapplication%3D%5C%22aps-service-flow%5C%22%7D%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D' \
  -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,ca;q=0.7' \
  -H 'Cookie: _ga=GA1.2.1265845426.1619685681; grafana_session=246d9a5388d25245c5770a1885cc7ebd' \
  --compressed \
  --insecure

3、loki log:
Jul 30 09:56:25 datacenter21 loki[19506]: level=info ts=2021-07-30T01:56:25.811294043Z caller=metrics.go:91 org_id=fake traceID=1e87745ebac63a6f latency=fast query="{application=\"aps-service-flow\"}" query_type=limited range_type=range length=1h0m1s step=2s duration=13.66145ms status=500 limit=1000 returned_lines=0 throughput=75MB total_bytes=1.0MB
Jul 30 09:56:25 datacenter21 loki[19506]: level=warn ts=2021-07-30T01:56:25.811410706Z caller=logging.go:71 traceID=1e87745ebac63a6f msg="GET /loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=%7Bapplication%3D%22aps-service-flow%22%7D&start=1627606585000000000&end=1627610186000000000&step=2 (500) 14.300607ms Response: \"3 errors: rpc error: code = Unknown desc = object not found in storage; rpc error: code = Unknown desc = object not found in storage; rpc error: code = Unknown desc = object not found in storage\\n\" ws: false; Accept: application/json, text/plain, */*; Accept-Encoding: gzip, deflate; Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,ca;q=0.7; User-Agent: Grafana/7.1.5; X-Forwarded-For: 10.18.233.8, 127.0.0.1, 127.0.0.1; X-Grafana-Org-Id: 1; X-Real-Ip: 10.18.233.8; "
4、grafana display
![image](https://user-images.githubusercontent.com/11514777/127588910-cdda0078-e8de-4c04-a191-a31d4c5c059e.png)

5、loki cluster info： 3 server node，  6 loki instance per server node，  loki-1.yaml

auth_enabled: false
chunk_store_config:
  max_look_back_period: 0s
compactor:
  shared_store: filesystem
  working_directory: /data/data1/loki/boltdb-shipper-compactor
distributor:
  ring:
    kvstore:
      store: etcd
      etcd:
        endpoints:
        - 10.19.165.20:2379
        - 10.19.165.21:2379
        - 10.19.165.22:2379
ingester:
  chunk_block_size: 524288
  chunk_target_size: 1536000
  chunk_idle_period: 30m
  chunk_retain_period: 15m
  max_chunk_age: 1h
  chunk_encoding: snappy
  lifecycler:
    interface_names:
    - bond0
    ring:
      kvstore:
        store: etcd
        etcd: 
          endpoints:
          - 10.19.165.20:2379
          - 10.19.165.21:2379
          - 10.19.165.22:2379
      replication_factor: 1
  max_transfer_retries: 0
limits_config:
  ingestion_rate_mb: 128
  ingestion_burst_size_mb: 168
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
schema_config:
  configs:
  - from: "2021-07-01"
    index:
      period: 24h
      prefix: index_
    object_store: filesystem
    schema: v11
    store: boltdb-shipper
server:
  http_listen_port: 3101
  grpc_listen_port: 9091
storage_config:
  boltdb_shipper:
    active_index_directory: /data/data1/loki/boltdb-shipper-active
    cache_location: /data/data1/loki/boltdb-shipper-cache
    cache_ttl: 24h
    resync_interval: 1m
    shared_store: s3
  filesystem:
    directory: /data/data1/loki/chunks
  aws:
    s3: http://abc:456@10.19.x.x:9000
    s3forcepathstyle: true
    bucketnames: loki
table_manager:
  retention_deletes_enabled: false
  retention_period: 0s

**Expected behavior**
1、query log correct 
2、my config has not right ？

**Environment:**
 - Infrastructure: CentOS Linux release 7.2.1511
 - Deployment tool: manual

**Comment by rt005744** [comment]
我也出现了这样的问题，请问后来你解决了吗
