### ISSUE TITLE
[promtail] Different log labels for pods running in k8s with docker-shim and containderd.

### ISSUE THREAD

**Issue by zbindenren** [grafana/loki#4079]
**Describe the bug**
We have a container that logs k8s events in json format like:

```json
  "metadata": {
    "name": "argocd-server-7f8b844757-dfjbx.1695f83ea50253c2",
    "namespace": "kube-argocd-master",
    "uid": "9ada17e1-a3fc-43cd-8480-913df2ef67c7",
    "resourceVersion": "815007",
    "creationTimestamp": "2021-07-30T08:08:17Z",
    "managedFields": [
      {
        "manager": "kubelet",
        "operation": "Update",
        "apiVersion": "v1",
        "time": "2021-07-30T08:08:17Z",
        "fieldsType": "FieldsV1",
        "fieldsV1": {
          "f:count": {},
          "f:firstTimestamp": {},
          "f:involvedObject": {
            "f:apiVersion": {},
            "f:fieldPath": {},
            "f:kind": {},
            "f:name": {},
            "f:namespace": {},
            "f:resourceVersion": {},
            "f:uid": {}
          },
          "f:lastTimestamp": {},
          "f:message": {},
          "f:reason": {},
          "f:source": {
            "f:component": {},
            "f:host": {}
          },
          "f:type": {}
        }
      }
    ]
  },
  "involvedObject": {
    "kind": "Pod",
    "namespace": "kube-argocd-master",
    "name": "argocd-server-7f8b844757-dfjbx",
    "uid": "6185ab0b-f31f-4ea7-8725-bf1f85fade72",
    "apiVersion": "v1",
    "resourceVersion": "306889",
    "fieldPath": "spec.containers{argocd-server}"
  },
  "reason": "Pulling",
  "message": "Pulling image",
  "source": {
    "component": "kubelet",
    "host": "example.com"
  },
  "firstTimestamp": "2021-07-28T13:43:08Z",
  "lastTimestamp": "2021-07-30T08:08:17Z",
  "count": 500,
  "type": "Normal",
  "eventTime": null,
  "reportingComponent": "",
  "reportingInstance": ""
}
```

When I view the result in grafana, the logs are parsed correctly for nodes running containderd:

![image](https://user-images.githubusercontent.com/1607088/127625581-6b4aba6e-8d13-48b6-a64e-79ede8b9ed59.png)

---

But for nodes running with docker-shim I get the following:

![image](https://user-images.githubusercontent.com/1607088/127625202-0ab7ebd9-7091-4ac4-8179-d938ad56fbc1.png)

**Expected behavior**
The parsed fields should be the same for both.

**Environment:**
 - Infrastructure: kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by dannykopping** [comment]
@zbindenren it looks like you're only showing the "Log Labels" in the first screenshot (no parsed fields).

"Log Labels" are those that Loki has parsed from your log line (using the `| json` pipeline presumably) combined with the labels setup at ingestion, while the "Parsed Fields" are Grafana's best attempt at analyzing the logs.

> The parsed fields should be the same for both.

Can you include a screenshot of just the parsed fields for these two node types?

**Comment by zbindenren** [comment]
Here the screenshot for the working wan with parsed fields:

![image](https://user-images.githubusercontent.com/1607088/127633496-6d66af3e-1af5-4e40-bbc9-4face9d92d62.png)

**Comment by dannykopping** [comment]
Thank you.

Can you paste the actual log lines of the two nodes you're comparing, please?

**Comment by zbindenren** [comment]
Ok now I see the difference. The non working raw log line looks like:

{"log":"{\"metadata\":{\"name\":\"ces-agent-7cbc4b4676-m7q6m.16968def32abbfe2\",\"namespace\":\"kube-ces\",\"uid\":\"f492912c-f989-430d-bea0-7d25a3058618\",\"resourceVersion\":\"1289942\",\"creationTimestamp\":\"2021-07-30T11:26:13Z\",\"managedFields\":[{\"manager\":\"kubelet\",\"operation\":\"Update\",\"apiVersion\":\"v1\",\"time\":\"2021-07-30T11:26:13Z\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:count\":{},\"f:firstTimestamp\":{},\"f:involvedObject\":{\"f:apiVersion\":{},\"f:fieldPath\":{},\"f:kind\":{},\"f:name\":{},\"f:namespace\":{},\"f:resourceVersion\":{},\"f:uid\":{}},\"f:lastTimestamp\":{},\"f:message\":{},\"f:reason\":{},\"f:source\":{\"f:component\":{},\"f:host\":{}},\"f:type\":{}}}]},\"involvedObject\":{\"kind\":\"Pod\",\"namespace\":\"kube-ces\",\"name\":\"ces-agent-7cbc4b4676-m7q6m\",\"uid\":\"4c094c22-03b3-47ba-be5a-0c6045ae39b2\",\"apiVersion\":\"v1\",\"resourceVersion\":\"1289922\",\"fieldPath\":\"spec.containers{ces-agent}\"},\"reason\":\"Started\",\"message\":\"Started container ces-agent\",\"source\":{\"component\":\"kubelet\",\"host\":\"example.com\"},\"firstTimestamp\":\"2021-07-30T11:26:13Z\",\"lastTimestamp\":\"2021-07-30T11:26:13Z\",\"count\":1,\"type\":\"Normal\",\"eventTime\":null,\"reportingComponent\":\"\",\"reportingInstance\":\"\"}\n","stream":"stdout","time":"2021-07-30T11:26:13.836473996Z"}

But when I do a `kubectl logs -f <podname>`, there is no `log` json  key. It looks like some component takes the `<raw logline>` and creates a `{"log":<"raw logline"}`. And this is only the case for worker nodes with with the docker-shim.

**Comment by dannykopping** [comment]
You'll need to run your logs through the `docker` pipeline stage:
https://grafana.com/docs/loki/latest/clients/promtail/configuration/#docker

**Comment by zbindenren** [comment]
Thanks, I missed that one. Does this work with a mixed environment? We have workers in the same cluster with docker and containerd (we are currently migrating).

**Comment by dannykopping** [comment]
Are you able to identify which nodes are which? If so, you could have two separate jobs with different pipeline stages.

**Comment by zbindenren** [comment]
The promtail config is deployed with helm chart. I try both pipelines and see what happens.

Thanks for your help.
