### ISSUE TITLE
promtail  server path prefix setting makes the static file 404 not found

### ISSUE THREAD

**Issue by jeyrce** [grafana/loki#4086]
**Describe the bug**
while I tried set a path prefix for promtail server, I found all of the static file 404 not found in webpage.

version: 2.2.1

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Screenshots, Promtail config, or terminal output**
![image](https://user-images.githubusercontent.com/33649388/127824308-8ef0302c-afb2-4f3c-b6be-4be5d4a98cbc.png)
![image](https://user-images.githubusercontent.com/33649388/127824489-7fcf72d7-1497-47a5-905a-d972dd394302.png)

**Comment by dannykopping** [comment]
Thanks for reporting this @Jeyrce.

I've reproduced the bug in v2.2.1 but it doesn't appear to be broken using the tip of `main`.
I suspect this was fixed incidentally along the way.

We have v2.3.0 coming out in the next couple weeks; could I ask you to please test again using that once it's released?

**Comment by Jeyrce** [comment]
OKay, thanks for support.

**Comment by liguozhong** [comment]
server:
  external_url: 10.10.168.77:15004/promtail


如果 存在反向代理时使用， 增加 external_url 配置。

**Comment by jeyrce** [comment]
I got the same problem in version 2.3.0 @ @dannykopping @liguozhong
