### ISSUE TITLE
Download the logs

### ISSUE THREAD

**Issue by soum1234** [grafana/loki#409]
**Is your feature request related to a problem? Please describe.**
I need to download the logs from loki .How can i do that?

**Comment by davkal** [comment]
- Which logs do you want to download? The result of a log query?
- How many logs do you want to download?
- Which format do you want the logs to be in? What about the log labels?

**Comment by soum1234** [comment]
Hi 

I have the logs from various microservices which are sent to loki server using promtail.Now in Grafana i can see the logs from various components.
suppose i search on a string "xyz" in a log label: abc and  i get n no of records, i should be able to download all the logs that matched the criterion into a file in normal text payload format or json format.
To answer your questions in specific:
Yes the result of log query should be downloaded
All the results that matched the log query should be downloaded .
The log labels along with the log should be downloaded.

**Comment by davkal** [comment]
What's a realistic limit for volume when downloading the results? 1MB, 10MB, 100MB?

**Comment by charlie-roosen** [comment]
I have a simpler use case with this requirement.

We plan to have short-lived containers run as Kubernetes jobs with logging to stdout.

We then want to use some selector to return all the stdout as text for this job.

Probably 1 MB is a reasonable size limit.  I haven't given much thought yet to the labels.

FYI, we will also be using Grafana.  This use case is to mimic the current behavior we have where users can get the full stdout for a specific job as a simple text file.

It looks like the cli could be used for this, but are there other ways?

**Comment by cyriltovena** [comment]
You can definitely use the http api for this.

Le mar. 3 sept. 2019 à 13:03, charlie-roosen <notifications@github.com> a
écrit :

**Comment by AdieOlami** [comment]
is there a way for this please?

**Comment by marcbachmann** [comment]
I've written some small service to query logs hourly from loki and then pushing them to s3.
The loki api offered everything that was needed, it just needs some glue.
Here's the service in case anybody is looking for a way to extract data (`logcli` would also support it, but it has a mandatory `limit` at the moment): https://github.com/livingdocsIO/loki-log-export

To the details:
- I've written an async iterator for my Node.js app to extract all the logs between a time range:
  https://github.com/livingdocsIO/loki-log-export/blob/master/get-logs.js#L20
- Then I've merged the retrieved streams into one stream of logs:
  https://github.com/livingdocsIO/loki-log-export/blob/master/merge-logs.js#L14-L34
- And then set up a pipeline to push them to s3: https://github.com/livingdocsIO/loki-log-export/blob/master/exporter.js#L104-L115

**Comment by cyriltovena** [comment]
Nice one @marcbachmann  !

**Comment by junneyang** [comment]
very useful feature, any update?

**Comment by pgassmann** [comment]
Same issue in Grafana Project: https://github.com/grafana/grafana/issues/28752

**Comment by Tristan971** [comment]
This was closed without much information but to answer @davkal:
> Which logs do you want to download? The result of a log query?

the result of a log query yes

> How many logs do you want to download?

all of them over a given timerange

> Which format do you want the logs to be in? What about the log labels?

same options as logcli offers in general? raw logs at least

> What's a realistic limit for volume when downloading the results? 1MB, 10MB, 100MB?

could be multiple gigabytes, the point is if one wants traces over a large period of time for statistical significance purposes

---
atm this is more or less (as in rather "less" than "more") achievable with raising --limit but still clearly outside of the use-case -- would be nice to have a `--limit=-1` or something similar to say "yes I want all of them thank you"

**Comment by AyrtonRicardo** [comment]
@Tristan971 I don't know if you already got your answer. But in the attached task we have a answer(probably for your problem as well)

Downloading is implemented via "inspector" in Grafana.

Check this out:
https://github.com/grafana/grafana/pull/32764

![image](https://user-images.githubusercontent.com/3937889/146150481-a3df9e2e-d530-47db-af63-04274e23dedf.png)

**Comment by Tristan971** [comment]
@AyrtonRicardo Unfortunately (unless that changed recently) you're limited to the number of data points loaded in the current panel. For Loki datasources that's a # of lines, which IIRC can't be increased beyond 9999 (might be lower, ymmv etc). So if I want to export millions of lines efficiently I'm sort of screwed.

**Comment by slim-bean** [comment]
Logcli now supports batching requests, so you can request arbitrarily large amounts of log lines from the CLI and it will fetch them in batches to not exceed the max lines limit. 

I think if there is a desire to be able to do something similar from the UI, an issue should be created in the Grafana repo to add batching support to the download option as well over there.

**Comment by Codecaver** [comment]
> Logcli now supports batching requests, so you can request arbitrarily large amounts of log lines from the CLI and it will fetch them in batches to not exceed the max lines limit.
> 
> I think if there is a desire to be able to do something similar from the UI, an issue should be created in the Grafana repo to add batching support to the download option as well over there.

How can I download several gigabytes of query logs using logcli

**Comment by Tristan971** [comment]
> How can I download several gigabytes of query logs using logcli

Unfortunately, there is no good solution at the moment, which is why I raised #6840 as follow-up...

**Comment by Codecaver** [comment]
> > How can I download several gigabytes of query logs using logcli
> 
> Unfortunately, there is no good solution at the moment, which is why I raised #6840 as follow-up...

Alright，I wrote a shell script that loops to download logs for a period of time. Use the logcli tool. Uh... looks like it works，I've downloaded a stream of logs for the past month, about 50G. But it takes time

**Comment by abate** [comment]
Same here
```
#!/bin/bash

set -x

JOB_ID=9079dc54-2f5c-4d74-a9aa-1d9eb39dd3c2

for I in `seq 0 655`; do
    FILE=logs_$I.txt
    ID="$JOB_ID:$I"
    QUERY="{aws_job_id=\"$ID\",job=\"varlogs\"}"
    docker run grafana/logcli:main-1b6d0bf-amd64 --addr=http://localhost:3100/ -o raw -q query $QUERY --limit 100000 --batch 100 --forward --from "2022-09-25T10:00:00Z" > $FILE
done
```

I'm using a script like this, but since I've GBs of load it takes an eternity :( 

I'm looking to use syslog or similar to collect the logs in text files (used for backup and more complex data analysis) and loki on the side for precises queries. It would be nice to have one system instead of two ..

**Comment by valyala** [comment]
> How can I download several gigabytes of query logs using logcli

You can download arbitrary amounts of logs, which match the given filters, via HTTP querying API by using `curl` in an alternative solution for logs according to [these docs](https://docs.victoriametrics.com/victorialogs/querying/#command-line).
