### ISSUE TITLE
Loki Timezone

### ISSUE THREAD

**Issue by lichao4Java** [grafana/loki#4099]
How can i configure Timezone to loki ?

System Date :

  Local time: 四 2021-08-05 13:23:24 CST
  Universal time: 四 2021-08-05 05:23:24 UTC
        RTC time: 四 2021-08-05 05:23:23
       Time zone: Asia/Shanghai (CST, +0800)
     NTP enabled: yes
NTP synchronized: yes
 RTC in local TZ: no
      DST active: n/a
  
System Time zone is CST

when i use HTTP API  /loki/api/v1/push  send log to Loki, Response is :

entry with timestamp 2021-08-04 06:01:34.268 +0000 UTC ignored, reason: 'entry out of order' for stream: {host="devconsul.drcuiyutao.com"},

it seems like UTC is the default Time zone , but System Time Zone is CST.

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.

**Comment by oreak** [comment]
> How can i configure Timezone to loki ?
> 
> System Date :
> 
> Local time: 四 2021-08-05 13:23:24 CST Universal time: 四 2021-08-05 05:23:24 UTC RTC time: 四 2021-08-05 05:23:23 Time zone: Asia/Shanghai (CST, +0800) NTP enabled: yes NTP synchronized: yes RTC in local TZ: no DST active: n/a
> 
> System Time zone is CST
> 
> when i use HTTP API /loki/api/v1/push send log to Loki, Response is :
> 
> entry with timestamp 2021-08-04 06:01:34.268 +0000 UTC ignored, reason: 'entry out of order' for stream: {host="devconsul.drcuiyutao.com"},
> 
> it seems like UTC is the default Time zone , but System Time Zone is CST.

How did you solve this problem? I changed loki's code, the default timezone is set to CST.

**Comment by lichao4Java** [comment]
> > How can i configure Timezone to loki ?
> > System Date :
> > Local time: 四 2021-08-05 13:23:24 CST Universal time: 四 2021-08-05 05:23:24 UTC RTC time: 四 2021-08-05 05:23:23 Time zone: Asia/Shanghai (CST, +0800) NTP enabled: yes NTP synchronized: yes RTC in local TZ: no DST active: n/a
> > System Time zone is CST
> > when i use HTTP API /loki/api/v1/push send log to Loki, Response is :
> > entry with timestamp 2021-08-04 06:01:34.268 +0000 UTC ignored, reason: 'entry out of order' for stream: {host="devconsul.drcuiyutao.com"},
> > it seems like UTC is the default Time zone , but System Time Zone is CST.
> 
> How did you solve this problem? I changed loki's code, the default timezone is set to CST. Why not support custom configuration time zone? @dannykopping

i give up it...
