### ISSUE TITLE
host.docker.internal only works on mac/linux and is not a best practice

### ISSUE THREAD

**Issue by Dieterbe** [grafana/loki#41]
see
* https://docs.docker.com/docker-for-mac/networking/#port-mapping

> The host has a changing IP address (or none if you have no network access). From 18.03 onwards our recommendation is to connect to the special DNS name host.docker.internal, which resolves to the internal IP address used by the host. This is for development purpose and will not work in a production environment outside of Docker for Mac.
* https://github.com/docker/for-linux/issues/264
* https://dev.to/bufferings/access-host-from-a-docker-container-4099

my recommendation is to use docker-compose to run grafana+promtail+loki. that way they can all talk to each other. + you need to run fewer commands.

**Comment by daniellee** [comment]
Added a docker-compose file [here](https://github.com/grafana/loki/blob/master/docs/docker-compose.yaml) in docs.

**Comment by leehambley** [comment]
Referenced file in previous comment is now at https://github.com/grafana/loki/blob/master/production/docker-compose.yaml

With that carrying a "production" stamp now in the filename I wonder if this issue can be closed?

**Comment by davkal** [comment]
Can be closed indeed.
