### ISSUE TITLE
Extracting Labels from Logs Design Document Review

### ISSUE THREAD

**Issue by slim-bean** [grafana/loki#410]
This is a request for review of the design document on how to extract labels from metrics:

https://docs.google.com/document/d/16y_XFux4h2oQkJdfQgMjqu3PUxMBAq71FoKC_SkHzvk/edit?usp=sharing

The plan is to leave this open for review for a few days and then convert it to a markdown doc and store it in the project repo for posterity.

@woodsaj @Dieterbe @tomwilkie @gouthamve @steven-sheehy @base698 @DanCech @davkal

**Comment by tomwilkie** [comment]
+1 LGTM, thanks Ed.

**Comment by daixiang0** [comment]
#447
