### ISSUE TITLE
Reduce (some) memcache errors to warnings

### ISSUE THREAD

**Issue by james-callahan** [grafana/loki#4106]
**Is your feature request related to a problem? Please describe.**

My ingester logs are full of:

> `level=error ts=2021-08-02T05:08:21.186763875Z caller=memcached.go:235 msg="failed to put to memcached" name=chunks err="server=192.168.100.100:11211: memcache: unexpected response line from \"set\": \"SERVER_ERROR out of memory storing object\\r\\n\""`

**Describe the solution you'd like**

According to @dannykopping it's nothing to worry about; if that's the case, then it should be reduced from an error to a warning.

**Describe alternatives you've considered**
Don't log anything at all if its normal behaviour?

**Additional context**
https://grafana.slack.com/archives/CEPJRLQNL/p1627881010016600

**Comment by dannykopping** [comment]
Thanks for logging the issue @james-callahan 

To clarify: I didn't actually say that it's nothing to worry about; I said that it indicates that caches cannot be added, which will impact performance.

**Comment by james-callahan** [comment]
> To clarify: I didn't actually say that it's nothing to worry about; I said that it indicates that caches cannot be added, which will impact performance.

Is there something to do in this situation then? (aside from giving memcache more memory?)
e.g. is there a way to use it in more of an LRU cache? (so that old+unused items get evicted)

**Comment by dannykopping** [comment]
Memcache is already an LRU cache to a large extent.

It's hard to provide any specific guidance here without knowing some further details about your memcached instances and the keys it's storing.

Do you use the memcached-exporter?
Or can you post the output from `echo stats | nc <host> <port>`?

**Comment by james-callahan** [comment]
> It's hard to provide any specific guidance here without knowing some further details about your memcached instances and the keys it's storing.

It's purely for loki.

> Do you use the memcached-exporter?

Yes. What stat(s) would you like?

You can see the base manifests we use here: https://github.com/BitGo/kustomize-loki/tree/master/loki
The memcache configuration there was derived from [the "production" one used in this repository](https://github.com/grafana/loki/blob/43b9b224ea5561fb37c004a054b7a3fc391662cd/production/ksonnet/loki/memcached.libsonnet).

>  Or can you post the output from `echo stats | nc <host> <port>`?

[memcache-stats.txt](https://github.com/grafana/loki/files/6966039/memcache-stats.txt)

**Comment by james-callahan** [comment]
@dannykopping the extra info requested is in my above reply

**Comment by taisho6339** [comment]
I faced same issue before.
In my situation, I reduced my chunk size and then the errors had gone.

before: chunk block size 1MiB  * 10 blocks
after: chunk block size 256KB * 10 blocks

**Comment by james-callahan** [comment]
@dannykopping I think this was waiting for a reply from you?

**Comment by maikihde-adh** [comment]
> I faced same issue before. In my situation, I reduced my chunk size and then the errors had gone.
> 
> before: chunk block size 1MiB * 10 blocks after: chunk block size 256KB * 10 blocks
> 
> Also, I found that memcached has the limitation of chunk size up to 1.5MB. https://grafana.com/docs/loki/latest/upgrading/
> 
> > chunk_target_size was increased to flush slightly larger chunks, if using memcache for a chunks store make sure it will accept files up to 1.5MB in size.

Please note that there are 2 different settings that you mentioned here:

chunk_target_size  (default = 1572864)
chunk_block_size (default = 262144)

However I am also observing this issue using Loki 2.3 and the distributed helm chart
