### ISSUE TITLE
recent promtail --version (2.3.0) does not contain build information

### ISSUE THREAD

**Issue by patrickjahns** [grafana/loki#4115]
**Describe the bug**
The latest release (2.3.0) of promtail does not contain any version information when executing `./promtail --version`

**To Reproduce**
1. Download latest promtail release zip from https://github.com/grafana/loki/releases/tag/v2.3.0
2. Unzip archive
3. Run `./promtail --version`
```
./promtail-darwin-amd64-2.3.0 --version
promtail, version  (branch: , revision: )
  build user:       
  build date:       
  go version:       go1.16.2
  platform:         darwin/amd64
```

**Expected behavior**
Similar to previous version, I would expect the information to be populated - example from promtail 2.2.1

```
./promtail-darwin-amd64 --version
promtail, version 2.2.1 (branch: HEAD, revision: babea82e)
  build user:       root@e2d295b84e26
  build date:       2021-04-06T00:52:41Z
  go version:       go1.15.3
  platform:         darwin/amd64

```

**Environment:**
 - Infrastructure: laptop ( amd64, darwin)
 - Deployment tool: [e.g., helm, jsonnet]

**Screenshots, Promtail config, or terminal output**
See reproduction steps

**Comment by bradleypettit** [comment]
I'm getting the same behaviour with the latest ([v2.3.0 release](https://github.com/grafana/loki/releases/download/v2.3.0/loki-linux-amd64.zip)) Loki binary too.

```
$ ./loki-2.3.0/loki-linux-amd64 --version
loki, version  (branch: , revision: )
  build user:
  build date:
  go version:       go1.16.2
  platform:         linux/amd64
```

**Comment by Jeyrce** [comment]
haha! Unexpectedly, large projects will have the same problems as me. It seems that ci/cd is very important.
