### ISSUE TITLE
logcli: Respect `--quiet` when tailing

### ISSUE THREAD

**Issue by andsens** [grafana/loki#4124]
The `--quiet` flag is respected for printing how labels are shown when querying but not when tailing:
https://github.com/grafana/loki/blob/32e55c30434c9fccdb22a577e8c88b9d3d9a8806/pkg/logcli/query/query.go#L271-L277
vs.
https://github.com/grafana/loki/blob/92a4e574483c2f629141975075c30a2a07f210a9/pkg/logcli/query/tail.go#L39-L45

**Comment by andsens** [comment]
/remove-lifecycle stale

Still an issue in master

**Comment by DylanGuedes** [comment]
I opened PR https://github.com/grafana/loki/pull/6033 tackling this. I was just not sure if I should take the quiet flag into account when logging number of dropped entries or not. Any thoughts on it?

**Comment by andsens** [comment]
I mean, the counterpart code doesn't. So just for consistencies sake I wouldn't.
