### ISSUE TITLE
HTTP API Endpoint to get Loki version not working in 2.3.0

### ISSUE THREAD

**Issue by Abuelodelanada** [grafana/loki#4133]
**Describe the bug**
Related to issue #3221 and PR #3972

I am running [Loki 2.3.0](https://hub.docker.com/layers/grafana/loki/2.3.0/images/sha256-15694dd2afbc67d3b7afd7b40c742bef54b242df5e1b471e382216485c526922?context=explore) and the the `/loki/api/v1/status/buildinfo` returns empty values:

```json
{"version":"","revision":"","branch":"","buildUser":"","buildDate":"","goVersion":""}
```

**To Reproduce**
1. Deploy Loki 2.3.0: `$ docker run -d --name=loki230 -p 3100:3100 grafana/loki:2.3.0`
2. Open in the browser: `http://localhost:3100/loki/api/v1/status/buildinfo`
3. Verify empty values in response

**Expected behavior**
Get Loki info (version, revision, etc)

**Environment:**
 - Docker version 20.10.8

**Comment by slim-bean** [comment]
Likely the same problem which is causing: https://github.com/grafana/loki/issues/4115
