### ISSUE TITLE
promtail daemonset without privileged SCC

### ISSUE THREAD

**Issue by yasharne** [grafana/loki#4138]
**Describe the bug**
As mentioned in [this comment](https://github.com/grafana/loki/issues/1165#issuecomment-677821897) in order to deploy promtail daemonset on openshift I need to add `privileged=true` but due to some security restrictions we cannot deploy the daemonset with this SCC, Are there any equivalent SCC to `privileged=true`?

**To Reproduce**
1. Deploy promtail `v2.3.0`

**Environment:**
 - Infrastructure: Openshift
 - Deployment tool: helm

**Comment by periklis** [comment]
You can look on creating a more constrained SCC via: https://docs.openshift.com/container-platform/4.7/authentication/managing-security-context-constraints.html

This looks like a missing piece in our helm charts/jsonnet deployment manifests to promtail.
