### ISSUE TITLE
Promtail: Timestamp stage, log errors

### ISSUE THREAD

**Issue by Thoro** [grafana/loki#4139]
**Is your feature request related to a problem? Please describe.**
Currently it's very hard to figure out that some timestamps cannot be parsed correctly, especially in the initial setup phase, and when one promtail instance is tailing multiple services

**Describe the solution you'd like**
Add an additional action_on_failure of type "log" that would log an error for the timestamp pipeline.

**Describe alternatives you've considered**
Add an additional property to enable logging on failure.

**Comment by dannykopping** [comment]
Hey @Thoro 

If you're using Promtail v2.3.0, you can use this:
https://grafana.com/docs/loki/latest/clients/promtail/troubleshooting/#inspecting-pipeline-stages

This should help you debug more effectively.
Please give this a try and let me know if that still doesn't cover this use-case.

**Comment by Thoro** [comment]
Hi,

I am aware of this, the main issue is, that I thought everything works correctly, and then suddenly I got 10k+ logs / second without seeing any errors on promtail side.

Which now also broke all streams since they are now all at the current time.

**Comment by dannykopping** [comment]
OK, thanks for the detail.
