### ISSUE TITLE
what is instanceId?

### ISSUE THREAD

**Issue by qq3884** [grafana/loki#414]
When running logcli, the required username and password require grafana to use the instance id and api keys.
I know the api key for my account, which is being logged in at grafana.com, but I do not know what the instance id is going to be.

**Comment by daixiang0** [comment]
refer to [doc](https://github.com/grafana/loki/blob/master/docs/logcli.md), no need to specify instanceid.

Could share your cmd?

**Comment by DanCech** [comment]
If you log in to your account at grafana.com and go to the details for the hosted logs instance, the instance id is shown in the "Using Grafana with Hosted Logs" section as the "User:" setting.
