### ISSUE TITLE
Loki docker driver unexpected EOF when sending to Grafana Cloud

### ISSUE THREAD

**Issue by daveram** [grafana/loki#4157]
**Describe the bug**
Stood up a Grafana Cloud instance, trying to ship logs from docker containers to Loki.  Installed docker loki plugin, configured log-opt defaults in daemon.json, restarted docker daemon and now getting a bunch of 400 Bad Request: unexpected EOF from my Grafana Cloud instance

**To Reproduce**
1. Install docker plugin
docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions
2. Add the following config to daemon.json
```
{
    "debug" : true,
    "log-driver": "loki",
    "log-opts": {
        "loki-url": "https://><user>:<pass>@logs-prod-us-central1.grafana.net/api/prom/push",
        "loki-batch-size": "400"
    }
}
```
3. Restart docker
4. Spin up new container
5. Tail /var/log/docker.log and see the following log entries (lots of them)
```
time="2021-08-13T01:10:24-07:00" level=info msg="level=error ts=2021-08-13T08:10:24.361455488Z caller=client.go:355 container_id=10941a2dd2d6ebfba2e6ab902991c59d1d53b1e4df77930cfe7a7e3ddf10efb0 component=client host=logs-prod-us-central1.grafana.net msg=\"final error sending batch\" status=400 error=\"server returned HTTP status 400 Bad Request (400): unexpected EOF\"" plugin=024894ce71054c61a1c27aa758cbda446226839679b0b21f11b0a0b379f918e2
time="2021-08-13T01:10:24-07:00" level=info msg="level=error ts=2021-08-13T08:10:24.418196416Z caller=client.go:355 container_id=10941a2dd2d6ebfba2e6ab902991c59d1d53b1e4df77930cfe7a7e3ddf10efb0 component=client host=logs-prod-us-central1.grafana.net msg=\"final error sending batch\" status=400 error=\"server returned HTTP status 400 Bad Request (400): unexpected EOF\"" plugin=024894ce71054c61a1c27aa758cbda446226839679b0b21f11b0a0b379f918e2
time="2021-08-13T01:10:24-07:00" level=info msg="level=error ts=2021-08-13T08:10:24.47402342Z caller=client.go:355 container_id=10941a2dd2d6ebfba2e6ab902991c59d1d53b1e4df77930cfe7a7e3ddf10efb0 component=client host=logs-prod-us-central1.grafana.net msg=\"final error sending batch\" status=400 error=\"server returned HTTP status 400 Bad Request (400): unexpected EOF\"" plugin=024894ce71054c61a1c27aa758cbda446226839679b0b21f11b0a0b379f918e2
time="2021-08-13T01:10:24-07:00" level=info msg="level=error ts=2021-08-13T08:10:24.531899588Z caller=client.go:355 container_id=10941a2dd2d6ebfba2e6ab902991c59d1d53b1e4df77930cfe7a7e3ddf10efb0 component=client host=logs-prod-us-central1.grafana.net msg=\"final error sending batch\" status=400 error=\"server returned HTTP status 400 Bad Request (400): proto: Stream: illegal tag 0 (wire type 0)\"" plugin=024894ce71054c61a1c27aa758cbda446226839679b0b21f11b0a0b379f918e2
```

**Expected behavior**
Log labels to start populating in Grafana Cloud loki explorer page, ability to query logs via LogQL

**Environment:**
 - Infrastructure: Bare-metal
 - Deployment tool: None, by hand

**Comment by Flokami** [comment]
Hello, same error for me on a local instance

**Comment by Flokami** [comment]
Up : Seems that building plugin from sources work, so the problem come from the plugin image maybe ?

**Comment by daveram** [comment]
Definitely plugin image, went with a tag that was 7 days older instead of latest and now it's working just fine.  Thanks for the assist @Flokami 

Leaving this open for now until the latest image tag gets resolved

**Comment by koloboid** [comment]
driver updated, just run docker plugin upgrade, seems working now.

**Comment by daveram** [comment]
Yep same here, closing this off
