### ISSUE TITLE
Promtail `logentry_dropped_lines_total` metric not incrementing

### ISSUE THREAD

**Issue by lukeplausin** [grafana/loki#4158]
**Describe the bug**
According to the docs, promtail should increment this counter when drop statements are matched.

https://grafana.com/docs/loki/latest/clients/promtail/stages/drop/

The documentation mentions a metric called "logentry_drop_lines_total", I can't see it in my prometheus deployment but there is one called `logentry_dropped_lines_total`. It has the correct labels set by the `drop_counter_reason` setting, but all of the counts are null.

**To Reproduce**
1. Deploy promtail with servicemonitor and prometheus
2. Deploy a pipeline with a drop statement
3. Check the promtail metrics

**Expected behavior**
* The `logentry_dropped_lines_total` metric should increment based on how many lines have been dropped by the pipeline
* The documentation should have the correct metric name

Promtail v.2.3.0

**Comment by owen-d** [comment]
oops!
