### ISSUE TITLE
Memory leak in Query-Frontend

### ISSUE THREAD

**Issue by vikrantsde** [grafana/loki#4161]
**Describe the bug**
Memory in query frontend is not getting released after queries

**To Reproduce**
1. Started Loki (2.3.0)
2. Running queries for some time in sharding = true

**Expected behavior**
The memory of the query-frontend should go down

**Environment:**
 - Infrastructure: kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by cyriltovena** [comment]
Hello !

Can you share pprof profile ? heap and goroutine would be helpful ( it's available under /debug/pprof/heap and /debug/pprof/goroutines)
