### ISSUE TITLE
promtail 2.3.0 version information is missing from Windows binary

### ISSUE THREAD

**Issue by jantari** [grafana/loki#4162]
**Describe the bug**
I downloaded the 2.3.0 binary release of promtail for Windows amd64,
and there appears to be absolutely no version information / metadata in the binary.

**To Reproduce**
I downloaded the 2.3.0 binary release of promtail for Windows amd64 from the GitHub release assets list.

The `--version` output is mostly blank/missing:
```
PS C:\Program Files\promtail> .\promtail-windows-amd64.exe --version
promtail, version  (branch: , revision: )
  build user:
  build date:
  go version:       go1.16.2
  platform:         windows/amd64
```

And there is also no file metadata, which is usually  expected from Windows binaries:
```
PS C:\Program Files\promtail> (Get-Item .\promtail-windows-amd64.exe).VersionInfo | fl


OriginalFilename  :
FileDescription   :
ProductName       :
Comments          :
CompanyName       :
FileName          : C:\Program Files\promtail\promtail-windows-amd64.exe
FileVersion       :
ProductVersion    :
IsDebug           : False
IsPatched         : False
IsPreRelease      : False
IsPrivateBuild    : False
IsSpecialBuild    : False
Language          :
LegalCopyright    :
LegalTrademarks   :
PrivateBuild      :
SpecialBuild      :
FileVersionRaw    : 0.0.0.0
ProductVersionRaw : 0.0.0.0
```

Even when the program starts, it's missing version information in the info-logs:
```
PS C:\Program Files\promtail> .\promtail-windows-amd64.exe --config.file="C:\ProgramData\promtail\config.yml"
level=info ts=2021-08-13T13:29:41.934844Z caller=server.go:239 http=[::]:9080 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2021-08-13T13:29:41.9353728Z caller=main.go:119 msg="Starting Promtail" version="(version=, branch=, revision=)"
```

**Expected behavior**
Version, commit-sha, branch ... all the release information that's supposed to be there should be in all the three places I've mentioned:

- `--version`
- File metadata
- in the stdout-log when starting up

**Environment:**
 - Infrastructure: Windows Server 2019 VM
 - Deployment tool: deployed latest binary from GitHb release assets via ansible

**Screenshots, Promtail config, or terminal output**
All relevant output is already seen above.

**Comment by dannykopping** [comment]
Hey @jantari 
Thanks for reporting this. It has already been identified and fixed in https://github.com/grafana/loki/pull/4135.
