### ISSUE TITLE
Expose pattern parser as a promtail pipeline stage

### ISSUE THREAD

**Issue by fktkrt** [grafana/loki#4166]
**Is your feature request related to a problem? Please describe.**
Currently, we can only use the new pattern parser "inline" for panels, and/or for ad-hoc queries resulting in repeated parser expressions.

**Describe the solution you'd like**
It would be nice to have the new pattern parser exposed as a [parser pipeline stage](https://grafana.com/docs/loki/latest/clients/promtail/pipelines/#stages) to make the extracted data available for the later stages and to simplify the queries. 

**Describe alternatives you've considered**
Alternatively, pattern parser can be used throughout queries/panels, but that is making it a bit inefficient.

**Comment by owen-d** [comment]
cc @cyriltovena @slim-bean I think this is a good idea

**Comment by slim-bean** [comment]
With promtail being Apache2 and Loki AGPL this won't be possible.  Importing the LogQL code into promtail would require relicensing promtail as AGPL. 

We do continue to discuss relicensing the query language to a more permissive license for reasons just like this but i don't expect anything to change on this in anytime in the near future.

**Comment by fktkrt** [comment]
Alright, that makes sense, thank you for the update.

**Comment by cyriltovena** [comment]
You can use it for recording rules and alert though, which is almost the same as if it was in Promtail except the network roundtrip.

**Comment by fktkrt** [comment]
Yes, I am doing exactly that, for now :)

**Comment by james-callahan** [comment]
>  Importing the LogQL code into promtail would require relicensing promtail as AGPL.
> 
> We do continue to discuss relicensing the query language to a more permissive license for reasons just like this but i don't expect anything to change on this in anytime in the near future.

Given that LogQL is used in both promtail and loki, how did this happen previously?
It's bad to let promtail and loki get out of sync on what they think LogQL is...

Given the copyright assignment via the CLA, such a relicensing shouldn't be too hard?

**Comment by cyriltovena** [comment]
It's more complex than that unfortunately. I really wish we had the full LogQL support in Promtail too.
