### ISSUE TITLE
[bug] distributor: Memory leak in distributor

### ISSUE THREAD

**Issue by liguozhong** [grafana/loki#4169]
![image](https://user-images.githubusercontent.com/9583245/129494682-60211fa5-64a2-4b16-83a3-c49bf69a9893.png)

**Comment by dannykopping** [comment]
@liguozhong please provide more details using the bug report template

**Comment by liguozhong** [comment]
update hints.
go routine leak.
![image](https://user-images.githubusercontent.com/9583245/131378644-180b6ce3-d4f1-452e-a50d-4dfb39313b50.png)
![image](https://user-images.githubusercontent.com/9583245/131378705-3d26761f-3346-4acf-bae8-9297919fe3b6.png)
