### ISSUE TITLE
v2.3.0 releases for amd64 missing version information

### ISSUE THREAD

**Issue by joonap** [grafana/loki#4170]
**Describe the bug**
The v2.3.0 binary releases do not output full version information when ran with 'command --version'

**To Reproduce**
1. Run executable with 'command --version'
2. Examine output

**Expected behavior**
Version information including build user and build date.

**Environment:**
 - Infrastructure: Local Linux system
 - Deployment tool: N/A

**Screenshots, Promtail config, or terminal output**
Should receive output with version information, build user and build date, e.g.:

```
promtail, version 2.2.0 (branch: HEAD, revision: a27c7991)
  build user:       root@b6becd8d0173
  build date:       2021-03-11T14:05:11Z
  go version:       go1.15.3
  platform:         linux/amd64
```

Instead you receive the following:
```
promtail, version  (branch: , revision: )
  build user:       
  build date:       
  go version:       go1.16.2
  platform:         linux/amd64
```

**Comment by joonap** [comment]
This issue can be verified with logcli, loki-canary, loki and promtail linux amd64 executables.

**Comment by dannykopping** [comment]
Thanks for reporting @joonap 

This issue has already been addressed in https://github.com/grafana/loki/pull/4135

**Comment by joonap** [comment]
@dannykopping Thanks! I had checked for other tickets before reporting but somehow missed that one. :)

**Comment by dannykopping** [comment]
No prob! :slightly_smiling_face:
