### ISSUE TITLE
running with DEPRECATED flag -store.max-look-back-period, use -querier.max-query-lookback instead

### ISSUE THREAD

**Issue by dbluxo** [grafana/loki#4178]
With Loki v2.3.0 a deprecated message is printed:

`running with DEPRECATED flag -store.max-look-back-period, use -querier.max-query-lookback instead`

Now `-querier.max-query-lookback` should be used instead.

Where can I find documentation on this configuration option?

On the [official configuration docs page ](https://grafana.com/docs/loki/latest/configuration/) I find the `-ingester.query-store-max-look-back-period` setting or the `-querier.engine.max-lookback-period` setting, but not the one just mentioned, something doesn't match here?

**Comment by systemcrash** [comment]
PLZ update website also....:

https://grafana.com/docs/loki/latest/configuration/#chunk_store_config

what to use now?
