### ISSUE TITLE
Docs: Describe how to scale Loki out into separate distributor, ingester, frontend etc instances.

### ISSUE THREAD

**Issue by jeschkies** [grafana/loki#4186]
**Is your feature request related to a problem? Please describe.**
The Tanka installation already distributes the workload across different Loki component. However, this method is bound to Tanka and Kubernetes. In case a user is not using these tools but would like to deploy Loki with there means they should have a documentation on how to start Loki components and connect them.

**Describe the solution you'd like**
Ideally we extend the [Scaling with Loki](https://grafana.com/docs/loki/latest/operations/scalability/) section and describe what the Tanka setup does.

**Describe alternatives you've considered**
We could point users to the Tanka ksonnet files. However, it is not trivial in my opinion to grok the required Loki commands from these files.

**Comment by MuhammadNaeemAkhtar** [comment]
> **Is your feature request related to a problem? Please describe.**
> The Tanka installation already distributes the workload across different Loki component. However, this method is bound to Tanka and Kubernetes. In case a user is not using these tools but would like to deploy Loki with there means they should have a documentation on how to start Loki components and connect them.
> 
> **Describe the solution you'd like**
> Ideally we extend the [Scaling with Loki](https://grafana.com/docs/loki/latest/operations/scalability/) section and describe what the Tanka setup does.
> 
> **Describe alternatives you've considered**
> We could point users to the Tanka ksonnet files. However, it is not trivial in my opinion to grok the required Loki commands from these files.

There is nothing on the link scaling with Loki https://grafana.com/docs/loki/latest/operations/scalability/ link, apart from 3 lines of small introduction.

**Comment by jeschkies** [comment]
@MuhammadNaeemAkhtar yes. That's my point. We should extend that documentation.

**Comment by MuhammadNaeemAkhtar** [comment]
Hi @duj4,
Did you deploy in k8s or docker?

**Comment by applike-ss** [comment]
A little scaling documentation would be nice. I am currently investigating on how/when to scale the ingesters, but i couldn't see what to use as a base yet.
