### ISSUE TITLE
Add MSI authentication for Azure Storage Account to chunks

### ISSUE THREAD

**Issue by NissesSenap** [grafana/loki#4201]
**Is your feature request related to a problem? Please describe.**
Currently when using when using Azure Storage Account it is only possible to use static SAS tokens to authenticate with the API. This works but introduces the need to manage token storage and rotation. When using AKS it is possible to use the project [aad-pod-identity](https://github.com/Azure/aad-pod-identity) to enable authnetication for individual pods, much like how ISRA works on EKS. The only requirement to use aad-pod-identity is that the client connecting to the API supports [MSI](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview) authentication.

**Describe the solution you'd like**
The solution would be to implement a hierarchy of authentication methods, where the storage client would first attempt to use MSI authentication and then fallback to the static tokens. We would need to change this to add MSI support, and where ever else the credentials are used.

**Describe alternatives you've considered**
There are no other alternatives if you want to make use of aad-pod-identity.

**Additional context**
I could probably implement this I just wanted to check that this is something that you will accept before starting to work on the feature.

There recently was a PR to do this together with a number of other tasks in Thanos, https://github.com/thanos-io/thanos/pull/3970/ can be a good place for inspiration.

**Comment by Ottovsky** [comment]
Any chance Loki will get Azure MSI support?
