### ISSUE TITLE
Error - server returned HTTP status 500 Internal Server Error (500): empty ring

### ISSUE THREAD

**Issue by toorsunov** [grafana/loki#4202]
`promtail_1  | level=warn ts=2021-08-23T07:22:20.680240681Z caller=client.go:344 component=client host=10.10.12.189:18080 msg="error sending batch, will retry" status=500 error="server returned HTTP status 500 Internal Server Error (500): empty ring"
`

Why I receive this error?
After restart Promtail connection resumes

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.

**Comment by sojjan1337** [comment]
@thejvmshid did you solve it? i'm running loki-distributed. As soon loki dies promtail cannot reconnect and i get the same error. But if loki is running and i reinstall promtail it works fine.

**Comment by sojjan1337** [comment]
+1 same problem here
