### ISSUE TITLE
server returned HTTP status 429 Too Many Requests

### ISSUE THREAD

**Issue by toorsunov** [grafana/loki#4204]
```
promtail_1  | level=warn ts=2021-08-23T07:59:26.712127914Z caller=client.go:344 component=client host=10.10.12.189:18080 msg="error sending batch, will retry" status=429 error="server returned HTTP status 429 Too Many Requests (429): entry with timestamp 2021-08-23 07:59:26.621124043 +0000 UTC ignored, reason: 'stream rate limit exceeded' for stream: {filename=\"/var/log/b/a.log\", host=\"10.10.12.128\", job=\"a\"},"
promtail_1  | level=warn ts=2021-08-23T07:59:27.369168249Z caller=client.go:344 component=client host=10.10.12.189:18080 msg="error sending batch, will retry" status=429 error="server returned HTTP status 429 Too Many Requests (429): entry with timestamp 2021-08-23 07:59:26.621124043 +0000 UTC ignored, reason: 'stream rate limit exceeded' for stream: {filename=\"/var/log/b/a.log\", host=\"10.10.12.128\", job=\"a\"},"
```

Promtail version: latest

**Comment by toorsunov** [comment]
<img width="318" alt="image" src="https://user-images.githubusercontent.com/35526267/130412799-038f8a87-d9a7-4a4b-af5f-9eb4943f3fa6.png">
increased in this moments

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.

**Comment by rmn-lux** [comment]
My experimental config, which seemed to help get rid of the 429 code. Might come in handy.

```   limits_config:
      retention_period: 72h
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_cache_freshness_per_query: 10m
      split_queries_by_interval: 15m
      # for big logs tune
      per_stream_rate_limit: 512M
      per_stream_rate_limit_burst: 1024M
      cardinality_limit: 200000
      ingestion_burst_size_mb: 1000
      ingestion_rate_mb: 10000
      max_entries_limit_per_query: 1000000
      max_label_value_length: 20480
      max_label_name_length: 10240
      max_label_names_per_series: 300
```

**Comment by JimKGD** [comment]
Alternatively, you can limit the intensity of data reading and pushing to Loki.
`promtail-windows-386.exe --config.file=promtail-local-config.yaml --limit.readline-rate-enabled=true --limit.readline-burst=1000 --limit.readline-rate=1000 --limit.readline-rate-drop=false`

**Comment by michaelniemand** [comment]
> ingestion_rate_mb: 10000

10GB log volume per second seems excessive

the [official docs](https://grafana.com/docs/loki/latest/configuration/#limits_config) state: 

# Per-user ingestion rate limit in sample size per second. Units in MB. default is 4

**Comment by RamaTripathi** [comment]
> My experimental config, which seemed to help get rid of the 429 code. Might come in handy.
> 
> ```
>       retention_period: 72h
>       enforce_metric_name: false
>       reject_old_samples: true
>       reject_old_samples_max_age: 168h
>       max_cache_freshness_per_query: 10m
>       split_queries_by_interval: 15m
>       # for big logs tune
>       per_stream_rate_limit: 512M
>       per_stream_rate_limit_burst: 1024M
>       cardinality_limit: 200000
>       ingestion_burst_size_mb: 1000
>       ingestion_rate_mb: 10000
>       max_entries_limit_per_query: 1000000
>       max_label_value_length: 20480
>       max_label_name_length: 10240
>       max_label_names_per_series: 300
> ```

it worked like a charm for me, was stuck debugging it for like 2 days.
