### ISSUE TITLE
level=error ts=2021-08-24T06:11:28.742362564Z caller=batch.go:690 msg="error fetching chunks" err="object not found in storage"

### ISSUE THREAD

**Issue by rt005744** [grafana/loki#4210]
choose last 5 minutes， query is ok
It was occoured error frequently when choose range last 1 hours or longer

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
