### ISSUE TITLE
Implement durable storage for recording rules samples

### ISSUE THREAD

**Issue by dannykopping** [grafana/loki#4241]
**Is your feature request related to a problem? Please describe.**
As of v2.3.0, the Loki `ruler` component has the ability to evaluate recording rules. These samples produced by these evaluations are buffered in-memory, and remote-written to Prometheus. Should a `ruler` crash, all of these samples will be lost.

**Describe the solution you'd like**
Implement a _Write-Ahead Log_ (WAL) and append samples to it, before remote-writing to Prometheus.
We should ideally have a WAL per tenant, because Prometheus will reject an entire batch of (e.g.) 1000 samples if 1 of them is invalid (out of order, duplicate, etc); we wouldn't want one tenant to affect the remote-writing of another because of invalid samples.

Luckily, Prometheus has implemented all of this WAL + remote-write functionality already, so we can reuse large amounts of code. The [Grafana Agent](https://github.com/grafana/agent) also implements some useful additions to the Prometheus WAL, and we can reuse that too.

**Describe alternatives you've considered**
We could try to unify the WAL implementation used by the ingesters, but these use-cases are not identical (the ingester WAL stores logs, this WAL will store metrics).

**Additional context**
As a side-benefit of using the Agent code, we could support multiple remote-write configurations. For example, if we wanted tenant _A_ to remote-write samples to Prometheus _A_, and tenant _B_ to Prometheus _B_ - this would now be possible.

**Comment by cten** [comment]
Will this support remove writing to a cluster of Prometheus servers?

**Comment by dannykopping** [comment]
@cten yup, and it already does in v2.3.0: https://grafana.com/docs/loki/latest/rules/#recording-rules

This issue (and the related PR #4344) are focusing on making the storage of the samples more durable _before_ they get remote-written to Prometheus.
