### ISSUE TITLE
Change the cortex_ prefix on runtimeconfig metrics to loki_

### ISSUE THREAD

**Issue by slim-bean** [grafana/loki#4243]
#4227 updated Loki to use the dskit runtime config, at the time it was decided to keep using the `cortex_` prefix on metrics exported by this component as to not break any existing dashboards.

When releasing 3.0 we should re-prefix these metrics with `loki_`

**Comment by dannykopping** [comment]
We also have a number of alerts using `cortex_`-prefixed metrics, which should be modified too.
