### ISSUE TITLE
Add support for Azure Blob Storage with Managed Identity

### ISSUE THREAD

**Issue by sandy2008** [grafana/loki#4256]
**Is your feature request related to a problem? Please describe.**
- Example: https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/tutorial-linux-vm-access-storage
- We need to add support for Azure Blob Storage with Managed Identity in certain VM not just with access key & account.

**Describe the solution you'd like**
- Add support for constantly get Bearer Token & get the bulks with the Token.

**Comment by sandy2008** [comment]
Example:
```

**Comment by tomasfreund** [comment]
I'd also like if there was an option to select the managed identity to use by client id. This is required when an AKS cluster has multiple identities, you need to specify which one to use or it fails.

**Comment by Ottovsky** [comment]
Any chance Loki will get Azure MSI support?

**Comment by sandy2008** [comment]
> Any chance Loki will get Azure MSI support?

Already submitted PR & merged.
https://github.com/grafana/loki/pull/4858

**Comment by tomasfreund** [comment]
It seems that the PR does not allow to select the managed identity to use. This can cause issues when the cluster has multiple managed identities.

**Comment by Ottovsky** [comment]
Yes, without ability to define User Assigned ID, it will make it hard to use it together with https://github.com/Azure/aad-pod-identity in the AKS.
