### ISSUE TITLE
[feature] distributor: reusing request goroutines

### ISSUE THREAD

**Issue by liguozhong** [grafana/loki#4260]
code=500,timeout.

![image](https://user-images.githubusercontent.com/9583245/131775087-64b8c7d9-4f30-46bf-9053-e2f8dd9a403b.png)
![image](https://user-images.githubusercontent.com/9583245/131775126-2a308ba6-9d13-4760-8872-4afbe8ff207b.png)

**Comment by cyriltovena** [comment]
Something that I have been thinking for distributors and queriers, this would also reduce the memory overhead.

By default goroutines should already be recycle if they don't have a deep cal stack IIRC.
