### ISSUE TITLE
WebIdentityErr: failed to retrieve credentials AWS and ServiceAccount with oidc Role

### ISSUE THREAD

**Issue by ingluife** [grafana/loki#4264]
**Describe the bug**
Hi Guys I'm having this issue. I've implemented Loki in an EKS Cluster in AWS. in the Loki setting I set up an IAM Role with the corresponding policy and permission for Assume role through the Loki ServiceAccont.

When the Loki POD is starting I got an error message with the credentials gets process according to the ServiceAccount. like this:
`WebIdentityErr: failed to retrieve credentials\ncaused by: RequestError: send request failed\ncaused by: Post \"https://sts.amazonaws.com/\": dial tcp <ip>: connect: connection refused`

**To Reproduce**
1. Install Loki with this setting:
```
- Set up ServiceAccount annotation with the corresponding AssumeRole:
eks.amazonaws.com/role-arn:  <replaced by role_arn>



- Permission policy attached to the AssumeRole:
data "aws_iam_policy_document" "loki_storage" {
  statement {
    sid       = "BucketAccess"
    actions   = [
      "s3:ListObjects",
      "s3:ListBucket",
      "s3:PutObject",
      "s3:GetObject"
    ]
    resources = [
      "<replaced by aws_s3_bucket.arn>/*"
    ]
  }
  statement {
    sid = "DynamoDBAccess"
    actions = ["dynamodb:*"]
    resources = ["arn:aws:dynamodb:*:<account_id>:table/loki_*"]
  }
}
data "aws_iam_policy_document" "loki_assume" {
  statement {
    sid       = "AllowAssumeRoleWithWebIdentity"
    actions   = ["sts:AssumeRoleWithWebIdentity"]
    resources = ["arn:aws:iam::<account_id>:oidc-provider/<cluster_oidc_issuer_url>"]
    condition {
      test     = "StringLike"
      variable = "<oidc_issuer_url>:sub"

      values = [
        "system:serviceaccount:grafana:loki",
      ]
    }
  }
}

```

**Expected behavior**
Be able to run assuming an IAM to connect to S3 Bucket and DynamoDB in AWS.

**Environment:**
 - Infrastructure: Kubernetes EKS
 - Deployment tool: helm
 - Chart version: v2.6.0

- Loki setting:
```
...
schema_config:
  configs:
  - from: 2020-05-15
    store: aws
    object_store: s3
    schema: v11
    index:
      prefix: loki_
storage_config:
  aws:
    s3: s3://region/bucket_name
    dynamodb:
      dynamodb_url: dynamodb://region
...
```

**Loki Logs output**
`level=info ts=2021-09-02T20:59:45.040096477Z caller=lifecycler.go:530 msg="not loading tokens from file, tokens file path is empty"
level=info ts=2021-09-02T20:59:45.040208118Z caller=lifecycler.go:559 msg="instance not found in ring, adding with no tokens" ring=ingester
level=info ts=2021-09-02T20:59:45.040347951Z caller=lifecycler.go:406 msg="auto-joining cluster after timeout" ring=ingester
level=info ts=2021-09-02T20:59:45.040892791Z caller=module_service.go:59 msg=initialising module=table-manager
level=info ts=2021-09-02T20:59:45.049012713Z caller=table_manager.go:324 msg="synching tables" expected_tables=314
level=info ts=2021-09-02T20:59:45.050713671Z caller=module_service.go:59 msg=initialising module=ring
level=info ts=2021-09-02T20:59:45.053064752Z caller=module_service.go:59 msg=initialising module=ingester-querier
level=info ts=2021-09-02T20:59:45.055938385Z caller=module_service.go:59 msg=initialising module=distributor
level=info ts=2021-09-02T20:59:45.056865744Z caller=loki.go:272 msg="Loki started"
level=error ts=2021-09-02T20:59:45.060654288Z caller=table_manager.go:218 msg="error syncing tables" err="WebIdentityErr: failed to retrieve credentials\ncaused by: RequestError: send request failed\ncaused by: Post \"https://sts.amazonaws.com/\": dial tcp 52.42.95.231:443: connect: connection refused"
`

**Comment by hairongGao** [comment]
bump into similar issue, but the error for me is

**Comment by sarasensible** [comment]
In my case I had the `loki.storageConfig.aws.insecure` set to true which caused the following connection refused error:

```
bash-4.2# curl -v http://loki-loki-distributed-query-frontend.monitoring.svc.cluster.local:3100/api/prom/label
*   Trying 10.0.38.208:3100...
* Connected to loki-loki-distributed-query-frontend.monitoring.svc.cluster.local (10.0.38.208) port 3100 (#0)
> GET /api/prom/label HTTP/1.1
> Host: loki-loki-distributed-query-frontend.monitoring.svc.cluster.local:3100
> User-Agent: curl/7.79.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Content-Type: application/json; charset=UTF-8
< Vary: Accept-Encoding
< Date: Tue, 19 Apr 2022 16:22:28 GMT
< Content-Length: 226
<
rpc error: code = Unknown desc = WebIdentityErr: failed to retrieve credentials
caused by: RequestError: send request failed
caused by: Post "http://sts.amazonaws.com/": dial tcp 52.119.198.216:80: connect: connection refused
```

The solution was to remove the `insecure: true` from the Helm config and it all worked.

**Comment by hairongGao** [comment]
> In my case I had the `loki.storageConfig.aws.insecure` set to true which caused the following connection refused error:
> 
> ```
> bash-4.2# curl -v http://loki-loki-distributed-query-frontend.monitoring.svc.cluster.local:3100/api/prom/label
> *   Trying 10.0.38.208:3100...
> * Connected to loki-loki-distributed-query-frontend.monitoring.svc.cluster.local (10.0.38.208) port 3100 (#0)
> > GET /api/prom/label HTTP/1.1
> > Host: loki-loki-distributed-query-frontend.monitoring.svc.cluster.local:3100
> > User-Agent: curl/7.79.1
> > Accept: */*
> >
> * Mark bundle as not supporting multiuse
> < HTTP/1.1 500 Internal Server Error
> < Content-Type: application/json; charset=UTF-8
> < Vary: Accept-Encoding
> < Date: Tue, 19 Apr 2022 16:22:28 GMT
> < Content-Length: 226
> <
> rpc error: code = Unknown desc = WebIdentityErr: failed to retrieve credentials
> caused by: RequestError: send request failed
> caused by: Post "http://sts.amazonaws.com/": dial tcp 52.119.198.216:80: connect: connection refused
> ```
> 
> The solution was to remove the `insecure: true` from the Helm config and it all worked.

You really make my day ! Thank you so much !
