### ISSUE TITLE
Loki fluent bit: Extracting and manipulating keys from a log line

### ISSUE THREAD

**Issue by senyosimpson** [grafana/loki#4274]
I'm using the fluent bit Loki plugin for ingesting logs. I want to use a key from a log line as a stream label using the `LabelKeys` configuration option. Unfortunately, I've had no success with it. I've figured the key issue is that the logs aren't parsed into key-value pairs with fluent bit. For example, I have a log line

```
host=xxxxx status=200 method=GET path=/users protocol=HTTP/1.1 response-length=4500
```
When I look at the logs of fluent bit, I get the record

```
map[log:host=xxxxx status=200 method=GET path=/users protocol=HTTP/1.1 response-length=4500]
```

I was hoping I would get something like

```
map[host:xxxxx, status:200 ...]
```
and that could be manipulated so I can set new stream labels using `LabelKeys`. I'm assuming getting the above result through your logs must be possible since it works with Kubernetes labels and ECS log metadata.

I'd basically like to know if there is something specific I need to do with my logs to be able to extract and manipulate keys.

**Comment by senyosimpson** [comment]
Misunderstanding on my side. Figured all I needed to do was add a parser to the fluent bit configuration and use my own custom fluent bit container with it.

**Comment by geevanakash** [comment]
@senyosimpson , Can you explain bit more the parser and custom fluent bit container. I am facing a problem where when I added loki as datasource , I am unable to filter deployed applications/pods via namespace label.
