### ISSUE TITLE
Promtail: inspect with correlation

### ISSUE THREAD

**Issue by Thoro** [grafana/loki#4280]
**Is your feature request related to a problem? Please describe.**
Currently using inspect with promtail and multiple stages / source files, leads to interleaved inspect output, which makes it impossible to correlate which log line failed a certain stage.

**Describe the solution you'd like**
Prepend a (random) identifier in front all inspect stages for each logline, to allow to search for failed log lines.

**Comment by dannykopping** [comment]
@Thoro can you please send through the flags used with Promtail when you received this interleaved output?

**Comment by Thoro** [comment]
@dannykopping  /usr/local/bin/promtail -dry-run --config.file=/etc/promtail/promtail.yaml -inspect

**Comment by dannykopping** [comment]
Thanks for that.

I would suggest using this along with `--stdin` as [described in the docs](https://grafana.com/docs/loki/latest/clients/promtail/troubleshooting/#inspecting-pipeline-stages). You can pipe a single line in to avoid this issue.

I do think you raise a valid point though, but can't guarantee this will be addressed with the highest priority.

**Comment by Thoro** [comment]
The issue is I have millions of lines, and some are failing in the parsing section, pretty hard to find which ones ;)

I can see that some are failing due to the inspect, but I can't figure out which ones they are.

**Comment by dannykopping** [comment]
Fair enough. We'll get to this when we can.

Submissions welcome, though! Should be relatively straightforward - [here's](https://github.com/grafana/loki/pull/4011/files#diff-b7d6427d78025a476dae4d59e0adb2a4b53509fdf7050ce7640779fadea01081) the file where the addition will most likely go.

**Comment by Thoro** [comment]
Any perferences on how this id is generated and it's length? I would go with the same way opentelemetry generated their ids.

**Comment by dannykopping** [comment]
They use 16 random bytes, right? I think that'd suffice. We already use https://github.com/gofrs/uuid but an UUIDv4 is quite long.

In any case, I think it should be hidden behind a disabled flag by default (`--inspect-uuid=true` maybe?) as it's extraneous and could cause confusion, and is only useful in situations like yours.

**Comment by Thoro** [comment]
@dannykopping Yes, 16 random bytes. I added a WIP PR, could you look over it?

I ended up changing the stderr output to stdout, because I still got interleaving with the standard output of the loglines.

I'm not sure the approach with adding a correlation label to each logline is good - but it was the easiest fix I could think of without introducing new fields / new references. Maybe an additional check should be added that this is only done when run with dry-run, because it will break loki.
