### ISSUE TITLE
Promtail Does Not Export Logs In Custom Docker Image

### ISSUE THREAD

**Issue by TheDarkula** [grafana/loki#4285]
**Describe the bug**
The issue is as stated in the title.

I am using biome, which is the free fork of chef's habitat. Essentially, it creates very stripped-down docker images.
One thing that often complicates things is that biome has libraries and the like in non-standard locations.
I am accustomed to remedying this, but I am hitting a runtime bug with promtail.

I want to use promtail to retrieve systemd journal entries. I have this volumes block:

```
    volumes:
      - /var/log/journal/:/hab/svc/promtail/var/log/journal/:ro
      - /etc/machine-id:/etc/machine-id:ro
```

I am building promtail with this command:

```
CGO_CFLAGS="-I$(pkg_path_for core/systemd)/include" go build -trimpath -buildmode=pie -mod=readonly -modcacherw -ldflags "-X github.com/grafana/loki/pkg/util/build.Version=$pkg_version -X github.com/grafana/loki/pkg/util/build.BuildDate=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -linkmode external -extldflags \"${LDFLAGS}\"" ./clients/cmd/promtail
```

The `pkg_path_for` function just returns the path of the specified package.

When running, promtail just shows this:

```
promtail_1    | promtail.default(O): level=info ts=2021-09-03T21:17:54.694560028Z caller=server.go:239 http=[::]:9080 grpc=[::]:9095 msg="server listening on addresses"
promtail_1    | promtail.default(O): level=info ts=2021-09-03T21:17:54.695523863Z caller=main.go:119 msg="Starting Promtail" version="(version=2.3.0, branch=, revision=)"
```

When I check loki through grafana, no logs are sent.

I have also shelled into the promtail container and run `lsof`, and none of the files in `/hab/svc/promtail/var/log/journal` are open.

Also, running `ldd` shows that all dependencies are satisfied:

```
/ # ldd /bin/promtail
	linux-vdso.so.1 (0x00007ffc96791000)
	libpthread.so.0 => /hab/pkgs/core/glibc/2.29/20200305172459/lib/libpthread.so.0 (0x00007f4dc85ac000)
	libdl.so.2 => /hab/pkgs/core/glibc/2.29/20200305172459/lib/libdl.so.2 (0x00007f4dc85a7000)
	libc.so.6 => /hab/pkgs/core/glibc/2.29/20200305172459/lib/libc.so.6 (0x00007f4dc83e4000)
	/hab/pkgs/core/glibc/2.29/20200305172459/lib/ld-linux-x86-64.so.2 => /hab/pkgs/core/glibc/2.29/20200305172459/lib64/ld-linux-x86-64.so.2 (0x00007f4dcdab7000)
```

**To Reproduce**
If necessary, I can give some basic instructions on how to build a biome/habitat image, but it involves quite a few steps.

**Expected behavior**
Promtail should export logs to loki.

**Environment:**
As specified in the details above, this is a custom (scratch) docker image.

**Comment by valankar** [comment]
Not sure if helpful, but recently I was trying to get systemd logging working when running promtail in a docker container. Of all places I found some config regarding `fluentd`:

https://github.com/grafana/loki/blob/71a8f2c2b11b419bd8c0af1f859671e5d8730448/docs/sources/send-data/fluentd/_index.md?plain=1#L61

I have no idea what fluentd is, but it seems these volumes are needed for promtail to read the journal when running in a docker container.
