### ISSUE TITLE
Promtail: Multiline plugin and lots of tailers leads to unfinished logline (with short timeout)

### ISSUE THREAD

**Issue by thoro** [grafana/loki#4288]
**Describe the bug**
I have a lot of log files concurrently open for a single scrape config, in the initial read the multiline stage sometimes misses logs, because for this specific stream no data is read within the max_timeout (in my case 1s), even though it's available.

**To Reproduce**
Start promtail with a config that reads from lots of files, I had 674 (large 5-10 MB each)files in the directory. Enable debug log.
You will see some "flush multiline block due to 1s timeout" logs.

**Expected behavior**
Multiline plugin should always combine data correctly, but I'm also aware this is caused by an overload of the tailers.

Maybe limiting the tailers and how they work is more appropriate than trying to fix the multiline stage.

**Environment:**
 - Infrastructure: bare-metal

**Comment by cstyan** [comment]
@thoro are you still experiencing this issue?

**Comment by thoro** [comment]
I have since adapted how the log files are selected, via an external file.

A bash script writes the current daily name into the file, and promtail then uses this.

**Comment by cstyan** [comment]
Thanks for the update. I'll close this for now but if you run into something similar please feel free to open a new issue with a reference to this one.
