### ISSUE TITLE
Base64 encoding of chunk ExternalKey in filesystem object store prevents per-tenant subdirectories

### ISSUE THREAD

**Issue by jfolz** [grafana/loki#4291]
**Describe the bug**
Docs for [filesystem object storage](https://grafana.com/docs/loki/latest/operations/storage/filesystem/) state that:
> A folder is created for every tenant all the chunks for one tenant are stored in that directory.

What happens instead is that chunks of different tenants are stored at the top level of the specified directory.

The [`Chunk.ExternalKey`](https://github.com/grafana/loki/blob/0e622072e9e0cb16353879aa89f7a80e60e6bb7b/vendor/github.com/cortexproject/cortex/pkg/chunk/chunk.go#L172) method suggests that a hierarchical structure is intended (UserID aka tenant is separated by a slash from the remainder of the key), but the [base64 encoding](https://github.com/grafana/loki/blob/0e622072e9e0cb16353879aa89f7a80e60e6bb7b/vendor/github.com/cortexproject/cortex/pkg/chunk/objectclient/client.go#L22) used by the [storage client](https://github.com/grafana/loki/blob/0e622072e9e0cb16353879aa89f7a80e60e6bb7b/pkg/storage/chunk/storage/factory.go#L301) prevents this from happening.

**To Reproduce**
1. Start Loki multi-tenant with filesystem storage.
2. Send logs from two or more tenants.

**Expected behavior**
Chunks for tenants are stored in subdirectories as stated.

**Environment:**
 - Infrastructure: bare-metal
 - Deployment tool: shell

**Comment by jfolz** [comment]
Notably, the used `base64.StdEncoding` [uses the forward slash character](https://cs.opensource.google/go/go/+/refs/tags/go1.17:src/encoding/base64/base64.go;drc=refs%2Ftags%2Fgo1.17;l=35), so it may produce paths arbitrary subdirectories. `base64.URLEncoding` uses `_` instead which would be safe.

**Comment by LinTechSo** [comment]
hi all, any updates? 
i hits same issue in version 2.4

**Comment by LinTechSo** [comment]
Hi @jfolz , Thanks. but where should i put this[ tenant_folders: true ] or similar in loki yaml configuration?

**Comment by jfolz** [comment]
It's only a WIP PR by me, not something that's currently released. You can watch it to see progress. It's currently blocked on some other changes though (see discussion there).

**Comment by jfolz** [comment]
.

**Comment by jfolz** [comment]
Support for schema v12 added for filesystem storage in #5291 fixes this.
