### ISSUE TITLE
Improve a LogCLI example about Grafana Cloud

### ISSUE THREAD

**Issue by KMiller-Grafana** [grafana/loki#4292]
The request from @doanbutar:

Hi Team, can we please add the following key points to our logcli docs under Grafana Cloud Example https://grafana.com/docs/loki/next/getting-started/logcli/#grafana-cloud-example

- use the ADDR specified in the Loki info for the hosted service
- use the same username as specified in the same place
- use an API key with Viewer role as PASSWORD

This is feedback from our customer

**Comment by erkannt** [comment]
I'm the customer in question. Happy to clarify where I can into issues confusion if desired.
