### ISSUE TITLE
feature: show in context

### ISSUE THREAD

**Issue by matti** [grafana/loki#431]
when I search something like "Exception", allow me to click "show this line in context" where it would make another search and show the line among other lines during that time.

**Comment by steven-sheehy** [comment]
When you say searching, I'm assuming you're meaning in Grafana UI? If so, you should direct such feature requests to [Grafana](https://github.com/grafana/grafana/issues).

**Comment by matti** [comment]
whoops, true

**Comment by hhstu** [comment]
how can i get something like  "cat   xxx.log  |grep  -C  5 "  by  loqql ?
