### ISSUE TITLE
Docs feedback: /storage/_index.md - Azure storage instructions aren't clear

### ISSUE THREAD

**Issue by hterik** [grafana/loki#4311]
Storage instructions for users of Azure is not very clear, this should be a very common use case which should be easier to get started with. Suggest following improvements:

1. Make single-store documentation more prominent with more clear explanation that it is generic, as that is from what i can understand the recommended store nowdays. Right now, for a new user, it is easy to confuse it as yet another specific index store such as Cassandra/BigTable/DynamoDB. Suggest hiding the specific stores under another sub-section.

2. Give a short oneliner explanation that if you are using Azure you should look at Single-Store instead. As described in https://github.com/grafana/loki/issues/343  Since other cloud providers are listed, one doing a quick Ctrl+F for Azure will today find nothing and just maybe assume it's not supported. Perhaps also include an example yaml.

Same goes for https://grafana.com/docs/loki/latest/architecture/ which does not mention Single-Store at all, only listing a few other storage providers as supported.

**Comment by cyriltovena** [comment]
This is correct thanks for the issue we should do this.

@KMiller-Grafana what do you think ?

**Comment by RomainPhil** [comment]
Any update concerning the requirement to use with azure blob storage ?

**Comment by KMiller-Grafana** [comment]
I still have no time to work on this. Hopefully soon.  Am bumping the priority within my list of tasks.

**Comment by GrafanaWriter** [comment]
@JStickler - can you please investigate?

**Comment by JStickler** [comment]
Closing as stale.  There have been multiple recent updates to the storage and architecture docs which should address this issue, especially around TSDB being the recommended single-store.

https://grafana.com/docs/loki/next/storage/ 

https://grafana.com/docs/loki/next/get-started/architecture/
