### ISSUE TITLE
Promtail has no logs with the jobs with EC2 autodiscovery

### ISSUE THREAD

**Issue by Karabiy** [grafana/loki#4318]
Job with EC2 service discovery based doesn't have any log being scrapped. 

1. Started Loki 2.0.0 (shouldn't affect) 
2. Started Promtail 2.3.0

```scrape_configs:
  - job_name: journal
    journal:
      json: false
      max_age: 12h
      path: /var/log/journal
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
  - job_name: ec2-logs
    ec2_sd_configs:
      - region: us-east-2
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: name
        action: replace
      - source_labels: [__meta_ec2_instance_id]
        target_label: instance
        action: replace
      - source_labels: [__meta_ec2_availability_zone]
        target_label: zone
        action: replace
      - action: replace
        replacement: /var/log/auth.log
        target_label: __path__
      - source_labels: [__meta_ec2_private_dns_name]
        regex: "(.*)"
        target_label: __host__
```
For specified configuration there's no logs being mentioned on UI, and no send. 

 - Infrastructure: AWS, EC2 
 - Deployment tool: manual 
 
![Screenshot_20210913_160026](https://user-images.githubusercontent.com/31805736/133088969-f680bdc1-0b74-4a6a-b002-d1258e9480fa.png)

**Comment by supersaeyan** [comment]
Facing the same issue, service discovery shows all targets dropped with error message "Dropped: ignoring target, wrong host"

Further tried various other ways of trying to select the machine promtail was running on by using regex: (/.) and target_label: host
But it matched all targets in both cases, resulting in duplicate logs with unique EC2 labels.

Can we please get a solution to match only the instance promtail is running on.
I am only using EC2 service discovery (ec2_sd) to add the Name tag, 
Last resort workaround would be by not using ec2_sd and adding the hostname: __host__ label.

**Comment by supersaeyan** [comment]
Another observation, I am using ubuntu where $HOSTNAME returns ip-1,2,3,4 instead of ip-1.2.3.4.compute.internal

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-naming.html

Found this doc if that is significant here

**Comment by supersaeyan** [comment]
@Karabiy Were you able to solve this?
