### ISSUE TITLE
Loki Ingester | Pod Never Ready | failed to flush user

### ISSUE THREAD

**Issue by sherifkayad** [grafana/loki#4323]
**Describe the bug**
All of a sudden one of the Loki Ingester Pods won't start (not ready) and the following error is continuously logged:
```
failed to flush user" err="RequestCanceled: request context canceled\ncaused by: context deadline exceeded"
```

**Expected behavior**
Loki should start normally

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Helm

**Screenshots, Promtail config, or terminal output**
![image](https://user-images.githubusercontent.com/8362784/133204776-8e0a8e55-4e2a-41b7-8cd5-f9baf05adcbe.png)

**Comment by liguozhong** [comment]
![image](https://user-images.githubusercontent.com/9583245/133542156-8ab21684-9a6b-4cc6-8888-d68ab4e79bd7.png)

**Comment by liguozhong** [comment]
kubectl delete po ingester-0 --grace-period=0 --force  -n loki
kubectl delete po ingester-1 --grace-period=0 --force  -n loki
kubectl delete po ingester-2 --grace-period=0 --force  -n loki

**Comment by sherifkayad** [comment]
@liguozhong thanks a lot for your help .. do you care to explain what exactly is wrong and these properties are fixing? I am not sure I understood the values of the properties you sent me.

**Comment by liguozhong** [comment]
![image](https://user-images.githubusercontent.com/9583245/133799983-5bbfc3f3-9dba-46f7-85b3-dd03d2a580c2.png)

**Comment by liguozhong** [comment]
Because of the code above. When err!=nil will re-execute, an infinite loop will occur ...

**Comment by sherifkayad** [comment]
@liguozhong Thanks for your help. Seems like the increased timeout has solved the problem for us. Closing this ticket.
