### ISSUE TITLE
Problem with permissions denied on /data/loki/chunks

### ISSUE THREAD

**Issue by Evantage-WS** [grafana/loki#4326]
Hi,

I have installed loki with
`helm upgrade --install loki grafana/loki-stack -f override-values.yaml -n loki --create-namespace
`

This is the contents of my override-values.yaml file:

`loki:
  enabled: true
  persistence: 
    enabled: true
    size: 1Gi
`

and I do get the permissions denied error below. Any help would be appreciated

`level=error ts=2021-09-14T12:45:19.990238168Z caller=log.go:106 msg="error running loki" err="stat /data/loki/chunks: permission denied\nerror initialising module: compactor\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:105\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:75\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:220\nmain.main\n\t/src/loki/cmd/loki/main.go:132\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374"`

Thanks!

**Comment by cdx7779** [comment]
msg="error running loki" err="stat /data/loki/chunks: permission denied\nerror initialising module:

**Comment by cdx7779** [comment]
persistence:
 # type: pvc
  enabled: true
  #storageClassName: loki-standard
  accessModes:
   - ReadWriteOnce
  size: 50Gi
  #annotations:
  #selector:
  #  matchLabels:
  #    app.kubernetes.io/name: loki
   #subPath: ""
  existingClaim: loki-standard
 # finalizers:
  #  - kubernetes.io/pvc-protection
## Pod Labels

**Comment by cdx7779** [comment]
loki     持久化  挂载   报错
