### ISSUE TITLE
server returned HTTP status 400 Bad Request (400): entry out of order for stream

### ISSUE THREAD

**Issue by bvandewalle** [grafana/loki#436]
I'm getting those type of errors nonstop on my cluster's Loki:

```
level=error ts=2019-03-29T02:06:49.147408285Z caller=client.go:185 msg="final error sending batch" status=400 error="server returned HTTP status 400 Bad Request (400): entry out of order for stream: {__filename__=\"/var/log/pods/33cce0fa-4fe7-11e9-a0ac-0a75695ff060/calico-node/0.log\", container_name=\"calico-node\", controller_revision_hash=\"4160928241\", instance=\"calico-node-gd7fx\", job=\"kube-system/\", k8s_app=\"calico-node\", namespace=\"kube-system\", pod_template_generation=\"1\", role_kubernetes_io_networking=\"1\", stream=\"stdout\"}"
```

I deployed the upstream Helm chart, the only modification I did was to delete all the drop statements from the config file (with those drop statements I would miss most of my pods for some reason).

**Comment by daixiang0** [comment]
Without delete all drop rule it would be ok i think.
The reason you mean is tracked in #432.

**Comment by daixiang0** [comment]
I test at local, the whole loki still work, while those logs exist.

**Comment by olegderid** [comment]
Please, reopen this issue it is reproduced consistently.

**Comment by ofiry-tm** [comment]
I have this issue also. it coem and goes and i have no idea why
