### ISSUE TITLE
recording rule giving an error

### ISSUE THREAD

**Issue by mvkrishna86** [grafana/loki#4379]
**Describe the bug**
I created a recording rule as below 
`sum(count_over_time({container="istio-proxy"} | json | __error__="",path!="" [1m])) by (app,path,method,response_code)`
but when I applied it, I am getting below error:
`var substitution failed for 'loki': json: unsupported type: map[interface {}]interface {}`

The same is working fine in Grafana Explore screen and generating the metrics.

**To Reproduce**
Specified the recording rules as below:
```
      directories:
        tenant_id:
          rules.yaml: |-
            groups:
              - name: logs-to-metrics
                interval: 1m
                rules:
                  - record: count_requests_1m
                    expr: 'sum(count_over_time({container="istio-proxy"} | json | __error__="",path!="" [1m])) by (app,path,method,response_code)'
```

**Expected behavior**
The recording rule should create new metrics  and push it cortex.

**Environment:**
 - Infrastructure: kubernetes
 - Deployment tool: Helm, Flux
 - Loki 2.3.0

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
```
$ kl get kustomization
NAME      READY   STATUS                                                                                      AGE
logging   False   var substitution failed for 'loki': json: unsupported type: map[interface {}]interface {}   108d
```

Helm describe output:

```
warning: Upgrade "loki-distributed" failed: timed out waiting for the condition
  Normal  error  26m                   helm-controller  reconciliation failed: Helm upgrade failed: timed out waiting for the condition
  Normal  error  4m23s (x18 over 26m)  helm-controller  reconciliation failed: upgrade retries exhausted
```

**Comment by dannykopping** [comment]
@mvkrishna86 this error seems to be coming from Flux, not from Loki.

I'm unfamiliar with Fluxv2, so unfortunately can't assist you there, but from what I can see in [the source](https://github.com/fluxcd/kustomize-controller/blob/main/controllers/kustomization_controller.go#L544-L557) is that this is related to variable substitutions.

Closing for now as this is not an issue with Loki strictly speaking, but please let us know if you find a solution for this in case another community member runs into this.
