### ISSUE TITLE
Data Sources / MySQL cannot use other port，except port 3306

### ISSUE THREAD

**Issue by smally10** [grafana/loki#4383]
**Describe the bug**

**To Reproduce**
1. Started Loki (SHA or version)
2. Started Promtail (SHA or version) to tail '...'
3. Query: `{} term`

**Expected behavior**

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by dannykopping** [comment]
@smally10 not sure that this is for us?
