### ISSUE TITLE
Loki's Promtail cuts long log lines with length greater than 16384 characters

### ISSUE THREAD

**Issue by MurzNN** [grafana/loki#4392]
**Describe the bug**
I have several very long lines (18000+ symbols) in Docker container logs, that presents in Docker's json log file as full JSON line without cutting.

But Loki shows them truncated at 16384 character, as result I see only last part of that enormous log line.

For example, I see only last 1000 symbols of line with length 17384 characters, but not the first part of line.

I found this "magic number" in documentation only here https://grafana.com/docs/metrics-enterprise/latest/config/reference/
```
  # The number of shards of series to use in TSDB (must be a power of 2).
  # Reducing this will decrease memory footprint, but can negatively impact
  # performance.
  # CLI flag: -blocks-storage.tsdb.stripe-size
  [stripe_size: <int> | default = 16384]
```
But this is for Loki Enterprise edition, and in Community edition it not works - with this config:
```
tsdb:
  stripe_size: 65536
```
I receiving the error on startup:
```
failed parsing config: /etc/loki/loki-config.yaml: yaml: unmarshal errors:
  line 67: field tsdb not found in type main.Config
```

Is there any solution exists for this problem? Or only a workaround to decrease log line length on application side?

**To Reproduce**
1. Started Grafana Agent with Loki
2. Started Docker container with some app
3. Add the line with length 18326 characters to container stdout
4. Do the query to Loki database to show that log line.
You will see only last 1942 symbols of your log line.

**Expected behavior**
All enormous log line should be available.

**Comment by ukolovda** [comment]
See #2281 , it should be a docker-related issue.

**Comment by MurzNN** [comment]
Thanks @ukolovda, seems similar but in my case it "eats" the first part of line. But maybe those "eatings" are happened because of wrong pipeline settings on my side, I will recheck.

For easier debugging I've created a docker-compose repo that reproduces the problem with splitting long lines to two parts: https://github.com/MurzNN/loki-long-lines

**Comment by MurzNN** [comment]
So the originate of this problem is Docker logs, that splits long lines to two log records, and solution is discussed in https://github.com/grafana/loki/issues/2281 so lets close this issue.
