### ISSUE TITLE
Loki reports "unkown" (sic) for unknown log severity

### ISSUE THREAD

**Issue by candlerb** [grafana/loki#441]
**Describe the bug**

See screenshot at end: it shows a log category of "unkown" rather than "unknown"

I don't know whether it's loki itself of grafana which is generating this.

**To Reproduce**
1. Started loki c9948233
2. Started promtail c9948233 to tail '/var/log/*log'
3. Open in Grafana 6.0.2 with Loki data source
4. Query: `{job="varlogs"}`

**Expected behavior**
I wasn't expecting to see log severity parsing; it wasn't mentioned in loki documentation, I haven't yet found out where in loki or grafana this takes place, and it's not in the log label set (aside: it would be useful if it were)

However, I would have expected to see "unknown" rather than "unkown"

**Environment:**
 - Infrastructure: Ubuntu 18.04 lxd container
 - Deployment tool: built from source with go 1.12.1

**Screenshots, promtail config, or terminal output**

![image](https://user-images.githubusercontent.com/44789/55292357-bb803780-53e1-11e9-8ae3-1a79294cd720.png)

**Comment by candlerb** [comment]
After some more experimentation, I think this may be happening grafana-side.

If I click on "info" to filter just to info messages, then tcpdump shows no additional query made to loki.

It appears that if the string "info" appears anywhere in the message - including "x-info" or "ci-info" - then grafana classifies it as "info".

![image](https://user-images.githubusercontent.com/44789/55292608-cee0d200-53e4-11e9-9397-f7febe92968d.png)

**Comment by daixiang0** [comment]
@candlerb I use grafana:master, the "unkown" typo gone.

**Comment by candlerb** [comment]
Thank you, I see now:

```
$ git diff v6.0.2 master | grep unkown
+$logs-color-unkown: $gray-2;
+$logs-color-unkown: $gray-5;
-  unkown = 'unkown',
-  [LogLevel.unkown]: getThemeColor('#8e8e8e', '#dde4ed'),
-    expect(getLogLevel('')).toBe(LogLevel.unkown);
-    expect(getLogLevel('this is information')).toBe(LogLevel.unkown);
-    return LogLevel.unkown;
-    level = LogLevel.unkown;
 $logs-color-unkown: $gray-2;
@@ -387,8 +391,8 @@ $logs-color-unkown: $gray-2;
 $logs-color-unkown: $gray-5;
```

However, even in master, I see that "unkown" still exists in a few places, mainly CSS:

```
$ grep -iR unkown . 2>/dev/null
./public/app/plugins/datasource/elasticsearch/elastic_response.ts:      result.message = err.reason || 'Unkown elastic error response';
./public/sass/_variables.light.generated.scss:$logs-color-unkown: $gray-5;
./public/sass/components/_panel_logs.scss:    background-color: $logs-color-unkown;
./public/sass/_variables.dark.generated.scss:$logs-color-unkown: $gray-2;
./packages/grafana-ui/src/themes/_variables.light.scss.tmpl.ts:$logs-color-unkown: $gray-5;
./packages/grafana-ui/src/themes/_variables.dark.scss.tmpl.ts:$logs-color-unkown: $gray-2;
./vendor/github.com/smartystreets/goconvey/convey/gotest/utils.go:	file, line, name = "<unkown file>", -1, "<unknown name>"
```

**Comment by steven-sheehy** [comment]
Those unkown don't get displayed to the UI, with the exception of that elastic_response which is not applicable to Logs. I think this can be closed.

**Comment by daixiang0** [comment]
yep, @candlerb those unkown are value of css, so UI is right.
If you want to fix all unkown, better to ask an issue in [grafana](https://github.com/grafana/grafana).
