### ISSUE TITLE
No serviceaccount for a promtail-only release

### ISSUE THREAD

**Issue by sboschman** [grafana/loki#442]
The promtail part of the chart doesn't include its own serviceaccount. By default it is linked to the serviceaccount of the loki part of the chart. Unfortunately the loki serviceaccount is only created if loki is enabled. If you try to only deploy promtail you end up without a serviceaccount for it and k8s won't start the pod cause of the missing serviceaccount.

**Comment by daixiang0** [comment]
@sboschman good catch, thanks.
