### ISSUE TITLE
Ruler: add limit for number of series produced by recording rules

### ISSUE THREAD

**Issue by dannykopping** [grafana/loki#4439]
**Is your feature request related to a problem? Please describe.**
A change has been made [upstream in prometheus](https://github.com/prometheus/prometheus/pull/9260/files) which allows for a limit to be passed to the alerting/recording rules evaluation, to prevent excessive series being produced.

**Describe the solution you'd like**
We should revendor `prometheus/prometheus` to obtain this functionality and expose this limit as a per-tenant and/or global configuration.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by SasSwart** [comment]
I'd be happy to take a look at this one

**Comment by vardhaman-surana** [comment]
looks like @SasSwart did not get a chance to work on it. 
@dannykopping can you assign this to me please ?

**Comment by dannykopping** [comment]
Done @vardhaman-surana 👍
