### ISSUE TITLE
Tailing of docker logs stops after ~30s with "Error grabbing logs: error decoding log message: context deadline exceeded"

### ISSUE THREAD

**Issue by dietmarb01** [grafana/loki#4447]
**Describe the bug**
When _tailing docker logs_ of a container that uses the loki-driver, output stops after 30 seconds with
`Error grabbing logs: error decoding log message: context deadline exceeded (Client.Timeout or context cancellation while reading body)`

Loki itself continues to receive logs (visible in Grafana).
The local log also continues to be recorded. Using `docker-compose logs --last=30 -t` shows that they are current.
It is the local _tailing_ that stops after ~30s, regardless whether I start from the beginning of the log with `docker-compose logs -t -f` or pick up later with `docker-compose logs --tail=10 -t -f`. 

**To Reproduce**
1. Started Loki (2.3.0)
2. Started Promtail (2.3.0), exposing the Loki API at localhost:3100, forwarding to "central" Loki
3. Started nginx with logging configured to loki-driver (2.3.0)

**Expected behavior**
Logging should continue (like it does when using json-file)

**Environment:**
 - Infrastructure: Linux VM
 - Docker version: 10.20.8
 - Deployment tool: docker-compose 1.29.2

**Screenshots, Promtail config, or terminal output**

```
docker-compose logs -f 

...
nxie2   | remote_addr=10.123.21.12 remote_user=- connection=1 host=e2.at.thales protocol=HTTP/2.0 method=GET cache_status=MISS status=401 body_bytes_sent=110 request_time=0.010 uri=/confluence/json/reindextaskprogress.action query="-" user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36 Edg/86.0.622.38" referer="https://my.company/confluence/admin/search-indexes.action" service=confluence
nxie2   | Error grabbing logs: error decoding log message: context deadline exceeded (Client.Timeout or context cancellation while reading body)
```

```
docker-compose.yaml:

    logging:
      driver: loki
      options:
        max-file:  '9'
        max-size:  '20m'
        no-file:   'false'
        keep-file: 'true'
        loki-url: http://localhost:3100/loki/api/v1/push
        loki-retries: '1'
        loki-timeout: '3s'
```

```
daemon.log:

Oct  9 20:29:28 atviesu209 dockerd[18951]: time="2021-10-09T20:29:28+02:00" level=info msg="level=info ts=2021-10-09T18:29:28.050872358Z caller=driver.go:77 msg=\"starting logging driver for container\" id=9c125ca3f68018bf6749462c41a391a7ebbad421f35f7a3c3ac5da2580a1f81c config=\"map[keep-file:true loki-retries:1 loki-timeout:3s loki-url:http://localhost:3100/loki/api/v1/push max-file:9 max-size:20m no-file:false]\" file=/run/docker/logging/13c6fda732533ca376e23b573fb5c30cfc446be35e4e3bc30b6ce3f53f6401fb logpath=/var/log/docker/9c125ca3f68018bf6749462c41a391a7ebbad421f35f7a3c3ac5da2580a1f81c/json.log" plugin=36cafce24410981da4205d5618684b221537c51fdc85a0fad31435a418926683

Oct  9 20:29:28 atviesu209 containerd[586]: time="2021-10-09T20:29:28.082334187+02:00" level=info msg="starting signal loop" namespace=moby path=/run/containerd/io.containerd.runtime.v2.task/moby/9c125ca3f68018bf6749462c41a391a7ebbad421f35f7a3c3ac5da2580a1f81c pid=5843

Oct  9 20:29:28 atviesu209 systemd[1]: Started libcontainer container 9c125ca3f68018bf6749462c41a391a7ebbad421f35f7a3c3ac5da2580a1f81c.

Oct  9 20:29:50 atviesu209 systemd[1]: run-docker-runtime\x2drunc-moby-94060038709f4e921730e9793bfcc31d4716850fe95a490cabaaab6868e2b3c0-runc.x2539H.mount: Succeeded.

Oct  9 20:29:58 atviesu209 dockerd[18951]: time="2021-10-09T20:29:58.906092643+02:00" level=error msg="Error streaming logs: error decoding log message: context deadline exceeded (Client.Timeout or context cancellation while reading body)" container=9c125ca3f68018bf6749462c41a391a7ebbad421f35f7a3c3ac5da2580a1f81c method="(*Daemon).ContainerLogs" module=daemon

```

**Comment by dietmarb01** [comment]
Also noticeable is the absence of the JSON-log when using loki-driver on the host-VM, despite `keep-file=true` and `no-file=false`.
Daemon log indicates that is saved _inside_ the loki-driver container, which I wouldn't know how to access for a post-mortem analysis.

**Comment by koloboid** [comment]
same there, @dietmarb01 did you find any workarround?

**Comment by dietmarb01** [comment]
No workaround other than junking the Loki-driver and using promtail on the docker json logs directly. 

Works better than expected: Promtail keeps scanning for new logs and picks up those of new containers without further action, missing just the ones that are too short-lived. Using `static_config` with  `__path__: "<docker-root>/*/*-json.log"` is all you need, no `file_sd`. 

To control for which containers I want to have logs collected, I tag log-lines on the docker side and use a pipeline in Promtail.  With additional tags I can even control sending to a "specialised" pipeline for preprocessing.

Container execution and log forwarding fully decoupled:-)

**Comment by koloboid** [comment]
It's magnificent! Thanks for sharing!

**Comment by koloboid** [comment]
Just mention - with latest driver this issue does not reproduces anymore. I think we can close this task.

**Comment by jeschkies** [comment]
> It is the local tailing that stops after ~30s

@dietmarb01 what do you mean by this?

**Comment by dietmarb01** [comment]
@jeschkies 
Log records keep being forwarded to Loki, but `docker logs --follow` does not produce any more output after ~30s

**Comment by jeschkies** [comment]
I wonder whether this is really a Loki Docker driver issue. You could enable the debug logs for the driver. It could be that it is too slow processing the logs.

**Comment by dietmarb01** [comment]
I would be surprised if it would be too slow -- all sites I used this on are internal ones with neglegible load.
