### ISSUE TITLE
Accessibility Feature request - Colors in line_format

### ISSUE THREAD

**Issue by Jessimon** [grafana/loki#4454]
**Is your feature request related to a problem? Please describe.**
When you have logs that contain a lot of similar data or have a lot of content it is very easy to take the wrong data from the log.

**Describe the solution you'd like**
This could be solved by adding color tags to the line_format so that you can give different colors to labels.
For example
`line_format "{{.host_name}} {{.status}} \"{{.info}}\" - Time: {{divf .time_micros 1000000}} sec"`
can become
`line_format "{{.host_name}} {{red .status}} \"{{.info}}\" - Time: {{blue divf .time_micros 1000000}} sec"`

**Describe alternatives you've considered**
An alternative is to work with spaces and special chars.
Example:
`line_format "{{.host_name}} -- {{.status}} -- \"{{.info}}\" -- Time: {{divf .time_micros 1000000}} sec"`
This works if the log lines are not too long.
Also this is not something you can use in all cases because you log may contain -- as part of the log.

**Additional context**
Colors also attract more attention from the user that spaces or special chars.

Thank you

**Comment by mllab-nl** [comment]
@Jessimon Would be nice to have that. 
meanwhile this might be helpful tp you and others: 
Loki is using go thttps://pkg.go.dev/text/template in https://grafana.com/docs/loki/latest/logql/template_functions/
That  means that you can do things like: 
{{if and (ge .status `200`) (lt .status `300`)}} OK {{.status}} {{else if and (ge .status `300`) (lt .status `400`) }} WARN {{.status}} {{else}} ERR {{.status}} {{end}} - from {{.remote_addr}} {{.http_host}} {{.request}} 

Using ERR and WARN will give you 2 extra colors: RED and YELLOW
![image](https://user-images.githubusercontent.com/29844962/181533823-a42f7e21-c7ba-4003-a4f1-b0259a11fffc.png)

You can test your template in any playground. I have used this one 
![image](https://user-images.githubusercontent.com/29844962/181535713-b13983d3-27fd-4224-a084-66c576e5e2ed.png)
https://repeatit.io/

Hope this is helpfull

**Comment by Jessimon** [comment]
@mllab-nl mllab-nl
Did not think of that.
Ok, that ls already something i can do indeed.

To get Green, what text is needed? INFO?
Most of my logs are standard not color labeled by loki.

Thanks for posting this mllab-nl.

**Comment by Alexsey** [comment]
there is a workaround - you can use ANSI escape codes, e.g.:
```
 | {{.host_name}} \u001b[31;3m{{.status}}\u001b[0m \"{{.info}}\" - Time: \u001b[31;1m{{divf .time_micros 1000000}}\u001b[0m sec
```
and combining this with what @mllab-nl you can even color the same part in different color depending on content

So I would say you can do pretty much anything although the produced templates code is quite ugly :(

**Comment by Jessimon** [comment]
@Alexsey @mllab-nl 
Thank you both for the help.

I made some Grafana dashboards with the methods shown and it is easier to read the logs and find the info you need or care about.
The dashboard is notisablely slower, but i guess that is the price to pay.

**Comment by Mastermho** [comment]
If someone stumbles over this old request, as me:

It is possible to color Text in in Loki.
This will do the trick:
| line_format `{{printf "\033[34m %s %s %s \033[32m %s" .value1 .value2 .value3 .value4 }}: {{ printf "\033[0m %s"  __line__ }}`

**Comment by Liquidmasl** [comment]
> If someone stumbles over this old request, as me:
> 
> It is possible to color Text in in Loki. This will do the trick: | line_format `{{printf "\033[34m %s %s %s \033[32m %s" .value1 .value2 .value3 .value4 }}: {{ printf "\033[0m %s" __line__ }}`

I have not managed to do that, the query executes but the text just stays white whatever I do... 
Am I missing something?

```
{service_name=~"$Service", service_name!="backbone"}  | regexp "(?P<log>.*)" 
| line_format "{{ printf \"%-15.15s\" .service_name }} | {{ printf "\u001b[1m %s \u001b[0m" .log }} 
```

**Comment by Mastermho** [comment]
Hi Liquidmasl
You have to enclose the line_format in backticks, then you are able to youse the doublequote within the line_format command.

![Image](https://github.com/user-attachments/assets/d274bd6c-1a69-40fc-91b5-e917206c61aa)
