### ISSUE TITLE
[Proposal] use go-discover for node discovery in cloud environment

### ISSUE THREAD

**Issue by yongzhang** [grafana/loki#4464]
In k8s environment, loki uses a headless service name for node discovery
```
memberlist:
  abort_if_cluster_join_fails: false

  # Expose this port on all distributor, ingester
  # and querier replicas.
  bind_port: 7946

  # You can use a headless k8s service for all distributor,
  # ingester and querier components.
  join_members:
  - loki-gossip-ring.loki.svc.cluster.local:7946
```

But I didn't find any native service discovery way out of k8s cluster, unless we rely on third party service like consul.
In cloud environment like aws, there's a go library https://github.com/hashicorp/go-discover, which can be used to discover ip addresses of nodes, and I know it's a built-in feature in consul for auto-discovery, it will be great if loki can use it to discover members without other dependencies, and, if this is possible, deploy a distributed loki cluster with AWS autoscaling group will be super easy then. Thanks.

**Comment by UpperM** [comment]
+1
