### ISSUE TITLE
Escaping not work on label names

### ISSUE THREAD

**Issue by dr-abadis** [grafana/loki#4470]
**Describe the bug**
I have a label name in which there are dash characters. Using `\` or backticks does not escape it and error occures.
This is my query:

{agent="nginx"} | json method="transaction.request.method",uri="transaction.request.uri",cdn="transaction.client_ip",host="transaction.request.headers.Host",clientIp=`transaction.request.headers.X-Forwarded-For`

There is no problem with method,uri,clientIp and host. but for X-Forwaded-For with backslash or backtick, error occures.

**To Reproduce**
1. Started Loki go1.16.2
2. Started Promtail go1.16.2
3. Query: {agent="nginx"} | json method="transaction.request.method",uri="transaction.request.uri",cdn="transaction.client_ip",host="transaction.request.headers.Host",clientIp="transaction.request.headers.X\-Forwarded\-For"
4. Query: {agent="nginx"} | json method="transaction.request.method",uri="transaction.request.uri",cdn="transaction.client_ip",host="transaction.request.headers.Host",clientIp=`transaction.request.headers.X-Forwarded-For`

**Expected behavior**
Error should not happen

**Environment:**
 - Infrastructure: Grafana
 - Deployment tool: Loki,Promtail

**Screenshots, Promtail config, or terminal output**
rpc error: code = Unknown desc = parse error : stage '| json rule_1="transaction.messages[0].details.match",method="transaction.request.method",uri="transaction.request.uri",cdn="transaction.client_ip",host="transaction.request.headers.Host",clientIp="transaction.request.headers.X-Forwarded-For"' : cannot parse expression [transaction.request.headers.X-Forwarded-For]: unexpected char -

**Comment by sigurdblueface** [comment]
try 
```
{agent="nginx"} | json clientIp=`transaction.request.headers["X-Forwarded-For"]`
```

**Comment by PieterDr** [comment]
I've just ran into this issue as well, but the workaround suggested by @sigurdblueface is not possible for me.
My problem is that the label is a top-level field in the JSON structure, so I cannot use the field accessor syntax.

e.g.

`{job=~"$service", env=~"$environment"} 
| json message, transactionId=`X-Log-Transaction-Id`

fails with error:

`2 errors: rpc error: code = Unknown desc = parse error : stage '| json message="message",transactionId="X-Log-Transaction-Id"' : cannot parse expression [X-Log-Transaction-Id]: unexpected char -; rpc error: code = Unknown desc = parse error : stage '| json message="message",transactionId="X-Log-Transaction-Id"' : cannot parse expression [X-Log-Transaction-Id]: unexpected char -`

**Comment by OktarianTB** [comment]
I had the same issue as @PieterDr and was able to solve it using the suggested workaround from @sigurdblueface.

The field I was trying to parse was `reservation-duration` which gave me the `cannot parse expression` error:
```
... | json reservation_duration="reservation-duration"
```

But the workaround worked fine:
```
... | json reservation_duration=`["reservation-duration"]`
```

**Comment by PieterDr** [comment]
The documentation could be improved then imo. I tried various different syntax constructions to make it work, but that one did not occur to me.
