### ISSUE TITLE
How to get all logs through the /loki/api/v1/tail interface

### ISSUE THREAD

**Issue by xiaozhi747** [grafana/loki#4489]
**Describe the bug**
Through the documentation, it is found that the /loki/api/v1/tail interface has a limit parameter to set the maximum number of entries to be returned, but I set 200,000, and the number of logs that can be seen is only about 2,000.

**To Reproduce**
My request connection is as follows: ws://xxx.com/logger/push/loki/api/v1/tail?query={record_step_uuid=\"74c134467d1b43eebe57467f98aaf01f\"}&start=1633676882285000000&limit=200000

**Expected behavior**
Able to display the number of logs around 200,000

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
Only able to display logs of about 2000 lines

**Comment by guobei2028** [comment]
I got the same problem.

**Comment by guobei2028** [comment]
@sandeepsukhani  Can you help us for this problem? thank you so much

**Comment by jeschkies** [comment]
Is there a particular reason to use `tail`? In any case, you could run a new tail request and set start to the timestamp of the last entry plus one. Say you received an entry at `1642177577802175688` then your next request would be `/loki/api/v1/tail?start=1642177577802175689`. This relates to #4793.

**Comment by guobei2028** [comment]
@jeschkies 
why need run a new tail request？
For example, when the number of log entries under the current label is 3000, and the limit of the tail interface is 5000,
I should be able to find all the logs with /loki/api/v1/tail?start=1642177577802175688. Should not initiate a new request with entry at 1642177577802175689.

**Comment by jeschkies** [comment]
Ah, you mean the request didn't return all entries even though it was *not* exceeding the limit? This may be a silly question but how did you verify the actual number of entries? Did you use [GET /loki/api/v1/query](https://grafana.com/docs/loki/latest/api/#get-lokiapiv1query)?

I'm trying to figure out whether the endpoint has a bug.

**Comment by guobei2028** [comment]
@jeschkies 
yes, when I use GET /loki/api/v1/query_range can get all logs, but GET /loki/api/v1/tail not. 
when I use tail, set limit to 5000, and the number of logs that can be seen is only about 2,000.

**Comment by vemulavarun** [comment]
give an example of loki/api/v1/tail
