### ISSUE TITLE
Add docs about setting up Promtail with log rotation

### ISSUE THREAD

**Issue by danmdinu** [grafana/loki#4526]
**Is your feature request related to a problem? Please describe.**
I couldn't find information on configuring Promtail to work with rolling log files. 
Say Promtail is configured to monitor for `*.log` files. A common scenario is that a `current_log.log` file is being rolled once it reaches a certain size in MB and gets renamed to `log_start_date.log` while a new `current_log.log` file is created. 

**Describe the solution you'd like**
I'd like to understand how to configure Promtail in the scenario described so that logs that were already parsed are not read a second time.

**Comment by vlad-diachenko** [comment]
it's still valid

**Comment by wang-yyi** [comment]
Is there a solution to this problem

**Comment by vlad-diachenko** [comment]
hey @wang-yyi . we do not know for sure if there is an issue. we will investigate how promtail deals with rotated files.
also, it depends on file rotation strategy... files might be rotated in a different way, some libraries might create a copy of base log file and just truncate the base file, some of them rename the base file and creates a new one... so, we are going to investigate it and will provide a solution and recommendation.

**Comment by talroze** [comment]
I have the same issue,
Rotated logs are resetting the positions.yaml file location,
Hence rendering the data not be scanned/scrapped/pushed to the loki server.
I need to find out the solution since without this data I cant use the Loki system.

**Comment by cedsana** [comment]
This isn't stale.

**Comment by dannykopping** [comment]
Closed by #8096
