### ISSUE TITLE
Consistent width for chunk names

### ISSUE THREAD

**Issue by candlerb** [grafana/loki#454]
**Describe the bug**
(Not really a bug, just something that could be neater)

Sometimes the loki chunk filenames are a different length, which puts an "=" sign in the base64 encoding, which makes the shell have to escape them.

This is due to using either 15 or 16 characters of hex data after the first part of the filename.

**To Reproduce**
1. Started loki (c9948233)
2. Started promtail (c9948233) to tail '/var/logs/*.log' (default config)
3. Wait around
4. `ls /tmp/loki/chunks`

**Behavior**

```
# ls /tmp/loki/chunks/
 ZmFrZS83YTI1N2M5ZWI2YTYyMDkwOjE2OWYzMTZiODE2OjE2OWYzMTZiODYyOjdkNzMyNGQy
 ZmFrZS83YTI1N2M5ZWI2YTYyMDkwOjE2OWYzMzk2ZWExOjE2OWYzMzk2ZWExOjE1MGVkZDA2
 ZmFrZS83YTI1N2M5ZWI2YTYyMDkwOjE2OWYzNzA1Y2YzOjE2OWYzNzA1Y2YzOmY3YzNhNjk3
 ZmFrZS83ZTAyYmFmNDA1NmYyN2Q0OjE2OWYzMTZiODE5OjE2OWYzMWE2MjU0OjE0ZDliNGE4
 ZmFrZS83ZTAyYmFmNDA1NmYyN2Q0OjE2OWYzMjExYmEyOjE2OWYzMjI5ZmU0OjNkMzM2M2I3
 ZmFrZS84ZTk0MDgzMzdiZDZlYzA0OjE2OWYzMTZiODFhOjE2OWYzMTZiODJmOjIyYmFhYWI2
'ZmFrZS85N2RiMjQ0MDM5ZWFiOGY6MTY5ZjM3MDVjZjM6MTY5ZjM3MDVjZjM6OGNiNmIwMjY='
'ZmFrZS85N2RiMjQ0MDM5ZWFiOGY6MTY5ZjMxNmI4MTc6MTY5ZjMxNmI4MjI6YWM3NWFkZmI='
'ZmFrZS85N2RiMjQ0MDM5ZWFiOGY6MTY5ZjMzOTZlYTE6MTY5ZjMzOTZlYTE6YTc3MjQ0MDA='
 ZmFrZS85NDY0MWIwNjQ0MGRkNGE0OjE2OWYzMTZiODFiOjE2OWYzMTZiOGVmOjI0ODBjYWVh
 ZmFrZS85ZjY0NjJiM2YxZmM5ZmZlOjE2OWYzMTZiODE5OjE2OWYzMTZiODFmOjE3NjA0ODFk
```

Notice how some of the filenames are quoted, because they end with "="

Decoding these, I can see that most of them start with 16 hex digits after the tenant ID:

```
# echo 'ZmFrZS83YTI1N2M5ZWI2YTYyMDkwOjE2OWYzMTZiODE2OjE2OWYzMTZiODYyOjdkNzMyNGQy' | base64 -d; echo
fake/7a257c9eb6a62090:169f316b816:169f316b862:7d7324d2
# echo 'print(len("7a257c9eb6a62090"))' | python3
16
```

But the quoted one has 15 hex digits at that point:

```
# echo 'ZmFrZS85N2RiMjQ0MDM5ZWFiOGY6MTY5ZjM3MDVjZjM6MTY5ZjM3MDVjZjM6OGNiNmIwMjY=' | base64 -d; echo
fake/97db244039eab8f:169f3705cf3:169f3705cf3:8cb6b026
# echo 'print(len("97db244039eab8f"))' | python3
15
```

I don't know what those hex digits are for, but they could be padded to a fixed 16 characters (%16x), e.g. `fake/097db2...`

**Environment:**
 - Ubuntu 18.04 lxd container on Ubuntu 18.04 host
 - Built from source with go 1.12.1

**Comment by candlerb** [comment]
I think I found it in [cortex](https://github.com/cortexproject/cortex/blob/master/pkg/chunk/chunk.go#L179):

```
return fmt.Sprintf("%s/%x:%x:%x:%x", c.UserID, uint64(c.Fingerprint), int64(c.From), int64(c.Through), c.Checksum)
```

Suggestion would be to change `%x` to `%016x` (at least the first one).  But this is very minor - it might just be a bit less surprising if the filenames were better aligned.

**Comment by Kuqd** [comment]
Hello @candlerb,

Could you open that issue on cortex side ?

Thank you

**Comment by candlerb** [comment]
Moved to https://github.com/cortexproject/cortex/issues/1352
