### ISSUE TITLE
Series API requests give inconsistent and/or missing results

### ISSUE THREAD

**Issue by slim-bean** [grafana/loki#4547]
**Describe the bug**

Using grafana `label_values()` which looks to call the Loki `series` API has caused some people to realize that results are missing and the behavior changes inconsistently, sometimes changing the timerange returns results, sometimes it doesn't.

**To Reproduce**

I don't have great info here but based on reports and my attempts to verify the issue I can confirm I saw the issue.

I was able to make logcli requests against old data from the reported timerange and confirmed that labels where not returned which should have been via the Series API

A little bit more playing I did seemed like any completely in the past time range struggled to return results, however the traces and execution time of the query often made it seem like the work was done to get the result yet logcli got an empty result set. 

When the timerange included now() as the `through` time, I was getting results.

It's often seen in a dashboard which uses a variable that reloads when the timerange changes, and then zoom in on a graph and see dropdown values change or disappear.

**Comment by jiayi-1994** [comment]
https://github.com/grafana/loki/issues/8034  @cyriltovena   Problem recurrence， Are there any good solutions?
