### ISSUE TITLE
logcli ignores --config logcli-config.yaml

### ISSUE THREAD

**Issue by candlerb** [grafana/loki#455]
**Describe the bug**
logcli ignores "addr" setting from logcli-config.yaml (in fact it doesn't appear to open the file specified by `--config` at all)

**To Reproduce**
1. Started loki (c9948233)
2. Started promtail (c9948233) to tail 'varlogs'
3. Build logcli
4. Copy `cmd/logcli/logcli-config.yaml` to `~/logcli-config.yaml`
5. Edit it so that it contains `addr: 127.0.0.1:3100`
6. `./logcli --config ~/logcli-config.yaml labels`

**Expected behavior**
Logcli would query local loki instance.  Instead, it tries (and fails) to connect to the cloud hosted one.

**Environment:**
 - Ubuntu 18.04 lxd container on Ubuntu 18.04 host
 - Built from source with go 1.12.1

**Screenshots, promtail config, or terminal output**

```
# cat ~/logcli-config.yaml
addr: http://127.0.0.1:3100

username:

password:
# ./logcli --config ~/logcli-config.yaml labels
https://logs-us-west1.grafana.net/api/prom/label
2019/04/07 07:51:37 Error doing request: Error response from server: "Unauthorized" (<nil>)
```

Using `strace` shows that the binary isn't even attempting to open the config file:

```
# strace -f -s128 ./logcli --config ~/logcli-config.yaml labels 2>/tmp/strace.out
https://logs-us-west1.grafana.net/api/prom/label
# grep logcli-config /tmp/strace.out
execve("./logcli", ["./logcli", "--config", "/root/logcli-config.yaml", "labels"], 0x7ffc79692da8 /* 21 vars */) = 0
# 
```

Workaround is to use `--addr` flag instead of `--config`

```
# ./logcli --addr http://127.0.0.1:3100 labels
http://127.0.0.1:3100/api/prom/label
__filename__
job
```

**Comment by daixiang0** [comment]
refer to #433

**Comment by candlerb** [comment]
Closing as this functionality is known to be broken and is being removed.
