### ISSUE TITLE
What is the expected behavior when pulling `grafana/loki:latest`

### ISSUE THREAD

**Issue by slim-bean** [grafana/loki#4557]
A bug introduced in a push to main recently resulted in a couple issues being reported

#4533
#4551

While the bug has since been fixed there are opinions shared by users on both tickets that the behavior for pulling `grafana/loki:latest` was not what they expected.

In both cases the feedback seemed to indicate that `latest` should point to a stable release and not the most recent build.

I tried to find any best practices through searching the internet but was unable to do so. 

My understanding of latest is that it's just the most recent push, not that it implies any level of stability but I'm seeing from feedback that other people expect differently.

Is there any prior art out there as to best practices here? Are there any other large projects which can be used as examples as to what we should do with image tagging?

Looking for researched opinions please with links or references to other information to help us chose a path here that makes sense for most users.

**Comment by Nemric** [comment]
All right, thanks for noticing the highly scientific case study ^^ 
Will these changes will be the same for grafana/promtail ? It seems they follow the same version number and I suppose it's for working well together isn't it ?
