### ISSUE TITLE
logcli sends debug output to stdout instead of stderr

### ISSUE THREAD

**Issue by candlerb** [grafana/loki#456]
**Describe the bug**
logcli mixes its debug output (e.g. the URL it's talking to) with the actual data you want

**To Reproduce**
1. `./logcli --addr http://127.0.0.1:3100 labels __filename__ 2>/dev/null`

**Expected behavior**
stdout should only have the data requested; debug or progress messages go to stderr.

**Environment:**
 - Ubuntu 18.04 lxd container on Ubuntu 18.04 host
 - Built from source using go 1.12.1

**Screenshots, promtail config, or terminal output**

```
# ./logcli --addr http://127.0.0.1:3100 labels __filename__ 2>/dev/null
http://127.0.0.1:3100/api/prom/label/__filename__/values
/var/log/auth.log
/var/log/syslog
```

It's not possible to separate the debug from the data, without hardcoding (for example) that logcli always sends the URL first.

**Comment by daixiang0** [comment]
it is an improvement indeed, i would take a look at this later,
