### ISSUE TITLE
Easy subscription or "tail" of loki logs

### ISSUE THREAD

**Issue by candlerb** [grafana/loki#457]
**Is your feature request related to a problem? Please describe.**

I would like to use loki as the repository of all raw logs, and feed them from loki into several other systems for analysis, metrics, alerting etc.

Generally I want to process logs in close to real time.  However since loki is a historical store I'd also like to be able to add or change systems and get them to reprocess logs from an earlier point in time.

**Describe the solution you'd like**

The ideal approach would be to subscribe to logs, specifying a start time and optional query filter, and getting the results back as a stream, i.e. "long polling".  If the connection breaks, then you reconnect and specify the start time as the last log event you've seen. [^1]

I think that [server sent events](https://en.wikipedia.org/wiki/Server-sent_events) (SSE) would be the modern way to do this.  SSE is just one continuous response with a MIME type of [text/event-stream](https://www.w3.org/TR/eventsource/).  Events could be structured in the same way as the query API response:

```
data: {"streams": [{"labels":...,"entries":[...]}]}

data: {"streams": [{"labels":...,"entries":[...]}]}
```

A clunkier approach would be to send separate records framed as a multipart/something, as used by [motion JPEG](https://stackoverflow.com/questions/47729941/mjpeg-over-http-specification?rq=1)

Either way opens the way for web-based front-ends that could display logs or a subset of logs in real time, as they arrive.

[^1]: It's possible you'll receive duplicate logs in this case.  Given the nanosecond resolution of timestamps, I'm not too worried, as long as the "ts" timestamps are when the message was received by loki and monotonically increasing - not the parsed timestamps from the messages themselves.

A message sequence number or offset would be better, and could also be used as the Event ID / Last-Event-ID in SSE, but I don't know if loki has such a thing internally.

**Describe alternatives you've considered**

A simple approach would be to poll the HTTP API, running an empty query with `start=<time-of-last-log-seen>&limit=1000`.  Unfortunately, you cannot provide an empty query today:

 ```
./logcli --addr http://127.0.0.1:3100 query '{}'
http://127.0.0.1:3100/api/prom/query?query=%7B%7D&limit=30&start=1554621157806093227&end=1554624757806093227&direction=BACKWARD&regexp=
2019/04/07 08:12:37 Query failed: Error response from server: syntax error
 (<nil>)
```

Loki could be modified to permit empty queries. These would be inefficient in normal use, and should generally be avoided, but they're probably OK when polling for messages received in the last few seconds, which would probably still be in RAM.

You can do a regexp query if there is a label which you know will exist on every log message:

    ```
    ./logcli --addr http://127.0.0.1:3100 query '{job=~".*"}'
    ```

But in any case, repeated polling is inefficient, and is more likely to end up with duplicated or missed messages than having a continuous stream.

**Comment by steven-sheehy** [comment]
There is a [PR](https://github.com/grafana/loki/pull/439) to expose tailing of logs as websocket

**Comment by candlerb** [comment]
Thank you, I will close this in favour of #439.
