### ISSUE TITLE
Kafka backend to Loki

### ISSUE THREAD

**Issue by candlerb** [grafana/loki#458]
**Is your feature request related to a problem? Please describe.**

This is more of an idea to float than a feature request, but it's an alternative to #457.

The use case: you want a canonical store of raw logs, which are streamed into other systems for additional processing (parsing, metrics, alerting).  But you also want it Loki-indexed so you can do quick and easy ad-hoc log searching via Grafana.

**Describe the solution you'd like**

My proposal is to use Kafka as the log storage backend, with Loki continuing to maintain the label index.

Instead of the chunk store:

* The message store is a Kafka topic with a configurable number of partitions - let's say 1000
* Each log message is written as a separate Kafka message
* Kafka message body is the raw log message
* Kafka message timestamp is the ts
* Kafka message key is the normalised [^1] label set [^2]

The way Kafka works is that a hash of the message key is used to assign the message to a partition.  Hence all messages with identical label set will go to the same partition.

Loki would continue to manage the label set database.

When you do a query like `{foo="123",bar="456"}` it would identify all matching label sets.  For each label set found, it would use the Kafka hashing algorithm to work out which partition it is in.  It would then query the identified partitions, for messages from the start time onwards, discarding messages which don't have a matching label set.

[^1]: it's important that equivalent label sets go into the same partition, so `{job="foo",file="bar"}` and `{file="bar",job="foo"}` would have to be normalised to a consistent form, e.g. sorted by label name.

[^2]: a naïve implementation writes the raw label set as the message key.  It could be quite large, and is repeated for every message.  However, since Kafka compresses the blocks it writes out, in practice this may be optimised out automatically.

A more advanced solution might maintain a mapping registry of each label set to (say) a 32-bit unique ID.  The 32-bit ID could be a hash of the label set, and incremented in the case of collisions.  Then each message would contain this 32-bit value as the message key, instead of the full tag set.

Some testing would need to be done to determine if this is a worthwhile optimisation; it also means that consumers who are interested in the actual tags would need to query the registry.

**Benefits of this solution**

* Kafka has reliability, replication, failover and scalability completely nailed down. It also has a clear concept of message offsets for restarting at a given point.
* Kafka message consumers can use the Kafka store directly without any knowledge of Loki
* Kafka allows message consumers to be scaled horizontally, where each consumer is assigned one or more message partitions. Messages with the same label set would go into the same partition, and therefore be processed in-sequence by the same consumer.
* Kafka handles message retention policy and expiry
* Kafka is a great architecture for message processing: messages can be read, analysed, written out to new topics with new labels/metadata, and potentially re-indexed in another Loki
* Kafka can be queried directly by other tools (e.g. Drill, Presto)
* If you already have Kafka in your infrastructure, this is a no-brainer add-on

**Downsides of this solution**

* Requires running at least a one-node Kafka+Zookeeper for the backend
* Once you have more unique label sets than the number of topic partitions, multiple label sets will be stored in the same partition.  Some queries will therefore read and discard data from some partitions.  In the worst case, if you give a query with a label set cardinality greater than number of partitions, it will end up reading all logs from all partitions for the specified time period.

    (Having said that: a Loki query with a high label set cardinality will have to read a large number of separate chunks, and that might be just as inefficient)
* Suppose you have one label set which is generating thousands of messages per second - access logs from a firewall, say.  One particular topic partition will become very large.  If you happen to do a query for some other label set which is in the same partition, then it will have a large amount of data to discard.

    The solution here, apart from having more topic partitions, is to pick one label and use it to select the topic, instead of putting all messages in one topic.  For example, using the "job" label to specify the topic would make a lot of sense.  Then `job="kubelogs"` would go into a different topic than `job="network"`.  This also allows those topics to be partitioned differently, and also shortens the remaining label set.

**Further optimisation**

So far I've considered that Loki keep the label index in its existing label store (e.g. boltdb).

However a Kafka topic would also make an excellent persistent store for the set of labels.  At startup, you'd just read all messages from this topic (into RAM or boltdb), and whenever you see a new unique label set, you'd write it out to the topic.

This is the mechanism used by projects such as KSQL to materialise tables in Kafka.  It would allow Loki itself to scale horizontally, keeping the label indexes in sync automatically.

**Describe alternatives you've considered**

See #457 for a pure Loki alternative without Kafka, where consumers can subscribe directly to Loki.

You could push all your raw logs into a single Kafka topic, and from there stream them into Loki with a simple consumer that writes to the Loki API.  But then you have two full copies of each raw log message - one in Kafka and one in Loki.

Since the Loki API is so simple, the feature idea described here could be built as a completely separate project, kept API-compatible so that Grafana and promtail could still talk to it.

**Comment by rrfeng** [comment]
In my opinion, kafka is not a good storage. I prefer use some tool transfer log from kafka to loki.
Like:

```
file -> filebeat -> kafka -> parser -> loki server
                                        -> parser -> other system

```

**Comment by candlerb** [comment]
> In my opinion, kafka is not a good storage

Could you explain why you don't think kafka is good for long-term storage?

**Comment by rrfeng** [comment]
> Could you explain why you don't think kafka is good for long-term storage?
Recovery is terrible with huge data, and balance or partition reassign. Sure kafka's design support long-term storage and actually someone use kafka as storage, but I won't.
For loki, object storage such as S3 is cheap and safe, and enough.

**Comment by candlerb** [comment]
I think there's a place for both.

Comparing with prometheus itself, they say it's not designed for long-term storage - it should "be treated as more of an ephemeral sliding window of recent data".  And they provide a remote storage facility for archival.

So I think there's a place for being able to query a raw log stream in Kafka, and also archiving into something like Loki.

**Comment by steven-sheehy** [comment]
I think this request belongs in the cortex library where the other storage backends live: https://github.com/cortexproject/cortex/tree/master/pkg/chunk
