### ISSUE TITLE
Docs feedback: /operations/storage/boltdb-shipper.md

### ISSUE THREAD

**Issue by b-0-b** [grafana/loki#4583]
Hello,

the last (3rd) paragraph in the `Index Gateway` section seems illogical to me.

```shell
Within Kubernetes, if you are not using an Index Gateway, we recommend running an Index Gateway as a StatefulSet with persistent storage for downloading and querying index files. This will obtain better read performance, and it will avoid using node disk.
```

I read it as you should be running the Index Gateway (that you are NOT using) as a StatefulSet. If you are NOT using something, it will not have a resource type...
Or is the intention to say that if you are not using an Index Gateway, you really should and it should be a StatefulSet?

**Comment by owen-d** [comment]
Thanks for reporting! Yeah, that's pretty confusing :scream:. I'll open a PR and try to sort it out, let me know what you think.

**Comment by b-0-b** [comment]
Thank you. Looks good to me :)
