### ISSUE TITLE
Test Zstd compression

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#4620]
From my understanding the ztsd decoder and encoder uses goroutines. This means when a decoder/encoder is pooled and will be garbage collected, but when release we don't call close and so we don't stop goroutines

We tried to add this finalizer https://github.com/grafana/loki/blob/main/pkg/chunkenc/pool.go#L235 from https://github.com/grafana/loki/pull/3306 but we didn't for the encoder.

But I'm wondering if we should may be find another solution, possible this can cause go-routines leak even with a finalizer

- Investigate if the writer also need the same treatment example https://github.com/segmentio/kafka-go/blob/ea83b2934c4ff79c5e4795b0806062cab913b3ae/compress/zstd/zstd.go#L113
- Attempt to write better test or benchmark showing possible leak
- Test in a dev environment Ztsd and ensure goroutines count are looking normal.

Alternatively if there's still issues:
- Investigate if we can't refactor pooling to guarantee call to `Close` once release/GC. (May be use LRU / custom free list ?)
- Benchmark change if we do refactoring.

**Comment by kavirajk** [comment]
Adding few references that may be helpful!
1. https://github.com/grafana/loki/pull/3064
1. https://grafana.slack.com/archives/CEPJRLQNL/p1635827026297100
