### ISSUE TITLE
ServiceDiscovery page for Promtail

### ISSUE THREAD

**Issue by metalmatze** [grafana/loki#463]
**Is your feature request related to a problem? Please describe.**
Prometheus has a Service Discovery page that displays the state of discovery things being relabelled and dropped. You can look at the page by visiting `/service-discovery` on your Prometheus.

**Describe the solution you'd like**
For PromTail's discovery it would be helpful to have a similar page in the internal http server of PromTail so that, when configuring or debugging PromTail's config, one can more easily see what PromTail discovers.

**Describe alternatives you've considered**
We could also just log more information to the logs, but that might get cluttered very quickly.

**Additional context**
- 

/cc @gouthamve

**Comment by davkal** [comment]
Related to #38
