### ISSUE TITLE
Issue in installation on Raspberry Pi 3+

### ISSUE THREAD

**Issue by speed4andy** [grafana/loki#4633]
Hello I wanted to install Loki for RB PI 3+ but unfortunetly in step:

./loki-linux-amd -config.file=loki-local-config.yaml

I get this error:
root@octopi:/home/pi/loki# ./loki-linux-arm -config.file=loki-local-config.yaml
failed parsing config: loki-local-config.yaml: yaml: unmarshal errors:
  line 48: field unordered_writes not found in type validation.plain

Can you please help me wih that issue??

THX 
Ondra

**Comment by owen-d** [comment]
Hey, that configuration is in the `main` branch, but isn't yet supported in a release, which is why you're seeing the issue. Don't worry though, we're going to cut a release within a week which will have that feature enabled by default :)

**Comment by sungup** [comment]
I know that the **unordered_writes** is a new option from 2.4.0 version. How about changing to 2.4.0 or comment out that option?
