### ISSUE TITLE
When will the new version（loki 2.4） be released 

### ISSUE THREAD

**Issue by vinson-zhang** [grafana/loki#4640]
I look forward to the out-of-order solution.When will the new version（loki 2.4） be released >

**Comment by atlee19** [comment]
From the Loki Community Call Google doc it says the targeted Release date for Loki 2.4 is for Observability Con which is next week Nov. 10, 2021.

**Comment by 09jvilla** [comment]
Closing since this is now released. 
https://grafana.com/docs/loki/latest/release-notes/v2-4/
