### ISSUE TITLE
Provide Metric query to calculate time difference between logs

### ISSUE THREAD

**Issue by scumpah** [grafana/loki#4659]
It might be a good idea to provide metric query to calculate timestamp difference between logs. Like for example {"message":"start request","timestamp":"timeA"} and {"message":"finish request","timestamp":"timeB"}

How do I get time difference between log1 and log2. More real use case, I want to know how long it took between the start log and end log of a request and total time taken by all the requests in the last 24 hours.

**Comment by jeschkies** [comment]
I wonder if you could transform the timestamps into unix timestamps and then subtract one vector from the other (https://grafana.com/docs/loki/latest/logql/#binary-operators).

**Comment by MarjanJordanovski** [comment]
> It might be a good idea to provide metric query to calculate timestamp difference between logs. Like for example {"message":"start request","timestamp":"timeA"} and {"message":"finish request","timestamp":"timeB"}
> 
> How do I get time difference between log1 and log2. More real use case, I want to know how long it took between the start log and end log of a request and total time taken by all the requests in the last 24 hours.

I was wondering the same thing. It can be done using Flink and a custom loki connector, but i would like to know if it is possible only using loki queries
