### ISSUE TITLE
ip cannot be used as a label in 2.3

### ISSUE THREAD

**Issue by xkilian** [grafana/loki#4665]
**Describe the bug**
Define an ip label in promtail for a stream and assign it to it the value of the source ip for managed devices.  (low cardinality, as the number of devices managed is very low and known in advance)
LogQL will throw an error, when querying in Grafana Explore: parse error at line 1, col 21: syntax error: unexpected ip, expecting IDENTIFIER 

**To Reproduce**
1. Started Loki 2.3
2. Started Promtail 2.3 and receive logs from rsyslogd
3. In Explore or Grafana Panel
3. Query: {app="RESEAU-RADIO",job="snmptrap"} (works)
4. Query {app="RESEAU-RADIO",ip="10.10.10.1",job="snmptrap"} (fails)
5. In Grafana Explore, the ip label is shown and suggested. When the query is sent to Loki to get the result, it throws the error.

**Expected behavior**
This worked in 2.2, must be related to the new filtering function named ip

**Environment:**
 - Infrastructure: Ubuntu 18.04LTS, loki monolith

Output:
parse error at line 1, col 21: syntax error: unexpected ip, expecting IDENTIFIER

**Comment by xkilian** [comment]
I have implemented this work-around, while waiting for an official answer:
 {app="RESEAU-RADIO",job="snmptrap"} |= ip("10.10.10.1")

**Comment by kavirajk** [comment]
Hi @xkilian this https://github.com/grafana/loki/pull/4598 fixes the ip label issue. And it will be available in 2.4!
