### ISSUE TITLE
TimeFormatting Promtail to Loki

### ISSUE THREAD

**Issue by sg-asterix** [grafana/loki#4685]
Hi, 

I am unable to get the custom timeformat to be working while sending the logs to LOKI.

The log line is shown below
_[06/Nov/2021:16:15:19 +0800] 10.10.10.3 - - "GET /sap/public/bc/icf/logoff HTTP/1.1" 200 9625 3_

The promtail config is also shown below

_server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: ./positions.yaml
client:
  url: 'http://<ip_address>:3100/loki/api/v1/push'
scrape_configs:
- job_name: DW1logs
  static_configs:
  - targets:
      - localhost
    labels:
      job: DW1logs
      host: d0awvwhtp01
      __path__: 'D:\usr\sap\DW1\W00\work\HTTP_ACCESS_LOG*'
  pipeline_stages:
  - match:
      selector: '{job="DW1logs"}'
      stages:
      - regex:
          expression: '\[(?P<req_date>.*?) (?P<timezone>.*?)\] (?P<ip>.*?) - - \"(?P<request_method>.*?) (?P<path>.*?)(?P<request_version> HTTP\/.*)?\" (?P<status>.*?) (?P<response_length>.*?) (?P<response_time>.*)'
      - labels: 
          req_date:
  - timestamp:
            source: req_date
            format: "02/Nov/2006:15:04:05"_

The output in Grafana explorer is shown below

![image](https://user-images.githubusercontent.com/91124526/140644308-fce870e8-7637-40b7-8fe5-ba2441515588.png)

Regards,

Hari

**Comment by NicoForce** [comment]
I'm experiencing this problem as well with Loki and Promtail 2.4.1.

**Comment by sushantkumar-amagi** [comment]
I am getting a similar problem with the following format `"2006-01-02 15:05:04.000"` with promtail version 2.4.1

**Comment by jeschkies** [comment]
@sg-asterix according to the [documentation](https://pkg.go.dev/time#pkg-constants) it should be `02/Jan/2006:15:04:05`
