### ISSUE TITLE
Version not included in promtail user-agent

### ISSUE THREAD

**Issue by klausenbusk** [grafana/loki#4686]
**Describe the bug**
The promtail user-agent doesn't include the version.

**To Reproduce**
1. Start the promtail Docker image (`docker.io/grafana/promtail:2.4.0`) with a client config pointing to some server
2. Wait for promtail to push logs

**Expected behavior**
The user-agent should be `promtail/2.4.0`

**Environment:**
 - Infrastructure: bare-metal
 - Deployment tool: Docker

**Screenshots, Promtail config, or terminal output**
Nginx log:
```
x.x.x.x monitoring.domain.tld - [07/Nov/2021:16:25:44 +0000] "POST /loki/api/v1/push HTTP/1.1" 302 0 "-" "promtail/" "-" 0.002
```
Version:
```sh
root@eeb8923229d1:/# promtail --version
promtail, version 2.4.0 (branch: HEAD, revision: 3987933cd)
  build user:       root@fc19e7dd4bc0
  build date:       2021-11-05T20:46:40Z
  go version:       go1.17.2
  platform:         linux/amd64
```

**Comment by cyriltovena** [comment]
Yeah it seems that the code for the agent will be run before the version initialization here.

https://github.com/grafana/loki/blob/main/pkg/util/build/build.go#L23
