### ISSUE TITLE
Null pointer exception while run compactor

### ISSUE THREAD

**Issue by sungup** [grafana/loki#4695]
**Describe the bug**
I have upgrade loki from 2.3.0 to 2.4.0. After upgrade loki, loki has failed every 10m. It seems to be occured while calling compactor.

**To Reproduce**
1. Started Loki on normally
2. after 10 min (default compaction_interval value), Loki wil stopped with null pointer error on “/src/loki/pkg/validation/limits.go:254”

**Expected behavior**
I reviewd the changes on  `pkg/validation/limit.go#L254` and it’s caller `pkg/storage/stores/shipper/compactor/retention/expiration.go#L126`. 
I think that the previous code was call-back function based logic, so if the Overrides::tenantLimits is empty or nil, just ignore the loop traversal as an empty map.
But, new version (2.4.0) code changed to simple map iteration logic  using returned map by *AllByUserId* function. *AllByUserID* in `limit.go` will return nil not empty map if Overrides::tenantLimits is nil. And *findSmallestRetentionPeriod* function in `expiration.go` accesses that nil pointer as a map without nil return handling.

So, I think an nil pointer handling on the findSmallestRetentionPeriod function should be added.

**Environment:**
 - Infrastructure: baremetal (CentOS 7.8)
 - Deployment tool: downloaded from GitHub project (re-packaging that binary into rpm to internal distribution)
 - Loki Version: 2.4.0
  
**Screenshots, Promtail config, or terminal output**

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1e796aa]
goroutine 11139 [running]:
github.com/grafana/loki/pkg/validation.(*Overrides).AllByUserID(0xc000353b60, 0xc00000b2c0)
/src/loki/pkg/validation/limits.go:254 +0x2a
github.com/grafana/loki/pkg/storage/stores/shipper/compactor/retention.findSmallestRetentionPeriod(0x2b539a8, 0xc000353b60, 0xc00a8e8510)
/src/loki/pkg/storage/stores/shipper/compactor/retention/expiration.go:126 +0xc9
github.com/grafana/loki/pkg/storage/stores/shipper/compactor/retention.(*expirationChecker).MarkPhaseStarted(0xc000216a70)
/src/loki/pkg/storage/stores/shipper/compactor/retention/expiration.go:60 +0x4f
github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*expirationChecker).MarkPhaseStarted(0xc0001efb00)
/src/loki/pkg/storage/stores/shipper/compactor/compactor.go:516 +0x33
github.com/grafana/loki/pkg/storage/stores/shippper/compactor.(*Compactor).RunCompaction(0xc00026b500, 0x2b52cc0, 0xc009de3b00, 0x0, 0x0)
/src/loki/pkg/storage/stores/shipper/compactor/compactor.go:409 +0x465
github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*Compactor).runCompactions.func1()
/src/loki/pkg/storage/stores/shipper/compactor/compactor:342 +0x45
github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*Compactor).runCompactions.func2()(0xc00026b500, 0xc00a8374c0, 00x2b52cc0, 0xc009de3b00)
/src/loki/pkg/storage/stores/shipper/compactor/compactor.go:350 +0x82
created by github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*Compactor).runCompactions
/src/loki/pkg/storage/stores/shipper/compactor/compactor.go:348 +0x484
loki.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Unit loki.service entered failed state.
loki.service failed.
loki.service holdoff time over scheduling restart.
```

ps. I cannot copy the full logs from system because of the private network, I re-typping the error logs on other system. Log information has typping error for that reason.

**Comment by yangvipguang** [comment]
I have the same issues  
![图片](https://user-images.githubusercontent.com/11416887/140720897-2cf6b0be-ac30-4949-893d-1c0646eb773a.png)

**Comment by yangvipguang** [comment]
I have  upgraded to  2.4.1 version. Everything workers well.
