### ISSUE TITLE
Promtail out of memory

### ISSUE THREAD

**Issue by kab-2** [grafana/loki#471]
Hallo,

I have installed GRAFANA, LOKI and PROMTAIL in docker, when start these 3 dockers then after a few seconds PROMTAIL stops i dont know why can anyone explain this?

**Comment by daixiang0** [comment]
no any logs?

**Comment by hekmat1** [comment]
it shows logs but when I: "docker contianer ls" it shows only grafana and loki that are running but no promtail...is it normal ?

**Comment by daixiang0** [comment]
do you use docker-compose to deploy?

**Comment by hekmat1** [comment]
yeah

**Comment by tomwilkie** [comment]
Try docker ps -a; that should show a stopped promtail container.  Then try
docker logs <container name> and send us those logs.

Thanks

Tom

**Comment by hekmat1** [comment]
docker ps -a
![image](https://user-images.githubusercontent.com/36574695/55947538-ee7ec280-5c4e-11e9-82be-7b5c02291179.png)
logs von promtail
![image (1)](https://user-images.githubusercontent.com/36574695/55947589-0bb39100-5c4f-11e9-914b-be688087ac08.png)

**Comment by tomwilkie** [comment]
Looks like it was an OOM:
https://success.docker.com/article/what-causes-a-container-to-exit-with-code-137

What does journalctl -k | grep -i -e memory -e oom and docker inspect
<container ID> say?

Thanks

Tom

**Comment by hekmat1** [comment]
now I have another issue (kswapd0) when I start dockers my machine get extreme slow and it consume the all ram (kswapd0)...I cant do journalctl...

thx 
regards

**Comment by hekmat1** [comment]
journalctl -k | grep -i -e memory -e oom <container id>
a part of this output:
![image](https://user-images.githubusercontent.com/36574695/55951128-cd21d480-5c56-11e9-8855-178b948bb17e.png)

**Comment by hekmat1** [comment]
@tomwilkie I have solved the kswapd0 issue but promtail not:
journalctl -k | grep -i -e memory -e oom
![promtail_problem](https://user-images.githubusercontent.com/36574695/55956281-e3825d00-5c63-11e9-9fe8-8a0515839afc.png)

**Comment by daixiang0** [comment]
seems that your machine has a little available memory, stop some process and try again.

**Comment by hekmat1** [comment]
You mean if I extend my memory it will be solved?

**Comment by daixiang0** [comment]
from the log, it is killed by system OOM, increase free memory could be useful i think,

**Comment by hekmat1** [comment]
@daixiang0 i increased my memory even to 3 Gigabyte but it is also not enough for Promtail container its something creepy

**Comment by daixiang0** [comment]
Since you run with docker, if system allocate docker some memory, all memory docker can use is limited. I think you are in this case.
Do you customize docker service config or anything related?

**Comment by kab-2** [comment]
I am using docker-compose and i didnt edit docker service but i have limited memory in docker-compose.yaml file

**Comment by Kuqd** [comment]
Hello @kab-2 ,

How long does it take for promtail to die ?
Can you provide more information about your computer specs and how memory the docker machine if any is allocated with ?

Can you try to change the config to point to an empty dir ? however the config is currently baked in the image if you want to mount a local one you could edit the docker compose as such:

```yaml
...
  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
      - ../cmd/promtail/promtail-docker-config.yaml:/etc/promtail/docker-config.yaml
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - loki
...
```

Thank you !

**Comment by Kuqd** [comment]
@kab-2 Feel free to reopen if you still have an issue.
