### ISSUE TITLE
grafana 8.x can't build, errors like this! please add tag!

### ISSUE THREAD

**Issue by cheneylew** [grafana/loki#4714]
go: github.com/grafana/loki@v1.6.2-0.20210520072447-15d417efe103 requires
        github.com/influxdata/telegraf@v1.16.3 requires
        golang.zx2c4.com/wireguard/wgctrl@v0.0.0-20200205215550-e35592f146e4 requires
        golang.zx2c4.com/wireguard@v0.0.20200121: reading golang.zx2c4.com/wireguard/go.mod at revision v0.0.20200121: unknown revision v0.0.20200121

**Comment by pkalliok-aiven** [comment]
I encountered the same problem with my build.  Running `make clean all`:

```
[...]
generate go files
/home/pkalliok/go/bin/wire-v0.5.0 gen -tags "oss" ./pkg/server
wire: go [list -e -json -compiled=true -test=false -export=false -deps=true -find=false -tags=wireinject oss -- ./pkg/server]: exit status 1: go: github.com/grafana/loki@v1.6.2-0.20210520072447-15d417efe103 requires
		github.com/influxdata/telegraf@v1.16.3 requires
		golang.zx2c4.com/wireguard/wgctrl@v0.0.0-20200205215550-e35592f146e4 requires
		golang.zx2c4.com/wireguard@v0.0.20200121: reading golang.zx2c4.com/wireguard/go.mod at revision v0.0.20200121: unknown revision v0.0.20200121
	
wire: generate failed
make: *** [Makefile:35: gen-go] Virhe 1
```

**Comment by pkalliok-aiven** [comment]
Maybe something wrong with our go environments?

**Comment by andreasgerstmayr** [comment]
in case you're still interested in this ticket, https://groups.google.com/g/golang-nuts/c/MVtHZUtZru4 describes the problem and shows possible solutions
