### ISSUE TITLE
Quorum arithmetic does not behave as documented

### ISSUE THREAD

**Issue by naveedyahyazadeh** [grafana/loki#4717]
**Describe the bug**
The documentation for a quorum describes it as `floor(replication_factor / 2) + 1`, but fails to mention that, in code, if the number of ingester/node replicas is greater than the replication_factor, then the equation instead becomes `floor(num_replicas / 2) + 1`. As a result, the end user will experience unexpected behavior for some combinations of `num_replicas` and `replication_factor` if they are solely using the documented calculation.

This behavior can be found in code here: https://github.com/grafana/dskit/blob/1b5b43df7d437714aab852c801fed530cb04b88e/ring/replication_strategy.go#L32

**To Reproduce**
1. Started Loki (2.3.0 in my case, but others as well)
2. Set number of ingester pods greater than the `replication_factor`
3. Once everything is running, delete enough replicas such that `floor(replication_factor/2)+1 < live replicas < floor(desired replicas/2)+1` 
4. Resulting error:
```
Response: \"at least <floor(desired replicas/2)+1> live replicas required, could only find <N>\\n\"
```

I ran the following combinations to test:
```
requested ingester replicas 3, replication factor 1 -> needs 2 live ingester replicas (not consistent with docs)
requested ingester replicas 5, replication factor 1 -> needs 2 live ingester replicas (not consistent with docs)
requested ingester replicas 3, replication factor 3 -> needs 2 live ingester replicas (consistent with docs)
requested ingester replicas 5, replication factor 3 -> needs 3 live ingester replicas (not consistent with docs)
```

**Expected behavior**
The docs should be updated to include the case where there are more ingesters than the replication_factor: `floor(max(num_ingesters,replication_factor)/2)+1`

**Environment:**
 - Infrastructure: [Kubernetes]
 - Deployment tool: [Argo+Helm]

**Screenshots, Promtail config, or terminal output**

/ring
![image](https://user-images.githubusercontent.com/54322109/140981695-b816ddd4-6786-4bcf-a9d9-46b8444ef0df.png)

/config
![image](https://user-images.githubusercontent.com/54322109/140982374-085837d2-23be-4f98-a810-93bf3486a898.png)

Deleting 1 pod yields the following error:
```
level=warn ts=2021-11-09T18:20:01.445131798Z caller=logging.go:71 traceID=<traceid> msg="POST /loki/api/v1/push (500) 6.789544ms Response: \"at least 2 live replicas required, could only find 1\\n\" ws: false; Accept-Encoding: identity; Connection: close; Content-Length: 399182; Content-Type: application/json; User-Agent: Vector/0.16.0; "
```

**Comment by marcusteixeira** [comment]
not stale.
