### ISSUE TITLE
Promtail using lots of inotify instances

### ISSUE THREAD

**Issue by sh0rez** [grafana/loki#4740]
#### Description

On a system with 1189 containers (yes, really), promtail fails to register new watchers:

```
level=error ts=2021-10-28T11:35:44.792212392Z caller=filetargetmanager.go:263 msg="Failed to create target" key="{container_id=\"c517dad0337ef4991ed311d1c0efd2ab008102af1b730b8da31b4f3ffa3fe050\", container_name=\"elegant_meninsky\", container_status=\"exited\", instance=\"play64\"}" error="filetarget.fsnotify.NewWatcher: too many open files"
```

Looking at ulimits first, those don't seem to be the issue:

```py
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1.048576e+06
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 566
```

However, promtail holds 111 inotify file-descriptors, which is quite close to the **user-wide** limit of 128:

```sh
# inside container, pid 1 is promtail
$ lsof -p 1 | grep inotify | wc -l
111

$ sysctl fs.inotify
fs.inotify.max_queued_events = 16384
fs.inotify.max_user_instances = 128
fs.inotify.max_user_watches = 8192
```

#### (Likely) cause

Promtail allocates a new `fsnotify.Watcher` for each target:

https://github.com/grafana/loki/blob/0116aa61c86fa983ddcbbd5e30a2141d2e89081a/clients/pkg/promtail/targets/file/filetarget.go#L80-L83

#### Solution

Raising `fs.inotify.max_user_instances` higher than the container count should allow promtail to operate fine (probably).

However, based on [this SE reply](https://unix.stackexchange.com/a/532844), it seems promtail should not allcoate an inotify handler for each target it watches, but use one for all.

This would only limit promtail to the 8192 inotify watches any user is permitted (which can also raised if anyone really has more containers than that). All in all promtail would run well in default setups more likely.

**To Reproduce**
1. Start a ridiculous amount of containers (they don't need to run, just log something once)
2. Run promtail (`grafana/promtail` on Docker, Image ID `8be4e7d21c56`)

Maybe related: https://github.com/grafana/loki/issues/1153

**Comment by dannykopping** [comment]
Thanks for the great detective work @sh0rez! This definitely seems like a plausible cause and a reasonable solution.
