### ISSUE TITLE
kubernetes labels not found

### ISSUE THREAD

**Issue by liji2003888** [grafana/loki#4746]
deploy Fluent-bit in kubernetes
There a lot of errors in console while send messge to loki：

![image](https://user-images.githubusercontent.com/4416960/141500774-e11663b0-6701-40ed-9711-27bd470c67b9.png)

**Comment by liampulles** [comment]
@liji2003888 Did you dins a solution by any chance? I'm getting the same thing

**Comment by umeat** [comment]
We are seeing this issue as well. Any ideas?

**Comment by liampulles** [comment]
@umeat I still have no idea what the problem was, but restarting the loki deployment stopped the issue at least.
