### ISSUE TITLE
#loki promtail at OpenWrt instance though opkg  package manager 

### ISSUE THREAD

**Issue by naren4b** [grafana/loki#4749]
#loki Is there any support for installing promtail at OpenWrt instance though opkg  package manager (i.e : like prometheus exporter Opkg package manager  extension to the article written by Matthew Helmke : How I monitor my OpenWrt router with Grafana Cloud and Prometheus )

**Comment by jeschkies** [comment]
@naren4b I'm not aware of one. Did you try to compile Promtail for OpenWrt? Could you link the article?

**Comment by jeschkies** [comment]
@matthewhelmke would you have a link to your post on OpenWrt?

**Comment by jlbribeiro** [comment]
@jeschkies (for future reference) The article was written in @grafana's blog:
https://grafana.com/blog/2021/02/09/how-i-monitor-my-openwrt-router-with-grafana-cloud-and-prometheus/

It makes use of the [prometheus-node-exporter-lua-*](https://openwrt.org/packages/pkgdata/prometheus-node-exporter-lua) packages.

Found this issue in search of a `promtail`(-like) package in OpenWRT.
