### ISSUE TITLE
Create a tool to recreate indexes from chunks

### ISSUE THREAD

**Issue by renrutmas** [grafana/loki#4755]
**Is your feature request related to a problem? Please describe.**
I managed to blow away my indexes by typoing the date in my schemas.  Now I've got a month of logs I can't access.

**Describe the solution you'd like**
./loki --recreate-indexes </path/to/chunk>

**Describe alternatives you've considered**
Give up on this period of logs.  Holds some really useful data though.

**Additional context**
schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
    - from: 2021-11-13    <== I put 2020 here
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: aws_index_    <== I had index_ here instead of aws_index_
        period: 24h

**Comment by sandeepsukhani** [comment]
It should not be too hard to build a tool for rebuilding index.
Dropping some pointers here if someone wants to contribute:
1. Building the schema using [CreateSchema](https://github.com/grafana/loki/blob/bfc77118a161f9cb7afe95c7fa89fffd523bbabe/pkg/storage/chunk/schema_config.go#L164):
  schema = cfg.CreateSchema().(chunk.SeriesStoreSchema)
2. Instantiate the index store using [NewIndexClient](https://github.com/grafana/loki/blob/77ea11724b438c15acd3890626430729832817f2/pkg/storage/chunk/storage/factory.go#L230):
  indexClient = NewIndexClient
3. decodeContext = [NewDecodeContext](https://github.com/grafana/loki/blob/ac6ace8dbdd77ee799ec637265fe24e2f79462fd/pkg/storage/chunk/chunk.go#L291)
4. Locate chunks from which the index needs to be rebuilt.
5. For each chunk do:
   * [c = ParseExternalKey](https://github.com/grafana/loki/blob/ac6ace8dbdd77ee799ec637265fe24e2f79462fd/pkg/storage/chunk/chunk.go#L92)
   * chunkBytes = \<chunk-bytes-downloaded-from-storage\>
   * [c.Decode(decodeContext, chunkBytes)](https://github.com/grafana/loki/blob/ac6ace8dbdd77ee799ec637265fe24e2f79462fd/pkg/storage/chunk/chunk.go#L299)
   * indexEntries = schema.GetCacheKeysAndLabelWriteEntries() + schema.GetChunkWriteEntries()
   * writeBatch = indexClient.NewWriteBatch()
   * insert all entries to writeBatch with `writeBatch.Add`
   * indexClient.BatchWrite(ctx, writeBatch)

**Comment by tharun208** [comment]
@sandeepsukhani I like to work on this issue.

**Comment by tharun208** [comment]
Wanted to clarify a doubt before implementing. Since `Loki` always runs as a daemon process. Can we add this new command to `logcli`?.

**Comment by lovelinuxalot** [comment]
Is this implemented somewhere? does anyone have the code built and ready somewhere?

**Comment by renrutmas** [comment]
> Wanted to clarify a doubt before implementing. Since `Loki` always runs as a daemon process. Can we add this new command to `logcli`?.

I think this is a good idea.

**Comment by samox73** [comment]
It would be a fantastic tool as a remedy when loki or the index schema config are updated and suddenly all old indices are gone.

**Comment by anfallow** [comment]
Have loki configured to work with boltdb-shipper and azure blob on 3 environments running on AKS clusters. Two of those currently have an issue that queriers download the files from blob yet cannot read those - the error is "invalid database", pointing to corrupted indexing (one of the environments is production :/ ). 

Tried searching for additional info about fixing the indexing, or at least being able to denote whether this is in fact the indexing problem, but the info is really scarce (basically a quick algorithm on someone else's issue). 

So some sort of tool to help us out with this would be really helpful (at least at this moment I am kind of shitting bricks as I am not sure whether I will be able to query the old logs that somehow got corrupted).

**Comment by bds-congnguyen** [comment]
Hi,
Is there any news on this features, I just lose >10TB log due to cannot rebuild index files

**Comment by hvisage** [comment]
How much does the migration tool share these "reindexer" stuff?

I also have chunks that seemed out of date with indice and wuold like to have it re-indexed or similar to "fsck" or "scrub" to make sure of the data etc.
