### ISSUE TITLE
Per-Tenant Index

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#4759]
Plan:
-  Use object store to figure if it's per-tenant index or not.
- Activate write with a config flag.

**Comment by sandeepsukhani** [comment]
@slim-bean @cyriltovena Here is the doc I wrote to discuss on the trigger for enabling per user index https://docs.google.com/document/d/1zRhcGsTKLNbOzgi1EVSL1tLG_fBdp7E0UsJmmIAh8HI/edit#
