### ISSUE TITLE
Loki startup logging when no rule files found and ruler docs

### ISSUE THREAD

**Issue by xkilian** [grafana/loki#4766]
**Is your feature request related to a problem? Please describe.**
Loki startup logs do not make it clear when NO rule files are loaded.

**Describe the solution you'd like**

If no rule files are found, put an entry in the the info logs of the loki startup to make it clear that no rule files where loaded.

Potentially identify if someone forgets to put a sub-directory for the rules.

**Describe alternatives you've considered**
Improve Grafana Documentation for ruler rule-path and storage directory to make it clear WHERE rule files should be and that a sub-directory is required. I believe the documentation and logging should be improved.

**Additional context**
Adding this will provide feedback to the user that Loki i not loading rules if theses are expected. Will help troubleshoot user errors.

**Comment by dannykopping** [comment]
While I don't disagree that this would be useful, it's a pretty slippery slope isn't it? We'd have to add info messages for all features that may be activated but aren't.

**Comment by xkilian** [comment]
Yes, I agree, that a Project Management decision needs to be done for Loki to choose which are the most common and/or problematic configurations that would warrant the addition of this as INFO in the logs. 
If it doesn't make the cut, consider at least putting it in the DEBUG level messages so that a user that is actively tracking why something is not working has a chance to figure it out.
The doc improvement IMO should be done and would avoid common problems.
Thanks for taking the time to provide meaningful feedback it is appreciated.

**Comment by xkilian** [comment]
As you stated, the same reflection should be considered for other common and/or problematic configurations that would warrant the addition of this. Loki has A LOT of configuration options, some of which would benefit from new DEBUG or INFO logs to help in making sure things are working as expected. (Low volume, just as a startup validation aid)
Let me also state that I love Loki and appreciate all the work put in to it. :-)
