### ISSUE TITLE
Content-Type is text/plain instead of application/json

### ISSUE THREAD

**Issue by Maillol** [grafana/loki#4768]
**Describe the bug**
The route api/v1/query_range returns a json body but the content-type header is set to test/plain

**To Reproduce**
1. Started Loki (SHA or version)

docker run --rm --name loki -p 3100:3100 -d grafana/loki:2.2.1

2. Made a post request 

curl -v -X POST -H "Content-Type: application/json" 'http://127.0.0.1:3100/loki/api/v1/push' --data '{"streams": [{"stream": {"severity": "info", "service": "foo"}, "values": [["1637077241564862464", "Hello World"]]}]}'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:3100...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 3100 (#0)
> POST /loki/api/v1/push HTTP/1.1
> Host: 127.0.0.1:3100
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 117
> 
* upload completely sent off: 117 out of 117 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 204 No Content
< Date: Tue, 16 Nov 2021 15:44:32 GMT
< 
* Connection #0 to host 127.0.0.1 left intact

3. Made a get request 

curl -v -G -H "Accept: application/json" 'http://127.0.0.1:3100/loki/api/v1/query_range' --data-urlencode 'query={service="foo"}'
*   Trying 127.0.0.1:3100...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 3100 (#0)
> GET /loki/api/v1/query_range?query=%7Bservice%3D%22foo%22%7D HTTP/1.1
> Host: 127.0.0.1:3100
> User-Agent: curl/7.68.0
> Accept: application/json
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: text/plain; charset=utf-8
< Date: Tue, 16 Nov 2021 15:55:08 GMT
< Content-Length: 727
< 
{"status":"success","data":{"resultType":"streams","result":[{"stream":{"service":"foo","severity":"info"},"values":[["1637077241564862464","Hello World"]]}],"stats":{"summary":{"bytesProcessedPerSecond":9173,"linesProcessedPerSecond":833,"totalBytesProcessed":11,"totalLinesProcessed":1,"execTime":0.001199133},"store":{"totalChunksRef":0,"totalChunksDownloaded":0,"chunksDownloadTime":0,"headChunkBytes":0,"headChunkLines":0,"decompressedBytes":0,"decompressedLines":0,"compressedBytes":0,"totalDuplicates":0},"ingester":{"totalReached":1,"totalChunksMatched":1,"totalBatches":1,"totalLinesSent":1,"headChunkBytes":11,"headChunkLines":1,"decompressedBytes":0,"decompressedLines":0,"compressedBytes":0,"totalDuplicates":0}}}}
* Connection #0 to host 127.0.0.1 left intact

**Expected behavior**
The Content-Type of response is "text/plain; charset=utf-8" instead of Application/json

**Environment:**
 - docker

**Comment by kavirajk** [comment]
Duplicate! of https://github.com/grafana/loki/issues/4791 already fixed in https://github.com/grafana/loki/pull/4828. Closing it!.

Feel free to re-open if you think otherwise!
