### ISSUE TITLE
fluent-bit Loki output plugin overrides fluent-bit escaped JSON parsing

### ISSUE THREAD

**Issue by nottug** [grafana/loki#4771]
**Describe the bug**
When using JSON logs with Docker, the JSON will be come escaped and stored in a JSON object like `{"json": "ESCAPED_JSON_STRING"}`. Native fluent-bit seems to handle this (and even has support with [decoders](https://docs.fluentbit.io/manual/pipeline/parsers/decoders) for this exact issue), though when using the loki fluent-bit output plugin, the JSON remains as an escaped string (even when using decoders). 

There seems to be solutions with promtail and Kubernetes for this issue, though I haven't been able to find a solution when using [ECS with firelens](https://grafana.com/docs/loki/latest/clients/aws/ecs/). I ended up forking Loki and creating a new config option `ParseJsonKeys` which works well. I'm happy to open a PR here if that's an acceptable solution, [this](https://github.com/sencha-dev/loki/commit/3972f4b1e3c9dace8079f0a7339fd5277e877e3a) is the relevant commit.

**To Reproduce**
1. Install fluent-bit v1.8.9
2. Checkout loki at tag v2.4.1
3. Run `make fluent-bit-plugin` in the loki repo
4. Create two fluent-bit config files
```
# fluent-bit-native.conf

[INPUT]
    name dummy
    dummy {"log":"{\"level\":\"error\"}","stream":"stdout"}
    samples 1

[Output]
    Name stdout
    Match *
```
```
# fluent-bit-loki.conf

[INPUT]
    name dummy
    dummy {"log":"{\"level\":\"error\"}","stream":"stdout"}
    samples 1

[Output]
    Name grafana-loki
    Match *
    Url ${LOKI_URL}
    LineFormat json
    LogLevel debug
```
5. Run `fluent-bit -e /PATH/TO/LOKI/clients/cmd/fluent-bit/out_grafana_loki.so -c fluent-bit-native.conf`
```
[0] dummy.0: [1637114099.496755000, {"log"=>"{"level":"error"}", "stream"=>"stdout"}]
```
6. Run `fluent-bit -e /PATH/TO/LOKI/clients/cmd/fluent-bit/out_grafana_loki.so -c fluent-bit-loki.conf`
```
level=debug caller=loki.go:53 id=0 msg="processing records" records="map[log:{\"level\":\"error\"} stream:stdout]"
```

**Expected behavior**
For fluent-bit to unescape the JSON string and store it as native JSON instead of a string.

**Environment:**
 - Infrastructure: ECS with firelens, fluent-bit v1.8.9, loki and loki fluent-bit output plugin v2.4.1
 - Deployment tool: Terraform

**Comment by nottug** [comment]
This is definitely still an issue and there is a relatively simple fix unless I'm misunderstanding how fluent bit is meant to be used here.

**Comment by bbangert** [comment]
I'm running into this as well, it seems pretty common that people use JSON structured logs, its bizarre that the Loki output won't ship them right.

**Comment by duboisph** [comment]
Also running into this issue, however when disabling `Merge_Log` on the kubernetes filter we use, json is properly shipped to Loki.

**Comment by cyriltovena** [comment]
Made a PR very similar to your branch but wanted to avoid back and forth.

FYI Next time @nottug don't hesitate to send the PR we'll review it gladly. We love cool contributions.

**Comment by nottug** [comment]
That's perfect, thank you - and noted, I definitely will in the future. Thanks for getting this resolved, feel free to close this once its merged.
