### ISSUE TITLE
can't push correctly json data to Loki

### ISSUE THREAD

**Issue by sleleko** [grafana/loki#478]
Hello!
Loki build is: master-d75212d
Promtail build is: master-d75212d

I,m try this
`curl -i -H "Content-type: application/json" \                                                                                                  
-X POST --data '{
  "streams": [
    {
      "labels": "{source=\"JSON\",job=\"simpleJsonJob\", host=\"SimpleHost\"}",
      "entries": [{ "timestamp": "1554887676", "line": "TEST!" }]
    }
  ]
}' "loki:3100/api/prom/push"
`
But recieve this anwer:
`HTTP/1.1 204 No Content
Date: Fri, 12 Apr 2019 05:19:09 GMT`
And in Loki can see only pushed erly lables - source = JSON,job = simpleJsonJob, and host= SimpleHost .

**Comment by steven-sheehy** [comment]
204 is the success response since there is no response payload. The problem here is your timestamp. The timestamp key is `ts` not `timestamp`. Also, your timestamp is not in the correct format. It should be in RFC 339 as shown [here](https://github.com/grafana/loki/blob/master/docs/api.md). Try this:

```shell
curl -i -H "Content-type: application/json" -X POST --data '{ "streams": [ { "labels": "{source=\"JSON\",job=\"simpleJsonJob\", host=\"SimpleHost\"}", "entries": [{ "ts": "2019-04-12T16:13:06.801064Z", "line": "TEST!" }] } ] }' http://loki:3100/api/prom/push
```

**Comment by sleleko** [comment]
> ```shell
> curl -i -H "Content-type: application/json" -X POST --data '{ "streams": [ { "labels": "{source=\"JSON\",job=\"simpleJsonJob\", host=\"SimpleHost\"}", "entries": [{ "ts": "2019-04-12T16:13:06.801064Z", "line": "TEST!" }] } ] }' http://loki:3100/api/prom/push
> ```

Thank you! Now its work.

**Comment by mrarunmalhotra** [comment]
Hi, getting same problem, kindly check the parameters. 

`curl -i -H "Content-type: application/json" -X POST --data '{ "streams": [ { "labels": "{source=\"JSON\",job=\"simpleJsonJob\", host=\"SimpleHost\"}", "entries": [{ "ts": "2021-04-23T16:13:06.801064Z", "line": "TEST!" }] } ] }' http://locahost:3100/loki/api/v1/push`

**RESULT**: 
HTTP/1.1 204 No Content
Date: Fri, 23 Apr 2021 16:47:22 GMT

**Comment by mbc99** [comment]
Hi, I tried posting a question here: https://community.grafana.com/t/send-json-log-to-http-api/56819 but no one responded so I'm going to assume I haven't made a silly mistake.

Trying to send the same content as slekelo did at the moment with Python:
```
import requests
headers = {'Content-type': 'application/json'}
json='{ "streams": [ { "labels": "{source=\"JSON\",job=\"simpleJsonJob\", host=\"SimpleHost\"}", "entries": [{ "timestamp": "1638135451", "line": "TEST!" }] } ] }'
response=requests.post("https://domain.net/loki/api/v1/push", headers=headers, data=json)
print (str(response.content))
```

But I get: 

> b'loghttp.PushRequest.Streams: []*loghttp.Stream: ReadObjectCB: object not ended with }, error found in #10 byte of ...|{source="JSON",job="|..., bigger context ...|{ "streams": [ { "labels": "{source="JSON",job="simpleJsonJob", host="SimpleHost"}", "en|...\n'
