### ISSUE TITLE
Simple Single Binary Jsonnet example

### ISSUE THREAD

**Issue by xaque208** [grafana/loki#4781]
**Is your feature request related to a problem? Please describe.**

I'd like to see an example of the simplest jsonnet example for a single-binary deployment of loki.

**Describe the solution you'd like**

Something akin to https://github.com/grafana/tempo/tree/main/example/tk/tempo-single-binary

**Describe alternatives you've considered**

Building one.

**Additional context**
Using kubernetes, but have a small footprint (memory) requirement.  I have a minio to use for backend storage that has plenty of room which I'm running off cluster.

**Comment by jeschkies** [comment]
@trevorwhitney we should have something, right?

**Comment by trevorwhitney** [comment]
hmm, we definitely have some ssd envrionments deployed with jsonnet, my guess is we just don't have anything public at the moment.
I can look into publicizing something.

**Comment by trevorwhitney** [comment]
@xaque208 here you go: https://github.com/grafana/jsonnet-libs/pull/723

**Comment by xaque208** [comment]
Awesome, thanks folks.
