### ISSUE TITLE
Add pagination options to HTTP API queries

### ISSUE THREAD

**Issue by renrutmas** [grafana/loki#4793]
**Is your feature request related to a problem? Please describe.**
I have a userbase that uses flat files for parsing decision trees made by algorithms and running a series of python scripts against that data.
The data is nearly enough in logfmt.
The analysis scripts currently load entire log files into memory because they do the parsing of datetime and filter values.
Using Loki we store the same set of log data and visualise in some Grafana dashboards.
To replace the existing flat file store I need to be able to provide a way to run the existing analysis scripts against the Loki data.
I can currently only get a limit of 5000 records via the HTTP API.

**Describe the solution you'd like**
 response = requests.get('http://10.1.1.10:3101/loki/api/v1/query_range?query='
                         +query
                         +'&start='
                         +startdate
                         +'&end='
                         +enddate
                         +'&startrecord='
                         +'5001'
                        )

Add a new variable allowing me to start from record number _n_

**Describe alternatives you've considered**
ELK - too complicated
Splunk - too expensive
Continue with flat files - too slow / disk space heavy

**Comment by renrutmas** [comment]
Yes using Python at the moment. 
Any code you can share in Java would be greatly appreciated.
Thanks.

**Comment by cyriltovena** [comment]
Streaming API via websocket might be better than pagination as no context needs to be store on the server and the client implementation will be easier.

**Comment by jeschkies** [comment]
> Streaming API via websocket might be better 
Do you mean `tail` or a different endpoint?

> as no context needs to be store on the server and the client implementation will be easier.
We don't have to store any context. The current batching uses the timestamps already. We just need to give the time range so the clients do not have to keep track.

@renrutmas [here](https://github.com/jeschkies/kafka-connect-loki/blob/main/src/main/java/com/grafana/loki/LokiSourceTask.java#L110) is a Java version. Please note that it does not loop. Kafka is taking care of it. Your client should just send a new request starting at `lastTimestamp +1`. [Here's](https://github.com/grafana/loki/blob/d6727398d042cc429232120a7127701278249a26/pkg/logcli/query/query.go#L93) a similar loop on `logcli`.

**Comment by jeschkies** [comment]
@renrutmas I dove into the implementation of the query endpoint. If I'm not mistaken the limit is not required. Do you want the pagination to continue querying after the endpoint?

**Comment by jeschkies** [comment]
I've tried to implement pagination but hit a road block https://github.com/grafana/loki/pull/5355

**Comment by turtleDev** [comment]
+1 

We're using Loki as both our log aggregator and a log server. Sometimes when the log lines within the same time window exceed batch size, the pagination logic that's officially recommended breaks down.
