### ISSUE TITLE
Document simple scalable deployment example using docker-compose

### ISSUE THREAD

**Issue by 09jvilla** [grafana/loki#4800]
@trevorwhitney to work with @KMiller-Grafana to take his video 
https://grafana.com/blog/2021/11/18/video-the-new-simple-scalable-deployment-for-grafana-loki-and-grafana-enterprise-logs/
and turn it into a permanent docs page. 

The permanent docs page should have:
1. Instead of using the rpm like @trevorwhitney does in the video, lets just use the docker images (since Loki doesn't have rpm packages right now). 
2. Lets ensure that the config files that are using in the video are properly commented to help users understand what is doing what.

**Comment by dginhoux** [comment]
Hi, 

Yes i think it's a good idea. im' trying to build a new loki stack with loki splitted in microservices.
An example will be very usefull to help us.
