### ISSUE TITLE
Disable compactor in single binary

### ISSUE THREAD

**Issue by bobykus31** [grafana/loki#4801]
Is there  any way to disable compactor when running loki single binary but leave all the other functionality?

**Comment by chaudum** [comment]
Hey @bobykus31

You may submit questions in any of the following ways:

  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

All questions submitted as issues will be closed.
