### ISSUE TITLE
Cannot build loki-mixin

### ISSUE THREAD

**Issue by DaveOHenry** [grafana/loki#4805]
**Describe the bug**
Building the Loki mixin fails, because a necessary lib is not included. See this commit:
https://github.com/grafana/loki/commit/5640cd0f7c06f0ed9bcc33f23f0d8a564952ba33#diff-091532576bfe45f8c168b3c12706d733ec550ba3461ad44614a761a399a9ab81R2

**To Reproduce**
1. git clone git@github.com:grafana/loki.git
2. jb init
3. jb install https://github.com:grafana/loki/production/loki-mixin@main
4. cd loki/vendor/loki-mixin
5. jsonnet -J vendor -S -e 'std.manifestYamlDoc((import "mixin.libsonnet").prometheusAlerts)' > alerts.yml
5. jsonnet -J vendor -S -e 'std.manifestYamlDoc((import "mixin.libsonnet").prometheusRules)' >files/rules.yml
6. jsonnet -J vendor -m files/dashboards -e '(import "mixin.libsonnet").grafanaDashboards'

**Expected behavior**
Building succeeds.

**Environment:**
Ubuntu 20.04

**Screenshots, Promtail config, or terminal output**
```
2021/11/23 17:02:25 RUNTIME ERROR: couldn't open import "grafonnet/template.libsonnet": no match locally or in the Jsonnet library paths
        vendor/github.com/grafana/loki/production/loki-mixin/dashboards/loki-logs.libsonnet:2:18-5thunk <template> from <$>
        vendor/github.com/grafana/loki/production/loki-mixin/dashboards/loki-logs.libsonnet:7:5-13
        vendor/github.com/grafana/loki/production/loki-mixin/dashboards/loki-logs.libsonnet:75:11-29       thunk from <object <anonymous>>
        During manifestation
```

**Comment by Lusitaniae** [comment]
Would be interesting to have the steps above documented on the website/github (for people new to mixins)
