### ISSUE TITLE
topk broken when using parsers in recent Grafana Cloud update?

### ISSUE THREAD

**Issue by loganmc10** [grafana/loki#4806]
**Describe the bug**
We have a query that looks like this:
```
topk(20,
sum by (SrcAddr) (
sum_over_time(
{job="netflow",SamplerAddress=~`${sampler}`,InIf=~`${inif}`,OutIf=~`${outif}`} | json | SrcAddr=ip("${src_addr}") DstAddr=ip("${dst_addr}") | unwrap Bytes[$__range])
))
```
This was working, it would show the top 20 talkers by SrcAddr. However, just recently the panel shows "maximum of series (500) reached for a single query".

**To Reproduce**
Grafana employees are welcome to check out our dashboard in Grafana Cloud: https://suncornoc.grafana.net/d/XlsOy1uMk/netflow-dashboard?orgId=1

We also have this same issue doing a query like this:
```
topk(20, sum(count_over_time({appname="sitecore_request_logging",job="syslog"} | logfmt[$__interval])) by (CLIENT_IP))
```
Again, it errors out saying we're over the maximum number of series for a single query, but I don't see how this is possible, since we're doing topk(20,...) and we are summing by a single label.

**Expected behavior**
Since we're using topk(20,...) I don't see how the query could return more than 20 results

**Environment:**
Grafana Cloud

**Comment by jeschkies** [comment]
Hi,
topk needs to evaluate all series matching the labels. This might exceed the maximum. I need to dig a little into the code to understand.

**Comment by loganmc10** [comment]
I was under the impression that the max series limit applied only to the final result returned, not intermediate calculations.

The other thing is, I know this used to work for us, and stopped working within the last day or two. Grafana Cloud doesn't give you any information about upgrades/software versions so I can't really say what changed.

**Comment by yongzhang** [comment]
I have the same issue, I was stuck on this all day ...

**Comment by cyriltovena** [comment]
Technically we can increase the limit, this is on all computed series used for returning the result since this is what will consume memory. In the case of a single IP it should be fine to increase,  but if someone where to use this with a long series name it could create out of memory issue on the cluster.

**Comment by loganmc10** [comment]
But this changed at some point recently correct? Before, only the final result seemed to matter for the series limit. This kind of thing is really frustrating as a Cloud customer. Grafana doesn't provide any changelogs, or upgrade/downgrade notices, I just wake up one day and all my panels look like this:
![image](https://user-images.githubusercontent.com/848146/146019411-897b687f-6992-4e5c-8896-18b57263a246.png)

Wouldn't this limit cripple a lot of metric use cases? For instance, if you have a web server that logs access requests, and you want to find your "top 50" users from the logs, if you're operating at any kind of scale you're going to have more than 500 or 2000 unique users, there would be no way to gather that information from the logs.

I really think Grafana should have paying Cloud consumers on some different release cadence from the OSS/free tier users. At the very least a changelog or an upgrade notice would be nice.

**Comment by cyriltovena** [comment]
I don't disagree with the changelog, that's something we're looking into. 

You are actually on a different cadence, you get faster update, every week we update all our cluster from dev, stage to prod and we make sure no breaking change is included.

This has not changed and was always the on all the processing, not the final result.

I'm also aware of the topk limitations, unfortunately removing the limit will make all our customer at risk of someone submitting a bad query. We're looking into two way to fix it:

- Supporting the @ modifier like Prometheus does, this way the topk is the same for all step in a query range.
- Add topk estimation.

In the meantime we can offer to increase that limit to something that work for everyone via support.

**Comment by loganmc10** [comment]
> This has not changed and was always the on all the processing, not the final result.

We'll have to agree to disagree on this I suppose. I know that it used to work for us, we used it every day, one day I woke up and all the panels said "maximum of series (500) reached for a single query" and then eventually the limit changed to 2000.

We were always over 500/2000 series for the intermediate processing, it's netflow data with 1000's of unique sources/destinations. We'll just have to look at a different product for netflow collection.

**Comment by yongzhang** [comment]
forgive my stupid question, does increasing the limit fix the issue? should topk(20, xxx) return 20 only?

**Comment by loganmc10** [comment]
> forgive my stupid question, does increasing the limit fix the issue? should topk(20, xxx) return 20 only?

Yes, but I believe what @cyriltovena is saying is that if the "xxx" portion of the query would have returned a number of series that are over the limit, it will still error out.

I still don't fully understand to be honest, for instance, I can't do this:
![image](https://user-images.githubusercontent.com/848146/146297253-dbf9ecbb-db23-4bea-be89-501e4b930be7.png)

But this works:
![image](https://user-images.githubusercontent.com/848146/146297302-a30186c5-8c0b-40f1-9c29-1b28b9e7360e.png)

So does this:
![image](https://user-images.githubusercontent.com/848146/146297403-fc23aee6-2b03-4722-bb61-baafb12d4a60.png)

I think the actual problem comes in when you try to use a parser in the query, for example:
![image](https://user-images.githubusercontent.com/848146/146297743-b1610b80-8aed-4182-bade-94fb29f9d07c.png)

When you use sum by it still works:
![image](https://user-images.githubusercontent.com/848146/146297858-e45864f7-d544-414f-9b56-32e399a5e3b3.png)

But topk no longer works:
![image](https://user-images.githubusercontent.com/848146/146297886-97473cdd-ca2f-4ab0-8595-b6d6152edfe8.png)

**Comment by yongzhang** [comment]
ahhh, thanks for the explanation, exactly I hit the issue using pattern.

**Comment by cyriltovena** [comment]
For most queries using `sum by` it will reduce the amount of labels at the edge hence why without the sum by you hit this limit faster.

The topk should work with the `sum by`. The pattern in you example adds a label that for sure has more than 2k values. But because you used a `sum by job`, it will discard it, Loki know this pattern is in fact not useful for the query.

I'm happy to dig deeper for queries that broke, it's not impossible another change could have had a side effect, but limit and how we apply it hasn't really changed.

You can reach out on slack if that works for you and debug this together.
