### ISSUE TITLE
How `retention_period` works with s3 as object storage?

### ISSUE THREAD

**Issue by JeffLuoo** [grafana/loki#4816]
Hi Loki experts,

I have a question regarding to the retention mechanism in Loki.

According to the doc: https://grafana.com/docs/loki/v2.2.1/operations/storage/retention/

`Table_Manager` is the only option in v2.2.1 to support the retention, and it says
```
When using S3 or GCS, the bucket storing the chunks needs to have the expiry policy set correctly. For more details check S3’s documentation or GCS’s documentation.
```

And according to https://grafana.com/docs/loki/v2.2.1/storage/#retention, it says
```
With the exception of the filesystem chunk store, Loki will not delete old chunk stores. This is generally handled instead by configuring TTLs (time to live) in the chunk store of your choice (bucket lifecycles in S3/GCS ...
```

I am now confused by that does the setting of `retention_period` work for using s3 as object storage backend..?

**Comment by yangvipguang** [comment]
@JeffLuoo    https://grafana.com/docs/loki/latest/operations/storage/retention/

**Comment by JeffLuoo** [comment]
@yangvipguang Thanks!

And I wanna ask one more question is that in my schema_config , if I didn’t create a new period_config section to switch to use the s3 as object_store. Instead, I just update the object_store field from filesystem to s3, what will be the behavior then? Does the `retention_period` still work for chunks that are sitting in the disk or they will never be dropped because the new configuration will point the Loki to seek for indexes storing under s3 starting from the time configured in from  section. This part is not mentioned in the doc.

**Comment by kavirajk** [comment]
We try to keep GitHub issues strictly for bug reports and feature requests.

This sounds like a question rather than an issue with Loki, so let's move the discussion to one of these channels:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.

**Comment by dellnoantechnp** [comment]
When using S3 or GCS, the bucket storing the chunks needs to have the expiry policy set correctly. 
For more details check [S3’s documentation](https://docs.aws.amazon.com/AmazonS3/latest/dev/object-lifecycle-mgmt.html) or [GCS’s documentation](https://cloud.google.com/storage/docs/managing-lifecycles).

**Comment by wind-framework** [comment]
@JeffLuoo I have test for simply switch to s3 storage one month ago, the retention will not work for old chunks in disk, old chunks still stay in disk when time is out of retention period.

**Comment by xpader** [comment]
@JeffLuoo I have test for simply switch to s3 storage one month ago, the retention will not work for old chunks in disk, old chunks still stay in disk when time is out of retention period.

**Comment by piratetm** [comment]
It is not works... So sad
