### ISSUE TITLE
Promtail mixin: Missing dashboard variable

### ISSUE THREAD

**Issue by DaveOHenry** [grafana/loki#4817]
**Describe the bug**
The dashboard does not display any data, because the "name" variable is missing.
I guess this commit introduced the issue:
https://github.com/grafana/loki/commit/5640cd0f7c06f0ed9bcc33f23f0d8a564952ba33#diff-7312fe320b636c6649986bbc434939d55a4d8be2b5bc791d6e632a90c9e7b4adL23-L36

Adding `.addTemplate('name', 'kube_pod_info{namespace="$namespace",pod=~"promtail.*"}', 'created_by_name')` to the dashboard definition fixes the problem as far as I can tell. Maybe I'm missing something with my poor understanding of jsonnet, but I'm pretty sure that this is not how it is supposed to work. 

**To Reproduce**
1. Build the mixin
2. Copy dashboard to Grafana instance
3. Observe that there is no data

**Expected behavior**
Dashboard renders data correctly.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: jsonnet, mixtool

**Screenshots, Promtail config, or terminal output**
![image](https://user-images.githubusercontent.com/20969773/143240447-04bae021-0824-4249-abaa-03431cc93aef.png)

**Comment by jeschkies** [comment]
Hm, I have to admit that I couldn't find any user of the `name` variable in `production/promtail-mixin`. Which version of the mixin are you using?

**Comment by DaveOHenry** [comment]
That's weird. I'm using the current one from the "main" branch and "$name" is used in every query as part of the job selector:
https://github.com/grafana/loki/blob/main/production/promtail-mixin/dashboards.libsonnet#L21-L22

**Comment by jeschkies** [comment]
Ah. Ok, I didn't know `$name` was working. I thought this was a Jsonnet string interpolation variable. Ok. So we do have to define it.

**Comment by DaveOHenry** [comment]
not stale
