### ISSUE TITLE
Can't push JSON data to Loki

### ISSUE THREAD

**Issue by mbc99** [grafana/loki#4837]
Hi, I tried posting a question here: https://community.grafana.com/t/send-json-log-to-http-api/56819 but no one responded so I'm going to assume I haven't made a silly mistake and there is something wrong on the Loki side.

Trying to send the same content as slekelo did at that moment: https://github.com/grafana/loki/issues/478
```
import requests
headers = {'Content-type': 'application/json'}
json='{ "streams": [ { "labels": "{source=\"JSON\",job=\"simpleJsonJob\", host=\"SimpleHost\"}", "entries": [{ "ts": "2021-08-12T16:13:06.801064Z", "line": "TEST!" }] } ] }'
response=requests.post("https://domain.net/loki/api/v1/push", headers=headers, data=json)
print (str(response.content))
```

But I get: 

> b'loghttp.PushRequest.Streams: []*loghttp.Stream: ReadObjectCB: object not ended with }, error found in #10 byte of ...|{source="JSON",job="|..., bigger context ...|{ "streams": [ { "labels": "{source="JSON",job="simpleJsonJob", host="SimpleHost"}", "en|...\n'

**Comment by cyriltovena** [comment]
The json is not the expected one from the API see:

https://grafana.com/docs/loki/latest/api/#post-lokiapiv1push

```
curl -v -H "Content-Type: application/json" -XPOST -s "http://localhost:3100/loki/api/v1/push" --data-raw \
  '{"streams": [{ "stream": { "foo": "bar2" }, "values": [ [ "1570818238000000000", "fizzbuzz" ] ] }]}'
```

**Comment by Theoooooo** [comment]
> The json is not the expected one from the API see:
> 
> https://grafana.com/docs/loki/latest/api/#post-lokiapiv1push
> 
> ```
> curl -v -H "Content-Type: application/json" -XPOST -s "http://localhost:3100/loki/api/v1/push" --data-raw \
>   '{"streams": [{ "stream": { "foo": "bar2" }, "values": [ [ "1570818238000000000", "fizzbuzz" ] ] }]}'
> ```

I'm having the exact same issue, i'm trying for 4 hours to get this to work but even using your exemple isn't working for me, i'm still getting the same error "error at least one label pair is required per stream"

My request :
``` bash
curl -i -X POST -H "Content-Type: application/json" "http://IP_ADDRESS:PORT/api/prom/push" --data-raw '{"streams":[{"stream":{"host":"SRV-TRE-REDIS01"},"entries":[{"ts":"2021-12-17T16:08:41.539697+01:00","task_id":"mfvsdhfhlsbet","result":"created"}]}]}'

HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Fri, 17 Dec 2021 15:35:36 GMT
Content-Length: 53

error at least one label pair is required per stream
```

Even if use the old label system, the request either got pass through, but i can't find any log inside my loki instance, or either i'm getting this error message

Any idea ? It's getting really frustrating trying to get this to work

**Comment by mbc99** [comment]
> > The json is not the expected one from the API see:
> > https://grafana.com/docs/loki/latest/api/#post-lokiapiv1push
> > ```
> > curl -v -H "Content-Type: application/json" -XPOST -s "http://localhost:3100/loki/api/v1/push" --data-raw \
> >   '{"streams": [{ "stream": { "foo": "bar2" }, "values": [ [ "1570818238000000000", "fizzbuzz" ] ] }]}'
> > ```
> 
> I'm having the exact same issue, i'm trying for 4 hours to get this to work but even using your exemple isn't working for me, i'm still getting the same error "error at least one label pair is required per stream"
> 
> My request :
> 
> ```shell
> curl -i -X POST -H "Content-Type: application/json" "http://IP_ADDRESS:PORT/api/prom/push" --data-raw '{"streams":[{"stream":{"host":"SRV-TRE-REDIS01"},"entries":[{"ts":"2021-12-17T16:08:41.539697+01:00","task_id":"mfvsdhfhlsbet","result":"created"}]}]}'
> 
> HTTP/1.1 400 Bad Request
> Content-Type: text/plain; charset=utf-8
> X-Content-Type-Options: nosniff
> Date: Fri, 17 Dec 2021 15:35:36 GMT
> Content-Length: 53
> 
> error at least one label pair is required per stream
> ```
> 
> Even if use the old label system, the request either got pass through, but i can't find any log inside my loki instance, or either i'm getting this error message
> 
> Any idea ? It's getting really frustrating trying to get this to work

I tried everything and got nothing.

I ended up giving up and changing the log format to avoid using json.

But it's wasteful because LOKI has options to format json messages on the UI. So it seems like it's only a matter of developing the right endpoint....

**Comment by Theoooooo** [comment]
> > > The json is not the expected one from the API see:
> > > https://grafana.com/docs/loki/latest/api/#post-lokiapiv1push
> > > ```
> > > curl -v -H "Content-Type: application/json" -XPOST -s "http://localhost:3100/loki/api/v1/push" --data-raw \
> > >   '{"streams": [{ "stream": { "foo": "bar2" }, "values": [ [ "1570818238000000000", "fizzbuzz" ] ] }]}'
> > > ```
> > 
> > 
> > I'm having the exact same issue, i'm trying for 4 hours to get this to work but even using your exemple isn't working for me, i'm still getting the same error "error at least one label pair is required per stream"
> > My request :
> > ```shell
> > curl -i -X POST -H "Content-Type: application/json" "http://IP_ADDRESS:PORT/api/prom/push" --data-raw '{"streams":[{"stream":{"host":"SRV-TRE-REDIS01"},"entries":[{"ts":"2021-12-17T16:08:41.539697+01:00","task_id":"mfvsdhfhlsbet","result":"created"}]}]}'
> > 
> > HTTP/1.1 400 Bad Request
> > Content-Type: text/plain; charset=utf-8
> > X-Content-Type-Options: nosniff
> > Date: Fri, 17 Dec 2021 15:35:36 GMT
> > Content-Length: 53
> > 
> > error at least one label pair is required per stream
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Even if use the old label system, the request either got pass through, but i can't find any log inside my loki instance, or either i'm getting this error message
> > Any idea ? It's getting really frustrating trying to get this to work
> 
> I tried everything and got nothing.
> 
> I ended up giving up and changing the log format to avoid using json.
> 
> But it's wasteful because LOKI has options to format json messages on the UI. So it seems like it's only a matter of developing the right endpoint....

Hey, i got it working a few hours later and i've been able to create a function to post json content to loki from a python script.

Here is the good format if you need it :
```json
{"streams": [{ "stream": {"job":"bot_python","task_id":"2022-03-01","type":"execution"}, "values": [[1570818238000000000, 'value=one text=string'],[1570818238000000000,'something=another_data integer=123456789']]}]}
```
The streams definition are going to be your labels inside loki. I hope i've helped you 👍

**Comment by github-amine-kherbouche** [comment]
> Hey, i got it working a few hours later and i've been able to create a function to post json content to loki from a python script.
> 
> Here is the good format if you need it :
> 
> ```json
> {"streams": [{ "stream": {"job":"bot_python","task_id":"2022-03-01","type":"execution"}, "values": [[1570818238000000000, 'value=one text=string'],[1570818238000000000,'something=another_data integer=123456789']]}]}
> ```
> 
> The streams definition are going to be your labels inside loki. I hope i've helped you +1

the UnixNano should be a string to get it to work.
