### ISSUE TITLE
Include additional fields in GEFL

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#4846]
As per the documentation we should include extra fields: https://docs.graylog.org/docs/gelf

They can be in form of `_[additional field] string (UTF-8) or number` and should be added as discovered labels as `__gelf_message_extra_<name>`.

**Comment by NMichas** [comment]
Hi @cyriltovena, 

Are you aware if `__gelf_message_extra_<name>` has actually been implemented? I can access fine the built-in labels (i.e. `__gelf_message_level`, `__gelf_message_host`, `__gelf_message_version`, and `__gelf_message_facility`) in my `relabel_configs` section, however any additional field my application sends seems to be ignored (e.g. `__gelf_message_extra_myfield`).  I also tried, just in case, `__gelf_message_myfield` but doesn't work either.

Note, that I can see a field named "_myfield" in the JSON output of my log entry when querying Loki in Grafana, so it looks like my app is correctly sending the field.

Thanks!

**Comment by darraghjones** [comment]
any chance of getting this ticket re-opened?
