### ISSUE TITLE
frontend not working after update to 2.4.0 from 2.3.0

### ISSUE THREAD

**Issue by xinau** [grafana/loki#4868]
**Describe the bug**
With the upgrade to Loki version 2.4.0 from 2.3.0 we've decided to use the common config block to simplify our setup.
As our AWS instances have different interface names (ens5) than the default values of loki, therefore we are required to override them.
Loki version 2.4.0 introduced new config settings for the frontend, including settings for the `instance_interface_names` with a default value of `[en0, eth0]`, which are as noted above not available on our instances.

**To Reproduce**

To reproduce this issue a minimal config is needed, loki version 2.4.0 and an instance with non default interface names.

```yaml
schema_config:
  configs:
    - from: 2021-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
```

```console
$ ./loki --config.file ./loki.yaml
...
Dec 03 10:02:39 loki-1.shared.codecentric.cloud loki[24914]: level=info ts=2021-12-03T10:02:39.519027279Z caller=shipper_index_client.go:108 msg="starting boltdb shipper in 0 mode"
Dec 03 10:02:39 loki-1.shared.codecentric.cloud loki[24914]: level=info ts=2021-12-03T10:02:39.520447359Z caller=worker.go:109 msg="Starting querier worker using query-scheduler and scheduler ring for addresses"
Dec 03 10:02:39 loki-1.shared.codecentric.cloud loki[24914]: level=warn ts=2021-12-03T10:02:39.521784878Z caller=net.go:19 msg="error getting interface" inf=eth0 err="route ip+net: no such network interface"
Dec 03 10:02:39 loki-1.shared.codecentric.cloud loki[24914]: level=warn ts=2021-12-03T10:02:39.521849077Z caller=net.go:19 msg="error getting interface" inf=en0 err="route ip+net: no such network interface"
...
```

The difference of the final frontend config for Loki version 2.3.0 and 2.4.0 is as follows.

```console
$ ./loki-2.3.0 --config.file ./loki.yaml --print-config-stderr 2>&1 | sed -n '/^frontend:/,/^ruler:/{//b; s/^  //p}' > output-2.3.0.yaml
$ ./loki-2.4.0 --config.file ./loki.yaml --print-config-stderr 2>&1 | sed -n '/^frontend:/,/^ruler:/{//b; s/^  //p}' > output-2.4.0.yaml
$ diff output-2.3.0.yaml output-2.4.0.yaml
5a6,31
> scheduler_address: ""
> scheduler_dns_lookup_period: 10s
> scheduler_worker_concurrency: 5
> grpc_client_config:
>   max_recv_msg_size: 104857600
>   max_send_msg_size: 16777216
>   grpc_compression: ""
>   rate_limit: 0
>   rate_limit_burst: 0
>   backoff_on_ratelimits: false
>   backoff_config:
>     min_period: 100ms
>     max_period: 10s
>     max_retries: 10
>   tls_enabled: false
>   tls_cert_path: ""
>   tls_key_path: ""
>   tls_ca_path: ""
>   tls_server_name: ""
>   tls_insecure_skip_verify: false
> instance_interface_names:
> - eth0
> - en0
> - lo
> address: ""
> port: 0
```

**Expected behavior**

None as this wasn't advertised as a breaking change and clearly is one or that the setting supplied in the common config block would also override these.

**Environment:**

We run Loki on multiple AWS instances, but this issue should apply to more environments. 

**Workaround:**

The workaround for this issue is quite simple, by configuring the `instance_interface_names` inside the `frontend` block as well.

```yaml
...
frontend:
  instance_interface_names: [ens5]
```

**Other**

* #4699 - has with high probability the same underlying issue.

**Comment by DylanGuedes** [comment]
Agreed, that should be better documented (especially in the upgrading guide). Regarding the changes:
- The net interface name present in the common configuration section is only applied to *ring* interface names (as it is in a ring subsection). That said, I think reusing it for the frontend would be confusing (the query_scheduler has a ring, not the frontend). 
- [en0, eth0] are default interface names used all around the project. I know that this caused your setup to run into problems but not defaulting to them, again, would be inconsistent/confusing for a lot of other users IMO

**Comment by xinau** [comment]
Don't get me wrong I didn't want to suggest to not default to `[en0, eth0]`. I just wanted to explain why this resulted in problems for us.

I agree with you that as the frontend doesn't have a ring, thus reusing the interfaces from the `common.ring` might be confusing for users. But I also think it's an unexpected surprise when you have defined them at a "common" place that a one specific component does behave differently than the rest.

Maybe a possible solution would be to "elevate" the `instance_interface_names` from `common.ring` to `common` and use this value for ring and frontend, therefore resolving potential ambiguity.

**Comment by DylanGuedes** [comment]
Agreed, having a more general `instance_interface_names` under `common` looks much better. I'll create an issue for it.

**Comment by xinau** [comment]
Thanks.

**Comment by DylanGuedes** [comment]
Closing this, as we've added a new common interface name configuration.

**Comment by xinau** [comment]
@DylanGuedes Thanks.
