### ISSUE TITLE
Promtail jsonnet results in invalid promtail.yml

### ISSUE THREAD

**Issue by xaque208** [grafana/loki#4883]
I'm deploying `grafana/loki:latest` into kubernetes with jsonnet and tanka, trying to get promtail up and running.

I have the following.
```jsonnet
local promtail = import 'promtail/promtail.libsonnet';

promtail {
  _config+:: {
    promtail_config+: {
      clients: [
        {
          scheme:: 'http',
          hostname: "loki:3200",
        },
      ] ,
    },
  },
```

And the link to show what I'm using.

```bash
❯ ls -ld vendor/promtail
0 lrwxrwxrwx 1 zach zach 51 Nov 27 12:47 vendor/promtail -> github.com/grafana/loki/production/ksonnet/promtail
```
But for some reason, `hostname` shows up in the `clients` config, which then throws an error when promtail starts because the field isn't valid.

```
❯ k describe configmaps promtail
Name:         promtail
Namespace:    default
Labels:       <none>
Annotations:  <none>

Data
====
promtail.yml:
----
clients:
  - hostname: loki:3200
    url: http://loki:3200/loki/api/v1/push
...
```

Perhaps I'm overlooking something in the jsonnet.  I couldn't find an example, so perhaps what I'm doing isn't correct.  Either way, would you mind providing some pointers?

**Comment by dannykopping** [comment]
Hey @xaque208 

The `clients` section of the config does not contain a `hostname` field:
https://grafana.com/docs/loki/latest/clients/promtail/configuration/#clients

You should just be able to remove that, and it should work?

**Comment by xaque208** [comment]
The trouble I'm running into is that to use the jsonnet lib, the `hostname` is required.

https://github.com/grafana/loki/blob/main/production/ksonnet/promtail/config.libsonnet#L13

But some munging happens and I'm not sure why the `hostname` end up in the config at all.

https://github.com/grafana/loki/blob/main/production/ksonnet/promtail/promtail.libsonnet#L28

**Comment by dannykopping** [comment]
Ah, I think I see the problem.

You've got `hostname` as an exported field (single colon); it should probably be hidden (double colon)

**Comment by xaque208** [comment]
Ohh I see now, thank you!
