### ISSUE TITLE
per_stream_rate_limit not working as intended - Or promtail_read_bytes_total metric is wrong? 

### ISSUE THREAD

**Issue by diranged** [grafana/loki#4887]
**Describe the bug**
_Slack Thread: https://grafana.slack.com/archives/CEPJRLQNL/p1638845037079200_

We were paged yesterday by a Promtail alert letting us know that promtail was seeing a high rate of retries to push into the Loki endpoint. When we investigated, we discovered that there was a noisy Pod emitting lots of logs, and that pod's log stream was being rate limited:

```
level=warn ts=2021-12-07T01:18:41.051494505Z caller=client.go:344 component=client host=observability-loki-gateway msg="error sending batch, will retry" status=429 error="server returned HTTP status 429 Too Many Requests (429): entry with timestamp 2021-12-07 01:18:39.25962493 +0000 UTC ignored, reason: 'Per stream rate limit exceeded (limit: 3MB/sec) while attempting to ingest for stream '{app=\"ksql-server\", container=\"ksql-server\", filename=\"/var/log/pods/ksqldb_ksqldb-ksql-server-headless-65f6b6b54c-tj5pp_1c178358-57f0-40e3-b432-7cc87f4e275e/ksql-server/0.log\", instance=\"ksqldb-ksql-server-headless\", job=\"ksqldb/ksql-server\", namespace=\"ksqldb\", node_name=\"ip-100-64-135-144.us-west-2.compute.internal\", pod=\"ksqldb-ksql-server-headless-65f6b6b54c-tj5pp\", scrape_job=\"kubernetes-pods\", scrape_namespace=\"observability\", scrape_pod=\"observability-promtail-qk9zj\", stream=\"stdout\"}' totaling 384B, consider splitting a stream via additional labels or contact your Loki administrator to see if the limt can be increased' for stream: {app=\"ksql-server\", container=\"ksql-server\", filename=\"/var/log/pods/ksqldb_ksqldb-ksql-server-headless-65f6b6b54c-tj5pp_1c178358-57f0-40e3-b432-7cc87f4e275e/ksql-server/0.log\", instance=\"ksqldb-ksql-server-head"
```

So we then went and thought - let's see how many logs are being collected by this pod in-bytes:

![image](https://user-images.githubusercontent.com/768067/145045681-8761abc4-3bc8-4bbd-8959-da5adc2a4477.png)

According to this graph, unless I am doing something wrong, we were bouncing around 300-600KB/sec.. not 3MB/sec. Now I am sure that the rate-limiting has to take into account  the time in which small chunks of data are sent ... but this feels to me like we weren't really anywhere close to the intended limit of the system.

Of course, the other option is that the `promtail_read_bytes_total` metric is wrong or being used incorrectly. The metric is [defined here as a "gauge"](https://grafana.com/docs/loki/latest/operations/observability/) - however, in the dashboard code it is [used as a counter](https://github.com/grafana/loki/blob/6347faf8761538be946f751da604fc20fc91d9c2/production/promtail-mixin/dashboards.libsonnet#L46-L47).

When we look at the one graph for this particular stream and remove the `rate()` function, it suddenly looks like perhaps it _is_ a gauge:

![image](https://user-images.githubusercontent.com/768067/145046425-c0b96155-1186-498f-8e74-0ce3dfe92454.png)

However, as soon as I look at that graph for other pods in the system, they start to look a lot more like counters:
![image](https://user-images.githubusercontent.com/768067/145046614-66a4ff0f-bfcb-41ef-ab00-6a3bbe01b7d4.png)
![image](https://user-images.githubusercontent.com/768067/145046772-80ce5479-7288-4f60-9a6b-0b06cb244d7a.png)

As I poke around, I find other strange patterns with the `promtail_read_bytes_total` metric like these sawtooths (which you see a hint of in the "observability" namespace above):
<img width="1544" alt="Screen Shot 2021-12-07 at 6 26 37 AM" src="https://user-images.githubusercontent.com/768067/145047211-cbe6c32e-ba61-4b91-8250-fe9c669c9ddf.png">
![image](https://user-images.githubusercontent.com/768067/145047556-eeeea9e5-615a-4f80-9640-0710da3a41b3.png)

So ultimately I am a bit confused.. the `promtail_read_bytes_total` metric certainly seems to be behaving differently on different pods. At the same time, 3Mb/sec of logs is quite a lot .. and while those noisy ksqldb pods were pretty loud, I don't know that they were _that_ loud.

**Environment:**
 - Infrastructure: Kubernetes on EKS, Prometheus 2.31.1, Loki 2.4.0, Grafana 8.3.0, Promtail 2.4.0
 - Deployment tool: Helm via ArgoCD

**Comment by diranged** [comment]
Simple followup question - how does the rate limiting bucketing work.. in how short a time do bytes need to flow in before it will trip the limit.

**Comment by naveedyahyazadeh** [comment]
I'm also interested in this issue. I know that 3MB/s is causing errors on my deployment, but I am not sure what metrics to use  to calculate a good value for `per_stream_rate_limit`

**Comment by kadern0** [comment]
Facing same issue

**Comment by joshross12** [comment]
Any advice here?

**Comment by bagechashu** [comment]
> https://grafana.com/docs/loki/latest/operations/request-validation-rate-limits/#per_stream_rate_limit

```
limits_config:
      per_stream_rate_limit: 5MB
```

Add the preceding configuration to the loki configuration file.
