### ISSUE TITLE
Docs feedback: /installation/docker.md

### ISSUE THREAD

**Issue by bluepuma77** [grafana/loki#4889]
**docker**
The docs state "Copy and paste the commands below into your command line". Well, that does not work because the docker commands do not demonise, therefore it will stop after the first docker command with displaying the logs.
I recommend to either state to copy them individually (or in different shell windows) or make them demonise (`-d`). The second one does not have a `--name`.

**docker-conpose**
The "Install with Docker Compose" sounds promising, it also does not demonise. It includes Grafana on port 3000, but that is not mentioned. And the Grafana instance requires a password!? Shouldn't this be the preferred way for the first test?

**Configs**
I would recommend to include the config files directly in the docker images. As far I know you can later simply overwrite them with a bind mount if necessary.

**Comment by jeschkies** [comment]
@bluepuma77 thanks for the feedback. Would you mind proposing the change in a pull request?

**Comment by telefax** [comment]
#5213 for the docker example
