### ISSUE TITLE
Add a common `instance_interface_names` configuration

### ISSUE THREAD

**Issue by DylanGuedes** [grafana/loki#4897]
**Is your feature request related to a problem? Please describe.**
Yes. With the latest Loki release (v2.4) we decided to have a common ring section that supports a common `instance_interface_names` that is only applied to rings. Since we have `instance_interface_names` for other connections that aren't ring-related (ex: frontend), not having this configuration mislead users into thinking that the one from the common ring will work for everything.

**Describe the solution you'd like**
I would like to have a new `instance_interface_names` under the `common` section. We already have one under  `common/ring`, which should supersede this one for rings in case both are specified.

**Describe alternatives you've considered**
Another option is having a more explicit log error, that will tell users to explicitly specify their instance interface names for the `frontend`.

**Additional context**
For reference:
https://github.com/grafana/loki/issues/4868
https://github.com/grafana/loki/issues/4699

**Comment by xinau** [comment]
@DylanGuedes I guess this is not only the case for the `instance_interface_names` but also for `instance_addr` and `instance_port` 

See also #4827
