### ISSUE TITLE
AWS Cloudwatch Support or Any Alternative way like same plugin to query from cloudwatch

### ISSUE THREAD

**Issue by sachin064** [grafana/loki#4907]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dannykopping** [comment]
Hi, can you please add more detail to the issue @sachin064?

**Comment by sachin064** [comment]
http://logging-loki:3100/loki/api/v1/label/application/values , this will return the application list from the loki database, is there any  plugin or helm chart there to query from the cloud watch logs.

**Comment by jeschkies** [comment]
@sachin064 you could either use a [datasource](https://grafana.com/docs/grafana/latest/datasources/aws-cloudwatch/) or import your logs via [Lambda Promtail](https://grafana.com/docs/loki/latest/clients/lambda-promtail/).
