### ISSUE TITLE
Mismatch between example and config documentation

### ISSUE THREAD

**Issue by m0rtalis** [grafana/loki#4915]
The documentation https://grafana.com/docs/loki/latest/configuration/#local_storage_config says the local_storage_config has only the _directory_ config, but in the examples it is configured with _chunks_directory_ and _rules_directory_.

https://github.com/grafana/loki/blob/24b4c0eed2ca35225c88d428f62766e4fffbc67a/cmd/loki/loki-local-config.yaml#L10-L12

**Comment by chaudum** [comment]
Hey @m0rtalis 
Thanks for reporting. That is indeed a mistake in the configuration reference.

**Comment by jefersoonaf** [comment]
Hey @chaudum
Your correction in the documentation was merged some time ago, but it seems that it was lost from the main branch at some point after a reorganization of the configuration .md files, as it is no longer in the current documentation.

I would greatly appreciate it if you could verify the reason for the removal, as I had the same question asked by @m0rtalis and ended up finding this issue that had the solution but is no longer in the latest documentation.
