### ISSUE TITLE
how to use promtail, loki metrics in Prometheus.

### ISSUE THREAD

**Issue by HanHoRang** [grafana/loki#4940]
While implementing the Loki dashboard, I noticed that there are Loki related metrics. 
(ex. loki_distributor_ingester_append_failures_total) 

![스크린샷 2021-12-16 오후 6 27 43](https://user-images.githubusercontent.com/46108451/146345378-a6825e6b-5f91-4e67-813c-bc3aa354f7e7.png)

However, I noticed that Prometheus promQL couldn't load the metric.
Through the grafana official document(https://grafana.com/docs/loki/latest/operations/observability/)
I understood that Loki and promtail endpoints should be registered in the Prometheus config.
Any yaml examples in this regard?

**Comment by Poweranimal** [comment]
I'm having the same issue.

All Loki Distributors specific metrics (documented [here](https://grafana.com/docs/loki/latest/operations/observability/#observing-grafana-loki)) are not exposed running in module mode `distributor`.
