### ISSUE TITLE
Read path not working for target=read,write

### ISSUE THREAD

**Issue by DylanGuedes** [grafana/loki#4943]
**Describe the bug**
When running Loki with `-target=read,write`, Loki runs just fine except that the query path doesn't handle requests appropriately.
That's not critical as users can just use `-target=all` instead, but if we don't expect to support this I think we could at least log an error during Loki initialization.

**To Reproduce**
- Run loki with `-target=read,write`
- Push data to Loki (I used promtail and it worked just fine)
- Try querying Loki data with Grafana. Requests will fail with a error similar to:
```
level=warn ts=2021-12-16T11:03:06.488244812Z caller=pool.go:184 msg="removing ingester failing healthcheck" addr=127.0.0.1:9095 reason="rpc error: code = DeadlineExceeded desc = context deadline exceeded"
level=warn ts=2021-12-16T11:03:06.488488771Z caller=grpc_logging.go:38 method=/logproto.Querier/GetChunkIDs duration=4.709494936s err="rpc error: code = Unavailable desc = error reading from server: read tcp 127
.0.0.1:59894->127.0.0.1:9095: use of closed network connection" msg="gRPC\n"                                                                                                                                       
level=warn ts=2021-12-16T11:03:06.48852627Z caller=grpc_logging.go:38 method=/logproto.Querier/GetChunkIDs duration=4.711402079s err="rpc error: code = Unavailable desc = error reading from server: read tcp 127.
0.0.1:59894->127.0.0.1:9095: use of closed network connection" msg="gRPC\n"                                                                                                                                        
level=warn ts=2021-12-16T11:03:06.488536472Z caller=grpc_logging.go:38 method=/logproto.Querier/GetChunkIDs duration=4.712385021s err="rpc error: code = Unavailable desc = error reading from server: read tcp 127
.0.0.1:59894->127.0.0.1:9095: use of closed network connection" msg="gRPC\n"                   
level=warn ts=2021-12-16T11:03:06.488547264Z caller=grpc_logging.go:38 method=/logproto.Querier/GetChunkIDs duration=4.711802907s err="rpc error: code = Unavailable desc = error reading from server: read tcp 127
.0.0.1:59894->127.0.0.1:9095: use of closed network connection" msg="gRPC\n"                   
level=warn ts=2021-12-16T11:03:06.488532667Z caller=grpc_logging.go:38 method=/logproto.Querier/GetChunkIDs duration=4.708983417s err="rpc error: code = Unavailable desc = error reading from server: read tcp 127
.0.0.1:59894->127.0.0.1:9095: use of closed network connection" msg="gRPC\n"                                                                                                                                       
level=warn ts=2021-12-16T11:03:06.488568215Z caller=grpc_logging.go:38 method=/logproto.Querier/GetChunkIDs duration=4.710521129s err="rpc error: code = Unavailable desc = error reading from server: read tcp 127
.0.0.1:59894->127.0.0.1:9095: use of closed network connection" msg="gRPC\n"                   
level=warn ts=2021-12-16T11:03:06.488580803Z caller=grpc_logging.go:38 method=/logproto.Querier/GetChunkIDs duration=4.709968094s err="rpc error: code = Unavailable desc = error reading from server: read tcp 127
.0.0.1:59894->127.0.0.1:9095: use of closed network connection" msg="gRPC\n"                   
level=warn ts=2021-12-16T11:03:06.488583878Z caller=grpc_logging.go:38 method=/logproto.Querier/GetChunkIDs duration=4.707851531s err="rpc error: code = Unavailable desc = error reading from server: read tcp 127
.0.0.1:59894->127.0.0.1:9095: use of closed network connection" msg="gRPC\n"
level=warn ts=2021-12-16T11:03:06.488586384Z caller=grpc_logging.go:38 method=/logproto.Querier/GetChunkIDs duration=4.714872108s err="rpc error: code = Unavailable desc = error reading from server: read tcp 127
.0.0.1:59894->127.0.0.1:9095: use of closed network connection" msg="gRPC\n"
level=warn ts=2021-12-16T11:03:06.488577309Z caller=grpc_logging.go:38 method=/logproto.Querier/GetChunkIDs duration=4.708492491s err="rpc error: code = Unavailable desc = error reading from server: read tcp 127
.0.0.1:59894->127.0.0.1:9095: use of closed network connection" msg="gRPC\n"
level=warn ts=2021-12-16T11:03:06.488547235Z caller=grpc_logging.go:38 method=/logproto.Querier/GetChunkIDs duration=4.715231941s err="rpc error: code = Unavailable desc = error reading from server: read tcp 127
.0.0.1:59894->127.0.0.1:9095: use of closed network connection" msg="gRPC\n"
level=warn ts=2021-12-16T11:03:06.488580513Z caller=grpc_logging.go:38 duration=4.71080502s method=/logproto.Querier/GetChunkIDs err="rpc error: code = Unavailable desc = error reading from server: read tcp 127.
0.0.1:59894->127.0.0.1:9095: use of closed network connection" msg="gRPC\n"
level=info ts=2021-12-16T11:03:06.488919099Z caller=metrics.go:92 org_id=fake latency=fast query="{metric=\"cortex_chunk_store_chunks_per_query_bucket\"}" query_type=limited range_type=range length=1h0m0s step=2
s duration=4.719388797s status=500 limit=1000 returned_lines=0 throughput=15kB total_bytes=69kB
level=warn ts=2021-12-16T11:03:06.489698691Z caller=logging.go:72 traceID=12c1795b73e00f46 orgID=fake msg="GET /loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=%7Bmetric%3D%22cortex_chunk_store_chunk
s_per_query_bucket%22%7D&start=1639648974942000000&end=1639652574942000000&step=2 (500) 11.536451883s Response: \"rpc error: code = Unavailable desc = error reading from server: read tcp 127.0.0.1:59894->127.0.0
.1:9095: use of closed network connection\\n\" ws: false; Accept: application/json, text/plain, */*; Accept-Encoding: gzip, deflate, br; Accept-Language: en-US,en;q=0.9,pt-BR;q=0.8,pt;q=0.7; Dnt: 1; Sec-Ch-Ua: \
" Not A;Brand\";v=\"99\", \"Chromium\";v=\"96\", \"Google Chrome\";v=\"96\"; Sec-Ch-Ua-Mobile: ?0; Sec-Ch-Ua-Platform: \"Linux\"; Sec-Fetch-Dest: empty; Sec-Fetch-Mode: cors; Sec-Fetch-Site: same-origin; User-Ag
ent: Grafana/8.2.0; X-Forwarded-For: 172.26.0.1, 172.26.0.1; X-Grafana-Org-Id: 1; "
```

**Expected behavior**
Expected the query to return just fine

**Environment:**
Local

**Screenshots, Promtail config, or terminal output**
Using `cmd/loki/loki-local-config.yaml`

**Comment by smoos** [comment]
As of v2.7.4 this is still a thing!

**Comment by DylanGuedes** [comment]
> As of v2.7.4 this is still a thing!

Tbh I just decided to not work on this because it is a misusage. There's no reason to run Loki with `target=read,write`.

**Comment by smoos** [comment]
> > As of v2.7.4 this is still a thing!
> 
> Tbh I just decided to not work on this because it is a misusage. There's no reason to run Loki with `target=read,write`.

Hey @DylanGuedes,

thanks for your answer! This leads me to the question, which mode(s) shall I use then? I guess, either "all" or completely as microservices setup? Additionally, would you advise to run, say 5 instances with `target=all`?

Thanks in advance,
sincerely
Sebastian

**Comment by DylanGuedes** [comment]
> > > As of v2.7.4 this is still a thing!
> > 
> > 
> > Tbh I just decided to not work on this because it is a misusage. There's no reason to run Loki with `target=read,write`.
> 
> Hey @DylanGuedes,
> 
> thanks for your answer! This leads me to the question, which mode(s) shall I use then? I guess, either "all" or completely as microservices setup? Additionally, would you advise to run, say 5 instances with `target=all`?
> 
> Thanks in advance, sincerely Sebastian

Sorry, my message was misleading: you should absolutely use the SSD mode (read, write targets), what I meant there is that you should run separate nodes with `target=read` and separate nodes with `target=write`. Ex, let's say you have 9 nodes: you select 6 of them to run `target=read` and 3 of them to run `target=write`. I don't recommend running all 9 of them with `target=write,read` though.

If that sounds confusing let me know, I can elaborate more.

**Comment by smoos** [comment]
No, the problem is entirely on my side. I'm currently trying to run 3 instances with `target:read` and 3 with `target:write`.

When I want to attach a grafana datasource to the read instances, it's failing with an error message about `logproto.Querier` not implemented (or similar). When switching the `target:read` to `target:all` it's working properly. 

My hypothesis therefor is, that some microservice, that is needed for serving to grafana datasources, is not started with `target:read`.

My bad for highjacking this old thread. Would you like me to open up a new issue, where I can additionally show my config and logs?

PS: The setup works fine for me, I just use the `target:all` instances as if they are `target:read` instances. But I'm wondering, if some really bad thingsTM might happen in the long run.

**Comment by DylanGuedes** [comment]
> No, the problem is entirely on my side. I'm currently trying to run 3 instances with `target:read` and 3 with `target:write`.
> 
> When I want to attach a grafana datasource to the read instances, it's failing with an error message about `logproto.Querier` not implemented (or similar). When switching the `target:read` to `target:all` it's working properly.
> 
> My hypothesis therefor is, that some microservice, that is needed for serving to grafana datasources, is not started with `target:read`.
> 
> My bad for highjacking this old thread. Would you like me to open up a new issue, where I can additionally show my config and logs?
> 
> PS: The setup works fine for me, I just use the `target:all` instances as if they are `target:read` instances. But I'm wondering, if some really bad thingsTM might happen in the long run.

just checking we're on the same page: your 3 instances running target=read are not the same as the 3 instances running target=write, right? If so: that's the problem; you have to either have an instance running target=read or target=write, you can't run both targets on the same instance. Explanation:

- Read target implements read proto interface/calls
- Write target implements write proto interface/calls

If a write target receives a query, since it doesn't implement the read proto/interface calls, it fails.

When you run a target with `-target=read,write` which proto handler will receive a request isn't necessarily the one you're expecting. You can have writes being received by the read target or queries being received by the write target. Both are problematic tbh. Solution is: use only `-target=read` or either `-target=write` on each instance OR use `-target=all`.

**Comment by smoos** [comment]
Thanks for the Explanation. I'm working with different instances.

I feel like this is the wrong thread to discuss this topic further. I'll open up a new issue, where I can provide more insight, config settings and such for example.

**Comment by DylanGuedes** [comment]
> Thanks for the Explanation. I'm working with different instances.
> 
> I feel like this is the wrong thread to discuss this topic further. I'll open up a new issue, where I can provide more insight, config settings and such for example.

yep let's discuss it there. but fyi: i think you're having your reads being routed to your write instances. so maybe a misconfigured kubernetes service, or nginx proxy, or something in that regards
