### ISSUE TITLE
Unable to install logstash-output-loki on Logstash 7.16.2

### ISSUE THREAD

**Issue by noel-rapido** [grafana/loki#4986]
**Description**
Trying to install logstash-output-loki on Logstash 7.16.2 is not possible anymore
Installation fails with error messages

This seems to be because of the version of logstash-codec-plain, that comes with Logstash

**To Reproduce**
1. Install logstash 7.16.2
2. try installing logstash-output-loki with `logstash-plugin install logstash-output-loki`

**Expected behavior**
Installation of the plugin would happen.

**Environment:**
Regardless

**Screenshots, Promtail config, or terminal output**
Terminal Output:
```bash
root@b107a7bb6821:/usr/share/logstash/bin# ./logstash-plugin install logstash-output-loki
```
```text
Using bundled JDK: /usr/share/logstash/jdk
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Validating logstash-output-loki
Resolving mixin dependencies
Installing logstash-output-loki
Plugin version conflict, aborting
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "logstash-codec-plain":
  In snapshot (Gemfile.lock):
    logstash-codec-plain (= 3.1.0)

  In Gemfile:
    logstash-codec-plain

    logstash-input-beats was resolved to 6.2.4, which depends on
      logstash-codec-plain

    logstash-input-jms was resolved to 3.1.2, which depends on
      logstash-codec-plain (~> 3.0)

    logstash-output-loki was resolved to 1.0.3, which depends on
      logstash-codec-plain (= 3.0.6)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

**Comment by noel-rapido** [comment]
Please ignore, I was able to resolve this by installing the `logstash-codec-plain (= 3.0.6)` plugin and installing the loki package.

**Comment by sschroed99** [comment]
How did you get around removing logstash-code-plain version 3.1.0 before installing 3.0.6?
