### ISSUE TITLE
Add regex label selection to pack stage to allow packing whole groups of labels

### ISSUE THREAD

**Issue by frittentheke** [grafana/loki#4987]
**Is your feature request related to a problem? Please describe.**
While it's possible to apply regex matching during relabeling (https://grafana.com/docs/loki/latest/clients/promtail/scraping/#relabeling) to rename a group of metadata labels (e.g. `__meta_kubernetes_*` or `__journal_*`) in order from them to be kept, this configuration approach is not yet possible for the pack stage.

Currently the pack stage (https://github.com/grafana/loki/pull/3401) only accepts a static list of labels via the `labels` option for them to be packed into the message. (https://grafana.com/docs/loki/latest/clients/promtail/stages/pack/#pack-stage-schema).  To copy all metadata from e.g. `__kubernetes`, it's required to know, provide and maintain the full list of all those labels in order for them to be packed with the message.

Also when extracting / parsing a nice set of all prefixed labels  (e.g. `myprefix_`) which can then just all be packed into the message with no additional configuration for each new label would be a great addition.

**Describe the solution you'd like**

Add support for regex pattern, just like for relabeling (https://grafana.com/docs/loki/latest/clients/promtail/scraping/#relabeling) to allow flexible selection of groups of labels and their sub-strings. This should work like with the labelmap action (relabeling):

```
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
```

**Describe alternatives you've considered**
-

**Additional context**
It might make sense to align this capability for the `labeldrop` and `labelkeep` stages as well.

**Comment by Daniel-Vaz** [comment]
I also have a need for this feature. 
Is there any workaround ?
