### ISSUE TITLE
Scale out single binary mode

### ISSUE THREAD

**Issue by gouthamve** [grafana/loki#50]
Currently the `all-in-one` (run locally) mode requires no `X-Scope-OrgID` header. I am not sure if that could be the case for the distributed mode too. Most users of Loki won't need multi-tenancy and not having a gateway would help.

**Comment by dawidmalina** [comment]
Any update on this topic? Is it now possible to scale single binary (helm) setup into multiple replicas? Looks like different ring configs can be provided: https://github.com/sboschman/loki/blob/master/production/helm/loki/values.yaml#L33

**Comment by slim-bean** [comment]
We are most of the way to being able to support this, I think it needs better documentation and some testing.

**Comment by unitto1** [comment]
any updates here?)

**Comment by PixelBumper** [comment]
We would be interested in helping out testing this :)
