### ISSUE TITLE
Loki helm chart not working as dependency: Error: can't get a valid version for repositories loki-stack. Try changing the version constraint in Chart.yaml

### ISSUE THREAD

**Issue by 938633** [grafana/loki#5000]
Hi,

Loki helm chart is working when I am manually pulling and installing but not when I am including it as a sub chart.
Below is the configuration I am using in my Chart.yaml. Please let me know how can I get it to work.

``dependencies:
- name:  loki-stack
  version: "2.5.0"
  repository: https://grafana.github.io/loki/charts
  condition: `loki-stack.enabled``

**Comment by leozz705** [comment]
版本应该是 version: "2.0.0" 吧～

**Comment by 938633** [comment]
@leozz705 Thanks. It worked for 2.0.0. How can I make it work with the latest version - 2.5.0?
