### ISSUE TITLE
hello~everyone! 请问loki的logql查询使用问题

### ISSUE THREAD

**Issue by leozz705** [grafana/loki#5002]
loki的logql怎么查询某个关键字后面的数字大于1 and 查询大于1的条数？
或者某一列的值大于1 和 查询大于1的条数？

**Comment by liguozhong** [comment]
{pod=~".*center.*"} |="total points" | regexp "([^s]+).*total points: (?P<rt>.*) time series.*" | rt >1000

![image](https://user-images.githubusercontent.com/9583245/148678649-3ca17f1b-4475-4989-bbff-839d397e3ea1.png)

**Comment by leozz705** [comment]
多谢～
