### ISSUE TITLE
syslog headers or meta tags as promtail lables. 

### ISSUE THREAD

**Issue by vaibhavt19** [grafana/loki#5019]
Syslog MSGHDR or SDATA.meta as label on promtail. 
We are adding some custom headers on syslog messages and currently parsing it to Graylog, All these headers are available for Query in Graylog right now. 
We are trying to translate these headers to promtail labels but after reading the documentation didn't find any clue. 
Syslog config
`rewrite r_add_aws_region { set("us-east-1" value(".SDATA.meta.aws_region")); };
log { source(s_src);
       rewrite (r_add_aws_region);
       destination(d_net);
 };
`

Graylog reference screenshot, 
All are the services and region fields are meta tags or headers. 
![image](https://user-images.githubusercontent.com/47231265/147722376-fe24f8c9-5524-4b9a-80f7-26aa69e23e28.png)

**Comment by chaudum** [comment]
Hey @vaibhavt19 

I think what you are looking for is relabelling the internal labels that Promtail generates when receiving syslog messages, such as

`__syslog_message_<HEADER>`
and
`__syslog_message_sd_<ID>_<KEY>` for structured data fields

You can find documentation about the available internal labels here: https://grafana.com/docs/loki/latest/clients/promtail/scraping/#syslog-receiver

**Comment by chaudum** [comment]
Still valid.
