### ISSUE TITLE
Allow additional args to be passed to the Loki container with Helm

### ISSUE THREAD

**Issue by sboschman** [grafana/loki#502]
**Is your feature request related to a problem? Please describe.**
Not all Loki settings are part of the config file. Most should be imo, but being able to pass them as extra args is a temporarily workaround. As far as I can tell though, the log level has always to be set with container args.

**Describe the solution you'd like**
Allow extra container args to be passed to the Helm chart of Loki.

**Describe alternatives you've considered**
Alternative would be to have a dedicated log level value. This is less flexible for whatever other args Loki supports which are not part of the config file.

**Comment by Kuqd** [comment]
Thank you @sboschman for this !
