### ISSUE TITLE
Vulnerabilities found by new AWS ECR enhanced image scanner (Grafana 8.3.2)

### ISSUE THREAD

**Issue by fatbasstard** [grafana/loki#5030]
Hi,

Just enabled the new ["Enhanced image scanning"](https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-scanning-enhanced.html) in AWS and ran it against our Grafana docker image. Multiple findings found:

```
    "imageScanFindings": {
        "imageScanCompletedAt": "2021-12-17T13:45:13.357000+01:00",
        "vulnerabilitySourceUpdatedAt": "2021-12-17T13:45:13.357000+01:00",
        "findingSeverityCounts": {
            "HIGH": 47,
            "MEDIUM": 48,
            "LOW": 1,
            "UNTRIAGED": 1,
            "CRITICAL": 3
        }
    }
}
```

Screenshot from the Console:
![image](https://user-images.githubusercontent.com/35613489/146548703-8b256989-5670-4cac-b49f-4f55deecdeaa.png)

Slightly related to https://github.com/grafana/grafana/issues/41063

Plugins installed on the image:
* genty-flowcharting-panel
* grafana-clock-panel
* simpod-json-datasource 
* natel-discrete-panel
* isaozler-paretochart-panel 
* ae3e-plotly-panel 
* grafana-image-renderer

**Comment by zuchka** [comment]
thank you! transferred this issue to the Loki repo so they can ack those two security issues 👍

**Comment by fatbasstard** [comment]
The 2 Loki issues still present in `8.3.6`
