### ISSUE TITLE
Add readiness handlers to distributor and querier modules

### ISSUE THREAD

**Issue by sboschman** [grafana/loki#504]
**Is your feature request related to a problem? Please describe.**
Currently only the ingester has a readiness handler (https://github.com/grafana/loki/blob/master/pkg/loki/modules.go#L148). If you deploy the three Loki components (distributor, ingester and querier) separately not all of them have a readiness handler to use as Kubernetes readiness/liveness probe paths. For the querier the path `/api/prom/label` could be used as readiness/liveness path. The readiness/liveness probes for the distributor had to be disabled though.

**Describe the solution you'd like**
Separate ready handlers for all three modules.

**Comment by jan25** [comment]
@Kuqd would you know if someone is already working on this? Otherwise i'm happy to take a look

**Comment by Kuqd** [comment]
Nobody is feel free to take it.

**Comment by adityacs** [comment]
@cyriltovena I would like to take this.

**Comment by jan25** [comment]
@adityacs I couldn't work on this. Go ahead!

**Comment by cyriltovena** [comment]
Please do ! I pinned the issue because we need this rather sooner than later.
