### ISSUE TITLE
Parse a windows event that contains JSON

### ISSUE THREAD

**Issue by hugosxm** [grafana/loki#5046]
Hi,

i use loki to store logs of a windows machine, logs are shipped with promtail with the event_logs scrap config. I understood that promtail serialize events to json, my problem is that the data field of my event contains JSON like so : 

`	
{"User_Name":"a.xxx","User_Type":"Advanced","Design_Formulary":"System_Settings","Design_Group_1":"Settings","Design_Group_2":"Motion_Adjustment","Design_Group_3":"","Event":"Tool_Lenght","Old_Value":"250_mm","New_Value":"150_mm"}`

Every "field" of the event is detected by loki as a "detected field", i would like that every field of my data is detected too, is this possible ?

I tried a json pipeline, with no succes.  Can someone provide help on this please ?

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
