### ISSUE TITLE
Passing Loki 'target' in config yaml requires number

### ISSUE THREAD

**Issue by sboschman** [grafana/loki#505]
**Describe the bug**
Deploying the distributor, ingester and querier separately with Helm using the config yaml requires the numeric identifier instead of the name.

```
config:
 target: 3
```

The '3' is the number for the distributor from the iota const definition in https://github.com/grafana/loki/blob/master/pkg/loki/modules.go#L25

Using args to supply the target one can use the module names, snippet taken from the ksonnet config:
```
  distributor_args::
   $._config.commonArgs {
     target: 'distributor',
   },
```

**Expected behavior**
Being able to use the names in the config yaml to specify the target, e.g.:
```
config:
  target: distributor
```

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Comment by daixiang0** [comment]
Not only in helm chart indeed, ksnnet still use '3' but it convert in below files:
```
ksonnet/loki/distributor.libsonnet:7:      target: 'distributor',
ksonnet/loki/ingester.libsonnet:6:      target: 'ingester',
ksonnet/loki/querier.libsonnet:6:      target: 'querier',
```
As you seen in distributor.libsonnet:
```
  distributor_deployment:
    deployment.new('distributor', 3, [$.distributor_container]) +  <===
```

In fact, there are lots of difference between helm and ksonnet, some features missed in helm which i am working on it.

**Comment by yaminisridaran** [comment]
Hi. I am new to Grafana Loki project. I would like to contribute to fix this bug.I have experience in working in helm. How can I start contributing?
