### ISSUE TITLE
unexpected IDENTIFIER when I using replace

### ISSUE THREAD

**Issue by lesomora** [grafana/loki#5055]
This is my query: 

{env="zabbix"} | logfmt | line_format "{{.value | replace ": " "="}}"

That is my string: 

ERROR: bad request Queues: /server_status ID: XXXXX Name: XXXXX stay for XXXX minutes in installation

I want replace ":" for "="

The expectation is turn those values "name:message" into a label

If I using ToLower that function works, but when I using some function who remove or insert some caracter on string... I got this error:

parse error at line 1, col 60: syntax error: unexpected IDENTIFIER

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.

**Comment by dannykopping** [comment]
You should avoid using double quotes within double quotes:

`line_format "{{.value | replace ": " "="}}"`

I believe that's what's causing your issue. If that doesn't help, please reach out in one of the channels listed above.
