### ISSUE TITLE
error happen when I deploy loki in aws eks: failed parsing config: /etc/loki/loki.yaml: parsing time

### ISSUE THREAD

**Issue by hepyu** [grafana/loki#5058]
the loki pod couldn't be deployed in aws eks, how to solve this error?
![image](https://user-images.githubusercontent.com/3917749/148329294-7cdc72c6-8ca6-4c6c-b9b8-eab989c6bd65.png)

**Comment by hepyu** [comment]
version:
loki-chart-version: 2.1.1
loki-image version: v2.0.0

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
