### ISSUE TITLE
Loki 2.4.1/Loki-stack 2.5.1: count_over_time leads to no-data instead of 0

### ISSUE THREAD

**Issue by mncod1ng** [grafana/loki#5074]
**Bug description**
The following LogQL-query 

`count_over_time({app="foo"} |= "bar" [$__range])` 

returns nil ("no data") instead of the (correct) number 0 when the filtered stream represents an empty set of log events. In consequence, further calculations/operations on "no data" like taking sums or differences fail and result in "no data" as well. To my knowledge, right now, there is no acceptable solution how to solve that problem. (e.g. adding a grafana transformation +0 prevents the user from adding alerts and so on)

**Steps to reproduce**
1. Loki: 2.4.1. Grafana: 8.1.6. (We use loki-stack 2.5.1)
3. Query: `count_over_time({app="foo"} |= "bar" [$__range])` where the filter results in an empty set of log events.

**Expected behavior**
Functions like count_over_time (and perhaps also other functions) should return 0 (instead of nil) when applied to an empty set of log events.

Justification: You cannot define well-formed calculations between two kinds of log events counts A and B, e.g. "number of incoming request - number of sucess responses" because every time there is "no data" for B the calculation "A  - B" results in "no data" even when A has a numeric count value.

**Environment:**
 - Infrastructure: Managed kubernetes cluster
 - Deployment tool (for loki-stack): helm

**Further Information**

- There was a report on a related bug [Issue #4420](https://github.com/grafana/loki/issues/4420). Which was apparently solved with [Commits · grafana/loki](https://github.com/grafana/loki/commits/v2.4.1?after=f61a4d2612d8fa3a385c90c363301ec05bab34d8+104&branch=v2.4.1) in a pull request on 12th of october 2021 and is integrated in Loki 2.4.1. But note please, that it did not solve the problem described here.
- Finally, we managed to find an ugly workaround for the bug. My colleague posted it on your forums ([workaround](https://community.grafana.com/t/xx-over-time-leads-to-no-data-no-calculations-operations-possible-please-help/58597)). Clearly, it's not user-friendly and not really intuitive, so this issue here still needs a fix. But maybe it helps you to find a solution for the problem.

**Comment by mncofinpro** [comment]
Finally, we managed to find an ugly workaround for the bug. My colleague posted it on your forums ([workaround](https://community.grafana.com/t/xx-over-time-leads-to-no-data-no-calculations-operations-possible-please-help/58597)). Clearly, it's not user-friendly and not really intuitive, so this issue here still needs a fix. But maybe it helps you to find a solution for the problem.

**Comment by tobernguyen** [comment]
I'm experiencing the same behavior for the `rate` query.

**Comment by clouedoc** [comment]
@mncofinpro's workaround works fine for me. Thanks 👍

**Comment by tobernguyen** [comment]
I am still having this issue

**Comment by carsten-gengel** [comment]
still relevant

**Comment by waterdrop01** [comment]
the suggested workaround doesn't work for me.

I'm not 100% sure this should be solved on the loki side, so I cross-posted the issue in the grafana repo => https://github.com/grafana/grafana/issues/48616

Would love to have someone share what is the recommended way to replace "no data" by "0" in Grafana dashboard using a loki datasource.

**Comment by carsten-gengel** [comment]
hi waterdrop01,
the workaround works as following:
you have a query, that returns "no data"
for example:
```
sum(count_over_time(
 {app="controller"} 
 |= "here is my incoming event"
 [$__range]))
```
by adding 

```
or
 sum(count_over_time({app="controller"} 
 [$__range])) * 0
```
you create data ($range must be big enough to at least fetch data. so maybe just use 24h as entry) at first that you just throw away with "*0"
 that leads to the final query:
```
(
 sum(count_over_time(
 {app="controller"} 
 |= "here is my incoming event"
 [$__range]))
 or
 sum(count_over_time({app="controller"} 
 [24h])) * 0
)
```
if you have multiple single xx_over_time in one  single request it has to be done for each one of them.
It's not beautiful but at least it works.
hope that helped to understand the underlying problem

**Comment by waterdrop01** [comment]
> hi waterdrop01, the workaround works as following: you have a query, that returns "no data" for example:
> 
> ```
> sum(count_over_time(
>  {app="controller"} 
>  |= "here is my incoming event"
>  [$__range]))
> ```
> 
> by adding
> 
> ```
> or
>  sum(count_over_time({app="controller"} 
>  [$__range])) * 0
> ```
> 
> you create data ($range must be big enough to at least fetch data. so maybe just use 24h as entry) at first that you just throw away with "*0" that leads to the final query:
> 
> ```
> (
>  sum(count_over_time(
>  {app="controller"} 
>  |= "here is my incoming event"
>  [$__range]))
>  or
>  sum(count_over_time({app="controller"} 
>  [24h])) * 0
> )
> ```
> 
> if you have multiple xx_over_time in one single request it has to be done for each one of them. It's not beautiful but at least it works. hope that helped to understand the underlying problem

thanks @carsten-gengel, it works perfectly. Didn't get the trick was that the second query had to return anything but "no data".

**Comment by svennergr** [comment]
Hi folks,

with Loki 2.7 we support `vector(0)` functions:

```
sum(count_over_time({namespace="traefik"}[5m])) # will return nothing
  or
vector(0) # will return 0
```

https://grafana.com/docs/loki/latest/logql/metric_queries/#functions

**Comment by clouedoc** [comment]
Awesome, thank you 💪
