### ISSUE TITLE
How to use  dynamic tenant in logstash output Loki ？

### ISSUE THREAD

**Issue by songyanping** [grafana/loki#5082]
Hello, we want to replace es with Loki. The previous architecture is filebeat, Kafka, logstash, es. We have made the following changes:

1. Logstash install the output Loki plug-in

2. In logstash, change output to

`      filter {
          mutate {
            add_field => {
              "application" => "kpi-%{app_name}"
            }
          }

      }

      output {
        loki {
          url => "http://loki-distributed-gateway.loki.svc.cluster.local/loki/api/v1/push"
          tenant_id => "%{application}"
          batch_wait => 1
          retries => 3
        }`

3. I want to use filter application field as tenant id, but it doesn't work.

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.

**Comment by HelonLee135** [comment]
Is anyone else following this? I'm following what the tier above says and it still doesn't work, when I click test in grafana it says: Data source connected, but no labels received. Verify that Loki and Promtail is configured properly.
