### ISSUE TITLE
Allow saving line_format as reusable logql operators

### ISSUE THREAD

**Issue by hterik** [grafana/loki#5084]
**Is your feature request related to a problem? Please describe.**
A lot of structural logs are really hard to read by humans, especially json based. Some of them more or less require a well written `line_format`.
For some examples of problematic data, see https://github.com/grafana/loki/issues/4249 https://github.com/grafana/loki/issues/4402 or https://github.com/grafana/grafana/issues/31481, which all got solved by clunky `line_format` workaround in the end.
One of the examples have this as proposed solution: :face_with_spiral_eyes: 
```
query
  | pattern `<_entry>`
  | json
  | line_format "{{ .msg }} {{ range $k, $v := (fromJson ._entry) }}{{ if not (eq $k \"t\" \"msg\") }}{{ $k }}={{ $v }} {{ end }}{{ end }}"
```
Writing this line_format by hand every time you open the explore panel is not feasible. Exploring logs via pre-made dashboards in Grafana isn't always as straightforward as it is for time series, logs are often more exploratory and require changing the filters. So storing it into a reusable function would help a lot 

**Describe the solution you'd like**
Allow storing this line_format inside Grafana or Loki to allow easy reuse in the explore panel, how and where this should be stored i haven't thought about. Above example would end up as this instead:
```
query
  | pattern `<_entry>`
  | json
  | my_json_repack_format
```
Taking it further, one could perhaps store not only the line_format but a whole chain of logql-operations as a custom operator. There is also open question of allowing parameters or not.

**Describe alternatives you've considered**
Honestly all the issues linked above have better proposed alternatives to this, especially tabular output. If they are too much work, this could be an intermediate simpler solution.

**Comment by cyriltovena** [comment]
Sounds like I also thought about this at some point.

See this proposal https://docs.google.com/document/d/1FXtvunqzDq6MVR5VmZfLhR872sahUocmmg68hPS1K0I/edit it never really got enough traction.

I'm hesitant still as of today, may be this can be solved by having a better way to switch between json and human readable format, but you have a special case where you want to remove msg, other people might have this key name differently or just not existing.

By the way the first pattern won't be required soon once https://github.com/grafana/loki/pull/4879 is merged. But that's doesn't really solve it the problem of complex template that can be reusable.

I also thought about leaving this for Grafana /cc @davkal @aocenas @ivanahuckova 

I'm open for the discussion.

**Comment by aocenas** [comment]
There are definitely possibilities inside Grafana. We could have this in config where you could specify random query snippets or pipeline steps and then reference them in query. This could be pretty neat once we have a visual editor as that would give you sort of reusable query blocks. @torkelo worked on visual editor (prom+loki) so he could have some ideas too.

**Comment by ivanahuckova** [comment]
I am wondering, if this wouldn't be solved by query history, more specifically shared history across whole org where you could star your/others queries (and therefore patterns) that you would like to reuse in the future?

**Comment by davkal** [comment]
Starred query history items could work, as you run an old query and tweak that. But it's still just a workaround.

An integration with the upcoming query builders seems more obvious, but at the same time, the line format patterns seem kind of custom. So perhaps they need saving somewhere. @torkelo demoed a query builder that has a "query patterns" menu to effectively get you started with partial queries, but those are mostly hard-coded. 

Traditionally these macros could be done via template variables, but this issue is concretely about Explore; so we could expose the upcoming global template variables in Explore and solve it that way. 

I'm hesitant to build anything that relies on Loki's own API into Grafana, unless there are other datasources that expose similar variables via their API.

**Comment by hterik** [comment]
Bump stale.
