### ISSUE TITLE
loki-canary msg="Error from iterator" err="reached tail max duration limit"

### ISSUE THREAD

**Issue by nvtkaszpir** [grafana/loki#5086]
**Describe the bug**
loki-canary throws in logs `msg="Error from iterator" err="reached tail max duration limit"`
this repeats every 1 hour. See screesnhot below.

**To Reproduce**
1. Started Loki 2.4.1
2. Started loki-canary 2.4.1
3. look at loki-canary logs

**Expected behavior**
No errors reported

**Environment:**
 - Infrastructure: kubernetes 1.18
 - Deployment tool: helm chart grafana/loki-canary + tanka on defaults

**Screenshots, Promtail config, or terminal output**
we got 35 nodes

snapshot https://snapshot.raintank.io/dashboard/snapshot/lhr9VUJ4WmDAp26r49h50o7BjALSlys2?orgId=2

![image](https://user-images.githubusercontent.com/1480252/148745854-f1a43af0-8e9f-4b12-9226-1bc3214d919e.png)

**Comment by vlcinsky** [comment]
I bumped into the same message when using logcli to tail logs for longer period of time. According to logs below it was exactly one hour.

```
2022/12/16 23:55:09 wss://logs-prod-us-central1.grafana.net/loki/api/v1/tail?limit=30&query=%7Bcluster_id%3D%22rdstmc-cro%22%2C+service_name%3D%22%2Fttr%22%7D&start=1671227709008835757
2022/12/17 00:55:09 Error reading stream: websocket: close 1011 (internal server error): reached tail max duration limit
```

So if server logs contain such an error, it is likely to be the case. Probably there is somewhere a limit (in loki code, on some webserver participating in the service, ...) for max duration of the websocket connection.

**Comment by Starefossen** [comment]
Seeing this error myself, wondering if there is a timeout some where I can configure this 🤔

**Comment by d-afanasiev** [comment]
Hi all.
Has anyone found a solution to this problem? 
Or can we only increase the timeout using the `tail_max_duration` parameter, but the error remains?

**Comment by kamui-fin** [comment]
Is there any way to disable this timeout?
