### ISSUE TITLE
Flush queue logs/alerts

### ISSUE THREAD

**Issue by owen-d** [grafana/loki#5090]
When debugging a cluster which was relatively underprovisioned, I found that the ingesters couldn't flush data fast enough to keep up with the ingestion rate. I I propose we do the following:

- Add an alert to the mixin when the flush queue length (`cortex_ingester_flush_queue_length`) is continually increasing.
- Add log messages when this is over some threshold (50?)
- Increase the flush queue default concurrency.

We could also look at more sophisticated strategies such as an adaptive goroutine pool based on outstanding queue length.

**Comment by cyriltovena** [comment]
Add this in troubleshooting section too.
