### ISSUE TITLE
Rename scheduler metrics such as cortex_query_scheduler_queue_length to have loki related prefix

### ISSUE THREAD

**Issue by james-callahan** [grafana/loki#5094]
**Is your feature request related to a problem? Please describe.**
Currently the query-scheduler has metrics that start with `cortex_query_scheduler_`. This software is loki, not cortex.

**Describe the solution you'd like**
Change the prefix to e.g. `loki_query_scheduler_`.

**Additional context**
e.g. https://github.com/grafana/loki/blob/6ef934b24c695ed5a7872d212552265d82b303a7/pkg/scheduler/scheduler.go#L153

**Comment by jeschkies** [comment]
@james-callahan thanks for finding this. Would you mind creating a pull request with the change? That'd be awesome!

**Comment by james-callahan** [comment]
> @james-callahan thanks for finding this. Would you mind creating a pull request with the change? That'd be awesome!

https://github.com/grafana/loki/pull/5096
