### ISSUE TITLE
Develop a command line with 10 lines before and after the grep keyword, similar to the linux grep -C command and the less command

### ISSUE THREAD

**Issue by chenyi19851209** [grafana/loki#5095]
Hello, please ask 2 questions.
I want to develop a command line tool based on loki’s http api and logql, and want to achieve the following functions:

Search for the error keyword and its context, similar to the linux command ‘**grep -C 10 error a.log**’ . I know that logql has log line filter and http range query, but I don’t know how to find the 10 lines before and after it.
Search for the error keyword and support jump search. For example, after searching for the first error keyword, press the n key to jump to the next matching error keyword, and search for the 10 lines before and after the next error.like linux **less** command.
Thank you for your guidance

I found that the previous question asked by other people has not been answered for a long time, so I mention it here, please help to answer:
https://community.grafana.com/t/develop-a-command-line-with-10-lines-before-and-after-the-grep-keyword-similar-to-the-linux-grep-c-command-and-the-less-command/58819

**Comment by cyriltovena** [comment]
Once you have your result, you need to send a backward query with the first timestamp and limit of 10 and a forward query with the last timestamp and a limit of 10. If you want to focus on a single file make sure you correctly set the label selector for that files for all queries.

See the query range http API. https://grafana.com/docs/loki/latest/api/#get-lokiapiv1query_range

I suggest to play with it locally.

You should check out how Grafana does it for the show-context feature. They are firing up those queries.

**Comment by mariusz-stepien-roche** [comment]
So you're trying to replicate the "show-context" behavior in the CLI? For anyone finding this issue from google, I was searching for this feature in the grafana gui and this link would've been helpful here: https://grafana.com/blog/2019/08/14/new-in-grafana-v6.3-introducing-lokis-log-row-context-viewer/

**Comment by kwach** [comment]
+1

**Comment by acocamitiga** [comment]
+1

**Comment by Judith-Vorster** [comment]
+1.

Stalebot closed as 'completed'? Is this feature now available?

**Comment by nuwan89** [comment]
+1

**Comment by ujwalreddy1** [comment]
+1

**Comment by BouchaaraAdil** [comment]
+1

**Comment by Farrukhraz** [comment]
+1

**Comment by michielfbr** [comment]
+1
