### ISSUE TITLE
How to send alarm where a error line appears in log.

### ISSUE THREAD

**Issue by naughtyGitCat** [grafana/loki#511]
Or does Loki system support alarm error lines in log ?

Please ask questions you have in the mailing list: https://groups.google.com/forum/#!forum/lokiproject

Or join our #loki slack channel at http://slack.raintank.io/

**Comment by Kuqd** [comment]
Hello @naughtyGitCat ,

Not yet but we plan to integrate Prometheus metrics based on logs ingested, this could then trigger an alarm.

Thank you !

**Comment by tim-oak** [comment]
:+1:

IMO something similar to the alert rules in prometheus would be great!
and than the reuse of the alertmanger even (since alertmanager is probably installed already anyhow ...)

Looking froward, and thanks for this very nice piece of software so far!
