### ISSUE TITLE
Log retention configuration for loki is not working

### ISSUE THREAD

**Issue by priyanka1806** [grafana/loki#5116]
Hi, I have below configuration for grafana loki . I am expecting that the chunks will be deleted after every 24hrs. But it is not working as expected.

auth_enabled: false

server:
http_listen_port: 3100

ingester:
lifecycler:
address:
ring:
kvstore:
store: inmemory
replication_factor: 1
final_sleep: 0s
chunk_idle_period: 5m
chunk_retain_period: 30s

schema_config:
configs:

from: 2022-01-11
store: boltdb
object_store: filesystem
schema: v11
index:
prefix: index_
period: 24h
storage_config:
boltdb:
directory: /u01/app/grafana/loki/index

filesystem:
directory: /u01/app/grafana/loki/chunks

compactor:
working_directory: /u01/app/grafana/loki
shared_store: filesystem
compaction_interval: 10m
retention_enabled: true
retention_delete_delay: 1h
retention_delete_worker_count: 100

limits_config:
enforce_metric_name: false
reject_old_samples: true
reject_old_samples_max_age: 24h
retention_period: 24h

chunk_store_config:
max_look_back_period: 24h

table_manager:
retention_deletes_enabled: true
retention_period: 24h

Need help in fixing the log retention issue.

**Comment by fayas-akram** [comment]
@priyanka1806 Table_Manager is unnecessary if you are using a compactor. Also, I am facing the same issue which deletes logs not exactly 24 Hours. it Deletes logs after 2days or more ( some days ).
Not exactly sure!

**Comment by bmm-alc** [comment]
To understqnd why chunk are not deleted immediatly look to https://grafana.com/docs/loki/latest/operations/storage/table-manager/#retention

I think this bug should be closed and your question be asked on http://community.grafana.com

**Comment by fayas-akram** [comment]
Already Asked on slack community. People not sure about this

**Comment by cyriltovena** [comment]
Never tried the compactor on filesystem, it should work but may be it can find chunks can you share logs of the compactor ? If you're using single binary, I doubt the compactor is running by default which could be why it doesn't work. We could add the compactor to single binary.

**Comment by LinTechSo** [comment]
Hi. Iam facing same issue on distributed Loki version 2.6.0 with compactor enabled configuration.
any updates ?

**Comment by Codecaver** [comment]
same issue here， Loki version 2.5.0
