### ISSUE TITLE
Can Elasticsearch(with logs and traces) be used to correlate LOGS+METRICS+TRACES ?

### ISSUE THREAD

**Issue by pkrishnanreflexion** [grafana/loki#5117]
We are having an existing system pushing logs and traces to Elasticsearch.
Do we essentially need loki, tempo and prometheus to correlate between logs traces and metrics?
Do we have to export legacy data to loki/tempo in order to correlate?

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
