### ISSUE TITLE
Docs: Fix wrong and missing common configuration section descriptions

### ISSUE THREAD

**Issue by DylanGuedes** [grafana/loki#5119]
**Describe the bug**
Bug 1: `path_prefix` configuration from the `common` section is wrongly describing it as `When defined, the given prefix will be present in front of the endpoint paths.`, when it is used to compose file paths to read/write from. 
Bug 2: Both, `chunks_directory` and `rules_directory` (also from the common section) aren't documented

**To Reproduce**
N/A

**Expected behavior**
N/A

**Environment:**
N/A

**Screenshots, Promtail config, or terminal output**
N/A

**Comment by darxriggs** [comment]
This should not be closed.
