### ISSUE TITLE
Loki Ruler to allow directory structures and glob patterns

### ISSUE THREAD

**Issue by davidbhoward** [grafana/loki#5142]
We have a need for Loki Ruler to be able to use a directory hierarchy and recursive glob patterns for rule files.  With a large organization, who has many rule files, a single directory can get messy and hard to manage.  

A couple of examples of this would be you could have a folder per team or a folder per data center based upon your needs.  You can see the benefit from an organizational perspective.

This already exists within Thanos Ruler (via --rule-file) and Prometheus (via rule_files:) and we would like to see this ability within Loki Ruler as well.  

For Thanos Ruler, we have one example of this being done to manage many levels of directories but requires the same argument multiple times.  However, in this example, you can see that it doesn't support recursive globs, which would simplify this configuration significantly.  

```
    --rule-file=/repos/data/giraffe-alerts/rules/*/global/*.yaml  \
    --rule-file=/repos/data/giraffe-alerts/rules/*/$DC/*.yaml  \
    --rule-file=/repos/data/giraffe-alerts/rules/*/global/*/*.yaml  \
    --rule-file=/repos/data/giraffe-alerts/rules/*/$DC/*/*.yaml  \
    --rule-file=/repos/data/giraffe-alerts/rules/*/global/*/*/*.yaml  \
    --rule-file=/repos/data/giraffe-alerts/rules/*/$DC/*/*/*.yaml  \
    --rule-file=/repos/data/giraffe-alerts/rules/*/global/*/*/*/*.yaml  \
    --rule-file=/repos/data/giraffe-alerts/rules/*/$DC/*/*/*/*.yaml  \
    --rule-file=/repos/data/giraffe-alerts/rules/*/global/*/*/*/*/*.yaml  \
    --rule-file=/repos/data/giraffe-alerts/rules/*/$DC/*/*/*/*/*.yaml  \
```

**Comment by owen-d** [comment]
Linking https://grafana.com/docs/loki/latest/rules/#ruler-storage in case you haven't seen it yet.

Loki has the concept of _tenancy_ built in, whereas Prometheus does not and Thanos does it via labels if I recall correctly. For us, this means we first off partition by tenant, creating a structure like (using the file system backend here for simplicity):
```
<loki_rules_config_path>/<tenant id>/rule_group_1.yaml
                                    /rule_group_2.yaml
```
Rule groups are the _atom_ here. They're always scheduled on a single ruler and the rules within each group are run in order with respect to each other. Specifying multiple rule groups lets the ruler replicas shard them across each other as a way to horizontally scale.

Anyways, back to your issue. If you're using the file system backend, you should be able to mount the configurations based on the `<tenant>/<rule_group>.yaml` form, like

```
app_team_tenant/rules.yaml
app_team_tenant/rules2.yaml
platform_tenant/rules1.yaml
platform_tenant/rules2.yaml
...etc
```

We _need_ to greatly improve the ease of understanding this with better docs; thanks for sticking with it!

**Comment by davidbhoward** [comment]
Thanks for your response, @owen-d.  Thank you for the link.  I have read through that along with doing some of my own testing to see what the behavior is.  What you describe above makes sense.  

My understanding is that Grafana doesn't support users being part of multiple orgs/tenants and being able to query across them.  I could be wrong here, so if I am, please let me know.

Our structure is that everyone will be part of a main org/tenant, but there will be a subset that will be part of a different org/tenant.  If this really isn't well supported on the Grafana side, we will need to first focus on the main org/tenant that everyone will have access to.  This means that everything will live under the `fake` tenant until that is supported on the Grafana side.  This is why everything for us will live in a single directory, where the concern comes up and directory and glob patterns are needed.  I can provide more details if this isn't making sense.  Thanks again for your response here.  

We really appreciate all the work that is being done on Loki and so far things look promising for us.
