### ISSUE TITLE
response larger than the max message size

### ISSUE THREAD

**Issue by qudonghui** [grafana/loki#5143]
Hi:
  When I query the log, I find the following error prompt
![image](https://user-images.githubusercontent.com/39752827/149491152-0328b2fe-865b-43c1-a3e8-071a1bf01110.png)
I tried to modify all the configurations including 16777216, but still didn't work
![image](https://user-images.githubusercontent.com/39752827/149491458-da9748dd-c2e2-4c37-87ee-de5a1998b3f5.png)

**Comment by pgassmann** [comment]
in the message `105093682 vs 16777216` on the left is the size of the response and on the right is the limit.

your new limit `104857600` is still smaller than 105093682

you can also reduce the timespan. What range did you query?

**Comment by qudonghui** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by pgassmann** [comment]
@qudonghui check if you can see from the loki logs which component is hitting a limit.

also check some other limits from this issue: https://github.com/grafana/loki/issues/4613#issuecomment-1018367471

do you really have / want / need such high amounts of logs. with 32mb per second allowed, that's up to 9,6 GB of logs in 5 min.
compared to that, 15 or 100mb limits seem small.

**Comment by qudonghui** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by HL230606** [comment]
for loki:2.5.0
<img width="1123" alt="image" src="https://github.com/grafana/loki/assets/23731971/b09dfcec-546d-4921-a17c-cc2ece0b1720">

**Comment by a-pattani** [comment]
Anyone was able to resolve this issue? What changes should be done? I am facing this issue.
