### ISSUE TITLE
`-print-config-stderr` and `-log-config-reverse-order` fail if env substitution is used

### ISSUE THREAD

**Issue by chaudum** [grafana/loki#5156]
**Describe the bug**
If the configuration file uses [env substitution](https://grafana.com/docs/loki/latest/configuration/#use-environment-variables-in-the-configuration) Loki fails to start if the CLI arguments `-print-config-stderr` or `-log-config-reverse-order` are provided.

**Steps to reproduce**

1. Use env substitution in config file, e.g.
   ```
   server:
     http_listen_port: ${LOKI_PORT:-3100}
   ```
2. Start Loki (`main-f884f2b82`) with env variable LOKI_PORT set and argument `-print-config-stderr` or `-log-config-reverse-order`

**Expected behaviour**
Loki applies env substitution and prints/logs config.

**Actual behaviour**

Loki fails to start:

```console
$ LOKI_PORT=3100 ./cmd/loki/loki -config.file=config.yaml -log-config-reverse-order
failed parsing config: config.yaml: yaml: unmarshal errors:
  line 4: cannot unmarshal !!str `${LOKI_...` into int

$ LOKI_PORT=3100 ./cmd/loki/loki -config.file=config.yaml -print-config-stderr     
failed parsing config: config.yaml: yaml: unmarshal errors:
  line 4: cannot unmarshal !!str `${LOKI_...` into int
```

**Comment by dannykopping** [comment]
What happens if you add the `-config.expand-env=true` flag?

**Comment by chaudum** [comment]
Right, that works :facepalm:
