### ISSUE TITLE
Performance: Push stuck at ingester's streamsMtx.Lock

### ISSUE THREAD

**Issue by RangerCD** [grafana/loki#5177]
**Is your feature request related to a problem? Please describe.**
I've noticed some performance issues for my Loki clusters after upgrading to `2.4.1`(exist before `2.4.1`, but discovered after upgrading).
About 1% of push requests (≈60 QPS) return code `500` with `context canceled` message after 2 seconds timeout.
Tracing data shows these failed requests spend too much time(6s~8s) on ingesters' `Push` GRPC calls, distributors return before ingesters return due to configured 2s timeout.
After diagnosing with pprof, I found out most these slow Push calls are stuck at 

https://github.com/grafana/loki/blob/985e965796c7c95c5c2999bc5a212313fc2a673a/pkg/ingester/instance.go#L157

which is an instance level streams lock.

This lock limits every Push calls to execute one at a time, causing performance bottleneck.

**Describe the solution you'd like**
Remove this instance level lock, make streams/streamsByFP concurrently readable.

**Describe alternatives you've considered**
None

**Additional context**

### Hardware

All targets are deployed directly to individual physical machines.

| Target | Instances num | CPU | Ram | Ethernet |
|-|-|-|-|-|
| Distributor | 2 | Intel(R) Xeon(R) Silver 4210 @ 2.20GHz * 2 | DDR4 16GB * 8 | 10Gb Fiber |
| Ingester | 5 | Intel(R) Xeon(R) Silver 4210 @ 2.20GHz * 2 | DDR4 32GB * 8 | 10Gb Fiber |

Other unrelated targets are not listed.

### Cluster Status

| Metric | Value | Prometheus metric |
|-|-|-|
| Distributor Throughput (Total) | ≈600 MiB/s | sum(irate(loki_distributor_bytes_received_total{}[2m])) |
| Ingester Memory Streams (Total) | ≈9000 | sum(loki_ingester_memory_streams{}) |
| Push QPS (Total) | ≈6000 | sum(rate(loki_request_duration_seconds_count{method=~"POST"}[2m])) |

### Log

```
level=warn ts=2022-01-19T01:59:27.715023461Z caller=logging.go:72 orgID=xxxxxx msg="POST /loki/api/v1/push (500) 1.999633256s Response: \"context canceled\\n\" ws: false; Connection: close; Content-Length: 53357; Content-Type: application/x-protobuf; User-Agent: promtail/; X-Nginx-Proxy: true; X-Original-Uri: /api/v1/loki/api/v1/push; X-Real-Ip: 10.xxx.xxx.xxx; X-Request-Id: c32c9d2cbedc22b1c2b73b09c2b7fc50; X-Scheme: http; X-Scope-Orgid: xxxxxx; "
```
Sensitive information is censored.

### Tracing

Tracing data shows these failed requests spend too much time(6s~8s) on ingesters' `Push` GRPC calls, distributors return before ingesters return due to configured 2s timeout.

![skywalking](https://user-images.githubusercontent.com/6872198/150049615-1f44e3c2-7984-478d-a3b5-cd3450a5e62d.png)

After checking several failed requests, all ingester instances appear to have this issue irregularly.

### PProf

Since tracing data shows this is an ingester issue, I've managed to capture goroutine info with pprof.

```
goroutine profile: total 886
631 @ 0x43b285 0x44cfc5 0x44cfae 0x46e767 0x48d625 0x48ed90 0x48ed22 0x22ba093 0x22b6406 0x191d849 0x229f1c2 0xa35d83 0x1ced756 0xa35d83 0x1e0178b 0xa35d83 0xb72464 0x209acd6 0xa35d83 0xb7585a 0xa35d83 0xa3a062 0xa35d83 0xb72a14 0xa35d83 0xa35f77 0x18f6a10 0x9ddaab 0x9e1f4c 0x9f0ecb 0x472881
#	0x46e766	sync.runtime_SemacquireMutex+0x46										/go/src/runtime/sema.go:71
#	0x48d624	sync.(*Mutex).lockSlow+0x104											/go/src/sync/mutex.go:138
#	0x48ed8f	sync.(*Mutex).Lock+0x8f												/go/src/sync/mutex.go:81
#	0x48ed21	sync.(*RWMutex).Lock+0x21											/go/src/sync/rwmutex.go:111
#	0x22ba092	github.com/grafana/loki/pkg/ingester.(*instance).Push+0x152							/buildspace/e4e619d835/loki/pkg/ingester/instance.go:161
#	0x22b6405	github.com/grafana/loki/pkg/ingester.(*Ingester).Push+0xe5							/buildspace/e4e619d835/loki/pkg/ingester/ingester.go:503
#	0x191d848	github.com/grafana/loki/pkg/logproto._Pusher_Push_Handler.func1+0x88						/buildspace/e4e619d835/loki/pkg/logproto/logproto.pb.go:2727
...
```

**Comment by RangerCD** [comment]
Accidentally send while editing, will reopen after finish.

**Comment by cyriltovena** [comment]
Nice what's that tracing tool you're using ?

**Comment by RangerCD** [comment]
> Thank you for the issue, I'll look into it. what's that tracing tool you're using ?

Apache SkyWalking, we've made some changes to let SkyWalking and Loki support each other.

**Comment by marcusteixeira** [comment]
same problem here.
`level=warn ts=2022-01-19T16:54:01.790208173Z caller=logging.go:72 traceID=7a5f0de10c9b3432 orgID=fake msg="POST /loki/api/v1/push (500) 10.480675502s Response: \"context canceled\\n\" ws: false; Accept: application/json; Content-Encoding: snappy; Content-Length: 129266; Content-Type: application/x-protobuf; User-Agent: xk6-loki/0.0.1; X-Scope-Orgid: xk6-tenant-14;`
