### ISSUE TITLE
d (day) and w (week) argument doesn't work with offset modifier 

### ISSUE THREAD

**Issue by chinmaygupta28** [grafana/loki#5199]
**Describe the bug**
Only hour (h), minute (m), milliseconds (ms) and second (s) duration format works with the offset modifier but day (d), week (w) and year (y) throws this error = `parse error at line 1, col 47: syntax error: unexpected NUMBER, expecting DURATION`

**To Reproduce**
Make the 1d and 1w query visible to reproduce the error.

[play.grafana.com link](https://play.grafana.org/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Loki%22,%7B%22refId%22:%22E%22,%22expr%22:%22count_over_time(%7Bagent%3D%5C%22promtail%5C%22%7D%5B1m%5D%20offset%201ms)%22,%22hide%22:true%7D,%7B%22refId%22:%22G%22,%22expr%22:%22count_over_time(%7Bagent%3D%5C%22promtail%5C%22%7D%5B1m%5D%20offset%201s)%22,%22hide%22:true%7D,%7B%22refId%22:%22A%22,%22expr%22:%22count_over_time(%7Bagent%3D%5C%22promtail%5C%22%7D%5B1m%5D%20offset%201m)%22,%22hide%22:true%7D,%7B%22refId%22:%22B%22,%22expr%22:%22count_over_time(%7Bagent%3D%5C%22promtail%5C%22%7D%5B1m%5D%20offset%201h)%22,%22hide%22:true%7D,%7B%22refId%22:%22C%22,%22expr%22:%22count_over_time(%7Bagent%3D%5C%22promtail%5C%22%7D%5B1m%5D%20offset%201d)%22,%22hide%22:true%7D,%7B%22refId%22:%22D%22,%22expr%22:%22count_over_time(%7Bagent%3D%5C%22promtail%5C%22%7D%5B1m%5D%20offset%201w)%22,%22hide%22:true%7D,%7B%22refId%22:%22F%22,%22expr%22:%22count_over_time(%7Bagent%3D%5C%22promtail%5C%22%7D%5B1m%5D%20offset%201y)%22,%22hide%22:true%7D%5D)

**Expected behavior**
I expect them to work as they work in promql.

**Environment:**
Any

**Screenshots, Promtail config, or terminal output**

![image](https://user-images.githubusercontent.com/2870699/150481905-71c81ffa-3629-4682-9ba3-f8b494c07765.png)
![image](https://user-images.githubusercontent.com/2870699/150481930-30fdaa19-2b0b-4269-b9a4-e393d14455d5.png)

**Comment by dannykopping** [comment]
@chinmaygupta28 thank you for reporting this.

This is indeed a bug. We state explicitly that we [support](https://grafana.com/docs/loki/latest/logql/metric_queries/#range-vector-aggregation) time durations the same way [Prometheus does](https://prometheus.io/docs/prometheus/latest/querying/basics/#time-durations), so this is an inconsistency.

**Comment by SasSwart** [comment]
I'll look into this and prepare a Pull Request.

**Comment by chinmaygupta28** [comment]
> @chinmaygupta28 thank you for reporting this.
> 
> This is indeed a bug. We state explicitly that we [support](https://grafana.com/docs/loki/latest/logql/metric_queries/#range-vector-aggregation) time durations the same way [Prometheus does](https://prometheus.io/docs/prometheus/latest/querying/basics/#time-durations), so this is an inconsistency.

Went through the docs and realized, year (y), seconds (s) doesn't work either, only minutes (m), hours (h) and milliseconds (ms) work. I will update the issue description.

**Comment by SasSwart** [comment]
Progress Update:

I've found the issue, but I'm still preparing the Pull Request.
Currently writing tests and ensuring that my changes don't have unintended side effects.

**Comment by SasSwart** [comment]
Progress Update:

I've implemented a naive solution, but its not optimal. I'd like to explore an alternative, less complex, solution before submitting a PR. After an examination tomorrow afternoon, I'll continue work on this issue.

**Comment by SasSwart** [comment]
Progress Update:

A [draft PR](https://github.com/grafana/loki/pull/5275/) is available
This is still actively WIP, so don't review yet, please.
