### ISSUE TITLE
Improve Loki config management

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#520]
**Is your feature request related to a problem? Please describe.**
Currently Loki configs file are not superseded by command line flags except for limits but limit
cannot be partially provided and fulfilled by default.

**Describe the solution you'd like**
Viper from https://github.com/spf13/viper could allow us to have correct order of config precedence with extra features like sane defaults and config reload. This should be fine to integrate even if cortex uses golang flag, viper support also it.

**Additional context**
https://github.com/grafana/loki/pull/519
https://github.com/grafana/loki/pull/518
https://github.com/cortexproject/cortex/blob/master/pkg/util/validation/limits.go#L65-L73

**Comment by daixiang0** [comment]
Is there any plan about promtail config?
Now i set a watch in [this PR](https://github.com/grafana/loki/pull/482) to reload config, if change to viper, would be easy.

**Comment by CyrilPeponnet** [comment]
+1 logcli / promtail and loki should be consistent and use viper / cobra to handle args / env var and config file.

**Comment by daixiang0** [comment]
some disguss on [slack](https://grafana.slack.com/archives/CEPJRLQNL/p1566959307032600)

**Comment by sh0rez** [comment]
Implemented in #980
