### ISSUE TITLE
Docs feedback: /installation/docker.md

### ISSUE THREAD

**Issue by telefax** [grafana/loki#5212]
Add the detach flag (-d) to the setup examples, otherwise the sentence "Docker containers are running Loki and Promtail using those config files." will not be correct, because you have to shutdown the first container in order to start promtail since they are running in attached mode.

For instance:

`wget https://raw.githubusercontent.com/grafana/loki/v2.4.2/cmd/loki/loki-local-config.yaml -O loki-config.yaml
docker run --name loki -d -v $(pwd):/mnt/config -p 3100:3100 grafana/loki:2.4.2 -config.file=/mnt/config/loki-config.yaml
wget https://raw.githubusercontent.com/grafana/loki/v2.4.2/clients/cmd/promtail/promtail-docker-config.yaml -O promtail-config.yaml
docker run -d -v $(pwd):/mnt/config -v /var/log:/var/log --link loki grafana/promtail:2.4.2 -config.file=/mnt/config/promtail-config.yaml`

**Comment by telefax** [comment]
#5213

**Comment by cstyan** [comment]
Resolved in #5213
