### ISSUE TITLE
Promtail: recover from corrupted position file

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#5218]
If Promtail crash while saving the positions file, this one can end up corrupted.

I suggested we always write first to new temporary file `position.yaml.new` and then `os.Rename` which I think is atomic on most platform.

**Comment by jeschkies** [comment]
I did a quick search. There are some caveats. What do you think about using https://github.com/google/renameio which claims to get it mostly right?

**Comment by cyriltovena** [comment]
Yes ! sounds good to me
