### ISSUE TITLE
All log entries duplicated since upgrade to 2.4.2

### ISSUE THREAD

**Issue by setpill** [grafana/loki#5252]
**Describe the bug**

* Since upgrading to 2.4.2, queried logs from after the upgrade are all shown twice.
* Queried logs from before the upgrade show only once.
* Viewing the live stream of logs shows them only once.

**Expected behavior**

Logs are not duplicated.

**Environment:**
 - Infrastructure: VM with s3-compatible storage backend for chunk storage.
 - Deployment tool: manual

**Screenshots, Promtail config, or terminal output**

Loki config: https://gist.github.com/setpill/167443e50ab67263e9455eb492f0c6cf

**Comment by setpill** [comment]
Please let me know if I can provide any additional details.

**Comment by cyriltovena** [comment]
Can you provide labels/logs and timestamp for duplicate logs ? Also the stats part of the API response ?

**Comment by setpill** [comment]
I am happy to provide more debug info as needed, just awaiting instructions on what additional information I can supply.
