### ISSUE TITLE
Support fine grained `retry` with custom `backoff` configs in gcs storage client.

### ISSUE THREAD

**Issue by kavirajk** [grafana/loki#5276]
The latest version of `cloud.go.com/go/storage` (v1.19.0) package supports retry options with custom backoff configs to GCS bucket API calls.

https://pkg.go.dev/cloud.google.com/go/storage#WithBackoff

Update the GCS client library used by Loki to > v1.19.0 and support custom retry + backoff.

main rationale being, some times when we trace slow queries, single GCS API call took more time than normal (because some of the previous call failed and client retried?). We also don't have enough metrics to confirm

Loki GCS client uses bit old GCS library that doesn't support (so no control) custom retry or backoff mechanisms. The default retry mechanism is follows, 
- start with 1 second initial delay, 
- and wait exponentially with multiplier of 2. (https://pkg.go.dev/github.com/googleapis/gax-go/v2#Backoff)

which may not be ideal in all the cases

**Comment by dannykopping** [comment]
How will this interact with our recent [request hedging](https://github.com/grafana/loki/pull/4826) addition?
