### ISSUE TITLE
Loki api returning Empty

### ISSUE THREAD

**Issue by sanjay-s-far** [grafana/loki#5277]
![Screenshot 2022-01-31 091509](https://user-images.githubusercontent.com/73020475/151736163-de637f40-25df-40c5-8958-aa80401b3e07.jpg)
As you can see in the above image whenever I am querying something using that API the result field is always empty

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
