### ISSUE TITLE
Promtail going into deadlock during normal rollout.

### ISSUE THREAD

**Issue by kavirajk** [grafana/loki#5279]
We found promtail health check is failing and not sending logs from some of the pods to Loki because of some deadlock

Some dumps and profile info below.
[goroutine.gz](https://github.com/grafana/loki/files/7971393/goroutine.gz)
[goroutine.prof.txt](https://github.com/grafana/loki/files/7971399/goroutine.prof.txt)

Related issues https://github.com/grafana/loki/issues/5162

**Comment by chaudum** [comment]
Probably solved by https://github.com/grafana/loki/pull/5283
