### ISSUE TITLE
grafana/loki-build-image:0.19.0 is not available on docker hub, but referenced in the Makefile

### ISSUE THREAD

**Issue by SasSwart** [grafana/loki#5294]
**Describe the bug**
grafana/loki-build-image:0.19.0 is not available on docker hub, but used in the Makefile.

**To Reproduce**
1. Checkout c88734b72c478c050ccef0823b9e47f4abfea88c (HEAD of main branch at the time of bug report)
2. Run `make check-generated-files`

**Expected behavior**
GoYacc parser should be generated.
It should then print a diff between the old parser and the newly generated one.
It should terminate with status code zero if no diff was found.

**Environment:**
 - Local development environment
 - Both inside VS Code and directly in a terminal

**Screenshots, Promtail config, or terminal output**
```
docker run --rm --tty -i \
        -v /home/sas/github/loki/.cache:/go/cache:delegated \
        -v /home/sas/github/loki/.pkg:/go/pkg:delegated \
        -v /home/sas/github/loki:/src/loki:delegated \
        grafana/loki-build-image:0.19.0 pkg/lokifrontend/frontend/v2/frontendv2pb/frontend.pb.go;
Unable to find image 'grafana/loki-build-image:0.19.0' locally
docker: Error response from daemon: manifest for grafana/loki-build-image:0.19.0 not found: manifest unknown: manifest unknown.
See 'docker run --help'.
make: *** [Makefile:351: pkg/lokifrontend/frontend/v2/frontendv2pb/frontend.pb.go] Error 125
```

**Comment by cyriltovena** [comment]
🤷 pushed.
