### ISSUE TITLE
`loki-build-image` should be built and published via CI

### ISSUE THREAD

**Issue by dannykopping** [grafana/loki#5296]
**Is your feature request related to a problem? Please describe.**
Following https://github.com/grafana/loki/issues/5294, which raised a flag about the build image not being published after https://github.com/grafana/loki/pull/5250 was merged, I discovered we are publishing this image from our workstations.

**Describe the solution you'd like**
We should build and publish this image via CI.

**Describe alternatives you've considered**
Pushing from our workstations does work, but this can introduce inconsistencies or leak local changes into the image which are not pushed. We also currently rely on tribal knowledge and memory to remember to push a new build image when necessary.

**Additional context**
The image is pushed with `make build-image-push`.

**Comment by dannykopping** [comment]
@cyriltovena also pointed out that fluentd (`make fluentd-push`) and logstash (`make logstash-push`) are also run locally.

**Comment by jeschkies** [comment]
How are we versioning the build image? That seems to be the only question. Otherwise it should be doable within a few days.

**Comment by dannykopping** [comment]
I believe it's using the `BUILD_IMAGE_VERSION` variable.

See https://github.com/grafana/loki/blob/main/Makefile#L558-L564

**Comment by jeschkies** [comment]
What do you think about using calendar versioning? We probably do not really track breaking changes.

**Comment by dannykopping** [comment]
We can use whatever we want; I don't think anybody else uses this image TBH.

**Comment by dannykopping** [comment]
I'm fine with calendar versioning, personally

**Comment by SasSwart** [comment]
>  I don't think anybody else uses this image TBH.

Does this image need to be on docker hub?
Since its primarily used for CI purposes, why not have the make file build it if its not present locally instead of pulling it from somewhere?

That would simplify the stack by not requiring a push to docker hub, nor versioning of the image.

**Comment by jeschkies** [comment]
> Since its primarily used for CI purposes, why not have the make file build it if its not present locally instead of pulling it from somewhere?

I sometimes use it locally and it's a PITA to build.
