### ISSUE TITLE
Add  wait time created by the LimitedRountTripper as a span log.

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#5316]
Currently a query with too high parallelism will get limited by the limitedRoundtripper https://github.com/grafana/loki/blob/main/pkg/querier/queryrange/limits.go#L292

However there's no trace of this happening, it would be great to add a span log and log that includes the time waited for goroutine capacity.

**Comment by Gabrielopesantos** [comment]
Hello,
This issue seems interesting and I would like to work on this issue, is that ok? Thank you

**Comment by dannykopping** [comment]
@Gabrielopesantos go for it 👍

**Comment by niuguy** [comment]
Hi @dannykopping. I submitted a pr for this one, would you be able to review and point out if I'm heading the right direction? I noticed that the CI failed, but I tried runing locally on main branch it also failed with the same error. appreciated if you can shed some light on this, thank you.
