### ISSUE TITLE
Add logfmt format in k6 load test push

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#5320]
This is the only one missing for pushing log in all common format.

**Comment by chaudum** [comment]
Since flog does not seem to be maintained any more and we already depend on my fork, I made a PR (https://github.com/chaudum/flog/pull/1) to the fork so we can pull that in.

**Comment by chaudum** [comment]
https://github.com/grafana/xk6-loki/pull/32

**Comment by vlad-diachenko** [comment]
looks like done.
