### ISSUE TITLE
Ruler: flaky test `TestStorageSetupWithRemoteWriteDisabled`

### ISSUE THREAD

**Issue by dannykopping** [grafana/loki#5338]
https://drone.grafana.net/grafana/loki/8487/1/3

This test has failed a few times lately.
I believe the change causing the failures was introduced in https://github.com/grafana/loki/pull/5253.

Not entirely sure why yet, since the [docs](https://pkg.go.dev/testing#T.TempDir) claim every successive call should create a unique directory.

> TempDir returns a temporary directory for the test to use. The directory is automatically removed by Cleanup when the test and all its subtests complete. Each subsequent call to t.TempDir returns a unique directory; if the directory creation fails, TempDir terminates the test by calling Fatal.

**Comment by MasslessParticle** [comment]
fixed by #5307
