### ISSUE TITLE
Unable to fetch logs from remote server to my local grafana/loki using promtail

### ISSUE THREAD

**Issue by woodydapogi** [grafana/loki#5367]
Hi all, I’m new to Grafana and found out that there’s a log aggregation using Loki with the help of Promtail. I was able to install and fetched logs from my localhost. I would want to get logs from remote servers (i.e: nginx logs from a remote nginx web server) and push it to my grafana server. What could be the possible way of doing it? Thanks so much!

From my server:
my-promtail-config.yaml
server:
http_listen_port: 9080
grpc_listen_port: 0

positions:
filename: /data/loki/positions.yaml
clients:

url: http://localhost:3100/loki/api/v1/push
scrape_configs:
job_name: nginx
static_configs:
targets:
<remote_server_ip>
labels:
job: nginx
path: /var/log/nginx/*.log
host: grafana-server

Remote server (not sure if i have to add promtail and push to my grafana server):
server:
http_listen_port: 9080
grpc_listen_port: 0

positions:
filename: /data/loki/positions.yaml
clients:

url: http://grafana-loki-server/loki/api/v1/push
scrape_configs:
job_name: nginx
static_configs:
targets:
localhost
labels:
job: nginx
path: /var/log/nginx/*.log
host: remote-logs

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.

**Comment by rgazzeh** [comment]
@woodydapogi  Have you found the solution?

**Comment by woodydapogi** [comment]
> 
Hi, 

This is based on our configurations. Just check the solution below and see if it helps. Thanks!

ISSUE 1.: Remote Promtail is not sending updated logs to Loki Server.

RESOLUTION: Since loki:3100 was changed to listen to proxy 10008. 
1.Go to loki01 UI > Configuration > Data Sources and change the loki URL to https://<our.loki.server>:10008/ and be sure to test the connection.

2. Enable Basic Auth with Credentials

3. Proceed to remote host/client promtail and update the server's url config file 
server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: https://admin:<our_loki_key>@<our.loki.server>:10008/loki/api/v1/push

scrape_configs:
  - job_name: nginx-logs
    static_configs:
    - targets:
        - localhost
      labels:
        job: sites-access-logs
        __path__: /var/www/*/log/access.log
