### ISSUE TITLE
[bug] query-fronted: concurrent query has a bottleneck

### ISSUE THREAD

**Issue by liguozhong** [grafana/loki#5378]
**7 day  - 2TB - cost 89s**
![image](https://user-images.githubusercontent.com/9583245/153714246-74ee227c-0802-4df1-b43b-78a5056673a0.png)

**bug ："interval" spans have different start times**
![image](https://user-images.githubusercontent.com/9583245/153713934-970a2641-5858-4ce0-ba29-490aac2bbd55.png)

**tracing top**
![image](https://user-images.githubusercontent.com/9583245/153713955-d94274d5-2aa1-4b75-a3a5-e1a6f106f031.png)

**No CPU throttled**
![image](https://user-images.githubusercontent.com/9583245/153714037-ca67c536-e919-4af0-a648-3fee0ccef0e4.png)

**Comment by liguozhong** [comment]
This 89s duration is because the query task load of the querier is not balanced？？
![image](https://user-images.githubusercontent.com/9583245/153716056-684ad71f-cf49-4386-a839-7213efd8372b.png)

**Comment by liguozhong** [comment]
loki deploy v2 querier path with scheduler
![image](https://user-images.githubusercontent.com/9583245/153717193-b1956b54-16b6-4ec8-a560-b6520aab5d26.png)

**Comment by cyriltovena** [comment]
The difference in the starting span could be max_query_parallelism

**Comment by liguozhong** [comment]
our cluster： 2Tb / 64s = 33Gb/s

The gap with the top level of 100Gb is still a bit big，we hope to achieve 100Gb。

![image](https://user-images.githubusercontent.com/9583245/153738689-6720271a-f942-4daa-996e-c7cc9ab81536.png)
https://github.com/grafana/loki/issues/5062

**Comment by cyriltovena** [comment]
I was mostly referring to the gap you have in interval spans, those are because you reach the max_paralellism_query.

For the unbalanced question, can you elaborate ?
