### ISSUE TITLE
logfmt pipeline stage isn't documented

### ISSUE THREAD

**Issue by m1keil** [grafana/loki#5384]
Apparently there is a `logfmt` stage [available](https://github.com/grafana/loki/blob/main/clients/pkg/logentry/stages/logfmt.go) in the promtail pipeline config, but the stage [isn't documented](https://grafana.com/docs/loki/latest/clients/promtail/stages/logfmt/).

**Comment by alanmcg** [comment]
Thanks, I remember being really disappointed that it wasn't part of promtail. I have tested the undocumented feature and it works great, it's as simple as:

`          stages:
            - logfmt:
                mapping:
                  thing: thing
                  value: value`

But this should of course be documented.
So happy you opened this issue :D

**Comment by MichelHollands** [comment]
This is documented now in https://grafana.com/docs/loki/latest/clients/promtail/stages/logfmt/
