### ISSUE TITLE
Many logs are missing from Loki datasource in grafana

### ISSUE THREAD

**Issue by Ashwin-Raj18** [grafana/loki#5412]
The Bug
I have fluent-bit in my cluster which outputs to elasticsearch and Loki. For the given app(label) and time interval, loki misses on lots of log line.

1. setup loki and elasticsearch as 2 different datasource
2. start fluent-bit and output logs to above DS.

**Expected behavior**
Loki should have all the logs as in elasticsearch (refer screenshot)

**Environment:**
 - Infrastructure:  Kubernetes, bare-metal (CaaS)
 - Deployment tool: e.g., helm

**Loki logs vs ES logs for same time interval and label**
![image](https://user-images.githubusercontent.com/63547678/154288556-6935cf99-a025-4d71-9017-169963ddb5f0.png)
![image](https://user-images.githubusercontent.com/63547678/154288611-5bc28854-5aa3-4c60-aa65-c79340ce7b27.png)

**fluent-bit.conf**
[FILTER]
    Name                grep
    Match               k8s_audit_sys_user
    Exclude             kind Event

[FILTER]
    Name                grep
    Match               systemd_sys_kubelet
    Exclude             HOSTNAME .*

[FILTER]
    Name                modify
    Condition          Key_Exists  kubernetes
    Copy                 kubernetes  k8s_resources
    Match_Regex    ^(k8s|kube\.var\.log\.containers).*$

[FILTER]
    Name                nest
    Operation           lift
    Match_Regex      ^(k8s|kube\.var\.log\.containers).*$
    Nested_under     k8s_resources
    Add_prefix          k8s_resource_

[FILTER]
    Name                grep
    Match_Regex     ^(k8s|kube\.var\.log\.containers).*$
    Exclude             k8s_resource_namespace_name .*(kube|caas)-system.*
	
[INPUT]
    Name              forward
    Listen              0.0.0.0
    Port                 24284
    Buffer_Chunk_Size 256KB
    Buffer_Max_Size   10MB
    Mem_Buf_Limit     8MB

[OUTPUT]
    Name  es
    Match *
    Host  elasticsearch-master
    Port  9200
    Logstash_Format On
    Retry_Limit 2
    Type  flb_type
    Time_Key @flb-timestamp
    Replace_Dots On
    Logstash_Prefix kubernetes_cluster
    
[OUTPUT]
    name                        loki
    match                       *
    host                         loki.monitoring.svc.cluster.local
    port                         3100
    labels                       job=fluent-bit
    auto_kubernetes_labels      on

**Comment by littlepangdi** [comment]
Timestamps of log entries in loki is the precise time when logs are collected by Promtail, for example,
![image](https://user-images.githubusercontent.com/41042306/154416871-cbfdf860-db6b-4ae9-a140-0a32b77994de.png)
 I think there is a chance that your logs is not missing but not uploaded yet.

**Comment by Ruppsn** [comment]
I think we might encounter the same Problem.

**The Bug**
I have fluent-bit in my cluster which outputs to file on host and loki. Everything is logged to file. But some streams to loki are breaking up. Respective the error streams are breaking up (see fluent-bit.conf). Maybe I am to stupid or i forgott something.

**Steps to reproduce the behavior:**
Setup loki and file based logging as 2 different outputs inside fluent-bit (containerised)
Start fluent-bit and output logs

**Expected behavior**
Loki should have the same logs like in file based logging

**Actual behavior**
Loki is getting the logs after a service is startet but after 5-10 minutes no more logs are sent to loki
We tried a tcp dump on lokis side. There are no logs sent to loki. So it must be on fluent-bits side. No errors in log.

We also tried only one output. File based is always working. Loki is behaving the same. Access logs are always send. Error logs are missing. 

**Environment:**
Infrastructure: Docker Swarm / Oracle Linux 8.3

**fluent-bit.conf**
[fluent-bit.txt](https://github.com/grafana/loki/files/8133445/fluent-bit.txt)

**Comment by Ashwin-Raj18** [comment]
> Timestamps of log entries in loki is the precise time when logs are collected by Promtail, for example, ![image](https://user-images.githubusercontent.com/41042306/154416871-cbfdf860-db6b-4ae9-a140-0a32b77994de.png) So consider the circumstances when production speed is less than sending speed, I think there is a chance that your logs is not missing but not uploaded yet.
![grafana-gh](https://user-images.githubusercontent.com/63547678/155557569-a13f000e-0f5c-431f-81fb-7309b3267370.png)

@littlepangdi the time zone printed on application log is different than that of loki. The application is running on remote server. I have observed that bunch of logs missing for a interval of time cyclically.

**Comment by DekusDenial** [comment]
When I used the official loki output plugin from fluent bit I have gotten way too many broken bad chunks and logs were basically lost as the fluent bit pods kept failing then in crashloop. I had to switch to use loki’s own plugin here and the issue disappeared without any change in the conf. Just my experience to share and also wonder why that was the case.

**Comment by Ruppsn** [comment]
@DekusDenial thanks for this.
Can you elaborate what you mean by lokis own plugin? So you don't use fluenbit?

**Comment by DekusDenial** [comment]
> @DekusDenial thanks for this.
> Can you elaborate what you mean by lokis own plugin? So you don't use fluenbit?

https://hub.docker.com/r/grafana/fluent-bit-plugin-loki, https://grafana.com/docs/loki/latest/clients/fluentbit/

**Comment by isshwar** [comment]
@Ashwin-Raj18 are you able to solve the issue? I am seeing the same and in the middle moving my set up from ELK to Loki but could not go forward as I am missing a lot of logs.
