### ISSUE TITLE
Ingester fails to write to chunks with "open: file too large"

### ISSUE THREAD

**Issue by prezhdarov** [grafana/loki#5422]
Seems OOMKill has caught all ingesters at some point and now all instance refuse to start with "open <filename>: file too large". The files in question are missing or never created.

Loki (2.4.2) deployed from loki-distributed helm chart runs on vanilla kubernetes (1.23.3) on debian 11
Now the tricky part - chunks storage is NFSv3 export from a NetApp storage system (a flexgroup) via NetApp Trident as RWX PVC.

This is what the ingester logs look like:
level=error ts=2022-02-17T12:41:58.407687115Z caller=flush.go:221 org_id=d1RMY60Mj1MyxosO msg="failed to flush user" err="open /var/loki/chunks/ZDFSTVk2ME1qMU15eG9zTy9mNzMxOTg2NTE0MDAxNmJmOjE3ZjA2Zjg3YTk0OjE3ZjA2Zjg3YTljOjgzZThjMjlm: file too large"
level=error ts=2022-02-17T12:41:58.408380738Z caller=flush.go:221 org_id=d1RMY60Mj1MyxosO msg="failed to flush user" err="open /var/loki/chunks/ZDFSTVk2ME1qMU15eG9zTy9lMTNjNDI0NjExNWYzYjBlOjE3ZjA2ZjcyNzI1OjE3ZjA3MDEzMmMxOjVhZTc2ZDdl: file too large"
level=error ts=2022-02-17T12:41:58.409144009Z caller=flush.go:221 org_id=d1RMY60Mj1MyxosO msg="failed to flush user" err="open /var/loki/chunks/ZDFSTVk2ME1qMU15eG9zTy9mNDA5MDhmNWQ5Y2VlNTUyOjE3ZjA2ZjVmNzE3OjE3ZjA3MGRkNTk2OjM5NzhlMjQ2: file too large"
level=error ts=2022-02-17T12:41:58.409735107Z caller=flush.go:221 org_id=d1RMY60Mj1MyxosO msg="failed to flush user" err="open /var/loki/chunks/ZDFSTVk2ME1qMU15eG9zTy9hZDRmNTc0OGZlNzFlODc4OjE3ZjA2ZjNhYTFiOjE3ZjA2ZmRkMjNkOmRkNGY2ZmMz: file too large"
level=error ts=2022-02-17T12:41:58.410292913Z caller=flush.go:221 org_id=d1RMY60Mj1MyxosO msg="failed to flush user" err="open /var/loki/chunks/ZDFSTVk2ME1qMU15eG9zTy85YzEyMGM1Yjc5OGIyZTRiOjE3ZjA2ZjViN2ViOjE3ZjA2ZmVmYmIwOmJlZjE5YTc0: file too large"

And of course if I try to list any of these files, they are missing i.e:
/mnt# ls -lah ZDFSTVk2ME1qMU15eG9zTy9mNzMxOTg2NTE0MDAxNmJmOjE3ZjA2Zjg3YTk0OjE3ZjA2Zjg3YTljOjgzZThjMjlm
ls: cannot access 'ZDFSTVk2ME1qMU15eG9zTy9mNzMxOTg2NTE0MDAxNmJmOjE3ZjA2Zjg3YTk0OjE3ZjA2Zjg3YTljOjgzZThjMjlm': No such file or directory

Where I have this NFS mounted on a separate host on /mnt

Is there a way this can be resolved, or this repository is gone?
Tried setting chunk_target_size to 1GB... didn't help

**Comment by dannykopping** [comment]
`file too large` is an error from the underlying OS i believe:
https://www.gnu.org/software/libc/manual/html_node/Error-Codes.html

> Macro: int EFBIG
> “File too large.” The size of a file would be larger than allowed by the system.

This is not something Loki can control, but rather something specific to your underlying NFS.

**Comment by dannykopping** [comment]
The error message is misleading; it's not about the size of the file relative to the whole, but rather a file (or directory) is exceeding some limit imposed by the OS.

How many files are in `/var/loki/chunks/`?

```bash
find /var/loki/chunks/ -type f | wc -l
```

**Comment by prezhdarov** [comment]
Found it (embarrassingly enough) it was the max dir size that hat it tripped 
`::*> vol show ams24_dmz_pvc_2754c412_fda9_4863_b8c2_a6cd74798107  -fields maxdir-size
vserver             volume                                             maxdir-size
------------------- -------------------------------------------------- -----------
vserver1 ams24_dmz_pvc_2754c412_fda9_4863_b8c2_a6cd74798107 320MB`

and when mounted 
`drwxrwxrwx   3 root root 320M Feb  7 09:48 mnt`

Files count is just about to reach 1 million - 998023. 

And this should be the end of this case. My trials with RWX large NFS volumes continue.

**Comment by dannykopping** [comment]
Glad to hear you found your answer :+1:
