### ISSUE TITLE
request time issue

### ISSUE THREAD

**Issue by lgy1027** [grafana/loki#5449]
The response time of initiating an http request is relatively long, and it is located in the time problem

http://127.0.0.1:31000/grafana/api/datasources/proxy/2/loki/api/v1/query_range?direction=BACKWARD&end=1645578857000000000&limit=5000&query=%7Bapp%3D%22monitor-kube-events-exporter%22%7D%7C~%60%22namespace%22%3A%22%28bita-user%29%22%60%7C%3D%60%22kind%22%3A%22Pod%22%60%7C%3D%60%22name%22%3A%22monitor-kube-events-exporter-599bbd4dbd-wqckc%22%60&start=1645518140000000000

http://127.0.0.1:31000/grafana/api/datasources/proxy/2/loki/api/v1/query_range?direction=BACKWARD&end=1645578857000000000&limit=5000&query=%7Bapp%3D%22monitor-kube-events-exporter%22%7D%7C~%60%22namespace%22%3A%22%28bita-user%29%22%60%7C%3D%60%22kind%22%3A%22Pod%22%60%7C%3D%60%22name%22%3A%22monitor-kube-events-exporter-599bbd4dbd-wqckc%22%60&start=1645578825375813700

The response time of the above two requests differs by four seconds

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
