### ISSUE TITLE
Time problem of requesting /query_range　to return results

### ISSUE THREAD

**Issue by wangjie-zzz** [grafana/loki#5451]
**Describe the bug**
When using the `direction = forward` parameter and specifying the start and end ranges to request `/loki/api/v1/query_range`, the contents of values in the response result are not within the range of start and end, but there is no problem when using the direction = backward request；

**To Reproduce**
1. When I use the following parameters to request  loki：
`http://x.x.x.x:3100/loki/api/v1/query_range?limit=100&query={filename="/var/logs/xxxxx.log"}&direction=FORWARD&start=1645607229724208708&end=1645614429724000000`
2. the returned results are as follows：
`{
    "status": "success",
    "data": {
        "resultType": "streams",
        "result": [
            {
                "stream": {
                    "filename": "/var/logs/xxx.log",
                    .....
                },
                "values": [
                    [
                        "1645602582025189598","..................."
                    ],
                    [
                        "1645602582025264673","..................."
                    ],
                    [
                        "1645602583276143859","......................"
                    ],
                    [
                        "1645602583276224270",".................."
                    ],
                    [
                        "1645602583276280963",".............."
                    ],
                    [
                        "1645602583276323605","............."
                    ],
                    ....................
                ]
            }
        ],
        "stats": {..............}
    }
}`

**Expected behavior**
The contents of values should be in the range of start and end；

**Environment:**
ｌｏｋｉ　version: 2.0.1

**Comment by wangjie-zzz** [comment]
This problem occurs when the start parameter is about an hour from the current time，
There is no problem with the query a few hours ago

**Comment by DylanGuedes** [comment]
That loki version is kinda old (v2.0.1). Can you confirm if it is solved for v2.4.2 (latest version)?

**Comment by wangjie-zzz** [comment]
> That loki version is kinda old (v2.0.1). Can you confirm if it is solved for v2.4.2 (latest version)?

Thanks very much. I tried version 2.3.0. It's OK, but where's the problem。。。
