### ISSUE TITLE
Support named profiles in LogCLI simlar to AWS CLI or kubectl

### ISSUE THREAD

**Issue by jeschkies** [grafana/loki#5453]
**Is your feature request related to a problem? Please describe.**
I'm using logcli for different clusters. It is annoying to manage the credentials via environment variables. It would be great to manage credentials in a `~/.logcli/config` file.

**Describe the solution you'd like**
The AWS CLI supports [named profiles](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html) and `kubectl` has [contexts](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/). LogCLI could follow the same pattern and accept a `-p`/`--profile` parameter that references a profile in `~/.logcli/config`. If no profile is passed the `default` profile is used if it exists. Flags such as `--password` and `--addr` override fields from the profile.

Profiles can be managed via the CLI as well with `logcli profile add <name>`. Password, address, username and other fields are passed via the [known flags]((https://grafana.com/docs/loki/latest/getting-started/logcli/#logcli-command-reference)) and stored in `~/.logcli/config`. `logcli profile remove <name>` removes a profile.

The configuration file `~/.logcli/config` is a [TOML](https://github.com/toml-lang/toml) file with the following layout:

```toml
[<profile name>]
addr = "https://myloki.grafana.com"
password = "<API key>"
username = "<instance ID>"
cert =  "<path>"
```

The field names correspond to the [flag names](https://grafana.com/docs/loki/latest/getting-started/logcli/#logcli-command-reference) `addr`, `username`, `password`, `ca-cert`, `tls-skip-verify`, `cert`, `key`, `org-id`, `bearer-token` and `bearer-token-file`.

Grafana Cloud should have a code snippet for setting up a profile.

**Describe alternatives you've considered**
I'm not aware of an alternative other than managing environment variables.

**Comment by dannykopping** [comment]
Sounds reasonable to me :+1:

**Comment by slim-bean** [comment]
As a cheap workaround I currently solve this with aliases:

```
alias logcli="LOKI_ADDR=https://logs-ops-tools1.grafana.net LOKI_USERNAME=29 LOKI_PASSWORD=${LOKI_OPS_PASSWORD} /home/ed/projects/loki/cmd/logcli/logcli"
```

In the past I've setup different aliases like `logclip` for prod or d for dev or whatever.

**Comment by simonswine** [comment]
I personally am happy with just using the environment variables, but I certainly can see why others would appreciate it.

I would like to suggest strongly to use `${XDG_CONFIG_HOME}` if we are storing something in the user's home directory (see [spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables)). Which would leave us with a directory like: `~/.config/logcli` by default.

I also think it is not trivial to define the precedence of config sources. I would assume the most natural is (from lowest to highest):
- Coming from the config file
- Environment variables
- CLI flags
