### ISSUE TITLE
count() result is inaccurate 

### ISSUE THREAD

**Issue by slim-bean** [grafana/loki#5461]
**Describe the bug**

When comparing the number of returned series from a query to the same query with `count()` wrapped around it the results are different.

The same `count` query sent directly to a querier and bypassing the query-frontend returns the correct result.

**Comment by cyriltovena** [comment]
logfmt will returns labels that will be the same across different shard
the only way to fix it is to shard the sum but not the count.

count is distinct count so you can’t have it once you mutate labels across shards.
