### ISSUE TITLE
Hashicorp's Nomad discovery for Promtail

### ISSUE THREAD

**Issue by m1keil** [grafana/loki#5464]
We would like to scrape [Nomad's](https://www.nomadproject.io/) scheduled workloads with Promtail.

**Describe the solution you'd like**

Adding a new `scrape_configs` option - `nomad_sd_config`, similar to the already existing `kubernetes_sd_config`.
This would enable promtail agent to scrape Nomad's client REST API for information about the currently running workloads on the host.

**Describe alternatives you've considered**

1. Use/write a custom service that continuously scrapes Nomad API and generates a config file that is suitable for `static_config` ([example](https://github.com/dmaes/nomad-logger))
2. Use Consul discovery (our current choice).
3. Use the log shipper pattern and run promtail as a sidecar per service. Use `stratic_config` again to pinpoint the details of the log files.
4. Using the docker logging driver.
5. Using a different log shipper.

**Additional context**
Using Consul discovery is our current way of doing this but it does introduce a number of shortcomings:

1. Every service that we want to collect logs from is required to be registered into Consul catalogue. 
2. This doesn't work well for short-lived workloads as services are being missed to get discovered.
3. Limited metadata is passed between Nomad and Consul by default which prevents promtail from accessing a more interesting and useful metadata.

**Comment by trevorwhitney** [comment]
Hey @m1keil, this has come up before, and might be a good thing to pursue. I'm curious about a few things first though.

First, out of curiosity, did you know Promtail has a [consul agent](https://github.com/grafana/loki/tree/main/clients/pkg/promtail/discovery/consulagent) service discovery mechanism as well? This uses the API of the agent co-located on the same node as promtail. This might alleviate some of the issues you're having with the Consul catalogue API, though services still need to be registered with the agent. Is it possible to have a Nomad deployment that's not registered with consul? 

Second, do you know what the current gap is between Consul and Nomad currently? What is some of the metadata you'd like to have that you're missing out on?

Finally, how does Nomad handle short-lived services? Do those not get registered with the consul agent? I'm curious to learn a bit more about how using the Nomad API would avoid missing these short-lived processes.

**Comment by m1keil** [comment]
Yes, we are currently using the consulagent SD.

>  Is it possible to have a Nomad deployment that's not registered with consul?
Nomad has good integration with Consul but it's not automatic. Each Nomad client will register to Consul automatically. However, any workloads that you run must register themselves via the [service{}](https://www.nomadproject.io/docs/job-specification/service) stanza of the Nomad job.
Some services might opt out from the registration if service discovery isn't required for them. 

> What is some of the metadata you'd like to have that you're missing out on?
Primary Nomad's metadata. With the current integration, you can get Nomad's task name and allocation ID. But you won't be able to reliably get the job name or the group's name or have the Nomad's [meta{}](https://www.nomadproject.io/docs/job-specification/meta) data.

Meta{} is an interesting one in itself. Nomad includes its own metadata definition you can define on different levels (Job/Group/Task). It doesn't get passed automatically to Consul's service meta. It's an entirely different thing. 

Is it possible to work around this? Yes. Is it kinda ugly? I think so :\ 

> Finally, how does Nomad handle short-lived services?
I think the problem is that Consulagent doesn't pick up the service in time. For example, I have a small backup batch job that runs for 15 seconds every few hours. Even though the service registers in Consul, it seems like promtail doesn't detect it. 
I took a quick peak in the code and from what I understand, promtail is supposed to use blocking queries and theoretically, this should be detected.. but in practice it seems like something is missing.

**Comment by nahsi** [comment]
I'm interested in this too. Currently I use `docker_sd_config`, but it doesn't work well with Nomad bridge. Example usage can be seen in this [issue](https://github.com/grafana/loki/issues/6165)

**Comment by m1keil** [comment]
Thanks @trevorwhitney!
I will check with Prometheus folks if there is an interest.

**Comment by AAverin** [comment]
Any plans to reopen this?
Prometheus does support `nomad_sd_configs` already, would be great to get the same for promtail.

**Comment by AAverin** [comment]
@m1keil did you have any progress asking prometheus devs?
I am the point where everything in my cluster works in pure Nomad except promtail + loki combination. Don't really want to bring Consul just because of that.
