### ISSUE TITLE
promtail external labels for each client

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#547]
Since we will soon support multiple client to send logs to multiple Loki instances and that external labels are configured per client should we allow external labels to be different for each client or move it to the global level ? What would be a good use case for this ?

see #536 which will bring support for per client external labels.

/cc @slim-bean @gouthamve

**Comment by slim-bean** [comment]
My thought here would be to allow both? leave the existing per client external labels but also add a global external labels (and corresponding command line flag).

Then at runtime all the global external labels would get merged into any client specific labels.  (All clients would have the global external labels applied to all streams)

This would also support backwards compatibility

**Comment by Kuqd** [comment]
Great will do
