### ISSUE TITLE
Loki remote-write no error messages if disabled on Prometheus

### ISSUE THREAD

**Issue by eyJhb** [grafana/loki#5471]
**Describe the bug**
If Loki Recording Rules are used with remote-write to a Prometheus instance, which does not have remote-write enabled (`--enable-feature=remote-write-receiver`), then Loki will fail to remote-write to Prometheus and fail silently.
I have tried this with log-level `info`, which should include any such error messages.

I can see that Loki executes the query in the rules, but then nothing more than that, no errors, etc.

**To Reproduce**
1. Start Prometheus without having enabled `remote-write-receiver`
2. Start Loki with remote write enabled Loki with some Recording Rules defined.
3. Produce some data to ensure that Recording Rules will write something
4. See that Loki queries for the data on the interval, but nothing shows up in Prometheus.
5. ??? Confirm no errors in Loki output
6. Enable remote-write-receiver on Prometheus and restart it
7. Confirm metrics showing up

**Expected behavior**
I would expect Loki to give an error in the kind of `remote-write not enabled on target host`.

**Environment:**
```
loki, version 2.4.2 (branch: unknown, revision: unknown)
  build user:       nix@nixpkgs
  build date:       unknown
  go version:       go1.16.13
  platform:         linux/amd64
  ```

**Comment by kgeckhart** [comment]
Hello I'm having a hard time recreating this issue do you have more info on your loki config + prometheus version? 

Using a docker-compose setup with loki 2.4.2 + latest prometheus, the error response from prometheus is logged in loki and it indicates the `remote-write-receiver` feature should be enabled,
`ts=2022-03-08T17:18:02.52468818Z caller=dedupe.go:112 storage=registry manager=tenant-wal instance=fake component=remote level=error remote_name=fake-rw url=http://prometheus:9090/api/v1/write msg="non-recoverable error" count=1 exemplarCount=0 err="server returned HTTP status 404 Not Found: remote write receiver needs to be enabled with --enable-feature=remote-write-receiver"`
When using a prometheus version < v2.25.0 the message doesn't include the context about the remote write receiver but still logs the 404. This appears to happen every time there is data to be written.

This seems to line up with the behavior of the prometheus remote storage used to handle the remote write, https://github.com/grafana/loki/blob/v2.4.2/vendor/github.com/prometheus/prometheus/storage/remote/client.go#L239. There's also the metric `loki_ruler_wal_prometheus_remote_storage_samples_failed_total` which is incremented when the write fails.

**Comment by eyJhb** [comment]
still important

**Comment by JustJordanT** [comment]
is this still important?

**Comment by eyJhb** [comment]
Given I didn't even reply so so long ago on how to reproduce it, I think we should just close this. Thanks for the reminder @JustJordanT :)
