### ISSUE TITLE
Promtail port 80 error

### ISSUE THREAD

**Issue by pabsroq** [grafana/loki#5473]
Hi,

I am trying to collect logs from a windows host and send them over to a remote grafana/loki/promtail server.

This host is also running IIS which I believe may create the issue which I experience then again, unsure as of why.

When running `promtail-windows-amd64.exe --config.file=sei_logs.yaml` we then receive `level=error ts=2022-02-24T21:32:02.4816473Z caller=main.go:115 msg="error creating promtail" error="listen tcp :80: bind: An attempt was made to access a socket in a way forbidden by its access permissions."`

Config file
`positions:
  filename: D:\scripts\x3_logs_positions.yaml

clients:
  - url: http://promtailserver:3100/loki/api/v1/push

scrape_configs:
- job_name: objserver
  static_configs:
  - targets:
      - localhost
    labels:
      job: BIService
      __path__: C:\Program Files\Sage\Sage Enterprise Intelligence\Service\objserver\BIService*.log

- job_name: objDistribution
  static_configs:
  - targets:
      - localhost
    labels:
      job: distribution_trace
      __path__: C:\Program Files\Sage\Sage Enterprise Intelligence\DistributionService\objDistribution\distributiontrace*.log

- job_name: DistributionLogs
  static_configs:
  - targets:
      - localhost
    labels:
      job: distribution
      __path__: C:\Program Files\Sage\Sage Enterprise Intelligence\Service\objserver\DistributionLogs\Distribution*.log`

We already have it working on a different non IIS host, hence the suspicion of something related to IIS and port 80, if that is the case, why would promtail use local 80 port for, and how to get around it?

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
