### ISSUE TITLE
Docs feedback: /api/_index.md

### ISSUE THREAD

**Issue by elliott-king** [grafana/loki#5476]
"Step vs interval" link is broken:

<img width="529" alt="Screen Shot 2022-02-25 at 9 59 52 AM" src="https://user-images.githubusercontent.com/8884571/155737271-78264dd8-0359-467d-a727-fe1e98ba71f9.png">

The heading does exist on the page, but it does not seem to be linkable:

<img width="1121" alt="Screen Shot 2022-02-25 at 10 00 19 AM" src="https://user-images.githubusercontent.com/8884571/155737337-f3e10b86-6f6e-49bf-8730-17fb97930f6b.png">

**Comment by KMiller-Grafana** [comment]
The issue is on page https://grafana.com/docs/loki/next/api/#grafana-loki-http-api
