### ISSUE TITLE
promtail/labels: Don't store __filename__ as it's a protected label.

### ISSUE THREAD

**Issue by CyrilPeponnet** [grafana/loki#548]
**Describe the bug**

Getting labels:

```
logcli --addr=http://192.168.50.10:3100 labels
2019/05/05 15:34:16 http://192.168.50.10:3100/api/prom/label
__filename__
app
application
component
container_id
service
stack
stream
type
```

As per the [documentation](https://github.com/grafana/loki/blob/master/docs/promtail.md)

```
Labels starting with __ (two underscores) are internal labels. They are not stored to the loki index and are invisible after Promtail. They "magically" appear from different sources.
```

`__filename__` is "magically" stored anyway.

Potentially caused by : https://github.com/grafana/loki/commit/600b24101ec7ddbddae4593020a3661c65686a4f#diff-4367a859d599222c7b8f83254f127bebR168

**To Reproduce**
1. Started loki lastest
2. Started promtail latest
3. Query: `labels`

**Expected behavior**

Protected labels should not be stored.

**Environment:**
 - Infrastructure: k8s, docker
 - Deployment tool: helm, stack

**Comment by tomwilkie** [comment]
Lets just call it `filename`.  Its needed to ensure uniqueness of the streams, which ensure we don't write out of order.

**Comment by steven-sheehy** [comment]
Fixed by https://github.com/grafana/loki/pull/552
