### ISSUE TITLE
Not Equals log stream selector doesn't work

### ISSUE THREAD

**Issue by dguendisch** [grafana/loki#550]
**Describe the bug**
It looks like using the not equals log stream selector `!=` doesn't work and returns results as if I hadn't used that label selector at all.

**To Reproduce**
In grafana explore tab I have a loki query `{instance="stg-cron-gcp-2glrp-wf-3515751877"}` returning me **44** results.
I extend the query and see e.g. that
`{instance="stg-cron-gcp-2glrp-wf-3515751877",container_name="wait"}` returns **25** results and
`{instance="stg-cron-gcp-2glrp-wf-3515751877",container_name="main"}`returns the other **19** results, so I obviously have only 2 containers: wait and main.

However using the not equals selector on the last label `{instance="stg-cron-gcp-2glrp-wf-3515751877",container_name!="wait"}` returns all **44** results (as in the very first query with the container_name selector).

**Expected behavior**
I expected the 19 results to be shown which don't match the label selector (as I've used the not-equals selector)

**Comment by Kuqd** [comment]
I could not reproduce this on latest. Do you have more informations ? I've found something else but nothing related.

**Comment by dguendisch** [comment]
I've updated loki to this image tag: `master-ff3e456` (5h old, the most current one).
Indeed, seems to work now, weird, my old image was just a few days old...
Well then, I'll close :)
