### ISSUE TITLE
lambda-promtail no longer working with basic auth

### ISSUE THREAD

**Issue by slim-bean** [grafana/loki#5518]
It looks like #5065 accidentally removed the code which sets the basic auth header on requests when the credentials are defined:

This code here: 

https://github.com/grafana/loki/pull/5065/files#diff-3e05d69520c09415677a800b675e72ed81465c0813fba9ea973ccd3c4c1528c2L112

Was not added to the new location where we send logs. Not sure if anything else was missed.

**Comment by dannykopping** [comment]
https://github.com/grafana/loki/pull/5503
I believe the author opened this to add it back.

**Comment by cstyan** [comment]
Thanks @dannykopping
