### ISSUE TITLE
promtail: A way to drop some logs lines given criterias

### ISSUE THREAD

**Issue by CyrilPeponnet** [grafana/loki#553]
**Is your feature request related to a problem? Please describe.**

Sometime you don't want to log some informations like tokens/ user info that could show up in services logs. Or you want to remove useless logs done by some services. Loki logging aggregation is cheap yes but sometimes useful logs are lost in noise.

**Describe the solution you'd like**

A way to drop logs lines all together or strip some part that are matching a regex for instance.

**Describe alternatives you've considered**

Looking away when I'm seeing sensitive information.

**Comment by Kuqd** [comment]
I need to check but I think this could be possible with the entry parser currently being developed.

**Comment by Kuqd** [comment]
@slim-bean we could achieve this with the entry_parser ?

**Comment by daixiang0** [comment]
I think drop rule can achieve this while need complex regex.

**Comment by devkws** [comment]
This might not be related, but I'm looking for a way to do something similar. For example I would want Loki to simply ignore debug and info logs.

**Comment by Kuqd** [comment]
Definitively something we can add into the current pipeline. For now you can just rewrite the output.

**Comment by nfrush** [comment]
@cyriltovena By re-write the output, do you mean write the output to null? Or how exactly does one go about mimicking a drop with a re-write?

**Comment by cyriltovena** [comment]
I meant you can rewrite the actual log line using our pipeline which may help in the meantime. We will definitively work on this issue.

**Comment by HarmtH** [comment]
I think this issues should have autoclosed when #1112 got merged.

For future googlers, [here](https://github.com/cyriltovena/loki/blob/master/docs/clients/promtail/stages/match.md#example) is a nice example for dropping log lines given certain criteria.

**Comment by cyriltovena** [comment]
Thanks you’re right !

**Comment by mlutfy** [comment]
Docs: https://grafana.com/docs/loki/latest/clients/promtail/stages/match/

(the link from the previous comment is 404)

**Comment by r0fls** [comment]
That will drop the whole log line, right? There is no way to drop given keys from the json, is there? e.g. dropping `{`.*password`: `.*'}` but preserving the rest of the json object.

**Comment by spstarr** [comment]
> I think this issue should have autoclosed when #1112 got merged.
> 
> For future googlers, [here](https://github.com/cyriltovena/loki/blob/master/docs/clients/promtail/stages/match.md#example) is a nice example for dropping log lines given certain criteria.

Now is:  https://github.com/cyriltovena/loki/blob/main/docs/sources/clients/promtail/stages/match.md
