### ISSUE TITLE
Use bucket per tenant option for multi tenant  Loki with s3 backend storage

### ISSUE THREAD

**Issue by LinTechSo** [grafana/loki#5530]
Hi, the current architecture of multi-tenant Loki is a directory for each tenant ID  under the existing bucket if we are using s3 backend storage. 

Is there a way to configure the Loki to create a bucket for each tenant instead of using directories per bucket?  (multi bucket option)

The problem is
Under multi-tenant architecture, there should be a way to monitor the space usage of each tenant with consideration of the retention time configuration.

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.

**Comment by JustinMason** [comment]
> Thank you for your question / support request. We try to keep GitHub issues strictly for bug reports and feature requests.

It seems like this is a "Feature Request", Bucket per tenant option for multi tenant Loki, or is this an Existing Feature of Loki and we are missing this configuration option?
