### ISSUE TITLE
label_format not working for question mark in the regex

### ISSUE THREAD

**Issue by yasharne** [grafana/loki#5549]
**Describe the bug**
I have some endpoints like these:
```
/v3/a/b/ABC-123/c
/v2/a/b/xyzABC-456/c
/v2/a/d?frequents=1
/v2/a/e?device_type=1
```
With this label format:
```
label_format endpoint=`{{regexReplaceAll "(.*/)(.*ABC-.*)(/.*)|(.*)(\?.*)" .request_uri "${1}{ID}${3}"}}`
```
But I get this error (I tried in both grafana and logcli):
```
parse error : stage '| label_format endpoint="{{regexReplaceAll \"(.*/)(.*ABC-.*)(/.*)|(.*)(\\?.*)\" .request_uri \"${1}{ID}${3}\"}}"' : invalid template for label 'endpoint': template: label:1: invalid syntax
```
I know there is something wrong with the question mark (?) as if I remove it, it will work but I don't know how to add the question mark, my regex works fine in https://regex101.com/ for golang

**To Reproduce**
1. Loki version 2.4.2

**Expected behavior**
Match the question mark

**Environment:**
 - Infrastructure: openshift
 - Deployment tool: helm

**Comment by dannykopping** [comment]
Thanks for reporting this @yasharne 

I was able to replicate the issue. I think you need to double-escape your `?`. When I did so, I got it to work:

```logql
{container="ingress-nginx"} |= `?` | json
  | label_format endpoint=`{{regexReplaceAll "(.*)\\?(.*)" .request_uri "${2}" }}`
```

This successfully returns everything after the `?` literal in the string.

**Comment by dannykopping** [comment]
I'm going to close this issue as it does not appear to be a bug, but please let me know if I have missed anything.
