### ISSUE TITLE
Is it possible to save log of k8s container pod that terminates with error?

### ISSUE THREAD

**Issue by kwon14** [grafana/loki#5555]
Hello. Thank you for your hard work.

Checking for loki introduction.
When the container pod in k8s is started and terminated with an error,
Can you save the log of that pod?
It is necessary to check what error the pod has terminated.

thank you.

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
