### ISSUE TITLE
Dynamic log path

### ISSUE THREAD

**Issue by VishalPhenom** [grafana/loki#5557]
We are using loki for logging.
we are sending request from different user and we want to change log path as per the user name.

lets say there are two user A and B. and we have define log path(in yaml file) "/tmp/loki" if user A request than logs should store to "/tmp/loki/A" and for B "/tmp/loki/B". 

is there any way we can define dynamic path for log? this user is not fix number it could N number.

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
