### ISSUE TITLE
[bug] logql: SelectSamples(), The latest 2-hour data is inaccurate

### ISSUE THREAD

**Issue by liguozhong** [grafana/loki#5574]
**Describe the bug**

The latest 2-hour data is inaccurate, it may be that the log in ingester cannot be deduplicated accurately.

loki logql:
sum (sum_over_time({module="api_server",operation="Agg_InvokeFunction"} | json  |unwrap aggCount [59s]))/60

prometheus promql:
sum(sum_over_time(fc_api_invoke_count{}[59s])/60)

![image](https://user-images.githubusercontent.com/9583245/157249487-f62a96e3-e4b9-48a9-982c-325a1bc2f2df.png)

**To Reproduce**
1. Started Loki (SHA or version)
2. Started Promtail (SHA or version) to tail '...'
3. Query: `{} term`

**Expected behavior**

<------------s3 logs--------------- >
<---------------------| [ingest logs]>
1s---------------------now-2h----now

loki querier Select Sample func should deduplicate the duplicate logs in ingest and s3, and the results in the last 2 hours should be consistent with prometheus promql result.  

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by liguozhong** [comment]
maybe 5470 PR has fix this issue. I will try
https://github.com/grafana/loki/pull/5470

**Comment by kavirajk** [comment]
That's correct. Got fixed in #5470. Closing this feel free to re-open if you think otherwise
