### ISSUE TITLE
Metric log_messages_total doesn't Account for All Log Messages

### ISSUE THREAD

**Issue by aapodoll** [grafana/loki#5601]
I am attempting to determine the number of logs per second going through my system in order to scale properly, and started using the metric log_messages_total. However it only supports log levels Debug, Info, Warn, and Error. When logs are labeled with other levels (example - Critical, Audit, Trace) they are missing from this metric, so the actual number of logs going through my system is significantly different than presented in the metric. 

All log messages should be accounted for in the log_messages_total metric. Either add a catch-all label such as Undefined for the log messages that don't have one of the predefined labels, or make the set of labels configurable. 

To get an accurate number of my logging rate, I am querying Loki directly - but this is quite a bit slower and more resource intensive than querying a metric.

**Comment by chaudum** [comment]
Hi @aapodoll 

I think you mix something up here. `loki_log_messages_total` is a metric that counts the amount of logs **produced by Loki**.
Loki only logs `debug`, `info`, `warn`, and `error`.

I _guess_ what you are looking for is a metric how many logs have been sent to / processed by Loki.

Metrics you can look at are:

For bytes/lines received on the distributors:

```
loki_distributor_lines_received_total
loki_distributor_bytes_received_total
```

For request latency:
```
loki_request_duration_seconds_count
```

**Comment by aapodoll** [comment]
Ah I see. Thanks for the info!
