### ISSUE TITLE
Doc

### ISSUE THREAD

**Issue by jhon-ye** [grafana/loki#5604]
### Deployment Doc 
```
Hi loki Team 
   i wanna use loki with micro mode, do you have any deployment doc with in k8s , i do not use helm
```

**Comment by chaudum** [comment]
Hey @jhon-ye,

Please submit questions in any of the following ways:
- On our [community forum](https://community.grafana.com/c/grafana-loki/41)
- To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
- In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

Github issues that are questions will be closed.

---

Setting up Loki in microservice mode is possible but we would not recommend it (therefore no docs). You can have a look at the [Helm templates](https://github.com/grafana/helm-charts/tree/main/charts/loki-distributed) to get an idea what's needed.
