### ISSUE TITLE
does promtail support collect json log from http protocol?

### ISSUE THREAD

**Issue by lddlww** [grafana/loki#5606]
data stream like follow：

service（send json log from http） ---->（collect json log from http，used like http server）promtail  ----> loki

**Comment by chaudum** [comment]
Hey @lddlww ,

Please submit questions in any of the following ways:

- On our [community forum](https://community.grafana.com/c/grafana-loki/41)
- To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
- In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

Github issues that are questions will be closed.

If you want to file a feature request, please use the "Feature request" issue template.
