### ISSUE TITLE
Bug: Restarting Loki yields "recovered from WAL segments with errors"

### ISSUE THREAD

**Issue by jfolz** [grafana/loki#5612]
**Describe the bug**
Restarting (single binary) Loki sometimes, but not always results in the following log message:

> Recovered from WAL segments with errors. Some streams and/or entries were likely not recovered due to WAL segment file corruptions (or WAL file deletions while Loki is running). No administrator action is needed and data loss is only a possibility if more than (replication factor / 2 + 1) ingesters suffer from this.

The default for replication factor appears to be 3, though since this is not a cluster deployment I am not sure whether that matters. There is should only be one ingester. We also set replication factor 1 for the ingester ring (see below for the full config).
According to the message that means data may have been lost. I don't have separate copies of all the logs, so I cannot check whether any data loss actually occurred.

So far these errors happened with version 2.3.0. For obvious reasons I have only recently updated to 2.4.2 and generally avoid restarting Loki as much as possible. I have not yet restarted since the update. I suspect this issue will be very hard if not impossible to reproduce, so I'd like to ask for some suggestions regarding config parameters to prevent/workaround/minimize the issue.

**To Reproduce**
1. Started Loki 2.3.0
2. Let Loki ingest logs for a while - the WAL replay error has happened after Loki was running for less than one hour or several months
3. Restart the loki service

**Expected behavior**
WAL replay works with no scary log messages about data loss.

**Environment:**
 - Infrastructure: bare-metal
 - Deployment tool: systemd service

**Screenshots, Promtail config, or terminal output**
Console message after restart of the Loki service:
```
level=error ts=2022-03-07T13:42:07.693025601Z caller=ingester.go:385 msg="Recovered from WAL segments with errors. Some streams and/or entries were likely not recovered due to WAL segment file corruptions (or WAL file deletions while Loki is running). No administrator action is needed and data loss is only a possibility if more than (replication factor / 2 + 1) ingesters suffer from this." elapsed=291.071513ms
```

[Loki config](https://github.com/grafana/loki/files/8238318/loki.yaml.txt)

[Loki systemd service file](https://github.com/grafana/loki/files/8238328/loki.service.txt)

**Comment by jfolz** [comment]
One change I have just made is to replace the SIGTERM via `ExecStop` directive with the following, possibly more "gentle" shutdown procedure:
```
TimeoutStopSec=60
KillSignal=SIGINT
```

Any further suggestions are very welcome. If a clustered deployment would provide better resilience against data loss I may also consider that.

**Comment by dreyTee** [comment]
Still see that happens, even after gentle restart suggested.
 any clues?

**Comment by jfolz** [comment]
@dreyTee Nothing new here. It happens even on the most recent version 2.9.3. There is [this](https://grafana.com/docs/loki/latest/reference/api/#flush-in-memory-chunks-and-shut-down) API that sounds like it would do something, but even this leads to WAL errors. Since restarts can lead to loss of data (at least I haven't been told otherwise), we're updating very infrequently and can't make regular backups, which just plain sucks.
