### ISSUE TITLE
Single binary Loki with memberlist config

### ISSUE THREAD

**Issue by ahmedTouati** [grafana/loki#5625]
**Describe the bug**
In Loki there are three modes monolithic, simple scalable and microservices modes, and you can run single binary loki as Horizontally scalable also according to architecture docs:
**Horizontally scale up a monolithic mode deployment to more instances by using a shared object store, and by configuring the [memberlist_config section 1](https://grafana.com/docs/loki/latest/configuration/#memberlist_config) to share state between all instances.

High availability can be configured by running two Loki instances using memberlist_config configuration and a shared object store.**

So i followed this example configuration for memberlist config ([Examples | Grafana Labs](https://grafana.com/docs/loki/latest/configuration/examples/#almost-zero-dependencyyaml)) in a single binary loki installation and increased replicas to two (loki-0,loki-1).
For **join_members**: i used loki headless service (loki-headless.loki.svc.cluster.local:3100) since loki-gossip-ring service is not available in this installation, but loki always fail to resolve it:
```
ts=2022-03-15T09:14:24.010697792Z caller=memberlist_logger.go:74 level=warn msg="Failed to resolve loki-headless.loki.svc.cluster.local:3100: lookup loki-headless.loki.svc.cluster.local on 172.20.0.10:53: no such host"
```
**Environment:**
 - Infrastructure: EKS
 - Deployment tool: helm
 - Loki: v2.3.0

**Comment by chaudum** [comment]
Hey @ahmedTouati 

It appears that you are using the wrong port for the `join_members` setting: `loki-headless.loki.svc.cluster.local:3100` <- you specified 3100, which is the HTTP port. However, you need to use the memberlist port, which is `7946` (see your linked docs example).

**Comment by ahmedTouati** [comment]
> Hey @ahmedTouati
> 
> It appears that you are using the wrong port for the `join_members` setting: `loki-headless.loki.svc.cluster.local:3100` <- you specified 3100, which is the HTTP port. However, you need to use the memberlist port, which is `7946` (see your linked docs example).

No i used **bind_port: 7946** then **loki-headless.loki.svc.cluster.local:7946** but the port still not exposed
