### ISSUE TITLE
Once syslog added it fails to start the service.

### ISSUE THREAD

**Issue by daven1985** [grafana/loki#5632]
Can't start Promtail once I enabled syslog with external host.

Standard setup to monitor itself and grafana logs. I tried to add Syslog from my Unifi controller but it errors out when I do that.

Status and when running just promtail....

```
ladmin@sr-operations:/etc/promtail$ sudo systemctl status promtail
 promtail.service - Promtail service
     Loaded: loaded (/etc/systemd/system/promtail.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2022-03-16 15:27:39 AEDT; 6s ago
    Process: 2355 ExecStart=/usr/local/bin/promtail -config.file /etc/promtail/config.yaml (code=exited, status=1/FAILURE)
   Main PID: 2355 (code=exited, status=1/FAILURE)

Mar 16 15:27:38 sr-operations systemd[1]: Started Promtail service.
Mar 16 15:27:39 sr-operations promtail[2355]: level=error ts=2022-03-16T04:27:39.276316538Z caller=main.go:115 msg="error creating promtail" error="failed to make syslog target manager: er>
Mar 16 15:27:39 sr-operations systemd[1]: promtail.service: Main process exited, code=exited, status=1/FAILURE
Mar 16 15:27:39 sr-operations systemd[1]: promtail.service: Failed with result 'exit-code'.
ladmin@sr-operations:/etc/promtail$ promtail
level=error ts=2022-03-16T04:27:49.281233902Z caller=main.go:115 msg="error creating promtail" error="at least one client config should be provided"
ladmin@sr-operations:/etc/promtail$ 

```

Config from: /etc/promtail/config.yaml

```
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /data/promtail/positions.yaml

clients:
  - url: http://127.0.0.1:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
- job_name: grafanalogs
  static_configs:
  - targets:
      - localhost
    labels:
      job: grafana
      __path__: /var/log/grafana/grafana.log
- job_name: unifi
  syslog:
    listen_address: 192.168.1.1:1514
    idle_timeout: 60s
    label_structured_data: yes
    labels:
      job: "unifi"
  relabel_configs:
    - source_labels: ['__syslog_message_hostname']
      target_label: 'host'
```

**Comment by dannykopping** [comment]
What version of promtail are you using @daven1985?

Please run `journalctl -u promtail` and paste the lines produced by a failed start.

**Comment by daven1985** [comment]
I managed to get it started. Though I can't have a listen_address in there.

The last issue now... and I will submit another ticket is that no logs are actually coming in.

```
-- Logs begin at Fri 2022-03-04 09:45:51 AEDT, end at Thu 2022-03-17 10:16:35 AEDT. --
Mar 04 11:01:49 sr-operations systemd[1]: Started Promtail service.
Mar 04 11:01:49 sr-operations promtail[18846]: level=info ts=2022-03-04T00:01:49.901900247Z caller=server.go:260 http=[::]:9080 grpc=[::]:33175 msg="server listening on addresses"
Mar 04 11:01:49 sr-operations promtail[18846]: level=info ts=2022-03-04T00:01:49.903379274Z caller=main.go:119 msg="Starting Promtail" version="(version=2.4.2, branch=HEAD, revision=525040a32)"
Mar 04 11:01:54 sr-operations promtail[18846]: level=info ts=2022-03-04T00:01:54.905979982Z caller=filetargetmanager.go:255 msg="Adding target" key="/var/log/*log:{job=\"varlogs\"}"
Mar 04 11:01:54 sr-operations promtail[18846]: level=info ts=2022-03-04T00:01:54.938185175Z caller=filetargetmanager.go:255 msg="Adding target" key="/var/log/grafana/grafana.log:{job=\"grafana\">
Mar 04 11:01:54 sr-operations promtail[18846]: ts=2022-03-04T00:01:54.940889024Z caller=log.go:168 level=info msg="Seeked /var/log/ubuntu-advantage.log - &{Offset:0 Whence:0}"
Mar 04 11:01:54 sr-operations promtail[18846]: level=info ts=2022-03-04T00:01:54.940988426Z caller=tailer.go:126 component=tailer msg="tail routine: started" path=/var/log/ubuntu-advantage.log
Mar 04 11:01:54 sr-operations promtail[18846]: ts=2022-03-04T00:01:54.941079728Z caller=log.go:168 level=info msg="Seeked /var/log/cloud-init.log - &{Offset:0 Whence:0}"
Mar 04 11:01:54 sr-operations promtail[18846]: level=info ts=2022-03-04T00:01:54.941104428Z caller=tailer.go:126 component=tailer msg="tail routine: started" path=/var/log/cloud-init.log
Mar 04 11:01:54 sr-operations promtail[18846]: ts=2022-03-04T00:01:54.941883843Z caller=log.go:168 level=info msg="Seeked /var/log/auth.log - &{Offset:0 Whence:0}"
Mar 04 11:01:54 sr-operations promtail[18846]: level=info ts=2022-03-04T00:01:54.941937044Z caller=tailer.go:126 component=tailer msg="tail routine: started" path=/var/log/auth.log
Mar 04 11:01:54 sr-operations promtail[18846]: ts=2022-03-04T00:01:54.942020445Z caller=log.go:168 level=info msg="Seeked /var/log/faillog - &{Offset:0 Whence:0}"
Mar 04 11:01:54 sr-operations promtail[18846]: level=info ts=2022-03-04T00:01:54.942044246Z caller=tailer.go:126 component=tailer msg="tail routine: started" path=/var/log/faillog
Mar 04 11:01:54 sr-operations promtail[18846]: ts=2022-03-04T00:01:54.942121647Z caller=log.go:168 level=info msg="Seeked /var/log/dpkg.log - &{Offset:0 Whence:0}"
Mar 04 11:01:54 sr-operations promtail[18846]: level=info ts=2022-03-04T00:01:54.942142947Z caller=tailer.go:126 component=tailer msg="tail routine: started" path=/var/log/dpkg.log
Mar 04 11:01:54 sr-operations promtail[18846]: ts=2022-03-04T00:01:54.942217549Z caller=log.go:168 level=info msg="Seeked /var/log/cloud-init-output.log - &{Offset:0 Whence:0}"
Mar 04 11:01:54 sr-operations promtail[18846]: level=info ts=2022-03-04T00:01:54.942505454Z caller=tailer.go:126 component=tailer msg="tail routine: started" path=/var/log/cloud-init-output.log
Mar 04 11:01:54 sr-operations promtail[18846]: ts=2022-03-04T00:01:54.942654157Z caller=log.go:168 level=info msg="Seeked /var/log/bootstrap.log - &{Offset:0 Whence:0}"
Mar 04 11:01:54 sr-operations promtail[18846]: level=info ts=2022-03-04T00:01:54.942721158Z caller=tailer.go:126 component=tailer msg="tail routine: started" path=/var/log/bootstrap.log
Mar 04 11:01:54 sr-operations promtail[18846]: ts=2022-03-04T00:01:54.942800759Z caller=log.go:168 level=info msg="Seeked /var/log/alternatives.log - &{Offset:0 Whence:0}"
Mar 04 11:01:54 sr-operations promtail[18846]: level=info ts=2022-03-04T00:01:54.94282146Z caller=tailer.go:126 component=tailer msg="tail routine: started" path=/var/log/alternatives.log
Mar 04 11:01:54 sr-operations promtail[18846]: ts=2022-03-04T00:01:54.942951162Z caller=log.go:168 level=info msg="Seeked /var/log/ubuntu-advantage-timer.log - &{Offset:0 Whence:0}"
Mar 04 11:01:54 sr-operations promtail[18846]: level=info ts=2022-03-04T00:01:54.942971863Z caller=tailer.go:126 component=tailer msg="tail routine: started" path=/var/log/ubuntu-advantage-timer>
Mar 04 11:01:54 sr-operations promtail[18846]: ts=2022-03-04T00:01:54.943409571Z caller=log.go:168 level=info msg="Seeked /var/log/kern.log - &{Offset:0 Whence:0}"
Mar 04 11:01:54 sr-operations promtail[18846]: level=info ts=2022-03-04T00:01:54.943503672Z caller=tailer.go:126 component=tailer msg="tail routine: started" path=/var/log/kern.log
Mar 04 11:01:54 sr-operations promtail[18846]: ts=2022-03-04T00:01:54.943621275Z caller=log.go:168 level=info msg="Seeked /var/log/syslog - &{Offset:0 Whence:0}"
Mar 04 11:01:54 sr-operations promtail[18846]: level=info ts=2022-03-04T00:01:54.943687676Z caller=tailer.go:126 component=tailer msg="tail routine: started" path=/var/log/syslog
Mar 04 11:01:54 sr-operations promtail[18846]: ts=2022-03-04T00:01:54.943786678Z caller=log.go:168 level=info msg="Seeked /var/log/lastlog - &{Offset:0 Whence:0}"
Mar 04 11:01:54 sr-operations promtail[18846]: level=info ts=2022-03-04T00:01:54.943827178Z caller=tailer.go:126 component=tailer msg="tail routine: started" path=/var/log/lastlog
Mar 04 11:01:54 sr-operations promtail[18846]: ts=2022-03-04T00:01:54.958193943Z caller=log.go:168 level=info msg="Seeked /var/log/grafana/grafana.log - &{Offset:0 Whence:0}"
Mar 04 11:01:55 sr-operations promtail[18846]: level=info ts=2022-03-04T00:01:54.958457548Z caller=tailer.go:126 component=tailer msg="tail routine: started" path=/var/log/grafana/grafana.log
Mar 04 11:02:13 sr-operations promtail[18846]: ts=2022-03-04T00:02:13.905794689Z caller=log.go:168 level=info msg="Re-opening moved/deleted file /var/log/grafana/grafana.log ..."
Mar 04 11:02:13 sr-operations promtail[18846]: ts=2022-03-04T00:02:13.906898508Z caller=log.go:168 level=info msg="Successfully reopened /var/log/grafana/grafana.log"
Mar 07 09:02:55 sr-operations promtail[18846]: ts=2022-03-06T22:02:55.711358996Z caller=log.go:168 level=info msg="Re-opening moved/deleted file /var/log/grafana/grafana.log ..."
Mar 07 09:02:55 sr-operations promtail[18846]: ts=2022-03-06T22:02:55.711537097Z caller=log.go:168 level=info msg="Successfully reopened /var/log/grafana/grafana.log"
Mar 07 09:03:04 sr-operations promtail[18846]: ts=2022-03-06T22:03:04.056208747Z caller=log.go:168 level=info msg="Re-opening moved/deleted file /var/log/syslog ..."
Mar 07 09:03:04 sr-operations promtail[18846]: ts=2022-03-06T22:03:04.05628876Z caller=log.go:168 level=info msg="Successfully reopened /var/log/syslog"
Mar 07 09:03:04 sr-operations promtail[18846]: ts=2022-03-06T22:03:04.056341768Z caller=log.go:168 level=info msg="Re-opening moved/deleted file /var/log/kern.log ..."
Mar 07 09:03:04 sr-operations promtail[18846]: ts=2022-03-06T22:03:04.056374773Z caller=log.go:168 level=info msg="Successfully reopened /var/log/kern.log"
Mar 07 09:03:04 sr-operations promtail[18846]: ts=2022-03-06T22:03:04.056418179Z caller=log.go:168 level=info msg="Re-opening moved/deleted file /var/log/auth.log ..."
Mar 07 09:03:04 sr-operations promtail[18846]: ts=2022-03-06T22:03:04.056450884Z caller=log.go:168 level=info msg="Successfully reopened /var/log/auth.log"
-- Reboot --
Mar 08 16:06:45 sr-operations systemd[1]: Started Promtail service.
Mar 08 16:06:47 sr-operations promtail[1454]: level=info ts=2022-03-08T05:06:47.589061617Z caller=server.go:260 http=[::]:9080 grpc=[::]:38087 msg="server listening on addresses"
Mar 08 16:06:47 sr-operations promtail[1454]: level=info ts=2022-03-08T05:06:47.59467366Z caller=main.go:119 msg="Starting Promtail" version="(version=2.4.2, branch=HEAD, revision=525040a32)"
Mar 08 16:06:52 sr-operations promtail[1454]: level=info ts=2022-03-08T05:06:52.56417848Z caller=filetargetmanager.go:255 msg="Adding target" key="/var/log/*log:{job=\"varlogs\"}"
Mar 08 16:06:52 sr-operations promtail[1454]: level=info ts=2022-03-08T05:06:52.567533205Z caller=filetargetmanager.go:255 msg="Adding target" key="/var/log/grafana/grafana.log:{job=\"grafana\"}"
Mar 08 16:06:52 sr-operations promtail[1454]: ts=2022-03-08T05:06:52.580964905Z caller=log.go:168 level=info msg="Seeked /var/log/ubuntu-advantage.log - &{Offset:0 Whence:0}"
Mar 08 16:06:52 sr-operations promtail[1454]: level=info ts=2022-03-08T05:06:52.582348163Z caller=tailer.go:126 component=tailer msg="tail routine: started" path=/var/log/ubuntu-advantage.log
Mar 08 16:06:52 sr-operations promtail[1454]: ts=2022-03-08T05:06:52.586659666Z caller=log.go:168 level=info msg="Seeked /var/log/cloud-init.log - &{Offset:80464 Whence:0}"
Mar 08 16:06:52 sr-operations promtail[1454]: level=info ts=2022-03-08T05:06:52.592678286Z caller=tailer.go:126 component=tailer msg="tail routine: started" path=/var/log/cloud-init.log
Mar 08 16:06:52 sr-operations promtail[1454]: ts=2022-03-08T05:06:52.593744785Z caller=log.go:168 level=info msg="Seeked /var/log/auth.log - &{Offset:0 Whence:0}"
Mar 08 16:06:52 sr-operations promtail[1454]: level=info ts=2022-03-08T05:06:52.594268282Z caller=tailer.go:126 component=tailer msg="tail routine: started" path=/var/log/auth.log
```

**Comment by dannykopping** [comment]
Great to hear you found the solution - please share it so others can benefit, too.

Please don't open an issue for the other problem, rather reach out to us here:

  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

We try to keep GitHub issues strictly for bug reports and feature requests.

**Comment by daven1985** [comment]
Will do. Thanks for letting me know.

**Comment by Ray-Db** [comment]
> I managed to get it started. Though I can't have a listen_address in there.
> 
> The last issue now... and I will submit another ticket is that no logs are actually coming in.
> 
> ```
> -- Logs begin at Fri 2022-03-04 09:45:51 AEDT, end at Thu 2022-03-17 10:16:35 AEDT. --
> Mar 04 11:01:49 sr-operations systemd[1]: Started Promtail service.
> Mar 04 11:01:49 sr-operations promtail[18846]: level=info ts=2022-03-04T00:01:49.901900247Z caller=server.go:260 http=[::]:9080 grpc=[::]:33175 msg="server listening on addresses"
> Mar 04 11:01:49 sr-operations promtail[18846]: level=info ts=2022-03-04T00:01:49.903379274Z caller=main.go:119 msg="Starting Promtail" version="(version=2.4.2, branch=HEAD, revision=525040a32)"
> Mar 04 11:01:54 sr-operations promtail[18846]: level=info ts=2022-03-04T00:01:54.905979982Z caller=filetargetmanager.go:255 msg="Adding target" key="/var/log/*log:{job=\"varlogs\"}"
> Mar 04 11:01:54 sr-operations promtail[18846]: level=info ts=2022-03-04T00:01:54.938185175Z caller=filetargetmanager.go:255 msg="Adding target" key="/var/log/grafana/grafana.log:{job=\"grafana\">
> Mar 04 11:01:54 sr-operations promtail[18846]: ts=2022-03-04T00:01:54.940889024Z caller=log.go:168 level=info msg="Seeked /var/log/ubuntu-advantage.log - &{Offset:0 Whence:0}"
> Mar 04 11:01:54 sr-operations promtail[18846]: level=info ts=2022-03-04T00:01:54.940988426Z caller=tailer.go:126 component=tailer msg="tail routine: started" path=/var/log/ubuntu-advantage.log
> Mar 04 11:01:54 sr-operations promtail[18846]: ts=2022-03-04T00:01:54.941079728Z caller=log.go:168 level=info msg="Seeked /var/log/cloud-init.log - &{Offset:0 Whence:0}"
> Mar 04 11:01:54 sr-operations promtail[18846]: level=info ts=2022-03-04T00:01:54.941104428Z caller=tailer.go:126 component=tailer msg="tail routine: started" path=/var/log/cloud-init.log
> Mar 04 11:01:54 sr-operations promtail[18846]: ts=2022-03-04T00:01:54.941883843Z caller=log.go:168 level=info msg="Seeked /var/log/auth.log - &{Offset:0 Whence:0}"
> Mar 04 11:01:54 sr-operations promtail[18846]: level=info ts=2022-03-04T00:01:54.941937044Z caller=tailer.go:126 component=tailer msg="tail routine: started" path=/var/log/auth.log
> Mar 04 11:01:54 sr-operations promtail[18846]: ts=2022-03-04T00:01:54.942020445Z caller=log.go:168 level=info msg="Seeked /var/log/faillog - &{Offset:0 Whence:0}"
> Mar 04 11:01:54 sr-operations promtail[18846]: level=info ts=2022-03-04T00:01:54.942044246Z caller=tailer.go:126 component=tailer msg="tail routine: started" path=/var/log/faillog
> Mar 04 11:01:54 sr-operations promtail[18846]: ts=2022-03-04T00:01:54.942121647Z caller=log.go:168 level=info msg="Seeked /var/log/dpkg.log - &{Offset:0 Whence:0}"
> Mar 04 11:01:54 sr-operations promtail[18846]: level=info ts=2022-03-04T00:01:54.942142947Z caller=tailer.go:126 component=tailer msg="tail routine: started" path=/var/log/dpkg.log
> Mar 04 11:01:54 sr-operations promtail[18846]: ts=2022-03-04T00:01:54.942217549Z caller=log.go:168 level=info msg="Seeked /var/log/cloud-init-output.log - &{Offset:0 Whence:0}"
> Mar 04 11:01:54 sr-operations promtail[18846]: level=info ts=2022-03-04T00:01:54.942505454Z caller=tailer.go:126 component=tailer msg="tail routine: started" path=/var/log/cloud-init-output.log
> Mar 04 11:01:54 sr-operations promtail[18846]: ts=2022-03-04T00:01:54.942654157Z caller=log.go:168 level=info msg="Seeked /var/log/bootstrap.log - &{Offset:0 Whence:0}"
> Mar 04 11:01:54 sr-operations promtail[18846]: level=info ts=2022-03-04T00:01:54.942721158Z caller=tailer.go:126 component=tailer msg="tail routine: started" path=/var/log/bootstrap.log
> Mar 04 11:01:54 sr-operations promtail[18846]: ts=2022-03-04T00:01:54.942800759Z caller=log.go:168 level=info msg="Seeked /var/log/alternatives.log - &{Offset:0 Whence:0}"
> Mar 04 11:01:54 sr-operations promtail[18846]: level=info ts=2022-03-04T00:01:54.94282146Z caller=tailer.go:126 component=tailer msg="tail routine: started" path=/var/log/alternatives.log
> Mar 04 11:01:54 sr-operations promtail[18846]: ts=2022-03-04T00:01:54.942951162Z caller=log.go:168 level=info msg="Seeked /var/log/ubuntu-advantage-timer.log - &{Offset:0 Whence:0}"
> Mar 04 11:01:54 sr-operations promtail[18846]: level=info ts=2022-03-04T00:01:54.942971863Z caller=tailer.go:126 component=tailer msg="tail routine: started" path=/var/log/ubuntu-advantage-timer>
> Mar 04 11:01:54 sr-operations promtail[18846]: ts=2022-03-04T00:01:54.943409571Z caller=log.go:168 level=info msg="Seeked /var/log/kern.log - &{Offset:0 Whence:0}"
> Mar 04 11:01:54 sr-operations promtail[18846]: level=info ts=2022-03-04T00:01:54.943503672Z caller=tailer.go:126 component=tailer msg="tail routine: started" path=/var/log/kern.log
> Mar 04 11:01:54 sr-operations promtail[18846]: ts=2022-03-04T00:01:54.943621275Z caller=log.go:168 level=info msg="Seeked /var/log/syslog - &{Offset:0 Whence:0}"
> Mar 04 11:01:54 sr-operations promtail[18846]: level=info ts=2022-03-04T00:01:54.943687676Z caller=tailer.go:126 component=tailer msg="tail routine: started" path=/var/log/syslog
> Mar 04 11:01:54 sr-operations promtail[18846]: ts=2022-03-04T00:01:54.943786678Z caller=log.go:168 level=info msg="Seeked /var/log/lastlog - &{Offset:0 Whence:0}"
> Mar 04 11:01:54 sr-operations promtail[18846]: level=info ts=2022-03-04T00:01:54.943827178Z caller=tailer.go:126 component=tailer msg="tail routine: started" path=/var/log/lastlog
> Mar 04 11:01:54 sr-operations promtail[18846]: ts=2022-03-04T00:01:54.958193943Z caller=log.go:168 level=info msg="Seeked /var/log/grafana/grafana.log - &{Offset:0 Whence:0}"
> Mar 04 11:01:55 sr-operations promtail[18846]: level=info ts=2022-03-04T00:01:54.958457548Z caller=tailer.go:126 component=tailer msg="tail routine: started" path=/var/log/grafana/grafana.log
> Mar 04 11:02:13 sr-operations promtail[18846]: ts=2022-03-04T00:02:13.905794689Z caller=log.go:168 level=info msg="Re-opening moved/deleted file /var/log/grafana/grafana.log ..."
> Mar 04 11:02:13 sr-operations promtail[18846]: ts=2022-03-04T00:02:13.906898508Z caller=log.go:168 level=info msg="Successfully reopened /var/log/grafana/grafana.log"
> Mar 07 09:02:55 sr-operations promtail[18846]: ts=2022-03-06T22:02:55.711358996Z caller=log.go:168 level=info msg="Re-opening moved/deleted file /var/log/grafana/grafana.log ..."
> Mar 07 09:02:55 sr-operations promtail[18846]: ts=2022-03-06T22:02:55.711537097Z caller=log.go:168 level=info msg="Successfully reopened /var/log/grafana/grafana.log"
> Mar 07 09:03:04 sr-operations promtail[18846]: ts=2022-03-06T22:03:04.056208747Z caller=log.go:168 level=info msg="Re-opening moved/deleted file /var/log/syslog ..."
> Mar 07 09:03:04 sr-operations promtail[18846]: ts=2022-03-06T22:03:04.05628876Z caller=log.go:168 level=info msg="Successfully reopened /var/log/syslog"
> Mar 07 09:03:04 sr-operations promtail[18846]: ts=2022-03-06T22:03:04.056341768Z caller=log.go:168 level=info msg="Re-opening moved/deleted file /var/log/kern.log ..."
> Mar 07 09:03:04 sr-operations promtail[18846]: ts=2022-03-06T22:03:04.056374773Z caller=log.go:168 level=info msg="Successfully reopened /var/log/kern.log"
> Mar 07 09:03:04 sr-operations promtail[18846]: ts=2022-03-06T22:03:04.056418179Z caller=log.go:168 level=info msg="Re-opening moved/deleted file /var/log/auth.log ..."
> Mar 07 09:03:04 sr-operations promtail[18846]: ts=2022-03-06T22:03:04.056450884Z caller=log.go:168 level=info msg="Successfully reopened /var/log/auth.log"
> -- Reboot --
> Mar 08 16:06:45 sr-operations systemd[1]: Started Promtail service.
> Mar 08 16:06:47 sr-operations promtail[1454]: level=info ts=2022-03-08T05:06:47.589061617Z caller=server.go:260 http=[::]:9080 grpc=[::]:38087 msg="server listening on addresses"
> Mar 08 16:06:47 sr-operations promtail[1454]: level=info ts=2022-03-08T05:06:47.59467366Z caller=main.go:119 msg="Starting Promtail" version="(version=2.4.2, branch=HEAD, revision=525040a32)"
> Mar 08 16:06:52 sr-operations promtail[1454]: level=info ts=2022-03-08T05:06:52.56417848Z caller=filetargetmanager.go:255 msg="Adding target" key="/var/log/*log:{job=\"varlogs\"}"
> Mar 08 16:06:52 sr-operations promtail[1454]: level=info ts=2022-03-08T05:06:52.567533205Z caller=filetargetmanager.go:255 msg="Adding target" key="/var/log/grafana/grafana.log:{job=\"grafana\"}"
> Mar 08 16:06:52 sr-operations promtail[1454]: ts=2022-03-08T05:06:52.580964905Z caller=log.go:168 level=info msg="Seeked /var/log/ubuntu-advantage.log - &{Offset:0 Whence:0}"
> Mar 08 16:06:52 sr-operations promtail[1454]: level=info ts=2022-03-08T05:06:52.582348163Z caller=tailer.go:126 component=tailer msg="tail routine: started" path=/var/log/ubuntu-advantage.log
> Mar 08 16:06:52 sr-operations promtail[1454]: ts=2022-03-08T05:06:52.586659666Z caller=log.go:168 level=info msg="Seeked /var/log/cloud-init.log - &{Offset:80464 Whence:0}"
> Mar 08 16:06:52 sr-operations promtail[1454]: level=info ts=2022-03-08T05:06:52.592678286Z caller=tailer.go:126 component=tailer msg="tail routine: started" path=/var/log/cloud-init.log
> Mar 08 16:06:52 sr-operations promtail[1454]: ts=2022-03-08T05:06:52.593744785Z caller=log.go:168 level=info msg="Seeked /var/log/auth.log - &{Offset:0 Whence:0}"
> Mar 08 16:06:52 sr-operations promtail[1454]: level=info ts=2022-03-08T05:06:52.594268282Z caller=tailer.go:126 component=tailer msg="tail routine: started" path=/var/log/auth.log
> ```

Hello,

How you manage to resolved the issue with  Promtail

**Comment by Jay-Sekar** [comment]
Hi could you please tell me how you managed to resolve that error
i am also getting the same error, mine Red hat based linux,the status always says activating
[jays@aws-euw2-stg-expressbe01 system]$ sudo systemctl status promtail
● promtail.service - Promtail service
   Loaded: loaded (/etc/systemd/system/promtail.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2023-11-05 14:10:05 UTC; 1s ago
  Process: 1869605 ExecStart=/usr/bin/promtail -config.file /etc/promtail/config.yml (code=exited, status=1/FAI>
 Main PID: 1869605 (code=exited, status=1/FAILURE)

Nov 05 14:10:05 aws-euw2-stg-expressbe01 systemd[1]: promtail.service: Main process exited, code=exited, status>
Nov 05 14:10:05 aws-euw2-stg-expressbe01 systemd[1]: promtail.service: Failed with result 'exit-code'.
