### ISSUE TITLE
loki 和 promtail 在同一个node 报错context deadline exceeded  

### ISSUE THREAD

**Issue by liujinyou** [grafana/loki#5637]
I installed loki-stack:2.6.1 with helm, and the promtail on the same node as loki reported the following error
And grafana and loki also reported a 502 error on the same node
level=warn ts=2022-03-16T09:22:45.909618063Z caller=client.go:288 component=client host=loki:3100 msg="error sending batch, will retry" status=-1 error="Post \"http://loki:3100/loki/api/v1/push\": context deadline exceeded"

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
