### ISSUE TITLE
Multiple table/schema for multiple applications logs

### ISSUE THREAD

**Issue by haresh1288** [grafana/loki#5639]
Hello, 

We have need to persist multiple applications logs and some of the application logs will have less number of days retention period time,
while some of the application required more number of days to retain the logs.

Is there any kind of configuration where we can have multiple Table/Schema with their own retention period ? Or application level logs retention period ?

Thanks in advance.

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
