### ISSUE TITLE
combine value of two lables in promtail config

### ISSUE THREAD

**Issue by VenkateswaranJ** [grafana/loki#5654]
How to add the values of multiple labels and assign them to another label in promtail config?

    scrape_configs:
      - job_name: journal
        journal:
          max_age: 12h
        relabel_configs:
        - source_labels: ['__journal__machine_id']
          target_label: 'HostId'
        - source_labels: ['__journal__hostname']
          target_label: 'HostName'
        - source_labels: ['__journal_syslog_identifier']
          target_label: 'ApplicationName'
        pipeline_stages:
        - match:
            selector: '{ApplicationName="test-app"}'
            stages:
            - static_labels:
                OriginId: //here I want to asign HostId+HostName+ApplicationName

In the end, I expect the value of label OriginId would be HostId+HostName+ApplicationName

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
