### ISSUE TITLE
Loki Run Not Auto Create  Cassandra Table

### ISSUE THREAD

**Issue by jhon-ye** [grafana/loki#5656]
**Describe the bug**
When use index store with Cassandra with args {-config.file=xxx, -target=write} ,if not init moudule named "table-manager" 
in code i can thank it support auto create table

version:2.4.2

**To Reproduce**
in loki.go i edit func setupModuleManager 
Ingester: {Store, Server, MemberlistKV, TenantConfigs, TableManager},

**Expected behavior**
i want run loki with args {-config.file=xxx, -target=write} ,it can auto create cassandra table

**Environment:**
 - k8s , loki version 2.4.2
 - Deployment tool: [kubectl]

**Comment by honganan** [comment]
-target=write,table-manager, it's mentioned here:https://grafana.com/docs/loki/latest/upgrading/
