### ISSUE TITLE
Ideas about a better query split strategy 

### ISSUE THREAD

**Issue by honganan** [grafana/loki#5694]
**Is your feature request related to a problem? Please describe.**
Loki can split a big query by interval, but if `split_by_interval` is low, like 1min, it processes many duplicate data which reduced it's query speed. If interval is set to higher it have risk of causing Querier OOM.

For example some of our application or service produce 10TiB logs per day, some others produce only GiBs. We need to set the interval below 1min and `parallelism` to low(like 1) for big apps, otherwise will cause OOM. Our pod size is 2C8G now.

Even we can set different split interval value for each tenant, but `parallelism` cannot be different, which makes throughput limited when query small apps.

**Describe the solution you'd like**

Is there a better split strategy can adapt both big and small apps? I can image two ways it can performs better:
1) Split query by chunk number or data size to process finally: If we can query index first and calculate how many chunks to process, then do the split by chunk number, as chunk size is almost the same, the split will be more scientific. We can create a new component serve for index query and management, then we can separate index query and chunk query in Frontend component. Index-gateway can also merged into the new component.
2) If split query won't cause process duplicate data, we can just use runtime limit config different `split_by_interval` for different tenant(app) (I am not sure we can do it);

**Describe alternatives you've considered**
A better query split strategy like above first idea.

**Additional context**
I know to realize the idea needs to change a lot, we can just discuss first.
what's more, Loki is an amazing product, it reduced huge costs in some of our datacenter.

**Comment by jlynch93** [comment]
I'd like to bump this as we are seeing a similar issue in production. or if anyone has found a solution to this problem? we typicall will either see an oom or the reponse will timeout but when using the loki cli we can query for a larger range and not run into the issues.

**Comment by jeschkies** [comment]
I think this relates to @owen-d's work on TSDB that allows better query planning.

**Comment by honganan** [comment]
> I think this relates to @owen-d's work on TSDB that allows better query planning.

Sounds exciting! I noticed there are new codes about TSDB committed. Do your know if there is any document about it, likes planning, designment or something else?

**Comment by honganan** [comment]
Since the new `bounded` split strategy introduced in 3.0, I think this can be closed now! That's Wonderful! @owen-d
