### ISSUE TITLE
HTTP request from logs

### ISSUE THREAD

**Issue by k-szortyka** [grafana/loki#5713]
How do I show information only about an HTTP request? e.g. 200, 302.

`Mar 25 20:47:09 server-02 docker/nginx_web_1[401055]: 172.29.0.3 - - [25/Mar/2022:19:47:09 +0000] "GET /sites/default/files/inline-images/logo.png HTTP/1.1" 200 57062 "https://www.domain.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0"`

**Comment by DylanGuedes** [comment]
Please, for questions use the public forum or public slack.
