### ISSUE TITLE
promtail oom due to sparse file larger than system memory

### ISSUE THREAD

**Issue by andbanman** [grafana/loki#5731]
**Describe the bug**
When promtail scrapes a sparse file that is larger than system memory, it uses all available memory trying to read it, causing OOM. This is the cause for #3878.

E.g. in an environment with large UIDs, lastlog appears as a very large file
```
$ ls -lsh /var/log/lastlog
84K -rw-rw-r-- 1 root utmp 507G Mar 30 15:38 /var/log/lastlog
```

**To Reproduce**
1. Create a large sparse file and add it to static_config __path__
2. Restart promtail

**Expected behavior**
Promtail either knows how to read the sparse format, detects when a file is too large, or ignores binary files in static_config. Why not permit something like `__path__: /var/log/*`?

**Comment by andbanman** [comment]
There's no ask here. Clsoing.

**Comment by jinnatar** [comment]
This is still very much an issue btw and the issue should not have been closed.

A workaround for a wide glob config is to define an exclude, and hope there's nothing else you need to exclude:
```yaml
  __path__: "/var/log/*log"
  __path_exclude__: "/var/log/lastlog"
```
