### ISSUE TITLE
Allow exclusion patterns on Promtail's `static_config`

### ISSUE THREAD

**Issue by tpaschalis** [grafana/loki#5744]
**Is your feature request related to a problem? Please describe.**
There's currently no easy way to _exclude_ files from Promtail's `static_config`, (or as part of a `file_sd_config` definition). 

This functionality might be useful in a number of scenarios:
- The target directory contains files with different formats, and we want to set up separate `pipeline_stages` for a subset of them
- The target directory might contain files which Promtail doesn't have access to. This would avoid polluting logs with `msg="failed to start tailer" error="open /tmp/log/root.log: permission denied" filename=/tmp/log/root.log`
- For security reasons, one might want to avoid tailing specific files or subdirectories
- We might want to exclude heavy/spammy log files

**Describe the solution you'd like**
There was a prior discussion over at #3804 which didn't have any negative feedback, but was shot down by stalebot. I think that the suggestion there was pretty reasonable.

I propose that we add a new `__path_exclude__` field under static_configs labels, which would use the same package for glob patterns. The config could look like
```
      scrape_configs:
        - job_name: system
          static_configs:
          - targets:
              - localhost
            labels:
              job: tmplogs
              __path__: /tmp/log/*.log
              __path_exclude__: /tmp/log/root.log
```

This new field would be used to perform a second doublestar.Match call and remove any found files from the `matches` slice before t.startTailing.

https://github.com/grafana/loki/blob/62876c57f76797df401190b5df6c0c9940b006b1/clients/pkg/promtail/targets/file/filetarget.go#L192-L197

**Describe alternatives you've considered**
An alternative would be to use `relabel_configs` to drop files with specific `__path__` labels.   
One drawback here is that people are hesitant to use relabelling rules, plus I think that doing it that way is more confusing (having to use both regexes for exclusion, and glob patterns for inclusion).

Another alternative would be working with the upstream bmatcuk/doublestar package to add a negation pattern there. If we don't want to support either option, we should mention at least in the docs that a user should consider stricter pattern matching to exclude files.

**Additional context**
I wouldn't think that glob patterns are _that_ performance-intensive, but still this change would only affect users who choose to use them.

If this seems reasonable, I'd be more than happy to start the implementation. Let me know what you think! ^^

**Comment by cyriltovena** [comment]
Sounds good to me.
