### ISSUE TITLE
Loki ingester Readiness probe is giving 503

### ISSUE THREAD

**Issue by kmrhemant916** [grafana/loki#5759]
**Describe the bug**
I have deployed loki in a distributed mode using helm chart. But the ingester component is not getting started as the Readiness probe fails everytime.

**To Reproduce**
1. Loki image version - docker.io/grafana/loki:2.4.2

**Expected behavior**

Loki ingester should start

**Environment:**
 - Infrastructure: kubernetes
 - Deployment tool: helm chart

**Helm override values**

loki:
  readinessProbe:
    httpGet:
      path: /ready
      port: http
    initialDelaySeconds: 60
    timeoutSeconds: 10
    periodSeconds: 60
  config: |
    auth_enabled: false

    server:
      http_listen_port: 3100

    distributor:
      ring:
        kvstore:
          store: memberlist

    memberlist:
      join_members:
        - {{ include "loki.fullname" . }}-memberlist

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
      chunk_idle_period: 30m
      chunk_block_size: 262144
      chunk_encoding: snappy
      chunk_retain_period: 1m
      max_transfer_retries: 0
      wal:
        dir: /var/loki/wal

    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_cache_freshness_per_query: 10m
      retention_period: 2160h

    schema_config:
      configs:
      - from: "2020-12-11"
        index:
          period: 24h
          prefix: index_
        object_store: azure
        schema: v11
        store: boltdb-shipper
    storage_config:
      azure:
        account_key: xxx-xxxx-xxxx-xxxx-xxxx-xxxx-xxxx
        account_name: a1loki
        container_name: staging
        request_timeout: 0
      boltdb_shipper:
        active_index_directory: /var/loki/boltdb-shipper-active
        cache_location: /var/loki/boltdb-shipper-cache
        cache_ttl: 24h
        shared_store: azure
      filesystem:
        directory: /var/loki/chunks
    {{- if .Values.indexGateway.enabled}}
      index_gateway_client:
        server_address: dns:///{{ include "loki.indexGatewayFullname" . }}:9095
    {{- end}}

    chunk_store_config:
      max_look_back_period: 0s

    table_manager:
      retention_deletes_enabled: false
      retention_period: 0s

    query_range:
      align_queries_with_step: true
      max_retries: 5
      split_queries_by_interval: 15m
      cache_results: true
      results_cache:
        cache:
          enable_fifocache: true
          fifocache:
            max_size_items: 1024
            validity: 24h

    frontend_worker:
      frontend_address: {{ include "loki.queryFrontendFullname" . }}:9095

    frontend:
      log_queries_longer_than: 5s
      compress_responses: true
      tail_proxy_url: http://{{ include "loki.querierFullname" . }}:3100

    compactor:
      shared_store: azure
      working_directory: /var/loki/retention
      compaction_interval: 10m
      retention_enabled: true
      retention_delete_delay: 2h
      retention_delete_worker_count: 150

    ruler:
      storage:
        type: local
        local:
          directory: /etc/loki/rules
      ring:
        kvstore:
          store: memberlist
      rule_path: /tmp/loki/scratch
      alertmanager_url: http://prometheus-kube-prometheus-alertmanager.monitoring.svc.cluster.local:9093
      external_url: https://alertmanager-staging.az.altairone.com
  schema_config:
    configs:
    - from: "2020-12-11"
      index:
        period: 24h
        prefix: index_
      object_store: azure
      schema: v11
      store: boltdb-shipper
  storage_config:
    azure:
      # For the account-key, see docs: https://docs.microsoft.com/en-us/azure/storage/common/storage-account-keys-manage?tabs=azure-portal
      account_key: xxx-xxxx-xxxx-xxxx-xxxx-xxxx
      # Your azure account name
      account_name: xxxxxx
      # See https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blobs-introduction#containers
      container_name: staging
      request_timeout: 0
    boltdb_shipper:
      active_index_directory: /var/loki/boltdb-shipper-active
      cache_location: /var/loki/boltdb-shipper-cache
      cache_ttl: 24h
      shared_store: azure
    filesystem:
      directory: /var/loki/chunks
serviceMonitor:
  enabled: true
  namespace: loki
ingester:
  replicas: 1
  persistence:
    enabled: true
    size: 500Gi
    storageClass: premium-retain
  resources:
    limits:
      cpu: '1'
      memory: 20G
    requests:
      cpu: 200m
      memory: 2G
distributor:
  replicas: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 60
querier:
  replicas: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 60
  persistence:
    enabled: true
    size: 500Gi
    storageClass: premium-retain
queryFrontend:
  replicas: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 60
gateway:
  enabled: true
  replicas: 1
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-az-altairone
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: 'true'
    hosts:
      - host: loki-staging.az.altairone.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: loki-gateway-tls
        hosts:
          - loki-staging.xxxx.xxxx.com
compactor:
  enabled: true
  persistence:
    enabled: true
    size: 500Gi
    storageClass: premium-retain
ruler:
  enabled: true
  replicas: 1
  persistence:
    enabled: true
    size: 100Gi
    storageClass: premium-retain
  directories:
    tenant_staging:
      rules1.txt: |
        groups:
          - name: sssd-certificate.rules
            rules:
              - alert: SssdCertificateExpiration
                expr: sum by (appliance_id) (count_over_time({filename=~"/var/log/sssd/.+"} |~ "certificate" [1m]) > 0)
                for: 2m
                labels:
                  severity: critical
                annotations:
                  description: "SSSD certificate on appliance_id - {{ $labels.appliance_id }} which is used to authenticate to the ldap server is or going to expired."
                  summary: SSSD certificate is about to or expired.

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
