### ISSUE TITLE
Multi-line log support by using unicode \u2028 character

### ISSUE THREAD

**Issue by sandstrom** [grafana/loki#5764]
**Problem**

Most log lines are short, so but for backtraces it really helps to add newlines. However, most log infrastructure (both loki and other stuff that's before it) assume that log lines are separated by `\n`.

**Solution**

Unicode has a linebreak character that's outside the ascii-range, so it won't trip up any system inbetween. It's just meant to be visually represented as a line break.

This character is `\u2028` (source: https://en.wikipedia.org/wiki/Newline#Unicode)

If Loki (or Grafana, probably) could render this as a on-screen line break when presenting logs, we could just update our logging code to replace all `\n` in the log line with `\u2028`.

**Comment by jeschkies** [comment]
Should Loki or rather Promtail treat `\u2028` as true line break then or should Grafana display the line break?

**Comment by sandstrom** [comment]
@jeschkies Grafana should display the linebreak 

(my understanding was that Loki, Promtail, logfmt or something else doesn't support linebreaks, because we have trouble getting them through, but I haven't digged into exactly why, so this assumption may be wrong)

**Comment by jeschkies** [comment]
Promtail uses `\n` for new lines if I'm not wrong. That means it will emit one line with `\u2028` in the middle. So it's a Grafana display issue. Could file an issue there?

**Comment by sandstrom** [comment]
Alright, I've opened an issue here: https://github.com/grafana/grafana/issues/47393
