### ISSUE TITLE
operator: Support for reconciling Loki Rules

### ISSUE THREAD

**Issue by mladedav** [grafana/loki#5843]
**Is your feature request related to a problem? Please describe.**
I want to declaratively create Loki alert rules for my applications.

**Describe the solution you'd like**
For the Loki operator to be able to watch for a new CR LokiRule, or to somehow reuse and watch for PrometheusRule

**Describe alternatives you've considered**
Using current imperative tooling possibly through Helm hooks to create these during installation.

**Additional context**
Similar requests that have died out:
https://github.com/grafana/loki/issues/2990
https://github.com/grafana/loki/issues/3456
Implementation that could be used as a starting point:
https://github.com/opsgy/loki-rule-operator

I would be happy to help out with this

**Comment by periklis** [comment]
@mladedav Thank you for reporting this issue, the SIG operator is currently working on a design proposal for integration a CRD for Loki Rules in the operator. Please stay tuned!

FYI, the loki-operator hosted here in this repository goes beyond reconciling rules. It is a fully fledged operator managing Loki installations on Kubernetes and OpenShift clusters. I will provide an overview on the next community meeting.

**Comment by rosscdh** [comment]
+1 something similar to the service monitor annotations would be nice; also the ability to design an write the alert in the ui but then export the json (as per dashboards) would be super awesome

**Comment by Jeinhaus** [comment]
Wouldn't a sidecar, that syncs labeled configmaps to a local volume work as well? Similar to the way the Grafana provisioning for dashboards works?
I added [this PR](https://github.com/grafana/helm-charts/pull/1625) in the old repository to provide that functionality.
Do you think I should add it here as well?
