### ISSUE TITLE
alert manager url per tenant

### ISSUE THREAD

**Issue by LinTechSo** [grafana/loki#5847]
Is there any way to add an alert manager URL for each tenant?
what does "# Each Alertmanager URL is treated as a separate group in the configuration." mean?

**Comment by cstyan** [comment]
At the moment there is not configuration that allows you to specify a different alertmanager URL per tenant.

> what does "# Each Alertmanager URL is treated as a separate group in the configuration." mean?

This means that each URL you specified will be treated as another unique Alertmanager that you wish to send **all** alerts too.
