### ISSUE TITLE
Promtail: Support CRI-O multi-lines

### ISSUE THREAD

**Issue by eduan-envel** [grafana/loki#5854]
**Is your feature request related to a problem? Please describe.**
Promtail has top-level support for CRI-O logs using the [cri stage](https://grafana.com/docs/loki/latest/clients/promtail/stages/cri/). However, this does not support multi-line CRI-O logs.  

**Describe the solution you'd like**
The `cri` stage just handles multi-lines.

**Describe alternatives you've considered**
A custom `multiline` step. This is possible but the `cri` step removes some of the log tags so it doesn't work in conjunction.

**Additional context**
CRI-O has two log tags, `P` indicating a partial logline (one that will be continued by another partial logline, or by a 'full log line'), and `F` indicating a full logline. 
Also, Fluent Bit already supports this. The documentation is [here](https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/multiline-parsing#built-in-multiline-parsers) with some additional context in the [feature request.](https://github.com/fluent/fluent-bit/issues/1316)

**Comment by kavirajk** [comment]
While working on PR to support `cri-o` multiline tag support #6177 in Loki, I found that `cri-0` is not handling stacktrace or panics as partial log lines correctly.

Created a bug report here.https://github.com/cri-o/cri-o/issues/5903

**Comment by kavirajk** [comment]
I think may be I misunderstood the purpose of log tags in `cri-0`?. may be cri-o split logs into multi lines only if it exceeds the log line threshold size and not during panic or stack-strace in the application.

**Comment by kekscode** [comment]
Yes correct. After 8192 bytes per line.

**Comment by dbluxo** [comment]
Is also described a bit here:  https://github.com/cri-o/cri-o/issues/4432  Nevertheless it would be very helpful to fix this issue, because a single line message stack trace, which is over 8192 bytes long, is split by cri-o and ends up in Loki with several log lines. If the application already creates a milti line stack strace, I think you can solve it this way: 
https://github.com/grafana/loki/issues/74
