### ISSUE TITLE
promtail: May I put positions.yaml file to S3 or other place rather than in my data volume.

### ISSUE THREAD

**Issue by liukch** [grafana/loki#5857]
I have to attach a data volume in AWS just for the `positions.yaml` file, it waste a lot of resource.
Put It to S3, it will cost a little of money,

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
