### ISSUE TITLE
Link to the upgrade guide in release notes of v2.5.0 broken

### ISSUE THREAD

**Issue by michaelkebe** [grafana/loki#5870]
**Describe the bug**
The link to tue upgrade guide is broken.

**To Reproduce**
1. Open https://github.com/grafana/loki/releases/tag/v2.5.0
2. Click on the link to the upgrade guide
3. 404

**Expected behavior**
The link should open e.g. https://github.com/grafana/loki/blob/v2.5.0/docs/sources/upgrading/_index.md#250

**Environment:**
 - GitHub Releases

**Screenshots, Promtail config, or terminal output**

**Comment by DylanGuedes** [comment]
I believe this is fixed now. Thanks for reporting it.
