### ISSUE TITLE
Update go4.org/unsafe/assume-no-moving-gc dependency to support Go 1.18

### ISSUE THREAD

**Issue by hdecarne** [grafana/loki#5875]
**Describe the bug**
After building Loki using Go 1.18 it panics at start as follows:

>panic: Something in this program imports go4.org/unsafe/assume-no-moving-gc to declare that it assumes a non-moving garbage collector, but your version of go4.org/unsafe/assume-no-moving-gc hasn't been updated to assert that it's safe against the go1.18 runtime. If you want to risk it, run with environment variable ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH=go1.18 set. Notably, if go1.18 adds a moving garbage collector, this program is unsafe to use.

Latest version go4.org/unsafe/assume-no-moving-gc dependency considers Go 1.18 save (see [commit](https://github.com/go4org/unsafe-assume-no-moving-gc/commit/538ce61f45ea5c2c48d7133d44b3e52c3db5c31e))

**To Reproduce**
1. Build Loki using Go 1.18
2. Start Loki

**Expected behavior**
Loki starts

**Environment:**
Custom Loki build on Gentoo

**Comment by FTamas77** [comment]
Hi! I have the same issue. I imported "gorgonia.org/gorgonia" and that's all. Any help? Thanks

**Comment by periklis** [comment]
You maybe interested to solve it like we did in the operator code base https://github.com/grafana/loki/pull/6748
