### ISSUE TITLE
Upgrade  Version2.5 + failed to get s3 object: NoSuchKey

### ISSUE THREAD

**Issue by yangvipguang** [grafana/loki#5896]
**Describe the bug**
Version: loki + promtail  2.5
Object Store:  aliyun  OSS (surport s3), alwalys used before and works very well.
![image](https://user-images.githubusercontent.com/11416887/163093400-652caa13-0dbe-486f-a1f6-85272fc1141d.png)

But, When I upgrade to version 2.5 , loki logs show error loki below?
![image](https://user-images.githubusercontent.com/11416887/163092662-896560bd-9fe2-4508-8732-1fb87474b06c.png)

**Comment by periklis** [comment]
@yangvipguang Can it be that you have eagerly switched an existing schema_config from V11 to V12?

**Comment by yangvipguang** [comment]
@periklis  I add a new schema for next day of upgrade, Does it have some problems?
![image](https://user-images.githubusercontent.com/11416887/163219201-7e609f85-ae8d-47e4-8c4d-82d0ebb15fb4.png)

**Comment by yangvipguang** [comment]
I try again and  it works well.

**Comment by gespi1** [comment]
> I try again and it works well.

do you mind telling us what was your fix? ty
