### ISSUE TITLE
Loki supports only 10 log groups in __aws_cloudwatch_log_group label?

### ISSUE THREAD

**Issue by ku9nov** [grafana/loki#5926]
**Describe the bug**
Hello. I'm use this terraform config https://github.com/grafana/loki/tree/main/tools/lambda-promtail for sending logs from CloudWatch to Grafana. When i try to add eleventh log group terraform want replaced all of them and create only 10.  I'm create second Lambda function, but in Grafana console i see only 10.
![2022-04-14_15-46](https://user-images.githubusercontent.com/69673517/163393672-4255105f-6f8c-4532-9d9a-6f823d77eae4.png)
When we use two lambdas function we can create more 10 subscription and they are showed in aws console.

**To Reproduce**
1. Add 11 log groups to `log_group_names` variable.

**Expected behavior**
See all log groups in Grafana console.

**Environment:**
 - Infrastructure: [Grafana-stack in Docker on Ubuntu, Lambda AWS.]
 - Deployment tool: [terraform]

**Screenshots, Promtail config, or terminal output**
Let me know if i can gave more info.

**Comment by cstyan** [comment]
This seems like a terraform specific issue, what version of terraform are you using? 

Can you show me the changes you're making to `variables.tf` (and `main.tf` if any are there). Also be careful that none of the log-group names are duplicates, terraform will automatically dedupe those. As far as I can tell there's no internal limit to a set length or the # of elements terraform `for_each` can iterate through.

You can test what `for_each` should expect your list to be like this:
- first run `terraform console`
- in the console try `toset(["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11"])` but replace the list items with the ones from your variables.tf file
- try again with `length(toset(["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11"]))
11`

**Comment by ku9nov** [comment]
You are right, i should use `for_each` instead old `length`.
Thank you. Now it seems all working correctly.
