### ISSUE TITLE
OOM crash results in 15k+ line stacktrace

### ISSUE THREAD

**Issue by setpill** [grafana/loki#5927]
**Describe the bug**

A loki OOM resulted in over 15k lines worth of stacktrace being written to the system log. 

**To Reproduce**
1. Started Loki 2.4.2
2. Perform a query big enough to trigger an OOM

**Expected behavior**
An OOM error with maybe some helpful information.

**Environment:**
 - Infrastructure: deployment on a VM
 - Deployment tool: manual

**Screenshots, Promtail config, or terminal output**
https://gist.github.com/setpill/b9fe2c36f76e2251c463f3a4d33f88fc

**Comment by dannykopping** [comment]
Thanks for reporting this @setpill :+1:

This is definitely suboptimal

**Comment by setpill** [comment]
On slack, further discussion indicated this is out of scope for loki as it is how go panics function. It was suggested to set `GOTRACEBACK=none` env variable when running loki ([reference](https://pkg.go.dev/runtime)). At this time, I can no longer reproduce the OOM situation, but it seems likely that this fixes the issue.
