### ISSUE TITLE
Promtail: ARM docker images are still affected by #2792 (journal input stops working after upgrading systemd to 246+)

### ISSUE THREAD

**Issue by abferm** [grafana/loki#5938]
**Describe the bug**
Promtail no longer collects journal logs after upgrading systemd/journald on ARM host
Appears to be the same as #2792, merged fix appears to only apply to AMD64 docker images, as the arm docker image does not list backports as an apt source.

**To Reproduce**
1. Install Docker on ARM host
2. Configure Promtail container to collect journal logs
3. Observe behavior difference between systemd versions

**Expected behavior**
Logs collected

**Environment:**

***Working***
 - balenaOS 2.83.21
 - systemd 244
 - docker image: grafana/promtail:2.4.2-arm

***Not Working***
 - balenaOS 2.95.8
 - systemd 249
 - docker image: grafana/promtail:2.4.2-arm

**Screenshots, Promtail config, or terminal output**
output of `journalctl --version` on working host (balenaOS 2.83.21)
```
systemd 244 (244.5+)
-PAM -AUDIT -SELINUX +IMA -APPARMOR -SMACK +SYSVINIT +UTMP -LIBCRYPTSETUP -GCRYPT -GNUTLS +ACL +XZ -LZ4 -SECCOMP +BLKID -ELFUTILS +KMOD -IDN2 -IDN -PCRE2 default-hierarchy=hybrid
```
output of `journalctl --version` on non-working host (balenaOS 2.95.8)
```
systemd 249 (249.3+)
-PAM -AUDIT -SELINUX -APPARMOR +IMA -SMACK +SECCOMP -GCRYPT -GNUTLS -OPENSSL +ACL +BLKID -CURL -ELFUTILS -FIDO2 -IDN2 -IDN -IPTC +KMOD -LIBCRYPTSETUP +LIBFDISK -PCRE2 -PWQUALITY -P11KIT -QRENCODE -BZIP2 -LZ4 -XZ -ZLIB +ZSTD -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=hybrid
```

**Comment by slim-bean** [comment]
Are you actually running on a 32bit OS? If you're on a 64bit OS you can use the `-arm64` image, or just specify `promtail:2.5.0` and docker will chose the correct architecture.

As you noticed in the PR we missed the fix the 32bit arm build and would need to PR it separately for a future release.

**Comment by abferm** [comment]
Unfortunately I am currently limited to a 32-bit OS for my platform.
