### ISSUE TITLE
No logs - "no files matched requested path, nothing will be tailed" path=/var/log/*log

### ISSUE THREAD

**Issue by AlexTeal03** [grafana/loki#5949]
**Describe the bug**
I am running loki & promtail 2.5 on OSS, localhost:3100/metrics display output & /ready shows that the instance is ready. No logs or labels are coming through to grafana, I used this command to debug: docker run -v c:\tealcraft\grafana:/mnt/config -v /var/log:/var/log --link loki grafana/promtail:2.5.0 --config.file=/mnt/config/promtail-config.yaml -log.level=debug

This gave me this error:  "no files matched requested path, nothing will be tailed" path=/var/log/*log
I have tried this with other paths which I know are correct and I get the same problem. 

**To Reproduce**
1. Started Loki 2.5
2. Started Promtail 2.5 to tail '/var/log/*log'
3. Ran docker run -v c:\tealcraft\grafana:/mnt/config -v /var/log:/var/log --link loki grafana/promtail:2.5.0 --config.file=/mnt/config/promtail-config.yaml -log.level=debug
4. Discovered the error "no files matched requested path, nothing will be tailed"

**Expected behavior**
Logs should come through to my grafana instance. 

**Environment:**
 - Infrastructure: Docker OSS (Windows PC)
 - Deployment tool: N/A

**Screenshots, Promtail config, or terminal output**
Promtail config: https://prnt.sc/rYtWq1vV2F9W
CMD output: https://prnt.sc/q-2KLkN4cDPb

**Comment by dannykopping** [comment]
@AlexTeal03 please `exec` into your container and ensure the files are present, and that they are appropriately permissioned.

This is unlikely to be a bug, so I'm going to close it.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
