### ISSUE TITLE
Display only if Exceed certain value 

### ISSUE THREAD

**Issue by rainbowhat** [grafana/loki#5962]
{$label_name=~"$label_value", job=~"$job", instance=~"$instance"} | json | line_format "➡️ {{.request_method}} {{.status}} {{.http_host}}{{.request_uri}} {{.request_time}}"

How do i get it to display if it exceed request time of only 1 second , so i can view the slow requests

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
