### ISSUE TITLE
ingester: grpc method=/logproto.Querier/Query fail.

### ISSUE THREAD

**Issue by liguozhong** [grafana/loki#5964]
**Describe the bug**
rpc error: code = Internal desc = transport: transport: the stream is done or WriteHeader was already called.

![image](https://user-images.githubusercontent.com/9583245/164195582-a48b8718-2640-4028-ac19-5b2256d35dc1.png)

![image](https://user-images.githubusercontent.com/9583245/164195707-9994ac0f-de5e-4c1b-b219-404e0f639b7a.png)

**To Reproduce**
1. Started Loki (SHA or version)
2. Started Promtail (SHA or version) to tail '...'
3. Query: `{} term`

**Expected behavior**

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by DylanGuedes** [comment]
Hey thanks for spotting this! I was wondering, is this a recent thing? :thinking:

**Comment by liguozhong** [comment]
This problem is from version 2.4.2 to 2.5.0.

![image](https://user-images.githubusercontent.com/9583245/164363855-a2c57eec-3859-45a3-9906-abc49a2f62e1.png)

**Comment by Tristan971** [comment]
Can reproduce it here as well, moving from 2.4.2 to to 2.5.0. Moving to 2.6.0 does not fix it either.

![2022-07-08 15_27_52-Explore - Loki - Grafana and 13 more pages - Personal - Microsoft​ Edge Beta](https://user-images.githubusercontent.com/875533/178012142-fa101df6-db9d-4673-99bd-f24ab08d3756.png)
