### ISSUE TITLE
Multi-line: add flag to skip \n addition in reconstruct

### ISSUE THREAD

**Issue by BitProcessor** [grafana/loki#5975]
Tested on `grafana/agent:v0.23.0`

In order to overcome this issue: https://github.com/grafana/loki/issues/2281 and get past the 16KB limit, I was trying to come up with a way to ingest large JSON log messages as a whole. For this, I based myself [on the example in the multiline stage docs](https://grafana.com/docs/loki/latest/clients/promtail/stages/multiline/#custom-log-format) and applied the following pipeline config to Grafana-agent:
```
                  - multiline:
                      # Identify zero-width space as first line of a multiline block.
                      # Note the string should be in single quotes.
                      firstline: '^\x{200B}\{'
                      max_wait_time: 3s
                  - replace:
                      expression: '^(\x{200B})'
                      replace: ''
```
The logs themselves were prefixed with a ZeroWidthSpace character, before the start of each individual JSON log message.

The replace stage was added to remove the special character, in order to get the Prettifyer working again in Grafana
The setup works, although not perfect:
- < 16KB logs get ingested fine with the special character removed and Grafana being all happy about it being JSON
- Logs > 16KB that get split by moby over multiple lines  also get ingested as 1 entry :partying_face: ... BUT....

It seems like grafana-agent is inserting newlines into them, which causes issues with JSON Prettify in Grafana. 

Testing this with a json field containing a massive amount of a's (all in a single-line valid json log message):
![image (1)](https://user-images.githubusercontent.com/50638541/163581429-5c274099-f145-41c3-8cbb-2802f0d403c3.png)

I think I found the piece of code that does this:
```
			// Append block line
			if state.buffer.Len() > 0 {
				state.buffer.WriteRune('\n')
			}
			state.buffer.WriteString(e.Line)
			state.currentLines++

			if state.currentLines == *m.cfg.MaxLines {
				m.flush(out, state)
			}
```
Which is a real bummer because well... JSON

**_Question_**: would it be possible to have a flag in the multiline stage to skip that newline ?

**Comment by BitProcessor** [comment]
Might not be needed after all, this fixes it:

```
                        - multiline:
                            # Identify zero-width space as first line of a multiline block.
                            # Note the string should be in single quotes.
                            firstline: '^\x{200B}\{'
                            max_wait_time: 3s
                        - replace:
                            expression: '^(\x{200B})'
                            replace: ''
                        - replace:
                            expression: '([\n])'
                            replace: ''
```
It removes the inserted newlines again, making the JSON valid again 🥳

**Comment by jeschkies** [comment]
I meant to answer. This is an interesting use case. You find a nice solution!

**Comment by BitProcessor** [comment]
@jeschkies thanks - it's a bit of a "hack" of course as it needs app-side log output adjustments 
Still hoping for fix [here](https://github.com/grafana/loki/issues/2281) one day 🤞🏻
