### ISSUE TITLE
Loki Pod Keep crashing (Back-off restarting failed container)

### ISSUE THREAD

**Issue by gauravbist** [grafana/loki#599]
**Describe the bug**
POD Crashing:  Back-off restarting failed container

Error: "level=error ts=2019-05-17T12:36:27.607054242Z caller=main.go:46 msg="error loading config" filename=/etc/loki/loki.yaml err="parsing time \"0\" as \"2006-01-02\": cannot parse \"0\" as \"2006\""

Install by step:
helm repo add loki https://grafana.github.io/loki/charts
helm repo update
helm upgrade --install loki loki/loki-stack  --namespace prometheus

kubectl get pods -n prometheus
NAME                                             READY   STATUS             RESTARTS   AGE
grafana-7c8896d746-fwf67                         1/1     Running            1          8d
loki-7479978bcb-ffxc9                            0/1     CrashLoopBackOff   9          23m
loki-promtail-2q972                              1/1     Running            0          1h
loki-promtail-hjmst                              1/1     Running            0          1h
loki-promtail-z4tdv                              1/1     Running            0          1h
loki-promtail-zcgjl                              1/1     Running            0          1h
prometheus-alertmanager-7fd59db7b8-zs77n         2/2     Running            0          7d
prometheus-kube-state-metrics-85bbbff4fd-rw8f5   1/1     Running            0          7d
prometheus-node-exporter-jlbhx                   1/1     Running            0          1h
prometheus-node-exporter-xlp8x                   1/1     Running            0          7d
prometheus-node-exporter-xmvvh                   1/1     Running            0          7d
prometheus-pushgateway-6dc8b595c9-ftg7l          1/1     Running            0          7d
prometheus-server-8567584bb-r64cs                2/2     Running            0          7d

kubectl logs loki-7479978bcb-ffxc9 -n prometheus
level=error ts=2019-05-17T12:41:38.645373008Z caller=main.go:46 msg="error loading config" filename=/etc/loki/loki.yaml err="parsing time \"0\" as \"2006-01-02\": cannot parse \"0\" as \"2006\""

**Comment by Kuqd** [comment]
Hello @gauravbist how does your loki.yaml looks like ?

**Comment by sandlis** [comment]
Fixed by commit https://github.com/grafana/loki/commit/f2fb161a08a1f8735939fd8fb65c7fd0006fcb5f

**Comment by gauravbist** [comment]
Where can I find it?

**Comment by gauravbist** [comment]
hi @sandlis how can I fix it on our setup. I am little new to this.

**Comment by Kuqd** [comment]
kubectl delete pod loki-7479978bcb-ffxc9

that should do the trick

**Comment by gauravbist** [comment]
Same issue.

After deleting old one.. New pod created with 

loki-7479978bcb-w4dgc       CrashLoopBackOff   

level=error ts=2019-05-17T12:58:14.602250591Z caller=main.go:46 msg="error loading config" filename=/etc/loki/loki.yaml err="parsing time \"0\" as \"2006-01-02\": cannot parse \"0\" as \"2006\""

**Comment by gauravbist** [comment]
if any other logs needed, please let me know

**Comment by Kuqd** [comment]
you loki image is not getting updated, try updating the deployment labels to force to pull a new image.

**Comment by gauravbist** [comment]
This is the running configuration.

Please let me know where should I update it.

[loki.txt](https://github.com/grafana/loki/files/3191626/loki.txt)

**Comment by Kuqd** [comment]
actually I can repro also, let me see what's going on.

**Comment by Kuqd** [comment]
can you run this :
helm repo update
helm upgrade --install loki loki/loki-stack --namespace prometheus

then delete the loki pods.

**Comment by gauravbist** [comment]
Perfect.. @Kuqd 

It is working now... Thanks

**Comment by Ferdinanddb** [comment]
Hello there @sandlis & @Kuqd & others, I am experiencing the same bug but my case is that I've installed (like 2 weeks ago) loki and promtail using `helm template` in order to get the YAML files and automatize the installation (cause i'm using Vagrant to fake a cluster architecture but anyway). 
Do you have any suggestion other than using helm for that please?

**Comment by sandlis** [comment]
Updating to latest loki image doesn't work for you? If you are doing your own configs then you need to do changes same as https://github.com/grafana/loki/commit/f2fb161a08a1f8735939fd8fb65c7fd0006fcb5f.

**Comment by Ferdinanddb** [comment]
Yes it doesn't work.. Here is the part of the YAML file which would have to update the image right?
`    spec:
      serviceAccountName: loki
      containers:
        - name: loki
          image: "grafana/loki:master"
          imagePullPolicy: Always
          args:
            - "-config.file=/etc/loki/loki.yaml"  `

Otherwise, how can I do the same changes as you mentioned in  grafana/loki@f2fb161 please? 
I don't see where I could replace that? I tried to `kubectl exec -it loki-... -bash ` but I can't access it and I get `error: unable to upgrade connection: container not found ("loki")`

**Comment by Kuqd** [comment]
you need to change the loki config map, it should be in your yaml generated via helm template.

**Comment by Ferdinanddb** [comment]
There is no ConfigMap for Loki generated by `helm template`, you mean the ConfigMap of Promtail?

**Comment by Ferdinanddb** [comment]
I found it, I had to update 2 things after generating a new `helm template` : 
- In `Secret` : the loki.yaml file to the new one
- In `Deployment` : the checksum/config to the new one 

Thank you for your time and your help guys !
