### ISSUE TITLE
Rethink chunk idle semantics

### ISSUE THREAD

**Issue by gouthamve** [grafana/loki#60]
In metrics, we know when to flush a chunk because we expect metrics to flow in at a constant rate. That is not the case with logs. A container might log only once every few mins or even every hour. Us flushing chunks in that case makes for bad compression and super sparse index.

One way to fix this would be to make the agent heartbeat which streams still "exist".

**Comment by slim-bean** [comment]
We just had some discussions about ways to solve this, including aggregating chunks into another file before writing to disk to guarantee appropriate size on disk.
