### ISSUE TITLE
DNS Resolver : The name to resolve is too specific.

### ISSUE THREAD

**Issue by treussart** [grafana/loki#6006]
**Describe the bug**
Into the file:
https://github.com/grafana/loki/blob/9cef86b162536179180724a0036956fc3572d904/production/ksonnet/loki/config.libsonnet#L96

The pod is crashloopbackoff because it cannot resolve the name: kube-dns.kube-system.svc.cluster.local

On my k8s cluster the name is coredns instead of kube-dns.

For resolve this issue, I created a new service with the same spec than coredns, but I think we should be able to change it in the Helm chart config.

**To Reproduce**
1. Rename the service to something other than kube-dns
2. Install the chart grafana/loki-simple-scalable

**Expected behavior**
A crashloopbackoff of the pods loki-simple-scalable-*

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Comment by irizzant** [comment]
This is configurable through the [chart options](https://github.com/grafana/helm-charts/blob/f942ba605f8780518b6ac7f52eb68fb275c02e8b/charts/loki-simple-scalable/values.yaml#L711)

**Comment by erSitzt** [comment]
Just for anyone who might stumble upon this..

RKE2 Cluster
```
global:
  clusterDomain: cluster.local
  dnsNamespace: kube-system
  dnsService: rke2-coredns-rke2-coredns
```
