### ISSUE TITLE
While creating an "Elasticsearch" Data source, getting error as "no such index"

### ISSUE THREAD

**Issue by mhulsurkar** [grafana/loki#603]
I have Grafana & Elastic search serivces started on my machine.I have Java 12.0.1 version installed. While tyring to add a "ElasticSearch" data source, I am getting an error saying no such index.

![image](https://user-images.githubusercontent.com/42846665/57952379-dcbdba00-78a1-11e9-8380-e677194be4ad.png)

Can anyone help me resolve this issue??

**Comment by steven-sheehy** [comment]
Please ask in the proper github repo: https://github.com/grafana/grafana/issues/

**Comment by Kuqd** [comment]
also, I doubt you want `Access: Default` with a host like `localhost`.

**Comment by marefr** [comment]
> also, I doubt you want `Access: Server(Default)` with a host like `localhost`. Click on the help button there, it will give you an idea of what's going on.

Actually server is the default for a reason and should always be the preferred, if nothing else specified.
