### ISSUE TITLE
"Show Context" in Split-View

### ISSUE THREAD

**Issue by lowb1rd** [grafana/loki#6031]
The "show context" feature is too limited.

**Describe the solution you'd like**
"Show Context" should open in the split view, highlighting the filtered line and showing the context of that file (say +/- 10 log lines). One could add then additional files to even see data from other logs/systems in that context. "Load more" entries should also be possible to skip further back and forth.

**Comment by DylanGuedes** [comment]
Hey thank you for reporting this! Do you mind though reporting it at the grafana repo instead?

**Comment by hunkjun** [comment]
> The "show context" feature is too limited.
> 
> **Describe the solution you'd like** "Show Context" should open in the split view, highlighting the filtered line and showing the context of that file (say +/- 10 log lines). One could add then additional files to even see data from other logs/systems in that context. "Load more" entries should also be possible to skip further back and forth.

It is very important in the case of large log.
