### ISSUE TITLE
Shorthand syntax for label selection in json parser

### ISSUE THREAD

**Issue by srhb** [grafana/loki#6036]
**Is your feature request related to a problem? Please describe.**
I'm ever so mildly miffed when I have to write `{...} | json foo="foo" | foo=...` to avoid making a label of every single field, even though I'm fine with the original name.

**Describe the solution you'd like**

A nice shorthand syntax for a direct selection (without translation) of json fields would be nice, eg. `{...} | json foo | foo=...` 

**Describe alternatives you've considered**
Remaining ever so mildly miffed, which I'll definitely survive.

**Additional context**

**Comment by cyriltovena** [comment]
sounds like a good idea to me.

**Comment by owen-d** [comment]
Yeah, great suggestion!
