### ISSUE TITLE
Loki POD crashes randomly

### ISSUE THREAD

**Issue by gauravbist** [grafana/loki#605]
**Describe the bug**
Loki Pod crashes randomly with Error: "Liveness probe failed: HTTP probe failed with statuscode: 500"

**To Reproduce**
Search in Grafana give error: "Unknown error during query transaction. Please check JS console logs" . Found Loki pod crashed with error:  "Liveness probe failed: HTTP probe failed with statuscode: 500"

**Comment by gauravbist** [comment]
Please ignore it..  I think its because of node health check is not working properly

**Comment by gauravbist** [comment]
I fixed the Nodes Liveness probe issue.. but still it is not resolved. as soon as I search logs in Grafana.. loki pod crashed. 

please find attached the loki pod details:

kubectl describe pod loki-d86549668-2c4r7 -n prometheus

[lokierror.txt](https://github.com/grafana/loki/files/3202672/lokierror.txt)

**Comment by Kuqd** [comment]
Hello @gauravbist ,

Can you share the logs of the pod crashing please ?

Thank you !

**Comment by gauravbist** [comment]
[loki-v5.txt](https://github.com/grafana/loki/files/3202745/loki-v5.txt)

is that you need?

**Comment by Kuqd** [comment]
I don't see any crash log, can you try to remove the liveness and readiness checks for a while see what happen ?

**Comment by gauravbist** [comment]
How to do it?  Should I remove below mentioned lines in loki deployment running yaml file?

` "livenessProbe": {
              "httpGet": {
                "path": "/ready",
                "port": "http-metrics",
                "scheme": "HTTP"
              },
              "initialDelaySeconds": 45,
              "timeoutSeconds": 5,
              "periodSeconds": 10,
              "successThreshold": 1,
              "failureThreshold": 3
            },
            "readinessProbe": {
              "httpGet": {
                "path": "/ready",
                "port": "http-metrics",
                "scheme": "HTTP"`

**Comment by gauravbist** [comment]
After removing liveness and readiness checks, so far no crashed.. but in grafana old logs are not coming...

**Comment by gauravbist** [comment]
It is still not stable.. sometimes it works but most of the time it crashes.

[loki-describe.txt](https://github.com/grafana/loki/files/3206273/loki-describe.txt)

Please let me know how to troubleshoot or debug the same.

**Comment by Kuqd** [comment]
I think your Loki is getting killed, can you look at memory usage and kubernetes events.

```
kubectl get events --all-namespaces
```

**Comment by gauravbist** [comment]
I don't think due to memory or cpu usage it is getting killed because node have 30GB memory with 4 vCpu core. and only few pods are running on it..

even events are also not showing it..
[events.txt](https://github.com/grafana/loki/files/3212593/events.txt)

Is there any setting or configuration where I can enable debug mode, so that we can trace the root cause?

**Comment by Kuqd** [comment]
Can you try to upgrade your helm deployment with lastest and also delete all loki pods once that's done ?

**Comment by gregwebs** [comment]
@gauravbist please check on the memory usage. We have seen an unbound memory leak in Loki.

**Comment by christopher-wong** [comment]
Ran into this problem today with the latest version of Loki. Health / Liveness checks keep failing and k8s kills the pod. Loki itself seems find and I can query logs until k8s kills the pod.

**Comment by gregwebs** [comment]
see #613

**Comment by Kuqd** [comment]
yeah let's keep the first issue only this is a dup of #613
