### ISSUE TITLE
loki pod crashloops when restarted

### ISSUE THREAD

**Issue by Moofasax** [grafana/loki#607]
**Describe the bug**
loki pod crashloops when restarted.
`level=error ts=2019-05-21T17:35:01.933858968Z caller=main.go:46 msg="error loading config" filename=/etc/loki/loki.yaml err="parsing time \"0\" as \"2006-01-02\": cannot parse \"0\" as \"2006\""
`
We tried  to use the helm values for AWS s3 and dynamo as storage, did a helm upgrade with the new values, got the error above, then rolled back, still got the error, then did a full helm delete and purge and started with a fresh re-deploy, still getting the error above.

This is the config of the file it is complaining about i believe.
`auth_enabled: false
ingester:
  chunk_block_size: 262144
  chunk_idle_period: 15m
  lifecycler:
    ring:
      replication_factor: 1
      store: inmemory
limits_config:
  enforce_metric_name: false
schema_config:
  configs:
  - from: 0
    index:
      period: 168h
      prefix: index_
    object_store: filesystem
    schema: v9
    store: boltdb
server:
  http_listen_port: 3100
storage_config:
  boltdb:
    directory: /data/loki/index
  filesystem:
    directory: /data/loki/chunks`

**To Reproduce**
helm install
kubectl delete the loki pod

**Expected behavior**
The pod restarts just fine.

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
AWS EKS
 - Deployment tool: [e.g., helm, jsonnet]
helm

**Screenshots, promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by Moofasax** [comment]
What chart should i fetch? i did a:
helm repo update
helm fetch loki/loki-stack

and got 0.9.1 which is giving the same error.

**Comment by negbie** [comment]
You need to change the "from" date format see here:

https://github.com/grafana/loki/blob/master/cmd/loki/loki-local-config.yaml#L16
