### ISSUE TITLE
Revise docs to include info instead of linking to other places

### ISSUE THREAD

**Issue by KMiller-Grafana** [grafana/loki#6080]
Comments by @trevorwhitney in https://github.com/grafana/loki/pull/6079 identify 2 spots in the Loki docs that link out to Mimir docs.  The features/configuration described in the Mimir docs should instead be included in the Loki docs, and in a Loki-specific context.

**Comment by GrafanaWriter** [comment]
Fixed with https://github.com/grafana/loki/pull/6079
