### ISSUE TITLE
500 empty ring

### ISSUE THREAD

**Issue by pablo102** [grafana/loki#6085]
Hello!

We adding Loki to grafana, getting error 500 empty ring. What is that mean
![500error_issue](https://user-images.githubusercontent.com/25483868/166449515-27f43318-3ff3-492e-96b6-fead335f0347.JPG)
?

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.

**Comment by dannykopping** [comment]
This issue was already asked in the public Slack channel. Please wait for a response there.
