### ISSUE TITLE
Grafana always report "Error connecting to datasource: Loki: Bad Gateway. 502"

### ISSUE THREAD

**Issue by xlloveyun** [grafana/loki#609]
##### Loki start but Grafana always report Error 502.
I tried to build and run from source like below:
<code>$ go get github.com/grafana/loki</code>
<code>$ cd $GOPATH/src/github.com/grafana/loki # GOPATH is $HOME/go by default.</code>
<code>$ go build ./cmd/loki</code>
<code>$ ./loki -config.file=./cmd/loki/loki-local-config.yaml</code>

And the loki logs like below 
```
level=info ts=2019-05-21T10:47:00.558441195Z caller=loki.go:122 msg=initialising module=server
level=info ts=2019-05-21T10:47:00.558530158Z caller=server.go:120 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2019-05-21T10:47:00.558610078Z caller=loki.go:122 msg=initialising module=overrides
level=info ts=2019-05-21T10:47:00.55861863Z caller=override.go:48 msg="per-tenant overides disabled"
level=info ts=2019-05-21T10:47:00.55862615Z caller=loki.go:122 msg=initialising module=store
level=info ts=2019-05-21T10:47:00.558707817Z caller=loki.go:122 msg=initialising module=ring
level=info ts=2019-05-21T10:47:00.558732354Z caller=loki.go:122 msg=initialising module=querier
level=info ts=2019-05-21T10:47:00.559169799Z caller=loki.go:122 msg=initialising module=ingester
level=info ts=2019-05-21T10:47:00.55925738Z caller=loki.go:122 msg=initialising module=distributor
level=info ts=2019-05-21T10:47:00.559289168Z caller=loki.go:122 msg=initialising module=all
level=info ts=2019-05-21T10:47:00.559351413Z caller=main.go:66 msg="Starting Loki" version="(version=, branch=, revision=)"
level=error ts=2019-05-21T10:47:00.559049891Z caller=consul_client.go:182 msg="error getting path" key=ring err=null
level=info ts=2019-05-21T10:47:00.559428549Z caller=lifecycler.go:373 msg="entry not found in ring, adding with no tokens"
level=info ts=2019-05-21T10:47:00.559723319Z caller=lifecycler.go:303 msg="auto-joining cluster after timeout"
```
Then I tried to add <code>http://localhost:3100</code> to grafana, then got 

```
Error connecting to datasource: Loki: Bad Gateway. 502
```

#### Environment:
Mac, debian and centos, Grafana in docker, and loki is build from source. I don't know what happend, I've checked the 3100 port has been opened, and iptables is stopped.

#### Expected behavior 
Grafana return success when click the <Code>Save&Test</Code> button.

**Comment by tmikaeld** [comment]
@xlloveyun Did you find out what the problem was? I have the same issue...

**Comment by cfstyle** [comment]
I have the same issue...

**Comment by tmikaeld** [comment]
@cfstyle You can connect to the IP of the host, like http://155.16.4.68:3100

**Comment by cfstyle** [comment]
> @cfstyle You can connect to the IP of the host, like http://155.16.4.68:3100

thanks. now it's working fine ( grafana can connect the loki and I can explore logs). 
But the error "404 page not found" is still there.

**Comment by tmikaeld** [comment]
@cfstyle Well, the promtail endpoint will only return 404 if you're not doing a query or posting data to it. For example, posting to http://155.16.4.68:3100/api/prom/push would work fine.

**Comment by kush2100** [comment]
Error connecting to datasource: Loki: Bad Gateway. 502
Grafana and Loki are working on same server. Now i want to configure Loki Datasource on public IP, it will give error Loki: Bad Gateway. 502. But when connect with localhost it will work. Can you please help me on this.

**Comment by Gooooodman** [comment]
Did you find out what the problem was? I have the same issue
why the issue is closed???? 
where is the solution ???

**Comment by cyriltovena** [comment]
Solution is make sure loki is healthy and properly configured in Grafana

**Comment by Gooooodman** [comment]
a matter of time

**Comment by hamiltont** [comment]
> Grafana in docker

That's your problem. To your docker container, `localhost` means "inside the same container". Loki is not running inside the container, hence the 502 error. 

If you've named the loki container, you can take advantage of Docker's DNS and use this as your datasource URL `http://loki:3100` - docker will have mapped `loki` (or whatever your container name is) to the proper IP for the container running loki. 

If loki is running not in a container, but on your host, you can use Dockers `host.docker.internal` domain as so `http://host.docker.internal:3100`. This will auto-map to the IP address of the host machine (as of docker 18.03+)

**Comment by paaragon** [comment]
> > Grafana in docker
> 
> That's your problem. To your docker container, `localhost` means "inside the same container". Loki is not running inside the container, hence the 502 error.
> 
> If you've named the loki container, you can take advantage of Docker's DNS and use this as your datasource URL `http://loki:3100` - docker will map `loki` (or whatever your container name is) to the proper IP for the container running loki. This works best if you're using docker-compose
> 
> If loki is running not in a container, but on your host, you can use Dockers `host.docker.internal` domain as so `http://host.docker.internal:3100`. This will auto-map to the IP address of the host machine (as of docker 18.03+)

This works perfect for me

**Comment by coffeeguy1** [comment]
For those who are using docker-compose you guys have to write like hamiltont said `http://loki:3100`

If you want to know more about it see [Networking in Compose](https://docs.docker.com/compose/networking/)

**Comment by geraldodev** [comment]
If you're not using docker and getting the issue, check the address of the service. I'm color blind and was tricked by http://localhost:3100 that is shown as hint. As soon I've typed http://localhost:3100 I've stopped to receive bad gateway

**Comment by pkrishnanreflexion** [comment]
> If you're not using docker and getting the issue, check the address of the service. I'm color blind and was tricked by http://localhost:3100 that is shown as hint. As soon I've typed http://localhost:3100 I've stopped to receive bad gateway

Very true, I too misunderstood the hint 'http://localhost:3100' as value 'http://localhost:3100'. After entering the value, the bad gateway disappeared and able to connect.
