### ISSUE TITLE
[Feature request] support regular expression for exclude line with string

### ISSUE THREAD

**Issue by patsevanton** [grafana/loki#6100]
Hello. Thanks for loki.

**Is your feature request related to a problem? Please describe.**
I have many many logs with same line.

**Describe the solution you'd like**
If loki can exclude line with string, i can faster find issue

**Describe alternatives you've considered**
cat log-file.txt | grep -v "string"

**Additional context**
no

**Comment by dannykopping** [comment]
Hi @patsevanton 

Have you tried using this syntax?

```logql
{stream="selector"} !~ "some.*regex"
```

More details here: https://grafana.com/docs/loki/latest/logql/log_queries/#log-stream-selector
