### ISSUE TITLE
Show which service is not running in `/ready` endpoint

### ISSUE THREAD

**Issue by pablo102** [grafana/loki#6103]
**Is your feature request related to a problem? Please describe.**
Show which services are in different states in the `/ready` endpoint

**Describe the solution you'd like**
When i use URL:3100/ready i can see that one service is not started.
Some services are not Running:
Running: 10
Starting: 1

**Describe alternatives you've considered**
N/A

**Additional context**
I am running in monolithic mode.

**Comment by dannykopping** [comment]
It seems we already have an endpoint `/services` which shows a mapping between services and state:

```bash
$ http http://localhost:3100/services
HTTP/1.1 200 OK
Content-Length: 281
Content-Type: text/plain; charset=utf-8
Date: Fri, 06 May 2022 10:01:13 GMT

query-scheduler => Running
querier => Running
query-frontend => Running
ingester => Running
ingester-querier => Running
store => Running
ring => Running
query-frontend-tripperware => Running
usage-report => Running
distributor => Running
memberlist-kv => Running
server => Running
```
