### ISSUE TITLE
Instant query returns `unimplemented` error

### ISSUE THREAD

**Issue by chaudum** [grafana/loki#6130]
**Describe the bug**

The following instant query returns an error `unimplemented`:

```logql
sum (count_over_time({foo="bar"} | logfmt | duration > 2s [3s]))
/
sum (count_over_time({foo="bar"} [3s]))
```

**To Reproduce**

Add the following case to the `TestRangeMappingEquivalence` (downstream_test.go) test:

```
{`sum (count_over_time({a=~".+"} | logfmt | b > 2 [3s])) / sum (count_over_time({a=~".+"} [3s]))`, time.Second},
```

**Expected behavior**

Should return correct result.

**Comment by trevorwhitney** [comment]
Is this the same bug @owen-d ran into on Friday?

**Comment by chaudum** [comment]
> Is this the same bug @owen-d ran into on Friday?

Yes it is.
