### ISSUE TITLE
undefined IngesterDesc 

### ISSUE THREAD

**Issue by mizeng** [grafana/loki#614]
**Describe the bug**
When I try to run any test in Loki project, I saw below error:
```
# loki/vendor/github.com/cortexproject/cortex/pkg/ring
../../vendor/github.com/cortexproject/cortex/pkg/ring/batch.go:16:15: undefined: IngesterDesc
```

I then search `IngesterDesc` in cortex and find nothing. Checked `Gopkg.toml` and found Loki relys on master of cortex. Seems master cortex has no `IngesterDesc`now.

**To Reproduce**
1. Get latest loki from Github master branch
2. Run any test.go in Loki Project.

**Expected behavior**
Test case should run normally and no error "undefined: IngesterDesc" showed.

**Comment by sandlis** [comment]
@mizeng You need to generate go code from protobuf files by running make protos command.

**Comment by sandlis** [comment]
Actually those are generated and checked in already it seems https://github.com/grafana/loki/blob/master/vendor/github.com/cortexproject/cortex/pkg/ring/ring.pb.go

Can you please check whether its there in your codebase?

**Comment by mizeng** [comment]
thanks.  This `ring.pb.go` is not in my codebase.

**Comment by mizeng** [comment]
why not add this to codebase just as the `logproto.pb.go` in https://github.com/grafana/loki/tree/master/pkg/logproto

**Comment by sandlis** [comment]
Its there already in master

**Comment by mizeng** [comment]
thanks a lot. it seems get deleted after I run command `dep ensure`..

**Comment by mizeng** [comment]
@sandlis btw, what's the correct steps to build loki project and get all the dependency installed correctlly? 
I git cloned loki code, run `dep ensure -update`. Then found errors like below
```
Solving failure: No versions of github.com/prometheus/prometheus met constraints:
	v2.9.2: Could not introduce github.com/prometheus/prometheus@v2.9.2, as it is not allowed by constraint master from project loki.
	v2.9.1: Could not introduce github.com/prometheus/prometheus@v2.9.1, as it is not allowed by constraint master from project loki.
	v2.9.0: Could not introduce github.com/prometheus/prometheus@v2.9.0, as it is not allowed by constraint master from project loki.
	v2.8.1: Could not introduce github.com/prometheus/prometheus@v2.8.1, as it is not allowed by constraint master from project loki.
	v2.8.0: Could not introduce github.com/prometheus/prometheus@v2.8.0, as it is not allowed by constraint master from project loki.
```

**Comment by sandlis** [comment]
You don't need to run dep commands unless you want to do any code changes. There is a Makefile at root, which has different targets. You can just run `make` without any target to build Loki.

**Comment by mizeng** [comment]
yes, I want to try some code change like another Index Storage. I will try `make` and then see if there's no "Can not resolve" in Go IDE.

**Comment by sandlis** [comment]
dep would still not be required if your changes are not introducing any new dependencies or not requiring a different version of existing dependencies.

**Comment by mizeng** [comment]
any better method than "make" since make seems did lots of unnecessary steps like download docker image and helm?

**Comment by sandlis** [comment]
You can do this: https://github.com/grafana/loki/blob/master/production/README.md#build-and-run-from-source
