### ISSUE TITLE
Q) How to build docker image from source?

### ISSUE THREAD

**Issue by heesuk-ahn** [grafana/loki#6162]
**Q) How to build docker image from source?**

Hello,

 I am going to build an image and deploy it to kubernetes to verify the code modifications.  

How do I do a production build?

First, I tried `make loki-image`. 

However, when I deploy the image to kubernetes, the following error occurs.

```
standard_init_linux.go:211: exec user process caused "exec format error“
```

**Comment by chaudum** [comment]
`make loki-image` is the correct way to build the image. Are you trying to run an amd64 on arm (or vice versa)?

---

Please note that questions submitted as issues will be closed, but you can submit questions in the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)
