### ISSUE TITLE
Promtail Windows Event Log missing user_data

### ISSUE THREAD

**Issue by Frank-Bo** [grafana/loki#6167]
**Describe the bug**
I collect windows eventlog entries with promtail. The data that is available in Loki seems to be missing the data that is in the XML view of the eventlog entry in the "UserData" section. 
I have already explicitly set the parameters "exclude_event_data: false" and "exclude_user_data: false" in promtail.yaml, without success. If a detected field "user_data" appears in Loki, this only contains a copy of the data from "event_data".

**To Reproduce**
1. Configure promtail on a windows machine to send windows eventlogs to loki
2. Create a windows eventlog entry containing UserData in the XML view (sorry, but I can't give instructions for this)
3. Check out these log entries in Grafana (Loki). There are no "user_data" entries and if there are, they are copies of "event_data".

**Expected behavior**
Also the data from the UserData area of the eventlog entries should appear in Grafana / Loki.

**Environment:**
 - Local installation on a CentOS 7 server. 
 - Grafana 8.5.0
 - Loki 2.4.2
 - Promtail 2.4.2 (Windows)
 - Windows Server 2016 (promtail)

**Screenshots, Promtail config, or terminal output**
promtail.yaml attached

![image](https://user-images.githubusercontent.com/81165353/168562574-dc49bee4-88ff-4dd2-93bc-ba6f45e73239.png)
[promtail-config.yaml.txt](https://github.com/grafana/loki/files/8698861/promtail-config.yaml.txt)

**Comment by MarNicGit** [comment]
![image](https://user-images.githubusercontent.com/47538428/196555271-a95b8206-4477-46a5-b288-e180d4643860.png)
Well that's not going to work.. I've submitted a PR that fixes this :)
