### ISSUE TITLE
Fetch error: 404 Not Found Instantiating http://localhost:3000/public/plugins/trino-datasource/module.js Loading plugins/trino-datasource/module

### ISSUE THREAD

**Issue by nguyenthanhlong98** [grafana/loki#6168]

**Comment by nguyenthanhlong98** [comment]
package.jon 
{
  "name": "trino-datasource",
  "version": "1.0.0",
  "description": "The Trino datasource allows to query and visualize Trino data from within Grafana.",
  "scripts": {
    "build": "grafana-toolkit plugin:build",
    "test": "grafana-toolkit plugin:test",
    "dev": "grafana-toolkit plugin:dev",
    "watch": "grafana-toolkit plugin:dev --watch",
    "sign": "grafana-toolkit plugin:sign",
    "start": "yarn watch"
  },
  "author": {
    "name": "Starburst Data",
    "url": "https://www.starburst.io/"
  },
  "license": "Apache-2.0",
  "devDependencies": {
    "@grafana/data": "8.5.1",
    "@grafana/runtime": "8.5.1",
    "@grafana/toolkit": "8.5.1",
    "@grafana/ui": "8.5.1",
    "@types/lodash": "4.14.182"
  },
  "resolutions": {
    "rxjs": "7.5.5"
  },
  "engines": {
    "node": ">=14"
  },
  "dependencies": {
    "@grafana/aws-sdk": "^0.0.35"
  }
} 
![Screenshot from 2022-05-16 16-27-12](https://user-images.githubusercontent.com/45157728/168568271-ac334796-0fa8-4cc3-89f1-cc3db8c251ea.png)

**Comment by nguyenthanhlong98** [comment]
![Screenshot from 2022-05-23 16-24-19](https://user-images.githubusercontent.com/45157728/169788756-e85aa919-3385-4da4-b3d4-ddb705c58fb2.png)

**Comment by nguyenthanhlong98** [comment]
![Screenshot from 2022-05-23 16-24-19](https://user-images.githubusercontent.com/45157728/169788854-47f62352-aa3f-434e-ab96-866016b7ff84.png)

**Comment by MariusMiricaBE** [comment]
@nguyenthanhlong98 Did you fixed it? I'm having the same issue.

**Comment by nguyenthanhlong98** [comment]
> @nguyenthanhlong98 Did you fixed it? I'm having the same issue.

follow repo on github step in step 
importance "mage -v" and run config trino grafana ip of pc(192.168....:8080). No (localhost):8080
https://golangexample.com/the-trino-datasource-allows-to-query-and-visualize-trino-data-from-within-grafana/

**Comment by Ansonator** [comment]
I ran into this same error.  For me, it was because I had manually installed the repo to `/var/lib/grafana/plugins/trino`.  It worked after I installed it at `/var/lib/grafana/plugins/trino-datasource/`.
