### ISSUE TITLE
Secrets leak through the config endpoint

### ISSUE THREAD

**Issue by alanhe** [grafana/loki#6184]
**Describe the bug**
Sensitive information like aws `access_key_id` and `secret_access_key` are listed in plain text when calling the `[GET] /config` endpoint. It seems to be a security violation for most companies. 

**Expected behavior**
They are type of `secret` in code, so I guess they can be masked as ******* when displayed. Or, maybe add an option to disable the `/config` endpoint.

**Comment by chaudum** [comment]
Hi @alanhe 
Thanks for reporting this issue! I double checked and figured out that AWS S3 credentials are correctly redacted in the config, whereas the BOS credentials aren't. We will provide a fix asap.
