### ISSUE TITLE
Default dynamobd parameters create huge monthly cost

### ISSUE THREAD

**Issue by pancochea** [grafana/loki#6210]
**Is your feature request related to a problem? Please describe.**
Using the default configuration for DynamoDB as index store uses a default configuration that incures in important costs. 1000/3000 read/write provisioned is projected to around 500$ per month.

**Describe the solution you'd like**
There are different options:
- Warn about the costs
- Default to much lower provisioned r/w capacity and advice to change it as needed
- Default to on-demand r/w capacity

**Comment by JStickler** [comment]
Closing as DynamoDB was deprecated in 2.9.  We do not plan any further development for DynamoDB as a storage backend.
