### ISSUE TITLE
Docs feedback: /operations/storage/logs-deletion.md

### ISSUE THREAD

**Issue by Sheldun21** [grafana/loki#6228]
Hey team!

This only works for On-Prem instances of grafana and not cloud.

Can we get a line that specifies this?

Thanks team for all you do!

**Comment by GrafanaWriter** [comment]
@Sheldun21 - Can you please confirm that this is still true only for on-prem, as we've recently added log line deletion to Cloud.

**Comment by JStickler** [comment]
Closing as we support log deletion in Cloud.
