### ISSUE TITLE
Please improve SampleExtractionErr message

### ISSUE THREAD

**Issue by bboreham** [grafana/loki#6265]
**Is your feature request related to a problem? Please describe.**

I got a message like this:
```
pipeline error: 'SampleExtractionErr' for series: '{__error__="SampleExtractionErr", cluster="prod-us-east-0", container="builder", controller_revision_hash="builder-6c7c8956f8", day="18880", job="mimir-dedicated-20/builder", name="builder", namespace="mimir-dedicated-20", pod="builder-7", prefix="migration", size="219060439\n", statefulset_kubernetes_io_pod_name="builder-7", stream="stderr", tenant="<redacted>"}'. Use a label filter to intentionally skip this error. (e.g | __error__!="SampleExtractionErr"). To skip all potential errors you can match empty errors.(e.g __error__="") The label filter can also be specified after unwrap. (e.g | unwrap latency | __error__="" )
```

I could not get from this message what was wrong.

According to an expert "The message is saying that this label could not be converted into a sample most likely the `\n`".

**Describe the solution you'd like**
A clear and concise description of what went wrong, and/or what I can do to improve matters.

**Comment by heapdavid** [comment]
Seeing this too, and it's not clear what the issue is with the query

**Comment by slim-bean** [comment]
I just found my way back to this as well, found last week that the code I added wasn't complete :( Thanks @simonswine for finding and fixing this!
