### ISSUE TITLE
Make loki-mixin dashboards work out of the box with Helm chart

### ISSUE THREAD

**Issue by pracucci** [grafana/loki#6266]
I am quite new to loki and mixin dashboards. We are using loki-distributed helm chart in our environment. And it seems to be the new mixin pre complied dashboars under mixin-complied folder are not working in our environment. Since, we are not getting value for cluster varaible. Most of the fields are not refelcting the data.

Kind of googling myself now, how to customize the complied dashboards to make to use for the loki-distributed helm charts (oss).

Attached images for reference.
![image](https://user-images.githubusercontent.com/46374106/170760468-43d0d483-1c5a-4481-8437-3b3b71bd21b2.png)
![image](https://user-images.githubusercontent.com/46374106/170760535-86989840-380c-43ea-92f3-e303f0148430.png)

_Originally posted by @sureshgoli25 in https://github.com/grafana/loki/issues/6234#issuecomment-1139832160_

**Comment by trevorwhitney** [comment]
I am hoping to tackle this for the `loki-simple-scalable` chart this quarter. I believe it will need to be done differently from `loki-simple-scalable` and `loki-distributed` as the labels are different. If anyone would like to chip in on this effort please let me know.

**Comment by trevorwhitney** [comment]
Some work that's been done relating to this issue:
* Compiled version of mixin: https://github.com/grafana/loki/pull/6254
* Support for SSD in loki mixin: https://github.com/grafana/loki/pull/6540
* Include and make work out of the box in Loki Helm chart: https://github.com/grafana/helm-charts/pull/1514

**Comment by trevorwhitney** [comment]
Completed with #6540

**Comment by aslafy-z** [comment]
Any chance this lands to [`loki-distributed`](https://github.com/grafana/helm-charts/blob/main/charts/loki-distributed/) chart?

**Comment by trevorwhitney** [comment]
I would be happy to review a PR if you want to use #1514 as a starting point, but I won't have the bandwidth to work on that in the near future.

**Comment by agermain** [comment]
Should this be closed? I believe the main reason these do not work is because they use `job=~"($namespace)/cortex-gw"` which is not addressed by https://github.com/grafana/helm-charts/pull/1514. I'm a non-jsonnet user and these dashboards will not work out of the box. My understanding is that Grafana Labs has a closed-source component for that but as a mixin user of just the alerts and dashboards I'd love to see these work out of the box so as to remove any hacks (e.g. replacing label at compile time). Is this piece of work being tracked somewhere else?

Seems to overlap with https://github.com/grafana/loki/issues/6234. https://github.com/grafana/loki/pull/6189 seems like fixed it for jsonnet users.
cc: @trevorwhitney @pracucci

**Comment by trevorwhitney** [comment]
@agermain you should be able to set `internal_components: false` to remove any dashboards that rely on our internal, closed source gateway: `https://github.com/grafana/loki/blob/3990b13a25d4cad92437b43c6dc2fadaa837cc35/production/loki-mixin/config.libsonnet#L16`

**Comment by DaveOHenry** [comment]
@trevorwhitney The problem is that the mixin is not as configurable as it should be. Some improvements were made in the past, but as @agermain already mentioned the "job" label is the issue here, because it uses a special naming convention like "($namespace)/<loki component>.

**Comment by trevorwhitney** [comment]
the mixin is only intended to work with our opinionated scrape configs, which have relabel configs that combing namespace with job to create that job label. the helm chart deploys `PodLogs` resources with those specific scrape configs, so the mixin should work "out of the box" with the helm chart as per the issue title. are those scrape configs not creating that label as expected when you use the helm chart?

**Comment by agermain** [comment]
> the mixin is only intended to work with our opinionated scrape configs, which have relabel configs that combing namespace with job to create that job label. the helm chart deploys `PodLogs` resources with those specific scrape configs, so the mixin should work "out of the box" with the helm chart as per the issue title. are those scrape configs not creating that label as expected when you use the helm chart?

The original comment references the usage of loki-distributed, which does not have `PodLogs` resources. I believe Mimir's [mixin](https://github.com/grafana/mimir/blob/ac6b91c6964ea556507c8e4681bf0467c64b33bb/operations/mimir-mixin/config.libsonnet#L29-L45) flexibility is what could work for multiple users here.

**Comment by trevorwhitney** [comment]
As the loki-distributed chart is maintained by the community, and not used by the Loki team at GL, I would file an issue against that chart in the `grafana/helm-charts` repo. I think the easiest approach would be to add a `PodLogs` resource to that chart that matches our opinionated scrape config. Alternatively you could PR the mixin to be more flexible. I would happy to give a review to either. Thanks!
