### ISSUE TITLE
Cassandra Client miss ConnectTimeout config

### ISSUE THREAD

**Issue by mizeng** [grafana/loki#628]
**Is your feature request related to a problem? Please describe.**
When I try to use a remote Cassandra, I met issue as below
`level=error ts=2019-05-28T08:11:18.448574Z caller=main.go:62 msg="error initialising loki" err="error initialising module: table-manager: gocql: unable to create session: unable to discover protocol version: gocql: no response to connection startup within timeout"`

It seems timeout when connecting to Cassandra. I red the source code in `cassandra.storage_client.go`, and found it supports a config named "Timeout". So I added this config and try again, but not works. 
Dig into Cassandra code, I found another config named "ConnectTimeout" which is "initial connection timeout, used during initial dial to server (default: 600ms)". I Then added this config with 6s, and the connecting problem is gone.

**Describe the solution you'd like**
![Screen Shot 2019-05-28 at 4 37 47 PM](https://user-images.githubusercontent.com/8059086/58463727-f7781480-8166-11e9-9ff3-e1dfdcf0879d.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by daixiang0** [comment]
not sure introduced by high version cassandra, file issue in corex project to confirm.

**Comment by mizeng** [comment]
filed https://github.com/cortexproject/cortex/pull/1422

**Comment by mizeng** [comment]
@daixiang0 above pr is merged. Could you help to update the Loki side dependency code of cortex with something like "dep ensure"?

**Comment by mizeng** [comment]
@daixiang0  I've filed one pr, could you please help to review? https://github.com/grafana/loki/pull/649

**Comment by mizeng** [comment]
merged. so closed this ticket.
