### ISSUE TITLE
 Failed to pull image "grafana/grafana:8.5.3": rpc error: code = Unknown desc = reading manifest 8.5.3 in registry.centos.org/grafana/grafana: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by ahmedidris-waseel** [grafana/loki#6334]
**Describe the bug**
 Failed to pull image "grafana/grafana:8.5.3": rpc error: code = Unknown desc = reading manifest 8.5.3 in registry.centos.org/grafana/grafana: manifest unknown: manifest unknown

**To Reproduce**
helm install prometheus-stack prometheus-community/kube-prometheus-stack --create-namespace -n monitoring 
**Expected behavior**
garafan image  should run 

**Environment:**
 - Infrastructure: [e.g., Kubernetes]
 - Deployment tool: [ helm,]

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
<img width="949" alt="unknown manifest" src="https://user-images.githubusercontent.com/47633678/172570203-14774a29-d45e-4005-aea7-a7085805928f.png">

**Comment by dannykopping** [comment]
This doesn't seem related to Loki at all.

@ahmedidris-waseel maybe you can elaborate on why you created it in this repo?
Closing for now

**Comment by ahmedidris-waseel** [comment]
created another one in https://github.com/grafana/helm-charts/issues/1463
