### ISSUE TITLE
Panic due to `unwrap` in mapped range vector in query planning

### ISSUE THREAD

**Issue by owen-d** [grafana/loki#6344]
There's a panic @cstyan is looking into in the range-splitting code. When handling a `rate(foo | unwrap)`, we map it to `(count_over_time(split1) + count_over_time(split2) ..etc ) / duration`, but `count_over_time` doesn't support unwrap! There's also a little nit that it doesn't support _extrapolated rates_: https://github.com/grafana/loki/blob/main/pkg/logql/range_vector.go#L236

What if we changed the optimization to the following:
```(rate(split1) * split1_duration + rate(split2) * split2_duration ..etc) / total_duration```

cc @cyriltovena @slim-bean @ssncferreira @chaudum

**Comment by chaudum** [comment]
@owen-d can you elaborate on what you mean with:

> There's also a little nit that it doesn't support extrapolated rates: https://github.com/grafana/loki/blob/main/pkg/logql/range_vector.go#L236
