### ISSUE TITLE
Log volume is not distributed properly over time

### ISSUE THREAD

**Issue by mdczaplicki** [grafana/loki#6350]
**Describe the bug**
Loki on Grafana 8.5.0 displays a clump of messages in log volume, instead of distribute them over time, like when they have occured.

**To Reproduce**
1. Started Loki 8.5.0 (6134e3cf35)
2. Query last 24 hours and see a clump of messages at around one point
3. Query last 6 hours and see volume distributed over time

**Expected behavior**
Volume is distributed properly over time regardless of range.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
![image](https://user-images.githubusercontent.com/9108586/172850100-93d1fa65-ffdf-40bd-bdf0-66b79ed952ba.png)
![image](https://user-images.githubusercontent.com/9108586/172850158-3cd7910c-2aa1-4219-9c56-5b906b891af0.png)

**Comment by mdczaplicki** [comment]
In first screenshot - you can see a volume from Last 24 hours. In second one - from Last 6 hours. Obviously - more volume is in the remaining 18 hours.

Just to make it a bit more clear - first screenshot shows 0 between 8:30 and now, whereas on the second screenshot - you can clearly see that there were some logs at these hours.

**Comment by DylanGuedes** [comment]
Np, thanks for reporting it.
