### ISSUE TITLE
Unclear concepts about queryfrontend and querier

### ISSUE THREAD

**Issue by caibirdme** [grafana/loki#6369]
I didn't find any docs about the role and the relations among these concepts:
* query-frontend
* frontendworker
* queryscheduler
* querier

According to the docs, I just know queryfrontend and querier, but frontend-worker and queryscheduler is unclear.
More specifically, what's the difference between querier and frontend-worker? I just see that `frontend-worker running within the querier`, but what does the `running WITHIN` means? Seems like they're the same thing, so why config at different places?

What's the relationship between query-frontend and query_scheduler？I just see
> The Query frontend has an in-memory queue that can be moved out into a separate process similar to the [Cortex Query Scheduler](https://cortexmetrics.io/docs/operations/scaling-query-frontend/#query-scheduler). This allows running multiple query frontends.

According to this, I guess query_scheduler is just a in-memory queue? If so, why not use redis but yet another service to just achieve such a simple functions? Or does it do more than I thought?

And according to
> It is not valid to start the querier with both a configured frontend and a scheduler address

So I cannot set frontend_address and scheduler_address at the same time right? What's the difference between using one or another? Which is better when considering scalebility? It's recommend to use query-frontend, but [Scalability](https://grafana.com/docs/loki/latest/operations/scalability/) document recommend query_scheduler？

I'm messed up, really need help from you.

I really hope that there's a clear components pictures to show all the components in microservice mode. 
* For read path, request to query-frondend, and then where's query_scheduler? where's frontend-worker. How does they comminicate with querier?
* `for avoiding deploy querier as statefulset, we recommend running an index-gateway .....  When using the Index Gateway within Kubernetes, we recommend using a StatefulSet with persistent storage for downloading and querying index files`. So I still need to deploy it as statefulset, either queier or index-gateway... What's the benefit of deploy querier as stateless and index-gateway as stateful?

**Comment by pbasgod7** [comment]
Thank you for raising this issue. I have to agree these concepts are so unclear.

**Comment by itsek** [comment]
Any Updates on this? The docs still don't explain it well

**Comment by gespi1** [comment]
bump

**Comment by JStickler** [comment]
@caibirdme, we've had a recent PR with an overhaul of the Components page that you can view [here](https://grafana.com/docs/loki/next/get-started/components/) that I think might answer most of these questions.

**Comment by JStickler** [comment]
Closed via #10666
