### ISSUE TITLE
Retrieve promtail configuration from HTTP endpoint

### ISSUE THREAD

**Issue by jedd** [grafana/loki#6387]
**Is your feature request related to a problem? Please describe.**

For metrics, we're using the Telegraf agent over node-exporter, primarily because of Telegraf's feature to pull config from an HTTP endpoint (in our case, NodeRED) at run time.

This lets us orchestrate configuration changes more easily, and needs only a regular restart cycle at the client end (eg. Restart / RuntimeMaxSec in the promtail systemd job).

Promtail's configuration must be provided at installation time and must be local to the client.

We have some existing orchestration tools around managing that, but these are more cumbersome than the remote-http endpoint approach.

So, the problem is that Promtail client configuration options are are limited to either a) install time, or b) third party CM tooling.

**Describe the solution you'd like**

As per InfluxDB's Telegraf doc:  https://docs.influxdata.com/telegraf/v1.21/administration/configuration/#configuration-file-locations

We would like to see a similar option, eg:

Filename and path, for example: --config /etc/promtail/promtail.yml
or
Remote URL endpoint, for example: --config "http://remote-URL-endpoint/%hostname"

InfluxDB described the process for Telegraf configurations over this channel in more detail at:

https://www.influxdata.com/blog/continuous-deployment-of-telegraf-configurations/

**Describe alternatives you've considered**

Ansible.  But it made me sad.

**Additional context**

The file_sd_configs directive may complicate this, but I suspect the option would exist to specify that/those in whatever configuration was shipped over the http channel, and thereby leave some local configuration options available by retaining local control over those sub-directories.   This may add complexity but increase versatility for config management.

**Comment by dannykopping** [comment]
I really like this idea, and we've discussed it internally within the Loki team before.

I think we need to implement runtime config reloading first before we implement this. That would also make it easier to orchestrate using Ansible (or some other IaC tool) because one could just manage the file and not have to orchestrate a restart of Promtail.

The security implications of this are interesting, as well. If an attacker were able to control your Promtail config, this would allow them to exfiltrate all data from that system, so we'd need to consider some kind of key exchange requirement.

**Comment by teaey** [comment]
It's a real requirements in my situation, I still think about how to do this.

**Comment by jedd** [comment]
> Sounds cool, It's a real requirement in my situation, I still think about how to do this.

@teaey  you've likely worked around or solved this locally already - but for posterity on this ticket I'll note we're experimenting with an approach I've written up in more detail in a sibling issue on this project, where we're using some systemd features, and calling back to nodered (a tool we're already using to dynamically build & deliver telegraf configs on the fly)  
  https://github.com/grafana/loki/issues/6388#issuecomment-1805121981

**Comment by cstyan** [comment]
@jedd closing re: our discussion on the other issue. Hopefully there's some support for your use case within the Agent soon :+1:
