### ISSUE TITLE
__line__ function not defined in label_format()

### ISSUE THREAD

**Issue by dokterbob** [grafana/loki#6402]
**Describe the bug**
The [documentation for template functions](https://grafana.com/docs/loki/latest/logql/template_functions/) mentions that line values can be accessed with `__line__`. In #4879 (Loki 2.5.0) it does seem that this was added to `line_format()` but it does not seem to be implemented for `label_format()`

**To Reproduce**
1. Started Loki (2.5.0)
2. Started Promtail to tail systemd journal
3. Query: `{unit="cron.service"} | label_format line=`{{ __line__ }}``

**Expected behavior**
Log output with `line` label set to value of line.

**Actual behavior**
Query error: `rpc error: code = Unknown desc = parse error : stage '| label_format line="{{ __line__ }}"' : invalid template for label 'line': template: label:1: function "__line__" not defined`

**Screenshots, Promtail config, or terminal output**
![image](https://user-images.githubusercontent.com/22742/173842390-3395be2c-2c64-4932-86c4-cf9b8aac4fe2.png)

**Comment by wxybear** [comment]
maybe you should use line_format
