### ISSUE TITLE
issue about promtail load

### ISSUE THREAD

**Issue by gotosre** [grafana/loki#6426]
i use filebeat to collect log, file input -> kafka output,,,and then use promtail(30 replicas) to consume kafka topic (120+ partition), do some dirty work then sink to loki. but for ordered stream, i cannot make cpu load of promtails as balanced as possible. that's one point.

promtail send stream to distributor via service(cluster ip) with only one network connection, that means  
here are as many loki instances as there are long connections. It is difficult to ensure load balancing through clutsterip.

The above two points, how can I make the load as balanced as possible？

plz help.

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
