### ISSUE TITLE
Return a different error when query is out of retention.

### ISSUE THREAD

**Issue by jeschkies** [grafana/loki#6438]
**Is your feature request related to a problem? Please describe.**
When I issue a query that is older than the retention period I receive an error message such as
```
invalid query, through < from (2021-10-27 00:00:00 +0000 UTC < 2022-05-20 15:42:06.265393559 +0000 UTC m=-2394895.003142755) 
```

That message is not too enlightening.

**Describe the solution you'd like**
Ideally the message would tell me that the query is outside of the retention period.

**Comment by stazdx** [comment]
This data is no longer available. Check the documentation if you want to extend the retention storage.

The idea is that 'retention storage' redirects to the url https://grafana.com/docs/loki/latest/operations/storage/retention/
