### ISSUE TITLE
Allow setting an alternate URL for usage reporting

### ISSUE THREAD

**Issue by MichaelCosby** [grafana/loki#6502]
**Is your feature request related to a problem? Please describe.**
I want to enable usage reporting, but the network setup of my application doesn't allow it. Specifically, the host that I run Loki cannot make requests to the internet. Since we have *very* few places where our system needs to make requests out, we have not created any kind of generic web proxy for outgoing connections so I can't just set up a standard proxy.

**Describe the solution you'd like**
I would like to have Loki make its requests to a configurable alternate URL. In my specific case, that URL would call an AWS lambda via HTTPS, and the lambda would then send the data on to stats.grafana.org. This gives me control and visibility over what data leaves our system and how it goes out.

**Describe alternatives you've considered**
I *could* implement this by adding an entry for stats.grafana.org in my private DNS and then adding my own certificate authority to the OS so that the TLS request continues to work. It will be difficult to justify spending that much time on this problem to my project manager.

I could also implement this by adding inspecting web proxy software, which would essentially be having a third party do the certificate authority and server certificate solution specified above. That would be expensive and time-consuming and, again, would only be used to send usage reports for Loki. While I believe that sending usage reports back is the right thing to do (and can benefit me directly with expanded features or continued support), it's difficult to justify the time and expense of that solution to my project manager as well.

**Comment by slim-bean** [comment]
Thanks for the issue @MichaelCosby and double thanks for taking the time to try to make stats collection work, it's proving to be really insightful for us so far!

I can't think of any reason why we couldn't expose the URL used in the configuration, this seems like a good idea to me. If this is something you have any time to do that would be awesome but it's also something we can probably get to in the near future as well.  I'm already really appreciative that you are trying this hard to make it work ❤️
