### ISSUE TITLE
json logs broken up into multiple lines

### ISSUE THREAD

**Issue by christopher-wong** [grafana/loki#651]
**Describe the bug**
When viewing JSON logs with Loki, it looks like Loki splits the JSON object between multiple lines, rather than having a whole object with queryable keys.

**Expected behavior**
Each JSON object should be a log line rather than split between lines.

```
2019-06-04 12:21:40	{ "region" : "us-west-2", ... }
```

**Environment:**
 - Infrastructure: Kubernets (AWS EKS)
 - Deployment tool: helm

**Screenshots, promtail config, or terminal output**
in the Grafana Explorer tab
```
2019-06-04 12:21:40	}
2019-06-04 12:21:40	"region" : "us-west-2"
2019-06-04 12:21:40	"environment" : "dev",
2019-06-04 12:21:40	"logType" : 2,
2019-06-04 12:21:40	"message" : "test logging message",
2019-06-04 12:21:40	"class" : "",
2019-06-04 12:21:40	"application" : "",
2019-06-04 12:21:40	{
```

**Comment by slim-bean** [comment]
Interesting, I think this is more of a grafana issue than loki, my money says those log lines have `\n` characters in them. @christopher-wong can you look at the raw log files and look if there is line break characters within the json?

**Comment by christopher-wong** [comment]
Ah, @slim-bean you're right. This is totally a user error. Accidentally pretty-printing the json. Closing this out.
