### ISSUE TITLE
build: getting lots of `unknown revision` errors

### ISSUE THREAD

**Issue by Dentrax** [grafana/loki#6519]
**Describe the bug**

Opened the fresh downloaded repo with Goland and got some weird errors:

```
go: github.com/ionos-cloud/sdk-go/v6@v6.0.5851: invalid version: unknown revision v6.0.5851
go: golang.zx2c4.com/wireguard@v0.0.20200121: invalid version: unknown revision v0.0.20200121
go: github.com/prometheus/prometheus@v1.8.2-0.20211119115433-692a54649ed7 requires
	github.com/ionos-cloud/sdk-go/v6@v6.0.5851: reading github.com/ionos-cloud/sdk-go/go.mod at revision v6.0.5851: unknown revision v6.0.5851
```

```
$ go mod tidy

go: github.com/prometheus/prometheus@v1.8.2-0.20211119115433-692a54649ed7 requires
	github.com/ionos-cloud/sdk-go/v6@v6.0.5851: reading github.com/ionos-cloud/sdk-go/go.mod at revision v6.0.5851: unknown revision v6.0.5851
```

Version: 8eed9a4ddebe5b5ccbd332ae517c4effe381da2a

**To Reproduce**
1. Fresh clone
2. cd into it, open with goland
3. see the errors

**Expected behavior**
It should work?

**Environment:**
`-`

**Screenshots, Promtail config, or terminal output**
`-`

Any thoughts how to fix these?

**Comment by Dentrax** [comment]
Keep getting different errors on Golang:

Added the following line and error has changed:
```
replace github.com/ionos-cloud/sdk-go/v6 => github.com/ionos-cloud/sdk-go/v6 v6.1.0
```

Error:
```
$ go mod tidy

go: github.com/thanos-io/thanos@v0.22.0 requires
	github.com/efficientgo/e2e@v0.11.2-0.20211027134903-67d538984a47 requires
	github.com/efficientgo/tools/core@v0.0.0-20210129205121-421d0828c9a6: invalid version: unknown revision 421d0828c9a6
```

Goland throws:
```
go: github.com/grafana/loki@v1.6.2-0.20220128102010-431d018ec64f: invalid version: unknown revision 431d018ec64f
go: github.com/harlow/kinesis-consumer@v0.3.6-0.20210911031324-5a873d6e9fec: invalid version: unknown revision 5a873d6e9fec
```

**Comment by javierhonduco** [comment]
Hi @Dentrax! Just in case this is still causing issues for you, I bumped into this when I saw this same error in our project, https://github.com/ionos-cloud/sdk-go/issues/27 seems to be the culprit

**Comment by Dentrax** [comment]
Thanks for the letting me know! 🤗 @javierhonduco Have you solved it yet? What should I do here?

**Comment by javierhonduco** [comment]
I haven't properly solved it, but setting `GOPROXY="https://proxy.golang.org,direct"` unblocked me

**Comment by Dentrax** [comment]
You are awesome @javierhonduco!

```
$ go env -w GOPROXY="https://proxy.golang.org,direct"
```

This one fixed the issue. Thanks! ❤️
