### ISSUE TITLE
rules page of grafana no data

### ISSUE THREAD

**Issue by egoisz** [grafana/loki#6523]
**Describe the bug**
My rule configuration has taken effect, and can also successfully alarm to alertmanager。
Grafana add loki database successfully，but i cannot see the rules on the page of grafana,there seems to be no data。
 curl http://loki-gateway:3100/prometheus/api/v1/rules reture
`
{"status":"success","data":{"groups":[]},"errorType":"","error":""}
`
How can i see the rules on my grafana。

i use helm deploy on k8s
Chart：grafana/loki-distributed-0.49.0
values.yaml：

`
global:
  image:

    registry: null

  priorityClassName: null

  clusterDomain: "cluster.local"

  dnsService: "kube-dns"

  dnsNamespace: "kube-system"

nameOverride: null

fullnameOverride: null

imagePullSecrets: []

loki:

  annotations: {}

  readinessProbe:
    httpGet:
      path: /ready
      port: http
    initialDelaySeconds: 30
    timeoutSeconds: 1
  livenessProbe:
    httpGet:
      path: /ready
      port: http
    initialDelaySeconds: 300
  image:

    registry: docker.io

    repository: grafana/loki

    tag: null

    pullPolicy: IfNotPresent

  podLabels: {}

  podAnnotations: {}

  revisionHistoryLimit: 10

  podSecurityContext:
    fsGroup: 10001
    runAsGroup: 10001
    runAsNonRoot: true
    runAsUser: 10001

  containerSecurityContext:
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
    allowPrivilegeEscalation: false

  existingSecretForConfig: ""

  config: |
    auth_enabled: false

    server:
      http_listen_port: 3100

    distributor:
      ring:
        kvstore:
          store: memberlist

    memberlist:
      join_members:
        - {{ include "loki.fullname" . }}-memberlist

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
      chunk_idle_period: 30m
      chunk_block_size: 262144
      chunk_encoding: snappy
      chunk_retain_period: 1m
      max_transfer_retries: 0
      wal:
        dir: /var/loki/wal

    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_cache_freshness_per_query: 10m
      split_queries_by_interval: 15m

    {{- if .Values.loki.schemaConfig}}
    schema_config:
    {{- toYaml .Values.loki.schemaConfig | nindent 2}}
    {{- end}}
    {{- if .Values.loki.storageConfig}}
    storage_config:
    {{- if .Values.indexGateway.enabled}}
    {{- $indexGatewayClient := dict "server_address" (printf "dns:///%s:9095" (include "loki.indexGatewayFullname" .)) }}
    {{- $_ := set .Values.loki.storageConfig.boltdb_shipper "index_gateway_client" $indexGatewayClient }}
    {{- end}}
    {{- toYaml .Values.loki.storageConfig | nindent 2}}
    {{- end}}

    chunk_store_config:
      max_look_back_period: 0s

    table_manager:
      retention_deletes_enabled: true
      retention_period: 24h

    query_range:
      align_queries_with_step: true
      max_retries: 5
      cache_results: true
      results_cache:
        cache:
          enable_fifocache: true
          fifocache:
            max_size_items: 1024
            validity: 24h

    frontend_worker:
      frontend_address: {{ include "loki.queryFrontendFullname" . }}:9095

    frontend:
      log_queries_longer_than: 5s
      compress_responses: true
      tail_proxy_url: http://{{ include "loki.querierFullname" . }}:3100

    compactor:
      shared_store: filesystem

    ruler:
      storage:
        type: local
        local:
          directory: /etc/loki/rules
      ring:
        kvstore:
          store: memberlist
      rule_path: /tmp/loki/scratch
      enable_alertmanager_v2: true
      enable_api: true         
      enable_sharding: true   

      alertmanager_url: http://10.3.15.83:9093

  schemaConfig:
    configs:
    - from: 2020-09-07
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: loki_index_
        period: 24h

  storageConfig:
    boltdb_shipper:
      shared_store: filesystem
      active_index_directory: /var/loki/index
      cache_location: /var/loki/cache
      cache_ttl: 168h
    filesystem:
      directory: /var/loki/chunks

  structuredConfig: {}
serviceAccount:

  create: true

  name: null

  imagePullSecrets: []

  annotations: {}

  automountServiceAccountToken: true

rbac:

  pspEnabled: false

  sccEnabled: false

serviceMonitor:

  enabled: false

  namespace: null

  namespaceSelector: {}

  annotations: {}

  labels: {}

  interval: null

  scrapeTimeout: null

  relabelings: []

  metricRelabelings: []

  scheme: http

  tlsConfig: null

prometheusRule:

  enabled: false

  namespace: null

  annotations: {}

  labels: {}

  groups: #[]
  - name: loki-rules
    rules:
      - record: job:loki_request_duration_seconds_bucket:sum_rate
        expr: sum(rate(loki_request_duration_seconds_bucket[1m])) by (le, job)
      - record: job_route:loki_request_duration_seconds_bucket:sum_rate
        expr: sum(rate(loki_request_duration_seconds_bucket[1m])) by (le, job, route)
      - record: node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate
        expr: sum(rate(container_cpu_usage_seconds_total[1m])) by (node, namespace, pod, container)

ingester:

  kind: StatefulSet

  replicas: 1
  image:

    registry: null

    repository: null

    tag: null

  priorityClassName: null

  podLabels: {}

  podAnnotations: {}

  serviceLabels: {}

  extraArgs: []

  extraEnv: []

  extraEnvFrom: []

  extraVolumeMounts: []

  extraVolumes: []

  resources: {}

  extraContainers: []

  terminationGracePeriodSeconds: 300

  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              {{- include "loki.ingesterSelectorLabels" . | nindent 10 }}
          topologyKey: kubernetes.io/hostname
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                {{- include "loki.ingesterSelectorLabels" . | nindent 12 }}
            topologyKey: failure-domain.beta.kubernetes.io/zone

  nodeSelector: {}

  tolerations: []
  persistence:

    enabled: true

    size: 10Gi

    storageClass: loki-local-pv

distributor:

  replicas: 1
  autoscaling:

    enabled: false

    minReplicas: 1

    maxReplicas: 3

    targetCPUUtilizationPercentage: 60

    targetMemoryUtilizationPercentage:
  image:

    registry: null

    repository: null

    tag: null

  priorityClassName: null

  podLabels: {}

  podAnnotations: {}

  serviceLabels: {}

  extraArgs: []

  extraEnv: []

  extraEnvFrom: []

  extraVolumeMounts: []

  extraVolumes: []

  resources: {}

  extraContainers: []

  terminationGracePeriodSeconds: 30

  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              {{- include "loki.distributorSelectorLabels" . | nindent 10 }}
          topologyKey: kubernetes.io/hostname
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                {{- include "loki.distributorSelectorLabels" . | nindent 12 }}
            topologyKey: failure-domain.beta.kubernetes.io/zone

  nodeSelector: {}

  tolerations: []

querier:

  replicas: 1
  autoscaling:

    enabled: false

    minReplicas: 1

    maxReplicas: 3

    targetCPUUtilizationPercentage: 60

    targetMemoryUtilizationPercentage:
  image:

    registry: null

    repository: null

    tag: null

  priorityClassName: null

  podLabels: {}

  podAnnotations: {}

  serviceLabels: {}

  extraArgs: []

  extraEnv: []

  extraEnvFrom: []

  extraVolumeMounts: []

  extraVolumes: []

  resources: {}

  extraContainers: []

  terminationGracePeriodSeconds: 30

  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              {{- include "loki.querierSelectorLabels" . | nindent 10 }}
          topologyKey: kubernetes.io/hostname
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                {{- include "loki.querierSelectorLabels" . | nindent 12 }}
            topologyKey: failure-domain.beta.kubernetes.io/zone

  nodeSelector: {}

  tolerations: []
  persistence:

    enabled: false

    size: 10Gi

    storageClass: null

queryFrontend:

  replicas: 1
  autoscaling:

    enabled: false

    minReplicas: 1

    maxReplicas: 3

    targetCPUUtilizationPercentage: 60

    targetMemoryUtilizationPercentage:
  image:

    registry: null

    repository: null

    tag: null

  priorityClassName: null

  podLabels: {}

  podAnnotations: {}

  serviceLabels: {}

  extraArgs: []

  extraEnv: []

  extraEnvFrom: []

  extraVolumeMounts: []

  extraVolumes: []

  resources: {}

  extraContainers: []

  terminationGracePeriodSeconds: 30

  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              {{- include "loki.queryFrontendSelectorLabels" . | nindent 10 }}
          topologyKey: kubernetes.io/hostname
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                {{- include "loki.queryFrontendSelectorLabels" . | nindent 12 }}
            topologyKey: failure-domain.beta.kubernetes.io/zone

  nodeSelector: {}

  tolerations: []

tableManager:

  enabled: false
  image:

    registry: null

    repository: null

    tag: null

  priorityClassName: null

  podLabels: {}

  podAnnotations: {}

  serviceLabels: {}

  extraArgs: []

  extraEnv: []

  extraEnvFrom: []

  extraVolumeMounts: []

  extraVolumes: []

  resources: {}

  extraContainers: []

  terminationGracePeriodSeconds: 30

  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              {{- include "loki.tableManagerSelectorLabels" . | nindent 10 }}
          topologyKey: kubernetes.io/hostname
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                {{- include "loki.tableManagerSelectorLabels" . | nindent 12 }}
            topologyKey: failure-domain.beta.kubernetes.io/zone

  nodeSelector: {}

  tolerations: []

gateway:

  enabled: true

  replicas: 1

  verboseLogging: true
  autoscaling:

    enabled: false

    minReplicas: 1

    maxReplicas: 3

    targetCPUUtilizationPercentage: 60

    targetMemoryUtilizationPercentage:

  deploymentStrategy:
    type: RollingUpdate
  image:

    registry: docker.io

    repository: nginxinc/nginx-unprivileged

    tag: 1.19-alpine

    pullPolicy: IfNotPresent

  priorityClassName: null

  podLabels: {}

  podAnnotations: {}

  extraArgs: []

  extraEnv: []

  extraEnvFrom: []

  extraVolumes: []

  extraVolumeMounts: []

  podSecurityContext:
    fsGroup: 101
    runAsGroup: 101
    runAsNonRoot: true
    runAsUser: 101

  containerSecurityContext:
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
    allowPrivilegeEscalation: false

  resources: {}

  extraContainers: []

  terminationGracePeriodSeconds: 30

  affinity: {}

  nodeSelector: {}

  tolerations: []

  service:

    port: 80

    type: ClusterIP

    clusterIP: null

    nodePort: null

    loadBalancerIP: null

    annotations: {}

    labels: {}

  ingress:

    enabled: false

    ingressClassName: ''

    annotations: {}

    hosts:
      - host: gateway.loki.example.com
        paths:
          - path: /

    tls:
      - secretName: loki-gateway-tls
        hosts:
          - gateway.loki.example.com

  basicAuth:

    enabled: false

    username: null

    password: null

    htpasswd: >-
      {{ htpasswd (required "'gateway.basicAuth.username' is required" .Values.gateway.basicAuth.username) (required "'gateway.basicAuth.password' is required" .Values.gateway.basicAuth.password) }}

    existingSecret: null

  readinessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 15
    timeoutSeconds: 1
  livenessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 30
  nginxConfig:

    logFormat: |-
      main '$remote_addr - $remote_user [$time_local]  $status '
              '"$request" $body_bytes_sent "$http_referer" '
              '"$http_user_agent" "$http_x_forwarded_for"';

    serverSnippet: ""

    httpSnippet: ""

    file: |
      worker_processes  5;  ## Default: 1
      error_log  /dev/stderr;
      pid        /tmp/nginx.pid;
      worker_rlimit_nofile 8192;

      events {
        worker_connections  4096;  ## Default: 1024
      }

      http {
        client_body_temp_path /tmp/client_temp;
        proxy_temp_path       /tmp/proxy_temp_path;
        fastcgi_temp_path     /tmp/fastcgi_temp;
        uwsgi_temp_path       /tmp/uwsgi_temp;
        scgi_temp_path        /tmp/scgi_temp;

        default_type application/octet-stream;
        log_format   {{ .Values.gateway.nginxConfig.logFormat }}

        {{- if .Values.gateway.verboseLogging }}
        access_log   /dev/stderr  main;
        {{- else }}

        map $status $loggable {
          ~^[23]  0;
          default 1;
        }
        access_log   /dev/stderr  main  if=$loggable;
        {{- end }}

        sendfile     on;
        tcp_nopush   on;
        resolver {{ .Values.global.dnsService }}.{{ .Values.global.dnsNamespace }}.svc.{{ .Values.global.clusterDomain }};

        {{- with .Values.gateway.nginxConfig.httpSnippet }}
        {{ . | nindent 2 }}
        {{- end }}

        server {
          listen             8080;

          {{- if .Values.gateway.basicAuth.enabled }}
          auth_basic           "Loki";
          auth_basic_user_file /etc/nginx/secrets/.htpasswd;
          {{- end }}

          location = / {
            return 200 'OK';
            auth_basic off;
          }

          location = /api/prom/push {
            proxy_pass       http://{{ include "loki.distributorFullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3100$request_uri;
          }

          location = /api/prom/tail {
            proxy_pass       http://{{ include "loki.querierFullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3100$request_uri;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
          }

          location ~ /prometheus/api/v1/alerts.* {
            proxy_pass       http://{{ include "loki.rulerFullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3100$request_uri;
          }
          location ~ /prometheus/api/v1/rules.* {
            proxy_pass       http://{{ include "loki.rulerFullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3100$request_uri;
          }
          location ~ /api/prom/rules.* {
            proxy_pass       http://{{ include "loki.rulerFullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3100$request_uri;
          }
          location ~ /api/prom/alerts.* {
            proxy_pass       http://{{ include "loki.rulerFullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3100$request_uri;
          }

          location ~ /api/prom/.* {
            proxy_pass       http://{{ include "loki.queryFrontendFullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3100$request_uri;
          }

          location = /loki/api/v1/push {
            proxy_pass       http://{{ include "loki.distributorFullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3100$request_uri;
          }

          location = /loki/api/v1/tail {
            proxy_pass       http://{{ include "loki.querierFullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3100$request_uri;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
          }

          location ~ /loki/api/.* {
            proxy_pass       http://{{ include "loki.queryFrontendFullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3100$request_uri;
          }

          {{- with .Values.gateway.nginxConfig.serverSnippet }}
          {{ . | nindent 4 }}
          {{- end }}
        }
      }

compactor:

  enabled: false
  image:

    registry: null

    repository: null

    tag: null

  priorityClassName: null

  podLabels: {}

  podAnnotations: {}

  serviceLabels: {}

  extraArgs: []

  extraEnv: []

  extraEnvFrom: []

  extraVolumeMounts: []

  extraVolumes: []

  resources: {}

  extraContainers: []

  terminationGracePeriodSeconds: 30

  nodeSelector: {}

  tolerations: []
  persistence:

    enabled: false

    size: 10Gi

    storageClass: null
  serviceAccount:
    create: false

    name: null

    imagePullSecrets: []

    annotations: {}

    automountServiceAccountToken: true

ruler:

  enabled: true

  kind: Deployment

  replicas: 1
  image:

    registry: null

    repository: null

    tag: null

  priorityClassName: null

  podLabels: {}

  podAnnotations: {}

  serviceLabels: {}

  extraArgs: []

  extraEnv: []

  extraEnvFrom: []

  extraVolumeMounts: #[]
    - name: data
      mountPath: /etc/loki/rules

  extraVolumes: #[]
    - name: data
      emptyDir: {}

  resources: {}

  extraContainers: []

  terminationGracePeriodSeconds: 300

  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              {{- include "loki.rulerSelectorLabels" . | nindent 10 }}
          topologyKey: kubernetes.io/hostname
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                {{- include "loki.rulerSelectorLabels" . | nindent 12 }}
            topologyKey: failure-domain.beta.kubernetes.io/zone

  nodeSelector: {}

  tolerations: []
  persistence:

    enabled: false

    size: 10Gi

    storageClass: null

  directories: #{}
    tenant_foo:
      rules1.txt: |
        groups:
          - name: should_fire
            rules:
              - alert: HighPercentageError
                expr: |
                   sum(rate({app="promtail",namespace="loki"} [5m])) > 0 
                for: 30s
                labels:
                  severity: warning
                  type: loki-k8s-221
                annotations:
                  summary: High error rate

indexGateway:

  enabled: false

  replicas: 1
  image:

    registry: null

    repository: null

    tag: null

  priorityClassName: null

  podLabels: {}

  podAnnotations: {}

  serviceLabels: {}

  extraArgs: []

  extraEnv: []

  extraEnvFrom: []

  extraVolumeMounts: []

  extraVolumes: []

  resources: {}

  extraContainers: []

  terminationGracePeriodSeconds: 300

  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              {{- include "loki.indexGatewaySelectorLabels" . | nindent 10 }}
          topologyKey: kubernetes.io/hostname
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                {{- include "loki.indexGatewaySelectorLabels" . | nindent 12 }}
            topologyKey: failure-domain.beta.kubernetes.io/zone

  nodeSelector: {}

  tolerations: []
  persistence:

    enabled: false

    size: 10Gi

    storageClass: null

memcached:
  readinessProbe:
    tcpSocket:
      port: http
    initialDelaySeconds: 5
    timeoutSeconds: 1
  livenessProbe:
    tcpSocket:
      port: http
    initialDelaySeconds: 10
  image:

    registry: docker.io

    repository: memcached

    tag: 1.6.7-alpine

    pullPolicy: IfNotPresent

  podLabels: {}

  podSecurityContext:
    fsGroup: 11211
    runAsGroup: 11211
    runAsNonRoot: true
    runAsUser: 11211

  containerSecurityContext:
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
    allowPrivilegeEscalation: false

memcachedExporter:

  enabled: false
  image:

    registry: docker.io

    repository: prom/memcached-exporter

    tag: v0.6.0

    pullPolicy: IfNotPresent

  podLabels: {}

  resources: {}

memcachedChunks:

  enabled: false

  replicas: 1

  priorityClassName: null

  podLabels: {}

  podAnnotations: {}

  serviceLabels: {}

  extraArgs:
    - -I 32m

  extraEnv: []

  extraEnvFrom: []

  resources: {}

  extraContainers: []

  terminationGracePeriodSeconds: 30

  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              {{- include "loki.memcachedChunksSelectorLabels" . | nindent 10 }}
          topologyKey: kubernetes.io/hostname
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                {{- include "loki.memcachedChunksSelectorLabels" . | nindent 12 }}
            topologyKey: failure-domain.beta.kubernetes.io/zone

  nodeSelector: {}

  tolerations: []

memcachedFrontend:

  enabled: false

  replicas: 1

  priorityClassName: null

  podLabels: {}

  podAnnotations: {}

  serviceLabels: {}

  extraArgs:
    - -I 32m

  extraEnv: []

  extraEnvFrom: []

  resources: {}

  extraContainers: []

  terminationGracePeriodSeconds: 30

  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              {{- include "loki.memcachedFrontendSelectorLabels" . | nindent 10 }}
          topologyKey: kubernetes.io/hostname
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                {{- include "loki.memcachedFrontendSelectorLabels" . | nindent 12 }}
            topologyKey: failure-domain.beta.kubernetes.io/zone

  nodeSelector: {}

  tolerations: []

memcachedIndexQueries:

  enabled: false

  replicas: 1

  priorityClassName: null

  podLabels: {}

  podAnnotations: {}

  serviceLabels: {}

  extraArgs:
    - -I 32m

  extraEnv: []

  extraEnvFrom: []

  resources: {}

  extraContainers: []

  terminationGracePeriodSeconds: 30

  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              {{- include "loki.memcachedIndexQueriesSelectorLabels" . | nindent 10 }}
          topologyKey: kubernetes.io/hostname
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                {{- include "loki.memcachedIndexQueriesSelectorLabels" . | nindent 12 }}
            topologyKey: failure-domain.beta.kubernetes.io/zone

  nodeSelector: {}

  tolerations: []

memcachedIndexWrites:

  enabled: false

  replicas: 1

  priorityClassName: null

  podLabels: {}

  podAnnotations: {}

  serviceLabels: {}

  extraArgs:
    - -I 32m

  extraEnv: []

  extraEnvFrom: []

  resources: {}

  extraContainers: []

  terminationGracePeriodSeconds: 30

  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              {{- include "loki.memcachedIndexWritesSelectorLabels" . | nindent 10 }}
          topologyKey: kubernetes.io/hostname
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                {{- include "loki.memcachedIndexWritesSelectorLabels" . | nindent 12 }}
            topologyKey: failure-domain.beta.kubernetes.io/zone

  nodeSelector: {}

  tolerations: []

networkPolicy:

  enabled: false
  metrics:

    podSelector: {}

    namespaceSelector: {}

    cidrs: []
  ingress:

    podSelector: {}

    namespaceSelector: {}
  alertmanager:

    port: 9093

    podSelector: {}

    namespaceSelector: {}
  externalStorage:

    ports: []

    cidrs: []
  discovery:

    port: null

    podSelector: {}

    namespaceSelector: {}

`

**To Reproduce**
1. Started Loki (SHA or version) 2.5.0
2. Started Promtail (SHA or version) to tail '...'
3. Query: `{} term`

**Expected behavior**

**Environment:**
helm 
Chart：grafana/loki-distributed-0.49.0
k8s：1.21.8

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.

**Comment by jojotong** [comment]
> My rule configuration has taken effect, and can also successfully alarm to alertmanager。
Grafana add loki database successfully，but i cannot see the rules on the page of grafana,there seems to be no data。
curl http://loki-gateway:3100/prometheus/api/v1/rules reture
{"status":"success","data":{"groups":[]},"errorType":"","error":""}

I meet the same problem. After I read the source code, I found that it's because I use single tenant. So loki api `/prometheus/api/v1/rules`  only find rules in the `fake` directory. And I put it in another directory.

https://github.com/grafana/loki/blob/92aa69bb5cddb8a4344fb8fcf48a3b1ea14c3a01/pkg/ruler/base/ruler.go#L668-L678

Maybe this can help you @egoisz
