### ISSUE TITLE
Recreate SSL certs used by Promtail tests

### ISSUE THREAD

**Issue by dannykopping** [grafana/loki#6527]
**Is your feature request related to a problem? Please describe.**
We had to recently disable a bunch of tests in https://github.com/grafana/loki/pull/6520 to get around a CI failure in a hurry.

**Describe the solution you'd like**
We should regenerate these with an expiry of like 10 years (or more if you're bullish on the lifespan of Promtail :trollface:)

**Describe alternatives you've considered**
Leaving the tests disabled, but that's not ideal

**Additional context**
@johanfleury you introduced these tests in #3907 (thanks!). Would you like to do the honours of renewing these certs (but please pick a longer expiry this time hehe)?

**Comment by johanfleury** [comment]
Woops, sorry about that. Those certs were generated for my local tests (hence the “short” lifetime) and I didn’t think about it when I put them into the test suite.

I’ll make a PR to fix that.

**Comment by dannykopping** [comment]
No worries! :slightly_smiling_face: thanks a lot @johanfleury :+1:
