### ISSUE TITLE
Directly push to Loki via lambda promtail

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#6532]
Currently we require to push to promtail first from lambda when reading logs event from S3.

But I think we should just push to loki directly this means we just need to allow a relabeling config and apply it for each logs.

**Comment by sherifkayad** [comment]
In my view this is very relevant.. We also have a similar need .. Technically speaking that's already possible.. however, the labels prefixed with `__` make the consolidation / readability really bad!

Maybe introducing a flag `send_to_loki` could be a solution and if that flag is set, the underscore prefixes and the `extra_` prefix are omitted

**Comment by cstyan** [comment]
> Currently we require to push to promtail first from lambda when reading logs event from S3.

Not sure what you mean here Cyril, it's already possible to push directly to loki.

> But I think we should just push to loki directly this means we just need to allow a relabeling config and apply it for each logs.

AFAIK we have no plans to support this. Maybe in the future the integrations team(s) will take over lambda-promtail and build something better.

The ask about removing the `__` prefix from labels is separate. If it's still relevant to you @sherifkayad please open a new issue.

Thanks!
