### ISSUE TITLE
Docs: Confusing documentation about retention

### ISSUE THREAD

**Issue by chaudum** [grafana/loki#6538]
**Describe the bug**

The docs about retention are confusing and contradicting.

> With the exception of the filesystem chunk store, Loki will not delete old chunk stores. This is generally handled instead by configuring TTLs (time to live) in the chunk store of your choice (bucket lifecycles in S3/GCS, and TTLs in Cassandra). 

https://grafana.com/docs/loki/latest/storage/#retention

vs.

> Retention through the [Table Manager](https://grafana.com/docs/loki/latest/operations/storage/table-manager/) is achieved by relying on the object store TTL feature, and will work for both [boltdb-shipper](https://grafana.com/docs/loki/latest/operations/storage/boltdb-shipper) store and chunk/index store. However retention through the [Compactor](https://grafana.com/docs/loki/latest/operations/storage/boltdb-shipper#compactor) is supported only with the [boltdb-shipper](https://grafana.com/docs/loki/latest/operations/storage/boltdb-shipper) store.

https://grafana.com/docs/loki/latest/storage/retention/

The former paragraph seems out-of-data and probably dates pre boltdb-shipper.

**Comment by JStickler** [comment]
@chaudum , does #10665 provide what you were hoping to add to the retention docs?  Can we close this issue?
