### ISSUE TITLE
Docs feedback: /fundamentals/labels.md: What makes a valid label?

### ISSUE THREAD

**Issue by rjhenry** [grafana/loki#6580]
I can't find any documentation on what is (or isn't) a valid label name, and as such wound up trying to push an invalid label name to Promtail. Would it be possible to document the requirements of a label name somewhere, potentially with a validation regex?

I'll take a look through the code and see if I can find a codified set of requirements, and if so create a pull request for the documentation; however, I'm not familiar with the Loki codebase (or Go in general) so it may be faster for someone else to update the documentation.

**Comment by MasslessParticle** [comment]
Thanks for the feedback! Loki Has the same label requirements as [Prometheus](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels)

I've added a PR
