### ISSUE TITLE
Unable to fetch labels from Loki (Failed to call resource)

### ISSUE THREAD

**Issue by vermaprateek695** [grafana/loki#6587]
We are working on PLG (promtail , loki and grafana) stack setup  ,  loki is deployed in distributed microservice mode . Promtail and loki is working as expected but when trying to add loki as a datasource in grafana dashboard we are getting the below error (PFA screenshot for the same). Can you please help on this.

**Unable to fetch labels from Loki (Failed to call resource)**

**Error logs :**
[](url)
logger=ngalert.multiorg.alertmanager t=2022-07-06T11:32:32.828175492Z level=info msg="starting MultiOrg Alertmanager"
logger=context traceID=00000000000000000000000000000000 t=2022-07-06T11:32:47.106273241Z level=error msg="Failed to look up user based on cookie" error="user token not found"
logger=context traceID=00000000000000000000000000000000 userId=0 orgId=0 uname= t=2022-07-06T11:32:47.106855537Z level=info msg="Request Completed" method=GET path=/api/live/ws status=401 [remote_addr=103.109.144.47](url) time_ms=0 duration=882.467µs size=27 referer= traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 t=2022-07-06T11:32:49.972688308Z level=error msg="Failed to look up user based on cookie" error="user token not found"
logger=context traceID=00000000000000000000000000000000 userId=0 orgId=0 uname= t=2022-07-06T11:32:49.973230974Z level=info msg="Request Completed" method=GET path=/api/live/ws status=401 remote_addr=103.109.144.47 time_ms=0 duration=803.529µs size=27 referer= traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 t=2022-07-06T11:32:57.025815355Z level=error msg="Failed to look up user based on cookie" error="user token not found"
logger=context traceID=00000000000000000000000000000000 userId=0 orgId=0 uname= t=2022-07-06T11:32:57.026380308Z level=info msg="Request Completed" method=GET path=/api/live/ws status=401 remote_addr=103.109.144.47 time_ms=0 duration=806.61µs size=27 referer= traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 userId=0 orgId=0 uname= t=2022-07-06T11:33:28.986560031Z level=info msg="Request Completed" method=GET path=/ status=302 remote_addr=103.109.144.47 time_ms=0 duration=647.649µs size=29 referer= traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 t=2022-07-06T11:33:34.591524688Z level=error msg="Failed to look up user based on cookie" error="user token not found"
logger=http.server t=2022-07-06T11:34:15.053938616Z level=info msg="Successful Login" User=admin@localhost
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-07-06T11:34:16.391597856Z level=info msg="Request Completed" method=GET path=/api/live/ws status=0 remote_addr=103.109.144.47 time_ms=1 duration=1.238192ms size=0 referer= traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-07-06T11:34:35.330607964Z level=error msg="Failed to call resource" error="<html>\r\n<head><title>401 Authorization Required</title></head>\r\n<body>\r\n<center><h1>401 Authorization Required</h1></center>\r\n<hr><center>nginx/1.19.10</center>\r\n</body>\r\n</html>\r\n" traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-07-06T11:34:35.330686778Z level=error msg="Request Completed" method=GET path=/api/datasources/1/resources/labels status=500 remote_addr=103.109.144.47 time_ms=83 duration=83.244973ms size=83

**Comment by vermaprateek695** [comment]
![image](https://user-images.githubusercontent.com/108801624/177542478-815c3ee1-d5f5-48dc-8e4d-25e3d64065b7.png)

**Comment by vermaprateek695** [comment]
`[17:07] Shah, Krimesh
logger=ngalert.multiorg.alertmanager t=2022-07-06T11:32:32.828175492Z level=info msg="starting MultiOrg Alertmanager"
logger=context traceID=00000000000000000000000000000000 t=2022-07-06T11:32:47.106273241Z level=error msg="Failed to look up user based on cookie" error="user token not found"
logger=context traceID=00000000000000000000000000000000 userId=0 orgId=0 uname= t=2022-07-06T11:32:47.106855537Z level=info msg="Request Completed" method=GET path=/api/live/ws status=401 remote_addr=103.109.144.47 time_ms=0 duration=882.467µs size=27 referer= traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 t=2022-07-06T11:32:49.972688308Z level=error msg="Failed to look up user based on cookie" error="user token not found"
logger=context traceID=00000000000000000000000000000000 userId=0 orgId=0 uname= t=2022-07-06T11:32:49.973230974Z level=info msg="Request Completed" method=GET path=/api/live/ws status=401 remote_addr=103.109.144.47 time_ms=0 duration=803.529µs size=27 referer= traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 t=2022-07-06T11:32:57.025815355Z level=error msg="Failed to look up user based on cookie" error="user token not found"
logger=context traceID=00000000000000000000000000000000 userId=0 orgId=0 uname= t=2022-07-06T11:32:57.026380308Z level=info msg="Request Completed" method=GET path=/api/live/ws status=401 remote_addr=103.109.144.47 time_ms=0 duration=806.61µs size=27 referer= traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 userId=0 orgId=0 uname= t=2022-07-06T11:33:28.986560031Z level=info msg="Request Completed" method=GET path=/ status=302 remote_addr=103.109.144.47 time_ms=0 duration=647.649µs size=29 referer= traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 t=2022-07-06T11:33:34.591524688Z level=error msg="Failed to look up user based on cookie" error="user token not found"
logger=http.server t=2022-07-06T11:34:15.053938616Z level=info msg="Successful Login" User=admin@localhost
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-07-06T11:34:16.391597856Z level=info msg="Request Completed" method=GET path=/api/live/ws status=0 remote_addr=103.109.144.47 time_ms=1 duration=1.238192ms size=0 referer= traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-07-06T11:34:35.330607964Z level=error msg="Failed to call resource" error="<html>\r\n<head><title>401 Authorization Required</title></head>\r\n<body>\r\n<center><h1>401 Authorization Required</h1></center>\r\n<hr><center>nginx/1.19.10</center>\r\n</body>\r\n</html>\r\n" traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-07-06T11:34:35.330686778Z level=error msg="Request Completed" method=GET path=/api/datasources/1/resources/labels status=500 remote_addr=103.109.144.47 time_ms=83 duration=83.244973ms size=83 referer=https://grafana.ingress.eval.lp.shoot.live.k8s-hana.ondemand.com/datasources/edit/P982945308D3682D1 traceID=00000000000000000000000000000000
Grafana

`

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
