### ISSUE TITLE
Proposal: Release Pipeline

### ISSUE THREAD

**Issue by sh0rez** [grafana/loki#659]
From time to time it might happen that one needs a pre-compiled, stable binary or even a docker container of `loki`, `promtail` or `logcli`.

However, the current release pipeline seems to be broken (#647), is hand-baked using Makefile and scripts and does not cover any systems other than `linux/amd64`. As a rather simple solution to all of this at once, let's consider the following:

### 1. GoReleaser
[GoReleaser](https://github.com/goreleaser/goreleaser) is a delivery tool aimed at `go` applications and covers in its most basic form cross-compiling and packaging of binaries, optionally generating release notes from the commit history and publishing all of this as a GitHub release. The benefits of such a system are:

* **Simple flow**: `git tag vX.X.X && git push`, CI runs `goreleaser` on tag, `goreleaser` gets the job done
* **Cross compiling**: No multitude of hand-baked `make` targets, but rather a single clean `.yaml` file which defines the desired artifacts, `GOOS` and `GOARCH` matrix and build arguments and `goreleaser` automatically builds all required artifacts for all operating systems (`linux`, `windows`, `darwin`, `freebsd`, etc.) and all architectures (`arm6`, `arm7`, `arm64`, `amd64`, `i386`, etc.)
* **Package managers**: currently `snap` (linux in theory), `brew` (osx, linux) and `scoop` (windows). This might be interesting for `logcli`

Until this point, artifacts are built and published. Great for humans!

### 2. Advanced docker image
In the last couple of years, Docker advanced the build pipeline a lot. Two new features could be especially beneficial:

* **multi-stage builds**: Instead of building the binary outside and copying it into the docker container, one could easily use `FROM golang as builder`, (cross)-compile the binary and use `FROM scratch; COPY --from=builder /app /app`. This allows super-small, highly portable images. Because in the final stage no single `RUN` command is needed, we can build every arch on our `amd64` CI! (also works for `debug` alpine images)

* **image-manifest v2**: with this new version of the image-manifest spec, native support for cross-platform images was added. This means, by correctly preparing an image (e.g. using `docker manifest`), different individual oarch images could be published under the same tag and during the pull-procedure the right one is automatically picked. Docker already does this with all major library images. It does not only reduce tag-waste but also is super user-friendly.

And now, rigid docker-images are provided for every major architecture (`arm6`, `arm7`, `arm64`, `amd64`, `i386`, maybe `risc-v` soon). Great for machines!

Open to thoughts :) @Kuqd @slim-bean @gouthamve

**Comment by steven-sheehy** [comment]
Multi-stage docker builds are nice, but they don't offer the possible to produce binaries to be consumed outside of docker as some people have requested. It also doesn't handle uploading artifacts and writing release notes. I've used goreleaser and like its declarative syntax. Vote Option 1.

**Comment by sh0rez** [comment]
> @steven-sheehy 
> Multi-stage docker builds are nice, but they don't offer the possible to produce binaries to be consumed outside of docker as some people have requested. It also doesn't handle uploading artifacts and writing release notes. I've used goreleaser and like its declarative syntax. Vote Option 1.

Hi, I don't think we need to choose between those two, as they are complementary to each other. The GoReleaser pipeline handles the general purpose binaries, etc. But as it is for releases, it only runs for tags.

However, the Docker support of GoReleaser does not really support Manifest v2, so I thought it would be better to do it ourselves. Of course the multi-stage could be skipped in favor of `COPY`ing the artifact from GoReleaser.

**Comment by Kuqd** [comment]
I'll be more than happy to have better targets for binaries.

Never used goreleaser but I'm not opposed to it.

**Comment by sh0rez** [comment]
> I'll be more than happy to have better targets for binaries.
> 
> Never used goreleaser but I'm not opposed to it.

Awesome! I'll start working on it.

**Comment by sh0rez** [comment]
Okay, an advanced docker image is available for testing at #668. Feedback is welcome!
