### ISSUE TITLE
Connect to Tempo through parsed labels, not only through fields

### ISSUE THREAD

**Issue by franroa** [grafana/loki#6614]
Hi there,

I was wondering if there is a way of using labels parsed from json to connect to Tempo, or maybe create derived fields from those labels.
Attached an image to explain

<img width="936" alt="loki-question" src="https://user-images.githubusercontent.com/2432583/177778968-332466ed-1222-48b3-b503-b45667f2478a.PNG">

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.

**Comment by JavaPerformance** [comment]
Could I re-open this as a feature request?
