### ISSUE TITLE
Loki doesn't report flush stats if cache is failing

### ISSUE THREAD

**Issue by saroshali-dbx** [grafana/loki#6674]
**Describe the bug**
If the cache is down, e.g. due to a misconfiguration, then Loki doesn't report stats on flushing chunks.  

**To Reproduce**
1. Started Loki version 2.5.0
2. Configure caching on the ingester, utilizing an invalid caching addr/endpoint/discovery, e.g. 
`
"-store.chunks-cache.cache-stubs=true",
"-store.chunks-cache.memcached.addresses={{INVALID_MEMCACHE_ADDR}}",
"-store.index-cache-write.memcached.addresses={{INVALID_MEMCACHE_ADDR}}"
`

**Expected behavior**
I expect failures in the cache to not impact writing to object storage and/or incrementing stats. 
Code Link: https://github.com/grafana/loki/blob/7f50a266560add019e47500ca29d87b7d8848938/pkg/ingester/flush.go#L366

**Comment by DylanGuedes** [comment]
thanks for reporting it, I'll take a look at it today.

**Comment by DylanGuedes** [comment]
Do you mind double checking this? With log-level=debug I could see the log message that reports that a flush is occurring just fine with the args you mentioned.

**Comment by saroshali-dbx** [comment]
Closing, not able to reproduce. Guessing was a flake with something in my environment.
