### ISSUE TITLE
Loki monitorin all namespace from kubernetes but its no necesary

### ISSUE THREAD

**Issue by alexisHuaracMallqui** [grafana/loki#6676]
install loke with the chart helm in a specific namespace but when I integrate it with grafana, it appears that loki starts to monitor the entire cluster, I mean that loki brings me information from other namespaces that I don't want to save their log, this configuration is correct ?

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
