### ISSUE TITLE
Port to arm64

### ISSUE THREAD

**Issue by vielmetti** [grafana/loki#67]
The build scripts have several dependencies on x86 that would need to be address to port `loki` to arm64.

* at https://github.com/grafana/loki/blob/master/loki-build-image/Dockerfile#L5 , Docker is installed by copying in an x86_64 binary
* at https://github.com/grafana/loki/blob/master/loki-build-image/Dockerfile#L16 , `gometalinter` is installed by copying in a linux-amd64 binary.

The `gometalinter` issue is also related at https://github.com/alecthomas/gometalinter/issues/566 , and probably needs to be dealt with first.

**Comment by vielmetti** [comment]
The `gometalinter` question is resolved.

**Comment by Kuqd** [comment]
closing in favor of #653
