### ISSUE TITLE
JSON Parser: Unable to extract field with `-` by parmeter name

### ISSUE THREAD

**Issue by danpoltawski** [grafana/loki#6716]
**Describe the bug**
Given the log line containing the json blob:
```
{"entry":"hello world","test-severity":"info"}
```

It's not possible to extract `test-severity` by parameter value using the `json` parser.

**To Reproduce**

1. Generate a log entry with the problematic contents  e.g. `echo '{"entry":"hello world","test-severity":"info"}' | logger`
3. Try to extract the `test-severity` as a label:

```
{hostname="dev"} |= `hello world` | json severity=`test-severity`
# 2 errors: rpc error: code = Unknown desc = parse error : stage '| json severity="test-severity"' : cannot parse expression [test-severity]: unexpected char -; rpc error: code = Unknown desc = parse error : stage '| json severity="test-severity"' : cannot parse expression [test-severity]: unexpected char - 

{hostname="dev"} |= `hello world` | json severity=`test\-severity`
# 2 errors: rpc error: code = Unknown desc = parse error : stage '| json severity="test\\-severity"' : cannot parse expression [test\-severity]: unexpected char \; rpc error: code = Unknown desc = parse error : stage '| json severity="test\\-severity"' : cannot parse expression [test\-severity]: unexpected char \ 

{hostname="dev"} |= `hello world` | json severity=`"test-severity"`
# 2 errors: rpc error: code = Unknown desc = parse error : stage '| json severity="\"test-severity\""' : cannot parse expression ["test-severity"]: syntax error: unexpected STRING, expecting LSB or FIELD; rpc error: code = Unknown desc = parse error : stage '| json severity="\"test-severity\""' : cannot parse expression ["test-severity"]: syntax error: unexpected STRING, expecting LSB or FIELD 

{hostname="dev.tnp.infra"} |= `hello world` | unpack | json severity=`test_severity`
#  (Doesn't match the value)
```

**Expected behavior**
Some way of extracting the json field named `test-severity`

Without using parameters the `json parser extracts it fine as `test_severity` - but in my case i've got a very complex json structure I don't want to extract all labels.

**Environment:**
 - Infrastructure:  bare-metal
 - Deployment tool: docker swarm
 - Loki 2.6.1

**Comment by dannykopping** [comment]
@danpoltawski I think that `| json severity=`["test-severity"]` should work. Can you try that please?

**Comment by danpoltawski** [comment]
>  Can you try that please?

That does work, thank you - however this is a simplified example of the real log line I was trying to parse which actually contains a nested object which I can't work out a solution to this.

So a slightly more complex example log line:
```{"entry":"hello world","extra":{"test-severity":"info"}}```

Tried:
```
| json severity=`["extra.test-severity"]
```
Parses ok but doesn't retrieve the contents

**Comment by danpoltawski** [comment]
Is this a bug then?

```
parse error : stage '| json severity="extra.[\"test-severity\"]"' : cannot parse expression [extra.["test-severity"]]: syntax error: unexpected LSB, expecting FIELD 
``

**Comment by dannykopping** [comment]
Apologies, I think it's actually

```logql
| json severity=`extra["test-severity"]`
```

(no dot between the fields) as per [the docs](https://grafana.com/docs/loki/latest/logql/log_queries/#json)

**Comment by dannykopping** [comment]
No worries! @danpoltawski :slightly_smiling_face:
