### ISSUE TITLE
Ingestion rate limit exceeded

### ISSUE THREAD

**Issue by LHFA** [grafana/loki#6731]
[promtail]$ cat config.yaml | grep -A2 client 
client:
  url: http://loki.ucsk.cn/loki/api/v1/push
[promtail]$ curl -s http://loki.ucsk.cn/config | grep -i Ingestion                                   
  ingestion_rate_strategy: global
  ingestion_rate_mb: 100
  ingestion_burst_size_mb: 6
[promtail]$ curl -s http://loki.ucsk.cn/config | grep per_stream_rate_limit
  per_stream_rate_limit: 3145728
  per_stream_rate_limit_burst: 15728640
[promtail]$ tail -1 promtail.log                                           
level=warn ts=2022-07-21T03:40:28.271918237Z caller=client.go:349 component=client host=loki.ucsk.cn msg="error sending batch, will retry" status=429 error="server returned HTTP status 429 Too Many Requests (429): Ingestion rate limit exceeded for user fake (limit: 20971520 bytes/sec) while attempting to ingest '1' lines totaling '11717733' bytes, reduce log volume or contact your Loki administrator to see if the limit can be increased"

**Why does this error occur?**
-----------------------------
OS centos6.9 
promtail  version 2.5.0
loki version 2.5.0

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
