### ISSUE TITLE
Is there any good way Promtail can send the log files within container to Loki without awareness of end user

### ISSUE THREAD

**Issue by dontan001** [grafana/loki#6734]
Hi, I am new to Loki and I have one question:-

Currently in our k8s clusters,  some customers are still writing logs to local files within container, as a result these logs can not be collected to Loki easily. 
I know we could add promtail as sidecar to customer pods to send logs, however this would update the customer's pod spec, as a result the pods would be bebuilt, which may be not welcome for some user

Can anybody suggest other good way for this? thanks a lot

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.

**Comment by dontan001** [comment]
sure

**Comment by dontan001** [comment]
https://grafana.slack.com/archives/CEPJRLQNL/p1658400492569629
