### ISSUE TITLE
grafana/fluent-bit-plugin-loki is not available in arm64

### ISSUE THREAD

**Issue by bitkill** [grafana/loki#6738]
**Is your feature request related to a problem? Please describe.**
I cannot use fluentbit loki in Fargate `arm64` instances, since this docker image is only available for `amd64`

**Describe the solution you'd like**
Instead of using `version-arch` (example: `grafana/fluent-bit-plugin-loki:2.5.0-amd64`), ~use~ also the release version without arch and compile this image for both architectures

**Describe alternatives you've considered**
Right now this forces me to compile and deploy my ecs containers in `amd64`.
I know how to do this cross-compile in github-actions, however I'm not familiar with drone builds

**Additional context**
_none_

**Comment by bitkill** [comment]
The docker pipeline seems to be defined here: https://github.com/grafana/loki/blob/main/.drone/drone.yml#L856

**Comment by ebosveld** [comment]
Would be good if this was picked up
