### ISSUE TITLE
How to get all logs chunk by chunk over a range of date?

### ISSUE THREAD

**Issue by oguzhancelikarslan** [grafana/loki#6760]
I prepared a query for getting logs over a range of time and set the limit to 1000.
`http://localhost:60176/loki/api/v1/query_range?query={job="x"}&start=1658741427&end=1658741428&limit=1000`

but if i have 100000 data between this range then I cant get all of the logs because of the limit.

is there a way for getting all of the data chunk by chunk without specifying any limit?

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
