### ISSUE TITLE
Promtail ignoring first log line

### ISSUE THREAD

**Issue by DylanGuedes** [grafana/loki#6765]
**Describe the bug**
Promtail scraping is ignoring the first log line of a file.

**To Reproduce**
1. Create a new log file
2. Configure promtail to read from it
3. Note that Promtail will ignore the first log line of it and start from the second one. You can test that by running promtail with --dry-run

**Comment by slim-bean** [comment]
Is this possibly a bug with --dry-run? 

Just wondering if we can rule that out first.

**Comment by DylanGuedes** [comment]
hmmmm good question. Let me test without it, brb
