### ISSUE TITLE
loki -version should work without config file

### ISSUE THREAD

**Issue by Nudin** [grafana/loki#6770]
**Describe the bug**
`loki -version` currently requires a configuration file to be passed or found at default location. This is unexpected, since it does not use the config file and causes troubles when deployments first check version to then install proper configuration file

**To Reproduce**
1. Make sure no config file is at the default location.
2. `loki -version`

**Expected behavior**
Print version information.

**Screenshots, Promtail config, or terminal output**
```
# /usr/local/bin/loki  -version
failed parsing config: config.yaml,config/config.yaml does not exist, set config.file for custom config path
```

**Comment by gyanesh-m** [comment]
Hi @dannykopping ! I will pick this up.
