### ISSUE TITLE
Loki fails to start when min_chunk_age field is present in its configuration file.

### ISSUE THREAD

**Issue by tvataire** [grafana/loki#6778]
**Describe the bug**
Loki fails to start when its configuration file contains a [chunk_store_config](https://grafana.com/docs/loki/latest/configuration/#chunk_store_config) section with a "min_chunk_age" field.

**To Reproduce**
1. Add the following content to your loki config file : 
```
chunk_store_config: 
  min_chunk_age: 15m
```
2. Start loki
3. Loki fails to start with the following error : 
```
failed parsing config: /etc/loki/local-config.yaml: yaml: unmarshal errors:
  line 39: field min_chunk_age not found in type storage.ChunkStoreConfig
```

**Expected behavior**
Loki should start given that the field 'min_chunk_age' is documented in the most recent version of the documentation.

**Environment:**
```
$ loki -version
loki version 2.5.0 (branch: HEAD, revision: 2d9d0ee23)
  build user:       root@1943682c9a28
  build date:       2022-04-07T21:38:39Z
  go version:       go1.17.8
  platform:         linux/amd64
```

Podman container running [Loki 2.5.0](https://hub.docker.com/layers/loki/grafana/loki/2.5.0/images/sha256-c4f9965d93379a7a69b4d21b07e8544d5005375abeff3727ecd266e527bab9d3) image.

**Screenshots, Promtail config, or terminal output**
```
$ podman logs loki
failed parsing config: /etc/loki/local-config.yaml: yaml: unmarshal errors:
  line 39: field min_chunk_age not found in type storage.ChunkStoreConfig
```

**Related issue**
#3600

**Comment by dannykopping** [comment]
Thanks for reporting this @tvataire. This config option no longer exists.
We no longer set a floor for the chunk age, but we do set a ceiling with `max_chunk_age` in the `ingester` block.

I have removed the docs reference in [this PR](https://github.com/grafana/loki/pull/6781).
