### ISSUE TITLE
I configured timestamp stage，But it doesn't show in grafana

### ISSUE THREAD

**Issue by zrtsw** [grafana/loki#6783]
log.file:
2022-07-27 16:17:30.007|uat|10.10.10.10|SID=10|WARN |RID=|TID=|CID=||HsfThreadPoolWatchJob.java(61)
———————————————————————————————————————————————————
The pipeline I defined is shown below

        stages:
        - regex:
            expression: '^(?s)(?P<time>.*)\|(?P<service>.*)\|(?P<ip>.*)\|SID=(?P<sid>[\d]+)\|(?P<level>[A-Z]*) ?\|RID=\|(?P<content>.{1,1000})'
        - labels:
            time:
            service:
            ip:
            level:
            content:
        - timestamp:
            source: time
            format: '2020-12-10 16:10:38.941'
        - output:
            source: content
————————————————————————————————————————————————————
But only content is displayed, not time，Can someone help me answer it？

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
