### ISSUE TITLE
Fork mailgun/groupcache for the Loki groupcache implementation

### ISSUE THREAD

**Issue by 09jvilla** [grafana/loki#6788]
Fork mailgun/groupcache and remove singleflight since it's no longer needed as we'll be using groupcache as a write-through cache, and the locking hurts performance.

**Comment by MasslessParticle** [comment]
I'm going to call this one done. We tested removing single flight and didn't see a performance improvement. We learned that if the cache is experiencing enough load to have lock contention, removing singleflight just moves the problem to the lock guarding the cache.
