### ISSUE TITLE
Unable to start with error "../loki-local-config.yaml: no such file or directory"

### ISSUE THREAD

**Issue by coolbrg** [grafana/loki#68]
Hi,

I was following the [Run locally using Docker](https://github.com/grafana/loki#run-locally-using-docker) instructions and hit by this first issue of file not found.

```
$ docker run --name loki --network=loki -p 3100:3100 --volume "$PWD/docs:/etc/loki" grafana/loki:master -config.file=/etc/loki/loki-local-config.yaml
level=error ts=2018-12-12T09:54:40.816954563Z caller=main.go:28 msg="error loading config" filename=/etc/loki/loki-local-config.yaml err="Error reading config file: open /etc/loki/loki-local-config.yaml: no such file or directory"
```

### Observation
When I cd into locally cloned repo of `loki`, I am able to start.
I was under assumption that I can start from any place like $HOME.

**Comment by daniellee** [comment]
Loki and promtail need config files - so you have to map them in somewhere. I will update the docs to be more clear on this point - thanks for reporting this!

**Comment by karlek** [comment]
The `--volume` flag is relative to your $PWD (working directory) and can't therefore load the config file from an arbitrary folder. That's why you need to be in the `loki` folder, so that the config file in the `docs` folder will be in the correct place.

**Comment by coolbrg** [comment]
@daniellee Please verify https://github.com/grafana/loki/pull/69.

**Comment by tomwilkie** [comment]
I've removed the raw docker instructions and tested that this works with compose.  I also moved the config into the container.  This should be fixed.
