### ISSUE TITLE
Docs feedback: /configuration/_index.md

### ISSUE THREAD

**Issue by SSvilen** [grafana/loki#6816]
I believe that memberlist is missing as an option in the default loki.yaml values documentation.

So [here](https://grafana.com/docs/loki/latest/configuration/#supported-contents-and-default-values-of-lokiyaml) there should be a line for ```memberlist``` too.

**Comment by OniHil** [comment]
Hello,
Is this as simple as just removing the doc:"hidden" from this line? https://github.com/grafana/loki/blob/9920a27f06b9a808bcd0d7323a55041bc343a8bc/pkg/loki/loki.go#L96

**Comment by JStickler** [comment]
This has been fixed since release 2.8.  Closing.
