### ISSUE TITLE
Code(429) desc = Maximum active stream limit exceeded, reduce the number of active streams (reduce labels or reduce label values), or contact your Loki administrator to see if the limit can be increased" msg=gRPC

### ISSUE THREAD

**Issue by firstsko** [grafana/loki#6825]
already set the max_streams_per_user to 0 to disable the stream limt ,but still got the Code(429) Warn on the log output,anything else to config? It seems noo effect to the Warn message And the incoming message have numerious delay  to out loki system

may be got too much streams labels?
My Auto discover label is below this:
"_namespace_": "test_app",
  "_node_name_": "jp-tokyo.192.168.24.161",
  "_pod_name_": "toprsd1552830195352866816-67c5c6db94-qrshg",
  "app": "toprs",
  "filename": "/var/lib/container/app/toprs/test/logs/application/toprsd1552830195352866816-67c5c6db94-qrshg_sql.2022-08-01-0.log",
  "_container_name_": "sidecar-front",
  "groupid": "1",
  "deploymentID": "d1552830195352866816",
  "_k8s_app_": "test_app",
  "_pod_host_ip_": "192.168.24.161",
  "branch": "release_testapp-623",
  "mesh_mode": "client",
  "_app_": "toprs",
  "_pod_uid_": "dc6a0f6d-c287-4327-81db-d4c5695027a6",
  "_service_name_": "test/test_app",
  "env": "test",
  "group": "default-release_top-623-d1552830195352866816-1",
  "mesh_version": "release",
  "pod_template_hash": "67c5c6db94",
  "region": "default",
  "_pod_ip_": "192.168.51.85"

config the promtail on k8s daemon sets config map:

the  configuation is below this:
-----------------------------------
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://10.64.0.213/loki/api/v1/push

scrape_configs:
  - job_name: kubernetes-pods-app
    pipeline_stages:
      - docker: {}
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - action: drop
        regex: .+
        source_labels:
          - __meta_kubernetes_pod_label_name
      - source_labels:
          - __meta_kubernetes_pod_label_app
        target_label: _k8s_app_
      - source_labels:
          - __meta_kubernetes_pod_node_name
        target_label: _node_name_
      - action: replace
        replacement: $1
        separator: /
        source_labels:
          - __meta_kubernetes_namespace
          - _k8s_app_
        target_label: _service_name_
      - action: replace
        source_labels:
          - __meta_kubernetes_namespace
        target_label: _namespace_
      - action: replace
        source_labels:
          - __meta_kubernetes_namespace
        target_label: _app_
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_name
        target_label: _pod_name_
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_uid
        target_label: _pod_uid_
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_host_ip
        target_label: _pod_host_ip_
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_ip
        target_label: _pod_ip_
      - action: replace
        source_labels:
          - __hf_env
        target_label: _env_
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_container_name
        target_label: _container_name_
      - action: replace
        replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
          - __meta_kubernetes_pod_uid
          - __meta_kubernetes_pod_container_name
        target_label: __path__
      - action: replace
        replacement: /var/lib/container/app/*$1/**/*.log
        separator: /
        source_labels:
          - __meta_kubernetes_namespace
        target_label: __path__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)

loki.yaml configuation is below this:
-----------------------------------------------
limits_config:
  ingestion_rate_strategy: 'local'
  max_cache_freshness_per_query: '10m'
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 32
  ingestion_burst_size_mb: 64
  # parallelize queries in 15min intervals
  split_queries_by_interval: 15m
  max_streams_per_user: 0
  per_stream_rate_limit: 32m
  per_stream_rate_limit_burst: 64m
  max_entries_limit_per_query: 5000
  max_concurrent_tail_requests: 100
  max_query_parallelism: 64
  retention_period: 4320h

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
