### ISSUE TITLE
Convert chunk file to plain text for long term backup

### ISSUE THREAD

**Issue by aitchjoe** [grafana/loki#6826]
**Is your feature request related to a problem? Please describe.**

For long term cold backup, we dont want loki binary format files, just need plain text file which we can view easily.

**Describe the solution you'd like**

* An util which can convert chunk file to plain text and include meta data. We found that fingerprint, userID/tenant, from/through, metric/labels in each chunk file.
* A full solution which can scheduled to transfer old chunk files to another s3 backup bucket with plain text format.

**Describe alternatives you've considered**

I havent find similar util or solution.

**Comment by 09jvilla** [comment]
Thanks for your feature request! We don't have anything that would do this right now and no plans for this on our near term roadmap, but you may be able to adapt https://github.com/grafana/loki/tree/main/cmd/chunks-inspect for your purposes.

**Comment by aitchjoe** [comment]
Yes, chunks-inspect is the util which we want although it is not out of the box. Thanks!
