### ISSUE TITLE
": context deadline exceeded" in promtail

### ISSUE THREAD

**Issue by claclin** [grafana/loki#6832]
Working with promtail I am finding the following message error:

level=warn ts=2022-08-03T09:14:40.664465602Z caller=client.go:344 component=client host=xxxxx:3100 msg="error sending batch, will retry" status=-1 error="Post \"http://172.100.44.33:3100/loki/api/v1/push\": context deadline exceeded"

Any idea or help please??

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
