### ISSUE TITLE
Multi-tenant Queries does not work

### ISSUE THREAD

**Issue by mariomann** [grafana/loki#6848]
I enabled the multi tenancy mode and want to use the multi-tenant queries. But it's not working.
I can't see any errors in the logs.

I followed the docs: https://grafana.com/docs/loki/latest/operations/multi-tenancy/#multi-tenant-queries

Multi-tenancy on Loki side is enabled:

auth_enabled: true
querier:
  multi_tenant_queries_enabled: true

Loki-version (Helm-chart version): 2.12.2
Loki-version: 2.5.0

Can you help us with this or is there any problem?

**Comment by dannykopping** [comment]
@mariomann which version of Loki are you using, and what is the behaviour you are seeing?
Are you seeing any errors?

**Comment by mariomann** [comment]
I use Loki-version: 2.5.0

I try to execute the following query in Grafana UI: `{app="grafana", __tenant_id__="2|3"}`
The result is: `No volume data.`
My goal is to search in for logs in multiple tenants.

Any idea how to do it?

**Comment by dannykopping** [comment]
This feature is available [from v2.6.0](https://github.com/grafana/loki/releases/tag/v2.6.0).
Please upgrade and try again.

We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.

**Comment by mariomann** [comment]
I did the update (Loki version: 2.6.1) and it's unfortunately still not working.

**Comment by dannykopping** [comment]
Please engage us in #loki in [Grafana's Public Slack](https://slack.grafana.com/) and we'll assist
