### ISSUE TITLE
[Helm] Test both filesystem and minio-backed modes for new helm chart

### ISSUE THREAD

**Issue by trevorwhitney** [grafana/loki#6875]
https://github.com/grafana/loki/issues/6873 will bring the helm chart back into the Loki repo,  and will support both single binary and simple-scalable deployment architectures. Since filesystem is the most popular storage option for single binary, and object storage is required for simple-scalable, we should limit those storage options to their respective architectures and make sure they both work.

**Comment by jeschkies** [comment]
We've done manual testing.
