### ISSUE TITLE
[Helm] Publish helm chart to grafana/helm-charts

### ISSUE THREAD

**Issue by trevorwhitney** [grafana/loki#6877]
While we are moving the helm chart source back to this repo, we don't want to change where the chart is hosted. As a result we need to incorporate the CI/GitHub Actions from https://github.com/grafana/helm-charts into this repo to publish the new chart to the same place.

* Migrate CI from grafana/helm-charts for testing helm chart changes
* Integrate the github action in the grafana/helm-charts repo (this will publish it, so we will tackle this last)

**Comment by jeschkies** [comment]
@trevorwhitney could this be a Drone step instead? How can the Helm chart be published to another git repo?

**Comment by trevorwhitney** [comment]
@krajorama was able to find a way to publish cross repo when they did a similar migration for the Mimir chart, let's check in with him on Monday.
