### ISSUE TITLE
Ingester not leaving properly

### ISSUE THREAD

**Issue by Kuqd** [grafana/loki#688]
When doing a Kubernetes deployment/statefulset rollout, most of the time when an ingester leave the ring it will not be clean and the entry in the ring stays as `LEAVING`.

When the new pod want to join, it restart indefinitely before the entry already exist. Manually forgetting the entry in the ring fixes the issue using `/ring` web page.

We should look into why this is happening so we don't need to be staring at every rollout.

**Comment by mizeng** [comment]
I met it too and have to manually click "forget" in `/ring` page.

**Comment by Kuqd** [comment]
You can't really automate this because you want to only forget ingesters in trouble but Loki expose that page at `http://localhost:3100/ring`

**Comment by mizeng** [comment]
FYI, I tried latest Loki code, and can not reproduce this issue after trying several times of replacing pods.

**Comment by Kuqd** [comment]
Yes the memory issue was causing this apparently.

@rfratto feel free to close if you haven't seen anything while working on transfer.

**Comment by rfratto** [comment]
I haven't been able to reproduce this since the memory fix; closing.
