### ISSUE TITLE
This time.Ticker make memory leak.

### ISSUE THREAD

**Issue by aaftio** [grafana/loki#6906]
https://github.com/grafana/loki/blob/a02ce69a98e7ffe498078324df891affdfacaafe/clients/pkg/promtail/client/client.go#L247

This ticker should be `Stop()` after when the run() function exit. 
I found this bug when my project import this client package, in my case, I create a lot clients, and close them after use, but I found there is a lot `time.NewTicker` in the heap.

**Comment by godwhoa** [comment]
They do call `maxWaitCheck.Stop()` in a defer.
https://github.com/grafana/loki/blob/a02ce69a98e7ffe498078324df891affdfacaafe/clients/pkg/promtail/client/client.go#L249-L250

**Comment by aaftio** [comment]
> 

Oh sorry I have saw it. But I found my project import the version is `v1.6.1`. https://github.com/grafana/loki/blob/623858df0df92e7b704c1f734e7b781983a41551/pkg/promtail/client/client.go#L166

The version 1.6.1 has this problem, but I don't want update my dependency package to 2.x.x, any idea to fix it?

**Comment by godwhoa** [comment]
Ah! you are right, looks like it got fixed in v2.2.1. Forking might be your only option if upgrading to 2.x.x is not possible.

**Comment by aaftio** [comment]
> Ah! you are right, looks like it got fixed in v2.2.1. Forking might be your only option if upgrading to 2.x.x is not possible.

Ok, I found the v1.6.1 has release two years ago, maybe it's not possible to release a new v1.6.2.
Thank you.
