### ISSUE TITLE
Implement vector() function

### ISSUE THREAD

**Issue by tonychoe** [grafana/loki#6946]
**Is your feature request related to a problem? Please describe.**
I want to turn null (no data) to zero in query result in easy and reliable way.

There are other Loki users who want the same.
https://community.grafana.com/t/how-can-i-turn-no-data-to-zero-in-loki/40694

**Describe the solution you'd like**
Implement a function like [vector()](https://prometheus.io/docs/prometheus/latest/querying/functions/#vector) in PromQL.
> vector(s scalar) returns the scalar s as a vector with no labels.
Then users can join their query with vector() to turn NULL to zero, as below.
```
vector1
or
vector(0)
```

**Describe alternatives you've considered**
(1) Grafana's transform feature.
However, this feature only works for a dashboard panel with single Loki query. It doesn't work for multiple queries for a panel. 

(2) Tried to generate zeros reliably, but not perfect
```
sum(count_over_time({namespace="traefik"}|="foo"[1m])) 
or
sum(count_over_time({namespace="traefik"}[1m])) < bool 0
```
The 2nd vector can still return NULL if there is no log data matching labels sets. Not useful for log streams which has fluctuating log ingestion. 

(3) Tried absent_over_time() as 2nd vector instead, it didn't work for me.
- Bug report: [Using absent_over_time with logical operator returns "Unimplemented" error. #6943](https://github.com/grafana/loki/issues/6943)

(4) First, stored the log-metrics in Prometheus. Second, use vector() in Prometheus. 
This works of course. But I wish I can do the same using LokiQL which is upstream.

**Additional context**

**Comment by dannykopping** [comment]
@liguozhong I'm reopening this since your PR doesn't fully implement this yet, since you're kindly splitting up the work into multiple PRs.

**Comment by ringerc** [comment]
For others who found this and who want to create a vector with labels from a scalar, the only option at the moment appears to be `label_replace(vector(1), "newlabel", "newvalue", "", ""))`
