### ISSUE TITLE
handle long log when query

### ISSUE THREAD

**Issue by jinni05** [grafana/loki#6948]
Hi, 

I'm using HTTP API to query our Loki log and have a issue when the log was so long. It can be breakdown into two seperate log. That why it hard to trace now.

Do we have any solutions for this?

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
