### ISSUE TITLE
Fluentd plugin: StatefulSet Fluentd

### ISSUE THREAD

**Issue by hatrena** [grafana/loki#6959]
Hi, 

I am using Fluentd as a log aggregator with the Loki output plugin. Let's say I have a StatefulSet with 3 replicas of Fluentd + PVC. in StatefulSet, each pod has its own volume and PVC. 

on the other hand, as far as I know, Loki is sensitive to the timestamp of the incoming logs where it rejects the logs with a more recent timestamp ("entry out of order"). 

So the question is, how to make sure that logs that are buffered and processed in 3 different PVCs are sitting into Loki in order by time?

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
