### ISSUE TITLE
Loki Grafana is not showing all pod logs

### ISSUE THREAD

**Issue by claratang98** [grafana/loki#6969]
Hi,

My Grafana UI is not showing all pod logs from loki. Only about 30% of the pods has logs. I have verified from running CLI commands that the logs for the pods exist but loki is not flushing/tailing these logs.

I deployed loki using helm and these are my loki-values.yaml.

![image](https://user-images.githubusercontent.com/90296566/186619077-84e24417-9e4c-43f1-8f9c-7c4be2d59f61.png)

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
