### ISSUE TITLE
Data source connected, but no labels received. Verify that Loki and Promtail is configured properly.

### ISSUE THREAD

**Issue by lydAndtry** [grafana/loki#6981]
using logback and loki's api, why display "Data source connected, but no labels received. Verify that Loki and Promtail is configured properly." in granfana-server

**Comment by lydAndtry** [comment]
> using logback and loki's api, why display "Data source connected, but no labels received. Verify that Loki and Promtail is configured properly." in granfana-server

using postman send 'http://localhost:3100/loki/api/v1/labels' and only get {"status":"success"}

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
