### ISSUE TITLE
Labels in a namespace not shown immediately 

### ISSUE THREAD

**Issue by SSvilen** [grafana/loki#6984]
**Describe the bug**
I'm not sure if it's a bug or something else, but I observe the following behavior:
1) I have a namespace, which has 3 dashes in it's name
2) Querying the series in that namespace does not seems to return the correct amount.
Example:
There are pods, created by jobs, which have label called "db". So when I query the logs using the explore based on namespace and db label it works. 
What does not work is when I use that db label in dashboard variables and using the log browser in explore menu. 
If in "log browser" menu I select the db label, I see the value I need populated. If I choose the namespace first, I do not see it.
In the browser as well as in loki logs, I can see that the series query does not find that entry (method=query.Series match="{namespace=\"my-crazy-named-namespace\"}" total_entries=0). Couple of hours later though I can see the db label, when chosing the namespace label first.

I'm conviced that it has to do with the namespace name, since that behavior appears only there.

**Expected behavior**
The series label should be shown.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Comment by chaudum** [comment]
> I'm conviced that it has to do with the namespace name, since that behavior appears only there.

I doubt that is has to do with the namespace label value.

Could you post the complete configuration file as well as whether you use the `loki` or `loki-distributed` Helm chart?

**Comment by SSvilen** [comment]
@chaudum ,
I moved the whole thing to a new namespace, which has a name in the format 'something-something' and not 'something-something-something-something.' 
With the new namespace the problem does not appear. 
Feel free to close the issue.
