### ISSUE TITLE
Promtail: Log scraping stops when changing label value for existing target in file_sd_config

### ISSUE THREAD

**Issue by chodges15** [grafana/loki#7001]
When a file-based SD target is updated with a new label and the updated target shares the same filename, all scraping of this target stops until promtail is restarted.

**To Reproduce**
Promtail is actively tailing the file described in the file_sd_config below:
```
{
  "targets": [
    "localhost"
  ],
  "labels": {
    "__path__": "/var/log/0.log",
    "app": "web",
    "package_id": "1",
  }
}
```
Then, the package_id label is changed from `1` to `2` by rewriting the file_sd_config with the new label, like:
```
{
  "targets": [
    "localhost"
  ],
  "labels": {
    "__path__": "/var/log/0.log",
    "app": "web",
    "package_id": "2",
  }
}
```

All subsequent logs are dropped until promtail is restarted.

**Expected behavior**
It would be very helpful to be able to update file based SD labels and having scraping continue without a restart. I can accept a short amount of time where outdated labels are being applied to the newer logs.

**Environment:**
 - Infrastructure: bare-metal
 - Deployment tool: custom
 - Promtail version:
 ```
promtail, version main-d6f50ca (branch: main, revision: d6f50ca5e)
  build user:       root@4c4d203c7175
  build date:       2022-06-16T15:44:00Z
  go version:       go1.17.9
  platform:         linux/amd64
```

**Screenshots, Promtail config, or terminal output**
The race condition can be observed here where the target remove occurs within a millisecond later of the target being added. (Newer logs on top) 
```
2022-08-29 19:33:04	
level=info ts=2022-08-29T19:33:04.384548861Z caller=filetargetmanager.go:358 msg="Removing target" key="/var/log/0.log:{app=\"web\", package_id=\"1\", task_name=\"loki_compactor\"}"
2022-08-29 19:33:04	
level=info ts=2022-08-29T19:33:04.384460071Z caller=filetargetmanager.go:335 msg="Adding target" key="/var/log/0.log:{app=\"web\", package_id=\"2\", task_name=\"loki_compactor\"}"
```

**Comment by chodges15** [comment]
From a quick look, I do not believe this section of `filetargetmanager` accounts for the fact that remove runs _after_ add; and there might be overlap in filenames.
https://github.com/grafana/loki/blob/f17d3d768cb915b656af20a2ef7973efae335d51/clients/pkg/promtail/targets/file/filetargetmanager.go#L366-L373

**Comment by mortaelth** [comment]
With upgrading Promtail from 2.4.1 to 2.6.1, we have noticed that Promtail eats all the cpu on the kubernetes node (8 cpu node, normal state is cpu usage around 8%)

In the logs I can see the "failed to remove file event watcher" message, so suspicion on keeping the file handles opened.

Downgrade to 2.4.1 will return cpu back to normal
