### ISSUE TITLE
Connecting promtail agent on a VM to loki instance on kubernetes

### ISSUE THREAD

**Issue by richamishra006** [grafana/loki#7032]
Hi, 
I have installed promtail-agent on a VM on azure and I have my PLG-stack setup on AKS cluster,
how can i forward the logs of that VM to grafana-loki setup om k8s. Do i need to do something with clients url or we can do something using api key ?
Please help

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
