### ISSUE TITLE
Is there any way to disable escaping "<", ">" and "&"? - (\u00xx)

### ISSUE THREAD

**Issue by ochnios** [grafana/loki#7033]
I am using **FluentBit + Loki + Grafana** stack to follow logs. I need to log XML fragments and search by them sometimes. I can't find anything with `<`, `>` and `&` because these characters are replaced with `\u003c`, `\u003e` and `\u0026amp;`. Yes, I can search `\u003cID\u003e512\u003c/ID\u003e` instead of `<ID>512</ID>` but my Grafana dashboards are used by other people which don't accept that. I checked FluentBit output and responses from Loki in Grafana and everything indicates that characters are escaped inside Loki. I have tried to make changes in Loki code but I'm not familiar with it and I can't find the exact place where escaping occurs. I know that this solution wouldn't be perfect at all but I'm trying any way to make searching by  `<`, `>` and `&` possible. I also noticed that there is no problem when I'm passing plain text to Loki - then problematic characters aren't escaped. Normally I'm passing logs in JSON format so I think that the JSON parser may escape characters. Please, give me any advice on what can I do to solve my problem.

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
