### ISSUE TITLE
Dead link in promtail scraping docs

### ISSUE THREAD

**Issue by mtjon** [grafana/loki#7050]
**Describe the bug**
Dead link in docs:

https://github.com/grafana/loki/blob/e39ea21e3cacda92661d1d77770c7d1486ec4124/docs/sources/clients/promtail/scraping.md?plain=1#L372

Following this link in the live docs results in a 404.

**To Reproduce**
1. Go to: https://grafana.com/docs/loki/latest/clients/promtail/scraping/#kafka
2. Try to follow link "see the [configuration](https://grafana.com/docs/loki/latest/clients/configuration/#kafka) section for more information."
3. Error 404.

**Expected behavior**
Get referred to the appropriate configuration reference.

**Comment by JStickler** [comment]
Fixed
