### ISSUE TITLE
New Helm chart 3.0.0 registry not updated for agent-operator

### ISSUE THREAD

**Issue by guidoffm** [grafana/loki#7056]
Helm chart 3.0.0

Although I set global.image.registry to a certain value the docker image for

`loki-grafana-agent-operator`

does not used the globally set registry.

**Comment by trevorwhitney** [comment]
This appears to be a problem with the agent-operator chart, which does not appear to be respecting `global` values: https://github.com/grafana/helm-charts/blob/8f64c1284a7b89cb245d6b0fd488088378d59d18/charts/agent-operator/templates/operator-deployment.yaml#L35

Global values should be accessible from [all charts](https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#global-chart-values).

Please open an issue against the [helm charts](https://github.com/grafana/helm-charts) repo where the grafana agent-operator helm chart is hosted. Thanks!
