### ISSUE TITLE
Persistent "Context canceled" errors

### ISSUE THREAD

**Issue by JRascagneres** [grafana/loki#7061]
**Describe the bug**
Get a lot of 'error processing request' 'context canceled' in my logs. Not entirely sure what is actually causing the cancellation as this is the only error I see.

```
level=error ts=2022-09-06T00:49:40.303326972Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled"
```

**To Reproduce**
Currently running the https://github.com/bitnami/charts/tree/master/bitnami/grafana-loki helm chart.
This occurs constantly when querying data.

**Expected behavior**
I expect these errors not to be constantly printed.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Above linked helm chart

**Screenshots, Promtail config, or terminal output**
![image](https://user-images.githubusercontent.com/3264971/188525267-04d8e882-c9d4-42aa-a838-74e3659ea6fd.png)

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
