### ISSUE TITLE
Unable to standardize `__extra` labels collected from lambda-promtail \ CW Logs

### ISSUE THREAD

**Issue by NickAdolf** [grafana/loki#7062]
https://github.com/grafana/loki/blob/93a5a71e621f742b47fdb49d4f11ae6c0ead27b9/tools/lambda-promtail/lambda-promtail/main.go#L95

I'm working on implementing the entire Grafana stack & I am a bit puzzled on why `extra labels` aren't used as passed in? Instead `__extra_` is appended, this makes it difficult to fully align labels throughout an environment. Adding 'environment=production' labels to all other sources results in a standard, usable pattern, the promtail lambda appends the `extra` meaning additional queries are needed to cover `__extra_environment=production`

Am I missing something?

**Comment by cstyan** [comment]
IIRC the original is that promtail added labels, including the ones from aws like `__aws_cloudwatch_log_group` are the same as promtail (inspired by prometheus) service discovery metadata labels. This means that currently relabeling via promtail is required to achieve what you're trying to do.

**Comment by Rohlik** [comment]
You can omit that `__extra` prefix by `OMIT_EXTRA_LABELS_PREFIX=true` 😉.

**Comment by cstyan** [comment]
@NickAdolf I'm closing this for now, please comment or open another issue if relabelling or the above mentioned config option doesn't work for you.
