### ISSUE TITLE
Loki query filters do not return result as expected

### ISSUE THREAD

**Issue by hisarbalik** [grafana/loki#707]
Loki returns empty result with not equal queries (also with regexp one like !~ "foo") and with equal queries not only queried log lines. I am using loki v0.1.0 on a kubernetes environment. 

**To Reproduce**
1. Loki with version 0.1.0 deployed on a kubernetes environment
2. Container/Pod log several lines like some lines with "foo" and some with "bar"
3. Promtail can collect logs from container/pod and push to the loki
4. Query: `{container_name="my-function"}` return all logs (all log lines with "foo" and "bar") from container/pod but `{container_name="my-function"} !="foo"` return empty result. I fI send queries like `{container_name="my-function"} |="foo"` return result with lines containing "foo" and "bar"

**Expected behavior**
Query: `{containe_name="my-function"} !="foo"` should return only log lines with containing "bar" and other but not lines containing "foo"

**Environment:**
 - Infrastructure: Kubernetes tested on minikube v0.33.1, GKE version 1.12.7-gke.x, and AKS version 1.14.x
 - Deployment tool: helm

**Comment by slim-bean** [comment]
How are you querying? If using Grafana make sure your version is 6.3, the LogQl query language was added in 6.3

6.3 is not released yet though I believe will be soon, for now you can use the [nightly builds](https://grafana.com/grafana/download/6.3.0-05547e12pre)

**Comment by hisarbalik** [comment]
> How are you querying? If using Grafana make sure your version is 6.3, the LogQl query language was added in 6.3
> 
> 6.3 is not released yet though I believe will be soon, for now you can use the [nightly builds](https://grafana.com/grafana/download/6.3.0-05547e12pre)

I am using grafana version 6.0.1 as well as loki API, both has same behaviour

**Comment by Kuqd** [comment]
I've spent some time in the query path I'll take a look.

**Comment by DanielDzr** [comment]
same here.

**Comment by Kuqd** [comment]
Alright I can reproduce it.

**Comment by DanielDzr** [comment]
![image](https://user-images.githubusercontent.com/51435828/60787040-1ff22600-a18b-11e9-88c8-eb846dd8aee7.png)
![image](https://user-images.githubusercontent.com/51435828/60787140-66478500-a18b-11e9-9b74-d9ac9b9e34a2.png)

**Comment by hisarbalik** [comment]
> Yep I cannot reproduce on master.
> 
> Have you tried to use the latest grafana ? `docker pull grafana/grafana-dev:master-e2cf7c9698ed319c05f911ad0ad5bf75f2fbb56`
> 
> It support LogQL properly but not the other version.

Sure I can update grafana but we using also direct API from loki (/api/prom/query endpoint).
My next question is, the filtering feature supported only via grafana?

**Comment by Kuqd** [comment]
you should be fine via the api what's the command you're using ?

**Comment by Kuqd** [comment]
@DanielDzr your grafana version can't handle that query you need 6.3

**Comment by DanielDzr** [comment]
@Kuqd  thanks.

**Comment by hisarbalik** [comment]
Here is a query from my local deployment:
`https://loki.kyma.lcal/api/prom/query?query={container_name="webhook"}&start=1562741712326000000&end=1562742492326000000&direction=backward&limit=1000&regexp=!=nats`

**Comment by pracucci** [comment]
> https://loki.kyma.local/api/prom/query?direction=BACKWARD&limit=1000&regexp=!%3Dnats&query=%7Bcontainer_name%3D%22webhook%22%7D&start=1562721456588000000&end=1562743056588000000

@hisarbalik The correct way to query it should be this one:
`https://loki.kyma.local/api/prom/query?direction=BACKWARD&limit=1000&regexp=&query=%7Bcontainer_name%3D%22webhook%22%7D%21%3D%22nats%22&start=1562721456588000000&end=1562743056588000000`

- `query`: `{container_name="webhook"}!="nats"`
- `regex`: empty

**Comment by Kuqd** [comment]
Yes that's correct, let's close it. You can re-open if that still doesn't work.

**Comment by hisarbalik** [comment]
> > https://loki.kyma.local/api/prom/query?direction=BACKWARD&limit=1000&regexp=!%3Dnats&query=%7Bcontainer_name%3D%22webhook%22%7D&start=1562721456588000000&end=1562743056588000000
> 
> @hisarbalik The correct way to query it should be this one:
> `https://loki.kyma.local/api/prom/query?direction=BACKWARD&limit=1000&regexp=&query=%7Bcontainer_name%3D%22webhook%22%7D%21%3D%22nats%22&start=1562721456588000000&end=1562743056588000000`
> 
> * `query`: `{container_name="webhook"}!="nats"`
> * `regex`: empty

Thanks for the example but this query resulting to HTTP-400 syntax error

**Comment by pracucci** [comment]
@hisarbalik A couple of questions, please:
1. Make sure you're running the `master` version of Loki
2. If still occurs with the `master` version, can you share the entire API response, please?

**Comment by hisarbalik** [comment]
> @hisarbalik A couple of questions, please:
> 
> 1. Make sure you're running the `master` version of Loki
> 2. If still occurs with the `master` version, can you share the entire API response, please?

I am using release version v0.1.0, is this a bug in release version or release version does not contains feature?

**Comment by Kuqd** [comment]
Using the API you should be fine on 0.1 however you may need some space `{container_name="webhook"} != "nats"`
