### ISSUE TITLE
Azure Blob Storage configuration does not honor azure.endpoint_suffix configuration

### ISSUE THREAD

**Issue by Pete-PlaytimeSolutions** [grafana/loki#7082]
**Describe the bug**
Configuring loki to use an azure blob storage in a region other than Azure global(blob.core.windows.net) is not working.
The Azure configuration should support other regions, such as 
- Azure China(blob.core.chinacloudapi.cn),
- Azure German(blob.core.cloudapi.de), 
- Azure US Government(blob.core.usgovcloudapi.net).
- local Azure Blob Storage emulator

**To Reproduce**
1. configured Loki using an Azure Blob Storage account with azure.endpoint_suffix=blob.core.usgovcloudapi.net
2. Tried staring Loki
3. Loki crashes, with error failed to authenticate request to "https://XXXX.blob.core.windows.net", as it is trying to hit a service in the wrong region...

**Expected behavior**
When Loki is configured using the endpoint_suffix option
`storage_config:`
`    azure:`
`          endpoint_suffix: blob.core.usgovcloudapi.net`

Then all Blob Storage API calls should use this configuration.

see:  [Loki Storage Documentation](https://grafana.com/docs/loki/latest/configuration/#azure_storage_config) 
`azure endpoint_suffix`

**Environment:**
 - any

**Comment by Pete-PlaytimeSolutions** [comment]
Please ignore, there just seems to be in consistencies in naming across the products account_name != account-name
The only suggestion would be that no config.yaml validation seems to occur, like it does in the other products..

**Comment by dannykopping** [comment]
I believe this was addressed in https://github.com/grafana/loki/pull/6842, and will be available in the next Loki release.

If you need to use this functionality right now, you may use one of the images we publish from the tip of `main`.
https://hub.docker.com/r/grafana/loki/tags
