### ISSUE TITLE
Change metric log_messages_total into something more clear

### ISSUE THREAD

**Issue by wiardvanrij** [grafana/loki#7088]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when non clear metric names are used. :D 
But in all seriousness, having: https://github.com/grafana/loki/blob/main/pkg/util/log/log.go#L56 the metric `log_messages_total` with a helper: `Total number of log messages.` in a logging application is just next level confusion. 

**Describe the solution you'd like**
Rename the metric to something much more clear. Maybe:
`internal_log_messages_total`
`self_logged_messages_total` 

If anything, let's be way more explicit in the helper. "I.e. "These are NOT logs Loki processed but logs Loki created themselves as output while running" or something like that. 

**Describe alternatives you've considered**
Just remove this metric. It's very confusing and with other components in a stack (be it fluentbit/promtail) and especially Loki, we can already count/analyse log outputs from applications. I'm not even sure why an application needs to create metrics for it.

**Additional context**
None.

**Comment by dannykopping** [comment]
Whoever picks this up: please include a _new_ metric with the better name and deprecate the old one (maybe even add **deprecated** in the description. We'll remove it entirely with v3.0.

**Comment by wiardvanrij** [comment]
> Whoever picks this up: please include a _new_ metric with the better name and deprecate the old one (maybe even add **deprecated** in the description. We'll remove it entirely with v3.0.

bit offtopic, but is there an ETA and roadmap for 3.0?

**Comment by dannykopping** [comment]
Nothing official yet, watch this space
