### ISSUE TITLE
"failed parsing config" when "loki -version" and missing "config.yaml,config/config.yaml"

### ISSUE THREAD

**Issue by nledez** [grafana/loki#7099]
**Describe the bug**
`failed parsing config` when launch `loki -version`.

**To Reproduce**
1. Remove files `config.yaml` and `config/config.yaml`
2. Launch `loki -version`
3. Have `failed parsing config: config.yaml,config/config.yaml does not exist, set config.file for custom config path`

**Expected behavior**
Have this output:
```
loki, version 2.6.1 (branch: HEAD, revision: 6bd05c9a4)
  build user:       root@af90ed01061f
  build date:       2022-07-18T08:41:09Z
  go version:       go1.17.6
  platform:         linux/amd64
```

**Environment:**
 - Infrastructure: bare-metal, laptop

**Terminal output**
```
# loki -version
failed parsing config: config.yaml,config/config.yaml does not exist, set config.file for custom config path

# loki -version --config.file /dev/null
loki, version 2.6.1 (branch: HEAD, revision: 6bd05c9a4)
  build user:       root@af90ed01061f
  build date:       2022-07-18T08:41:09Z
  go version:       go1.17.6
  platform:         linux/amd64
```

**Comment by dannykopping** [comment]
Thank you for your bug report.

This was addressed in https://github.com/grafana/loki/pull/6802 and will be made available in the next release.
