### ISSUE TITLE
[Helm 3.0.1] loki.singleBinarySelectorLabels in values.yaml

### ISSUE THREAD

**Issue by blezoray** [grafana/loki#7105]
Hello,

in the new helm chart, in the values.yaml, line 733, I think there is a mistake :
https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml#L733
It should be 
```yaml
              {{- include "loki.singleBinarySelectorLabels" . | nindent 10 }}
```
Could you check that ?

Rgds.

**Comment by trevorwhitney** [comment]
yup, sure is! thanks for catching that, PR is up.
