### ISSUE TITLE
Docs feedback: /configuration/_index.md

### ISSUE THREAD

**Issue by manotoshroy** [grafana/loki#7117]
The compactor block has **deletion_mode** description twice

1st occurrence:
# Which deletion mode to use. Supported values are: disabled,
# whole-stream-deletion, filter-only, and filter-and-delete.
# CLI flag: -boltdb.shipper.compactor.deletion-mode
[deletion_mode: <string> | default = "whole-stream-deletion"]

2nd occurrence:
# Deletion mode.
# Can be one of "disabled", "filter-only", or "filter-and-delete".
# When set to "filter-only" or "filter-and-delete", and if
# retention_enabled is true, then the log entry deletion API endpoints are available.
# CLI flag: -boltdb.shipper.compactor.deletion-mode
[deletion_mode: <string> | default = "disabled"]

Please remove the first occurrence.

**Comment by 09jvilla** [comment]
closing this now that pr is merged
