### ISSUE TITLE
rpc error while doing queries

### ISSUE THREAD

**Issue by rizwankh** [grafana/loki#7138]
`logcli-darwin-amd64 --org-id=3 query '{filename="/var/log/audit.log"}' --since=2h --stats`

Results in:

```http://192.168.247.101:3100/loki/api/v1/query_range?direction=BACKWARD&end=1663051587986047000&limit=30&query=%7Bfilename%3D%22%2Fvar%2Flog%2Faudit.log%22%7D&start=1663044387986047000
Error response from server: rpc error: code = Unknown desc = invalid version 3
```

I get this error pretty randomly and have not been able to pin-point what is the issue. Running Loki in distributed mode. 3 nodes with `target: all` and 1 node with `target: query-frontend`.

Loki version: `2.0`

**Comment by dannykopping** [comment]
Are you running different versions of the LogCLI and Loki?

**Comment by rizwankh** [comment]
I tried with logcli version 2.0.0 and still it behaves the same.

``` 
./logcli-2.0.0 --org-id=3 query '{filename="/var/log/audit.log"}' --since=2h --stats
http://192.168.247.104:3100/loki/api/v1/query_range?direction=BACKWARD&end=1663232635298553000&limit=30&query=%7Bfilename%3D%22%2Fvar%2Flog%2Faudit.log%22%7D&start=1663225435298553000
Query failed: Error response from server: Multiple errors: [rpc error: code = Unknown desc = invalid version 3 invalid version 3]
 (<nil>)
```

**Comment by rizwankh** [comment]
@dannykopping Do you need any further information? 

Thanks in advance.

**Comment by rizwankh** [comment]
@dannykopping I would really appreciate a response here or you can tell me that I need to buy a support contract to get this sorted. At least give some feedback. Thanks

**Comment by dannykopping** [comment]
@rizwankh apologies for the delayed response.
I would recommend upgrading to the latest versions of Loki and LogCLI. v2.0.0 is very old, and the issue has likely been addressed in the meantime.

Please reopen the issue if you encounter the same issue with the latest versions.

**Comment by rizwankh** [comment]
Thanks @dannykopping. I updated last night to v2.6.0 and the error is gone. I guess I needed that push :)

**Comment by dannykopping** [comment]
Happy to hear it!
