### ISSUE TITLE
JSON properties in log line is not sorted

### ISSUE THREAD

**Issue by jjayabal23** [grafana/loki#7139]
**Describe the bug**
I am reading a json log line using promtail and pushing it to loki. While querying the logs via grafana, I notice that the json properties order is completely different for each log line. Due to this it is very hard to compare two log lines after querying.

**To Reproduce**
1. Write a log line to a file with the format below,
    `{"instance_type":"test","level":"info","message":{"data":{"externalContextId":"id","flowName":"flow_name","message":"Log Message","messageId":"950296e6855b93d3","pod_name":"pod-name-d6d4db99f-977g5","properties":[{"key":"prop1","value":"1"},{"key":"prop2","value":"2"}]}},"timestamp":1662972062128}`
3. Read the log line using promtail and push it to loki. Add few more log lines with a different timestamp and push the logs to loki.
4. Query the logs in grafana query editor or use logcli to fetch the logs.
5. The response of each returned log line contains the json properties in different order. It is not maintaining the order in which the log line is pushed to loki.

**Expected behavior**
The Json log message returned by loki should be same as the one that is available in the log file pushed to loki

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Helm (loki-simple-scalable v1.8.0, promtail v6.2.1)

**Screenshots, Promtail config, or terminal output**
The log lines shown are the same json object but the output is in different order.
![image](https://user-images.githubusercontent.com/85246587/189841732-97d8276d-be89-46ef-a2ac-0514963d72c1.png)

**Comment by dannykopping** [comment]
Hi @jjayabal23 - thanks for this.

The reason is that Go does not support ordered maps, so this is not strictly a bug but more of a feature request for adding a `sort_keys` functions, I'd say.

**Comment by niranjanative** [comment]
I think this issue has already been solved in latest version, as I am not able to reproduce this. Please do confirm and close the issue.

**Comment by jjayabal23** [comment]
Thanks. I don't see a helm chart that installs the latest version of loki. I will try to override the tag and check if that works.

**Comment by akhilanarayanan** [comment]
I tested this with loki v2.8.2 and the issue isn't there!

**Comment by akhilanarayanan** [comment]
I tested this with loki v2.8.2 and the issue doesn't seem to be there

**Comment by jjayabal23** [comment]
I could confirm that it works with loki v2.8.2

**Comment by ylihemmo** [comment]
@jjayabal23 or anyone else, could you verify if this is working for you correctly in version 3?
I seem to be having this issue even with latest 3.1.1.
