### ISSUE TITLE
lambda-promtail:  Getting loki credentials with Secret Manager

### ISSUE THREAD

**Issue by lfelipevaca** [grafana/loki#7169]
**Is your feature request related to a problem? Please describe.**
currently Loki authentication credentials are set in the Lambda environment variables, in order to have a better control of this sensitive data it would be advisable to obtain this data from AWS secret manager.

**Describe the solution you'd like**
I wrote a patch to lambda-promtail which does that: https://github.com/grafana/loki/pull/7168/

**Additional context**
I tested the solution by running a custom build of lambda-promtail and it is working, additionally it is guaranteed that no break changes are introduced.

**Comment by cstyan** [comment]
related PR was closed due to inactivity, feel free to comment if you want to reopen

**Comment by SSE69** [comment]
Hello, I'd like to reopen this issue.
