### ISSUE TITLE
Loki: Bad Gateway. 502

### ISSUE THREAD

**Issue by prasenforu** [grafana/loki#717]
I am running Loki & Grafana as a standalone container in same host, containers are running fine with NO error.

when I adding Loki data source with local IP (host IP) I am getting following error.

![image](https://user-images.githubusercontent.com/19322497/60663782-d00b1a80-9e7d-11e9-8898-f094612f30ea.png)

But when I adding Loki data source with PUBLIC IP,  I got connection. 

![image](https://user-images.githubusercontent.com/19322497/60663738-afdb5b80-9e7d-11e9-8fd4-ea81659dc9d0.png)
 
For security reason its not meaning that I have to connect with Public IP.

Please advice.

**Comment by Kuqd** [comment]
Are you runing 2 container ? one for Grafana and one for Loki ?

If so you can't use localhost in Grafana as they don't share the same network stack.

If you need to link containers.

**Comment by prasenforu** [comment]
Yes, I am running 2 container.  One for Grafana and another one for Loki .

But when I am adding data source not using  ```localhost``` , using host IP.

**Comment by Kuqd** [comment]
If you're on macos you can try this dns instead: `http://docker.for.mac.localhost:3100/`

**Comment by prasenforu** [comment]
I am using Linux but want use using as a standard host ip

**Comment by Kuqd** [comment]
Did you tried `--network=host`?

**Comment by prasenforu** [comment]
@Kuqd

Sorry delay in reply.

I tried with ```--network=host``` but no luck.

**Comment by hsafe** [comment]
Sorry it is too late but if you used the docker-compose which you should, I guess it is enough to give the name of the loki instead of localhost as the dockers share the same network and they can see each other....
