### ISSUE TITLE
Concurrent map read and map write in promtail pod

### ISSUE THREAD

**Issue by athrunecho** [grafana/loki#7180]
**Describe the bug**
Some of my promtail pods in CrashLoopBackOff and restart over 1000 times.
After I check the pod logs, I found it start with a fatal error log:
fatal error: concurrent map read and map write

**To Reproduce**
The issue occurs suddenly and after sometime whe nI check the pod goes fine.

**Expected behavior**
promtail should normally work. 

**Environment:**
Kubenetes: v1.22.11
promtail: v2.1.0

**Screenshots, Promtail config, or terminal output**
![Screen Shot 2022-09-14 at 14 04 59](https://user-images.githubusercontent.com/25002032/190552464-70323083-ea90-4f71-b70f-4ceed8b1f3d3.png)

**Comment by liguozhong** [comment]
Please provide a more comprehensive panic log.

**Comment by athrunecho** [comment]
![1](https://user-images.githubusercontent.com/25002032/191156961-d403a47a-c1d3-4358-a928-058e14e1be92.png)

![2](https://user-images.githubusercontent.com/25002032/191157631-5ee173cc-c3e1-4ab3-9ba1-044a8050c4e2.png)

![3](https://user-images.githubusercontent.com/25002032/191157646-74e25af0-63b6-4c8d-b345-37a87c9ee362.png)

**Comment by liguozhong** [comment]
Thank you for the detailed log provided. According to the log, I found that there is a code that is relatively dangerous. A lock is added to protect thread safety, but it will lead to performance degradation. I need to wait for the loki team review.

**Comment by liguozhong** [comment]
promtail v2.1.0 code.

```go
// Process implements Stage
func (m *matcherStage) Process(lbs model.LabelSet, extracted map[string]interface{}, t *time.Time, entry *string) {
	for _, filter := range m.matchers {
		if !filter.Matches(string(lbs[model.LabelName(filter.Name)])) {
			return
		}
	}

	sp := m.pipeline.ForStream(labels.FromMap(util.ModelLabelSetToMap(lbs)))
	if newLine, newLabels, ok := sp.ProcessString(*entry); ok {
		switch m.action {
		case MatchActionDrop:
			// Adds the drop label to not be sent by the api.EntryHandler
			lbs[dropLabel] = model.LabelValue(m.dropReason)
		case MatchActionKeep:
			*entry = newLine
			for k := range lbs {
				delete(lbs, k)
			}
			for _, l := range newLabels.Labels() {
				lbs[model.LabelName(l.Name)] = model.LabelValue(l.Value)
			}
			m.stage.Process(lbs, extracted, t, entry)
		}
	}
}

```

**Comment by liguozhong** [comment]
https://github.com/grafana/loki/pull/2996
After this PR introduces channel, it seems that it should be able to solve the problem of concurrent access. 

The previous implementation without channel seems to be concurrency insecure. Because each NewFileTarget() of Promtail 2.1.0 will have a go routine to access the Process interface of pipleline concurrently.

You can use the latest promtail(2.7.0) or a version after this PR. Pipelines that introduce channels are thread-safe.

If my investigation is correct. I believe that the new version of promtail will no longer have this map concurrency problem.

**Comment by cstyan** [comment]
closing since @liguozhong's PR should have fixed this
