### ISSUE TITLE
Your logs might have incorrectly escaped content

### ISSUE THREAD

**Issue by leozz705** [grafana/loki#7192]
如图，如何修改配置：
![image](https://user-images.githubusercontent.com/78150430/190837890-6edfa397-a89a-4d91-8077-d9bc24e35072.png)
如下图，控制台输出的日志并没有那些字符
![image](https://user-images.githubusercontent.com/78150430/190837974-4ba040b0-2dfd-4604-940b-7f39fee904c5.png)

**Comment by liguozhong** [comment]
`      const hasUnescapedContent = !!message.match(/\\n|\\t|\\r/);
`
code in github.com/grafana/grafana/public/app/core/logs_model.ts

There should be \\t special symbols in your log.

![image](https://user-images.githubusercontent.com/9583245/190973190-8398b656-7e3a-4cdb-987e-490c2325cbd8.png)

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.

**Comment by sourcehawk** [comment]
Is there a bug in loki or should newlines not be formatted at all?
