### ISSUE TITLE
Loki migration between k8s clusters

### ISSUE THREAD

**Issue by nutslove** [grafana/loki#7193]
Hi Loki team.
I’m using loki-distributed on AWS EKS, trying to test for migration between k8s clusters.
I thought that it could be done like what I attached.
But, even though throw /flush API to ingesters in old Loki, a query to new Loki doesn’t get logs that exist in old Loki.
Did I miss something?
Is there the best way to migrate between k8s clusters?
Thanks.
![image](https://user-images.githubusercontent.com/43600385/190849846-3d6f6230-1350-4a4f-8879-e248db451a3c.png)
![image](https://user-images.githubusercontent.com/43600385/190849854-c6437b84-57d4-488e-9ac6-c51dd8df6a6b.png)
![image](https://user-images.githubusercontent.com/43600385/190849873-5e24e289-f0e8-4932-baf1-4e10af3ced8c.png)
![image](https://user-images.githubusercontent.com/43600385/190849878-b6426688-8829-43a6-b472-c4065b5f25e6.png)
![image](https://user-images.githubusercontent.com/43600385/190849881-1ddd6321-3b33-4003-b3e3-4e73b0fa7208.png)
![image](https://user-images.githubusercontent.com/43600385/190849889-aba3c8af-fc2a-4668-8617-5a4c0f0b9b04.png)
![image](https://user-images.githubusercontent.com/43600385/190849893-78710d4a-983e-4511-b4f3-597a96a0cf1c.png)

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
