### ISSUE TITLE
Prettify JSON is rounding integers

### ISSUE THREAD

**Issue by andrejshapal** [grafana/loki#7198]
**Describe the bug**
When Prettify JSON is used to show the logs in explorer and JSON contains integer as value (not sure about length) the value is getting rounded.

**To Reproduce**
1. Started Loki 2.6.1
2. Started Promtail 2.6.1

**Expected behavior**
After prettifying information is shows without changes.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

The value before prettifying:
![image](https://user-images.githubusercontent.com/96792836/191266238-2e6a31bd-e436-40b6-9a72-c764cdce6d19.png)

After prettifying value changes:
![image](https://user-images.githubusercontent.com/96792836/191266884-d7322a7f-6f09-43cc-8aab-501b29dfd8aa.png)

I our case we use hashed ID which is integer and we were not able to find any data before understood prettify is changing ID.

**Comment by chaudum** [comment]
Hi @andrejshapal 
The prettifying of the JSON is not done by Loki but by Grafana itself, so it is likely a problem there.

A quick check with the JS console in the browser yielded the same rounding error:

![2022-09-24_09-44-08](https://user-images.githubusercontent.com/281260/192086725-39e146e1-27cd-42e7-95a3-65839b295cd0.png)
