### ISSUE TITLE
fluentd-grafana-loki

### ISSUE THREAD

**Issue by sayi65** [grafana/loki#722]
**Describe the bug**

fluentd-grafa-loki is used in td-agent 3。
The following error occurs when requesting loki from fluentd
failed to POST http://<IP>:30500/api/prom/push (400 Bad Request entry o
ut of order for stream: {env="test"}

**Environment:**
 Ubuntu14

**Comment by Kuqd** [comment]
Hello @sayi65 ,

Could this be related to this : https://github.com/grafana/loki/tree/master/fluentd/fluent-plugin-grafana-loki#multi-worker-usage ?

**Comment by sayi65** [comment]
@Kuqd 
I was confirm That. and I made the following settings
```
<filter tail>
   @type record_modifier
   char_encoding utf-8
   char_encoding utf-8:euc-jp
   <record>
      fluentd_worker "fluentd"
   </record>
</filter>
<match tail>
   @type loki
   endpoint_url http://xxx.xxx.xxx.xxx:30500
   label_keys "fluentd_workier"
   labels {"env":"test"}
   tenant fake
</match>
```

but I get parameter 'label_keys' in `<match></match>` is not used.
Is my setting wrong?

**Comment by Kuqd** [comment]
@laitalaj any idea ? I'm not a fluentd expert myself.

**Comment by laitalaj** [comment]
@sayi65 you have a typo there; you've written `label_keys "fluentd_workier"` when you meant `label_keys "fluentd_worker"`.

Also, to avoid those out-of-order errors, you'll need to store the worker ID instead of a static string in that label - the value set for the `fluentd_worker` label in the record modifier should be  `"#{worker_id}"` (or at least include the worker id)

**Comment by sayi65** [comment]
@laitalaj 
sorry,  about typo .  i found The problem and fixed.
after fix that same ploblem.

from td-agent.log i found  my worker iD is 0.
`starting fluentd worker pid=14783 ppid=14778 worker=0`
so need I set in label_keys="worker=0"?

it is my setting as below.

```
<source>
  @type tail
  path /var/log/test1/**/eventlog_%Y%m%d*.txt
  pos_file /tmp/event.log.pos
  tag tail.event
  path_key log_file
  format /^(?<time>[^ ]*\S) (?<code>[^ ]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$/
</source>

<source>
  @type tail
  path /var/log/test1/**/errorlog_%Y%m%d*.txt
  pos_file /tmp/error.log.pos
  tag tail.error
  path_key log_file
  format /^(?<time>[^ ]*\S) (?<code>[^ ]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$/
</source>

<filter **>
   type record_transformer
   enable_ruby
   <record>
      hostname "${hostname}"
   </record>
</filter>
<filter **>
   @type record_modifier
   char_encoding utf-8
   char_encoding utf-8:euc-jp
  <record>
      fluentd_worker "worker=0"
   </record>
</filter>
<match **>
   @type loki
   endpoint_url http://xxx.xxx.xxx.xxx:30500
   label_keys "fluentd_worker"
   labels {"env":"test1"}
   tenant fake
</match>
```

**Comment by laitalaj** [comment]
@sayi65 you're supposed to put a literal `#{worker_id}` there; it will get replaced with the actual worker ID by fluentd [as specified here](https://docs.fluentd.org/deployment/multi-process-workers#output-plugin).

However, it doesn't seem like you are running a multi-worker setup. Are you forwarding to one loki instance from multiple fluentd instances? In that case, you'll need to have the hostname (or some other fluentd-instance-specific info) in the labels. Also, are you certain that the timestamps in the actual logs are in correct order?

**Comment by sayi65** [comment]
@laitalaj 
Thank you for your comment
> However, it doesn't seem like you are running a multi-worker setup. Are you forwarding to one loki instance from multiple fluentd instances?

I'm transferring logs from multiple fluentd instances to one loki instance.

>  In that case, you'll need to have the hostname (or some other fluentd-instance-specific info) in the labels. Also, are you certain that the timestamps in the actual logs are in correct order?

The label is set to hostname.
but label key is same. The label is [env]
timestamps is correct.    
400 error does not always occur

**Comment by laitalaj** [comment]
You currently seem to have hostname set in the log record, but not in the labels.  Try setting `label_keys "hostname"` in the `<match **>` - that should do the trick, as long as the fluentd instances are running on different hosts.

**Comment by sayi65** [comment]
@laitalaj 

Thank you for your support .
it works well.
