### ISSUE TITLE
[Helm 3.1.0] ruler config for single-binary

### ISSUE THREAD

**Issue by blezoray** [grafana/loki#7226]
Hello,

When I use the helm chart 3.1.0 with single-binary deployment (storage.type: filesystem), and no rulerConfig, Loki doesn't start properly because the loki configmap contains this:
```yaml
ruler:
  storage: null
```
I think this is link to https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml#L134

Could you take into account this case ?

**Comment by jeschkies** [comment]
Is this related to #7267?
