### ISSUE TITLE
problems with ingested

### ISSUE THREAD

**Issue by joaqquin89** [grafana/loki#7234]
Hi guys

I write this message because I need some answers about Loki And the piece called ingester .. I don't know why appear this message 
![image](https://user-images.githubusercontent.com/16735054/191993902-7a1cee17-78d4-4afc-978a-1f8acf1971fa.png)

in the deep what is the problem here ?

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
