### ISSUE TITLE
with Cassandra storage problem 

### ISSUE THREAD

**Issue by WANGTRUI** [grafana/loki#7238]
我的表管理器设置如下：
table_manager:
    chunk_tables_provisioning:
        inactive_read_throughput: 0
        inactive_write_throughput: 0
        provisioned_read_throughput: 0
        provisioned_write_throughput: 0
    index_tables_provisioning:
        inactive_read_throughput: 0
        inactive_write_throughput: 0
        provisioned_read_throughput: 0
        provisioned_write_throughput: 0
    retention_deletes_enabled: true
    retention_period: 7200h
但是却报以下异常：
![image](https://user-images.githubusercontent.com/61115130/192129240-7fcdabb5-8a41-4ac3-8922-aad71a48ced0.png)
有没有大师解答一下？

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
