### ISSUE TITLE
Context deadline exceeded during query after 5 minutes

### ISSUE THREAD

**Issue by VtG242** [grafana/loki#7245]
Hi,

I use loki-distributed(2.6.0) in basic configuration to test limits (see components bellow for illustration):

loki-dist-distributor-6985757c94-t5rzc    
loki-dist-gateway-6b487d89ff-ltvrv 
loki-dist-ingester-0
loki-dist-memcached-frontend-0
loki-dist-memcached-index-queries-0
loki-dist-querier-0 
loki-dist-query-frontend-6bd587ff6-qpbkc
loki-dist-ruler-75f6bb9477-4kwfn

data is stored on S3 for approximately 3 months (1.5 GB)

I'm trying to run expensive query: 
`sum(count_over_time({namespace=~".+"} |= "ERROR"[$__range])) by (namespace)`
in order to test final number and limits for individual loki components.

I'm able to perform the query for 14 days but not for more. 
Longer range ends with `context deadline exceeded` after 5 minutes always.

In logs I see:
- query-frontend
```
level=warn ts=2022-09-26T11:27:02.543128071Z caller=grpc_logging.go:55 method=/frontend.Frontend/Process duration=38m58.67251922s err="context deadline exceeded" msg="gRPC\n"
level=error ts=2022-09-26T11:27:02.543332581Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context deadline exceeded"
level=warn ts=2022-09-26T11:27:02.543609904Z caller=logging.go:72 traceID=5bddbd580e868eff orgID=fake msg="GET /loki/api/v1/query_range?direction=backward&end=1664191322075000000&limit=1500&query=sum%28count_over_time%28%7Bnamespace%3D~%22.%2B%22%7D+%7C%3D+%22ERROR%22%5B1296000s%5D%29%29+by+%28namespace%29&start=1662895322075000000&step=900000ms (504) 5m0.003251296s Response: \"context deadline exceeded\" ws: false; Accept-Encoding: gzip; Connection: close; User-Agent: Grafana/9.0.2; "
```
- querier:
```
level=error ts=2022-09-26T11:27:02.543989552Z caller=frontend_processor.go:69 msg="error processing requests" address=10.254.132.186:9095 err="rpc error: code = Unknown desc = context deadline exceeded"
```

I have set following timeouts:

- grafana (loki datasource timeout 120s)
```
[dataproxy]
timeout = 360
```
- nginx (loki-distributed gateway)
```
proxy_connect_timeout       900;
proxy_send_timeout          900;
proxy_read_timeout          900;
send_timeout                900;
```
- loki
```
server:
  http_server_read_timeout: 600s
  http_server_write_timeout: 600s
querier:
  engine:
    timeout: 10m
    query_timeout: 10m
```
Is there any other timeout to tweak?

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.

**Comment by NikhilVerma04** [comment]
Hello @VtG242, I was facing the same problem generally it happens when the query took more time to serve your request than the default query_timeout value in Loki. We can increase it in Loki configuration but the query_timeout has been dissipated by Loki from querier now we have to mention it in the limits_config in the configuration file.

querier:
  engine:
    timeout: 10m
    query_timeout: 10m

remove it from here and move it to limits_config

limits_config:
  query_timeout : 1200s

This works from me. 😄
