### ISSUE TITLE
logcli query: respect `--since` and `--limit` when tailing

### ISSUE THREAD

**Issue by shane-axiom** [grafana/loki#726]
Currently when using `--tail` both `--limit` and `--since` are disregarded and no log lines previous to when the tailing started are output. Users should be able to request previous log lines using `--limit` and/or `--since` when tailing, as is possible with other log cli tools like `docker logs`.

Maybe an initial "normal" log request could be run and output before starting the websocket?

**Comment by sh0rez** [comment]
Looking into this

**Comment by shane-axiom** [comment]
@sh0rez Thanks for taking on all these feature requests, much appreciated!
