### ISSUE TITLE
[Helm] Issue with loki service in singleBinary

### ISSUE THREAD

**Issue by fyannk** [grafana/loki#7260]
**Describe the bug**
Fresh install through Helm Chart of single binary is not working when going through deffault service.

Currently we have [here](https://github.com/grafana/loki/blob/dcfba366de2fbe036df31e28200df983d4808e67/production/helm/loki/templates/single-binary/service.yaml#L21):

```yaml
  selector:
    {{- include "loki.selectorLabels" . | nindent 4 }}
```

And we **should** have:

```yaml
  selector:
    {{- include "loki.singleBinarySelectorLabels" . | nindent 4 }}
```

Hence, service point to all instances created by Helm Chart, Canary included !

Promtail cannot push logs and Grafana cannot read them

**To Reproduce**
Fresh install the solution with values:

```yaml
loki:
  storage:
      type: 'filesystem'
    rulerConfig:
      storage:
        type: local
```

**Expected behavior**
Included default service should be working

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Logs**

```log
level=error ts=2022-09-27T11:18:17.537024173Z caller=client.go:380 component=client host=loki:3100 msg="final error sending batch" status=404 error="server returned HTTP status 404 Not Found (404): 404 page not found"
level=error ts=2022-09-27T11:18:18.337102338Z caller=client.go:380 component=client host=loki:3100 msg="final error sending batch" status=404 error="server returned HTTP status 404 Not Found (404): 404 page not found"
```

**Comment by besteban1989** [comment]
I'm running with the same issue, @fyannk your solution works, I updated the kubernetes service manually, also created the PR. @jeschkies can you help us reviewing the PR ? 

Thanks.

**Comment by besteban1989** [comment]
@vlad-diachenko can we have a new helm chart version? If you can add a new version will be very helpful. Thanks.

**Comment by vlad-diachenko** [comment]
> @vlad-diachenko can we have a new helm chart version? If you can add a new version will be very helpful. Thanks.

Hey @besteban1989 . sorry for the delay. yes, I released the new version of helm chart at the moment when I merged the PR... so, you can use the latest chart, the changes are there....
