### ISSUE TITLE
Documentation website

### ISSUE THREAD

**Issue by pracucci** [grafana/loki#727]
In preparation for the first stable release, is there any interest in working on a public documentation website similarly to prometheus.io?

@tomwilkie @Kuqd

**Comment by Kuqd** [comment]
Yes we do want to work on this. I personally had in mind to use docsy I did used it successfully with my previous project https://agones.dev/site/.

So yes definitively.

/cc @gouthamve

**Comment by pracucci** [comment]
@Kuqd I would be glad to contribute. A part from the tooling, do you already have thoughts about the contents and how to organize it?

**Comment by Kuqd** [comment]
I've not yet come up with this but we can discuss this here.

**Comment by Kuqd** [comment]
I've talked to the team and the plan is to first get the full documentation as markdown, then we're going to use that with a static generator.

So I'd say for now let's focus on documentation in this repo.

**Comment by sh0rez** [comment]
Personally, I have made perfect experience with using Gatsby (https://www.gatsbyjs.org/) for this kind of purpose. 

This system shares my love for Real websites, no templates, React and Markdown.

After all, you build some React skeletons, parse the markdown into it, get all of the nasty parts (SSR, lazy loading, bundle splitting, bla bla bla) managed. And still a static website (GH-pages, Netlify, etc.)

TBH I would prefer this over Hugo / Jekyll / whatevertheiselse
