### ISSUE TITLE
Consider splitting the logproto on its own package

### ISSUE THREAD

**Issue by jpkrohling** [grafana/loki#7281]
**Is your feature request related to a problem? Please describe.**
When consuming the logproto package, like in the Loki translator from the OpenTelemetry Collector Contrib repository [[link](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/a473a33e01e3a7a7b06d0df1c96927f5d1e18018/pkg/translator/loki/go.mod#L6)], dependencies that aren't relevant, such as Prometheus or Thanos (see #7217), are included in the dependency graph.

**Describe the solution you'd like**
I would like to suggest splitting the logproto package into its own Go module. It doesn't have to have its own repository.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by NPellet** [comment]
We also got just bit by this. We're trying to reuse the generated gRPC client, but we're pulling a ton of dependencies which are breaking bazel and is just not viable.

imho splitting should be fairly easy, this has been done for the push module

**Comment by jpkrohling** [comment]
I'm closing, it's been a while since this was opened and no feedback was given yet. Given that the loki exporter is now deprecated, we likely don't need this anymore.
