### ISSUE TITLE
loki 

### ISSUE THREAD

**Issue by anmolrai16** [grafana/loki#7282]
Can't add Loki as data source by ip http://172.16.10.15:3100.
On press Save & test getting error:Unable to fetch labels from Loki (Failed to call resource), please check the server logs for more details

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
