### ISSUE TITLE
failed to send row while processing boltdb index query: timed out sending response

### ISSUE THREAD

**Issue by oysteinhagenpettersen** [grafana/loki#7314]
**Describe the bug**
Started to see the following error message in the loki logs

`method=SeriesStore.LabelNamesForMetricName level=error msg=lookupLabelNamesBySeries err="failed to send row while processing boltdb index query: timed out sending response"`

**Environment:**
 - Infrastructure: Kubernetes
 - Loki v2.5.0

**Comment by oysteinhagenpettersen** [comment]
Done some more digging here. The "failed to send row" message lines up with the p90 and p99 in loki_boltdb_shipper_request_duration_seconds_bucket historgram sort of "maxing out".

**Comment by chaudum** [comment]
Hey @oysteinhagenpettersen Do you see another error log just before that line you posted above? That could help narrowing down the problem.
Also, do you use a chunks cache (e.g. Memcached)?

**Comment by oysteinhagenpettersen** [comment]
@chaudum , thanks for you reply. The message right before the message above is: 

`
"GET /loki/api/v1/labels?end=1663660500000000000&start=1663660020000000000 (500) 39.224818468s Response: \"failed to send row while processing boltdb index query: timed out sending response\\n\" ws: false; X-Scope-Orgid: fake; uber-trace-id: 591bcee126ff3325:755263383ff24bc0:370eb5aa9c63ce51:1; "
`

When checking the trace for this message I can see that the Shipper.Query method invocation takes a lot of time: 39 sec.

We are not using Memcached at the moment, but we are using the fifocache, with the following config: 

```yaml
  cache_results: true
  results_cache:
    cache:
      enable_fifocache: true
      fifocache:
        max_size_bytes: 2GB
        validity: 24h
```

**Comment by oysteinhagenpettersen** [comment]
@chaudum , we are also running the queries as a k8s deployment and not a StatefulSet. Not sure if this could be something to look at?

**Comment by oysteinhagenpettersen** [comment]
Have testing with running the index gateway as a StatefulSet now. When following the traces we can see that the querier calls the index gateway which again calls Shipper.Query. Looks like the SeriesStore.LabelNamesForMetricName is the part that cases the massive loop and that this is the part that uses all the query time.

**Comment by oysteinhagenpettersen** [comment]
I am ready to close this now. We saw a big improvement in query time when running the querier as a StatefulSet without the index gateway. We store 14 days of index in the querier using the `query_ready_num_days` config. 

We still have some issues with getting the cache setup correct but at least this has been a big improvement. 

I was never able to track down where the `failed to send row while processing boltdb index query: timed out sending response` message originated from, but using traces we could see that it was using too much time downloading indexes at query time.
