### ISSUE TITLE
[helm] Migration guide from `grafana/loki-distributed` to `grafana/loki`

### ISSUE THREAD

**Issue by trevorwhitney** [grafana/loki#7330]
Moving from the old `grafana/loki-distributed` helm chart to the new `grafana/loki` helm chart is not a simple process, as it involves moving from a distributed topology to a simple-scalable one. We need a migration guide on how to doe this without data loss.

**Comment by braunsonm** [comment]
@trevorwhitney is the `loki` chart recommended over the distributed chart these days? You mention "old" when describing it and the fact that you're looking to add migration documentation seems to suggest that but I thought they solved different volumes of data.

Or is `loki` considered reasonably as scalable as distributed microservices architecture?

**Comment by trallnag** [comment]
@braunsonm in the issue / pull request that migrates the simple scalable Helm chart to the new loki Helm chart it is mentioned that the simple scalable deployment mode is the one most used and maintained by the developers.

I'm currently trying to figure out how to migrate from distributed to scalable. Although my setup is very simple and all my data is stored in S3.

I'm having more difficulties to figure out how to adapt my release values to the new chart. There's now a lot of templating going on

**Comment by trevorwhitney** [comment]
@braunsonm in response to feedback from both open source users and customers of Grafana Enterprise Logs for better helm support, the Loki team is taking on the responsibility to build and actively support a helm chart. In the past, helm chart efforts (such as `loki-distributed`) have been largely community driven with occasional help from the Loki team. The new `loki` chart will be more actively maintained by the Loki maintainers, and thus we will likely be contributing less to community efforts.

The new chart is more opinionated based on how we run Loki ourselves at Grafana Labs. As a result, we are currently only planning to support single binary using local filesystem storage, and the scalable deployment (previously referred to as Simple Scalable) type using object storage. Our recommendation is that more complicated deployment topologies (such as the microservices approach used in `loki-distributed`) require more flexible deployment tools than helm. It is not our intention to add every possible configuration option via the `loki` chart's `values.yaml` that you might need in a distributed deployment, as our goal with this chart is easier installation and operation.

So, to answer your question, if you are looking for something maintained by and tested at Grafana Labs, I would recommend the new `loki` chart, or doing microservices via our published jsonnet libraries. If you are comfortable with a more community-driven chart, one that you might want to get involved with, I think staying on `loki-distributed` is great!

**Comment by trevorwhitney** [comment]
@trallnag I just re-opened this issue as I accidentally closed it with helm chart changes that are needed for the migration guide, but that PR didn't actually include the migration guide. Working on that today, so keep tabs on this issue for a guide that should help you out.

The tl;dr; is you're going to spin up a second cluster using the new chart, join that scalable cluster with your distributed cluster via memberlist, then take down the distributed cluster's ingesters 1 by 1 until there are none left, at which point you can delete the distributed cluster.
