### ISSUE TITLE
Add Log Graph based on log graph in explore

### ISSUE THREAD

**Issue by Rezzhaf** [grafana/loki#7350]
![image](https://user-images.githubusercontent.com/113589335/194252411-1d419ce6-b371-45b7-89c8-8395400860f9.png)

Hi everyone, i just want to ask about this.

i want to make dashboard based on log graph on explore. its like when the log created on what time

{app="asj-jarvis"}|= ":500,"

select app with filtering option

but on dashboard visualitation, i cant find anything like it.

can someone help?

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
