### ISSUE TITLE
Question | How to use multi tenancy in a scalable way

### ISSUE THREAD

**Issue by noamApps** [grafana/loki#7351]
Hello! Is there a way to add an extra label to an incoming stream with a URI parameter? my use case is to allow multi tenancy in an autonomous and scalable way:
- If I use the multi-tenancy feature, Im required to either manually add a datasource for each new tenant, or edit an existing one with "|new tenant" if using Loki 2.6+
- Tried to use single datasource without multi tenancy and implement multi tenancy with labels - but couldn't find a way to do add a global extra label in the uri (I want to achieve that in the receiving end and not in the log-sending agent)

Thanks for the help!

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
