### ISSUE TITLE
Tracebacks on Startup (Line 1126)/Unterminated regular expressions (Line 22) on Windows 10 Pro

### ISSUE THREAD

**Issue by g33k247** [grafana/loki#7352]
- Receiving multiple (16 or 17) errors on startup:
`File "\\vboxsvr\workspace\Loki\loki.py", line 1126, in initialize_yara_rules yara.SyntaxError: line 22: unterminated regular expression Traceback (most recent call last)" and 'yara.SyntaxError: line 22: unterminated regular expression`

**To Reproduce**
- Start Loki ".\Loki.exe"

**Expected behavior**
- No errors

**Environment:**
- Windows 10 Pro

**Screenshots*
![2022-10-06_06-07-36](https://user-images.githubusercontent.com/8498814/194286488-49a9f5ea-c292-4ca2-b10c-d78cf32e7637.jpg)

**Comment by dannykopping** [comment]
I believe the repo you should report this to is https://github.com/Neo23x0/Loki.
