### ISSUE TITLE
loki in Grafana UI report error: syntax error: unexpected IDENTIFIER, expecting != or !~ or |~ or |="

### ISSUE THREAD

**Issue by thermal-life** [grafana/loki#7373]
Describe the bug:
        i'm trying to match  some error message by loki Grafana UI , when i click the UI button to create query，it's wok。but write  the same query manually by loki Grafana UI ,  I get this error:
invalid match stage config: invalid selector syntax for match stage: parse error at line 1, col 28: syntax error: unexpected IDENTIFIER, expecting != or !~ or |~ or |="
![image](https://user-images.githubusercontent.com/66098206/194705253-e273696f-e198-48c7-b041-0eb3a93be093.png)

It was always work a few days ago.

grafana: 8.5.3
loki: 2.3.0
promtail: 2.3.0

**Comment by yzchen27** [comment]
hi,I have encountered the same problem,  how to solve it?
