### ISSUE TITLE
Docs feedback: /installation/simple-scalable-helm.md

### ISSUE THREAD

**Issue by joejulian** [grafana/loki#7374]
The chart this page references is "DEPRECATEDD" (sic). What's the best way to do this with helm, now?

**Comment by trallnag** [comment]
It has been moved to this location: https://github.com/grafana/loki/tree/main/production/helm/loki

**Comment by joejulian** [comment]
Should the docs be updated to match?

**Comment by trallnag** [comment]
Yes, they should. There are many other things lacking in the docs (for example an explanation of all the things included in the chart), but I don't have enough knowledge to update them properly (content wise).

**Comment by JStickler** [comment]
Closed via https://github.com/grafana/loki/pull/7034
Docs are here https://grafana.com/docs/loki/latest/setup/install/helm/install-scalable/
