### ISSUE TITLE
Filter operators documentation

### ISSUE THREAD

**Issue by pracucci** [grafana/loki#739]
According to `docs/usage.md`, Grafana supports the filter expression in the format `{job="mysql"} |= "error"` where the supported filter operators are:

- `|=`
- `!=`
- `|~`
- `!~`

Digging in the source code, I've the feeling such filter operators have not been implemented and Loki actually always use a regex match.

Is my understanding correct? If yes, do you agree if we update `usage.md` to reflect the current implementation?

**Comment by Kuqd** [comment]
It is implemented in the logql package. There’s also a PR for an evolution of this.

**Comment by pracucci** [comment]
How can I practically use it via Grafana o calling the query API? Do you
mind sharing any hint, please?

**Comment by pracucci** [comment]
Duplicate of https://github.com/grafana/loki/issues/707. I will follow up in the original issue. Sorry for the noise.
