### ISSUE TITLE
Chart grafana/loki: Non-existing config loki.authEnabled in examples

### ISSUE THREAD

**Issue by trallnag** [grafana/loki#7409]
As of today the example [production/helm/loki/docs/examples/oss/overrides-oss-gcs.yaml (permalink)](https://github.com/grafana/loki/blob/85e524788e9892c4413157ce07b516f88109c935/production/helm/loki/docs/examples/oss/overrides-oss-gcs.yaml) contains the following block:

```yaml
loki:
  authEnabled: false
```

This is incorrect. There is no `authEnabled` in the `values.yaml`. It has to be `auth_enabled`. Or the templates need to be updated to use `authEnabled`.

**Comment by jeschkies** [comment]
@trallnag thanks. Could you create a pull request with the changes?
