### ISSUE TITLE
docs not clear about case sensitive expression and supported regex syntax

### ISSUE THREAD

**Issue by Dieterbe** [grafana/loki#741]
Hi, I read https://grafana.com/docs/features/datasources/loki/ 
It does not describe case sensitive of query expression (regex) part of the query.
In my experience, it is case sensitive. is there a way to make it insensitive? either way, seems like it could be described in the docs.

**Comment by Dieterbe** [comment]
actually, it would also be beneficial to describe the dialect/syntax of regex supported.
for example, seems like alternation ("or" as in `foo|bar`) works, so seems like posix extended regex works

**Comment by steven-sheehy** [comment]
Loki is not case sensitive by default, but can be by adding golang regex modifiers `(?i)` before the regex. I changed Grafana to add these by default when sending the query. But yes, more docs would be nice.
