### ISSUE TITLE
DynamoDB custom endpoint

### ISSUE THREAD

**Issue by abrekhov** [grafana/loki#7433]
Hi! 

There are parameters for S3 compatible APIs for storage. I want to use custom endpoint for DynamoDB compatible storage (e.g. [Serverless YDB](https://cloud.yandex.com/en/docs/ydb/docapi/tools/aws-setup)). 

How can use it? 

If it supported, I want to store index and chunks in custom DynamoDB service with custom endpoint.

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
