### ISSUE TITLE
Support lambda-promtail pipeline_stages

### ISSUE THREAD

**Issue by kyfk** [grafana/loki#7475]
**Is your feature request related to a problem? Please describe.**
When I use lambda-promtail on AWS EKS on Fargate, there's only way to send logs to Grafana Cloud Loki is lambda-promtail.
My applications output logs as json formatted to Cloudwatch Logs, then lambda-promtail send Grafana Cloud Loki.
I want to process that logs before sending to Loki, however lambda-promtail seems not to support `pipeline_stages`.

**Describe the solution you'd like**
I'd like to use syntax of loki's 'pipeline_stages'.
lambda-promtail doesn't need some configs(eg scrape_configs), it should be omitted in the configuration parsing implements.
https://grafana.com/docs/loki/latest/clients/promtail/pipelines/

**Describe alternatives you've considered**

**Additional context**

**Comment by mattiasnensen** [comment]
Any update on this?

**Comment by majandres** [comment]
i've tried going from lambda-promtail -> promtail -> loki endpoint... but this doesn't seem to work either.
would be nice to include pipeline stages at the lambda level... but maybe that will put too much load on the lambda?

**Comment by jeschkies** [comment]
Hm, I'd have to look at this but you could also use another Lambda which is probably more work. Unfortunately I don't think we have the resources to add pipeline stages to lambda but I'm happy to review any contributions adding them.

**Comment by mvadu** [comment]
> i've tried going from lambda-promtail -> promtail -> loki endpoint... but this doesn't seem to work either. would be nice to include pipeline stages at the lambda level... but maybe that will put too much load on the lambda?

We have used this successfully..  We have a need to generate metrics from logs, and needed to run with pipeline stages. We ran a grafana agent with [loki api end point](https://grafana.com/docs/loki/latest/clients/promtail/configuration/#loki_push_api), and having it scrape its own metrics and send to backend end. But having to run this instance on an EC2 defeats the purpose of lambda. We would really love to have this ask implemented where in we can just pass a config to promtail_lambda and have it process it for us.

**Comment by cstyan** [comment]
This is something we currently have no plans to support. As of right now lambda-promtail is best effort maintained and the majority of the features are community contributed. It was always meant to be a band aid to the fact that AWS doesn't let you get logs out of cloudwatch in any nicer way. 

The intended way to achieve the result you want is as you've described, running promtail in between lambda-promtail and loki.
