### ISSUE TITLE
Offset modifier doesn't accept negative values

### ISSUE THREAD

**Issue by jrivera294** [grafana/loki#7476]
**Describe the bug**
Negative offset modifiers in logql queries from Grafana throw the following exception:
`parse error at line 2, col 408: syntax error: unexpected -, expecting DURATION`

**To Reproduce**
Logql query with negative offset example (from prometheus documentation: https://prometheus.io/docs/prometheus/latest/querying/basics/#offset-modifier):
`rate(http_requests_total[5m] offset -1w)`

My current query:
`sum by (source) (count_over_time({logset="api_dataset"}[1d] offset -1d))`

**Expected behavior**
Same as promql negative offsets

**Environment:**
 - Infrastructure: docker-swarm

**Comment by dannykopping** [comment]
Thank you for reporting this @jrivera294 :+1: 
Please confirm your Loki version number?

**Comment by jrivera294** [comment]
Hi @dannykopping, sure:
`{"version":"2.6.1","revision":"6bd05c9a4","branch":"HEAD","buildUser":"root@ea1e89b8da02","buildDate":"2022-07-18T08:49:07Z","goVersion":""}`

**Comment by dojutsu-user** [comment]
Hi @dannykopping,
I would like to take this issue up. First time here, can you provide more info on this issue.

**Comment by dannykopping** [comment]
Hii @dojutsu-user

I think the description is pretty self-explanatory. What additional info do you require?

**Comment by dojutsu-user** [comment]
Hi @dannykopping,
Sorry, will let you know if anything comes. I am able to reproduce this in tests, will raise the fix in sometime.

**Comment by dojutsu-user** [comment]
Hi @dannykopping,
Not able to figure out the exact source of error. Can you help me here?
