### ISSUE TITLE
Docs feedback: /fundamentals/architecture/components.md

### ISSUE THREAD

**Issue by akauppi** [grafana/loki#7477]
Some changes to the paragraph:
https://grafana.com/docs/loki/latest/fundamentals/architecture/components/#timestamp-ordering

It currently states:

>Loki can be configured to [accept out-of-order writes](https://grafana.com/docs/loki/latest/fundamentals/configuration/#accept-out-of-order-writes).

Problems:

- The URL in the text no longer works
- What does this mean for Grafana Cloud users?

   Grafana Cloud allows log entries to be out-of-order, [since 2021](https://grafana.com/blog/2021/09/16/avoid-dropped-logs-due-to-out-of-order-timestamps-with-a-new-loki-feature/). I think this could be clearly stated in the context here.

Suggestion:

>Loki [accepts out-of-order writes](https://grafana.com/docs/loki/latest/configuration/#accept-out-of-order-writes) by default.

..as seen [here](https://grafana.com/docs/loki/latest/best-practices/)

**Comment by ameyanator** [comment]
I would like to work on this issue.
