### ISSUE TITLE
Upstream go-kit/log fork changes

### ISSUE THREAD

**Issue by 56quarters** [grafana/loki#7491]
**Is your feature request related to a problem? Please describe.**

In order to build the internal Grafana cloud gateway, we vendor a variety of projects into the same repo including Loki. Loki using a [replace directive and fork](https://github.com/grafana/loki/blob/7debe7c235061f51b02dabd3c9dba9daa485506b/go.mod#L349-L351) of something like go-kit/log makes it difficult to include Loki.

**Describe the solution you'd like**

The changes in the fork of go-kit/log are upstreamed so that everyone can get the benefit with no extra effort.

**Describe alternatives you've considered**

* Replicating the `replace` to every project that consumes Loki in any way.
* Remove dependency on Loki from the internal gateway.

**Comment by dannykopping** [comment]
@56quarters thanks for the good call out here - I will submit my patch upstream to go-kit/log when I get a chance.
Is this actively blocking anything?

**Comment by freeformz** [comment]
This looks like it's no longer the case that a go-kit/log replace exists in the go.mod file and this issue should probably be closed.

**Comment by dannykopping** [comment]
Thank you, that's correct!

Closed by https://github.com/grafana/loki/pull/8162
