### ISSUE TITLE
failed parse dynamodb URL when password contain '/'

### ISSUE THREAD

**Issue by LuckySB** [grafana/loki#7506]
**Describe the bug**

loki fail to start with error:
```
failed parsing config: /etc/loki/config/config.yaml: parse "dynamodb://AKIAZEGVD4ZGLD6S1111:IBqSwP/oldTb4wzqhUmBQoOrk34567tfuXxWFO9X@us-west-1": invalid port ":IBqSwP" after host
```

**To Reproduce**

Start loki in EKS with dynamodb storage and AWS user password with / symbol

```
dynamodb_url: dynamodb://AKIAZEGVD4ZGLD6S1111:IBqSwP/oldTb4wzqhUmBQoOrk34567tfuXxWFO9X@us-west-1
```

**Comment by camme** [comment]
I just had the same issue but got it to work if I escaped the '/' with %2F. Hope it helps.

**Comment by JStickler** [comment]
Closing as this sounds like it has a workaround.  And DynamoDB was deprecated in 2.9.  We do not plan any further development for DynamoDB as a storage backend.
