### ISSUE TITLE
Loki --version fails unless you point to a config file

### ISSUE THREAD

**Issue by weakcamel** [grafana/loki#7554]
**Describe the bug**

**To Reproduce**

1. Install latest Loki (2.6.0) with config file in e.g. `/etc/loki/loki.yml`
2. Check version with `loki --version`

**Expected behavior**

By convention, a version check shouldn't depend on having a configuration file present.

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Screenshots, Promtail config, or terminal output**

This fails:
```
# loki --version
failed parsing config: config.yaml,config/config.yaml does not exist, set config.file for custom config path
```

whereas e.g. this succeeds:

```
# loki --version --config.file /etc/loki/loki.yml
loki, version 2.6.0 (branch: HEAD, revision: b92f113cb)
  build user:       root@6af236db210a
  build date:       2022-07-08T13:40:05Z
  go version:       go1.17.6
  platform:         linux/amd64
```

**Comment by dannykopping** [comment]
No worries :)
