### ISSUE TITLE
deployed promtail in nomad : Error refreshing service - consul

### ISSUE THREAD

**Issue by maddy023** [grafana/loki#7571]
Promtail is deployed in nomad with below job config, to scrape the logs and push to loki. 

Promtail Config:
```

job "promtail" {
  datacenters = ["us-west-2"]
  # Runs on all nomad clients
  type = "service"

  constraint {
    attribute = meta.cluster
    operator  = "="
    value     = "service"
  }


  group "promtail" {
    count = 1

    network {
      dns {
        servers = ["172.17.0.1", "8.8.8.8", "8.8.4.4"]
      }
      port "http" {
        static = 3200
      }
    }

    restart {
      attempts = 3
      delay    = "20s"
      mode     = "delay"
    }

    task "promtail" {
      driver = "docker"
      template {
        data        = <<EOTC

server:
  http_listen_port: 3200
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki.domain.co/loki/api/v1/push #exposed loki

scrape_configs:
- job_name: 'nomad-logs'
  consul_sd_configs:
    - server: 'http://consul.domain.co:8500' # where connsul is exposed 
  relabel_configs:
    - source_labels: [__meta_consul_node]
      target_label: __host__
    - source_labels: [__meta_consul_service_metadata_external_source]
      target_label: source
      regex: (.*)
      replacement: '$1'
    - source_labels: [__meta_consul_service_id]
      regex: '_nomad-task-([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})-.*'
      target_label:  'task_id'
      replacement: '$1'
    - source_labels: [__meta_consul_tags]
      regex: ',(app|monitoring),'
      target_label:  'group'
      replacement:   '$1'
    - source_labels: [__meta_consul_service]
      target_label: job
    - source_labels: ['__meta_consul_node']
      regex:         '(.*)'
      target_label:  'instance'
      replacement:   '$1'
    - source_labels: [__meta_consul_service_id]
      regex: '_nomad-task-([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})-.*'
      target_label:  '__path__'
      replacement: '/nomad/alloc/$1/alloc/logs/*std*.{?,??}'
EOTC
        destination = "/local/promtail.yml"
      }

      config {
        image = "grafana/promtail:2.2.1"
        ports = ["http"]
        args = [
          "-config.file=/local/promtail.yml",
          "-print-config-stderr"
        ]
        volumes = [
          "/etc/nomad/:/nomad/"
        ]
      }

      resources {
        cpu    = 50
        memory = 100
      }

      service {
        name = "promtail"
        port = "http"
        tags = ["monitoring","prometheus"]

        check {
          name     = "Promtail HTTP"
          type     = "http"
          path     = "/targets"
          interval = "5s"
          timeout  = "2s"

          check_restart {
            limit           = 2
            grace           = "60s"
            ignore_warnings = false
          }
        }
      }
    }
  }
}

```

Promtail Logs:

**_**```
level=info ts=2022-11-02T06:11:23.752046042Z caller=server.go:229 http=[::]:3200 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2022-11-02T06:11:23.75256025Z caller=main.go:112 msg="Starting Promtail" version="(version=2.2.1, branch=HEAD, revision=babea82ef)"
level=error ts=2022-11-02T06:12:53.299030482Z caller=consul.go:503 component=discovery discovery=consul msg="Error refreshing service" service=ghcr-io-euforia-wuw-main tags= err="Unexpected response code: 504 ()"
level=error ts=2022-11-02T06:12:53.299326587Z caller=consul.go:385 component=discovery discovery=consul msg="Error refreshing service list" err="Unexpected response code: 504 ()"
level=error ts=2022-11-02T06:12:53.299540994Z caller=consul.go:503 component=discovery discovery=consul msg="Error refreshing service" service=-detect tags= err="Unexpected response code: 504 ()"
level=error ts=2022-11-02T06:12:53.299571411Z caller=consul.go:503 component=discovery discovery=consul msg="Error refreshing service" service=proxy tags= err="Unexpected response code: 504 ()"
level=error ts=2022-11-02T06:12:53.299594444Z caller=consul.go:503 component=discovery discovery=consul msg="Error refreshing service" service=auth tags= err="Unexpected response code:504 ()"
level=error ts=2022-11-02T06:12:53.299613379Z caller=consul.go:503 component=discovery discovery=consul msg="Error refreshing service" service=nomad tags= err="Unexpected response code: 504 ()"
level=error ts=2022-11-02T06:12:53.300596306Z caller=consul.go:503 component=discovery discovery=consul msg="Error refreshing service" service=fabio tags= err="Unexpected response code: 504 ()"
level=error ts=2022-11-02T06:12:53.30088398Z caller=consul.go:503 component=discovery discovery=consul msg="Error refreshing service" service=-deploy tags= err="Unexpected response code: 504 ()"
level=error ts=2022-11-02T06:12:53.301032825Z caller=consul.go:503 component=discovery discovery=consul msg="Error refreshing service" service=consul tags= err="Unexpected response code: 504 ()"
level=error ts=2022-11-02T06:12:53.301099701Z caller=consul.go:503 component=discovery discovery=consul msg="Error refreshing service" service=loki tags= err="Unexpected response code: 504()"
level=error ts=2022-11-0
```**_**

**Comment by dannykopping** [comment]
It seems to me that your the endpoint you're using for consul service discovery is returning a 504 (`Unexpected response code: 504()`).
This doesn't seem like a bug in promtail to me, but rather an issue in your setup.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
