### ISSUE TITLE
-version option bad behaviour

### ISSUE THREAD

**Issue by ethiquable** [grafana/loki#7603]
**Describe the bug**
-version requires a config.yaml file

**To Reproduce**
1. Started Loki (2.6.1)
2. Started Promtail (2.4.1) to tail '...'
3. Query: `{} term`

**Expected behavior**
loki-linux-amd64 -version
loki, version 2.6.1 (branch: HEAD, revision: 6bd05c9a4)
  build user:       root@af90ed01061f
  build date:       2022-07-18T08:41:09Z
  go version:       go1.17.6
  platform:         linux/amd64

**Environment:**
 - Infrastructure: bare-metal
 - Deployment tool: none

**Screenshots, Promtail config, or terminal output**
loki-linux-amd64 -version                                                
failed parsing config: config.yaml,config/config.yaml does not exist, set config.file for custom config path

**Comment by dannykopping** [comment]
This has already been addressed in https://github.com/grafana/loki/pull/6802, and will be available in the upcoming 2.7 release.
