### ISSUE TITLE
Change default resolution

### ISSUE THREAD

**Issue by jmipba55** [grafana/loki#7615]
When we run a query on a loki datasource, is it possible to change the default resolution value? In order to improve performance, we want the default value to be 1/10.
![Captura de pantalla 2022-11-07 a las 10 39 00](https://user-images.githubusercontent.com/76151408/200324046-eedfbff2-8590-4a13-974f-d7384c9d2cd6.png)

**Comment by MichelHollands** [comment]
@jmipba55 This is configured in Grafana (and not in Loki). See [Grafana provisioning](https://grafana.com/docs/grafana/latest/administration/provisioning/) for a way to set this.
