### ISSUE TITLE
logcli query: using --no-labels and --tail together results in error

### ISSUE THREAD

**Issue by shane-axiom** [grafana/loki#765]
Using `logcli query` with both `--tail` and `--no-labels` results in the following error:

```
logcli query --tail --no-labels '{stream="stderr"}' 
2019/07/16 20:35:54 ws://<host>:3100/api/prom/tail?query=%7Bstream%3D%22stderr%22%7D&regexp=&delay_for=0
2019/07/16 20:35:55 Failed to parse labels: parse error at char 1: missing metric name or metric selector
```

Omitting either of the `--tail` or `--no-labels` flags works fine. Also, connecting to the websocket URL output by logcli directly seems to work fine, so I suspect the error is in `logcli`'s parsing of the results.

**Comment by adityacs** [comment]
@shane-axiom I am unable to reproduce this error. I can get the query working with both `--tail` and `--no-labels`

**Comment by adityacs** [comment]
@shane-axiom I am unable to reproduce this error. Could you please provide more details?

**Comment by javefang** [comment]
I'm using logcli v0.2.0, experiencing the same error.

```
logcli query --no-labels --tail '{namespace="kube-system"}'
2019/08/06 18:57:28 ws://localhost:3100/api/prom/tail?query=%7Bnamespace%3D%22kube-system%22%7D&regexp=&delay_for=0&limit=30&start=1565110648524749236
2019/08/06 18:57:29 Failed to parse labels: parse error at char 1: missing metric name or metric selector
```
