### ISSUE TITLE
Log labels not displaying all the app/namespace

### ISSUE THREAD

**Issue by Sharathmk99** [grafana/loki#767]
Hi Team,

When there is a active logs, Loki->Log Label show all the apps/namespaces/etc... But if there is no active logs it doesn't show apps which are inactive.
For example app A is writing some logs, then i can see this app under Loki->Log labels->Apps->App A. If app A stops writing logs for sometime i can't see this app under Loki->Log labels->Apps->. 

If i select the time range as this year also it will not show. But i query like 
`{app="app A"}`
I can see logs. Any configuration i have to do for this?

Thank you for your time!

**Comment by Kuqd** [comment]
This should be fixed if you update Loki to the last docker image.

**Comment by Sharathmk99** [comment]
Thank you very much. I'll try to update and check.

**Comment by Sharathmk99** [comment]
Do i need to upgrade to latest? I'm currently using v0.1.0

**Comment by Kuqd** [comment]
Yes just update your image to master, we should have soon a release schedule

**Comment by Sharathmk99** [comment]
After upgrading  to master also still same behavior.

**Comment by cyriltovena** [comment]
@Sharathmk99 We're going to need more informations (config used, error logs).
