### ISSUE TITLE
timechart by level

### ISSUE THREAD

**Issue by mehrdad2000** [grafana/loki#7679]
Hi
I need to show logs by level on time chart on dashboard.

here is my the query 
{job="varlogs"} | pattern `<timestamp> <time> <hostname> <level> <msg>` 

i try this but doesn't return result:
{job="varlogs"} | pattern `<timestamp> <time> <hostname> <level> <msg>` | by (level)

Any idea?
Thanks

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
