### ISSUE TITLE
promtail parse my labels right but I don't have in loki

### ISSUE THREAD

**Issue by raulcejas04** [grafana/loki#7680]
I suppose promtail parse my labels right, because I can not see any error in my promtail log,
 but I don't have this labels in loki, I can not see serial for example, I attached an screenshot at the end of this post.

I compile promtail and get detailled debug:

[inspect: regex stage]: 
{stages.Entry}.Extracted["serial"]:
	+: 12345678920
{stages.Entry}.Extracted["time"]:
	+: 2022-12-11T19:40:04-03:00
[inspect: regex stage]: 
{stages.Entry}.Extracted["serial"]:
	+: 12345678920
{stages.Entry}.Extracted["time"]:
	+: 2022-12-11T19:40:05-03:00
[inspect: labels stage]: 
{stages.Entry}.Entry.Labels:
	-: {__path__="/var/log2/*", job="jobprueba"}
	+: {__path__="/var/log2/*", job="jobprueba", serial="12345678920", time="2022-12-11T19:40:04-03:00"}
[inspect: labels stage]: 
{stages.Entry}.Entry.Labels:
	-: {__path__="/var/log2/*", job="jobprueba"}
	+: {__path__="/var/log2/*", job="jobprueba", serial="12345678920", time="2022-12-11T19:40:05-03:00"}
[inspect: timestamp stage]: 
{stages.Entry}.Entry.Entry.Timestamp:
	-: 2022-11-12 20:05:45.600363181 -0300 -03
	+: 2022-12-11 19:40:04 -0300 -03
[inspect: regex stage]: 
{stages.Entry}.Extracted["serial"]:
	+: 12345678921
{stages.Entry}.Extracted["time"]:
	+: 2022-12-11T19:40:06-03:00
2022-12-11T19:40:04-0300	{__path__="/var/log2/*", job="jobprueba", serial="12345678920", time="2022-12-11T19:40:04-03:00"}	12345678920 2022-12-11T19:40:04-03:00  3396  5008 I cvip-ch :  0000016359001505560 ARM 00888 HP_PPRIOR       [rc/stages/pose_prior_stage.cpp:00047]:I:: PosePriorStage: using LM [7617662218, 1] generated at 7617662218, shift[0arc, 0.0mm]
[inspect: timestamp stage]: 
{stages.Entry}.Entry.Entry.Timestamp:
	-: 2022-11-12 20:05:45.600364761 -0300 -03
	+: 2022-12-11 19:40:05 -0300 -03
2022-12-11T19:40:05-0300	{__path__="/var/log2/*", job="jobprueba", serial="12345678920", time="2022-12-11T19:40:05-03:00"}	12345678920 2022-12-11T19:40:05-03:00  3396  5008 I cvip-ch :  0000016359026477355 ARM 00888 HP_PPRIOR       [rm/src/headpose_arm_blocks.cpp:00680]:I:: [HP_INFO] High vision latency of 26308us, vision 7617728884 imu 7617755192
[inspect: labels stage]: 
{stages.Entry}.Entry.Labels:
	-: {__path__="/var/log2/*", job="jobprueba"}
	+: {__path__="/var/log2/*", job="jobprueba", serial="12345678921", time="2022-12-11T19:40:06-03:00"}
[inspect: regex stage]: 
{stages.Entry}.Extracted["serial"]:
	+: 12345678922
{stages.Entry}.Extracted["time"]:
	+: 2022-12-11T19:40:07-03:00
[inspect: timestamp stage]: 
{stages.Entry}.Entry.Entry.Timestamp:
	-: 2022-11-12 20:05:45.600367402 -0300 -03
	+: 2022-12-11 19:40:06 -0300 -03

We can see time and serial labels that are in my config.yaml:

scrape_configs:
  - job_name: jobprueba
    pipeline_stages:
      - match:
          selector: '{job="jobprueba"}'
          stages:
          - regex:
              expression: '^(?P<serial>\w+) (?P<time>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}[+-]\d{2}:\d{2}).*$'
          - labels:
              serial:
              msg:
              time:          
          - timestamp:
              source: time          
              format: RFC3339
              location: "America/Buenos_Aires"
        
    static_configs:
      - targets:
          - localhost
        labels:
          job: jobprueba
          __path__: /var/log2/*

It is my promtail config:

scrape_configs:
  - job_name: jobprueba
    pipeline_stages:
      - match:
          selector: '{job="jobprueba"}'
          stages:
          - regex:
              expression: '^(?P<serial>\w+) (?P<time>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}[+-]\d{2}:\d{2}).*$'
          - labels:
              serial:
              time:          
          - timestamp:
              source: time          
              format: RFC3339
              location: "America/Buenos_Aires"
        
    static_configs:
      - targets:
          - localhost
        labels:
          job: jobprueba
          __path__: /var/log2/*

I run promtail from terminal and in docker and I am getting the same result.

in the image I only have the default labels filename and  job, but I don't have serial, and the timestamp is not exactly the same as in my log

I am running promtail in the console for debuging and in docker with loki and grafana.

If I get labels my label serial are no present:

curl http://192.168.1.5:3100/loki/api/v1/labels
{"status":"success","data":["__name__","filename","job"]}

thank you

**Comment by MichelHollands** [comment]
@raulcejas04 You don't have a [capture group name](https://grafana.com/docs/loki/latest/clients/promtail/stages/regex/#schema) in your regexes. That could explain why you don't get the labels. Promtail won't know how what name to use.

Please reopen the ticket if you have more questions
