### ISSUE TITLE
grpc response size larger than max configured

### ISSUE THREAD

**Issue by lcarbajales** [grafana/loki#7700]
**Describe the bug**
We get the following error message from the querier container when doing a query from Grafana
`caller=scheduler_processor.go:163 org_id=fake msg="response larger than max message size" size=175214367 maxMessageSize=104857600`
This happens despite all Loki components grpc recv/send max message being configured at 104857600, so it comes as a surprise that any other component would send size 175214367 through grpc.
This error only happens when doing a very specific line filter on a log stream, if the line filter is changed or removed completely from the same log stream (querying all logs in the same time range) the error doesn't happen, which leads us to believe it could be a bug.
Something that could be related to this behaviour is that the log stream in question contains some very large log lines (in the range of MiB)

**To Reproduce**
1. Open an "explore" page in Grafana with a relatively small time-range, in our case it was "last 1 hour".
2. Query: `{<log_stream>} |= <line_filter>`: query fails with described error message above from the querier.

3. Query: `{<log_stream>}`: no error message at all

**Expected behavior**
Expected query to succeed with a specific <line_filter> if the same log stream and time range succeeds with no line filters.

**Environment:**
 - Infrastructure: Kubernetes

**Screenshots, Promtail config, or terminal output**
All loki-components (querier, query grpc_client and grpc_server configs are set as such (taken from the /config endpoint)
`grpc_client_config:
    max_recv_msg_size: 104857600
    max_send_msg_size: 104857600
`
`grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
`

**Comment by vanugrah** [comment]
We're running into this issue as well!

**Comment by liguozhong** [comment]
show loki.yaml please

**Comment by lcarbajales** [comment]
Hi @liguozhong!
Thanks for reaching out, do you need the full /config for the deployed components or only need to see the loki.yaml file itself?

**Comment by liguozhong** [comment]
loki.yaml

**Comment by lcarbajales** [comment]
Awesome, let me know if there's anything else i can provide to help analyze this.
[loki-yaml.txt](https://github.com/grafana/loki/files/10123152/loki-yaml.txt)

@vanugrah This might be of your interest as well.

**Comment by liguozhong** [comment]
> Awesome, let me know if there's anything else i can provide to help analyze this. [loki-yaml.txt](https://github.com/grafana/loki/files/10123152/loki-yaml.txt)
> 
> @vanugrah This might be of your interest as well.

```
frontend_worker:
 scheduler_address: ****
 match_max_concurrent: true
```
-->
```
frontend_worker:
 scheduler_address: ****
 match_max_concurrent: true
 grpc_client_config:
   max_send_msg_size: 1.048576e+08
```

add grpc_client_config here

**Comment by lcarbajales** [comment]
Thanks for the response 😄 , I'll give it a try and come back to you, although that's already in the realized config as its the default value as far as i understand.
Here's the current frontend_worker realized config:

`frontend_worker:
  frontend_address: ""
  scheduler_address: ****
  dns_lookup_duration: 3s
  parallelism: 10
  match_max_concurrent: true
  id: ""
  grpc_client_config:
    max_recv_msg_size: 104857600
    max_send_msg_size: 104857600
    grpc_compression: ""
    rate_limit: 0
    rate_limit_burst: 0
    backoff_on_ratelimits: false
    backoff_config:
      min_period: 100ms
      max_period: 10s
      max_retries: 10
    tls_enabled: false
    tls_cert_path: ""
    tls_key_path: ""
    tls_ca_path: ""
    tls_server_name: ""
    tls_insecure_skip_verify: false
`

**Comment by liguozhong** [comment]
max_send_msg_size: 1.048576e+08
   max_send_msg_size: 1.048576e+09
   max_send_msg_size: 1.048576e+10
   max_send_msg_size: 1.048576e+11

**Comment by lcarbajales** [comment]
Hi @liguozhong !
Sorry for the inconvenience, but i don't understand exactly the meaning of the last message, do you mean to try all those 4 values for the `max_send_msg_size`?

Also, it might just be a coincidence, but i found a config value in the frontend component that seems suspicious:
`frontend:
  max_body_size: 10485760
`
It doesn't seem to be documented at all, but that is the default value (notice it's missing a 0 digit) as we are not setting it in loki.yaml

**Comment by liguozhong** [comment]
yes


`caller=scheduler_processor.go:163 org_id=fake msg="response larger than max message size" size=175214367 maxMessageSize=104857600
`

max_send_msg_size: 1.048576e+09
or 
max_send_msg_size: 1.048576e+10

**Comment by lcarbajales** [comment]
Hi @liguozhong !
Thanks for all the help :)
Unfortunately we haven't been able to reproduce it lately, and realized config seems consistent all the way. In any case, we haven't seen the error happen again so it might have just been a very unlikely edge case.
