### ISSUE TITLE
Messages from Azure eventhub (Kafka) does not seem to be consumed by promtail

### ISSUE THREAD

**Issue by oscni** [grafana/loki#7704]
**Describe the bug**
Messages from Azure eventhub (Kafka) does not seem to be consumed. Testing promtail to a local kafka server without TLS or SASL works.

**To Reproduce**
Using kafkacat with the following parameter works:
kafkacat -b XYZ.servicebus.windows.net:9093 -C -t XYZ -X "security.protocol=sasl_ssl" -X "sasl.mechanisms=PLAIN" -X sasl.username='$ConnectionString' -X sasl.password='Endpoint=sb://XYZ.servicebus.windows.net/;SharedAccessKeyName=XYZ;SharedAccessKey=XYZ;EntityPath=XYZ'

Using promtail on the same machine with the following parameters does not seem to work:
    scrape_configs:
    - job_name: kafka
      kafka:
        brokers:
          - XYZ:9093
        topics:
          - XYZ
        group_id: XYZ
        labels:
          job: kafka
        authentication:
          type: sasl
          sasl_config:
            mechanism: PLAIN
            user: $ConnectionString
            password: Endpoint=sb://XYZ.servicebus.windows.net/;SharedAccessKeyName=XYZ;SharedAccessKey=XYZ;EntityPath=XYZ
            use_tls: true
            server_name: XYZ

**Expected behavior**
Expects the messages to be consumed and delivered.

**Environment:**
Kubernetes

**Screenshots, Promtail config, or terminal output**
Another job on the same promtail picking up local log files works. So the delivery from promtail to log backend is verified.
The last log output from promtail is msg="consuming topic" and also the topic name and correct number of partitions. Entering any faulty in the password string makes the connecton fails completely so promtail seems to be able to make a connection and get the correct number of partitions from the kafka server.
Doing a tcpdump shows that the normal TCP and SSL handshake goes ok, but after just a couple of application data packets a new TCP and SSL handshake is started, this continues forever.

Azure recommends following when not receiving any messages. Don't know if that has anything to do with it.
"Make sure that your request.timeout.ms is at least the recommended value of 60000 and your session.timeout.ms is at least the recommended value of 30000."

**Comment by sblancohaivision** [comment]
@oscni I have it working by setting a lower Kafka version (1.0.2.0). Higher versions connect, but do not consume any message.

**Comment by oscni** [comment]
Interesting, I tried with older version than you specified but still what azure supported as minimum version. Also tried with never version but both failed. 1.0.2 however works so now data is flowing :) Many thanks for looking into it!
For future reference if someone does google-fu promtail seems to use sarama go library so the same behavior probably exists there also.
