### ISSUE TITLE
Update go.mod module to v2

### ISSUE THREAD

**Issue by bogdandrutu** [grafana/loki#7728]
See:

```shell
$ go get github.com/grafana/loki@v2.7.0
go: github.com/grafana/loki@v2.7.0: invalid version: module contains a go.mod file, so module path must match major version ("github.com/grafana/loki/v2")
$ go get github.com/grafana/loki/v2@v2.7.0
go: github.com/grafana/loki@v2.7.0: invalid version: module contains a go.mod file, so module path must match major version ("github.com/grafana/loki/v2")
```

**Comment by chaudum** [comment]
Hey @bogdandrutu We are aware of the "broken" behaviour and there has been some discussion around that in https://github.com/grafana/loki/issues/2826

We may consider using a `v3` module path for Loki 3.0, as it was raised here: https://github.com/grafana/loki/issues/7076#issuecomment-1239018974

I'm closing the issue as "duplicate".
