### ISSUE TITLE
logcli --until or --to flag similar to --from=FROM

### ISSUE THREAD

**Issue by Dieterbe** [grafana/loki#774]
logcli has 
```
      --from=FROM        Start looking for logs at this absolute time
```
it would be very useful if there was a corresponding --to flag.

**Comment by adityacs** [comment]
I think this is good to have feature. Even docker logs has this feature. 
@Dieterbe If I get a "yes" to this feature I can work on this and create PR.

**Comment by Kuqd** [comment]
@adityacs there is other issue you can take care of, also join on slack channel if you want to contribute that would make communication easier.

Thanks.
