### ISSUE TITLE
More Precise Log Deletion Options

### ISSUE THREAD

**Issue by thejosephstevens** [grafana/loki#7741]
**Is your feature request related to a problem? Please describe.**
The current log deletion mechanism is too coarse grained. If there is a sensitive value that is logged across many different components (or environments, or in some other way does not align well to individual log streams), then the only existing method for log deletion is to create a label filter for the total set of places where it may appear and call for deletion of all of the associated logs, which may in certain cases be all logs that exist.

**Describe the solution you'd like**
There's two options I can think of:
1. Log deletion with full LogQL support, e.g. `{app=~".+", environment=~".+"} |= "Sensitive value anchor"`, which would go through all log streams and only delete logs matching the full filter (including the text filter), which would be more precise than the existing method, and very easy to compose LogQL queries for. I understand that this would require re-writing block files in-place, which would likely be some mix of hard to implement, and/or slow.
2. The other way I can think of is you run a query like `{app=~".+", environment=~".+"} |= "Sensitive value anchor"`, but rather than running it live through LogCLI or Grafana, you submit it as a POST (or something) to the compactor, and the compactor submits LogQL requests for the full duration of the query to identify all of the places where the offending log can be found, and then generates a set of log deletion queries, using label combinations and tight time bounds to minimize the impact of the log deletion e.g.
```
{environment="staging", app="api"}&start=1652839200&end=1652997600
{environment="prod", app="spark"}&start=1652839000&end=1652997200
{environment="customer-foo", app="frontend"}&start=1652832400&end=1652998900
```

**Describe alternatives you've considered**
Currently the only alternatives I have are:
1. Slowly working my way backwards through time to manually figure out these time windows like method 2 above, and composing a focused log deletion
2. Scaling my Loki cluster to the moon to try and do this querying work all in one shot (this would be a truly massive cluster to not have the query timeout)
3. Just drop all logs

**Additional context**
We have about 83 TiB of logs, it's challenging to try and query all of them in a single LogQL query.

**Comment by michaelkebe** [comment]
I think option 1 is implemented.
Your first alternative could maybe handled with the `max_interval` parameter.

From the docs https://grafana.com/docs/loki/latest/api/#compactor:
> Query parameters:
> * query=<series_selector>: query argument that identifies the streams from which to delete with optional line filters.
> * start=<rfc3339 | unix_seconds_timestamp>: A timestamp that identifies the start of the time window within which entries will be deleted. This parameter is required.
> * end=<rfc3339 | unix_seconds_timestamp>: A timestamp that identifies the end of the time window within which entries will be deleted. If not specified, defaults to the current time.
> * max_interval=< duration > : The maximum time period the delete request can span. If the request is larger than this value, it is split into several requests of <= max_interval. Valid time units are s, m, and h.
>
> ...

To handle large deletes these configuration parameters could help. From https://grafana.com/docs/loki/latest/configuration/#compactor.

```
# The total amount of worker to use to delete chunks.
# CLI flag: -boltdb.shipper.compactor.retention-delete-worker-count
[retention_delete_worker_count: <int> | default = 150]

# The max number of delete requests to run per compaction cycle.
# CLI flag: -boltdb.shipper.compactor.delete-batch-size
[delete_batch_size: <duration> | default = 70]
```

**Comment by thejosephstevens** [comment]
Oh, wow, you're totally right!
>The query parameter can also include filter operations. For example query={foo="bar"} |= "other" will filter out lines that contain the string “other” for the streams matching the stream selector {foo="bar"}.

I wonder if that changed recently, I could've sworn only label stream selectors were permitted.

Thanks for responding, I'll go ahead and close!

**Comment by michaelkebe** [comment]
Yeah, you are right. It was introduced in Version 2.6.0, I think.

https://github.com/grafana/loki/releases/tag/v2.6.0
