### ISSUE TITLE
Documentation about use gateway with ingress

### ISSUE THREAD

**Issue by raxidex** [grafana/loki#7761]
The page https://grafana.com/docs/loki/latest/installation/helm/concepts/#gateway says:
```
The gateway must be enabled if an Ingress is required, since the Ingress exposes the gateway only
```

But the values.yaml says:
```
# Use either this ingress or the gateway, but not both at once.
# If you enable this, make sure to disable the gateway.
# You'll need to supply authn configuration for your ingress controller.
```

Which configuration should we follow?

Thanks, Marcelo.

**Comment by hervenicol** [comment]
You need an ingress, but there's 2 different ingresses that can be created from this helm chart:
`.ingress.enabled` => won't create the gateway
`.gateway.ingress.enabled` => will create an ingress for the gateway

The gateway requires the second one to be exposed. And is incompatible with the first one.
Se both paragraphs are right, but deserve some additional info.

**Comment by raxidex** [comment]
thanks for the clarification
