### ISSUE TITLE
Promtail 2.7.0 won't start on OpenWRT 22.03 x86/64.

### ISSUE THREAD

**Issue by bodyscape** [grafana/loki#7764]
**Describe the bug**
Promtail won't start on OpenWRT 22.03 x86/64.
When i try to run promtail with this cmd : **./promtail-linux-amd64**
I have this error : **-ash: ./promtail-linux-amd64: not found**
Really weird because the file is there and have the execute right like the loki-linux-amd64.

**Expected behavior**
I think it's suppose to start because Loki, Logcli and loki-canary work with the same version 2.7.0.

**Environment:**
OpenWrt 22.03.2 r19803-9a599fee93 / LuCI openwrt-22.03 branch git-22.304.65171-ec905e6
Linux Kernel 5.10.146
Promtail 2.7.0

**Screenshots, Promtail config, or terminal output**
![Capture](https://user-images.githubusercontent.com/30115568/203672264-1bf9d517-3949-4a57-84d9-06b56e4ca8fe.JPG)

**Comment by dannykopping** [comment]
@bodyscape can you please send a directory listing of this directory?
By definition this can't be a promtail issue because the promtail binary is not being found, but I'll see if I can help.

**Comment by bodyscape** [comment]
@dannykopping 

I think your right, i just don't understand.  ;) Thanks for the help.

![Capture](https://user-images.githubusercontent.com/30115568/203784009-aaaac204-e73f-4bac-b770-f47a63287a4e.JPG)
![Capture2](https://user-images.githubusercontent.com/30115568/203784011-e5731171-f1b3-45cc-8908-c53ad60db020.JPG)

**Comment by dannykopping** [comment]
Only thing I can think of here is to run `strace`:

```bash
$ strace -f -o /tmp/strace ./promtail-linux-amd64
```

Post the contents of `/tmp/strace` (bearing in mind there may be sensitive details), and I'll see if anything stands out.

**Comment by bodyscape** [comment]
No strace file is created if a run promtail or loki.

![Capture](https://user-images.githubusercontent.com/30115568/203803492-f3d5f301-7776-4cd1-a704-228ff9427b4a.JPG)

**Comment by dannykopping** [comment]
Try run `echo $$` to get the pid of this pseudo-terminal (A).
Then, in another shell (B), run `strace -f -o /tmp/strace -p <the pid>`. Once you have that running, run `./promtail-linux-amd64` in (A).

**Comment by bodyscape** [comment]
Sorry the file was there the first time.. my bad!!!

where i run  strace -f -o /tmp/strace ./promtail-linux-amd64 : 
5629  execve("./promtail-linux-amd64", ["./promtail-linux-amd64"], 0x7ffc2a674e18 /* 15 vars */) = -1 ENOENT (No such file or directory)
5629  +++ exited with 1 +++


When i run the 2 terminal like you said :
3590  restart_syscall(<... resuming interrupted read ...>) = 1
3590  read(0, ".", 1)                   = 1
3590  writev(1, [{iov_base=".", iov_len=1}, {iov_base=NULL, iov_len=0}], 2) = 1
3590  poll([{fd=0, events=POLLIN}], 1, -1) = 1 ([{fd=0, revents=POLLIN}])
3590  read(0, "/", 1)                   = 1
3590  writev(1, [{iov_base="/", iov_len=1}, {iov_base=NULL, iov_len=0}], 2) = 1
3590  poll([{fd=0, events=POLLIN}], 1, -1) = 1 ([{fd=0, revents=POLLIN}])
3590  read(0, "p", 1)                   = 1
3590  writev(1, [{iov_base="p", iov_len=1}, {iov_base=NULL, iov_len=0}], 2) = 1
3590  poll([{fd=0, events=POLLIN}], 1, -1) = 1 ([{fd=0, revents=POLLIN}])
3590  read(0, "r", 1)                   = 1
3590  writev(1, [{iov_base="r", iov_len=1}, {iov_base=NULL, iov_len=0}], 2) = 1
3590  poll([{fd=0, events=POLLIN}], 1, -1) = 1 ([{fd=0, revents=POLLIN}])
3590  read(0, "\t", 1)                  = 1
3590  mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f867820b000
3590  open("./", O_RDONLY|O_LARGEFILE|O_CLOEXEC|O_DIRECTORY) = 3
3590  fcntl(3, F_SETFD, FD_CLOEXEC)     = 0
3590  getdents64(3, 0x7f867820e6f8 /* 6 entries */, 2048) = 208
3590  stat("./promtail-linux-amd64", {st_mode=S_IFREG|0777, st_size=84666752, ...}) = 0
3590  getdents64(3, 0x7f867820e6f8 /* 0 entries */, 2048) = 0
3590  close(3)                          = 0
3590  munmap(0x7f867820b000, 4096)      = 0
3590  writev(1, [{iov_base="\r\33]0;root@Security: /mnt/sda3/pr"..., iov_len=99}, {iov_base=NULL, iov_len=0}], 2) = 99
3590  poll([{fd=0, events=POLLIN}], 1, -1) = 1 ([{fd=0, revents=POLLIN}])
3590  read(0, "\n", 1)                  = 1
3590  writev(1, [{iov_base="", iov_len=0}, {iov_base="\n", iov_len=1}], 2) = 1
3590  ioctl(0, SNDCTL_TMR_START or TCSETS, {B38400 opost isig icanon echo ...}) = 0
3590  rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1 RT_2], [], 8) = 0
3590  rt_sigprocmask(SIG_BLOCK, ~[], ~[KILL STOP RTMIN RT_1 RT_2], 8) = 0
3590  fork()                            = 5633
3590  rt_sigprocmask(SIG_SETMASK, ~[KILL STOP RTMIN RT_1 RT_2], NULL, 8) = 0
3590  rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
3590  setpgid(5633, 5633)               = 0
3590  wait4(-1,  <unfinished ...>
5633  gettid()                          = 5633
5633  rt_sigprocmask(SIG_SETMASK, ~[KILL STOP RTMIN RT_1 RT_2], NULL, 8) = 0
5633  rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
5633  getpid()                          = 5633
5633  setpgid(0, 5633)                  = 0
5633  ioctl(10, TIOCSPGRP, [5633])      = 0
5633  rt_sigaction(SIGTSTP, {sa_handler=SIG_DFL, sa_mask=~[RTMIN RT_1 RT_2], sa_flags=SA_RESTORER, sa_restorer=0x7f867826ceba}, NULL, 8) = 0
5633  rt_sigaction(SIGTTOU, NULL, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=0}, 8) = 0
5633  rt_sigaction(SIGTTOU, {sa_handler=SIG_DFL, sa_mask=~[RTMIN RT_1 RT_2], sa_flags=SA_RESTORER, sa_restorer=0x7f867826ceba}, NULL, 8) = 0
5633  rt_sigaction(SIGINT, {sa_handler=SIG_DFL, sa_mask=~[RTMIN RT_1 RT_2], sa_flags=SA_RESTORER, sa_restorer=0x7f867826ceba}, NULL, 8) = 0
5633  rt_sigaction(SIGTERM, {sa_handler=SIG_DFL, sa_mask=~[RTMIN RT_1 RT_2], sa_flags=SA_RESTORER, sa_restorer=0x7f867826ceba}, NULL, 8) = 0
5633  rt_sigaction(SIGQUIT, {sa_handler=SIG_DFL, sa_mask=~[RTMIN RT_1 RT_2], sa_flags=SA_RESTORER, sa_restorer=0x7f867826ceba}, NULL, 8) = 0
5633  execve("./promtail-linux-amd64", ["./promtail-linux-amd64"], 0x7f867829c190 /* 15 vars */) = -1 ENOENT (No such file or directory)
5633  writev(2, [{iov_base="-ash: ", iov_len=6}, {iov_base=NULL, iov_len=0}], 2) = 6
5633  writev(2, [{iov_base="./promtail-linux-amd64: not foun"..., iov_len=33}, {iov_base=NULL, iov_len=0}], 2) = 33
5633  writev(2, [{iov_base="", iov_len=0}, {iov_base="\n", iov_len=1}], 2) = 1
5633  exit_group(127)                   = ?
5633  +++ exited with 127 +++
3590  <... wait4 resumed>[{WIFEXITED(s) && WEXITSTATUS(s) == 127}], WSTOPPED, NULL) = 5633
3590  --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=5633, si_uid=0, si_status=127, si_utime=0, si_stime=0} ---
3590  rt_sigreturn({mask=[]})           = 5633
3590  wait4(-1, 0x7ffd0546d28c, WNOHANG|WSTOPPED, NULL) = -1 ECHILD (No child process)
3590  ioctl(10, TIOCSPGRP, [3590])      = 0
3590  ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
3590  ioctl(0, SNDCTL_TMR_START or TCSETS, {B38400 opost -isig -icanon -echo ...}) = 0
3590  ioctl(0, TIOCGWINSZ, {ws_row=38, ws_col=133, ws_xpixel=0, ws_ypixel=0}) = 0
3590  geteuid()                         = 0
3590  open("/etc/passwd", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
3590  fcntl(3, F_SETFD, FD_CLOEXEC)     = 0
3590  mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f867820b000
3590  fcntl(3, F_SETFD, FD_CLOEXEC)     = 0
3590  read(3, "root:x:0:0:root:/root:/bin/ash\nd"..., 1024) = 374
3590  lseek(3, -343, SEEK_CUR)          = 31
3590  close(3)                          = 0
3590  munmap(0x7f867820b000, 4096)      = 0
3590  uname({sysname="Linux", nodename="Security", ...}) = 0
3590  getcwd("/mnt/sda3/promtail", 192) = 19
3590  uname({sysname="Linux", nodename="Security", ...}) = 0
3590  geteuid()                         = 0
3590  writev(1, [{iov_base="\33]0;root@Security: /mnt/sda3/pro"..., iov_len=72}, {iov_base=NULL, iov_len=0}], 2) = 72
3590  poll([{fd=0, events=POLLIN}], 1, -1

**Comment by dannykopping** [comment]
Thanks for this.
OK, I suspect a problem with your disk perhaps. Try executing promtail with the full (not relative) path?
Try deleting the file and downloading it again
Try checking the sha256 against https://github.com/grafana/loki/releases/download/v2.7.0/SHA256SUMS

If none of those work, then I don't really have many other ideas right now

**Comment by bodyscape** [comment]
I already try the full path and downloading again serveral time. Also test other version. don't work.

I try to validate the checksum like you said, they are the same.

Do you know if there are minimum requirement to run it?

**Comment by dannykopping** [comment]
Not really, just a couple hundred MB of RAM.
In any case, it wouldn't manifest in this way.

This looks like an OS/hardware issue, not one with Promtail, so unfortunately I think I'll have to close this issue - but please do let us know if you find the issue! If you find evidence that it is a Promtail issue, we can certainly reopen this.

Best of luck @bodyscape

**Comment by bodyscape** [comment]
Thanks for you help. :) @dannykopping

**Comment by bodyscape** [comment]
@dannykopping 

Anyway idea for the dynamic link??

![Capture](https://user-images.githubusercontent.com/30115568/203847646-c3fd1379-0798-4207-abe6-7cb4b5892020.JPG)

**Comment by dannykopping** [comment]
Oh interesting... that seems odd.
@trevorwhitney do you know anything about this? Did we change the way these binaries are built for 2.7?

**Comment by bodyscape** [comment]
i build from the source and i add this flag like the upper line. Now it's work flawless on my OpenWRT. :)
![Capture](https://user-images.githubusercontent.com/30115568/203862515-63f9c023-8f18-4db5-a224-6c959374df88.JPG)

**Comment by vlad-diachenko** [comment]
Hey @bodyscape . it looks like we already had such an issue ([here](https://github.com/grafana/loki/pull/809#issuecomment-516766456)) ;) 
I will figure out a few questions about the binaries build process to see if we can build a static binary with enabled CGO... I will keep you updated.

**Comment by trevorwhitney** [comment]
@dannykopping we did change the build for loki a bit, using `go` directly instead of `gox`, and adding `-trimpath` flags, and maybe the flag stuff carried over for `promtail` as well?

**Comment by vlad-diachenko** [comment]
> @dannykopping we did change the build for loki a bit, using `go` directly instead of `gox`, and adding `-trimpath` flags, and maybe the flag stuff carried over for `promtail` as well?

hey @trevorwhitney . we still use `gox` to build binaries that are published to github.  https://github.com/grafana/loki/blob/main/Makefile#L260

**Comment by vlad-diachenko** [comment]
hey @bodyscape . do you have any updates? did [this comment](https://github.com/grafana/loki/pull/809#issuecomment-516766456) help to you ? 
Also, taking into account [this comment](https://github.com/grafana/loki/pull/1072#discussion_r1033586676), it looks like we can not build fully static binary.

**Comment by bodyscape** [comment]
Hey @vlad-diachenko. It's ok, like i said. I made my custom build with the config i change. it's work great since. 

Thanks for your help.
