### ISSUE TITLE
Loki Canary - Fluentbit

### ISSUE THREAD

**Issue by lswith** [grafana/loki#7775]
**Is your feature request related to a problem? Please describe.**
I am trying to use Loki Canary from inside an AWS ECS Cluster. The AWS ECS Cluster only allows fluentbit as a means to send logs to Loki. I'd like to use the Loki Canary in this scenario, with fluentbit.

The issue is that fluentbit sends it's logs in the format:
```
container_id="47409985af6fed03fa2444c0dbacb7fe951eb38ed255d8552944a76b5769b5a1" container_name="/ecs-loki-canary-task-18-lokicanary-cca5e8c1fb8fa6ade901" source="stdout" log="1669367942122441008 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp"
```

But Loki canary expects the format to be:
```
1669368302116394757 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp
```

**Describe the solution you'd like**
I'd love if I could choose a label for Loki canary to parse, i.e. the "logs" label.

**Describe alternatives you've considered**
I've looked into trying to get fluentbit to stop messing with the log format, and just send the "log" output, but it seems that fluentbit is always going to send a structured log to Loki.

**Additional context**

**Comment by kavirajk** [comment]
@lswith this looks like something that should be possible or to be fixed on the agent side (fluentbit). Seems to be too specific use case to support it on `loki-canary` itself. 

From the Loki canary perspective, it just expects same log lines that it writing and it's up to agent to control the additional metadata

Also there is new mode in `loki-canary` called push mode (`-push` flag enables it) that enable loki-canary to push logs it is generating into Loki directly without needing to writ to file and scrape by agent like flutentbit. 

May be use try that and see if that works for you? (NOTE: It's very new and may expect some rough edges).
