### ISSUE TITLE
Add gauge for limits_config.max_concurrent_tail_requests

### ISSUE THREAD

**Issue by nicoche** [grafana/loki#7794]
**Is your feature request related to a problem? Please describe.**

We recently had an issue with our loki instance where we hit the max number of concurrent tail requests, as configured by `limits_config.max_concurrent_tail_requests`. We want to setup an alert to know when we're getting close the limit.

We noticed that there is a gauge to track the number of active tail requests (`loki_querier_tail_active`). However, there is no gauge which tracks the current limit; hence, our prometheus alert uses a hardcoded limit. Every time we will change the limit, we will need to change the alert so it takes into account the new limit.

**Describe the solution you'd like**

A gauge with a value == `limits_config.max_concurrent_tail_requests` would be great. Then, we can setup the alert once and never touch it ever again.

**Describe alternatives you've considered**

N/A

**Additional context**

Let me know if that looks like a good idea to you. I'm happy to provide a PR.

**Comment by chaudum** [comment]
Hey @nicoche what you are describing is done by the `overrides-exporter`. The overrides-exporter reads the values from the config and runtime config and exposes them as metrics. It can be run as a single instance alongside the Loki installation.
https://grafana.com/docs/loki/latest/operations/overrides-exporter/

You can query your limits as such:

```
loki_overrides{user="your-tenant", limit_name="max_concurrent_tail_requests"}
or
loki_overrides_defaults{limit_name="max_concurrent_tail_requests"}
```

The metric `loki_overrides` uses the per-tenant value from the `overrides.yaml`, `loki_overrides_defaults` uses the cluster-wide default value.

**Comment by nicoche** [comment]
Thanks for your answer! It's great that there is a mechanism for that, sorry I have not found it by myself.

I understand that the overrides_exporter is configured by the `runtime_config` block. Is that correct?
If yes, do you happen to know how well this works with Loki's helm chart? It seems that there is currently no way to configure the `runtime_config` block from the values file.
