### ISSUE TITLE
Case-insensitive regex line filters with leading or trailing wildcards only match uppercase results

### ISSUE THREAD

**Issue by kelnage** [grafana/loki#7837]
**Describe the bug**
When a query contains a line filter regular expression with leading or trailing wildcards `.*` and the case-insensitive flag set `(?i)`, Loki only appears to match the uppercase version of the string.

**To Reproduce**
You can see the differing behaviour with these two examples on LogQL analyser: [with wildcards](https://grafana.com/docs/loki/latest/logql/analyzer/?query=%7C%7E+%60%28%3Fi%29.*test.*%60&line%5B%5D=msg%3D%22lower+case%22+target%3D%22test%22&line%5B%5D=msg%3D%22upper+case%22+target%3D%22TEST%22), [without wildcards](https://grafana.com/docs/loki/latest/logql/analyzer/?query=%7C%7E+%60%28%3Fi%29test%60&line%5B%5D=msg%3D%22lower+case%22+target%3D%22test%22&line%5B%5D=msg%3D%22upper+case%22+target%3D%22TEST%22)

1. Started Loki (version on Grafana Cloud, [v9.2.7-0f96ed148c (0f96ed148c)](https://github.com/grafana/grafana/blob/main/CHANGELOG.md))
2. Started Promtail (HEAD-1b627d8) to tail Windows System Log data and ran `attrib +s` then `attrib +S` on two files
3. Query: `{job="windows"} |~ "(?i).*\\ \\+s.*"`

**Expected behavior**
Two results should have come back, one log entry containing ` +s` and another containing ` +S`. Only the latter was returned.

**Environment:**
 - Infrastructure: Grafana Cloud

**Comment by adityacs** [comment]
Fixed by https://github.com/grafana/loki/pull/8037
