### ISSUE TITLE
How to connect Loki as my DataSource inside the Grafana deployed via `Kueb-Prometheus-stack`?

### ISSUE THREAD

**Issue by imoisharma18** [grafana/loki#7843]
Hi there, 

I have deployed the https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack helm chart inside my `monitoring` namespace. And, I have deployed the https://artifacthub.io/packages/helm/grafana/loki helm chart under the same namespace. 

I am not facing any issue w/ `Prometheus` connection for seeing the metrics but the Loki data source complains about this error

```
Unable to fetch labels from Loki (Failed to call resource), please check the server logs for more details
```

The URL which I am putting for Loki in the DataSource is this: http://loki-read.monitoring.svc.cluster.local:3100/

Can anyone tell me what I am missing?

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
