### ISSUE TITLE
Helm chart of loki-read simple scalable lacks HPA (HorizontalPodAutoscaler)

### ISSUE THREAD

**Issue by adambro** [grafana/loki#7864]
**Describe the bug**
The HPA (HorizontalPodAutoscaler) attributes are mentioned in [values](./production/helm/loki/values.yaml) and [reference](./docs/sources/installation/helm/reference.md) docs, as `read.autoscaling.enabled` for example.

However there's no reference of any HorizontalPodAutoscaler kind nor those attributes in **read** part of chart. The gateway part is has HPA explicitly as an example.

**To Reproduce**
Look at the chart files or try to deploy HPA for **read** Loki pods.

**Expected behavior**
Set HorizontalPodAutoscaler kind or provide an alternative to scale `loki-read` StatefulSet.

Or maybe the HPA was there, bug got removed for some reason and only docs are not being cleaned up?

**Environment:**
 - Infrastructure: Kubernetes, simple-scalable deployment
 - Deployment tool: Helm via FluxCD in my case

**Screenshots, Promtail config, or terminal output**
N/A

**Comment by ahmedzidan** [comment]
Can't wait to see that, this is very important for us currently.

**Comment by joereyna** [comment]
This would be an easy PR.  I might do it.

**Comment by adambro** [comment]
@joereyna I think PR #8684 already provides solution.
