### ISSUE TITLE
loki retention is only 1h

### ISSUE THREAD

**Issue by korenlev** [grafana/loki#7875]
grafana-loki helm chart

**To Reproduce**
1. deploy loki helm chart: https://github.com/bitnami/charts/tree/main/bitnami/grafana-loki/#installing-the-chart
2. use only default settings
3. look at log retention after several hours - only the last 1h logs are kept

**Expected behavior**
Config per https://grafana.com/docs/loki/latest/operations/storage/retention/ should be operational (like 3h retention)

Kubernetes, using grafana, grafana-loki, promtail

all settings to defaults as the above.
others reporting the same issue and getting no resolution:
 https://github.com/grafana/loki/issues/6513
https://github.com/bitnami/charts/issues/10824

we are rolling out grafana cloud and this bug effects our decision tree

**Comment by korenlev** [comment]
this is a documented limitation: https://github.com/bitnami/charts/tree/main/bitnami/grafana-loki/#limitation
But this is huge upset in the default deployment !
I think there was a release that supported local.
There are use cases where local filesystem has more then enough storage and is faster then object storage, so might be desirable.
For what it's worth in my case this was a blocker for using loki.

**Comment by MichelHollands** [comment]
@korenlev The Loki project now has an official helm chart. This provides a [single binary](https://grafana.com/docs/loki/latest/installation/helm/install-monolithic/) installation which supports the [filesystem](https://grafana.com/docs/loki/latest/installation/helm/configure-storage/). Would this be an option?

Feel free to reopen the ticket if you have more questions.
