### ISSUE TITLE
logstash with loki as output is not populating kubernetes labels on grafana.

### ISSUE THREAD

**Issue by jijeshvu07** [grafana/loki#7881]
**Describe the bug**
I have configured loki+logstash kubernetes cluster with input as file /var/log/** 
Grafana is able to connected to the datasource but grafana is unable to find the labels.

**To Reproduce**
inside logstash.yaml 
```
 input {
         file {
            id => "varlog"
            path => ["/var/log/**"]
            type => "var log"
            start_position => "beginning"
          }
      }
       filter {
        if [kubernetes] {
          mutate {
            add_field => {
              "container_name" => "%{[kubernetes][container][name]}"
              "namespace" => "%{[kubernetes][namespace]}"
              "pod" => "%{[kubernetes][pod][name]}"
            }
            replace => { "host" => "%{[kubernetes][node][name]}"}
          }
        }
        mutate {
          remove_field => ["tags"]
        }
      }
      output {
        loki {
          url => "http://loki-loki-distributed-distributor.loki-benchmark.svc.cluster.local:3100/loki/api/v1/push"
        }
      }
```

**Expected behavior**
   Grafana should be show the labels eg: pods, namespace, container_name 

**Environment:**
 -  Kubernetes
 - Deployment tool: helm

**Screenshots, Grafana UI**

<img width="699" alt="Screenshot 2022-11-25 at 4 06 24 PM" src="https://user-images.githubusercontent.com/3931019/206406042-6ae655ad-8902-4e83-bdb5-a99dcfd8b4bf.png">

**Comment by adityacs** [comment]
@jijeshvu07 Do you see `failed payload` message when you run logstash in debug mode? 

Also, could you please use `stdout` plugin in output and paste the results here?

**Comment by jijeshvu07** [comment]
@adityacs  Logs are coming there are no issues with that. The real problem with this running in kubernetes, It does not find the kubernetes metadata like pods, namespace and container names.

**Comment by jijeshvu07** [comment]
> @jijeshvu07 Do you see `failed payload` message when you run logstash in debug mode?
> 
> Also, could you please use `stdout` plugin in output and paste the results here?

Logs are coming there are no issues with that. The real problem with this running in kubernetes, It does not find the kubernetes metadata like pods, namespace and container names.

**Comment by adityacs** [comment]
@jijeshvu07 By default, we don't consider the nested fields in loki-output plugin. Reason being, nested fields can be deep and parsing and converting it to flat labels will create lot of labels which would increase cardinality unnecessarily. Also, logstash itself has `filter` stage and plugins like `mutate` which can handle this. We don't want to duplicate that in loki-output plugin code.
