### ISSUE TITLE
how to set deletion mode in helm-chart? (Use deletion_mode per tenant configuration instead warning)

### ISSUE THREAD

**Issue by m-wack** [grafana/loki#7884]
Hello, I am using the helm-chart in single binary mode with this config line:

compactor:
  deletion_mode: filter-and-delete

However I am getting a warning:

boltdb.shipper.compactor.deletion-mode has been deprecated and will be ignored. I found out to use deletion_mode per tenant configuration instead. But I cannot find any documentation on what I need to set in my values.yaml for this value to be applied. I am not using multi-tenancy but just a single tenant (the default 'fake' tenant, which is set by auth_enabled: false).

Can someone help me where to provide delete_mode in my values to get them applied? I need to delete lots of log data.

Thanks in advance.

**Comment by Bak3y** [comment]
I'm also attempting to set this via helm, and I've tried both `compactor.deletion_mode` and `limits_config.deletion_mode` and in both cases the setting appears to be ignored, resulting in a running config of `filter-only`

**Comment by rgroothuijsen** [comment]
If I understand the documentation correctly, it's now specified as an override in a separate runtime configuration YAML. The filename of this file is specified in your global config under `runtime_config.file`, and in this file you'd have an `overrides.deletion_mode` key.

**Comment by rgroothuijsen** [comment]
Ah, you're right, seems it works a little differently when configured through values.yaml. I haven't tested it entirely yet, but at least this values.yaml was accepted as a valid configuration:
```
loki:
  runtimeConfig:
    overrides:
      fake:
        deletion_mode: "filter-and-delete"
```
In this case, `fake` is the default tenant ID, which you'd have to change to the actual tenant ID that you want to configure.

**Comment by m-wack** [comment]
FWIW this seems to work, so if it gets properly documented I think this can be closed.

**Comment by BaskiGIT** [comment]
@m-wack : Have you been enable to view the runtime config which you set?

When I set it to 'disabled' I don't seem to be having a way to view the runtime config applied to loki.

**Comment by m-wack** [comment]
@BaskiGIT I am using 'filter-and-delete' and that's showing up under the /config endpoint. Haven't tested 'disabled' sorry.

**Comment by ccruz2** [comment]
Hi @m-wack how exactly do you request for logs deletion?

**Comment by m-wack** [comment]
> Hi @m-wack how exactly do you request for logs deletion?

Not sure what the exact question here is.
We just set this config:

```
loki:
  runtimeConfig:
    overrides:
      TENANT:
        deletion_mode: "filter-and-delete"
```

We are using default 2 week retention and it seems to work, no logs older than 2w exist.

**Comment by gespi1** [comment]
how do i set it for all tenants, setting this for all tenants is repetitive no?

**Comment by pgillich** [comment]
```
loki:
  limits_config:
    deletion_mode: filter-and-delete
```
