### ISSUE TITLE
Docs feedback: /installation/helm/install-scalable/index.md

### ISSUE THREAD

**Issue by djryanj** [grafana/loki#7892]
There is a typo: "Consult the [Reference](https://grafana.com/docs/loki/latest/installation/helm/reference) for configuring otehr storage providers."

The word "otehr" should be "other".

The phrase: "It is not possible to run the scalable mode with the fulesystem storage."

Contains a typo; "fulesystem" should be "filesystem".

**Comment by MichelHollands** [comment]
Already fixed
