### ISSUE TITLE
`topk(499,  …)` won't resolve `maximum of series (500) reached` error

### ISSUE THREAD

**Issue by samjewell** [grafana/loki#7932]
**Describe the bug**

I ran `count_over_time({job=~".+"}[5m])` over a large Loki instance (Grafana Ops), and got the error:
```
maximum of series (500) reached for a single query
```

Naturally thought I could fix it with a `topk(500, …)`
But it doesn't work (even with `499` ) see screenshot. As a user, topk should work in this situation :disappointed:

<img width="461" alt="image (6)" src="https://user-images.githubusercontent.com/2903904/207557535-518b4dc1-74e9-46c6-ae08-043c9f1130ec.png">

**To Reproduce**
See above

**Expected behavior**
When I wrap in Topk, I should see the error go away, and the number of series specified get returned

**Environment:**
A Hosted-Loki tenant on GrafanaCloud

# Notes 
Discussed on Grafana private Slack here: https://raintank-corp.slack.com/archives/C9T1FLN9K/p1670865169766989

**Comment by chaudum** [comment]
When you use a `topk(k, ...)` in an instant query, then you get the top k results for a particular point in time.
However, when used in a range query, `topk(k, ...)` produces the top k results for each point in time (each step of the range). This can lead to much more than the expected k results, because the top may change over time.

**Comment by samjewell** [comment]
Ah fantastic. Thanks a lot @chaudum that's super clear.

I guess I'll close this issue for now, as at least I understand the limitation and can work around it (and others will be able to do the same). I still find this somewhat unintuitive, but I'm not sure what we could improve here, or where.

**Comment by Hades32** [comment]
>  and can work around it (and others will be able to do the same)

but how??? 😅

**Comment by sukreshmanda123** [comment]
@chaudum I am trying to learn the Loki querying. What is the difference between Instant query and Range query?
