### ISSUE TITLE
`sort_desc` missing from LogQL

### ISSUE THREAD

**Issue by samjewell** [grafana/loki#7933]
**Describe the bug**
`sort_desc` is missing from LogQL. It's present in PromQL.

As a user I expect LogQL to be a strict superset of PromQL.

**Environment:**
Hosted Loki instance on GrafanaCloud

**Comment by liguozhong** [comment]
hi, do you have an example of how to use `sort` and `sort_desc` in logql that you expect to run? This can help contributors to better complete this feature.

for example:
`sort(rate(({app=~"foo|bar"} |~".+bar")[1m])) without (app) 
`

**Comment by samjewell** [comment]
I'm often in the role of administering a Loki instance, and trying to manage the total consumption. I'm using queries such as this one:
```
sum(count_over_time({namespace=~".+"}[1m])) by (namespace)
```

I want to wrap it in `sort_desc` to I can see the largest consumers / worst offenders at the top of the list. Ie.
```
sort_desc(sum(count_over_time({namespace=~".+"}[1m])) by (namespace))
```

**Comment by liguozhong** [comment]
thanks,This logql is very helpful for us to complete the PR correctly
