### ISSUE TITLE
What is the difference between totalLinesSent and totalLinesProcessed?

### ISSUE THREAD

**Issue by MarjanJordanovski** [grafana/loki#7952]
Hello,

I see that loki is giving me different results for _totalLinesProcessed_ and _totalLinesSent_. I wonder why is that, as it's not clear to me from the docs. 
If _totalLinesProcessed_ is the overall number of log lines that are processed, why are not all those lines sent, and not only some number of lines that are counted with _totalLinesSent_?

//not sure if this info is relevant, but query that I'm using looks something like this:
query={instance="test", service="test"}&limit=5000&start=2022-12-15T16:30:09.560Z&end=2022-12-15T16:48:09.570Z

Thanks!

**Comment by MichelHollands** [comment]
@MarjanJordanovski 

TotalLinesProcessed is the number of lines read from the store (AWS S3) and from the ingesters for a request. Log lines are stored in chunks. TotalLinesProcessed includes the headers of those chunks as well in addition to the decompressed log lines in the chunks. 

TotalLinesSent is the number of lines sent by the ingesters. These are recent log lines still stored in the ingester memory. By default an ingester will hold 2 hours of log lines before storing them in the store.

Hope that helps. Please reopen the ticket if you need more information.
