### ISSUE TITLE
docker command is wrong!

### ISSUE THREAD

**Issue by liy-cn** [grafana/loki#7976]
**Screenshots, Promtail config, or terminal output**

<img width="886" alt="image" src="https://user-images.githubusercontent.com/2853829/208640231-2959534d-4966-46c6-ab4d-e3381ed5df83.png">

the correct command is 
```
docker pull grafana/loki:2.7.1
docker pull grafana/promtail:2.7.1
```

**Comment by jeschkies** [comment]
Thanks. I've update the release notes.
