### ISSUE TITLE
Grafana/loki failed Failed to load log volume for this query

### ISSUE THREAD

**Issue by kona125** [grafana/loki#7979]
**Describe the bug**
I have one loki instance and I am sending multiple promtail instances. I was doing some testing and then I decided to change my jobs to different name. Also I manually deleted all the chunks from local storage. Now  I have this error in grafana: 
Failed to load log volume for this query
rpc error: code = Unknown desc = open /loki/chunks/ZmFrZS9iYjFlZTllNGU2OWUxN2RkOjE4NTJmNWI3YjZiOjE4NTJmNWI4MmZkOjUxOGY4Mjhm: no such file or directory

So know I have also some old job names in grafana. Also my loki-config.yml.
# (default configuration)
auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h       # Any chunk not receiving new logs in this time will be flushed
  max_chunk_age: 1h           # All chunks will be flushed when they hit this age, default is 1h
  chunk_target_size: 1048576  # Loki will attempt to build chunks up to 1.5MB, flushing first if chunk_idle_period or max_chunk_age is reached first
  chunk_retain_period: 30s    # Must be greater than index read cache TTL if using an index cache (Default index read cache TTL is 5m)
  max_transfer_retries: 0     # Chunk transfers disabled
  wal:
    dir: /loki/wal
compactor:
  working_directory: /loki/boltdb-shipper-compactor
  shared_store: filesystem
  compaction_interval: 5m
  retention_enabled: false
 # retention_delete_delay: 2h
 # retention_delete_worker_count: 150

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb:
    directory: /loki/index
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

limits_config:
#  retention_period: 182d
 # per_stream_rate_limit: 512M
#  per_stream_rate_limit_burst: 1024M
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_burst_size_mb: 16
  ingestion_rate_mb: 16

chunk_store_config:
  max_look_back_period: 744h

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules-temp
  alertmanager_url: localhost
  ring:
    kvstore:
      store: inmemory
  enable_api: true

I tried not to have retention, in case it could delete all the job name I didn't want.

**To Reproduce**
I don't know how to reproduce it correctly. 

**Expected behavior**
I just expected my new jobs with the different names.

**Environment:**
 - Infrastructure: Simple

**Screenshots, Promtail config, or terminal output**
![log-volume](https://user-images.githubusercontent.com/121103390/208669232-cd06b783-c52b-4a97-9ec3-2337fd3926c4.PNG)

I don't know hot to fix this.
Problem 1: I don't want the old job names.
Problem 2: Failed to load log volume for this query
rpc error: code = Unknown desc = open /loki/chunks/ZmFrZS9iYjFlZTllNGU2OWUxN2RkOjE4NTJmNWI3YjZiOjE4NTJmNWI4MmZkOjUxOGY4Mjhm: no such file or directory

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.

**Comment by withinboredom** [comment]
It'd be great if search engines could index those things... time to go further down the rabbit hole.
