### ISSUE TITLE
Mixed UTC and Local timezone on "logcli query"

### ISSUE THREAD

**Issue by pracucci** [grafana/loki#798]
If `loki` is running on a system with the timezone different than UTC, then the output of `logcli query` will display log entries with mixed timezone (UTC and Local).

The reason is that `logcli query` will query both the ingesters and the store. The ingesters internally store the timestamps with a `time.Time` in `UTC` timezone, while the storage reads the entries timestamp from chunk blocks in the `Local` timezone.

In particular, the parsing of a log entry timestamp is done in `pkg/chunkenc/gzip.go` at `bufferedIterator.Next()`:
```
si.cur.Timestamp = time.Unix(0, ts)
```

`time.Unix()` parses an unix epoch timestamp in UTC timezone returning a `time.Time` in the `Local` timezone.

I would like to work on an improvement, and I'm suggesting the following:
1. Always enforce UTC inside loki, so changing the timestamp parsing into `si.cur.Timestamp = time.Unix(0, ts).UTC()`
2. Add an option to `logcli query` to specify the timezone with which the user prefers the timestamps (can be `UTC` or `Local`) and then enforce it while formatting the output

What's your take?

**Comment by Kuqd** [comment]
Sounds good to me ! Specially if you have spotted disparity in the current code when using Loki.
