### ISSUE TITLE
High Availability on Local PC

### ISSUE THREAD

**Issue by Manoharan-NMS** [grafana/loki#7987]
How to configure High Availability for Loki in Local Setup. (Without Cloud).

**Comment by chaudum** [comment]
You may submit questions in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

**NOTE: All questions submitted as issues will be closed.**
