### ISSUE TITLE
Running Loki as Cluster

### ISSUE THREAD

**Issue by tfchan0** [grafana/loki#799]
Hi, wonder if Loki supports running in cluster?  For example, running multiple instance of Loki.  If it's supported, would be great if can point me to some configuration/doc.  Thanks!

**Comment by sh0rez** [comment]
Yes, take a look at the docs please:
https://github.com/grafana/loki/blob/master/docs/operations.md#scalability

**Comment by tfchan0** [comment]
Hi, sorry that not familiarize with ksonnet.  I was looking at using helm.  Based on the blog, do I have to run ingestor, etc independently?  Or I can scale up the Loki itself (with Helm)?  

For example, can I run multiple Loki pods under the headless service and Promtail push the log to the service (and behind it will push to one of the Loki instance)?  Or Promtail needs to aware of all Loki pods and push to each one of them independently.

Thanks.

**Comment by sh0rez** [comment]
There is not really a Loki. Loki consists of Ingesters, Queriers, etc.

The Helm chart currently runs a single one of each as a single process. 

You will NEVER have a cluster of these single process instances. You will have to run each component individually, but you can scale individually then as well.
