### ISSUE TITLE
Promtail hostPath mount

### ISSUE THREAD

**Issue by inbarpatashnik** [grafana/loki#8020]
Hi :) 
I’ve been trying to collect pods logs in openshift with Promtail, but it wouldn’t work for me  because of permissions problems with the hostPath in the config file.
Is it possible to replace the hostPath mounts to one I don’t need high permissions to?

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
