### ISSUE TITLE
Docs: Fix broken links

### ISSUE THREAD

**Issue by osg-grafana** [grafana/loki#8033]
See https://docs.google.com/spreadsheets/d/1WyZE-U8lFKWk4kDa8AP_g1pAu38CY_-4mHyAM-Se0p0/edit.

**Comment by osg-grafana** [comment]
Removing myself because I do not have the bandwidth for this at the moment.

**Comment by osg-grafana** [comment]
@knylander-grafana, is this indeed done? If so, please close this issue.

**Comment by JStickler** [comment]
Closing, as 404 dashboard currently shows no broken links in Loki.
