### ISSUE TITLE
Cannot use extracted variable inside a regular expression filter

### ISSUE THREAD

**Issue by madmurl0c** [grafana/loki#8058]
Hey everyone, I recently started using Loki and think I found a bug (maybe I just didn't do it right).

**Describe the bug**
It seems like it is not possible to use a values that was extracted using `| json` inside a regular expression filter.

**To Reproduce**
```
topk(10, sum by (http_referer) (count_over_time({container_name="...", source="stdout"} | json | http_referer != '' and http_referer !~ '.*?$http_host.*?' | __error__="" [$__interval])))
```

**Expected behavior**
I would expect this to filter out every line where `http_referer` includes the value of `http_host` but it doesn't.

Example:
Data:
```
{http_referer: "https://google.com/", http_host="app.company.com"},
{http_referer: "https://app.company.com/", http_host="app.company.com"}
```

Expected output:
```
{http_referer: "https://google.com/", http_host="app.company.com"}
```

Current output:
```
{http_referer: "https://google.com/", http_host="app.company.com"},
{http_referer: "https://app.company.com/", http_host="app.company.com"}
```

It works when I manually type `app.company.com` instead of `$http_host` inside the query like so
```
topk(10, sum by (http_referer) (count_over_time({container_name="...", source="stdout"} | json | http_referer != '' and http_referer !~ '.*?app.company.com.*?' | __error__="" [$__interval])))
```

**Environment:**
Self hosted Docker stack
```
  loki:
    image: grafana/loki:2.7.1
    ...

  grafana:
    image: grafana/grafana:9.3.1
    ...
```

**Screenshots, Promtail config, or terminal output**
- see above

I hope you can help me with that, if you need any more info feel free to ask :)

**Comment by MichelHollands** [comment]
@madmurl0c We don't support the `$label_name` to add a label inside a string. It's unlikely that will be added. There doesn't seem to be a way to do what you want at the moment. I tried creating a new label with label format (`label_format reg = ".*?$http_host.*?" | http_referer =~ reg` but that doesn't work either.

Why do have ? after `.*` by the way in the regular expression?

**Comment by MichelHollands** [comment]
Feel free to reopen this if you have more questions.
