### ISSUE TITLE
Helm: Use image tag for version labels in k8s resources

### ISSUE THREAD

**Issue by der-eismann** [grafana/loki#8077]
**Describe the bug**
The helm chart for this project creates Kubernetes resources with a `app.kubernetes.io/version` label. The value for this version is the `AppVersion` of the chart, which currently is pinned to v2.7.0. However v2.7.1 has been out for a month and if I set this as the image tag in the values.yaml, all the resources still have `app.kubernetes.io/version: "2.7.0"`, which is incorrect. So shouldn't the image tag be used for the version label, if set?

**To Reproduce**
1. Create minimal values.yaml with  
```yaml
loki:
  image:
    tag: 2.7.1
   ```
2. Execute helm template with `helm template loki -f values.yaml grafana/loki`
3. Verify that resources have `app.kubernetes.io/version: "2.7.0"`

**Expected behavior**
Kubernetes labels should have the actual version, not the one pinned for the chart. If not, helm charts should be released with each software release simultaneously.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**

**Comment by jeschkies** [comment]
Yes. I think you are correct. Would you mind proposing the change in a pull request?

**Comment by der-eismann** [comment]
> Yes. I think you are correct. Would you mind proposing the change in a pull request?

Sure, just opened #8135 :slightly_smiling_face:
