### ISSUE TITLE
promtail start error  "invalid regex stage config: could not compile regular expression: error parsing regexp" 

### ISSUE THREAD

**Issue by yangyubin1** [grafana/loki#8082]
**Describe the bug**

We use Promtail for collecting logs , when we use regex  like (?=xxx)  ， after save the config file ,we find we fail to restart promtail
and log shows error "**could not compile regular expression: error parsing regexp**"

Promtail Config：

server:
  http_listen_port: 9080
  grpc_listen_port: 0
  http_server_read_timeout: 20s
  http_server_write_timeout: 10s
  grpc_server_max_recv_msg_size: 1048576
  grpc_server_max_send_msg_size: 1048576
  grpc_server_max_concurrent_streams: 50
  log_level: info

positions:
  filename: /app/docker/promtail/application-positions.yaml
  sync_period: 10s
target_config:
  sync_period: 10s
clients:
  - url: http://127.0.0.1/loki/api/v1/push
    tenant_id: test
scrape_configs:
  - job_name: consul
    consul_sd_configs:
      - server: 127.0.0.1:8500
        services: [loki-exporter127.0.0.1]
    relabel_configs:
      - separator: ;
        regex: __meta_consul_service_metadata_(.+)
        replacement: $1
        action: labelmap
    pipeline_stages:
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}'
          max_wait_time: 3s
      - regex:
          expression: '(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}) (?P<level>[A-Z]+) .*'
      - labels:
          level:
      - timestamp:
          source: timestamp
          location: 'Asia/Shanghai'
          format: '2006-01-02 15:04:05.999'
      - drop:
          older_than: 1h
      - regex:
          source: filename
          expression: '(?P<hf_pod_ip>((25[0-5]|2[0-4]\d|((1\d{2})|([1-9]?\d)))\.){3}(25[0-5]|2[0-4]\d|((1\d{2})|([1-9]?\d))))'
      - labels:
          hf_pod_ip:
      - regex:
          source: filename
          **### expression: '(?P<env1>(test(?=/)))'**   # this regex  promtail not support
      - labels:
          env1: 

When I start promtail,  the log shows below , so the promtail fail to start

level=error ts=2023-01-10T07:22:44.316259008Z caller=main.go:115 msg="error creating promtail" error="failed to make file target manager: invalid regex stage config: could not compile regular expression: error parsing regexp: invalid or unsupported Perl syntax: `(?=`"

**Expected behavior**
When search how to solve this problem on the Internet， Many Articles suggest  we should use regexp2  not regexp

regexp2 download---->    **go get -u github.com/dlclark/regexp2**

Regexp can not support  Complex regular expressions，like below

![图片](https://user-images.githubusercontent.com/26540663/211496860-1ddaae78-4ff5-42b5-b07d-105fbc5fab61.png)

**Environment:**
   Alibaba ECS

hope your imformation，thx ^ ^

**Comment by MichelHollands** [comment]
@yangyubin1 We only support the default Go regexes. This means `(?=re` is not supported as indicated in the table you provide. We are unlikely to change this as the performance of the regex library is important. Because of this we have been making performance fixes to the standard Go regex library. I should also note that the https://github.com/dlclark/regexp2 library is meant to support .NET regular expressions whereas we only support the Go regular expressions.
