### ISSUE TITLE
#7500 ( [Helm] Add support for azure blob storage) is incomplete.

### ISSUE THREAD

**Issue by Tazmaniac** [grafana/loki#8097]
**Describe the bug**
The code in production/helm/loki/templates/_helpers.tpl
```
{{/* Predicate function to determin if custom ruler config should be included */}}
{{- define "loki.shouldIncludeRulerConfig" }}
{{- or (not (empty .Values.loki.rulerConfig)) (.Values.minio.enabled) (eq .Values.loki.storage.type "s3") (eq .Values.loki.storage.type "gcs") }}
{{- end }}

```
Should be I think 

```
{{/* Predicate function to determin if custom ruler config should be included */}}
{{- define "loki.shouldIncludeRulerConfig" }}
{{- or (not (empty .Values.loki.rulerConfig)) (.Values.minio.enabled) (eq .Values.loki.storage.type "s3") (eq .Values.loki.storage.type "gcs") (eq .Values.loki.storage.type "azure") }}
{{- end }}
```
**To Reproduce**
helm deployment with azure storage and no personalized ruler config does not generate a config map with azure storage config for the ruler.

**Expected behavior**
Using azure type storage should unlock ruler config generation.
RulerConfig for azure storage type is properly prepared in the template helper (part of #7500 commit).

**Environment:**
 - Infrastructure: AKS
 - Deployment tool: helm

**Comment by jeschkies** [comment]
Thanks for find out. Would you mind creating a pull request with the change you've described?

**Comment by Tazmaniac** [comment]
I hope it is done correctly. This is my first PR on github :-)
