### ISSUE TITLE
Ksonnet Library

### ISSUE THREAD

**Issue by jdbaldry** [grafana/loki#81]
Can't wait to get playing with this. Would you be interested in a ksonnet library a la prometheus-ksonnet, or does it already exist?

**Comment by gouthamve** [comment]
Hi, I'm in charge of the ksonnet for Loki. Keep an eye on: https://github.com/grafana/loki/tree/master/ksonnet and https://github.com/grafana/loki/tree/master/mixin

Only the promtail ksonnet works for now but I'll have everything working tomorrow. Please keep an eye out!

**Comment by jdbaldry** [comment]
Hey Goutham! I probably should have had a look around the code before I jumped in haha! 

Will try it out super soon, KubeCon permitting :)

**Comment by jdbaldry** [comment]
Actually a bit of an aside, are there plans for an update to the ksonnet tool from ks 0.8.0?

**Comment by rverma-nikiai** [comment]
Hi all, as per the announcement of team behind ksonnet shutting down the project, many cncf projects (e.g. kubeflow) are migrating to solutions like kustomize. A rationale for the same can be found here https://docs.google.com/document/d/1SVm-xffIdWiMYkl_nQO5C6HHK46NWkfDGPDUL5ukeME/edit#heading=h.frwscropjuwb.

**Comment by metalmatze** [comment]
There is currently now real thread to the way that ksonnet is used in this project and many others, who only use ksonnet-lib. I've recently updated ksonnet to add ksonnet.beta.4 which is generated from Kubernetes 1.14.
