### ISSUE TITLE
Promtail: Crashing when attempts to log to /tmp

### ISSUE THREAD

**Issue by srolija** [grafana/loki#810]
**Describe the bug**
When there is Kubernetes networking error, pod crashes because it is unable to log to `/tmp` directory inside the docker container running on Kubernetes.

**To Reproduce**
I don't have exact steps; but it seems that other libraries had the same issue as well https://github.com/containous/traefik/issues/1785. 

**Expected behavior**
It should log to stderr instead of crashing.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, promtail config, or terminal output**
```
level=info ts=2019-07-29T12:44:53.127010214Z caller=kubernetes.go:191 component=discovery discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-07-29T12:44:53.131183645Z caller=server.go:120 http=[::]:3101 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2019-07-29T12:44:53.131411077Z caller=main.go:49 msg="Starting Promtail" version="(version=master-4439828, branch=master, revision=4439828)"
level=warn ts=2019-07-29T12:45:09.246241186Z caller=logging.go:49 msg="GET /ready (500) 76.182µs Response: \"Not ready: Unable to find any logs to tail. Please verify permissions, volumes, scrape_config, etc.\\n\" ws: false; Accept-Encoding: gzip; Connection: close; User-Agent: kube-probe/1.15; "
level=warn ts=2019-07-29T12:45:19.243888649Z caller=logging.go:49 msg="GET /ready (500) 52.969µs Response: \"Not ready: Unable to find any logs to tail. Please verify permissions, volumes, scrape_config, etc.\\n\" ws: false; Accept-Encoding: gzip; Connection: close; User-Agent: kube-probe/1.15; "
E0729 12:45:23.133612       1 reflector.go:134] github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:282: Failed to list *v1.Pod: Get https://172.17.0.1:443/api/v1/pods?limit=500&resourceVersion=0: dial tcp 172.17.0.1:443: i/o timeout
E0729 12:45:23.133612       1 reflector.go:134] github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:282: Failed to list *v1.Pod: Get https://172.17.0.1:443/api/v1/pods?limit=500&resourceVersion=0: dial tcp 172.17.0.1:443: i/o timeout
log: exiting because of error: log: cannot create log: open /tmp/promtail.promtail-xqstd.unknownuser.log.ERROR.20190729-124523.1: read-only file system
```

**Possible Solutions**
Judging by the issue liked above and the solution https://github.com/containous/traefik/issues/1785#issuecomment-312529617, as a workaround it should be possible to avoid this bug by setting the flag before Prometheus Client is instantiated (transitive dependency of Cortex). Alternatively it should be possible to avoid the issue by mounting tmpfs volume to the pod itself.

**Comment by steven-sheehy** [comment]
It would crash regardless eventually if it couldn't connect to Kubernetes, so you should fix that problem first. I don't think mounting a volume just because a logging library is erroneously writing to a file is a good solution.

Looks like some projects like Kubernetes and [prometheus](https://github.com/prometheus/prometheus/pull/4931) addressed this by swapping glog with its api compatible [glog-gokit](https://github.com/kubermatic/glog-gokit).

**Comment by cyriltovena** [comment]
I'm also happy to follow the same concept as they did here:

https://github.com/containous/traefik/pull/1817/files

Easy enough ! Help is appreciated for that one !

**Comment by srolija** [comment]
This issue is still open.
