### ISSUE TITLE
loki docker driver plugin panic runtime error in docker-ce 19.03.1

### ISSUE THREAD

**Issue by chewrocca** [grafana/loki#812]
**Describe the bug**
Loki Docker driver plugin panic runtime error in dockerd logs in docker-ce 19.03.1.  After upgrading to docker-ce 19.03.1, one of the containers (promregator) abruptly stops logging and enters into an unstable state.  Upon looking at the dockerd logs at the same time that promregator enters the unstable state, Loki docker driver receives the following in the dockerd logs:  

```Jul 29 12:59:10 dockerhost1 dockerd: time="2019-07-29T12:59:10-05:00" level=error msg="panic: runtime error: invalid memory address or nil pointer dereference" plugin=725a5e112aa83fd14899d04a8aa68cefd0ee26257
cf4347a0e1c51b17663971e
Jul 29 12:59:10 dockerhost1 dockerd: time="2019-07-29T12:59:10-05:00" level=error msg="[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x153d1b3]" plugin=725a5e112aa83fd14899d04a8aa68cefd0ee2625
7cf4347a0e1c51b17663971e
Jul 29 12:59:10 dockerhost1 dockerd: time="2019-07-29T12:59:10-05:00" level=error plugin=725a5e112aa83fd14899d04a8aa68cefd0ee26257cf4347a0e1c51b17663971e
Jul 29 12:59:10 dockerhost1 dockerd: time="2019-07-29T12:59:10-05:00" level=error msg="goroutine 166 [running]:" plugin=725a5e112aa83fd14899d04a8aa68cefd0ee26257cf4347a0e1c51b17663971e
Jul 29 12:59:10 dockerhost1 dockerd: time="2019-07-29T12:59:10-05:00" level=error msg="main.consumeLog(0xc0003f8b40)" plugin=725a5e112aa83fd14899d04a8aa68cefd0ee26257cf4347a0e1c51b17663971e
Jul 29 12:59:10 dockerhost1 dockerd: time="2019-07-29T12:59:10-05:00" level=error msg="\t/go/src/github.com/grafana/loki/cmd/docker-driver/driver.go:127 +0x2c3" plugin=725a5e112aa83fd14899d04a8aa68cefd0ee2625
7cf4347a0e1c51b17663971e
Jul 29 12:59:10 dockerhost1 dockerd: time="2019-07-29T12:59:10-05:00" level=error msg="created by main.(*driver).StartLogging" plugin=725a5e112aa83fd14899d04a8aa68cefd0ee26257cf4347a0e1c51b17663971e
Jul 29 12:59:10 dockerhost1 dockerd: time="2019-07-29T12:59:10-05:00" level=error msg="\t/go/src/github.com/grafana/loki/cmd/docker-driver/driver.go:95 +0x673" plugin=725a5e112aa83fd14899d04a8aa68cefd0ee26257
cf4347a0e1c51b17663971e
Jul 29 12:59:10 dockerhost1 dockerd: time="2019-07-29T12:59:10.787122134-05:00" level=error msg="Error streaming logs: error decoding log message: unexpected EOF" container=b966bd44d84cd0059ac43df594111a59041
53d3ae3483078db549607f14db213 method="(*Daemon).ContainerLogs" module=daemon
Jul 29 12:59:10 dockerhost1 dockerd: time="2019-07-29T12:59:10.787470474-05:00" level=debug msg="end logs (<nil>)" container=b966bd44d84cd0059ac43df594111a5904153d3ae3483078db549607f14db213 method="(*Daemon).
ContainerLogs" module=daemon
```

**To Reproduce**
1. Install Loki Docker plugin 
2. Deploy Promregator 0.5.7 with the following in Docker compose file:
```
x-default-opts: &default-opts
  init: true
  logging:
    driver: "loki"
    options:
      loki-url: ${LOKI_URL:?err}
```
3. Watch Promregator logs with `docker logs -f <PromregatorContainerID>` and dockerd logs.  Prometheus calls Promregator metrics endpoints, `docker logs` abrupty returns to prompt and Promregator enters an usable state (only reboot appears to kill the container).  

**Expected behavior**
Not to panic 

**Environment:**
 - Infrastructure: Tested in Docker Swarm running on RedHat 7 on VMware and tested with Docker swarm running on Centos 7 running on VirtualBox (laptop). 
 - Deployment tool: Docker Swarm with Docker Compose files for deployment

**Screenshots, promtail config, or terminal output**
see log snippet above.

**Comment by cyriltovena** [comment]
It was working before ? but upgrading to docker docker-ce 19.03.1 triggered this ? What was the version before ?

I can add a fail safe there.

**Comment by chewrocca** [comment]
Yes, this was previously working. This works without issue in 18.09.6 but fails with 18.09.7+.

**Comment by cyriltovena** [comment]
Seems that this commit actually triggers something new that wasn't happening before. I'll send a fix asap.

**Comment by cyriltovena** [comment]
Should be fixed with the latest version (currently building in our CI), let me know how it goes @chewrocca .

Thank you so much for the report ! ❤️

**Comment by chewrocca** [comment]
Thank you so much for the super quick fix and attention to this issue!  I'll test this out.

**Comment by chewrocca** [comment]
Tested successfully in 19.03.1 and 18.09.7.  Thanks again!
