### ISSUE TITLE
Grafana in loki-stack helm chart  has the bug parse error at line 1, col 3

### ISSUE THREAD

**Issue by alexcpn** [grafana/loki#8136]
Installed latest loki-stack via helm and immediately hit upon this grafan bug; Basically not able to search in the logs!

Grafan bug:-  parse error at line 1, col 3 https://github.com/grafana/grafana/issues/54535

helm list -n loki
```
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
loki    loki            1               2023-01-13 15:09:38.9407809 +0530 IST   deployed        loki-stack-2.8.9        v2.6.1
```
Grafana version in the above stack has the bug
```
grafana/grafana:8.3.5`
```

Please update grafana to the latest or to the version which works; Please see details here https://github.com/grafana/grafana/issues/61472

**Comment by DylanGuedes** [comment]
Hey thank you for your report.
I'm closing the issue since `loki-stack` isn't on this repo anymore, is deprecated, and wasn't maintained by Grafana. I recommend you to either create your issue under https://github.com/grafana/helm-charts or to migrate to `grafana/loki` chart instead.
