### ISSUE TITLE
Helm: Expose single binary service configuration in values

### ISSUE THREAD

**Issue by sapslaj** [grafana/loki#8146]
**Is your feature request related to a problem? Please describe.**
The Service used in single-binary mode in the Helm chart does not expose any configuration options the same way the Service for the gateway does.

**Describe the solution you'd like**
The same options that `gateway.service` has available should be configurable for the single-binary Service via `values.yaml`. Something like the following should be possible:

```yaml
singleBinary:
  service:
    type: NodePort # default is ClusterIP
    nodePort: 31000 # default is null
```

**Describe alternatives you've considered**
An optionally enableable secondary Service with all of the configuration options exposed in `values.yaml`. It seems like overkill given that the ingress will point to the already existing service anyway.

**Additional context**
Having these options exposed is very helpful for dev setups where something like a simple `NodePort` is much simpler for accessing Loki than going through an ingress. This is possible to do with the simple-scalable configuration since the gateway's service can be configured to be of type `NodePort` or whatever you want. However the single-binary configuration is more desirable on resource-constrained setups like those used for dev environments.

One potentially weird thing is that the single-binary Service has a gRPC port in addition to the HTTP port. I'm not sure how much it will harm the ergonomics to have both a `.service.port` and a `.service.grpcPort`.

**Comment by mateuszdrab** [comment]
Hi @sapslaj 

I came across this issue as I was looking to find out if anyone reported/requested that the gateway feature is made compatible with single binary mode.

I tried to deploy a small loki instance (which uses local storage instead of s3) but I wanted to re-use as many of the values (since I use Flux).
My main instance uses the gateway but the single binary deployment doesn't support that, so I'd have to duplicate a number of settings to get this to work.

If the gateway supported single binary, would that solve your issue as well?

**Comment by sapslaj** [comment]
@mateuszdrab Yep, adding gateway support to single binary would solve the issue, since then I can just configure the gateway's service to be a `NodePort` or `LoadBalancer` or whatever.

**Comment by trevorwhitney** [comment]
I propose we instead enable the gateway for single binary: https://github.com/grafana/loki/issues/8269, as this will lead to less exposed configuration and more consistency between the different modes. This will also help those hoping to run an HA single binary configuration #8185.

**Comment by mateuszdrab** [comment]
I agree too @trevorwhitney

**Comment by sapslaj** [comment]
I agree as well. Let's go with #8269.

**Comment by trevorwhitney** [comment]
https://github.com/grafana/loki/pull/8284
