### ISSUE TITLE
Setup multiple Loki instances in different clusters for combined monitoring.

### ISSUE THREAD

**Issue by junoriosity** [grafana/loki#8148]
We are currently running multiple k8s clusters and we would like to have logging for all of them. Hence it would be helpful if the following aspects are fulfilled:

- Can we persist Loki/Promtail logs to the same S3 bucket?
- Is it possible to have a look at them and query them in one Grafana instance?

If this is possible, could you give me some easy examples of how to set it up via helm charts like (https://artifacthub.io/packages/helm/grafana/loki-stack)? It would be great if you could help me here! 🙂

**Comment by jeschkies** [comment]
You can send all logs to the same Loki cluster. Say you have a Grafana Cloud account all logs could go there labeled with the cluster they are coming from.

**Comment by junoriosity** [comment]
@jeschkies Many thanks for getting back to me.

However, since I am absolutely new to Loki and Promtail, could you help me, how exactly I do things for cluster A, B and C? That would be awesome.

**Comment by chaudum** [comment]
Hey @junoriosity If you have general questions, pleases submit them in any of the following ways:

- On our [community forum](https://community.grafana.com/c/grafana-loki/41)
- In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

**NOTE: Github is meant for bug reports and feature requests; questions submitted as issues will be closed.**
