### ISSUE TITLE
Docs feedback: /installation/helm/install-scalable/index.md

### ISSUE THREAD

**Issue by flavono123** [grafana/loki#8149]
https://grafana.com/docs/loki/latest/installation/helm/install-scalable/
A typo in "To deploy Loki in scalable mode:" > 3:

```diff
Consult the [Reference](https://grafana.com/docs/loki/latest/installation/helm/reference) for configuring 
-otehr
+other
storage providers.
```

**Comment by jeschkies** [comment]
Thanks. Would you mind creating a Pull Request?

**Comment by flavono123** [comment]
Oh, it was fixed already.
https://github.com/grafana/loki/pull/7676
I got this trying to make a PR. Never mind.
