### ISSUE TITLE
[Website LOKI/Question] Update information about schedule/planning for release on the loki website.

### ISSUE THREAD

**Issue by Yivan** [grafana/loki#815]
Hello,

It would be nice to have more information on the loki website about when a stable release is planning or at least some clues.

It recently go from alpha to beta, but knowing stable release horizon would be of great help (end yer 2019, mid -2020, etc ?).
When do you think loki will be released ?

This issue can be pinned and renamed "Planned date for release" too, so any people going on github could find this info on this issue too. 

I would like to ask too, is the version beta enough stable for a production usage ?

Best regards.

**Comment by Yivan** [comment]
[disable stale]
Any answer please ?

**Comment by cyriltovena** [comment]
Hello, yes this is planned, we will first rework documentation then work on a website.

**Comment by Yivan** [comment]
@cyriltovena Thanks !

**Comment by cyriltovena** [comment]
few months.

**Comment by GrafanaWriter** [comment]
Given that this is quite stale, and [contributor and community information](https://grafana.com/docs/loki/latest/community/) is provided as part of the Loki docs, I will close this issue.
