### ISSUE TITLE
It returns "500 - grpc: received message larger than max (12948666 vs. 4194304)" when try to post logs to Loki server

### ISSUE THREAD

**Issue by JackJiaJJ** [grafana/loki#8154]
**Describe the bug**

Loki version:   0.45.1 (loki-distributed-0.45.1.tgz)

When I use Loki push api to post logs to Loki server, it returns below:

level=warn ts=2023-01-14T14:08:12.883956704Z caller=logging.go:72 traceID=77f6ea78a866de32 orgID=fake msg="POST /loki/api/v1/push (500) 258.28899ms Response: \"rpc error: code = ResourceExhausted desc = grpc: received message larger than max (13102563 vs. 4194304)\\n\" ws: false; Accept-Encoding: gzip; Connection: close; Content-Length: 14770169; Content-Type: application/json; Forwarded: for=129.41.87.3;host=loki-demo-020.platform.dev.automation.ibm.com;proto=https; User-Agent: Go-http-client/1.1; X-Forwarded-For: 129.41.87.3; X-Forwarded-Host: loki-demo-020.platform.dev.automation.ibm.com; X-Forwarded-Port: 443; X-Forwarded-Proto: https; "

**To Reproduce**
1. deploy loki with helm, loki version is loki-distributed-0.45.1.tgz
2. pull logs from ibm cis (pull logs every 1 minute) and then post them to loki server
3. get below output:
   rpc error: code = ResourceExhausted desc = grpc: received message larger than max (12948666 vs. 4194304)

**Expected behavior**
I expect I can post the log which is bigger than 4 M successfully to Loki server

**Environment:**
 - Infrastructure: K8s
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

Below is part of my configuration file:

  config: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_server_max_recv_msg_size: 104857600
      grpc_server_max_send_msg_size: 104857600

    distributor:
      ring:
        kvstore:
          store: memberlist

    memberlist:
      join_members:
        - {{ include "loki.fullname" . }}-memberlist
    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
      chunk_idle_period: 30m
      chunk_block_size: 262144
      chunk_encoding: snappy
      chunk_retain_period: 1m
      max_transfer_retries: 0
      wal:
        dir: /var/loki/wal

    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_cache_freshness_per_query: 10m
      split_queries_by_interval: 15m
      ingestion_rate_strategy: local
      ingestion_rate_mb: 15
      ingestion_burst_size_mb: 24
      retention_period: 744h

**Comment by chaudum** [comment]
@JackJiaJJ You are using a very old version of the Helm chart (0.45.x - current is 0.69.x) and therefore Loki as well (2.4.x - current is 2.7.x).

Loki 2.4.x still had some limitations regarding max request size in place, which have been removed in the latest version.

**Comment by JackJiaJJ** [comment]
@chaudum thanks a lot for your response ! I will give a try with latest Helm chart (Loki）
