### ISSUE TITLE
Fluent-plugin-grafana-loki: Ruby version 3.x not supported

### ISSUE THREAD

**Issue by drbugfinder-work** [grafana/loki#8195]
We found out, that the newest gem version (1.2.19 [- https://my.diffend.io/gems/fluent-plugin-grafana-loki/1.2.18/1.2.19](https://my.diffend.io/gems/fluent-plugin-grafana-loki/1.2.18/1.2.19#d2h-004177)) cannot be installed with Ruby version 3.x. 
We are actively using the output plugin by replacing the out_loki.rb file and couldn't find any incompatibilities to Ruby 3.x. 

We assume, that this dependency limitation was just a mistake. 

https://github.com/grafana/loki/blob/cf23194d05d33105958f9e1ef70da3ed9717a81c/clients/cmd/fluentd/fluent-plugin-grafana-loki.gemspec#L16

**Comment by chaudum** [comment]
Hey @drbugfinder-work It was less a mistake than the fact that Ruby 3.x was not released yet when we wrote the plugin. Maybe we were just overly cautious about incompatibility with major version releases.
I am not a Ruby guy, so do you mind testing it with Ruby 3.x and open a PR with the dependency change?

**Comment by drbugfinder-work** [comment]
Hi @chaudum,

As I wrote, we are using this plugin with Ruby 3.x in many instances for more than one year with high workload and without any issues. But with the changes in the last version, the possibility to upgrade is blocked now (unless we do manual changes). So I would either suggest to do some testing on your side and change the component dependencies to support Ruby 3.x or (not so nice solution) revert the component dependency back to support all Ruby versions.

**Comment by drbugfinder-work** [comment]
Thank you very much! I'll give it a try to install.
