### ISSUE TITLE
Pipeline stages tooling

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#820]
The YAML configuration is quite hard to get right and the feedback loop is horrible.

It would great to have a tool that validates, lint and explains this configuration.

Cherry on the top that would be neat to be able to test with some real log line.

I’m thinking about building a small web ui container, we could also host it at Grafana so our users wouldn’t need to use docker at all. But first we should simply promtail as a cli.

/cc @slim-bean

**Comment by slim-bean** [comment]
one version of this I've seen with other tools and would like to do with promtail is to run the binary with a flag to your config file and something like `-stdin` where it doesn't tail files but just parses log lines from stdin and prints out how it would have been processed

**Comment by slim-bean** [comment]
when we figure out a Loki website I think having a hosted config validator as you describe would be fantastic

**Comment by pracucci** [comment]
> Cherry on the top that would be neat to be able to test with some real log line.

@cyriltovena May the experiment done in https://github.com/pracucci/lokitool be of any interest to be backported to this repo?

**Comment by cyriltovena** [comment]
Yeah for sure

**Comment by pracucci** [comment]
@cyriltovena How would you name the tool once backported to the `grafana/loki` repo? Should be integrated into `logcli` or as a separate tool?

**Comment by valmack** [comment]
> > Cherry on the top that would be neat to be able to test with some real log line.
> 
> @cyriltovena May the experiment done in https://github.com/pracucci/lokitool be of any interest to be backported to this repo?

I would also be happy to help with adding a vscode plugin for this (if that is of interest)

**Comment by cyriltovena** [comment]
> > > Cherry on the top that would be neat to be able to test with some real log line.
> > 
> > 
> > @cyriltovena May the experiment done in https://github.com/pracucci/lokitool be of any interest to be backported to this repo?
> 
> I would also be happy to help with adding a vscode plugin for this (if that is of interest)

Sure is !

Promtail now support --dry-run so you could use that.
