### ISSUE TITLE
Object Storage - Local Index, Cloud Chunks

### ISSUE THREAD

**Issue by Serrvosky** [grafana/loki#828]
Is it possible to use local Boltdb as a index storage and Scaleway as object storage for chunks?

**Comment by cyriltovena** [comment]
Does scaleway is an object storage like s3 ? It is possible but you need to a new storage integration this is in cortex.

**Comment by adityacs** [comment]
@Serrvosky Any storage service which has s3 compatible API can be used as Object storage. Please refer [s3](https://github.com/mizeng/loki/blob/ce980305d90dd17d05c23df51cddb3c3c673778d/docs/operations.md) section in the doc.
In case scaleway doesn't support s3 API, a new storage should be added in cortex to support scaleway as mentioned by @cyriltovena

**Comment by cyriltovena** [comment]
If you really want scaleway, please do open an issue on cortex.

Thanks !
