### ISSUE TITLE
TestGZIPCompression skipped

### ISSUE THREAD

**Issue by pracucci** [grafana/loki#829]
The `TestGZIPCompression` in `pkg/chunkenc/gzip_test.go` is skipped because missing the fixture file `NASA_access_log_Aug95` (nice name, BTW).

Looking at the file history, the test is there since the beginning https://github.com/grafana/loki/pull/10.

@gouthamve may you elaborate a bit more on the purpose of that test (if you remember)? I would be glad to submit a PR to make it work, if you see a value in keeping it (and making it run).

**Comment by cyriltovena** [comment]
This was more a of proof concept hacking test. I think there is test testing compression and decompression if not you could add then but we should not use a file.
