### ISSUE TITLE
"logcli query --tail" doesn't print any historic log until the first tailed log is ingested

### ISSUE THREAD

**Issue by pracucci** [grafana/loki#833]
**Describe the bug**
When you run `logcli query --tail` with a `--from` you will get historical logs first and then new logs tailed from ingesters. However, the historical logs are not printed until the first tailed log arrive from any ingester.

**To Reproduce**
1. Started loki `master` version
2. Started promtail `master` version to tail `/tmp/test.json`
3. `echo "test" >> /tmp/test.json`
4. Run `./logcli query --addr="http://localhost:3100" '{type="test"}' --tail --from="2019-08-01T00:00:00Z"`
5. The "test" log won't be displayed until another `echo "test" >> /tmp/test.json` will be issued

**Expected behavior**
Historical logs should be displayed immediately, even if no new logs are tailed.

**Root cause**
The tailing is implemented in `Querier.Tail()`, which starts tailing on all ingesters as well as will issue a `logproto.QueryRequest`. Stream and query iterators are merged together and passed to a new instance of `Tailer`, where the `Tailer.next()` method gets the next `logproto.Entry` (if any).

However, the `Tailer.next()` does:
```
if t.openStreamIterator.Len() == 0 || !time.Now().After(t.openStreamIterator.Peek().Add(t.delayFor)) || !t.openStreamIterator.Next() {
    return false
}
```

but `t.openStreamIterator.Len()` is `0` until the first `t.openStreamIterator.Push()` is called by `pushTailResponseFromIngester()` (when the first tailed log arrives).

Why? Because `t.openStreamIterator` is an instance of `heapIterator`, which has `Len()` returning `0` until the first `Next()` is called, due to how the "prenext" is implemented internally. From my perspective, it's an `heapIterator` bug and a possible solution (which fixed this issue) would be this one:
https://github.com/grafana/loki/compare/master...pracucci:fix-history-querying-on-tail

I would like to gather some feedback if the proposed solution makes sense or breaks any design contract made by `heapIterator` (unfortunately code doc is very poor), before proceeding adding tests and submitting a PR.

**Comment by pracucci** [comment]
@cyriltovena May you share some thoughts or ping someone who can share some light on the `heapIterator` expected behaviour, please?

**Comment by cyriltovena** [comment]
No the heapIterator is fine the problem is more on the usage within the tailing package.

The heapIteror contains a list of EntryIterator, each of them are pre-fetch to be able to compare top lvl entries and decide which one should be the next one and which one is a duplicate.

In case of duplicate found the EntryIterator is advance before being place back in the the heap.

**Comment by cyriltovena** [comment]
Ho yes I look at your code this is safe to add ! and yep it should fix the problem.
