### ISSUE TITLE
Compactor deleted all the index structure from S3 after retention_enabled change

### ISSUE THREAD

**Issue by danielrosa-zh** [grafana/loki#8359]
**Describe the bug**
During a compactor configuration change to be able to delete log entries, following this [procedure](https://grafana.com/docs/loki/latest/operations/storage/logs-deletion/), compactor deleted all our index folders from S3, so due this we are not able to search old data.

**To Reproduce**
1. Started Loki Distributed using version 2.6
2. Configure compactor settings as below, the previous value was `false`

`    compactor:
         retention_enabled: true
         deletion_mode: filter-and-delete
`

**Expected behavior**
Loki index folders remain as is on S3

**Environment:**
 - Infrastructure: EKS
 - Loki Version: loki-distributed-0.55.1	2.6.1

**Logs**

`
2023-01-31 10:13:25 | {"log":"level=info ts=2023-01-31T13:13:25.111455971Z caller=index_set.go:281 table-name=loki-distributed-index-19109 msg=\"removing source db files from storage\" count=1\n","stream":"stderr","time":"2023-01-31T13:13:25.111526417Z"}
`

**Comment by danielrosa-zh** [comment]
Please, is there a way to rebuild index from chunks somehow ? The chucks still there on s3 but unsearchable due to the missing indexes.

**Comment by slim-bean** [comment]
I'm very sorry to hear this :(

It looks like there is a default for retention of 744h in the [limits_config](https://grafana.com/docs/loki/latest/configuration/#limits_config)

If you previously did not have `retention_enabled` set to true it sounds like the compactor may have applied 31days of retention from this default config, deleting your older logs. ☹️ 

I'm sorry to say I feel like I would have more bad news, I would expect the compactor to have deleted all the chunks before it deleted the index files.

**Comment by vinicius-seedcx** [comment]
The chunks are still available in s3, is there a way of re creating the index?

**Comment by slim-bean** [comment]
I'm very sorry, we don't have any tooling which can do this.

**Comment by slim-bean** [comment]
The best I have to offer is a tool called "chunks-inspect" which can read the binary format of Loki's chunk files:

https://github.com/grafana/loki/tree/main/cmd/chunks-inspect

I'm sorry this is not in itself the most helpful :(

**Comment by slim-bean** [comment]
I've been revisiting the code as I was surprised the chunks were not deleted first, it works differently from what I remembered

**WARNING, YOUR CHUNKS ARE LIKELY STILL SCHEDULED TO BE DELETED**

The chunks which have been marked as being expired by retention are marked in a separate file, the compactor will come through and process this file in the future. It looks like the default window here is 24 hours.

This file exists only on the local compactor disk, it's not uploaded to object store.

I would recommend
* If possible, enable versioning on your bucket objects, we set ours to keep one non-current version for 7 days (if something is deleted you would have 7 days to recover it)
* Scale your compactor to zero and delete the underlying pvc and pv to remove these mark files then scale it back to 1

**Comment by slim-bean** [comment]
If this is helpful before deleting the compactor mark files you can use them to see exactly what chunks it's planning on deleting to get a list of chunks which are no longer indexed

The files are stored in 

```
/data/compactor/retention/markers
```
(The path in the distributed helm chart I thin is /var/loki/compactor...)

The files start with a timestamp, if you download them you can view them with https://github.com/br0xen/boltbrowser

**Comment by danielrosa-zh** [comment]
Hi @slim-bean , thanks for your help so far. We scaled down compactor to try avoid compactor deletes chunks, we will try enable compactor tomorrow again. Our major issue now is about the missing indexes that compactor deleted, It was not expected. Now we enable S3 versioning on bucket to avoid this in the future. We are still trying to understand why compactor deleted all the indexes.

About limits_config, we already have a parameter below applied:
`
limits_config:
  retention_period: 0s
`

**Comment by slim-bean** [comment]
I dug through this earlier, and it looks like the zero value "0s" does not disable this limit, it's [used here](https://github.com/grafana/loki/blob/b2d0481cbeee17355a4305ba48b7517c0cdea080/pkg/storage/stores/indexshipper/compactor/retention/expiration.go#L56-L55)

I'm sorry to say this sounds like another unfortunate event in this tragedy

Many defaults in Loki have a 0 value which means "disabled" but this one does not.

I'm sorry this is too late to help you but a few changes we will make after this:

* Make the documentation clearer in the deletes section when enabling `retention_enabled` to look at retention_period
* The 0 value for `retention_period` should disable it.


Please be careful when enabling the compactor, if you are going to try to recover the marker files I would suggest changing the config so that the compactor can't make changes to the object store.

**Comment by danielrosa-zh** [comment]
@slim-bean appreciate your help,
Please, what the recomended configuration for `retention_period‘ to keep logs forever? You mean 0s does not?
It was keeping in fact, until we set `retention_enabled‘ from false to true. As I understood this parameter did the mess and the documentarion should be revisited, right?

Just let me know what config we need to adjust before start compactor again (there is no pvc) and the chunks is still there on s3
Thanks

**Comment by danielrosa-zh** [comment]
@slim-bean 
So, based on that, today we defined `retention_period` to 61320h instead of `0s` and defined `retention_enabled: true` on compactor. Compactor started fine, keeping the old chunks, however we aren't able to search due to missing index.

Thanks for your support, I hope Grafana members can improve the documention soon.

**Comment by mecseid** [comment]
Hi @slim-bean ,
I run almost the same problem. After I updated my Helm-installed single-binary Loki instance from v2.x to v4.x, I lost my boltdb files, but the chunks stayed untouched.

Am I understanding correctly that If I don't touch the chunk files, then they will be deleted by the compactor after the retention time?

As I see, multiple people run into the same problem (lost indexes):
https://github.com/grafana/loki/issues/2201
https://github.com/grafana/loki/issues/4755

Is there any plan to create a tool for index recreation?

**Comment by slim-bean** [comment]
> Am I understanding correctly that If I don't touch the chunk files, then they will be deleted by the compactor after the retention time?

I'm not sure from your description if you encountered the exact same issue, but if you did, yes, there is a marker file created on the compactor disk and it will come back around and delete all the chunks. It will do so in 24 hours. 

I suggest enabling object versioning asap to make sure you can recover anything deleted which you don't want deleted.

To stop the compactor from deleting these chunks you need to remove the marker file, apologies I'm on my phone without easy access to detail where the file is, not sure if I did so previously in this thread. You can also just delete the compactor disk.

Unfortunately there is no tool to recreate the index, this is in theory possible but is not very easy to build and unfortunately I don't think is anything we would get to in the short term.

You could maybe find some downloaded and cached index files in the queries or index-gateway.

I'm sorry this has happened to you as well :(

I started the work to improve the docs and change the default retention time and will be finishing this early next week to hopefully make this not catch anyone by surprise.

We also have some documentation under review to encourage always having object versioning enabled to allow recovery from accidents related to deletes.

**Comment by mecseid** [comment]
It's okay, thank you for the quick response!

**Comment by rgg1993** [comment]
Hey there! I'm jumping into this issue, which is weird because this is our configuration for loki:

```

compactor:
  shared_store: s3
  working_directory: /loki/compactor

storage_config:
  aws:
    region: my-region
    bucketnames: my-bucket
    s3: s3://my-region/my-bucket

  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
    shared_store: s3

limits_config:
  query_timeout: 350s
  retention_period: 0s
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_cache_freshness_per_query: 10m
  split_queries_by_interval: 24h
  per_stream_rate_limit: "5MB"
  per_stream_rate_limit_burst: "15MB"
  ingestion_rate_mb: 50
  ingestion_burst_size_mb: 100
  max_entries_limit_per_query: 1000
  max_label_value_length: 20480
  max_label_name_length: 10240
  max_label_names_per_series: 300
```

From what I've read this shouldn't delete the indexes stored inside index_XXXX, right?  However, we can see that it wants to delete the files:

```
level=info ts=2024-05-29T13:36:12.492852269Z caller=index_set.go:269 table-name=index_19871 user-id=fake user-id=fake msg="removing source db files from storage" count=33
level=info ts=2024-05-29T13:36:13.167063433Z caller=index_set.go:269 table-name=index_19871 msg="removing source db files from storage" count=32
level=info ts=2024-05-29T13:36:13.837938719Z caller=compactor.go:688 msg="finished compacting table" table-name=index_19871
```

and in the s3 buckets the version has been marked for deletion. 

Note that the compactor doesn't have retention_enabled set to true and the retention_period is set to the default value of 0s.

@slim-bean  any idea? We're currently using Loki 2.9.7 version, with Grafana 10.1.10. Deployed using docker-compose. 

The documentation makes it extremely confusing because it says that 

![image](https://github.com/grafana/loki/assets/70332427/8eb5cc3b-300b-4c9e-adfb-39c7f7e790f3)

See doc here: https://grafana.com/docs/loki/v2.9.x/storage/#retention
