### ISSUE TITLE
helm - make multi tenant easy: use tenant id from nginx $remote_user

### ISSUE THREAD

**Issue by a5r0n** [grafana/loki#8380]
**Is your feature request related to a problem? Please describe.**
right not if you need to have multi tenant deployments it's very difficult to have.

**Describe the solution you'd like**
use helm template the manage tenants simple by setting name and password,

if we create htpasswd file from username and password array,
we simple can add inside nginx config template to pass the username as tenantId.

**Describe alternatives you've considered**
N/A

**Additional context**
https://nginx.org/en/docs/http/ngx_http_core_module.html#var_remote_user

**Comment by UpperM** [comment]
I've done this by adding
```  
nginxConfig:
    serverSnippet: "proxy_set_header X-Scope-OrgID $remote_user;"
```

But yeah, I think it's a good idea to have this by default when tenant are enabled

**Comment by jeschkies** [comment]
@a5r0n and @UpperM I'm not sure we'll have time to add this. However, feel free to propose it in a pull request if it's not too much work.

**Comment by a5r0n** [comment]
should we add some info in the [docs](https://grafana.com/docs/loki/latest/operations/multi-tenancy/)?
