### ISSUE TITLE
Create Windows Event Log message parser Promtail stage

### ISSUE THREAD

**Issue by kelnage** [grafana/loki#8384]
Although Promtail can [export Windows Event Log data](https://github.com/grafana/loki/tree/main/clients/pkg/promtail/targets/windows/win_eventlog), one of the key fields (Message) is sent as a large string of data, rather than being broken up into smaller component parts (it is in essence a list of key-value pairs, with the key and value separated with `: `, and the pairs separated with (Windows) newlines - i.e., `\r\n`).

Whilst this can be worked around at query time with some [rather horrific LogQL](https://github.com/grafana/pySigma-backend-loki/blob/main/sigma/pipelines/loki/loki.py#L100) (in terms of both complexity and performance), Promtail supports running additional stages after the basic ingest is complete - adding a Windows Event Log Message-parsing stage could significantly improve the performance of such queries going forward.

I have written a first attempt at an implementation of such a parser in grafana/loki#8382.

**Comment by DinoChueh** [comment]
Hi @kelnage I'm encountering this issue. Could you provide your complete Promtail config for Windows for reference?
