### ISSUE TITLE
Docs Feedback: Helm installation page doesn't installation instructions

### ISSUE THREAD

**Issue by DylanGuedes** [grafana/loki#8440]
**Is your feature request related to a problem? Please describe.**
The helm install Loki page isn't clear on how to install things. Page available here: https://grafana.com/docs/loki/next/installation/helm/install-scalable/
I'd expect a command to install the helm chart.

**Comment by jeschkies** [comment]
I think upgrade does if there's no installation but I might be wrong.

**Comment by DylanGuedes** [comment]
> I think upgrade does if there's no installation but I might be wrong.

It doesn't  :cry:
