### ISSUE TITLE
Documentation references embedded-cache but by looking at the code I think it should be 

### ISSUE THREAD

**Issue by AnderssonPeter** [grafana/loki#8462]
**Describe the bug**
The https://grafana.com/docs/loki/latest/configuration/ page references the wrong name `embedded-cache` should be `embedded_cache`?

**To Reproduce**
Visit https://grafana.com/docs/loki/latest/configuration/ search for `embedded-cache`.

**Expected behavior**
Shoud use _ like all other configurations.

**Environment:**
 - Documentation

**Comment by Andrew-Prendergast** [comment]
I've run into this issue too, if you follow the docs as they are written Loki will fail to start:
`failed parsing config: /etc/loki/loki-querier-config.yaml: yaml: unmarshal errors:
  line 71: field embedded-cache not found in type cache.Config
  line 146: field embedded-cache not found in type cache.Config`
The correct field is `embedded_cache`

**Comment by hackery** [comment]
Looks like that was fixed in #7797 but docs regeneration to web hasn't happened since.

**Comment by JStickler** [comment]
#7797 has been backported to the 2.7.x branch via #8554.

**Comment by JStickler** [comment]
Closing as this has been fixed.
