### ISSUE TITLE
lambda-promtail: possible error in model.LabelName, creates duplicate/incorrect label names

### ISSUE THREAD

**Issue by spedersen-emailage** [grafana/loki#8470]
**Describe the bug**

I re-deployed lambda-promtail today and noticed that the default labels have been modified. For ELB, they now show up as:

* `__aws_s3_lb_lb`
* `__aws_s3_lb_lb_owner`

You can see `_lb` is used twice.

They should (or did) look like this: 

* `__aws_s3_log_lb`
* `__aws_s3_log_lb_owner`

It appears to be related to [this commit (lambda-promtail: Add support for VPC flow Logs to lambda-promtail)](https://github.com/grafana/loki/commit/4d5678aa17feb3c9a4f503c171fa115eafe4e182#diff-c898e72f3b15b46b32f9405b243b7d5b56b68db7bf03541fefd587dc9e49af8eL70-R90), where `model.LabelName` was updated to support multiple sources.

I assume the update should have been more like:

```
model.LabelName(fmt.Sprintf("__aws_log_%s", logType)):       model.LabelValue(labels["src"]),
model.LabelName(fmt.Sprintf("__aws_log_%s_owner", logType)): model.LabelValue(labels["account_id"]),
```

**To Reproduce**
1. Deploy latest version of lambda-promtail as of 2023-02-08.
2. Forward ELB logs via S3 trigger.
3. Bad labels added to forwarded logs.

**Expected behavior**

See **Description**.

**Environment:**
- N/A

**Screenshots, Promtail config, or terminal output**
- N/A

**Comment by chaudum** [comment]
Hi @spedersen-emailage Thanks for reporting this regression and spotting where it happened. We will provide a fix for that.
