### ISSUE TITLE
How to query the total number of Loki

### ISSUE THREAD

**Issue by gongbpeng** [grafana/loki#8516]
The data is stored in loki, my Java program, using the http interface to query. How do I query the total number of stored data.

**Comment by chaudum** [comment]
You may submit questions in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

**NOTE: All questions submitted as issues will be closed.**
