### ISSUE TITLE
Unable to compile: error: github.com/grafana/loki@v1.6.1/pkg/promtail/client/client.go:133:69: cannot use false (untyped bool constant) as config.HTTPClientOption value in argument to config.NewClientFromConfig

### ISSUE THREAD

**Issue by tathagatachowdhury** [grafana/loki#8540]
While trying to create new promtail client using
https://pkg.go.dev/github.com/grafana/loki@v1.6.1/pkg/promtail/client#New

Getting error:
```/github.com/grafana/loki@v1.6.1/pkg/promtail/client/client.go:133:69: cannot use false (untyped bool constant) as config.HTTPClientOption value in argument to config.NewClientFromConfig```

Using golang v1.18

OS: rhel 8

**Comment by chaudum** [comment]
Based on the information you provide I don't know what you try to do. If you think it's a bug then please give a code example that does not work and what you expect it to do.

If it's just a general question, please submit it in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

**NOTE: All questions submitted as issues will be closed.**
