### ISSUE TITLE
operator: Adding additional env vars and secrets into loki stack pods

### ISSUE THREAD

**Issue by yaroslavkasatikov** [grafana/loki#8555]
Hi team, 

Basically the question which we want to solve is using loki stack which installed with help of loki-operator with temporary s3 credential ( which can be get with help of AWS STS ). 

So we found that loki has support EKS with their annotations. Also s3 client is based on standard aws go module.  So we want to use [aws-basic-config-no-creds.yaml](https://grafana.com/docs/loki/latest/configuration/examples/#aws-basic-config-no-credsyaml) config for s3 and inject into loki pods some AWS environment variables like AWS_SHARED_CREDENTIALS_FILE or smth other.

So for testing this idea we need to have an ability to inject additional secrets and environment variables into loki stack pods. I haven't found this in operator code. 

If you know better solution for STS Assume Role using, please  tell me :) 

Many thanks

**Comment by periklis** [comment]
@yaroslavkasatikov Good catch we don't support this simple approach yet with AWS. FWIW we had a similar ask for GCP using a `key.json` (See https://github.com/grafana/loki/blob/main/operator/internal/handlers/internal/storage/secrets.go#L65-L81). I believe we can follow a similar approach here for AWS (https://github.com/grafana/loki/blob/main/operator/internal/handlers/internal/storage/secrets.go#L83-L113) where we either accept a `key.json` provided in the secret or an `access_key_id` and `access_key_secret` pair.

Do you have the capacity to create a PR for this? We are glad to welcome new contributors and will guide you through the review.

**Comment by vardhaman-surana** [comment]
@periklis is this still important ?
as per my understanding in function : https://github.com/grafana/loki/blob/main/operator/internal/handlers/internal/storage/secrets.go#L83-L113
we just need to read "key.json" for the file data and then unmarshal it to get the access key id and other relevant fields.

if my understanding is correct can i start working on this ?

**Comment by periklis** [comment]
@vardhaman-surana Yes this will be addressed as described in the enhancement proposal: #1503

**Comment by periklis** [comment]
As per enhancement proposal in #11060 already addressed and merged into main adding support for proper AWS STS support closing this ticket. Feel free to try our shiny new STS support from main now only and very soon as a Community Loki Operator release v0.6.0 on you friendly OperatorHub of choice.
