### ISSUE TITLE
Support adding annotations to all service's templates 

### ISSUE THREAD

**Issue by majid-akbari** [grafana/loki#8627]
I want to use "[Topology Aware Hints](https://kubernetes.io/docs/concepts/services-networking/topology-aware-hints/)" feature of Kubernetes, but currently the helm chart templatefor `service` only support adding annotation for [gateway](https://github.com/grafana/loki/blob/9f8aa4b98a0048c658f49a6f9c3ad76e115efc84/production/helm/loki/templates/gateway/service-gateway.yaml#L12-L14) nodes.

Could you please add annotation support to all other targets like read/write/backend?

**Comment by majerus1223** [comment]
Any chance this is going to be deployed soon?
