### ISSUE TITLE
Canary 2.7.3 Push Mode Always Uses HTTP

### ISSUE THREAD

**Issue by tonyswu** [grafana/loki#8630]
**Describe the bug**

Canary push mode uses HTTP even if -tls=true is set.

**To Reproduce**

1. Configure Loki with a HTTPS frontend (we use AWS ALB).
2. Start canary with the following configuration:

```
[ "-addr=loki-internal.alb:443", "-interval=10s", "-labelname=canary-id", "-labelvalue=canary-1234", "-push", "-tls=true", "-streamname=source", "-streamvalue=stdout", "-user=<LOKI_USER>", "-pass=<LOKI_PASSWORD>" ]
```

**Expected behavior**

When -tls=true is set I'd expect Canary to use HTTPS when pushing.

**Environment:**

- Infrastructure: AWS ECS
- Deployment tool: Terraform

**Screenshots, Promtail config, or terminal output**

With above configuration, we get the following logs from ALB:

```
https 2023-02-24T16:28:12.171480Z app/loki1-internal-alb/9f17bbd3f79c57ad <IP>:45354 - -1 -1 -1 400 - 256 370 "POST http://loki-internal.alb:443/loki/api/v1/push HTTP/1.1" "canary-push/2.7.3" - - - "-" "-" "-" - 2023-02-24T16:28:12.170000Z "-" "-" "-" "-" "-" "-" "-"
```

**Comment by tonyswu** [comment]
I had submitted an identical issue before: https://github.com/grafana/loki/issues/7692

Which seem to have never been resolved even after the pull request merge.

**Comment by owenhaynes** [comment]
Its fixed on the head branch and has not been backported to the 2.7.* line. I just started using the head canary image to fix this

**Comment by tonyswu** [comment]
Got it. I wasn't quite sure how the release tag is generated. I'll close this for now then, hopefully it makes its way into a release soon.
