### ISSUE TITLE
[Docs]  Update content on Scalability page

### ISSUE THREAD

**Issue by JStickler** [grafana/loki#8631]
**Describe the bug**
Content on Loki Scalability (https://grafana.com/docs/loki/latest/operations/scalability/) is out of date.  Page links to a [blog post](https://grafana.com/blog/2018/12/12/loki-prometheus-inspired-open-source-logging-for-cloud-natives/) from 2018 that says "Loki is very much alpha software and should not be used in production environments."

**Expected behavior**
Up to date information about how to scale Loki in a production environment.

**Comment by GrafanaWriter** [comment]
@JStickler - Please reopen if I'm incorrect, but I believe this has been fixed.
