### ISSUE TITLE
operator: Allow disabling the s3forcepathstyle option for S3 Storage in CRD

### ISSUE THREAD

**Issue by xuanyunhui** [grafana/loki#8638]
**Is your feature request related to a problem? Please describe.**
The AlibabaCloud OSS service is not compatible s3 path like accessible, that is only domain style, so we need to set s3forcepathstyle is off. But the operator is not support s3forcepathstyle for S3 storage.

**Describe the solution you'd like**
enable option(s3forcepathstyle) in CRD and Loki-config.yaml

**Describe alternatives you've considered**
current we just hardcode  Loki-config.yaml and repackage operator image for our cluster

**Additional context**

**Comment by periklis** [comment]
@xuanyunhui If by operator you mean the[ Loki Operator](https://github.com/grafana/loki/tree/main/operator) (Official docs page: https://loki-operator.dev/) hosted in this repository then I am glad to inform you that we support `s3forcepathstyle: true` by default (See [loki-config.yaml#L22-L30](https://github.com/grafana/loki/blob/main/operator/internal/manifests/internal/config/loki-config.yaml#L22-L30) This is so to enable on-prem object storage providers like Minio and OpenShift Data Foundation (the two cases that have been requested so far). Is this what you are looking for?

**Comment by xuanyunhui** [comment]
> @xuanyunhui If by operator you mean the[ Loki Operator](https://github.com/grafana/loki/tree/main/operator) (Official docs page: https://loki-operator.dev/) hosted in this repository then I am glad to inform you that we support `s3forcepathstyle: true` by default (See [loki-config.yaml#L22-L30](https://github.com/grafana/loki/blob/main/operator/internal/manifests/internal/config/loki-config.yaml#L22-L30) This is so to enable on-prem object storage providers like Minio and OpenShift Data Foundation (the two cases that have been requested so far). Is this what you are looking for?

Thanks for you reply!
Maybe I didn't describe clearly，so I change the title of this issuer.
In my case I hope setting the s3forcepathstyle: false

**Comment by periklis** [comment]
> > @xuanyunhui If by operator you mean the[ Loki Operator](https://github.com/grafana/loki/tree/main/operator) (Official docs page: https://loki-operator.dev/) hosted in this repository then I am glad to inform you that we support `s3forcepathstyle: true` by default (See [loki-config.yaml#L22-L30](https://github.com/grafana/loki/blob/main/operator/internal/manifests/internal/config/loki-config.yaml#L22-L30) This is so to enable on-prem object storage providers like Minio and OpenShift Data Foundation (the two cases that have been requested so far). Is this what you are looking for?
> 
> Thanks for you reply! Maybe I didn't describe clearly，so I change the title of this issuer. In my case I hope setting the `s3forcepathstyle: false`

Ok my bad, I was primed by the title first and did not read the description carefully.

My suggestion here is to add this as a new Objest Storage Type in the CRD either called `Alibaba OSS` or `S3 host-based`. Would like to contribute this? Our SIG Operator will be glad to help you out here with reviews on your first contribution.

**Comment by xuanyunhui** [comment]
I have some doubts.
 If a new Object Storage Type in the CRD either called `Alibaba OSS`, Named `S3` is still used in the generated loki configuration，that will confuse users. 
So, I think one way is called `S3 host-based` is best if just modify Loki-operator.
Another way is add a new Object Storage Type and use native `Alibaba OSS` SDK to Loki then add this Object Storage Type to Loki-operator.
 What do your think of which is best?

**Comment by xuanyunhui** [comment]
@periklis I found `Alibaba OSS` is supported  in the Loki code, So I go to try Add a new Object Storage Type in the CRD either called Alibaba OSS.

**Comment by periklis** [comment]
If Loki supports `Alibaba OSS` natively, I will suggest to add this as a new Object Storage Type into the CRD. Supporting native client SDKs is the preferred way for maintenance sanity. A couple of pointers for your first contribution, since you are going to add a new type (besides [CRD](https://github.com/grafana/loki/blob/main/operator/apis/loki/v1/lokistack_types.go#L372-L384) and `loki-config.yaml` [rendering](https://github.com/grafana/loki/blob/main/operator/internal/manifests/internal/config/loki-config.yaml#L9-L47)):
- Ensure to add support for a separate secret handler besides S3. See [here](https://github.com/grafana/loki/blob/main/operator/internal/handlers/internal/storage/secrets.go#L19-L30).
- Ensure to add docs for the new object storage type. See [here](https://github.com/grafana/loki/blob/main/operator/docs/lokistack/object_storage.md).

**Comment by xuanyunhui** [comment]
@periklis I summited pull requests. What should I do next?

**Comment by periklis** [comment]
@xuanyunhui AFAICS the native AlibabaCloud support in Loki is not released yet. #8410 is merged but not yet released. This will land with Loki 2.8.0 soon. After that we can certainly release a new version of the Community Loki Operator to make your PR #8661 available (probably v0.3.0 as per v0.2.0 pending to go out soon See #8651).

In the meantime I would be grateful is you want to add a separate contribution to have an object-storage-type like `S3-virtual-hosted`. This can expedite solving your request until we get the native AlibabaCloud support. WDYT?

**Comment by xuanyunhui** [comment]
@xuanyunhui That's good idea，I will summit another PR soon.

**Comment by xuanyunhui** [comment]
I pushed commit [bb6e30c8b](https://github.com/grafana/loki/commit/bb6e30c8b0c5d6f46b2bbb573008912d94b06010) to branch of fork repository. 
This commit do not working with Loki.

Follow describe
```
...
common:
 storage:
    s3:
      s3: https://oss-cn-beijing-internal.aliyuncs.com
      bucketnames: bucketname
      region: cn-beijing
      access_key_id: somekey
      secret_access_key: somesecret
      s3forcepathstyle: false
...
storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/index_cache
    cache_ttl: 24h
    resync_interval: 5m
    shared_store: s3-virtual-hosted
...
```

`shared_store: s3-virtual-hosted` generate by  `{{- $store := .ObjectStorage.SharedStore }}` and reference from `lokiv1.ObjectStorageSecretType`

I need to add some conditions to make it work，So I think waiting the native AlibabaCloud support in Loki being released is best choice. WDYT?

**Comment by periklis** [comment]
The issue comes from the fact that the value of the CRD enumeration `s3-virtual-hosted` is passed here directly: https://github.com/grafana/loki/commit/bb6e30c8b0c5d6f46b2bbb573008912d94b06010#diff-af0aaa09df37635705b3fa3181eb7b306f7a7dc6dae418d641e8c8be1cd8b831R14-R17

Actually you could simply by mapping both `s3` and `s3-virtual-hosted` into one storage option. From a user perspective it is still a choice, but the code can handle both. Here is some code to illustrate:
```go
// ExtractSecret reads a k8s secret into a manifest object storage struct if valid.
func ExtractSecret(s *corev1.Secret, secretType lokiv1.ObjectStorageSecretType) (*storage.Options, error) {
	var err error
	storageOpts := storage.Options{
		SecretName:  s.Name,
		SharedStore: secretType,
	}
	switch secretType {
	case lokiv1.ObjectStorageSecretAzure:
		storageOpts.Azure, err = extractAzureConfigSecret(s)
	case lokiv1.ObjectStorageSecretGCS:
		storageOpts.GCS, err = extractGCSConfigSecret(s)
	case lokiv1.ObjectStorageSecretS3:
		storageOpts.S3, err = extractS3ConfigSecret(s)
		storageOpts.S3.EnforcePathStyle = true
	case lokiv1.ObjectStorageSecretS3VirtualHosted:
		storageOpts.S3, err = extractS3ConfigSecret(s)
		storageOpts.S3.EnforcePathStyle = false
		storageOpts.SecretType = lokiv1.ObjectStorageSecretS3
	case lokiv1.ObjectStorageSecretSwift:
		storageOpts.Swift, err = extractSwiftConfigSecret(s)
	
	default:
		return nil, kverrors.New("unknown secret type", "type", secretType)
	}
	if err != nil {
		return nil, err
	}
	return &storageOpts, nil
}
```

**Comment by xuanyunhui** [comment]
@periklis Thanks for guiding me! I was starting a PR for s3-virtual-hosted storage

**Comment by xuanyunhui** [comment]
@periklis I feel the change for S3 storage is complex, with no more time to process. So I will wait for Loki 2.8.0 to be released.
