### ISSUE TITLE
Incorrect default value for querier.query-timeout in the documentation

### ISSUE THREAD

**Issue by Withel** [grafana/loki#8673]
**Describe the bug**
According to 2.7.0 release notes:

https://grafana.com/docs/loki/latest/upgrading/#270 default value for querier.query-timeout is 0s, instead of 1m, as in previous versions.

Nevertheless, in the documentation default value still points to 1m. https://grafana.com/docs/loki/latest/configuration/#querier

**To Reproduce**
No reproduction steps.

**Expected behavior**
Correct value in the documentation.

**Environment:**
 - Loki Documentation

**Screenshots, Promtail config, or terminal output**
Third line in YAML section in the documentation regarding Loki configuration:

https://grafana.com/docs/loki/latest/configuration/#querier

**Comment by Withel** [comment]
I created PR that fixes that: https://github.com/grafana/loki/pull/8674

Apologies for all the mistakes made in writing this issue or PR, but it's my first time proposing changes for OSS. I just hope it'll help. 

Kind regards

**Comment by GrafanaWriter** [comment]
Fixed by https://github.com/grafana/loki/pull/8804
