### ISSUE TITLE
Error from Hardcoded "client_max_body_size" in HTTPSnippet

### ISSUE THREAD

**Issue by seanocca** [grafana/loki#8736]
**Describe the bug**
The bug occurs on startup of the gateway pod. 
It errors out the error message in the screenshot/terminal output section.
I have tried to set my own value for the setting `client_max_body_size` and it won't let me override the value.

**To Reproduce**
1. Set `httpSnippet` to this value
```
httpSnippet: |
    client_max_body_size 256M
```
2. Start up Loki and receive error on the `loki-gateway` pod log

**Expected behavior**
I would expect to be able to set this piece of config either through the `httpSnippet` config line or via the nginxFile. 
As you have abstracted the file away from the config section it makes it hard to set that value without re-importing the file into the `values.yaml` file.

**Environment:**
 - Infrastructure: **Kubernetes**
 - Deployment tool: **helm 3**
 - Loki Version: **Loki helm version 4.8.0**

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

`nginx: [emerg] "client_max_body_size" directive is duplicate in /etc/nginx/nginx.conf:39`

Current config setup
https://github.com/grafana/loki/blob/main/production/helm/loki/templates/_helpers.tpl#L515

**Comment by TheBaus** [comment]
Yeah this does seem to be a bug, if you look at:
[```  client_max_body_size  4M;```](https://github.com/grafana/loki/blob/2c7309e0f78bbf8b3c08863351394d4d12035f24/production/helm/loki/templates/_helpers.tpl#LL571C3-L571C28) 

You find the hardcoded line and then below that is:
[```  {{- with .Values.gateway.nginxConfig.httpSnippet }}```](https://github.com/grafana/loki/blob/2c7309e0f78bbf8b3c08863351394d4d12035f24/production/helm/loki/templates/_helpers.tpl#L597)

So when one goes to try override with your own values in the nginxConfig section, you get the nginx emerg error and new gateway pods will not startup:
```    nginxConfig:
      httpSnippet: |-
        client_max_body_size 100M;
        proxy_read_timeout   600;
        proxy_send_timeout   600;```

**Comment by khanh96le** [comment]
I guess, the `client_max_body_size` field must 1/ have its own value, or 2/ just remove it from the `_helpers.tpl` file to avoid duplication
Meanwhile waiting for the fix from Grafana, I made a workaround by adding a small change following the 1/ approach

In file values.yaml
```
gateway:
  nginxConfig:
    clientMaxBodySize: "10M"
```

In file _helpers.tpl
```
client_max_body_size {{ .Values.gateway.nginxConfig.clientMaxBodySize }};
```

**Comment by hadariz** [comment]
@khanh96le nice workaround. 
It's important to replace the hard coded values of the nginx config to variables so that we could override them from the values.yaml such as:
worker_processes, worker_rlimit_nofile, worker_connections, worker_connections,client_max_body_size , etc..

**Comment by trevorwhitney** [comment]
This sounds like a bug, thanks for bringing it up. I think the best thing to due here is to move the default `client_max_body_size` into the default for `httpSnippet`. I want to be careful not to promote every nginx config to a corresponding value in `values.yaml`, but I think it's reasonable to move a "block" of config into the `httpSnippet` section.

The outcome I'd like to see is, if I don't provide any custom values, I get the defaults of what the chart is now producing. If I want to override any value is this section, I have to provide the whole section. Sound good? If so, I'd be happy to review PR. If not, happy to hear your thoughts?

Thanks!

**Comment by shacharsharf** [comment]
Hi,
This bug is somewhat annoying, any update?

Thanks :)

**Comment by leotorjeman1** [comment]
Hello,

Would greatly appreciate if you can provide any update on this issue as it effect us as well.
Thank you

**Comment by satyamsundaram** [comment]
I think there was a [PR](https://github.com/grafana/loki/pull/11348) fixing this bug
but it wasn't merged and now has merge conflicts

if nobody is looking into this, I can raise a new PR
since this one seems inactive

**Comment by satyamsundaram** [comment]
Hey, @trevorwhitney can you review my PR #12924?
I've implemented @khanh96le's approach until there is a discussion about what should and should not be moved into the `httpSnippet` section.
