### ISSUE TITLE
Docs feedback: /fundamentals/architecture/deployment-modes.md

### ISSUE THREAD

**Issue by seanocca** [grafana/loki#8754]
The deployment mode documentation does not explain the new deployment model created in the Helm chart.
The deployment model with a Read Deployment, a Write StatefulSet, and a Backend Deployment.

Can you please provide some further information about this deployment model as it will become the default model for the Loki Helm chart?

**Comment by DylanGuedes** [comment]
Thanks for the feedback, we should definitely improve that page.

Just to not leave you without anything, the new deployment mode that you're referring to is the SSD Mode (Simple-Scalable Deployment mode) and it has its [own section on the docs](https://grafana.com/docs/loki/latest/fundamentals/architecture/deployment-modes/#simple-scalable-deployment-mode). The docs are quite simple right now and aren't covering the `backend` component though (it was added more recently).

**Comment by seanocca** [comment]
The `backend` component is certainly what I was trying to find out more about.
I also falsely assumed that this would not fall under the SSD model of deployment because of that new pod arrangement.

Thank you @DylanGuedes for the fast reply

**Comment by Eve832** [comment]
Hi @JStickler, can you please take a look and update this ticket?

**Comment by arnouthoebreckx** [comment]
Bump, what does the backend component do exactly?

**Comment by DylanGuedes** [comment]
> Bump, what does the backend component do exactly?

it handles rules evaluation and if I'm not mistaken it also runs the index-gateway so that the `read` can be non-stateful

**Comment by JStickler** [comment]
@seanocca  would love your feedback on the docs PR to update the Deployment Models topic.
https://github.com/grafana/loki/pull/10589

**Comment by seanocca** [comment]
> @seanocca would love your feedback on the docs PR to update the Deployment Models topic. #10589

@JStickler I took a look at the documentation it looks really good to clear up the missing information. It would be nice to have some acknowledgement of data storage limitations. My experience with S3 limits on prefix have caused issues as I have partially seen here #10430

**Comment by JStickler** [comment]
@seanocca The data limitations is a little too detailed for the Deployment modes topic, which is meant to be a more general overview.  But I'll keep that in mind when I get to revising the storage topics.
