### ISSUE TITLE
Avoid fetching tags in makefile

### ISSUE THREAD

**Issue by salvacorts** [grafana/loki#8770]
**Describe the bug**
When running any make target, the following script is run:
https://github.com/grafana/loki/blob/4f8d3240f6ba1d203f4713fe4a7afe109bdb8ee1/Makefile#L37

By default, some make targets are executed inside a docker container with the `loki-build-image`. This container will run the make target again with `BUILD_IN_CONTAINER=false` therefore running the `fetch-tags` scripts above. This leads to git keep asking to accept the fingerprint of _github.com_ for every make target executed.

We should probably run that script only in CI pipelines.

**To Reproduce**
1. Run `make protos` for example.

**Expected behavior**

The make targets should be run without a human in the loop accepting the _github.com_ fingerprint for git.

**Comment by chaudum** [comment]
Fixed with https://github.com/grafana/loki/pull/8854
