### ISSUE TITLE
Logs cannot be sent to lambda-promtail via Kinesis

### ISSUE THREAD

**Issue by benjamin-awd** [grafana/loki#8807]
**Describe the bug**
Logs cannot be sent to lambda-promtail via Kinesis, due to a timestamp parsing bug.

This issue was addressed in https://github.com/grafana/loki/pull/7158, and the fix was merged on Jan 13. However, it looks this was missed in the 2.7.3 and 2.7.4 releases.

This means that the lambda-promtail public images hosted on [ECR](https://gallery.ecr.aws/grafana/lambda-promtail) cannot be used to send logs to Kinesis. As a work around, I am currently using the `lambda-promtail:main-9f8aa4b-amd64` image.

**To Reproduce**
To compare the releases:
```
# Download the kinesis.go file from the v2.7.4 release
wget https://github.com/grafana/loki/archive/refs/tags/v2.7.4.zip
unzip v2.7.4.zip loki-2.7.4/tools/lambda-promtail/lambda-promtail/kinesis.go
mkdir -p /tmp/loki-v2.7.4
cp loki-2.7.4/tools/lambda-promtail/lambda-promtail/kinesis.go /tmp/loki-v2.7.4

# Download the kinesis.go file from the main branch
wget https://raw.githubusercontent.com/grafana/loki/main/tools/lambda-promtail/lambda-promtail/kinesis.go
mkdir -p /tmp/loki-main
cp kinesis.go /tmp/loki-main

git diff /tmp/loki-v2.7.4/kinesis.go /tmp/loki-main/kinesis.go
```

**Expected behavior**
The latest images for promtail lambda (e.g. on https://gallery.ecr.aws/grafana/lambda-promtail) should have the updated code for Kinesis, and should allow logs to be sent to Grafana via Kinesis.

**Environment:**
 - Infrastructure: AWS ECR
 - Deployment tool: n/a

**Comment by cstyan** [comment]
hey @benjamin-awd is this still an issue for you?

The linked PR went into main, but we build our public releases off of internal weekly release cuts. 2.7.x was likely based off of a weekly release prior to that PR being merged. lambda-promtail images tagged with 2.8.x or 2.9.x should have the fix. That being said, we don't really maintain or version lambda-promtail in the same way we do for loki. 

The version tagging being the same is mostly a convenience for notifying people when certain changes happened but again is unfortunately inconsistent.

**Comment by benjamin-awd** [comment]
I haven't checked since then, but if the latest version of lambda-promtail has this fix then I think we can close this.

**Comment by cstyan** [comment]
:+1: sounds good, thanks. If you still have issues with newer builds please let me know!
