### ISSUE TITLE
Allow Redis config to set reading across all replicas

### ISSUE THREAD

**Issue by wtchangdm** [grafana/loki#8811]
**Is your feature request related to a problem? Please describe.**

Hi! We are using Grafana Loki with Elasticache for Redis (cluster mode enabled) on AWS as our external cache.

However, after checking on the metrics, we noticed that primary replica (master) often shows `NetworkBandwidthOutAllowanceExceeded` from time to time. We can scale the node type vertically, that's for sure. But we also noticed that the replica was not read even once.

**Describe the solution you'd like**

According to the universal redis client configuration, there is no [`RouteRandomly`][1] setting there:
 https://github.com/grafana/loki/blob/8886800bf6e7547b41fe604d71765c2870b6c328/pkg/storage/chunk/cache/redis_client.go#L76-L85

I believe on production environments, one or more read replicas are usually expected. It would be great to increase the utilization of existing resources by adding support for reading from multiple nodes, especially for read-heavy use case like Loki.

Please consider about it, thanks. 🙂

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

[1]: https://pkg.go.dev/github.com/redis/go-redis/v9#UniversalOptions

**Comment by wtchangdm** [comment]
I can try to make a pull request if it's ok?

**Comment by dannykopping** [comment]
Is your replica in the set of `Addrs`?

**Comment by dannykopping** [comment]
From the docs:

> NewUniversalClient returns a new multi client. The type of the returned client depends on the following conditions:

> 1. If the MasterName option is specified, a sentinel-backed FailoverClient is returned. 2. if the number of Addrs is two or more, a ClusterClient is returned. 3. Otherwise, a single-node Client is returned.

**Comment by wtchangdm** [comment]
@dannykopping thanks for the reply!

ElastiCache for Redis (cluster mode enabled) actually only gives you [a single configuration endpoint][1], and it's up to the client to get all the primary/read replicas of all shards.

And since I don't see `MasterName` is used in the code above, I think we can just check the `Addrs` part.

When you try to resolve IPs from the configuration endpoint above, you get all of the IPs in the cluster (In my case, there are two IPs indicating the primary replica and the read replica of the only shard we are using).

```bash
$ dog xxxxxxxxxx-cache.nk2xxxx.clustercfg.apne1.cache.amazonaws.com
A xxxxxxxxxx-cache.nk2xxxx.clustercfg.apne1.cache.amazonaws.com. 15s   10.x.xx.xx
A xxxxxxxxxx-cache.nk2xxxx.clustercfg.apne1.cache.amazonaws.com. 15s   10.x.xx.xx (different than the previous one)
```

The following is the part where Loki gets all the IPs of the given endpoint (`addrs`), and overwrite `endpoints` if there are more than one (which is the case here). Related PR: #4947

https://github.com/grafana/loki/blob/8886800bf6e7547b41fe604d71765c2870b6c328/pkg/storage/chunk/cache/redis_client.go#L59-L77

So:

> Is your replica in the set of Addrs?

Yes I think so since the configuration endpoints resolves multiple IPs.

Aside from the endpoint discussion above, because the universal options didn't use `ReadOnly`, which makes it default to `false`, therefore no read replica access for us.

From [docs][2]:

```
        // Enables read-only commands on slave nodes.
	ReadOnly [bool](https://pkg.go.dev/builtin#bool)
	// Allows routing read-only commands to the closest master or slave node.
	// It automatically enables ReadOnly.
	RouteByLatency [bool](https://pkg.go.dev/builtin#bool)
	// Allows routing read-only commands to the random master or slave node.
	// It automatically enables ReadOnly.
	RouteRandomly [bool](https://pkg.go.dev/builtin#bool)
```

[1]: https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Endpoints.html
[2]: https://pkg.go.dev/github.com/redis/go-redis/v9#ClusterOptions

**Comment by dannykopping** [comment]
Thanks for the detailed response 👍 
We'd welcome this change if you'd like to contribute it!

_Unrelated: TIL about [`dog`](https://github.com/ogham/dog)... nice!_
