### ISSUE TITLE
Helm chart should enable ruler sharding

### ISSUE THREAD

**Issue by adeverteuil** [grafana/loki#8843]
**Describe the bug**

The ruler ring is used to determine which rulers evaluate which rule groups.
https://grafana.com/docs/loki/latest/fundamentals/architecture/rings/#about-the-ruler-ring

However, the `ruler.enable_sharding` defaults to false and it is not enabled in the Helm template. You need to append this in the `loki.rulerConfig` structure in your Helm values.
https://grafana.com/docs/loki/latest/configuration/#ruler

When I look at the ring health page in the Grafana GEL plugin, I see "Sharding is disabled for the Ruler service." This message disappears when I enable sharing (see the screenshots below). This make me think that there is no point having a ruler ring if sharding is not enabled, and that most production deployments should want sharding enabled. Should we override this config default in the Helm chart?

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Helm (grafana/loki)

**Screenshots, Promtail config, or terminal output**

Sharding disabled (the default):
![Screenshot 2023-03-17 12-57-09 sharding disabled](https://user-images.githubusercontent.com/3270755/226460016-03e0bd7a-3b42-4025-9b7e-7052015287a7.png)

Sharding enabled (what I think we should enable in the Helm chart by default):
![Screenshot 2023-03-17 12-59-34 sharding enabled](https://user-images.githubusercontent.com/3270755/226460019-8e2bf990-68b2-4a9f-9f6c-f11d9dafc544.png)

**Comment by sladyn98** [comment]
@dannykopping Can I get some idea on where can I go about making this change
