### ISSUE TITLE
Does Loki compactor remove duplicate data while compacting chunks?

### ISSUE THREAD

**Issue by hatrena** [grafana/loki#8943]
I am trying some load testing to my setup and sending a simple HTTP request (http://localhost) to my application so that i can observe the logs in Grafana Loki.

I am using fluentd to collect logs of my application and send them to Loki.

All the load testing requests (1000 rps for 10 seconds) are identical as `172.21.0.1 - - [29/Mar/2023:22:15:11 +0000] "GET / HTTP/1.1" 200 615 "-" "-" "-"`, except that the time would be different every second. What I observed in Grafana Loki is that I see only 1 or 2 requests per second rather than 1k rps. 

Then I added a random string at the end of the request (http://localhost?name=$random) and tried the load test again and observed that the result in Grafana Loki is almost 1000 rps.

I am assuming that the Loki compactor is removing the duplicates while compacting the chunks. how valid is my assumption? I could not find anything in the docs.

**Comment by slim-bean** [comment]
The compactor (as of the time of this message) does not touch chunks at all and does no de-duplication.

Loki itself uses the following rules for storing logs:

* Exactly one entry per nanosecond timestamp with the same exact log string
* Unlimited entries at the same nanosecond timestamp with different log strings

In this case the de-duplication is being done by Loki, I would suggest if possible to just increase the precision of your timestamp if you can to nanosecond level. Or keep adding the random string.

**Comment by hatrena** [comment]
I have managed to use K6 to send some load tests to provide better timestamp precision and a random string (as you suggested). Now everything looks ok. I think we don't expect this amount of identical logs in the real world. 

thanks for the hints anyway.
