### ISSUE TITLE
Promtail crash loop during k8s master upgrade

### ISSUE THREAD

**Issue by zarbis** [grafana/loki#899]
**Describe the bug**
During k8s master upgrade process Promtail enters crash loop. Not sure if it's expected behavior.

**To Reproduce**
1. Started loki 0.2
2. Started promtail 0.2
3. Started k8s master upgrade

**Expected behavior**
Promtail keeps collecting logs during master upgrade.

**Environment:**
 - Infrastructure: GKE v1.11.10-gke.5 => v1.12.9-gke.7
 - Deployment tool: helm

**Screenshots, promtail config, or terminal output**
Logs during master upgrade and several minutes after:
```
level=info ts=2019-08-15T14:07:22.659211374Z caller=kubernetes.go:192 component=discovery discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-08-15T14:07:22.661982562Z caller=server.go:120 http=[::]:3101 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2019-08-15T14:07:22.66247835Z caller=main.go:55 msg="Starting Promtail" version="(version=v0.2.0, branch=HEAD, revision=321b928c)"
level=warn ts=2019-08-15T14:07:37.218882636Z caller=logging.go:49 msg="GET /ready (500) 99.067µs Response: \"Not ready: Unable to find any logs to tail. Please verify permissions, volumes, scrape_config, etc.\\n\" ws: false; Accept-Encoding: gzip; Connection: close; User-Agent: kube-probe/1.11+; "
I0815 14:07:38.250114       1 trace.go:82] Trace[819516683]: "Reflector github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:283 ListAndWatch" (started: 2019-08-15 14:07:22.66129257 +0000 UTC m=+0.104844611) (total time: 15.588632115s):
Trace[819516683]: [15.587470628s] [15.587470628s] Objects listed
log: exiting because of error: log: cannot create log: open /tmp/promtail.loki-promtail-ffwjv.unknownuser.log.INFO.20190815-140738.1: read-only file system
```

**Comment by slim-bean** [comment]
This is from a promtail instance running on the master node?

**Comment by zarbis** [comment]
@slim-bean On GKE master node is unseen to end user. Promtail crashes on EVERY node, forgot to mention that important detail :)

**Comment by slim-bean** [comment]
interesting... we are on GKE mostly too and recently upgraded our masters, will have to look and see if we had the same issue, we are using the ksonnet config rather than helm which are mostly the same (I think with the exception of where the positions.yaml file is stored)

**Comment by pracucci** [comment]
According to the output, /tmp has been mounted as read-only and since the position file is written there in your setup, promtail fails to write it.

I would suggest you to investigate:
- Is /tmp intentionally read-only?
- If yes, switch the positions file to a different read-write location

**Comment by adityacs** [comment]
The issue is related to #810. I guess it's the same glog library problem
