### ISSUE TITLE
Unable to Connect Elasticache as Redis Endpoint

### ISSUE THREAD

**Issue by seanocca** [grafana/loki#9026]
**Describe the bug**
I receive an `i/o timeout` error on every Redis connection command to the cluster.
The config propagates correctly and we can see the URL and Password are set correctly.

**To Reproduce**
1. Build AWS Elasticache with universally `0.0.0.0/0` on port `6379`
2. Create below config for Loki passing in the Elasticache URL through secrets
3. Start Loki on Helm Chart
4. Receive Error

**Expected behavior**
Loki to connect and use the Redis Elasticache cluster as cache 

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm
 - Chart Version: 4.8.0

**Screenshots, Promtail config, or terminal output**

```
level=error ts=2023-04-04T00:44:57.128168075Z caller=redis_cache.go:61 msg="failed to put to redis" name=store.index-cache-read.redis err="i/o timeout"
level=warn ts=2023-04-04T00:44:57.128208685Z caller=background.go:127 msg="backgroundCache writeBackLoop Cache.Store fail" err="i/o timeout"
```

CONFIG
<img width="316" alt="image" src="https://user-images.githubusercontent.com/32288543/229954307-32aa6b70-d9e8-4eaa-8165-4968be0bf52e.png">

**Comment by rgroothuijsen** [comment]
To exclude general connectivity issues, is the Redis endpoint reachable from your cluster when using basic tools like `redis-cli`?

**Comment by seanocca** [comment]
> To exclude general connectivity issues, is the Redis endpoint reachable from your cluster when using basic tools like `redis-cli`?

@rgroothuijsen the cluster was reachable from the instance using `redis-cli`. However it needed to have the `tls` enabled for both the `redis-cli` and the Loki config the working config for AWS Elasticache is below

![image](https://user-images.githubusercontent.com/32288543/231024604-8b10c033-8991-4f02-92a9-d00637bc720d.png)

**Comment by niroshea** [comment]
@seanocca I encountered the same problem, how did you solve it?
