### ISSUE TITLE
Problem install CentOS 7

### ISSUE THREAD

**Issue by fmcardosom** [grafana/loki#903]
While installing on CentOS 7 this is happening:

[root@itcos7snoop01 loki]# go get github.com/grafana/loki
can't load package: package github.com/grafana/loki: no Go files in /root/work/src/github.com/grafana/loki

Any thoughts ?

Regards,

FC

**Comment by rfratto** [comment]
Hi! That's [normal](https://github.com/grafana/loki/blob/master/CONTRIBUTING.md) since we don't have any .go files at the root of the project. You can either run `git clone` or `go get github.com/grafana/loki/...` to get the code.

**Comment by fmcardosom** [comment]
Thank you
