### ISSUE TITLE
Docs feedback: /logql/log_queries/_index.md - some errors in the results shown in :Drop labels expression" section?

### ISSUE THREAD

**Issue by ethirolle** [grafana/loki#9052]
I reviewed this doc page, https://grafana.com/docs/loki/latest/logql/log_queries/, and it is fantastic, but I _think_ there may be some errors in the results from the example `drop` expression here:

https://github.com/grafana/loki/blob/main/docs/sources/logql/log_queries/_index.md?plain=1#L628-L629
```
{host="grafana.net", job="varlogs", method="GET", status="200"} {""app": "some-api-service",", "level": "info", "method": "GET", "path": "/", "host": "grafana.net", "status": "200"}
{app="other-service", host="grafana.net", job="varlogs", method="GET", status="200"} {"app": "other-service",, "level": "info", "method": "GET", "path": "/", "host": "grafana.net", "status": "200"}
```

In first line:

- a double quote at start of the log line portion: `""app"`
- extra `",` here: `"some-api-service",",`

In second line:

- double comma here: `{"app": "other-service",,`

**Comment by JStickler** [comment]
Fixed via #9506
