### ISSUE TITLE
The official Linux release binary of promtail 2.8.0 is built without systemd journal support (on at least amd64)

### ISSUE THREAD

**Issue by siebenmann** [grafana/loki#9060]
**Describe the bug**
The official promtail binaries for Linux amd64 are built without support for reading from the systemd journal. Starting them with the journal configured as a log source gets you:

```
level=info ts=2023-04-06T15:19:32.082276461Z caller=promtail.go:133 msg="Reloading configuration file" md5sum=f77bc87e64d66cca88ef9c78b403eb79
level=warn ts=2023-04-06T15:19:32.082499874Z caller=journaltargetmanager.go:29 msg="WARNING!!! Journal target was configured but support for reading the systemd journal is not compiled into this build of promtail!"
level=info ts=2023-04-06T15:19:32.084100883Z caller=server.go:323 http=[::]:9080 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2023-04-06T15:19:32.084264747Z caller=main.go:174 msg="Starting Promtail" version="(version=2.8.0, branch=HEAD, revision=90888a0cc)"
level=warn ts=2023-04-06T15:19:32.084327616Z caller=promtail.go:265 msg="enable watchConfig"
```
I suspect that promtail binaries were not built with [the new build tag to include the journal](https://github.com/grafana/loki/blob/release-2.8.x/docs/sources/upgrading/_index.md#the-go-build-tag-promtail_journal_enabled-was-introduced) that's covered in the 2.8 upgrade notes.

**Comment by m1keil** [comment]
just hit the same issue...

**Comment by dannykopping** [comment]
Thank you for reporting this.

We will get it sorted out and update our build automation to prevent reoccurrences in the future.

**Comment by jeschkies** [comment]
This fix is up for review. I'm a little confused when this regression was introduced though.

**Comment by frittentheke** [comment]
@trevorwhitney are you pushing out that 2.8.1 with just journald support (re)added or are you waiting for more bugfixes?

**Comment by trevorwhitney** [comment]
It will go out this week. There were a couple other fixes we wanted in there.

**Comment by trevorwhitney** [comment]
fixed in the latest release! https://github.com/grafana/loki/releases/tag/v2.8.1
