### ISSUE TITLE
Discrepancy between CI tests and local environment tests

### ISSUE THREAD

**Issue by Demianeen** [grafana/loki#9079]
**Describe the bug**
I have encountered the bug that the tests in the CI environment for Loki are running differently compared to the tests that I run locally on my development environment. Specifically, I am observing discrepancies in the test results, with tests passing locally but failing in the CI environment.

**To Reproduce**
1. [Clone repo](https://github.com/Demianeen/react-production)
2. Run `npm run storybook` and launch the Docker
3. Run `npm run test:ui` and observe that the tests pass locally
4. View the repo history and notice that all recent commits have failed to pass the tests

**Expected behavior**
I expect the tests to exhibit consistent behaviour across different environments, including both local development environments and the CI environment. Test results should be reproducible and consistent, regardless of the environment in which they are executed.

**Environment:**
 - Local: Macbook M1, Docker v4.17.0
 - CI: GitHub actions

package.json
```json
"scripts": {
    "test:ui": "npx loki test",
    "test:ui:ok": "npx loki approve",
    "test:ui:ci": "npx loki --requireReference --reactUri file:./storybook-static",
    "storybook": "start-storybook -p 6006 -c ./config/storybook",
    "build:storybook": "build-storybook -c ./config/storybook",
  },,
"devDependencies": {
"loki": "^0.30.0",
},
"loki": {
    "configurations": {
      "chrome.laptop": {
        "target": "chrome.docker",
        "width": 1366,
        "height": 768,
        "deviceScaleFactor": 1,
        "mobile": false
      },
      "chrome.iphone7": {
        "target": "chrome.docker",
        "preset": "iPhone 7"
      }
    }
  }
```
Additional information:
1. While attempting to build Storybook locally and launch the CI command for testing, I encountered an issue where the Docker process appeared to hang indefinitely after running the npm run test:ui:ci command.
2. The last log displayed was "RUNS chrome.docker: Starting".

Logs: 
```console
npm run test:ui:ci

> react-production@1.0.0 test:ui:ci
> npx loki --requireReference --reactUri file:./storybook-static

loki test v0.30.3
(node:16804) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
 RUNS  chrome.docker: Starting
```

**Comment by chaudum** [comment]
Hi @Demianeen 

I am not sure what you are referring to. This repository is about the Loki log aggregation system and is written in Go.

You are probably want to raise the issue on https://github.com/oblador/loki which is the repository for the visual regression testing tool for Storybook.

**Comment by DeadMonstr** [comment]
same error
