### ISSUE TITLE
LokiQL regex operator in stream selector together with escaping does not match label with two dots.

### ISSUE THREAD

**Issue by itsx** [grafana/loki#9111]
**What happened**:
  Our Logs dashboard broke about a week ago for labels containing two dots.

  We have a Logs panel with the following query:
` {__aws_cloudwatch_log_stream=~"$log_stream"} $query`
 `log_stream` variable has "Multi-value" and "Include All" options enabled.

  For _**labels containing two dots**_, the following expression (single value in variables) incorrectly does not match any logs: 
  `{ __aws_cloudwatch_log_stream=~"mongo1\\.company\\.internal"} |~ "(?i)"`

  However, the following expression (two values in variable} matches logs correctly: 
  `{ __aws_cloudwatch_log_stream=~"mongo1\\.company\\.internal|mongo2\\.company\\.internal"} |~ "(?i)"`

  This applies for all our labels containing two dots (expression are copied from Query inspector).

  Furthermore, when I try following expressions with deleted backslashes, they all work:
  Expr: `{ __aws_cloudwatch_log_stream=~"mongo1.company.internal"} |~ "(?i)"`
  Expr: `{ __aws_cloudwatch_log_stream=~"mongo1\\.company.internal"} |~ "(?i)"`
  Expr: `{ __aws_cloudwatch_log_stream=~"mongo1.company\\.internal"} |~ "(?i)"`

**What you expected to happen**:
  Query correctly matches labels for all selected variable values (single value, multi-value, All) like before.

**How to reproduce it (as minimally and precisely as possible)**:
  1) Prepare logs with label values containing at least two dots, e.g.: 
     label: `__aws_cloudwatch_log_stream`, value:  `mongo.company.internal`

  2) In Logs panel or Query explorer, try to match logs with expression containing escaped dots, e.g.:
      Expr: `{ __aws_cloudwatch_log_stream=~"mongo1\\.company\\.internal"} |~ "(?i)"`

  3) Above expression matches no logs.
  
**Environment**:
- Grafana version:
  Grafana v9.5.0-cloud.2.f143d34 (efe95b4c21)
- Data source type & version:
  Loki, Grafana Cloud
- OS Grafana is installed on:
  Grafana Cloud
- User OS & Browser:
  Ubuntu 22.04.1 LTS
  Chromium Version 111.0.5563.110 (Official Build) snap (64-bit)

**Comment by svennergr** [comment]
Might be related to https://github.com/grafana/loki/pull/8763 / https://github.com/grafana/loki/pull/9108

**Comment by jeschkies** [comment]
Thanks for using the LogQL Analyzer. This makes triaging much simpler. So ```| logfmt | level =~ `mongo\.company\.internal` ``` should actually be optimized into ```| logfmt | level = `mongo.company.internal` ```. Maybe there's a bug there.

**Comment by wardbekker** [comment]
Seeing the same issue with the dashboard variable selection on this dashboard: https://play.grafana.org/d/T512JVH7z/loki-nginx-service-mesh-json-version?orgId=1

**Comment by jeschkies** [comment]
It's not even working for one line https://grafana.com/docs/loki/latest/logql/analyzer/?query=%7C+logfmt+%7C+level+%3D%7E+%60mongo%5C.company%5C.internal%60&line%5B%5D=level%3Dmongo.company.internal+foo%3Dbar
