### ISSUE TITLE
Restore loki-backend StatefulSet after kill

### ISSUE THREAD

**Issue by thevops** [grafana/loki#9114]
I've accidentally killed one of 3 replicas of StatefulSet `loki-backend` and they started to return such logs:
```
level=error ts=2023-04-12T14:00:57.650187769Z caller=manager.go:272 storage=registry manager=tenant-wal msg="instance stopped abnormally, restarting after backoff period" err="failed to initialize instance: error creating WAL: create dir: mkdir ruler-wal: read-only file system" backoff=1s instance=fake
level=error ts=2023-04-12T14:00:58.651070907Z caller=instance.go:240 storage=registry manager=tenant-wal instance=fake msg="failed to initialize instance" err="error creating WAL: create dir: mkdir ruler-wal: read-only file system"
level=error ts=2023-04-12T14:00:58.651102171Z caller=manager.go:272 storage=registry manager=tenant-wal msg="instance stopped abnormally, restarting after backoff period" err="failed to initialize instance: error creating WAL: create dir: mkdir ruler-wal: read-only file system" backoff=1s instance=fake
```

I tried:
- scale down StatefulSet to zero and scale up again (I had 3 replicas)
- scale down StatefulSet and remove PVC/PV attached to loki-backend replicas
Nothing helped.

I'm using Google Cloud Storage (GCS) as storage. It's a bit weird because I still can see logs in Grafana, so Loki is streaming them properly.

How can I fix `loki-backend`?

**Comment by thevops** [comment]
Fixed with
```
  rulerConfig:
    wal:
      dir: /var/loki/ruler-wal
```
I'm using Loki Helm chart.
https://github.com/grafana/loki/blob/helm-loki-4.5.1/production/helm/loki/values.yaml#L278

**Comment by lieberlois** [comment]
> Fixed with
> 
> ```
>   rulerConfig:
>     wal:
>       dir: /var/loki/ruler-wal
> ```
> 
> I'm using Loki Helm chart. https://github.com/grafana/loki/blob/helm-loki-4.5.1/production/helm/loki/values.yaml#L278

Thank you so much! Do you maybe want to contribute this to the upstream chart? Had the same issue with Loki 3.2

**Comment by thevops** [comment]
@lieberlois good to see that it helped not only me :)
What do you mean regarding contribution? It's just adding a piece of configuration. I don't think it should be included in the defaults.

**Comment by lieberlois** [comment]
I was thinking we might want to have this as a sane default in the chart, since it doesn't work with the current default configuration?
