### ISSUE TITLE
[Question]Loki logs warn `err="rpc error: code = Code(400) desc = entry with timestamp`  

### ISSUE THREAD

**Issue by 9265zl** [grafana/loki#9151]
```[tasklist]
### Tasks
- [x] why my loki logs this error keeps coming up `err="rpc error: code = Code(400) desc = entry with timestamp`
```

HI,
I tried  local  installing loki and promtail,but apppear the following error occurs.Although the log level is a warn, I would like to know why this is, and how can I fix this?

```
531 Apr 17 11:03:18 node2 loki-linux-amd64[1852370]: level=warn ts=2023-04-17T03:03:18.045323318Z caller=grpc_logging.go:38 method=/logproto.Pusher/Push duration=244.963?s err="rpc error: code = Code(400) desc = entry with timestamp 2023-04-17 03:04:14.747850533 +0000 UTC ignored, reason: 'entry out of order' for stream: {cluster=\"nide_test\", filename=\"/b_iscsi/log/ctdb_run.log\", host=\"192.168.3.19\"},\nentry with timestamp 2023-04-17 03:04:14.747856824 +0000 UTC ignored, reason: 'entry out of order' for stream: {cluster=\"nide_test\", filename=\"/b_iscsi/log/ctdb_run.log\", host=\"192.168.3.19\"},\nentry with timestamp 2023-04-17 03:04:14.747958653 +0000 UTC ignored, reason: 'entry out of order' for stream: {cluster=\"nide_test\", filename=\"/b_iscsi/log/ctdb_run.log\", host=\"192.168.3.19\"},\nentry with timestamp 2023-04-17 03:04:14.748047226 +0000 UTC ignored, reason: 'entry out of order' for stream: {cluster=\"nide_test\", filename=\"/b_iscsi/log/ctdb_run.log\", host=\"192.168.3.19\"},\ntotal ignored: 4 out of 4" msg="gRPC\n"
532 Apr 17 11:03:18 node2 loki-linux-amd64[1852370]: level=warn ts=2023-04-17T03:03:18.137961463Z caller=grpc_logging.go:38 method=/logproto.Pusher/Push duration=285.436?s err="rpc error: code = Code(400) desc = entry with timestamp 2023-04-17 03:08:46.030832216 +0000 UTC ignored, reason: 'entry out of order' for stream: {cluster=\"nide_test\", filename=\"/b_iscsi/log/ctdb_run.log\", host=\"192.168.3.19\"},\nentry with timestamp 2023-04-17 03:08:46.030836536 +0000 UTC ignored, reason: 'entry out of order' for stream: {cluster=\"nide_test\", filename=\"/b_iscsi/log/ctdb_run.log\", host=\"192.168.3.19\"},\nentry with timestamp 2023-04-17 03:08:46.030918606 +0000 UTC ignored, reason: 'entry out of order' for stream: {cluster=\"nide_test\", filename=\"/b_iscsi/log/ctdb_run.log\", host=\"192.168.3.19\"},\nentry with timestamp 2023-04-17 03:08:46.030964036 +0000 UTC ignored, reason: 'entry out of order' for stream: {cluster=\"nide_test\", filename=\"/b_iscsi/log/ctdb_run.log\", host=\"192.168.3.19\"},\nentry with timestamp 2023-04-17 03:08:47.031264726 +0000 UTC ignored, reason: 'entry out of order' for stream: {cluster=\"nide_test\", filename=\"/b_iscsi/log/ctdb_run.log\", host=\"192.168.3.19\"},\nentry with timestamp 2023-04-17 03:08:47.031270176 +0000 UTC ignored, reason: 'entry out of order' for stream: {cluster=\"nide_test\", filename=\"/b_iscsi/log/ctdb_run.log\", host=\"192.168.3.19\"},\nentry with timestamp 2023-04-17 03:08:47.031442406 +0000 UTC ignored, reason: 'entry out of order' for stream: {cluster=\"nide_test\", filename=\"/b_iscsi/log/ctdb_run.log\", host=\"192.168.3.19\"},\nentry with timestamp 2023-04-17 03:08:47.031444876 +0000 UTC ignored, reason: 'entry out of order' for stream: {cluster=\"nide_test\", filename=\"/b_iscsi/log/ctdb_run.log\", host=\"192.168.3.19\"},\ntotal ignored: 8 out of 8" msg="gRPC\n"
533 Apr 17 11:03:18 node2 loki-linux-amd64[1852370]: level=warn ts=2023-04-17T03:03:18.234936648Z caller=grpc_logging.go:38 method=/logproto.Pusher/Push duration=318.447?s err="rpc error: code = Code(400) desc = entry with timestamp 2023-04-17 03:04:15.729672494 +0000 UTC ignored, reason: 'entry out of order' for stream: {cluster=\"nide_test\", filename=\"/var/log/ceph/ceph.log\", host=\"192.168.3.19\"},\ntotal ignored: 1 out of 1" msg="gRPC\n"
534 Apr 17 11:03:18 node2 loki-linux-amd64[1852370]: level=warn ts=2023-04-17T03:03:18.261352319Z caller=grpc_logging.go:38 method=/logproto.Pusher/Push duration=588.423?s err="rpc error: code = Code(400) desc = entry with timestamp 2023-04-17 03:05:37.986389167 +0000 UTC ignored, reason: 'entry out of order' for stream: {cluster=\"nide_test\", filename=\"/b_iscsi/log/meminfo_performance.log\", host=\"192.168.3.19\"},\ntotal ignored: 1 out of 1" msg="gRPC\n"

```

Best Regards,
Rob.

**Comment by chaudum** [comment]
Hi @9265zl 

The warning clearly states that the entry is out of order, which means you are sending logs from a stream (set of unique labels) not with timestamps in ascending order.

While Loki supports out-of-order writes out of the box, the limit to the earliest time out-of-order entries may have is defined by `time_of_most_recent_line - (max_chunk_age / 2)`. `max_chunk_age` defaults to 2h.

Read more here: https://grafana.com/docs/loki/next/configuration/#accept-out-of-order-writes

Hope this helps.

**Comment by vvayne676** [comment]
Hi  @chaudum I have similar issue but no out of order

When I run single loki instance, promtail can forward logs to loki correctly. Yet I have 3 loki instances (target is all) and replication factor is 3, then I forward logs to one of the loki instance I got below errors ` level=warn ts=2023-04-19T09:03:05.618647081Z caller=grpc_logging.go:43 method=/logproto.Pusher/Push duration=6.098819ms err="rpc error: code = Code(400) desc = entry with timestamp 2023-04-17 07:24:45 +0000 UTC ignored, reason: 'entry too far behind, oldest acceptable timestamp is: 2023-04-18T02:15:06Z' for stream: {author=\"\", filename=\""},`

Below is my Loki config, I used docker compose to get them up.
> auth_enabled: false
> 
> server:
>   http_listen_port: 3100
>   grpc_listen_port: 9096
>   log_level: debug
> 
> distributor:
>   ring:
>     kvstore:
>       store: memberlist
> 
> ingester:
>   lifecycler:
>     address: 127.0.0.1
>     ring:
>       replication_factor: 3
>       heartbeat_timeout: 1m
>       kvstore:
>         store: memberlist
>     join_after: 5s
>     final_sleep: 0s
>     num_tokens: 256    
>   wal:
>     enabled: true
>     dir: /loki/ingester/wal
> 
> schema_config:
>   configs:
>     - from: 2020-10-24
>       store: boltdb-shipper
>       object_store: gcs
>       schema: v11
>       index:
>         prefix: index_
>         period: 24h
> 
> 
> storage_config:
>   boltdb_shipper:
>     shared_store: gcs
>     active_index_directory: /loki/data/index
>     cache_location: /loki/cache
>   gcs:
>     bucket_name: my-loki-data
>     service_account: xxx
> 
>  
> compactor:
>   working_directory: /loki/compactor
>   shared_store: gcs
>   compaction_interval: 1h
>  
> 
> limits_config:
>   reject_old_samples: false
> chunk_store_config:
>   max_look_back_period: 336h
> table_manager:
>   retention_deletes_enabled: true
>   retention_period: 168h
> 
> 
> 
> memberlist:
>   join_members: ["loki1:7946", "loki2:7947","loki3:7948"]
>   dead_node_reclaim_time: 30s
>   gossip_to_dead_nodes_time: 15s
>   left_ingesters_timeout: 30s
>   bind_addr: ['0.0.0.0']
>   bind_port: 7946
>   gossip_interval: 2s
    
Best
Wayne

**Comment by 9265zl** [comment]
Thank you so much for helping me out!

@chaudum

**Comment by 9265zl** [comment]
Hi @chaudum 
I need to ask you for help again

How about this question?  Loki error logs `loki-linux-amd64[32663]: level=error ts=2023-04-20T09:06:46.620052139Z caller=wlog.go:508 msg="sync previous segment" err="sync wal/00000042: input/output error"`

This error happens from time to time, and there is no context associated with it. I tried searching the Internet, but nothing. I felt loki's error was incomplete.
Thanks again.

Best Regards,
Rob.

**Comment by JStickler** [comment]
Questions have a better chance of being answered if you ask them on the [community forums](https://community.grafana.com/c/grafana-loki/41).

Closing as it looks like the original question was answered.
