### ISSUE TITLE
clarify retention: period vs duration

### ISSUE THREAD

**Issue by Morriz** [grafana/loki#916]
Please explain: 
`[NOTE] Retention period should be at least twice the duration of periodic table config, which currently defaults to 7 days.`

What is `the duration of periodic table config`? Why does it exist and what is the relation to the period?

**Comment by pracucci** [comment]
> Retention period should be at least twice the duration of periodic table config, which currently defaults to 7 days.

@cyriltovena May you explain the rationale behind it? In my recent investigation on how the table manager works, I've realized that actually it keeps `floor(retention_period / table_period) + 1` tables, so I would say that the retention period should be at least equal to the period table period (not the double) and should be a multiple of it.

**Comment by cyriltovena** [comment]
I actually don't know much about retention, @sandlis can you help here ?

**Comment by sandlis** [comment]
@Morriz index tables hold index for a configurable duration to help optimize the queries. Its value defaults to 7 days. Retention deletes complete table at a time so it deletes the whole table only when whole table is out of retention period since there is no way to delete tables partially.

@pracucci you are right, need to update the docs. It should just say retention should be multiple of periodic table duration. Will send a PR.

**Comment by pracucci** [comment]
> @pracucci you are right, need to update the docs. It should just say retention should be multiple of periodic table duration.

@sandlis I'm still dubious why "retention should be multiple of periodic table duration". Why can't the retention be equal to the period table duration? The current table manager implementation keeps the last `floor(retention_period / table_period) + 1`  tables, so if `retention_period == table_period` it will keep the last 2 tables, which looks OK to me.

**Comment by sandlis** [comment]
Cortex now does not support retention period which is not a multiple of periodic table duration which also means Loki won't support it. It was changed by me recently since partial deletion of tables is not supported yet and it was setting wrong expectations.

**Comment by pracucci** [comment]
> Cortex now does not support retention period which is not a multiple of periodic table duration which also means Loki won't support it

Sorry @sandlis but **I've misunderstood your last message**. We're on the same page. Retention must be:
1. Always a multiple of table `period`
2. At least equal to the table `period` (while currently the doc erroneously says that it must be at least the double)
