### ISSUE TITLE
JSON: Accessing string from array leads to `Unknown value type` error

### ISSUE THREAD

**Issue by svennergr** [grafana/loki#9179]
**Describe the bug**
Given a JSON logline `{"foo":["bar"]}` and trying to access the `bar` string from it leads to a `Unknown value type` error.

You can see it here: https://grafana.com/docs/loki/latest/logql/analyzer/?query=%7C+json+baz%3D%22foo%5B0%5D%22&line%5B%5D=%7B%22foo%22%3A%5B%22bar%22%5D%7D
![image](https://user-images.githubusercontent.com/8092184/232795896-47cd6c5a-4c2b-4e23-9803-054cf69c8997.png)

Using number arrays works as expected: https://grafana.com/docs/loki/latest/logql/analyzer/?query=%7C+json+baz%3D%22foo%5B0%5D%22&line%5B%5D=%7B%22foo%22%3A%5B1%5D%7D
![image](https://user-images.githubusercontent.com/8092184/232795944-ce389802-70b6-46cf-9d61-5dc147d838c9.png)

**To Reproduce**
1. Go to https://grafana.com/docs/loki/latest/logql/analyzer/?query=%7C+json+baz%3D%22foo%5B0%5D%22&line%5B%5D=%7B%22foo%22%3A%5B%22bar%22%5D%7D

**Expected behavior**

String slices should be parsed as number slices.

**Environment:**
 - Loki: latest

**Comment by rgroothuijsen** [comment]
This appears to be an oddity in the underlying JSON parser. When the string is either wrapped in a JSON object or in a 2-dimensional array, it suddenly does manage to parse.

**Comment by slvlirnoff** [comment]
Any news on this one? Looks very odd indeed.

**Comment by slvlirnoff** [comment]
It works if the string can be parsed to a 'known' type, i.e. "21:12:12", "500"
See here, items 0 and 1 can be extracted but not "abc": https://grafana.com/docs/loki/latest/query/analyzer/?query=%7C+json+baz%3D%22foo%5B0%5D%22%2C+bazz%3D%22foo%5B1%5D%22%2C+bazzz%3D%22foo%5B2%5D%22&line%5B%5D=%7B%22foo%22%3A%5B%2221%3A12%3A00%22%2C+%22500%22%2C+%22abc%22%5D%7D

**Comment by slvlirnoff** [comment]
After more sleuthing, it seems to have been introduced by #8734 and would be related to https://github.com/buger/jsonparser/issues/232

**Comment by jrgvf** [comment]
Hi, any news?

**Comment by paul1r** [comment]
Hello, apologies for the delay!  I've integrated a fix today that should fix this issue. If it does not, please reopen this.
