### ISSUE TITLE
Deploying Loki Helm chart with singleBinary do not deploy Grafana dashboards configmaps

### ISSUE THREAD

**Issue by dragoangel** [grafana/loki#9183]
**Describe the bug**
No configMap created for Grafana dashboards when used with `singleBinary`. If remove `singleBinary` then dashboards will be created by Helm. I assume `if` condition in the template is wrong. 

**Expected behavior**
Configmaps `loki-dashboards-1\2` with `grafana_label: 1` would be in place.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Comment by bmm-alc** [comment]
confirmed here.
is it the same issue than #7657 ?

**Comment by dragoangel** [comment]
Yep, closed as duplicate
