### ISSUE TITLE
promtail binary or some standalone ?

### ISSUE THREAD

**Issue by petarkozic** [grafana/loki#92]
Congrats on this project.
I tested locally with docker and works great.

I already using prometheus and love they project :)

I have one baremetal lab server with virtualization and I want to implement promtail on whole instances to test, but problem is promtail. I don't want to use docker on all instances.
Do you have some binary of promtail ?

Indeed, I'm using ELK stack for logging about 50-60 instances and I want to switch on this when become stable :)

Great job ! Support from me !

**Comment by solidnerd** [comment]
Hey @petarkozic ,

in the meantime what you cold do is to copy the binary from the container.

```
docker create --name promtail-bin grafana/promtail:make-images-static-26a87c9
docker cp promtail-bin:/usr/bin/promtail .
docker rm -f promtail-bin
./promtail
```

**Comment by petarkozic** [comment]
Thank you @solidnerd 
Works like a charm ;)

**Comment by bbigras** [comment]
Could this issue be kept open so we can track when the situation will change?
