### ISSUE TITLE
Docs feedback: /docs/sources/installation/helm/reference.md

### ISSUE THREAD

**Issue by callmehyde** [grafana/loki#9219]
On the following page, the "default" column stretches the page width to be verrrrry wide. I'm not sure if it's possible for us to wrap text that's in a code block, but that would be ideal.
* https://grafana.com/docs/loki/latest/installation/helm/install-monolithic/

Here's a quick video of what I'm experiencing (Chrome 112.0.5615.137, macOS 13.3.1). 

---

https://user-images.githubusercontent.com/13998241/233526692-da1ad6f2-6c7d-4707-b079-a62ed562fd6a.mp4

**Comment by GrafanaWriter** [comment]
This is a website issue, so I've passed the feedback to that team. Thanks for the video!

**Comment by JStickler** [comment]
The website team just rolled out a new feature that solves this problem.  You can now click **Expand Table** to view tables.  The Your browser's search works in the pop-up table window.
![ExpandTable](https://github.com/grafana/loki/assets/4106682/897fe7e2-c695-402f-89e5-80f7f24d4c72)
