### ISSUE TITLE
Add support to detect high entropy strings in log lines

### ISSUE THREAD

**Issue by marcosnils** [grafana/loki#923]
**Is your feature request related to a problem? Please describe.**
Developers sometimes output sensitive information.

**Describe the solution you'd like**
Configure Loki to detect high entropy strings and obfuscate/remove the conflicting value.

**Describe alternatives you've considered**
Porting something like https://github.com/lyft/high-entropy-string to Go and provide a flag to enable it in Loki being aware of the performance implications this could have

**Additional context**
It's important to flag some applications as critical in terms of security due to the data that they usually handle and a requirement that we have is to constantly audit the logs that the system is producing. We just thought it'd be nice if Loki could provide something out of the box to help with this task.

/cc @caarlos0

**Comment by slim-bean** [comment]
Interesting idea!  If finding high entropy strings, what do you think would be the best course of action? update a metric? try to remove the string?

**Comment by marcosnils** [comment]
Updating a metric and removing the conflicting string and replacing with some garbage data would be nice to start. That's what other systems usually do.

**Comment by caarlos0** [comment]
FWIW I can work on porting the high-entropy-string lib (or find alternatives) 🤔

**Comment by pracucci** [comment]
> replacing with some garbage data

I would suggest a static configurable string (ie. defaults to `OMITTED`), so that the user can also easily search it across logs.

**Comment by marcosnils** [comment]
> I would suggest a static configurable string (ie. defaults to `OMITTED`), so that the user can also easily search it across logs.

SGTM!
