### ISSUE TITLE
promtail: lack of metrics on dropped batches because of ingester unavailable

### ISSUE THREAD

**Issue by pracucci** [grafana/loki#925]
**Is your feature request related to a problem? Please describe.**
If the ingester is unavailable, log entries batches are dropped (discarded) once all `maxretries` are exausted. However, I can't find a reliable way to alert on it, due to the lack of metrics.

I would suggest to add the following metrics to `pkg/promtail/client/client.go`:

- `promtail_dropped_bytes_total`: Number of bytes of log lines dropped because failed to be sent to the ingester after all retries
- `promtail_log_entries_sent_total`: Total number of log entries sent to the ingester
- `promtail_log_entries_dropped_total`: Total number of log entries dropped because failed to be sent to the ingester after all retries

What's your take? If you see a value on it, I will work on a PR.

**Comment by cyriltovena** [comment]
Hey Marco,

Yes we do see value !

That would be a useful addition.

Thank you.
