### ISSUE TITLE
Case-insensitive flag line filter regex only matching uppercase

### ISSUE THREAD

**Issue by kelnage** [grafana/loki#9294]
**Describe the bug**
Using the case-insensitive flag `(?i)`in a label regex filter `=~` causes the query to only match uppercase values, rather than any case.

**To Reproduce**
1. Using the [LogQL Analyzer](https://grafana.com/docs/loki/latest/logql/analyzer/?query=%7C+logfmt+%7C+level+%3D%7E+%60%28%3Fi%29info%60&line%5B%5D=level%3Dinfo&line%5B%5D=level%3DINFO&line%5B%5D=level%3DInFo) demonstrates this issue - only one of the sample log entries (the second one, `level=INFO`) is matched by this query
2. Sample data: 
```
level=info
level=INFO
level=InFo
```
3. Test query: `{job="analyze"} | logfmt | level =~ "(?i)info"`

**Expected behavior**
Every row in the sample data should have been matched. Using the case-insensitive flag on stream selectors does not appear to have the same outcome.

**Additional information**
Potentially related to #7837?

**Comment by akruchinkin** [comment]
Thank you!
