### ISSUE TITLE
Does not start on Windows subsystem for Linux

### ISSUE THREAD

**Issue by StianOvrevage** [grafana/loki#93]
Not able to test out loki on my Windows machine running Ubuntu under WSL.

Tried both the `docker run` commands and `docker-compose up` without luck:

```
Attaching to docs_grafana_1, docs_loki_1, docs_promtail_1
loki_1      | level=error ts=2018-12-13T15:43:37.3741138Z caller=main.go:28 msg="error loading config" filename=/etc/loki/loki-local-config.yaml err="Error reading config file: open /etc/loki/loki-local-config.yaml: no such file or directory"
promtail_1  | level=error ts=2018-12-13T15:43:37.5404898Z caller=main.go:29 msg="error loading config" filename=/etc/promtail/promtail-docker-config.yaml err="Eeror reading config file: open /etc/promtail/promtail-docker-config.yaml: no such file or directory"
```

I tried to open a shell interactively inside the loki container so that I could verify if the volume mount was successful `docker run -v "$PWD/docs:/etc/loki" -it grafana/loki:master bash` but that does not work, probably because the way you have used cmd/entrypoint in the Dockerfile, but I was not able to find any Dockerfile in the repo to dig deeper.

The docker commands in the quick start also refers to config files in the docs repo, it should probably be clearer that you NEED to clone the repo even when running the `docker run` commands. Or better, provide some default config files or something. And config should also be over-rideable using environment variables, for example the way Grafana does it today.

Other than that I'm super stoked to try loki out soon!

**Comment by daniil-konovalenko** [comment]
As far as I know, docker is not yet supported by WSL. Have you tried running it via Docker for Windows?

**Comment by StianOvrevage** [comment]
I suspect I know how I messed it up. Will try again soon and report back!

**Comment by slim-bean** [comment]
Closing this guy due to age, please let us know if there are still issues!
