### ISSUE TITLE
Live tailing sends duplicate logs

### ISSUE THREAD

**Issue by slim-bean** [grafana/loki#931]
**Describe the bug**
When connected over the websocket you can/will receive duplicate logs (same labels, same message)

**Expected behavior**
Ideally we would not send duplicate logs

**Comment by aocenas** [comment]
@cyriltovena Based on our yesterday discussion I understand that this is not really fixable short term and client should either deduplicate itself or use the [delay_for](https://github.com/grafana/loki/blob/bb2b925255ff20e6662f32491d35b09e0491c4f7/docs/api.md#get-lokiapiv1tail).

**Comment by slim-bean** [comment]
Closing this issue, it's always going to be difficult to remove all duplicates when using replication, the `delay_for` paramater can help but if you want your logs super fast you may get dupes.

**Comment by joshross12** [comment]
> Closing this issue, it's always going to be difficult to remove all duplicates when using replication, the `delay_for` paramater can help but if you want your logs super fast you may get dupes.

When you say "using replication", do you mean within the promtail config? Or loki? Also, I am seeing what I think is a similar issue, however, the duplicate logs are coming from promtail agents running on different nodes. Was that the problem you were having @slim-bean ?
