### ISSUE TITLE
Loki documentation and general issues with RuleAPI deployed via Helm with S3 backend

### ISSUE THREAD

**Issue by dragoangel** [grafana/loki#9351]
**Describe the bug**
Generally it not possible in any way to create Rules in Loki that work with S3 storage due to missing working documentation and tools:
- as written in document: [Create Grafana Mimir or Loki managed recording rules](https://grafana.com/docs/grafana/latest/alerting/alerting-rules/create-mimir-loki-managed-recording-rule/) Grafana should provide option to write rules to Loki if Loki deployed with shared storage, but actually it can't and not provide any debug details why it fails, no errors displayed. Please see screenshots at the bottom of the ticket.
- [Alerting and Recording Rules](https://grafana.com/docs/loki/latest/rules/#interacting-with-the-ruler) mention [cortextool](https://github.com/grafana/cortex-tools#rules) which throws 404 errors when try speak with Loki Gateway. Please see logs at the bottom of the ticket.

**To Reproduce**
1. Started Loki v2.8.0 via [Loki Helm-chart v5.2.0](https://github.com/grafana/loki/tree/main/production/helm/loki) with S3 storage
2. Started Grafana v9.5.1 (bc353e4b2d), added Loki datasource pointing to Loki gateway with an enabled option to manage alert rules
3. Tried to add alert\record rules via Grafana - failed with 0 details
4. Downloaded on my PC cortextool v0.10.7
5. PortForward Loki Gateway via kubectl to my local PC
6. Tried to add rules.yaml via CLI point to PortForwarded Loki Gateway - failed with 404 error

**Expected behavior**
Have the option to use both Grafana and cortextool to list\read\write rules to Loki with S3 as storage backend.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
Loki Datasource configuration in Grafana with all options on and no errors:
![image](https://user-images.githubusercontent.com/1865999/235316419-5ef776e8-4c72-4b4b-a5d4-500cb274515e.png)

Create alert page in Grafana with Loki datasource configured not provide option to create rules:
![image](https://user-images.githubusercontent.com/1865999/235316349-e2673e1c-0318-443f-948c-9bc60b47c956.png)

Result of running cortextool (tried with and without `--backend=loki`, different links in debug, but same result):
```
PS C:\Users\aleks> cortextool version
version 0.10.7
checking latest version... You are on the latest version
cortextool rules list --backend=loki --address=http://localhost:10925/ --id=fake --log.level=debug
time="2023-04-30T00:51:25+03:00" level=info msg="log level set to debug"
time="2023-04-30T00:51:25+03:00" level=debug msg="sending request to cortex api" method=GET url="http://localhost:10925/api/prom/rules"
time="2023-04-30T00:51:26+03:00" level=debug msg="checking response" status="404 Not Found"
time="2023-04-30T00:51:26+03:00" level=debug msg="server returned HTTP status 404 Not Found: 404 page not found" fields.msg="404 page not found" status="404 Not Found"
time="2023-04-30T00:51:26+03:00" level=fatal msg="unable to read rules from cortex, requested resource not found"
PS C:\Users\aleks> cortextool rules lint -n .\Desktop\rules.yaml
time="2023-04-29T21:00:59+03:00" level=info msg="SUCCESS: 1 rules found, 1 linted expressions"
PS C:\Users\aleks> cortextool rules load .\Desktop\rules.yaml --backend=loki --address=http://localhost:10925/ --id=fake --log.level=debug
time="2023-04-30T00:49:43+03:00" level=info msg="log level set to debug"
group: 'NginxRules', ns: 'ingress-nginx'
/api/prom/rules/ingress-nginx/NginxRules
time="2023-04-30T00:49:43+03:00" level=debug msg="sending request to cortex api" method=GET url="http://localhost:10925/api/prom/rules/ingress-nginx/NginxRules"
time="2023-04-30T00:49:43+03:00" level=debug msg="checking response" status="404 Not Found"
time="2023-04-30T00:49:43+03:00" level=debug msg="server returned HTTP status 404 Not Found: 404 page not found" fields.msg="404 page not found" status="404 Not Found"
time="2023-04-30T00:49:43+03:00" level=debug msg="sending request to cortex api" method=POST url="http://localhost:10925/api/prom/rules/ingress-nginx"
time="2023-04-30T00:49:44+03:00" level=debug msg="checking response" status="404 Not Found"
time="2023-04-30T00:49:44+03:00" level=debug msg="server returned HTTP status 404 Not Found: 404 page not found" fields.msg="404 page not found" status="404 Not Found"
time="2023-04-30T00:49:44+03:00" level=error msg="unable to load rule group" error="requested resource not found" group=NginxRules namespace=ingress-nginx
cortextool.exe: error: load operation unsuccessful, try --help
```

**Comment by dragoangel** [comment]
With 5.5.0 chart update issue solved. Rules and alerts can be created with both cortextool and Grafana alerting page. Thank you

**Comment by dragoangel** [comment]
Actually, I face another issue: alert and recording hang on "creating" without any further details. Files created on S3 but nothing happened after.
![image](https://user-images.githubusercontent.com/1865999/236096029-a3932f67-a081-4432-bfd5-c6ea1fbe43f9.png)

**Comment by dragoangel** [comment]
Reopen, hope `error running loki err="mkdir rules-wal: read-only file` will be fixed

**Comment by smeeklai** [comment]
@dragoangel Hi. Can you tell how to use cortextool with Thanos? I'm running Thanos but I don't know how to use that tool with Thanos to upload rules to an S3 bucket.

**Comment by dragoangel** [comment]
> @dragoangel Hi. Can you tell how to use cortextool with Thanos? I'm running Thanos but I don't know how to use that tool with Thanos to upload rules to an S3 bucket.

Thanos doesn't use cortextool, it use same approach as Prometheus: just yaml configs or Prometheus operator created resources in CRDs, tagged in way to be picked up only by one of them.

**Comment by yelhouti** [comment]
@dragoangel 
Thanks for sharing your experience, I am trying to also using configMap with s3, but rules are not picked up.
here is my config map:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-alerting-rules
  labels:
  loki_rule: ""
data:
  watchdog.yaml: |
    groups:
      - name: watchdog
        rules:
          - alert: Watchdog
            annotations:
              message: "Loki watchdog"
            expr: 1
            labels:
              severity: none
              loki: loki

```
i change the sidecar config like this:
```yml
sidecar:
  rules:
    folder: /rules/fake
```

and I can see that the yaml file are copied into /rules/fake/watchdog.yaml but when I query the backend for rules, it keeps returning `no rule groups found` I am sure I am missing something stupid, could you help please ?

**Comment by dragoangel** [comment]
> @dragoangel 
> Thanks for sharing your experience, I am trying to also using configMap with s3, but rules are not picked up.
> here is my config map:
> ```yaml
> apiVersion: v1
> kind: ConfigMap
> metadata:
>   name: loki-alerting-rules
>   labels:
>   loki_rule: ""
> data:
>   watchdog.yaml: |
>     groups:
>       - name: watchdog
>         rules:
>           - alert: Watchdog
>             annotations:
>               message: "Loki watchdog"
>             expr: 1
>             labels:
>               severity: none
>               loki: loki
> 
> ```
> I changed the sidecar config like this:
> ```yml
> sidecar:
>   rules:
>     folder: /rules/fake
> ```
> 
> and I can see that the yaml file are copied into /rules/fake/watchdog.yaml but when I query the backend for rules, it keeps returning `no rule groups found` I am sure I am missing something stupid, could you help please ?
> 
> 

Obviously rules folder where to copy rules and from where load them must align and it's not in your case, no other way off...

**Comment by yelhouti** [comment]
@dragoangel when using S3 where does it load them from by default ? is there a way to change that ?

**Comment by dragoangel** [comment]
> @dragoangel when using S3 where does it load them from by default ? is there a way to change that ? Should I change it ? Could you provided a working values.yaml with s3 and configmap please ?

When you using s3 you can just edit or create rules in grafana. I prefer gitops so I go with configmaps and sidecar

**Comment by yelhouti** [comment]
@dragoangel Thanks a lot for taking the time respond every time. 
Are you able to use s3 for logs storage and configmaps/filesystem for rules ?

**Comment by dragoangel** [comment]
> @dragoangel Thanks a lot for taking the time respond every time. Are you able to use s3 for logs storage and configmaps/filesystem for rules ?

yes, why no? but this only applies to k8s as sidecar is all about k8s

**Comment by yelhouti** [comment]
@dragoangel I ma using the latest loki helm chart. and storage is defined in one place:
https://github.com/grafana/loki/blob/e7fdeb974aff62c5775b9f98ebb2228000b28c8d/production/helm/loki/values.yaml#L312-L320
once I set it to S3 all storages are set to s3. could you provide a snippet of your values.yaml ? or are you doing this with an older chart ?

**Comment by dragoangel** [comment]
@yelhouti no matter what is set on s3 if you set:
```yaml
...
    rulerConfig:
      storage:
        type: local
        local:
          directory: /var/loki/rules
      rule_path: /var/loki/rules-temp
      wal:
        dir: /var/loki/ruler-wal
...
  sidecar:
    enabled: true
    enableUniqueFilenames: true
    rules:
      enabled: true
      label: loki_rule
      labelValue: "1"
      folder: /var/loki/rules/fake
      searchNamespace: ALL
```

**Comment by yelhouti** [comment]
@dragoangel thanks a lot, worked like a charm
