### ISSUE TITLE
Loki microservices Tanka: error during manifest generation

### ISSUE THREAD

**Issue by irizzant** [grafana/loki#9361]
**Describe the bug**
There is an error during manifest generation with the following options:
```
memberlist_ring_enabled: true,
create_service_monitor: true,
```

The error is:
`Error: evaluating jsonnet: RUNTIME ERROR: Field does not exist: name
        /home/ivan.rizzante/kubernetes/gitops/loki/vendor/loki/servicemonitor.libsonnet:42:13-42        thunk from <object <anonymous>>
        Array element 3
        Field "values"
        Array element 0
        Field "matchExpressions"
        Field "selector"
        Field "spec"
        Field "serviceMonitor"
        During manifestation`

**To Reproduce**
1. Started Loki 2.8.1
2. Set configuration parameters as above
3. Render jsonnet manifests with `tk show`

**Expected behavior**
I should be able to generate the manifests

**Environment:**
 - Infrastructure: kubernetes
 - Deployment tool: jsonnet

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by DylanGuedes** [comment]
> Hi @DylanGuedes , do you know when these changes will be released (I mean in a stable release not master)?
> 
> Thanks

Not sure, but probably less than 2 months (2.9 release)
