### ISSUE TITLE
promtail-lambda ingest cloudtrail logs from s3

### ISSUE THREAD

**Issue by gkaskonas** [grafana/loki#9367]
**Is your feature request related to a problem? Please describe.**
It already supports logs from s3 for vpc flow logs and lb logs why not cloudtrail?

**Describe the solution you'd like**
Update promtail lambda to parse cloudtrail logs as well

**Describe alternatives you've considered**
None

**Additional context**

**Comment by cstyan** [comment]
PRs for supporting additional AWS products are welcome but internally we're not really using lambda-promtail extensively and it's maintenance is currently best effort.

**Comment by elliotdobson** [comment]
It looks like this feature was added in grafana/loki#9497. @gkaskonas can you confirm this fits your use case?

**Comment by JStickler** [comment]
Closing as it looks like this feature has been added .
