### ISSUE TITLE
Wrong docker image tag in release 2.8.1 page

### ISSUE THREAD

**Issue by askya** [grafana/loki#9384]
**Describe the bug**
Error on page https://github.com/grafana/loki/releases/tag/v2.8.1.  
Wrong Docker tag provided :
```
docker pull "grafana/loki:v2.8.1"
docker pull "grafana/promtail:v2.8.1"
```
Executing those commands fails.
```# docker pull "grafana/loki:v2.8.1"
Error response from daemon: manifest for grafana/loki:v2.8.1 not found: manifest unknown: manifest unknown
```

**To Reproduce**
Run `docker pull "grafana/loki:v2.8.1`

**Expected behavior**
`v` should not be in the tags name. The commands should be :
```
docker pull "grafana/loki:2.8.1"
docker pull "grafana/promtail:2.8.1"
```

**Environment:**
 - Docker

**Screenshots, Promtail config, or terminal output**
None

**Comment by wtchangdm** [comment]
Looks like this is also the case for `2.8.2`.

**Comment by salvacorts** [comment]
Thanks for reporting this issue! Should be fixed now :)
