### ISSUE TITLE
basic dashboard request

### ISSUE THREAD

**Issue by daixiang0** [grafana/loki#95]
Is there any basic dashboard example?

I really want to try it with a dashboard example.

**Comment by jgsqware** [comment]
If you install the Grafana night build from master branch `grafana/grafana:master` with the env variable 
```
env:
          - name: GF_EXPLORE_ENABLED
            value: "true"```
To enable the Explore view, you wil have the loki dashboard where you can already play with the queries

**Comment by viktorsmari** [comment]
What is the **quickest way** to get some test data to play with?
I started everything with `docker-compose up` and I see the Explore tab, but I have no data in it.

**Comment by davkal** [comment]
After running `docker-compose up` you need to log in (`admin` and `admin`) and add Loki as a datasource:

<img width="619" alt="screenshot 2018-12-14 at 17 43 36" src="https://user-images.githubusercontent.com/859729/50037603-fa6fb600-ffc7-11e8-966c-4d83e9bda7df.png">

The screenshot shows what it should look like after you click "Save & Test". 

Next step is to go to Explore and use the "Log labels" button to select a log stream. Here is an example:
<img width="1235" alt="screenshot 2018-12-14 at 17 47 06" src="https://user-images.githubusercontent.com/859729/50037626-4ae71380-ffc8-11e8-9d00-b5edf0d4be14.png">

**Comment by daixiang0** [comment]
Wonderful!
I misunderstood that loki need to craete a dashboard yesterday.

**Comment by davkal** [comment]
Looks like this is resolved then.

**Comment by davkal** [comment]
Let's keep this open until #117 is merged.
