### ISSUE TITLE
Loki Backend hangs indefinitely during shutdown

### ISSUE THREAD

**Issue by uhthomas** [grafana/loki#9523]
**Describe the bug**

The Loki Backend container will hang indefinitely when attempting to shutdown. The rollout only progresses due to the 5 minute grace period from Kubernetes.

```sh
❯ k -n loki get po
NAME                           READY   STATUS    RESTARTS   AGE
loki-backend-0                 1/1     Running   0          3m16s
loki-backend-1                 1/1     Running   0          9m7s
loki-backend-2                 1/1     Running   0          14m
```

**To Reproduce**
1. Install the Loki helm chart.
2. Restart the stateful set.

```sh
k -n loki rollout restart sts loki-backend
```

**Expected behavior**
It should gracefully shutdown in a timely manner.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Helm

**Screenshots, Promtail config, or terminal output**

N/A - see above.

**Comment by buroa** [comment]
+1, seeing this in my lab as well. I'm unable to have the Helm chart rollout successfully (version update) due to the `loki-backend` pods never terminating, so it get's in a stuck loop. I started noticing this behavior about a week ago. The only way to "update" is to delete everything (deployments, statefulsets) and let it deploy fresh.

**Comment by uhthomas** [comment]
I forgot to include the logs.... Hopefully they're helpful in understanding what's getting stuck.

```
level=info ts=2023-05-25T16:07:39.299200425Z caller=signals.go:55 msg="=== received SIGINT/SIGTERM ===\n*** exiting"
level=info ts=2023-05-25T16:07:39.299498457Z caller=manager.go:265 msg="stopping user managers"
level=info ts=2023-05-25T16:07:39.29951218Z caller=manager.go:279 msg="all user managers stopped"
level=info ts=2023-05-25T16:07:39.299529947Z caller=mapper.go:47 msg="cleaning up mapped rules directory" path=/var/loki/rules-temp
level=info ts=2023-05-25T16:07:39.29956959Z caller=module_service.go:114 msg="module stopped" module=ruler
level=info ts=2023-05-25T16:07:39.299720754Z caller=compactor.go:393 msg="compactor exiting"
level=info ts=2023-05-25T16:07:39.299748845Z caller=basic_lifecycler.go:202 msg="ring lifecycler is shutting down" ring=compactor
level=info ts=2023-05-25T16:07:39.299881392Z caller=module_service.go:114 msg="module stopped" module=query-scheduler
level=warn ts=2023-05-25T16:07:39.299908949Z caller=grpc_logging.go:64 duration=1h10m37.310410219s method=/schedulerpb.SchedulerForQuerier/QuerierLoop err="queue is stopped" msg=gRPC
level=warn ts=2023-05-25T16:07:39.299932647Z caller=grpc_logging.go:64 method=/schedulerpb.SchedulerForQuerier/QuerierLoop duration=1h10m37.310393585s err="queue is stopped" msg=gRPC
level=warn ts=2023-05-25T16:07:39.299917799Z caller=grpc_logging.go:64 method=/schedulerpb.SchedulerForQuerier/QuerierLoop duration=1h4m57.68348322s err="queue is stopped" msg=gRPC
level=warn ts=2023-05-25T16:07:39.299991222Z caller=grpc_logging.go:64 method=/schedulerpb.SchedulerForQuerier/QuerierLoop duration=1h5m1.146566658s err="queue is stopped" msg=gRPC
level=warn ts=2023-05-25T16:07:39.300020361Z caller=grpc_logging.go:64 method=/schedulerpb.SchedulerForQuerier/QuerierLoop duration=1h5m0.942151554s err="queue is stopped" msg=gRPC
level=warn ts=2023-05-25T16:07:39.300103127Z caller=grpc_logging.go:64 method=/schedulerpb.SchedulerForQuerier/QuerierLoop duration=1h10m34.362229459s err="queue is stopped" msg=gRPC
level=warn ts=2023-05-25T16:07:39.300090077Z caller=grpc_logging.go:64 method=/schedulerpb.SchedulerForQuerier/QuerierLoop duration=1h10m39.892106686s err="queue is stopped" msg=gRPC
level=info ts=2023-05-25T16:07:39.300105737Z caller=module_service.go:114 msg="module stopped" module=index-gateway
level=info ts=2023-05-25T16:07:39.3001402Z caller=basic_lifecycler.go:372 msg="unregistering instance from ring" ring=compactor
level=warn ts=2023-05-25T16:07:39.300160241Z caller=grpc_logging.go:64 duration=1h5m0.94236336s method=/schedulerpb.SchedulerForQuerier/QuerierLoop err="queue is stopped" msg=gRPC
level=warn ts=2023-05-25T16:07:39.300197945Z caller=grpc_logging.go:64 method=/schedulerpb.SchedulerForQuerier/QuerierLoop duration=1h10m34.36239909s err="queue is stopped" msg=gRPC
level=info ts=2023-05-25T16:07:39.300219547Z caller=module_service.go:114 msg="module stopped" module=store
level=info ts=2023-05-25T16:07:39.300234251Z caller=basic_lifecycler.go:242 msg="instance removed from the ring" ring=compactor
level=info ts=2023-05-25T16:07:39.300277319Z caller=module_service.go:114 msg="module stopped" module=ingester-querier
level=info ts=2023-05-25T16:07:39.300283645Z caller=module_service.go:114 msg="module stopped" module=compactor
level=info ts=2023-05-25T16:07:39.300293796Z caller=basic_lifecycler.go:202 msg="ring lifecycler is shutting down" ring=index-gateway
level=info ts=2023-05-25T16:07:39.300330834Z caller=module_service.go:114 msg="module stopped" module=usage-report
level=info ts=2023-05-25T16:07:39.300348543Z caller=module_service.go:114 msg="module stopped" module=ring
level=info ts=2023-05-25T16:07:39.300513653Z caller=basic_lifecycler.go:372 msg="unregistering instance from ring" ring=index-gateway
level=info ts=2023-05-25T16:07:39.300631501Z caller=basic_lifecycler.go:242 msg="instance removed from the ring" ring=index-gateway
level=info ts=2023-05-25T16:07:39.300691522Z caller=module_service.go:114 msg="module stopped" module=index-gateway-ring
level=info ts=2023-05-25T16:07:39.300763845Z caller=module_service.go:114 msg="module stopped" module=runtime-config
level=info ts=2023-05-25T16:07:39.300804459Z caller=memberlist_client.go:641 msg="leaving memberlist cluster"
level=warn ts=2023-05-25T16:07:39.809692654Z caller=grpc_logging.go:64 method=/schedulerpb.SchedulerForQuerier/QuerierLoop duration=204.959µs err="scheduler is not running" msg=gRPC
level=warn ts=2023-05-25T16:07:39.811677406Z caller=grpc_logging.go:64 method=/schedulerpb.SchedulerForQuerier/QuerierLoop duration=110.869µs err="scheduler is not running" msg=gRPC
level=warn ts=2023-05-25T16:07:39.817323365Z caller=grpc_logging.go:64 method=/schedulerpb.SchedulerForQuerier/QuerierLoop duration=51.33µs err="scheduler is not running" msg=gRPC
level=warn ts=2023-05-25T16:07:39.946732016Z caller=grpc_logging.go:64 duration=198.244µs method=/schedulerpb.SchedulerForQuerier/QuerierLoop err="scheduler is not running" msg=gRPC
level=warn ts=2023-05-25T16:07:39.949491523Z caller=grpc_logging.go:64 method=/schedulerpb.SchedulerForQuerier/QuerierLoop duration=54.409µs err="scheduler is not running" msg=gRPC
level=warn ts=2023-05-25T16:07:39.951243087Z caller=grpc_logging.go:64 method=/schedulerpb.SchedulerForQuerier/QuerierLoop duration=56.497µs err="scheduler is not running" msg=gRPC
level=warn ts=2023-05-25T16:07:39.956390936Z caller=grpc_logging.go:64 method=/schedulerpb.SchedulerForQuerier/QuerierLoop duration=204.032µs err="scheduler is not running" msg=gRPC
level=warn ts=2023-05-25T16:07:39.987964926Z caller=grpc_logging.go:64 method=/schedulerpb.SchedulerForQuerier/QuerierLoop duration=139.639µs err="scheduler is not running" msg=gRPC
level=info ts=2023-05-25T16:07:40.016124479Z caller=module_service.go:114 msg="module stopped" module=memberlist-kv
```

**Comment by szinn** [comment]
I have noticed this issue as well.

**Comment by tyriis** [comment]
currently this is a really annoying issue as it require me to manually apply updates of loki on all gitops managed clusters :disappointed: any chance to get this fixed?

**Comment by icereed** [comment]
Do you have embedded cache enabled? When we switched to external cache using Memcached we saw a better behaviour. Maybe the embedded cache doesn't terminate some connections?

**Comment by jseiser** [comment]
Same issue here. No memcache, using S3 for the backends.

**Comment by stdmje** [comment]
I have noticed the same issue.

**Comment by NilsGriebner** [comment]
Same here.

**Comment by tyriis** [comment]
any chance to get some official feedback or a possible workaround, I have currently disabled loki upgrades to automerge in renovate. This is not a solution :(
for anyone interested in the : https://github.com/tyriis/renovate-config/blob/main/flux/prevent-automerge-loki.json5

**Comment by epneo-banuprakash** [comment]
<img width="939" alt="image" src="https://github.com/grafana/loki/assets/89842780/535c0adc-93dd-4aaf-9f51-7121250c1cf4">
i am facing the above issue with grafana/loki-stack with hlem chart in AKS 1.25 version any help??

**Comment by cdancy** [comment]
We're seeing similar issues here as well. Tagging some developers in hope of getting some traction or at least a response of some kind here.

@JStickler @chaudum @kavirajk

**Comment by tyriis** [comment]
I have found a way to live with it, by accepting that a rollout with 3 backends will take ~20min to reconcile :(

**Comment by epneo-banuprakash** [comment]
> <img alt="image" width="939" src="https://private-user-images.githubusercontent.com/89842780/280195181-535c0adc-93dd-4aaf-9f51-7121250c1cf4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyODk4OTEsIm5iZiI6MTcwMjI4OTU5MSwicGF0aCI6Ii84OTg0Mjc4MC8yODAxOTUxODEtNTM1YzBhZGMtOTNkZC00YWFmLTlmNTEtNzEyMTI1MGMxY2Y0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDEwMTMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjOGY4NmU0YzlmNTk2MDU5ZTk3NDczMDFmNWIwYTE4ZTM2Yzk4MWM2MzAxOGFiMDQwNDBiNzFlMzUzYjgyZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._ICa9BoqgAUTdyM9DZhtUQOCf86Jv4k6mpXDdsC3jkw"> i am facing the above issue with grafana/loki-stack with hlem chart in AKS 1.25 version any help??

some deep digging into that issue has been resolved..thanks

**Comment by uhthomas** [comment]
> > <img alt="image" width="939" src="https://private-user-images.githubusercontent.com/89842780/280195181-535c0adc-93dd-4aaf-9f51-7121250c1cf4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyODk4OTEsIm5iZiI6MTcwMjI4OTU5MSwicGF0aCI6Ii84OTg0Mjc4MC8yODAxOTUxODEtNTM1YzBhZGMtOTNkZC00YWFmLTlmNTEtNzEyMTI1MGMxY2Y0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDEwMTMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjOGY4NmU0YzlmNTk2MDU5ZTk3NDczMDFmNWIwYTE4ZTM2Yzk4MWM2MzAxOGFiMDQwNDBiNzFlMzUzYjgyZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._ICa9BoqgAUTdyM9DZhtUQOCf86Jv4k6mpXDdsC3jkw"> i am facing the above issue with grafana/loki-stack with hlem chart in AKS 1.25 version any help??
> 
> 
> 
> some deep digging into that issue has been resolved..thanks

Off-topic. The on-topic issue is not resolved.

**Comment by tyriis** [comment]
> I am facing this exact issue in EKS, any updates on how I can get my loki log pods to terminate on a helm uninstall?

hey @andrewgkew I am using flux, increasing the timeout for a helm release from 5 -> 15 min solved it for me (I use 3 replica) if you have more you need to find a timeout where each replica can be killed after wait + healthcheck + start time hope it helps.

**Comment by andrewgkew** [comment]
> > I am facing this exact issue in EKS, any updates on how I can get my loki log pods to terminate on a helm uninstall?
> 
> hey @andrewgkew I am using flux, increasing the timeout for a helm release from 5 -> 15 min solved it for me (I use 3 replica) if you have more you need to find a timeout where each replica can be killed after wait + healthcheck + start time hope it helps.

@tyriis thanks for the tip. But this means my removing of the pods could take 15 minutes? Thats crazy. I assume this is just a work around? Any idea whats causing it and why Grafana are not fixing the issue?

**Comment by tyriis** [comment]
@andrewgkew yeah ofc this is a workaround (and it does not scale) as this thread is not responded, I live with it for now

**Comment by clawoflight** [comment]
We also experience this issue, and it prevents rolling patches of the cluster because nodes cannot be drained properly.
How can we help debug this?

**Comment by EraYaN** [comment]
This also seems to break single binary mode when a node shuts down and it corrupts all data. Loki just hangs for too long and then linux just kills the process. It really needs to respect that first sigterm it gets, both in backend mode and in singlebinary mode. Like you better flush and shutdown because you are going to get killed soon.

**Comment by cyriltovena** [comment]
Can someone provides a goroutine dump when that happens please ?

```
curl http://localhost:<port>/debug/pprof/goroutine?debug=2
```

**Comment by elburnetto-intapp** [comment]
If it helps, we've upgraded to V3 and we haven't seen this issue since.

**Comment by cyriltovena** [comment]
Another way to get the dumb is using kubectl exec

```
kubectl exec loki-logs-2wj2f -n monitoring —- kill -6
```

**Comment by andrewgkew** [comment]
@cyriltovena I can confirm that this issue goes away with upgrading to v3 of Loki, thanks @elburnetto-intapp for the tip.

**Comment by onedr0p** [comment]
@uhthomas You can probably close this issue. I can confirm v3 doesn't have this issue either.

**Comment by ellisonch** [comment]
I'm still seeing this behavior on 3.5.7 in SimpleScalable mode.  As above, if i delete the read pod, the backend immediately shuts down.  Otherwise it takes 5 minutes to eventually be force-killed.
