### ISSUE TITLE
Loki chart 5.5.6 breaks helm upgrade by changing sts podManagementPolicy

### ISSUE THREAD

**Issue by tbondarchuk** [grafana/loki#9524]
**Describe the bug**
Loki chart 5.5.6 breaks helm upgrade by [changing](https://github.com/grafana/loki/commit/f9aba994555da55f424163a49b53bb6643946aa2#diff-66c0976f3e4a28eece6585c5ba1267c5bea934f7c2345006a96f4489694101ab) sts podManagementPolicy from `Parallel` to `OrderedReady` which fails since that field cannot be modified on sts.

I guess solution is to delete affected sts but that's quite disruptive and would be nice for this to be mentioned in release notes or smth. Or at least use variable there so it can be overridden in values.

**To Reproduce**
1. upgrade loki chart to 5.5.6

**Expected behavior**
upgrade to proceed without failure

**Environment:**
 - Infrastructure: kubernentes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
Helm upgrade error:

```
 Upgrade "loki" failed: cannot patch "loki-write" with kind StatefulSet: StatefulSet.apps "loki-write" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden
```

**Comment by tbondarchuk** [comment]
@oleksii-boiko-ua please check.

**Comment by oleksii-boiko-ua** [comment]
let me add condition and set default as it was before

**Comment by uhthomas** [comment]
dupe of #9519
