### ISSUE TITLE
Loki can use other agent?

### ISSUE THREAD

**Issue by ColdV** [grafana/loki#9526]
Loki can use other agent? we want not use promtail, use our own agent like promtail.

**Comment by rogerogers** [comment]
https://grafana.com/docs/loki/latest/clients/  You can choose any one that you like.

**Comment by ColdV** [comment]
> https://grafana.com/docs/loki/latest/clients/ You can choose any one that you like.

so, except for the clients listed in this document, we can use our client? right?  and can quote some doc to me?

**Comment by rogerogers** [comment]
> > https://grafana.com/docs/loki/latest/clients/ You can choose any one that you like.
> 
> so, except for the clients listed in this document, we can use our client? right? and can quote some access doc to me?

Maybe you can directly use REST API , like this https://grafana.com/docs/loki/latest/api/#push-log-entries-to-loki.

**Comment by ColdV** [comment]
thanks, and other one question.  we want reduce Net IO between client and loki.  so if i send some compress log to loki, loki can handle these compress log?

**Comment by rogerogers** [comment]
According to the documentation, protobuf and gzipped JSON are both supported.

**Comment by ColdV** [comment]
OKK.  please tell me the doc url

**Comment by rogerogers** [comment]
> > > https://grafana.com/docs/loki/latest/clients/ You can choose any one that you like.
> > 
> > 
> > so, except for the clients listed in this document, we can use our client? right? and can quote some access doc to me?
> 
> Maybe you can directly use REST API , like this https://grafana.com/docs/loki/latest/api/#push-log-entries-to-loki.

this

**Comment by ColdV** [comment]
OK.  we look soon.   thank yo every much, was laborious.

**Comment by vlad-diachenko** [comment]
I believe the question is answered and we can close the issue) let us know if you have questions
