### ISSUE TITLE
Promtail - Possibly not reading new configs

### ISSUE THREAD

**Issue by Raltrwx** [grafana/loki#9540]
**Describe the bug**
A handful of servers are not adding a label to their logs when I have added that in promtail's config file post-installation.

**To Reproduce**
I installed promtail to my edge servers, using ansible to orchestrate the installation. I first tested it on a small batch of servers (15 total), then realized I wanted to add a HOSTNAME label.

I edited the config-promtail.yml and added another label, then re-ran my promtail installation on the entire fleet (including the servers I tested the install on first). This is the scrape job in question:

```
scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: internallogs
          host: ${HOSTNAME}
          __path__: /var/lib/monitor/*/*log
```

The logs for the 15 test servers are refusing to label the logs with the hostname, I suspect because I installed promtail already and in some manner my changes to promtail's config are not being used, no hostname label at all:

`May 26 16:39:29 zz-archgpu loki[133959]: level=info ts=2023-05-26T16:39:29.877084754Z caller=flush.go:168 msg="flushing stream" user=fake fp=845f982d1732f73d immediate=false num_chunks=1 labels="{filename=\"/var/lib/monitor/4416/camera_4416_26-5-2023.log\", job=\"internallogs\"}"`

I have:

1. Started promtail, stopped promtail, disabled & reneabled promtail.
2. I have done systemctl daemon-reload .
3. I have tried deleting /etc/promtail/config-promtail.yml, rebooting the server, manually SCP'ing the config back to the remote server.
4. I have tried starting promtail with an empty config file, hoping to clear a "cache" of some sort.
5. promtail -config.file=/etc/promtail/config-promtail.yml -check-syntax (Checks out 100%, says no errors)
6. Read this entire page: https://grafana.com/docs/loki/latest/clients/promtail/troubleshooting/

**Expected behavior**

This is one of my servers sending a log with the correct label,  host=\"be-03\"

`May 26 16:23:30 zz-archgpu loki[133959]: level=info ts=2023-05-26T16:23:30.03603313Z caller=flush.go:168 msg="flushing stream" user=fake fp=546f96695cd01da4 immediate=false num_chunks=1 labels="{filename=\"/var/lib/monitor/2895/camera_2895_1-1-2023.log\", host=\"be-03\", job=\"internallogs\"}"`

I want my 15 test servers to pick up the new config and labels their logs just as these ~350 other servers are doing so. 

**Environment:**
 - Infrastructure: Bare Metal (Everything is on bare metal, Promtail on the edge on Debian 11, Loki on a server behind my desk running Arch linux)
 - Deployment tool: Ansible

**Comment by DylanGuedes** [comment]
Hey I didn't know Promtail had support for vars like `${HOSTNAME}`. Where did you find it?

**Comment by Raltrwx** [comment]
@DylanGuedes 

https://github.com/grafana/loki/issues/634#issuecomment-975601882

**Comment by Raltrwx** [comment]
The logs just started showing up correctly, I imagine promtail had to finish processing "current jobs" or something, and I am just too impatient. 

`May 26 18:09:59 zz-archgpu loki[133959]: level=info ts=2023-05-26T18:09:59.876688399Z caller=flush.go:168 msg="flushing stream" user=fake fp=314d24ede6f26e8f immediate=false num_chunks=1 labels="{filename=\"/var/lib/monitor/4416/camera_4416_26-5-2023.log\", host=\"VG-MJ0JS9LM\", job=\"internallogs\"}"`

**Comment by DylanGuedes** [comment]
that's nice, thank you
