### ISSUE TITLE
loki helm chart: statefulset with multiple nodes behaving erratically

### ISSUE THREAD

**Issue by Morriz** [grafana/loki#957]
**Describe the bug**
given `replicas: 2` for loki helm chart values leads to the service being load balanced to one of the two, but the nodes don't deliver the same state. I would assume a statefulset to either elect a leader (master/slave) or be multi master and sync state (ACID compliant in this case). However, it seems no such concerns are addressed in the statefulset. If there is no cluster-like behaviour built in, why create a statefulset and allow the chart to set the replica count? Maybe I am missing something here. 

Maybe you can document what is achievable by increasing the replica count, and how it works in your particular setup?

**To Reproduce**
1. Started loki (SHA or version) 0.3.0
2. Started promtail (SHA or version) to tail '...' 
3. Query: `{} term`

**Expected behavior**
The service to deliver one source of truth

**Environment:**
 - Infrastructure:Kubernetes
 - Deployment tool: helm

**Screenshots, promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by steven-sheehy** [comment]
The helm chart only runs Loki in [monolith](https://grafana.com/blog/2019/04/15/how-we-designed-loki-to-work-easily-both-as-microservices-and-as-monoliths/) mode and cannot be scaled that way (though I wish it could be for simpler use cases). To scale horizontally, you need to run Loki components individually in microservice mode. The helm chart doesn't support that unfortunately.

**Comment by cyriltovena** [comment]
See https://github.com/grafana/loki/issues/50 , we are planning to support this
