### ISSUE TITLE
where to update loki info in grafana cloud

### ISSUE THREAD

**Issue by daixiang0** [grafana/loki#96]
I login grafana and use cloud to try loki.

I want to update below info:
```
Sending logs from a kubernetes cluster
You can use the following command to configure and install promtail on your kubernetes cluster:

curl -fsS https://raw.githubusercontent.com/grafana/loki/master/tools/promtail.sh | sh -s 1041 <Your Grafana.com API Key> logs-us-west1.grafana.net default | kubectl apply --namespace=default -f  -
```
since it only only works for default namespace.

But i do not know which file i need to update, could someone help me?

**Comment by daixiang0** [comment]
@gouthamve Hi, do you know where to update it?

**Comment by DanCech** [comment]
If you want to run promtail in a different namespace, you can replace the 2 instances of `default` in that command with the namespace you would like to deploy it in.

**Comment by daixiang0** [comment]
Sure, i also add a PR #116.

**Comment by daixiang0** [comment]
It is better to add a comment about this, since new user may get no data if they use custom namespace.

**Comment by daixiang0** [comment]
So where to update this info?

**Comment by daixiang0** [comment]
@DanCech plesse update loki info in
