### ISSUE TITLE
Loki uses S3 as storage retry strategy

### ISSUE THREAD

**Issue by maaiika** [grafana/loki#9651]
Our Loki uses S3 as the back-end storage. Under what circumstances will Loki perform abnormally lot PutObject operations on S3? Currently, it has been observed that Loki performed more than one billion PutObject operations on S3 within 5 days in February, but no Object was actually written to S3. 

the information i got: pkg/ingester/flush.go#L25
```
const (
	// Backoff for retrying 'immediate' flushes. Only counts for queue
	// position, not wallclock time.
	flushBackoff = 1 * time.Second

	nameLabel = "__name__"
	logsValue = "logs"

	flushReasonIdle   = "idle"
	flushReasonMaxAge = "max_age"
	flushReasonForced = "forced"
	flushReasonFull   = "full"
	flushReasonSynced = "synced"
)
```

version git commit id: `
5e53303cb8abec0af0bc1ad1a995310d3d175acc
`

maybe the error log(We lost a lot of logs at the point in time when PutObject was executed): `
level=error ts=2023-02-14T15:59:32.773279455Z caller=flush.go:144 org_id=fake msg="failed to flush" err="failed to flush chunks: store put chunk: InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.\n\tstatus code: 403, request id: HSKTM7ECYHXPVD1C, host id: AAgLsqHMORIcF3tRAej+WXGQ+aTLiZiTW4u+YUzIEhQWMHbmqhmuHg9NrCK0w1FIAOIhLVmyr RI=, num_chunks: 1, labels: {app=\"cattle-cluster- agent\", container=\"cluster-register\", filename=\"/var/log/pods/cattle-system_cattle-cluster-agent-78ff8ddf59-hlgp9_771efa05-91b6-426e-b6a8-47f2530ca41f/cluster-register/382 .log\", job=\"cattle-system/cattle-cluster-agent\", namespace=\"cattle-system\", node_name=\"ip-1.us-east-2 .compute.internal\", pod=\"cattle-cluster-agent-78ff8ddf59-hlgp9\"}"
`

**Comment by sinycn** [comment]
same as you, i use those seting `# storage:
    # bucketNames:
    #   chunks: chunks-oregon-7474
    #   ruler: ruler-oregon-7474
    #   admin: admin-oregon-7474
    # type: s3
    # s3:
    #   region: us-west-2
    #   secretAccessKey: XXXXXX
    #   accessKeyId: XXXXX
    #   s3ForcePathStyle: false
    #   insecure: false`
 loki make 2,394,163,565 requstes  in 2 days， and spend  USD 11970.82   i think may be it is a bug need to be fixed

**Comment by aledegano** [comment]
This weird behavior is still in place and it is potentially catastrophic.

There is no reason for Loki to hammer S3 after it gets a 403.

**Comment by aledegano** [comment]
It's great news that this has been "completed", but where and how if I may ask?

**Comment by maaiika** [comment]
> It's great news that this has been "completed", but where and how if I may ask?

I just want to ask about Loki's retry strategy for 403 status. anyway the abnormal AWS bill has been generated and I almost lost my job.

**Comment by aledegano** [comment]
> > It's great news that this has been "completed", but where and how if I may ask?
> 
> I just want to ask about Loki's retry strategy for 403 status. anyway the abnormal AWS bill has been generated and I almost lost my job.

Sorry to hear that, but then it seems that the issue is very much still there. Could you re-open the issue please?

**Comment by maaiika** [comment]
> > > It's great news that this has been "completed", but where and how if I may ask?
> > 
> > 
> > I just want to ask about Loki's retry strategy for 403 status. anyway the abnormal AWS bill has been generated and I almost lost my job.
> 
> Sorry to hear that, but then it seems that the issue is very much still there. Could you re-open the issue please?

I think this problem is caused by my misunderstanding of Loki's retry strategy. It will not happen if AK/SK are filled in correctly. In addition, this configuration https://github.com/grafana/loki/issues/9651#issuecomment-1678453881 can also alleviate this problem. If your problem is not caused by incorrect AK/SK filling, I suggest you create a new issue.
