### ISSUE TITLE
Loki Docker driver uses an unbounded json log file

### ISSUE THREAD

**Issue by fbuecklers** [grafana/loki#966]
**Describe the bug**
The Loki docker log driver initialize a json logger under the hod, but does not configure max-file nor max-size. Therefore the log file which is created by the json logger increase infinitely.

**To Reproduce**
1. Run a docker container with the Loki log driver

**Expected behavior**
The Loki log driver should use better default values when it initialize the json log driver. It should also expose the max-file and max-size parameters to make them configurable. 

In Addition, should the log file of the json logger not be placed in it's default location?

**Environment:**
 - Infrastructure: A docker server with the installed Loki docker driver

**Screenshots, promtail config, or terminal output**
See also the related discussion on Google Groups
https://groups.google.com/forum/m/#!msg/lokiproject/ase75D9O2Zk/wO0jPsh_BQAJ

**Comment by cyriltovena** [comment]
@fbuecklers are you running a enterprise version ?

**Comment by fbuecklers** [comment]
Nope we have tested it on the community version.
