### ISSUE TITLE
Disable selfMonitoring and LokiCanary not working in Helm chart due to validate (test)

### ISSUE THREAD

**Issue by DanielCastronovo** [grafana/loki#9663]
**Describe the bug**
Disable selfMonitoring and LokiCanary not working in Helm chart due to validate (test)

**To Reproduce**

1 - Disable selfMonitoring and LokiCanary in values.yaml
2 - Deploy Helm chart Loki

**Expected behavior**
SelfMonitoring and LokiCanary disabled.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Helm (chart Loki Version : 5.5.1)

**Screenshots, Promtail config, or terminal output**
Error: execution error at (loki/templates/validate.yaml:6:4): Helm test requires self monitoring to be enabled
```
│ 
│   with module.loki.helm_release.loki,
│   on ../../main.tf line 5, in resource "helm_release" "loki":
│    5: resource "helm_release" "loki" {
```
It's seems to be related to this test :
```
{{- if and (not .Values.monitoring.selfMonitoring.enabled) .Values.test.enabled }}
{{- fail "Helm test requires self monitoring to be enabled"}}
{{- end }}

{{- if and (not .Values.monitoring.lokiCanary.enabled) .Values.test.enabled }}
{{- fail "Helm test requires the Loki Canary to be enabled"}}
{{- end }}
```

**Comment by alexvaque** [comment]
I found the same
