### ISSUE TITLE
add formatting function to pad left + truncate

### ISSUE THREAD

**Issue by zeitlinger** [grafana/loki#9667]
Background:

For the app-o11y plugin, we want to create a log pattern where the message body always starts at the same position.
Before the body, we want to have the severity, instance ID, thread name, logger name.

This is roughly it.

{exporter="OTLP"} | json | resources_service_name="frontend" | resources_service_namespace="ecommerce" | line_format `{{ __timestamp__ | date "2006-01-02T15:04:05.00 GMT" }} - {{.severity}} [{{.resources_service_instance_id}}/{{.attributes_thread_name}}] - {{trunc -40 .instrumentation_scope_name}}: {{.body}}`.

At the moment, truncating is possible - and easy to understand for the user.
We would like to have a solution that additionally pad left.

Let's call it `fixedWithPadLeft` - as in [this one](https://commons.apache.org/proper/commons-text/javadocs/api-release/org/apache/commons/text/TextStringBuilder.html#appendFixedWidthPadLeft(java.lang.Object,int,char)) - but it's only a suggestion.

`{{fixedWithPadLeft length input}}`

| input  | length | result |
|--------|--------|--------|
| foo    | 4      | " foo" |
| foobar | 4      | "obar" |

**Comment by zeitlinger** [comment]
Thinking about it, "align right" is easier to understand (at least for me) than "pad left", because it describes the result instead of the steps.

**Comment by zeitlinger** [comment]
Even better would be to have a new line_fmt `"%5s", "foo"` line formatting function that supports  go fmt like syntax, but with support for truncation, like in [this idea](https://github.com/adaltas/node-printf/issues/23) - I guess this is overkill for a quick fix.

**Comment by cyrille-leclerc** [comment]
Solution:

```
{{ alignLeft 5 "hello world"}}
{{ alignRight 5 "hello world"}}
```

See https://github.com/grafana/loki/pull/9672
