### ISSUE TITLE
Loki Docker driver split stderr from stdout

### ISSUE THREAD

**Issue by valherru** [grafana/loki#968]
With current configuration both docker standard outputs are mixed together so it's not possible to clearly filter error and info messages from each other. Correct me if I'm wrong please but in this way you can easily miss some important error messages from stderr what is not ideal solution.

Would be possible to have some option to follow "docker standards" more and keep these two outputs separated for each container? (e.g. option that would enable labels for it?)

**Comment by cyriltovena** [comment]
Seems reasonable I’ll take a look. The default should definitely parses docker log.

**Comment by zamkeita** [comment]
Bonsoir,
je suis novice dans grafana et loki,je ne comprends pas la solution.
pourriez-vous m'aider s'il vous plait?le probleme est le meme, je voudrais separer  stderr de stdout.
merci d'avance.
