### ISSUE TITLE
split_queries_by_interval on wrong place in config

### ISSUE THREAD

**Issue by bumarcell** [grafana/loki#9688]
According to [Query Frontend docu](https://grafana.com/docs/loki/latest/configuration/query-frontend/#parallelization), the config `split_queries_by_interval` should be in the yaml config under `query_range`.
It appears, however, it es being templated under `limits_config`

Do I have a misunderstanding here?

Regards

**Comment by jimmymjin** [comment]
In 2.5.0 `split_queries_by_interval` can only be defined in the `limits_config` section, Loki will fail to start if you do not remove the `split_queries_by_interval` config from the `query_range` section. 
reference: [https://grafana.com/docs/loki/latest/upgrading/#250](url)

BTW, the new default value of 30m didn't work for me,  I changed it to 24h to fix "too many outstanding requests" issue mentioned here: [https://github.com/grafana/loki/issues/5123](url)

**Comment by chaudum** [comment]
Hi @bumarcell You are right, the paragraph about parallelization is incorrect. The correct place to put the `split_queries_by_interval` is the `limits_config` as @jimmymjin pointed out.

**Comment by chaudum** [comment]
Additionally the CLI flag argument may be confusing as well, since it has the prefix `-querier.` Unfortunately, this cannot be changed easily. The setting is a per-tenant setting.

**Comment by bumarcell** [comment]
Alright, thanks for clarification 🙏
