### ISSUE TITLE
loki-gateway's image in the helm chart defaults to two year old tag `docker.io/nginxinc/nginx-unprivileged:1.19-alpine`

### ISSUE THREAD

**Issue by TheDen** [grafana/loki#9738]
**Describe the bug**

We're getting a lot of vuln alerts for `loki-gateway` since it's using [docker.io/nginxinc/nginx-unprivileged:1.19-alpine](http://docker.io/nginxinc/nginx-unprivileged:1.19-alpine) (now two years old).

I noticed it's the only image that has a default tag pinned, I'm not sure if this was intentional, or if it just needs a version bump,
https://github.com/grafana/loki/blob/c0d9a2b4bad71d42fdbd2eeacab0a6e928a64f9f/production/helm/loki/values.yaml#L1183-L1196

**To Reproduce**
Installing via Helm, `loki-gateway` uses the outdated base image by default, unless the user overrides the tag. Ideally this image should be bumped with the loki version.

**Expected behavior**
The base image to be tagged to a major version  [1-alpine](https://hub.docker.com/layers/nginxinc/nginx-unprivileged/1-alpine/images/sha256-83826e5c15fa3e53b5cf42118703f6f5b72acb7321377c5a0b664021b56b25f5)

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Helm

**Screenshots, Promtail config, or terminal output**
M/A

**Comment by ashseqera** [comment]
Will this be addressed anytime soon? It seems like a security threat, especially considering the recent vulnerability in xz utils

**Comment by earimont-ib** [comment]
@TheDen You may want to close this as Loki has been using an updated version 
 for some time now https://github.com/grafana/loki/blob/v2.9.6/production/helm/loki/values.yaml#L1209

**Comment by TheDen** [comment]
Thanks @earimont-ib — closing this issue
