### ISSUE TITLE
docker plugin enable Loki gives an error

### ISSUE THREAD

**Issue by steveww** [grafana/loki#974]
**Describe the bug**
After installing the plugin.
$ docker plugin enable loki
error: dial unix /run/docker/plugins/9c4f09236095deb097b2a9d864b7152451bb4d300f009f11971773a282a985f9/loki.sock: connect: no such file or directory"
The plugin remains disabled and unusable

**To Reproduce**
$ docker plugin install  grafana/loki-docker-driver:latest --alias loki --grant-all-permissions
$ docker plugin enable loki

**Expected behavior**
Just work

**Environment:**
 Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 06:18:36 2019
 OS/Arch:           linux/arm
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 06:12:41 2019
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Screenshots, promtail config, or terminal output**

**Comment by steveww** [comment]
Looks like an ARM issue, works OK on Intel.

**Comment by sh0rez** [comment]
Hi, 

I am sorry, but we are currently not packaging the docker plugin for other platforms than `linux/amd64`.

This may change in the future, once our CI system allows it.

In the meantime, you can build the plugin yourself for the desired os / arch. To do so, clone the repository on the target system and run `make docker-driver`. This should compile it correctly locally.

**Comment by steveww** [comment]
Cross compiling on linux/amd64 to linux/arm works OK.

**Comment by 87594589-7087-4f7c-b204-e84312ae374c** [comment]
To chime in on demand, I just got this error and ARM64 support would be great.

**Comment by perosb** [comment]
> Cross compiling on linux/amd64 to linux/arm works OK.

any hints on how can this be done @steveww?

building it on arm64 as suggested in https://github.com/grafana/loki/issues/974#issuecomment-528492440 fails for me:
```Status: Downloaded newer image for grafana/loki-build-image:0.9.0
 ---> 055a15113048
Step 3/10 : COPY . /src/loki
 ---> 1e437dca72d9
Step 4/10 : WORKDIR /src/loki
 ---> Running in e5d65944e1fb
Removing intermediate container e5d65944e1fb
 ---> 56d1db0de82a
Step 5/10 : RUN make clean && make BUILD_IN_CONTAINER=false cmd/docker-driver/docker-driver
 ---> Running in 8d43b0fbd6f2
standard_init_linux.go:211: exec user process caused "exec format error"
The command '/bin/sh -c make clean && make BUILD_IN_CONTAINER=false cmd/docker-driver/docker-driver' returned a non-zero code: 1
make: *** [Makefile:372: docker-driver] Error 1```

**Comment by steveww** [comment]
Compiling everything on a RPi is a challenge as the compilation takes a lot of memory that the RPi does not have. I cross compile on a Linux server, it's a lot quicker too.

$ GOARCH=arm go build ./cmd/loki

Then just copy the binary to the RPi.

**Comment by hemna** [comment]
> Compiling everything on a RPi is a challenge as the compilation takes a lot of memory that the RPi does not have. I cross compile on a Linux server, it's a lot quicker too.
> 
> $ GOARCH=arm go build ./cmd/loki
> 
> Then just copy the binary to the RPi.

I had to run
GOARCH=arm go build ./cmd/docker-driver

Then scp the 'docker-driver' executable to my rpi's /var/lib/docker/plugins/<ID>/rootfs/bin dir
where ID is the ID of the docker plugin

```
waboring@airspy:~: $  docker plugin list
ID                  NAME                DESCRIPTION           ENABLED
f2386e8f68e4        loki:latest         Loki Logging Driver   true
```

Then I enabled the docker driver and it was happy

```
waboring@airspy:~: $  docker plugin enable loki
loki
```

**Comment by tam481** [comment]
Hello all,
I've compiled the binary but how do I install it manually? The location "/var/lib/docker/plugins//rootfs/bin dir" does not exist. I can get as far as "/var/lib/docker/plugins".

**Comment by perosb** [comment]
Did you try using https://github.com/grafana/loki/issues/1973#issuecomment-645084374

If not, I think you need to install per the instructions, which will fail, but create the needed folder.

**Comment by matitalatina** [comment]
I try to explain better how I made it works on Raspberry Pi

1. Follow the [instructions to install the driver](https://grafana.com/docs/loki/latest/clients/docker-driver/) so type
  ```bash
  docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions
  ```
2. It will fail with `error: dial unix /run/docker/plugins/...`
3. Clone [loki repo](https://github.com/grafana/loki) on any machine you like, we'll cross-compile for arm
4. Go to the root of the loki project just cloned
5. type
  ```bash
  GOOS=linux GOARCH=arm GOARM=7 go build ./cmd/docker-driver
  ```
  If you have Raspberry 1 change `7` with `6`.

  You should see `docker-driver` file cross-compiled
  
6. Return on the Raspberry Pi and type `sudo ls /var/lib/docker/plugins/` you should see a directory with a very long alphanumeric name like, you should copy our cross-compiled `docker-driver` in ` /var/lib/docker/plugins/<ALPHA_NUMERIC_FOLDER>/rootfs/bin`
7. Type `docker plugin enable loki`
8. Now it should work!

**Comment by oscmedgon** [comment]
The method described by @matitalatina here https://github.com/grafana/loki/issues/974#issuecomment-766390258 doesn't work anymore with a fresh clone of the repository to make it work you need to go to the release v2.1.0 
```shell
LOKI_VERSION=v2.1.0
git checkout "tags/${LOKI_VERSION}" -b setup
cd loki && GOOS=linux GOARCH=arm GOARM=7 go build ./cmd/docker-driver
```
Then you can follow the steps given above to complete your install.

**Comment by PeterBennink** [comment]
@oscmedgon They've simply changed the folder the plugin can be found in. `/clients/cmd/docker-driver` is the current folder, replacing only this folder in @matitalatina's instructions should make the whole thing work again without going back to an older version.

**Comment by SuperBenji99** [comment]
Hi guys, also trying to get the loki driver to work on my rpi4.
Too bad there's no arm complied version of the driver, hoping this gets fixed soon!

In the meantime, trying to follow the steps above. (first time cloning a git repo and compiling)
I cloned the repo succesffully:

`sudo git clone https://github.com/grafana/loki.git
Cloning into 'loki'...
remote: Enumerating objects: 123756, done.
remote: Counting objects: 100% (1147/1147), done.
remote: Compressing objects: 100% (732/732), done.
remote: Total 123756 (delta 555), reused 889 (delta 395), pack-reused 122609
Receiving objects: 100% (123756/123756), 221.99 MiB | 27.31 MiB/s, done.
Resolving deltas: 100% (76965/76965), done.
Updating files: 100% (11664/11664), done.`

Then it looked like (on a separate ubuntu-server box) I need to install  the golang-go apt package. Did so successfully.

Then when I try to run the updated command with the new path: GOOS=linux GOARCH=arm GOARM=7 go build ./clients/cmd/docker-driver I get an error: 

`GOOS=linux GOARCH=arm GOARM=7 go build ./clients/cmd/docker-driver
error obtaining VCS status: exit status 128
	Use -buildvcs=false to disable VCS stamping.`

Anyone know how to fix? (appreciate the help! :) )

**Comment by andormarkus** [comment]
Hi All,

I have tried to comply in on my rpi4 2GB as well and got the following error:

``` shell
pi@raspberrypi:~/loki $ GOOS=linux GOARCH=arm GOARM=7 go build ./clients/cmd/docker-driver/
vendor/github.com/grafana/dskit/kv/memberlist/http_status_handler.go:4:2: cannot find package "." in:
	/home/pi/loki/vendor/embed
vendor/golang.org/x/net/http2/transport.go:19:2: cannot find package "." in:
	/home/pi/loki/vendor/io/fs
```

Trying to use `LOKI_VERSION=v2.1.0`

**Comment by SAS-1** [comment]
> Hi All,
> 
> I have tried to comply in on my rpi4 2GB as well and got the following error:
> 
> ```shell
> pi@raspberrypi:~/loki $ GOOS=linux GOARCH=arm GOARM=7 go build ./clients/cmd/docker-driver/
> vendor/github.com/grafana/dskit/kv/memberlist/http_status_handler.go:4:2: cannot find package "." in:
> 	/home/pi/loki/vendor/embed
> vendor/golang.org/x/net/http2/transport.go:19:2: cannot find package "." in:
> 	/home/pi/loki/vendor/io/fs
> ```
> 
> Trying to use `LOKI_VERSION=v2.1.0`

Same error tried both 2.1 and latest both give the same. Does anyone know any other way to get it working or to download a compiled version?

**Comment by loganphillips792** [comment]
Combining the answers of @matitalatina and @PeterBennink worked for me on a RaspberryPi 3B (armv7 CPU architecture).

**Comment by MrRTi** [comment]
steps from https://github.com/grafana/loki/issues/974#issuecomment-766390258
and 

```
GOOS=linux GOARCH=arm GOARM=7 go build ./clients/cmd/docker-driver
```

works with current main (220cbdd4f) on RaspberryPi 4B. builded on pi

**Comment by WinFinn** [comment]
So I also ended up here, but got it working in the end following peaces from various sites:
Installing docker-driver on a RasPi 4 4GB (with: Raspbian 11 - bullseye, docker 23.0.4)
docker-driver build done on IntelNUC VM (Ubuntu 20.04.6)
Basically following instruction from matitalatina https://github.com/grafana/loki/issues/974#issuecomment-766390258, replacing directory according peterbennink https://github.com/grafana/loki/issues/974#issuecomment-897165660
With following additions:
- installing golang with apt-get will install an old version (1.13.8) that is not compatible for this build: Installed using golangs own instructions: https://go.dev/doc/install
- running build command...  needed "-mod=mod" option added to build
`GOOS=linux GOARCH=arm GOARM=7 go build -mod=mod ./clients/cmd/docker-driver`
- copying docker-driver file to RasPi with SCP (not replacing old file yet)
`sudo scp <user>@<IP of VM>:<remote dir of docker-driver>/docker-driver /<local dir>/docker-driver`
- change rights on the copied file (yes it was lost in copying if not build on same system) 
`sudo chmod --reference=/var/lib/docker/plugins/<ALPHA_NUMERIC_FOLDER>/rootfs/bin/docker-driver /<path to copied file>/docker-driver`
- Then replacing the original driver with new
`sudo mv /<path to copied file>/docker-driver /var/lib/docker/plugins/<ALPHA_NUMERIC_FOLDER>/rootfs/bin/docker-driver`

**Comment by Lefuneste83** [comment]
This solution does indeed works and compiles in a minute on a recent PC.
Latest version of Golang in Ubuntu repos seems fine also (go version go1.18.1 linux/amd64) on a Linux Mint 21.2
It compiled in a breeze and seems to run fine on Rasp4 4GB.

**Comment by adiii717** [comment]
> I try to explain better how I made it work on Raspberry Pi
> 
> 1. Follow the [instructions to install the driver](https://grafana.com/docs/loki/latest/clients/docker-driver/) so type
> 
> ```shell
> docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions
> ```
> 
> 2. It will fail with `error: dial unix /run/docker/plugins/...`
> 3. Clone [loki repo](https://github.com/grafana/loki) on any machine you like, we'll cross-compile for arm
> 4. Go to the root of the loki project just cloned
> 5. type
> 
> ```shell
> GOOS=linux GOARCH=arm GOARM=7 go build ./cmd/docker-driver
> ```
> 
> If you have Raspberry 1 change `7` with `6`.
> 
> You should see `docker-driver` file cross-compiled
> 
> 6. Return on the Raspberry Pi and type `sudo ls /var/lib/docker/plugins/` you should see a directory with a very long alphanumeric name like, you should copy our cross-compiled `docker-driver` in ` /var/lib/docker/plugins/<ALPHA_NUMERIC_FOLDER>/rootfs/bin`
> 7. Type `docker plugin enable loki`
> 8. Now it should work!

this does not work for the latest version `v2.8.4`, I am getting 
```
 GOOS=linux GOARCH=arm GOARM=7 go build ./cmd/docker-driver
stat /path/loki/cmd/docker-driver: directory not found
```

**Comment by Lefuneste83** [comment]
They slightly changed the repo structure

GOOS=linux GOARCH=arm GOARM=7 go build ./clients/cmd/docker-driver

**Comment by croepha** [comment]
I also hit this... using ARM64 on AWS EC2

**Comment by sjhill01** [comment]
Is it time to reconsider providing this for ARM??

**Comment by mario21ic** [comment]
I agree, it's time to compile for ARM

**Comment by solumath** [comment]
When we have docker/podman where it can be compiled, I think it isn't unreasonable to ask for ARM support.

**Comment by manubuk** [comment]
This works for me on RPI4: `docker plugin install docker.io/grafana/loki-docker-driver:arm-v7 --alias loki --grant-all-permissions`

**Comment by mindhaq** [comment]
@manubuk can you check if you got a recent version of the plugin with this command? According to [docker hub](https://hub.docker.com/layers/grafana/loki-docker-driver/arm-v7/images/sha256-4c7c1ba0588affdc44b8810eb2089c789b2e8d4294695f672c28dce848320a2f?context=explore), that tag was last published on Jun 17th 2020.

**Comment by manubuk** [comment]
> @manubuk can you check if you got a recent version of the plugin with this command? According to [docker hub](https://hub.docker.com/layers/grafana/loki-docker-driver/arm-v7/images/sha256-4c7c1ba0588affdc44b8810eb2089c789b2e8d4294695f672c28dce848320a2f?context=explore), that tag was last published on Jun 17th 2020.

I'm using grafana/loki:2.3.0 dated 2021-08-06.
That's the only one that worked for me on RPI.

**Comment by ytugarev** [comment]
Did work for me  on Rockchip RK3588, I used container with GO to compile. Min version is 1.23

`root@e880c6b3152a:/opt/loki# GOOS=linux GOARCH=arm GOARM=8 go build ./clients/cmd/docker-driver
root@e880c6b3152a:/opt/loki# go version
go version go1.23.3 linux/arm64`

**Comment by tucksaun** [comment]
but also thank you to @trevorwhitney for taking care of the polishing effort that was necessary on the releasing part and the pipelines
