### ISSUE TITLE
No required module provides package k8s.io/apimachinery/pkg/util/clock

### ISSUE THREAD

**Issue by dangbb** [grafana/loki#9749]
**Describe the bug**
 When I follow the Loki/Promtail setup, I got stuck when build promtail with command:

```
go build --tags=promtail_journal_enabled ./clients/cmd/promtail
```

Log:
```
../go/pkg/mod/k8s.io/client-go@v0.21.0/rest/request.go:42:2: no required module provides package k8s.io/apimachinery/pkg/util/clock; to add it:
        go get k8s.io/apimachinery/pkg/util/clock
```

**To Reproduce**
1. Clone source code from master branch (commit: `695ea3222`)
2. Follow step at `README.md/Building from source`

**Expected behavior**

The promtail build should be successful.

**Environment:**
 - Infrastructure: Ubuntu-22.04
 - Deployment tool: Run via termimal 

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

![image](https://github.com/grafana/loki/assets/51513363/4913cf06-d87f-4293-8138-c7d17ceafac1)

**Comment by shubmjagtap** [comment]
same problem encountered

**Comment by dangbb** [comment]
I just find out that if I run `go mod tidy` or `go mod vendor`, some conflict will happen. As a result, I cannot build from that. 

So in this case, I just use the `vendor` folder in the source code. Surprisingly, It work.
