### ISSUE TITLE
go get v2 fails

### ISSUE THREAD

**Issue by const-tmp** [grafana/loki#9764]
**Describe the bug**
Cannot `go get` [library](https://github.com/grafana/loki/blob/main/clients/pkg/promtail/client/client.go) mentioned [in documentation](https://grafana.com/docs/loki/latest/api/#push-log-entries-to-loki) 

**To Reproduce**
```
➜  go get github.com/grafana/loki@v2.8.2

go: github.com/grafana/loki@v2.8.2: invalid version: module contains a go.mod file, so module path must match major version ("github.com/grafana/loki/v2")


➜  go get github.com/grafana/loki/v2@v2.8.2

go: github.com/grafana/loki@v2.8.2: invalid version: module contains a go.mod file, so module path must match major version ("github.com/grafana/loki/v2")


➜  go get github.com/grafana/loki/v2       

go: module github.com/grafana/loki@upgrade found (v1.6.1), but does not contain package github.com/grafana/loki/v2
```

**Expected behavior**
Download library mentioned in documentation

**Environment:**
go version go1.20.4 darwin/arm64

**Comment by chaudum** [comment]
Hey @const-tmp  We are aware of the "broken" behaviour and there has been some discussion around that in https://github.com/grafana/loki/issues/2826

We may consider using a `v3` module path for Loki 3.0, as it was raised here: https://github.com/grafana/loki/issues/7076#issuecomment-1239018974

I'm closing the issue as "duplicate".
