### ISSUE TITLE
Change logger from go-kit to ??

### ISSUE THREAD

**Issue by slim-bean** [grafana/loki#977]
There are a few reasons we are unhappy with the go-kit logger

  * Inability to obtain the current log level (See #976)
  * Logger returns an error
  * Issues with log statements missing when you don't put in the correct number of key=value pairs

I think there may have been other reasons, but generally consensus is we'd like a different logger.  

So which one?  [Logrus](https://github.com/sirupsen/logrus) was the first pick, it's used by prometheus now and other Grafana projects, although performance looks slower than go-kit.

There is also [zap](https://github.com/uber-go/zap) which claims to be the fastest, and similar [zerolog](https://github.com/rs/zerolog)

Lastly, do we want to continue logging key=value log messages, move to JSON? or print a formatted string?

Opinions?

**Comment by sh0rez** [comment]
Just taken a look at `zerolog`, seems to be pretty neat. Like the json output and the optional human readable one, seems to be pretty fast and has a nice API

**Comment by pracucci** [comment]
In my experience, JSON structured logging is generally the easier to parse and most widely supported by log aggregators. At the same time, it's the hardest to read from a human (ie. local dev/test environment).

Over the time, I started appreciating software providing two log formats (ie. via cli flag): JSON and textual. For example, the popular "pino" logger for Node.js provides a tool to pipe the JSON output and nicely format/color it for humans, to be used in the local dev/test env.

**Comment by dswarbrick** [comment]
Whilst some Prometheus exporters still use logrus, they actually intend to migrate them to go-kit: https://groups.google.com/d/topic/prometheus-developers/RIG0suqj6nI/discussion

IMHO, if logrus should be off the table due to Prometheus abandoning it, and go-kit is not palatable, maybe it's time to look at zap?
