### ISSUE TITLE
can loki index support hbase?

### ISSUE THREAD

**Issue by wpcnjupt** [grafana/loki#978]
loki index support cassandra/bigtable/dynamodb. however, we do not have anyone of them. 
can loki index support hbase, or else?

**Comment by sh0rez** [comment]
Loki directly takes its storage code from weaveworks/cortex (https://github.com/cortexproject/cortex/tree/master/pkg/chunk). If you need a new storage backend, please file a feature request there!

**Comment by wpcnjupt** [comment]
Thanks a lot.
