### ISSUE TITLE
docker logging driver does not like max-file

### ISSUE THREAD

**Issue by steveww** [grafana/loki#979]
**Describe the bug**
Using docker-compose to start a container. Configuration uses loki logging driver. The container fails to start.

ERROR: for fc8b50abc17f_mail-system_fetchmail_1  Cannot start service fetchmail: failed to initialize logging driver: error creating logger: error creating loki logger: loki: wrong log-opt: 'max-file' - fc8b50abc17f8062485990faf00825b321a11d0f830a97fc4256e08d94804c88

**To Reproduce**
Install loki logging plugin.
docker plugin install grafana/loki-docker-driver:latest --alias --grant-all-permissions

Use loki driver inside docker-compose.yaml
  logging:
      driver: "loki"
      options:
        loki-url: "http://192.168.22.1:3100/api/prom/push"
        loki-batch-size: "400"
        max-size: "250k"
        max-file: "4"

**Expected behavior**
No errors, container starts, logging sent to Loki at specified address.

Environment:
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:22:03 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:20:35 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by steveww** [comment]
If I compile it myself then use docker plugin create docker-driver
It works just fine. Something wrong with the hosted image?

**Comment by cyriltovena** [comment]
We've fixed it last week, I'll check latest to ensure everything is ok.

**Comment by cyriltovena** [comment]
Yes the CI stopped working for docker driver I think, though it should be fine now, @slim-bean @sh0rez can you confirm and close ?

**Comment by cyriltovena** [comment]
I can confirm latest is fine.
