### ISSUE TITLE
False warn for "per-tenant timeout not configured"

### ISSUE THREAD

**Issue by BaskiGIT** [grafana/loki#9801]
**Describe the bug**
With Loki 2.8.2 simple scalable mode ( read and write targets ) per-tenant timeout is configured using runtime configuration. But Loki shows a warn `per-tenant timeout not configured, using default engine timeout (\"5m0s\"). This behavior will change in the next major to always use the default per-tenant timeout (\"5m\").`

**To Reproduce**
1. Create runtime configuration in runtime.yaml  
```
overrides:
      fake:
        query_timeout: 10m
```
2. Set runtime_config in loki config
```
runtime_config:
      file: /etc/loki_runtime/runtime.yaml
```
3. Start Loki of version 2.8.2
4. See the logs of read or write pods
5. The first line of log reports a warn like below
    

> level=warn ts=2023-06-26T14:24:12.394946274Z caller=loki.go:286 msg="per-tenant timeout not configured, using default engine timeout (\"5m0s\"). This behavior will change in the next major to always use the default per-tenant timeout (\"5m\")."

**Expected behavior**
Since `query_timeout` is already defined in runtime configuration this line of log is not expected to appear. Either Loki logging system is false or runtime configuration is not respected.

**Environment:**
 - gke
 - kustomize

**Screenshots, Promtail config, or terminal output**
<img width="1504" alt="image" src="https://github.com/grafana/loki/assets/17687380/f5fbcfb9-fa02-453f-b673-bf75e3947543">

**Comment by aminesnow** [comment]
I've investigated this bug for the last couple of days. I can confirm that this is just an issue with the log wording.
The per-tenant `Overrides` are applied as expected, and the logic behind the warning only pertains to the global Limits Config and not the per-tenant one.
I'll open a PR soon to suggest a better wording for that warning message.
