### ISSUE TITLE
Docs: Loki-Logging-Driver Install is 2.5 years out of date

### ISSUE THREAD

**Issue by QuinnBast** [grafana/loki#9802]
Hello!

I think I have found an issue with the documentation for the loki-logging-driver documentation which is [found here](https://grafana.com/docs/loki/latest/clients/docker-driver/).

The documentation referenced above says "Viewing: v2.8.x (latest)". However, in the installation steps, the documentation indicates the install steps are to run the command:

```
docker plugin install grafana/loki-docker-driver:latest
```

This would normally be an accepted approach, and at the surface nothing looks wrong. However, if you look deeper at this command, it actually references an outdated docker image. The docker image, [loki-docker-driver:latest](https://hub.docker.com/layers/grafana/loki-docker-driver/latest/images/sha256-82270b494d8c157f035fde65bc0159076f4c4361b5bb061b4fc817e8db04234a?context=explore), is referencing a release that was created on Nov 4, 2021 at 2:52 pm; a release made ~2.5 years ago. Normally, "latest" would point to the latest docker image, however, it seems that the maintainers of this plugin have accidentally pushed a tag named "latest" which makes the `latest` tag not actually reference the most recent release. The current latest​ tag seems to be referencing a build that is somewhere between `2.0.0` and `2.2.0` (based on the timestamp) despite the documentation stating "Viewing: v2.8.x (latest)". There are a few [2.8.x releases on docker-hub](https://hub.docker.com/r/grafana/loki-docker-driver/tags?page=1&name=2.8) within the past few months (definitely more recent than the `latest` tag).

This leads me to believe that one of the following things might need to happen:

1. There is a documentation issue, "latest" is no longer relevant, and the docs should instead say something like `loki-docker-driver:2.8.0`, for example.
2. Or, the hard-set `latest` tag should be deleted from docker hub to auto-track the most recent release.
3. Or, your CI/CD automation pipelines need to be updated so that when a new version is released, you also update the `latest` tag to reference the newest release.

Let me know if this is the case!

**Comment by Eve832** [comment]
@JStickler can you make sure the appropriate devs get eyes on this?

**Comment by QuinnBast** [comment]
Looks good! Can probably close this issue, but is this solution future-proof? Or is there a process in place to ensure this document gets updated on future releases?

**Comment by JStickler** [comment]
> is this solution future-proof? 
@QuinnBast That's a very good question, and one that I'm still thinking about how to solve.  I'm also asking around if we can get the "lastest" tag removed from that 2.5 year old image (or delete the image).
