### ISSUE TITLE
the ruler.storage does not support alibabacloud oss actually

### ISSUE THREAD

**Issue by phantomedc** [grafana/loki#9892]
**Describe the bug**
As I follow the loki documentation: https://grafana.com/docs/loki/latest/configuration/#ruler
it says that ruler.storage support alibabacloud_storage_config, 
but it always starts failed:
level=error ts=2023-07-10T07:11:37.900412426Z caller=log.go:171 msg="error running loki" err="unrecognized rule storage mode alibabacloud, choose one of: configdb, gcs, s3, swift, azure, local
then I look into :https://github.com/grafana/loki/blob/5f380872b407fe90f5b1c09be0d5363a64d1712a/pkg/ruler/base/storage.go#L97
the alibabacloud would never be matched. 
and there is a mistake in the documentation:
  # Configures backend rule storage for AlibabaCloud Object Storage (OSS).
  # The CLI flags prefix for this block configuration is: ruler

the prefix should be ruler.storage

**To Reproduce**
1. Started Loki (SHA or version)
2. Started Promtail (SHA or version) to tail '...'
3. Query: `{} term`

**Expected behavior**

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by phantomedc** [comment]
additionally, can I disable the /config  http API? it shows all my cloud storage key and secret

**Comment by Dev-Arhaan** [comment]
Hi I'd like to work on this issue, is anyone else working on it?

**Comment by aminesnow** [comment]
Hi @Dev-Arhaan, I've been working on this and will submit the PR soon.
