### ISSUE TITLE
[Grafana Enterprise logs] disabled data source creation 

### ISSUE THREAD

**Issue by LinTechSo** [grafana/loki#9917]
Hi.
i have deployed Enterprise Loki on my own k8s cluster with SSD helm chart
and also i use Grafana enterprise

After reading grafana  and loki enterprise documentation , i have configured everything.
the Admin APIs are accessible and everything works

But my problem is below screen shot

![Screenshot 1402-04-21 at 14 06 36](https://github.com/grafana/loki/assets/53074289/2e8c33d6-c346-4796-90ed-4af8d21a54a0)

Why grafana enterprise logs in Grafana Apps can not create a data source itself with (token based) ? 
i faced this issue after creating a token
i try add all access policies ....the problem is not came from acess policy grafana loki itself

**Comment by JStickler** [comment]
@LinTechSo It's unclear from your issue, were you unable to create a data source after clicking the **Create a data source** button?

![CreateADataSource](https://github.com/grafana/loki/assets/4106682/33d75ebb-2dc8-4796-9ebf-f1fe37bb6830)

Or did you just want to know why creating a data source doesn't happen automatically?  I think the answer to that is that we don't want to make assumptions about what data source should be associated with a particular tenant and leave that up to the customer to configure.

**Comment by LinTechSo** [comment]
Hi @JStickler . thanks for the reply.
yes, i were unable to create a data source after clicking the Create a data source button and also i found what was the problem.
this issue happens when the Grafana enterprise logs app in Grafana enterprise doesn't have an access to the `/config` API and also this below problem
<img width="990" alt="Screenshot 1402-04-30 at 02 57 02" src="https://github.com/grafana/loki/assets/53074289/9633a965-525a-4c57-9275-1ec651af56c8">

**Comment by LinTechSo** [comment]
After i add this path to the nginx config file 
the issue has been fixed
<img width="675" alt="Screenshot 1402-04-30 at 02 44 51" src="https://github.com/grafana/loki/assets/53074289/24c9932c-e2db-4450-89d5-18c4f8c33278">

**Comment by LinTechSo** [comment]
This issue has fixed 
https://github.com/grafana/loki/pull/10000
