### ISSUE TITLE
Error while running lambda promtail

### ISSUE THREAD

**Issue by edeno1** [grafana/loki#9929]
Hello everyone, I have been running lambda Promtail for several months in my cloud environment, I pull logs from cloud watch and send them to Loki.

The logs are sent successfully but the lambda is throwing unusual amounts of errors
In 1 hour I have more than 3000 errors that look like this:
```
level=error caller=promtail.go:158 err="error sending batch, will retry, status: -1 error: Post \"https://logs-prod-us-central1.grafana.net/loki/api/v1 /push\": context deadline exceeded\n"
level=error caller=promtail.go:158 err="error sending batch, will retry, status: -1 error: Post \"https://logs-prod-us-central1.grafana.net/loki/api/v1 /push\": context deadline exceeded\n"
level=error caller=promtail.go:158 err="error sending batch, will retry, status: -1 error: Post \"https://logs-prod-us-central1.grafana.net/loki/api/v1 /push\": context deadline exceeded\n"
level=error caller=promtail.go:158 err="error sending batch, will retry, status: -1 error: Post \"https://logs-prod-us-central1.grafana.net/loki/api/v1 /push\": context deadline exceeded\n"
```

**Comment by salvacorts** [comment]
This issue looks like a question. You may submit questions in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

Closing it. Feel free to re-open it if you think this is an actual bug. In this case, please choose and use the bug report template when creating a new issue. Thank you!
