### ISSUE TITLE
loki_distributor_bytes_received_total Metric Abnormal

### ISSUE THREAD

**Issue by wkshare** [grafana/loki#9954]
https://github.com/grafana/loki/blob/23e59fa4a95b64d2a77ac6377f287938ed363872/docs/sources/operations/observability.md?plain=1#L29C36-L29C36

loki, version 2.6.1 (branch: HEAD, revision: 6bd05c9a4)
  build user:       root@af90ed01061f
  build date:       2022-07-18T08:41:09Z
  go version:       go1.17.6
  platform:         linux/amd64

I have a three node Loki cluster, but there is always one Metric whose stats look inaccurate, as you can see in the screenshot below. The total amount of logs received keeps increasing, while in reality there is not such a large amount of data.
With three nodes, only one node has this, the other 2 are normal.

my query: rate(loki_distributor_bytes_received_total[3m])

How should I check where the data traffic is coming from? wich ip？

**Comment by wkshare** [comment]
![Uploading 16895776855018637577437734746258.jpg…]()

**Comment by wkshare** [comment]
![Uploading 16895778617791817068417710888141.jpg…]()

**Comment by salvacorts** [comment]
Looks like the images you attached were not uploaded correctly. Also, please follow the bug report template when creating an issue for reporting a bug.

**Comment by wkshare** [comment]
@salvacorts okay, i recreate new bug issue.
