### ISSUE TITLE
Finish sentence.

### ISSUE THREAD

**Issue by smwltr** [grafana/loki#9960]
https://github.com/grafana/loki/blob/443693fb7234886b753deb1e3ae7468d428d8297/clients/pkg/promtail/promtail.go#L257

When trying to decipher this error by reading the code, the comment here is incomplete.

**Comment by JStickler** [comment]
@liguozhong , it looks like this was introduce as part of https://github.com/grafana/loki/commit/fb26baa5b1bd58b33a34e9c946c81b253d7610bc

Do you have any idea what you meant to say in this incomplete comment?

**Comment by liguozhong** [comment]
This comment can be deleted. The original code refers to the code from prometheus, and this comment is from prometheus.
https://github.com/prometheus/prometheus/blob/main/cmd/prometheus/main.go#L957
		```go
                // Reload handler.

		// Make sure that sighup handler is registered with a redirect to the channel before the potentially
		// long and synchronous tsdb init.
		hup := make(chan os.Signal, 1)
```
