### ISSUE TITLE
Browser access is download

### ISSUE THREAD

**Issue by pptfz** [grafana/loki#9977]
I followed these steps to install  I set all replicas to 1 because I have only one worker node and access it as a NodePort
```
helm repo add grafana https://grafana.github.io/helm-charts
helm pull grafana/loki
tar xf loki-5.8.9.tgz
cd loki
helm install loki -n loki --create-namespace .
```

The following is the status of all resources
![iShot_2023-07-19_18 39 31](https://github.com/grafana/loki/assets/44946546/14bbb813-9668-44e1-a635-f9393d07dac6)

problem
Access IP address :30016  Then there is the download, the downloaded file is txt format, the content is just ok
How do you solve this problem

**Comment by chaudum** [comment]
Loki does not provide an HTML page or API endpoint at `/`. Endpoints are documented [here](https://grafana.com/docs/loki/latest/api/).

However, adding a page at root is something we should think about.

**Comment by pptfz** [comment]
Thank you very much. I thought loki was going to have a web interface, but I realized that I misunderstood and the query was supposed to be in grafana
