### ISSUE TITLE
Too many 'upstream request timeout'

### ISSUE THREAD

**Issue by albertdb** [grafana/loki#999]
**Describe the bug**
When searching for intervals with high amount of log lines, Loki returns error in a few seconds (not after 30s which is the Grafana timeout).

This is seen on Grafana as a `upstream request timeout`
and in Loki logs as `level=warn ts=2019-09-10T10:52:45.688072537Z caller=grpc_logging.go:54 method=/logproto.Querier/Query duration=16.742316643s err="rpc error: code = Internal desc = transport: transport: the stream is done or WriteHeader was already called" msg="gRPC\n"`

**To Reproduce**
1. Started loki-stack v0.3.0 taking logs of entire Kubernetes cluster (default settings)
3. Query two days after: `{stream="stdout"} whatever` for last 7 days 

**Expected behavior**

Get 1000 results (or the configured limit) or, when searching for something that doesn't appear in any log line, reach Grafana timeout.

**Environment:**
 - Infrastructure: Kubernetes 1.15.2
 - Deployment tool: helm

**Comment by albertdb** [comment]
Never mind, it was Ambassador default 3000ms timeout (facepalm).

**Comment by LinTechSo** [comment]
Hi. any updates ?
